CC26xx Driver Library: flash.c File Reference
flash.c File Reference
#include "../inc/hw_types.h"
#include "../inc/hw_ccfg.h"
#include "../inc/hw_fcfg2.h"
#include "flash.h"
#include "chipinfo.h"
Macros
#define CCFG_OFFSET_SECURITY CCFG_O_BL_CONFIG
#define CCFG_OFFSET_SECT_PROT CCFG_O_CCFG_WEPROT_31_0_BY2K
#define CCFG_SIZE_SECURITY 0x00000018
#define CCFG_SIZE_SECT_PROT 0x00000004
Typedefs
typedef uint32_t(* FlashPrgPointer_t) (uint8_t *, uint32_t, uint32_t)
typedef uint32_t(* FlashSectorErasePointer_t) (uint32_t)
Functions
static void IssueFsmCommand (tFlashStateCommandsType eCommand)
void FlashPowerModeSet (uint32_t ui32PowerMode, uint32_t ui32BankGracePeriod, uint32_t ui32PumpGracePeriod)
Set power mode.
uint32_t FlashPowerModeGet (void)
Get current configured power mode.
void FlashProtectionSet (uint32_t ui32SectorAddress, uint32_t ui32ProtectMode)
Set sector protection.
uint32_t FlashProtectionGet (uint32_t ui32SectorAddress)
Get sector protection.
uint32_t FlashProtectionSave (uint32_t ui32SectorAddress)
Save sector protection to make it permanent.
uint32_t FlashSectorErase (uint32_t ui32SectorAddress)
Erase a flash sector.
static uint32_t FlashCopyOneFlashWordToHW (uint8_t *pBuf, uint32_t FlashAddr, uint32_t startIdx, uint32_t endIdx)
static uint32_t FlashCopyMultiFlashWordToHW (uint8_t *pBuf, uint32_t FlashAddr, uint32_t numBytes)
uint32_t FlashProgram (uint8_t *pui8DataBuffer, uint32_t ui32Address, uint32_t ui32Count)
Programs unprotected flash sectors in the main bank.
uint32_t FlashProgram4X (uint8_t *pui8DataBuffer, uint32_t ui32Address, uint32_t ui32Count)
uint32_t FlashProgramNowait (uint32_t ui32StartAddress, uint8_t *pui8DataBuffer, uint8_t ui8NoOfBytes)
Starts programming within unprotected main bank flash sector and returns.
bool FlashEfuseReadRow (uint32_t *pui32EfuseData, uint32_t ui32RowAddress)
Reads efuse data from specified row.
void FlashDisableSectorsForWrite (void)
Disables all sectors for erase and programming on the active bank.
Variables
const uint8_t g_pui8CcfgDefaultSec []
Macro Definition Documentation
CCFG_OFFSET_SECT_PROT
#define CCFG_OFFSET_SECT_PROT CCFG_O_CCFG_WEPROT_31_0_BY2K
CCFG_OFFSET_SECURITY
#define CCFG_OFFSET_SECURITY CCFG_O_BL_CONFIG
Referenced by FlashSectorErase().
CCFG_SIZE_SECT_PROT
#define CCFG_SIZE_SECT_PROT 0x00000004
Referenced by FlashProtectionSave().
CCFG_SIZE_SECURITY
#define CCFG_SIZE_SECURITY 0x00000018
Referenced by FlashSectorErase().
Typedef Documentation
FlashPrgPointer_t
typedef uint32_t(* FlashPrgPointer_t) (uint8_t *, uint32_t, uint32_t)
FlashSectorErasePointer_t
typedef uint32_t(* FlashSectorErasePointer_t) (uint32_t)
Function Documentation
FlashCopyMultiFlashWordToHW()
static uint32_t FlashCopyMultiFlashWordToHW (uint8_t * pBuf, uint32_t FlashAddr, uint32_t numBytes) static
Referenced by FlashProgram(), and FlashProgram4X().
 {
     uint32_t wordIdx;
     uint32_t flashdata=0;
     uint32_t cmdDataOffset;
     // double check the Flash address is 32 or 64 byte aligned
     /* based on the Flash addr to figure the cdata index register
        1. convert the system byte address to flash word address (>>4)
        2. based on the flash word address to find command data index (last 2 bit)
        3. cmddataOffset will be 0,32(0x20), 64 (0x40)
     */
     cmdDataOffset = ((FlashAddr >> 4) & 0x3 ) << 4 ;
     // in 2X/4X program mode, Byte Enable register is required
     // to set to 0xFFFF
     HWREG(NVMNW_BASE + NVMNW_O_CMDBYTEN ) = 0xFFFF;
     // build data buffer from byte address to Flash word address
     for (wordIdx = 0; wordIdx < (numBytes >> 2); wordIdx++)
     {
         flashdata = ( pBuf[3] << 24 ) |
                     ( pBuf[2] << 16 ) |
                     ( pBuf[1] << 8  ) |
                     ( pBuf[0] ) ;
         HWREG(NVMNW_BASE + NVMNW_O_CMDDATA0 + cmdDataOffset + (4 * wordIdx)) = flashdata ;
         /* next 4 data byte */
         pBuf += 4;
     }
     return (numBytes);
 }
FlashCopyOneFlashWordToHW()
static uint32_t FlashCopyOneFlashWordToHW (uint8_t * pBuf, uint32_t FlashAddr, uint32_t startIdx, uint32_t endIdx) static
Referenced by FlashProgram(), and FlashProgram4X().
 {
     uint32_t dataBuf[FLASHWORDSIZE_ONE/4];
     uint32_t i,wordIdx,byteIdx;
     uint32_t byteEnableVal =0;
     uint32_t cmdDataOffset;
     // init the dataBuf to zero
     for (i = 0; i < (FLASHWORDSIZE_ONE/4); i++)
     {
         dataBuf[i] = 0x00000000;
     }
     // build data buffer from byte address to Flash word address
     // build the byte enable value
     for (i = startIdx; i <= endIdx; i++)
     {
         byteEnableVal |= 1 << i ;
         wordIdx = i >> FLASHWORD_SHIFTBIT ;
         byteIdx = i & FLASHWORD_MASKBIT ;
         dataBuf[wordIdx] |= (*pBuf) << ( 8 * byteIdx );
         /* next data byte */
         pBuf++;
     }
     /* based on the Flash addr to figure the cdata index register
        1. convert the system byte address to flash word address (>>4)
        2. based on the flash word address to find command data index (last 2 bit)
        3. cmddataOffset will be 0,16(0x10),32(0x20),48(0x30)
     */
     cmdDataOffset = ((FlashAddr >> 4) & 0x3 ) << 4 ;
     /* write the data buffer to Flash Command data buffer */
     HWREG(NVMNW_BASE + NVMNW_O_CMDDATA0 + cmdDataOffset ) = dataBuf[0];
     HWREG(NVMNW_BASE + NVMNW_O_CMDDATA1 + cmdDataOffset ) = dataBuf[1];
     HWREG(NVMNW_BASE + NVMNW_O_CMDDATA2 + cmdDataOffset ) = dataBuf[2];
     HWREG(NVMNW_BASE + NVMNW_O_CMDDATA3 + cmdDataOffset ) = dataBuf[3];
     /* update the byte enable register (mask) */
     HWREG(NVMNW_BASE + NVMNW_O_CMDBYTEN ) = byteEnableVal;
     return (endIdx - startIdx + 1);
 }
IssueFsmCommand()
static void IssueFsmCommand (tFlashStateCommandsType eCommand) static
Issues a command to the Flash State Machine.
Parameters
eCommand specifies the FSM command.
Issues a command to the Flash State Machine.
Returns
None
Referenced by FlashProgram(), FlashProgram4X(), and FlashSectorErase().
 {
     // Check the arguments.
     ASSERT(
         eCommand == FAPI_ERASE_SECTOR    || eCommand == FAPI_ERASE_BANK ||
         eCommand == FAPI_PROGRAM_FOURWORD || eCommand == FAPI_CLEAR_STATUS ||
         eCommand == FAPI_PROGRAM_ONEWORD  || eCommand == FAPI_PROGRAM_TWOWORD );
     // write to NW COMMAND Type register
     HWREG(NVMNW_BASE + NVMNW_O_CMDTYPE) = eCommand;
     // write to NW Execute register
     HWREG(NVMNW_BASE + NVMNW_O_CMDEXEC) = NVMNW_CMDEXEC_VAL_EXECUTE;
 }
Variable Documentation
g_pui8CcfgDefaultSec
const uint8_t g_pui8CcfgDefaultSec[]
Initial value:
= {0xFF, 0xFF, 0xFF, 0xC5,
                                        0xFF, 0xFF, 0xFF, 0xFF,
                                        0xFF, 0xFF, 0xFF, 0xFF,
                                        0xC5, 0xC5, 0xC5, 0xFF,
                                        0xC5, 0xC5, 0xC5, 0xFF,
                                        0xC5, 0xC5, 0xC5, 0xFF
                                       }
Referenced by FlashSectorErase().