CC26xx Driver Library: [i2s.h] Inter-IC Sound
[i2s.h] Inter-IC Sound
Peripherals
Data Structures
struct I2SControlTable
A structure that defines an audio control table. Note: Memory for this structure must be initialized by user application. See detailed description!
Functions
void I2SEnable (uint32_t ui32Base)
Enables the I2S module for operation.
static void I2SDisable (uint32_t ui32Base)
Disables the I2S module for operation.
void I2SAudioFormatConfigure (uint32_t ui32Base, uint32_t ui32FmtCfg, uint32_t ui32BitClkDelay)
Configures the I2S module.
void I2SChannelConfigure (uint32_t ui32Base, uint32_t ui32Chan0Cfg, uint32_t ui32Chan1Cfg)
Setup the audio channel configuration.
static void I2SClockConfigure (uint32_t ui32Base, uint32_t ui32ClkConfig)
Configure the I2S frame clock.
void I2SBufferConfig (uint32_t ui32Base, uint32_t ui32InBufBase, uint32_t ui32OutBufBase, uint16_t ui16DMABufSize, uint16_t ui16ChanBufSize)
Set the input buffer pointers.
void I2SPointerUpdate (uint32_t ui32Base, bool bInput)
Update the buffer pointers.
void I2SPointerSet (uint32_t ui32Base, bool bInput, void *pNextPointer)
Set a buffer pointer (input or output) directly.
static void I2SIntRegister (uint32_t ui32Base, void(*pfnHandler)(void))
Registers an interrupt handler for an I2S interrupt in the dynamic interrupt table.
static void I2SIntUnregister (uint32_t ui32Base)
Unregisters an interrupt handler for a I2S interrupt in the dynamic interrupt table.
void I2SSampleStampConfigure (uint32_t ui32Base, bool bInput, bool bOutput)
Configure the sample stamp generator.
static void I2SIntEnable (uint32_t ui32Base, uint32_t ui32IntFlags)
Enables individual I2S interrupt sources.
static void I2SIntDisable (uint32_t ui32Base, uint32_t ui32IntFlags)
Disables individual I2S interrupt sources.
static uint32_t I2SIntStatus (uint32_t ui32Base, bool bMasked)
Gets the current interrupt status.
static void I2SIntClear (uint32_t ui32Base, uint32_t ui32IntFlags)
Clears I2S interrupt sources.
static void I2SSampleStampEnable (uint32_t ui32Base)
Enable the Sample Stamp generator.
static void I2SSampleStampDisable (uint32_t ui32Base)
Disable the Sample Stamp generator.
uint32_t I2SSampleStampGet (uint32_t ui32Base, uint32_t ui32Channel)
Get the current value of a sample stamp counter.
static void I2SStart (uint32_t ui32Base, uint8_t ui8FixDMALength)
Starts the I2S.
static void I2SStop (uint32_t ui32Base)
Stops the I2S module for operation.
static void I2SFormatConfigure (uint32_t ui32Base, uint8_t ui8iDataDelay, uint8_t ui8iMemory24Bits, uint8_t ui8iSamplingEdge, bool boolDualPhase, uint8_t ui8BitsPerSample, uint16_t ui16transmissionDelay)
Configure the serial format of the I2S module.
static void I2SFrameConfigure (uint32_t ui32Base, uint8_t ui8StatusAD0, uint8_t ui8ChanAD0, uint8_t ui8StatusAD1, uint8_t ui8ChanAD1)
Setup the two interfaces SD0 and SD1 (also called AD0 and AD1).
static void I2SWclkConfigure (uint32_t ui32Base, bool boolMaster, bool boolWCLKInvert)
Configure the I2S frame clock (also called WCLK or WS).
static void I2SInPointerSet (uint32_t ui32Base, uint32_t ui32NextPointer)
Set the input buffer pointer.
static void I2SOutPointerSet (uint32_t ui32Base, uint32_t ui32NextPointer)
Set the output buffer pointer.
static uint32_t I2SInPointerNextGet (uint32_t ui32Base)
Get value stored in PTR NEXT IN register.
static uint32_t I2SOutPointerNextGet (uint32_t ui32Base)
Get value stored in PTR NEXT OUT register.
static uint32_t I2SInPointerGet (uint32_t ui32Base)
Get value stored in PTR IN register.
static uint32_t I2SOutPointerGet (uint32_t ui32Base)
Get value stored in PTR OUT register.
static void I2SSampleStampInConfigure (uint32_t ui32Base, uint16_t ui16TrigValue)
Configure the IN sample stamp generator.
static void I2SSampleStampOutConfigure (uint32_t ui32Base, uint16_t ui16TrigValue)
Configure the OUT sample stamp generator.
static void I2SWclkCounterConfigure (uint32_t ui32Base, int16_t i16Value)
Add the specified value to the WCLK count.
static void I2SWclkCounterReset (uint32_t ui32Base)
Reset the WCLK count.
Variables
I2SControlTable * g_pControlTable
Detailed Description
Introduction
The I2S API provides a set of functions for using the I2S module. This module provides a standardized serial interface to transfer audio samples from and to external audio devices such as a codec, DAC, or ADC.
The I2S module has the following features:
Audio clock signals are internally generated by the PRCM module or externally by another device.
One or two data pins, which can be configured independently as input or output
Various data formats according to the settings of the module
Up to two channels per data pin for dual phase formats and up to eight channels per data pin for single phase formats
DMA with double-buffered pointers
Error detection for DMA and audio clock signal integrity
A Samplestamp generator that allows maintaining of constant audio latency
The I2S module is configured through the functions I2SFormatConfigure(), I2SFrameConfigure() and I2SWclkConfigure(). Transfers are enabled using I2SStart(). Transfers are disabled using I2SStop(). Please note that a specific procedure exists in order to disable transfers without losing data (refer to I2SStop()).
Data are transmitted using the two double-buffered pointers. For each interface, two registers are set with the address of the data to transfer. These registers are named INPTR and INPTRNEXT for the input interface and OUTPTR and OUTPTRNEXT for the output. When PTR is consumed, the hardware copies the content of PTRNEXT into PTR and the next transfer begins. The address of the next value to write or to read in memory (i.e. to receive or to send out) is set using I2SInPointerSet() and I2SOutPointerSet(). The values contented by INPTRNEXT, OUTPTRNEXT, INPTR and OUTPTR can be read using I2SInPointerNextGet(), I2SOutPointerNextGet(), I2SInPointerGet() and I2SOutPointerGet() functions.
Interrupts can help the user to refresh pointers on time. Interrupts can also be used to detect I2S errors. I2SIntEnable() and I2SIntDisable() activate and deactivate interrupt(s). Interrupt status can be read through I2SIntStatus() and a pending interrupt can be acquitted by I2SIntClear() function.
The sample stamps generator can be configured to slightly delay the emission or the reception of the data (based on the number of WCLK cycles) using I2SSampleStampInConfigure(), I2SSampleStampOutConfigure(), I2SWclkCounterReset() and I2SWclkCounterConfigure(). The current sample stamp can be computed using I2SSampleStampGet(). To finish, the sample stamps generator can be enable and disable using the following functions: I2SSampleStampEnable() and I2SSampleStampDisable(). The sample stamps generator must be enabled prior to any transfer.
Note: Other functions contained in the PRCM API are required to handle I2S.
API
Two APIs are coexisting. It is recommended to only use the new API as the old one is deprecated and will be removed soon.
New API: Functions to perform I2S configuration:
I2SStart()
I2SStop()
I2SFormatConfigure()
I2SFrameConfigure()
I2SWclkConfigure()
Functions to perform transfers:
I2SInPointerSet()
I2SOutPointerSet()
I2SInPointerGet()
I2SOutPointerGet()
I2SInPointerNextGet()
I2SOutPointerNextGet()
Functions to handle interruptions:
I2SIntEnable()
I2SIntDisable()
I2SIntStatus()
I2SIntClear()
Functions to handle sample stamps
I2SSampleStampEnable()
I2SSampleStampDisable()
I2SSampleStampInConfigure()
I2SSampleStampOutConfigure()
I2SSampleStampGet()
I2SWclkCounterConfigure()
I2SWclkCounterReset()
Old API: I2SEnable(), I2SDisable(), I2SAudioFormatConfigure(), I2SChannelConfigure(), I2SClockConfigure(), I2SBufferConfig(), I2SIntEnable(), I2SIntDisable(), I2SIntStatus(), I2SIntClear(), I2SSampleStampEnable(), I2SSampleStampDisable(), I2SSampleStampGet(), I2SPointerSet (), I2SPointerUpdate(), I2SSampleStampConfigure(), I2SIntRegister(), I2SIntUnregister()
Function Documentation
I2SAudioFormatConfigure()
void I2SAudioFormatConfigure (uint32_t ui32Base, uint32_t ui32FmtCfg, uint32_t ui32BitClkDelay)
Configures the I2S module.
Deprecated:
This function will be removed in a future release.
The word length defines the size of the word transmitted on the data lines. For single phased formats I2S_WORD_LENGTH_x is the exact number of bits per word. In dual phased format this is the maximum number of bits per word. The size is set using I2S_WORD_LENGTH_8, I2S_WORD_LENGTH_16 or I2S_WORD_LENGTH_24.
Parameters
ui32Base is the I2S module base address.
ui32FmtCfg is the bitwise OR of several options:
Sample size:
I2S_MEM_LENGTH_16
I2S_MEM_LENGTH_24
Clock edge sampling:
I2S_POS_EDGE
I2S_NEG_EDGE
Phase:
I2S_DUAL_PHASE_FMT
I2S_SINGLE_PHASE_FMT
Word length:
I2S_WORD_LENGTH_8
I2S_WORD_LENGTH_16
I2S_WORD_LENGTH_24
ui32BitClkDelay defines the bit clock delay by setting the number of bit clock periods between the positive word clock edge and the MSB of the first word in a phase. The bit clock delay is determined by the ratio between the bit clock and the frame clock and the chosen audio format. The bit clock delay must be configured depending on the chosen audio format:
0 : Left Justified Format (LJF).
1 : I2S and DSP format.
2-255 : Right Justified format (RJF).
Returns
None
See also
I2SChannelConfigure()
Referenced by I2SDisable().
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     ASSERT(ui32BitClkDelay <= 255);
     // Save the length of the audio words stored in memory.
     g_pControlTable->ui16MemLen = (ui32FmtCfg & I2S_MEM_LENGTH_24) ? 24 : 16;
     // Write the configuration.
     HWREG(I2S0_BASE + I2S_O_AIFFMTCFG) = ui32FmtCfg | (ui32BitClkDelay << I2S_AIFFMTCFG_DATA_DELAY_S);
 }
I2SBufferConfig()
void I2SBufferConfig (uint32_t ui32Base, uint32_t ui32InBufBase, uint32_t ui32OutBufBase, uint16_t ui16DMABufSize, uint16_t ui16ChanBufSize)
Set the input buffer pointers.
Deprecated:
This function will be removed in a future release.
The next pointer should always be written while the DMA is using the previous written pointer. If not written in time an I2S_INT_PTR_ERR will occur and all outputs will be disabled.
Note
At startup the next data pointer should be written just before and just after calling the I2SEnable().
Parameters
ui32Base is the base address of the I2S module.
ui32InBufBase is the address of the input buffer.
ui32OutBufBase is the address of the output buffer.
ui16DMABufSize is the size of the DMA buffers. Must be greater than 0!
ui16ChanBufSize is the size of the channel buffers.
Returns
None
Referenced by I2SClockConfigure().
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     ASSERT(ui16DMABufSize > 0);
     // Setup the input data pointer and buffer sizes.
     g_pControlTable->ui16DMABufSize = ui16DMABufSize;
     g_pControlTable->ui16ChBufSize = ui16ChanBufSize;
     g_pControlTable->ui32InBase = ui32InBufBase;
     g_pControlTable->ui32OutBase = ui32OutBufBase;
 }
I2SChannelConfigure()
void I2SChannelConfigure (uint32_t ui32Base, uint32_t ui32Chan0Cfg, uint32_t ui32Chan1Cfg)
Setup the audio channel configuration.
Deprecated:
This function will be removed in a future release.
The channel configuration is a bitwise OR of the input/output mode of each data line and the active audio channels within a specific audio frame.
Setting up the input/output mode use one of:
I2S_LINE_UNUSED
I2S_LINE_INPUT
I2S_LINE_OUTPUT
For dual phased audio (LJF,RJF,I2S) only mono and stereo modes are allowed. For single phased audio format (DSP) up to 8 active channels are allowed on a single data line. For setting up the active channels in a frame use:
Single phased, use a bitwise OR'ed combination of:
I2S_CHAN0_ACT
I2S_CHAN1_ACT
I2S_CHAN2_ACT
I2S_CHAN3_ACT
I2S_CHAN4_ACT
I2S_CHAN5_ACT
I2S_CHAN6_ACT
I2S_CHAN7_ACT
Dual phased, use one of:
I2S_MONO_MODE (same as I2S_CHAN0_ACT)
I2S_STEREO_MODE (same as I2S_CHAN0_ACT | I2S_CHAN1_ACT)
Note
The audio format and the clock configuration should be set using I2SAudioFormatConfigure()
Parameters
ui32Base is base address of the I2S module.
ui32Chan0Cfg defines the channel configuration for data line 0.
ui32Chan1Cfg defines the channel configuration for data line 1.
Returns
None
See also
I2SAudioFormatConfigure()
Referenced by I2SDisable().
 {
     uint32_t ui32InChan;
     uint32_t ui32OutChan;
     uint32_t ui32ChanMask;
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     ASSERT(ui32Chan0Cfg & (I2S_CHAN_CFG_MASK | I2S_LINE_MASK))
     ASSERT(ui32Chan1Cfg & (I2S_CHAN_CFG_MASK | I2S_LINE_MASK))
     ui32InChan = 0;
     ui32OutChan = 0;
     // Configure input/output channels.
     HWREG(I2S0_BASE + I2S_O_AIFDIRCFG) = (
         (( ui32Chan0Cfg << I2S_AIFDIRCFG_AD0_S) & I2S_AIFDIRCFG_AD0_M ) |
         (( ui32Chan1Cfg << I2S_AIFDIRCFG_AD1_S) & I2S_AIFDIRCFG_AD1_M )   );
     // Configure the valid channel mask.
     HWREG(I2S0_BASE + I2S_O_AIFWMASK0) = (ui32Chan0Cfg >> 8) & I2S_AIFWMASK0_MASK_M;
     HWREG(I2S0_BASE + I2S_O_AIFWMASK1) = (ui32Chan1Cfg >> 8) & I2S_AIFWMASK1_MASK_M;
     // Resolve and save the number of input and output channels.
     ui32ChanMask = (ui32Chan0Cfg & I2S_CHAN_CFG_MASK) >> 8;
     if(ui32Chan0Cfg & I2S_LINE_INPUT)
     {
         while(ui32ChanMask)
         {
             if(ui32ChanMask & 0x1)
             {
                 ui32InChan++;
             }
             // Shift down channel mask
             ui32ChanMask >>= 1;
         }
     }
     else if(ui32Chan0Cfg & I2S_LINE_OUTPUT)
     {
         while(ui32ChanMask)
         {
             if(ui32ChanMask & 0x1)
             {
                 ui32OutChan++;
             }
             // Shift down channel mask
             ui32ChanMask >>= 1;
         }
     }
     ui32ChanMask = (ui32Chan1Cfg & I2S_CHAN_CFG_MASK) >> 8;
     if(ui32Chan1Cfg & I2S_LINE_INPUT)
     {
         while(ui32ChanMask)
         {
             if(ui32ChanMask & 0x1)
             {
                 ui32InChan++;
             }
             // Shift down channel mask
             ui32ChanMask >>= 1;
         }
     }
     else if(ui32Chan1Cfg & I2S_LINE_OUTPUT)
     {
         while(ui32ChanMask)
         {
             if(ui32ChanMask & 0x1)
             {
                 ui32OutChan++;
             }
             // Shift down channel mask
             ui32ChanMask >>= 1;
         }
     }
     g_pControlTable->ui8InChan = (uint8_t)ui32InChan;
     g_pControlTable->ui8OutChan = (uint8_t)ui32OutChan;
 }
I2SClockConfigure()
static void I2SClockConfigure (uint32_t ui32Base, uint32_t ui32ClkConfig) inline static
Configure the I2S frame clock.
Deprecated:
This function will be removed in a future release.
Configure I2S clock to be either internal or external and either normal or inverted.
Note
The bit clock configuration is done externally, but the internal/ external setting must match what is chosen internally in the I2S module for the frame clock.
Parameters
ui32Base is the base address of the I2S module.
ui32ClkConfig is the clock configuration parameter. Bitwise OR'ed combination of clock source and clock polarity:
Clock source:
I2S_EXT_WCLK : External clock.
I2S_INT_WCLK : Internal clock.
Clock polarity:
I2S_NORMAL_WCLK : Normal clock.
I2S_INVERT_WCLK : Inverted clock.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Setup register WCLK Source.
     HWREG(I2S0_BASE + I2S_O_AIFWCLKSRC) = ui32ClkConfig &
                                          (I2S_AIFWCLKSRC_WCLK_INV_M |
                                           I2S_AIFWCLKSRC_WCLK_SRC_M);
 }
I2SDisable()
static void I2SDisable (uint32_t ui32Base) inline static
Disables the I2S module for operation.
Deprecated:
This function will be removed in a future release.
This function will immediately disable the I2S module. To ensure that all buffer operations are completed before shutting down, the correct procedure is:
Do not update the data pointers using I2SPointerUpdate().
Await next interrupt resulting in I2S_INT_PTR_ERR.
Disable the I2S using I2SDisable() and clear the pointer error using I2SIntClear().
Disable bit clock source (done externally).
Parameters
ui32Base is the I2S module base address.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Disable the I2S module.
     HWREG(I2S0_BASE + I2S_O_AIFDMACFG) = 0x0;
 }
I2SEnable()
void I2SEnable (uint32_t ui32Base)
Enables the I2S module for operation.
Deprecated:
This function will be removed in a future release.
Note
The module should only be enabled after configuration. When the module is disabled, no data or clocks will be generated on the I2S signals.
Immediately after enabling the module the programmer should update the DMA data pointer registers using I2SPointerUpdate() to ensure a new pointer is written before the DMA transfer completes. Failure to update the pointer in time will result in an I2S_INT_PTR_ERR.
Parameters
ui32Base is the I2S module base address.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Make sure the control table pointer is setup to a memory location.
     if(!(g_pControlTable))
     {
         return;
     }
     // Write the address to the first input/output buffer.
     HWREG(I2S0_BASE + I2S_O_AIFINPTRNEXT) = g_pControlTable->ui32InBase;
     g_pControlTable->ui32InOffset = 0;
     HWREG(I2S0_BASE + I2S_O_AIFOUTPTRNEXT) = g_pControlTable->ui32OutBase;
     g_pControlTable->ui32OutOffset = 0;
     // Enable the I2S module.
     HWREG(I2S0_BASE + I2S_O_AIFDMACFG) = (uint32_t)g_pControlTable->ui16DMABufSize - 1;
 }
I2SFormatConfigure()
static void I2SFormatConfigure (uint32_t ui32Base, uint8_t ui8iDataDelay, uint8_t ui8iMemory24Bits, uint8_t ui8iSamplingEdge, bool boolDualPhase, uint8_t ui8BitsPerSample, uint16_t ui16transmissionDelay) inline static
Configure the serial format of the I2S module.
The word length defines the size of the word transmitted on the data lines. For single phased formats ui8BitsPerSample is the exact number of bits per word. In dual phased format this is the maximum number of bits per word.
Parameters
ui32Base is the I2S module base address.
ui8iDataDelay is the number of BCLK periods between the first WCLK edge and the MSB of the first audio channel data transferred during the phase.
ui8iMemory24Bits selects if the samples in memory are coded on 16 bits or 24 bits. Possible values are:
I2S_MEM_LENGTH_16
I2S_MEM_LENGTH_24
ui8iSamplingEdge selects if sampling on falling or rising edges. Possible values are:
I2S_NEG_EDGE
I2S_POS_EDGE
boolDualPhase must be set to true for dual phase and to false for single phase and user-defined phase.
ui8BitsPerSample is the number of bits transmitted for each sample. If this number does not match with the memory length selected (16 bits or 24 bits), samples will be truncated or padded.
ui16transmissionDelay is the number of WCLK periods before the first transmission.
Returns
None
See also
I2SFrameConfigure()
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     ASSERT(ui8BitsPerSample <= 24); // Max. I2S_AIFFMTCFG_WORD_LEN
     ASSERT(ui8BitsPerSample >= 8);  // Min. I2S_AIFFMTCFG_WORD_LEN
     // Setup register AIFFMTCFG Source.
     HWREGH(I2S0_BASE + I2S_O_AIFFMTCFG) =
                                 (ui8iDataDelay      << I2S_AIFFMTCFG_DATA_DELAY_S) |
                                 (ui8iMemory24Bits   << I2S_AIFFMTCFG_MEM_LEN_24_S) |
                                 (ui8iSamplingEdge   << I2S_AIFFMTCFG_SMPL_EDGE_S ) |
                                 (boolDualPhase      << I2S_AIFFMTCFG_DUAL_PHASE_S) |
                                 (ui8BitsPerSample   << I2S_AIFFMTCFG_WORD_LEN_S  );
     // Number of WCLK periods before the first read / write
     HWREGH(I2S0_BASE + I2S_O_STMPWPER) = ui16transmissionDelay;
 }
I2SFrameConfigure()
static void I2SFrameConfigure (uint32_t ui32Base, uint8_t ui8StatusAD0, uint8_t ui8ChanAD0, uint8_t ui8StatusAD1, uint8_t ui8ChanAD1) inline static
Setup the two interfaces SD0 and SD1 (also called AD0 and AD1).
This function sets interface's direction and activated channels.
Parameters
ui32Base is base address of the I2S module.
ui8StatusAD0 defines the usage of AD0 0x00: AD0 is disabled 0x01, AD0 is an input 0x02, AD0 is an output
ui8ChanAD0 defines the channel mask for AD0. Use a bitwise OR'ed combination of:
I2S_CHAN0_MASK
I2S_CHAN1_MASK
I2S_CHAN2_MASK
I2S_CHAN3_MASK
I2S_CHAN4_MASK
I2S_CHAN5_MASK
I2S_CHAN6_MASK
I2S_CHAN7_MASK
ui8StatusAD1 defines the usage of AD1 0x00: AD1 is disabled 0x10, AD1 is an input 0x20, AD1 is an output
ui8ChanAD1 defines the channel mask for AD1. Use a bitwise OR'ed combination of:
I2S_CHAN0_MASK
I2S_CHAN1_MASK
I2S_CHAN2_MASK
I2S_CHAN3_MASK
I2S_CHAN4_MASK
I2S_CHAN5_MASK
I2S_CHAN6_MASK
I2S_CHAN7_MASK
Returns
None
See also
I2SFormatConfigure()
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Configure input/output channels.
     HWREGB(I2S0_BASE + I2S_O_AIFDIRCFG) = (ui8StatusAD0 | ui8StatusAD1);
     // Configure the valid channel mask.
     HWREGB(I2S0_BASE + I2S_O_AIFWMASK0) = ui8ChanAD0;
     HWREGB(I2S0_BASE + I2S_O_AIFWMASK1) = ui8ChanAD1;
 }
I2SInPointerGet()
static uint32_t I2SInPointerGet (uint32_t ui32Base) inline static
Get value stored in PTR IN register.
Parameters
ui32Base is the base address of the I2S module.
Returns
the value of PTR IN.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     return (HWREG(I2S0_BASE + I2S_O_AIFINPTR));
 }
I2SInPointerNextGet()
static uint32_t I2SInPointerNextGet (uint32_t ui32Base) inline static
Get value stored in PTR NEXT IN register.
Parameters
ui32Base is the base address of the I2S module.
Returns
the value of PTR NEXT IN.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     return (HWREG(I2S0_BASE + I2S_O_AIFINPTRNEXT));
 }
I2SInPointerSet()
static void I2SInPointerSet (uint32_t ui32Base, uint32_t ui32NextPointer) inline static
Set the input buffer pointer.
The next pointer should always be written while the DMA is using the previous written pointer. If not written in time an I2S_INT_PTR_ERR will occur and all inputs and outputs will be disabled. This function relies on pointer is pointing to a valid address.
Note
It is recommended that the pointer update is done in an interrupt context to ensure that the update is performed before the buffer is full.
Parameters
ui32Base is the base address of the I2S module.
ui32NextPointer is the adress of the data
Returns
None
See also
I2SOutPointerSet()
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     HWREG(I2S0_BASE + I2S_O_AIFINPTRNEXT) = ui32NextPointer;
 }
I2SIntClear()
static void I2SIntClear (uint32_t ui32Base, uint32_t ui32IntFlags) inline static
Clears I2S interrupt sources.
The specified I2S interrupt sources are cleared, so that they no longer assert. This function must be called in the interrupt handler to keep the interrupt from being recognized again immediately upon exit.
Note
Due to write buffers and synchronizers in the system it may take several clock cycles from a register write clearing an event in a module and until the event is actually cleared in the NVIC of the system CPU. It is recommended to clear the event source early in the interrupt service routine (ISR) to allow the event clear to propagate to the NVIC before returning from the ISR. At the same time, an early event clear allows new events of the same type to be pended instead of ignored if the event is cleared later in the ISR. It is the responsibility of the programmer to make sure that enough time has passed before returning from the ISR to avoid false re-triggering of the cleared event. A simple, although not necessarily optimal, way of clearing an event before returning from the ISR is:
Write to clear event (interrupt source). (buffered write)
Dummy read from the event source module. (making sure the write has propagated)
Wait two system CPU clock cycles (user code or two NOPs). (allowing cleared event to propagate through any synchronizers)
Parameters
ui32Base is the base address of the I2S port.
ui32IntFlags is a bit mask of the interrupt sources to be cleared. The parameter is the bitwise OR of any of the following:
I2S_INT_DMA_IN
I2S_INT_DMA_OUT
I2S_INT_TIMEOUT
I2S_INT_BUS_ERR
I2S_INT_WCLK_ERR
I2S_INT_PTR_ERR
I2S_INT_ALL (covers all the above)
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Clear the requested interrupt sources.
     HWREG(I2S0_BASE + I2S_O_IRQCLR) = ui32IntFlags;
 }
I2SIntDisable()
static void I2SIntDisable (uint32_t ui32Base, uint32_t ui32IntFlags) inline static
Disables individual I2S interrupt sources.
This function disables the indicated I2S interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
ui32Base is the base address of the I2S port.
ui32IntFlags is the bit mask of the interrupt sources to be disabled. The parameter is the bitwise OR of any of the following:
I2S_INT_DMA_IN
I2S_INT_DMA_OUT
I2S_INT_TIMEOUT
I2S_INT_BUS_ERR
I2S_INT_WCLK_ERR
I2S_INT_PTR_ERR
I2S_INT_ALL (covers all the above)
Returns
None.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Disable the specified interrupts.
     HWREG(I2S0_BASE + I2S_O_IRQMASK) &= ~ui32IntFlags;
 }
I2SIntEnable()
static void I2SIntEnable (uint32_t ui32Base, uint32_t ui32IntFlags) inline static
Enables individual I2S interrupt sources.
This function enables the indicated I2S interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
ui32Base is the base address of the I2S port.
ui32IntFlags is the bit mask of the interrupt sources to be enabled. The parameter is the bitwise OR of any of the following:
I2S_INT_DMA_IN
I2S_INT_DMA_OUT
I2S_INT_TIMEOUT
I2S_INT_BUS_ERR
I2S_INT_WCLK_ERR
I2S_INT_PTR_ERR
I2S_INT_ALL (covers all the above)
Returns
None.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Enable the specified interrupts.
     HWREG(I2S0_BASE + I2S_O_IRQMASK) |= ui32IntFlags;
 }
I2SIntRegister()
static void I2SIntRegister (uint32_t ui32Base, void(*)(void) pfnHandler) inline static
Registers an interrupt handler for an I2S interrupt in the dynamic interrupt table.
Deprecated:
This function will be removed in a future release.
Note
Only use this function if you want to use the dynamic vector table (in SRAM)!
This function registers a function as the interrupt handler for a specific interrupt and enables the corresponding interrupt in the interrupt controller.
Specific I2S interrupts must be enabled via I2SIntEnable(). It is the interrupt handler's responsibility to clear the interrupt source.
Parameters
ui32Base is the base address of the I2S module.
pfnHandler is a pointer to the function to be called when the I2S interrupt occurs.
Returns
None
See also
IntRegister() for important information about registering interrupt handlers.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Register the interrupt handler.
     IntRegister(INT_I2S_IRQ, pfnHandler);
     // Enable the I2S interrupt.
     IntEnable(INT_I2S_IRQ);
 }
I2SIntStatus()
static uint32_t I2SIntStatus (uint32_t ui32Base, bool bMasked) inline static
Gets the current interrupt status.
This function returns the interrupt status for the specified I2S. Either the raw interrupt status or the status of interrupts that are allowed to reflect to the processor can be returned.
Parameters
ui32Base is the base address of the I2S port
bMasked selects between raw and masked interrupt status:
false : Raw interrupt status is required.
true : Masked interrupt status is required.
Returns
Returns the current interrupt status as a vector of:
I2S_INT_DMA_IN
I2S_INT_DMA_OUT
I2S_INT_TIMEOUT
I2S_INT_BUS_ERR
I2S_INT_WCLK_ERR
I2S_INT_PTR_ERR
 {
     uint32_t ui32Mask;
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Return either the interrupt status or the raw interrupt status as
     // requested.
     if(bMasked)
     {
         ui32Mask = HWREG(I2S0_BASE + I2S_O_IRQFLAGS);
         return(ui32Mask & HWREG(I2S0_BASE + I2S_O_IRQMASK));
     }
     else
     {
         return(HWREG(I2S0_BASE + I2S_O_IRQFLAGS));
     }
 }
I2SIntUnregister()
static void I2SIntUnregister (uint32_t ui32Base) inline static
Unregisters an interrupt handler for a I2S interrupt in the dynamic interrupt table.
Deprecated:
This function will be removed in a future release.
This function does the actual unregistering of the interrupt handler. It clears the handler to be called when an I2S interrupt occurs. This function also masks off the interrupt in the interrupt controller so that the interrupt handler no longer is called.
Parameters
ui32Base is the base address of the I2S port.
Returns
None
See also
IntRegister() for important information about registering interrupt handlers.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Disable the interrupt.
     IntDisable(INT_I2S_IRQ);
     // Unregister the interrupt handler.
     IntUnregister(INT_I2S_IRQ);
 }
I2SOutPointerGet()
static uint32_t I2SOutPointerGet (uint32_t ui32Base) inline static
Get value stored in PTR OUT register.
Parameters
ui32Base is the base address of the I2S module.
Returns
the value of PTR OUT.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     return (HWREG(I2S0_BASE + I2S_O_AIFOUTPTR));
 }
I2SOutPointerNextGet()
static uint32_t I2SOutPointerNextGet (uint32_t ui32Base) inline static
Get value stored in PTR NEXT OUT register.
Parameters
ui32Base is the base address of the I2S module.
Returns
the value of PTR NEXT OUT.
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     return (HWREG(I2S0_BASE + I2S_O_AIFOUTPTRNEXT));
 }
I2SOutPointerSet()
static void I2SOutPointerSet (uint32_t ui32Base, uint32_t ui32NextPointer) inline static
Set the output buffer pointer.
The next pointer should always be written while the DMA is using the previous written pointer. If not written in time an I2S_INT_PTR_ERR will occur and all inputs and outputs will be disabled. This function relies on pointer is pointing to a valid address.
Note
It is recommended that the pointer update is done in an interrupt context to ensure that the update is performed before the buffer is full.
Parameters
ui32Base is the base address of the I2S module.
ui32NextPointer is the adress of the data
Returns
None
See also
I2SInPointerSet()
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     HWREG(I2S0_BASE + I2S_O_AIFOUTPTRNEXT) = ui32NextPointer;
 }
I2SPointerSet()
void I2SPointerSet (uint32_t ui32Base, bool bInput, void * pNextPointer)
Set a buffer pointer (input or output) directly.
Deprecated:
This function will be removed in a future release.
This function allows bypassing of the pointers in the global control table.
The next pointer should always be written while the DMA is using the previous written pointer. If not written in time an I2S_INT_PTR_ERR will occur and all outputs will be disabled. Nothing is preventing the pointers from being identical, but this function relies on both pointers (input or output pointers) are pointing to a valid address.
Note
It is recommended that the pointer update is done in an interrupt context to ensure that the update is performed before the buffer is full.
Parameters
ui32Base is the base address of the I2S module.
bInput determines whether to update input or output pointer.
true : Update input pointer.
false : Update output pointer
pNextPointer is a void pointer to user defined buffer.
Returns
None
See also
I2SPointerUpdate()
Referenced by I2SClockConfigure().
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Update the next input/output pointer with the correct address.
     if(bInput == true)
     {
         HWREG(I2S0_BASE + I2S_O_AIFINPTRNEXT) = (uint32_t)pNextPointer;
     }
     else
     {
         HWREG(I2S0_BASE + I2S_O_AIFOUTPTRNEXT) = (uint32_t)pNextPointer;
     }
 }
I2SPointerUpdate()
void I2SPointerUpdate (uint32_t ui32Base, bool bInput)
Update the buffer pointers.
Deprecated:
This function will be removed in a future release.
The next pointer should always be written while the DMA is using the previous written pointer. If not written in time an I2S_INT_PTR_ERR will occur and all outputs will be disabled. Nothing is preventing the pointers from being identical, but this function relies on both pointers (input or output pointers) are pointing to a valid address.
Note
It is recommended that the pointer update is done in an interrupt context to ensure that the update is performed before the buffer is full.
Parameters
ui32Base is the base address of the I2S module.
bInput determines whether to update input or output pointer.
true : Update input pointer.
false : Update output pointer
Returns
None
See also
I2SPointerSet()
Referenced by I2SClockConfigure().
 {
     uint32_t ui32NextPtr;
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Update the next input/output pointer with the correct address.
     if(bInput == true)
     {
         ui32NextPtr = (g_pControlTable->ui8InChan *
                        (g_pControlTable->ui16MemLen >> 3)) *
                       g_pControlTable->ui16DMABufSize;
         g_pControlTable->ui32InOffset = ((g_pControlTable->ui32InOffset +
                                          ui32NextPtr) %
                                          g_pControlTable->ui16ChBufSize);
         HWREG(I2S0_BASE + I2S_O_AIFINPTRNEXT) = g_pControlTable->ui32InOffset +
                                                g_pControlTable->ui32InBase;
     }
     else
     {
         ui32NextPtr = (g_pControlTable->ui8OutChan *
                        (g_pControlTable->ui16MemLen >> 3)) *
                       g_pControlTable->ui16DMABufSize;
         g_pControlTable->ui32OutOffset = ((g_pControlTable->ui32OutOffset +
                                          ui32NextPtr) %
                                          g_pControlTable->ui16ChBufSize);
         HWREG(I2S0_BASE + I2S_O_AIFOUTPTRNEXT) =
                          g_pControlTable->ui32OutOffset +
                          g_pControlTable->ui32OutBase;
     }
 }
I2SSampleStampConfigure()
void I2SSampleStampConfigure (uint32_t ui32Base, bool bInput, bool bOutput)
Configure the sample stamp generator.
Deprecated:
This function will be removed in a future release.
Use this function to configure the sample stamp generator.
Parameters
ui32Base is the base address of the I2S module.
bInput enables triggering of the sample stamp generator on input.
bOutput enables triggering of the sample stamp generator on output.
Returns
None
Referenced by I2SIntUnregister().
 {
     uint32_t ui32Trigger;
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     ui32Trigger = HWREG(I2S0_BASE + I2S_O_STMPWCNT);
     ui32Trigger = (ui32Trigger + 2) % g_pControlTable->ui16ChBufSize;
     // Setup the sample stamp trigger for input streams.
     if(bInput)
     {
         HWREG(I2S0_BASE + I2S_O_STMPINTRIG) = ui32Trigger;
     }
     // Setup the sample stamp trigger for output streams.
     if(bOutput)
     {
         HWREG(I2S0_BASE + I2S_O_STMPOUTTRIG) = ui32Trigger;
     }
 }
I2SSampleStampDisable()
static void I2SSampleStampDisable (uint32_t ui32Base) inline static
Disable the Sample Stamp generator.
Use this function to disable the sample stamp generators. When the sample stamp generator is disabled, the clock counters are automatically cleared.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Clear the enable bit.
     HWREG(I2S0_BASE + I2S_O_STMPCTL) = 0;
 }
I2SSampleStampEnable()
static void I2SSampleStampEnable (uint32_t ui32Base) inline static
Enable the Sample Stamp generator.
Use this function to enable the sample stamp generators.
Note
It is the user's responsibility to ensure that the sample stamp generator is properly configured before it is enabled. It is the setting of the Input and Output triggers configured using I2SSampleStampConfigure() that triggers the start point of the audio streams.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Set the enable bit.
     HWREG(I2S0_BASE + I2S_O_STMPCTL) = I2S_STMPCTL_STMP_EN;
 }
I2SSampleStampGet()
uint32_t I2SSampleStampGet (uint32_t ui32Base, uint32_t ui32Channel)
Get the current value of a sample stamp counter.
Parameters
ui32Base is the base address of the I2S module.
ui32Channel is the sample stamp counter to sample
Returns
Returns the current value of the selected sample stamp channel.
Referenced by I2SSampleStampDisable().
 {
     uint32_t ui32FrameClkCnt;
     uint32_t ui32SysClkCnt;
     uint32_t ui32PeriodSysClkCnt;
     uint32_t ui32SampleStamp;
     // Get the number of Frame clock counts since last stamp.
     ui32FrameClkCnt = HWREG(I2S0_BASE + I2S_O_STMPWCNTCAPT0);
     // Get the number of system clock ticks since last frame clock edge.
     ui32SysClkCnt = HWREG(I2S0_BASE + I2S_O_STMPXCNTCAPT0);
     // Get the number system clock ticks in the last frame clock period.
     ui32PeriodSysClkCnt = HWREG(I2S0_BASE + I2S_O_STMPXPER);
     // Calculate the sample stamp.
     ui32SampleStamp = (ui32SysClkCnt << 16) / ui32PeriodSysClkCnt;
     ui32SampleStamp = (ui32SampleStamp > I2S_STMP_SATURATION) ?
                       I2S_STMP_SATURATION : ui32SampleStamp;
     ui32SampleStamp |= (ui32FrameClkCnt << 16);
     return (ui32SampleStamp);
 }
I2SSampleStampInConfigure()
static void I2SSampleStampInConfigure (uint32_t ui32Base, uint16_t ui16TrigValue) inline static
Configure the IN sample stamp generator.
Use this function to configure the sample stamp generator.
Parameters
ui32Base is the base address of the I2S module.
ui16TrigValue value used to set the trigger.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Setup the sample stamp trigger for input streams.
     HWREGH(I2S0_BASE + I2S_O_STMPINTRIG) = ui16TrigValue;
 }
I2SSampleStampOutConfigure()
static void I2SSampleStampOutConfigure (uint32_t ui32Base, uint16_t ui16TrigValue) inline static
Configure the OUT sample stamp generator.
Use this function to configure the sample stamp generator.
Parameters
ui32Base is the base address of the I2S module.
ui16TrigValue value used to set the trigger.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Setup the sample stamp trigger for output streams.
     HWREGH(I2S0_BASE + I2S_O_STMPOUTTRIG) = ui16TrigValue;
 }
I2SStart()
static void I2SStart (uint32_t ui32Base, uint8_t ui8FixDMALength) inline static
Starts the I2S.
I2S must be configured before it is started.
Note
Immediately after enabling the module the programmer must update the DMA data pointer registers using I2SInPointerSet() and I2SOutPointerSet() to ensure a new pointer is written before the DMA transfer completes. Failure to update the pointer in time will result in an I2S_INT_PTR_ERR.
Parameters
ui32Base is the I2S module base address.
ui8FixDMALength is the length of the DMA buffer: this will allow the DMA to read ui8FixDMALength between to pointer refreshes.
Returns
None
See also
I2SStop()
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Enable the I2S module.
     HWREG(I2S0_BASE + I2S_O_AIFDMACFG) = ui8FixDMALength;
 }
I2SStop()
static void I2SStop (uint32_t ui32Base) inline static
Stops the I2S module for operation.
This function will immediately disable the I2S module. To ensure that all buffer operations are completed before shutting down, the correct procedure is:
Do not update the data pointers using I2SInPointerSet() and I2SOutPointerSet().
Await that values returned by I2SInPointerNextGet(), I2SOutPointerNextGet(), I2SInPointerGet() and I2SOutPointerGet() are zero.
Disable the I2S using I2SStop() and clear the pointer error using I2SIntClear().
Disable bit clock source (done externally).
Parameters
ui32Base is the I2S module base address.
Returns
None
See also
I2SStart()
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     // Disable the I2S module.
     HWREG(I2S0_BASE + I2S_O_AIFDMACFG) = 0x00;
 }
I2SWclkConfigure()
static void I2SWclkConfigure (uint32_t ui32Base, bool boolMaster, bool boolWCLKInvert) inline static
Configure the I2S frame clock (also called WCLK or WS).
Configure WCLK clock to be either internal (master) or external (slave). Configure WCLK clock either normal or inverted.
Note
The bit clock configuration is done externally, but the internal/ external setting must match what is chosen internally in the I2S module for the frame clock.
Parameters
ui32Base is the base address of the I2S module.
boolMaster false: the device is a slave (external clock) true: the device is a master (internal clock)
boolWCLKInvert false: WCLK is not inverted true: WCLK is internally inverted
Returns
None
 {
     // if(boolMaster == 0) then ui8ClkSource = 1
     // if(boolMaster == 1) then ui8ClkSource = 2
     uint8_t ui8ClkSource = (uint8_t)boolMaster + 0x01;
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     ASSERT(ui8ClkSource < I2S_AIFWCLKSRC_WCLK_SRC_RESERVED);
     // Setup register WCLK Source.
     HWREGB(I2S0_BASE + I2S_O_AIFWCLKSRC) =
                                ((ui8ClkSource       << I2S_AIFWCLKSRC_WCLK_SRC_S) |
                                 (boolWCLKInvert     << I2S_AIFWCLKSRC_WCLK_INV_S ));
 }
I2SWclkCounterConfigure()
static void I2SWclkCounterConfigure (uint32_t ui32Base, int16_t i16Value) inline static
Add the specified value to the WCLK count.
Parameters
ui32Base is the base address of the I2S module.
i16Value is the offset to add to the counter (this value can be negative)
Returns
None
 {
     uint16_t ui16MinusValue;
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     if (i16Value >= 0)
     {
         HWREGH(I2S0_BASE + I2S_O_STMPWADD) = i16Value;
     }
     else
     {
         ui16MinusValue = (uint16_t)(-i16Value);
         HWREGH(I2S0_BASE + I2S_O_STMPWADD) = HWREGH(I2S0_BASE + I2S_O_STMPWPER) - ui16MinusValue;
     }
 }
I2SWclkCounterReset()
static void I2SWclkCounterReset (uint32_t ui32Base) inline static
Reset the WCLK count.
Parameters
ui32Base is the base address of the I2S module.
Returns
None
 {
     // Check the arguments.
     ASSERT(I2SBaseValid(ui32Base));
     HWREGH(I2S0_BASE + I2S_O_STMPWSET) = 0;
 }
Macro Definition Documentation
I2S_CHAN0_ACT
#define I2S_CHAN0_ACT 0x00000100
I2S_CHAN0_MASK
#define I2S_CHAN0_MASK 0x00000001
I2S_CHAN1_ACT
#define I2S_CHAN1_ACT 0x00000200
I2S_CHAN1_MASK
#define I2S_CHAN1_MASK 0x00000002
I2S_CHAN2_ACT
#define I2S_CHAN2_ACT 0x00000400
I2S_CHAN2_MASK
#define I2S_CHAN2_MASK 0x00000004
I2S_CHAN3_ACT
#define I2S_CHAN3_ACT 0x00000800
I2S_CHAN3_MASK
#define I2S_CHAN3_MASK 0x00000008
I2S_CHAN4_ACT
#define I2S_CHAN4_ACT 0x00001000
I2S_CHAN4_MASK
#define I2S_CHAN4_MASK 0x00000010
I2S_CHAN5_ACT
#define I2S_CHAN5_ACT 0x00002000
I2S_CHAN5_MASK
#define I2S_CHAN5_MASK 0x00000020
I2S_CHAN6_ACT
#define I2S_CHAN6_ACT 0x00004000
I2S_CHAN6_MASK
#define I2S_CHAN6_MASK 0x00000040
I2S_CHAN7_ACT
#define I2S_CHAN7_ACT 0x00008000
I2S_CHAN7_MASK
#define I2S_CHAN7_MASK 0x00000080
I2S_CHAN_CFG_MASK
#define I2S_CHAN_CFG_MASK 0x0000FF00
Referenced by I2SChannelConfigure().
I2S_DMA_BUF_SIZE_128
#define I2S_DMA_BUF_SIZE_128 0x00000080
I2S_DMA_BUF_SIZE_256
#define I2S_DMA_BUF_SIZE_256 0x00000100
I2S_DMA_BUF_SIZE_64
#define I2S_DMA_BUF_SIZE_64 0x00000040
I2S_DUAL_PHASE_FMT
#define I2S_DUAL_PHASE_FMT 0x00000020
I2S_EXT_WCLK
#define I2S_EXT_WCLK 0x00000001
I2S_INT_ALL
#define I2S_INT_ALL 0x0000003F
I2S_INT_BUS_ERR
#define I2S_INT_BUS_ERR 0x00000004
I2S_INT_DMA_IN
#define I2S_INT_DMA_IN 0x00000020
I2S_INT_DMA_OUT
#define I2S_INT_DMA_OUT 0x00000010
I2S_INT_PTR_ERR
#define I2S_INT_PTR_ERR 0x00000001
I2S_INT_TIMEOUT
#define I2S_INT_TIMEOUT 0x00000008
I2S_INT_WCLK
#define I2S_INT_WCLK 0x00000002
I2S_INT_WCLK_ERR
#define I2S_INT_WCLK_ERR 0x00000002
I2S_INVERT_WCLK
#define I2S_INVERT_WCLK 0x00000004
I2S_LINE_INPUT
#define I2S_LINE_INPUT 0x00000001
Referenced by I2SChannelConfigure().
I2S_LINE_MASK
#define I2S_LINE_MASK 0x00000003
Referenced by I2SChannelConfigure().
I2S_LINE_OUTPUT
#define I2S_LINE_OUTPUT 0x00000002
Referenced by I2SChannelConfigure().
I2S_LINE_UNUSED
#define I2S_LINE_UNUSED 0x00000000
I2S_MEM_LENGTH_16
#define I2S_MEM_LENGTH_16 0x00000000
I2S_MEM_LENGTH_24
#define I2S_MEM_LENGTH_24 0x00000080
Referenced by I2SAudioFormatConfigure().
I2S_MONO_MODE
#define I2S_MONO_MODE 0x00000100
I2S_NEG_EDGE
#define I2S_NEG_EDGE 0x00000000
I2S_NORMAL_WCLK
#define I2S_NORMAL_WCLK 0x00000000
I2S_POS_EDGE
#define I2S_POS_EDGE 0x00000040
I2S_SINGLE_PHASE_FMT
#define I2S_SINGLE_PHASE_FMT 0x00000000
I2S_STEREO_MODE
#define I2S_STEREO_MODE 0x00000300
I2S_STMP0
#define I2S_STMP0 0x00000001
I2S_STMP1
#define I2S_STMP1 0x00000002
I2S_STMP_SATURATION
#define I2S_STMP_SATURATION 0x0000FFFF
Referenced by I2SSampleStampGet().
I2S_WORD_LENGTH_16
#define I2S_WORD_LENGTH_16 0x00000010
I2S_WORD_LENGTH_24
#define I2S_WORD_LENGTH_24 0x00000018
I2S_WORD_LENGTH_8
#define I2S_WORD_LENGTH_8 0x00000008
Variable Documentation
g_pControlTable
I2SControlTable* g_pControlTable