rflib: Rfc_api
Rfc_api
Data Structures
struct rfTrim_t
Macros
#define RFC_MAX_SEARCH_DEPTH 5
#define RFC_IEEE_CMD_BG_ADDRESS 0x21000160
#define RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME 24
#define RFC_PA_TYPE_ADDRESS 0x21000385
#define RFC_PA_TYPE_MASK 0x04
#define RFC_PA_GAIN_ADDRESS 0x21000398
#define RFC_PA_GAIN_MASK 0x003FFFFF
#define RFC_FE_MODE_ESCAPE_VALUE 0xFF
#define RFC_FE_OVERRIDE_ADDRESS 0x0703
#define RFC_FE_OVERRIDE_MASK 0x0000FFFF
#define RFCCpeIntGetAndClear NOROM_RFCCpeIntGetAndClear
#define RFCDoorbellSendTo NOROM_RFCDoorbellSendTo
#define RFCSynthPowerDown NOROM_RFCSynthPowerDown
#define RFCCpePatchReset NOROM_RFCCpePatchReset
#define RFCOverrideSearch NOROM_RFCOverrideSearch
#define RFCOverrideUpdate NOROM_RFCOverrideUpdate
#define RFCHwIntGetAndClear NOROM_RFCHwIntGetAndClear
#define RFCAnaDivTxOverride NOROM_RFCAnaDivTxOverride
#define RFC_MAX_SEARCH_DEPTH 5
#define RFC_IEEE_CMD_BG_ADDRESS 0x21000160
#define RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME 24
#define RFC_PA_TYPE_ADDRESS 0x21000385
#define RFC_PA_TYPE_MASK 0x04
#define RFC_PA_GAIN_ADDRESS 0x21000398
#define RFC_PA_GAIN_MASK 0x003FFFFF
#define RFC_FE_MODE_ESCAPE_VALUE 0xFF
#define RFC_FE_OVERRIDE_ADDRESS 0x0703
#define RFC_FE_OVERRIDE_MASK 0x0000FFFF
#define RFCCpeIntGetAndClear NOROM_RFCCpeIntGetAndClear
#define RFCDoorbellSendTo NOROM_RFCDoorbellSendTo
#define RFCSynthPowerDown NOROM_RFCSynthPowerDown
#define RFCCpePatchReset NOROM_RFCCpePatchReset
#define RFCOverrideSearch NOROM_RFCOverrideSearch
#define RFCOverrideUpdate NOROM_RFCOverrideUpdate
#define RFCHwIntGetAndClear NOROM_RFCHwIntGetAndClear
#define RFCAnaDivTxOverride NOROM_RFCAnaDivTxOverride
#define RFCRfTrimRead NOROM_RFCRfTrimRead
#define RFCRfTrimSet NOROM_RFCRfTrimSet
#define RFC_MAX_SEARCH_DEPTH 5
#define RFC_IEEE_CMD_BG_ADDRESS 0x21000160
#define RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME 24
#define RFC_PA_TYPE_ADDRESS 0x21000385
#define RFC_PA_TYPE_MASK 0x04
#define RFC_PA_GAIN_ADDRESS 0x21000398
#define RFC_PA_GAIN_MASK 0x003FFFFF
#define RFC_FE_MODE_ESCAPE_VALUE 0xFF
#define RFC_FE_OVERRIDE_ADDRESS 0x0703
#define RFC_FE_OVERRIDE_MASK 0x0000FFFF
#define RFCCpeIntGetAndClear NOROM_RFCCpeIntGetAndClear
#define RFCDoorbellSendTo NOROM_RFCDoorbellSendTo
#define RFCSynthPowerDown NOROM_RFCSynthPowerDown
#define RFCCpePatchReset NOROM_RFCCpePatchReset
#define RFCOverrideSearch NOROM_RFCOverrideSearch
#define RFCOverrideUpdate NOROM_RFCOverrideUpdate
#define RFCHwIntGetAndClear NOROM_RFCHwIntGetAndClear
#define RFCAnaDivTxOverride NOROM_RFCAnaDivTxOverride
Functions
__STATIC_INLINE void RFCClockEnable (void)
Enable the RF core clocks.
__STATIC_INLINE void RFCClockDisable (void)
Disable the RF core clocks.
__STATIC_INLINE void RFCCpeIntClear (uint32_t ui32Mask)
Clear HW interrupt flags.
__STATIC_INLINE void RFCHwIntClear (uint32_t ui32Mask)
Clear CPE interrupt flags.
__STATIC_INLINE void RFCCpe0IntSelect (uint32_t ui32Mask)
Select interrupt sources to CPE0 (assign to INT_RFC_CPE_0 interrupt vector).
__STATIC_INLINE void RFCCpe1IntSelect (uint32_t ui32Mask)
Select interrupt sources to CPE1 (assign to INT_RFC_CPE_1 interrupt vector).
__STATIC_INLINE void RFCCpeIntEnable (uint32_t ui32Mask)
Enable CPEx interrupt sources.
__STATIC_INLINE void RFCCpe0IntSelectClearEnable (uint32_t ui32Mask)
Select, clear, and enable interrupt sources to CPE0.
__STATIC_INLINE void RFCCpe1IntSelectClearEnable (uint32_t ui32Mask)
Select, clear, and enable interrupt sources to CPE1.
__STATIC_INLINE void RFCHwIntEnable (uint32_t ui32Mask)
Enable HW interrupt sources.
__STATIC_INLINE void RFCCpeIntDisable (uint32_t ui32Mask)
Disable CPE interrupt sources.
__STATIC_INLINE void RFCHwIntDisable (uint32_t ui32Mask)
Disable HW interrupt sources.
uint32_t NOROM_RFCCpeIntGetAndClear (uint32_t ui32Mask)
Get and clear CPE interrupt flags.
__STATIC_INLINE void RFCAckIntClear (void)
Clear ACK interrupt flag.
uint32_t NOROM_RFCDoorbellSendTo (uint32_t pOp)
Send a radio operation to the doorbell and wait for an acknowledgment.
void NOROM_RFCSynthPowerDown (void)
This function implements a fast way to turn off the synthesizer.
void NOROM_RFCCpePatchReset (void)
Reset previously patched CPE RAM to a state where it can be patched again.
uint8_t NOROM_RFCOverrideSearch (const uint32_t *pOverride, const uint32_t pattern, const uint32_t mask, const uint8_t searchDepth)
uint8_t NOROM_RFCOverrideUpdate (rfc_radioOp_t *pOpSetup, uint32_t *pParams)
Function to update override list.
uint32_t NOROM_RFCHwIntGetAndClear (uint32_t ui32Mask)
Get and clear HW interrupt flags.
__STATIC_INLINE bool RFCGetPaType (void)
Get the type of currently selected PA.
__STATIC_INLINE uint32_t RFCGetPaGain (void)
Get the gain of currently selected PA.
__STATIC_INLINE uint32_t RFCGetPowerDomainStatus (void)
Get the power domain status of the radio core.
__STATIC_INLINE uint32_t RFCGetIeeeRxCaptureTime (void)
uint32_t NOROM_RFCAnaDivTxOverride (uint8_t loDivider, uint8_t frontEndMode)
Function to calculate the proper override run-time for the High Gain PA.
void NOROM_RFCRfTrimRead (rfc_radioOp_t *pOpSetup, rfTrim_t *rfTrim)
Read RF trim from flash using CM4.
void NOROM_RFCRfTrimSet (rfTrim_t *rfTrim)
Write preloaded RF trim values directly into CPE.
Detailed Description
Macro Definition Documentation
RFC_MAX_SEARCH_DEPTH [1/3]
#define RFC_MAX_SEARCH_DEPTH 5
RFC_IEEE_CMD_BG_ADDRESS [1/3]
#define RFC_IEEE_CMD_BG_ADDRESS 0x21000160
Referenced by RFCGetIeeeRxCaptureTime().
RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME [1/3]
#define RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME 24
Referenced by RFCGetIeeeRxCaptureTime().
RFC_PA_TYPE_ADDRESS [1/3]
#define RFC_PA_TYPE_ADDRESS 0x21000385
Referenced by RFCGetPaType().
RFC_PA_TYPE_MASK [1/3]
#define RFC_PA_TYPE_MASK 0x04
Referenced by RFCGetPaType().
RFC_PA_GAIN_ADDRESS [1/3]
#define RFC_PA_GAIN_ADDRESS 0x21000398
Referenced by RFCGetPaGain().
RFC_PA_GAIN_MASK [1/3]
#define RFC_PA_GAIN_MASK 0x003FFFFF
Referenced by RFCGetPaGain().
RFC_FE_MODE_ESCAPE_VALUE [1/3]
#define RFC_FE_MODE_ESCAPE_VALUE 0xFF
RFC_FE_OVERRIDE_ADDRESS [1/3]
#define RFC_FE_OVERRIDE_ADDRESS 0x0703
RFC_FE_OVERRIDE_MASK [1/3]
#define RFC_FE_OVERRIDE_MASK 0x0000FFFF
RFCCpeIntGetAndClear [1/3]
#define RFCCpeIntGetAndClear NOROM_RFCCpeIntGetAndClear
Referenced by RFCHwIntDisable().
RFCDoorbellSendTo [1/3]
#define RFCDoorbellSendTo NOROM_RFCDoorbellSendTo
Referenced by RFCAckIntClear().
RFCSynthPowerDown [1/3]
#define RFCSynthPowerDown NOROM_RFCSynthPowerDown
Referenced by RFCAckIntClear().
RFCCpePatchReset [1/3]
#define RFCCpePatchReset NOROM_RFCCpePatchReset
Referenced by RFCAckIntClear().
RFCOverrideSearch [1/3]
#define RFCOverrideSearch NOROM_RFCOverrideSearch
Referenced by RFCAckIntClear().
RFCOverrideUpdate [1/3]
#define RFCOverrideUpdate NOROM_RFCOverrideUpdate
Referenced by RFCAckIntClear().
RFCHwIntGetAndClear [1/3]
#define RFCHwIntGetAndClear NOROM_RFCHwIntGetAndClear
Referenced by RFCAckIntClear().
RFCAnaDivTxOverride [1/3]
#define RFCAnaDivTxOverride NOROM_RFCAnaDivTxOverride
Referenced by RFCGetIeeeRxCaptureTime().
RFC_MAX_SEARCH_DEPTH [2/3]
#define RFC_MAX_SEARCH_DEPTH 5
RFC_IEEE_CMD_BG_ADDRESS [2/3]
#define RFC_IEEE_CMD_BG_ADDRESS 0x21000160
RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME [2/3]
#define RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME 24
RFC_PA_TYPE_ADDRESS [2/3]
#define RFC_PA_TYPE_ADDRESS 0x21000385
RFC_PA_TYPE_MASK [2/3]
#define RFC_PA_TYPE_MASK 0x04
RFC_PA_GAIN_ADDRESS [2/3]
#define RFC_PA_GAIN_ADDRESS 0x21000398
RFC_PA_GAIN_MASK [2/3]
#define RFC_PA_GAIN_MASK 0x003FFFFF
RFC_FE_MODE_ESCAPE_VALUE [2/3]
#define RFC_FE_MODE_ESCAPE_VALUE 0xFF
RFC_FE_OVERRIDE_ADDRESS [2/3]
#define RFC_FE_OVERRIDE_ADDRESS 0x0703
RFC_FE_OVERRIDE_MASK [2/3]
#define RFC_FE_OVERRIDE_MASK 0x0000FFFF
RFCCpeIntGetAndClear [2/3]
#define RFCCpeIntGetAndClear NOROM_RFCCpeIntGetAndClear
RFCDoorbellSendTo [2/3]
#define RFCDoorbellSendTo NOROM_RFCDoorbellSendTo
RFCSynthPowerDown [2/3]
#define RFCSynthPowerDown NOROM_RFCSynthPowerDown
RFCCpePatchReset [2/3]
#define RFCCpePatchReset NOROM_RFCCpePatchReset
RFCOverrideSearch [2/3]
#define RFCOverrideSearch NOROM_RFCOverrideSearch
RFCOverrideUpdate [2/3]
#define RFCOverrideUpdate NOROM_RFCOverrideUpdate
RFCHwIntGetAndClear [2/3]
#define RFCHwIntGetAndClear NOROM_RFCHwIntGetAndClear
RFCAnaDivTxOverride [2/3]
#define RFCAnaDivTxOverride NOROM_RFCAnaDivTxOverride
RFCRfTrimRead
#define RFCRfTrimRead NOROM_RFCRfTrimRead
RFCRfTrimSet
#define RFCRfTrimSet NOROM_RFCRfTrimSet
RFC_MAX_SEARCH_DEPTH [3/3]
#define RFC_MAX_SEARCH_DEPTH 5
RFC_IEEE_CMD_BG_ADDRESS [3/3]
#define RFC_IEEE_CMD_BG_ADDRESS 0x21000160
RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME [3/3]
#define RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME 24
RFC_PA_TYPE_ADDRESS [3/3]
#define RFC_PA_TYPE_ADDRESS 0x21000385
RFC_PA_TYPE_MASK [3/3]
#define RFC_PA_TYPE_MASK 0x04
RFC_PA_GAIN_ADDRESS [3/3]
#define RFC_PA_GAIN_ADDRESS 0x21000398
RFC_PA_GAIN_MASK [3/3]
#define RFC_PA_GAIN_MASK 0x003FFFFF
RFC_FE_MODE_ESCAPE_VALUE [3/3]
#define RFC_FE_MODE_ESCAPE_VALUE 0xFF
RFC_FE_OVERRIDE_ADDRESS [3/3]
#define RFC_FE_OVERRIDE_ADDRESS 0x0703
RFC_FE_OVERRIDE_MASK [3/3]
#define RFC_FE_OVERRIDE_MASK 0x0000FFFF
RFCCpeIntGetAndClear [3/3]
#define RFCCpeIntGetAndClear NOROM_RFCCpeIntGetAndClear
RFCDoorbellSendTo [3/3]
#define RFCDoorbellSendTo NOROM_RFCDoorbellSendTo
RFCSynthPowerDown [3/3]
#define RFCSynthPowerDown NOROM_RFCSynthPowerDown
RFCCpePatchReset [3/3]
#define RFCCpePatchReset NOROM_RFCCpePatchReset
RFCOverrideSearch [3/3]
#define RFCOverrideSearch NOROM_RFCOverrideSearch
RFCOverrideUpdate [3/3]
#define RFCOverrideUpdate NOROM_RFCOverrideUpdate
RFCHwIntGetAndClear [3/3]
#define RFCHwIntGetAndClear NOROM_RFCHwIntGetAndClear
RFCAnaDivTxOverride [3/3]
#define RFCAnaDivTxOverride NOROM_RFCAnaDivTxOverride
Function Documentation
RFCClockEnable()
__STATIC_INLINE void RFCClockEnable (void)
Enable the RF core clocks.
As soon as the RF core is started it will handle clock control autonomously. No check should be performed to check the clocks. Instead the radio can be ping'ed through the command interface.
Returns
None
RFCClockDisable()
__STATIC_INLINE void RFCClockDisable (void)
Disable the RF core clocks.
As soon as the RF core is started it will handle clock control autonomously. No check should be performed to check the clocks. Instead the radio can be ping'ed through the command interface.
When disabling clocks it is the programmers responsibility that the RF core clocks are safely gated. I.e. the RF core should be safely 'parked'.
Returns
None
RFCCpeIntClear()
__STATIC_INLINE void RFCCpeIntClear (uint32_t ui32Mask)
Clear HW interrupt flags.
Referenced by RFCCpe0IntSelectClearEnable(), and RFCCpe1IntSelectClearEnable().
RFCHwIntClear()
__STATIC_INLINE void RFCHwIntClear (uint32_t ui32Mask)
Clear CPE interrupt flags.
RFCCpe0IntSelect()
__STATIC_INLINE void RFCCpe0IntSelect (uint32_t ui32Mask)
Select interrupt sources to CPE0 (assign to INT_RFC_CPE_0 interrupt vector).
Referenced by RFCCpe0IntSelectClearEnable().
RFCCpe1IntSelect()
__STATIC_INLINE void RFCCpe1IntSelect (uint32_t ui32Mask)
Select interrupt sources to CPE1 (assign to INT_RFC_CPE_1 interrupt vector).
Referenced by RFCCpe1IntSelectClearEnable().
RFCCpeIntEnable()
__STATIC_INLINE void RFCCpeIntEnable (uint32_t ui32Mask)
Enable CPEx interrupt sources.
Referenced by RFCCpe0IntSelectClearEnable(), and RFCCpe1IntSelectClearEnable().
RFCCpe0IntSelectClearEnable()
__STATIC_INLINE void RFCCpe0IntSelectClearEnable (uint32_t ui32Mask)
Select, clear, and enable interrupt sources to CPE0.
References RFCCpe0IntSelect(), RFCCpeIntClear(), and RFCCpeIntEnable().
RFCCpe1IntSelectClearEnable()
__STATIC_INLINE void RFCCpe1IntSelectClearEnable (uint32_t ui32Mask)
Select, clear, and enable interrupt sources to CPE1.
References RFCCpe1IntSelect(), RFCCpeIntClear(), and RFCCpeIntEnable().
RFCHwIntEnable()
__STATIC_INLINE void RFCHwIntEnable (uint32_t ui32Mask)
Enable HW interrupt sources.
RFCCpeIntDisable()
__STATIC_INLINE void RFCCpeIntDisable (uint32_t ui32Mask)
Disable CPE interrupt sources.
RFCHwIntDisable()
__STATIC_INLINE void RFCHwIntDisable (uint32_t ui32Mask)
Disable HW interrupt sources.
References RFCCpeIntGetAndClear.
NOROM_RFCCpeIntGetAndClear()
uint32_t NOROM_RFCCpeIntGetAndClear (uint32_t ui32Mask)
Get and clear CPE interrupt flags.
RFCAckIntClear()
__STATIC_INLINE void RFCAckIntClear (void)
Clear ACK interrupt flag.
References RFCCpePatchReset, RFCDoorbellSendTo, RFCHwIntGetAndClear, RFCOverrideSearch, RFCOverrideUpdate, and RFCSynthPowerDown.
NOROM_RFCDoorbellSendTo()
uint32_t NOROM_RFCDoorbellSendTo (uint32_t pOp)
Send a radio operation to the doorbell and wait for an acknowledgment.
NOROM_RFCSynthPowerDown()
void NOROM_RFCSynthPowerDown (void)
This function implements a fast way to turn off the synthesizer.
NOROM_RFCCpePatchReset()
void NOROM_RFCCpePatchReset (void)
Reset previously patched CPE RAM to a state where it can be patched again.
NOROM_RFCOverrideSearch()
uint8_t NOROM_RFCOverrideSearch (const uint32_t * pOverride, const uint32_t pattern, const uint32_t mask, const uint8_t searchDepth)
NOROM_RFCOverrideUpdate()
uint8_t NOROM_RFCOverrideUpdate (rfc_radioOp_t * pOpSetup, uint32_t * pParams)
Function to update override list.
NOROM_RFCHwIntGetAndClear()
uint32_t NOROM_RFCHwIntGetAndClear (uint32_t ui32Mask)
Get and clear HW interrupt flags.
RFCGetPaType()
__STATIC_INLINE bool RFCGetPaType (void)
Get the type of currently selected PA.
References RFC_PA_TYPE_ADDRESS, and RFC_PA_TYPE_MASK.
RFCGetPaGain()
__STATIC_INLINE uint32_t RFCGetPaGain (void)
Get the gain of currently selected PA.
References RFC_PA_GAIN_ADDRESS, and RFC_PA_GAIN_MASK.
RFCGetPowerDomainStatus()
__STATIC_INLINE uint32_t RFCGetPowerDomainStatus (void)
Get the power domain status of the radio core.
RFCGetIeeeRxCaptureTime()
__STATIC_INLINE uint32_t RFCGetIeeeRxCaptureTime (void)
Get the capture time from RFC_RAM of the current received packet in an IEEE RX command Warning: Reading from RFC_RAM requires the RF Core to be powered.
References RFC_IEEE_CMD_BG_ADDRESS, RFC_IEEE_CMD_BG_IEEE_RX_O_CAP_TIME, and RFCAnaDivTxOverride.
NOROM_RFCAnaDivTxOverride()
uint32_t NOROM_RFCAnaDivTxOverride (uint8_t loDivider, uint8_t frontEndMode)
Function to calculate the proper override run-time for the High Gain PA.
NOROM_RFCRfTrimRead()
void NOROM_RFCRfTrimRead (rfc_radioOp_t * pOpSetup, rfTrim_t * rfTrim)
Read RF trim from flash using CM4.
NOROM_RFCRfTrimSet()
void NOROM_RFCRfTrimSet (rfTrim_t * rfTrim)
Write preloaded RF trim values directly into CPE.
Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale