CC26xx Driver Library: osc.c File Reference
osc.c File Reference
#include <stdlib.h>
#include "../inc/hw_types.h"
#include "../inc/hw_ccfg.h"
#include "../inc/hw_fcfg1.h"
#include "aon_batmon.h"
#include "aon_rtc.h"
#include "osc.h"
#include "sys_ctrl.h"
#include "setup_rom.h"
Data Structures
struct OscHfGlobals_t
struct hposc_insertions_t
struct hposc_param_t
Macros
#define RTC_CV_TO_MS(x) ((1000 * (x)) >> 16)
#define RTC_CV_TO_US(x) ((1000000 * (x)) >> 16)
#define D1OFFSET_25C (-16)
#define D2OFFSET_85C (-23)
#define D3OFFSET_n40C (5)
#define HPOSC_COEFF_BITS (20)
#define HPOSC_COEFF0_BITS (16)
#define HPOSC_D_BITS (30)
#define HPOSC_COEFF0_SHIFT (HPOSC_COEFF_BITS - HPOSC_COEFF0_BITS)
#define HPOSC_SHIFT1 (2*HPOSC_COEFF_BITS - HPOSC_D_BITS)
#define HPOSC_DC_BIAS (100000)
Functions
XoscLf_Params_t _lfXoscParams __attribute__ ((weak))
void OSCClockSourceSet (uint32_t ui32SrcClk, uint32_t ui32Osc)
Configure the oscillator input to the a source clock.
uint32_t OSCClockSourceGet (uint32_t ui32SrcClk)
Get the source clock settings.
uint32_t OSCHF_GetStartupTime (uint32_t timeUntilWakeupInMs)
Returns maximum startup time (in microseconds) of XOSC_HF.
void OSCHF_TurnOnXosc (void)
Turns on XOSC_HF (but without switching to XOSC_HF).
bool OSCHF_AttemptToSwitchToXosc (void)
Switch to XOSC_HF if XOSC_HF is ready.
void OSCHF_SwitchToRcOscTurnOffXosc (void)
Switch to RCOSC_HF and turn off XOSC_HF.
static void InternCapArrayAdjustWithBaseline7001F (int32_t capArrayDelta)
static uint32_t SpecialCapArrayWorkaroundEnabledAndNeeded (void)
void OSC_CapArrayAdjustWorkaround_Boot (void)
Special XOSC_HF workaround adjustment for CC13x2 / CC26x2 XOSC_CAPARRAY_DELTA setting in CCFG (Customer configuration)
void OSC_AdjustXoscHfCapArray (int32_t capArrDelta)
Adjust the XOSC HF cap array relative to the factory setting.
static void multiplyColumns (int64_t *v1, int64_t *v2, int64_t *pBuf, uint8_t shift)
static int64_t findDenominator (int64_t *col0, int64_t *col1, int64_t *col2)
static int64_t findNumerator (int32_t *pInput, int64_t *pBuf)
static void findHposcCoefficients (int32_t *pInput, int64_t *col0, int64_t *col1, int64_t *col2, hposc_param_t *pParam)
static void findHposcPc (int64_t *pCoeff, uint8_t *pBits, int32_t *pTemp, uint8_t nTemp, int64_t *pOutput)
static void readTempAndFreq (uint32_t regAddr, int32_t *pTemp, int32_t *pdFreq, int32_t deltaFreq)
void OSC_HPOSCInitializeFrequencyOffsetParameters (void)
HPOSC initialization function. Must always be called before using HPOSC.
void OSC_HPOSC_Debug_InitFreqOffsetParams (HposcDebugData_t *pDebugData)
Debug function to calculate the HPOSC polynomials for experimental data sets.
void OSC_HPOSCInitializeSingleInsertionFreqOffsParams (uint32_t measFieldAddress)
Special HPOSC initialization function for single temperature compensation.
void OSC_LFXOSCInitStaticOffset (void)
Initialize device specific coefficient for XOSC LF RTC compensation.
int32_t OSC_LFXOSCRelativeFrequencyOffsetGet (int32_t temperature)
Calculates the ppm offset of XOSC LF for a given temperature.
int32_t OSC_HPOSCRelativeFrequencyOffsetGet (int32_t tempDegC)
Calculate the temperature dependent relative frequency offset of HPOSC.
int16_t OSC_HPOSCRelativeFrequencyOffsetToRFCoreFormatConvert (int32_t HPOSC_RelFreqOffset)
Converts the relative frequency offset of HPOSC to the RF Core parameter format.
void OSC_HPOSCRtcCompensate (int32_t relFreqOffset)
Compensate the RTC increment based on the relative frequency offset of HPOSC.
uint32_t OSCHF_DebugGetCrystalAmplitude (void)
Get crystal amplitude (assuming crystal is running).
uint32_t OSCHF_DebugGetExpectedAverageCrystalAmplitude (void)
Get the expected average crystal amplitude.
uint32_t OSCHF_DebugGetCrystalStartupTime (void)
Measure the crystal startup time.
Variables
static OscHfGlobals_t oscHfGlobals
int32_t _hposcCoeffs [4] = {0}
Macro Definition Documentation
D1OFFSET_25C
#define D1OFFSET_25C (-16)
Referenced by OSC_HPOSCInitializeFrequencyOffsetParameters().
D2OFFSET_85C
#define D2OFFSET_85C (-23)
Referenced by OSC_HPOSCInitializeFrequencyOffsetParameters().
D3OFFSET_n40C
#define D3OFFSET_n40C (5)
Referenced by OSC_HPOSCInitializeFrequencyOffsetParameters().
HPOSC_COEFF0_BITS
#define HPOSC_COEFF0_BITS (16)
Referenced by findHposcCoefficients(), and OSC_HPOSCRelativeFrequencyOffsetGet().
HPOSC_COEFF0_SHIFT
#define HPOSC_COEFF0_SHIFT (HPOSC_COEFF_BITS - HPOSC_COEFF0_BITS)
Referenced by findHposcCoefficients(), and OSC_HPOSCRelativeFrequencyOffsetGet().
HPOSC_COEFF_BITS
#define HPOSC_COEFF_BITS (20)
Referenced by findDenominator(), findHposcCoefficients(), and findHposcPc().
HPOSC_D_BITS
#define HPOSC_D_BITS (30)
Referenced by findHposcCoefficients().
HPOSC_DC_BIAS
#define HPOSC_DC_BIAS (100000)
Referenced by findHposcCoefficients().
HPOSC_SHIFT1
#define HPOSC_SHIFT1 (2*HPOSC_COEFF_BITS - HPOSC_D_BITS)
Referenced by findDenominator(), and findHposcCoefficients().
RTC_CV_TO_MS
#define RTC_CV_TO_MS (x) ((1000 * (x)) >> 16)
Referenced by OSCHF_GetStartupTime().
RTC_CV_TO_US
#define RTC_CV_TO_US (x) ((1000000 * (x)) >> 16)
Referenced by OSCHF_AttemptToSwitchToXosc(), and OSCHF_GetStartupTime().
Function Documentation
__attribute__()
XoscLf_Params_t _lfXoscParams __attribute__ ((weak))
Referenced by CPUbasepriGet(), CPUbasepriSet(), CPUcpsid(), CPUcpsie(), CPUdelay(), CPUprimask(), CPUsev(), CPUwfe(), and CPUwfi().
findDenominator()
static int64_t findDenominator (int64_t * col0, int64_t * col1, int64_t * col2) static
Referenced by findHposcCoefficients().
 {
     int64_t tmp, tmpBuf[6];
     multiplyColumns(col1, col2, tmpBuf, HPOSC_SHIFT1); // Keep HPOSC_D_BITS precision
     tmp = (tmpBuf[0]*col0[0] - tmpBuf[1]*col0[0] - tmpBuf[2]*col0[1] +
            tmpBuf[3]*col0[1] + tmpBuf[4]*col0[2] - tmpBuf[5]*col0[2]) >> HPOSC_COEFF_BITS;
     return tmp;
 }
findHposcCoefficients()
static void findHposcCoefficients (int32_t * pInput, int64_t * col0, int64_t * col1, int64_t * col2, hposc_param_t * pParam) static
Referenced by OSC_HPOSC_Debug_InitFreqOffsetParams(), OSC_HPOSCInitializeFrequencyOffsetParameters(), and OSC_HPOSCInitializeSingleInsertionFreqOffsParams().
 {
     int64_t d,c0,c1,c2,cn,tmpBuf[6];
     int32_t inputBuf[3];
     uint8_t i;
     if(col1 == NULL) /* 1 insertion */
     {
         inputBuf[0] = pInput[0] - HPOSC_DC_BIAS;
         c0 = (((int64_t)inputBuf[0] << HPOSC_D_BITS) / col0[0]);
         c1 = 0;
         c2 = 0;
     }
     else /* 3 insertion */
     {
         /* Apply DC bias to input data */
         for(i = 0; i < 3; i++)
         {
             inputBuf[i] = pInput[i] - HPOSC_DC_BIAS;
         }
         /* Solve intermediate parameters, d: HPOSC_D_BITS, c: HPOSC_COEFF_BITS*2 bits */
         d = findDenominator(col0, col1, col2);
         multiplyColumns(col1, col2, tmpBuf, 0);
         cn = findNumerator(inputBuf, tmpBuf);
         c0 = cn / d;
         multiplyColumns(col0, col2, tmpBuf, 0);
         cn = -1*findNumerator(inputBuf, tmpBuf);
         c1 = cn / d;
         multiplyColumns(col0, col1, tmpBuf, 0);
         cn = findNumerator(inputBuf, tmpBuf);
         c2 = cn / d;
     }
     /* Compute TCF polynomial coefficients */
     for(i = 0; i < 4; i++)
     {
         cn = (((pParam->pu0c[i]*c0) >> (pParam->pu0b[i] - HPOSC_COEFF_BITS)) +
               ((pParam->pu1c[i]*c1) >> (pParam->pu1b[i] - HPOSC_COEFF_BITS)) +
               ((pParam->pu2c[i]*c2) >> (pParam->pu2b[i] - HPOSC_COEFF_BITS))) >> HPOSC_SHIFT1;
         if(i<3)
         {
             _hposcCoeffs[3-i] = cn;
         }
         else
         {
             _hposcCoeffs[0] = (cn >> HPOSC_COEFF0_SHIFT) + ((int64_t)HPOSC_DC_BIAS << HPOSC_COEFF0_BITS); // p[0] is combined with the DC bias
         }
     }
 }
findHposcPc()
static void findHposcPc (int64_t * pCoeff, uint8_t * pBits, int32_t * pTemp, uint8_t nTemp, int64_t * pOutput) static
Referenced by OSC_HPOSC_Debug_InitFreqOffsetParams(), OSC_HPOSCInitializeFrequencyOffsetParameters(), and OSC_HPOSCInitializeSingleInsertionFreqOffsParams().
 {
     uint8_t i;
     int32_t t1,t2,t3;
     for(i = 0; i < nTemp; i++)
     {
         t1 = pTemp[i];
         t2 = t1*t1;
         t3 = t2*t1;
         pOutput[i] = (((int64_t)pCoeff[0]*t3)>>(pBits[0]-HPOSC_COEFF_BITS)) + (((int64_t)pCoeff[1]*t2)>>(pBits[1]-HPOSC_COEFF_BITS)) +
                      (((int64_t)pCoeff[2]*t1)>>(pBits[2]-HPOSC_COEFF_BITS)) + (((int64_t)pCoeff[3]   )>>(pBits[3]-HPOSC_COEFF_BITS));
     }
 }
findNumerator()
static int64_t findNumerator (int32_t * pInput, int64_t * pBuf) static
Referenced by findHposcCoefficients().
 {
     int64_t tmp;
     tmp = ((int64_t)pInput[0]*pBuf[0]) - ((int64_t)pInput[0]*pBuf[1]) - ((int64_t)pInput[1]*pBuf[2]) +
           ((int64_t)pInput[1]*pBuf[3]) + ((int64_t)pInput[2]*pBuf[4]) - ((int64_t)pInput[2]*pBuf[5]);
     return tmp;
 }
InternCapArrayAdjustWithBaseline7001F()
static void InternCapArrayAdjustWithBaseline7001F (int32_t capArrayDelta) static
Referenced by OSC_AdjustXoscHfCapArray(), and OSC_CapArrayAdjustWorkaround_Boot().
 {
     int32_t     capArrayIndex       ;
     uint32_t    row                 ;
     uint32_t    col                 ;
     capArrayIndex = 36 + capArrayDelta ; // index = 36 corresponds to row/col 7/001F (which corresponds to 6.1pF)
     if ( capArrayIndex <  0 ) capArrayIndex =  0 ;
     if ( capArrayIndex > 63 ) capArrayIndex = 63 ;
     row = 0xF >> ( 3 - ( capArrayIndex >> 4 ));
     col = 0xFFFF >> ( 15 - ( capArrayIndex & 0xF ));
     HWREG( AUX_DDI0_OSC_BASE + DDI_0_OSC_O_ANABYPASSVAL1 ) = (( row << DDI_0_OSC_ANABYPASSVAL1_XOSC_HF_ROW_Q12_S    ) |
                                                               ( col << DDI_0_OSC_ANABYPASSVAL1_XOSC_HF_COLUMN_Q12_S )   );
 }
multiplyColumns()
static void multiplyColumns (int64_t * v1, int64_t * v2, int64_t * pBuf, uint8_t shift) static
Referenced by findDenominator(), and findHposcCoefficients().
 {
     pBuf[0] = (v1[1]*v2[2]) >> shift;
     pBuf[1] = (v1[2]*v2[1]) >> shift;
     pBuf[2] = (v1[0]*v2[2]) >> shift;
     pBuf[3] = (v1[2]*v2[0]) >> shift;
     pBuf[4] = (v1[0]*v2[1]) >> shift;
     pBuf[5] = (v1[1]*v2[0]) >> shift;
 }
readTempAndFreq()
static void readTempAndFreq (uint32_t regAddr, int32_t * pTemp, int32_t * pdFreq, int32_t deltaFreq) static
Referenced by OSC_HPOSC_Debug_InitFreqOffsetParams(), OSC_HPOSCInitializeFrequencyOffsetParameters(), and OSC_HPOSCInitializeSingleInsertionFreqOffsParams().
 {
     uint32_t insertionData = HWREG(regAddr);
     /* temp_stored = Temperature - 27, offset by -27C */
     *pTemp = (((int32_t)( insertionData << ( 32 - FCFG1_HPOSC_MEAS_1_HPOSC_T1_W - FCFG1_HPOSC_MEAS_1_HPOSC_T1_S )))
                                         >> ( 32 - FCFG1_HPOSC_MEAS_1_HPOSC_T1_W ));
     /* dFreq_stored = round( (Freq/12e6 - 1) * 2^22 ), 12MHz is the ideal frequency */
     *pdFreq = (((int32_t)( insertionData << ( 32 - FCFG1_HPOSC_MEAS_1_HPOSC_D1_W - FCFG1_HPOSC_MEAS_1_HPOSC_D1_S )))
                                          >> ( 32 - FCFG1_HPOSC_MEAS_1_HPOSC_D1_W ));
     *pdFreq = *pdFreq + deltaFreq;
 }
SpecialCapArrayWorkaroundEnabledAndNeeded()
static uint32_t SpecialCapArrayWorkaroundEnabledAndNeeded (void) static
Referenced by OSC_AdjustXoscHfCapArray(), and OSC_CapArrayAdjustWorkaround_Boot().
 {
     if ((( HWREG( CCFG_BASE + CCFG_O_SIZE_AND_DIS_FLAGS ) & CCFG_SIZE_AND_DIS_FLAGS_DIS_LINEAR_CAPARRAY_DELTA_WORKAROUND ) == 0      ) &&
         ((( HWREG( FCFG1_BASE + FCFG1_O_CONFIG_OSC_TOP ) >> FCFG1_CONFIG_OSC_TOP_XOSC_HF_COLUMN_Q12_S ) & 0x000FFFF1 ) == 0x000701F0 )    )
     {
         return ( 1 );
     } else {
         return ( 0 );
     }
 }
Variable Documentation
_hposcCoeffs
int32_t _hposcCoeffs[4] = {0}
oscHfGlobals
OscHfGlobals_t oscHfGlobals static