CC26xx Driver Library: rom_crypto.c File Reference
rom_crypto.c File Reference
#include <stdint.h>
#include "rom_crypto.h"
Typedefs
typedef uint8_t(* ecc_keygen_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *)
typedef uint8_t(* ecdsa_sign_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *)
typedef uint8_t(* ecdsa_verify_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *)
typedef uint8_t(* ecdh_computeSharedSecret_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *)
Functions
void ECC_initialize (uint32_t *pWorkzone)
Initialize elliptic curve parameters to default values and specify workzone.
void ECC_init (uint32_t *workzone, uint8_t windowSize, const uint32_t *prime, const uint32_t *order, const uint32_t *a, const uint32_t *b, const uint32_t *generatorX, const uint32_t *generatorY)
Initialize elliptic curve parameters to specified values and specify workzone.
uint8_t ECC_generateKey (uint32_t *randString, uint32_t *privateKey, uint32_t *publicKey_x, uint32_t *publicKey_y)
Generate a key.
uint8_t ECC_ECDSA_sign (uint32_t *secretKey, uint32_t *text, uint32_t *randString, uint32_t *sign1, uint32_t *sign2)
Sign data.
uint8_t ECC_ECDSA_verify (uint32_t *publicKey_x, uint32_t *publicKey_y, uint32_t *text, uint32_t *sign1, uint32_t *sign2)
Verify signature.
uint8_t ECC_ECDH_computeSharedSecret (uint32_t *privateKey, uint32_t *publicKey_x, uint32_t *publicKey_y, uint32_t *sharedSecret_x, uint32_t *sharedSecret_y)
Compute the shared secret.
Variables
ecc_keygen_t ecc_generatekey = (ecc_keygen_t)(0x1001f94d)
ecdsa_sign_t ecc_ecdsa_sign = (ecdsa_sign_t)(0x10010381)
ecdsa_verify_t ecc_ecdsa_verify = (ecdsa_verify_t)(0x1000c805)
ecdh_computeSharedSecret_t ecdh_computeSharedSecret = (ecdh_computeSharedSecret_t)(0x10023485)
Typedef Documentation
ecc_keygen_t
typedef uint8_t(* ecc_keygen_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *)
ecdh_computeSharedSecret_t
typedef uint8_t(* ecdh_computeSharedSecret_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *)
ecdsa_sign_t
typedef uint8_t(* ecdsa_sign_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *)
ecdsa_verify_t
typedef uint8_t(* ecdsa_verify_t) (uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *)
Variable Documentation
ecc_ecdsa_sign
ecdsa_sign_t ecc_ecdsa_sign = (ecdsa_sign_t)(0x10010381)
Referenced by ECC_ECDSA_sign().
ecc_ecdsa_verify
ecdsa_verify_t ecc_ecdsa_verify = (ecdsa_verify_t)(0x1000c805)
Referenced by ECC_ECDSA_verify().
ecc_generatekey
ecc_keygen_t ecc_generatekey = (ecc_keygen_t)(0x1001f94d)
Referenced by ECC_generateKey().
ecdh_computeSharedSecret
ecdh_computeSharedSecret_t ecdh_computeSharedSecret = (ecdh_computeSharedSecret_t)(0x10023485)
Referenced by ECC_ECDH_computeSharedSecret().