OpenThread: alarm.cpp File Reference
alarm.cpp File Reference
#include "openthread-posix-config.h"
#include "platform-posix.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <openthread/platform/alarm-micro.h>
#include <openthread/platform/alarm-milli.h>
#include <openthread/platform/diag.h>
#include "common/code_utils.hpp"
Macros
#define OT_POSIX_CLOCK_ID CLOCK_MONOTONIC
Functions
uint32_t otPlatAlarmMilliGetNow (void)
void otPlatAlarmMilliStartAt (otInstance *aInstance, uint32_t aT0, uint32_t aDt)
void otPlatAlarmMilliStop (otInstance *aInstance)
uint64_t otPlatTimeGet (void)
static uint64_t platformAlarmGetNow (void)
void platformAlarmInit (uint32_t aSpeedUpFactor, int aRealTimeSignal)
void platformAlarmProcess (otInstance *aInstance)
void platformAlarmUpdateTimeout (struct timeval *aTimeout)
Variables
static bool sIsMsRunning = false
static uint32_t sMsAlarm = 0
static uint32_t sSpeedUpFactor = 1
Macro Definition Documentation
OT_POSIX_CLOCK_ID
#define OT_POSIX_CLOCK_ID CLOCK_MONOTONIC
Referenced by otPlatTimeGet().
Function Documentation
platformAlarmGetNow()
static uint64_t platformAlarmGetNow (void) static
References otPlatTimeGet(), and sSpeedUpFactor.
Referenced by otPlatAlarmMilliGetNow(), otPlatAlarmMilliStop(), and platformAlarmUpdateTimeout().
platformAlarmInit()
void platformAlarmInit (uint32_t aSpeedUpFactor, int aRealTimeSignal)
This function initializes the alarm service used by OpenThread.
Parameters
[in] aSpeedUpFactor The speed up factor.
[in] aRealTimeSignal The real time signal for microsecond alarms.
References DieNow, OT_EXIT_ERROR_ERRNO, OT_EXIT_INVALID_ARGUMENTS, otLogWarnPlat(), sSpeedUpFactor, and VerifyOrDie.
Referenced by platformInit().
platformAlarmUpdateTimeout()
void platformAlarmUpdateTimeout (struct timeval * tv)
This function retrieves the time remaining until the alarm fires.
Parameters
[out] aTimeval A pointer to the timeval struct.
References platformAlarmGetNow(), sIsMsRunning, sMsAlarm, sSpeedUpFactor, US_PER_MS, US_PER_S, and VerifyOrExit.
Referenced by otSysMainloopUpdate().
platformAlarmProcess()
void platformAlarmProcess (otInstance * aInstance)
This function performs alarm driver processing.
Parameters
[in] aInstance The OpenThread instance structure.
References otPlatAlarmMicroFired(), otPlatAlarmMicroGetNow(), otPlatAlarmMilliFired(), otPlatAlarmMilliGetNow(), otPlatDiagAlarmFired(), otPlatDiagModeGet(), sIsMsRunning, and sMsAlarm.
Referenced by otSysMainloopProcess().
Variable Documentation
sIsMsRunning
bool sIsMsRunning = false static
Referenced by otPlatAlarmMilliStartAt(), otPlatAlarmMilliStop(), platformAlarmProcess(), and platformAlarmUpdateTimeout().
sMsAlarm
uint32_t sMsAlarm = 0 static
Referenced by otPlatAlarmMilliStartAt(), platformAlarmProcess(), and platformAlarmUpdateTimeout().
sSpeedUpFactor
uint32_t sSpeedUpFactor = 1 static
Referenced by platformAlarmGetNow(), platformAlarmInit(), and platformAlarmUpdateTimeout().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale