OpenThread: Instance Class Reference
Instance Class Reference
Core-instance
#include <instance.hpp>
Data Structures
class BufferInfo
Public Member Functions
void Finalize (void)
template<typename Type >
Type & Get (void)
template<>
Instance & Get (void)
template<>
Radio & Get (void)
template<>
Radio::Callbacks & Get (void)
template<>
Tasklet::Scheduler & Get (void)
template<>
TimerMilli::Scheduler & Get (void)
bool IsInitialized (void) const
void Reset (void)
Static Public Member Functions
static Instance & Get (void)
static LogLevel GetLogLevel (void)
static Instance & InitSingle (void)
Private Member Functions
void AfterInit (void)
Instance (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
bool mIsInitialized
Radio mRadio
Random::Manager mRandomManager
Tasklet::Scheduler mTaskletScheduler
TimerMilli::Scheduler mTimerMilliScheduler
Detailed Description
This class represents an OpenThread instance.
This class contains all the components used by OpenThread.
Constructor & Destructor Documentation
Instance()
Instance (void) private
Referenced by Instance::Get(), and Instance::InitSingle().
Member Function Documentation
InitSingle()
Instance & InitSingle (void) static
This static method initializes the single OpenThread instance.
This method initializes OpenThread and prepares it for subsequent OpenThread API calls. This function must be called before any other calls to OpenThread.
Returns
A reference to the single OpenThread instance.
References Instance::AfterInit(), Instance::Get(), ot::gInstanceRaw, Instance::Instance(), Instance::mIsInitialized, and VerifyOrExit.
Referenced by otInstanceInitSingle().
Get() [1/6]
Instance & Get (void) static
This static method returns a reference to the single OpenThread instance.
Returns
A reference to the single OpenThread instance.
References Instance::AfterInit(), ot::gInstanceRaw, Instance::Instance(), and VerifyOrExit.
Referenced by Dataset::ApplyConfiguration(), Headers::DecompressFrom(), Dataset::Info::GenerateRandom(), Instance::InitSingle(), NcpBase::NcpBase(), otIp6SelectSourceAddress(), otIp6SetEnabled(), otLinkGetChannel(), otLinkSetChannel(), otLinkSetEnabled(), otLinkSetExtendedAddress(), otLinkSetPanId(), otLinkSetPromiscuous(), otLinkSetSupportedChannelMask(), TimerMilli::RemoveAll(), RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp(), ExternalRouteConfig::SetFrom(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
IsInitialized()
bool IsInitialized (void) const inline
This method indicates whether or not the instance is valid/initialized and not yet finalized.
Returns
TRUE if the instance is valid/initialized, FALSE otherwise.
Reset()
void Reset (void)
This method triggers a platform reset.
The reset process ensures that all the OpenThread state/info (stored in volatile memory) is erased. Note that this method does not erase any persistent state/info saved in non-volatile memory.
References Instance::mRadio, and otPlatReset().
GetLogLevel()
static LogLevel GetLogLevel (void) inline static
This method returns the active log level.
Returns
The log level.
References OPENTHREAD_CONFIG_LOG_LEVEL.
Referenced by MeshForwarder::CalcFrameVersion(), and otLoggingGetLevel().
Finalize()
void Finalize (void)
This method finalizes the OpenThread instance.
This method should be called when OpenThread instance is no longer in use.
Object was created on buffer, so instead of deleting the object we call destructor explicitly.
References Clearable< Type >::Clear(), IgnoreError(), ot::kErrorInvalidState, ot::kErrorNone, otBufferInfo::m6loReassemblyQueue, otBufferInfo::m6loSendQueue, otBufferInfo::mApplicationCoapQueue, otBufferInfo::mCoapQueue, otBufferInfo::mCoapSecureQueue, otBufferInfo::mFreeBuffers, otBufferInfo::mIp6Queue, Instance::mIsInitialized, otBufferInfo::mMleQueue, otBufferInfo::mMplQueue, otBufferInfo::mTotalBuffers, OT_TOOL_WEAK, OT_UNUSED_VARIABLE, otIp6SetEnabled(), otLinkSetEnabled(), otPlatLogHandleLevelChanged(), otPlatReset(), otThreadSetEnabled(), and VerifyOrExit.
Get() [2/6]
Type& Get (void) inline
This template method returns a reference to a given Type object belonging to the OpenThread instance.
For example, Get<MeshForwarder>() returns a reference to the MeshForwarder object of the instance.
Note that any Type for which the Get<Type> is defined MUST be uniquely accessible from the OpenThread Instance through the member variable property hierarchy.
Specializations of the Get<Type>() method are defined in this file after the Instance class definition.
Returns
A reference to the Type object of the instance.
AfterInit()
void AfterInit (void) private
References Instance::mIsInitialized.
Referenced by Instance::Get(), and Instance::InitSingle().
Get() [3/6]
Radio& Get (void) inline
Get() [4/6]
Radio::Callbacks& Get (void) inline
Get() [5/6]
Tasklet::Scheduler& Get (void) inline
Get() [6/6]
TimerMilli::Scheduler& Get (void) inline
Field Documentation
mTaskletScheduler
Tasklet::Scheduler mTaskletScheduler private
mTimerMilliScheduler
TimerMilli::Scheduler mTimerMilliScheduler private
mRandomManager
Random::Manager mRandomManager private
mRadio
Radio mRadio private
Referenced by Instance::Reset().
mIsInitialized
bool mIsInitialized private
Referenced by Instance::AfterInit(), Instance::Finalize(), and Instance::InitSingle().
The documentation for this class was generated from the following files:
instance.hpp
instance.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale