OpenThread: Option Class Reference
Option Class Reference
Core-coap
#include <coap_message.hpp>
Data Structures
class Iterator
Public Member Functions
uint16_t GetLength (void) const
uint16_t GetNumber (void) const
Additional Inherited Members
Data Fields inherited from otCoapOption
uint16_t mLength
Option Length.
uint16_t mNumber
Option Number.
Detailed Description
This class represents a CoAP option.
Member Function Documentation
GetNumber()
uint16_t GetNumber (void) const inline
This method gets the CoAP Option Number.
Returns
The CoAP Option Number.
Referenced by CoapBase::DequeueMessage(), CoapBase::ProcessReceivedRequest(), and CoapBase::ProcessReceivedResponse().
GetLength()
uint16_t GetLength (void) const inline
This method gets the CoAP Option Length (length of Option Value in bytes).
Returns
The CoAP Option Length (in bytes).
References ot::DefineCoreType(), and ot::DefineMapEnum().
Referenced by Message::AppendBlockOption(), CoapBase::DequeueMessage(), CoapBase::ProcessReceivedRequest(), and Message::ReadUriPathOptions().
The documentation for this class was generated from the following file:
coap_message.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale