OpenThread: Option::Iterator Class Reference
Option::Iterator Class Reference
#include <coap_message.hpp>
Public Member Functions
Error Advance (void)
Error Advance (uint16_t aNumber)
const Message & GetMessage (void) const
const Option * GetOption (void) const
uint16_t GetPayloadMessageOffset (void) const
bool HasParseErrored (void) const
Error Init (const Message &aMessage)
Error Init (const Message &aMessage, uint16_t aNumber)
bool IsDone (void) const
Error ReadOptionValue (void *aValue) const
Error ReadOptionValue (uint64_t &aUintValue) const
Private Member Functions
Error InitOrAdvance (const Message *aMessage, uint16_t aNumber)
void MarkAsDone (void)
void MarkAsParseErrored (void)
Error Read (uint16_t aLength, void *aBuffer)
Error ReadExtendedOptionField (uint16_t &aValue)
Static Private Attributes
static constexpr uint16_t kIteratorDoneLength = 0xffff
static constexpr uint16_t kNextOptionOffsetParseError = 0
Additional Inherited Members
Data Fields inherited from otCoapOptionIterator
const otMessage * mMessage
CoAP message.
uint16_t mNextOptionOffset
Byte offset of next option.
otCoapOption mOption
CoAP message option.
Detailed Description
This class represents an iterator for CoAP options.
Member Function Documentation
Init() [1/2]
Error Init (const Message & aMessage)
This method initializes the iterator to iterate over CoAP Options in a CoAP message.
The iterator MUST be initialized before any other methods are used, otherwise its behavior is undefined.
After initialization, the iterator is either updated to point to the first option, or it is marked as done (i.e., IsDone() returns true) when there is no option or if there is a parse error.
Parameters
[in] aMessage The CoAP message.
Return values
kErrorNone Successfully initialized. Iterator is either at the first option or done.
kErrorParse CoAP Option header in aMessage is not well-formed.
References Message::GetHelpData(), Message::GetLength(), Message::GetOptionStart(), ot::kErrorParse, Message::HelpData::mHeaderOffset, and VerifyOrExit.
Referenced by Message::AppendBlockOption(), CoapBase::DequeueMessage(), Message::ParseHeader(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), Message::ReadUriPathOptions(), and CoapBase::SendMessage().
Init() [2/2]
Error Init (const Message & aMessage, uint16_t aNumber) inline
This method initializes the iterator to iterate over CoAP Options in a CoAP message matching a given Option Number value.
The iterator MUST be initialized before any other methods are used, otherwise its behavior is undefined.
After initialization, the iterator is either updated to point to the first option matching the given Option Number value, or it is marked as done (i.e., IsDone() returns true) when there is no matching option or if there is a parse error.
Parameters
[in] aMessage The CoAP message.
[in] aNumber The CoAP Option Number.
Return values
kErrorNone Successfully initialized. Iterator is either at the first matching option or done.
kErrorParse CoAP Option header in aMessage is not well-formed.
IsDone()
bool IsDone (void) const inline
This method indicates whether or not the iterator is done (i.e., has reached the end of CoAP Option Header).
Return values
TRUE Iterator is done (reached end of Option header).
FALSE Iterator is not done and currently pointing to a CoAP Option.
Referenced by CoapBase::DequeueMessage(), Message::ParseHeader(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), Message::ReadUriPathOptions(), and CoapBase::SendMessage().
HasParseErrored()
bool HasParseErrored (void) const inline
This method indicates whether or not there was a earlier parse error (i.e., whether the iterator is valid).
After a parse errors, iterator would also be marked as done.
Return values
TRUE There was an earlier parse error and the iterator is not valid.
FALSE There was no earlier parse error and the iterator is valid.
Advance() [1/2]
Error Advance (void)
This method advances the iterator to the next CoAP Option in the header.
The iterator is updated to point to the next option or marked as done when there are no more options.
Return values
kErrorNone Successfully advanced the iterator.
kErrorParse CoAP Option header is not well-formed.
References ExitNow, Message::GetLength(), ot::kErrorNone, ot::kErrorParse, Message::kOptionDeltaMask, Message::kOptionDeltaOffset, Message::kOptionLengthMask, Message::kOptionLengthOffset, Message::kPayloadMarker, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::DequeueMessage(), Message::ParseHeader(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), and Message::ReadUriPathOptions().
Advance() [2/2]
Error Advance (uint16_t aNumber) inline
This method advances the iterator to the next CoAP Option in the header matching a given Option Number value.
The iterator is updated to point to the next matching option or marked as done when there are no more matching options.
Parameters
[in] aNumber The CoAP Option Number.
Return values
kErrorNone Successfully advanced the iterator.
kErrorParse CoAP Option header is not well-formed.
GetMessage()
const Message& GetMessage (void) const inline
This method gets the CoAP message associated with the iterator.
Returns
A reference to the CoAP message.
GetOption()
const Option* GetOption (void) const inline
This methods gets a pointer to the current CoAP Option to which the iterator is currently pointing.
Returns
A pointer to the current CoAP Option, or nullptr if iterator is done (or there was an earlier parse error).
Referenced by Message::AppendBlockOption(), CoapBase::DequeueMessage(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), and Message::ReadUriPathOptions().
ReadOptionValue() [1/2]
Error ReadOptionValue (void * aValue) const
This method reads the current Option Value into a given buffer.
Parameters
[out] aValue The pointer to a buffer to copy the Option Value. The buffer is assumed to be sufficiently large (i.e. at least GetOption()->GetLength() bytes).
Return values
kErrorNone Successfully read and copied the Option Value into given buffer.
kErrorNotFound Iterator is done (not pointing to any option).
References ot::kErrorNone, ot::kErrorNotFound, and VerifyOrExit.
Referenced by Message::AppendBlockOption(), CoapBase::DequeueMessage(), CoapBase::ProcessReceivedRequest(), Message::ReadUriPathOptions(), and CoapBase::SendMessage().
ReadOptionValue() [2/2]
Error ReadOptionValue (uint64_t & aUintValue) const
This method read the current Option Value which is assumed to be an unsigned integer.
Parameters
[out] aUintValue A reference to uint64_t to output the read Option Value.
Return values
kErrorNone Successfully read the Option value.
kErrorNoBufs Value is too long to fit in an uint64_t.
kErrorNotFound Iterator is done (not pointing to any option).
References IgnoreError(), ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNotFound, and VerifyOrExit.
GetPayloadMessageOffset()
uint16_t GetPayloadMessageOffset (void) const inline
This method gets the offset of beginning of the CoAP message payload (after the CoAP header).
This method MUST be used after the iterator is done (i.e. iterated through all options).
Returns
The offset of beginning of the CoAP message payload
Referenced by Message::ParseHeader().
MarkAsDone()
void MarkAsDone (void) inline private
MarkAsParseErrored()
void MarkAsParseErrored (void) inline private
References Message::Read().
Read()
Error Read (uint16_t aLength, void * aBuffer) private
References ot::kErrorNone, Message::Read(), and SuccessOrExit.
ReadExtendedOptionField()
Error ReadExtendedOptionField (uint16_t & aValue) private
References ot::Encoding::BigEndian::HostSwap16(), ot::kErrorNone, ot::kErrorParse, Message::kOption1ByteExtension, Message::kOption1ByteExtensionOffset, Message::kOption2ByteExtension, Message::kOption2ByteExtensionOffset, Message::Read(), SuccessOrExit, and VerifyOrExit.
InitOrAdvance()
Error InitOrAdvance (const Message * aMessage, uint16_t aNumber) private
References Message::Init(), and ot::kErrorNone.
Field Documentation
kIteratorDoneLength
constexpr uint16_t kIteratorDoneLength = 0xffff static private
kNextOptionOffsetParseError
constexpr uint16_t kNextOptionOffsetParseError = 0 static private
The documentation for this class was generated from the following files:
coap_message.hpp
coap_message.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale