OpenThread: SteeringData Class Reference
SteeringData Class Reference
#include <meshcop.hpp>
Data Structures
struct HashBitIndexes
Public Member Functions
void Clear (void)
bool Contains (const Mac::ExtAddress &aJoinerId) const
bool Contains (const JoinerDiscerner &aDiscerner) const
bool Contains (const HashBitIndexes &aIndexes) const
const uint8_t * GetData (void) const
uint8_t * GetData (void)
uint8_t GetLength (void) const
void Init (uint8_t aLength=kMaxLength)
bool IsEmpty (void) const
bool PermitsAllJoiners (void) const
void SetToPermitAllJoiners (void)
void UpdateBloomFilter (const Mac::ExtAddress &aJoinerId)
void UpdateBloomFilter (const JoinerDiscerner &aDiscerner)
Static Public Member Functions
static void CalculateHashBitIndexes (const Mac::ExtAddress &aJoinerId, HashBitIndexes &aIndexes)
static void CalculateHashBitIndexes (const JoinerDiscerner &aDiscerner, HashBitIndexes &aIndexes)
Static Public Attributes
static constexpr uint8_t kMaxLength = OT_STEERING_DATA_MAX_LENGTH
Maximum Steering Data length (in bytes).
Private Member Functions
uint8_t BitFlag (uint8_t aBit) const
uint8_t BitIndex (uint8_t aBit) const
void ClearBit (uint8_t aBit)
bool DoesAllMatch (uint8_t aMatch) const
bool GetBit (uint8_t aBit) const
uint8_t GetNumBits (void) const
void SetBit (uint8_t aBit)
void UpdateBloomFilter (const HashBitIndexes &aIndexes)
Static Private Attributes
static constexpr uint8_t kPermitAll = 0xff
Additional Inherited Members
Data Fields inherited from otSteeringData
uint8_t m8 [OT_STEERING_DATA_MAX_LENGTH]
Byte values.
uint8_t mLength
Length of steering data (bytes)
Detailed Description
This type represents Steering Data (bloom filter).
Member Function Documentation
Init()
void Init (uint8_t aLength = kMaxLength)
This method initializes the Steering Data and clears the bloom filter.
Parameters
[in] aLength The Steering Data length (in bytes) - MUST be smaller than or equal to kMaxLength.
References JoinerPskd::kMaxLength, otJoinerPskd::m8, and OT_ASSERT.
Referenced by SteeringDataTlv::CopyTo(), and DiscoverScanner::HandleDiscoveryResponse().
Clear()
void Clear (void) inline
This method clears the bloom filter (all bits are cleared and no Joiner Id is accepted)..
The Steering Data length (bloom filter length) is set to one byte with all bits cleared.
SetToPermitAllJoiners()
void SetToPermitAllJoiners (void)
This method sets the bloom filter to permit all Joiner IDs.
To permit all Joiner IDs, The Steering Data length (bloom filter length) is set to one byte with all bits set.
References otJoinerPskd::m8.
GetLength()
uint8_t GetLength (void) const inline
This method returns the Steering Data length (in bytes).
Returns
The Steering Data length (in bytes).
GetData() [1/2]
const uint8_t* GetData (void) const inline
This method gets the Steering Data buffer (bloom filter).
Returns
A pointer to the Steering Data buffer.
References otJoinerPskd::m8.
Referenced by SteeringDataTlv::CopyTo(), and DiscoverScanner::HandleDiscoveryResponse().
GetData() [2/2]
uint8_t* GetData (void) inline
This method gets the Steering Data buffer (bloom filter).
Returns
A pointer to the Steering Data buffer.
References otJoinerPskd::m8.
UpdateBloomFilter() [1/3]
void UpdateBloomFilter (const Mac::ExtAddress & aJoinerId)
This method updates the bloom filter adding the given Joiner ID.
Parameters
[in] aJoinerId The Joiner ID to add to bloom filter.
UpdateBloomFilter() [2/3]
void UpdateBloomFilter (const JoinerDiscerner & aDiscerner)
This method updates the bloom filter adding a given Joiner Discerner.
Parameters
[in] aDiscerner The Joiner Discerner to add to bloom filter.
IsEmpty()
bool IsEmpty (void) const inline
This method indicates whether the bloom filter is empty (all the bits are cleared).
Returns
TRUE if the bloom filter is empty, FALSE otherwise.
PermitsAllJoiners()
bool PermitsAllJoiners (void) const inline
This method indicates whether the bloom filter permits all Joiner IDs (all the bits are set).
Returns
TRUE if the bloom filter permits all Joiners IDs, FALSE otherwise.
Contains() [1/3]
bool Contains (const Mac::ExtAddress & aJoinerId) const
This method indicates whether the bloom filter contains a given Joiner ID.
Parameters
[in] aJoinerId A Joiner ID.
Returns
TRUE if the bloom filter contains aJoinerId, FALSE otherwise.
Referenced by DiscoverScanner::HandleDiscoveryResponse(), and LeaderBase::SteeringDataCheck().
Contains() [2/3]
bool Contains (const JoinerDiscerner & aDiscerner) const
This method indicates whether the bloom filter contains a given Joiner Discerner.
Parameters
[in] aDiscerner A Joiner Discerner.
Returns
TRUE if the bloom filter contains aDiscerner, FALSE otherwise.
Contains() [3/3]
bool Contains (const HashBitIndexes & aIndexes) const
This method indicates whether the bloom filter contains the hash bit indexes (derived from a Joiner ID).
Parameters
[in] aIndexes A hash bit index structure (derived from a Joiner ID).
Returns
TRUE if the bloom filter contains the Joiner ID mapping to aIndexes, FALSE otherwise.
References SteeringData::HashBitIndexes::mIndex.
CalculateHashBitIndexes() [1/2]
void CalculateHashBitIndexes (const Mac::ExtAddress & aJoinerId, HashBitIndexes & aIndexes) static
This static method calculates the bloom filter hash bit indexes from a given Joiner ID.
The first hash bit index is derived using CRC16-CCITT and second one using CRC16-ANSI.
Parameters
[in] aJoinerId The Joiner ID to calculate the hash bit indexes.
[out] aIndexes A reference to a HashBitIndexes structure to output the calculated index values.
References Crc16::Get(), Crc16::kAnsi, Crc16::kCcitt, otExtAddress::m8, SteeringData::HashBitIndexes::mIndex, and Crc16::Update().
Referenced by DiscoverScanner::Discover(), and LeaderBase::SteeringDataCheckJoiner().
CalculateHashBitIndexes() [2/2]
void CalculateHashBitIndexes (const JoinerDiscerner & aDiscerner, HashBitIndexes & aIndexes) static
This static method calculates the bloom filter hash bit indexes from a given Joiner Discerner.
The first hash bit index is derived using CRC16-CCITT and second one using CRC16-ANSI.
Parameters
[in] aDiscerner The Joiner Discerner to calculate the hash bit indexes.
[out] aIndexes A reference to a HashBitIndexes structure to output the calculated index values.
References Clearable< Type >::Clear(), and JoinerDiscerner::CopyTo().
GetNumBits()
uint8_t GetNumBits (void) const inline private
BitIndex()
uint8_t BitIndex (uint8_t aBit) const inline private
BitFlag()
uint8_t BitFlag (uint8_t aBit) const inline private
GetBit()
bool GetBit (uint8_t aBit) const inline private
References otJoinerPskd::m8.
SetBit()
void SetBit (uint8_t aBit) inline private
References otJoinerPskd::m8.
ClearBit()
void ClearBit (uint8_t aBit) inline private
References ot::MeshCoP::ComputeJoinerId(), ot::MeshCoP::GeneratePskc(), ot::MeshCoP::GetBorderAgentRloc(), ot::MeshCoP::LogError(), and otJoinerPskd::m8.
DoesAllMatch()
bool DoesAllMatch (uint8_t aMatch) const private
References otJoinerPskd::m8.
UpdateBloomFilter() [3/3]
void UpdateBloomFilter (const HashBitIndexes & aIndexes) private
References JoinerPskd::kMaxLength, SteeringData::HashBitIndexes::mIndex, and OT_ASSERT.
Field Documentation
kMaxLength
constexpr uint8_t kMaxLength = OT_STEERING_DATA_MAX_LENGTH static
Maximum Steering Data length (in bytes).
Referenced by DiscoverScanner::HandleDiscoveryResponse().
kPermitAll
constexpr uint8_t kPermitAll = 0xff static private
The documentation for this class was generated from the following files:
meshcop.hpp
meshcop.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale