OpenThread: TxFrames Class Reference
TxFrames Class Reference
Core-mac
#include <mac_links.hpp>
Public Member Functions
void Clear (void)
TxFrame & GetBroadcastTxFrame (void)
void SetChannel (uint8_t aChannel)
void SetMaxCsmaBackoffs (uint8_t aMaxCsmaBackoffs)
void SetMaxFrameRetries (uint8_t aMaxFrameRetries)
void SetSequence (uint8_t aSequence)
Private Member Functions
TxFrames (Instance &aInstance)
Private Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
InstanceLocator (Instance &aInstance)
Private Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
GetProvider (void)=default
Friends
class Links
Detailed Description
This class represents tx frames for different radio link types.
Constructor & Destructor Documentation
TxFrames()
TxFrames (Instance & aInstance) explicit private
References TxFrames::GetBroadcastTxFrame(), and Frame::GetMtu().
Referenced by TxFrames::SetMaxFrameRetries().
Member Function Documentation
GetBroadcastTxFrame()
TxFrame& GetBroadcastTxFrame (void) inline
This method gets a tx frame for sending a broadcast frame.
Returns
A reference to a TxFrame for broadcast.
Referenced by Mac::BeginTransmit(), Mac::PrepareBeacon(), Mac::PrepareBeaconRequest(), and TxFrames::TxFrames().
Clear()
void Clear (void) inline
This method clears all supported radio tx frames (sets the PSDU length to zero and clears flags).
Referenced by Mac::BeginTransmit(), and Mac::PrepareBeacon().
SetChannel()
void SetChannel (uint8_t aChannel) inline
This method sets the channel on all supported radio tx frames.
Parameters
[in] aChannel A channel.
Referenced by Mac::BeginTransmit().
SetSequence()
void SetSequence (uint8_t aSequence) inline
This method sets the Sequence Number value on all supported radio tx frames.
Parameters
[in] aSequence The Sequence Number value.
SetMaxCsmaBackoffs()
void SetMaxCsmaBackoffs (uint8_t aMaxCsmaBackoffs) inline
This method sets the maximum number of the CSMA-CA backoffs on all supported radio tx frames.
Parameters
[in] aMaxCsmaBackoffs The maximum number of CSMA-CA backoffs.
Referenced by Mac::BeginTransmit().
SetMaxFrameRetries()
void SetMaxFrameRetries (uint8_t aMaxFrameRetries) inline
This method sets the maximum number of retries allowed after a transmission failure on all supported radio tx frames.
Parameters
[in] aMaxFrameRetries The maximum number of retries allowed after a transmission failure.
References TxFrames::TxFrames().
Referenced by Mac::BeginTransmit(), and DataPollSender::PrepareDataRequest().
Friends And Related Function Documentation
Links
friend class Links friend
The documentation for this class was generated from the following files:
mac_links.hpp
mac_links.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale