OpenThread: Notifier Class Reference
Notifier Class Reference
Core-notifier
#include <notifier.hpp>
Data Structures
struct ExternalCallback
Public Member Functions
bool HasSignaled (Event aEvent) const
bool IsPending (void) const
Notifier (Instance &aInstance)
Error RegisterCallback (otStateChangedCallback aCallback, void *aContext)
void RemoveCallback (otStateChangedCallback aCallback, void *aContext)
void Signal (Event aEvent)
void SignalIfFirst (Event aEvent)
template<typename Type >
Error Update (Type &aVariable, const Type &aNewValue, Event aEvent)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void EmitEvents (void)
const char * EventToString (Event aEvent) const
void LogEvents (Events aEvents) const
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void EmitEvents (Tasklet &aTasklet)
Private Attributes
Events mEventsToSignal
ExternalCallback mExternalCallbacks [kMaxExternalHandlers]
Events mSignaledEvents
Tasklet mTask
Static Private Attributes
static constexpr uint16_t kFlagsStringBufferSize = kFlagsStringLineLimit + kMaxFlagNameLength
static constexpr uint16_t kFlagsStringLineLimit = 70
static constexpr uint16_t kMaxExternalHandlers = OPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS
static constexpr uint8_t kMaxFlagNameLength = 25
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements the OpenThread Notifier.
For core internal modules, Notifier class emits events directly to them by invoking method HandleNotifierEvents() on the module instance.
A otStateChangedCallback callback can be explicitly registered with the Notifier. This is mainly intended for use by external users (i.e.provided as an OpenThread public API). Max number of such callbacks that can be registered at the same time is specified by OPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS configuration parameter.
Constructor & Destructor Documentation
Notifier()
Notifier (Instance & aInstance) explicit
This constructor initializes a Notifier instance.
Parameters
[in] aInstance A reference to OpenThread instance.
References Notifier::mExternalCallbacks.
Member Function Documentation
RegisterCallback()
Error RegisterCallback (otStateChangedCallback aCallback, void * aContext)
This method registers an otStateChangedCallback handler.
Parameters
[in] aCallback A pointer to the handler function that is called to notify of the changes.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Successfully registered the callback.
kErrorAlready The callback was already registered.
kErrorNoBufs Could not add the callback due to resource constraints.
References ot::kErrorAlready, ot::kErrorNoBufs, ot::kErrorNone, Notifier::ExternalCallback::mContext, Notifier::mExternalCallbacks, Notifier::ExternalCallback::mHandler, and VerifyOrExit.
RemoveCallback()
void RemoveCallback (otStateChangedCallback aCallback, void * aContext)
This method removes/unregisters a previously registered otStateChangedCallback handler.
Parameters
[in] aCallback A pointer to the callback function pointer.
[in] aContext A pointer to arbitrary context information.
References Notifier::mExternalCallbacks, and VerifyOrExit.
Signal()
void Signal (Event aEvent)
This method schedules signaling of an event.
Parameters
[in] aEvent The event to signal.
References Events::Add(), Notifier::mEventsToSignal, Notifier::mSignaledEvents, Notifier::mTask, and Tasklet::Post().
Referenced by Notifier::SignalIfFirst().
SignalIfFirst()
void SignalIfFirst (Event aEvent)
This method schedules signaling of am event only if the event has not been signaled before (first time signal).
Parameters
[in] aEvent The event to signal.
References Notifier::HasSignaled(), and Notifier::Signal().
IsPending()
bool IsPending (void) const inline
This method indicates whether or not an event signal callback is pending/scheduled.
Returns
TRUE if a callback is pending, FALSE otherwise.
HasSignaled()
bool HasSignaled (Event aEvent) const inline
This method indicates whether or not an event has been signaled before.
Parameters
[in] aEvent The event to check.
Return values
TRUE The event aEvent have been signaled before.
FALSE The event aEvent has not been signaled before.
Referenced by Notifier::SignalIfFirst().
Update()
Error Update (Type & aVariable, const Type & aNewValue, Event aEvent) inline
This template method updates a variable of a type Type with a new value and signals the given event.
If the variable is already set to the same value, this method returns kErrorAlready and the event is signaled using SignalIfFirst() (i.e., signal is scheduled only if event has not been signaled before).
The template Type should support comparison operator == and assignment operator =.
Parameters
[in,out] aVariable A reference to the variable to update.
[in] aNewValue The new value.
[in] aEvent The event to signal.
Return values
kErrorNone The variable was update successfully and aEvent was signaled.
kErrorAlready The variable was already set to the same value.
References ot::kErrorAlready, and ot::kErrorNone.
EmitEvents() [1/2]
void EmitEvents (Tasklet & aTasklet) static private
References Notifier::EmitEvents(), and GetProvider< InstanceGetProvider >::Get().
EmitEvents() [2/2]
void EmitEvents (void) private
References Events::Clear(), Notifier::EventToString(), ot::GetArrayLength(), Events::GetAsFlags(), Events::IsEmpty(), Notifier::kFlagsStringLineLimit, Notifier::LogEvents(), LogInfo, Notifier::mEventsToSignal, Notifier::mExternalCallbacks, and VerifyOrExit.
Referenced by Notifier::EmitEvents().
LogEvents()
void LogEvents (Events aEvents) const private
Referenced by Notifier::EmitEvents().
EventToString()
const char * EventToString (Event aEvent) const private
Referenced by Notifier::EmitEvents().
Field Documentation
kMaxExternalHandlers
constexpr uint16_t kMaxExternalHandlers = OPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS static private
kFlagsStringLineLimit
constexpr uint16_t kFlagsStringLineLimit = 70 static private
Referenced by Notifier::EmitEvents().
kMaxFlagNameLength
constexpr uint8_t kMaxFlagNameLength = 25 static private
kFlagsStringBufferSize
constexpr uint16_t kFlagsStringBufferSize = kFlagsStringLineLimit + kMaxFlagNameLength static private
mEventsToSignal
Events mEventsToSignal private
Referenced by Notifier::EmitEvents(), and Notifier::Signal().
mSignaledEvents
Events mSignaledEvents private
Referenced by Notifier::Signal().
mTask
Tasklet mTask private
Referenced by Notifier::Signal().
mExternalCallbacks
ExternalCallback mExternalCallbacks[kMaxExternalHandlers] private
Referenced by Notifier::EmitEvents(), Notifier::Notifier(), Notifier::RegisterCallback(), and Notifier::RemoveCallback().
The documentation for this class was generated from the following files:
notifier.hpp
notifier.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale