OpenThread: PriorityQueue Class Reference
PriorityQueue Class Reference
Core-message
#include <message.hpp>
Public Types
typedef otMessageQueueInfo Info
This struct represents info (number of messages/buffers) about a queue.
Public Member Functions
Message::Iterator begin (void)
Message::ConstIterator begin (void) const
void Dequeue (Message &aMessage)
void DequeueAndFree (Message &aMessage)
void DequeueAndFreeAll (void)
Message::Iterator end (void)
Message::ConstIterator end (void) const
void Enqueue (Message &aMessage)
Message * GetHead (void)
const Message * GetHead (void) const
Message * GetHeadForPriority (Message::Priority aPriority)
const Message * GetHeadForPriority (Message::Priority aPriority) const
void GetInfo (Info &aInfo) const
Message * GetTail (void)
const Message * GetTail (void) const
PriorityQueue (void)
Private Member Functions
const Message * FindFirstNonNullTail (Message::Priority aStartPriorityLevel) const
Message * FindFirstNonNullTail (Message::Priority aStartPriorityLevel)
uint8_t PrevPriority (uint8_t aPriority) const
Private Member Functions inherited from Clearable< PriorityQueue >
void Clear (void)
Private Attributes
Message * mTails [Message::kNumPriorities]
Friends
class Message
A TMF message.
class MessagePool
class MessageQueue
Detailed Description
This class implements a priority queue.
Member Typedef Documentation
Info
typedef otMessageQueueInfo Info
This struct represents info (number of messages/buffers) about a queue.
Constructor & Destructor Documentation
PriorityQueue()
PriorityQueue (void) inline
This constructor initializes the priority queue.
Member Function Documentation
GetHead() [1/2]
Message* GetHead (void) inline
This method returns a pointer to the first message.
Returns
A pointer to the first message.
References ot::AsConst(), ot::AsNonConst(), and PriorityQueue::GetHead().
Referenced by PriorityQueue::GetHead(), Ip6::HandleSendQueue(), MeshForwarder::PrepareNextDirectTransmission(), and MeshForwarder::ResumeMessageTransmissions().
GetHead() [2/2]
const Message* GetHead (void) const
This method returns a pointer to the first message.
Returns
A pointer to the first message.
GetHeadForPriority() [1/2]
Message* GetHeadForPriority (Message::Priority aPriority) inline
This method returns a pointer to the first message for a given priority level.
Parameters
[in] aPriority Priority level.
Returns
A pointer to the first message with given priority level or nullptr if there is no messages with this priority level.
References ot::AsConst(), and ot::AsNonConst().
GetHeadForPriority() [2/2]
const Message* GetHeadForPriority (Message::Priority aPriority) const
This method returns a pointer to the first message for a given priority level.
Parameters
[in] aPriority Priority level.
Returns
A pointer to the first message with given priority level or nullptr if there is no messages with this priority level.
Enqueue()
void Enqueue (Message & aMessage)
This method adds a message to the queue.
Parameters
[in] aMessage The message to add.
Referenced by Ip6::EnqueueDatagram().
Dequeue()
void Dequeue (Message & aMessage)
This method removes a message from the list.
Parameters
[in] aMessage The message to remove.
Referenced by Ip6::HandleSendQueue().
DequeueAndFree()
void DequeueAndFree (Message & aMessage)
This method removes a message from the queue and frees it.
Parameters
[in] aMessage The message to remove and free.
Referenced by MeshForwarder::PrepareNextDirectTransmission(), MeshForwarder::RemoveMessage(), and MeshForwarder::RemoveMessageIfNoPendingTx().
DequeueAndFreeAll()
void DequeueAndFreeAll (void)
This method removes and frees all messages from the queue.
Referenced by MeshForwarder::Stop().
GetTail() [1/2]
Message* GetTail (void) inline
This method returns the tail of the list (last message in the list).
Returns
A pointer to the tail of the list.
References ot::AsConst(), ot::AsNonConst(), and PriorityQueue::GetTail().
Referenced by PriorityQueue::GetTail().
GetTail() [2/2]
const Message* GetTail (void) const
This method returns the tail of the list (last message in the list).
Returns
A pointer to the tail of the list.
GetInfo()
void GetInfo (Info & aInfo) const
This method gets the information about number of messages and buffers in the priority queue.
This method updates aInfo array and adds number of message/buffers in the message queue to the corresponding member variable in aInfo. The caller needs to make sure aInfo is initialized before calling this method (e.g., clearing aInfo). Same aInfo can be passed in multiple calls of GetInfo(aInfo) on different queues to add up the number of messages/buffers on different queues.
Parameters
[out] aInfo A reference to an Info structure to update.
begin() [1/2]
Message::Iterator begin (void)
end() [1/2]
Message::Iterator end (void) inline
begin() [2/2]
Message::ConstIterator begin (void) const
end() [2/2]
Message::ConstIterator end (void) const inline
PrevPriority()
uint8_t PrevPriority (uint8_t aPriority) const inline private
FindFirstNonNullTail() [1/2]
const Message* FindFirstNonNullTail (Message::Priority aStartPriorityLevel) const private
FindFirstNonNullTail() [2/2]
Message* FindFirstNonNullTail (Message::Priority aStartPriorityLevel) inline private
References ot::AsConst(), and ot::AsNonConst().
Friends And Related Function Documentation
Message
friend class Message friend
A TMF message.
MessageQueue
friend class MessageQueue friend
MessagePool
friend class MessagePool friend
Field Documentation
mTails
Message* mTails[Message::kNumPriorities] private
The documentation for this class was generated from the following file:
message.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale