OpenThread: Udp Class Reference
Udp Class Reference
#include <udp.hpp>
Public Member Functions
void Deinit (void)
void Init (const char *aIfName)
void Process (const otSysMainloopContext &aContext) override
void SetUp (void)
void TearDown (void)
void Update (otSysMainloopContext &aContext) override
Static Public Member Functions
static Udp & Get (void)
Additional Inherited Members
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Member Function Documentation
Get()
static Udp& Get (void) static
Referenced by platformDeinit(), platformInit(), platformSetUp(), and platformTearDown().
Init()
void Init (const char * aIfName)
Referenced by platformInit().
SetUp()
void SetUp (void)
Referenced by platformSetUp().
TearDown()
void TearDown (void)
Referenced by platformTearDown().
Deinit()
void Deinit (void)
Referenced by platformDeinit().
Update()
void Update (otSysMainloopContext & aContext) override virtual
This method registers events in the mainloop.
Parameters
[in,out] aContext A reference to the mainloop context.
Implements Source.
Process()
void Process (const otSysMainloopContext & aContext) override virtual
This method processes the mainloop events.
Parameters
[in] aContext A reference to the mainloop context.
Implements Source.
The documentation for this class was generated from the following file:
udp.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale