OpenThread: RouteTlv Class Reference
RouteTlv Class Reference
MLE » TLVs
#include <network_diagnostic_tlvs.hpp>
Public Member Functions
uint8_t GetLinkQualityIn (uint8_t aRouterIndex) const
uint8_t GetLinkQualityOut (uint8_t aRouterIndex) const
uint8_t GetRouteCost (uint8_t aRouterIndex) const
uint8_t GetRouteDataLength (void) const
uint8_t GetRouterIdSequence (void) const
void Init (void)
bool IsRouterIdSet (uint8_t aRouterId) const
bool IsValid (void) const
void SetLinkQualityIn (uint8_t aRouterIndex, uint8_t aLinkQuality)
void SetLinkQualityOut (uint8_t aRouterIndex, uint8_t aLinkQuality)
void SetRouteCost (uint8_t aRouterIndex, uint8_t aRouteCost)
void SetRouteDataLength (uint8_t aLength)
void SetRouterId (uint8_t aRouterId)
void SetRouterIdSequence (uint8_t aSequence)
Public Member Functions inherited from NetworkDiagnosticTlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint8_t mRouteData [Mle::kMaxRouterId+1]
Mle::RouterIdSet mRouterIdMask
uint8_t mRouterIdSequence
Static Private Attributes
static constexpr uint8_t kLinkQualityInMask = 3 << kLinkQualityInOffset
static constexpr uint8_t kLinkQualityInOffset = 4
static constexpr uint8_t kLinkQualityOutMask = 3 << kLinkQualityOutOffset
static constexpr uint8_t kLinkQualityOutOffset = 6
static constexpr uint8_t kRouteCostMask = 0xf << kRouteCostOffset
static constexpr uint8_t kRouteCostOffset = 0
Additional Inherited Members
Public Types inherited from NetworkDiagnosticTlv
enum Type : uint8_t {
kExtMacAddress = OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS, kAddress16 = OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS, kMode = OT_NETWORK_DIAGNOSTIC_TLV_MODE, kTimeout = OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT,
kConnectivity = OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY, kRoute = OT_NETWORK_DIAGNOSTIC_TLV_ROUTE, kLeaderData = OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA, kNetworkData = OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA,
kIp6AddressList = OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST, kMacCounters = OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS, kBatteryLevel = OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL, kSupplyVoltage = OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE,
kChildTable = OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE, kChannelPages = OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES, kTypeList = OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST, kMaxChildTimeout = OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
}
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< NetworkDiagnosticTlv::kRoute >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements Route TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References NetworkDiagnosticTlv::kRoute, Tlv::SetLength(), and NetworkDiagnosticTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
GetRouterIdSequence()
uint8_t GetRouterIdSequence (void) const inline
This method returns the Router ID Sequence value.
Returns
The Router ID Sequence value.
SetRouterIdSequence()
void SetRouterIdSequence (uint8_t aSequence) inline
This method sets the Router ID Sequence value.
Parameters
[in] aSequence The Router ID Sequence value.
IsRouterIdSet()
bool IsRouterIdSet (uint8_t aRouterId) const inline
This method indicates whether or not a Router ID bit is set.
Parameters
[in] aRouterId The Router ID.
Return values
TRUE If the Router ID bit is set.
FALSE If the Router ID bit is not set.
SetRouterId()
void SetRouterId (uint8_t aRouterId) inline
This method sets the Router ID bit.
Parameters
[in] aRouterId The Router ID bit to set.
GetRouteDataLength()
uint8_t GetRouteDataLength (void) const inline
This method returns the Route Data Length value.
Returns
The Route Data Length value.
References Tlv::GetLength().
SetRouteDataLength()
void SetRouteDataLength (uint8_t aLength) inline
This method sets the Route Data Length value.
Parameters
[in] aLength The Route Data Length value.
References Tlv::SetLength().
GetRouteCost()
uint8_t GetRouteCost (uint8_t aRouterIndex) const inline
This method returns the Route Cost value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Route Cost value for a given Router index.
SetRouteCost()
void SetRouteCost (uint8_t aRouterIndex, uint8_t aRouteCost) inline
This method sets the Route Cost value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aRouteCost The Route Cost value.
GetLinkQualityIn()
uint8_t GetLinkQualityIn (uint8_t aRouterIndex) const inline
This method returns the Link Quality In value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Link Quality In value for a given Router index.
SetLinkQualityIn()
void SetLinkQualityIn (uint8_t aRouterIndex, uint8_t aLinkQuality) inline
This method sets the Link Quality In value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aLinkQuality The Link Quality In value for a given Router index.
GetLinkQualityOut()
uint8_t GetLinkQualityOut (uint8_t aRouterIndex) const inline
This method returns the Link Quality Out value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Link Quality Out value for a given Router index.
SetLinkQualityOut()
void SetLinkQualityOut (uint8_t aRouterIndex, uint8_t aLinkQuality) inline
This method sets the Link Quality Out value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aLinkQuality The Link Quality Out value for a given Router index.
Field Documentation
kLinkQualityOutOffset
constexpr uint8_t kLinkQualityOutOffset = 6 static private
kLinkQualityOutMask
constexpr uint8_t kLinkQualityOutMask = 3 << kLinkQualityOutOffset static private
kLinkQualityInOffset
constexpr uint8_t kLinkQualityInOffset = 4 static private
kLinkQualityInMask
constexpr uint8_t kLinkQualityInMask = 3 << kLinkQualityInOffset static private
kRouteCostOffset
constexpr uint8_t kRouteCostOffset = 0 static private
kRouteCostMask
constexpr uint8_t kRouteCostMask = 0xf << kRouteCostOffset static private
mRouterIdSequence
uint8_t mRouterIdSequence private
mRouterIdMask
Mle::RouterIdSet mRouterIdMask private
mRouteData
uint8_t mRouteData[Mle::kMaxRouterId+1] private
The documentation for this class was generated from the following file:
network_diagnostic_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale