OpenThread: Header Class Reference
Header Class Reference
Core-ip4-ip4
#include <ip4_types.hpp>
Public Member Functions
uint16_t GetChecksum (void) const
Address & GetDestination (void)
const Address & GetDestination (void) const
bool GetDf (void) const
uint8_t GetDscp (void) const
uint8_t GetDscpEcn (void) const
Ecn GetEcn (void) const
uint16_t GetFragmentOffset (void) const
uint16_t GetIdentification (void) const
bool GetMf (void) const
uint8_t GetProtocol (void) const
Address & GetSource (void)
const Address & GetSource (void) const
uint16_t GetTotalLength (void) const
uint8_t GetTtl (void) const
void InitVersionIhl (void)
bool IsValid (void) const
bool IsVersion4 (void) const
Error ParseFrom (const Message &aMessage)
void SetChecksum (uint16_t aChecksum)
void SetDestination (const Address &aDestination)
void SetDscp (uint8_t aDscp)
void SetEcn (Ecn aEcn)
void SetIdentification (uint16_t aIdentification)
void SetProtocol (uint8_t aProtocol)
void SetSource (const Address &aSource)
void SetTotalLength (uint16_t aLength)
void SetTtl (uint8_t aTtl)
void SetVersionIhl (uint8_t aVersionIhl)
Public Member Functions inherited from Clearable< Header >
void Clear (void)
Static Public Attributes
static constexpr uint8_t kDestinationAddressOffset = 16
static constexpr uint8_t kFlagsFragmentOffset = 6
static constexpr uint8_t kHeaderChecksumOffset = 10
static constexpr uint8_t kIdenficationOffset = 4
static constexpr uint8_t kProtocolOffset = 9
static constexpr uint8_t kSourceAddressOffset = 12
static constexpr uint8_t kTotalLengthOffset = 2
static constexpr uint8_t kTrafficClassOffset = 1
static constexpr uint8_t kTtlOffset = 8
static constexpr uint8_t kVersionIhlOffset = 0
Private Attributes
Address mDestination
uint8_t mDscpEcn
uint16_t mFlagsFargmentOffset
uint16_t mHeaderChecksum
uint16_t mIdentification
uint8_t mProtocol
Address mSource
uint16_t mTotalLength
uint8_t mTtl
uint8_t mVersIhl
Static Private Attributes
static constexpr uint16_t kDscpMask = 0xfc
static constexpr uint8_t kDscpOffset = 2
static constexpr uint8_t kEcnMask = 0x03
static constexpr uint8_t kEcnOffset = 0
static constexpr uint16_t kFlagsDf = 0x4000
static constexpr uint16_t kFlagsMask = 0xe000
static constexpr uint16_t kFlagsMf = 0x2000
static constexpr uint16_t kFragmentOffsetMask = 0x1fff
static constexpr uint8_t kIhlMask = 0x0f
static constexpr uint32_t kVersIhlInit = 0x45
static constexpr uint8_t kVersion4 = 0x40
static constexpr uint8_t kVersionMask = 0xf0
Detailed Description
This class implements IPv4 header generation and parsing.
Member Function Documentation
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the header appears to be well-formed.
Return values
TRUE If the header appears to be well-formed.
FALSE If the header does not appear to be well-formed.
InitVersionIhl()
void InitVersionIhl (void) inline
This method initializes the Version to 4 and sets Traffic Class and Flow fields to zero.
The other fields in the IPv4 header remain unchanged.
SetVersionIhl()
void SetVersionIhl (uint8_t aVersionIhl) inline
This method sets the version and Ihl of the IPv4 header.
Parameters
[in] aVersionIhl The octet for the version and Ihl field.
IsVersion4()
bool IsVersion4 (void) const inline
This method indicates whether or not the IPv4 Version is set to 6.
Return values
TRUE If the IPv4 Version is set to 4.
FALSE If the IPv4 Version is not set to 4.
GetDscpEcn()
uint8_t GetDscpEcn (void) const inline
This method returns the octet for DSCP + ECN.
Return values
The octet for DSCP and ECN.
GetDscp()
uint8_t GetDscp (void) const inline
This method gets the 6-bit Differentiated Services Code Point (DSCP) from Traffic Class field.
Returns
The DSCP value.
SetDscp()
void SetDscp (uint8_t aDscp) inline
This method sets 6-bit Differentiated Services Code Point (DSCP) in IPv4 header.
Parameters
[in] aDscp The DSCP value.
GetEcn()
Ecn GetEcn (void) const inline
This method gets the 2-bit Explicit Congestion Notification (ECN) from Traffic Class field.
Returns
The ECN value.
SetEcn()
void SetEcn (Ecn aEcn) inline
This method sets the 2-bit Explicit Congestion Notification (ECN) in IPv4 header..
Parameters
[in] aEcn The ECN value.
GetTotalLength()
uint16_t GetTotalLength (void) const inline
This method returns the IPv4 Payload Length value.
Returns
The IPv4 Payload Length value.
References ot::Encoding::BigEndian::HostSwap16().
SetTotalLength()
void SetTotalLength (uint16_t aLength) inline
This method sets the IPv4 Payload Length value.
Parameters
[in] aLength The IPv4 Payload Length value.
References ot::Encoding::BigEndian::HostSwap16().
GetProtocol()
uint8_t GetProtocol (void) const inline
This method returns the IPv4 payload protocol.
Returns
The IPv4 payload protocol value.
SetProtocol()
void SetProtocol (uint8_t aProtocol) inline
This method sets the IPv4 payload protocol.
Parameters
[in] aProtocol The IPv4 payload protocol.
GetChecksum()
uint16_t GetChecksum (void) const inline
This method returns the IPv4 header checksum, the checksum is in host endian.
Returns
The checksum field in the IPv4 header.
References ot::Encoding::BigEndian::HostSwap16().
SetChecksum()
void SetChecksum (uint16_t aChecksum) inline
This method sets the IPv4 header checksum, the checksum is in host endian.
Parameters
[in] aChecksum The checksum for the IPv4 header.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Checksum::UpdateIp4HeaderChecksum().
GetIdentification()
uint16_t GetIdentification (void) const inline
This method returns the IPv4 Identification value.
Returns
The IPv4 Identification value.
References ot::Encoding::BigEndian::HostSwap16().
SetIdentification()
void SetIdentification (uint16_t aIdentification) inline
This method sets the IPv4 Identification value.
Parameters
[in] aIdentification The IPv4 Identification value.
References ot::Encoding::BigEndian::HostSwap16().
GetTtl()
uint8_t GetTtl (void) const inline
This method returns the IPv4 Time-to-Live value.
Returns
The IPv4 Time-to-Live value.
SetTtl()
void SetTtl (uint8_t aTtl) inline
This method sets the IPv4 Time-to-Live value.
Parameters
[in] aTtl The IPv4 Time-to-Live value.
GetSource() [1/2]
Address& GetSource (void) inline
This method returns the IPv4 Source address.
Returns
A reference to the IPv4 Source address.
GetSource() [2/2]
const Address& GetSource (void) const inline
This method returns the IPv4 Source address.
Returns
A reference to the IPv4 Source address.
SetSource()
void SetSource (const Address & aSource) inline
This method sets the IPv4 Source address.
Parameters
[in] aSource A reference to the IPv4 Source address.
GetDestination() [1/2]
Address& GetDestination (void) inline
This method returns the IPv4 Destination address.
Returns
A reference to the IPv4 Destination address.
GetDestination() [2/2]
const Address& GetDestination (void) const inline
This method returns the IPv4 Destination address.
Returns
A reference to the IPv4 Destination address.
SetDestination()
void SetDestination (const Address & aDestination) inline
This method sets the IPv4 Destination address.
Parameters
[in] aDestination A reference to the IPv4 Destination address.
ParseFrom()
Error ParseFrom (const Message & aMessage)
This method parses and validates the IPv4 header from a given message.
The header is read from aMessage at offset zero.
Parameters
[in] aMessage The IPv4 message.
Return values
kErrorNone Successfully parsed the IPv4 header from aMessage.
kErrorParse Malformed IPv4 header or message (e.g., message does not contained expected payload length).
References Message::GetLength(), ot::kErrorNone, ot::kErrorParse, Message::Read(), SuccessOrExit, and VerifyOrExit.
GetDf()
bool GetDf (void) const inline
This method returns the Df flag in the IPv4 header.
Returns
Whether don't fragment flag is set.
References ot::Encoding::BigEndian::HostSwap16().
GetMf()
bool GetMf (void) const inline
This method returns the Mf flag in the IPv4 header.
Returns
Whether more fragments flag is set.
References ot::Encoding::BigEndian::HostSwap16().
GetFragmentOffset()
uint16_t GetFragmentOffset (void) const inline
This method returns the fragment offset in the IPv4 header.
Returns
The fragment offset of the IPv4 packet.
References ot::Encoding::BigEndian::HostSwap16().
Field Documentation
kVersionIhlOffset
constexpr uint8_t kVersionIhlOffset = 0 static
kTrafficClassOffset
constexpr uint8_t kTrafficClassOffset = 1 static
kTotalLengthOffset
constexpr uint8_t kTotalLengthOffset = 2 static
kIdenficationOffset
constexpr uint8_t kIdenficationOffset = 4 static
kFlagsFragmentOffset
constexpr uint8_t kFlagsFragmentOffset = 6 static
kTtlOffset
constexpr uint8_t kTtlOffset = 8 static
kProtocolOffset
constexpr uint8_t kProtocolOffset = 9 static
kHeaderChecksumOffset
constexpr uint8_t kHeaderChecksumOffset = 10 static
kSourceAddressOffset
constexpr uint8_t kSourceAddressOffset = 12 static
kDestinationAddressOffset
constexpr uint8_t kDestinationAddressOffset = 16 static
kVersion4
constexpr uint8_t kVersion4 = 0x40 static private
kVersionMask
constexpr uint8_t kVersionMask = 0xf0 static private
kIhlMask
constexpr uint8_t kIhlMask = 0x0f static private
kDscpOffset
constexpr uint8_t kDscpOffset = 2 static private
kDscpMask
constexpr uint16_t kDscpMask = 0xfc static private
kEcnOffset
constexpr uint8_t kEcnOffset = 0 static private
kEcnMask
constexpr uint8_t kEcnMask = 0x03 static private
kFlagsMask
constexpr uint16_t kFlagsMask = 0xe000 static private
kFlagsDf
constexpr uint16_t kFlagsDf = 0x4000 static private
kFlagsMf
constexpr uint16_t kFlagsMf = 0x2000 static private
kFragmentOffsetMask
constexpr uint16_t kFragmentOffsetMask = 0x1fff static private
kVersIhlInit
constexpr uint32_t kVersIhlInit = 0x45 static private
mVersIhl
uint8_t mVersIhl private
mDscpEcn
uint8_t mDscpEcn private
mTotalLength
uint16_t mTotalLength private
mIdentification
uint16_t mIdentification private
mFlagsFargmentOffset
uint16_t mFlagsFargmentOffset private
mTtl
uint8_t mTtl private
mProtocol
uint8_t mProtocol private
mHeaderChecksum
uint16_t mHeaderChecksum private
mSource
Address mSource private
mDestination
Address mDestination private
The documentation for this class was generated from the following files:
ip4_types.hpp
ip4_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale