OpenThread: TimeTicker Class Reference
TimeTicker Class Reference
#include <time_ticker.hpp>
Public Types
enum Receiver : uint8_t {
kMeshForwarder, kMleRouter, kAddressResolver, kChildSupervisor,
kIp6FragmentReassembler, kDuaManager, kMlrManager, kNetworkDataNotifier,
kNumReceivers
}
Public Member Functions
bool IsReceiverRegistered (Receiver aReceiver) const
void RegisterReceiver (Receiver aReceiver)
TimeTicker (Instance &aInstance)
void UnregisterReceiver (Receiver aReceiver)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void HandleTimer (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleTimer (Timer &aTimer)
static constexpr uint32_t Mask (Receiver aReceiver)
Private Attributes
uint32_t mReceivers
TimerMilli mTimer
Static Private Attributes
static constexpr uint32_t kRestartJitter = 4
static constexpr uint32_t kTickInterval = Time::kOneSecondInMsec
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class represents a time ticker.
The time ticker emits periodic ticks (with 1 second period interval) to a set of registered tick receiver modules. The tick receivers (OpenThread objects) are identified by the Receiver enumeration. The receiver objects must provide HandleTimeTick() method which would be invoked by TimeTicker periodically.
Member Enumeration Documentation
Receiver
enum Receiver : uint8_t
This enumeration represents time tick receivers.
This enumeration contains the list of all OpenThread modules that can be registered as time tick receivers.
Enumerator
kMeshForwarder
MeshForwarder
kMleRouter
Mle::MleRouter
kAddressResolver
AddressResolver
kChildSupervisor
Utils::ChildSupervisor
kIp6FragmentReassembler
Ip6::Ip6 (handling of fragmented messages)
kDuaManager
DuaManager
kMlrManager
MlrManager
kNetworkDataNotifier
NetworkData::Notifier
kNumReceivers
Number of receivers.
Constructor & Destructor Documentation
TimeTicker()
TimeTicker (Instance & aInstance) explicit
This constructor initializes the TimeTicker instance.
Member Function Documentation
RegisterReceiver()
void RegisterReceiver (Receiver aReceiver)
This method registers a receiver with TimeTicker to receive periodic ticks.
Parameters
[in] aReceiver A tick receiver identifier.
References ot::Random::NonCrypto::GetUint32InRange(), Timer::IsRunning(), TimeTicker::kTickInterval, TimeTicker::Mask(), TimeTicker::mReceivers, TimeTicker::mTimer, and TimerMilli::Start().
UnregisterReceiver()
void UnregisterReceiver (Receiver aReceiver)
This method unregisters a receiver with TimeTicker to receive periodic ticks.
Parameters
[in] aReceiver A tick receiver identifier.
References TimeTicker::Mask(), TimeTicker::mReceivers, TimeTicker::mTimer, and TimerMilli::Stop().
IsReceiverRegistered()
bool IsReceiverRegistered (Receiver aReceiver) const inline
This method indicates whether a receiver is registered with TimeTicker to receive periodic ticks.
Parameters
[in] aReceiver A tick receiver identifier.
Return values
TRUE If aReceiver is registered with TimeTicker.
FALSE If aReceiver is not registered with TimeTicker.
References TimeTicker::Mask(), and TimeTicker::mReceivers.
Mask()
static constexpr uint32_t Mask (Receiver aReceiver) inline static private
References TimeTicker::HandleTimer().
Referenced by TimeTicker::HandleTimer(), TimeTicker::IsReceiverRegistered(), TimeTicker::RegisterReceiver(), and TimeTicker::UnregisterReceiver().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and TimeTicker::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References ot::Random::NonCrypto::AddJitter(), TimerMilli::FireAt(), Timer::GetFireTime(), TimeTicker::kAddressResolver, TimeTicker::kChildSupervisor, TimeTicker::kDuaManager, TimeTicker::kIp6FragmentReassembler, TimeTicker::kMeshForwarder, TimeTicker::kMleRouter, TimeTicker::kMlrManager, TimeTicker::kNetworkDataNotifier, TimeTicker::kRestartJitter, TimeTicker::kTickInterval, TimeTicker::Mask(), TimeTicker::mReceivers, and TimeTicker::mTimer.
Referenced by TimeTicker::HandleTimer(), and TimeTicker::Mask().
Field Documentation
kTickInterval
constexpr uint32_t kTickInterval = Time::kOneSecondInMsec static private
Referenced by TimeTicker::HandleTimer(), and TimeTicker::RegisterReceiver().
kRestartJitter
constexpr uint32_t kRestartJitter = 4 static private
Referenced by TimeTicker::HandleTimer().
mReceivers
uint32_t mReceivers private
Referenced by TimeTicker::HandleTimer(), TimeTicker::IsReceiverRegistered(), TimeTicker::RegisterReceiver(), and TimeTicker::UnregisterReceiver().
mTimer
TimerMilli mTimer private
Referenced by TimeTicker::HandleTimer(), TimeTicker::RegisterReceiver(), and TimeTicker::UnregisterReceiver().
The documentation for this class was generated from the following files:
time_ticker.hpp
time_ticker.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale