OpenThread: TimerMilli Class Reference
TimerMilli Class Reference
Core-timer
#include <timer.hpp>
Data Structures
class Scheduler
Public Member Functions
void FireAt (TimeMilli aFireTime)
void FireAtIfEarlier (TimeMilli aFireTime)
void Start (uint32_t aDelay)
void StartAt (TimeMilli aStartTime, uint32_t aDelay)
void Stop (void)
TimerMilli (Instance &aInstance, Handler aHandler)
Public Member Functions inherited from Timer
Time GetFireTime (void) const
bool IsRunning (void) const
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Public Member Functions inherited from LinkedListEntry< Timer >
const Timer * GetNext (void) const
Timer * GetNext (void)
void SetNext (Timer *aNext)
Static Public Member Functions
static TimeMilli GetNow (void)
Static Protected Member Functions
static void RemoveAll (Instance &aInstance)
Additional Inherited Members
Public Types inherited from Timer
typedef void(&) Handler(Timer &aTimer)
Static Public Attributes inherited from Timer
static const uint32_t kMaxDelay = (Time::kMaxDuration >> 1)
Protected Member Functions inherited from Timer
bool DoesFireBefore (const Timer &aSecondTimer, Time aNow) const
void Fired (void)
Timer (Instance &aInstance, Handler aHandler)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Protected Attributes inherited from Timer
Time mFireTime
Handler mHandler
Timer * mNext
Detailed Description
This class implements the millisecond timer.
Constructor & Destructor Documentation
TimerMilli()
TimerMilli (Instance & aInstance, Handler aHandler) inline
This constructor creates a millisecond timer instance.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aHandler A pointer to a function that is called when the timer expires.
Member Function Documentation
Start()
void Start (uint32_t aDelay)
This method schedules the timer to fire after a given delay (in milliseconds) from now.
Parameters
[in] aDelay The delay in milliseconds. It must not be longer than kMaxDelay.
Referenced by Mle::Attach(), Mle::DetachGracefully(), SubMac::EnergyScan(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), DiscoverScanner::HandleDiscoveryRequestFrameTxDone(), DatasetManager::HandleMgmtSetResponse(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), Mpl::HandleSeedSetTimer(), TrickleTimer::HandleTimer(), AnnounceSenderBase::HandleTimer(), Mac::HandleTransmitDone(), SubMac::HandleTransmitStarted(), Mac::PerformNextOperation(), TimeTicker::RegisterReceiver(), DatasetManager::Save(), Mle::ScheduleMessageTransmissionTimer(), AnnounceSenderBase::SendAnnounce(), DatasetManager::SendSet(), Interpreter::SetCommandTimeout(), Mle::SetStateChild(), KeyManager::StartKeyRotationTimer(), TrickleTimer::StartNewInterval(), SubMac::StartTimerForBackoff(), Mac::UpdateIdleMode(), and Mpl::UpdateSeedSet().
StartAt()
void StartAt (TimeMilli aStartTime, uint32_t aDelay)
This method schedules the timer to fire after a given delay (in milliseconds) from a given start time.
Parameters
[in] aStartTime The start time.
[in] aDelay The delay in milliseconds. It must not be longer than kMaxDelay.
References Timer::kMaxDelay, and OT_ASSERT.
Referenced by PendingDatasetManager::HandleDelayTimer(), KeyManager::HandleKeyRotationTimer(), DataPollSender::ResetKeepAliveTimer(), SubMac::SampleRssi(), DataPollSender::ScheduleNextPoll(), SubMac::StartCsmaBackoff(), and PendingDatasetManager::StartDelayTimer().
FireAt()
void FireAt (TimeMilli aFireTime)
This method schedules the timer to fire at a given fire time.
Parameters
[in] aFireTime The fire time.
References Timer::mFireTime.
Referenced by Mle::HandleDelayedResponseTimer(), CoapBase::HandleRetransmissionTimer(), TimeTicker::HandleTimer(), ResponsesQueue::HandleTimer(), and Mac::UpdateIdleMode().
FireAtIfEarlier()
void FireAtIfEarlier (TimeMilli aFireTime)
This method (re-)schedules the timer with a given a fire time only if the timer is not running or the new given fire time is earlier than the current fire time.
Parameters
[in] aFireTime The fire time.
References Timer::IsRunning(), and Timer::mFireTime.
Referenced by CoapBase::CopyAndEnqueueMessage(), ResponsesQueue::EnqueueResponse(), and Mle::TxMessage::SendAfterDelay().
Stop()
void Stop (void)
This method stops the timer.
Referenced by DatasetManager::Clear(), PendingDatasetManager::Clear(), CoapBase::DequeueMessage(), SubMac::Disable(), DiscoverScanner::HandleDiscoverComplete(), EnergyScanServer::HandleNotifierEvents(), Mac::HandleReceivedFrame(), SubMac::HandleTransmitDone(), SubMac::Init(), Interpreter::OutputResult(), Mac::PerformNextOperation(), DatasetManager::Restore(), Mle::ScheduleMessageTransmissionTimer(), DataPollSender::SendDataPoll(), Mac::SetRxOnWhenIdle(), Mle::SetStateDetached(), PendingDatasetManager::StartDelayTimer(), Mac::StartOperation(), AnnounceSenderBase::Stop(), TrickleTimer::Stop(), KeyManager::Stop(), Mle::Stop(), DataPollSender::StopPolling(), and TimeTicker::UnregisterReceiver().
GetNow()
static TimeMilli GetNow (void) inline static
This static method returns the current time in milliseconds.
Returns
The current time in milliseconds.
References otPlatAlarmMilliGetNow(), and Timer::Scheduler::RemoveAll().
Referenced by Dataset::AppendMleDatasetTlv(), Mle::CheckReachability(), SubMac::EnergyScan(), ResponsesQueue::EnqueueResponse(), AddressResolver::HandleAddressError(), Mle::HandleAdvertisement(), Mle::HandleDelayedResponseTimer(), Ip6::HandleOptions(), Mac::HandleReceivedFrame(), CoapBase::HandleRetransmissionTimer(), Mpl::HandleSeedSetTimer(), ResponsesQueue::HandleTimer(), Mac::LogFrameTxFailure(), Neighbor::MatchesFilter(), Mac::PerformNextOperation(), DatasetLocal::Read(), Dataset::ReadFromMessage(), Mac::RequestDirectFrameTransmission(), DataPollSender::ResetKeepAliveTimer(), MeshForwarder::ResumeMessageTransmissions(), SubMac::SampleRssi(), DatasetLocal::Save(), DataPollSender::ScheduleNextPoll(), Mle::TxMessage::SendAfterDelay(), CoapBase::SendMessage(), Neighbor::Info::SetFrom(), Dataset::SetFrom(), Router::Info::SetFrom(), Dataset::SetTlv(), Neighbor::StateToString(), and MeshForwarder::UpdateReassemblyList().
RemoveAll()
void RemoveAll (Instance & aInstance) static protected
References Instance::Get().
The documentation for this class was generated from the following files:
timer.hpp
timer.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale