OpenThread: Time Class Reference
Time Class Reference
Core-timer
#include <time.hpp>
Public Member Functions
Time GetDistantFuture (void) const
Time GetDistantPast (void) const
uint32_t GetValue (void) const
Time operator+ (uint32_t aDuration) const
void operator+= (uint32_t aDuration)
uint32_t operator- (const Time &aOther) const
Time operator- (uint32_t aDuration) const
void operator-= (uint32_t aDuration)
bool operator< (const Time &aOther) const
bool operator<= (const Time &aOther) const
bool operator== (const Time &aOther) const
bool operator> (const Time &aOther) const
bool operator>= (const Time &aOther) const
void SetValue (uint32_t aValue)
Time (void)=default
Time (uint32_t aValue)
Public Member Functions inherited from Unequatable< Time >
bool operator!= (const Time &aOther) const
Static Public Member Functions
static uint32_t constexpr MsecToSec (uint32_t aMilliseconds)
static uint32_t constexpr SecToMsec (uint32_t aSeconds)
Static Public Attributes
static const uint32_t kMaxDuration = ~static_cast<uint32_t>(0UL)
static constexpr uint32_t kOneDayInMsec = kOneHourInMsec * 24
One day interval in msec.
static constexpr uint32_t kOneHourInMsec = kOneMinuteInMsec * 60
One hour interval in msec.
static constexpr uint32_t kOneMinuteInMsec = kOneSecondInMsec * 60
One minute interval in msec.
static constexpr uint32_t kOneSecondInMsec = 1000u
One second interval in msec.
Private Attributes
uint32_t mValue
Static Private Attributes
static constexpr uint32_t kDistantFuture = (1UL << 31)
Detailed Description
This class represents a time instance.
Constructor & Destructor Documentation
Time() [1/2]
Time (void) default
This is the default constructor for a Time object.
Referenced by Time::GetDistantFuture(), Time::GetDistantPast(), Time::operator+(), and Time::operator-().
Time() [2/2]
Time (uint32_t aValue) inline explicit
This constructor initializes a Time object with a given value.
Parameters
[in] aValue The numeric time value to initialize the Time object.
References Time::SetValue().
Member Function Documentation
GetValue()
uint32_t GetValue (void) const inline
This method gets the numeric time value associated with the Time object.
Returns
The numeric Time value.
References Time::mValue.
SetValue()
void SetValue (uint32_t aValue) inline
This method sets the numeric time value.
Parameters
[in] aValue The numeric time value.
References Time::mValue.
Referenced by Time::Time().
operator-() [1/2]
uint32_t operator- (const Time & aOther) const inline
This method calculates the time duration between two Time instances.
Note
Expression (t1 - t2) returns the duration of the interval starting from t2 and ending at t1. When calculating the duration, t2 is assumed to be in the past relative tot1. The duration calculation correctly takes into account the wrapping of numeric value ofTimeinstances. The returned value can span the entire range of theuint32_t` type.
Parameters
[in] aOther A Time instance to subtract from.
Returns
The duration of interval from aOther to this Time object.
References Time::mValue.
operator+()
Time operator+ (uint32_t aDuration) const inline
This method returns a new Time which is ahead of this Time object by a given duration.
Parameters
[in] aDuration A duration.
Returns
A new Time which is ahead of this object by .
References Time::mValue, and Time::Time().
operator-() [2/2]
Time operator- (uint32_t aDuration) const inline
This method returns a new Time which is behind this Time object by a given duration.
Parameters
[in] aDuration A duration.
Returns
A new Time which is behind this object by .
References Time::mValue, and Time::Time().
operator+=()
void operator+= (uint32_t aDuration) inline
This method moves this Time object forward by a given duration.
Parameters
[in] aDuration A duration.
References Time::mValue.
operator-=()
void operator-= (uint32_t aDuration) inline
This method moves this Time object backward by a given duration.
Parameters
[in] aDuration A duration.
References Time::mValue.
operator==()
bool operator== (const Time & aOther) const inline
This method indicates whether two Time instances are equal.
Parameters
[in] aOther A Time instance to compare with.
Return values
TRUE The two Time instances are equal.
FALSE The two Time instances are not equal.
References Time::mValue.
operator<()
bool operator< (const Time & aOther) const inline
This method indicates whether this Time instance is strictly before another one.
Note
The comparison operators correctly take into account the wrapping of Time numeric value. For a given Time instance t0, any Time instance t where (t - t0) is less than half the range of uint32_t type is considered to be after t0, otherwise it is considered to be before 't0' (or equal to it). As an example to illustrate this model we can use clock hours: If we are at hour 12, hours 1 to 5 are considered to be after 12, and hours 6 to 11 are considered to be before 12.
Parameters
[in] aOther A Time instance to compare with.
Return values
TRUE This Time instance is strictly before aOther.
FALSE This Time instance is not strictly before aOther.
References SerialNumber::IsLess(), and Time::mValue.
operator>=()
bool operator>= (const Time & aOther) const inline
This method indicates whether this Time instance is after or equal to another one.
Parameters
[in] aOther A Time instance to compare with.
Return values
TRUE This Time instance is after or equal to aOther.
FALSE This Time instance is not after or equal to aOther.
operator<=()
bool operator<= (const Time & aOther) const inline
This method indicates whether this Time instance is before or equal to another one.
Parameters
[in] aOther A Time instance to compare with.
Return values
TRUE This Time instance is before or equal to aOther.
FALSE This Time instance is not before or equal to aOther.
operator>()
bool operator> (const Time & aOther) const inline
This method indicates whether this Time instance is strictly after another one.
Parameters
[in] aOther A Time instance to compare with.
Return values
TRUE This Time instance is strictly after aOther.
FALSE This Time instance is not strictly after aOther.
GetDistantFuture()
Time GetDistantFuture (void) const inline
This method returns a new Time instance which is in distant future relative to current Time object.
The returned distance future Time is guaranteed to be equal or after (as defined by comparison operator <=) any other Time which is after this Time object, i.e., for any t for which we have *this <= t, it is ensured that t <= this->GetGetDistantFuture().
Returns
A new Time in distance future relative to current Time object.
References Time::kDistantFuture, Time::mValue, and Time::Time().
Referenced by Mle::HandleDelayedResponseTimer(), CoapBase::HandleRetransmissionTimer(), Mpl::HandleSeedSetTimer(), and ResponsesQueue::HandleTimer().
GetDistantPast()
Time GetDistantPast (void) const inline
This method returns a new Time instance which is in distant past relative to current Time object.
The returned distance past Time is guaranteed to be equal or before (as defined by comparison operator >=) any other Time which is before this Time object, i.e., for any t for which we have *this >= t, it is ensured that t >= this->GetDistantPast().
Returns
A new Time in distance past relative to current Time object.
References Time::kDistantFuture, Time::mValue, and Time::Time().
SecToMsec()
static uint32_t constexpr SecToMsec (uint32_t aSeconds) inline static
This static method converts a given number of seconds to milliseconds.
Parameters
[in] aSeconds The seconds value to convert to milliseconds.
Returns
The number of milliseconds.
Referenced by DataPollSender::GetDefaultPollPeriod(), Ip6::HandleOptions(), Mle::ScheduleMessageTransmissionTimer(), and MeshForwarder::UpdateReassemblyList().
MsecToSec()
static uint32_t constexpr MsecToSec (uint32_t aMilliseconds) inline static
This static method converts a given number of milliseconds to seconds.
Parameters
[in] aMilliseconds The milliseconds value to convert to seconds.
Returns
The number of seconds.
Referenced by AddressResolver::HandleAddressError(), Neighbor::Info::SetFrom(), Router::Info::SetFrom(), and Neighbor::StateToString().
Field Documentation
kOneSecondInMsec
constexpr uint32_t kOneSecondInMsec = 1000u static
One second interval in msec.
kOneMinuteInMsec
constexpr uint32_t kOneMinuteInMsec = kOneSecondInMsec * 60 static
One minute interval in msec.
kOneHourInMsec
constexpr uint32_t kOneHourInMsec = kOneMinuteInMsec * 60 static
One hour interval in msec.
kOneDayInMsec
constexpr uint32_t kOneDayInMsec = kOneHourInMsec * 24 static
One day interval in msec.
kMaxDuration
const uint32_t kMaxDuration = ~static_cast<uint32_t>(0UL) static
This constant defines a maximum time duration ensured to be longer than any other duration.
kDistantFuture
constexpr uint32_t kDistantFuture = (1UL << 31) static private
Referenced by Time::GetDistantFuture(), and Time::GetDistantPast().
mValue
uint32_t mValue private
Referenced by Time::GetDistantFuture(), Time::GetDistantPast(), Time::GetValue(), Time::operator+(), Time::operator+=(), Time::operator-(), Time::operator-=(), Time::operator<(), Time::operator==(), and Time::SetValue().
The documentation for this class was generated from the following file:
time.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale