OpenThread: TxFrame Class Reference
TxFrame Class Reference
Core-mac
#include <mac_frame.hpp>
Public Member Functions
void CopyFrom (const TxFrame &aFromFrame)
Error GenerateEnhAck (const RxFrame &aFrame, bool aIsFramePending, const uint8_t *aIeData, uint8_t aIeLength)
void GenerateImmAck (const RxFrame &aFrame, bool aIsFramePending)
const Mac::KeyMaterial & GetAesKey (void) const
uint8_t GetMaxCsmaBackoffs (void) const
uint8_t GetMaxFrameRetries (void) const
bool IsARetransmission (void) const
bool IsCsmaCaEnabled (void) const
bool IsHeaderUpdated (void) const
bool IsSecurityProcessed (void) const
void ProcessTransmitAesCcm (const ExtAddress &aExtAddress)
void SetAesKey (const Mac::KeyMaterial &aAesKey)
void SetCsmaCaEnabled (bool aCsmaCaEnabled)
void SetIsARetransmission (bool aIsARetx)
void SetIsHeaderUpdated (bool aIsHeaderUpdated)
void SetIsSecurityProcessed (bool aIsSecurityProcessed)
void SetMaxCsmaBackoffs (uint8_t aMaxCsmaBackoffs)
void SetMaxFrameRetries (uint8_t aMaxFrameRetries)
void SetTxDelay (uint32_t aTxDelay)
void SetTxDelayBaseTime (uint32_t aTxDelayBaseTime)
Public Member Functions inherited from Frame
bool GetAckRequest (void) const
uint8_t GetChannel (void) const
Error GetCommandId (uint8_t &aCommandId) const
Error GetDstAddr (Address &aAddress) const
Error GetDstPanId (PanId &aPanId) const
uint8_t GetFcsSize (void) const
uint8_t * GetFooter (void)
const uint8_t * GetFooter (void) const
uint8_t GetFooterLength (void) const
uint16_t GetFrameControlField (void) const
Error GetFrameCounter (uint32_t &aFrameCounter) const
bool GetFramePending (void) const
uint8_t * GetHeader (void)
const uint8_t * GetHeader (void) const
uint8_t GetHeaderLength (void) const
Error GetKeyId (uint8_t &aKeyId) const
Error GetKeyIdMode (uint8_t &aKeyIdMode) const
const uint8_t * GetKeySource (void) const
uint16_t GetLength (void) const
uint16_t GetMaxPayloadLength (void) const
uint16_t GetMtu (void) const
uint8_t * GetPayload (void)
const uint8_t * GetPayload (void) const
uint16_t GetPayloadLength (void) const
uint8_t * GetPsdu (void)
const uint8_t * GetPsdu (void) const
uint16_t GetPsduLength (void) const
Error GetSecurityControlField (uint8_t &aSecurityControlField) const
bool GetSecurityEnabled (void) const
Error GetSecurityLevel (uint8_t &aSecurityLevel) const
uint8_t GetSequence (void) const
Error GetSrcAddr (Address &aAddress) const
Error GetSrcPanId (PanId &aPanId) const
uint8_t GetType (void) const
uint16_t GetVersion (void) const
void InitMacHeader (uint16_t aFcf, uint8_t aSecurityControl)
bool IsAck (void) const
bool IsDataRequestCommand (void) const
bool IsDstAddrPresent () const
bool IsDstPanIdPresent (void) const
bool IsEmpty (void) const
bool IsIePresent (void) const
bool IsPanIdCompressed (void) const
bool IsSrcAddrPresent (void) const
bool IsSrcPanIdPresent (void) const
bool IsVersion2015 (void) const
void SetAckRequest (bool aAckRequest)
void SetChannel (uint8_t aChannel)
Error SetCommandId (uint8_t aCommandId)
void SetDstAddr (ShortAddress aShortAddress)
void SetDstAddr (const ExtAddress &aExtAddress)
void SetDstAddr (const Address &aAddress)
void SetDstPanId (PanId aPanId)
void SetFrameCounter (uint32_t aFrameCounter)
void SetFramePending (bool aFramePending)
void SetKeyId (uint8_t aKeyId)
void SetKeySource (const uint8_t *aKeySource)
void SetLength (uint16_t aLength)
void SetPayloadLength (uint16_t aLength)
void SetSecurityControlField (uint8_t aSecurityControlField)
void SetSequence (uint8_t aSequence)
void SetSrcAddr (ShortAddress aShortAddress)
void SetSrcAddr (const ExtAddress &aExtAddress)
void SetSrcAddr (const Address &aAddress)
Error SetSrcPanId (PanId aPanId)
InfoString ToInfoString (void) const
Error ValidatePsdu (void) const
Additional Inherited Members
Public Types inherited from Frame
typedef String< kInfoStringSize > InfoString
Data Fields inherited from otRadioFrame
uint8_t mChannel
Channel used to transmit/receive the frame.
union {
struct {
bool mAckedWithFramePending: 1
This indicates if this frame was acknowledged with frame pending set.
bool mAckedWithSecEnhAck: 1
This indicates if this frame was acknowledged with secured enhance ACK.
uint32_t mAckFrameCounter
ACK security frame counter (applicable when mAckedWithSecEnhAck is set).
uint8_t mAckKeyId
ACK security key index (applicable when mAckedWithSecEnhAck is set).
uint8_t mLqi
Link Quality Indicator for received frames.
int8_t mRssi
Received signal strength indicator in dBm for received frames.
uint64_t mTimestamp
} mRxInfo
struct {
const otMacKeyMaterial * mAesKey
The key material used for AES-CCM frame security.
bool mCslPresent: 1
Set to true if CSL header IE is present.
bool mCsmaCaEnabled: 1
Set to true to enable CSMA-CA for this packet, false otherwise.
otRadioIeInfo * mIeInfo
The pointer to the Header IE(s) related information.
bool mIsARetx: 1
Indicates whether the frame is a retransmission or not.
bool mIsHeaderUpdated: 1
bool mIsSecurityProcessed: 1
True if SubMac should skip the AES processing of this frame.
uint8_t mMaxCsmaBackoffs
Maximum number of backoffs attempts before declaring CCA failure.
uint8_t mMaxFrameRetries
Maximum number of retries allowed after a transmission failure.
uint32_t mTxDelay
The delay time for this transmission (based on mTxDelayBaseTime).
uint32_t mTxDelayBaseTime
The base time for the transmission delay.
} mTxInfo
} mInfo
uint16_t mLength
Length of the PSDU.
uint8_t * mPsdu
The PSDU.
uint8_t mRadioType
Radio link type - should be ignored by radio driver.
Static Public Attributes inherited from Frame
static constexpr uint8_t k154FcsSize = sizeof(uint16_t)
static constexpr uint8_t kCommandIdSize = sizeof(uint8_t)
static constexpr uint8_t kDsnSize = sizeof(uint8_t)
static constexpr uint16_t kFcfAckRequest = 1 << 5
static constexpr uint16_t kFcfDstAddrExt = 3 << 10
static constexpr uint16_t kFcfDstAddrMask = 3 << 10
static constexpr uint16_t kFcfDstAddrNone = 0 << 10
static constexpr uint16_t kFcfDstAddrShort = 2 << 10
static constexpr uint16_t kFcfFrameAck = 2 << 0
static constexpr uint16_t kFcfFrameBeacon = 0 << 0
static constexpr uint16_t kFcfFrameData = 1 << 0
static constexpr uint16_t kFcfFrameMacCmd = 3 << 0
static constexpr uint16_t kFcfFramePending = 1 << 4
static constexpr uint16_t kFcfFrameTypeMask = 7 << 0
static constexpr uint16_t kFcfFrameVersion2006 = 1 << 12
static constexpr uint16_t kFcfFrameVersion2015 = 2 << 12
static constexpr uint16_t kFcfFrameVersionMask = 3 << 12
static constexpr uint16_t kFcfIePresent = 1 << 9
static constexpr uint16_t kFcfPanidCompression = 1 << 6
static constexpr uint16_t kFcfSecurityEnabled = 1 << 3
static constexpr uint8_t kFcfSize = sizeof(uint16_t)
static constexpr uint16_t kFcfSrcAddrExt = 3 << 14
static constexpr uint16_t kFcfSrcAddrMask = 3 << 14
static constexpr uint16_t kFcfSrcAddrNone = 0 << 14
static constexpr uint16_t kFcfSrcAddrShort = 2 << 14
static constexpr uint8_t kFrameCounterSize = sizeof(uint32_t)
static constexpr uint8_t kImmAckLength = kFcfSize + kDsnSize + k154FcsSize
static constexpr uint16_t kInfoStringSize = 128
Max chars for InfoString (ToInfoString()).
static constexpr uint8_t kKeyIdMode0 = 0 << 3
static constexpr uint8_t kKeyIdMode1 = 1 << 3
static constexpr uint8_t kKeyIdMode2 = 2 << 3
static constexpr uint8_t kKeyIdMode3 = 3 << 3
static constexpr uint8_t kKeyIdModeMask = 3 << 3
static constexpr uint8_t kKeyIndexSize = sizeof(uint8_t)
static constexpr uint8_t kKeySourceSizeMode0 = 0
static constexpr uint8_t kKeySourceSizeMode1 = 0
static constexpr uint8_t kKeySourceSizeMode2 = 4
static constexpr uint8_t kKeySourceSizeMode3 = 8
static constexpr uint8_t kMacCmdAssociationRequest = 1
static constexpr uint8_t kMacCmdAssociationResponse = 2
static constexpr uint8_t kMacCmdBeaconRequest = 7
static constexpr uint8_t kMacCmdCoordinatorRealignment = 8
static constexpr uint8_t kMacCmdDataRequest = 4
static constexpr uint8_t kMacCmdDisassociationNotification = 3
static constexpr uint8_t kMacCmdGtsRequest = 9
static constexpr uint8_t kMacCmdOrphanNotification = 6
static constexpr uint8_t kMacCmdPanidConflictNotification = 5
static constexpr uint8_t kMaxMicSize = kMic128Size
static constexpr uint8_t kMic0Size = 0
static constexpr uint8_t kMic128Size = 128 / CHAR_BIT
static constexpr uint8_t kMic32Size = 32 / CHAR_BIT
static constexpr uint8_t kMic64Size = 64 / CHAR_BIT
static constexpr uint8_t kSecEnc = 4 << 0
static constexpr uint8_t kSecEncMic128 = 7 << 0
static constexpr uint8_t kSecEncMic32 = 5 << 0
static constexpr uint8_t kSecEncMic64 = 6 << 0
static constexpr uint8_t kSecLevelMask = 7 << 0
static constexpr uint8_t kSecMic128 = 3 << 0
static constexpr uint8_t kSecMic32 = 1 << 0
static constexpr uint8_t kSecMic64 = 2 << 0
static constexpr uint8_t kSecNone = 0 << 0
static constexpr uint8_t kSecurityControlSize = sizeof(uint8_t)
Protected Member Functions inherited from Frame
uint8_t FindDstAddrIndex (void) const
uint8_t FindDstPanIdIndex (void) const
uint8_t FindPayloadIndex (void) const
uint8_t FindSecurityHeaderIndex (void) const
uint8_t FindSrcAddrIndex (void) const
uint8_t FindSrcPanIdIndex (void) const
uint8_t SkipAddrFieldIndex (void) const
uint8_t SkipSecurityHeaderIndex (void) const
Static Protected Member Functions inherited from Frame
static uint8_t CalculateAddrFieldSize (uint16_t aFcf)
static uint8_t CalculateMicSize (uint8_t aSecurityControl)
static uint8_t CalculateSecurityHeaderSize (uint8_t aSecurityControl)
static uint8_t GetKeySourceLength (uint8_t aKeyIdMode)
static bool IsDstAddrPresent (uint16_t aFcf)
static bool IsDstPanIdPresent (uint16_t aFcf)
static bool IsSrcAddrPresent (uint16_t aFcf)
static bool IsSrcPanIdPresent (uint16_t aFcf)
static bool IsVersion2015 (uint16_t aFcf)
Static Protected Attributes inherited from Frame
static constexpr uint8_t kInvalidIndex = 0xff
static constexpr uint8_t kInvalidSize = kInvalidIndex
static constexpr uint8_t kMaxPsduSize = kInvalidSize - 1
static constexpr uint8_t kSequenceIndex = kFcfSize
Detailed Description
This class supports IEEE 802.15.4 MAC frame generation for transmission.
Member Function Documentation
GetMaxCsmaBackoffs()
uint8_t GetMaxCsmaBackoffs (void) const inline
This method returns the maximum number of backoffs the CSMA-CA algorithm will attempt before declaring a channel access failure.
Equivalent to macMaxCSMABackoffs in IEEE 802.15.4-2006.
Returns
The maximum number of backoffs the CSMA-CA algorithm will attempt before declaring a channel access failure.
Referenced by SubMac::HandleTransmitDone().
SetMaxCsmaBackoffs()
void SetMaxCsmaBackoffs (uint8_t aMaxCsmaBackoffs) inline
This method sets the maximum number of backoffs the CSMA-CA algorithm will attempt before declaring a channel access failure.
Equivalent to macMaxCSMABackoffs in IEEE 802.15.4-2006.
Parameters
[in] aMaxCsmaBackoffs The maximum number of backoffs the CSMA-CA algorithm will attempt before declaring a channel access failure.
Referenced by Mac::BeginTransmit().
GetMaxFrameRetries()
uint8_t GetMaxFrameRetries (void) const inline
This method returns the maximum number of retries allowed after a transmission failure.
Equivalent to macMaxFrameRetries in IEEE 802.15.4-2006.
Returns
The maximum number of retries allowed after a transmission failure.
Referenced by SubMac::HandleTransmitDone(), and Mac::SetPromiscuous().
SetMaxFrameRetries()
void SetMaxFrameRetries (uint8_t aMaxFrameRetries) inline
This method sets the maximum number of retries allowed after a transmission failure.
Equivalent to macMaxFrameRetries in IEEE 802.15.4-2006.
Parameters
[in] aMaxFrameRetries The maximum number of retries allowed after a transmission failure.
Referenced by Mac::BeginTransmit().
IsARetransmission()
bool IsARetransmission (void) const inline
This method indicates whether or not the frame is a retransmission.
Return values
TRUE Frame is a retransmission
FALSE This is a new frame and not a retransmission of an earlier frame.
Referenced by Mac::BeginTransmit().
SetIsARetransmission()
void SetIsARetransmission (bool aIsARetx) inline
This method sets the retransmission flag attribute.
Parameters
[in] aIsARetx TRUE if frame is a retransmission of an earlier frame, FALSE otherwise.
Referenced by MeshForwarder::HandleFrameRequest(), and SubMac::HandleTransmitDone().
IsCsmaCaEnabled()
bool IsCsmaCaEnabled (void) const inline
This method indicates whether or not CSMA-CA is enabled.
Return values
TRUE CSMA-CA is enabled.
FALSE CSMA-CA is not enabled is not enabled.
Referenced by SubMac::HandleTransmitDone().
SetCsmaCaEnabled()
void SetCsmaCaEnabled (bool aCsmaCaEnabled) inline
This method sets the CSMA-CA enabled attribute.
Parameters
[in] aCsmaCaEnabled TRUE if CSMA-CA must be enabled for this packet, FALSE otherwise.
GetAesKey()
const Mac::KeyMaterial& GetAesKey (void) const inline
This method returns the key used for frame encryption and authentication (AES CCM).
Returns
The pointer to the key.
SetAesKey()
void SetAesKey (const Mac::KeyMaterial & aAesKey) inline
This method sets the key used for frame encryption and authentication (AES CCM).
Parameters
[in] aAesKey The pointer to the key.
Referenced by SubMac::ProcessTransmitSecurity(), and Mac::ProcessTransmitSecurity().
CopyFrom()
void CopyFrom (const TxFrame & aFromFrame)
This method copies the PSDU and all attributes (except for frame link type) from another frame.
Note
This method performs a deep copy meaning the content of PSDU buffer from the given frame is copied into the PSDU buffer of the current frame.
Parameters
[in] aFromFrame The frame to copy from.
References Frame::GetFcsSize(), Frame::GetPsduLength(), otRadioFrame::mInfo, otRadioFrame::mLength, otRadioFrame::mPsdu, otRadioFrame::mTxInfo, and HeaderIe::SetLength().
Referenced by Mac::BeginTransmit().
ProcessTransmitAesCcm()
void ProcessTransmitAesCcm (const ExtAddress & aExtAddress)
This method performs AES CCM on the frame which is going to be sent.
Parameters
[in] aExtAddress A reference to the extended address, which will be used to generate nonce for AES CCM computation.
References AesCcm::Finalize(), AesCcm::GenerateNonce(), AesCcm::Header(), AesCcm::Init(), AesCcm::kEncrypt, AesCcm::kNonceSize, OT_UNUSED_VARIABLE, AesCcm::Payload(), AesCcm::SetKey(), SuccessOrExit, and VerifyOrExit.
Referenced by SubMac::ProcessTransmitSecurity(), and Mac::ProcessTransmitSecurity().
IsSecurityProcessed()
bool IsSecurityProcessed (void) const inline
This method indicates whether or not the frame has security processed.
Return values
TRUE The frame already has security processed.
FALSE The frame does not have security processed.
Referenced by Mac::BeginTransmit(), and SubMac::ProcessTransmitSecurity().
SetIsSecurityProcessed()
void SetIsSecurityProcessed (bool aIsSecurityProcessed) inline
This method sets the security processed flag attribute.
Parameters
[in] aIsSecurityProcessed TRUE if the frame already has security processed.
IsHeaderUpdated()
bool IsHeaderUpdated (void) const inline
This method indicates whether or not the frame header is updated.
Return values
TRUE The frame already has the header updated.
FALSE The frame does not have the header updated.
Referenced by SubMac::ProcessTransmitSecurity(), Mac::ProcessTransmitSecurity(), and SubMac::SignalFrameCounterUsedOnTxDone().
SetIsHeaderUpdated()
void SetIsHeaderUpdated (bool aIsHeaderUpdated) inline
This method sets the header updated flag attribute.
Parameters
[in] aIsHeaderUpdated TRUE if the frame header is updated.
GenerateImmAck()
void GenerateImmAck (const RxFrame & aFrame, bool aIsFramePending)
Generate Imm-Ack in this frame object.
Parameters
[in] aFrame A reference to the frame received.
[in] aIsFramePending Value of the ACK's frame pending bit.
References Frame::GetSequence(), Frame::GetVersion(), otRadioFrame::mChannel, and ot::Encoding::BigEndian::WriteUint16().
GenerateEnhAck()
Error GenerateEnhAck (const RxFrame & aFrame, bool aIsFramePending, const uint8_t * aIeData, uint8_t aIeLength)
Generate Enh-Ack in this frame object.
Parameters
[in] aFrame A reference to the frame received.
[in] aIsFramePending Value of the ACK's frame pending bit.
[in] aIeData A pointer to the IE data portion of the ACK to be sent.
[in] aIeLength The length of IE data portion of the ACK to be sent.
Return values
kErrorNone Successfully generated Enh Ack.
kErrorParse aFrame has incorrect format.
References ExitNow, Frame::GetDstPanId(), Frame::GetFrameControlField(), Frame::GetKeyId(), Frame::GetSecurityControlField(), Frame::GetSecurityEnabled(), Frame::GetSequence(), Frame::GetSrcAddr(), Frame::GetSrcPanId(), Frame::IsDstPanIdPresent(), Frame::IsPanIdCompressed(), Frame::IsSrcAddrPresent(), Frame::IsSrcPanIdPresent(), ot::kErrorNone, ot::kErrorParse, otRadioFrame::mChannel, OT_ASSERT, SuccessOrExit, and ot::Encoding::BigEndian::WriteUint16().
SetTxDelay()
void SetTxDelay (uint32_t aTxDelay) inline
Set TX delay field for the frame.
Parameters
[in] aTxDelay The delay time for the TX frame.
SetTxDelayBaseTime()
void SetTxDelayBaseTime (uint32_t aTxDelayBaseTime) inline
Set TX delay base time field for the frame.
Parameters
[in] aTxDelayBaseTime The delay base time for the TX frame.
References OT_TOOL_PACKED_BEGIN.
The documentation for this class was generated from the following files:
mac_frame.hpp
mac_frame.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale