OpenThread: SockAddr Class Reference
SockAddr Class Reference
Core-ipv6 » IPv6
#include <socket.hpp>
Public Types
typedef String< kInfoStringSize > InfoString
Public Member Functions
Address & GetAddress (void)
const Address & GetAddress (void) const
uint16_t GetPort (void) const
bool operator== (const SockAddr &aOther) const
void SetAddress (const Address &aAddress)
void SetPort (uint16_t aPort)
SockAddr (void)
SockAddr (uint16_t aPort)
SockAddr (const Address &aAddress, uint16_t aPort)
InfoString ToString (void) const
void ToString (char *aBuffer, uint16_t aSize) const
Public Member Functions inherited from Clearable< SockAddr >
void Clear (void)
Public Member Functions inherited from Unequatable< SockAddr >
bool operator!= (const SockAddr &aOther) const
Static Public Attributes
static constexpr uint16_t kInfoStringSize = OT_IP6_SOCK_ADDR_STRING_SIZE
Info string size (ToString()).
Private Member Functions
void ToString (StringWriter &aWriter) const
Additional Inherited Members
Data Fields inherited from otSockAddr
otIp6Address mAddress
An IPv6 address.
uint16_t mPort
A transport-layer port.
Detailed Description
This class implements a socket address.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Constructor & Destructor Documentation
SockAddr() [1/3]
SockAddr (void) inline
This constructor initializes the socket address (all fields are set to zero).
References Clearable< MessageInfo >::Clear().
SockAddr() [2/3]
SockAddr (uint16_t aPort) inline explicit
This constructor initializes the socket address with a given port number.
Parameters
[in] aPort A port number.
SockAddr() [3/3]
SockAddr (const Address & aAddress, uint16_t aPort) inline
This constructor initializes the socket address with a given address and port number.
Parameters
[in] aAddress An IPv6 address.
[in] aPort A port number.
Member Function Documentation
GetAddress() [1/2]
Address& GetAddress (void) inline
This method returns a reference to the IPv6 address.
Returns
A reference to the IPv6 address.
References ot::AsCoreType().
Referenced by Udp::Bind(), Manager::GetNextDnsSrpUnicastInfo(), Udp::SocketHandle::Matches(), SockAddr::operator==(), Udp::SendTo(), and SockAddr::ToString().
GetAddress() [2/2]
const Address& GetAddress (void) const inline
This method returns a reference to the IPv6 address.
Returns
A reference to the IPv6 address.
References ot::AsCoreType().
SetAddress()
void SetAddress (const Address & aAddress) inline
This method sets the IPv6 address.
Parameters
[in] aAddress The IPv6 address.
Referenced by Manager::GetNextDnsSrpUnicastInfo().
GetPort()
uint16_t GetPort (void) const inline
This method returns the socket address port number.
Returns
The port number
Referenced by SockAddr::operator==(), and SockAddr::ToString().
SetPort()
void SetPort (uint16_t aPort) inline
This method sets the socket address port number.
Parameters
[in] aPort The port number.
Referenced by Manager::GetNextDnsSrpUnicastInfo().
operator==()
bool operator== (const SockAddr & aOther) const inline
This method overloads operator == to evaluate whether or not two SockAddr instances are equal (same address and port number).
Parameters
[in] aOther The other SockAddr instance to compare with.
Return values
TRUE If the two SockAddr instances are equal.
FALSE If the two SockAddr instances not equal.
References ot::DefineCoreType(), SockAddr::GetAddress(), and SockAddr::GetPort().
ToString() [1/3]
SockAddr::InfoString ToString (void) const
This method converts the socket address to a string.
The string is formatted as "[<ipv6 address>]:<port number>".
Returns
An InfoString containing the string representation of the SockAddr
Referenced by SockAddr::ToString().
ToString() [2/3]
void ToString (char * aBuffer, uint16_t aSize) const
This method converts a given IPv6 socket address to a human-readable string.
The IPv6 socket address string is formatted as "[<ipv6 address>]:<port>".
If the resulting string does not fit in aBuffer (within its aSize characters), the string will be truncated but the outputted string is always null-terminated.
Parameters
[out] aBuffer A pointer to a char array to output the string (MUST NOT be NULL).
[in] aSize The size of aBuffer (in bytes).
References SockAddr::ToString().
ToString() [3/3]
void ToString (StringWriter & aWriter) const private
References StringWriter::Append(), SockAddr::GetAddress(), SockAddr::GetPort(), and SockAddr::ToString().
Field Documentation
kInfoStringSize
constexpr uint16_t kInfoStringSize = OT_IP6_SOCK_ADDR_STRING_SIZE static
Info string size (ToString()).
The documentation for this class was generated from the following files:
socket.hpp
socket.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale