OpenThread: KeyMaterial Class Reference
KeyMaterial Class Reference
Core-mac
#include <mac_types.hpp>
Public Member Functions
void Clear (void)
void ConvertToCryptoKey (Crypto::Key &aCryptoKey) const
void ExtractKey (Key &aKey)
const Key & GetKey (void) const
KeyMaterial (void)
bool operator== (const KeyMaterial &aOther) const
void SetFrom (const Key &aKey, bool aIsExportable=false)
Public Member Functions inherited from Unequatable< KeyMaterial >
bool operator!= (const KeyMaterial &aOther) const
Private Member Functions
Key & GetKey (void)
void SetKey (const Key &aKey)
Additional Inherited Members
Data Fields inherited from otMacKeyMaterial
union {
otMacKey mKey
Key stored as literal.
otMacKeyRef mKeyRef
Reference to the key stored.
} mKeyMaterial
Detailed Description
This class represents a MAC Key Material.
Constructor & Destructor Documentation
KeyMaterial()
KeyMaterial (void) inline
This constructor initializes a KeyMaterial.
References Clearable< ExtAddress >::Clear().
Member Function Documentation
Clear()
void Clear (void)
This method clears the KeyMaterial.
Under OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE, if the KeyMaterial currently stores a valid previous KeyRef, the Clear() call will ensure to delete the previous KeyRef and set it to kInvalidKeyRef.
Referenced by SubMac::Init().
GetKey() [1/2]
const Key& GetKey (void) const inline
This method gets the literal Key.
Returns
The literal Key
References Equatable< ExtAddress >::operator==().
Referenced by KeyMaterial::operator==().
SetFrom()
void SetFrom (const Key & aKey, bool aIsExportable = false)
This method sets the KeyMaterial from a given Key.
If the KeyMaterial currently stores a valid KeyRef, the SetFrom() call will ensure to delete the previous one before creating and using a new KeyRef associated with the new Key.
Parameters
[in] aKey A reference to the new key.
[in] aIsExportable Boolean indicating if the key is exportable (this is only applicable under OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE config).
References Key::GetBytes(), Key::kSize, OT_UNUSED_VARIABLE, and SuccessOrAssert.
Referenced by KeyManager::GetTemporaryMleKey(), Mac::Mac(), KeyManager::SetKek(), and KeyManager::UpdateKeyMaterial().
ExtractKey()
void ExtractKey (Key & aKey)
This method extracts the literal key from KeyMaterial
Parameters
[out] aKey A reference to the output the key.
References Clearable< Type >::Clear(), Key::kSize, otMacKey::m8, and SuccessOrAssert.
ConvertToCryptoKey()
void ConvertToCryptoKey (Crypto::Key & aCryptoKey) const
This method converts KeyMaterial to a Crypto::Key.
Parameters
[out] aCryptoKey A reference to a Crypto::Key to populate.
References Key::kSize, and Key::Set().
Referenced by AesCcm::SetKey().
operator==()
bool operator== (const KeyMaterial & aOther) const
This method overloads operator == to evaluate whether or not two KeyMaterial instances are equal.
Parameters
[in] aOther The other KeyMaterial instance to compare with.
Return values
TRUE If the two KeyMaterial instances are equal.
FALSE If the two KeyMaterial instances are not equal.
References KeyMaterial::GetKey().
GetKey() [2/2]
Key& GetKey (void) inline private
SetKey()
void SetKey (const Key & aKey) inline private
References Clearable< ExtAddress >::Clear(), ExtAddress::kInfoStringSize, OPENTHREAD_CONFIG_RADIO_LINK_IEEE_802_15_4_ENABLE, OPENTHREAD_CONFIG_RADIO_LINK_TREL_ENABLE, and ExtAddress::ToString().
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale