OpenThread: Header Class Reference
Header Class Reference
Core-dns
#include <dns_types.hpp>
Public Types
enum QueryType : uint8_t {
kQueryTypeStandard = 0, kQueryTypeInverse = 1, kQueryTypeStatus = 2, kQueryTypeNotify = 4,
kQueryTypeUpdate = 5, kQueryTypeDso = 6
}
enum Response : uint8_t {
kResponseSuccess = 0, kResponseFormatError = 1, kResponseServerFailure = 2, kResponseNameError = 3,
kResponseNotImplemented = 4, kResponseRefused = 5, kResponseNameExists = 6, kResponseRecordExists = 7,
kResponseRecordNotExists = 8, kResponseNotAuth = 9, kResponseNotZone = 10, kDsoTypeNotImplemented = 11,
kResponseBadName = 20, kResponseBadAlg = 21, kResponseBadTruncation = 22
}
enum Type : uint8_t { kTypeQuery = 0, kTypeResponse = 1 }
Public Member Functions
void ClearAuthoritativeAnswerFlag (void)
void ClearRecursionAvailableFlag (void)
void ClearRecursionDesiredFlag (void)
void ClearTruncationFlag (void)
uint16_t GetAdditionalRecordCount (void) const
uint16_t GetAnswerCount (void) const
uint16_t GetAuthorityRecordCount (void) const
uint16_t GetMessageId (void) const
QueryType GetQueryType (void) const
uint16_t GetQuestionCount (void) const
Response GetResponseCode (void) const
Type GetType (void) const
Header (void)
bool IsAuthoritativeAnswerFlagSet (void) const
bool IsRecursionAvailableFlagSet (void) const
bool IsRecursionDesiredFlagSet (void) const
bool IsTruncationFlagSet (void) const
void SetAdditionalRecordCount (uint16_t aCount)
void SetAnswerCount (uint16_t aCount)
void SetAuthoritativeAnswerFlag (void)
void SetAuthorityRecordCount (uint16_t aCount)
void SetMessageId (uint16_t aMessageId)
void SetQueryType (QueryType aType)
void SetQuestionCount (uint16_t aCount)
Error SetRandomMessageId (void)
void SetRecursionAvailableFlag (void)
void SetRecursionDesiredFlag (void)
void SetResponseCode (Response aResponse)
void SetTruncationFlag (void)
void SetType (Type aType)
Public Member Functions inherited from Clearable< Header >
void Clear (void)
Static Public Member Functions
static Error ResponseCodeToError (Response aResponse)
Private Attributes
uint16_t mAnCount
uint16_t mArCount
uint8_t mFlags [2]
uint16_t mMessageId
uint16_t mNsCount
uint16_t mQdCount
Static Private Attributes
static constexpr uint8_t kAaFlagMask = 0x01 << kAaFlagOffset
static constexpr uint8_t kAaFlagOffset = 2
static constexpr uint8_t kOpCodeMask = 0x0f << kOpCodeOffset
static constexpr uint8_t kOpCodeOffset = 3
static constexpr uint8_t kQrFlagMask = 0x01 << kQrFlagOffset
static constexpr uint8_t kQrFlagOffset = 7
static constexpr uint8_t kRaFlagMask = 0x01 << kRaFlagOffset
static constexpr uint8_t kRaFlagOffset = 7
static constexpr uint8_t kRCodeMask = 0x0f << kRCodeOffset
static constexpr uint8_t kRCodeOffset = 0
static constexpr uint8_t kRdFlagMask = 0x01 << kRdFlagOffset
static constexpr uint8_t kRdFlagOffset = 0
static constexpr uint8_t kTcFlagMask = 0x01 << kTcFlagOffset
static constexpr uint8_t kTcFlagOffset = 1
Detailed Description
This class implements DNS header generation and parsing.
Member Enumeration Documentation
Type
enum Type : uint8_t
Defines types of DNS message.
Enumerator
kTypeQuery
kTypeResponse
QueryType
enum QueryType : uint8_t
Defines types of query.
Enumerator
kQueryTypeStandard
kQueryTypeInverse
kQueryTypeStatus
kQueryTypeNotify
kQueryTypeUpdate
kQueryTypeDso
Response
enum Response : uint8_t
Defines response codes.
Enumerator
kResponseSuccess
Success (no error condition).
kResponseFormatError
Server unable to interpret request due to format error.
kResponseServerFailure
Server encountered an internal failure.
kResponseNameError
Name that ought to exist, does not exists.
kResponseNotImplemented
Server does not support the query type (OpCode).
kResponseRefused
Server refused to perform operation for policy or security reasons.
kResponseNameExists
Some name that ought not to exist, does exist.
kResponseRecordExists
Some RRset that ought not to exist, does exist.
kResponseRecordNotExists
Some RRset that ought to exist, does not exist.
kResponseNotAuth
Service is not authoritative for zone.
kResponseNotZone
A name is not in the zone.
kDsoTypeNotImplemented
DSO TLV TYPE is not implemented.
kResponseBadName
Bad name.
kResponseBadAlg
Bad algorithm.
kResponseBadTruncation
Bad truncation.
Constructor & Destructor Documentation
Header()
Header (void) inline
Default constructor for DNS Header.
References Clearable< Header >::Clear().
Member Function Documentation
GetMessageId()
uint16_t GetMessageId (void) const inline
This method returns the Message ID.
Returns
The Message ID value.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mMessageId.
SetMessageId()
void SetMessageId (uint16_t aMessageId) inline
This method sets the Message ID.
Parameters
[in] aMessageId The Message ID value.
References ot::Encoding::BigEndian::HostSwap16(), Header::mMessageId, and Header::SetRandomMessageId().
SetRandomMessageId()
Error SetRandomMessageId (void)
This method sets the Message ID to a crypto-secure randomly generated number.
Return values
kErrorNone Successfully generated random Message ID.
kErrorFailed Could not generate random Message ID.
References ot::Random::Crypto::FillBuffer(), and Header::mMessageId.
Referenced by Header::SetMessageId().
GetType()
Type GetType (void) const inline
This method returns the type of the message.
Returns
The type of the message.
References Header::kQrFlagMask, Header::kQrFlagOffset, and Header::mFlags.
Referenced by AaaaRecord::IsValid(), KeyRecord::IsValid(), and SigRecord::IsValid().
SetType()
void SetType (Type aType) inline
This method sets the type of the message.
Parameters
[in] aType The type of the message.
References Header::kQrFlagMask, Header::kQrFlagOffset, and Header::mFlags.
Referenced by ResourceRecord::Init(), OptRecord::Init(), and Question::Question().
GetQueryType()
QueryType GetQueryType (void) const inline
This method returns the type of the query.
Returns
The type of the query.
References Header::kOpCodeMask, Header::kOpCodeOffset, and Header::mFlags.
SetQueryType()
void SetQueryType (QueryType aType) inline
This method sets the type of the query.
Parameters
[in] aType The type of the query.
References Header::kOpCodeMask, Header::kOpCodeOffset, and Header::mFlags.
Referenced by UpdateHeader::UpdateHeader().
IsAuthoritativeAnswerFlagSet()
bool IsAuthoritativeAnswerFlagSet (void) const inline
This method specifies in response message if the responding name server is an authority for the domain name in question section.
Returns
True if Authoritative Answer flag (AA) is set in the header, false otherwise.
References Header::kAaFlagMask, and Header::mFlags.
ClearAuthoritativeAnswerFlag()
void ClearAuthoritativeAnswerFlag (void) inline
This method clears the Authoritative Answer flag (AA) in the header.
References Header::kAaFlagMask, and Header::mFlags.
SetAuthoritativeAnswerFlag()
void SetAuthoritativeAnswerFlag (void) inline
This method sets the Authoritative Answer flag (AA) in the header.
References Header::kAaFlagMask, and Header::mFlags.
IsTruncationFlagSet()
bool IsTruncationFlagSet (void) const inline
This method specifies if message is truncated.
Returns
True if Truncation flag (TC) is set in the header, false otherwise.
References Header::kTcFlagMask, and Header::mFlags.
ClearTruncationFlag()
void ClearTruncationFlag (void) inline
This method clears the Truncation flag (TC) in the header.
References Header::kTcFlagMask, and Header::mFlags.
SetTruncationFlag()
void SetTruncationFlag (void) inline
This method sets the Truncation flag (TC) in the header.
References Header::kTcFlagMask, and Header::mFlags.
IsRecursionDesiredFlagSet()
bool IsRecursionDesiredFlagSet (void) const inline
This method specifies if resolver wants to direct the name server to pursue the query recursively.
Returns
True if Recursion Desired flag (RD) is set in the header, false otherwise.
References Header::kRdFlagMask, and Header::mFlags.
ClearRecursionDesiredFlag()
void ClearRecursionDesiredFlag (void) inline
This method clears the Recursion Desired flag (RD) in the header.
References Header::kRdFlagMask, and Header::mFlags.
SetRecursionDesiredFlag()
void SetRecursionDesiredFlag (void) inline
This method sets the Recursion Desired flag (RD) in the header.
References Header::kRdFlagMask, and Header::mFlags.
IsRecursionAvailableFlagSet()
bool IsRecursionAvailableFlagSet (void) const inline
This method denotes whether recursive query support is available in the name server.
Returns
True if Recursion Available flag (RA) is set in the header, false otherwise.
References Header::kRaFlagMask, and Header::mFlags.
ClearRecursionAvailableFlag()
void ClearRecursionAvailableFlag (void) inline
This method clears the Recursion Available flag (RA) in the header.
References Header::kRaFlagMask, and Header::mFlags.
SetRecursionAvailableFlag()
void SetRecursionAvailableFlag (void) inline
This method sets the Recursion Available flag (RA) in the header.
References Header::kRaFlagMask, and Header::mFlags.
GetResponseCode()
Response GetResponseCode (void) const inline
This method returns the response code.
Returns
The response code from the header.
References Header::kRCodeMask, Header::kRCodeOffset, and Header::mFlags.
SetResponseCode()
void SetResponseCode (Response aResponse) inline
This method sets the response code.
Parameters
[in] aResponse The type of the response.
References Header::kRCodeMask, Header::kRCodeOffset, Header::mFlags, and Header::ResponseCodeToError().
ResponseCodeToError()
Error ResponseCodeToError (Response aResponse) static
This method converts a Response Code into a related Error.
kResponseSuccess (0) : Success (no error condition) -> kErrorNone
kResponseFormatError (1) : Server unable to interpret due to format error -> kErrorParse
kResponseServerFailure (2) : Server encountered an internal failure -> kErrorFailed
kResponseNameError (3) : Name that ought to exist, does not exists -> kErrorNotFound
kResponseNotImplemented (4) : Server does not support the query type (OpCode) -> kErrorNotImplemented
kResponseRefused (5) : Server refused for policy/security reasons -> kErrorSecurity
kResponseNameExists (6) : Some name that ought not to exist, does exist -> kErrorDuplicated
kResponseRecordExists (7) : Some RRset that ought not to exist, does exist -> kErrorDuplicated
kResponseRecordNotExists (8) : Some RRset that ought to exist, does not exist -> kErrorNotFound
kResponseNotAuth (9) : Service is not authoritative for zone -> kErrorSecurity
kResponseNotZone (10) : A name is not in the zone -> kErrorParse
kDsoTypeNotImplemented (11) : DSO TLV Type is not implemented -> kErrorNotImplemented
kResponseBadName (20) : Bad name -> kErrorParse
kResponseBadAlg (21) : Bad algorithm -> kErrorSecurity
kResponseBadTruncation (22) : Bad truncation -> kErrorParse
Other error -> kErrorFailed
Parameters
[in] aResponse The response code to convert.
References Header::kDsoTypeNotImplemented, ot::kErrorDuplicated, ot::kErrorFailed, ot::kErrorNone, ot::kErrorNotCapable, ot::kErrorNotFound, ot::kErrorNotImplemented, ot::kErrorParse, ot::kErrorSecurity, Header::kResponseBadAlg, Header::kResponseBadName, Header::kResponseBadTruncation, Header::kResponseFormatError, Header::kResponseNameError, Header::kResponseNameExists, Header::kResponseNotAuth, Header::kResponseNotImplemented, Header::kResponseNotZone, Header::kResponseRecordExists, Header::kResponseRecordNotExists, Header::kResponseRefused, Header::kResponseServerFailure, and Header::kResponseSuccess.
Referenced by Header::SetResponseCode().
GetQuestionCount()
uint16_t GetQuestionCount (void) const inline
This method returns the number of entries in question section.
Returns
The number of entries in question section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mQdCount.
Referenced by UpdateHeader::GetZoneRecordCount().
SetQuestionCount()
void SetQuestionCount (uint16_t aCount) inline
This method sets the number of entries in question section.
Parameters
[in] aCount The number of entries in question section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mQdCount.
Referenced by UpdateHeader::SetZoneRecordCount().
GetAnswerCount()
uint16_t GetAnswerCount (void) const inline
This method returns the number of entries in answer section.
Returns
The number of entries in answer section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mAnCount.
Referenced by UpdateHeader::GetPrerequisiteRecordCount().
SetAnswerCount()
void SetAnswerCount (uint16_t aCount) inline
This method sets the number of entries in answer section.
Parameters
[in] aCount The number of entries in answer section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mAnCount.
Referenced by UpdateHeader::SetPrerequisiteRecordCount().
GetAuthorityRecordCount()
uint16_t GetAuthorityRecordCount (void) const inline
This method returns the number of entries in authority records section.
Returns
The number of entries in authority records section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mNsCount.
Referenced by UpdateHeader::GetUpdateRecordCount().
SetAuthorityRecordCount()
void SetAuthorityRecordCount (uint16_t aCount) inline
This method sets the number of entries in authority records section.
Parameters
[in] aCount The number of entries in authority records section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mNsCount.
Referenced by UpdateHeader::SetUpdateRecordCount().
GetAdditionalRecordCount()
uint16_t GetAdditionalRecordCount (void) const inline
This method returns the number of entries in additional records section.
Returns
The number of entries in additional records section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mArCount.
SetAdditionalRecordCount()
void SetAdditionalRecordCount (uint16_t aCount) inline
This method sets the number of entries in additional records section.
Parameters
[in] aCount The number of entries in additional records section.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mArCount.
Field Documentation
kQrFlagOffset
constexpr uint8_t kQrFlagOffset = 7 static private
Referenced by Header::GetType(), and Header::SetType().
kQrFlagMask
constexpr uint8_t kQrFlagMask = 0x01 << kQrFlagOffset static private
Referenced by Header::GetType(), and Header::SetType().
kOpCodeOffset
constexpr uint8_t kOpCodeOffset = 3 static private
Referenced by Header::GetQueryType(), and Header::SetQueryType().
kOpCodeMask
constexpr uint8_t kOpCodeMask = 0x0f << kOpCodeOffset static private
Referenced by Header::GetQueryType(), and Header::SetQueryType().
kAaFlagOffset
constexpr uint8_t kAaFlagOffset = 2 static private
kAaFlagMask
constexpr uint8_t kAaFlagMask = 0x01 << kAaFlagOffset static private
Referenced by Header::ClearAuthoritativeAnswerFlag(), Header::IsAuthoritativeAnswerFlagSet(), and Header::SetAuthoritativeAnswerFlag().
kTcFlagOffset
constexpr uint8_t kTcFlagOffset = 1 static private
kTcFlagMask
constexpr uint8_t kTcFlagMask = 0x01 << kTcFlagOffset static private
Referenced by Header::ClearTruncationFlag(), Header::IsTruncationFlagSet(), and Header::SetTruncationFlag().
kRdFlagOffset
constexpr uint8_t kRdFlagOffset = 0 static private
kRdFlagMask
constexpr uint8_t kRdFlagMask = 0x01 << kRdFlagOffset static private
Referenced by Header::ClearRecursionDesiredFlag(), Header::IsRecursionDesiredFlagSet(), and Header::SetRecursionDesiredFlag().
kRaFlagOffset
constexpr uint8_t kRaFlagOffset = 7 static private
kRaFlagMask
constexpr uint8_t kRaFlagMask = 0x01 << kRaFlagOffset static private
Referenced by Header::ClearRecursionAvailableFlag(), Header::IsRecursionAvailableFlagSet(), and Header::SetRecursionAvailableFlag().
kRCodeOffset
constexpr uint8_t kRCodeOffset = 0 static private
Referenced by Header::GetResponseCode(), and Header::SetResponseCode().
kRCodeMask
constexpr uint8_t kRCodeMask = 0x0f << kRCodeOffset static private
Referenced by Header::GetResponseCode(), and Header::SetResponseCode().
mMessageId
uint16_t mMessageId private
Referenced by Header::GetMessageId(), Header::SetMessageId(), and Header::SetRandomMessageId().
mFlags
uint8_t mFlags[2] private
Referenced by Header::ClearAuthoritativeAnswerFlag(), Header::ClearRecursionAvailableFlag(), Header::ClearRecursionDesiredFlag(), Header::ClearTruncationFlag(), KeyRecord::GetOwnerFlags(), Header::GetQueryType(), Header::GetResponseCode(), KeyRecord::GetSignatoryFlags(), Header::GetType(), KeyRecord::GetUseFlags(), Header::IsAuthoritativeAnswerFlagSet(), Header::IsRecursionAvailableFlagSet(), Header::IsRecursionDesiredFlagSet(), Header::IsTruncationFlagSet(), Header::SetAuthoritativeAnswerFlag(), KeyRecord::SetFlags(), Header::SetQueryType(), Header::SetRecursionAvailableFlag(), Header::SetRecursionDesiredFlag(), Header::SetResponseCode(), Header::SetTruncationFlag(), and Header::SetType().
mQdCount
uint16_t mQdCount private
Referenced by Header::GetQuestionCount(), and Header::SetQuestionCount().
mAnCount
uint16_t mAnCount private
Referenced by Header::GetAnswerCount(), and Header::SetAnswerCount().
mNsCount
uint16_t mNsCount private
Referenced by Header::GetAuthorityRecordCount(), and Header::SetAuthorityRecordCount().
mArCount
uint16_t mArCount private
Referenced by Header::GetAdditionalRecordCount(), and Header::SetAdditionalRecordCount().
The documentation for this class was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale