OpenThread: Decoder Class Reference
Decoder Class Reference
#include <hdlc.hpp>
Public Types
typedef void(* FrameHandler) (void *aContext, otError aError)
Public Member Functions
void Decode (const uint8_t *aData, uint16_t aLength)
Decoder (FrameWritePointer &aFrameWritePointer, FrameHandler aFrameHandler, void *aContext)
void Reset (void)
Private Types
enum State { kStateNoSync, kStateSync, kStateEscaped }
Private Attributes
void * mContext
uint16_t mDecodedLength
uint16_t mFcs
FrameHandler mFrameHandler
State mState
FrameWritePointer & mWritePointer
Detailed Description
This class implements the HDLC-lite decoder.
Member Typedef Documentation
FrameHandler
typedef void(* FrameHandler) (void *aContext, otError aError)
This function pointer is called when either a complete frame has been decoded or an error occurs during decoding.
The decoded frame (or the partially decoded frame in case of an error) is available in aFrameWritePointer buffer given in Decoder constructor.
Parameters
[in] aContext A pointer to arbitrary context information.
[in] aError OT_ERROR_NONE if the frame was decoded successfully, OT_ERROR_PARSE if the Frame Check Sequence (FCS) was incorrect in decoded frame, OT_ERROR_NO_BUFS insufficient buffer space available to save the decoded frame.
Member Enumeration Documentation
State
enum State private
Enumerator
kStateNoSync
kStateSync
kStateEscaped
Constructor & Destructor Documentation
Decoder()
Decoder (FrameWritePointer & aFrameWritePointer, FrameHandler aFrameHandler, void * aContext)
This constructor initializes the decoder.
Parameters
[in] aFrameWritePointer The FrameWritePointer used by Decoder to write the decoded frames.
[in] aFrameHandler The frame handler callback function pointer.
[in] aContext A pointer to arbitrary context information.
Member Function Documentation
Decode()
void Decode (const uint8_t * aData, uint16_t aLength)
This method feeds a block of data into the decoder.
If during decoding, a full HDLC frame is successfully decoded or an error occurs, the FrameHandler callback is called. The decoded frame (or the partially decoded frame in case of an error) is available in aFrameWritePointer buffer from the constructor. The Decoder user (if required) must update/reset the write pointer from this callback for the next frame to be decoded.
Parameters
[in] aData A pointer to a buffer containing data to be fed to decoder.
[in] aLength The number of bytes in aData.
References FrameWritePointer::CanWrite(), IgnoreError(), ot::Hdlc::kEscapeSequence, ot::Hdlc::kFcsSize, ot::Hdlc::kFlagSequence, ot::Hdlc::kGoodFcs, ot::Hdlc::kInitFcs, Decoder::kStateEscaped, Decoder::kStateNoSync, Decoder::kStateSync, Decoder::mContext, Decoder::mDecodedLength, Decoder::mFcs, Decoder::mFrameHandler, Decoder::mState, Decoder::mWritePointer, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_PARSE, FrameWritePointer::UndoLastWrites(), ot::Hdlc::UpdateFcs(), and FrameWritePointer::WriteByte().
Referenced by HdlcInterface::Read(), and HdlcInterface::WaitForFrame().
Reset()
void Reset (void)
This method resets internal states of the decoder.
References Decoder::kStateNoSync, Decoder::mDecodedLength, Decoder::mFcs, and Decoder::mState.
Field Documentation
mState
State mState private
Referenced by Decoder::Decode(), and Decoder::Reset().
mWritePointer
FrameWritePointer& mWritePointer private
Referenced by Decoder::Decode().
mFrameHandler
FrameHandler mFrameHandler private
Referenced by Decoder::Decode().
mContext
void* mContext private
Referenced by Decoder::Decode().
mFcs
uint16_t mFcs private
Referenced by Decoder::Decode(), and Decoder::Reset().
mDecodedLength
uint16_t mDecodedLength private
Referenced by Decoder::Decode(), and Decoder::Reset().
The documentation for this class was generated from the following files:
hdlc.hpp
hdlc.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale