OpenThread: Message Class Reference
Message Class Reference
Core-coap
#include <coap_message.hpp>
Data Structures
class ConstIterator
struct Header
struct HelpData
class Iterator
Public Types
enum BlockType : uint8_t { kBlockType1 = 1, kBlockType2 = 2 }
typedef ot::Coap::Code Code
CoAP Code.
typedef ot::Coap::Type Type
CoAP Type.
Public Types inherited from Message
enum LinkSecurityMode : bool { kNoLinkSecurity = false, kWithLinkSecurity = true }
enum Ownership : uint8_t { kTakeCustody, kCopyToUse }
enum Priority : uint8_t { kPriorityLow = OT_MESSAGE_PRIORITY_LOW, kPriorityNormal = OT_MESSAGE_PRIORITY_NORMAL, kPriorityHigh = OT_MESSAGE_PRIORITY_HIGH, kPriorityNet = OT_MESSAGE_PRIORITY_HIGH + 1 }
enum SubType : uint8_t {
kSubTypeNone = 0, kSubTypeMleAnnounce = 1, kSubTypeMleDiscoverRequest = 2, kSubTypeMleDiscoverResponse = 3,
kSubTypeJoinerEntrust = 4, kSubTypeMplRetransmission = 5, kSubTypeMleGeneral = 6, kSubTypeJoinerFinalizeResponse = 7,
kSubTypeMleChildUpdateRequest = 8, kSubTypeMleDataResponse = 9, kSubTypeMleChildIdRequest = 10, kSubTypeMleDataRequest = 11
}
enum Type : uint8_t {
kTypeIp6 = 0, kType6lowpan = 1, kTypeSupervision = 2, kTypeMacEmptyData = 3,
kTypeIp4 = 4, kTypeOther = 5
}
Public Member Functions
Error AppendBlockOption (BlockType aType, uint32_t aNum, bool aMore, otCoapBlockSzx aSize)
Error AppendContentFormatOption (otCoapOptionContentFormat aContentFormat)
Error AppendMaxAgeOption (uint32_t aMaxAge)
Error AppendObserveOption (uint32_t aObserve)
Error AppendOption (uint16_t aNumber, uint16_t aLength, const void *aValue)
Error AppendProxyUriOption (const char *aProxyUri)
Error AppendStringOption (uint16_t aNumber, const char *aValue)
Error AppendUintOption (uint16_t aNumber, uint32_t aValue)
Error AppendUriPathOptions (const char *aUriPath)
Error AppendUriQueryOption (const char *aUriQuery)
Message * Clone (uint16_t aLength) const
Message * Clone (void) const
void Finish (void)
Error GenerateRandomToken (uint8_t aTokenLength)
uint8_t GetCode (void) const
uint16_t GetMessageId (void) const
Message * GetNextCoapMessage (void)
const Message * GetNextCoapMessage (void) const
uint16_t GetOptionStart (void) const
const uint8_t * GetToken (void) const
uint8_t GetTokenLength (void) const
uint8_t GetType (void) const
Error GetUriPath (char *aUriPath) const
uint8_t GetVersion (void) const
void Init (void)
void Init (Type aType, Code aCode)
Error Init (Type aType, Code aCode, const char *aUriPath)
Error InitAsPost (const Ip6::Address &aDestination, const char *aUriPath)
bool IsAck (void) const
bool IsConfirmable (void) const
bool IsConfirmablePostRequest (void) const
bool IsDeleteRequest (void) const
bool IsEmpty (void) const
bool IsGetRequest (void) const
bool IsNonConfirmable (void) const
bool IsNonConfirmablePostRequest (void) const
bool IsPostRequest (void) const
bool IsPutRequest (void) const
bool IsRequest (void) const
bool IsReset (void) const
bool IsResponse (void) const
bool IsTokenEqual (const Message &aMessage) const
Error ParseHeader (void)
Error ReadUriPathOptions (char(&aUriPath)[kMaxReceivedUriPath+1]) const
void SetCode (Code aCode)
Error SetDefaultResponseHeader (const Message &aRequest)
void SetMessageId (uint16_t aMessageId)
Error SetPayloadMarker (void)
Error SetToken (const uint8_t *aToken, uint8_t aTokenLength)
Error SetTokenFromMessage (const Message &aMessage)
void SetType (Type aType)
void SetVersion (uint8_t aVersion)
Public Member Functions inherited from Message
void AddRss (int8_t aRss)
template<typename ObjectType >
Error Append (const ObjectType &aObject)
Error AppendBytes (const void *aBuf, uint16_t aLength)
Error AppendBytesFromMessage (const Message &aMessage, uint16_t aOffset, uint16_t aLength)
template<DataLengthType kDataLengthType>
Error AppendData (const Data< kDataLengthType > &aData)
void ClearChildMask (uint16_t aChildIndex)
void ClearDirectTransmission (void)
Message * Clone (uint16_t aLength) const
Message * Clone (void) const
template<typename ObjectType >
bool Compare (uint16_t aOffset, const ObjectType &aObject) const
bool CompareBytes (uint16_t aOffset, const void *aBuf, uint16_t aLength, ByteMatcher aMatcher=nullptr) const
bool CompareBytes (uint16_t aOffset, const Message &aOtherMessage, uint16_t aOtherOffset, uint16_t aLength, ByteMatcher aMatcher=nullptr) const
uint16_t CopyTo (uint16_t aSourceOffset, uint16_t aDestinationOffset, uint16_t aLength, Message &aMessage) const
void Free (void)
int8_t GetAverageRss (void) const
uint8_t GetBufferCount (void) const
uint8_t GetChannel (void) const
bool GetChildMask (uint16_t aChildIndex) const
uint32_t GetDatagramTag (void) const
bool GetDoNotEvict (void) const
Instance & GetInstance (void) const
uint16_t GetLength (void) const
uint16_t GetMeshDest (void) const
MessageQueue * GetMessageQueue (void) const
bool GetMulticastLoop (void) const
Message * GetNext (void) const
uint16_t GetOffset (void) const
uint16_t GetPanId (void) const
Priority GetPriority (void) const
PriorityQueue * GetPriorityQueue (void) const
const RssAverager & GetRssAverager (void) const
SubType GetSubType (void) const
TimeMilli GetTimestamp (void) const
bool GetTxSuccess (void) const
Type GetType (void) const
bool IsChildPending (void) const
bool IsDirectTransmission (void) const
bool IsLinkSecurityEnabled (void) const
bool IsResolvingAddress (void) const
bool IsSubTypeMle (void) const
bool IsTimeSync (void) const
void MoveOffset (int aDelta)
template<typename ObjectType >
Error Prepend (const ObjectType &aObject)
Error PrependBytes (const void *aBuf, uint16_t aLength)
Error Read (uint16_t aOffset, void *aBuf, uint16_t aLength) const
template<typename ObjectType >
Error Read (uint16_t aOffset, ObjectType &aObject) const
uint16_t ReadBytes (uint16_t aOffset, void *aBuf, uint16_t aLength) const
void RemoveHeader (uint16_t aLength)
void SetChannel (uint8_t aChannel)
void SetChildMask (uint16_t aChildIndex)
void SetDatagramTag (uint32_t aTag)
void SetDirectTransmission (void)
void SetDoNotEvict (bool aDoNotEvict)
Error SetLength (uint16_t aLength)
void SetLinkInfo (const ThreadLinkInfo &aLinkInfo)
void SetLinkSecurityEnabled (bool aEnabled)
void SetMeshDest (uint16_t aMeshDest)
void SetMulticastLoop (bool aMulticastLoop)
void SetOffset (uint16_t aOffset)
void SetPanId (uint16_t aPanId)
Error SetPriority (Priority aPriority)
void SetResolvingAddress (bool aResolvingAddress)
void SetSubType (SubType aSubType)
void SetTimestamp (TimeMilli aTimestamp)
void SetTimestampToNow (void)
void SetTxSuccess (bool aTxSuccess)
void SetType (Type aType)
template<typename ObjectType >
void Write (uint16_t aOffset, const ObjectType &aObject)
void WriteBytes (uint16_t aOffset, const void *aBuf, uint16_t aLength)
template<DataLengthType kDataLengthType>
void WriteData (uint16_t aOffset, const Data< kDataLengthType > &aData)
Public Member Functions inherited from Buffer
Buffer * GetNextBuffer (void)
const Buffer * GetNextBuffer (void) const
void SetNextBuffer (Buffer *aNext)
Public Member Functions inherited from LinkedListEntry< Buffer >
const Buffer * GetNext (void) const
Buffer * GetNext (void)
void SetNext (Buffer *aNext)
Public Member Functions inherited from GetProvider< Message >
Type & Get (void) const
Static Public Member Functions
static uint16_t GetHelpDataReserved (void)
Static Public Member Functions inherited from Message
static const char * PriorityToString (Priority aPriority)
Static Public Attributes
static constexpr uint8_t kBlockSzxBase = 4
static constexpr uint8_t kDefaultTokenLength = OT_COAP_DEFAULT_TOKEN_LENGTH
Default token length.
static constexpr uint8_t kMaxReceivedUriPath = 32
Max URI path length on rx msgs.
static constexpr uint8_t kMaxTokenLength = OT_COAP_MAX_TOKEN_LENGTH
Maximum token length.
Static Public Attributes inherited from Message
static constexpr uint8_t kNumPriorities = 4
Number of priority levels.
Private Member Functions
const HelpData & GetHelpData (void) const
HelpData & GetHelpData (void)
uint8_t * GetToken (void)
void SetTokenLength (uint8_t aTokenLength)
uint8_t WriteExtendedOptionField (uint16_t aValue, uint8_t *&aBuffer)
Private Attributes
OT_TOOL_PACKED_BEGIN struct ot::Coap::Message::Header OT_TOOL_PACKED_END
Static Private Attributes
static constexpr uint8_t kBlockMOffset = 3
static constexpr uint32_t kBlockNumMax = 0xffff
static constexpr uint8_t kBlockNumOffset = 4
static constexpr uint8_t kBlockSzxOffset = 0
static constexpr uint8_t kHelpDataAlignment = sizeof(uint16_t)
static constexpr uint16_t kMaxHeaderLength = 512
static constexpr uint8_t kMaxOptionHeaderSize = 5
static constexpr uint16_t kMinHeaderLength = 4
static constexpr uint32_t kObserveMask = 0xffffff
static constexpr uint8_t kOption1ByteExtension = 13
static constexpr uint16_t kOption1ByteExtensionOffset = 13
static constexpr uint8_t kOption2ByteExtension = 14
static constexpr uint16_t kOption2ByteExtensionOffset = 269
static constexpr uint8_t kOptionDeltaMask = 0xf << kOptionDeltaOffset
static constexpr uint8_t kOptionDeltaOffset = 4
static constexpr uint8_t kOptionLengthMask = 0xf << kOptionLengthOffset
static constexpr uint8_t kOptionLengthOffset = 0
static constexpr uint8_t kPayloadMarker = 0xff
static constexpr uint8_t kTokenLengthMask = 0xf << kTokenLengthOffset
static constexpr uint8_t kTokenLengthOffset = 0
static constexpr uint8_t kTypeMask = 0x3 << kTypeOffset
static constexpr uint8_t kTypeOffset = 4
static constexpr uint8_t kVersion1 = 1
static constexpr uint8_t kVersionMask = 0x3 << kVersionOffset
static constexpr uint8_t kVersionOffset = 6
Friends
class MessageQueue
class Option
Additional Inherited Members
Data Fields inherited from otMessageBuffer
struct otMessageBuffer * mNext
Pointer to the next buffer.
Protected Member Functions inherited from Message
uint16_t GetReserved (void) const
void SetReserved (uint16_t aReservedHeader)
Protected Member Functions inherited from Buffer
uint8_t * GetData (void)
const uint8_t * GetData (void) const
uint8_t * GetFirstData (void)
const uint8_t * GetFirstData (void) const
Metadata & GetMetadata (void)
const Metadata & GetMetadata (void) const
Protected Member Functions inherited from GetProvider< Message >
GetProvider (void)=default
Static Protected Attributes inherited from Buffer
static constexpr uint16_t kBufferDataSize = kBufferSize - sizeof(otMessageBuffer)
static constexpr uint16_t kHeadBufferDataSize = kBufferDataSize - sizeof(Metadata)
Detailed Description
This class implements CoAP message generation and parsing.
Member Typedef Documentation
Type
typedef ot::Coap::Type Type
CoAP Type.
Code
typedef ot::Coap::Code Code
CoAP Code.
Member Enumeration Documentation
BlockType
enum BlockType : uint8_t
CoAP Block1/Block2 Types
Enumerator
kBlockType1
kBlockType2
Member Function Documentation
Init() [1/3]
void Init (void)
This method initializes the CoAP header.
References Clearable< Type >::Clear(), Message::GetHelpData(), IgnoreError(), Message::kMinHeaderLength, Message::kVersion1, Message::HelpData::mHeaderLength, OT_COAP_OPTION_BLOCK_SZX_16, Message::SetLength(), Message::SetOffset(), and Message::SetVersion().
Referenced by AddressResolver::AddressResolver(), CoapBase::DequeueMessage(), Message::Init(), Message::InitAsPost(), CoapBase::InitMessage(), Option::Iterator::InitOrAdvance(), CoapBase::SendEmptyMessage(), CoapBase::SendHeaderResponse(), and Message::SetDefaultResponseHeader().
Init() [2/3]
void Init (Type aType, Code aCode)
This method initializes the CoAP header with specific Type and Code.
Parameters
[in] aType The Type value.
[in] aCode The Code value.
References Message::Init(), Message::SetCode(), and Message::SetType().
Init() [3/3]
Error Init (Type aType, Code aCode, const char * aUriPath)
This method initializes the CoAP header with specific Type and Code.
Parameters
[in] aType The Type value.
[in] aCode The Code value.
[in] aUriPath A pointer to a null-terminated string.
Return values
kErrorNone Successfully appended the option.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendUriPathOptions(), Message::GenerateRandomToken(), Message::Init(), Message::kDefaultTokenLength, and SuccessOrExit.
InitAsPost()
Error InitAsPost (const Ip6::Address & aDestination, const char * aUriPath)
This method initializes the CoAP header as kCodePost with a given URI Path with its type determined from a given destination IPv6 address.
Parameters
[in] aDestination The message destination IPv6 address used to determine the CoAP type, kTypeNonConfirmable if multicast address, kTypeConfirmable otherwise.
[in] aUriPath A pointer to a null-terminated string.
Return values
kErrorNone Successfully appended the option.
kErrorNoBufs The option length exceeds the buffer size.
References Message::Init(), Address::IsMulticast(), ot::Coap::kCodePost, ot::Coap::kTypeConfirmable, and ot::Coap::kTypeNonConfirmable.
Finish()
void Finish (void)
This method writes header to the message. This must be called before sending the message.
This method also checks whether the payload marker is set (SetPayloadMarker()) but the message contains no payload, and if so it removes the payload marker from the message.
References Message::GetHelpData(), Message::GetLength(), Message::GetOptionStart(), IgnoreError(), Message::SetLength(), and Message::WriteBytes().
Referenced by CoapBase::ProcessReceivedRequest(), CoapBase::SendEmptyMessage(), and CoapBase::SendMessage().
GetVersion()
uint8_t GetVersion (void) const inline
This method returns the Version value.
Returns
The Version value.
References Message::GetHelpData(), Message::kVersionMask, and Message::kVersionOffset.
SetVersion()
void SetVersion (uint8_t aVersion) inline
This method sets the Version value.
Parameters
[in] aVersion The Version value.
References Message::GetHelpData(), Message::kVersionMask, Message::kVersionOffset, Message::HelpData::mHeader, and Message::Header::mVersionTypeToken.
Referenced by Message::Init().
GetType()
uint8_t GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Message::GetHelpData(), Message::kTypeMask, and Message::kTypeOffset.
Referenced by CoapBase::FindRelatedRequest(), Message::IsAck(), Message::IsConfirmable(), Message::IsNonConfirmable(), Message::IsReset(), CoapBase::ProcessReceivedResponse(), CoapBase::SendHeaderResponse(), and CoapBase::SendMessage().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Message::GetHelpData(), Message::kTypeMask, Message::kTypeOffset, Message::HelpData::mHeader, and Message::Header::mVersionTypeToken.
Referenced by Message::Init(), and CoapBase::SendMessage().
GetCode()
uint8_t GetCode (void) const inline
This method returns the Code value.
Returns
The Code value.
References Message::GetHelpData(), Message::Header::mCode, and Message::HelpData::mHeader.
Referenced by Message::Clone(), CoapBase::DequeueMessage(), Message::IsDeleteRequest(), Message::IsEmpty(), Message::IsGetRequest(), Message::IsPostRequest(), Message::IsPutRequest(), Message::IsRequest(), Message::IsResponse(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
SetCode()
void SetCode (Code aCode) inline
This method sets the Code value.
Parameters
[in] aCode The Code value.
References Message::GetHelpData(), Message::Header::mCode, and Message::HelpData::mHeader.
Referenced by Message::Init().
GetMessageId()
uint16_t GetMessageId (void) const inline
This method returns the Message ID value.
Returns
The Message ID value.
References Message::GetHelpData(), and ot::Encoding::BigEndian::HostSwap16().
Referenced by CoapBase::DequeueMessage(), ResponsesQueue::FindMatchedResponse(), CoapBase::FindRelatedRequest(), CoapBase::SendEmptyMessage(), CoapBase::SendHeaderResponse(), and Message::SetDefaultResponseHeader().
SetMessageId()
void SetMessageId (uint16_t aMessageId) inline
This method sets the Message ID value.
Parameters
[in] aMessageId The Message ID value.
References Message::GetHelpData(), ot::Encoding::BigEndian::HostSwap16(), Message::HelpData::mHeader, and Message::Header::mMessageId.
Referenced by CoapBase::DequeueMessage(), CoapBase::SendEmptyMessage(), CoapBase::SendHeaderResponse(), CoapBase::SendMessage(), and Message::SetDefaultResponseHeader().
GetTokenLength()
uint8_t GetTokenLength (void) const inline
This method returns the Token length.
Returns
The Token length.
References Message::GetHelpData(), Message::kTokenLengthMask, and Message::kTokenLengthOffset.
Referenced by CoapBase::DequeueMessage(), Message::GetOptionStart(), Message::IsTokenEqual(), Message::ParseHeader(), and Message::SetTokenFromMessage().
GetToken() [1/2]
const uint8_t* GetToken (void) const inline
This method returns a pointer to the Token value.
Returns
A pointer to the Token value.
References Message::AppendOption(), Message::AppendStringOption(), Message::AppendUintOption(), Message::GenerateRandomToken(), Message::GetHelpData(), Message::IsTokenEqual(), Message::HelpData::mHeader, Message::Header::mToken, Message::SetToken(), and Message::SetTokenFromMessage().
Referenced by Message::IsTokenEqual(), Message::SetToken(), and Message::SetTokenFromMessage().
SetToken()
Error SetToken (const uint8_t * aToken, uint8_t aTokenLength)
This method sets the Token value and length.
Parameters
[in] aToken A pointer to the Token value.
[in] aTokenLength The Length of aToken.
Return values
kErrorNone Successfully set the token value.
kErrorNoBufs Insufficient message buffers available to set the token value.
References Message::GetHelpData(), Message::GetToken(), Message::kMaxTokenLength, Message::HelpData::mHeaderLength, OT_ASSERT, Message::SetLength(), and Message::SetTokenLength().
Referenced by CoapBase::DequeueMessage(), Message::GenerateRandomToken(), Message::GetToken(), and Message::SetTokenFromMessage().
SetTokenFromMessage()
Error SetTokenFromMessage (const Message & aMessage)
This method sets the Token value and length by copying it from another given message.
Parameters
[in] aMessage The message to copy the Token from.
Return values
kErrorNone Successfully set the token value.
kErrorNoBufs Insufficient message buffers available to set the token value.
References Message::GetToken(), Message::GetTokenLength(), and Message::SetToken().
Referenced by Message::GetToken(), CoapBase::SendHeaderResponse(), and Message::SetDefaultResponseHeader().
GenerateRandomToken()
Error GenerateRandomToken (uint8_t aTokenLength)
This method sets the Token length and randomizes its value.
Parameters
[in] aTokenLength The Length of a Token to set.
Return values
kErrorNone Successfully set the token value.
kErrorNoBufs Insufficient message buffers available to set the token value.
References ot::Random::Crypto::FillBuffer(), IgnoreError(), Message::kMaxTokenLength, OT_ASSERT, and Message::SetToken().
Referenced by Message::GetToken(), and Message::Init().
IsTokenEqual()
bool IsTokenEqual (const Message & aMessage) const
This method checks if Tokens in two CoAP headers are equal.
Parameters
[in] aMessage A header to compare.
Return values
TRUE If two Tokens are equal.
FALSE If Tokens differ in length or value.
References Message::GetToken(), and Message::GetTokenLength().
Referenced by CoapBase::FindRelatedRequest(), Message::GetToken(), and CoapBase::ProcessReceivedResponse().
AppendOption()
Error AppendOption (uint16_t aNumber, uint16_t aLength, const void * aValue)
This method appends a CoAP option.
Parameters
[in] aNumber The CoAP Option number.
[in] aLength The CoAP Option length.
[in] aValue A pointer to the CoAP Option value (aLength bytes are used as Option value).
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendBytes(), Message::GetHelpData(), Message::GetLength(), ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, Message::kMaxHeaderLength, Message::kMaxOptionHeaderSize, Message::kOptionDeltaOffset, Message::kOptionLengthOffset, Message::HelpData::mHeaderLength, Message::HelpData::mOptionLast, SuccessOrExit, VerifyOrExit, and Message::WriteExtendedOptionField().
Referenced by Message::AppendStringOption(), Message::AppendUintOption(), Message::AppendUriPathOptions(), CoapBase::DequeueMessage(), and Message::GetToken().
AppendUintOption()
Error AppendUintOption (uint16_t aNumber, uint32_t aValue)
This method appends an unsigned integer CoAP option as specified in RFC-7252 section-3.2
Parameters
[in] aNumber The CoAP Option number.
[in] aValue The CoAP Option unsigned integer value.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendOption(), and ot::Encoding::BigEndian::WriteUint32().
Referenced by Message::AppendBlockOption(), Message::AppendContentFormatOption(), Message::AppendMaxAgeOption(), Message::AppendObserveOption(), and Message::GetToken().
AppendStringOption()
Error AppendStringOption (uint16_t aNumber, const char * aValue)
This method appends a string CoAP option.
Parameters
[in] aNumber The CoAP Option number.
[in] aValue The CoAP Option string value.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendOption().
Referenced by Message::AppendProxyUriOption(), Message::AppendUriPathOptions(), Message::AppendUriQueryOption(), and Message::GetToken().
AppendObserveOption()
Error AppendObserveOption (uint32_t aObserve) inline
This method appends an Observe option.
Parameters
[in] aObserve Observe field value.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendBlockOption(), Message::AppendUintOption(), Message::AppendUriPathOptions(), Message::kObserveMask, ot::Coap::kOptionObserve, and Message::ReadUriPathOptions().
AppendUriPathOptions()
Error AppendUriPathOptions (const char * aUriPath)
This method appends a Uri-Path option.
Parameters
[in] aUriPath A pointer to a null-terminated string.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendOption(), Message::AppendStringOption(), ot::kErrorNone, ot::Coap::kOptionUriPath, ot::StringFind(), and SuccessOrExit.
Referenced by AddressResolver::AddressResolver(), Message::AppendObserveOption(), and Message::Init().
ReadUriPathOptions()
Error ReadUriPathOptions (char(&) aUriPath[kMaxReceivedUriPath+1]) const
This method reads the Uri-Path options and constructs the URI path in the buffer referenced by aUriPath.
Parameters
[in] aUriPath A reference to the buffer for storing URI path. NOTE: The buffer size must be kMaxReceivedUriPath + 1.
Return values
kErrorNone Successfully read the Uri-Path options.
kErrorParse CoAP Option header not well-formed.
References Option::Iterator::Advance(), ot::GetArrayEnd(), Option::GetLength(), Option::Iterator::GetOption(), IgnoreError(), Option::Iterator::Init(), Option::Iterator::IsDone(), ot::kErrorNone, ot::kErrorParse, ot::Coap::kOptionUriPath, Option::Iterator::ReadOptionValue(), SuccessOrExit, and VerifyOrExit.
Referenced by Message::AppendObserveOption(), and CoapBase::ProcessReceivedRequest().
AppendBlockOption()
Error AppendBlockOption (Message::BlockType aType, uint32_t aNum, bool aMore, otCoapBlockSzx aSize)
This method appends a Block option
Parameters
[in] aType Type of block option, 1 or 2.
[in] aNum Current block number.
[in] aMore Boolean to indicate more blocks are to be sent.
[in] aSize Maximum block size.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendUintOption(), Option::GetLength(), Option::Iterator::GetOption(), Option::Iterator::Init(), Message::kBlockMOffset, Message::kBlockNumMax, Message::kBlockNumOffset, Message::kBlockType1, Message::kBlockType2, ot::kErrorInvalidArgs, ot::kErrorNone, Message::kMaxOptionHeaderSize, ot::Coap::kOptionBlock1, ot::Coap::kOptionBlock2, OT_COAP_OPTION_BLOCK_SZX_1024, Option::Iterator::ReadOptionValue(), SuccessOrExit, and VerifyOrExit.
Referenced by Message::AppendObserveOption(), and CoapBase::DequeueMessage().
AppendProxyUriOption()
Error AppendProxyUriOption (const char * aProxyUri) inline
This method appends a Proxy-Uri option.
Parameters
[in] aProxyUri A pointer to a null-terminated string.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendStringOption(), and ot::Coap::kOptionProxyUri.
AppendContentFormatOption()
Error AppendContentFormatOption (otCoapOptionContentFormat aContentFormat) inline
This method appends a Content-Format option.
Parameters
[in] aContentFormat The Content Format value.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendUintOption(), and ot::Coap::kOptionContentFormat.
AppendMaxAgeOption()
Error AppendMaxAgeOption (uint32_t aMaxAge) inline
This method appends a Max-Age option.
Parameters
[in] aMaxAge The Max-Age value.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendUintOption(), and ot::Coap::kOptionMaxAge.
AppendUriQueryOption()
Error AppendUriQueryOption (const char * aUriQuery) inline
This method appends a single Uri-Query option.
Parameters
[in] aUriQuery A pointer to null-terminated string, which should contain a single key=value pair.
Return values
kErrorNone Successfully appended the option.
kErrorInvalidArgs The option type is not equal or greater than the last option type.
kErrorNoBufs The option length exceeds the buffer size.
References Message::AppendStringOption(), Message::GetHelpData(), Message::GetUriPath(), ot::Coap::kOptionUriQuery, Message::HelpData::mHeaderLength, and Message::SetPayloadMarker().
GetUriPath()
Error GetUriPath (char * aUriPath) const
This function reads and reassembles the URI path string and fills it into aUriPath.
Return values
kErrorNone URI path string has been reassembled.
kErrorNoBufs URI path string is too long.
Referenced by Message::AppendUriQueryOption().
SetPayloadMarker()
Error SetPayloadMarker (void)
This method adds Payload Marker indicating beginning of the payload to the CoAP header.
It also set offset to the start of payload.
Return values
kErrorNone Payload Marker successfully added.
kErrorNoBufs Message Payload Marker exceeds the buffer size.
References Message::Append(), Message::GetHelpData(), Message::GetLength(), ot::kErrorNoBufs, ot::kErrorNone, Message::kMaxHeaderLength, Message::kPayloadMarker, Message::HelpData::mHeaderLength, Message::HelpData::mPayloadMarkerSet, Message::SetOffset(), SuccessOrExit, and VerifyOrExit.
Referenced by AddressResolver::AddressResolver(), Message::AppendUriQueryOption(), CoapBase::DequeueMessage(), CoapBase::InitMessage(), and CoapBase::InitResponse().
GetOptionStart()
uint16_t GetOptionStart (void) const inline
This method returns the offset of the first CoAP option.
Returns
The offset of the first CoAP option.
References Message::GetHelpData(), Message::GetTokenLength(), Message::kMinHeaderLength, Message::ParseHeader(), and Message::SetDefaultResponseHeader().
Referenced by Message::Finish(), Option::Iterator::Init(), and CoapBase::SendMessage().
ParseHeader()
Error ParseHeader (void)
This method parses CoAP header and moves offset end of CoAP header.
Return values
kErrorNone Successfully parsed CoAP header from the message.
kErrorParse Failed to parse the CoAP header.
References Option::Iterator::Advance(), Clearable< Type >::Clear(), Buffer::GetFirstData(), Message::GetHelpData(), Message::GetOffset(), Option::Iterator::GetPayloadMessageOffset(), Message::GetReserved(), Message::GetTokenLength(), IgnoreError(), Option::Iterator::Init(), Option::Iterator::IsDone(), ot::kErrorNone, ot::kErrorParse, Message::kMaxTokenLength, Message::HelpData::mHeaderLength, Message::HelpData::mHeaderOffset, Message::MoveOffset(), OT_ASSERT, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by Message::GetOptionStart(), and CoapBase::Receive().
SetDefaultResponseHeader()
Error SetDefaultResponseHeader (const Message & aRequest)
This method sets a default response header based on request header.
Parameters
[in] aRequest The request message.
Return values
kErrorNone Successfully set the default response header.
kErrorNoBufs Insufficient message buffers available to set the default response header.
References Message::GetMessageId(), Message::Init(), ot::Coap::kCodeChanged, ot::Coap::kTypeAck, Message::SetMessageId(), and Message::SetTokenFromMessage().
Referenced by Message::GetOptionStart(), and CoapBase::InitResponse().
IsEmpty()
bool IsEmpty (void) const inline
This method checks if a header is an empty message header.
Return values
TRUE Message is an empty message header.
FALSE Message is not an empty message header.
References Message::GetCode(), and ot::Coap::kCodeEmpty.
Referenced by CoapBase::ProcessReceivedResponse().
IsRequest()
bool IsRequest (void) const inline
This method checks if a header is a request header.
Return values
TRUE Message is a request header.
FALSE Message is not a request header.
References Message::GetCode(), ot::Coap::kCodeDelete, and ot::Coap::kCodeGet.
Referenced by CoapBase::ProcessReceivedResponse(), CoapBase::Receive(), and CoapBase::SendHeaderResponse().
IsGetRequest()
bool IsGetRequest (void) const inline
This method indicates whether or not the CoAP code in header is "Get" request.
Return values
TRUE Message is a Get request.
FALSE Message is not a Get request.
References Message::GetCode(), and ot::Coap::kCodeGet.
Referenced by CoapBase::SendMessage().
IsPostRequest()
bool IsPostRequest (void) const inline
This method indicates whether or not the CoAP code in header is "Post" request.
Return values
TRUE Message is a Post request.
FALSE Message is not a Post request.
References Message::GetCode(), and ot::Coap::kCodePost.
Referenced by AddressResolver::HandleAddressError(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), AnnounceBeginServer::HandleRequest(), Message::IsConfirmablePostRequest(), and Message::IsNonConfirmablePostRequest().
IsPutRequest()
bool IsPutRequest (void) const inline
This method indicates whether or not the CoAP code in header is "Put" request.
Return values
TRUE Message is a Put request.
FALSE Message is not a Put request.
References Message::GetCode(), and ot::Coap::kCodePut.
IsDeleteRequest()
bool IsDeleteRequest (void) const inline
This method indicates whether or not the CoAP code in header is "Delete" request.
Return values
TRUE Message is a Delete request.
FALSE Message is not a Delete request.
References Message::GetCode(), and ot::Coap::kCodeDelete.
IsResponse()
bool IsResponse (void) const inline
This method checks if a header is a response header.
Return values
TRUE Message is a response header.
FALSE Message is not a response header.
References Message::GetCode(), and OT_COAP_CODE_RESPONSE_MIN.
Referenced by CoapBase::ProcessReceivedResponse().
IsConfirmable()
bool IsConfirmable (void) const inline
This method checks if a header is a CON message header.
Return values
TRUE Message is a CON message header.
FALSE Message is not is a CON message header.
References Message::GetType(), and ot::Coap::kTypeConfirmable.
Referenced by AddressResolver::HandleAddressError(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), AnnounceBeginServer::HandleRequest(), Message::IsConfirmablePostRequest(), CoapBase::ProcessReceivedResponse(), CoapBase::Receive(), CoapBase::SendEmptyAck(), CoapBase::SendEmptyMessage(), and CoapBase::SendMessage().
IsNonConfirmable()
bool IsNonConfirmable (void) const inline
This method checks if a header is a NON message header.
Return values
TRUE Message is a NON message header.
FALSE Message is not is a NON message header.
References Message::GetType(), and ot::Coap::kTypeNonConfirmable.
Referenced by Message::IsNonConfirmablePostRequest(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
IsAck()
bool IsAck (void) const inline
This method checks if a header is a ACK message header.
Return values
TRUE Message is a ACK message header.
FALSE Message is not is a ACK message header.
References Message::GetType(), and ot::Coap::kTypeAck.
IsReset()
bool IsReset (void) const inline
This method checks if a header is a RST message header.
Return values
TRUE Message is a RST message header.
FALSE Message is not is a RST message header.
References Message::Clone(), Message::GetType(), Message::IsConfirmablePostRequest(), Message::IsNonConfirmablePostRequest(), and ot::Coap::kTypeReset.
IsConfirmablePostRequest()
bool IsConfirmablePostRequest (void) const
This method indicates whether or not the header is a confirmable Put request (i.e, kTypeConfirmable with kCodePost).
Return values
TRUE Message is a confirmable Post request.
FALSE Message is not a confirmable Post request.
References Message::IsConfirmable(), and Message::IsPostRequest().
Referenced by AddressResolver::AddressResolver(), and Message::IsReset().
IsNonConfirmablePostRequest()
bool IsNonConfirmablePostRequest (void) const
This method indicates whether or not the header is a non-confirmable Put request (i.e, kTypeNonConfirmable with kCodePost).
Return values
TRUE Message is a non-confirmable Post request.
FALSE Message is not a non-confirmable Post request.
References Message::IsNonConfirmable(), and Message::IsPostRequest().
Referenced by AddressResolver::HandleAddressError(), and Message::IsReset().
Clone() [1/2]
Message * Clone (uint16_t aLength) const
This method creates a copy of this CoAP message.
It allocates the new message from the same message pool as the original one and copies aLength octets of the payload. The Type, SubType, LinkSecurity, Offset, InterfaceId, and Priority fields on the cloned message are also copied from the original one.
Parameters
[in] aLength Number of payload bytes to copy.
Returns
A pointer to the message or nullptr if insufficient message buffers are available.
References Message::Clone(), Message::GetCode(), Message::GetHelpData(), BinarySearch::IsSorted(), ot::Coap::kCodeBadGateway, ot::Coap::kCodeBadOption, ot::Coap::kCodeBadRequest, ot::Coap::kCodeChanged, ot::Coap::kCodeContent, ot::Coap::kCodeContinue, ot::Coap::kCodeCreated, ot::Coap::kCodeDelete, ot::Coap::kCodeDeleted, ot::Coap::kCodeEmpty, ot::Coap::kCodeForbidden, ot::Coap::kCodeGatewayTimeout, ot::Coap::kCodeGet, ot::Coap::kCodeInternalError, ot::Coap::kCodeMethodNotAllowed, ot::Coap::kCodeNotAcceptable, ot::Coap::kCodeNotFound, ot::Coap::kCodeNotImplemented, ot::Coap::kCodePost, ot::Coap::kCodePreconditionFailed, ot::Coap::kCodeProxyNotSupported, ot::Coap::kCodePut, ot::Coap::kCodeRequestIncomplete, ot::Coap::kCodeRequestTooLarge, ot::Coap::kCodeServiceUnavailable, ot::Coap::kCodeUnauthorized, ot::Coap::kCodeUnsupportedFormat, ot::Coap::kCodeValid, Stringify::Lookup(), and VerifyOrExit.
Referenced by CoapBase::CopyAndEnqueueMessage(), CoapBase::DequeueMessage(), ResponsesQueue::EnqueueResponse(), ResponsesQueue::GetMatchedResponseCopy(), and CoapBase::SendCopy().
Clone() [2/2]
Message* Clone (void) const inline
This method creates a copy of the message.
It allocates the new message from the same message pool as the original one and copies the entire payload. The Type, SubType, LinkSecurity, Offset, InterfaceId, and Priority fields on the cloned message are also copied from the original one.
Returns
A pointer to the message or nullptr if insufficient message buffers are available.
References Message::Clone(), and Message::GetLength().
Referenced by Message::Clone(), and Message::IsReset().
GetHelpDataReserved()
static uint16_t GetHelpDataReserved (void) inline static
This method returns the minimal reserved bytes required for CoAP message.
References Message::kHelpDataAlignment.
GetNextCoapMessage() [1/2]
Message* GetNextCoapMessage (void) inline
This method returns a pointer to the next message after this as a Coap::Message.
This method should be used when the message is in a Coap::MessageQueue (i.e., a queue containing only CoAP messages).
Returns
A pointer to the next message in the queue or nullptr if at the end of the queue.
References Message::GetNext().
GetNextCoapMessage() [2/2]
const Message* GetNextCoapMessage (void) const inline
This method returns a pointer to the next message after this as a Coap::Message.
This method should be used when the message is in a Coap::MessageQueue (i.e., a queue containing only CoAP messages).
Returns
A pointer to the next message in the queue or nullptr if at the end of the queue.
References Message::GetNext().
GetHelpData() [1/2]
const HelpData& GetHelpData (void) const inline private
References Buffer::GetFirstData(), Buffer::kHeadBufferDataSize, and OT_ALIGN.
Referenced by Message::AppendOption(), Message::AppendUriQueryOption(), Message::Clone(), Message::Finish(), Message::GetCode(), Message::GetMessageId(), Message::GetOptionStart(), Message::GetToken(), Message::GetTokenLength(), Message::GetType(), Message::GetVersion(), Message::Init(), Option::Iterator::Init(), Message::ParseHeader(), Message::SetCode(), Message::SetMessageId(), Message::SetPayloadMarker(), Message::SetToken(), Message::SetTokenLength(), Message::SetType(), and Message::SetVersion().
GetHelpData() [2/2]
HelpData& GetHelpData (void) inline private
References ot::AsConst(), ot::AsNonConst(), and Message::GetHelpData().
Referenced by Message::GetHelpData().
GetToken() [2/2]
uint8_t* GetToken (void) inline private
References Message::GetHelpData(), Message::HelpData::mHeader, and Message::Header::mToken.
SetTokenLength()
void SetTokenLength (uint8_t aTokenLength) inline private
References Message::GetHelpData(), Message::kTokenLengthOffset, Message::HelpData::mHeader, Message::Header::mVersionTypeToken, and Message::WriteExtendedOptionField().
Referenced by Message::SetToken().
WriteExtendedOptionField()
uint8_t WriteExtendedOptionField (uint16_t aValue, uint8_t *& aBuffer) private
References Message::kOption1ByteExtension, Message::kOption1ByteExtensionOffset, Message::kOption2ByteExtension, Message::kOption2ByteExtensionOffset, and ot::Encoding::BigEndian::WriteUint16().
Referenced by Message::AppendOption(), and Message::SetTokenLength().
Friends And Related Function Documentation
Option
friend class Option friend
MessageQueue
friend class MessageQueue friend
Field Documentation
kDefaultTokenLength
constexpr uint8_t kDefaultTokenLength = OT_COAP_DEFAULT_TOKEN_LENGTH static
Default token length.
Referenced by Message::Init().
kMaxReceivedUriPath
constexpr uint8_t kMaxReceivedUriPath = 32 static
Max URI path length on rx msgs.
Referenced by CoapBase::ProcessReceivedRequest().
kMaxTokenLength
constexpr uint8_t kMaxTokenLength = OT_COAP_MAX_TOKEN_LENGTH static
Maximum token length.
Referenced by Message::GenerateRandomToken(), Message::ParseHeader(), and Message::SetToken().
kBlockSzxBase
constexpr uint8_t kBlockSzxBase = 4 static
kVersionOffset
constexpr uint8_t kVersionOffset = 6 static private
Referenced by Message::GetVersion(), and Message::SetVersion().
kVersionMask
constexpr uint8_t kVersionMask = 0x3 << kVersionOffset static private
Referenced by Message::GetVersion(), and Message::SetVersion().
kVersion1
constexpr uint8_t kVersion1 = 1 static private
Referenced by Message::Init().
kTypeOffset
constexpr uint8_t kTypeOffset = 4 static private
Referenced by Message::GetType(), and Message::SetType().
kTypeMask
constexpr uint8_t kTypeMask = 0x3 << kTypeOffset static private
Referenced by Message::GetType(), and Message::SetType().
kTokenLengthOffset
constexpr uint8_t kTokenLengthOffset = 0 static private
Referenced by Message::GetTokenLength(), and Message::SetTokenLength().
kTokenLengthMask
constexpr uint8_t kTokenLengthMask = 0xf << kTokenLengthOffset static private
Referenced by Message::GetTokenLength().
kOptionDeltaOffset
constexpr uint8_t kOptionDeltaOffset = 4 static private
Referenced by Option::Iterator::Advance(), and Message::AppendOption().
kOptionDeltaMask
constexpr uint8_t kOptionDeltaMask = 0xf << kOptionDeltaOffset static private
Referenced by Option::Iterator::Advance().
kOptionLengthOffset
constexpr uint8_t kOptionLengthOffset = 0 static private
Referenced by Option::Iterator::Advance(), and Message::AppendOption().
kOptionLengthMask
constexpr uint8_t kOptionLengthMask = 0xf << kOptionLengthOffset static private
Referenced by Option::Iterator::Advance().
kMaxOptionHeaderSize
constexpr uint8_t kMaxOptionHeaderSize = 5 static private
Referenced by Message::AppendBlockOption(), and Message::AppendOption().
kOption1ByteExtension
constexpr uint8_t kOption1ByteExtension = 13 static private
Referenced by Option::Iterator::ReadExtendedOptionField(), and Message::WriteExtendedOptionField().
kOption2ByteExtension
constexpr uint8_t kOption2ByteExtension = 14 static private
Referenced by Option::Iterator::ReadExtendedOptionField(), and Message::WriteExtendedOptionField().
kPayloadMarker
constexpr uint8_t kPayloadMarker = 0xff static private
Referenced by Option::Iterator::Advance(), and Message::SetPayloadMarker().
kHelpDataAlignment
constexpr uint8_t kHelpDataAlignment = sizeof(uint16_t) static private
Referenced by Message::GetHelpDataReserved().
kMinHeaderLength
constexpr uint16_t kMinHeaderLength = 4 static private
Referenced by Message::GetOptionStart(), and Message::Init().
kMaxHeaderLength
constexpr uint16_t kMaxHeaderLength = 512 static private
Referenced by Message::AppendOption(), and Message::SetPayloadMarker().
kOption1ByteExtensionOffset
constexpr uint16_t kOption1ByteExtensionOffset = 13 static private
Referenced by Option::Iterator::ReadExtendedOptionField(), and Message::WriteExtendedOptionField().
kOption2ByteExtensionOffset
constexpr uint16_t kOption2ByteExtensionOffset = 269 static private
Referenced by Option::Iterator::ReadExtendedOptionField(), and Message::WriteExtendedOptionField().
kBlockSzxOffset
constexpr uint8_t kBlockSzxOffset = 0 static private
kBlockMOffset
constexpr uint8_t kBlockMOffset = 3 static private
Referenced by Message::AppendBlockOption().
kBlockNumOffset
constexpr uint8_t kBlockNumOffset = 4 static private
Referenced by Message::AppendBlockOption().
kObserveMask
constexpr uint32_t kObserveMask = 0xffffff static private
Referenced by Message::AppendObserveOption().
kBlockNumMax
constexpr uint32_t kBlockNumMax = 0xffff static private
Referenced by Message::AppendBlockOption().
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN struct ot::Coap::Message::Header OT_TOOL_PACKED_END private
The documentation for this class was generated from the following files:
coap_message.hpp
coap_message.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale