OpenThread: Encoder Class Reference
Encoder Class Reference
#include <hdlc.hpp>
Public Member Functions
otError BeginFrame (void)
otError Encode (uint8_t aByte)
otError Encode (const uint8_t *aData, uint16_t aLength)
Encoder (FrameWritePointer &aWritePointer)
otError EndFrame (void)
Private Attributes
uint16_t mFcs
FrameWritePointer & mWritePointer
Detailed Description
This class implements the HDLC-lite encoder.
Constructor & Destructor Documentation
Encoder()
Encoder (FrameWritePointer & aWritePointer) explicit
This constructor initializes the object.
Parameters
[in] aWritePointer The FrameWritePointer used by Encoder to write the encoded frames.
Member Function Documentation
BeginFrame()
otError BeginFrame (void)
This method begins an HDLC frame.
Return values
OT_ERROR_NONE Successfully started the HDLC frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to start the HDLC frame.
References ot::Hdlc::kFlagSequence, ot::Hdlc::kInitFcs, Encoder::mFcs, Encoder::mWritePointer, and FrameWritePointer::WriteByte().
Referenced by HdlcInterface::SendFrame().
Encode() [1/2]
otError Encode (uint8_t aByte)
This method encodes a single byte into current frame.
If there is no space to add the byte, the write pointer in frame buffer remains the same.
Parameters
[in] aByte A byte value to encode and add to frame.
Return values
OT_ERROR_NONE Successfully encoded and added the byte to frame buffer.
OT_ERROR_NO_BUFS Insufficient buffer space available to encode and add the byte.
References FrameWritePointer::CanWrite(), ot::Hdlc::HdlcByteNeedsEscape(), IgnoreError(), ot::Hdlc::kEscapeSequence, Encoder::mFcs, Encoder::mWritePointer, OT_ERROR_NO_BUFS, OT_ERROR_NONE, SuccessOrExit, ot::Hdlc::UpdateFcs(), VerifyOrExit, and FrameWritePointer::WriteByte().
Referenced by Encoder::Encode(), Encoder::EndFrame(), and HdlcInterface::SendFrame().
Encode() [2/2]
otError Encode (const uint8_t * aData, uint16_t aLength)
This method encodes a given block of data into current frame.
This method returns success only if there is space in buffer to encode the entire block of data. If there is no space to encode the entire block of data, the write pointer in frame buffer remains the same.
Parameters
[in] aData A pointer to a buffer containing the data to encode.
[in] aLength The number of bytes in aData.
Return values
OT_ERROR_NONE Successfully encoded and added the data to frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the frame.
References Encoder::Encode(), Encoder::mFcs, Encoder::mWritePointer, OT_ERROR_NONE, and SuccessOrExit.
EndFrame()
otError EndFrame (void)
This method ends/finalizes the HDLC frame.
Return values
OT_ERROR_NONE Successfully ended the HDLC frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to end the HDLC frame.
References Encoder::Encode(), ot::Hdlc::kFlagSequence, Encoder::mFcs, Encoder::mWritePointer, OT_ERROR_NONE, SuccessOrExit, and FrameWritePointer::WriteByte().
Referenced by HdlcInterface::SendFrame().
Field Documentation
mWritePointer
FrameWritePointer& mWritePointer private
Referenced by Encoder::BeginFrame(), Encoder::Encode(), and Encoder::EndFrame().
mFcs
uint16_t mFcs private
Referenced by Encoder::BeginFrame(), Encoder::Encode(), and Encoder::EndFrame().
The documentation for this class was generated from the following files:
hdlc.hpp
hdlc.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale