OpenThread: Option Class Reference
Option Class Reference
#include <nd6.hpp>
Data Structures
class Iterator
Public Types
enum Type : uint8_t { kTypePrefixInfo = 3, kTypeRouteInfo = 24 }
Public Member Functions
uint16_t GetLength (void) const
uint16_t GetSize (void) const
uint8_t GetType (void) const
bool IsValid (void) const
void SetLength (uint8_t aLength)
void SetSize (uint16_t aSize)
void SetType (Type aType)
Static Public Attributes
static constexpr uint16_t kLengthUnit = 8
The unit of length in octets.
Private Attributes
uint8_t mLength
uint8_t mType
Friends
class RouterAdvertMessage
Detailed Description
This class represents the variable length options in Neighbor Discovery messages.
See also
PrefixInfoOption
RouteInfoOption
Member Enumeration Documentation
Type
enum Type : uint8_t
Enumerator
kTypePrefixInfo
Prefix Information Option.
kTypeRouteInfo
Route Information Option.
Member Function Documentation
GetType()
uint8_t GetType (void) const inline
This method gets the option type.
Returns
The option type.
References Option::mType.
SetType()
void SetType (Type aType) inline
This method sets the option type.
Parameters
[in] aType The option type.
References Option::mType.
Referenced by PrefixInfoOption::Init(), and RouteInfoOption::Init().
SetSize()
void SetSize (uint16_t aSize) inline
This method sets the length based on a given total option size in bytes.
Th option must end on a 64-bit boundary, so the length is derived as (aSize + 7) / 8 * 8.
Parameters
[in] aSize The size of option in bytes.
References Option::mLength.
Referenced by PrefixInfoOption::Init().
GetSize()
uint16_t GetSize (void) const inline
This method returns the size of the option in bytes.
Returns
The size of the option in bytes.
References Option::kLengthUnit, and Option::mLength.
Referenced by PrefixInfoOption::IsValid(), RouteInfoOption::IsValid(), and Option::Iterator::Next().
SetLength()
void SetLength (uint8_t aLength) inline
This method sets the length of the option (in unit of 8 bytes).
Parameters
[in] aLength The length of the option in unit of 8 bytes.
References Option::mLength.
Referenced by RouterAdvertMessage::AppendOption(), and RouteInfoOption::SetPrefix().
GetLength()
uint16_t GetLength (void) const inline
This method returns the length of the option (in unit of 8 bytes).
Returns
The length of the option in unit of 8 bytes.
References Option::mLength.
Referenced by RouterAdvertMessage::AppendOption(), and RouteInfoOption::IsValid().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not this option is valid.
Return values
TRUE The option is valid.
FALSE The option is not valid.
References Option::mLength.
Referenced by PrefixInfoOption::GetPreferredLifetime(), RouteInfoOption::GetRouteLifetime(), and Option::Iterator::Validate().
Friends And Related Function Documentation
RouterAdvertMessage
friend class RouterAdvertMessage friend
Field Documentation
kLengthUnit
constexpr uint16_t kLengthUnit = 8 static
The unit of length in octets.
Referenced by Option::GetSize(), and RouteInfoOption::OptionSizeForPrefix().
mType
uint8_t mType private
Referenced by Option::GetType(), RouterAdvertMessage::Header::SetToDefault(), and Option::SetType().
mLength
uint8_t mLength private
Referenced by Option::GetLength(), Option::GetSize(), Option::IsValid(), Option::SetLength(), and Option::SetSize().
The documentation for this class was generated from the following file:
nd6.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale