OpenThread: BeaconPayload Class Reference
BeaconPayload Class Reference
Core-mac
#include <mac_frame.hpp>
Public Member Functions
void ClearJoiningPermitted (void)
void ClearNative (void)
const otExtendedPanId & GetExtendedPanId (void) const
MeshCoP::NameData GetNetworkName (void) const
uint8_t GetProtocolId (void) const
uint8_t GetProtocolVersion (void) const
void Init (void)
bool IsJoiningPermitted (void) const
bool IsNative (void) const
bool IsValid (void) const
void SetExtendedPanId (const otExtendedPanId &aExtPanId)
void SetJoiningPermitted (void)
void SetNative (void)
void SetNetworkName (const MeshCoP::NameData &aNameData)
Static Public Attributes
static constexpr uint8_t kJoiningFlag = 1 << 0
Joining Permitted flag.
static constexpr uint8_t kNativeFlag = 1 << 3
Native Commissioner flag.
static constexpr uint8_t kProtocolId = 3
Thread Protocol ID.
static constexpr uint8_t kProtocolVersion = 2
Thread Protocol version.
static constexpr uint8_t kVersionMask = 0xf << kVersionOffset
Version field mask.
static constexpr uint8_t kVersionOffset = 4
Version field bit offset.
Private Attributes
otExtendedPanId mExtendedPanId
uint8_t mFlags
char mNetworkName [MeshCoP::NetworkName::kMaxSize]
uint8_t mProtocolId
Detailed Description
This class implements IEEE 802.15.4 Beacon Payload generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the Beacon Payload.
Referenced by Mac::PrepareBeacon().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the beacon appears to be a valid Thread Beacon Payload.
Return values
TRUE If the beacon appears to be a valid Thread Beacon Payload.
FALSE If the beacon does not appear to be a valid Thread Beacon Payload.
Referenced by Mac::ConvertBeaconToActiveScanResult().
GetProtocolId()
uint8_t GetProtocolId (void) const inline
This method returns the Protocol ID value.
Returns
the Protocol ID value.
GetProtocolVersion()
uint8_t GetProtocolVersion (void) const inline
This method returns the Protocol Version value.
Returns
The Protocol Version value.
Referenced by Mac::ConvertBeaconToActiveScanResult().
IsNative()
bool IsNative (void) const inline
This method indicates whether or not the Native Commissioner flag is set.
Return values
TRUE If the Native Commissioner flag is set.
FALSE If the Native Commissioner flag is not set.
Referenced by Mac::ConvertBeaconToActiveScanResult().
ClearNative()
void ClearNative (void) inline
This method clears the Native Commissioner flag.
SetNative()
void SetNative (void) inline
This method sets the Native Commissioner flag.
IsJoiningPermitted()
bool IsJoiningPermitted (void) const inline
This method indicates whether or not the Joining Permitted flag is set.
Return values
TRUE If the Joining Permitted flag is set.
FALSE If the Joining Permitted flag is not set.
Referenced by Mac::ConvertBeaconToActiveScanResult().
ClearJoiningPermitted()
void ClearJoiningPermitted (void) inline
This method clears the Joining Permitted flag.
Referenced by Mac::PrepareBeacon().
SetJoiningPermitted()
void SetJoiningPermitted (void) inline
This method sets the Joining Permitted flag.
References OPENTHREAD_CONFIG_MAC_JOIN_BEACON_VERSION.
Referenced by Mac::PrepareBeacon().
GetNetworkName()
MeshCoP::NameData GetNetworkName (void) const inline
This method gets the Network Name field.
Returns
The Network Name field as NameData.
Referenced by Mac::ConvertBeaconToActiveScanResult().
SetNetworkName()
void SetNetworkName (const MeshCoP::NameData & aNameData) inline
This method sets the Network Name field.
Parameters
[in] aNameData The Network Name (as a NameData).
References NameData::CopyTo().
Referenced by Mac::PrepareBeacon().
GetExtendedPanId()
const otExtendedPanId& GetExtendedPanId (void) const inline
This method returns the Extended PAN ID field.
Returns
The Extended PAN ID field.
Referenced by Mac::ConvertBeaconToActiveScanResult().
SetExtendedPanId()
void SetExtendedPanId (const otExtendedPanId & aExtPanId) inline
This method sets the Extended PAN ID field.
Parameters
[in] aExtPanId An Extended PAN ID.
Referenced by Mac::PrepareBeacon().
Field Documentation
kProtocolId
constexpr uint8_t kProtocolId = 3 static
Thread Protocol ID.
kProtocolVersion
constexpr uint8_t kProtocolVersion = 2 static
Thread Protocol version.
kVersionOffset
constexpr uint8_t kVersionOffset = 4 static
Version field bit offset.
kVersionMask
constexpr uint8_t kVersionMask = 0xf << kVersionOffset static
Version field mask.
kNativeFlag
constexpr uint8_t kNativeFlag = 1 << 3 static
Native Commissioner flag.
kJoiningFlag
constexpr uint8_t kJoiningFlag = 1 << 0 static
Joining Permitted flag.
mProtocolId
uint8_t mProtocolId private
mFlags
uint8_t mFlags private
mNetworkName
char mNetworkName[MeshCoP::NetworkName::kMaxSize] private
mExtendedPanId
otExtendedPanId mExtendedPanId private
The documentation for this class was generated from the following file:
mac_frame.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale