OpenThread: Netif::ExternalMulticastAddress Class Reference
Netif::ExternalMulticastAddress Class Reference
#include <netif.hpp>
Data Structures
class Iterator
Private Member Functions
ExternalMulticastAddress * GetNext (void)
Friends
class LinkedList< ExternalMulticastAddress >
class Netif
Additional Inherited Members
Public Member Functions inherited from Netif::MulticastAddress
const Address & GetAddress (void) const
Address & GetAddress (void)
const MulticastAddress * GetNext (void) const
MulticastAddress * GetNext (void)
Public Member Functions inherited from LinkedListEntry< MulticastAddress >
const MulticastAddress * GetNext (void) const
MulticastAddress * GetNext (void)
void SetNext (MulticastAddress *aNext)
Public Member Functions inherited from Clearable< MulticastAddress >
void Clear (void)
Data Fields inherited from otNetifMulticastAddress
otIp6Address mAddress
The IPv6 multicast address.
const struct otNetifMulticastAddress * mNext
A pointer to the next network interface multicast address.
Member Function Documentation
GetNext()
ExternalMulticastAddress* GetNext (void) inline private
References ot::AsNonConst(), otNetifAddress::mNext, Netif::Netif(), and Netif::SetAddressCallback().
Friends And Related Function Documentation
Netif
friend class Netif friend
LinkedList< ExternalMulticastAddress >
friend class LinkedList< ExternalMulticastAddress > friend
The documentation for this class was generated from the following file:
netif.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale