OpenThread: Buffer Class Reference
Buffer Class Reference
#include <spinel_buffer.hpp>
Data Structures
struct WritePosition
Public Types
typedef void(* BufferCallback) (void *aContext, FrameTag aTag, Priority aPriority, Buffer *aBuffer)
typedef const void * FrameTag
enum Priority { kPriorityLow = 0, kPriorityHigh = 1 }
Public Member Functions
Buffer (uint8_t *aBuffer, uint16_t aBufferLength)
void Clear (void)
void InFrameBegin (Priority aPriority)
otError InFrameEnd (void)
otError InFrameFeedByte (uint8_t aByte)
otError InFrameFeedData (const uint8_t *aDataBuffer, uint16_t aDataBufferLength)
uint16_t InFrameGetDistance (const WritePosition &aPosition) const
FrameTag InFrameGetLastTag (void) const
otError InFrameGetPosition (WritePosition &aPosition)
otError InFrameOverwrite (const WritePosition &aPosition, const uint8_t *aDataBuffer, uint16_t aDataBufferLength)
otError InFrameReset (const WritePosition &aPosition)
bool IsEmpty (void) const
otError OutFrameBegin (void)
uint16_t OutFrameGetLength (void)
FrameTag OutFrameGetTag (void)
bool OutFrameHasEnded (void)
uint16_t OutFrameRead (uint16_t aReadLength, uint8_t *aDataBuffer)
uint8_t OutFrameReadByte (void)
otError OutFrameRemove (void)
void SetFrameAddedCallback (BufferCallback aFrameAddedCallback, void *aFrameAddedContext)
void SetFrameRemovedCallback (BufferCallback aFrameRemovedCallback, void *aFrameRemovedContext)
Static Public Attributes
static const FrameTag kInvalidTag = nullptr
Private Types
enum {
kReadByteAfterFrameHasEnded = 0, kMessageReadBufferSize = 16, kUnknownFrameLength = 0xffff, kSegmentHeaderSize = 2,
kSegmentHeaderLengthMask = 0x3fff, kMaxSegments = 10, kSegmentHeaderNoFlag = 0, kSegmentHeaderNewFrameFlag = (1 << 15),
kSegmentHeaderMessageIndicatorFlag = (1 << 14), kNumPrios = (kPriorityHigh + 1)
}
enum Direction { kForward = kPriorityLow, kBackward = kPriorityHigh, kUnknown }
enum ReadState { kReadStateNotActive, kReadStateInSegment, kReadStateInMessage, kReadStateDone }
Private Member Functions
uint16_t GetDistance (const uint8_t *aStartPtr, const uint8_t *aEndPtr, Direction aDirection) const
uint8_t * GetUpdatedBufPtr (uint8_t *aBufPtr, uint16_t aOffset, Direction aDirection) const
bool HasFrame (Priority aPriority) const
otError InFrameAppend (uint8_t aByte)
otError InFrameBeginSegment (void)
void InFrameDiscard (void)
void InFrameEndSegment (uint16_t aSegmentHeaderFlags)
bool InFrameIsWriting (Priority aPriority) const
void OutFrameMoveToNextSegment (void)
otError OutFramePrepareSegment (void)
void OutFrameSelectReadDirection (void)
uint16_t ReadUint16At (uint8_t *aBufPtr, Direction aDirection)
void UpdateReadWriteStartPointers (void)
void WriteUint16At (uint8_t *aBufPtr, uint16_t aValue, Direction aDirection)
Private Attributes
uint8_t *const mBuffer
uint8_t *const mBufferEnd
const uint16_t mBufferLength
BufferCallback mFrameAddedCallback
void * mFrameAddedContext
BufferCallback mFrameRemovedCallback
void * mFrameRemovedContext
Direction mReadDirection
uint16_t mReadFrameLength
uint8_t * mReadFrameStart [kNumPrios]
uint8_t * mReadPointer
uint8_t * mReadSegmentHead
uint8_t * mReadSegmentTail
ReadState mReadState
Direction mWriteDirection
uint8_t * mWriteFrameStart [kNumPrios]
FrameTag mWriteFrameTag
uint8_t * mWriteSegmentHead
uint8_t * mWriteSegmentTail
Friends
class Encoder
Detailed Description
This class implements a buffer/queue for storing Ncp frames.
A frame can consist of a sequence of data bytes and/or the content of an otMessage or a combination of the two. Buffer implements priority FIFO logic for storing and reading frames. Two priority levels of high and low are supported. Within same priority level first-in-first-out order is preserved. High priority frames are read ahead of any low priority ones.
Member Typedef Documentation
FrameTag
typedef const void* FrameTag
Defines the (abstract) frame tag type. The tag is a unique value (within currently queued frames) associated with a frame in the Buffer. Frame tags can be compared with one another using operator ==.
BufferCallback
typedef void(* BufferCallback) (void *aContext, FrameTag aTag, Priority aPriority, Buffer *aBuffer)
Defines a function pointer callback which is invoked to inform a change in Buffer either when a new frame is added/written to Buffer or when a frame is removed from Buffer.
Parameters
[in] aContext A pointer to arbitrary context information.
[in] aTag The tag associated with the frame which is added or removed.
[in] aPriority The priority of frame.
[in] aBuffer A pointer to the Buffer.
Member Enumeration Documentation
Priority
enum Priority
Defines the priority of a frame. High priority frames are read before low priority frames. Within same priority level FIFO order is preserved.
Enumerator
kPriorityLow
Indicates low/normal priority for a frame.
kPriorityHigh
Indicates high priority for a frame.
anonymous enum
anonymous enum private
Enumerator
kReadByteAfterFrameHasEnded
kMessageReadBufferSize
kUnknownFrameLength
kSegmentHeaderSize
kSegmentHeaderLengthMask
kMaxSegments
kSegmentHeaderNoFlag
kSegmentHeaderNewFrameFlag
kSegmentHeaderMessageIndicatorFlag
kNumPrios
ReadState
enum ReadState private
Enumerator
kReadStateNotActive
kReadStateInSegment
kReadStateInMessage
kReadStateDone
Direction
enum Direction private
Enumerator
kForward
kBackward
kUnknown
Constructor & Destructor Documentation
Buffer()
Buffer (uint8_t * aBuffer, uint16_t aBufferLength)
This constructor initializes an NCP frame buffer.
Parameters
[in] aBuffer A pointer to a buffer which will be used by NCP frame buffer.
[in] aBufferLength The buffer size (in bytes).
References Buffer::Clear(), otMessageQueueInit(), Buffer::SetFrameAddedCallback(), and Buffer::SetFrameRemovedCallback().
Member Function Documentation
Clear()
void Clear (void)
This method clears the NCP frame buffer. All the frames are cleared/removed.
References Buffer::GetUpdatedBufPtr(), Buffer::kBackward, Buffer::kForward, Buffer::kInvalidTag, Buffer::kPriorityHigh, Buffer::kPriorityLow, Buffer::kReadStateNotActive, Buffer::kUnknown, Buffer::kUnknownFrameLength, Buffer::mBuffer, Buffer::mReadDirection, Buffer::mReadFrameLength, Buffer::mReadFrameStart, Buffer::mReadPointer, Buffer::mReadSegmentHead, Buffer::mReadSegmentTail, Buffer::mReadState, Buffer::mWriteDirection, Buffer::mWriteFrameStart, Buffer::mWriteFrameTag, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, otMessageFree(), otMessageQueueDequeue(), and otMessageQueueGetHead().
Referenced by Buffer::Buffer().
SetFrameAddedCallback()
void SetFrameAddedCallback (BufferCallback aFrameAddedCallback, void * aFrameAddedContext)
This method sets the FrameAdded callback and its context.
Subsequent calls to this method will overwrite the previous callback and its context.
Parameters
[in] aFrameAddedCallback Callback invoked when a new frame is successfully added to buffer.
[in] aFrameAddedContext A pointer to arbitrary context used with frame added callback.
References Buffer::mFrameAddedCallback, and Buffer::mFrameAddedContext.
Referenced by Buffer::Buffer().
SetFrameRemovedCallback()
void SetFrameRemovedCallback (BufferCallback aFrameRemovedCallback, void * aFrameRemovedContext)
This method sets the FrameRemoved callback and its context.
Subsequent calls to this method will overwrite the previous callback and its context.
Parameters
[in] aFrameRemovedCallback Callback invoked when a frame is removed from buffer.
[in] aFrameRemovedContext A pointer to arbitrary context used with frame removed callback.
References Buffer::mFrameRemovedCallback, and Buffer::mFrameRemovedContext.
Referenced by Buffer::Buffer(), and NcpBase::NcpBase().
InFrameBegin()
void InFrameBegin (Priority aPriority)
This method begins a new input frame (InFrame) to be added/written to the frame buffer.
If there is a previous frame being written (for which InFrameEnd() has not yet been called), calling InFrameBegin() will discard and clear the previous unfinished frame.
Parameters
[in] aPriority Priority level of the new input frame.
References Buffer::InFrameDiscard(), Buffer::kBackward, Buffer::kForward, Buffer::kPriorityHigh, Buffer::kPriorityLow, Buffer::mWriteDirection, Buffer::mWriteFrameStart, Buffer::mWriteSegmentHead, and Buffer::mWriteSegmentTail.
Referenced by Encoder::BeginFrame().
InFrameFeedByte()
otError InFrameFeedByte (uint8_t aByte)
This method adds a single byte to current input frame.
Before using this method InFrameBegin() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aByte The byte value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given byte to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the byte.
OT_ERROR_INVALID_STATE InFrameBegin() has not been called earlier to start the frame.
References Buffer::InFrameAppend(), Buffer::InFrameBeginSegment(), Buffer::kUnknown, Buffer::mWriteDirection, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by Encoder::OpenStruct(), Encoder::WriteBool(), Encoder::WriteUint16(), Encoder::WriteUint32(), Encoder::WriteUint64(), Encoder::WriteUint8(), and Encoder::WriteUtf8().
InFrameFeedData()
otError InFrameFeedData (const uint8_t * aDataBuffer, uint16_t aDataBufferLength)
This method adds data to the current input frame.
Before using this method InFrameBegin() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aDataBuffer A pointer to data buffer.
[in] aDataBufferLength The length of the data buffer.
Return values
OT_ERROR_NONE Successfully added new data to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add data.
OT_ERROR_INVALID_STATE InFrameBegin() has not been called earlier to start the frame.
References Buffer::InFrameAppend(), Buffer::InFrameBeginSegment(), Buffer::InFrameEndSegment(), Buffer::kSegmentHeaderMessageIndicatorFlag, Buffer::kUnknown, Buffer::mWriteDirection, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, otMessageQueueEnqueue(), SuccessOrExit, and VerifyOrExit.
Referenced by Encoder::WriteData(), Encoder::WritePacked(), and Encoder::WriteVPacked().
InFrameGetPosition()
otError InFrameGetPosition (WritePosition & aPosition)
This method gets the current write position in the input frame.
The write position is returned in aPosition. The saved position can later be used to overwrite the frame content (using InFrameOverwrite()) or discard a portion of written frame and move the write pointer back to the saved position (using InFrameReset()).
Parameters
[out] aPosition A reference to a WritePosition to save the current write position.
Return values
OT_ERROR_NONE Successfully saved current write position in aPosition.
OT_ERROR_INVALID_STATE InFrameBegin() has not been called earlier to start the frame.
References Buffer::InFrameBeginSegment(), Buffer::kUnknown, Buffer::WritePosition::mPosition, Buffer::WritePosition::mSegmentHead, Buffer::mWriteDirection, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by Encoder::OpenStruct(), and Encoder::SavePosition().
InFrameOverwrite()
otError InFrameOverwrite (const WritePosition & aPosition, const uint8_t * aDataBuffer, uint16_t aDataBufferLength)
This method overwrites the previously written content in the current input frame at a given write position.
The write position aPostion must belong to the same input frame saved earlier with InFrameGetPosition(). This method does not allow writing beyond the current end of the input frame (i.e., it can only write over previously added content). If writing aDataBufferLength bytes from write position aPosition goes beyond the end, this method does not change the input frame and returns error status OT_ERROR_INVALID_ARGS. This method cannot be used if the input frame has an added otMessage (i.e., a previous call to InFrameFeedMessage()).
Parameters
[in] aPosition A reference to the write position.
[in] aDataBuffer A pointer to data buffer.
[in] aDataBufferLength The length of the data buffer.
Return values
OT_ERROR_NONE Successfully overwrote the data at the given write position.
OT_ERROR_INVALID_STATE No input frame (InFrameBegin() has not been called).
OT_ERROR_INVALID_ARGS The given write position is not valid (i.e., if it does not belong to same input frame), or the input frame has an added otMessage, or the write operation will go beyond the current end of the input frame.
References Buffer::GetDistance(), Buffer::GetUpdatedBufPtr(), Buffer::kUnknown, Buffer::WritePosition::mPosition, Buffer::WritePosition::mSegmentHead, Buffer::mWriteDirection, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, and VerifyOrExit.
Referenced by Encoder::CloseStruct().
InFrameReset()
otError InFrameReset (const WritePosition & aPosition)
This method resets the write position of input frame back to a previously saved position. Any previously added content after the write position is discarded.
The write position aPosition must belong to the same input frame saved earlier with InFrameGetPosition(). This method cannot be used if the input frame has an added otMessage (i.e., a previous call to InFrameFeedMessage()).
Parameters
[in] aPosition A reference to write position
Return values
OT_ERROR_NONE Successfully reset the write position of current input frame..
OT_ERROR_INVALID_STATE No input frame (InFrameBegin() has not been called).
OT_ERROR_INVALID_ARGS The given write position is not valid (does not belong to same input frame), or the input frame has an added otMessage.
References Buffer::GetDistance(), Buffer::kUnknown, Buffer::WritePosition::mPosition, Buffer::WritePosition::mSegmentHead, Buffer::mWriteDirection, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, and VerifyOrExit.
Referenced by Encoder::ResetToSaved().
InFrameGetDistance()
uint16_t InFrameGetDistance (const WritePosition & aPosition) const
This method gets the distance (number of bytes) from a given saved position to current end of frame.
The write position aPosition must belong to the same input frame saved earlier with InFrameGetPosition(). This method cannot be used if the input frame has an added otMessage (i.e., a previous call to InFrameFeedMessage()). In case of invalid argument, this method returns zero.
Parameters
[in] aPosition A reference to write position
Returns
The distance (number of bytes) from a write position to current end of frame, or zero for invalid arguments.
References Buffer::GetDistance(), Buffer::kUnknown, Buffer::WritePosition::mPosition, Buffer::WritePosition::mSegmentHead, Buffer::mWriteDirection, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, and VerifyOrExit.
Referenced by Encoder::CloseStruct().
InFrameEnd()
otError InFrameEnd (void)
This method finalizes/ends the current input frame being written to the buffer.
Before using this method InFrameBegin() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the frame and return error status OT_ERROR_NO_BUFS.
Return values
OT_ERROR_NONE Successfully ended the input frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add message.
OT_ERROR_INVALID_STATE InFrameBegin() has not been called earlier to start the frame.
References Buffer::InFrameEndSegment(), Buffer::kSegmentHeaderNoFlag, Buffer::kUnknown, Buffer::mFrameAddedCallback, Buffer::mFrameAddedContext, Buffer::mWriteDirection, Buffer::mWriteFrameStart, Buffer::mWriteFrameTag, Buffer::mWriteSegmentHead, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, otMessageQueueDequeue(), otMessageQueueEnqueue(), otMessageQueueGetHead(), and VerifyOrExit.
Referenced by Encoder::EndFrame().
InFrameGetLastTag()
Buffer::FrameTag InFrameGetLastTag (void) const
This method returns the tag assigned to last successfully written/added frame to NcpBuffer (i.e., last input frame for which InFrameEnd() was called and returned success status). The tag is a unique value (within currently queued frames) associated with a frame in the Buffer. The tag can be used to identify the same frame when it is read and removed from the NcpBuffer. Tags can be compared using operator ==.
Returns
The tag of the last successfully written frame, or kInvalidTag if no frame is written so far.
References Buffer::mWriteFrameTag.
Referenced by NcpBase::GetLastOutboundFrameTag().
IsEmpty()
bool IsEmpty (void) const
This method checks if the buffer is empty. A non-empty buffer contains at least one full frame for reading.
Return values
TRUE Buffer is not empty and contains at least one full frame for reading.
FALSE Buffer is empty and contains no frame for reading.
References Buffer::HasFrame(), Buffer::kPriorityHigh, and Buffer::kPriorityLow.
Referenced by Buffer::OutFrameBegin(), Buffer::OutFrameGetLength(), Buffer::OutFrameGetTag(), and Buffer::OutFrameRemove().
OutFrameBegin()
otError OutFrameBegin (void)
This method begins/prepares an output frame to be read from the frame buffer if there is no current active output frame, or resets the read offset if there is a current active output frame.
The NCP buffer maintains a read offset for the current frame being read. Before reading any bytes from the frame this method should be called to prepare the frame and set the read offset.
If part or even all of current frame has been read, a sub-sequent call to this method will reset the read offset back to beginning of current output frame (note that the current output frame will remain unchanged even in case where a higher priority frame was written to buffer while reading current output frame). A prepared output frame will stay active as current output frame until it is explicitly removed using OutFrameRemove().
Return values
OT_ERROR_NONE Successfully started/prepared a new output frame for reading.
OT_ERROR_NOT_FOUND No frame available in buffer for reading.
References Buffer::IsEmpty(), Buffer::mReadDirection, Buffer::mReadFrameStart, Buffer::mReadSegmentHead, Buffer::mReadSegmentTail, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, Buffer::OutFramePrepareSegment(), Buffer::OutFrameSelectReadDirection(), and VerifyOrExit.
OutFrameHasEnded()
bool OutFrameHasEnded (void)
This method checks if the current output frame (being read) has ended.
The NCP buffer maintains a read offset for the current output frame being read. This method returns true if the read offset has reached the end of the frame and there are no more bytes available to read, or if there is no currently active output frame.
Return values
TRUE Frame has ended (no more bytes available to read from current output frame), or there is currently no prepared/active output frame.
FALSE Frame still has more data to read.
References Buffer::kReadStateDone, Buffer::kReadStateNotActive, and Buffer::mReadState.
Referenced by Buffer::OutFrameRead().
OutFrameReadByte()
uint8_t OutFrameReadByte (void)
This method reads and returns the next byte from the current output frame.
The NCP buffer maintains a read offset for the current output frame being read. This method reads and returns the next byte from the current frame and moves the read offset forward. If read offset is already at the end current output frame, this method returns zero.
Returns
The next byte from the current output frame or zero if current output frame has ended or there is prepared/active output from.
References Buffer::GetUpdatedBufPtr(), IgnoreError(), Buffer::kReadByteAfterFrameHasEnded, Buffer::kReadStateDone, Buffer::kReadStateInMessage, Buffer::kReadStateInSegment, Buffer::kReadStateNotActive, Buffer::mReadDirection, Buffer::mReadPointer, Buffer::mReadSegmentTail, Buffer::mReadState, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_FALL_THROUGH, and Buffer::OutFramePrepareSegment().
Referenced by Buffer::OutFrameRead().
OutFrameRead()
uint16_t OutFrameRead (uint16_t aReadLength, uint8_t * aDataBuffer)
This method reads and copies bytes from the current output frame into a given buffer.
The NCP buffer maintains a read offset for the current output frame being read. This method attempts to read the given number of bytes (aReadLength) from the current frame and copies the bytes into the given data buffer (aDataBuffer). It also moves the read offset forward accordingly. If there are fewer bytes remaining in current frame than the requested aReadLength, the available bytes are read/copied. This methods returns the number of bytes read from frame and copied into aDataBuffer.
Parameters
[in] aReadLength Number of bytes to read.
[out] aDataBuffer A pointer to a data buffer.
Returns
The number of bytes read and copied into data buffer.
References Buffer::OutFrameHasEnded(), and Buffer::OutFrameReadByte().
OutFrameRemove()
otError OutFrameRemove (void)
This method removes the current or front output frame from the buffer.
If there is an active output from being read (an output frame was prepared earlier with a successful call to OutFrameBegin()), this method removes the current active output frame. If there is no current active frame, the front frame in the queue (the next frame which would have been read) will be removed.
When a frame is removed all its associated messages will be freed.
If the remove operation is successful, this method will invoke the FrameRemovedCallback (if not nullptr) before returning the success state.
Return values
OT_ERROR_NONE Successfully removed the front frame.
OT_ERROR_NOT_FOUND No frame available in NCP frame buffer to remove.
References Buffer::GetUpdatedBufPtr(), Buffer::IsEmpty(), Buffer::kMaxSegments, Buffer::kReadStateNotActive, Buffer::kSegmentHeaderLengthMask, Buffer::kSegmentHeaderMessageIndicatorFlag, Buffer::kSegmentHeaderNewFrameFlag, Buffer::kSegmentHeaderSize, Buffer::kUnknownFrameLength, Buffer::mFrameRemovedCallback, Buffer::mFrameRemovedContext, Buffer::mReadDirection, Buffer::mReadFrameLength, Buffer::mReadFrameStart, Buffer::mReadState, Buffer::mWriteFrameStart, OT_ASSERT, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, otMessageFree(), otMessageQueueDequeue(), otMessageQueueGetHead(), Buffer::OutFrameSelectReadDirection(), Buffer::ReadUint16At(), Buffer::UpdateReadWriteStartPointers(), and VerifyOrExit.
OutFrameGetLength()
uint16_t OutFrameGetLength (void)
This method returns the number of bytes (length) of current or front frame in the NCP frame buffer.
If there is an active output from being read (an output frame was prepared earlier with successful call to OutFrameBegin()), this method returns the length of the current output frame. If there is no current active frame, the length of the front frame in the queue (the next frame which would have been read) will be returned.
If there is no frame in buffer, this method returns zero.
Returns
The number of bytes (length) of current/front frame, or zero if no frame in buffer.
References Buffer::GetUpdatedBufPtr(), Buffer::IsEmpty(), Buffer::kMaxSegments, Buffer::kReadStateNotActive, Buffer::kSegmentHeaderLengthMask, Buffer::kSegmentHeaderMessageIndicatorFlag, Buffer::kSegmentHeaderNewFrameFlag, Buffer::kSegmentHeaderSize, Buffer::kUnknownFrameLength, Buffer::mReadDirection, Buffer::mReadFrameLength, Buffer::mReadFrameStart, Buffer::mReadState, Buffer::mWriteFrameStart, OT_ASSERT, otMessageGetLength(), otMessageQueueGetHead(), otMessageQueueGetNext(), Buffer::OutFrameSelectReadDirection(), Buffer::ReadUint16At(), and VerifyOrExit.
OutFrameGetTag()
Buffer::FrameTag OutFrameGetTag (void)
This method returns the tag value associated to current or front frame in the NCP frame buffer.
If there is an active output from being read (an output frame was prepared earlier with successful call to OutFrameBegin()), this method returns the tag associated with current output frame. If there is no current active frame, the tag associated with the front frame in the queue (the next frame which would have been read) will be returned.
If there is no frame in buffer, this method returns kInvalidTag.
Returns
The tag assigned to the current/from output frame, or kInvalidTag if no frame in buffer.
References Buffer::IsEmpty(), Buffer::kInvalidTag, Buffer::mReadDirection, Buffer::mReadFrameStart, and Buffer::OutFrameSelectReadDirection().
GetUpdatedBufPtr()
uint8_t * GetUpdatedBufPtr (uint8_t * aBufPtr, uint16_t aOffset, Direction aDirection) const private
References Buffer::kBackward, Buffer::kForward, Buffer::kUnknown, Buffer::mBuffer, Buffer::mBufferEnd, Buffer::mBufferLength, OT_ASSERT, and OT_UNREACHABLE_CODE.
Referenced by Buffer::Clear(), Buffer::InFrameAppend(), Buffer::InFrameOverwrite(), Buffer::OutFrameGetLength(), Buffer::OutFramePrepareSegment(), Buffer::OutFrameReadByte(), Buffer::OutFrameRemove(), Buffer::ReadUint16At(), Buffer::UpdateReadWriteStartPointers(), and Buffer::WriteUint16At().
GetDistance()
uint16_t GetDistance (const uint8_t * aStartPtr, const uint8_t * aEndPtr, Direction aDirection) const private
References Buffer::kBackward, Buffer::kForward, Buffer::kUnknown, Buffer::mBuffer, Buffer::mBufferEnd, OT_ASSERT, and OT_UNREACHABLE_CODE.
Referenced by Buffer::InFrameEndSegment(), Buffer::InFrameGetDistance(), Buffer::InFrameOverwrite(), and Buffer::InFrameReset().
ReadUint16At()
uint16_t ReadUint16At (uint8_t * aBufPtr, Direction aDirection) private
References Buffer::GetUpdatedBufPtr().
Referenced by Buffer::InFrameEndSegment(), Buffer::OutFrameGetLength(), Buffer::OutFramePrepareSegment(), and Buffer::OutFrameRemove().
WriteUint16At()
void WriteUint16At (uint8_t * aBufPtr, uint16_t aValue, Direction aDirection) private
References Buffer::GetUpdatedBufPtr().
Referenced by Buffer::InFrameBeginSegment(), and Buffer::InFrameEndSegment().
HasFrame()
bool HasFrame (Priority aPriority) const private
References Buffer::mReadFrameStart, and Buffer::mWriteFrameStart.
Referenced by Buffer::IsEmpty(), Buffer::OutFrameSelectReadDirection(), and Buffer::UpdateReadWriteStartPointers().
UpdateReadWriteStartPointers()
void UpdateReadWriteStartPointers (void) private
References ExitNow, Buffer::GetUpdatedBufPtr(), Buffer::HasFrame(), Buffer::InFrameIsWriting(), Buffer::kBackward, Buffer::kForward, Buffer::kPriorityHigh, Buffer::kPriorityLow, Buffer::mReadFrameStart, and Buffer::mWriteFrameStart.
Referenced by Buffer::InFrameDiscard(), and Buffer::OutFrameRemove().
InFrameAppend()
otError InFrameAppend (uint8_t aByte) private
References Buffer::GetUpdatedBufPtr(), Buffer::InFrameDiscard(), Buffer::kBackward, Buffer::kForward, Buffer::kUnknown, Buffer::mWriteDirection, Buffer::mWriteFrameStart, Buffer::mWriteSegmentTail, OT_ASSERT, OT_ERROR_NO_BUFS, and OT_ERROR_NONE.
Referenced by Buffer::InFrameBeginSegment(), Buffer::InFrameFeedByte(), and Buffer::InFrameFeedData().
InFrameBeginSegment()
otError InFrameBeginSegment (void) private
References Buffer::InFrameAppend(), Buffer::kSegmentHeaderNewFrameFlag, Buffer::kSegmentHeaderNoFlag, Buffer::kSegmentHeaderSize, Buffer::mWriteDirection, Buffer::mWriteFrameStart, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, OT_ERROR_NONE, SuccessOrExit, VerifyOrExit, and Buffer::WriteUint16At().
Referenced by Buffer::InFrameFeedByte(), Buffer::InFrameFeedData(), and Buffer::InFrameGetPosition().
InFrameEndSegment()
void InFrameEndSegment (uint16_t aSegmentHeaderFlags) private
References Buffer::GetDistance(), Buffer::kSegmentHeaderLengthMask, Buffer::kSegmentHeaderSize, Buffer::mWriteDirection, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, Buffer::ReadUint16At(), and Buffer::WriteUint16At().
Referenced by Buffer::InFrameEnd(), and Buffer::InFrameFeedData().
InFrameDiscard()
void InFrameDiscard (void) private
References Buffer::kUnknown, Buffer::mWriteDirection, Buffer::mWriteFrameStart, Buffer::mWriteSegmentHead, Buffer::mWriteSegmentTail, otMessageQueueDequeue(), otMessageQueueGetHead(), Buffer::UpdateReadWriteStartPointers(), and VerifyOrExit.
Referenced by Buffer::InFrameAppend(), and Buffer::InFrameBegin().
InFrameIsWriting()
bool InFrameIsWriting (Priority aPriority) const private
References Buffer::mWriteDirection.
Referenced by Buffer::UpdateReadWriteStartPointers().
OutFrameSelectReadDirection()
void OutFrameSelectReadDirection (void) private
References Buffer::HasFrame(), Buffer::kBackward, Buffer::kForward, Buffer::kPriorityHigh, Buffer::kReadStateNotActive, Buffer::mReadDirection, and Buffer::mReadState.
Referenced by Buffer::OutFrameBegin(), Buffer::OutFrameGetLength(), Buffer::OutFrameGetTag(), and Buffer::OutFrameRemove().
OutFramePrepareSegment()
otError OutFramePrepareSegment (void) private
References ExitNow, Buffer::GetUpdatedBufPtr(), Buffer::kReadStateDone, Buffer::kReadStateInMessage, Buffer::kReadStateInSegment, Buffer::kSegmentHeaderLengthMask, Buffer::kSegmentHeaderMessageIndicatorFlag, Buffer::kSegmentHeaderNewFrameFlag, Buffer::kSegmentHeaderSize, Buffer::mReadDirection, Buffer::mReadFrameStart, Buffer::mReadPointer, Buffer::mReadSegmentHead, Buffer::mReadSegmentTail, Buffer::mReadState, Buffer::mWriteFrameStart, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, otMessageGetLength(), otMessageQueueGetHead(), otMessageQueueGetNext(), otMessageRead(), Buffer::ReadUint16At(), SuccessOrExit, and VerifyOrExit.
Referenced by Buffer::OutFrameBegin(), and Buffer::OutFrameReadByte().
OutFrameMoveToNextSegment()
void OutFrameMoveToNextSegment (void) private
Friends And Related Function Documentation
Encoder
friend class Encoder friend
Field Documentation
kInvalidTag
const Buffer::FrameTag kInvalidTag = nullptr static
Defines the tag value indicating an invalid tag (e.g., when there is no frame).
Referenced by Buffer::Clear(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), and Buffer::OutFrameGetTag().
mBuffer
uint8_t* const mBuffer private
Referenced by Buffer::Clear(), Buffer::GetDistance(), and Buffer::GetUpdatedBufPtr().
mBufferEnd
uint8_t* const mBufferEnd private
Referenced by Buffer::GetDistance(), and Buffer::GetUpdatedBufPtr().
mBufferLength
const uint16_t mBufferLength private
Referenced by Buffer::GetUpdatedBufPtr().
mFrameAddedCallback
BufferCallback mFrameAddedCallback private
Referenced by Buffer::InFrameEnd(), and Buffer::SetFrameAddedCallback().
mFrameAddedContext
void* mFrameAddedContext private
Referenced by Buffer::InFrameEnd(), and Buffer::SetFrameAddedCallback().
mFrameRemovedCallback
BufferCallback mFrameRemovedCallback private
Referenced by Buffer::OutFrameRemove(), and Buffer::SetFrameRemovedCallback().
mFrameRemovedContext
void* mFrameRemovedContext private
Referenced by Buffer::OutFrameRemove(), and Buffer::SetFrameRemovedCallback().
mWriteDirection
Direction mWriteDirection private
Referenced by Buffer::Clear(), Buffer::InFrameAppend(), Buffer::InFrameBegin(), Buffer::InFrameBeginSegment(), Buffer::InFrameDiscard(), Buffer::InFrameEnd(), Buffer::InFrameEndSegment(), Buffer::InFrameFeedByte(), Buffer::InFrameFeedData(), Buffer::InFrameGetDistance(), Buffer::InFrameGetPosition(), Buffer::InFrameIsWriting(), Buffer::InFrameOverwrite(), and Buffer::InFrameReset().
mWriteFrameStart
uint8_t* mWriteFrameStart[kNumPrios] private
Referenced by Buffer::Clear(), Buffer::HasFrame(), Buffer::InFrameAppend(), Buffer::InFrameBegin(), Buffer::InFrameBeginSegment(), Buffer::InFrameDiscard(), Buffer::InFrameEnd(), Buffer::OutFrameGetLength(), Buffer::OutFramePrepareSegment(), Buffer::OutFrameRemove(), and Buffer::UpdateReadWriteStartPointers().
mWriteSegmentHead
uint8_t* mWriteSegmentHead private
Referenced by Buffer::Clear(), Buffer::InFrameBegin(), Buffer::InFrameBeginSegment(), Buffer::InFrameDiscard(), Buffer::InFrameEnd(), Buffer::InFrameEndSegment(), Buffer::InFrameGetDistance(), Buffer::InFrameGetPosition(), Buffer::InFrameOverwrite(), and Buffer::InFrameReset().
mWriteSegmentTail
uint8_t* mWriteSegmentTail private
Referenced by Buffer::Clear(), Buffer::InFrameAppend(), Buffer::InFrameBegin(), Buffer::InFrameBeginSegment(), Buffer::InFrameDiscard(), Buffer::InFrameEndSegment(), Buffer::InFrameGetDistance(), Buffer::InFrameGetPosition(), Buffer::InFrameOverwrite(), and Buffer::InFrameReset().
mWriteFrameTag
FrameTag mWriteFrameTag private
Referenced by Buffer::Clear(), Buffer::InFrameEnd(), and Buffer::InFrameGetLastTag().
mReadDirection
Direction mReadDirection private
Referenced by Buffer::Clear(), Buffer::OutFrameBegin(), Buffer::OutFrameGetLength(), Buffer::OutFrameGetTag(), Buffer::OutFramePrepareSegment(), Buffer::OutFrameReadByte(), Buffer::OutFrameRemove(), and Buffer::OutFrameSelectReadDirection().
mReadState
ReadState mReadState private
Referenced by Buffer::Clear(), Buffer::OutFrameGetLength(), Buffer::OutFrameHasEnded(), Buffer::OutFramePrepareSegment(), Buffer::OutFrameReadByte(), Buffer::OutFrameRemove(), and Buffer::OutFrameSelectReadDirection().
mReadFrameLength
uint16_t mReadFrameLength private
Referenced by Buffer::Clear(), Buffer::OutFrameGetLength(), and Buffer::OutFrameRemove().
mReadFrameStart
uint8_t* mReadFrameStart[kNumPrios] private
Referenced by Buffer::Clear(), Buffer::HasFrame(), Buffer::OutFrameBegin(), Buffer::OutFrameGetLength(), Buffer::OutFrameGetTag(), Buffer::OutFramePrepareSegment(), Buffer::OutFrameRemove(), and Buffer::UpdateReadWriteStartPointers().
mReadSegmentHead
uint8_t* mReadSegmentHead private
Referenced by Buffer::Clear(), Buffer::OutFrameBegin(), and Buffer::OutFramePrepareSegment().
mReadSegmentTail
uint8_t* mReadSegmentTail private
Referenced by Buffer::Clear(), Buffer::OutFrameBegin(), Buffer::OutFramePrepareSegment(), and Buffer::OutFrameReadByte().
mReadPointer
uint8_t* mReadPointer private
Referenced by Buffer::Clear(), Buffer::OutFramePrepareSegment(), and Buffer::OutFrameReadByte().
The documentation for this class was generated from the following files:
spinel_buffer.hpp
spinel_buffer.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale