OpenThread: Dataset::Info Class Reference
Dataset::Info Class Reference
#include <dataset.hpp>
Public Member Functions
Error GenerateRandom (Instance &aInstance)
void GetActiveTimestamp (Timestamp &aTimestamp) const
uint16_t GetChannel (void) const
otChannelMask GetChannelMask (void) const
uint32_t GetDelay (void) const
const ExtendedPanId & GetExtendedPanId (void) const
const Ip6::NetworkPrefix & GetMeshLocalPrefix (void) const
const NetworkKey & GetNetworkKey (void) const
const NetworkName & GetNetworkName (void) const
Mac::PanId GetPanId (void) const
void GetPendingTimestamp (Timestamp &aTimestamp) const
const Pskc & GetPskc (void) const
const SecurityPolicy & GetSecurityPolicy (void) const
bool IsActiveTimestampPresent (void) const
bool IsChannelMaskPresent (void) const
bool IsChannelPresent (void) const
bool IsDelayPresent (void) const
bool IsExtendedPanIdPresent (void) const
bool IsMeshLocalPrefixPresent (void) const
bool IsNetworkKeyPresent (void) const
bool IsNetworkNamePresent (void) const
bool IsPanIdPresent (void) const
bool IsPendingTimestampPresent (void) const
bool IsPskcPresent (void) const
bool IsSecurityPolicyPresent (void) const
bool IsSubsetOf (const Info &aOther) const
void SetActiveTimestamp (const Timestamp &aTimestamp)
void SetChannel (uint16_t aChannel)
void SetChannelMask (otChannelMask aChannelMask)
void SetDelay (uint32_t aDelay)
void SetExtendedPanId (const ExtendedPanId &aExtendedPanId)
void SetMeshLocalPrefix (const Ip6::NetworkPrefix &aMeshLocalPrefix)
void SetNetworkKey (const NetworkKey &aNetworkKey)
void SetNetworkName (const NameData &aNetworkNameData)
void SetPanId (Mac::PanId aPanId)
void SetPendingTimestamp (const Timestamp &aTimestamp)
void SetPskc (const Pskc &aPskc)
void SetSecurityPolicy (const SecurityPolicy &aSecurityPolicy)
NetworkKey & UpdateNetworkKey (void)
Public Member Functions inherited from Clearable< Info >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otOperationalDataset
otTimestamp mActiveTimestamp
Active Timestamp.
uint16_t mChannel
Channel.
otChannelMask mChannelMask
Channel Mask.
otOperationalDatasetComponents mComponents
Specifies which components are set in the Dataset.
uint32_t mDelay
Delay Timer.
otExtendedPanId mExtendedPanId
Extended PAN ID.
otMeshLocalPrefix mMeshLocalPrefix
Mesh Local Prefix.
otNetworkKey mNetworkKey
Network Key.
otNetworkName mNetworkName
Network Name.
otPanId mPanId
PAN ID.
otTimestamp mPendingTimestamp
Pending Timestamp.
otPskc mPskc
PSKc.
otSecurityPolicy mSecurityPolicy
Security Policy.
Detailed Description
This type represents the information about the fields contained an Active or Pending Operational Dataset.
Member Function Documentation
IsActiveTimestampPresent()
bool IsActiveTimestampPresent (void) const inline
This method indicates whether or not the Active Timestamp is present in the Dataset.
Returns
TRUE if Active Timestamp is present, FALSE otherwise.
Referenced by Dataset::SetFrom().
GetActiveTimestamp()
void GetActiveTimestamp (Timestamp & aTimestamp) const inline
This method gets the Active Timestamp in the Dataset.
This method MUST be used when Active Timestamp component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Active Timestamp in the Dataset.
References Timestamp::SetFromTimestamp().
Referenced by Dataset::SetFrom().
SetActiveTimestamp()
void SetActiveTimestamp (const Timestamp & aTimestamp) inline
This method sets the Active Timestamp in the Dataset.
Parameters
[in] aTimestamp A Timestamp value.
References Timestamp::ConvertTo().
Referenced by Dataset::ConvertTo().
IsPendingTimestampPresent()
bool IsPendingTimestampPresent (void) const inline
This method indicates whether or not the Pending Timestamp is present in the Dataset.
Returns
TRUE if Pending Timestamp is present, FALSE otherwise.
Referenced by Dataset::SetFrom().
GetPendingTimestamp()
void GetPendingTimestamp (Timestamp & aTimestamp) const inline
This method gets the Pending Timestamp in the Dataset.
This method MUST be used when Pending Timestamp component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Pending Timestamp in the Dataset.
References Timestamp::SetFromTimestamp().
Referenced by Dataset::SetFrom().
SetPendingTimestamp()
void SetPendingTimestamp (const Timestamp & aTimestamp) inline
This method sets the Pending Timestamp in the Dataset.
Parameters
[in] aTimestamp A Timestamp value.
References Timestamp::ConvertTo().
Referenced by Dataset::ConvertTo().
IsNetworkKeyPresent()
bool IsNetworkKeyPresent (void) const inline
This method indicates whether or not the Network Key is present in the Dataset.
Returns
TRUE if Network Key is present, FALSE otherwise.
Referenced by ActiveDatasetManager::IsCommissioned(), Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetNetworkKey()
const NetworkKey& GetNetworkKey (void) const inline
This method gets the Network Key in the Dataset.
This method MUST be used when Network Key component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Network Key in the Dataset.
References ot::AsCoreType().
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetNetworkKey()
void SetNetworkKey (const NetworkKey & aNetworkKey) inline
This method sets the Network Key in the Dataset.
Parameters
[in] aNetworkKey A Network Key.
Referenced by Dataset::ConvertTo().
UpdateNetworkKey()
NetworkKey& UpdateNetworkKey (void) inline
This method returns a reference to the Network Key in the Dataset to be updated by caller.
Returns
A reference to the Network Key in the Dataset.
References ot::AsCoreType().
IsNetworkNamePresent()
bool IsNetworkNamePresent (void) const inline
This method indicates whether or not the Network Name is present in the Dataset.
Returns
TRUE if Network Name is present, FALSE otherwise.
Referenced by ActiveDatasetManager::IsCommissioned(), Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetNetworkName()
const NetworkName& GetNetworkName (void) const inline
This method gets the Network Name in the Dataset.
This method MUST be used when Network Name component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Network Name in the Dataset.
References ot::AsCoreType().
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetNetworkName()
void SetNetworkName (const NameData & aNetworkNameData) inline
This method sets the Network Name in the Dataset.
Parameters
[in] aNetworkNameData A Network Name Data.
References ot::AsCoreType(), IgnoreError(), and Dataset::Set().
Referenced by Dataset::ConvertTo().
IsExtendedPanIdPresent()
bool IsExtendedPanIdPresent (void) const inline
This method indicates whether or not the Extended PAN ID is present in the Dataset.
Returns
TRUE if Extended PAN ID is present, FALSE otherwise.
Referenced by ActiveDatasetManager::IsCommissioned(), Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetExtendedPanId()
const ExtendedPanId& GetExtendedPanId (void) const inline
This method gets the Extended PAN ID in the Dataset.
This method MUST be used when Extended PAN ID component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Extended PAN ID in the Dataset.
References ot::AsCoreType().
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetExtendedPanId()
void SetExtendedPanId (const ExtendedPanId & aExtendedPanId) inline
This method sets the Extended PAN ID in the Dataset.
Parameters
[in] aExtendedPanId An Extended PAN ID.
Referenced by Dataset::ConvertTo().
IsMeshLocalPrefixPresent()
bool IsMeshLocalPrefixPresent (void) const inline
This method indicates whether or not the Mesh Local Prefix is present in the Dataset.
Returns
TRUE if Mesh Local Prefix is present, FALSE otherwise.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetMeshLocalPrefix()
const Ip6::NetworkPrefix& GetMeshLocalPrefix (void) const inline
This method gets the Mesh Local Prefix in the Dataset.
This method MUST be used when Mesh Local Prefix component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Mesh Local Prefix in the Dataset.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetMeshLocalPrefix()
void SetMeshLocalPrefix (const Ip6::NetworkPrefix & aMeshLocalPrefix) inline
This method sets the Mesh Local Prefix in the Dataset.
Parameters
[in] aMeshLocalPrefix A Mesh Local Prefix.
Referenced by Dataset::ConvertTo().
IsDelayPresent()
bool IsDelayPresent (void) const inline
This method indicates whether or not the Delay Timer is present in the Dataset.
Returns
TRUE if Delay Timer is present, FALSE otherwise.
Referenced by Dataset::SetFrom().
GetDelay()
uint32_t GetDelay (void) const inline
This method gets the Delay Timer in the Dataset.
This method MUST be used when Delay Timer component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Delay Timer in the Dataset.
Referenced by Dataset::SetFrom().
SetDelay()
void SetDelay (uint32_t aDelay) inline
This method sets the Delay Timer in the Dataset.
Parameters
[in] aDelay A Delay value.
Referenced by Dataset::ConvertTo().
IsPanIdPresent()
bool IsPanIdPresent (void) const inline
This method indicates whether or not the PAN ID is present in the Dataset.
Returns
TRUE if PAN ID is present, FALSE otherwise.
Referenced by ActiveDatasetManager::IsCommissioned(), Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetPanId()
Mac::PanId GetPanId (void) const inline
This method gets the PAN ID in the Dataset.
This method MUST be used when PAN ID component is present in the Dataset, otherwise its behavior is undefined.
Returns
The PAN ID in the Dataset.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetPanId()
void SetPanId (Mac::PanId aPanId) inline
This method sets the PAN ID in the Dataset.
Parameters
[in] aPanId A PAN ID.
Referenced by Dataset::ConvertTo().
IsChannelPresent()
bool IsChannelPresent (void) const inline
This method indicates whether or not the Channel is present in the Dataset.
Returns
TRUE if Channel is present, FALSE otherwise.
Referenced by ActiveDatasetManager::IsCommissioned(), Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetChannel()
uint16_t GetChannel (void) const inline
This method gets the Channel in the Dataset.
This method MUST be used when Channel component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Channel in the Dataset.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetChannel()
void SetChannel (uint16_t aChannel) inline
This method sets the Channel in the Dataset.
Parameters
[in] aChannel A Channel.
Referenced by Dataset::ConvertTo().
IsPskcPresent()
bool IsPskcPresent (void) const inline
This method indicates whether or not the PSKc is present in the Dataset.
Returns
TRUE if PSKc is present, FALSE otherwise.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetPskc()
const Pskc& GetPskc (void) const inline
This method gets the PSKc in the Dataset.
This method MUST be used when PSKc component is present in the Dataset, otherwise its behavior is undefined.
Returns
The PSKc in the Dataset.
References ot::AsCoreType().
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetPskc()
void SetPskc (const Pskc & aPskc) inline
This method set the PSKc in the Dataset.
Parameters
[in] aPskc A PSKc value.
Referenced by Dataset::ConvertTo().
IsSecurityPolicyPresent()
bool IsSecurityPolicyPresent (void) const inline
This method indicates whether or not the Security Policy is present in the Dataset.
Returns
TRUE if Security Policy is present, FALSE otherwise.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetSecurityPolicy()
const SecurityPolicy& GetSecurityPolicy (void) const inline
This method gets the Security Policy in the Dataset.
This method MUST be used when Security Policy component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Security Policy in the Dataset.
References ot::AsCoreType().
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetSecurityPolicy()
void SetSecurityPolicy (const SecurityPolicy & aSecurityPolicy) inline
This method sets the Security Policy in the Dataset.
Parameters
[in] aSecurityPolicy A Security Policy to set in Dataset.
Referenced by Dataset::ConvertTo().
IsChannelMaskPresent()
bool IsChannelMaskPresent (void) const inline
This method indicates whether or not the Channel Mask is present in the Dataset.
Returns
TRUE if Channel Mask is present, FALSE otherwise.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
GetChannelMask()
otChannelMask GetChannelMask (void) const inline
This method gets the Channel Mask in the Dataset.
This method MUST be used when Channel Mask component is present in the Dataset, otherwise its behavior is undefined.
Returns
The Channel Mask in the Dataset.
Referenced by Dataset::Info::IsSubsetOf(), and Dataset::SetFrom().
SetChannelMask()
void SetChannelMask (otChannelMask aChannelMask) inline
This method sets the Channel Mask in the Dataset.
Parameters
[in] aChannelMask A Channel Mask value.
References Clearable< Components >::Clear(), Dataset::Dataset(), and Dataset::IsValid().
Referenced by Dataset::ConvertTo().
GenerateRandom()
Error GenerateRandom (Instance & aInstance)
This method populates the Dataset with random fields.
The Network Key, PSKc, Mesh Local Prefix, PAN ID, and Extended PAN ID are generated randomly (crypto-secure) with Network Name set to "OpenThread-%04x" with PAN ID appended as hex. The Channel is chosen randomly from radio's preferred channel mask, Channel Mask is set from radio's supported mask, and Security Policy Flags from current KeyManager value.
Parameters
[in] aInstance The OpenThread instance.
Return values
kErrorNone If the Dataset was generated successfully.
References ot::AsCoreType(), Clearable< Info >::Clear(), ot::Random::Crypto::FillBuffer(), ot::Mac::GenerateRandomPanId(), Instance::Get(), ChannelMask::GetMask(), Radio::GetPreferredChannelMask(), ChannelMask::Intersect(), otNetworkName::m8, otExtendedPanId::m8, otOperationalDataset::mActiveTimestamp, otTimestamp::mAuthoritative, otOperationalDataset::mChannel, otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDataset::mExtendedPanId, otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelMaskPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkKeyPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPskcPresent, otOperationalDatasetComponents::mIsSecurityPolicyPresent, otOperationalDataset::mMeshLocalPrefix, otOperationalDataset::mNetworkKey, otOperationalDataset::mNetworkName, otOperationalDataset::mPanId, otOperationalDataset::mPskc, otTimestamp::mSeconds, otOperationalDataset::mSecurityPolicy, otTimestamp::mTicks, and SuccessOrExit.
Referenced by ActiveDatasetManager::Save().
IsSubsetOf()
bool IsSubsetOf (const Info & aOther) const
This method checks whether the Dataset is a subset of another one, i.e., all the components in the current Dataset are also present in the aOther and the component values fully match.
The matching of components in the two Datasets excludes Active/Pending Timestamp and Delay components.
Parameters
[in] aOther The other Dataset to check against.
Return values
TRUE The current dataset is a subset of aOther.
FALSE The current Dataset is not a subset of aOther.
References Dataset::Info::GetChannel(), Dataset::Info::GetChannelMask(), Dataset::Info::GetExtendedPanId(), Dataset::Info::GetMeshLocalPrefix(), Dataset::Info::GetNetworkKey(), Dataset::Info::GetNetworkName(), Dataset::Info::GetPanId(), Dataset::Info::GetPskc(), Dataset::Info::GetSecurityPolicy(), Dataset::Info::IsChannelMaskPresent(), Dataset::Info::IsChannelPresent(), Dataset::Info::IsExtendedPanIdPresent(), Dataset::Info::IsMeshLocalPrefixPresent(), Dataset::Info::IsNetworkKeyPresent(), Dataset::Info::IsNetworkNamePresent(), Dataset::Info::IsPanIdPresent(), Dataset::Info::IsPskcPresent(), Dataset::Info::IsSecurityPolicyPresent(), and VerifyOrExit.
The documentation for this class was generated from the following files:
dataset.hpp
dataset.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale