OpenThread: Interpreter Class Reference
Interpreter Class Reference
#include <cli.hpp>
Public Types
typedef Utils::CmdLineParser::Arg Arg
Public Types inherited from OutputBase
typedef Utils::CmdLineParser::Arg Arg
An argument.
Public Member Functions
Interpreter (Instance *aInstance, otCliOutputCallback aCallback, void *aContext)
void ProcessLine (char *aBuf)
void SetUserCommands (const otCliCommand *aCommands, uint8_t aLength, void *aContext)
Public Member Functions inherited from Output
otInstance * GetInstancePtr (void)
Output (otInstance *aInstance, otCliOutputCallback aCallback, void *aCallbackContext)
void OutputBytes (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytes (const uint8_t(&aBytes)[kBytesLength])
void OutputBytesLine (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytesLine (const uint8_t(&aBytes)[kBytesLength])
template<typename Cli , uint16_t kLength>
void OutputCommandTable (const CommandEntry< Cli >(&aCommandTable)[kLength])
void OutputEnabledDisabledStatus (bool aEnabled)
void OutputExtAddress (const otExtAddress &aExtAddress)
void OutputExtAddressLine (const otExtAddress &aExtAddress)
void OutputFormat (const char *aFormat,...)
void OutputFormat (uint8_t aIndentSize, const char *aFormat,...)
void OutputLine (const char *aFormat,...)
void OutputLine (uint8_t aIndentSize, const char *aFormat,...)
void OutputSpaces (uint8_t aCount)
template<uint8_t kTableNumColumns>
void OutputTableHeader (const char *const (&aTitles)[kTableNumColumns], const uint8_t(&aWidths)[kTableNumColumns])
template<uint8_t kTableNumColumns>
void OutputTableSeparator (const uint8_t(&aWidths)[kTableNumColumns])
Static Public Member Functions
static const char * AddressOriginToString (uint8_t aOrigin)
static Interpreter & GetInterpreter (void)
static void Initialize (otInstance *aInstance, otCliOutputCallback aCallback, void *aContext)
static bool IsInitialized (void)
static const char * LinkModeToString (const otLinkModeConfig &aLinkMode, char(&aStringBuffer)[kLinkModeStringSize])
static otError ParseEnableOrDisable (const Arg &aArg, bool &aEnable)
static otError ParsePreference (const Arg &aArg, otRoutePreference &aPreference)
static const char * PreferenceToString (signed int aPreference)
Static Public Member Functions inherited from OutputBase
template<typename EnumType , uint16_t kLength>
static const char * Stringify (EnumType aEnum, const char *const (&aTable)[kLength], const char *aNotFound=kUnknownString)
Static Public Attributes
static constexpr uint8_t kLinkModeStringSize = sizeof("rdn")
Size of string buffer for a MLE Link Mode.
Static Public Attributes inherited from OutputBase
static const char kUnknownString [] = "unknown"
Static Protected Attributes
static Interpreter * sInterpreter = nullptr
Private Types
enum { kIndentSize = 4, kMaxArgs = 32, kMaxAutoAddresses = 8, kMaxLineLength = OPENTHREAD_CONFIG_CLI_MAX_LINE_LENGTH }
using Command = CommandEntry< Interpreter >
template<typename ValueType >
using GetHandler = ValueType(otInstance *)
template<typename ValueType >
using SetHandler = void(otInstance *, ValueType)
template<typename ValueType >
using SetHandlerFailable = otError(otInstance *, ValueType)
Private Member Functions
template<>
constexpr const char * FormatStringFor (void)
template<>
constexpr const char * FormatStringFor (void)
template<>
constexpr const char * FormatStringFor (void)
template<>
constexpr const char * FormatStringFor (void)
template<>
constexpr const char * FormatStringFor (void)
template<>
constexpr const char * FormatStringFor (void)
void HandleTimer (void)
void OutputPrompt (void)
void OutputResult (otError aError)
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<CommandId kCommandId>
otError Process (Arg aArgs[])
otError ProcessCommand (Arg aArgs[])
template<typename ValueType >
otError ProcessGet (Arg aArgs[], GetHandler< ValueType > aGetHandler)
template<typename ValueType >
otError ProcessGetSet (Arg aArgs[], GetHandler< ValueType > aGetHandler, SetHandler< ValueType > aSetHandler)
template<typename ValueType >
otError ProcessGetSet (Arg aArgs[], GetHandler< ValueType > aGetHandler, SetHandlerFailable< ValueType > aSetHandler)
template<typename ValueType >
otError ProcessSet (Arg aArgs[], SetHandler< ValueType > aSetHandler)
template<typename ValueType >
otError ProcessSet (Arg aArgs[], SetHandlerFailable< ValueType > aSetHandler)
otError ProcessUserCommands (Arg aArgs[])
void SetCommandTimeout (uint32_t aTimeoutMilli)
Static Private Member Functions
template<typename ValueType >
static constexpr const char * FormatStringFor (void)
static void HandleTimer (Timer &aTimer)
static otError ParseJoinerDiscerner (Arg &aArg, otJoinerDiscerner &aDiscerner)
Private Attributes
bool mCommandIsPending
TimerMilliContext mTimer
const otCliCommand * mUserCommands
void * mUserCommandsContext
uint8_t mUserCommandsLength
Static Private Attributes
static constexpr uint32_t kLocateTimeoutMsecs = 2500
static constexpr uint32_t kNetworkDiagnosticTimeoutMsecs = 5000
Friends
void otCliAppendResult (otError aError)
void otCliOutputBytes (const uint8_t *aBytes, uint8_t aLength)
void otCliOutputFormat (const char *aFmt,...)
void otCliPlatLogv (otLogLevel, otLogRegion, const char *, va_list)
Additional Inherited Members
Protected Member Functions inherited from Output
void LogInput (const Arg *)
void OutputFormatV (const char *aFormat, va_list aArguments)
void SetEmittingCommandOutput (bool)
Protected Member Functions inherited from OutputBase
OutputBase (void)=default
Detailed Description
This class implements the CLI interpreter.
Member Typedef Documentation
Arg
typedef Utils::CmdLineParser::Arg Arg
Command
using Command = CommandEntry<Interpreter> private
GetHandler
using GetHandler = ValueType (otInstance *) private
SetHandler
using SetHandler = void (otInstance *, ValueType) private
SetHandlerFailable
using SetHandlerFailable = otError (otInstance *, ValueType) private
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kIndentSize
kMaxArgs
kMaxAutoAddresses
kMaxLineLength
Constructor & Destructor Documentation
Interpreter()
Interpreter (Instance * aInstance, otCliOutputCallback aCallback, void * aContext) explicit
Constructor
Parameters
[in] aInstance The OpenThread instance structure.
[in] aCallback A callback method called to process CLI output.
[in] aContext A user context pointer.
References Output::GetInstancePtr(), otThreadSetDiscoveryRequestCallback(), and Interpreter::OutputPrompt().
Referenced by Interpreter::Initialize().
Member Function Documentation
GetInterpreter()
static Interpreter& GetInterpreter (void) inline static
This method returns a reference to the interpreter object.
Returns
A reference to the interpreter object.
References Interpreter::Initialize(), OT_ASSERT, and Interpreter::sInterpreter.
Referenced by otCliAppendResult(), otCliInputLine(), otCliOutputBytes(), otCliOutputFormat(), otCliPlatLogv(), and otCliSetUserCommands().
Initialize()
void Initialize (otInstance * aInstance, otCliOutputCallback aCallback, void * aContext) static
This method initializes the Console interpreter.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aCallback A pointer to a callback method.
[in] aContext A pointer to a user context.
References Interpreter::Interpreter().
Referenced by Interpreter::GetInterpreter(), and otCliInit().
IsInitialized()
static bool IsInitialized (void) inline static
This method returns whether the interpreter is initialized.
Returns
Whether the interpreter is initialized.
References Interpreter::ParseEnableOrDisable(), Interpreter::ProcessLine(), Interpreter::SetUserCommands(), and Interpreter::sInterpreter.
Referenced by otCliPlatLogv().
ProcessLine()
void ProcessLine (char * aBuf)
This method interprets a CLI command.
Parameters
[in] aBuf A pointer to a string.
References ExitNow, Output::GetInstancePtr(), Interpreter::kMaxArgs, Interpreter::kMaxLineLength, Output::LogInput(), Interpreter::mCommandIsPending, OT_ASSERT, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_ERROR_PARSE, otDiagIsEnabled(), Output::OutputLine(), Interpreter::OutputPrompt(), Interpreter::OutputResult(), ot::Utils::CmdLineParser::ParseCmd(), Interpreter::ProcessCommand(), ot::StringLength(), SuccessOrExit, and VerifyOrExit.
Referenced by Interpreter::IsInitialized(), and otCliInputLine().
ParseEnableOrDisable()
static otError ParseEnableOrDisable (const Arg & aArg, bool & aEnable) static
This static method checks a given argument string against "enable" or "disable" commands.
Parameters
[in] aArg The argument string to parse.
[out] aEnable Boolean variable to return outcome on success. Set to TRUE for "enable" command, and FALSE for "disable" command.
Return values
OT_ERROR_NONE Successfully parsed the aString and updated aEnable.
OT_ERROR_INVALID_COMMAND The aString is not "enable" or "disable" command.
Referenced by Interpreter::IsInitialized(), UdpExample::ProcessLinkSecurity(), and Interpreter::SetUserCommands().
SetUserCommands()
void SetUserCommands (const otCliCommand * aCommands, uint8_t aLength, void * aContext)
This method sets the user command table.
Parameters
[in] aCommands A pointer to an array with user commands.
[in] aLength aUserCommands length.
[in] aContext aUserCommands length.
References Interpreter::AddressOriginToString(), String< kSize >::AsCString(), ot::Cli::Cmd(), ExitNow, Address::FromString(), Arg::GetCString(), Output::GetInstancePtr(), MessageInfo::GetPeerAddr(), IgnoreError(), Arg::IsEmpty(), ot::kErrorInvalidArgs, Interpreter::kIndentSize, Interpreter::kLinkModeStringSize, Interpreter::kLocateTimeoutMsecs, Interpreter::kNetworkDiagnosticTimeoutMsecs, ot::kUsPerTenSymbols, Interpreter::LinkModeToString(), otBufferInfo::m6loReassemblyQueue, otBufferInfo::m6loSendQueue, otNetworkKey::m8, otIp6InterfaceIdentifier::OT_TOOL_PACKED_FIELD::m8, otNetworkName::m8, otExtendedPanId::m8, otPskc::m8, otExtAddress::m8, otNetworkDiagConnectivity::mActiveRouters, otNetworkDiagTlv::mAddr16, otNetifAddress::mAddress, otSockAddr::mAddress, otBackboneRouterMulticastListenerInfo::mAddress, otNetifAddress::mAddressOrigin, otChildInfo::mAge, otNeighborInfo::mAge, otRouterInfo::mAge, otRouterInfo::mAllocated, otPingSenderConfig::mAllowZeroHopLimit, otBufferInfo::mApplicationCoapQueue, otMleCounters::mAttachAttempts, otChildInfo::mAverageRssi, otNeighborInfo::mAverageRssi, otRadioCoexMetrics::mAvgRxRequestToGrantTime, otRadioCoexMetrics::mAvgTxRequestToGrantTime, otNetworkDiagTlv::mBatteryLevel, otMleCounters::mBetterPartitionAttachAttempts, otPingSenderConfig::mCallbackContext, otCacheEntryInfo::mCanEvict, otActiveScanResult::mChannel, otEnergyScanResult::mChannel, otNetworkDiagTlv::mChannelPages, otChildInfo::mChildId, otNetworkDiagChildEntry::mChildId, otMleCounters::mChildRole, otNetworkDiagTlv::mChildTable, otBufferInfo::mCoapQueue, otBufferInfo::mCoapSecureQueue, otBorderRouterConfig::mConfigure, otNetworkDiagTlv::mConnectivity, otPingSenderConfig::mCount, otRouterInfo::mCslClockAccuracy, otRouterInfo::mCslUncertainty, otNetworkDiagTlv::mData, otLeaderData::mDataVersion, otBorderRouterConfig::mDefaultRoute, otPingSenderConfig::mDestination, otMleCounters::mDetachedRole, otLinkModeConfig::mDeviceType, otBorderRouterConfig::mDhcp, otMleCounters::mDisabledRole, otActiveScanResult::mDiscover, otBorderRouterConfig::mDp, otServiceConfig::mEnterpriseNumber, otChildInfo::mExtAddress, otTrelPeer::mExtAddress, otNeighborInfo::mExtAddress, otMacFilterEntry::mExtAddress, otRouterInfo::mExtAddress, otNetworkDiagTlv::mExtAddress, otActiveScanResult::mExtAddress, otThreadDiscoveryRequestInfo::mExtAddress, otActiveScanResult::mExtendedPanId, otTrelPeer::mExtPanId, otIp6InterfaceIdentifier::mFields, otBufferInfo::mFreeBuffers, otChildInfo::mFullNetworkData, otNeighborInfo::mFullNetworkData, otChildInfo::mFullThreadDevice, otNeighborInfo::mFullThreadDevice, otPingSenderReply::mHopLimit, otPingSenderConfig::mHopLimit, otDnsServiceInfo::mHostAddress, otDnsServiceInfo::mHostAddressTtl, otDnsServiceInfo::mHostNameBuffer, otDnsServiceInfo::mHostNameBufferSize, otNetworkDiagConnectivity::mIdSequence, otNetworkDiagRoute::mIdSequence, otMultiRadioNeighborInfo::mIeee802154Info, otNetworkDiagMacCounters::mIfInBroadcastPkts, otNetworkDiagMacCounters::mIfInDiscards, otNetworkDiagMacCounters::mIfInErrors, otNetworkDiagMacCounters::mIfInUcastPkts, otNetworkDiagMacCounters::mIfInUnknownProtos, otNetworkDiagMacCounters::mIfOutBroadcastPkts, otNetworkDiagMacCounters::mIfOutDiscards, otNetworkDiagMacCounters::mIfOutErrors, otNetworkDiagMacCounters::mIfOutUcastPkts, otPingSenderConfig::mInterval, otNetworkDiagTlv::mIp6AddrList, otBufferInfo::mIp6Queue, otNeighborInfo::mIsChild, otChildInfo::mIsCslSynced, otThreadDiscoveryRequestInfo::mIsJoiner, otPingSenderStatistics::mIsMulticast, otBorderRoutingPrefixTableEntry::mIsOnLink, otChildInfo::mIsStateRestoring, otNeighborInfo::mLastRssi, otCacheEntryInfo::mLastTransTime, otNetworkDiagConnectivity::mLeaderCost, otNetworkDiagTlv::mLeaderData, otMleCounters::mLeaderRole, otLeaderData::mLeaderRouterId, otJoinerDiscerner::mLength, otIp6Prefix::mLength, otRadioFrame::mLength, otRouterInfo::mLinkEstablished, otLinkMetrics::mLinkMargin, otLinkMetricsValues::mLinkMarginValue, otLinkMetricsSeriesFlags::mLinkProbe, otNetworkDiagConnectivity::mLinkQuality1, otNetworkDiagConnectivity::mLinkQuality2, otNetworkDiagConnectivity::mLinkQuality3, otChildInfo::mLinkQualityIn, otRouterInfo::mLinkQualityIn, otNetworkDiagRouteData::mLinkQualityIn, otRouterInfo::mLinkQualityOut, otNetworkDiagRouteData::mLinkQualityOut, otActiveScanResult::mLqi, otLinkMetrics::mLqi, otLinkMetricsValues::mLqiValue, otLinkMetricsSeriesFlags::mMacAck, otNetworkDiagTlv::mMacCounters, otLinkMetricsSeriesFlags::mMacData, otLinkMetricsSeriesFlags::mMacDataRequest, otNetworkDiagTlv::mMaxChildTimeout, otPingSenderStatistics::mMaxRoundTripTime, otEnergyScanResult::mMaxRssi, otDnsQueryConfig::mMaxTxAttempts, otCacheEntryInfo::mMeshLocalEid, otSntpQuery::mMessageInfo, otLinkMetricsValues::mMetrics, otPingSenderStatistics::mMinRoundTripTime, otBufferInfo::mMleQueue, otBackboneRouterConfig::mMlrTimeout, otNetworkDiagChildEntry::mMode, otNetworkDiagTlv::mMode, otBufferInfo::mMplQueue, otBorderRoutingPrefixTableEntry::mMsecSinceLastUpdate, otExternalRouteConfig::mNat64, otBorderRouterConfig::mNdDns, otLinkModeConfig::mNetworkData, otNetworkDiagTlv::mNetworkData, otChildInfo::mNetworkDataVersion, otActiveScanResult::mNetworkName, otUdpSocket::mNext, otNetifAddress::mNext, otNetifMulticastAddress::mNext, otRouterInfo::mNextHop, otRadioCoexMetrics::mNumGrantGlitch, otRadioCoexMetrics::mNumRxDelayedGrant, otRadioCoexMetrics::mNumRxGrantDeactivatedDuringRequest, otRadioCoexMetrics::mNumRxGrantImmediate, otRadioCoexMetrics::mNumRxGrantNone, otRadioCoexMetrics::mNumRxGrantWait, otRadioCoexMetrics::mNumRxGrantWaitActivated, otRadioCoexMetrics::mNumRxGrantWaitTimeout, otRadioCoexMetrics::mNumRxRequest, otRadioCoexMetrics::mNumTxDelayedGrant, otRadioCoexMetrics::mNumTxGrantDeactivatedDuringRequest, otRadioCoexMetrics::mNumTxGrantImmediate, otRadioCoexMetrics::mNumTxGrantWait, otRadioCoexMetrics::mNumTxGrantWaitActivated, otRadioCoexMetrics::mNumTxGrantWaitTimeout, otRadioCoexMetrics::mNumTxRequest, otBorderRouterConfig::mOnMesh, otActiveScanResult::mPanId, otMleCounters::mParentChanges, otNetworkDiagConnectivity::mParentPriority, otLeaderData::mPartitionId, otMleCounters::mPartitionIdChanges, otRouterInfo::mPathCost, otLinkMetrics::mPduCount, otLinkMetricsValues::mPduCountValue, otMessageInfo::mPeerAddr, otSockAddr::mPort, otDnsServiceInfo::mPort, otRadioLinkInfo::mPreference, otBorderRouterConfig::mPreference, otExternalRouteConfig::mPreference, otBorderRouterConfig::mPreferred, otNetifAddress::mPreferred, otBorderRoutingPrefixTableEntry::mPreferredLifetime, otBorderRouterConfig::mPrefix, otExternalRouteConfig::mPrefix, otBorderRoutingPrefixTableEntry::mPrefix, otIp6Prefix::mPrefix, otNetifAddress::mPrefixLength, otDnsServiceInfo::mPriority, otRadioFrame::mPsdu, otChildInfo::mQueuedMessageCnt, otPingSenderStatistics::mReceivedCount, otDnsQueryConfig::mRecursionFlag, otPingSenderConfig::mReplyCallback, otBackboneRouterConfig::mReregistrationDelay, otLinkMetrics::mReserved, otDnsQueryConfig::mResponseTimeout, otCacheEntryInfo::mRetryDelay, otChildInfo::mRloc16, otNeighborInfo::mRloc16, otCacheEntryInfo::mRloc16, otRouterInfo::mRloc16, otPingSenderReply::mRoundTripTime, otNetworkDiagTlv::mRoute, otNetworkDiagRouteData::mRouteCost, otNetworkDiagRoute::mRouteCount, otNetworkDiagRoute::mRouteData, otBorderRoutingPrefixTableEntry::mRoutePreference, otBorderRoutingPrefixTableEntry::mRouterAddress, otRouterInfo::mRouterId, otNetworkDiagRouteData::mRouterId, otMleCounters::mRouterRole, otActiveScanResult::mRssi, otLinkMetrics::mRssi, otMacFilterEntry::mRssIn, otLinkMetricsValues::mRssiValue, otMacCounters::mRxAddressFiltered, otMacCounters::mRxBeacon, otMacCounters::mRxBeaconRequest, otMacCounters::mRxBroadcast, otMacCounters::mRxData, otMacCounters::mRxDataPoll, otMacCounters::mRxDestAddrFiltered, otMacCounters::mRxDuplicated, otMacCounters::mRxErrFcs, otMacCounters::mRxErrInvalidSrcAddr, otMacCounters::mRxErrNoFrame, otMacCounters::mRxErrOther, otMacCounters::mRxErrSec, otMacCounters::mRxErrUnknownNeighbor, otIpCounters::mRxFailure, otChildInfo::mRxOnWhenIdle, otLinkModeConfig::mRxOnWhenIdle, otNeighborInfo::mRxOnWhenIdle, otMacCounters::mRxOther, otIpCounters::mRxSuccess, otMacCounters::mRxTotal, otMacCounters::mRxUnicast, otNetworkDiagConnectivity::mSedBufferSize, otNetworkDiagConnectivity::mSedDatagramCount, otPingSenderReply::mSenderAddress, otPingSenderStatistics::mSentCount, otBackboneRouterConfig::mSequenceNumber, otPingSenderReply::mSequenceNumber, otBackboneRouterConfig::mServer16, otServiceConfig::mServerConfig, otServerConfig::mServerData, otServerConfig::mServerDataLength, otDnsQueryConfig::mServerSockAddr, otServiceConfig::mServiceData, otServiceConfig::mServiceDataLength, otPingSenderReply::mSize, otPingSenderConfig::mSize, otBorderRouterConfig::mSlaac, otTrelPeer::mSockAddr, otPingSenderConfig::mSource, otBorderRouterConfig::mStable, otExternalRouteConfig::mStable, otServerConfig::mStable, otLeaderData::mStableDataVersion, otCacheEntryInfo::mState, otPingSenderConfig::mStatisticsCallback, otRadioCoexMetrics::mStopped, otNetworkDiagTlv::mSupplyVoltage, otMultiRadioNeighborInfo::mSupportsIeee802154, otMultiRadioNeighborInfo::mSupportsTrelUdp6, otCacheEntryInfo::mTarget, otChildInfo::mTimeout, otCacheEntryInfo::mTimeout, otPingSenderConfig::mTimeout, otNetworkDiagChildEntry::mTimeout, otNetworkDiagTlv::mTimeout, otBackboneRouterMulticastListenerInfo::mTimeout, otBufferInfo::mTotalBuffers, otPingSenderStatistics::mTotalRoundTripTime, otMultiRadioNeighborInfo::mTrelUdp6Info, otDnsServiceInfo::mTtl, otMacCounters::mTxAcked, otMacCounters::mTxAckRequested, otMacCounters::mTxBeacon, otMacCounters::mTxBeaconRequest, otMacCounters::mTxBroadcast, otMacCounters::mTxData, otMacCounters::mTxDataPoll, otMacCounters::mTxErrBusyChannel, otMacCounters::mTxErrCca, otIpCounters::mTxFailure, otMacCounters::mTxNoAckRequested, otMacCounters::mTxOther, otMacCounters::mTxRetry, otIpCounters::mTxSuccess, otDnsServiceInfo::mTxtData, otDnsServiceInfo::mTxtDataSize, otDnsServiceInfo::mTxtDataTtl, otMacCounters::mTxTotal, otMacCounters::mTxUnicast, otNetworkDiagTlv::mType, Interpreter::mUserCommands, Interpreter::mUserCommandsContext, Interpreter::mUserCommandsLength, otNetifAddress::mValid, otCacheEntryInfo::mValidLastTrans, otBorderRoutingPrefixTableEntry::mValidLifetime, otJoinerDiscerner::mValue, otChildInfo::mVersion, otRouterInfo::mVersion, otThreadDiscoveryRequestInfo::mVersion, otDnsServiceInfo::mWeight, otLeaderData::mWeighting, OT_ADDRESS_ORIGIN_DHCPV6, OT_ADDRESS_ORIGIN_MANUAL, OT_ADDRESS_ORIGIN_SLAAC, OT_ADDRESS_ORIGIN_THREAD, OT_ARRAY_LENGTH, OT_BACKBONE_ROUTER_MULTICAST_LISTENER_ITERATOR_INIT, OT_BACKBONE_ROUTER_STATE_DISABLED, OT_BACKBONE_ROUTER_STATE_PRIMARY, OT_BACKBONE_ROUTER_STATE_SECONDARY, OT_BORDER_AGENT_STATE_ACTIVE, OT_BORDER_AGENT_STATE_STARTED, OT_BORDER_AGENT_STATE_STOPPED, OT_CACHE_ENTRY_STATE_CACHED, OT_CACHE_ENTRY_STATE_RETRY_QUERY, OT_CHILD_IP6_ADDRESS_ITERATOR_INIT, OT_DNS_FLAG_NO_RECURSION, OT_DNS_FLAG_RECURSION_DESIRED, OT_DNS_MAX_LABEL_SIZE, OT_DNS_MAX_NAME_SIZE, OT_ERROR_ALREADY, OT_ERROR_BUSY, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_COMMAND, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_NOT_IMPLEMENTED, OT_ERROR_PENDING, OT_EXT_ADDRESS_SIZE, OT_IP6_MAX_MLR_ADDRESSES, OT_IP6_PREFIX_BITSIZE, OT_IP6_PREFIX_STRING_SIZE, OT_IP6_SOCK_ADDR_STRING_SIZE, OT_LINK_METRICS_ENH_ACK_CLEAR, OT_LINK_METRICS_ENH_ACK_REGISTER, OT_LINK_METRICS_STATUS_CANNOT_SUPPORT_NEW_SERIES, OT_LINK_METRICS_STATUS_NO_MATCHING_FRAMES_RECEIVED, OT_LINK_METRICS_STATUS_OTHER_ERROR, OT_LINK_METRICS_STATUS_SERIESID_ALREADY_REGISTERED, OT_LINK_METRICS_STATUS_SERIESID_NOT_RECOGNIZED, OT_LINK_METRICS_STATUS_SUCCESS, OT_MAC_FILTER_ADDRESS_MODE_ALLOWLIST, OT_MAC_FILTER_ADDRESS_MODE_DENYLIST, OT_MAC_FILTER_ADDRESS_MODE_DISABLED, OT_MAC_FILTER_FIXED_RSS_DISABLED, OT_MAC_FILTER_ITERATOR_INIT, OT_NEIGHBOR_INFO_ITERATOR_INIT, OT_NETWORK_DATA_ITERATOR_INIT, OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT, OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL, OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES, OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE, OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY, OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS, OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST, OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA, OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS, OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT, OT_NETWORK_DIAGNOSTIC_TLV_MODE, OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA, OT_NETWORK_DIAGNOSTIC_TLV_ROUTE, OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS, OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE, OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT, OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES, OT_NETWORK_TIME_RESYNC_NEEDED, OT_NETWORK_TIME_SYNCHRONIZED, OT_NETWORK_TIME_UNSYNCHRONIZED, OT_PANID_BROADCAST, OT_ROUTE_PREFERENCE_HIGH, OT_ROUTE_PREFERENCE_LOW, OT_ROUTE_PREFERENCE_MED, OT_SNTP_DEFAULT_SERVER_IP, OT_SNTP_DEFAULT_SERVER_PORT, OT_UNUSED_VARIABLE, OT_UPTIME_STRING_SIZE, otBackboneRouterConfigNextDuaRegistrationResponse(), otBackboneRouterConfigNextMulticastListenerRegistrationResponse(), otBackboneRouterGetConfig(), otBackboneRouterGetDomainPrefix(), otBackboneRouterGetPrimary(), otBackboneRouterGetRegistrationJitter(), otBackboneRouterGetState(), otBackboneRouterMulticastListenerAdd(), otBackboneRouterMulticastListenerClear(), otBackboneRouterMulticastListenerGetNext(), otBackboneRouterRegister(), otBackboneRouterSetConfig(), otBackboneRouterSetEnabled(), otBackboneRouterSetRegistrationJitter(), otBorderAgentGetState(), otBorderAgentGetUdpPort(), otBorderRouterAddOnMeshPrefix(), otBorderRouterAddRoute(), otBorderRouterGetNextOnMeshPrefix(), otBorderRouterGetNextRoute(), otBorderRouterRemoveOnMeshPrefix(), otBorderRouterRemoveRoute(), otBorderRoutingGetFavoredNat64Prefix(), otBorderRoutingGetFavoredOmrPrefix(), otBorderRoutingGetNat64Prefix(), otBorderRoutingGetNextPrefixTableEntry(), otBorderRoutingGetOmrPrefix(), otBorderRoutingGetOnLinkPrefix(), otBorderRoutingGetRouteInfoOptionPreference(), otBorderRoutingPrefixTableInitIterator(), otBorderRoutingSetEnabled(), otBorderRoutingSetRouteInfoOptionPreference(), otChannelManagerGetAutoChannelSelectionEnabled(), otChannelManagerGetAutoChannelSelectionInterval(), otChannelManagerGetCcaFailureRateThreshold(), otChannelManagerGetDelay(), otChannelManagerGetFavoredChannels(), otChannelManagerGetRequestedChannel(), otChannelManagerGetSupportedChannels(), otChannelManagerRequestChannelChange(), otChannelManagerRequestChannelSelect(), otChannelManagerSetAutoChannelSelectionEnabled(), otChannelManagerSetAutoChannelSelectionInterval(), otChannelManagerSetCcaFailureRateThreshold(), otChannelManagerSetDelay(), otChannelManagerSetFavoredChannels(), otChannelManagerSetSupportedChannels(), otChannelMonitorGetChannelOccupancy(), otChannelMonitorGetRssiThreshold(), otChannelMonitorGetSampleCount(), otChannelMonitorGetSampleInterval(), otChannelMonitorGetSampleWindow(), otChannelMonitorIsEnabled(), otChannelMonitorSetEnabled(), otChildSupervisionGetCheckTimeout(), otChildSupervisionGetInterval(), otChildSupervisionSetCheckTimeout(), otChildSupervisionSetInterval(), otDatasetGeneratePskc(), otDatasetGetDelayTimerMinimal(), otDatasetSetDelayTimerMinimal(), otDnsAddressResponseGetAddress(), otDnsAddressResponseGetHostName(), otDnsBrowseResponseGetServiceInfo(), otDnsBrowseResponseGetServiceInstance(), otDnsBrowseResponseGetServiceName(), otDnsClientBrowse(), otDnsClientGetDefaultConfig(), otDnsClientResolveAddress(), otDnsClientResolveIp4Address(), otDnsClientResolveService(), otDnsClientSetDefaultConfig(), otDnsIsNameCompressionEnabled(), otDnsServiceResponseGetServiceInfo(), otDnsServiceResponseGetServiceName(), otDnsSetNameCompressionEnabled(), otGetVersionString(), otInstanceFactoryReset(), otInstanceGetUptime(), otInstanceGetUptimeAsString(), otIp6AddressToString(), otIp6AddUnicastAddress(), otIp6AddUnsecurePort(), otIp6GetMulticastAddresses(), otIp6GetUnicastAddresses(), otIp6GetUnsecurePorts(), otIp6IsAddressEqual(), otIp6IsEnabled(), otIp6IsMulticastPromiscuousEnabled(), otIp6PrefixToString(), otIp6RegisterMulticastListeners(), otIp6RemoveAllUnsecurePorts(), otIp6RemoveUnicastAddress(), otIp6RemoveUnsecurePort(), otIp6SetEnabled(), otIp6SetMeshLocalIid(), otIp6SetMulticastPromiscuousEnabled(), otIp6SockAddrToString(), otIp6SubscribeMulticastAddress(), otIp6UnsubscribeMulticastAddress(), otLinkActiveScan(), otLinkConvertLinkQualityToRss(), otLinkConvertRssToLinkQuality(), otLinkCslGetChannel(), otLinkCslGetPeriod(), otLinkCslGetTimeout(), otLinkCslSetChannel(), otLinkCslSetPeriod(), otLinkCslSetTimeout(), otLinkEnergyScan(), otLinkFilterAddAddress(), otLinkFilterAddRssIn(), otLinkFilterClearAddresses(), otLinkFilterClearAllRssIn(), otLinkFilterClearDefaultRssIn(), otLinkFilterGetAddressMode(), otLinkFilterGetNextAddress(), otLinkFilterGetNextRssIn(), otLinkFilterRemoveAddress(), otLinkFilterRemoveRssIn(), otLinkFilterSetAddressMode(), otLinkFilterSetDefaultRssIn(), otLinkGetChannel(), otLinkGetCounters(), otLinkGetExtendedAddress(), otLinkGetFactoryAssignedIeeeEui64(), otLinkGetMaxFrameRetriesDirect(), otLinkGetMaxFrameRetriesIndirect(), otLinkGetPanId(), otLinkGetPollPeriod(), otLinkGetSupportedChannelMask(), otLinkIsPromiscuous(), otLinkIsRadioFilterEnabled(), otLinkMetricsConfigEnhAckProbing(), otLinkMetricsConfigForwardTrackingSeries(), otLinkMetricsQuery(), otLinkMetricsSendLinkProbe(), otLinkResetCounters(), otLinkSendDataRequest(), otLinkSendEmptyData(), otLinkSetChannel(), otLinkSetExtendedAddress(), otLinkSetMaxFrameRetriesDirect(), otLinkSetMaxFrameRetriesIndirect(), otLinkSetPanId(), otLinkSetPcapCallback(), otLinkSetPollPeriod(), otLinkSetPromiscuous(), otLinkSetRadioFilterEnabled(), otLoggingGetLevel(), otLoggingSetLevel(), otMessageGetBufferInfo(), otMessageGetLength(), otMessageGetOffset(), otMessageRead(), otMultiRadioGetNeighborInfo(), otNetworkTimeGet(), otNetworkTimeGetSyncPeriod(), otNetworkTimeGetXtalThreshold(), otNetworkTimeSetSyncPeriod(), otNetworkTimeSetXtalThreshold(), otPingSenderPing(), otPingSenderStop(), otPlatDebugUart_logfile(), otPlatRadioGetCcaEnergyDetectThreshold(), otPlatRadioGetCoexMetrics(), otPlatRadioGetFemLnaGain(), otPlatRadioGetPreferredChannelMask(), otPlatRadioGetPromiscuous(), otPlatRadioGetRegion(), otPlatRadioGetSupportedChannelMask(), otPlatRadioGetTransmitPower(), otPlatRadioGetVersionString(), otPlatRadioIsCoexEnabled(), otPlatRadioSetCcaEnergyDetectThreshold(), otPlatRadioSetCoexEnabled(), otPlatRadioSetFemLnaGain(), otPlatRadioSetRegion(), otPlatRadioSetTransmitPower(), otServerAddService(), otServerGetNextService(), otServerRemoveService(), otSntpClientQuery(), otThreadBecomeChild(), otThreadBecomeDetached(), otThreadBecomeLeader(), otThreadBecomeRouter(), otThreadDetachGracefully(), otThreadDeviceRoleToString(), otThreadDiscover(), otThreadErrorToString(), otThreadGetChildInfoById(), otThreadGetChildInfoByIndex(), otThreadGetChildNextIp6Address(), otThreadGetChildTimeout(), otThreadGetContextIdReuseDelay(), otThreadGetDeviceRole(), otThreadGetDomainName(), otThreadGetExtendedPanId(), otThreadGetFixedDuaInterfaceIdentifier(), otThreadGetIp6Counters(), otThreadGetJoinerUdpPort(), otThreadGetKeySequenceCounter(), otThreadGetKeySwitchGuardTime(), otThreadGetLeaderData(), otThreadGetLinkLocalAllThreadNodesMulticastAddress(), otThreadGetLinkLocalIp6Address(), otThreadGetLinkMode(), otThreadGetLocalLeaderWeight(), otThreadGetMaxAllowedChildren(), otThreadGetMaxChildIpAddresses(), otThreadGetMaxRouterId(), otThreadGetMeshLocalEid(), otThreadGetMeshLocalPrefix(), otThreadGetMleCounters(), otThreadGetNetworkIdTimeout(), otThreadGetNetworkKey(), otThreadGetNetworkKeyRef(), otThreadGetNetworkName(), otThreadGetNextCacheEntry(), otThreadGetNextDiagnosticTlv(), otThreadGetNextNeighborInfo(), otThreadGetParentInfo(), otThreadGetParentPriority(), otThreadGetPartitionId(), otThreadGetPreferredLeaderPartitionId(), otThreadGetPskc(), otThreadGetPskcRef(), otThreadGetRealmLocalAllThreadNodesMulticastAddress(), otThreadGetRloc(), otThreadGetRloc16(), otThreadGetRouterDowngradeThreshold(), otThreadGetRouterIdRange(), otThreadGetRouterInfo(), otThreadGetRouterSelectionJitter(), otThreadGetRouterUpgradeThreshold(), otThreadGetVersion(), otThreadIsAnycastLocateInProgress(), otThreadIsRouterEligible(), otThreadIsSingleton(), otThreadLocateAnycastDestination(), otThreadReleaseRouterId(), otThreadResetIp6Counters(), otThreadResetMleCounters(), otThreadSearchForBetterParent(), otThreadSendAddressNotification(), otThreadSendDiagnosticGet(), otThreadSendDiagnosticReset(), otThreadSendProactiveBackboneNotification(), otThreadSetCcmEnabled(), otThreadSetChildTimeout(), otThreadSetContextIdReuseDelay(), otThreadSetDomainName(), otThreadSetEnabled(), otThreadSetExtendedPanId(), otThreadSetFixedDuaInterfaceIdentifier(), otThreadSetJoinerUdpPort(), otThreadSetKeySequenceCounter(), otThreadSetKeySwitchGuardTime(), otThreadSetLinkMode(), otThreadSetLocalLeaderWeight(), otThreadSetMaxAllowedChildren(), otThreadSetMaxChildIpAddresses(), otThreadSetMeshLocalPrefix(), otThreadSetNetworkIdTimeout(), otThreadSetNetworkKey(), otThreadSetNetworkKeyRef(), otThreadSetNetworkName(), otThreadSetParentPriority(), otThreadSetPreferredLeaderPartitionId(), otThreadSetPreferredRouterId(), otThreadSetPskc(), otThreadSetPskcRef(), otThreadSetRouterDowngradeThreshold(), otThreadSetRouterEligible(), otThreadSetRouterIdRange(), otThreadSetRouterSelectionJitter(), otThreadSetRouterUpgradeThreshold(), otThreadSetThreadVersionCheckEnabled(), otTrelDisable(), otTrelEnable(), otTrelGetNextPeer(), otTrelInitPeerIterator(), otTrelIsEnabled(), otTrelIsFilterEnabled(), otTrelSetFilterEnabled(), otUdpGetSockets(), Output::OutputBytes(), Output::OutputBytesLine(), Output::OutputEnabledDisabledStatus(), Output::OutputExtAddress(), Output::OutputExtAddressLine(), Output::OutputFormat(), Output::OutputLine(), Interpreter::OutputResult(), Output::OutputTableHeader(), ot::Utils::CmdLineParser::ParseAsBool(), ot::Utils::CmdLineParser::ParseAsHexString(), ot::Utils::CmdLineParser::ParseAsInt8(), ot::Utils::CmdLineParser::ParseAsUint16(), Arg::ParseAsUint16(), ot::Utils::CmdLineParser::ParseAsUint32(), Arg::ParseAsUint32(), Arg::ParseAsUint64(), ot::Utils::CmdLineParser::ParseAsUint8(), Arg::ParseAsUint8(), Interpreter::ParseEnableOrDisable(), Interpreter::ParseJoinerDiscerner(), Interpreter::ParsePreference(), Interpreter::PreferenceToString(), Interpreter::Process(), Interpreter::ProcessGet(), Interpreter::ProcessGetSet(), Interpreter::ProcessSet(), Interpreter::SetCommandTimeout(), MessageInfo::SetPeerPort(), OutputBase::Stringify(), SuccessOrExit, ChannelMask::ToString(), and VerifyOrExit.
Referenced by Interpreter::IsInitialized(), and otCliSetUserCommands().
LinkModeToString()
const char * LinkModeToString (const otLinkModeConfig & aLinkMode, char(&) aStringBuffer[kLinkModeStringSize]) static
This method converts a given MLE Link Mode to flag string.
The characters 'r', 'd', and 'n' are respectively used for mRxOnWhenIdle, mDeviceType and mNetworkData flags. If all flags are false, then "-" is returned.
Parameters
[in] aLinkMode The MLE Link Mode to convert.
[out] aStringBuffer A reference to an string array to place the string.
Returns
A pointer aStringBuffer which contains the converted string.
References ot::Cli::Cmd(), Arg::CopyArgsToStringArray(), Arg::GetArgsLength(), Output::GetInstancePtr(), Interpreter::kMaxArgs, otLinkModeConfig::mDeviceType, otLinkModeConfig::mNetworkData, otLinkModeConfig::mRxOnWhenIdle, OPENTHREAD_CONFIG_DIAG_OUTPUT_BUFFER_SIZE, otDiagProcessCmd(), Output::OutputFormat(), and Interpreter::Process().
Referenced by Interpreter::SetUserCommands().
AddressOriginToString()
static const char* AddressOriginToString (uint8_t aOrigin) static
This method converts an IPv6 address origin OT_ADDRESS_ORIGIN_* value to human-readable string.
Parameters
[in] aOrigin The IPv6 address origin to convert.
Returns
A human-readable string representation of aOrigin.
Referenced by Interpreter::SetUserCommands().
ParsePreference()
static otError ParsePreference (const Arg & aArg, otRoutePreference & aPreference) static
This static method parses a given argument string as a route preference comparing it against "high", "med", or "low".
Parameters
[in] aArg The argument string to parse.
[out] aPreference Reference to a otRoutePreference to return the parsed preference.
Return values
OT_ERROR_NONE Successfully parsed aArg and updated aPreference.
OT_ERROR_INVALID_ARG aArg is not a valid preference string "high", "med", or "low".
Referenced by Interpreter::SetUserCommands().
PreferenceToString()
static const char* PreferenceToString (signed int aPreference) static
This static method converts a route preference value to human-readable string.
Parameters
[in] aPreference The preference value to convert (OT_ROUTE_PREFERENCE_* values).
Returns
A string representation aPreference.
Referenced by NetworkData::OutputPrefix(), NetworkData::OutputRoute(), and Interpreter::SetUserCommands().
FormatStringFor() [1/7]
static constexpr const char* FormatStringFor (void) static private
ProcessGet()
otError ProcessGet (Arg aArgs[], GetHandler< ValueType > aGetHandler) inline private
References Output::GetInstancePtr(), OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Output::OutputLine(), and VerifyOrExit.
Referenced by Interpreter::ProcessGetSet(), and Interpreter::SetUserCommands().
ProcessSet() [1/2]
otError ProcessSet (Arg aArgs[], SetHandler< ValueType > aSetHandler) inline private
References Output::GetInstancePtr(), OT_ERROR_INVALID_ARGS, SuccessOrExit, and VerifyOrExit.
Referenced by Interpreter::ProcessGetSet(), and Interpreter::SetUserCommands().
ProcessSet() [2/2]
otError ProcessSet (Arg aArgs[], SetHandlerFailable< ValueType > aSetHandler) inline private
References Output::GetInstancePtr(), OT_ERROR_INVALID_ARGS, SuccessOrExit, and VerifyOrExit.
ProcessGetSet() [1/2]
otError ProcessGetSet (Arg aArgs[], GetHandler< ValueType > aGetHandler, SetHandler< ValueType > aSetHandler) inline private
References OT_ERROR_NONE, Interpreter::ProcessGet(), Interpreter::ProcessSet(), and VerifyOrExit.
Referenced by Interpreter::SetUserCommands().
ProcessGetSet() [2/2]
otError ProcessGetSet (Arg aArgs[], GetHandler< ValueType > aGetHandler, SetHandlerFailable< ValueType > aSetHandler) inline private
References Interpreter::HandleTimer(), OT_ERROR_NONE, Interpreter::OutputPrompt(), Interpreter::OutputResult(), Interpreter::ParseJoinerDiscerner(), Interpreter::Process(), Interpreter::ProcessCommand(), Interpreter::ProcessGet(), Interpreter::ProcessSet(), Interpreter::ProcessUserCommands(), Interpreter::SetCommandTimeout(), and VerifyOrExit.
OutputPrompt()
void OutputPrompt (void) private
References Output::OutputFormat(), and Output::SetEmittingCommandOutput().
Referenced by Interpreter::Interpreter(), Interpreter::OutputResult(), Interpreter::ProcessGetSet(), and Interpreter::ProcessLine().
OutputResult()
void OutputResult (otError aError) private
References Interpreter::mCommandIsPending, Interpreter::mTimer, OT_ASSERT, OT_ERROR_NONE, OT_ERROR_PENDING, otThreadErrorToString(), Output::OutputLine(), Interpreter::OutputPrompt(), TimerMilli::Stop(), and VerifyOrExit.
Referenced by Interpreter::HandleTimer(), otCliAppendResult(), Interpreter::ProcessGetSet(), Interpreter::ProcessLine(), and Interpreter::SetUserCommands().
ParseJoinerDiscerner()
static otError ParseJoinerDiscerner (Arg & aArg, otJoinerDiscerner & aDiscerner) static private
Referenced by NetworkData::Process(), Interpreter::ProcessGetSet(), and Interpreter::SetUserCommands().
ProcessCommand()
otError ProcessCommand (Arg aArgs[]) private
References CmdEntry, BinarySearch::Find(), BinarySearch::IsSorted(), kCommands, OutputBase::CommandEntry< Cli >::mHandler, Interpreter::mUserCommands, Interpreter::mUserCommandsLength, OT_ERROR_NONE, Output::OutputCommandTable(), Output::OutputLine(), and Interpreter::ProcessUserCommands().
Referenced by Interpreter::ProcessGetSet(), and Interpreter::ProcessLine().
Process() [1/3]
otError Process (Arg aArgs[]) private
Referenced by Interpreter::LinkModeToString(), Interpreter::ProcessGetSet(), and Interpreter::SetUserCommands().
ProcessUserCommands()
otError ProcessUserCommands (Arg aArgs[]) private
References Arg::CopyArgsToStringArray(), Arg::GetArgsLength(), Interpreter::kMaxArgs, otCliCommand::mCommand, Interpreter::mUserCommands, Interpreter::mUserCommandsContext, Interpreter::mUserCommandsLength, OT_ERROR_INVALID_COMMAND, and OT_ERROR_NONE.
Referenced by Interpreter::ProcessCommand(), and Interpreter::ProcessGetSet().
SetCommandTimeout()
void SetCommandTimeout (uint32_t aTimeoutMilli) private
References Interpreter::mCommandIsPending, Interpreter::mTimer, OT_ASSERT, and TimerMilli::Start().
Referenced by Interpreter::ProcessGetSet(), and Interpreter::SetUserCommands().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References Interpreter::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References OT_ERROR_NONE, OT_ERROR_RESPONSE_TIMEOUT, and Interpreter::OutputResult().
Referenced by Interpreter::HandleTimer(), and Interpreter::ProcessGetSet().
Process() [2/3]
otError Process (Arg aArgs[]) private
References OPENTHREAD_API_VERSION, OT_ERROR_INVALID_COMMAND, OT_ERROR_NONE, otGetVersionString(), and Output::OutputLine().
Process() [3/3]
otError Process (Arg aArgs[]) private
References Output::GetInstancePtr(), OT_ERROR_NONE, OT_UNUSED_VARIABLE, and otInstanceReset().
FormatStringFor() [2/7]
constexpr const char* FormatStringFor (void) inline private
FormatStringFor() [3/7]
constexpr const char* FormatStringFor (void) inline private
FormatStringFor() [4/7]
constexpr const char* FormatStringFor (void) inline private
FormatStringFor() [5/7]
constexpr const char* FormatStringFor (void) inline private
FormatStringFor() [6/7]
constexpr const char* FormatStringFor (void) inline private
FormatStringFor() [7/7]
constexpr const char* FormatStringFor (void) inline private
Friends And Related Function Documentation
otCliPlatLogv
void otCliPlatLogv (otLogLevel , otLogRegion , const char * , va_list) friend
Callback to write the OpenThread Log to the CLI console
Parameters
[in] aLogLevel The log level.
[in] aLogRegion The log region.
[in] aFormat A pointer to the format string.
[in] aArgs va_list matching aFormat.
otCliAppendResult
void otCliAppendResult (otError aError) friend
Write error code to the CLI console
If the aError is OT_ERROR_PENDING nothing will be outputted.
Parameters
[in] aError Error code value.
otCliOutputBytes
void otCliOutputBytes (const uint8_t * aBytes, uint8_t aLength) friend
Write a number of bytes to the CLI console as a hex string.
Parameters
[in] aBytes A pointer to data which should be printed.
[in] aLength aBytes length.
otCliOutputFormat
void otCliOutputFormat (const char * aFmt, ...) friend
Write formatted string to the CLI console
Parameters
[in] aFmt A pointer to the format string.
[in] ... A matching list of arguments.
Field Documentation
kLinkModeStringSize
constexpr uint8_t kLinkModeStringSize = sizeof("rdn") static
Size of string buffer for a MLE Link Mode.
Referenced by Interpreter::SetUserCommands().
sInterpreter
Interpreter * sInterpreter = nullptr static protected
Referenced by Interpreter::GetInterpreter(), and Interpreter::IsInitialized().
kNetworkDiagnosticTimeoutMsecs
constexpr uint32_t kNetworkDiagnosticTimeoutMsecs = 5000 static private
Referenced by Interpreter::SetUserCommands().
kLocateTimeoutMsecs
constexpr uint32_t kLocateTimeoutMsecs = 2500 static private
Referenced by Interpreter::SetUserCommands().
mUserCommands
const otCliCommand* mUserCommands private
Referenced by Interpreter::ProcessCommand(), Interpreter::ProcessUserCommands(), and Interpreter::SetUserCommands().
mUserCommandsLength
uint8_t mUserCommandsLength private
Referenced by Interpreter::ProcessCommand(), Interpreter::ProcessUserCommands(), and Interpreter::SetUserCommands().
mUserCommandsContext
void* mUserCommandsContext private
Referenced by Interpreter::ProcessUserCommands(), and Interpreter::SetUserCommands().
mCommandIsPending
bool mCommandIsPending private
Referenced by Interpreter::OutputResult(), Interpreter::ProcessLine(), and Interpreter::SetCommandTimeout().
mTimer
TimerMilliContext mTimer private
Referenced by Interpreter::OutputResult(), and Interpreter::SetCommandTimeout().
The documentation for this class was generated from the following files:
cli.hpp
cli.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale