OpenThread: Checksum Class Reference
Checksum Class Reference
#include <checksum.hpp>
Static Public Member Functions
static void UpdateIp4HeaderChecksum (Ip4::Header &aHeader)
static void UpdateMessageChecksum (Message &aMessage, const Ip6::Address &aSource, const Ip6::Address &aDestination, uint8_t aIpProto)
static void UpdateMessageChecksum (Message &aMessage, const Ip4::Address &aSource, const Ip4::Address &aDestination, uint8_t aIpProto)
static Error VerifyMessageChecksum (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, uint8_t aIpProto)
Private Member Functions
void AddData (const uint8_t *aBuffer, uint16_t aLength)
void AddUint16 (uint16_t aUint16)
void AddUint8 (uint8_t aUint8)
void Calculate (const Ip6::Address &aSource, const Ip6::Address &aDestination, uint8_t aIpProto, const Message &aMessage)
void Calculate (const Ip4::Address &aSource, const Ip4::Address &aDestination, uint8_t aIpProto, const Message &aMessage)
Checksum (void)
uint16_t GetValue (void) const
void WriteToMessage (uint16_t aOffset, Message &aMessage) const
Private Attributes
bool mAtOddIndex
uint16_t mValue
Static Private Attributes
static constexpr uint16_t kValidRxChecksum = 0xffff
Friends
class ChecksumTester
Detailed Description
This class implements IP checksum calculation and verification.
Constructor & Destructor Documentation
Checksum()
Checksum (void) inline private
Member Function Documentation
VerifyMessageChecksum()
Error VerifyMessageChecksum (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo, uint8_t aIpProto) static
This static method verifies the checksum in a given message (if UDP/ICMP6).
Parameters
[in] aMessage The message to verify its checksum. The aMessage.GetOffset() should point to start UDP/ICMP6 header.
[in] aMessageInfo The message info associated with aMessage.
[in] aIpProto The Internet Protocol value.
Return values
kErrorNone The checksum is valid if UDP/ICMP6 protocol, or not a UDP/ICMP6 protocol.
kErrorDrop The check is not valid and message should be dropped.
References Checksum::Calculate(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Checksum::GetValue(), ot::kErrorDrop, ot::kErrorNone, and Checksum::kValidRxChecksum.
Referenced by Icmp::HandleMessage(), and Udp::HandleMessage().
UpdateMessageChecksum() [1/2]
void UpdateMessageChecksum (Message & aMessage, const Ip6::Address & aSource, const Ip6::Address & aDestination, uint8_t aIpProto) static
This static method calculates and then updates the checksum in a given message (if TCP/UDP/ICMPv6).
Parameters
[in,out] aMessage The message to update the checksum in. The aMessage.GetOffset() should point to start of the TCP/UDP/ICMPv6 header. On exit the checksum field in TCP/UDP/ICMPv6 header in the message is updated.
[in] aSource The source address.
[in] aDestination The destination address.
[in] aIpProto The Internet Protocol value.
References Checksum::Calculate(), ExitNow, Message::GetOffset(), Icmp::Header::kChecksumFieldOffset, Udp::Header::kChecksumFieldOffset, Tcp::Header::kChecksumFieldOffset, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, Message::Write(), and Checksum::WriteToMessage().
Referenced by Ip6::SendDatagram().
UpdateMessageChecksum() [2/2]
void UpdateMessageChecksum (Message & aMessage, const Ip4::Address & aSource, const Ip4::Address & aDestination, uint8_t aIpProto) static
This static method calculates and then updates the checksum in a given IPv4 message (if TCP/UDP/ICMP(v4)).
Parameters
[in,out] aMessage The message to update the checksum in. The aMessage.GetOffset() should point to start of the TCP/UDP/ICMP(v4) header. On exit the checksum field in TCP/UDP/ICMP(v4) header in the message is updated.
[in] aSource The source address.
[in] aDestination The destination address.
[in] aIpProto The Internet Protocol value.
References Checksum::Calculate(), ExitNow, Message::GetOffset(), Udp::Header::kChecksumFieldOffset, Tcp::Header::kChecksumFieldOffset, Icmp::Header::kChecksumFieldOffset, ot::Ip4::kProtoIcmp, ot::Ip4::kProtoTcp, ot::Ip4::kProtoUdp, Message::Write(), and Checksum::WriteToMessage().
UpdateIp4HeaderChecksum()
void UpdateIp4HeaderChecksum (Ip4::Header & aHeader) static
This static method calculates and then updates the checksum field in the IPv4 header.
Parameters
[in,out] aHeader The IPv4 header to update the checksum in.
References Checksum::AddData(), Checksum::GetValue(), and Header::SetChecksum().
GetValue()
uint16_t GetValue (void) const inline private
References Checksum::AddData(), Checksum::AddUint16(), Checksum::AddUint8(), Checksum::Calculate(), Checksum::mValue, and Checksum::WriteToMessage().
Referenced by Checksum::UpdateIp4HeaderChecksum(), Checksum::VerifyMessageChecksum(), and Checksum::WriteToMessage().
AddUint8()
void AddUint8 (uint8_t aUint8) private
References Checksum::mAtOddIndex, and Checksum::mValue.
Referenced by Checksum::AddData(), Checksum::AddUint16(), and Checksum::GetValue().
AddUint16()
void AddUint16 (uint16_t aUint16) private
References Checksum::AddUint8().
Referenced by Checksum::Calculate(), and Checksum::GetValue().
AddData()
void AddData (const uint8_t * aBuffer, uint16_t aLength) private
References Checksum::AddUint8().
Referenced by Checksum::Calculate(), Checksum::GetValue(), and Checksum::UpdateIp4HeaderChecksum().
WriteToMessage()
void WriteToMessage (uint16_t aOffset, Message & aMessage) const private
References Checksum::GetValue(), ot::Encoding::BigEndian::HostSwap16(), and Message::Write().
Referenced by Checksum::GetValue(), and Checksum::UpdateMessageChecksum().
Calculate() [1/2]
void Calculate (const Ip6::Address & aSource, const Ip6::Address & aDestination, uint8_t aIpProto, const Message & aMessage) private
References Checksum::AddData(), Checksum::AddUint16(), Data< kDataLengthType >::GetBytes(), Address::GetBytes(), Message::GetFirstChunk(), Data< kDataLengthType >::GetLength(), Message::GetLength(), Message::GetNextChunk(), and Message::GetOffset().
Referenced by Checksum::GetValue(), Checksum::UpdateMessageChecksum(), and Checksum::VerifyMessageChecksum().
Calculate() [2/2]
void Calculate (const Ip4::Address & aSource, const Ip4::Address & aDestination, uint8_t aIpProto, const Message & aMessage) private
References Checksum::AddData(), Checksum::AddUint16(), Address::GetBytes(), Data< kDataLengthType >::GetBytes(), Message::GetFirstChunk(), Data< kDataLengthType >::GetLength(), Message::GetLength(), Message::GetNextChunk(), Message::GetOffset(), and ot::Ip4::kProtoIcmp.
Friends And Related Function Documentation
ChecksumTester
friend class ChecksumTester friend
Field Documentation
kValidRxChecksum
constexpr uint16_t kValidRxChecksum = 0xffff static private
Referenced by Checksum::VerifyMessageChecksum().
mValue
uint16_t mValue private
Referenced by Checksum::AddUint8(), and Checksum::GetValue().
mAtOddIndex
bool mAtOddIndex private
Referenced by Checksum::AddUint8().
The documentation for this class was generated from the following files:
checksum.hpp
checksum.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale