OpenThread: Daemon Class Reference
Daemon Class Reference
#include <daemon.hpp>
Public Member Functions
void Process (const otSysMainloopContext &aContext) override
void SetUp (void)
void TearDown (void)
void Update (otSysMainloopContext &aContext) override
Static Public Member Functions
static Daemon & Get (void)
Private Member Functions
void InitializeSessionSocket (void)
int OutputFormatV (const char *aFormat, va_list aArguments)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
int mDaemonLock = -1
int mListenSocket = -1
int mSessionSocket = -1
Member Function Documentation
Get()
static Daemon& Get (void) static
Referenced by platformSetUp(), and platformTearDown().
SetUp()
void SetUp (void)
Referenced by platformSetUp().
TearDown()
void TearDown (void)
Referenced by platformTearDown().
Update()
void Update (otSysMainloopContext & aContext) override virtual
This method registers events in the mainloop.
Parameters
[in,out] aContext A reference to the mainloop context.
Implements Source.
Process()
void Process (const otSysMainloopContext & aContext) override virtual
This method processes the mainloop events.
Parameters
[in] aContext A reference to the mainloop context.
Implements Source.
OutputFormatV()
int OutputFormatV (const char * aFormat, va_list aArguments) private
InitializeSessionSocket()
void InitializeSessionSocket (void) private
Field Documentation
mListenSocket
int mListenSocket = -1 private
mDaemonLock
int mDaemonLock = -1 private
mSessionSocket
int mSessionSocket = -1 private
The documentation for this class was generated from the following file:
daemon.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale