OpenThread: Manager Class Reference
Manager Class Reference
#include <network_data_service.hpp>
Data Structures
class Iterator
Public Member Functions
Error FindPreferredDnsSrpAnycastInfo (DnsSrpAnycast::Info &aInfo) const
void GetBackboneRouterPrimary (ot::BackboneRouter::BackboneRouterConfig &aConfig) const
Error GetNextDnsSrpAnycastInfo (Iterator &aIterator, DnsSrpAnycast::Info &aInfo) const
Error GetNextDnsSrpUnicastInfo (Iterator &aIterator, DnsSrpUnicast::Info &aInfo) const
template<typename ServiceType >
Error GetServiceId (bool aServerStable, uint8_t &aServiceId) const
Manager (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
Error GetServiceId (const void *aServiceData, uint8_t aServiceDataLength, bool aServerStable, uint8_t &aServiceId) const
bool IsBackboneRouterPreferredTo (const ServerTlv &aServerTlv, const BackboneRouter::ServerData &aServerData, const ServerTlv &aOtherServerTlv, const BackboneRouter::ServerData &aOtherServerData) const
Error IterateToNextServer (Iterator &aIterator) const
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class manages the Thread Service entries in Thread Network Data.
Constructor & Destructor Documentation
Manager()
Manager (Instance & aInstance) inline explicit
This constructor initializes the Manager object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
GetServiceId() [1/2]
Error GetServiceId (bool aServerStable, uint8_t & aServiceId) const inline
This method gets the Service ID for the specified service from Thread Network Data.
The template type ServiceType has the following requirements:
It MUST have a constant ServiceType::kServiceNumber specifying the service number.
Template Parameters
ServiceType The service type to be added.
Parameters
[in] aServerStable The Stable flag value for Server TLV
[out] aServiceId A reference where to put the Service ID.
Return values
kErrorNone Successfully got the Service ID.
kErrorNotFound The specified service was not found.
Referenced by Manager::GetServiceId().
GetBackboneRouterPrimary()
void GetBackboneRouterPrimary (ot::BackboneRouter::BackboneRouterConfig & aConfig) const
This method gets the Primary Backbone Router (PBBR) in the Thread Network Data.
Parameters
[out] aConfig The Primary Backbone Router configuration.
References Data< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), BackboneRouter::ServerData::GetMlrTimeout(), BackboneRouter::ServerData::GetReregistrationDelay(), BackboneRouter::ServerData::GetSequenceNumber(), ServerTlv::GetServer16(), ServerTlv::GetServerData(), Data< kDataLengthType >::Init(), Manager::IsBackboneRouterPreferredTo(), Manager::IterateToNextServer(), ot::kErrorNone, BackboneRouter::kServiceDataMinSize, NetworkData::kServicePrefixMatch, ot::Mac::kShortAddrInvalid, otBackboneRouterConfig::mMlrTimeout, otBackboneRouterConfig::mReregistrationDelay, otBackboneRouterConfig::mSequenceNumber, otBackboneRouterConfig::mServer16, Manager::Iterator::mServerSubTlv, Manager::Iterator::mServiceTlv, and VerifyOrExit.
GetNextDnsSrpAnycastInfo()
Error GetNextDnsSrpAnycastInfo (Iterator & aIterator, DnsSrpAnycast::Info & aInfo) const
This method gets the next DNS/SRP info from the Thread Network Data "DNS/SRP Service Anycast Address" entries.
To get the first entry, aIterator should be cleared (e.g., a new instance of Iterator or calling Clear() method).
Parameters
[in,out] aIterator A reference to an iterator.
[out] aInfo A reference to DnsSrpAnycast::Info to return the info.
Return values
kErrorNone Successfully got the next info. aInfo and aIterator are updated.
kErrorNotFound No more matching entries in the Network Data.
References Data< kDataLengthType >::GetBytes(), ServiceTlv::GetServiceData(), ServiceTlv::GetServiceDataLength(), ServiceTlv::GetServiceId(), Data< kDataLengthType >::InitFrom(), ot::kErrorNone, ot::kErrorNotFound, NetworkData::kServicePrefixMatch, DnsSrpAnycast::Info::mAnycastAddress, DnsSrpAnycast::Info::mSequenceNumber, Manager::Iterator::mServiceTlv, Mle::ServiceAlocFromId(), Address::SetToAnycastLocator(), and VerifyOrExit.
Referenced by Manager::FindPreferredDnsSrpAnycastInfo().
FindPreferredDnsSrpAnycastInfo()
Error FindPreferredDnsSrpAnycastInfo (DnsSrpAnycast::Info & aInfo) const
This method finds the preferred DNS/SRP info among all the Thread Network Data "DNS/SRP Service Anycast Address" entries.
The preferred entry is determined based on the sequence number value where a larger value (in the sense specified by Serial Number Arithmetic logic in RFC-1982) is considered more recent and therefore preferred.
Parameters
[out] aInfo A reference to DnsSrpAnycast::Info to return the info.
Return values
kErrorNone Successfully found the preferred info. aInfo is updated.
kErrorNotFound No "DNS/SRP Service Anycast" entry in Network Data.
References Manager::GetNextDnsSrpAnycastInfo(), SerialNumber::IsGreater(), ot::kErrorNone, ot::kErrorNotFound, DnsSrpAnycast::Info::mSequenceNumber, Manager::Iterator::Reset(), and SuccessOrExit.
GetNextDnsSrpUnicastInfo()
Error GetNextDnsSrpUnicastInfo (Iterator & aIterator, DnsSrpUnicast::Info & aInfo) const
This method gets the next DNS/SRP info from the Thread Network Data "DNS/SRP Service Unicast Address" entries.
To get the first entry aIterator should be cleared (e.g., a new instance of Iterator or calling Clear() method).
Parameters
[in,out] aIterator A reference to an iterator.
[out] aInfo A reference to DnsSrpUnicast::Info to return the info.
Return values
kErrorNone Successfully got the next info. aInfo and aIterator are updated.
kErrorNotFound No more matching entries in the Network Data.
References ExitNow, DnsSrpUnicast::ServiceData::GetAddress(), SockAddr::GetAddress(), DnsSrpUnicast::ServerData::GetAddress(), Data< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), DnsSrpUnicast::ServiceData::GetPort(), DnsSrpUnicast::ServerData::GetPort(), ServerTlv::GetServer16(), ServerTlv::GetServerData(), ServiceTlv::GetServiceData(), ServiceTlv::GetServiceDataLength(), Data< kDataLengthType >::InitFrom(), Manager::IterateToNextServer(), ot::kErrorNone, ot::kErrorNotFound, DnsSrpUnicast::kFromServerData, DnsSrpUnicast::kFromServiceData, NetworkData::kServicePrefixMatch, DnsSrpUnicast::Info::mOrigin, Manager::Iterator::mServerSubTlv, Manager::Iterator::mServiceTlv, DnsSrpUnicast::Info::mSockAddr, ot::Encoding::BigEndian::ReadUint16(), SockAddr::SetAddress(), SockAddr::SetPort(), Address::SetToRoutingLocator(), and VerifyOrExit.
GetServiceId() [2/2]
Error GetServiceId (const void * aServiceData, uint8_t aServiceDataLength, bool aServerStable, uint8_t & aServiceId) const private
References Manager::GetServiceId(), Data< kDataLengthType >::Init(), and ot::NetworkData::Service::kThreadEnterpriseNumber.
IterateToNextServer()
Error IterateToNextServer (Iterator & aIterator) const private
References NetworkDataTlv::GetNext(), ServiceTlv::GetSubTlvs(), ot::kErrorNone, ot::kErrorNotFound, Manager::Iterator::mServerSubTlv, Manager::Iterator::mServiceTlv, and VerifyOrExit.
Referenced by Manager::GetBackboneRouterPrimary(), and Manager::GetNextDnsSrpUnicastInfo().
IsBackboneRouterPreferredTo()
bool IsBackboneRouterPreferredTo (const ServerTlv & aServerTlv, const BackboneRouter::ServerData & aServerData, const ServerTlv & aOtherServerTlv, const BackboneRouter::ServerData & aOtherServerData) const private
References BackboneRouter::ServerData::GetSequenceNumber(), ServerTlv::GetServer16(), Mle::Rloc16FromRouterId(), and VerifyOrExit.
Referenced by Manager::GetBackboneRouterPrimary().
The documentation for this class was generated from the following files:
network_data_service.hpp
network_data_service.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale