OpenThread: MessageQueue Class Reference
MessageQueue Class Reference
Core-message
#include <message.hpp>
Public Types
typedef otMessageQueueInfo Info
This struct represents info (number of messages/buffers) about a queue.
enum QueuePosition : uint8_t { kQueuePositionHead, kQueuePositionTail }
Public Member Functions
Message::Iterator begin (void)
Message::ConstIterator begin (void) const
void Dequeue (Message &aMessage)
void DequeueAndFree (Message &aMessage)
void DequeueAndFreeAll (void)
Message::Iterator end (void)
Message::ConstIterator end (void) const
void Enqueue (Message &aMessage)
void Enqueue (Message &aMessage, QueuePosition aPosition)
Message * GetHead (void)
const Message * GetHead (void) const
void GetInfo (Info &aInfo) const
MessageQueue (void)
Private Member Functions
Message * GetTail (void)
const Message * GetTail (void) const
void SetTail (Message *aMessage)
Friends
class Message
A TMF message.
class PriorityQueue
Additional Inherited Members
Data Fields inherited from otMessageQueue
void * mData
Opaque data used by the implementation.
Detailed Description
This class implements a message queue.
Member Typedef Documentation
Info
typedef otMessageQueueInfo Info
This struct represents info (number of messages/buffers) about a queue.
Member Enumeration Documentation
QueuePosition
enum QueuePosition : uint8_t
This enumeration represents a position (head or tail) in the queue. This is used to specify where a new message should be added in the queue.
Enumerator
kQueuePositionHead
Indicates the head (front) of the list.
kQueuePositionTail
Indicates the tail (end) of the list.
Constructor & Destructor Documentation
MessageQueue()
MessageQueue (void) inline
This constructor initializes the message queue.
Member Function Documentation
GetHead() [1/2]
Message* GetHead (void) inline
This method returns a pointer to the first message.
Returns
A pointer to the first message.
Referenced by MessageQueue::GetHead().
GetHead() [2/2]
const Message* GetHead (void) const inline
This method returns a pointer to the first message.
Returns
A pointer to the first message.
Enqueue() [1/2]
void Enqueue (Message & aMessage) inline
This method adds a message to the end of the list.
Parameters
[in] aMessage The message to add.
References MessageQueue::Enqueue().
Referenced by MessageQueue::Enqueue(), MeshForwarder::HandleFragment(), and Mle::TxMessage::SendAfterDelay().
Enqueue() [2/2]
void Enqueue (Message & aMessage, QueuePosition aPosition)
This method adds a message at a given position (head/tail) of the list.
Parameters
[in] aMessage The message to add.
[in] aPosition The position (head or tail) where to add the message.
Dequeue()
void Dequeue (Message & aMessage)
This method removes a message from the list.
Parameters
[in] aMessage The message to remove.
Referenced by MessageQueue::Dequeue(), and MeshForwarder::HandleFragment().
DequeueAndFree()
void DequeueAndFree (Message & aMessage)
This method removes a message from the queue and frees it.
Parameters
[in] aMessage The message to remove and free.
Referenced by MessageQueue::DequeueAndFree().
DequeueAndFreeAll()
void DequeueAndFreeAll (void)
This method removes and frees all messages from the queue.
Referenced by ResponsesQueue::DequeueAllResponses(), and MeshForwarder::Stop().
GetInfo()
void GetInfo (Info & aInfo) const
This method gets the information about number of messages and buffers in the queue.
This method updates aInfo and adds number of message/buffers in the message queue to the corresponding member variable in aInfo. The caller needs to make sure aInfo is initialized before calling this method (e.g., clearing aInfo). Same aInfo can be passed in multiple calls of GetInfo(aInfo) on different queues to add up the number of messages/buffers on different queues.
Parameters
[out] aInfo A reference to Info structure to update.ni
begin() [1/2]
Message::Iterator begin (void)
end() [1/2]
Message::Iterator end (void) inline
begin() [2/2]
Message::ConstIterator begin (void) const
end() [2/2]
Message::ConstIterator end (void) const inline
GetTail() [1/2]
Message* GetTail (void) inline private
GetTail() [2/2]
const Message* GetTail (void) const inline private
SetTail()
void SetTail (Message * aMessage) inline private
Friends And Related Function Documentation
Message
friend class Message friend
A TMF message.
PriorityQueue
friend class PriorityQueue friend
The documentation for this class was generated from the following file:
message.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale