OpenThread: OutputWrapper Class Reference
OutputWrapper Class Reference
#include <cli_output.hpp>
Protected Member Functions
otInstance * GetInstancePtr (void)
template<uint8_t kBytesLength>
void OutputBytes (const uint8_t(&aBytes)[kBytesLength])
void OutputBytes (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytesLine (const uint8_t(&aBytes)[kBytesLength])
void OutputBytesLine (const uint8_t *aBytes, uint16_t aLength)
template<typename Cli , uint16_t kLength>
void OutputCommandTable (const CommandEntry< Cli >(&aCommandTable)[kLength])
void OutputEnabledDisabledStatus (bool aEnabled)
void OutputExtAddress (const otExtAddress &aExtAddress)
void OutputExtAddressLine (const otExtAddress &aExtAddress)
template<typename... Args>
void OutputFormat (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputFormat (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
void OutputSpaces (uint8_t aCount)
template<uint8_t kTableNumColumns>
void OutputTableHeader (const char *const (&aTitles)[kTableNumColumns], const uint8_t(&aWidths)[kTableNumColumns])
template<uint8_t kTableNumColumns>
void OutputTableSeparator (const uint8_t(&aWidths)[kTableNumColumns])
OutputWrapper (Output &aOutput)
Protected Member Functions inherited from OutputBase
OutputBase (void)=default
Private Attributes
Output & mOutput
Additional Inherited Members
Public Types inherited from OutputBase
typedef Utils::CmdLineParser::Arg Arg
An argument.
Static Public Member Functions inherited from OutputBase
template<typename EnumType , uint16_t kLength>
static const char * Stringify (EnumType aEnum, const char *const (&aTable)[kLength], const char *aNotFound=kUnknownString)
Static Public Attributes inherited from OutputBase
static const char kUnknownString [] = "unknown"
Constructor & Destructor Documentation
OutputWrapper()
OutputWrapper (Output & aOutput) inline explicit protected
Member Function Documentation
GetInstancePtr()
otInstance* GetInstancePtr (void) inline protected
Referenced by NetworkData::GetNextPrefix(), NetworkData::GetNextRoute(), NetworkData::GetNextService(), NetworkData::OutputBinary(), NetworkData::OutputService(), Dataset::Process(), NetworkData::Process(), UdpExample::ProcessBind(), UdpExample::ProcessClose(), UdpExample::ProcessConnect(), UdpExample::ProcessOpen(), and UdpExample::ProcessSend().
OutputFormat() [1/2]
void OutputFormat (const char * aFormat, Args... aArgs) inline protected
Referenced by UdpExample::HandleUdpReceive(), NetworkData::OutputPrefix(), NetworkData::OutputRoute(), Dataset::OutputSecurityPolicy(), NetworkData::OutputService(), Dataset::Print(), and Dataset::Process().
OutputFormat() [2/2]
void OutputFormat (uint8_t aIndentSize, const char * aFormat, Args... aArgs) inline protected
OutputLine() [1/2]
void OutputLine (const char * aFormat, Args... aArgs) inline protected
Referenced by UdpExample::HandleUdpReceive(), NetworkData::OutputPrefix(), NetworkData::OutputPrefixes(), NetworkData::OutputRoute(), NetworkData::OutputRoutes(), Dataset::OutputSecurityPolicy(), NetworkData::OutputService(), NetworkData::OutputServices(), Dataset::Print(), Dataset::Process(), and UdpExample::ProcessHelp().
OutputLine() [2/2]
void OutputLine (uint8_t aIndentSize, const char * aFormat, Args... aArgs) inline protected
OutputBytes() [1/2]
void OutputBytes (const uint8_t(&) aBytes[kBytesLength]) inline protected
Referenced by NetworkData::OutputService().
OutputBytesLine() [1/2]
void OutputBytesLine (const uint8_t(&) aBytes[kBytesLength]) inline protected
Referenced by NetworkData::OutputBinary(), Dataset::Print(), and Dataset::Process().
OutputSpaces()
void OutputSpaces (uint8_t aCount) inline protected
OutputBytes() [2/2]
void OutputBytes (const uint8_t * aBytes, uint16_t aLength) inline protected
OutputBytesLine() [2/2]
void OutputBytesLine (const uint8_t * aBytes, uint16_t aLength) inline protected
OutputExtAddress()
void OutputExtAddress (const otExtAddress & aExtAddress) inline protected
OutputExtAddressLine()
void OutputExtAddressLine (const otExtAddress & aExtAddress) inline protected
OutputEnabledDisabledStatus()
void OutputEnabledDisabledStatus (bool aEnabled) inline protected
Referenced by Dataset::Process(), and UdpExample::ProcessLinkSecurity().
OutputTableHeader()
void OutputTableHeader (const char *const (&) aTitles[kTableNumColumns], const uint8_t(&) aWidths[kTableNumColumns]) inline protected
OutputTableSeparator()
void OutputTableSeparator (const uint8_t(&) aWidths[kTableNumColumns]) inline protected
OutputCommandTable()
void OutputCommandTable (const CommandEntry< Cli >(&) aCommandTable[kLength]) inline protected
Referenced by Dataset::Process(), and NetworkData::Process().
Field Documentation
mOutput
Output& mOutput private
The documentation for this class was generated from the following file:
cli_output.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale