OpenThread: String< kSize > Class Template Reference
String< kSize > Class Template Reference
Core-string
#include <string.hpp>
Public Member Functions
const char * AsCString (void) const
String (void)
Public Member Functions inherited from StringWriter
StringWriter & Append (const char *aFormat,...)
StringWriter & AppendHexBytes (const uint8_t *aBytes, uint16_t aLength)
StringWriter & AppendVarArgs (const char *aFormat, va_list aArgs)
StringWriter & Clear (void)
void ConvertToLowercase (void)
void ConvertToUppercase (void)
uint16_t GetLength (void) const
uint16_t GetSize (void) const
bool IsTruncated (void) const
StringWriter (char *aBuffer, uint16_t aSize)
Private Attributes
char mBuffer [kSize]
Detailed Description
template<uint16_t kSize>
class ot::String< kSize >
This class defines a fixed-size string.
Constructor & Destructor Documentation
String()
String (void) inline
This constructor initializes the string as empty.
Member Function Documentation
AsCString()
const char* AsCString (void) const inline
This method returns the string as a null-terminated C string.
Returns
The null-terminated C string.
References StringWriter::mBuffer.
Referenced by AddressResolver::AddressResolver(), MeshForwarder::CalcFrameVersion(), Mle::CheckReachability(), Leader::GetServiceId(), AddressResolver::HandleAddressError(), otSysGetThreadNetifIndex(), Output::OutputFormatV(), RxFrame::ProcessReceiveAesCcm(), DatasetManager::SendGetResponse(), Mle::SetDeviceMode(), SubMac::SetExtAddress(), Mac::SetPromiscuous(), Interpreter::SetUserCommands(), and MeshForwarder::UpdateNeighborLinkFailures().
Field Documentation
mBuffer
char mBuffer[kSize] private
The documentation for this class was generated from the following file:
string.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale