OpenThread: Prefix Class Reference
Prefix Class Reference
Core-ipv6 » IPv6
#include <ip6_address.hpp>
Public Types
typedef String< kInfoStringSize > InfoString
Public Member Functions
bool ContainsPrefix (const Prefix &aSubPrefix) const
bool ContainsPrefix (const NetworkPrefix &aSubPrefix) const
const uint8_t * GetBytes (void) const
uint8_t GetBytesSize (void) const
uint8_t GetLength (void) const
uint16_t GetSubnetId (void) const
bool IsEqual (const uint8_t *aPrefixBytes, uint8_t aPrefixLength) const
bool IsLinkLocal (void) const
bool IsMulticast (void) const
bool IsUniqueLocal (void) const
bool IsValid (void) const
bool IsValidNat64 (void) const
bool operator< (const Prefix &aOther) const
bool operator== (const Prefix &aOther) const
void Set (const uint8_t *aPrefix, uint8_t aLength)
void Set (const NetworkPrefix &aNetworkPrefix)
void SetLength (uint8_t aLength)
void SetSubnetId (uint16_t aSubnetId)
InfoString ToString (void) const
void ToString (char *aBuffer, uint16_t aSize) const
Public Member Functions inherited from Clearable< Prefix >
void Clear (void)
Public Member Functions inherited from Unequatable< Prefix >
bool operator!= (const Prefix &aOther) const
Static Public Member Functions
static bool IsValidNat64PrefixLength (uint8_t aLength)
static uint8_t MatchLength (const uint8_t *aPrefixA, const uint8_t *aPrefixB, uint8_t aMaxSize)
static uint8_t SizeForLength (uint8_t aLength)
Static Public Attributes
static constexpr uint16_t kInfoStringSize = OT_IP6_PREFIX_STRING_SIZE
Info string size (ToString()).
static constexpr uint8_t kMaxLength = OT_IP6_ADDRESS_SIZE * CHAR_BIT
Max length of a prefix in bits.
static constexpr uint8_t kMaxSize = OT_IP6_ADDRESS_SIZE
Max (byte) size of a prefix.
Private Member Functions
void ToString (StringWriter &aWriter) const
Additional Inherited Members
Data Fields inherited from otIp6Prefix
uint8_t mLength
The IPv6 prefix length (in bits).
otIp6Address mPrefix
The IPv6 prefix.
Detailed Description
This class represents an IPv6 Prefix.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Function Documentation
GetBytes()
const uint8_t* GetBytes (void) const inline
This method gets the prefix as a pointer to a byte array.
Returns
A pointer to a byte array containing the Prefix.
Referenced by InterfaceIdentifier::ApplyPrefix(), Lowpan::CompressMulticast(), Prefix::ContainsPrefix(), Lowpan::DecompressBaseHeader(), NetworkData::FindPrefix(), MutableNetworkData::FindPrefix(), PrefixTlv::Init(), Address::MatchesPrefix(), Prefix::operator<(), Prefix::operator==(), Address::SetMulticastNetworkPrefix(), RouteInfoOption::SetPrefix(), and Address::SetPrefix().
GetSubnetId()
uint16_t GetSubnetId (void) const inline
This method gets the subnet ID of the prefix.
Returns
The 16-bit subnet ID.
References ot::Encoding::BigEndian::HostSwap16().
GetLength()
uint8_t GetLength (void) const inline
This method gets the prefix length (in bits).
Returns
The prefix length (in bits).
Referenced by RouterAdvertMessage::AppendRouteInfoOption(), InterfaceIdentifier::ApplyPrefix(), Lowpan::CompressMulticast(), Prefix::ContainsPrefix(), Lowpan::DecompressBaseHeader(), NetworkData::FindPrefix(), MutableNetworkData::FindPrefix(), LeaderBase::GetContext(), Leader::GetDomainPrefix(), Leader::HasDomainPrefix(), Netif::UnicastAddress::HasPrefix(), PrefixTlv::Init(), Address::MatchesPrefix(), Prefix::operator<(), Address::SetMulticastNetworkPrefix(), Address::SetPrefix(), Address::SynthesizeFromIp4Address(), and Leader::UpdateDomainPrefixConfig().
GetBytesSize()
uint8_t GetBytesSize (void) const inline
This method returns the size (in bytes) of the prefix.
Returns
The size (in bytes) of the prefix array.
Referenced by Prefix::ContainsPrefix(), Address::MatchesPrefix(), and RouteInfoOption::SetPrefix().
Set() [1/2]
void Set (const uint8_t * aPrefix, uint8_t aLength)
This method sets the prefix.
Parameters
[in] aPrefix A pointer to buffer containing the prefix bytes.
[in] aLength The length or prefix in bits.
Referenced by PrefixTlv::CopyPrefixTo(), LeaderBase::GetContext(), LeaderBase::GetContextForMeshLocalPrefix(), PrefixInfoOption::GetPrefix(), RouteInfoOption::GetPrefix(), and Address::GetPrefix().
Set() [2/2]
void Set (const NetworkPrefix & aNetworkPrefix) inline
This method sets the prefix from a given Network Prefix.
Parameters
[in] aNetworkPrefix A Network Prefix.
References otIp6NetworkPrefix::m8, and Prefix::Set().
Referenced by Prefix::Set().
SetSubnetId()
void SetSubnetId (uint16_t aSubnetId) inline
This method sets the subnet ID of the prefix.
Parameters
[in] aSubnetId A 16-bit subnet ID.
References ot::Encoding::BigEndian::HostSwap16().
SetLength()
void SetLength (uint8_t aLength) inline
This method set the prefix length.
Parameters
[in] aLength The new prefix length (in bits).
Referenced by LeaderBase::GetContext(), Leader::Reset(), and Leader::UpdateDomainPrefixConfig().
IsValid()
bool IsValid (void) const inline
This method indicates whether prefix length is valid (smaller or equal to max length).
Return values
TRUE The prefix length is valid.
FALSE The prefix length is not valid.
IsLinkLocal()
bool IsLinkLocal (void) const
This method indicates whether the prefix is a Link-Local prefix.
Return values
TRUE The prefix is a Link-Local prefix.
FALSE The prefix is not a Link-Local prefix.
References ot::Encoding::BigEndian::HostSwap16().
IsMulticast()
bool IsMulticast (void) const
This method indicates whether the prefix is a Multicast prefix.
Return values
TRUE The prefix is a Multicast prefix.
FALSE The prefix is not a Multicast prefix.
IsUniqueLocal()
bool IsUniqueLocal (void) const
This method indicates whether the prefix is a Unique-Local prefix.
Return values
TRUE The prefix is a Unique-Local prefix.
FALSE The prefix is not a Unique-Local prefix.
IsEqual()
bool IsEqual (const uint8_t * aPrefixBytes, uint8_t aPrefixLength) const
This method indicates whether the prefix is equal to a given prefix.
Parameters
[in] aPrefixBytes A pointer to buffer containing the prefix bytes to compare with.
[in] aPrefixLength The length of prefix (in bits) specified by aPrefixBytes.
Return values
TRUE If the prefix is equal to the specified prefix by aPrefixBytes and aPrefixLength.
FALSE If the prefix is not equal to the specified prefix by aPrefixBytes and aPrefixLength.
Referenced by PrefixTlv::IsEqual().
ContainsPrefix() [1/2]
bool ContainsPrefix (const Prefix & aSubPrefix) const
This method indicates whether the prefix contains a sub-prefix.
Parameters
[in] aSubPrefix A sub-prefix.
Return values
TRUE The prefix contains the aSubPrefix
FALSE The prefix does not contains the aSubPrefix.
References Prefix::GetBytes(), Prefix::GetBytesSize(), Prefix::GetLength(), and otIp6Prefix::mLength.
ContainsPrefix() [2/2]
bool ContainsPrefix (const NetworkPrefix & aSubPrefix) const
This method indicates whether the prefix contains a sub-prefix (given as a NetworkPrefix).
Parameters
[in] aSubPrefix A sub-prefix (as a NetworkPrefix).
Return values
TRUE The prefix contains the aSubPrefix
FALSE The prefix does not contains the aSubPrefix.
References NetworkPrefix::kLength, NetworkPrefix::kSize, and otIp6NetworkPrefix::m8.
operator==()
bool operator== (const Prefix & aOther) const
This method overloads operator == to evaluate whether or not two prefixes are equal.
Parameters
[in] aOther The other prefix to compare with.
Return values
TRUE If the two prefixes are equal.
FALSE If the two prefixes are not equal.
References Prefix::GetBytes(), and otIp6Prefix::mLength.
operator<()
bool operator< (const Prefix & aOther) const
This method overloads operator < to compare two prefixes.
If the two prefixes have the same length N, then the bytes are compared directly (as two big-endian N-bit numbers). If the two prefix have different lengths, the shorter prefix is padded by 0 bit up to the longer prefix length N before the bytes are compared (as big-endian N-bit numbers). If all bytes are equal, the prefix with shorter length is considered smaller.
Parameters
[in] aOther The other prefix to compare against.
Return values
TRUE If the prefix is smaller than aOther.
FALSE If the prefix is not smaller than aOther.
References ExitNow, Prefix::GetBytes(), Prefix::GetLength(), and ot::Min().
SizeForLength()
static uint8_t SizeForLength (uint8_t aLength) inline static
This static method converts a prefix length (in bits) to size (number of bytes).
Parameters
[in] aLength A prefix length (in bits).
Returns
The size (in bytes) of the prefix.
References BitVectorBytes.
Referenced by PrefixTlv::CalculateSize(), PrefixTlv::GetSubTlvs(), PrefixTlv::GetSubTlvsLength(), PrefixTlv::Init(), PrefixTlv::IsEqual(), PrefixTlv::IsValid(), Address::MatchesPrefix(), and PrefixTlv::SetSubTlvsLength().
MatchLength()
uint8_t MatchLength (const uint8_t * aPrefixA, const uint8_t * aPrefixB, uint8_t aMaxSize) static
This static method returns the number of IPv6 prefix bits that match.
Parameters
[in] aPrefixA A pointer to a byte array containing a first prefix.
[in] aPrefixB A pointer to a byte array containing a second prefix.
[in] aMaxSize Number of bytes of the two prefixes.
Returns
The number of prefix bits that match.
References Address::kSize, and OT_ASSERT.
Referenced by PrefixTlv::IsEqual(), Address::MatchesPrefix(), Cidr::operator==(), and Address::PrefixMatch().
IsValidNat64PrefixLength()
bool IsValidNat64PrefixLength (uint8_t aLength) static
This method indicates whether or not a given prefix length is valid for use as a NAT64 prefix.
A NAT64 prefix must have one of the following lengths: 32, 40, 48, 56, 64, or 96 (per RFC 6502).
Parameters
[in] aLength The length of the prefix.
Return values
TRUE If the prefix has a valid length for use as a NAT64 prefix.
FALSE If the prefix does not have a valid length for use as a NAT64 prefix.
Referenced by Address::ExtractFromIp6Address().
IsValidNat64()
bool IsValidNat64 (void) const inline
This method indicates whether or not the prefix has a valid length for use as a NAT64 prefix.
A NAT64 prefix must have one of the following lengths: 32, 40, 48, 56, 64, or 96 (per RFC 6502).
Return values
TRUE If the prefix has a valid length for use as a NAT64 prefix.
FALSE If the prefix does not have a valid length for use as a NAT64 prefix.
References OT_TOOL_PACKED_BEGIN, and ot::Ip4::OT_TOOL_PACKED_END.
Referenced by LeaderBase::GetPreferredNat64Prefix(), and Address::SynthesizeFromIp4Address().
ToString() [1/3]
Prefix::InfoString ToString (void) const
This method converts the prefix to a string.
The IPv6 prefix string is formatted as "%x:%x:%x:...[::]/plen".
Returns
An InfoString containing the string representation of the Prefix.
Referenced by Leader::GetServiceId().
ToString() [2/3]
void ToString (char * aBuffer, uint16_t aSize) const
This method converts the prefix to a string.
The IPv6 prefix string is formatted as "%x:%x:%x:...[::]/plen".
If the resulting string does not fit in aBuffer (within its aSize characters), the string will be truncated but the outputted string is always null-terminated.
Parameters
[out] aBuffer A pointer to a char array to output the string (MUST NOT be nullptr).
[in] aSize The size of aBuffer (in bytes).
ToString() [3/3]
void ToString (StringWriter & aWriter) const private
References StringWriter::Append(), ot::AsCoreType(), and Address::kSize.
Field Documentation
kMaxLength
constexpr uint8_t kMaxLength = OT_IP6_ADDRESS_SIZE * CHAR_BIT static
Max length of a prefix in bits.
Referenced by PrefixInfoOption::IsValid(), and RouteInfoOption::IsValid().
kMaxSize
constexpr uint8_t kMaxSize = OT_IP6_ADDRESS_SIZE static
Max (byte) size of a prefix.
kInfoStringSize
constexpr uint16_t kInfoStringSize = OT_IP6_PREFIX_STRING_SIZE static
Info string size (ToString()).
The documentation for this class was generated from the following files:
ip6_address.hpp
ip6_address.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale