OpenThread: BackboneRouter::ServerData Class Reference
BackboneRouter::ServerData Class Reference
#include <network_data_service.hpp>
Public Member Functions
uint8_t GetLength (void) const
uint32_t GetMlrTimeout (void) const
uint16_t GetReregistrationDelay (void) const
uint8_t GetSequenceNumber (void) const
void SetMlrTimeout (uint32_t aMlrTimeout)
void SetReregistrationDelay (uint16_t aReregistrationDelay)
void SetSequenceNumber (uint8_t aSequenceNumber)
Private Attributes
uint32_t mMlrTimeout
uint16_t mReregistrationDelay
uint8_t mSequenceNumber
Detailed Description
This class implements the generation and parsing of "Backbone Router Service" server data.
Member Function Documentation
GetLength()
uint8_t GetLength (void) const inline
This method returns the length (in bytes) of server data.
Returns
The server data length in bytes.
GetSequenceNumber()
uint8_t GetSequenceNumber (void) const inline
This method returns the sequence number of Backbone Router.
Returns
The sequence number of the Backbone Router.
References BackboneRouter::ServerData::mSequenceNumber.
Referenced by Manager::GetBackboneRouterPrimary(), and Manager::IsBackboneRouterPreferredTo().
SetSequenceNumber()
void SetSequenceNumber (uint8_t aSequenceNumber) inline
This method sets the sequence number of Backbone Router.
Parameters
[in] aSequenceNumber The sequence number of Backbone Router.
References BackboneRouter::ServerData::mSequenceNumber.
GetReregistrationDelay()
uint16_t GetReregistrationDelay (void) const inline
This method returns the Registration Delay (in seconds) of Backbone Router.
Returns
The BBR Registration Delay (in seconds) of Backbone Router.
References ot::Encoding::BigEndian::HostSwap16(), and BackboneRouter::ServerData::mReregistrationDelay.
Referenced by Manager::GetBackboneRouterPrimary().
SetReregistrationDelay()
void SetReregistrationDelay (uint16_t aReregistrationDelay) inline
This method sets the Registration Delay (in seconds) of Backbone Router.
Parameters
[in] aReregistrationDelay The Registration Delay (in seconds) of Backbone Router.
References ot::Encoding::BigEndian::HostSwap16(), and BackboneRouter::ServerData::mReregistrationDelay.
GetMlrTimeout()
uint32_t GetMlrTimeout (void) const inline
This method returns the multicast listener report timeout (in seconds) of Backbone Router.
Returns
The multicast listener report timeout (in seconds) of Backbone Router.
References ot::Encoding::BigEndian::HostSwap32(), and BackboneRouter::ServerData::mMlrTimeout.
Referenced by Manager::GetBackboneRouterPrimary().
SetMlrTimeout()
void SetMlrTimeout (uint32_t aMlrTimeout) inline
This method sets multicast listener report timeout (in seconds) of Backbone Router.
Parameters
[in] aMlrTimeout The multicast listener report timeout (in seconds) of Backbone Router.
References ot::Encoding::BigEndian::HostSwap32(), and BackboneRouter::ServerData::mMlrTimeout.
Field Documentation
mSequenceNumber
uint8_t mSequenceNumber private
Referenced by BackboneRouter::ServerData::GetSequenceNumber(), DnsSrpAnycast::ServiceData::GetSequenceNumber(), and BackboneRouter::ServerData::SetSequenceNumber().
mReregistrationDelay
uint16_t mReregistrationDelay private
Referenced by BackboneRouter::ServerData::GetReregistrationDelay(), and BackboneRouter::ServerData::SetReregistrationDelay().
mMlrTimeout
uint32_t mMlrTimeout private
Referenced by BackboneRouter::ServerData::GetMlrTimeout(), and BackboneRouter::ServerData::SetMlrTimeout().
The documentation for this class was generated from the following file:
network_data_service.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale