OpenThread: Decoder Class Reference
Decoder Class Reference
#include <spinel_decoder.hpp>
Public Types
enum { kMaxNestedStructs = 4 }
Public Member Functions
otError CloseStruct (void)
Decoder (void)
const uint8_t * GetFrame (void) const
uint16_t GetLength (void) const
uint16_t GetReadLength (void) const
uint16_t GetRemainingLength (void) const
uint16_t GetRemainingLengthInStruct (void) const
void Init (const uint8_t *aFrame, uint16_t aLength)
bool IsAllRead (void) const
bool IsAllReadInStruct (void) const
otError OpenStruct (void)
otError ReadBool (bool &aBool)
otError ReadData (const uint8_t *&aData, uint16_t &aDataLen)
otError ReadDataWithLen (const uint8_t *&aData, uint16_t &aDataLen)
otError ReadEui48 (const spinel_eui48_t *&aEui48Ptr)
otError ReadEui48 (const uint8_t *&aEui48BufPtr)
otError ReadEui48 (spinel_eui48_t &aEui48)
otError ReadEui64 (const spinel_eui64_t *&aEui64Ptr)
otError ReadEui64 (const otExtAddress *&aEui64Ptr)
otError ReadEui64 (const uint8_t *&aEui64BufPtr)
otError ReadEui64 (spinel_eui64_t &aEui64)
otError ReadEui64 (otExtAddress &aEui64)
otError ReadInt16 (int16_t &aInt16)
otError ReadInt32 (int32_t &aInt32)
otError ReadInt64 (int64_t &aInt64)
otError ReadInt8 (int8_t &aInt8)
otError ReadIp6Address (const spinel_ipv6addr_t *&aIp6AddrPtr)
otError ReadIp6Address (const otIp6Address *&aIp6AddrPtr)
otError ReadIp6Address (const uint8_t *&aIp6AddrBufPtr)
otError ReadIp6Address (spinel_ipv6addr_t &aIp6Addr)
otError ReadIp6Address (otIp6Address &aIp6Addr)
otError ReadUint16 (uint16_t &aUint16)
otError ReadUint32 (uint32_t &aUint32)
otError ReadUint64 (uint64_t &aUint64)
otError ReadUint8 (uint8_t &aUint8)
otError ReadUintPacked (unsigned int &aUint)
otError ReadUtf8 (const char *&aUtf8)
void Reset (void)
otError ResetToSaved (void)
void SavePosition (void)
Private Member Functions
void ClearSavedPosition (void)
bool IsSavedPositionValid (void) const
otError ReadItem (const uint8_t **aPtr, uint16_t aSize)
Private Attributes
uint16_t mEnd
const uint8_t * mFrame
uint16_t mIndex
uint16_t mLength
uint8_t mNumOpenStructs
uint16_t mPrevEnd [kMaxNestedStructs]
uint16_t mSavedEnd
uint16_t mSavedIndex
uint8_t mSavedNumOpenStructs
Detailed Description
This class defines a spinel decoder.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kMaxNestedStructs
Maximum number of nested structs.
Constructor & Destructor Documentation
Decoder()
Decoder (void)
This constructor initializes a Decoder object.
Member Function Documentation
Init()
void Init (const uint8_t * aFrame, uint16_t aLength)
This method initializes the decoder to start decoding a new frame.
It sets the read position to the start of the frame and also erases/voids any saved positions (see SavePosition() and ResetToSaved() methods).
Parameters
[in] aFrame Pointer to the buffer containing the frame to be decoded.
[in] aLength Length (number of bytes) of the frame.
References Decoder::ClearSavedPosition(), Decoder::mFrame, Decoder::mLength, and Decoder::Reset().
Referenced by NcpBase::HandleReceive(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
GetFrame()
const uint8_t* GetFrame (void) const inline
This method returns the pointer to the start of the frame.
Returns
A pointer to buffer containing current frame being decoded.
References Decoder::mFrame.
GetLength()
uint16_t GetLength (void) const inline
This method returns the total length of current frame being decoded.
Returns
The length of current frame being decoded.
References Decoder::mLength.
GetReadLength()
uint16_t GetReadLength (void) const inline
This method returns the number of bytes that are already read/decoded from the frame.
Returns
The number of bytes already read from frame.
References Decoder::mIndex.
GetRemainingLength()
uint16_t GetRemainingLength (void) const inline
This method returns the number of remaining (not yet read/decoded) bytes in the frame.
Returns
The number of remaining unread bytes in the frame.
References Decoder::mIndex, and Decoder::mLength.
IsAllRead()
bool IsAllRead (void) const inline
This method indicates whether or not all the bytes in the frame are read.
Returns
TRUE if all the bytes in the buffer are read, FALSE otherwise.
References Decoder::mIndex, Decoder::mLength, Decoder::ReadBool(), Decoder::ReadInt16(), Decoder::ReadInt32(), Decoder::ReadInt64(), Decoder::ReadInt8(), Decoder::ReadUint16(), Decoder::ReadUint32(), Decoder::ReadUint64(), Decoder::ReadUint8(), Decoder::ReadUintPacked(), and Decoder::Reset().
Reset()
void Reset (void)
This method resets the read position to beginning of frame. It will also void/erase any previously saved position using SavePosition() method.
References Decoder::ClearSavedPosition(), Decoder::mEnd, Decoder::mIndex, Decoder::mLength, and Decoder::mNumOpenStructs.
Referenced by Decoder::Init(), and Decoder::IsAllRead().
ReadBool()
otError ReadBool (bool & aBool)
This method decodes and reads a boolean value form the frame.
On success, the read position gets updated.
Parameters
[out] aBool Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, OT_ERROR_PARSE, Decoder::ReadUint8(), and SuccessOrExit.
Referenced by NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet(), and Decoder::IsAllRead().
ReadInt8()
otError ReadInt8 (int8_t & aInt8)
This method decodes and reads an int8_t value form the frame.
On success, the read position get updated.
Parameters
[out] aInt8 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, Decoder::ReadUint8(), and SuccessOrExit.
Referenced by NcpBase::HandlePropertySet(), and Decoder::IsAllRead().
ReadUint8()
otError ReadUint8 (uint8_t & aUint8)
This method decodes and reads an uint8_t value form the frame.
On success, the read position gets updated.
Parameters
[out] aUint8 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::mEnd, Decoder::mFrame, Decoder::mIndex, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by NcpBase::CommandHandler_RESET(), NcpBase::DecodeChannelMask(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), NcpBase::HandleReceive(), Decoder::IsAllRead(), Decoder::ReadBool(), Decoder::ReadInt8(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
ReadInt16()
otError ReadInt16 (int16_t & aInt16)
This method decodes and reads an int16_t value form the frame.
On success, the read position gets updated.
Parameters
[out] aInt16 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, Decoder::ReadUint16(), and SuccessOrExit.
Referenced by Decoder::IsAllRead().
ReadUint16()
otError ReadUint16 (uint16_t & aUint16)
This method decodes and reads an uint16_t value form the frame.
On success, the read position gets updated.
Parameters
[out] aUint16 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::mEnd, Decoder::mFrame, Decoder::mIndex, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandlePropertySet(), Decoder::IsAllRead(), Decoder::OpenStruct(), Decoder::ReadDataWithLen(), Decoder::ReadInt16(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
ReadInt32()
otError ReadInt32 (int32_t & aInt32)
This method decodes and reads an int32_t value form the frame.
On success, the read position gets updated.
Parameters
[out] aInt32 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, Decoder::ReadUint32(), and SuccessOrExit.
Referenced by Decoder::IsAllRead().
ReadUint32()
otError ReadUint32 (uint32_t & aUint32)
This method decodes and reads an uint32_t value form the frame.
On success, the read position gets updated.
Parameters
[out] aUint32 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::mEnd, Decoder::mFrame, Decoder::mIndex, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), Decoder::IsAllRead(), Decoder::ReadInt32(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
ReadInt64()
otError ReadInt64 (int64_t & aInt64)
This method decodes and reads an int64_t value form the frame.
On success, the read position gets updated.
Parameters
[out] aInt64 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, Decoder::ReadUint64(), and SuccessOrExit.
Referenced by Decoder::IsAllRead().
ReadUint64()
otError ReadUint64 (uint64_t & aUint64)
This method decodes and reads an uint64_t value form the frame.
On success, the read position gets updated.
Parameters
[out] aUint64 Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::mEnd, Decoder::mFrame, Decoder::mIndex, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by NcpBase::HandlePropertySet(), Decoder::IsAllRead(), and Decoder::ReadInt64().
ReadUintPacked()
otError ReadUintPacked (unsigned int & aUint)
This method decodes (using spinel packed integer format) and reads an unsigned integer value form the frame.
On success, the read position gets updated.
Parameters
[out] aUint Reference to variable to output the read value.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::mEnd, Decoder::mFrame, Decoder::mIndex, OT_ERROR_NONE, OT_ERROR_PARSE, spinel_packed_uint_decode(), and VerifyOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandleCommand(), NcpBase::HandlePropertyInsert(), NcpBase::HandlePropertyRemove(), NcpBase::HandlePropertySet(), Decoder::IsAllRead(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
ReadIp6Address() [1/5]
otError ReadIp6Address (const spinel_ipv6addr_t *& aIp6AddrPtr) inline
This method decodes and reads an IPv6 address form the frame.
On success, the read position gets updated.
Parameters
[out] aIp6AddrPtr Reference to IPv6 address pointer to output the value (as spinel_ipv6addr_t). On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::ReadItem().
Referenced by Decoder::ReadIp6Address(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
ReadIp6Address() [2/5]
otError ReadIp6Address (const otIp6Address *& aIp6AddrPtr) inline
This method decodes and reads an IPv6 address form the frame.
On success, the read position gets updated.
Parameters
[out] aIp6AddrPtr Reference to IPv6 address pointer to output the value (as otIp6Address). On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::ReadItem().
ReadIp6Address() [3/5]
otError ReadIp6Address (const uint8_t *& aIp6AddrBufPtr) inline
This method decodes and reads an IPv6 address form the frame.
On success, the read position gets updated.
Parameters
[out] aIp6AddrBufPtr Reference to a buffer pointer to output the value. On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::ReadIp6Address(), and Decoder::ReadItem().
ReadIp6Address() [4/5]
otError ReadIp6Address (spinel_ipv6addr_t & aIp6Addr)
This method decodes and reads an IPv6 address form the frame.
On success, the read position gets updated and the IP address is copied into the given output variable.
Parameters
[out] aIp6Addr Reference to IPv6 address variable to output the value (as spinel_ipv6addr_t). On success, the address is copied into the output variable.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, OT_ERROR_PARSE, Decoder::ReadIp6Address(), SuccessOrExit, and VerifyOrExit.
ReadIp6Address() [5/5]
otError ReadIp6Address (otIp6Address & aIp6Addr)
This method decodes and reads an IPv6 address form the frame.
On success, the read position gets updated and the IP address is copied into the given output variable.
Parameters
[out] aIp6Addr Reference to IPv6 address variable to output the value (as otIp6Address). On success, the address is copied into the output variable.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, OT_ERROR_PARSE, Decoder::ReadIp6Address(), SuccessOrExit, and VerifyOrExit.
ReadEui64() [1/5]
otError ReadEui64 (const spinel_eui64_t *& aEui64Ptr) inline
This method decodes and reads an EUI64 value form the frame.
On success, the read position gets updated.
Parameters
[out] aEui64Ptr Reference to an EUI64 pointer to output the value (as spinel_eui64_t). On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::ReadItem().
Referenced by NcpBase::HandlePropertySet(), and Decoder::ReadEui64().
ReadEui64() [2/5]
otError ReadEui64 (const otExtAddress *& aEui64Ptr) inline
This method decodes and reads an EUI64 value form the frame.
On success, the read position gets updated.
Parameters
[out] aEui64Ptr Reference to an EUI64 pointer to output the value (as otExtAddress). On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::ReadItem().
ReadEui64() [3/5]
otError ReadEui64 (const uint8_t *& aEui64BufPtr) inline
This method decodes and reads an EUI64 value form the frame.
On success, the read position gets updated.
Parameters
[out] aEui64BufPtr Reference to a buffer pointer to output the value. On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::ReadEui64(), and Decoder::ReadItem().
ReadEui64() [4/5]
otError ReadEui64 (spinel_eui64_t & aEui64)
This method decodes and reads an EUI64 value form the frame.
On success, the read position gets updated and the EUI64 value is copied into the given output variable.
Parameters
[out] aEui64 Reference to EUI64 variable to output the value (as spinel_eui64_t). On success, the address is copied into the output variable.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, OT_ERROR_PARSE, Decoder::ReadEui64(), SuccessOrExit, and VerifyOrExit.
ReadEui64() [5/5]
otError ReadEui64 (otExtAddress & aEui64)
This method decodes and reads an EUI64 value form the frame.
On success, the read position gets updated and the EUI64 value is copied into the given output variable.
Parameters
[out] aEui64 Reference to EUI64 variable to output the value (as otExtAddress). On success, the address is copied into the output variable.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, OT_ERROR_PARSE, Decoder::ReadEui64(), SuccessOrExit, and VerifyOrExit.
ReadEui48() [1/3]
otError ReadEui48 (const spinel_eui48_t *& aEui48Ptr) inline
This method decodes and reads an EUI48 value form the frame.
On success, the read position gets updated.
Parameters
[out] aEui48Ptr Reference to an EUI48 pointer to output the value (as spinel_eui48_t). On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::ReadItem().
Referenced by Decoder::ReadEui48().
ReadEui48() [2/3]
otError ReadEui48 (const uint8_t *& aEui48BufPtr) inline
This method decodes and reads an EUI48 value form the frame.
On success, the read position gets updated.
Parameters
[out] aEui48BufPtr Reference to a buffer pointer to output the value. On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::CloseStruct(), Decoder::OpenStruct(), Decoder::ReadData(), Decoder::ReadDataWithLen(), Decoder::ReadEui48(), Decoder::ReadItem(), and Decoder::ReadUtf8().
ReadEui48() [3/3]
otError ReadEui48 (spinel_eui48_t & aEui48)
This method decodes and reads an EUI48 value form the frame.
On success, the read position gets updated and the EUI48 value is copied into the given output variable.
Parameters
[out] aEui48 Reference to EUI48 variable to output the value (as spinel_eui48_t). On success, value is copied into the output variable.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, OT_ERROR_PARSE, Decoder::ReadEui48(), SuccessOrExit, and VerifyOrExit.
ReadUtf8()
otError ReadUtf8 (const char *& aUtf8)
This method decodes and reads a UTF8 string form the frame.
On success, the read position gets updated.
Parameters
[out] aUtf8 Reference to a char pointer to output the string. On success, the pointer variable is updated.
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::mEnd, Decoder::mFrame, Decoder::mIndex, OT_ERROR_NONE, OT_ERROR_PARSE, ot::StringLength(), and VerifyOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), Decoder::ReadEui48(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
ReadData()
otError ReadData (const uint8_t *& aData, uint16_t & aDataLen)
This method decodes and reads a data blob (sequence of bytes) form the frame.
On success, the read position gets updated.
Parameters
[out] aData Reference to pointer variable to output the data. On success, the pointer variable is updated.
[out] aDataLen Reference to variable to output the data length (number of bytes).
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References Decoder::mEnd, Decoder::mIndex, and Decoder::ReadItem().
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandleCommandPropertyInsertRemove(), Decoder::ReadEui48(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
ReadDataWithLen()
otError ReadDataWithLen (const uint8_t *& aData, uint16_t & aDataLen)
This method decodes and reads a data blob (sequence of bytes) with data length.
The data length is assumed to be prepended before the data content (encoded as a uint16_t). The size of the length field should not be included in the length value. This method corresponds to SPINEL_DATATYPE_DATA_WLEN type.
Parameters
[out] aData Reference to pointer variable to output the data. On success, the pointer variable is updated.
[out] aDataLen Reference to variable to out the data length (number of bytes).
Return values
OT_ERROR_NONE Successfully read the value.
OT_ERROR_PARSE Failed to parse/decode the value.
References OT_ERROR_NONE, Decoder::ReadItem(), Decoder::ReadUint16(), and SuccessOrExit.
Referenced by Decoder::ReadEui48().
OpenStruct()
otError OpenStruct (void)
This method opens a struct in the frame.
After a successful call to this method, all the subsequent Read{SomeType}() methods decode and read the field/value from the current open struct until the struct is closed using CloseStruct() method. Structures can be nested. Up to kMaxNestedStructs nested structs can be opened at the same time.
Return values
OT_ERROR_NONE Successfully opened a struct.
OT_ERROR_PARSE Failed to parse/open a struct.
OT_ERROR_INVALID_STATE Already at the maximum number of nested open structures.
References Decoder::kMaxNestedStructs, Decoder::mEnd, Decoder::mIndex, Decoder::mNumOpenStructs, Decoder::mPrevEnd, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_ERROR_PARSE, Decoder::ReadUint16(), SuccessOrExit, and VerifyOrExit.
Referenced by Decoder::ReadEui48(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
CloseStruct()
otError CloseStruct (void)
This method closes the most recently opened struct (using OpenStruct()) in the frame.
On success, the read position is moved to end of the struct skipping any unread bytes within the struct.
Return values
OT_ERROR_NONE Successfully closed the struct.
OT_ERROR_INVALID_STATE There is no current open struct to close.
References Decoder::ClearSavedPosition(), Decoder::IsSavedPositionValid(), Decoder::mEnd, Decoder::mIndex, Decoder::mNumOpenStructs, Decoder::mPrevEnd, Decoder::mSavedNumOpenStructs, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, and VerifyOrExit.
Referenced by Decoder::ReadEui48(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
GetRemainingLengthInStruct()
uint16_t GetRemainingLengthInStruct (void) const inline
This method returns the number of remaining/unread bytes in the current inner-most open structure.
If there is no currently open structure the number of remaining bytes in whole frame is returned instead.
Returns
The number of remaining unread bytes in the inner-most open structure.
References Decoder::mEnd, and Decoder::mIndex.
Referenced by NcpBase::CommandHandler_RESET(), NcpBase::HandlePropertySet(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
IsAllReadInStruct()
bool IsAllReadInStruct (void) const inline
This method indicates whether or not all the bytes in inner-most open structure are read.
If there is no currently open structure, the whole frame is considered instead.
Returns
TRUE if all the bytes are read, FALSE otherwise.
References Decoder::mEnd, Decoder::mIndex, Decoder::ReadItem(), Decoder::ResetToSaved(), and Decoder::SavePosition().
Referenced by NcpBase::DecodeChannelMask(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
SavePosition()
void SavePosition (void)
This method saves the current read position in the frame.
A subsequent call to SavePosition() will overwrite the previously saved position. The saved position can be used to move the read position back (using ResetToSaved()) and re-read the same content.
Saved position can be within an open struct, and it remembers its enclosing struct. When the enclosing struct is closed, the saved position will be voided and can no longer be used. This ensures that we cannot jump back to middle an already fully decoded/read and closed struct.
References Decoder::mEnd, Decoder::mIndex, Decoder::mNumOpenStructs, Decoder::mSavedEnd, Decoder::mSavedIndex, and Decoder::mSavedNumOpenStructs.
Referenced by NcpBase::HandleCommandPropertyInsertRemove(), and Decoder::IsAllReadInStruct().
ResetToSaved()
otError ResetToSaved (void)
This method resets/moves the read position to a previously saved position.
The saved position remembers its enclosing structure. When ResetToSaved() is called, the current open structure will be the same as when position was saved.
Return values
OT_ERROR_NONE Successfully reset the read position.
OT_ERROR_INVALID_STATE The saved position is not valid (there is no saved position or the saved position was voided since its enclosing struct was closed).
References Decoder::IsSavedPositionValid(), Decoder::mEnd, Decoder::mIndex, Decoder::mNumOpenStructs, Decoder::mSavedEnd, Decoder::mSavedIndex, Decoder::mSavedNumOpenStructs, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, and VerifyOrExit.
Referenced by NcpBase::HandleCommandPropertyInsertRemove(), and Decoder::IsAllReadInStruct().
ReadItem()
otError ReadItem (const uint8_t ** aPtr, uint16_t aSize) private
References Decoder::mEnd, Decoder::mFrame, Decoder::mIndex, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by Decoder::IsAllReadInStruct(), Decoder::ReadData(), Decoder::ReadDataWithLen(), Decoder::ReadEui48(), Decoder::ReadEui64(), and Decoder::ReadIp6Address().
ClearSavedPosition()
void ClearSavedPosition (void) inline private
References Decoder::mLength, and Decoder::mSavedIndex.
Referenced by Decoder::CloseStruct(), Decoder::Init(), and Decoder::Reset().
IsSavedPositionValid()
bool IsSavedPositionValid (void) const inline private
References Decoder::mLength, and Decoder::mSavedIndex.
Referenced by Decoder::CloseStruct(), and Decoder::ResetToSaved().
Field Documentation
mFrame
const uint8_t* mFrame private
Referenced by Decoder::GetFrame(), Decoder::Init(), Decoder::ReadItem(), Decoder::ReadUint16(), Decoder::ReadUint32(), Decoder::ReadUint64(), Decoder::ReadUint8(), Decoder::ReadUintPacked(), and Decoder::ReadUtf8().
mLength
uint16_t mLength private
Referenced by Decoder::ClearSavedPosition(), Decoder::GetLength(), Decoder::GetRemainingLength(), Decoder::Init(), Decoder::IsAllRead(), Decoder::IsSavedPositionValid(), and Decoder::Reset().
mIndex
uint16_t mIndex private
Referenced by Decoder::CloseStruct(), Decoder::GetReadLength(), Decoder::GetRemainingLength(), Decoder::GetRemainingLengthInStruct(), Decoder::IsAllRead(), Decoder::IsAllReadInStruct(), Decoder::OpenStruct(), Decoder::ReadData(), Decoder::ReadItem(), Decoder::ReadUint16(), Decoder::ReadUint32(), Decoder::ReadUint64(), Decoder::ReadUint8(), Decoder::ReadUintPacked(), Decoder::ReadUtf8(), Decoder::Reset(), Decoder::ResetToSaved(), and Decoder::SavePosition().
mEnd
uint16_t mEnd private
Referenced by Decoder::CloseStruct(), Decoder::GetRemainingLengthInStruct(), Decoder::IsAllReadInStruct(), Decoder::OpenStruct(), Decoder::ReadData(), Decoder::ReadItem(), Decoder::ReadUint16(), Decoder::ReadUint32(), Decoder::ReadUint64(), Decoder::ReadUint8(), Decoder::ReadUintPacked(), Decoder::ReadUtf8(), Decoder::Reset(), Decoder::ResetToSaved(), and Decoder::SavePosition().
mNumOpenStructs
uint8_t mNumOpenStructs private
Referenced by Decoder::CloseStruct(), Decoder::OpenStruct(), Decoder::Reset(), Decoder::ResetToSaved(), and Decoder::SavePosition().
mSavedNumOpenStructs
uint8_t mSavedNumOpenStructs private
Referenced by Decoder::CloseStruct(), Decoder::ResetToSaved(), and Decoder::SavePosition().
mSavedIndex
uint16_t mSavedIndex private
Referenced by Decoder::ClearSavedPosition(), Decoder::IsSavedPositionValid(), Decoder::ResetToSaved(), and Decoder::SavePosition().
mSavedEnd
uint16_t mSavedEnd private
Referenced by Decoder::ResetToSaved(), and Decoder::SavePosition().
mPrevEnd
uint16_t mPrevEnd[kMaxNestedStructs] private
Referenced by Decoder::CloseStruct(), and Decoder::OpenStruct().
The documentation for this class was generated from the following files:
spinel_decoder.hpp
spinel_decoder.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale