OpenThread: HdlcInterface Class Reference
HdlcInterface Class Reference
#include <hdlc_interface.hpp>
Public Member Functions
void Deinit (void)
uint32_t GetBusSpeed (void) const
const otRcpInterfaceMetrics * GetRcpInterfaceMetrics (void) const
HdlcInterface (Spinel::SpinelInterface::ReceiveFrameCallback aCallback, void *aCallbackContext, Spinel::SpinelInterface::RxFrameBuffer &aFrameBuffer)
otError Init (const Url::Url &aRadioUrl)
void OnRcpReset (void)
void Process (const RadioProcessContext &aContext)
otError ResetConnection (void)
otError SendFrame (const uint8_t *aFrame, uint16_t aLength)
void UpdateFdSet (fd_set &aReadFdSet, fd_set &aWriteFdSet, int &aMaxFd, struct timeval &aTimeout)
otError WaitForFrame (uint64_t aTimeoutUs)
~HdlcInterface (void)
Private Types
enum {
kMaxFrameSize = Spinel::SpinelInterface::kMaxFrameSize, kMaxWaitTime = 2000, kResetTimeout = 5000, kOpenFileDelay = 500,
kRemoveRcpDelay
}
Private Member Functions
void CloseFile (void)
void Decode (const uint8_t *aBuffer, uint16_t aLength)
void HandleHdlcFrame (otError aError)
HdlcInterface (const HdlcInterface &)
int OpenFile (const Url::Url &aRadioUrl)
HdlcInterface & operator= (const HdlcInterface &)
void Read (void)
otError WaitForWritable (void)
otError Write (const uint8_t *aFrame, uint16_t aLength)
Static Private Member Functions
static int ForkPty (const Url::Url &aRadioUrl)
static void HandleHdlcFrame (void *aContext, otError aError)
Private Attributes
uint32_t mBaudRate
Hdlc::Decoder mHdlcDecoder
otRcpInterfaceMetrics mInterfaceMetrics
const Url::Url * mRadioUrl
Spinel::SpinelInterface::RxFrameBuffer & mReceiveFrameBuffer
Spinel::SpinelInterface::ReceiveFrameCallback mReceiveFrameCallback
void * mReceiveFrameContext
int mSockFd
Detailed Description
This class defines an HDLC interface to the Radio Co-processor (RCP)
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kMaxFrameSize
kMaxWaitTime
Maximum wait time in Milliseconds for socket to become writable (see SendFrame).
kResetTimeout
Maximum wait time in Milliseconds for file to become ready (see ResetConnection).
kOpenFileDelay
Delay between open file calls, in Milliseconds (see ResetConnection).
kRemoveRcpDelay
Delay for removing RCP device from host OS after hard reset (see ResetConnection).
Constructor & Destructor Documentation
HdlcInterface() [1/2]
HdlcInterface (Spinel::SpinelInterface::ReceiveFrameCallback aCallback, void * aCallbackContext, Spinel::SpinelInterface::RxFrameBuffer & aFrameBuffer)
This constructor initializes the object.
Parameters
[in] aCallback Callback on frame received
[in] aCallbackContext Callback context
[in] aFrameBuffer A reference to a RxFrameBuffer object.
~HdlcInterface()
~HdlcInterface (void)
This destructor deinitializes the object.
HdlcInterface() [2/2]
HdlcInterface (const HdlcInterface &) private
Member Function Documentation
Init()
otError Init (const Url::Url & aRadioUrl)
This method initializes the interface to the Radio Co-processor (RCP)
Note
This method should be called before reading and sending spinel frames to the interface.
Parameters
[in] aRadioUrl RadioUrl parsed from radio url.
Return values
OT_ERROR_NONE The interface is initialized successfully
OT_ERROR_ALREADY The interface is already initialized.
OT_ERROR_INVALID_ARGS The UART device or executable cannot be found or failed to open/run.
References ExitNow, Url::GetPath(), OT_ERROR_ALREADY, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_EXIT_INVALID_ARGUMENTS, otLogCritPlat(), VerifyOrDie, and VerifyOrExit.
Deinit()
void Deinit (void)
This method deinitializes the interface to the RCP.
SendFrame()
otError SendFrame (const uint8_t * aFrame, uint16_t aLength)
This method encodes and sends a spinel frame to Radio Co-processor (RCP) over the socket.
This is blocking call, i.e., if the socket is not writable, this method waits for it to become writable for up to kMaxWaitTime interval.
Parameters
[in] aFrame A pointer to buffer containing the spinel frame to send.
[in] aLength The length (number of bytes) in the frame.
Return values
OT_ERROR_NONE Successfully encoded and sent the spinel frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to encode the frame.
OT_ERROR_FAILED Failed to send due to socket not becoming writable within kMaxWaitTime.
References Encoder::BeginFrame(), Encoder::Encode(), Encoder::EndFrame(), FrameBuffer< kSize >::GetFrame(), FrameBuffer< kSize >::GetLength(), OT_ERROR_NONE, and SuccessOrExit.
WaitForFrame()
otError WaitForFrame (uint64_t aTimeoutUs)
This method waits for receiving part or all of spinel frame within specified interval.
Parameters
[in] aTimeout The timeout value in microseconds.
Return values
OT_ERROR_NONE Part or all of spinel frame is received.
OT_ERROR_RESPONSE_TIMEOUT No spinel frame is received within aTimeout.
References Decoder::Decode(), DieNow, DieNowWithMessage, ExitNow, VirtualTimeEvent::mData, VirtualTimeEvent::mDataLength, VirtualTimeEvent::mDelay, VirtualTimeEvent::mEvent, OT_ERROR_NONE, OT_ERROR_RESPONSE_TIMEOUT, OT_EXIT_FAILURE, OT_SIM_EVENT_ALARM_FIRED, OT_SIM_EVENT_RADIO_SPINEL_WRITE, US_PER_S, VerifyOrExit, virtualTimeReceiveEvent(), and virtualTimeSendSleepEvent().
UpdateFdSet()
void UpdateFdSet (fd_set & aReadFdSet, fd_set & aWriteFdSet, int & aMaxFd, struct timeval & aTimeout)
This method updates the file descriptor sets with file descriptors used by the radio driver.
Parameters
[in,out] aReadFdSet A reference to the read file descriptors.
[in,out] aWriteFdSet A reference to the write file descriptors.
[in,out] aMaxFd A reference to the max file descriptor.
[in,out] aTimeout A reference to the timeout.
References OT_UNUSED_VARIABLE.
Process()
void Process (const RadioProcessContext & aContext)
This method performs radio driver processing.
Parameters
[in] aContext The context containing fd_sets.
References RadioProcessContext::mReadFdSet.
GetBusSpeed()
uint32_t GetBusSpeed (void) const inline
This method returns the bus speed between the host and the radio.
Returns
Bus speed in bits/second.
References HdlcInterface::mBaudRate, HdlcInterface::OnRcpReset(), and HdlcInterface::ResetConnection().
OnRcpReset()
void OnRcpReset (void)
This method is called when RCP failure detected and resets internal states of the interface.
Referenced by HdlcInterface::GetBusSpeed().
ResetConnection()
otError ResetConnection (void)
This method is called when RCP is reset to recreate the connection with it.
References ExitNow, OT_ERROR_FAILED, OT_ERROR_NONE, otLogCritPlat(), otPlatTimeGet(), and US_PER_MS.
Referenced by HdlcInterface::GetBusSpeed().
GetRcpInterfaceMetrics()
const otRcpInterfaceMetrics* GetRcpInterfaceMetrics (void) const inline
This method returns the RCP interface metrics.
Returns
The RCP interface metrics.
References HdlcInterface::CloseFile(), HdlcInterface::Decode(), HdlcInterface::ForkPty(), HdlcInterface::HandleHdlcFrame(), HdlcInterface::mInterfaceMetrics, HdlcInterface::OpenFile(), HdlcInterface::Read(), HdlcInterface::WaitForWritable(), and HdlcInterface::Write().
Read()
void Read (void) private
This method instructs HdlcInterface to read and decode data from radio over the socket.
If a full HDLC frame is decoded while reading data, this method invokes the HandleReceivedFrame() (on the aCallback object from constructor) to pass the received frame to be processed.
References Decoder::Decode(), DieNow, and OT_EXIT_ERROR_ERRNO.
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
WaitForWritable()
otError WaitForWritable (void) private
This method waits for the socket file descriptor associated with the HDLC interface to become writable within kMaxWaitTime interval.
Return values
OT_ERROR_NONE Socket is writable.
OT_ERROR_FAILED Socket did not become writable within kMaxWaitTime.
References DieNow, ExitNow, OT_ERROR_FAILED, OT_ERROR_NONE, OT_EXIT_ERROR_ERRNO, OT_EXIT_FAILURE, otPlatTimeGet(), US_PER_MS, and US_PER_S.
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
Write()
otError Write (const uint8_t * aFrame, uint16_t aLength) private
This method writes a given frame to the socket.
This is blocking call, i.e., if the socket is not writable, this method waits for it to become writable for up to kMaxWaitTime interval.
Parameters
[in] aFrame A pointer to buffer containing the frame to write.
[in] aLength The length (number of bytes) in the frame.
Return values
OT_ERROR_NONE Frame was written successfully.
OT_ERROR_FAILED Failed to write due to socket not becoming writable within kMaxWaitTime.
References OT_ERROR_NONE, OT_EXIT_ERROR_ERRNO, SuccessOrExit, VerifyOrDie, and virtualTimeSendRadioSpinelWriteEvent().
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
Decode()
void Decode (const uint8_t * aBuffer, uint16_t aLength) private
This method performs HDLC decoding on received data.
If a full HDLC frame is decoded while reading data, this method invokes the HandleReceivedFrame() (on the aCallback object from constructor) to pass the received frame to be processed.
Parameters
[in] aBuffer A pointer to buffer containing data.
[in] aLength The length (number of bytes) in the buffer.
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
HandleHdlcFrame() [1/2]
void HandleHdlcFrame (void * aContext, otError aError) static private
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
HandleHdlcFrame() [2/2]
void HandleHdlcFrame (otError aError) private
References OT_ERROR_NONE, otLogWarnPlat(), and otThreadErrorToString().
OpenFile()
int OpenFile (const Url::Url & aRadioUrl) private
This method opens file specified by aRadioUrl.
Parameters
[in] aRadioUrl A reference to object containing path to file and data for configuring the connection with tty type file.
Return values
The file descriptor of newly opened file.
References DieNow, ExitNow, Url::GetPath(), Url::GetValue(), OT_EXIT_FAILURE, OT_EXIT_INVALID_ARGUMENTS, and VerifyOrExit.
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
CloseFile()
void CloseFile (void) private
This method closes file associated with the file descriptor.
References VerifyOrExit.
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
ForkPty()
int ForkPty (const Url::Url & aRadioUrl) static private
References DieNowWithMessage, Url::GetPath(), Url::GetValue(), OT_ARRAY_LENGTH, OT_EXIT_ERROR_ERRNO, OT_EXIT_INVALID_ARGUMENTS, and VerifyOrDie.
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
operator=()
HdlcInterface& operator= (const HdlcInterface &) private
Field Documentation
mReceiveFrameCallback
Spinel::SpinelInterface::ReceiveFrameCallback mReceiveFrameCallback private
mReceiveFrameContext
void* mReceiveFrameContext private
mReceiveFrameBuffer
Spinel::SpinelInterface::RxFrameBuffer& mReceiveFrameBuffer private
mSockFd
int mSockFd private
mBaudRate
uint32_t mBaudRate private
Referenced by HdlcInterface::GetBusSpeed().
mHdlcDecoder
Hdlc::Decoder mHdlcDecoder private
mRadioUrl
const Url::Url* mRadioUrl private
mInterfaceMetrics
otRcpInterfaceMetrics mInterfaceMetrics private
Referenced by HdlcInterface::GetRcpInterfaceMetrics().
The documentation for this class was generated from the following files:
hdlc_interface.hpp
hdlc_interface.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale