OpenThread: SecurityPolicy Class Reference
SecurityPolicy Class Reference
Core-security
#include <key_manager.hpp>
Public Member Functions
void GetFlags (uint8_t *aFlags, uint8_t aFlagsLength) const
SecurityPolicy (void)
void SetFlags (const uint8_t *aFlags, uint8_t aFlagsLength)
void SetToDefault (void)
Public Member Functions inherited from Equatable< SecurityPolicy >
bool operator== (const SecurityPolicy &aOther) const
Public Member Functions inherited from Unequatable< SecurityPolicy >
bool operator!= (const SecurityPolicy &aOther) const
Static Public Attributes
static constexpr uint16_t kDefaultKeyRotationTime = 672
Default Key Rotation Time (in unit of hours).
static constexpr uint16_t kMinKeyRotationTime = 1
The minimum Key Rotation Time in hours.
static constexpr uint8_t kVersionThresholdOffsetVersion = 3
Private Member Functions
void SetToDefaultFlags (void)
Static Private Attributes
static constexpr uint8_t kAutonomousEnrollmentMask = 1 << 1
static constexpr uint8_t kBeaconsMask = 1 << 3
static constexpr uint8_t kCommercialCommissioningMask = 1 << 2
static constexpr uint8_t kDefaultFlags = 0xff
static constexpr uint8_t kExternalCommissioningMask = 1 << 4
static constexpr uint8_t kNativeCommissioningMask = 1 << 6
static constexpr uint8_t kNetworkKeyProvisioningMask = 1 << 0
static constexpr uint8_t kNonCcmRoutersMask = 1 << 6
static constexpr uint8_t kObtainNetworkKeyMask = 1 << 7
static constexpr uint8_t kReservedMask = 0x38
static constexpr uint8_t kRoutersMask = 1 << 5
static constexpr uint8_t kTobleLinkMask = 1 << 7
static constexpr uint8_t kVersionThresholdForRoutingMask = 0x07
Additional Inherited Members
Data Fields inherited from otSecurityPolicy
bool mAutonomousEnrollmentEnabled: 1
Autonomous Enrollment is enabled.
bool mCommercialCommissioningEnabled: 1
Commercial Commissioning is enabled.
bool mExternalCommissioningEnabled: 1
External Commissioner authentication is allowed.
bool mNativeCommissioningEnabled: 1
Native Commissioning using PSKc is allowed.
bool mNetworkKeyProvisioningEnabled: 1
Network Key Provisioning is enabled.
bool mNonCcmRoutersEnabled: 1
Non-CCM Routers enabled.
bool mObtainNetworkKeyEnabled: 1
Obtaining the Network Key for out-of-band commissioning is enabled.
uint16_t mRotationTime
The value for thrKeyRotation in units of hours.
bool mRoutersEnabled: 1
Thread 1.0/1.1.x Routers are enabled.
bool mTobleLinkEnabled: 1
ToBLE link is enabled.
uint8_t mVersionThresholdForRouting: 3
Version-threshold for Routing.
Detailed Description
This class represents Security Policy Rotation and Flags.
Constructor & Destructor Documentation
SecurityPolicy()
SecurityPolicy (void) inline
This constructor initializes the object with default Key Rotation Time and Security Policy Flags.
References SecurityPolicy::GetFlags(), SecurityPolicy::SetFlags(), and SecurityPolicy::SetToDefault().
Member Function Documentation
SetToDefault()
void SetToDefault (void)
This method sets the Security Policy to default values.
References SecurityPolicy::kDefaultKeyRotationTime, otSecurityPolicy::mRotationTime, and SecurityPolicy::SetToDefaultFlags().
Referenced by SecurityPolicy::SecurityPolicy().
SetFlags()
void SetFlags (const uint8_t * aFlags, uint8_t aFlagsLength)
This method sets the Security Policy Flags.
Parameters
[in] aFlags The Security Policy Flags.
[in] aFlagsLength The length of the Security Policy Flags, 1 byte for Thread 1.1 devices, and 2 bytes for Thread 1.2 or higher.
References SecurityPolicy::kAutonomousEnrollmentMask, SecurityPolicy::kCommercialCommissioningMask, SecurityPolicy::kExternalCommissioningMask, SecurityPolicy::kNativeCommissioningMask, SecurityPolicy::kNetworkKeyProvisioningMask, SecurityPolicy::kNonCcmRoutersMask, SecurityPolicy::kObtainNetworkKeyMask, SecurityPolicy::kRoutersMask, SecurityPolicy::kTobleLinkMask, SecurityPolicy::kVersionThresholdForRoutingMask, otSecurityPolicy::mAutonomousEnrollmentEnabled, otSecurityPolicy::mCommercialCommissioningEnabled, otSecurityPolicy::mExternalCommissioningEnabled, otSecurityPolicy::mNativeCommissioningEnabled, otSecurityPolicy::mNetworkKeyProvisioningEnabled, otSecurityPolicy::mNonCcmRoutersEnabled, otSecurityPolicy::mObtainNetworkKeyEnabled, otSecurityPolicy::mRoutersEnabled, otSecurityPolicy::mTobleLinkEnabled, otSecurityPolicy::mVersionThresholdForRouting, OT_ASSERT, SecurityPolicy::SetToDefaultFlags(), and VerifyOrExit.
Referenced by SecurityPolicyTlv::GetSecurityPolicy(), and SecurityPolicy::SecurityPolicy().
GetFlags()
void GetFlags (uint8_t * aFlags, uint8_t aFlagsLength) const
This method returns the Security Policy Flags.
Parameters
[out] aFlags A pointer to the Security Policy Flags buffer.
[in] aFlagsLength The length of the Security Policy Flags buffer.
References SecurityPolicy::kAutonomousEnrollmentMask, SecurityPolicy::kCommercialCommissioningMask, SecurityPolicy::kExternalCommissioningMask, SecurityPolicy::kNativeCommissioningMask, SecurityPolicy::kNetworkKeyProvisioningMask, SecurityPolicy::kNonCcmRoutersMask, SecurityPolicy::kObtainNetworkKeyMask, SecurityPolicy::kReservedMask, SecurityPolicy::kRoutersMask, SecurityPolicy::kTobleLinkMask, otSecurityPolicy::mAutonomousEnrollmentEnabled, otSecurityPolicy::mCommercialCommissioningEnabled, otSecurityPolicy::mExternalCommissioningEnabled, otSecurityPolicy::mNativeCommissioningEnabled, otSecurityPolicy::mNetworkKeyProvisioningEnabled, otSecurityPolicy::mNonCcmRoutersEnabled, otSecurityPolicy::mObtainNetworkKeyEnabled, otSecurityPolicy::mRoutersEnabled, otSecurityPolicy::mTobleLinkEnabled, otSecurityPolicy::mVersionThresholdForRouting, OT_ASSERT, and VerifyOrExit.
Referenced by SecurityPolicy::SecurityPolicy(), and SecurityPolicyTlv::SetSecurityPolicy().
SetToDefaultFlags()
void SetToDefaultFlags (void) private
References otSecurityPolicy::mAutonomousEnrollmentEnabled, otSecurityPolicy::mCommercialCommissioningEnabled, otSecurityPolicy::mExternalCommissioningEnabled, otSecurityPolicy::mNativeCommissioningEnabled, otSecurityPolicy::mNetworkKeyProvisioningEnabled, otSecurityPolicy::mNonCcmRoutersEnabled, otSecurityPolicy::mObtainNetworkKeyEnabled, otSecurityPolicy::mRoutersEnabled, otSecurityPolicy::mTobleLinkEnabled, and otSecurityPolicy::mVersionThresholdForRouting.
Referenced by SecurityPolicy::SetFlags(), and SecurityPolicy::SetToDefault().
Field Documentation
kVersionThresholdOffsetVersion
constexpr uint8_t kVersionThresholdOffsetVersion = 3 static
Offset between the Thread Version and the Version-threshold valid for Routing.
kMinKeyRotationTime
constexpr uint16_t kMinKeyRotationTime = 1 static
The minimum Key Rotation Time in hours.
Referenced by KeyManager::SetSecurityPolicy().
kDefaultKeyRotationTime
constexpr uint16_t kDefaultKeyRotationTime = 672 static
Default Key Rotation Time (in unit of hours).
Referenced by SecurityPolicy::SetToDefault().
kDefaultFlags
constexpr uint8_t kDefaultFlags = 0xff static private
kObtainNetworkKeyMask
constexpr uint8_t kObtainNetworkKeyMask = 1 << 7 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kNativeCommissioningMask
constexpr uint8_t kNativeCommissioningMask = 1 << 6 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kRoutersMask
constexpr uint8_t kRoutersMask = 1 << 5 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kExternalCommissioningMask
constexpr uint8_t kExternalCommissioningMask = 1 << 4 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kBeaconsMask
constexpr uint8_t kBeaconsMask = 1 << 3 static private
kCommercialCommissioningMask
constexpr uint8_t kCommercialCommissioningMask = 1 << 2 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kAutonomousEnrollmentMask
constexpr uint8_t kAutonomousEnrollmentMask = 1 << 1 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kNetworkKeyProvisioningMask
constexpr uint8_t kNetworkKeyProvisioningMask = 1 << 0 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kTobleLinkMask
constexpr uint8_t kTobleLinkMask = 1 << 7 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kNonCcmRoutersMask
constexpr uint8_t kNonCcmRoutersMask = 1 << 6 static private
Referenced by SecurityPolicy::GetFlags(), and SecurityPolicy::SetFlags().
kReservedMask
constexpr uint8_t kReservedMask = 0x38 static private
Referenced by SecurityPolicy::GetFlags().
kVersionThresholdForRoutingMask
constexpr uint8_t kVersionThresholdForRoutingMask = 0x07 static private
Referenced by SecurityPolicy::SetFlags().
The documentation for this class was generated from the following files:
key_manager.hpp
key_manager.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale