OpenThread: Heap Class Reference
Heap Class Reference
#include <heap.hpp>
Public Member Functions
void * CAlloc (size_t aCount, size_t aSize)
void Free (void *aPointer)
size_t GetCapacity (void) const
size_t GetFreeSize (void) const
Heap (void)
bool IsClean (void) const
Private Member Functions
Block & BlockAt (uint16_t aOffset)
void BlockInsert (Block &aPrev, Block &aBlock)
Block & BlockNext (const Block &aBlock)
Block & BlockOf (void *aPointer)
uint16_t BlockOffset (const Block &aBlock)
Block & BlockPrev (const Block &aBlock)
Block & BlockRight (const Block &aBlock)
Block & BlockSuper (void)
bool IsLeftFree (const Block &aBlock)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
union {
uint16_t m16 [kMemorySize/sizeof(uint16_t)]
uint8_t m8 [kMemorySize]
uint16_t mFreeSize
long mLong [kMemorySize/sizeof(long)]
} mMemory
Static Private Attributes
static constexpr uint16_t kAlignSize = sizeof(void *)
static constexpr uint16_t kBlockRemainderSize = kAlignSize - sizeof(uint16_t) * 2
static constexpr uint16_t kFirstBlockOffset = kAlignSize * 2 - sizeof(uint16_t)
static constexpr uint16_t kFirstBlockSize = kMemorySize - kAlignSize * 3 + kBlockRemainderSize
static constexpr uint16_t kGuardBlockOffset = kMemorySize - sizeof(uint16_t)
static constexpr uint16_t kMemorySize = OPENTHREAD_CONFIG_HEAP_INTERNAL_SIZE_NO_DTLS
static constexpr uint16_t kSuperBlockOffset = kAlignSize - sizeof(uint16_t)
static constexpr uint16_t kSuperBlockSize = kAlignSize - sizeof(Block)
Detailed Description
This class defines functionality to manipulate heap.
This implementation is currently for mbedTLS.
The memory is divided into blocks. The whole picture is as follows:
+--------------------------------------------------------------------------+
|    unused      |    super   | block 1 | block 2 | ... | block n | guard  |
+----------------+------------+---------+---------+-----+---------+--------+
| kAlignSize - 2 | kAlignSize | 4 + s1  | 4 + s2  | ... | 4 + s4  |   2    |
+--------------------------------------------------------------------------+
Constructor & Destructor Documentation
Heap()
Heap (void)
This constructor initializes a memory heap.
References Heap::BlockAt(), Heap::BlockOffset(), Heap::BlockRight(), Heap::kFirstBlockSize, Block::kGuardBlockSize, Heap::kSuperBlockOffset, Heap::kSuperBlockSize, Heap::mMemory, Block::SetNext(), and Block::SetSize().
Member Function Documentation
CAlloc()
void * CAlloc (size_t aCount, size_t aSize)
This method allocates at least aCount * bytes memory and initialize to zero.
Parameters
[in] aCount Number of allocate units.
[in] aSize Unit size in bytes.
Returns
A pointer to the allocated memory.
Return values
nullptr Indicates not enough memory.
References Heap::BlockInsert(), Heap::BlockNext(), Heap::BlockRight(), Heap::BlockSuper(), Block::GetNext(), Block::GetPointer(), Block::GetSize(), Block::IsFree(), Heap::kAlignSize, Heap::kBlockRemainderSize, Heap::mMemory, Block::SetNext(), Block::SetSize(), and VerifyOrExit.
Free()
void Free (void * aPointer)
This method free memory pointed by aPointer.
Parameters
[in] aPointer A pointer to the memory to free.
References Heap::BlockInsert(), Heap::BlockNext(), Heap::BlockOf(), Heap::BlockOffset(), Heap::BlockPrev(), Heap::BlockRight(), Heap::BlockSuper(), Block::GetLeftNext(), Block::GetNext(), Block::GetSize(), Block::IsFree(), Heap::IsLeftFree(), Heap::mMemory, Block::SetNext(), and Block::SetSize().
IsClean()
bool IsClean (void) const inline
This method returns whether the heap is clean.
References ot::AsNonConst(), Block::GetNext(), and Block::GetSize().
GetCapacity()
size_t GetCapacity (void) const inline
This method returns the capacity of this heap.
GetFreeSize()
size_t GetFreeSize (void) const inline
This method returns free space of this heap.
References OPENTHREAD_CONFIG_HEAP_INTERNAL_SIZE.
BlockAt()
Block& BlockAt (uint16_t aOffset) inline private
This method returns the block at offset aOffset.
Parameters
[in] aOffset Offset in bytes.
Returns
A reference to the block.
Referenced by Heap::Heap().
BlockOf()
Block& BlockOf (void * aPointer) inline private
This method returns the block of aPointer.
Parameters
[in] aPointer The pointer returned by CAlloc().
Returns
A reference to the block.
Referenced by Heap::Free().
BlockSuper()
Block& BlockSuper (void) inline private
This method returns the super block.
Returns
Reference to the super block.
Referenced by Heap::BlockPrev(), Heap::CAlloc(), and Heap::Free().
BlockNext()
Block& BlockNext (const Block & aBlock) inline private
This method returns the free block after aBlock in the free block list.
Parameters
[in] aBlock A reference to the block.
Returns
Reference to the free block after this block.
References Block::GetNext().
Referenced by Heap::BlockInsert(), Heap::BlockPrev(), Heap::CAlloc(), and Heap::Free().
BlockRight()
Block& BlockRight (const Block & aBlock) inline private
This method returns the block on the right side of aBlock.
Parameters
[in] aBlock A reference to the block.
Returns
Reference to the block on the right side.
References Block::GetSize().
Referenced by Heap::CAlloc(), Heap::Free(), and Heap::Heap().
BlockPrev()
Block & BlockPrev (const Block & aBlock) private
This method returns the free block before aBlock in the free block list.
Returns
Reference to the free block before this block.
References Heap::BlockNext(), Heap::BlockOffset(), Heap::BlockSuper(), and Block::GetNext().
Referenced by Heap::Free().
IsLeftFree()
bool IsLeftFree (const Block & aBlock) inline private
This method returns whether the block on the left side of aBlock is free.
Parameters
[in] aBlock A reference to the block.
References Block::IsLeftFree().
Referenced by Heap::Free().
BlockOffset()
uint16_t BlockOffset (const Block & aBlock) inline private
This method returns the offset of aBlock.
Parameters
[in] aBlock A reference to the block.
Returns
Offset in bytes of aBlock.
Referenced by Heap::BlockInsert(), Heap::BlockPrev(), Heap::Free(), and Heap::Heap().
BlockInsert()
void BlockInsert (Block & aPrev, Block & aBlock) private
This method inserts aBlock into the free block list.
The free block list is single linked and is sorted by size from minimal to maximum.
Parameters
[in] aPrev A reference to the block after which to place aBlock.
[in] aBlock A reference to the block.
References Heap::BlockNext(), Heap::BlockOffset(), Block::GetNext(), Block::GetSize(), and Block::SetNext().
Referenced by Heap::CAlloc(), and Heap::Free().
Field Documentation
kMemorySize
constexpr uint16_t kMemorySize = OPENTHREAD_CONFIG_HEAP_INTERNAL_SIZE_NO_DTLS static private
kAlignSize
constexpr uint16_t kAlignSize = sizeof(void *) static private
Referenced by Heap::CAlloc().
kBlockRemainderSize
constexpr uint16_t kBlockRemainderSize = kAlignSize - sizeof(uint16_t) * 2 static private
Referenced by Heap::CAlloc().
kSuperBlockSize
constexpr uint16_t kSuperBlockSize = kAlignSize - sizeof(Block) static private
Referenced by Heap::Heap().
kFirstBlockSize
constexpr uint16_t kFirstBlockSize = kMemorySize - kAlignSize * 3 + kBlockRemainderSize static private
Referenced by Heap::Heap().
kSuperBlockOffset
constexpr uint16_t kSuperBlockOffset = kAlignSize - sizeof(uint16_t) static private
Referenced by Heap::Heap().
kFirstBlockOffset
constexpr uint16_t kFirstBlockOffset = kAlignSize * 2 - sizeof(uint16_t) static private
kGuardBlockOffset
constexpr uint16_t kGuardBlockOffset = kMemorySize - sizeof(uint16_t) static private
mFreeSize
uint16_t mFreeSize
mLong
long mLong[kMemorySize/sizeof(long)]
m8
uint8_t m8[kMemorySize]
m16
uint16_t m16[kMemorySize/sizeof(uint16_t)]
mMemory
union { ... } mMemory
Referenced by Heap::CAlloc(), Heap::Free(), and Heap::Heap().
The documentation for this class was generated from the following files:
utils/heap.hpp
utils/heap.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale