OpenThread: Udp Class Reference
Udp Class Reference
Core-udp
#include <udp6.hpp>
Data Structures
class Header
class Receiver
class Socket
class SocketHandle
Public Member Functions
Error AddReceiver (Receiver &aReceiver)
Error Bind (SocketHandle &aSocket, const SockAddr &aSockAddr, otNetifIdentifier aNetifIdentifier)
Error Close (SocketHandle &aSocket)
Error Connect (SocketHandle &aSocket, const SockAddr &aSockAddr)
uint16_t GetEphemeralPort (void)
SocketHandle * GetUdpSockets (void)
Error HandleMessage (Message &aMessage, MessageInfo &aMessageInfo)
void HandlePayload (Message &aMessage, MessageInfo &aMessageInfo)
bool IsOpen (const SocketHandle &aSocket) const
bool IsPortInUse (uint16_t aPort) const
Message * NewMessage (uint16_t aReserved, const Message::Settings &aSettings=Message::Settings::GetDefault())
Error Open (SocketHandle &aSocket, otUdpReceive aHandler, void *aContext)
Error RemoveReceiver (Receiver &aReceiver)
Error SendDatagram (Message &aMessage, MessageInfo &aMessageInfo, uint8_t aIpProto)
Error SendTo (SocketHandle &aSocket, Message &aMessage, const MessageInfo &aMessageInfo)
bool ShouldUsePlatformUdp (uint16_t aPort) const
Udp (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Data Fields
ot::Ip6::Udp::Header OT_TOOL_PACKED_END
Private Member Functions
void AddSocket (SocketHandle &aSocket)
void RemoveSocket (SocketHandle &aSocket)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static bool IsPortReserved (uint16_t aPort)
Private Attributes
uint16_t mEphemeralPort
LinkedList< Receiver > mReceivers
LinkedList< SocketHandle > mSockets
Static Private Attributes
static constexpr uint16_t kDynamicPortMax = 65535
static constexpr uint16_t kDynamicPortMin = 49152
static constexpr uint16_t kSrpServerPortMax = OPENTHREAD_CONFIG_SRP_SERVER_UDP_PORT_MAX
static constexpr uint16_t kSrpServerPortMin = OPENTHREAD_CONFIG_SRP_SERVER_UDP_PORT_MIN
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements core UDP message handling.
Constructor & Destructor Documentation
Udp()
Udp (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to OpenThread instance.
Member Function Documentation
AddReceiver()
Error AddReceiver (Receiver & aReceiver)
This method adds a UDP receiver.
Parameters
[in] aReceiver A reference to the UDP receiver.
Return values
kErrorNone Successfully added the UDP receiver.
kErrorAlready The UDP receiver was already added.
References Udp::mReceivers.
RemoveReceiver()
Error RemoveReceiver (Receiver & aReceiver)
This method removes a UDP receiver.
Parameters
[in] aReceiver A reference to the UDP receiver.
Return values
kErrorNone Successfully removed the UDP receiver.
kErrorNotFound The UDP receiver was not added.
References Udp::mReceivers, LinkedListEntry< Type >::SetNext(), and SuccessOrExit.
Open()
Error Open (SocketHandle & aSocket, otUdpReceive aHandler, void * aContext)
This method opens a UDP socket.
Parameters
[in] aSocket A reference to the socket.
[in] aHandler A pointer to a function that is called when receiving UDP messages.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Successfully opened the socket.
kErrorFailed Failed to open the socket.
References Udp::AddSocket(), Clearable< Type >::Clear(), Udp::SocketHandle::GetPeerName(), Udp::SocketHandle::GetSockName(), Udp::IsOpen(), ot::kErrorNone, otUdpSocket::mContext, otUdpSocket::mHandler, OT_ASSERT, otPlatUdpSocket(), and SuccessOrExit.
IsOpen()
bool IsOpen (const SocketHandle & aSocket) const inline
This method returns if a UDP socket is open.
Parameters
[in] aSocket A reference to the socket.
Returns
If the UDP socket is open.
References Udp::Bind(), Udp::Close(), Udp::Connect(), Message::Settings::GetDefault(), Udp::GetEphemeralPort(), Udp::HandleMessage(), Udp::HandlePayload(), Udp::mSockets, Udp::NewMessage(), Udp::SendDatagram(), and Udp::SendTo().
Referenced by Udp::Close(), and Udp::Open().
Bind()
Error Bind (SocketHandle & aSocket, const SockAddr & aSockAddr, otNetifIdentifier aNetifIdentifier)
This method binds a UDP socket.
Parameters
[in] aSocket A reference to the socket.
[in] aSockAddr A reference to the socket address.
[in] aNetifIdentifier The network interface identifier.
Return values
kErrorNone Successfully bound the socket.
kErrorInvalidArgs Unable to bind to Thread network interface with the given address.
kErrorFailed Failed to bind UDP Socket.
References ExitNow, SockAddr::GetAddress(), Udp::GetEphemeralPort(), LinkedListEntry< Type >::GetNext(), Udp::SocketHandle::IsBound(), Address::IsUnspecified(), ot::kErrorInvalidArgs, ot::kErrorNone, otSockAddr::mPort, Udp::mSockets, otUdpSocket::mSockName, OT_NETIF_BACKBONE, OT_UNUSED_VARIABLE, otPlatUdpBind(), otPlatUdpBindToNetif(), Udp::RemoveSocket(), Udp::ShouldUsePlatformUdp(), SuccessOrExit, and VerifyOrExit.
Referenced by Udp::Connect(), Udp::IsOpen(), and Udp::SendTo().
Connect()
Error Connect (SocketHandle & aSocket, const SockAddr & aSockAddr)
This method connects a UDP socket.
Parameters
[in] aSocket A reference to the socket.
[in] aSockAddr A reference to the socket address.
Return values
kErrorNone Successfully connected the socket.
kErrorFailed Failed to connect UDP Socket.
References Udp::Bind(), Udp::SocketHandle::GetSockName(), Udp::SocketHandle::IsBound(), ot::kErrorNone, otUdpSocket::mPeerName, OT_NETIF_THREAD, otPlatUdpConnect(), Udp::ShouldUsePlatformUdp(), and SuccessOrExit.
Referenced by Udp::Socket::Bind(), and Udp::IsOpen().
Close()
Error Close (SocketHandle & aSocket)
This method closes the UDP socket.
Parameters
[in] aSocket A reference to the socket.
Return values
kErrorNone Successfully closed the UDP socket.
kErrorFailed Failed to close UDP Socket.
References Clearable< Type >::Clear(), Udp::SocketHandle::GetPeerName(), Udp::SocketHandle::GetSockName(), Udp::IsOpen(), ot::kErrorNone, otPlatUdpClose(), Udp::RemoveSocket(), SuccessOrExit, and VerifyOrExit.
Referenced by Udp::Socket::Connect(), and Udp::IsOpen().
SendTo()
Error SendTo (SocketHandle & aSocket, Message & aMessage, const MessageInfo & aMessageInfo)
This method sends a UDP message using a socket.
Parameters
[in] aSocket A reference to the socket.
[in] aMessage The message to send.
[in] aMessageInfo The message info associated with aMessage.
Return values
kErrorNone Successfully sent the UDP message.
kErrorInvalidArgs If no peer is specified in aMessageInfo or by Connect().
kErrorNoBufs Insufficient available buffer to add the UDP and IPv6 headers.
References Udp::Bind(), SockAddr::GetAddress(), MessageInfo::GetPeerAddr(), Udp::SocketHandle::GetPeerName(), MessageInfo::GetSockAddr(), Udp::SocketHandle::GetSockName(), MessageInfo::GetSockPort(), Udp::SocketHandle::IsBound(), Address::IsUnspecified(), ot::kErrorInvalidArgs, ot::kErrorNone, ot::Ip6::kProtoUdp, otMessageInfo::mPeerPort, otSockAddr::mPort, OT_NETIF_THREAD, otPlatUdpSend(), Udp::SendDatagram(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), MessageInfo::SetSockPort(), Udp::ShouldUsePlatformUdp(), SuccessOrExit, and VerifyOrExit.
Referenced by Udp::Socket::Connect(), and Udp::IsOpen().
GetEphemeralPort()
uint16_t GetEphemeralPort (void)
This method returns a new ephemeral port.
Returns
A new ephemeral port.
References Udp::IsPortReserved(), Udp::kDynamicPortMax, Udp::kDynamicPortMin, and Udp::mEphemeralPort.
Referenced by Udp::Bind(), and Udp::IsOpen().
NewMessage()
Message * NewMessage (uint16_t aReserved, const Message::Settings & aSettings = Message::Settings::GetDefault())
This method returns a new UDP message with sufficient header space reserved.
Parameters
[in] aReserved The number of header bytes to reserve after the UDP header.
[in] aSettings The message settings.
Returns
A pointer to the message or nullptr if no buffers are available.
Referenced by Udp::IsOpen().
SendDatagram()
Error SendDatagram (Message & aMessage, MessageInfo & aMessageInfo, uint8_t aIpProto)
This method sends an IPv6 datagram.
Parameters
[in] aMessage A reference to the message.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aIpProto The Internet Protocol value.
Return values
kErrorNone Successfully enqueued the message into an output interface.
kErrorNoBufs Insufficient available buffer to add the IPv6 headers.
References Message::GetLength(), MessageInfo::GetPeerAddr(), MessageInfo::IsHostInterface(), ot::kErrorNone, ot::kErrorNoRoute, otMessageInfo::mPeerPort, otMessageInfo::mSockPort, Message::Prepend(), Udp::Header::SetChecksum(), Udp::Header::SetDestinationPort(), Udp::Header::SetLength(), Message::SetOffset(), Udp::Header::SetSourcePort(), SuccessOrExit, and VerifyOrExit.
Referenced by Udp::IsOpen(), and Udp::SendTo().
HandleMessage()
Error HandleMessage (Message & aMessage, MessageInfo & aMessageInfo)
This method handles a received UDP message.
Parameters
[in] aMessage A reference to the UDP message to process.
[in] aMessageInfo A reference to the message info associated with aMessage.
Return values
kErrorNone Successfully processed the UDP message.
kErrorDrop Could not fully process the UDP message.
References Udp::Header::GetDestinationPort(), Message::GetOffset(), Udp::Header::GetSourcePort(), Udp::HandlePayload(), Udp::IsPortInUse(), ot::kErrorNone, ot::Ip6::kProtoUdp, Message::MoveOffset(), otMessageInfo::mPeerPort, Udp::mReceivers, otMessageInfo::mSockPort, Message::Read(), Udp::ShouldUsePlatformUdp(), SuccessOrExit, Checksum::VerifyMessageChecksum(), and VerifyOrExit.
Referenced by Ip6::HandlePayload(), and Udp::IsOpen().
HandlePayload()
void HandlePayload (Message & aMessage, MessageInfo & aMessageInfo)
This method handles a received UDP message with offset set to the payload.
Parameters
[in] aMessage A reference to the UDP message to process.
[in] aMessageInfo A reference to the message info associated with aMessage.
References Message::GetOffset(), Udp::SocketHandle::HandleUdpReceive(), MessageInfo::IsHostInterface(), Udp::mSockets, OT_ASSERT, Message::RemoveHeader(), and VerifyOrExit.
Referenced by Udp::HandleMessage(), and Udp::IsOpen().
GetUdpSockets()
SocketHandle* GetUdpSockets (void) inline
This method returns the head of UDP Sockets list.
Returns
A pointer to the head of UDP Socket linked list.
References Udp::IsPortInUse(), Udp::mSockets, and Udp::ShouldUsePlatformUdp().
IsPortInUse()
bool IsPortInUse (uint16_t aPort) const
This method returns whether a udp port is being used by OpenThread or any of it's optional features, e.g. CoAP API.
Parameters
[in] aPort The udp port
Return values
True when port is used by the OpenThread.
False when the port is not used by OpenThread.
References Udp::mSockets.
Referenced by Udp::GetUdpSockets(), and Udp::HandleMessage().
ShouldUsePlatformUdp()
bool ShouldUsePlatformUdp (uint16_t aPort) const
This method returns whether a udp port belongs to the platform or the stack.
Parameters
[in] aPort The udp port
Return values
True when the port belongs to the platform.
False when the port belongs to the stack.
References ot::Tmf::kUdpPort, ot::Mle::kUdpPort, otSockAddr::mPort, otUdpSocket::mSockName, OPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE, OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE, OPENTHREAD_CONFIG_DNSSD_SERVER_BIND_UNSPECIFIED_NETIF, and OPENTHREAD_CONFIG_DNSSD_SERVER_ENABLE.
Referenced by Udp::Bind(), Udp::Connect(), Udp::GetUdpSockets(), Udp::HandleMessage(), and Udp::SendTo().
IsPortReserved()
bool IsPortReserved (uint16_t aPort) static private
References Udp::kSrpServerPortMax, Udp::kSrpServerPortMin, and ot::Tmf::kUdpPort.
Referenced by Udp::GetEphemeralPort().
AddSocket()
void AddSocket (SocketHandle & aSocket) private
References Udp::mSockets, and SuccessOrExit.
Referenced by Udp::Open().
RemoveSocket()
void RemoveSocket (SocketHandle & aSocket) private
References Udp::mSockets, LinkedListEntry< Type >::SetNext(), and SuccessOrExit.
Referenced by Udp::Bind(), and Udp::Close().
Field Documentation
OT_TOOL_PACKED_END
ot::Ip6::Udp::Header OT_TOOL_PACKED_END
kDynamicPortMin
constexpr uint16_t kDynamicPortMin = 49152 static private
Referenced by Udp::GetEphemeralPort().
kDynamicPortMax
constexpr uint16_t kDynamicPortMax = 65535 static private
Referenced by Udp::GetEphemeralPort().
kSrpServerPortMin
constexpr uint16_t kSrpServerPortMin = OPENTHREAD_CONFIG_SRP_SERVER_UDP_PORT_MIN static private
Referenced by Udp::IsPortReserved().
kSrpServerPortMax
constexpr uint16_t kSrpServerPortMax = OPENTHREAD_CONFIG_SRP_SERVER_UDP_PORT_MAX static private
Referenced by Udp::IsPortReserved().
mEphemeralPort
uint16_t mEphemeralPort private
Referenced by Udp::GetEphemeralPort().
mReceivers
LinkedList<Receiver> mReceivers private
Referenced by Udp::AddReceiver(), Udp::HandleMessage(), and Udp::RemoveReceiver().
mSockets
LinkedList<SocketHandle> mSockets private
Referenced by Udp::AddSocket(), Udp::Bind(), Udp::GetUdpSockets(), Udp::HandlePayload(), Udp::IsOpen(), Udp::IsPortInUse(), and Udp::RemoveSocket().
The documentation for this class was generated from the following files:
udp6.hpp
udp6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale