OpenThread: ExtendedPanIdManager Class Reference
ExtendedPanIdManager Class Reference
#include <extended_panid.hpp>
Public Member Functions
ExtendedPanIdManager (Instance &aInstance)
const ExtendedPanId & GetExtPanId (void) const
void SetExtPanId (const ExtendedPanId &aExtendedPanId)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Attributes
ExtendedPanId mExtendedPanId
Static Private Attributes
static const otExtendedPanId sExtendedPanidInit
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Constructor & Destructor Documentation
ExtendedPanIdManager()
ExtendedPanIdManager (Instance & aInstance) explicit
Constructor.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ot::AsCoreType(), Clearable< Type >::Clear(), ExtendedPanIdManager::mExtendedPanId, ExtendedPanIdManager::SetExtPanId(), and ExtendedPanIdManager::sExtendedPanidInit.
Member Function Documentation
GetExtPanId()
const ExtendedPanId& GetExtPanId (void) const inline
This method returns the Extended PAN Identifier.
Returns
The Extended PAN Identifier.
SetExtPanId()
void SetExtPanId (const ExtendedPanId & aExtendedPanId)
This method sets the Extended PAN Identifier.
Parameters
[in] aExtendedPanId The Extended PAN Identifier.
References IgnoreError(), ot::kEventThreadExtPanIdChanged, and ExtendedPanIdManager::mExtendedPanId.
Referenced by ExtendedPanIdManager::ExtendedPanIdManager().
Field Documentation
sExtendedPanidInit
const otExtendedPanId sExtendedPanidInit static private
Initial value:
= {
    {0xde, 0xad, 0x00, 0xbe, 0xef, 0x00, 0xca, 0xfe},
}
Referenced by ExtendedPanIdManager::ExtendedPanIdManager().
mExtendedPanId
ExtendedPanId mExtendedPanId private
Referenced by ExtendedPanIdManager::ExtendedPanIdManager(), and ExtendedPanIdManager::SetExtPanId().
The documentation for this class was generated from the following files:
extended_panid.hpp
extended_panid.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale