OpenThread: Dataset Class Reference
Dataset Class Reference
#include <cli_dataset.hpp>
Public Types
typedef Utils::CmdLineParser::Arg Arg
Public Member Functions
Dataset (Output &aOutput)
otError Process (Arg aArgs[])
Private Types
using Command = CommandEntry< Dataset >
Private Types inherited from OutputBase
typedef Utils::CmdLineParser::Arg Arg
An argument.
Private Member Functions
void OutputSecurityPolicy (const otSecurityPolicy &aSecurityPolicy)
otError ParseSecurityPolicy (otSecurityPolicy &aSecurityPolicy, Arg *&aArgs)
otError Print (otOperationalDataset &aDataset)
template<CommandId kCommandId>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
Private Member Functions inherited from OutputWrapper
otInstance * GetInstancePtr (void)
template<uint8_t kBytesLength>
void OutputBytes (const uint8_t(&aBytes)[kBytesLength])
void OutputBytes (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytesLine (const uint8_t(&aBytes)[kBytesLength])
void OutputBytesLine (const uint8_t *aBytes, uint16_t aLength)
template<typename Cli , uint16_t kLength>
void OutputCommandTable (const CommandEntry< Cli >(&aCommandTable)[kLength])
void OutputEnabledDisabledStatus (bool aEnabled)
void OutputExtAddress (const otExtAddress &aExtAddress)
void OutputExtAddressLine (const otExtAddress &aExtAddress)
template<typename... Args>
void OutputFormat (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputFormat (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
void OutputSpaces (uint8_t aCount)
template<uint8_t kTableNumColumns>
void OutputTableHeader (const char *const (&aTitles)[kTableNumColumns], const uint8_t(&aWidths)[kTableNumColumns])
template<uint8_t kTableNumColumns>
void OutputTableSeparator (const uint8_t(&aWidths)[kTableNumColumns])
OutputWrapper (Output &aOutput)
Private Member Functions inherited from OutputBase
OutputBase (void)=default
Static Private Attributes
static otOperationalDataset sDataset
Static Private Attributes inherited from OutputBase
static const char kUnknownString [] = "unknown"
Additional Inherited Members
Static Private Member Functions inherited from OutputBase
template<typename EnumType , uint16_t kLength>
static const char * Stringify (EnumType aEnum, const char *const (&aTable)[kLength], const char *aNotFound=kUnknownString)
Detailed Description
This class implements the Dataset CLI interpreter.
Member Typedef Documentation
Arg
typedef Utils::CmdLineParser::Arg Arg
Command
using Command = CommandEntry<Dataset> private
Constructor & Destructor Documentation
Dataset()
Dataset (Output & aOutput) inline explicit
References Dataset::Process().
Member Function Documentation
Process() [1/22]
otError Process (Arg aArgs[])
This method interprets a list of CLI arguments.
Parameters
[in] aArgs An array of command line arguments.
References CmdEntry, ExitNow, BinarySearch::Find(), BinarySearch::IsSorted(), kCommands, OutputBase::CommandEntry< Cli >::mHandler, OT_ERROR_INVALID_COMMAND, OT_ERROR_NONE, OutputWrapper::OutputCommandTable(), Dataset::Print(), Dataset::sDataset, and VerifyOrExit.
Referenced by Dataset::Dataset(), and Dataset::Process().
Process() [2/22]
otError Process (Arg aArgs[]) private
Print()
otError Print (otOperationalDataset & aDataset) private
References otNetworkKey::m8, otNetworkName::m8, otExtendedPanId::m8, otPskc::m8, otOperationalDataset::mActiveTimestamp, otOperationalDataset::mChannel, otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDataset::mDelay, otOperationalDataset::mExtendedPanId, otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelMaskPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsDelayPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkKeyPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPendingTimestampPresent, otOperationalDatasetComponents::mIsPskcPresent, otOperationalDatasetComponents::mIsSecurityPolicyPresent, otOperationalDataset::mMeshLocalPrefix, otOperationalDataset::mNetworkKey, otOperationalDataset::mNetworkName, otOperationalDataset::mPanId, otOperationalDataset::mPendingTimestamp, otOperationalDataset::mPskc, otTimestamp::mSeconds, otOperationalDataset::mSecurityPolicy, OT_ERROR_NONE, OutputWrapper::OutputBytesLine(), OutputWrapper::OutputFormat(), OutputWrapper::OutputLine(), and Dataset::OutputSecurityPolicy().
Referenced by Dataset::Process().
OutputSecurityPolicy()
void OutputSecurityPolicy (const otSecurityPolicy & aSecurityPolicy) private
References otSecurityPolicy::mAutonomousEnrollmentEnabled, otSecurityPolicy::mCommercialCommissioningEnabled, otSecurityPolicy::mExternalCommissioningEnabled, otSecurityPolicy::mNativeCommissioningEnabled, otSecurityPolicy::mNetworkKeyProvisioningEnabled, otSecurityPolicy::mNonCcmRoutersEnabled, otSecurityPolicy::mObtainNetworkKeyEnabled, otSecurityPolicy::mRotationTime, otSecurityPolicy::mRoutersEnabled, OutputWrapper::OutputFormat(), and OutputWrapper::OutputLine().
Referenced by Dataset::Print(), and Dataset::Process().
ParseSecurityPolicy()
otError ParseSecurityPolicy (otSecurityPolicy & aSecurityPolicy, Arg *& aArgs) private
References ExitNow, otSecurityPolicy::mAutonomousEnrollmentEnabled, otSecurityPolicy::mCommercialCommissioningEnabled, otSecurityPolicy::mExternalCommissioningEnabled, otSecurityPolicy::mNativeCommissioningEnabled, otSecurityPolicy::mNetworkKeyProvisioningEnabled, otSecurityPolicy::mNonCcmRoutersEnabled, otSecurityPolicy::mObtainNetworkKeyEnabled, otSecurityPolicy::mRotationTime, otSecurityPolicy::mRoutersEnabled, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Arg::ParseAsUint16(), SuccessOrExit, and VerifyOrExit.
Referenced by Dataset::Process().
Process() [3/22]
otError Process (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), otOperationalDatasetTlvs::mLength, otOperationalDatasetTlvs::mTlvs, OT_ERROR_INVALID_ARGS, otDatasetCreateNewNetwork(), otDatasetGetActive(), otDatasetGetPending(), otDatasetParseTlvs(), ot::Utils::CmdLineParser::ParseAsHexString(), Dataset::sDataset, and SuccessOrExit.
Process() [4/22]
otError Process (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), otOperationalDatasetTlvs::mLength, otOperationalDatasetTlvs::mTlvs, OT_ERROR_INVALID_ARGS, otDatasetGetActive(), otDatasetGetActiveTlvs(), OutputWrapper::OutputBytesLine(), Dataset::Print(), and SuccessOrExit.
Process() [5/22]
otError Process (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), otOperationalDatasetTlvs::mLength, otOperationalDatasetTlvs::mTlvs, OT_ERROR_INVALID_ARGS, otDatasetGetPending(), otDatasetGetPendingTlvs(), OutputWrapper::OutputBytesLine(), Dataset::Print(), and SuccessOrExit.
Process() [6/22]
otError Process (Arg aArgs[]) private
References otOperationalDataset::mActiveTimestamp, otTimestamp::mAuthoritative, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsActiveTimestampPresent, otTimestamp::mSeconds, otTimestamp::mTicks, OT_ERROR_NONE, OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsUint64(), Dataset::sDataset, and SuccessOrExit.
Process() [7/22]
otError Process (Arg aArgs[]) private
References otOperationalDataset::mChannel, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsChannelPresent, OT_ERROR_NONE, OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsUint16(), Dataset::sDataset, and SuccessOrExit.
Process() [8/22]
otError Process (Arg aArgs[]) private
References otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsChannelMaskPresent, OT_ERROR_NONE, OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsUint32(), Dataset::sDataset, and SuccessOrExit.
Process() [9/22]
otError Process (Arg aArgs[]) private
References OT_ERROR_NONE, OT_UNUSED_VARIABLE, and Dataset::sDataset.
Process() [10/22]
otError Process (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), OT_ERROR_INVALID_ARGS, otDatasetSetActive(), otDatasetSetPending(), and Dataset::sDataset.
Process() [11/22]
otError Process (Arg aArgs[]) private
References otOperationalDataset::mComponents, otOperationalDataset::mDelay, otOperationalDatasetComponents::mIsDelayPresent, OT_ERROR_NONE, OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsUint32(), Dataset::sDataset, and SuccessOrExit.
Process() [12/22]
otError Process (Arg aArgs[]) private
References otExtendedPanId::m8, otOperationalDataset::mComponents, otOperationalDataset::mExtendedPanId, otOperationalDatasetComponents::mIsExtendedPanIdPresent, OT_ERROR_NONE, OutputWrapper::OutputBytesLine(), ot::Utils::CmdLineParser::ParseAsHexString(), Dataset::sDataset, and SuccessOrExit.
Process() [13/22]
otError Process (Arg aArgs[]) private
References otIp6NetworkPrefix::m8, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otOperationalDataset::mComponents, otIp6Address::mFields, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDataset::mMeshLocalPrefix, OT_ERROR_NONE, OutputWrapper::OutputFormat(), Dataset::sDataset, and SuccessOrExit.
Process() [14/22]
otError Process (Arg aArgs[]) private
References otNetworkKey::m8, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsNetworkKeyPresent, otOperationalDataset::mNetworkKey, OT_ERROR_NONE, OutputWrapper::OutputBytesLine(), ot::Utils::CmdLineParser::ParseAsHexString(), Dataset::sDataset, and SuccessOrExit.
Process() [15/22]
otError Process (Arg aArgs[]) private
References otNetworkName::m8, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDataset::mNetworkName, OT_ERROR_NONE, otNetworkNameFromString(), OutputWrapper::OutputLine(), Dataset::sDataset, and SuccessOrExit.
Process() [16/22]
otError Process (Arg aArgs[]) private
References otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDataset::mPanId, OT_ERROR_NONE, OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsUint16(), Dataset::sDataset, and SuccessOrExit.
Process() [17/22]
otError Process (Arg aArgs[]) private
References otTimestamp::mAuthoritative, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsPendingTimestampPresent, otOperationalDataset::mPendingTimestamp, otTimestamp::mSeconds, otTimestamp::mTicks, OT_ERROR_NONE, OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsUint64(), Dataset::sDataset, and SuccessOrExit.
Process() [18/22]
otError Process (Arg aArgs[]) private
References ExitNow, OutputWrapper::GetInstancePtr(), Arg::IsEmpty(), otNetworkKey::m8, otIp6NetworkPrefix::m8, otExtendedPanId::m8, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otOperationalDataset::mActiveTimestamp, otTimestamp::mAuthoritative, otOperationalDataset::mChannel, otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDataset::mDelay, otOperationalDataset::mExtendedPanId, otIp6Address::mFields, otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelMaskPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsDelayPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkKeyPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPendingTimestampPresent, otOperationalDatasetComponents::mIsSecurityPolicyPresent, otOperationalDataset::mMeshLocalPrefix, otOperationalDataset::mNetworkKey, otOperationalDataset::mNetworkName, otOperationalDataset::mPanId, otOperationalDataset::mPendingTimestamp, otTimestamp::mSeconds, otOperationalDataset::mSecurityPolicy, otTimestamp::mTicks, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDatasetSendMgmtActiveSet(), otDatasetSendMgmtPendingSet(), otNetworkNameFromString(), Dataset::ParseSecurityPolicy(), SuccessOrExit, and VerifyOrExit.
Process() [19/22]
otError Process (Arg aArgs[]) private
References ExitNow, OutputWrapper::GetInstancePtr(), Arg::IsEmpty(), otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsDelayPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkKeyPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPendingTimestampPresent, otOperationalDatasetComponents::mIsSecurityPolicyPresent, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDatasetSendMgmtActiveGet(), otDatasetSendMgmtPendingGet(), and SuccessOrExit.
Process() [20/22]
otError Process (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), otPskc::m8, otOperationalDataset::mComponents, otOperationalDataset::mExtendedPanId, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPskcPresent, otOperationalDataset::mNetworkName, otOperationalDataset::mPskc, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDatasetGeneratePskc(), otThreadGetExtendedPanId(), otThreadGetNetworkName(), OutputWrapper::OutputBytesLine(), ot::Utils::CmdLineParser::ParseAsHexString(), Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
Process() [21/22]
otError Process (Arg aArgs[]) private
References otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsSecurityPolicyPresent, otOperationalDataset::mSecurityPolicy, OT_ERROR_NONE, Dataset::OutputSecurityPolicy(), Dataset::ParseSecurityPolicy(), Dataset::sDataset, and SuccessOrExit.
Process() [22/22]
otError Process (Arg aArgs[]) private
References ot::Cli::Cmd(), Dataset::ConvertTo(), ExitNow, Dataset::GetBytes(), OutputWrapper::GetInstancePtr(), Dataset::IsValid(), Dataset::kMaxSize, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDatasetSetActive(), otDatasetSetPending(), otDatasetUpdaterCancelUpdate(), otDatasetUpdaterIsUpdateOngoing(), otDatasetUpdaterRequestUpdate(), otThreadErrorToString(), OutputWrapper::OutputEnabledDisabledStatus(), OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsHexString(), Dataset::Process(), Dataset::sDataset, Dataset::SetSize(), SuccessOrExit, and VerifyOrExit.
Field Documentation
sDataset
otOperationalDataset sDataset static private
Referenced by Dataset::Process().
The documentation for this class was generated from the following files:
cli_dataset.hpp
cli_dataset.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale