OpenThread: PrefixTlv Class Reference
PrefixTlv Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Member Functions
void CopyPrefixTo (Ip6::Prefix &aPrefix) const
template<typename SubTlvType >
SubTlvType * FindSubTlv (void)
template<typename SubTlvType >
const SubTlvType * FindSubTlv (void) const
template<typename SubTlvType >
SubTlvType * FindSubTlv (bool aStable)
template<typename SubTlvType >
const SubTlvType * FindSubTlv (bool aStable) const
NetworkDataTlv * FindSubTlv (Type aType)
const NetworkDataTlv * FindSubTlv (Type aType) const
NetworkDataTlv * FindSubTlv (Type aType, bool aStable)
const NetworkDataTlv * FindSubTlv (Type aType, bool aStable) const
uint8_t GetDomainId (void) const
uint8_t * GetPrefix (void)
const uint8_t * GetPrefix (void) const
uint8_t GetPrefixLength (void) const
NetworkDataTlv * GetSubTlvs (void)
const NetworkDataTlv * GetSubTlvs (void) const
uint8_t GetSubTlvsLength (void) const
void Init (uint8_t aDomainId, uint8_t aPrefixLength, const uint8_t *aPrefix)
void Init (uint8_t aDomainId, const Ip6::Prefix aPrefix)
bool IsEqual (Ip6::Prefix &aPrefix) const
bool IsEqual (const uint8_t *aPrefix, uint8_t aPrefixLength) const
bool IsValid (void) const
void SetSubTlvsLength (uint8_t aLength)
Public Member Functions inherited from NetworkDataTlv
void ClearStable (void)
void DecreaseLength (uint8_t aDecrement)
uint8_t GetLength (void) const
NetworkDataTlv * GetNext (void)
const NetworkDataTlv * GetNext (void) const
uint8_t GetSize (void) const
Type GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
void IncreaseLength (uint8_t aIncrement)
void Init (void)
bool IsStable (void) const
void SetLength (uint8_t aLength)
void SetStable (void)
void SetType (Type aType)
Static Public Member Functions
static uint16_t CalculateSize (uint8_t aPrefixLength)
Static Public Member Functions inherited from NetworkDataTlv
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType, bool aStable)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType, bool aStable)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, bool aStable)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, bool aStable)
Static Public Attributes
static constexpr Type kType = kTypePrefix
The TLV Type.
Private Attributes
uint8_t mDomainId
uint8_t mPrefixLength
Additional Inherited Members
Public Types inherited from NetworkDataTlv
enum Type : uint8_t {
kTypeHasRoute = 0, kTypePrefix = 1, kTypeBorderRouter = 2, kTypeContext = 3,
kTypeCommissioningData = 4, kTypeService = 5, kTypeServer = 6
}
Detailed Description
This class implements Prefix TLV generation and parsing.
Member Function Documentation
Init() [1/2]
void Init (uint8_t aDomainId, uint8_t aPrefixLength, const uint8_t * aPrefix) inline
This method initializes the TLV.
Parameters
[in] aDomainId The Domain ID.
[in] aPrefixLength The Prefix Length in bits.
[in] aPrefix A pointer to the prefix.
References NetworkDataTlv::Init(), NetworkDataTlv::kTypePrefix, NetworkDataTlv::SetType(), and Prefix::SizeForLength().
Init() [2/2]
void Init (uint8_t aDomainId, const Ip6::Prefix aPrefix) inline
This method initializes the TLV.
Parameters
[in] aDomainId The Domain ID.
[in] aPrefix The Prefix.
References Prefix::GetBytes(), Prefix::GetLength(), and NetworkDataTlv::Init().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References NetworkDataTlv::GetLength(), and Prefix::SizeForLength().
GetDomainId()
uint8_t GetDomainId (void) const inline
This method returns the Domain ID value.
Returns
The Domain ID value.
Referenced by LeaderBase::ExternalRouteLookup(), and LeaderBase::RouteLookup().
GetPrefixLength()
uint8_t GetPrefixLength (void) const inline
This method returns the Prefix Length value.
Returns
The Prefix Length value (in bits).
Referenced by LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), and LeaderBase::GetContext().
GetPrefix() [1/2]
uint8_t* GetPrefix (void) inline
This method returns a pointer to the Prefix.
Returns
A pointer to the Prefix.
Referenced by LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), and LeaderBase::GetContext().
GetPrefix() [2/2]
const uint8_t* GetPrefix (void) const inline
This method returns a pointer to the Prefix.
Returns
A pointer to the Prefix.
CopyPrefixTo()
void CopyPrefixTo (Ip6::Prefix & aPrefix) const inline
This method copies the Prefix from TLV into a given Ip6::Prefix.
Parameters
[out] aPrefix An Ip6::Prefix to copy the Prefix from TLV into.
References Prefix::Set().
Referenced by OnMeshPrefixConfig::SetFrom(), and ExternalRouteConfig::SetFrom().
IsEqual() [1/2]
bool IsEqual (Ip6::Prefix & aPrefix) const inline
This method indicates whether the Prefix from TLV is equal to a given Ip6::Prefix.
Parameters
[in] aPrefix A Prefix to compare with.
Return values
TRUE The TLV's Prefix is equal to aPrefix.
FALSE The TLV's Prefix is not equal to aPrefix.
References Prefix::IsEqual().
Referenced by NetworkData::FindPrefix().
IsEqual() [2/2]
bool IsEqual (const uint8_t * aPrefix, uint8_t aPrefixLength) const inline
This method indicates whether the Prefix from TLV is equal to a given Prefix.
Parameters
[in] aPrefix A pointer to an IPv6 prefix to compare with.
[in] aPrefixLength The prefix length pointed to by aPrefix (in bits).
Return values
TRUE The TLV's Prefix is equal to aPrefix.
FALSE The TLV's Prefix is not equal aPrefix.
References Prefix::MatchLength(), and Prefix::SizeForLength().
GetSubTlvs() [1/2]
NetworkDataTlv* GetSubTlvs (void) inline
This method returns a pointer to the Sub-TLVs.
Returns
A pointer to the Sub-TLVs.
References Prefix::SizeForLength().
Referenced by MutableNetworkData::RemoveTemporaryDataIn().
GetSubTlvs() [2/2]
const NetworkDataTlv* GetSubTlvs (void) const inline
This method returns a pointer to the Sub-TLVs.
Returns
A pointer to the Sub-TLVs.
References Prefix::SizeForLength().
GetSubTlvsLength()
uint8_t GetSubTlvsLength (void) const inline
This method returns the Sub-TLVs length in bytes.
Returns
The Sub-TLVs length in bytes.
References NetworkDataTlv::GetLength(), and Prefix::SizeForLength().
Referenced by MutableNetworkData::RemoveTemporaryData(), and MutableNetworkData::RemoveTemporaryDataIn().
SetSubTlvsLength()
void SetSubTlvsLength (uint8_t aLength) inline
This method sets the Sub-TLVs length in bytes.
Parameters
[in] aLength The Sub-TLVs length in bytes.
References NetworkDataTlv::SetLength(), and Prefix::SizeForLength().
Referenced by MutableNetworkData::RemoveTemporaryDataIn().
FindSubTlv() [1/8]
SubTlvType* FindSubTlv (void) inline
This template method searches in the sub-TLVs to find the first one matching a given TLV type.
Template Parameters
SubTlvType The sub-TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Returns
A pointer to the TLV if found, or nullptr if not found.
Referenced by NetworkDataTlv::Find(), LeaderBase::GetContext(), LeaderBase::IsOnMesh(), and MutableNetworkData::RemoveTemporaryDataIn().
FindSubTlv() [2/8]
const SubTlvType* FindSubTlv (void) const inline
This template method searches in the sub-TLVs to find the first one matching a given TLV Type.
Template Parameters
SubTlvType The sub-TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Returns
A pointer to the TLV if found, or nullptr if not found.
FindSubTlv() [3/8]
SubTlvType* FindSubTlv (bool aStable) inline
This template method searches in the sub-TLVs to find the first one matching a given TLV type and stable flag.
Template Parameters
SubTlvType The sub-TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Parameters
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
FindSubTlv() [4/8]
const SubTlvType* FindSubTlv (bool aStable) const inline
This template method searches in the sub-TLVs to find the first one matching a given TLV type and stable flag.
Template Parameters
SubTlvType The sub-TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Parameters
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
FindSubTlv() [5/8]
NetworkDataTlv* FindSubTlv (Type aType) inline
This method searches in the sub-TLVs to find the first one matching a given TLV type.
Parameters
[in] aType The sub-TLV type to search for.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ot::AsConst(), ot::AsNonConst(), and PrefixTlv::FindSubTlv().
Referenced by PrefixTlv::FindSubTlv().
FindSubTlv() [6/8]
const NetworkDataTlv* FindSubTlv (Type aType) const
This method searches in the sub-TLVs to find the first one matching a given TLV type.
Parameters
[in] aType The sub-TLV type to search for.
Returns
A pointer to the TLV if found, or nullptr if not found.
FindSubTlv() [7/8]
NetworkDataTlv* FindSubTlv (Type aType, bool aStable) inline
This method searches in the sub-TLVs to find the first one matching a given TLV type and stable flag.
Parameters
[in] aType The sub-TLV type to search for.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ot::AsConst(), and ot::AsNonConst().
FindSubTlv() [8/8]
const NetworkDataTlv* FindSubTlv (Type aType, bool aStable) const
This method searches in the sub-TLVs to find the first one matching a given TLV type and stable flag.
Parameters
[in] aType The sub-TLV type to search for.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
CalculateSize()
static uint16_t CalculateSize (uint8_t aPrefixLength) inline static
This static method calculates the total size (number of bytes) of a Prefix TLV with a given Prefix Length value.
Note that the returned size does include the Type and Length fields in the TLV, but does not account for any sub TLVs of the Prefix TLV.
Parameters
[in] aPrefixLength A Prefix Length in bits.
Returns
The size (number of bytes) of the Prefix TLV.
References Prefix::SizeForLength().
Field Documentation
kType
constexpr Type kType = kTypePrefix static
The TLV Type.
mDomainId
uint8_t mDomainId private
mPrefixLength
uint8_t mPrefixLength private
The documentation for this class was generated from the following file:
network_data_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale