OpenThread: NetworkName Class Reference
NetworkName Class Reference
#include <network_name.hpp>
Public Member Functions
const char * GetAsCString (void) const
NameData GetAsData (void) const
NetworkName (void)
bool operator== (const NetworkName &aOther) const
Error Set (const char *aNameString)
Error Set (const NameData &aNameData)
Public Member Functions inherited from Unequatable< NetworkName >
bool operator!= (const NetworkName &aOther) const
Static Public Attributes
static constexpr uint8_t kMaxSize = OT_NETWORK_NAME_MAX_SIZE
Additional Inherited Members
Data Fields inherited from otNetworkName
char m8 [OT_NETWORK_NAME_MAX_SIZE+1]
Byte values. The + 1 is for null char.
Detailed Description
This structure represents an Network Name.
Constructor & Destructor Documentation
NetworkName()
NetworkName (void) inline
This constructor initializes the Network Name as an empty string.
Member Function Documentation
GetAsCString()
const char* GetAsCString (void) const inline
This method gets the Network Name as a null terminated C string.
Returns
The Network Name as a null terminated C string array.
References Data< kWithUint8Length >::operator==().
Referenced by ot::MeshCoP::GetBorderAgentRloc().
GetAsData()
NameData GetAsData (void) const
This method gets the Network Name as NameData.
Returns
The Network Name as NameData.
References NameData::NameData(), and ot::StringLength().
Referenced by NetworkName::operator==(), and Dataset::SetFrom().
Set() [1/2]
Error Set (const char * aNameString)
This method sets the Network Name from a given null terminated C string.
This method also validates that the given aNameString follows UTF-8 encoding and can fit in kMaxSize chars.
Parameters
[in] aNameString A name C string.
Return values
kErrorNone Successfully set the Network Name.
kErrorAlready The name is already set to the same string.
kErrorInvalidArgs Given name is invalid (too long or does not follow UTF-8 encoding).
References ot::IsValidUtf8String(), ot::kErrorInvalidArgs, and VerifyOrExit.
Referenced by NetworkNameManager::SetDomainName(), and NetworkNameManager::SetNetworkName().
Set() [2/2]
Error Set (const NameData & aNameData)
This method sets the Network Name.
Parameters
[in] aNameData A reference to name data.
Return values
kErrorNone Successfully set the Network Name.
kErrorAlready The name is already set to the same string.
kErrorInvalidArgs Given name is too long.
References Data< kDataLengthType >::CopyBytesTo(), ExitNow, NameData::GetBuffer(), NameData::GetLength(), ot::kErrorAlready, ot::kErrorInvalidArgs, ot::kErrorNone, Data< kDataLengthType >::MatchesBytesIn(), Data< kDataLengthType >::SetLength(), ot::StringLength(), and VerifyOrExit.
operator==()
bool operator== (const NetworkName & aOther) const
This method overloads operator == to evaluate whether or not two given NetworkName objects are equal.
Parameters
[in] aOther The other NetworkName to compare with.
Return values
TRUE If the two are equal.
FALSE If the two are not equal.
References NetworkName::GetAsData().
Field Documentation
kMaxSize
constexpr uint8_t kMaxSize = OT_NETWORK_NAME_MAX_SIZE static
This constant specified the maximum number of chars in Network Name (excludes null char).
The documentation for this class was generated from the following files:
network_name.hpp
network_name.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale