OpenThread: Tlv Class Reference
Tlv Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Types
enum Type : uint8_t {
kSourceAddress = 0, kMode = 1, kTimeout = 2, kChallenge = 3,
kResponse = 4, kLinkFrameCounter = 5, kLinkQuality = 6, kNetworkParameter = 7,
kMleFrameCounter = 8, kRoute = 9, kAddress16 = 10, kLeaderData = 11,
kNetworkData = 12, kTlvRequest = 13, kScanMask = 14, kConnectivity = 15,
kLinkMargin = 16, kStatus = 17, kVersion = 18, kAddressRegistration = 19,
kChannel = 20, kPanId = 21, kActiveTimestamp = 22, kPendingTimestamp = 23,
kActiveDataset = 24, kPendingDataset = 25, kDiscovery = 26, kCslChannel = 80,
kCslTimeout = 85, kCslClockAccuracy = 86, kLinkMetricsQuery = 87, kLinkMetricsManagement = 88,
kLinkMetricsReport = 89, kLinkProbe = 90, kTimeRequest = 252, kTimeParameter = 253,
kXtalAccuracy = 254, kInvalid = 255
}
Public Member Functions
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Additional Inherited Members
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements MLE TLV generation and parsing.
Member Enumeration Documentation
Type
enum Type : uint8_t
MLE TLV Types.
Enumerator
kSourceAddress
Source Address TLV.
kMode
Mode TLV.
kTimeout
Timeout TLV.
kChallenge
Challenge TLV.
kResponse
Response TLV.
kLinkFrameCounter
Link-Layer Frame Counter TLV.
kLinkQuality
Link Quality TLV.
kNetworkParameter
Network Parameter TLV.
kMleFrameCounter
MLE Frame Counter TLV.
kRoute
Route64 TLV.
kAddress16
Address16 TLV.
kLeaderData
Leader Data TLV.
kNetworkData
Network Data TLV.
kTlvRequest
TLV Request TLV.
kScanMask
Scan Mask TLV.
kConnectivity
Connectivity TLV.
kLinkMargin
Link Margin TLV.
kStatus
Status TLV.
kVersion
Version TLV.
kAddressRegistration
Address Registration TLV.
kChannel
Channel TLV.
kPanId
PAN ID TLV.
kActiveTimestamp
Active Timestamp TLV.
kPendingTimestamp
Pending Timestamp TLV.
kActiveDataset
Active Operational Dataset TLV.
kPendingDataset
Pending Operational Dataset TLV.
kDiscovery
Thread Discovery TLV.
kCslChannel
CSL Channel TLV.
kCslTimeout
CSL Timeout TLV.
kCslClockAccuracy
CSL Clock Accuracy TLV.
kLinkMetricsQuery
Link Metrics Query TLV.
kLinkMetricsManagement
Link Metrics Management TLV.
kLinkMetricsReport
Link Metrics Report TLV.
kLinkProbe
Link Probe TLV.
kTimeRequest
Time Request TLV.
Applicable/Required only when time synchronization service (OPENTHREAD_CONFIG_TIME_SYNC_ENABLE) is enabled.
kTimeParameter
Time Parameter TLV.
kXtalAccuracy
XTAL Accuracy TLV.
kInvalid
Member Function Documentation
GetType()
Type GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Tlv::GetType().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References ot::Mle::OT_TOOL_PACKED_END, and Tlv::SetType().
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), Dataset::AppendMleDatasetTlv(), DiscoverScanner::Discover(), Mle::HasMoreChannelsToAnnouce(), RouteTlv::Init(), LeaderDataTlv::Init(), ConnectivityTlv::Init(), ChannelTlv::Init(), Mle::RoleToString(), and Mle::TxMessage::SendAfterDelay().
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale