OpenThread: LeaderDataTlv Class Reference
LeaderDataTlv Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Member Functions
void Get (LeaderData &aLeaderData) const
void Init (void)
bool IsValid (void) const
void Set (const LeaderData &aLeaderData)
Public Member Functions inherited from Tlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint8_t mDataVersion
uint8_t mLeaderRouterId
uint32_t mPartitionId
uint8_t mStableDataVersion
uint8_t mWeighting
Additional Inherited Members
Public Types inherited from Tlv
enum Type : uint8_t {
kSourceAddress = 0, kMode = 1, kTimeout = 2, kChallenge = 3,
kResponse = 4, kLinkFrameCounter = 5, kLinkQuality = 6, kNetworkParameter = 7,
kMleFrameCounter = 8, kRoute = 9, kAddress16 = 10, kLeaderData = 11,
kNetworkData = 12, kTlvRequest = 13, kScanMask = 14, kConnectivity = 15,
kLinkMargin = 16, kStatus = 17, kVersion = 18, kAddressRegistration = 19,
kChannel = 20, kPanId = 21, kActiveTimestamp = 22, kPendingTimestamp = 23,
kActiveDataset = 24, kPendingDataset = 25, kDiscovery = 26, kCslChannel = 80,
kCslTimeout = 85, kCslClockAccuracy = 86, kLinkMetricsQuery = 87, kLinkMetricsManagement = 88,
kLinkMetricsReport = 89, kLinkProbe = 90, kTimeRequest = 252, kTimeParameter = 253,
kXtalAccuracy = 254, kInvalid = 255
}
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< Tlv::kLeaderData >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements Leader Data TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References Tlv::kLeaderData, Tlv::SetLength(), and Tlv::SetType().
Referenced by Mle::TxMessage::AppendLeaderDataTlv().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
Referenced by Mle::RxMessage::ReadLeaderDataTlv().
Get()
void Get (LeaderData & aLeaderData) const inline
This method gets the Leader Data info from TLV.
Parameters
[out] aLeaderData A reference to output Leader Data info.
References ot::Encoding::BigEndian::HostSwap32(), LeaderData::SetDataVersion(), LeaderData::SetLeaderRouterId(), LeaderData::SetPartitionId(), LeaderData::SetStableDataVersion(), and LeaderData::SetWeighting().
Referenced by Mle::RxMessage::ReadLeaderDataTlv().
Set()
void Set (const LeaderData & aLeaderData) inline
This method sets the Leader Data.
Parameters
[in] aLeaderData A Leader Data.
References LeaderData::GetDataVersion(), LeaderData::GetLeaderRouterId(), LeaderData::GetPartitionId(), LeaderData::GetWeighting(), ot::Encoding::BigEndian::HostSwap32(), ot::NetworkData::kFullSet, and ot::NetworkData::kStableSubset.
Referenced by Mle::TxMessage::AppendLeaderDataTlv().
Field Documentation
mPartitionId
uint32_t mPartitionId private
mWeighting
uint8_t mWeighting private
mDataVersion
uint8_t mDataVersion private
mStableDataVersion
uint8_t mStableDataVersion private
mLeaderRouterId
uint8_t mLeaderRouterId private
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale