OpenThread: Dataset Class Reference
Dataset Class Reference
#include <dataset.hpp>
Data Structures
class Components
class Info
Public Types
enum Type : uint8_t { kActive, kPending }
Public Member Functions
Error AppendMleDatasetTlv (Type aType, Message &aMessage) const
Error ApplyConfiguration (Instance &aInstance, bool *aIsNetworkKeyUpdated=nullptr) const
void Clear (void)
void ConvertTo (Info &aDatasetInfo) const
void ConvertTo (otOperationalDatasetTlvs &aDataset) const
void ConvertToActive (void)
Dataset (void)
uint8_t * GetBytes (void)
const uint8_t * GetBytes (void) const
uint16_t GetSize (void) const
Error GetTimestamp (Type aType, Timestamp &aTimestamp) const
Tlv * GetTlv (Tlv::Type aType)
const Tlv * GetTlv (Tlv::Type aType) const
template<typename TlvType >
TlvType * GetTlv (void)
template<typename TlvType >
const TlvType * GetTlv (void) const
Tlv * GetTlvsEnd (void)
const Tlv * GetTlvsEnd (void) const
Tlv * GetTlvsStart (void)
const Tlv * GetTlvsStart (void) const
TimeMilli GetUpdateTime (void) const
bool IsValid (void) const
Error ReadFromMessage (const Message &aMessage, uint16_t aOffset, uint8_t aLength)
void RemoveTlv (Tlv::Type aType)
void Set (Type aType, const Dataset &aDataset)
Error SetFrom (const Info &aDatasetInfo)
void SetFrom (const otOperationalDatasetTlvs &aDataset)
void SetSize (uint16_t aSize)
void SetTimestamp (Type aType, const Timestamp &aTimestamp)
Error SetTlv (const Tlv &aTlv)
Error SetTlv (Tlv::Type aType, const void *aValue, uint8_t aLength)
template<typename ValueType >
Error SetTlv (Tlv::Type aType, const ValueType &aValue)
template<>
Error SetTlv (Tlv::Type aType, const uint16_t &aValue)
template<>
Error SetTlv (Tlv::Type aType, const uint32_t &aValue)
Static Public Member Functions
static const char * TypeToString (Type aType)
Static Public Attributes
static constexpr uint8_t kMaxGetTypes = 64
Max number of types in MGMT_GET.req.
static constexpr uint8_t kMaxSize = OT_OPERATIONAL_DATASET_MAX_LENGTH
Max size of MeshCoP Dataset (bytes)
static constexpr uint8_t kMaxValueSize = 16
Max size of a TLV value (bytes)
Private Member Functions
void RemoveTlv (Tlv *aTlv)
Private Attributes
uint8_t mTlvs [kMaxSize]
The Dataset buffer.
TimeMilli mUpdateTime
Local time last updated.
Friends
class DatasetLocal
Detailed Description
This class represents MeshCop Dataset.
Member Enumeration Documentation
Type
enum Type : uint8_t
This enumeration represents the Dataset type (active or pending).
Enumerator
kActive
Active Dataset.
kPending
Pending Dataset.
Constructor & Destructor Documentation
Dataset()
Dataset (void)
This constructor initializes the object.
References Dataset::mTlvs.
Referenced by Dataset::Info::SetChannelMask().
Member Function Documentation
Clear()
void Clear (void)
This method clears the Dataset.
IsValid()
bool IsValid (void) const
This method indicates whether or not the dataset appears to be well-formed.
Returns
TRUE if the dataset appears to be well-formed, FALSE otherwise.
References Tlv::GetNext(), Dataset::GetTlvsEnd(), Dataset::GetTlvsStart(), Tlv::IsValid(), and VerifyOrExit.
Referenced by Dataset::ApplyConfiguration(), otDatasetParseTlvs(), Dataset::Process(), Dataset::ReadFromMessage(), and Dataset::Info::SetChannelMask().
GetTlv() [1/4]
Tlv* GetTlv (Tlv::Type aType) inline
This method returns a pointer to the TLV with a given type.
Parameters
[in] aType A TLV type.
Returns
A pointer to the TLV or nullptr if none is found.
References ot::AsConst(), ot::AsNonConst(), and Dataset::GetTlv().
Referenced by DatasetManager::GetChannelMask(), Dataset::GetTlv(), PendingDatasetManager::HandleDelayTimer(), DatasetLocal::Read(), DatasetLocal::Save(), DatasetManager::SendGetResponse(), and PendingDatasetManager::StartDelayTimer().
GetTlv() [2/4]
const Tlv * GetTlv (Tlv::Type aType) const
This method returns a pointer to the TLV with a given type.
Parameters
[in] aType The TLV type.
Returns
A pointer to the TLV or nullptr if none is found.
References Tlv::FindTlv(), and Dataset::mTlvs.
GetTlv() [3/4]
TlvType* GetTlv (void) inline
This template method returns a pointer to the TLV with a given template type TlvType
Returns
A pointer to the TLV or nullptr if none is found.
Referenced by Dataset::GetTlv(), Dataset::RemoveTlv(), and Dataset::SetTlv().
GetTlv() [4/4]
const TlvType* GetTlv (void) const inline
This template method returns a pointer to the TLV with a given template type TlvType
Returns
A pointer to the TLV or nullptr if none is found.
References Dataset::GetTlv().
GetBytes() [1/2]
uint8_t* GetBytes (void) inline
This method returns a pointer to the byte representation of the Dataset.
Returns
A pointer to the byte representation of the Dataset.
References Dataset::mTlvs.
Referenced by DatasetManager::AppendDatasetToMessage(), Dataset::Process(), Settings::ReadOperationalDataset(), Settings::SaveOperationalDataset(), DatasetManager::SendSet(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
GetBytes() [2/2]
const uint8_t* GetBytes (void) const inline
This method returns a pointer to the byte representation of the Dataset.
Returns
A pointer to the byte representation of the Dataset.
References Dataset::ConvertTo(), and Dataset::mTlvs.
ConvertTo() [1/2]
void ConvertTo (Info & aDatasetInfo) const
This method converts the TLV representation to structure representation.
Parameters
[out] aDatasetInfo A reference to Info object to output the Dataset.
References Clearable< Type >::Clear(), Dataset::GetTimestamp(), Dataset::GetTlvsEnd(), Dataset::GetTlvsStart(), Tlv::kActiveTimestamp, Tlv::kChannel, Tlv::kChannelMask, Tlv::kDelayTimer, Tlv::kExtendedPanId, Tlv::kMeshLocalPrefix, Tlv::kNetworkKey, Tlv::kNetworkName, Tlv::kPanId, Tlv::kPendingTimestamp, Tlv::kPskc, Tlv::kSecurityPolicy, Dataset::Info::SetActiveTimestamp(), Dataset::Info::SetChannel(), Dataset::Info::SetChannelMask(), Dataset::Info::SetDelay(), Dataset::Info::SetExtendedPanId(), Dataset::Info::SetMeshLocalPrefix(), Dataset::Info::SetNetworkKey(), Dataset::Info::SetNetworkName(), Dataset::Info::SetPanId(), Dataset::Info::SetPendingTimestamp(), Dataset::Info::SetPskc(), and Dataset::Info::SetSecurityPolicy().
Referenced by Dataset::GetBytes(), otDatasetParseTlvs(), Dataset::Process(), and DatasetLocal::Read().
ConvertTo() [2/2]
void ConvertTo (otOperationalDatasetTlvs & aDataset) const
This method converts the TLV representation to structure representation.
Parameters
[out] aDataset A reference to otOperationalDatasetTlvs to output the Dataset.
References otOperationalDatasetTlvs::mLength, otOperationalDatasetTlvs::mTlvs, and Dataset::mTlvs.
GetSize()
uint16_t GetSize (void) const inline
This method returns the Dataset size in bytes.
Returns
The Dataset size in bytes.
Referenced by DatasetManager::AppendDatasetToMessage(), DatasetLocal::Save(), Settings::SaveOperationalDataset(), DatasetManager::SendSet(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
SetSize()
void SetSize (uint16_t aSize) inline
This method sets the Dataset size in bytes.
Parameters
[in] aSize The Dataset size in bytes.
Referenced by Dataset::Process(), and Settings::ReadOperationalDataset().
GetUpdateTime()
TimeMilli GetUpdateTime (void) const inline
This method returns the local time the dataset was last updated.
Returns
The local time the dataset was last updated.
References Dataset::GetTimestamp(), Dataset::mUpdateTime, Dataset::SetTimestamp(), and Dataset::SetTlv().
Referenced by PendingDatasetManager::HandleDelayTimer(), Dataset::Set(), and PendingDatasetManager::StartDelayTimer().
GetTimestamp()
Error GetTimestamp (Type aType, Timestamp & aTimestamp) const
This method gets the Timestamp (Active or Pending).
Parameters
[in] aType The type: active or pending.
[out] aTimestamp A reference to a Timestamp to output the value.
Return values
kErrorNone Timestamp was read successfully. aTimestamp is updated.
kErrorNotFound Could not find the requested Timestamp TLV.
References ActiveTimestampTlv::GetTimestamp(), PendingTimestampTlv::GetTimestamp(), Dataset::kActive, ot::kErrorNone, ot::kErrorNotFound, and VerifyOrExit.
Referenced by Dataset::ConvertTo(), Dataset::GetUpdateTime(), DatasetManager::Restore(), DatasetLocal::Restore(), DatasetLocal::Save(), DatasetManager::Save(), and DatasetManager::SendSet().
SetTimestamp()
void SetTimestamp (Type aType, const Timestamp & aTimestamp)
This method sets the Timestamp value.
Parameters
[in] aType The type: active or pending.
[in] aTimestamp A Timestamp.
References IgnoreError(), Dataset::kActive, Tlv::kActiveTimestamp, Tlv::kPendingTimestamp, and Dataset::SetTlv().
Referenced by Dataset::GetUpdateTime(), ActiveDatasetManager::Save(), and PendingDatasetManager::Save().
SetTlv() [1/5]
Error SetTlv (const Tlv & aTlv)
This method sets a TLV in the Dataset.
Parameters
[in] aTlv A reference to the TLV.
Return values
kErrorNone Successfully set the TLV.
kErrorNoBufs Could not set the TLV due to insufficient buffer space.
References Tlv::GetLength(), Tlv::GetType(), and Tlv::GetValue().
Referenced by Dataset::GetUpdateTime(), Dataset::SetFrom(), Dataset::SetTimestamp(), and Dataset::SetTlv().
SetTlv() [2/5]
Error SetTlv (Tlv::Type aType, const void * aValue, uint8_t aLength)
This method sets a TLV with a given TLV Type and Value.
Parameters
[in] aType The TLV Type.
[in] aValue A pointer to TLV Value.
[in] aLength The TLV Length in bytes (length of aValue).
Return values
kErrorNone Successfully set the TLV.
kErrorNoBufs Could not set the TLV due to insufficient buffer space.
References Tlv::GetLength(), TimerMilli::GetNow(), Dataset::GetTlv(), ot::kErrorNoBufs, ot::kErrorNone, Dataset::mTlvs, Dataset::mUpdateTime, Dataset::RemoveTlv(), Tlv::SetLength(), Tlv::SetType(), and VerifyOrExit.
SetTlv() [3/5]
Error SetTlv (Tlv::Type aType, const ValueType & aValue) inline
This template method sets a TLV with a given TLV Type and Value.
Template Parameters
ValueType The type of TLV's Value.
Parameters
[in] aType The TLV Type.
[in] aValue The TLV Value (of type ValueType).
Return values
kErrorNone Successfully set the TLV.
kErrorNoBufs Could not set the TLV due to insufficient buffer space.
References Dataset::AppendMleDatasetTlv(), Dataset::ApplyConfiguration(), Dataset::ConvertToActive(), Dataset::ReadFromMessage(), Dataset::RemoveTlv(), Dataset::Set(), Dataset::SetFrom(), and Dataset::SetTlv().
ReadFromMessage()
Error ReadFromMessage (const Message & aMessage, uint16_t aOffset, uint8_t aLength)
This method reads the Dataset from a given message and checks that it is well-formed and valid.
Parameters
[in] aMessage The message to read from.
[in] aOffset The offset in aMessage to start reading the Dataset TLVs.
[in] aLength The dataset length in bytes.
Return values
kErrorNone Successfully read and validated the Dataset.
kErrorParse Could not read or parse the dataset from aMessage.
References TimerMilli::GetNow(), Dataset::IsValid(), ot::kErrorNone, ot::kErrorParse, Dataset::mTlvs, Dataset::mUpdateTime, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by ActiveDatasetManager::Save(), PendingDatasetManager::Save(), and Dataset::SetTlv().
Set()
void Set (Type aType, const Dataset & aDataset)
This method sets the Dataset using an existing Dataset.
If this Dataset is an Active Dataset, any Pending Timestamp and Delay Timer TLVs will be omitted in the copy from aDataset.
Parameters
[in] aType The type of the dataset, active or pending.
[in] aDataset The input Dataset.
References Dataset::GetUpdateTime(), Dataset::kActive, Tlv::kDelayTimer, Tlv::kPendingTimestamp, Dataset::mTlvs, Dataset::mUpdateTime, and Dataset::RemoveTlv().
Referenced by DatasetLocal::Save(), Dataset::Info::SetNetworkName(), and Dataset::SetTlv().
SetFrom() [1/2]
Error SetFrom (const Info & aDatasetInfo)
This method sets the Dataset from a given structure representation.
Parameters
[in] aDatasetInfo The input Dataset as Dataset::Info.
Return values
kErrorNone Successfully set the Dataset.
kErrorInvalidArgs Dataset is missing Active and/or Pending Timestamp.
References Dataset::Info::GetActiveTimestamp(), NetworkName::GetAsData(), NameData::GetBuffer(), Dataset::Info::GetChannel(), Dataset::Info::GetChannelMask(), Dataset::Info::GetDelay(), Dataset::Info::GetExtendedPanId(), NameData::GetLength(), Dataset::Info::GetMeshLocalPrefix(), Dataset::Info::GetNetworkKey(), Dataset::Info::GetNetworkName(), TimerMilli::GetNow(), Dataset::Info::GetPanId(), Dataset::Info::GetPendingTimestamp(), Dataset::Info::GetPskc(), Dataset::Info::GetSecurityPolicy(), IgnoreError(), ChannelTlv::Init(), SecurityPolicyTlv::Init(), ChannelMaskTlv::Init(), Dataset::Info::IsActiveTimestampPresent(), Dataset::Info::IsChannelMaskPresent(), Dataset::Info::IsChannelPresent(), Dataset::Info::IsDelayPresent(), Dataset::Info::IsExtendedPanIdPresent(), Dataset::Info::IsMeshLocalPrefixPresent(), Dataset::Info::IsNetworkKeyPresent(), Dataset::Info::IsNetworkNamePresent(), Dataset::Info::IsPanIdPresent(), Dataset::Info::IsPendingTimestampPresent(), Dataset::Info::IsPskcPresent(), Dataset::Info::IsSecurityPolicyPresent(), Tlv::kActiveTimestamp, Tlv::kDelayTimer, ot::kErrorNone, Tlv::kExtendedPanId, Tlv::kMeshLocalPrefix, Tlv::kNetworkKey, Tlv::kNetworkName, Tlv::kPanId, Tlv::kPendingTimestamp, Tlv::kPskc, Dataset::mUpdateTime, ChannelTlv::SetChannel(), ChannelMaskTlv::SetChannelMask(), SecurityPolicyTlv::SetSecurityPolicy(), and Dataset::SetTlv().
Referenced by DatasetManager::AppendDatasetToMessage(), otDatasetParseTlvs(), DatasetLocal::Save(), Dataset::SetTlv(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
SetFrom() [2/2]
void SetFrom (const otOperationalDatasetTlvs & aDataset)
This method sets the Dataset using aDataset.
Parameters
[in] aDataset The input Dataset as otOperationalDatasetTlvs.
References otOperationalDatasetTlvs::mLength, otOperationalDatasetTlvs::mTlvs, and Dataset::mTlvs.
RemoveTlv() [1/2]
void RemoveTlv (Tlv::Type aType)
This method removes a TLV from the Dataset.
Parameters
[in] aType The type of a specific TLV.
References Dataset::GetTlv(), and VerifyOrExit.
Referenced by Dataset::ConvertToActive(), Dataset::GetTlvsEnd(), DatasetLocal::Read(), Dataset::Set(), and Dataset::SetTlv().
AppendMleDatasetTlv()
Error AppendMleDatasetTlv (Type aType, Message & aMessage) const
This method appends the MLE Dataset TLV but excluding MeshCoP Sub Timestamp TLV.
Parameters
[in] aType The type of the dataset, active or pending.
[in] aMessage A message to append to.
Return values
kErrorNone Successfully append MLE Dataset TLV without MeshCoP Sub Timestamp TLV.
kErrorNoBufs Insufficient available buffers to append the message with MLE Dataset TLV.
References Message::Append(), Tlv::AppendTo(), DelayTimerTlv::GetDelayTimer(), TimerMilli::GetNow(), Dataset::GetTlvsEnd(), Dataset::GetTlvsStart(), Dataset::kActive, Tlv::kActiveDataset, Tlv::kActiveTimestamp, Tlv::kDelayTimer, ot::kErrorNone, Dataset::kPending, Tlv::kPendingDataset, Tlv::kPendingTimestamp, Dataset::mUpdateTime, DelayTimerTlv::SetDelayTimer(), Tlv::SetLength(), Tlv::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by Dataset::SetTlv().
ApplyConfiguration()
Error ApplyConfiguration (Instance & aInstance, bool * aIsNetworkKeyUpdated = nullptr) const
This method applies the Active or Pending Dataset to the Thread interface.
Parameters
[in] aInstance A reference to the OpenThread instance.
[out] aIsNetworkKeyUpdated A pointer to where to place whether network key was updated.
Return values
kErrorNone Successfully applied configuration.
kErrorParse The dataset has at least one TLV with invalid format.
References ot::ErrorToString(), ExitNow, Instance::Get(), NetworkKeyTlv::GetNetworkKey(), Dataset::GetTlvsEnd(), Dataset::GetTlvsStart(), IgnoreError(), Dataset::IsValid(), Tlv::kChannel, ot::kErrorNone, ot::kErrorParse, Tlv::kExtendedPanId, Tlv::kMeshLocalPrefix, Tlv::kNetworkKey, Tlv::kNetworkName, Tlv::kPanId, Tlv::kPskc, Tlv::kSecurityPolicy, LogWarn, NetworkNameManager::SetNetworkName(), Mac::SetPanChannel(), Mac::SetPanId(), and VerifyOrExit.
Referenced by DatasetManager::ApplyConfiguration(), DatasetManager::Restore(), DatasetManager::Save(), and Dataset::SetTlv().
ConvertToActive()
void ConvertToActive (void)
This method converts a Pending Dataset to an Active Dataset.
This method removes the Delay Timer and Pending Timestamp TLVs
References Tlv::kDelayTimer, Tlv::kPendingTimestamp, and Dataset::RemoveTlv().
Referenced by PendingDatasetManager::HandleDelayTimer(), and Dataset::SetTlv().
GetTlvsStart() [1/2]
Tlv* GetTlvsStart (void) inline
This method returns a pointer to the start of Dataset TLVs sequence.
Returns
A pointer to the start of Dataset TLVs sequence.
References Dataset::mTlvs.
Referenced by Dataset::AppendMleDatasetTlv(), Dataset::ApplyConfiguration(), Dataset::ConvertTo(), Dataset::IsValid(), and DatasetManager::SendGetResponse().
GetTlvsStart() [2/2]
const Tlv* GetTlvsStart (void) const inline
This method returns a pointer to the start of Dataset TLVs sequence.
Returns
A pointer to start of Dataset TLVs sequence.
References Dataset::mTlvs.
GetTlvsEnd() [1/2]
Tlv* GetTlvsEnd (void) inline
This method returns a pointer to the past-the-end of Dataset TLVs sequence.
Note that past-the-end points to the byte after the end of the last TLV in Dataset TLVs sequence.
Returns
A pointer to past-the-end of Dataset TLVs sequence.
References Dataset::mTlvs.
Referenced by Dataset::AppendMleDatasetTlv(), Dataset::ApplyConfiguration(), Dataset::ConvertTo(), Dataset::IsValid(), and DatasetManager::SendGetResponse().
GetTlvsEnd() [2/2]
const Tlv* GetTlvsEnd (void) const inline
This method returns a pointer to the past-the-end of Dataset TLVs sequence.
Note that past-the-end points to the byte after the end of the last TLV in Dataset TLVs sequence.
Returns
A pointer to past-the-end of Dataset TLVs sequence.
References Dataset::mTlvs, Dataset::RemoveTlv(), and Dataset::TypeToString().
TypeToString()
const char * TypeToString (Type aType) static
This static method converts a Dataset Type to a string.
Parameters
[in] aType A Dataset type.
References Dataset::kActive.
Referenced by Dataset::GetTlvsEnd(), DatasetLocal::Save(), and DatasetManager::SendSet().
RemoveTlv() [2/2]
void RemoveTlv (Tlv * aTlv) private
References Tlv::GetLength(), and Dataset::mTlvs.
SetTlv() [4/5]
Error SetTlv (Tlv::Type aType, const uint16_t & aValue) inline
This is a template specialization of SetTlv<ValueType> with a uint16_t value type.
Parameters
[in] aType The TLV Type.
[in] aValue The TLV value (as uint16_t).
Return values
kErrorNone Successfully set the TLV.
kErrorNoBufs Could not set the TLV due to insufficient buffer space.
References ot::Encoding::BigEndian::HostSwap16(), and Dataset::SetTlv().
SetTlv() [5/5]
Error SetTlv (Tlv::Type aType, const uint32_t & aValue) inline
This is a template specialization of SetTlv<ValueType> with a uint32_t value type
Parameters
[in] aType The TLV Type.
[in] aValue The TLV value (as uint32_t).
Return values
kErrorNone Successfully set the TLV.
kErrorNoBufs Could not set the TLV due to insufficient buffer space.
References ot::DefineCoreType(), ot::Encoding::BigEndian::HostSwap32(), and Dataset::SetTlv().
Friends And Related Function Documentation
DatasetLocal
friend class DatasetLocal friend
Field Documentation
kMaxSize
constexpr uint8_t kMaxSize = OT_OPERATIONAL_DATASET_MAX_LENGTH static
Max size of MeshCoP Dataset (bytes)
Referenced by Dataset::Process(), and Settings::ReadOperationalDataset().
kMaxValueSize
constexpr uint8_t kMaxValueSize = 16 static
Max size of a TLV value (bytes)
kMaxGetTypes
constexpr uint8_t kMaxGetTypes = 64 static
Max number of types in MGMT_GET.req.
Referenced by DatasetManager::HandleGet().
mTlvs
uint8_t mTlvs[kMaxSize] private
The Dataset buffer.
Referenced by Dataset::ConvertTo(), Dataset::Dataset(), Dataset::GetBytes(), Dataset::GetTlv(), Dataset::GetTlvsEnd(), Dataset::GetTlvsStart(), Dataset::ReadFromMessage(), Dataset::RemoveTlv(), Dataset::Set(), Dataset::SetFrom(), and Dataset::SetTlv().
mUpdateTime
TimeMilli mUpdateTime private
Local time last updated.
Referenced by Dataset::AppendMleDatasetTlv(), Dataset::GetUpdateTime(), DatasetLocal::Read(), Dataset::ReadFromMessage(), Dataset::Set(), Dataset::SetFrom(), and Dataset::SetTlv().
The documentation for this class was generated from the following files:
dataset.hpp
dataset.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale