OpenThread: Leader Class Reference
Leader Class Reference
#include <bbr_leader.hpp>
Public Types
enum DomainPrefixState : uint8_t {
kDomainPrefixNone = 0, kDomainPrefixAdded, kDomainPrefixRemoved, kDomainPrefixRefreshed,
kDomainPrefixUnchanged
}
enum State : uint8_t {
kStateNone = 0, kStateAdded, kStateRemoved, kStateToTriggerRereg,
kStateRefreshed, kStateUnchanged
}
Public Member Functions
Error GetConfig (BackboneRouterConfig &aConfig) const
const Ip6::Prefix * GetDomainPrefix (void) const
uint16_t GetServer16 (void) const
Error GetServiceId (uint8_t &aServiceId) const
bool HasDomainPrefix (void) const
bool HasPrimary (void) const
bool IsDomainUnicast (const Ip6::Address &aAddress) const
Leader (Instance &aInstance)
void Reset (void)
void Update (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void LogBackboneRouterPrimary (State, const BackboneRouterConfig &) const
void LogDomainPrefix (DomainPrefixState, const Ip6::Prefix &) const
void UpdateBackboneRouterPrimary (void)
void UpdateDomainPrefixConfig (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
BackboneRouterConfig mConfig
Primary Backbone Router information.
Ip6::Prefix mDomainPrefix
Domain Prefix in the Thread network.
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements the basic Primary Backbone Router service operations.
Member Enumeration Documentation
State
enum State : uint8_t
Enumerator
kStateNone
Not exist (trigger Backbone Router register its service).
kStateAdded
Newly added.
kStateRemoved
Newly removed (trigger Backbone Router register its service).
kStateToTriggerRereg
Short address or sequence number changes (trigger re-registration). May also have ReregistrationDelay or MlrTimeout update.
kStateRefreshed
Only ReregistrationDelay or MlrTimeout changes.
kStateUnchanged
No change on Primary Backbone Router information (only for logging).
DomainPrefixState
enum DomainPrefixState : uint8_t
Enumerator
kDomainPrefixNone
Not available.
kDomainPrefixAdded
Added.
kDomainPrefixRemoved
Removed.
kDomainPrefixRefreshed
Changed.
kDomainPrefixUnchanged
Nothing changed.
Constructor & Destructor Documentation
Leader()
Leader (Instance & aInstance) explicit
This constructor initializes the Leader.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Leader::Reset().
Member Function Documentation
Reset()
void Reset (void)
This method resets the cached Primary Backbone Router.
References ot::Mac::kShortAddrInvalid, Leader::mConfig, Leader::mDomainPrefix, otBackboneRouterConfig::mServer16, and Prefix::SetLength().
Referenced by Leader::Leader().
Update()
void Update (void)
This method updates the cached Primary Backbone Router if any when new network data is available.
References Leader::UpdateBackboneRouterPrimary(), and Leader::UpdateDomainPrefixConfig().
GetConfig()
Error GetConfig (BackboneRouterConfig & aConfig) const
This method gets the Primary Backbone Router in the Thread Network.
Parameters
[out] aConfig The Primary Backbone Router information.
Return values
kErrorNone Successfully got the Primary Backbone Router information.
kErrorNotFound No Backbone Router in the Thread Network.
References Leader::HasPrimary(), ot::kErrorNone, ot::kErrorNotFound, Leader::mConfig, and VerifyOrExit.
GetServiceId()
Error GetServiceId (uint8_t & aServiceId) const
This method gets the Backbone Router Service ID.
Parameters
[out] aServiceId The reference whether to put the Backbone Router Service ID.
Return values
kErrorNone Successfully got the Backbone Router Service ID.
kErrorNotFound Backbone Router service doesn't exist.
References String< kSize >::AsCString(), Leader::HasPrimary(), Leader::kDomainPrefixAdded, Leader::kDomainPrefixNone, Leader::kDomainPrefixRefreshed, Leader::kDomainPrefixRemoved, Leader::kDomainPrefixUnchanged, ot::kErrorNone, ot::kErrorNotFound, Leader::kStateAdded, Leader::kStateNone, Leader::kStateRefreshed, Leader::kStateRemoved, Leader::kStateToTriggerRereg, Leader::kStateUnchanged, Leader::LogBackboneRouterPrimary(), Leader::LogDomainPrefix(), LogInfo, otBackboneRouterConfig::mMlrTimeout, otBackboneRouterConfig::mReregistrationDelay, otBackboneRouterConfig::mSequenceNumber, otBackboneRouterConfig::mServer16, OT_UNUSED_VARIABLE, Prefix::ToString(), and VerifyOrExit.
GetServer16()
uint16_t GetServer16 (void) const inline
This method gets the short address of the Primary Backbone Router.
Returns
short address of Primary Backbone Router, or Mac::kShortAddrInvalid if no Primary Backbone Router.
References Leader::mConfig, and otBackboneRouterConfig::mServer16.
HasPrimary()
bool HasPrimary (void) const inline
This method indicates whether or not there is Primary Backbone Router.
Return values
TRUE If there is Primary Backbone Router.
FALSE If there is no Primary Backbone Router.
References ot::Mac::kShortAddrInvalid, Leader::mConfig, and otBackboneRouterConfig::mServer16.
Referenced by Leader::GetConfig(), and Leader::GetServiceId().
GetDomainPrefix()
const Ip6::Prefix* GetDomainPrefix (void) const inline
This method gets the Domain Prefix in the Thread Network.
Return values
A pointer to the Domain Prefix or nullptr if there is no Domain Prefix.
References Prefix::GetLength(), and Leader::mDomainPrefix.
HasDomainPrefix()
bool HasDomainPrefix (void) const inline
This method indicates whether or not the Domain Prefix is available in the Thread Network.
Return values
TRUE If there is Domain Prefix.
FALSE If there is no Domain Prefix.
References Prefix::GetLength(), Leader::IsDomainUnicast(), Leader::LogBackboneRouterPrimary(), Leader::LogDomainPrefix(), Leader::mDomainPrefix, Leader::UpdateBackboneRouterPrimary(), and Leader::UpdateDomainPrefixConfig().
Referenced by Leader::IsDomainUnicast().
IsDomainUnicast()
bool IsDomainUnicast (const Ip6::Address & aAddress) const
This method indicates whether or not the address is a Domain Unicast Address.
Parameters
[in] aAddress A reference to the address.
Return values
true aAddress is a Domain Unicast Address.
false aAddress is not a Domain Unicast Address.
References Leader::HasDomainPrefix(), Address::MatchesPrefix(), and Leader::mDomainPrefix.
Referenced by Leader::HasDomainPrefix().
UpdateBackboneRouterPrimary()
void UpdateBackboneRouterPrimary (void) private
References ot::Mle::kMlrTimeoutMax, ot::Mle::kMlrTimeoutMin, ot::Mac::kShortAddrInvalid, Leader::kStateAdded, Leader::kStateNone, Leader::kStateRefreshed, Leader::kStateRemoved, Leader::kStateToTriggerRereg, Leader::kStateUnchanged, Leader::LogBackboneRouterPrimary(), LogNote, Leader::mConfig, otBackboneRouterConfig::mMlrTimeout, otBackboneRouterConfig::mReregistrationDelay, otBackboneRouterConfig::mSequenceNumber, and otBackboneRouterConfig::mServer16.
Referenced by Leader::HasDomainPrefix(), and Leader::Update().
UpdateDomainPrefixConfig()
void UpdateDomainPrefixConfig (void) private
References Prefix::GetLength(), OnMeshPrefixConfig::GetPrefix(), Leader::kDomainPrefixAdded, Leader::kDomainPrefixNone, Leader::kDomainPrefixRefreshed, Leader::kDomainPrefixRemoved, Leader::kDomainPrefixUnchanged, ot::kErrorNone, ot::NetworkData::kIteratorInit, Leader::LogDomainPrefix(), Leader::mDomainPrefix, otBorderRouterConfig::mDp, otIp6Prefix::mLength, and Prefix::SetLength().
Referenced by Leader::HasDomainPrefix(), and Leader::Update().
LogBackboneRouterPrimary()
void LogBackboneRouterPrimary (State , const BackboneRouterConfig &) const inline private
Referenced by Leader::GetServiceId(), Leader::HasDomainPrefix(), and Leader::UpdateBackboneRouterPrimary().
LogDomainPrefix()
void LogDomainPrefix (DomainPrefixState , const Ip6::Prefix &) const inline private
Referenced by Leader::GetServiceId(), Leader::HasDomainPrefix(), and Leader::UpdateDomainPrefixConfig().
Field Documentation
mConfig
BackboneRouterConfig mConfig private
Primary Backbone Router information.
Referenced by Leader::GetConfig(), Leader::GetServer16(), Leader::HasPrimary(), Leader::Reset(), and Leader::UpdateBackboneRouterPrimary().
mDomainPrefix
Ip6::Prefix mDomainPrefix private
Domain Prefix in the Thread network.
Referenced by Leader::GetDomainPrefix(), Leader::HasDomainPrefix(), Leader::IsDomainUnicast(), Leader::Reset(), and Leader::UpdateDomainPrefixConfig().
The documentation for this class was generated from the following files:
bbr_leader.hpp
bbr_leader.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale