OpenThread: Neighbor Class Reference
Neighbor Class Reference
#include <topology.hpp>
Data Structures
class AddressMatcher
class Info
Public Types
enum State : uint8_t {
kStateInvalid, kStateRestored, kStateParentRequest, kStateParentResponse,
kStateChildIdRequest, kStateLinkRequest, kStateChildUpdateRequest, kStateValid
}
enum StateFilter : uint8_t {
kInStateValid, kInStateValidOrRestoring, kInStateChildIdRequest, kInStateValidOrAttaching,
kInStateInvalid, kInStateAnyExceptInvalid, kInStateAnyExceptValidOrRestoring, kInStateAny
}
Public Member Functions
void ClearExtAddress (void)
void GenerateChallenge (void)
const uint8_t * GetChallenge (void) const
uint8_t GetChallengeSize (void) const
Mle::DeviceMode GetDeviceMode (void) const
const Mac::ExtAddress & GetExtAddress (void) const
uint32_t GetKeySequence (void) const
TimeMilli GetLastHeard (void) const
uint32_t GetLinkAckFrameCounter (void) const
uint8_t GetLinkFailures (void) const
Mac::LinkFrameCounters & GetLinkFrameCounters (void)
const Mac::LinkFrameCounters & GetLinkFrameCounters (void) const
LinkQualityInfo & GetLinkInfo (void)
const LinkQualityInfo & GetLinkInfo (void) const
uint32_t GetMleFrameCounter (void) const
NetworkData::Type GetNetworkDataType (void) const
uint16_t GetRloc16 (void) const
uint8_t GetRouterId (void) const
State GetState (void) const
uint16_t GetVersion (void) const
void IncrementLinkFailures (void)
bool IsEnhancedKeepAliveSupported (void) const
bool IsFullThreadDevice (void) const
bool IsRxOnWhenIdle (void) const
bool IsStateChildIdRequest (void) const
bool IsStateInvalid (void) const
bool IsStateLinkRequest (void) const
bool IsStateParentResponse (void) const
bool IsStateRestored (void) const
bool IsStateRestoring (void) const
bool IsStateValid (void) const
bool IsStateValidOrAttaching (void) const
bool IsStateValidOrRestoring (void) const
bool IsThreadVersion1p1 (void) const
bool IsThreadVersion1p2OrHigher (void) const
bool IsThreadVersionCslCapable (void) const
bool Matches (const AddressMatcher &aMatcher) const
bool MatchesFilter (StateFilter aFilter) const
void ResetLinkFailures (void)
void SetDeviceMode (Mle::DeviceMode aMode)
void SetExtAddress (const Mac::ExtAddress &aAddress)
void SetKeySequence (uint32_t aKeySequence)
void SetLastHeard (TimeMilli aLastHeard)
void SetLinkAckFrameCounter (uint32_t aAckFrameCounter)
void SetMleFrameCounter (uint32_t aFrameCounter)
void SetRloc16 (uint16_t aRloc16)
void SetState (State aState)
void SetVersion (uint16_t aVersion)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Member Functions
static const char * StateToString (State aState)
Protected Member Functions
void Init (Instance &aInstance)
Protected Member Functions inherited from InstanceLocatorInit
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Private Types
enum : uint32_t { kLastRxFragmentTagTimeout = OPENTHREAD_CONFIG_MULTI_RADIO_FRAG_TAG_TIMEOUT }
Private Attributes
uint32_t mKeySequence
Current key sequence.
TimeMilli mLastHeard
Time when last heard.
uint8_t mLinkFailures
Consecutive link failure count.
LinkQualityInfo mLinkInfo
Link quality info (contains average RSS, link margin and link quality)
Mac::ExtAddress mMacAddr
The IEEE 802.15.4 Extended Address.
uint8_t mMode: 4
The MLE device mode.
uint16_t mRloc16
The RLOC16.
uint8_t mState: 4
The link state.
union {
struct {
uint8_t mChallenge [Mle::kMaxChallengeSize]
The challenge value.
} mPending
struct {
uint32_t mLinkAckFrameCounter
The Link Ack Frame Counter.
Mac::LinkFrameCounters mLinkFrameCounters
The Link Frame Counters.
uint32_t mMleFrameCounter
The MLE Frame Counter.
} mValid
} mValidPending
uint16_t mVersion
The MLE version.
Detailed Description
This class represents a Thread neighbor.
Member Enumeration Documentation
State
enum State : uint8_t
Neighbor link states.
Enumerator
kStateInvalid
Neighbor link is invalid.
kStateRestored
Neighbor is restored from non-volatile memory.
kStateParentRequest
Received an MLE Parent Request message.
kStateParentResponse
Received an MLE Parent Response message.
kStateChildIdRequest
Received an MLE Child ID Request message.
kStateLinkRequest
Sent an MLE Link Request message.
kStateChildUpdateRequest
Sent an MLE Child Update Request message (trying to restore the child)
kStateValid
Link is valid.
StateFilter
enum StateFilter : uint8_t
This enumeration defines state filters used for finding a neighbor or iterating through the child/neighbor table.
Each filter definition accepts a subset of State values.
Enumerator
kInStateValid
Accept neighbor only in kStateValid.
kInStateValidOrRestoring
Accept neighbor with IsStateValidOrRestoring() being true.
kInStateChildIdRequest
Accept neighbor only in Child:kStateChildIdRequest.
kInStateValidOrAttaching
Accept neighbor with IsStateValidOrAttaching() being true.
kInStateInvalid
Accept neighbor only in kStateInvalid.
kInStateAnyExceptInvalid
Accept neighbor in any state except kStateInvalid.
kInStateAnyExceptValidOrRestoring
Accept neighbor in any state except IsStateValidOrRestoring().
kInStateAny
Accept neighbor in any state.
anonymous enum
anonymous enum : uint32_t private
Enumerator
kLastRxFragmentTagTimeout
Frag tag timeout in msec.
Member Function Documentation
GetState()
State GetState (void) const inline
This method returns the current state.
Returns
The current state.
References Neighbor::mState.
Referenced by Neighbor::IsStateValidOrAttaching().
SetState()
void SetState (State aState) inline
This method sets the current state.
Parameters
[in] aState The state value.
References Neighbor::mState.
Referenced by Mle::BecomeDetached(), Mle::HandleAttachTimer(), Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Neighbor::Init(), Mle::Restore(), Mle::SendChildIdRequest(), and Mle::SetRole().
IsStateInvalid()
bool IsStateInvalid (void) const inline
This method indicates whether the neighbor is in the Invalid state.
Returns
TRUE if the neighbor is in the Invalid state, FALSE otherwise.
References Neighbor::kStateInvalid, and Neighbor::mState.
Referenced by Mle::HandleUdpReceive(), and Neighbor::MatchesFilter().
IsStateChildIdRequest()
bool IsStateChildIdRequest (void) const inline
This method indicates whether the neighbor is in the Child ID Request state.
Returns
TRUE if the neighbor is in the Child ID Request state, FALSE otherwise.
References Neighbor::kStateChildIdRequest, and Neighbor::mState.
Referenced by Neighbor::MatchesFilter().
IsStateLinkRequest()
bool IsStateLinkRequest (void) const inline
This method indicates whether the neighbor is in the Link Request state.
Returns
TRUE if the neighbor is in the Link Request state, FALSE otherwise.
References Neighbor::kStateLinkRequest, and Neighbor::mState.
IsStateParentResponse()
bool IsStateParentResponse (void) const inline
This method indicates whether the neighbor is in the Parent Response state.
Returns
TRUE if the neighbor is in the Parent Response state, FALSE otherwise.
References Neighbor::kStateParentResponse, and Neighbor::mState.
Referenced by Mle::HandleParentResponse(), and Mle::HasAcceptableParentCandidate().
IsStateRestoring()
bool IsStateRestoring (void) const inline
This method indicates whether the neighbor is being restored.
Returns
TRUE if the neighbor is being restored, FALSE otherwise.
References Neighbor::kStateChildUpdateRequest, Neighbor::kStateRestored, and Neighbor::mState.
Referenced by Neighbor::IsStateValidOrRestoring().
IsStateRestored()
bool IsStateRestored (void) const inline
This method indicates whether the neighbor is in the Restored state.
Returns
TRUE if the neighbor is in the Restored state, FALSE otherwise.
References Neighbor::kStateRestored, and Neighbor::mState.
IsStateValid()
bool IsStateValid (void) const inline
This method indicates whether the neighbor is valid (frame counters are synchronized).
Returns
TRUE if the neighbor is valid, FALSE otherwise.
References Neighbor::kStateValid, and Neighbor::mState.
Referenced by NeighborTable::FindNeighbor(), Mle::GetNextHop(), DataPollSender::GetParent(), Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleUdpReceive(), Neighbor::MatchesFilter(), Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), Mle::ReestablishLinkWithNeighbor(), Router::Info::SetFrom(), and Neighbor::StateToString().
IsStateValidOrRestoring()
bool IsStateValidOrRestoring (void) const inline
This method indicates whether the neighbor is in valid state or if it is being restored.
When in these states messages can be sent to and/or received from the neighbor.
Returns
TRUE if the neighbor is in valid, restored, or being restored states, FALSE otherwise.
References Neighbor::IsStateRestoring(), Neighbor::IsStateValidOrAttaching(), Neighbor::kStateValid, Neighbor::MatchesFilter(), and Neighbor::mState.
Referenced by DataPollSender::GetPollDestinationAddress(), Neighbor::MatchesFilter(), and Mle::SendChildUpdateRequest().
IsStateValidOrAttaching()
bool IsStateValidOrAttaching (void) const
This method indicates if the neighbor state is valid, attaching, or restored.
The states kStateRestored, kStateChildIdRequest, kStateChildUpdateRequest, kStateValid, and kStateLinkRequest are considered as valid, attaching, or restored.
Returns
TRUE if the neighbor state is valid, attaching, or restored, FALSE otherwise.
References Neighbor::GetState(), Neighbor::kStateChildIdRequest, Neighbor::kStateChildUpdateRequest, Neighbor::kStateInvalid, Neighbor::kStateLinkRequest, Neighbor::kStateParentRequest, Neighbor::kStateParentResponse, Neighbor::kStateRestored, and Neighbor::kStateValid.
Referenced by Neighbor::IsStateValidOrRestoring(), and Neighbor::MatchesFilter().
MatchesFilter()
bool MatchesFilter (StateFilter aFilter) const
This method indicates whether neighbor state matches a given state filter.
Parameters
[in] aFilter A state filter (StateFilter enumeration) to match against.
Returns
TRUE if the neighbor state matches the filter, FALSE otherwise.
References TimerMilli::GetNow(), Neighbor::IsStateChildIdRequest(), Neighbor::IsStateInvalid(), Neighbor::IsStateValid(), Neighbor::IsStateValidOrAttaching(), Neighbor::IsStateValidOrRestoring(), Neighbor::kInStateAny, Neighbor::kInStateAnyExceptInvalid, Neighbor::kInStateAnyExceptValidOrRestoring, Neighbor::kInStateChildIdRequest, Neighbor::kInStateInvalid, Neighbor::kInStateValid, Neighbor::kInStateValidOrAttaching, Neighbor::kInStateValidOrRestoring, and Neighbor::kLastRxFragmentTagTimeout.
Referenced by Neighbor::IsStateValidOrRestoring(), and Neighbor::AddressMatcher::Matches().
Matches()
bool Matches (const AddressMatcher & aMatcher) const inline
This method indicates whether neighbor matches a given AddressMatcher.
Parameters
[in] aMatcher An AddressMatcher to match against.
Returns
TRUE if the neighbor matches the address and state filter of aMatcher, FALSE otherwise.
References Neighbor::AddressMatcher::Matches().
Referenced by NeighborTable::FindParent().
GetDeviceMode()
Mle::DeviceMode GetDeviceMode (void) const inline
This method gets the device mode flags.
Returns
The device mode flags.
References Neighbor::mMode.
Referenced by Neighbor::GetNetworkDataType(), Neighbor::IsFullThreadDevice(), Neighbor::IsRxOnWhenIdle(), and Neighbor::StateToString().
SetDeviceMode()
void SetDeviceMode (Mle::DeviceMode aMode) inline
This method sets the device mode flags.
Parameters
[in] aMode The device mode flags.
References DeviceMode::Get(), and Neighbor::mMode.
Referenced by Mle::HandleParentResponse(), Mle::Restore(), and Neighbor::StateToString().
IsRxOnWhenIdle()
bool IsRxOnWhenIdle (void) const inline
This method indicates whether or not the device is rx-on-when-idle.
Returns
TRUE if rx-on-when-idle, FALSE otherwise.
References Neighbor::GetDeviceMode(), and DeviceMode::IsRxOnWhenIdle().
Referenced by Neighbor::IsThreadVersionCslCapable(), and Neighbor::Info::SetFrom().
IsFullThreadDevice()
bool IsFullThreadDevice (void) const inline
This method indicates whether or not the device is a Full Thread Device.
Returns
TRUE if a Full Thread Device, FALSE otherwise.
References Neighbor::GetDeviceMode(), and DeviceMode::IsFullThreadDevice().
Referenced by Neighbor::Info::SetFrom().
GetNetworkDataType()
NetworkData::Type GetNetworkDataType (void) const inline
This method gets the Network Data type (full set or stable subset) that the device requests.
Returns
The Network Data type.
References Neighbor::GetDeviceMode(), and DeviceMode::GetNetworkDataType().
Referenced by Neighbor::Info::SetFrom().
ClearExtAddress()
void ClearExtAddress (void) inline
This method sets all bytes of the Extended Address to zero.
References Neighbor::mMacAddr.
GetExtAddress()
const Mac::ExtAddress& GetExtAddress (void) const inline
This method returns the Extended Address.
Returns
A reference to the Extended Address.
References Neighbor::mMacAddr.
Referenced by DataPollSender::GetPollDestinationAddress(), Mle::HandleMessageTransmissionTimer(), Mle::HandleParentResponse(), Neighbor::AddressMatcher::Matches(), Mac::ProcessEnhAckSecurity(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Neighbor::Info::SetFrom(), Router::Info::SetFrom(), Mle::Store(), and MeshForwarder::UpdateNeighborLinkFailures().
SetExtAddress()
void SetExtAddress (const Mac::ExtAddress & aAddress) inline
This method sets the Extended Address.
Parameters
[in] aAddress The Extended Address value to set.
References Neighbor::mMacAddr.
Referenced by Mle::HandleParentResponse(), and Mle::Restore().
GetKeySequence()
uint32_t GetKeySequence (void) const inline
This method gets the key sequence value.
Returns
The key sequence value.
References Neighbor::mKeySequence.
Referenced by Mle::HandleUdpReceive(), and Mac::ProcessReceiveSecurity().
SetKeySequence()
void SetKeySequence (uint32_t aKeySequence) inline
This method sets the key sequence value.
Parameters
[in] aKeySequence The key sequence value.
References Neighbor::mKeySequence.
Referenced by Mle::HandleParentResponse(), Mle::HandleUdpReceive(), Mac::ProcessReceiveSecurity(), and KeyManager::ResetFrameCounters().
GetLastHeard()
TimeMilli GetLastHeard (void) const inline
This method returns the last heard time.
Returns
The last heard time.
References Neighbor::mLastHeard.
Referenced by Neighbor::Info::SetFrom(), and Router::Info::SetFrom().
SetLastHeard()
void SetLastHeard (TimeMilli aLastHeard) inline
This method sets the last heard time.
Parameters
[in] aLastHeard The last heard time.
References Neighbor::mLastHeard.
Referenced by Mle::HandleAdvertisement().
GetLinkFrameCounters() [1/2]
Mac::LinkFrameCounters& GetLinkFrameCounters (void) inline
This method gets the link frame counters.
Returns
A reference to Mac::LinkFrameCounters containing link frame counter for all supported radio links.
References Neighbor::mValidPending.
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Mle::HandleUdpReceive(), Mac::ProcessReceiveSecurity(), KeyManager::ResetFrameCounters(), and Neighbor::Info::SetFrom().
GetLinkFrameCounters() [2/2]
const Mac::LinkFrameCounters& GetLinkFrameCounters (void) const inline
This method gets the link frame counters.
Returns
A reference to Mac::LinkFrameCounters containing link frame counter for all supported radio links.
References Neighbor::mValidPending.
GetLinkAckFrameCounter()
uint32_t GetLinkAckFrameCounter (void) const inline
This method gets the link ACK frame counter value.
Returns
The link ACK frame counter value.
References Neighbor::mValidPending.
Referenced by Mac::ProcessEnhAckSecurity(), and Mac::ProcessReceiveSecurity().
SetLinkAckFrameCounter()
void SetLinkAckFrameCounter (uint32_t aAckFrameCounter) inline
This method sets the link ACK frame counter value.
Parameters
[in] aAckFrameCounter The link ACK frame counter value.
References Neighbor::mValidPending, and OT_UNUSED_VARIABLE.
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Mle::HandleUdpReceive(), Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), and KeyManager::ResetFrameCounters().
GetMleFrameCounter()
uint32_t GetMleFrameCounter (void) const inline
This method gets the MLE frame counter value.
Returns
The MLE frame counter value.
References Neighbor::mValidPending.
Referenced by Mle::HandleUdpReceive(), and Neighbor::Info::SetFrom().
SetMleFrameCounter()
void SetMleFrameCounter (uint32_t aFrameCounter) inline
This method sets the MLE frame counter value.
Parameters
[in] aFrameCounter The MLE frame counter value.
References Neighbor::mValidPending.
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Mle::HandleUdpReceive(), Mac::ProcessReceiveSecurity(), and KeyManager::ResetFrameCounters().
GetRloc16()
uint16_t GetRloc16 (void) const inline
This method gets the RLOC16 value.
Returns
The RLOC16 value.
References Neighbor::mRloc16.
Referenced by MeshForwarder::CalcFrameVersion(), Mle::CheckReachability(), Mle::GetNextHop(), DataPollSender::GetPollDestinationAddress(), Mle::HandleAdvertisement(), Mle::HandleChildUpdateRequest(), Mle::HandleUdpReceive(), Mle::IsBetterParent(), Neighbor::AddressMatcher::Matches(), Mle::ReestablishLinkWithNeighbor(), Mle::Restore(), Neighbor::Info::SetFrom(), Router::Info::SetFrom(), Mle::SetStateChild(), and MeshForwarder::UpdateNeighborLinkFailures().
GetRouterId()
uint8_t GetRouterId (void) const inline
This method gets the Router ID value.
Returns
The Router ID value.
References ot::Mle::kRouterIdOffset, and Neighbor::mRloc16.
SetRloc16()
void SetRloc16 (uint16_t aRloc16) inline
This method sets the RLOC16 value.
Parameters
[in] aRloc16 The RLOC16 value.
References SerialNumber::IsGreater(), and Neighbor::mRloc16.
Referenced by Mle::HandleChildIdResponse(), Mle::HandleParentResponse(), and Mle::Restore().
IsThreadVersion1p1()
bool IsThreadVersion1p1 (void) const inline
This method indicates whether or not it is Thread 1.1.
Returns
TRUE if neighbors is Thread 1.1, FALSE otherwise.
References Neighbor::kStateInvalid, ot::kThreadVersion1p1, Neighbor::mState, and Neighbor::mVersion.
Referenced by Mle::HandleNotifierEvents().
IsThreadVersion1p2OrHigher()
bool IsThreadVersion1p2OrHigher (void) const inline
This method indicates whether or not neighbor is Thread 1.2 or higher..
Returns
TRUE if neighbor is Thread 1.2 or higher, FALSE otherwise.
References Neighbor::kStateInvalid, ot::kThreadVersion1p2, Neighbor::mState, and Neighbor::mVersion.
Referenced by Neighbor::IsThreadVersionCslCapable().
IsThreadVersionCslCapable()
bool IsThreadVersionCslCapable (void) const inline
This method indicates whether Thread version supports CSL.
Returns
TRUE if CSL is supported, FALSE otherwise.
References Neighbor::IsRxOnWhenIdle(), and Neighbor::IsThreadVersion1p2OrHigher().
IsEnhancedKeepAliveSupported()
bool IsEnhancedKeepAliveSupported (void) const inline
This method indicates whether Enhanced Keep-Alive is supported or not.
Returns
TRUE if Enhanced Keep-Alive is supported, FALSE otherwise.
References Neighbor::kStateInvalid, Neighbor::mState, Neighbor::mVersion, and OT_THREAD_VERSION_1_2.
GetVersion()
uint16_t GetVersion (void) const inline
This method gets the device MLE version.
References Neighbor::mVersion.
Referenced by Mle::IsBetterParent(), Router::Info::SetFrom(), and Mle::Store().
SetVersion()
void SetVersion (uint16_t aVersion) inline
This method sets the device MLE version.
Parameters
[in] aVersion The device MLE version.
References Neighbor::mVersion.
Referenced by Mle::HandleParentResponse(), and Mle::Restore().
GetLinkFailures()
uint8_t GetLinkFailures (void) const inline
This method gets the number of consecutive link failures.
Returns
The number of consecutive link failures.
References Neighbor::mLinkFailures.
Referenced by MeshForwarder::UpdateNeighborLinkFailures().
IncrementLinkFailures()
void IncrementLinkFailures (void) inline
This method increments the number of consecutive link failures.
References Neighbor::mLinkFailures.
Referenced by MeshForwarder::UpdateNeighborLinkFailures().
ResetLinkFailures()
void ResetLinkFailures (void) inline
This method resets the number of consecutive link failures to zero.
References Neighbor::mLinkFailures.
Referenced by Mle::HandleParentResponse(), and MeshForwarder::UpdateNeighborLinkFailures().
GetLinkInfo() [1/2]
LinkQualityInfo& GetLinkInfo (void) inline
This method returns the LinkQualityInfo object.
Returns
The LinkQualityInfo object.
References Neighbor::mLinkInfo.
Referenced by Mle::CheckReachability(), Mle::HandleParentResponse(), Mle::HasAcceptableParentCandidate(), Mle::IsBetterParent(), Neighbor::Info::SetFrom(), Router::Info::SetFrom(), and MeshForwarder::UpdateSendMessage().
GetLinkInfo() [2/2]
const LinkQualityInfo& GetLinkInfo (void) const inline
This method returns the LinkQualityInfo object.
Returns
The LinkQualityInfo object.
References Neighbor::GenerateChallenge(), and Neighbor::mLinkInfo.
GenerateChallenge()
void GenerateChallenge (void)
This method generates a new challenge value for MLE Link Request/Response exchanges.
References ot::Random::Crypto::FillBuffer(), IgnoreError(), and Neighbor::mValidPending.
Referenced by Neighbor::GetLinkInfo().
GetChallenge()
const uint8_t* GetChallenge (void) const inline
This method returns the current challenge value for MLE Link Request/Response exchanges.
Returns
The current challenge value.
References Neighbor::mValidPending.
GetChallengeSize()
uint8_t GetChallengeSize (void) const inline
This method returns the size (bytes) of the challenge value for MLE Link Request/Response exchanges.
Returns
The size (bytes) of the challenge value for MLE Link Request/Response exchanges.
References Neighbor::Init(), Neighbor::mValidPending, and Neighbor::StateToString().
StateToString()
const char * StateToString (State aState) static
This method converts a given State to a human-readable string.
Parameters
[in] aState A neighbor state.
Returns
A string representation of given state.
References Mle::ChildIdFromRloc16(), ot::ClampToUint8(), ExitNow, ot::Random::Crypto::FillBuffer(), ot::GetArrayEnd(), Neighbor::GetDeviceMode(), Address::GetIid(), InstanceLocator::GetInstance(), TimerMilli::GetNow(), IgnoreError(), Neighbor::Init(), Neighbor::IsStateValid(), Address::IsUnspecified(), NeighborTable::kChildModeChanged, ot::kErrorAlready, ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNotFound, ot::NetworkData::kFullSet, Neighbor::kStateChildIdRequest, Neighbor::kStateChildUpdateRequest, Neighbor::kStateInvalid, Neighbor::kStateLinkRequest, Neighbor::kStateParentRequest, Neighbor::kStateParentResponse, Neighbor::kStateRestored, Neighbor::kStateValid, Address::kTypeMulticastLargerThanRealmLocal, Address::MatchesFilter(), Neighbor::AddressMatcher::mExtAddress, Neighbor::mRloc16, Time::MsecToSec(), Neighbor::mVersion, OT_ASSERT, Neighbor::SetDeviceMode(), Address::SetIid(), Address::SetPrefix(), SuccessOrExit, and VerifyOrExit.
Referenced by Neighbor::GetChallengeSize().
Init()
void Init (Instance & aInstance) protected
This method initializes the Neighbor object.
Parameters
[in] aInstance A reference to OpenThread instance.
References InstanceLocatorInit::Init(), LinkQualityInfo::Init(), Neighbor::kStateInvalid, Neighbor::mLinkInfo, and Neighbor::SetState().
Referenced by Router::Clear(), Parent::Clear(), Neighbor::GetChallengeSize(), Router::Init(), Parent::Init(), and Neighbor::StateToString().
Field Documentation
mMacAddr
Mac::ExtAddress mMacAddr private
The IEEE 802.15.4 Extended Address.
Referenced by Neighbor::ClearExtAddress(), Neighbor::GetExtAddress(), and Neighbor::SetExtAddress().
mLastHeard
TimeMilli mLastHeard private
Time when last heard.
Referenced by Neighbor::GetLastHeard(), and Neighbor::SetLastHeard().
mLinkFrameCounters
Mac::LinkFrameCounters mLinkFrameCounters
The Link Frame Counters.
mMleFrameCounter
uint32_t mMleFrameCounter
The MLE Frame Counter.
Referenced by Neighbor::Info::SetFrom().
mLinkAckFrameCounter
uint32_t mLinkAckFrameCounter
The Link Ack Frame Counter.
mValid
struct { ... } mValid
mChallenge
uint8_t mChallenge[Mle::kMaxChallengeSize]
The challenge value.
mPending
struct { ... } mPending
mValidPending
union { ... } mValidPending
Referenced by Neighbor::GenerateChallenge(), Neighbor::GetChallenge(), Neighbor::GetChallengeSize(), Neighbor::GetLinkAckFrameCounter(), Neighbor::GetLinkFrameCounters(), Neighbor::GetMleFrameCounter(), Neighbor::SetLinkAckFrameCounter(), and Neighbor::SetMleFrameCounter().
mKeySequence
uint32_t mKeySequence private
Current key sequence.
Referenced by Neighbor::GetKeySequence(), and Neighbor::SetKeySequence().
mRloc16
uint16_t mRloc16 private
The RLOC16.
Referenced by Neighbor::GetRloc16(), Neighbor::GetRouterId(), Neighbor::Info::SetFrom(), Router::Info::SetFrom(), Neighbor::SetRloc16(), and Neighbor::StateToString().
mState
uint8_t mState private
The link state.
Referenced by Neighbor::GetState(), Neighbor::IsEnhancedKeepAliveSupported(), Neighbor::IsStateChildIdRequest(), Neighbor::IsStateInvalid(), Neighbor::IsStateLinkRequest(), Neighbor::IsStateParentResponse(), Neighbor::IsStateRestored(), Neighbor::IsStateRestoring(), Neighbor::IsStateValid(), Neighbor::IsStateValidOrRestoring(), Neighbor::IsThreadVersion1p1(), Neighbor::IsThreadVersion1p2OrHigher(), and Neighbor::SetState().
mMode
uint8_t mMode private
The MLE device mode.
Referenced by Neighbor::GetDeviceMode(), and Neighbor::SetDeviceMode().
mLinkFailures
uint8_t mLinkFailures private
Consecutive link failure count.
Referenced by Neighbor::GetLinkFailures(), Neighbor::IncrementLinkFailures(), and Neighbor::ResetLinkFailures().
mVersion
uint16_t mVersion private
The MLE version.
Referenced by Neighbor::GetVersion(), Neighbor::IsEnhancedKeepAliveSupported(), Neighbor::IsThreadVersion1p1(), Neighbor::IsThreadVersion1p2OrHigher(), Router::Info::SetFrom(), Neighbor::SetVersion(), and Neighbor::StateToString().
mLinkInfo
LinkQualityInfo mLinkInfo private
Link quality info (contains average RSS, link margin and link quality)
Referenced by Neighbor::GetLinkInfo(), and Neighbor::Init().
The documentation for this class was generated from the following files:
topology.hpp
topology.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale