OpenThread: FragmentHeader Class Reference
FragmentHeader Class Reference
Core-6lowpan
#include <lowpan.hpp>
Data Structures
class FirstFrag
class NextFrag
Public Member Functions
uint16_t GetDatagramOffset (void) const
uint16_t GetDatagramSize (void) const
uint16_t GetDatagramTag (void) const
Error ParseFrom (FrameData &aFrameData)
Error ParseFrom (const Message &aMessage, uint16_t aOffset, uint16_t &aHeaderLength)
Static Public Member Functions
static bool IsFragmentHeader (const FrameData &aFrameData)
Data Fields
OT_TOOL_PACKED_BEGIN class ot::Lowpan::FragmentHeader::FirstFrag OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::Lowpan::FragmentHeader::NextFrag OT_TOOL_PACKED_END
Private Member Functions
Error ParseFrom (const uint8_t *aFrame, uint16_t aFrameLength, uint16_t &aHeaderLength)
Static Private Member Functions
static bool IsFragmentHeader (const uint8_t *aFrame, uint16_t aFrameLength)
Private Attributes
uint16_t mOffset
uint16_t mSize
uint16_t mTag
Static Private Attributes
static constexpr uint8_t kDispatch = 0xc0
static constexpr uint8_t kDispatchMask = 0xd8
static constexpr uint8_t kOffsetFlag = 1 << 5
static constexpr uint8_t kOffsetIndex = 4
static constexpr uint16_t kOffsetMask = 0xfff8
static constexpr uint8_t kSizeIndex = 0
static constexpr uint16_t kSizeMask = 0x7ff
static constexpr uint8_t kTagIndex = 2
Detailed Description
This class implements Fragment Header generation and parsing.
Member Function Documentation
IsFragmentHeader() [1/2]
bool IsFragmentHeader (const FrameData & aFrameData) static
This static method indicates whether or not the header (in a given frame) is a Fragment Header.
Note
This method checks whether the frame has the minimum required length and that the first byte in header (dispatch byte) matches the Fragment Header dispatch value. It does not fully parse and validate the Fragment Header. ParseFrom() method can be used to fully parse and validate the header.
Parameters
[in] aFrameData The frame data.
Return values
TRUE If the header matches the Fragment Header dispatch value.
FALSE If the header does not match the Fragment Header dispatch value.
References Data< kDataLengthType >::GetBytes(), and Data< kDataLengthType >::GetLength().
Referenced by MeshForwarder::HandleReceivedFrame().
ParseFrom() [1/3]
Error ParseFrom (FrameData & aFrameData)
This method parses the Fragment Header from a given frame data.
If the Fragment Header is parsed successfully the aFrameData is updated to skip over the parsed header bytes.
Parameters
[in,out] aFrameData The frame data to parse from.
Return values
kErrorNone Fragment Header parsed successfully. aFrameData is updated to skip over parsed header.
kErrorParse Fragment header could not be parsed.
References Data< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), FrameData::SkipOver(), and SuccessOrExit.
Referenced by Headers::DecompressFrom(), MeshForwarder::HandleFragment(), and MeshForwarder::ResumeMessageTransmissions().
ParseFrom() [2/3]
Error ParseFrom (const Message & aMessage, uint16_t aOffset, uint16_t & aHeaderLength)
This method parses the Fragment Header from a message.
Parameters
[in] aMessage The message to read from.
[in] aOffset The offset within the message to start reading from.
[out] aHeaderLength A reference to a variable to output the parsed header length (on success).
Return values
kErrorNone Fragment Header parsed successfully.
kErrorParse Fragment header could not be parsed from aFrame.
References Message::ReadBytes().
GetDatagramSize()
uint16_t GetDatagramSize (void) const inline
This method returns the Datagram Size value.
Returns
The Datagram Size value.
Referenced by MeshForwarder::CalcFrameVersion(), MeshForwarder::HandleFragment(), and MeshForwarder::ResumeMessageTransmissions().
GetDatagramTag()
uint16_t GetDatagramTag (void) const inline
This method returns the Datagram Tag value.
Returns
The Datagram Tag value.
Referenced by MeshForwarder::CalcFrameVersion(), MeshForwarder::HandleFragment(), and MeshForwarder::ResumeMessageTransmissions().
GetDatagramOffset()
uint16_t GetDatagramOffset (void) const inline
This method returns the Datagram Offset value.
The returned offset value is always multiple of 8.
Returns
The Datagram Offset value (multiple of 8).
Referenced by MeshForwarder::CalcFrameVersion(), Headers::DecompressFrom(), MeshForwarder::HandleFragment(), and MeshForwarder::ResumeMessageTransmissions().
IsFragmentHeader() [2/2]
bool IsFragmentHeader (const uint8_t * aFrame, uint16_t aFrameLength) static private
ParseFrom() [3/3]
Error ParseFrom (const uint8_t * aFrame, uint16_t aFrameLength, uint16_t & aHeaderLength) private
References ot::kErrorNone, ot::kErrorParse, ot::Encoding::BigEndian::ReadUint16(), and VerifyOrExit.
Field Documentation
OT_TOOL_PACKED_END [1/2]
OT_TOOL_PACKED_BEGIN class ot::Lowpan::FragmentHeader::FirstFrag OT_TOOL_PACKED_END
OT_TOOL_PACKED_END [2/2]
OT_TOOL_PACKED_BEGIN class ot::Lowpan::FragmentHeader::NextFrag OT_TOOL_PACKED_END
kDispatch
constexpr uint8_t kDispatch = 0xc0 static private
kDispatchMask
constexpr uint8_t kDispatchMask = 0xd8 static private
kOffsetFlag
constexpr uint8_t kOffsetFlag = 1 << 5 static private
kSizeMask
constexpr uint16_t kSizeMask = 0x7ff static private
kOffsetMask
constexpr uint16_t kOffsetMask = 0xfff8 static private
kSizeIndex
constexpr uint8_t kSizeIndex = 0 static private
kTagIndex
constexpr uint8_t kTagIndex = 2 static private
kOffsetIndex
constexpr uint8_t kOffsetIndex = 4 static private
mSize
uint16_t mSize private
mTag
uint16_t mTag private
mOffset
uint16_t mOffset private
The documentation for this class was generated from the following files:
lowpan.hpp
lowpan.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale