OpenThread: ChannelMaskEntryBase Class Reference
ChannelMaskEntryBase Class Reference
#include <meshcop_tlvs.hpp>
Public Member Functions
void ClearChannel (uint8_t aChannel)
uint8_t GetChannelPage (void) const
uint16_t GetEntrySize (void) const
uint8_t GetMaskLength (void) const
const ChannelMaskEntryBase * GetNext (void) const
ChannelMaskEntryBase * GetNext (void)
bool IsChannelSet (uint8_t aChannel) const
void SetChannel (uint8_t aChannel)
void SetChannelPage (uint8_t aChannelPage)
void SetMaskLength (uint8_t aMaskLength)
Private Attributes
uint8_t mChannelPage
uint8_t mMaskLength
Detailed Description
This class implements Channel Mask Entry generation and parsing.
Member Function Documentation
GetChannelPage()
uint8_t GetChannelPage (void) const inline
This method gets the ChannelPage value.
Returns
The ChannelPage value.
Referenced by ChannelMaskTlv::GetChannelMask(), and ChannelMaskBaseTlv::IsValid().
SetChannelPage()
void SetChannelPage (uint8_t aChannelPage) inline
This method sets the ChannelPage value.
Parameters
[in] aChannelPage The ChannelPage value.
Referenced by ChannelMaskTlv::SetChannelMask().
GetMaskLength()
uint8_t GetMaskLength (void) const inline
This method gets the MaskLength value.
Returns
The MaskLength value.
SetMaskLength()
void SetMaskLength (uint8_t aMaskLength) inline
This method sets the MaskLength value.
Parameters
[in] aMaskLength The MaskLength value.
GetEntrySize()
uint16_t GetEntrySize (void) const inline
This method returns the total size of this Channel Mask Entry including the mask.
Returns
The total size of this entry (number of bytes).
Referenced by ChannelMaskTlv::GetChannelMask(), and ChannelMaskBaseTlv::GetFirstEntry().
ClearChannel()
void ClearChannel (uint8_t aChannel) inline
This method clears the bit corresponding to aChannel in ChannelMask.
Parameters
[in] aChannel The channel in ChannelMask to clear.
SetChannel()
void SetChannel (uint8_t aChannel) inline
This method sets the bit corresponding to aChannel in ChannelMask.
Parameters
[in] aChannel The channel in ChannelMask to set.
IsChannelSet()
bool IsChannelSet (uint8_t aChannel) const inline
This method indicates whether or not the bit corresponding to aChannel in ChannelMask is set.
Parameters
[in] aChannel The channel in ChannelMask to get.
GetNext() [1/2]
const ChannelMaskEntryBase* GetNext (void) const inline
This method gets the next Channel Mask Entry in a Channel Mask TLV.
Returns
A pointer to next Channel Mask Entry.
Referenced by ChannelMaskTlv::GetChannelMask(), ChannelMaskBaseTlv::IsValid(), and ChannelMaskTlv::SetChannelMask().
GetNext() [2/2]
ChannelMaskEntryBase* GetNext (void) inline
This method gets the next Channel Mask Entry in a Channel Mask TLV.
Returns
A pointer to next Channel Mask Entry.
References ot::AsConst(), ot::AsNonConst(), and ChannelMaskEntryBase::GetNext().
Referenced by ChannelMaskEntryBase::GetNext().
Field Documentation
mChannelPage
uint8_t mChannelPage private
mMaskLength
uint8_t mMaskLength private
The documentation for this class was generated from the following file:
meshcop_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale