OpenThread: Events Class Reference
Events Class Reference
Core-notifier
#include <notifier.hpp>
Public Types
typedef otChangedFlags Flags
Public Member Functions
void Add (Event aEvent)
void Clear (void)
bool Contains (Event aEvent) const
bool ContainsAll (Flags aEvents) const
bool ContainsAny (Flags aEvents) const
Events (void)
Flags GetAsFlags (void) const
bool IsEmpty (void) const
Private Attributes
Flags mEventFlags
Detailed Description
This type represents a list of events.
Member Typedef Documentation
Flags
typedef otChangedFlags Flags
This type represents a bit-field indicating a list of events (with values from Event)
Constructor & Destructor Documentation
Events()
Events (void) inline
This constructor initializes the Events list (as empty).
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the Events list.
References Events::mEventFlags.
Referenced by Notifier::EmitEvents().
Contains()
bool Contains (Event aEvent) const inline
This method indicates whether the Events list contains a given event.
Parameters
[in] aEvent The event to check.
Returns
TRUE if the list contains the aEvent, FALSE otherwise.
References Events::mEventFlags.
Referenced by EnergyScanServer::HandleNotifierEvents(), Mle::HandleNotifierEvents(), and AnnounceSenderBase::HandleTimer().
ContainsAny()
bool ContainsAny (Flags aEvents) const inline
This method indicates whether the Events list contains any of a given set of events.
Parameters
[in] aEvents The events set to check (must be a collection of Event constants combined using |).
Returns
TRUE if the list contains any of the aEvents set, FALSE otherwise.
References Events::mEventFlags.
Referenced by Mle::HandleNotifierEvents().
ContainsAll()
bool ContainsAll (Flags aEvents) const inline
This method indicates whether the Events list contains all of a given set of events.
Parameters
[in] aEvents The events set to check (must be collection of Event constants combined using |).
Returns
TRUE if the list contains all of the aEvents set, FALSE otherwise.
References Events::mEventFlags.
Add()
void Add (Event aEvent) inline
This method adds a given event to the Events list.
Parameters
[in] aEvent The event to add.
References Events::mEventFlags.
Referenced by Notifier::Signal().
IsEmpty()
bool IsEmpty (void) const inline
This method indicates whether the Events list is empty.
Returns
TRUE if the list is empty, FALSE otherwise.
References Events::mEventFlags.
Referenced by Notifier::EmitEvents().
GetAsFlags()
Flags GetAsFlags (void) const inline
This method gets the Events list as bit-field Flags value.
Returns
The list as bit-field Flags value.
References Events::mEventFlags.
Referenced by Notifier::EmitEvents().
Field Documentation
mEventFlags
Flags mEventFlags private
Referenced by Events::Add(), Events::Clear(), Events::Contains(), Events::ContainsAll(), Events::ContainsAny(), Events::GetAsFlags(), and Events::IsEmpty().
The documentation for this class was generated from the following file:
notifier.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale