OpenThread: JoinerPskd Class Reference
JoinerPskd Class Reference
#include <meshcop.hpp>
Public Member Functions
const char * GetAsCString (void) const
uint8_t GetLength (void) const
bool IsValid (void) const
bool operator== (const JoinerPskd &aOther) const
Error SetFrom (const char *aPskdString)
Public Member Functions inherited from Clearable< JoinerPskd >
void Clear (void)
Public Member Functions inherited from Unequatable< JoinerPskd >
bool operator!= (const JoinerPskd &aOther) const
Static Public Member Functions
static bool IsPskdValid (const char *aPskdString)
Static Public Attributes
static constexpr uint8_t kMaxLength = OT_JOINER_MAX_PSKD_LENGTH
Max PSKd string length (excludes null char)
static constexpr uint8_t kMinLength = 6
Min PSKd string length (excludes null char)
Additional Inherited Members
Data Fields inherited from otJoinerPskd
char m8 [OT_JOINER_MAX_PSKD_LENGTH+1]
Char string array (must be null terminated - +1 is for null char).
Detailed Description
This type represents a Joiner PSKd.
Member Function Documentation
IsValid()
bool IsValid (void) const inline
This method indicates whether the PSKd if well-formed and valid.
Per Thread specification, a Joining Device Credential is encoded as uppercase alphanumeric characters (base32-thread: 0-9, A-Z excluding I, O, Q, and Z for readability) with a minimum length of 6 such characters and a maximum length of 32 such characters.
Returns
TRUE if the PSKd is valid, FALSE otherwise.
References JoinerPskd::IsPskdValid(), otJoinerPskd::m8, and JoinerPskd::SetFrom().
Referenced by JoinerDiscerner::CopyTo(), JoinerDiscerner::Matches(), and JoinerDiscerner::operator==().
SetFrom()
Error SetFrom (const char * aPskdString)
This method sets the joiner PSKd from a given C string.
Parameters
[in] aPskdString A pointer to the PSKd C string array.
Return values
kErrorNone The PSKd was updated successfully.
kErrorInvalidArgs The given PSKd C string is not valid.
References Clearable< JoinerPskd >::Clear(), JoinerPskd::IsPskdValid(), ot::kErrorInvalidArgs, ot::kErrorNone, otJoinerPskd::m8, ot::StringLength(), and VerifyOrExit.
Referenced by JoinerPskd::IsValid().
GetAsCString()
const char* GetAsCString (void) const inline
This method gets the PSKd as a null terminated C string.
This method must be used after the PSKd is validated, otherwise its behavior is undefined.
Returns
The PSKd as a C string.
References otJoinerPskd::m8.
GetLength()
uint8_t GetLength (void) const inline
This method gets the PSKd string length.
This method must be used after the PSKd is validated, otherwise its behavior is undefined.
Returns
The PSKd string length.
References JoinerPskd::IsPskdValid(), otJoinerPskd::m8, JoinerPskd::operator==(), and ot::StringLength().
operator==()
bool operator== (const JoinerPskd & aOther) const
This method overloads operator == to evaluate whether or not two PSKds are equal.
Parameters
[in] aOther The other PSKd to compare with.
Return values
TRUE If the two are equal.
FALSE If the two are not equal.
References ExitNow, and otJoinerPskd::m8.
Referenced by JoinerPskd::GetLength(), and JoinerDiscerner::IsValid().
IsPskdValid()
bool IsPskdValid (const char * aPskdString) static
This static method indicates whether a given PSKd string if well-formed and valid.
Parameters
[in] aPskdString A pointer to a PSKd string array.
See also
IsValid()
Returns
TRUE if aPskdString is valid, FALSE otherwise.
References JoinerPskd::kMaxLength, JoinerPskd::kMinLength, ot::StringLength(), and VerifyOrExit.
Referenced by JoinerPskd::GetLength(), JoinerPskd::IsValid(), and JoinerPskd::SetFrom().
Field Documentation
kMinLength
constexpr uint8_t kMinLength = 6 static
Min PSKd string length (excludes null char)
Referenced by JoinerPskd::IsPskdValid().
kMaxLength
constexpr uint8_t kMaxLength = OT_JOINER_MAX_PSKD_LENGTH static
Max PSKd string length (excludes null char)
Referenced by SteeringData::Init(), JoinerPskd::IsPskdValid(), JoinerDiscerner::IsValid(), and SteeringData::UpdateBloomFilter().
The documentation for this class was generated from the following files:
meshcop.hpp
meshcop.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale