OpenThread: RouterAdvertMessage Class Reference
RouterAdvertMessage Class Reference
#include <nd6.hpp>
Data Structures
class Header
Public Types
typedef Data< kWithUint16Length > Icmp6Packet
A data buffer containing an ICMPv6 packet.
Public Member Functions
Error AppendPrefixInfoOption (const Prefix &aPrefix, uint32_t aValidLifetime, uint32_t aPreferredLifetime)
Error AppendRouteInfoOption (const Prefix &aPrefix, uint32_t aRouteLifetime, RoutePreference aPreference)
Option::Iterator begin (void) const
bool ContainsAnyOptions (void) const
Option::Iterator end (void) const
const Icmp6Packet & GetAsPacket (void) const
const Header & GetHeader (void) const
bool IsValid (void) const
RouterAdvertMessage (const Icmp6Packet &aPacket)
template<uint16_t kBufferSize>
RouterAdvertMessage (const Header &aHeader, uint8_t(&aBuffer)[kBufferSize])
Data Fields
ot::Ip6::Nd::RouterAdvertMessage::Header OT_TOOL_PACKED_END
Private Member Functions
Option * AppendOption (uint16_t aOptionSize)
const uint8_t * GetDataEnd (void) const
const uint8_t * GetOptionStart (void) const
Private Attributes
Data< kWithUint16Length > mData
uint16_t mMaxLength
Detailed Description
This class represents a Router Advertisement message.
Member Typedef Documentation
Icmp6Packet
typedef Data<kWithUint16Length> Icmp6Packet
A data buffer containing an ICMPv6 packet.
Constructor & Destructor Documentation
RouterAdvertMessage() [1/2]
RouterAdvertMessage (const Icmp6Packet & aPacket) inline explicit
This constructor initializes the RA message from a received packet data buffer.
Parameters
[in] aPacket A received packet data.
RouterAdvertMessage() [2/2]
RouterAdvertMessage (const Header & aHeader, uint8_t(&) aBuffer[kBufferSize]) inline
This template constructor initializes the RA message with a given header using a given buffer to store the RA message.
Template Parameters
kBufferSize The size of the buffer used to store the RA message.
Parameters
[in] aHeader The RA message header.
[in] aBuffer The data buffer to store the RA message in.
Member Function Documentation
GetAsPacket()
const Icmp6Packet& GetAsPacket (void) const inline
This method gets the RA message as an Icmp6Packet.
Returns
The RA message as an Icmp6Packet.
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the RA message is valid.
Return values
TRUE If the RA message is valid.
FALSE If the RA message is not valid.
GetHeader()
const Header& GetHeader (void) const inline
This method gets the RA message's header.
Returns
The RA message's header.
AppendPrefixInfoOption()
Error AppendPrefixInfoOption (const Prefix & aPrefix, uint32_t aValidLifetime, uint32_t aPreferredLifetime)
This method appends a Prefix Info Option to the RA message.
The appended Prefix Info Option will have both on-link (L) and autonomous address-configuration (A) flags set.
Parameters
[in] aPrefix The prefix.
[in] aValidLifetime The valid lifetime in seconds.
[in] aPreferredLifetime The preferred lifetime in seconds.
Return values
kErrorNone Option is appended successfully.
kErrorNoBufs No more space in the buffer to append the option.
References PrefixInfoOption::Init(), ot::kErrorNoBufs, ot::kErrorNone, PrefixInfoOption::SetAutoAddrConfigFlag(), PrefixInfoOption::SetOnLinkFlag(), PrefixInfoOption::SetPreferredLifetime(), PrefixInfoOption::SetPrefix(), PrefixInfoOption::SetValidLifetime(), and VerifyOrExit.
AppendRouteInfoOption()
Error AppendRouteInfoOption (const Prefix & aPrefix, uint32_t aRouteLifetime, RoutePreference aPreference)
This method appends a Route Info Option to the RA message.
Parameters
[in] aPrefix The prefix.
[in] aRouteLifetime The route lifetime in seconds.
[in] aPreference The route preference.
Return values
kErrorNone Option is appended successfully.
kErrorNoBufs No more space in the buffer to append the option.
References Prefix::GetLength(), RouteInfoOption::Init(), ot::kErrorNoBufs, ot::kErrorNone, RouteInfoOption::OptionSizeForPrefix(), RouteInfoOption::SetPreference(), RouteInfoOption::SetPrefix(), RouteInfoOption::SetRouteLifetime(), and VerifyOrExit.
ContainsAnyOptions()
bool ContainsAnyOptions (void) const inline
This method indicates whether or not the RA message contains any options.
Return values
TRUE If the RA message contains at least one option.
FALSE If the RA message contains no options.
begin()
Option::Iterator begin (void) const inline
end()
Option::Iterator end (void) const inline
GetOptionStart()
const uint8_t* GetOptionStart (void) const inline private
GetDataEnd()
const uint8_t* GetDataEnd (void) const inline private
AppendOption()
Option * AppendOption (uint16_t aOptionSize) private
References ot::AsNonConst(), Option::GetLength(), Option::SetLength(), and VerifyOrExit.
Field Documentation
OT_TOOL_PACKED_END
ot::Ip6::Nd::RouterAdvertMessage::Header OT_TOOL_PACKED_END
mData
Data<kWithUint16Length> mData private
mMaxLength
uint16_t mMaxLength private
The documentation for this class was generated from the following files:
nd6.hpp
nd6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale