OpenThread: RouteInfoOption Class Reference
RouteInfoOption Class Reference
#include <nd6.hpp>
Public Member Functions
RoutePreference GetPreference (void) const
void GetPrefix (Prefix &aPrefix) const
uint32_t GetRouteLifetime (void) const
void Init (void)
bool IsValid (void) const
RouteInfoOption (void)=delete
void SetPreference (RoutePreference aPreference)
void SetPrefix (const Prefix &aPrefix)
void SetRouteLifetime (uint32_t aLifetime)
Public Member Functions inherited from Option
uint16_t GetLength (void) const
uint16_t GetSize (void) const
uint8_t GetType (void) const
bool IsValid (void) const
void SetLength (uint8_t aLength)
void SetSize (uint16_t aSize)
void SetType (Type aType)
Static Public Member Functions
static uint8_t OptionLengthForPrefix (uint8_t aPrefixLength)
static uint16_t OptionSizeForPrefix (uint8_t aPrefixLength)
Static Public Attributes
static constexpr uint16_t kMinSize = kLengthUnit
Minimum size (in bytes) of a Route Info Option.
static constexpr Type kType = kTypeRouteInfo
Route Information Option Type.
Static Public Attributes inherited from Option
static constexpr uint16_t kLengthUnit = 8
The unit of length in octets.
Private Member Functions
uint8_t * GetPrefixBytes (void)
const uint8_t * GetPrefixBytes (void) const
Private Member Functions inherited from Clearable< RouteInfoOption >
void Clear (void)
Private Attributes
uint8_t mPrefixLength
uint8_t mResvdPrf
uint32_t mRouteLifetime
Static Private Attributes
static constexpr uint8_t kPreferenceMask = 3 << kPreferenceOffset
static constexpr uint8_t kPreferenceOffset = 3
Additional Inherited Members
Public Types inherited from Option
enum Type : uint8_t { kTypePrefixInfo = 3, kTypeRouteInfo = 24 }
Detailed Description
This class represents the Route Information Option.
See section 2.3 of RFC 4191 for definition of this option. [https://tools.ietf.org/html/rfc4191#section-2.3]
Constructor & Destructor Documentation
RouteInfoOption()
RouteInfoOption (void) delete
Member Function Documentation
Init()
void Init (void)
This method initializes the option setting the type and clearing (setting to zero) all other fields.
References Option::kTypeRouteInfo, and Option::SetType().
Referenced by RouterAdvertMessage::AppendRouteInfoOption().
SetPreference()
void SetPreference (RoutePreference aPreference)
This method sets the route preference.
Parameters
[in] aPreference The route preference.
References ot::NetworkData::RoutePreferenceToValue().
Referenced by RouterAdvertMessage::AppendRouteInfoOption().
GetPreference()
RoutePreference GetPreference (void) const
This method gets the route preference.
Returns
The route preference.
References ot::NetworkData::RoutePreferenceFromValue().
SetRouteLifetime()
void SetRouteLifetime (uint32_t aLifetime) inline
This method sets the lifetime of the route in seconds.
Parameters
[in] aLifetime The lifetime of the route in seconds.
References ot::Encoding::BigEndian::HostSwap32().
Referenced by RouterAdvertMessage::AppendRouteInfoOption().
GetRouteLifetime()
uint32_t GetRouteLifetime (void) const inline
This method gets Route Lifetime in seconds.
Returns
The Route Lifetime in seconds.
References ot::Encoding::BigEndian::HostSwap32(), and Option::IsValid().
SetPrefix()
void SetPrefix (const Prefix & aPrefix)
This method sets the prefix and adjusts the option length based on the prefix length.
Parameters
[in] aPrefix The prefix contained in this option.
References Prefix::GetBytes(), Prefix::GetBytesSize(), otIp6Prefix::mLength, and Option::SetLength().
Referenced by RouterAdvertMessage::AppendRouteInfoOption().
GetPrefix()
void GetPrefix (Prefix & aPrefix) const
This method gets the prefix in this option.
Parameters
[out] aPrefix Reference to a Prefix to return the prefix.
References Prefix::Set().
IsValid()
bool IsValid (void) const
This method tells whether this option is valid.
Returns
A boolean indicates whether this option is valid.
References Option::GetLength(), Option::GetSize(), ot::NetworkData::IsRoutePreferenceValid(), and Prefix::kMaxLength.
OptionLengthForPrefix()
uint8_t OptionLengthForPrefix (uint8_t aPrefixLength) static
This static method calculates the minimum option length for a given prefix length.
The option length (which is in unit of 8 octets) can be 1, 2, or 3 depending on the prefix length. It can be 1 for a zero prefix length, 2 if the prefix length is not greater than 64, and 3 otherwise.
Parameters
[in] aPrefixLength The prefix length (in bits).
Returns
The option length (in unit of 8 octet) for aPrefixLength.
OptionSizeForPrefix()
static uint16_t OptionSizeForPrefix (uint8_t aPrefixLength) inline static
This static method calculates the minimum option size (in bytes) for a given prefix length.
Parameters
[in] aPrefixLength The prefix length (in bits).
Returns
The option size (in bytes) for aPrefixLength.
References Option::kLengthUnit.
Referenced by RouterAdvertMessage::AppendRouteInfoOption().
GetPrefixBytes() [1/2]
uint8_t* GetPrefixBytes (void) inline private
References ot::AsConst(), ot::AsNonConst(), and RouteInfoOption::GetPrefixBytes().
Referenced by RouteInfoOption::GetPrefixBytes().
GetPrefixBytes() [2/2]
const uint8_t* GetPrefixBytes (void) const inline private
Field Documentation
kMinSize
constexpr uint16_t kMinSize = kLengthUnit static
Minimum size (in bytes) of a Route Info Option.
kType
constexpr Type kType = kTypeRouteInfo static
Route Information Option Type.
kPreferenceOffset
constexpr uint8_t kPreferenceOffset = 3 static private
kPreferenceMask
constexpr uint8_t kPreferenceMask = 3 << kPreferenceOffset static private
mPrefixLength
uint8_t mPrefixLength private
mResvdPrf
uint8_t mResvdPrf private
mRouteLifetime
uint32_t mRouteLifetime private
The documentation for this class was generated from the following files:
nd6.hpp
nd6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale