OpenThread: KeyManager Class Reference
KeyManager Class Reference
Core-security
#include <key_manager.hpp>
Data Structures
union HashKeys
struct Keys
Public Member Functions
void ExtractKek (Kek &aKek)
uint32_t GetCurrentKeySequence (void) const
const Mle::KeyMaterial & GetCurrentMleKey (void) const
const KekKeyMaterial & GetKek (void) const
uint32_t GetKekFrameCounter (void) const
uint32_t GetKeySwitchGuardTime (void) const
uint32_t GetMaximumMacFrameCounter (void) const
uint32_t GetMleFrameCounter (void) const
void GetNetworkKey (NetworkKey &aNetworkKey) const
void GetPskc (Pskc &aPskc) const
const SecurityPolicy & GetSecurityPolicy (void) const
const Mle::KeyMaterial & GetTemporaryMleKey (uint32_t aKeySequence)
void IncrementKekFrameCounter (void)
void IncrementMleFrameCounter (void)
bool IsPskcSet (void) const
KeyManager (Instance &aInstance)
void MacFrameCounterUsed (uint32_t aMacFrameCounter)
void SetAllMacFrameCounters (uint32_t aMacFrameCounter)
void SetCurrentKeySequence (uint32_t aKeySequence)
void SetKek (const Kek &aKek)
void SetKek (const uint8_t *aKekBytes)
void SetKeySwitchGuardTime (uint32_t aKeySwitchGuardTime)
void SetMleFrameCounter (uint32_t aMleFrameCounter)
void SetNetworkKey (const NetworkKey &aNetworkKey)
void SetPskc (const Pskc &aPskc)
void SetSecurityPolicy (const SecurityPolicy &aSecurityPolicy)
void SetStoredMacFrameCounter (uint32_t aStoredMacFrameCounter)
void SetStoredMleFrameCounter (uint32_t aStoredMleFrameCounter)
void Start (void)
void Stop (void)
void UpdateKeyMaterial (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void ComputeKeys (uint32_t aKeySequence, HashKeys &aHashKeys)
void HandleKeyRotationTimer (void)
void ResetFrameCounters (void)
void StartKeyRotationTimer (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleKeyRotationTimer (Timer &aTimer)
Private Attributes
uint32_t mHoursSinceKeyRotation
bool mIsPskcSet: 1
KekKeyMaterial mKek
uint32_t mKekFrameCounter
TimerMilli mKeyRotationTimer
uint32_t mKeySequence
bool mKeySwitchGuardEnabled
uint32_t mKeySwitchGuardTime
Mac::LinkFrameCounters mMacFrameCounters
uint32_t mMleFrameCounter
Mle::KeyMaterial mMleKey
NetworkKey mNetworkKey
Pskc mPskc
SecurityPolicy mSecurityPolicy
uint32_t mStoredMacFrameCounter
uint32_t mStoredMleFrameCounter
Mle::KeyMaterial mTemporaryMleKey
OT_TOOL_PACKED_BEGIN struct ot::KeyManager::Keys OT_TOOL_PACKED_END
Static Private Attributes
static constexpr uint32_t kDefaultKeySwitchGuardTime = 624
static constexpr bool kExportableMacKeys = OPENTHREAD_CONFIG_PLATFORM_MAC_KEYS_EXPORTABLE_ENABLE
static constexpr uint32_t kOneHourIntervalInMsec = 3600u * 1000u
static const uint8_t kThreadString []
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class defines Thread Key Manager.
Constructor & Destructor Documentation
KeyManager()
KeyManager (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Clearable< Type >::Clear(), NetworkKey::GenerateRandom(), IgnoreError(), KeyManager::mMacFrameCounters, KeyManager::mNetworkKey, KeyManager::mPskc, otPlatCryptoInit(), and LinkFrameCounters::Reset().
Member Function Documentation
Start()
void Start (void)
This method starts KeyManager rotation timer and sets guard timer to initial value.
References KeyManager::mKeySwitchGuardEnabled, and KeyManager::StartKeyRotationTimer().
Stop()
void Stop (void)
This method stops KeyManager timers.
References KeyManager::mKeyRotationTimer, and TimerMilli::Stop().
GetNetworkKey()
void GetNetworkKey (NetworkKey & aNetworkKey) const
This method gets the Thread Network Key.
Parameters
[out] aNetworkKey A reference to a NetworkKey to output the Thread Network Key.
References Clearable< Type >::Clear(), NetworkKey::kSize, otNetworkKey::m8, KeyManager::mNetworkKey, OT_ASSERT, and SuccessOrAssert.
Referenced by KeyManager::SetNetworkKey().
SetNetworkKey()
void SetNetworkKey (const NetworkKey & aNetworkKey)
This method sets the Thread Network Key.
Parameters
[in] aNetworkKey A Thread Network Key.
References KeyManager::GetNetworkKey(), ot::kEventNetworkKeyChanged, ot::kEventThreadKeySeqCounterChanged, KeyManager::mKeySequence, KeyManager::mNetworkKey, KeyManager::ResetFrameCounters(), SuccessOrExit, KeyManager::UpdateKeyMaterial(), and VerifyOrExit.
IsPskcSet()
bool IsPskcSet (void) const inline
This method indicates whether the PSKc is configured.
A value of all zeros indicates that the PSKc is not configured.
Return values
TRUE if the PSKc is configured.
FALSE if the PSKc is not not configured.
GetPskc()
void GetPskc (Pskc & aPskc) const
This method gets the PKSc.
Parameters
[out] aPskc A reference to a Pskc to return the PSKc.
References Clearable< Type >::Clear(), ExitNow, ot::kEventNetworkKeyChanged, ot::kEventPskcChanged, ot::kEventThreadKeySeqCounterChanged, NetworkKey::kSize, Pskc::kSize, otNetworkKey::m8, otPskc::m8, KeyManager::mIsPskcSet, KeyManager::mKeySequence, KeyManager::mPskc, OT_ASSERT, KeyManager::ResetFrameCounters(), SuccessOrAssert, KeyManager::UpdateKeyMaterial(), and VerifyOrExit.
Referenced by KeyManager::SetPskc().
SetPskc()
void SetPskc (const Pskc & aPskc)
This method sets the PSKc.
Parameters
[in] aPskc A reference to the PSKc.
References KeyManager::GetPskc(), ot::kEventPskcChanged, KeyManager::mIsPskcSet, KeyManager::mPskc, SuccessOrExit, and VerifyOrExit.
GetCurrentKeySequence()
uint32_t GetCurrentKeySequence (void) const inline
This method returns the current key sequence value.
Returns
The current key sequence value.
Referenced by Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
SetCurrentKeySequence()
void SetCurrentKeySequence (uint32_t aKeySequence)
This method sets the current key sequence value.
Parameters
[in] aKeySequence The key sequence value.
References Timer::IsRunning(), ot::kEventThreadKeySeqCounterChanged, KeyManager::mHoursSinceKeyRotation, KeyManager::mKeyRotationTimer, KeyManager::mKeySequence, KeyManager::mKeySwitchGuardEnabled, KeyManager::mKeySwitchGuardTime, KeyManager::mMleFrameCounter, KeyManager::SetAllMacFrameCounters(), KeyManager::StartKeyRotationTimer(), KeyManager::UpdateKeyMaterial(), and VerifyOrExit.
Referenced by KeyManager::HandleKeyRotationTimer(), and Mac::ProcessReceiveSecurity().
GetCurrentMleKey()
const Mle::KeyMaterial& GetCurrentMleKey (void) const inline
This method returns the current MLE key Material.
Returns
The current MLE key.
GetTemporaryMleKey()
const Mle::KeyMaterial & GetTemporaryMleKey (uint32_t aKeySequence)
This method returns a temporary MLE key Material computed from the given key sequence.
Parameters
[in] aKeySequence The key sequence value.
Returns
The temporary MLE key.
References KeyManager::ComputeKeys(), KeyManager::HashKeys::GetMleKey(), KeyManager::mTemporaryMleKey, and KeyMaterial::SetFrom().
GetMaximumMacFrameCounter()
uint32_t GetMaximumMacFrameCounter (void) const inline
This method gets the maximum MAC Frame Counter among all supported radio links.
Returns
The maximum MAC frame Counter among all supported radio links.
SetAllMacFrameCounters()
void SetAllMacFrameCounters (uint32_t aMacFrameCounter)
This method sets the current MAC Frame Counter value for all radio links.
Parameters
[in] aMacFrameCounter The MAC Frame Counter value.
References IgnoreError(), KeyManager::MacFrameCounterUsed(), KeyManager::mMacFrameCounters, KeyManager::mStoredMacFrameCounter, LinkFrameCounters::SetAll(), and VerifyOrExit.
Referenced by KeyManager::SetCurrentKeySequence().
SetStoredMacFrameCounter()
void SetStoredMacFrameCounter (uint32_t aStoredMacFrameCounter) inline
This method sets the MAC Frame Counter value which is stored in non-volatile memory.
Parameters
[in] aStoredMacFrameCounter The stored MAC Frame Counter value.
GetMleFrameCounter()
uint32_t GetMleFrameCounter (void) const inline
This method returns the current MLE Frame Counter value.
Returns
The current MLE Frame Counter value.
SetMleFrameCounter()
void SetMleFrameCounter (uint32_t aMleFrameCounter) inline
This method sets the current MLE Frame Counter value.
Parameters
[in] aMleFrameCounter The MLE Frame Counter value.
SetStoredMleFrameCounter()
void SetStoredMleFrameCounter (uint32_t aStoredMleFrameCounter) inline
This method sets the MLE Frame Counter value which is stored in non-volatile memory.
Parameters
[in] aStoredMleFrameCounter The stored MLE Frame Counter value.
IncrementMleFrameCounter()
void IncrementMleFrameCounter (void)
This method increments the current MLE Frame Counter value.
References IgnoreError(), KeyManager::mMleFrameCounter, and KeyManager::mStoredMleFrameCounter.
GetKek()
const KekKeyMaterial& GetKek (void) const inline
This method returns the KEK as KekKeyMaterail
Returns
The KEK as KekKeyMaterial.
Referenced by Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
ExtractKek()
void ExtractKek (Kek & aKek) inline
This method retrieves the KEK as literal Kek key.
Parameters
[out] aKek A reference to a Kek to output the retrieved KEK.
SetKek() [1/2]
void SetKek (const Kek & aKek)
This method sets the KEK.
Parameters
[in] aKek A KEK.
References KeyManager::mKek, KeyManager::mKekFrameCounter, and KeyMaterial::SetFrom().
SetKek() [2/2]
void SetKek (const uint8_t * aKekBytes) inline
This method sets the KEK.
Parameters
[in] aKekBytes A pointer to the KEK bytes.
References KeyManager::SetKek().
Referenced by KeyManager::SetKek().
GetKekFrameCounter()
uint32_t GetKekFrameCounter (void) const inline
This method returns the current KEK Frame Counter value.
Returns
The current KEK Frame Counter value.
Referenced by Mac::ProcessTransmitSecurity().
IncrementKekFrameCounter()
void IncrementKekFrameCounter (void) inline
This method increments the current KEK Frame Counter value.
Referenced by Mac::ProcessTransmitSecurity().
GetKeySwitchGuardTime()
uint32_t GetKeySwitchGuardTime (void) const inline
This method returns the KeySwitchGuardTime.
The KeySwitchGuardTime is the time interval during which key rotation procedure is prevented.
Returns
The KeySwitchGuardTime value in hours.
SetKeySwitchGuardTime()
void SetKeySwitchGuardTime (uint32_t aKeySwitchGuardTime) inline
This method sets the KeySwitchGuardTime.
The KeySwitchGuardTime is the time interval during which key rotation procedure is prevented.
Parameters
[in] aKeySwitchGuardTime The KeySwitchGuardTime value in hours.
GetSecurityPolicy()
const SecurityPolicy& GetSecurityPolicy (void) const inline
This method returns the Security Policy.
The Security Policy specifies Key Rotation Time and network administrator preferences for which security-related operations are allowed or disallowed.
Returns
The SecurityPolicy.
SetSecurityPolicy()
void SetSecurityPolicy (const SecurityPolicy & aSecurityPolicy)
This method sets the Security Policy.
The Security Policy specifies Key Rotation Time and network administrator preferences for which security-related operations are allowed or disallowed.
Parameters
[in] aSecurityPolicy The Security Policy.
References ExitNow, IgnoreError(), ot::kEventSecurityPolicyChanged, SecurityPolicy::kMinKeyRotationTime, LogNote, otSecurityPolicy::mRotationTime, and KeyManager::mSecurityPolicy.
UpdateKeyMaterial()
void UpdateKeyMaterial (void)
This method updates the MAC keys and MLE key.
References KeyManager::ComputeKeys(), KeyManager::HashKeys::GetMacKey(), KeyManager::HashKeys::GetMleKey(), KeyManager::kExportableMacKeys, Frame::kKeyIdMode1, KeyManager::mKeySequence, KeyManager::mMleKey, and KeyMaterial::SetFrom().
Referenced by KeyManager::GetPskc(), KeyManager::SetCurrentKeySequence(), and KeyManager::SetNetworkKey().
MacFrameCounterUsed()
void MacFrameCounterUsed (uint32_t aMacFrameCounter)
This method handles MAC frame counter changes (callback from SubMac for 15.4 security frame change).
This is called to indicate the aMacFrameCounter value is now used.
Parameters
[in] aMacFrameCounter The 15.4 link MAC frame counter value.
References IgnoreError(), KeyManager::mMacFrameCounters, and KeyManager::mStoredMacFrameCounter.
Referenced by KeyManager::SetAllMacFrameCounters().
ComputeKeys()
void ComputeKeys (uint32_t aKeySequence, HashKeys & aHashKeys) private
References HkdfSha256::Expand(), HkdfSha256::Extract(), HmacSha256::Finish(), NetworkKey::kSize, Key::kSize, KeyManager::kThreadString, otNetworkKey::m8, otMacKey::m8, KeyManager::HashKeys::mHash, KeyManager::mNetworkKey, Key::Set(), HmacSha256::Start(), HmacSha256::Update(), and ot::Encoding::BigEndian::WriteUint32().
Referenced by KeyManager::GetTemporaryMleKey(), and KeyManager::UpdateKeyMaterial().
StartKeyRotationTimer()
void StartKeyRotationTimer (void) private
References KeyManager::kOneHourIntervalInMsec, KeyManager::mHoursSinceKeyRotation, KeyManager::mKeyRotationTimer, and TimerMilli::Start().
Referenced by KeyManager::SetCurrentKeySequence(), and KeyManager::Start().
HandleKeyRotationTimer() [1/2]
void HandleKeyRotationTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and KeyManager::HandleKeyRotationTimer().
HandleKeyRotationTimer() [2/2]
void HandleKeyRotationTimer (void) private
References Timer::GetFireTime(), KeyManager::kOneHourIntervalInMsec, KeyManager::mHoursSinceKeyRotation, KeyManager::mKeyRotationTimer, KeyManager::mKeySequence, otSecurityPolicy::mRotationTime, KeyManager::mSecurityPolicy, KeyManager::SetCurrentKeySequence(), and TimerMilli::StartAt().
Referenced by KeyManager::HandleKeyRotationTimer().
ResetFrameCounters()
void ResetFrameCounters (void) private
References Neighbor::GetLinkFrameCounters(), LinkFrameCounters::Reset(), Neighbor::SetKeySequence(), Neighbor::SetLinkAckFrameCounter(), and Neighbor::SetMleFrameCounter().
Referenced by KeyManager::GetPskc(), and KeyManager::SetNetworkKey().
Field Documentation
kDefaultKeySwitchGuardTime
constexpr uint32_t kDefaultKeySwitchGuardTime = 624 static private
kOneHourIntervalInMsec
constexpr uint32_t kOneHourIntervalInMsec = 3600u * 1000u static private
Referenced by KeyManager::HandleKeyRotationTimer(), and KeyManager::StartKeyRotationTimer().
kExportableMacKeys
constexpr bool kExportableMacKeys = OPENTHREAD_CONFIG_PLATFORM_MAC_KEYS_EXPORTABLE_ENABLE static private
Referenced by KeyManager::UpdateKeyMaterial().
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN struct ot::KeyManager::Keys OT_TOOL_PACKED_END private
kThreadString
const uint8_t kThreadString static private
Initial value:
= {
    'T', 'h', 'r', 'e', 'a', 'd',
}
Referenced by KeyManager::ComputeKeys().
mNetworkKey
NetworkKey mNetworkKey private
Referenced by KeyManager::ComputeKeys(), KeyManager::GetNetworkKey(), KeyManager::KeyManager(), and KeyManager::SetNetworkKey().
mKeySequence
uint32_t mKeySequence private
Referenced by KeyManager::GetPskc(), KeyManager::HandleKeyRotationTimer(), KeyManager::SetCurrentKeySequence(), KeyManager::SetNetworkKey(), and KeyManager::UpdateKeyMaterial().
mMleKey
Mle::KeyMaterial mMleKey private
Referenced by KeyManager::UpdateKeyMaterial().
mTemporaryMleKey
Mle::KeyMaterial mTemporaryMleKey private
Referenced by KeyManager::GetTemporaryMleKey().
mMacFrameCounters
Mac::LinkFrameCounters mMacFrameCounters private
Referenced by KeyManager::KeyManager(), KeyManager::MacFrameCounterUsed(), and KeyManager::SetAllMacFrameCounters().
mMleFrameCounter
uint32_t mMleFrameCounter private
Referenced by KeyManager::IncrementMleFrameCounter(), and KeyManager::SetCurrentKeySequence().
mStoredMacFrameCounter
uint32_t mStoredMacFrameCounter private
Referenced by KeyManager::MacFrameCounterUsed(), and KeyManager::SetAllMacFrameCounters().
mStoredMleFrameCounter
uint32_t mStoredMleFrameCounter private
Referenced by KeyManager::IncrementMleFrameCounter().
mHoursSinceKeyRotation
uint32_t mHoursSinceKeyRotation private
Referenced by KeyManager::HandleKeyRotationTimer(), KeyManager::SetCurrentKeySequence(), and KeyManager::StartKeyRotationTimer().
mKeySwitchGuardTime
uint32_t mKeySwitchGuardTime private
Referenced by KeyManager::SetCurrentKeySequence().
mKeySwitchGuardEnabled
bool mKeySwitchGuardEnabled private
Referenced by KeyManager::SetCurrentKeySequence(), and KeyManager::Start().
mKeyRotationTimer
TimerMilli mKeyRotationTimer private
Referenced by KeyManager::HandleKeyRotationTimer(), KeyManager::SetCurrentKeySequence(), KeyManager::StartKeyRotationTimer(), and KeyManager::Stop().
mPskc
Pskc mPskc private
Referenced by KeyManager::GetPskc(), KeyManager::KeyManager(), and KeyManager::SetPskc().
mKek
KekKeyMaterial mKek private
Referenced by KeyManager::SetKek().
mKekFrameCounter
uint32_t mKekFrameCounter private
Referenced by KeyManager::SetKek().
mSecurityPolicy
SecurityPolicy mSecurityPolicy private
Referenced by KeyManager::HandleKeyRotationTimer(), and KeyManager::SetSecurityPolicy().
mIsPskcSet
bool mIsPskcSet private
Referenced by KeyManager::GetPskc(), and KeyManager::SetPskc().
The documentation for this class was generated from the following files:
key_manager.hpp
key_manager.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale