OpenThread: Encoder Class Reference
Encoder Class Reference
#include <spinel_encoder.hpp>
Public Member Functions
otError BeginFrame (Spinel::Buffer::Priority aPriority)
otError BeginFrame (uint8_t aHeader, unsigned int aCommand)
otError BeginFrame (uint8_t aHeader, unsigned int aCommand, spinel_prop_key_t aKey)
otError CloseStruct (void)
Encoder (Spinel::Buffer &aNcpBuffer)
otError EndFrame (void)
otError OpenStruct (void)
otError OverwriteWithLastStatusError (spinel_status_t aStatus)
otError ResetToSaved (void)
otError SavePosition (void)
otError WriteBool (bool aBool)
otError WriteData (const uint8_t *aData, uint16_t aDataLen)
otError WriteDataWithLen (const uint8_t *aData, uint16_t aDataLen)
otError WriteEui48 (const spinel_eui48_t &aEui48)
otError WriteEui48 (const uint8_t *aEui48)
otError WriteEui64 (const spinel_eui64_t &aEui64)
otError WriteEui64 (const otExtAddress &aExtAddress)
otError WriteEui64 (const uint8_t *aEui64)
otError WriteInt16 (int16_t aInt16)
otError WriteInt32 (int32_t aInt32)
otError WriteInt64 (int64_t aInt64)
otError WriteInt8 (int8_t aInt8)
otError WriteIp6Address (const spinel_ipv6addr_t &aIp6Addr)
otError WriteIp6Address (const otIp6Address &aIp6Addr)
otError WriteIp6Address (const uint8_t *aIp6AddrBuf)
otError WritePacked (const char *aPackFormat,...)
otError WriteUint16 (uint16_t aUint16)
otError WriteUint32 (uint32_t aUint32)
otError WriteUint64 (uint64_t aUint64)
otError WriteUint8 (uint8_t aUint8)
otError WriteUintPacked (unsigned int aUint)
otError WriteUtf8 (const char *aUtf8)
otError WriteVPacked (const char *aPackFormat, va_list aArgs)
Private Types
enum { kPackFormatBufferSize = 96, kMaxNestedStructs = 4 }
Private Attributes
Spinel::Buffer & mNcpBuffer
uint8_t mNumOpenStructs
uint8_t mSavedNumOpenStructs
Spinel::Buffer::WritePosition mSavedPosition
Spinel::Buffer::WritePosition mStructPosition [kMaxNestedStructs]
Detailed Description
This class defines a spinel encoder.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kPackFormatBufferSize
Size of buffer used when encoding using WritePacked() or WriteVPacked().
kMaxNestedStructs
Maximum number of nested structs.
Constructor & Destructor Documentation
Encoder()
Encoder (Spinel::Buffer & aNcpBuffer) inline explicit
This constructor initializes a Encoder object.
Parameters
[in] aNcpBuffer A reference to a Spinel::Buffer where the frames are written.
References Encoder::BeginFrame(), Encoder::EndFrame(), and Encoder::OverwriteWithLastStatusError().
Member Function Documentation
BeginFrame() [1/3]
otError BeginFrame (Spinel::Buffer::Priority aPriority)
This method begins a new frame to be added/written to the frame buffer.
If there is a previous frame being written (for which EndFrame() has not yet been called), calling BeginFrame() will discard and clear the previous unfinished frame.
Parameters
[in] aPriority Priority level of the new input frame.
Return values
OT_ERROR_NONE Successfully started a new frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to start a new frame.
References Buffer::InFrameBegin(), Encoder::mNcpBuffer, Encoder::mNumOpenStructs, and OT_ERROR_NONE.
Referenced by Encoder::BeginFrame(), NcpBase::CommandHandler_PROP_VALUE_update(), Encoder::Encoder(), NcpBase::Log(), NcpBase::StreamWrite(), NcpBase::WriteLastStatusFrame(), NcpBase::WritePropertyValueInsertedRemovedFrame(), and NcpBase::WritePropertyValueIsFrame().
BeginFrame() [2/3]
otError BeginFrame (uint8_t aHeader, unsigned int aCommand)
This method begins a new spinel command frame to be added/written to the frame buffer.
If there is a previous frame being written (for which EndFrame() has not yet been called), calling BeginFrame() will discard and clear the previous unfinished frame.
The spinel transaction ID (TID) in the given spinel header is used to determine the priority level of the new frame. Non-zero TID value indicates that the frame is a response and therefore it uses higher priority level.
Parameters
[in] aHeader Spinel header for new the command frame.
[in] aCommand Spinel command.
Return values
OT_ERROR_NONE Successfully started a new frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to start a new frame.
References Encoder::BeginFrame(), Buffer::kPriorityHigh, Buffer::kPriorityLow, OT_ERROR_NONE, SPINEL_HEADER_GET_TID, SuccessOrExit, Encoder::WriteUint8(), and Encoder::WriteUintPacked().
BeginFrame() [3/3]
otError BeginFrame (uint8_t aHeader, unsigned int aCommand, spinel_prop_key_t aKey)
This method begins a new spinel property update command frame to be added/written to the frame buffer.
If there is a previous frame being written (for which EndFrame() has not yet been called), calling BeginFrame() will discard and clear the previous unfinished frame.
The spinel transaction ID (TID) in the given spinel header is used to determine the priority level of the new frame. Non-zero TID value indicates that the frame is a response and therefore it uses higher priority level.
This method saves the write position before the property key (see also SavePosition()) so that if fetching the property fails and the property key should be switched to LAST_STATUS with an error status, the saved position can be used to update the property key in the frame (see also OverwriteWithLastStatusError())
Parameters
[in] aHeader Spinel header for new the command frame.
[in] aCommand Spinel command.
[in] aKey Spinel property key
Return values
OT_ERROR_NONE Successfully started a new frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to start a new frame.
References Encoder::BeginFrame(), OT_ERROR_NONE, Encoder::SavePosition(), SuccessOrExit, and Encoder::WriteUintPacked().
OverwriteWithLastStatusError()
otError OverwriteWithLastStatusError (spinel_status_t aStatus)
This method overwrites the property key with LAST_STATUS in a property update command frame.
This method should be only used after a successful BeginFrame(aHeader, aCommand, aPropertKey), otherwise, its behavior is undefined.
This method moves the write position back to saved position by BeginFrame() and replaces the property key SPINEL_PROP_LAST_STATUS and writes the given spinel status error.
Parameters
[in] aStatus Spinel error status
Return values
OT_ERROR_NONE Successfully updated the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to update the frame.
References OT_ERROR_NONE, Encoder::ResetToSaved(), SPINEL_PROP_LAST_STATUS, SuccessOrExit, and Encoder::WriteUintPacked().
Referenced by Encoder::Encoder(), and NcpBase::HandlePropertyGet().
EndFrame()
otError EndFrame (void)
This method finalizes/ends the current frame being written to the buffer.
Before using this method BeginFrame() must be called to start and prepare a new frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the frame and return error status OT_ERROR_NO_BUFS.
This method ensures to close any open structure (previously opened using OpenStruct() but not closed using CloseStruct()).
Return values
OT_ERROR_NONE Successfully ended the input frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add message.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::CloseStruct(), Buffer::InFrameEnd(), Encoder::mNcpBuffer, Encoder::mNumOpenStructs, OT_ERROR_NONE, and SuccessOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), Encoder::Encoder(), NcpBase::Log(), NcpBase::StreamWrite(), NcpBase::WriteLastStatusFrame(), NcpBase::WritePropertyValueInsertedRemovedFrame(), and NcpBase::WritePropertyValueIsFrame().
WriteBool()
otError WriteBool (bool aBool) inline
This method encodes and writes a boolean value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aBool The boolean value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given byte to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedByte(), and Encoder::mNcpBuffer.
Referenced by NcpBase::HandlePropertyGet().
WriteUint8()
otError WriteUint8 (uint8_t aUint8) inline
This method encodes and writes a uint8_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aUint8 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedByte(), and Encoder::mNcpBuffer.
Referenced by Encoder::BeginFrame(), NcpBase::EncodeChannelMask(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet(), NcpBase::Log(), and Encoder::WriteInt8().
WriteInt8()
otError WriteInt8 (int8_t aInt8) inline
This method encodes and writes an int8_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aInt8 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::WriteUint16(), and Encoder::WriteUint8().
Referenced by NcpBase::HandlePropertyGet().
WriteUint16()
otError WriteUint16 (uint16_t aUint16)
This method encodes and writes a uint16_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aUint16 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedByte(), Encoder::mNcpBuffer, OT_ERROR_NONE, and SuccessOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandlePropertyGet(), Encoder::WriteDataWithLen(), Encoder::WriteInt16(), and Encoder::WriteInt8().
WriteInt16()
otError WriteInt16 (int16_t aInt16) inline
This method encodes and writes an int16_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aInt16 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::WriteUint16(), and Encoder::WriteUint32().
WriteUint32()
otError WriteUint32 (uint32_t aUint32)
This method encodes and writes a uint32_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aUint32 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedByte(), Encoder::mNcpBuffer, OT_ERROR_NONE, and SuccessOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandlePropertyGet(), Encoder::WriteInt16(), and Encoder::WriteInt32().
WriteInt32()
otError WriteInt32 (int32_t aInt32) inline
This method encodes and writes an int32_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aInt32 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::WriteUint32(), and Encoder::WriteUint64().
WriteUint64()
otError WriteUint64 (uint64_t aUint64)
This method encodes and writes a uint64_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aUint64 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedByte(), Encoder::mNcpBuffer, OT_ERROR_NONE, and SuccessOrExit.
Referenced by NcpBase::HandlePropertyGet(), NcpBase::Log(), Encoder::WriteInt32(), and Encoder::WriteInt64().
WriteInt64()
otError WriteInt64 (int64_t aInt64) inline
This method encodes and writes an int64_t value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aInt64 The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::WriteUint64(), and Encoder::WriteUintPacked().
WriteUintPacked()
otError WriteUintPacked (unsigned int aUint)
This method encodes (using spinel packed integer format) and writes a value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aUint The value to add to input frame.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References spinel_packed_uint_encode(), and Encoder::WriteData().
Referenced by Encoder::BeginFrame(), NcpBase::HandlePropertyGet(), NcpBase::Log(), Encoder::OverwriteWithLastStatusError(), Encoder::WriteInt64(), and NcpBase::WriteLastStatusFrame().
WriteIp6Address() [1/3]
otError WriteIp6Address (const spinel_ipv6addr_t & aIp6Addr) inline
This method encodes and writes an IPv6 address to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aIp6Addr A reference to the IPv6 address to be added (as spinel_ipv6addr_t)
Return values
OT_ERROR_NONE Successfully added given address to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the IP address.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References spinel_ipv6addr_t::bytes, and Encoder::WriteIp6Address().
Referenced by Encoder::WriteIp6Address().
WriteIp6Address() [2/3]
otError WriteIp6Address (const otIp6Address & aIp6Addr) inline
This method encodes and writes an IPv6 address to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aIp6Addr A reference to the IPv6 address to be added (as otIp6Address)
Return values
OT_ERROR_NONE Successfully added given address to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the IP address.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, and Encoder::WriteIp6Address().
Referenced by Encoder::WriteIp6Address().
WriteIp6Address() [3/3]
otError WriteIp6Address (const uint8_t * aIp6AddrBuf) inline
This method encodes and writes an IPv6 address to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aIp6AddrBuf A pointer to a buffer containing the IPv6 address.
Return values
OT_ERROR_NONE Successfully added given address to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the IP address.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::WriteData().
WriteEui64() [1/3]
otError WriteEui64 (const spinel_eui64_t & aEui64) inline
This method encodes and writes an EUI64 value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aEui64 A reference to the EUI64 value as a spinel_eui64_t type.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the EUI64 value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References spinel_eui64_t::bytes, and Encoder::WriteEui64().
Referenced by NcpBase::HandlePropertyGet(), and Encoder::WriteEui64().
WriteEui64() [2/3]
otError WriteEui64 (const otExtAddress & aExtAddress) inline
This method encodes and writes an EUI64 value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aExtAddress A reference to an otExtAddress
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the EUI64 value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References otExtAddress::m8, and Encoder::WriteEui64().
Referenced by Encoder::WriteEui64().
WriteEui64() [3/3]
otError WriteEui64 (const uint8_t * aEui64) inline
This method encodes and writes an EUI64 value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aEui64 A pointer to a buffer containing the EUI64 value.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the EUI64 value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::WriteData().
WriteEui48() [1/2]
otError WriteEui48 (const spinel_eui48_t & aEui48) inline
This method encodes and writes an EUI48 value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aEui48 A reference to the EUI48 value.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the EUI48 value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References spinel_eui48_t::bytes, and Encoder::WriteEui48().
Referenced by Encoder::WriteEui48().
WriteEui48() [2/2]
otError WriteEui48 (const uint8_t * aEui48) inline
This method encodes and writes an EUI48 value to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aEui48 A pointer to a buffer containing the EUI64 value.
Return values
OT_ERROR_NONE Successfully added given value to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the EUI48 value.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::WriteData(), and Encoder::WriteUtf8().
WriteUtf8()
otError WriteUtf8 (const char * aUtf8)
This method encodes and writes a UTF8 string to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aUtf8 A const character pointer (C string).
Return values
OT_ERROR_NONE Successfully added given string to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the string.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedByte(), Encoder::mNcpBuffer, SuccessOrExit, and Encoder::WriteData().
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandlePropertyGet(), NcpBase::Log(), and Encoder::WriteEui48().
WriteData()
otError WriteData (const uint8_t * aData, uint16_t aDataLen) inline
This method encodes and writes a sequence of bytes to current input frame.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aData A pointer to data buffer.
[in] aDataLen The length (number of bytes) in the data buffer.
Return values
OT_ERROR_NONE Successfully added given data to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the byte.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Encoder::CloseStruct(), Buffer::InFrameFeedData(), Encoder::mNcpBuffer, Encoder::OpenStruct(), Encoder::ResetToSaved(), Encoder::SavePosition(), Encoder::WriteDataWithLen(), Encoder::WritePacked(), and Encoder::WriteVPacked().
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::StreamWrite(), Encoder::WriteDataWithLen(), Encoder::WriteEui48(), Encoder::WriteEui64(), Encoder::WriteIp6Address(), NcpBase::WritePropertyValueInsertedRemovedFrame(), Encoder::WriteUintPacked(), and Encoder::WriteUtf8().
WriteDataWithLen()
otError WriteDataWithLen (const uint8_t * aData, uint16_t aDataLen)
This method encodes and writes a data blob (sequence of bytes) with its length prepended before the data.
The length of the data (in bytes) is prepended (with the length encoded as a uint16). The size of the length field is not included in the length. This is similar to SPINEL_DATATYPE_DATA_WLEN type.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Parameters
[in] aData A pointer to data buffer.
[in] aDataLen The length (number of bytes) in the data buffer.
Return values
OT_ERROR_NONE Successfully added given data to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the byte.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References OT_ERROR_NONE, SuccessOrExit, Encoder::WriteData(), and Encoder::WriteUint16().
Referenced by Encoder::WriteData().
WritePacked()
otError WritePacked (const char * aPackFormat, ...)
This method encodes and writes a set of variables to the current input frame using a given spinel packing format string.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Note that the encoded buffer should fit in kPackFormatBufferSize bytes.
Parameters
[in] aPackFormat A string giving the spinel packing format.
[in] ... Variable arguments corresponding to the types given in aPackFormat (see spinel_datatype_pack()).
Return values
OT_ERROR_NONE Successfully added given data to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the byte.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedData(), Encoder::kPackFormatBufferSize, Encoder::mNcpBuffer, OT_ERROR_NO_BUFS, OT_ERROR_NONE, spinel_datatype_vpack(), and VerifyOrExit.
Referenced by Encoder::WriteData().
WriteVPacked()
otError WriteVPacked (const char * aPackFormat, va_list aArgs)
This method encodes and writes a set of variables to the current input frame using a given spinel packing format string.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the current input frame and return the error status OT_ERROR_NO_BUFS.
Note that the encoded buffer should fit in kPackFormatBufferSize bytes.
Parameters
[in] aPackFormat A string giving the spinel packing format.
[in] aArgs Variable arguments corresponding to the types given in aPackFormat (see spinel_datatype_pack()).
Return values
OT_ERROR_NONE Successfully added given data to the frame.
OT_ERROR_NO_BUFS Insufficient buffer space available to add the byte.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameFeedData(), Encoder::kPackFormatBufferSize, Encoder::mNcpBuffer, OT_ERROR_NO_BUFS, OT_ERROR_NONE, spinel_datatype_vpack(), and VerifyOrExit.
Referenced by Encoder::WriteData().
OpenStruct()
otError OpenStruct (void)
This method opens a struct in the current input frame.
After a successful call to this method, all the subsequent Write<SomeType>() methods add the field/value to the current open struct until the struct is closed using CloseStruct() method. Structures can be nested. Up to kMaxNestedStructs nested structs can be opened at the same time.
Before using this method BeginFrame() must be called to start and prepare a new input frame. Otherwise, this method does nothing and returns error status OT_ERROR_INVALID_STATE.
If no buffer space is available, this method will discard and clear the frame and return error status OT_ERROR_NO_BUFS.
Return values
OT_ERROR_NONE Successfully opened the struct.
OT_ERROR_NO_BUFS Insufficient buffer space available to open the struct.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame or if we reached the maximum number of nested open structures.
References Buffer::InFrameFeedByte(), Buffer::InFrameGetPosition(), Encoder::kMaxNestedStructs, Encoder::mNcpBuffer, Encoder::mNumOpenStructs, Encoder::mStructPosition, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by NcpBase::HandlePropertyGet(), and Encoder::WriteData().
CloseStruct()
otError CloseStruct (void)
This method closes the most recently opened struct (using OpenStruct()) in the current input frame.
Each call to CloseStruct() must correspond to an earlier successfully opened struct. If a frame is ended using EndFrame() with remaining open structs, the EndFrame() method will close all the remaining structs.
If no buffer space is available, this method will discard and clear the frame and return error status OT_ERROR_NO_BUFS.
Return values
OT_ERROR_NONE Successfully closed the most recently opened struct.
OT_ERROR_NO_BUFS Insufficient buffer space available to open the struct.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame or if there is no open struct to close
References Buffer::InFrameGetDistance(), Buffer::InFrameOverwrite(), Encoder::mNcpBuffer, Encoder::mNumOpenStructs, Encoder::mStructPosition, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by Encoder::EndFrame(), NcpBase::HandlePropertyGet(), and Encoder::WriteData().
SavePosition()
otError SavePosition (void)
This method saves the current write position in the input frame.
The saved position can later be used to discard a portion of written/encoded frame and move the write pointer back to the saved position (using ResetToSaved()).
Return values
OT_ERROR_NONE Successfully saved current write position in aPosition.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
References Buffer::InFrameGetPosition(), Encoder::mNcpBuffer, Encoder::mNumOpenStructs, Encoder::mSavedNumOpenStructs, Encoder::mSavedPosition, OT_ERROR_NONE, and SuccessOrExit.
Referenced by Encoder::BeginFrame(), and Encoder::WriteData().
ResetToSaved()
otError ResetToSaved (void)
This method resets the write position of input frame back to a previously saved position. Any added content after the write position is discarded.
The saved position must belong to the same input frame saved earlier with SavePosition(). This method cannot be used if the input frame has an added otMessage.
Return values
OT_ERROR_NONE Successfully reset the write position of current input frame.
OT_ERROR_INVALID_STATE BeginFrame() has not been called earlier to start the frame.
OT_ERROR_INVALID_ARGS The saved position is not valid (does not belong to same input frame), or the input frame has an added otMessage.
References Buffer::InFrameReset(), Encoder::mNcpBuffer, Encoder::mNumOpenStructs, Encoder::mSavedNumOpenStructs, Encoder::mSavedPosition, OT_ERROR_NONE, and SuccessOrExit.
Referenced by Encoder::OverwriteWithLastStatusError(), and Encoder::WriteData().
Field Documentation
mNcpBuffer
Spinel::Buffer& mNcpBuffer private
Referenced by Encoder::BeginFrame(), Encoder::CloseStruct(), Encoder::EndFrame(), Encoder::OpenStruct(), Encoder::ResetToSaved(), Encoder::SavePosition(), Encoder::WriteBool(), Encoder::WriteData(), Encoder::WritePacked(), Encoder::WriteUint16(), Encoder::WriteUint32(), Encoder::WriteUint64(), Encoder::WriteUint8(), Encoder::WriteUtf8(), and Encoder::WriteVPacked().
mStructPosition
Spinel::Buffer::WritePosition mStructPosition[kMaxNestedStructs] private
Referenced by Encoder::CloseStruct(), and Encoder::OpenStruct().
mNumOpenStructs
uint8_t mNumOpenStructs private
Referenced by Encoder::BeginFrame(), Encoder::CloseStruct(), Encoder::EndFrame(), Encoder::OpenStruct(), Encoder::ResetToSaved(), and Encoder::SavePosition().
mSavedNumOpenStructs
uint8_t mSavedNumOpenStructs private
Referenced by Encoder::ResetToSaved(), and Encoder::SavePosition().
mSavedPosition
Spinel::Buffer::WritePosition mSavedPosition private
Referenced by Encoder::ResetToSaved(), and Encoder::SavePosition().
The documentation for this class was generated from the following files:
spinel_encoder.hpp
spinel_encoder.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale