OpenThread: HasRouteEntry Class Reference
HasRouteEntry Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Member Functions
uint8_t GetFlags (void) const
HasRouteEntry * GetNext (void)
const HasRouteEntry * GetNext (void) const
int8_t GetPreference (void) const
uint16_t GetRloc (void) const
void Init (void)
bool IsNat64 (void) const
void SetFlags (uint8_t aFlags)
void SetRloc (uint16_t aRloc16)
Public Member Functions inherited from Equatable< HasRouteEntry >
bool operator== (const HasRouteEntry &aOther) const
Public Member Functions inherited from Unequatable< HasRouteEntry >
bool operator!= (const HasRouteEntry &aOther) const
Static Public Member Functions
static uint8_t FlagsWithoutPreference (uint8_t aFlags)
static int8_t PreferenceFromFlags (uint8_t aFlags)
Private Attributes
uint8_t mFlags
uint16_t mRloc
Static Private Attributes
static constexpr uint8_t kNat64Flag = 1 << 5
static constexpr uint8_t kPreferenceMask = 3 << kPreferenceOffset
static constexpr uint8_t kPreferenceOffset = 6
Friends
class ExternalRouteConfig
Detailed Description
This class implements Has Route TLV entry generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the header.
References ot::Mac::kShortAddrInvalid.
GetRloc()
uint16_t GetRloc (void) const inline
This method returns the RLOC16 value.
Returns
The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by LeaderBase::ExternalRouteLookup(), NetworkData::Iterate(), and ExternalRouteConfig::SetFrom().
SetRloc()
void SetRloc (uint16_t aRloc16) inline
This method sets the RLOC16 value.
Parameters
[in] aRloc16 The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
GetPreference()
int8_t GetPreference (void) const inline
This method returns the Preference value.
Returns
The preference value.
Referenced by LeaderBase::ExternalRouteLookup().
GetFlags()
uint8_t GetFlags (void) const inline
This method gets the Flags value.
Returns
The Flags value.
Referenced by ExternalRouteConfig::SetFrom().
SetFlags()
void SetFlags (uint8_t aFlags) inline
This method sets the Flags value.
Parameters
[in] aFlags The Flags value.
IsNat64()
bool IsNat64 (void) const inline
This method indicates whether or not the NAT64 flag is set.
Return values
TRUE If the NAT64 flag is set.
FALSE If the NAT64 flag is not set.
GetNext() [1/2]
HasRouteEntry* GetNext (void) inline
This method returns a pointer to the next HasRouteEntry.
Returns
A pointer to the next HasRouteEntry.
Referenced by LeaderBase::ExternalRouteLookup(), and MutableNetworkData::RemoveTemporaryDataIn().
GetNext() [2/2]
const HasRouteEntry* GetNext (void) const inline
This method returns a pointer to the next HasRouteEntry.
Returns
A pointer to the next HasRouteEntry.
FlagsWithoutPreference()
static uint8_t FlagsWithoutPreference (uint8_t aFlags) inline static
This static method returns an updated flags bitmask by removing the preference bits (sets them to zero) from a given flags bitmask.
Parameters
[in] aFlags The flags bitmask.
Returns
An updated version aFlags with preference bits cleared.
PreferenceFromFlags()
static int8_t PreferenceFromFlags (uint8_t aFlags) inline static
This static method gets the preference field from a flags bitmask.
Parameters
[in] aFlags The flags.
Returns
The preference field from the aFlags.
References ot::NetworkData::RoutePreferenceFromValue().
Friends And Related Function Documentation
ExternalRouteConfig
friend class ExternalRouteConfig friend
Field Documentation
kPreferenceOffset
constexpr uint8_t kPreferenceOffset = 6 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags(), and ExternalRouteConfig::SetFromTlvFlags().
kPreferenceMask
constexpr uint8_t kPreferenceMask = 3 << kPreferenceOffset static private
kNat64Flag
constexpr uint8_t kNat64Flag = 1 << 5 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags(), and ExternalRouteConfig::SetFromTlvFlags().
mRloc
uint16_t mRloc private
mFlags
uint8_t mFlags private
The documentation for this class was generated from the following file:
network_data_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale