OpenThread: ServiceConfig Class Reference
ServiceConfig Class Reference
#include <network_data_types.hpp>
Data Structures
class ServerConfig
Public Member Functions
const ServerConfig & GetServerConfig (void) const
ServerConfig & GetServerConfig (void)
void GetServiceData (ServiceData &aServiceData) const
bool operator== (const ServiceConfig &aOther) const
Public Member Functions inherited from Clearable< ServiceConfig >
void Clear (void)
Public Member Functions inherited from Unequatable< ServiceConfig >
bool operator!= (const ServiceConfig &aOther) const
Private Member Functions
void SetFrom (const ServiceTlv &aServiceTlv, const ServerTlv &aServerTlv)
Friends
class NetworkData
Additional Inherited Members
Data Fields inherited from otServiceConfig
uint32_t mEnterpriseNumber
IANA Enterprise Number.
otServerConfig mServerConfig
The Server configuration.
uint8_t mServiceData [OT_SERVICE_DATA_MAX_SIZE]
Service data bytes.
uint8_t mServiceDataLength
Length of service data.
uint8_t mServiceId
Service ID (when iterating over the Network Data).
Detailed Description
This type represents a Service configuration.
Member Function Documentation
GetServiceData()
void GetServiceData (ServiceData & aServiceData) const inline
This method gets the Service Data.
Parameters
[out] aServiceData A reference to a ServiceData to return the data.
References Data< kDataLengthType >::Init().
Referenced by LeaderBase::GetServiceId().
GetServerConfig() [1/2]
const ServerConfig& GetServerConfig (void) const inline
This method gets the Server configuration.
Returns
The Server configuration.
Referenced by NetworkData::ContainsService(), and ServiceConfig::operator==().
GetServerConfig() [2/2]
ServerConfig& GetServerConfig (void) inline
This method gets the Server configuration.
Returns
The Server configuration.
References ot::DefineCoreType(), Equatable< OnMeshPrefixConfig >::operator==(), and OnMeshPrefixConfig::SetFrom().
operator==()
bool operator== (const ServiceConfig & aOther) const
This method overloads operator == to evaluate whether or not two ServiceConfig instances are equal.
Parameters
[in] aOther The other ServiceConfig instance to compare with.
Return values
TRUE If the two ServiceConfig instances are equal.
FALSE If the two ServiceConfig instances are not equal.
References ServiceConfig::GetServerConfig(), otServiceConfig::mEnterpriseNumber, otServiceConfig::mServiceData, and otServiceConfig::mServiceDataLength.
SetFrom()
void SetFrom (const ServiceTlv & aServiceTlv, const ServerTlv & aServerTlv) private
References Clearable< OnMeshPrefixConfig >::Clear(), Data< kDataLengthType >::CopyBytesTo(), ServiceTlv::GetEnterpriseNumber(), Data< kDataLengthType >::GetLength(), ServiceTlv::GetServiceData(), and ServiceTlv::GetServiceId().
Referenced by NetworkData::Iterate().
Friends And Related Function Documentation
NetworkData
friend class NetworkData friend
The documentation for this class was generated from the following files:
network_data_types.hpp
network_data_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale