OpenThread: ExtensionHeader Class Reference
ExtensionHeader Class Reference
Core-ipv6 » IPv6
#include <ip6_headers.hpp>
Public Member Functions
uint8_t GetLength (void) const
uint8_t GetNextHeader (void) const
void SetLength (uint8_t aLength)
void SetNextHeader (uint8_t aNextHeader)
Private Attributes
uint8_t mLength
uint8_t mNextHeader
Detailed Description
This class implements IPv6 Extension Header generation and processing.
Member Function Documentation
GetNextHeader()
uint8_t GetNextHeader (void) const inline
This method returns the IPv6 Next Header value.
Returns
The IPv6 Next Header value.
References Header::mNextHeader.
Referenced by Lowpan::CompressExtensionHeader(), Ip6::HandleExtensionHeaders(), and Ip6::RemoveMplOption().
SetNextHeader()
void SetNextHeader (uint8_t aNextHeader) inline
This method sets the IPv6 Next Header value.
Parameters
[in] aNextHeader The IPv6 Next Header value.
References Header::mNextHeader.
Referenced by Ip6::AddMplOption().
GetLength()
uint8_t GetLength (void) const inline
This method returns the IPv6 Header Extension Length value.
Returns
The IPv6 Header Extension Length value.
Referenced by Lowpan::CompressExtensionHeader(), Ip6::HandleOptions(), Ip6::InsertMplOption(), and Ip6::RemoveMplOption().
SetLength()
void SetLength (uint8_t aLength) inline
This method sets the IPv6 Header Extension Length value.
Parameters
[in] aLength The IPv6 Header Extension Length value.
Referenced by Ip6::AddMplOption(), Ip6::InsertMplOption(), and Ip6::RemoveMplOption().
Field Documentation
mNextHeader
uint8_t mNextHeader private
mLength
uint8_t mLength private
The documentation for this class was generated from the following file:
ip6_headers.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale