OpenThread: PendingDatasetManager Class Reference
PendingDatasetManager Class Reference
#include <dataset_manager.hpp>
Public Member Functions
void Clear (void)
void ClearNetwork (void)
PendingDatasetManager (Instance &aInstance)
Error Save (const Dataset::Info &aDatasetInfo)
Error Save (const otOperationalDatasetTlvs &aDataset)
Error Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Error Save (const Dataset &aDataset)
Public Member Functions inherited from DatasetManager
Error ApplyConfiguration (void) const
Error GetChannelMask (Mac::ChannelMask &aChannelMask) const
const Timestamp * GetTimestamp (void) const
void HandleDetach (void)
Error Read (Dataset &aDataset) const
Error Read (Dataset::Info &aDatasetInfo) const
Error Read (otOperationalDatasetTlvs &aDataset) const
Error Restore (void)
Error SendGetRequest (const Dataset::Components &aDatasetComponents, const uint8_t *aTlvTypes, uint8_t aLength, const otIp6Address *aAddress) const
Error SendSetRequest (const Dataset::Info &aDatasetInfo, const uint8_t *aTlvs, uint8_t aLength, otDatasetMgmtSetCallback aCallback, void *aContext)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void HandleDelayTimer (void)
void HandleGet (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleTimer (void)
void StartDelayTimer (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleDelayTimer (Timer &aTimer)
static void HandleGet (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleTimer (Timer &aTimer)
Private Attributes
TimerMilli mDelayTimer
Coap::Resource mResourceGet
Additional Inherited Members
Protected Member Functions inherited from DatasetManager
void Clear (void)
DatasetManager (Instance &aInstance, Dataset::Type aType, TimerMilli::Handler aTimerHandler)
Dataset::Type GetType (void) const
void HandleGet (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleNetworkUpdate (void)
void HandleTimer (void)
Error Save (const Dataset &aDataset)
Error Save (const Dataset::Info &aDatasetInfo)
Error Save (const otOperationalDatasetTlvs &aDataset)
Error Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Error SaveLocal (const Dataset &aDataset)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Protected Attributes inherited from DatasetManager
DatasetLocal mLocal
Timestamp mTimestamp
bool mTimestampValid: 1
ot::MeshCoP::DatasetManager::DatasetTlv OT_TOOL_PACKED_END
Constructor & Destructor Documentation
PendingDatasetManager()
PendingDatasetManager (Instance & aInstance) explicit
This constructor initializes the PendingDatasetManager object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References PendingDatasetManager::mResourceGet.
Member Function Documentation
Clear()
void Clear (void)
This method clears the Pending Operational Dataset.
This method also stops the Delay Timer if it was active.
References DatasetManager::Clear(), PendingDatasetManager::mDelayTimer, and TimerMilli::Stop().
Referenced by PendingDatasetManager::HandleDelayTimer().
ClearNetwork()
void ClearNetwork (void)
This method clears the network Pending Operational Dataset.
This method also stops the Delay Timer if it was active.
References Clearable< Type >::Clear(), IgnoreError(), DatasetManager::mTimestamp, DatasetManager::mTimestampValid, and DatasetManager::Save().
Save() [1/4]
Error Save (const Dataset::Info & aDatasetInfo)
This method saves the Operational Dataset in non-volatile memory.
This method also starts the Delay Timer.
Parameters
[in] aDatasetInfo The Operational Dataset as Dataset::Info.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References DatasetManager::Save(), PendingDatasetManager::StartDelayTimer(), and SuccessOrExit.
Referenced by PendingDatasetManager::HandleDelayTimer().
Save() [2/4]
Error Save (const otOperationalDatasetTlvs & aDataset)
This method saves the Operational Dataset in non-volatile memory.
This method also starts the Delay Timer.
Parameters
[in] aDataset The Operational Dataset.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References DatasetManager::Save(), PendingDatasetManager::StartDelayTimer(), and SuccessOrExit.
Save() [3/4]
Error Save (const Timestamp & aTimestamp, const Message & aMessage, uint16_t aOffset, uint8_t aLength)
This method sets the Operational Dataset for the partition.
This method also updates the non-volatile version if the partition's Operational Dataset is newer.
This method also starts the Delay Timer.
Parameters
[in] aTimestamp The timestamp for the Operational Dataset.
[in] aMessage The message buffer.
[in] aOffset The offset where the Operational Dataset begins.
[in] aLength The length of the Operational Dataset.
References ot::kErrorNone, Dataset::kPending, Dataset::ReadFromMessage(), DatasetManager::Save(), Dataset::SetTimestamp(), PendingDatasetManager::StartDelayTimer(), and SuccessOrExit.
Save() [4/4]
Error Save (const Dataset & aDataset)
This method saves the Operational Dataset in non-volatile memory.
Parameters
[in] aDataset The Operational Dataset.
Return values
kErrorNone Successfully applied configuration.
kErrorParse The dataset has at least one TLV with invalid format.
References DatasetManager::SaveLocal(), PendingDatasetManager::StartDelayTimer(), and SuccessOrExit.
StartDelayTimer()
void StartDelayTimer (void) private
References DelayTimerTlv::GetDelayTimer(), Dataset::GetTlv(), Dataset::GetUpdateTime(), IgnoreError(), Timer::kMaxDelay, LogInfo, PendingDatasetManager::mDelayTimer, DatasetManager::Read(), TimerMilli::StartAt(), and TimerMilli::Stop().
Referenced by PendingDatasetManager::Save().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and PendingDatasetManager::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) inline private
References DatasetManager::HandleGet(), and DatasetManager::HandleTimer().
Referenced by PendingDatasetManager::HandleTimer().
HandleDelayTimer() [1/2]
void HandleDelayTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and PendingDatasetManager::HandleDelayTimer().
HandleDelayTimer() [2/2]
void HandleDelayTimer (void) private
References PendingDatasetManager::Clear(), Dataset::ConvertToActive(), ExitNow, DelayTimerTlv::GetDelayTimer(), Timer::GetFireTime(), Dataset::GetTlv(), Dataset::GetUpdateTime(), IgnoreError(), LogInfo, PendingDatasetManager::mDelayTimer, DatasetManager::Read(), PendingDatasetManager::Save(), and TimerMilli::StartAt().
Referenced by PendingDatasetManager::HandleDelayTimer().
HandleGet() [1/2]
void HandleGet (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References ot::AsCoapMessage(), and ot::AsCoreType().
HandleGet() [2/2]
void HandleGet (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) const private
References DatasetManager::HandleGet().
Field Documentation
mDelayTimer
TimerMilli mDelayTimer private
Referenced by PendingDatasetManager::Clear(), PendingDatasetManager::HandleDelayTimer(), and PendingDatasetManager::StartDelayTimer().
mResourceGet
Coap::Resource mResourceGet private
Referenced by PendingDatasetManager::PendingDatasetManager().
The documentation for this class was generated from the following files:
dataset_manager.hpp
dataset_manager.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale