OpenThread: AesEcb Class Reference
AesEcb Class Reference
Core-security
#include <aes_ecb.hpp>
Public Member Functions
AesEcb (void)
void Encrypt (const uint8_t aInput[kBlockSize], uint8_t aOutput[kBlockSize])
void SetKey (const Key &aKey)
~AesEcb (void)
Static Public Attributes
static constexpr uint8_t kBlockSize = 16
AES-128 block size (bytes).
Private Member Functions
OT_DEFINE_ALIGNED_VAR (mContextStorage, kAesContextSize, uint64_t)
Private Attributes
otCryptoContext mContext
Detailed Description
This class implements AES ECB computation.
Constructor & Destructor Documentation
AesEcb()
AesEcb (void)
Constructor to initialize the mbedtls_aes_context.
References AesEcb::mContext, otCryptoContext::mContext, otCryptoContext::mContextSize, otPlatCryptoAesInit(), and SuccessOrAssert.
~AesEcb()
~AesEcb (void)
Destructor to free the mbedtls_aes_context.
References AesEcb::mContext, otPlatCryptoAesFree(), and SuccessOrAssert.
Member Function Documentation
SetKey()
void SetKey (const Key & aKey)
This method sets the key.
Parameters
[in] aKey Crypto Key used for ECB operation
References AesEcb::mContext, otPlatCryptoAesSetKey(), and SuccessOrAssert.
Referenced by AesCcm::SetKey().
Encrypt()
void Encrypt (const uint8_t aInput[kBlockSize], uint8_t aOutput[kBlockSize])
This method encrypts data.
Parameters
[in] aInput A pointer to the input buffer.
[out] aOutput A pointer to the output buffer.
References AesEcb::mContext, otPlatCryptoAesEncrypt(), and SuccessOrAssert.
Referenced by AesCcm::Finalize(), AesCcm::Header(), AesCcm::Init(), and AesCcm::Payload().
OT_DEFINE_ALIGNED_VAR()
OT_DEFINE_ALIGNED_VAR (mContextStorage , kAesContextSize , uint64_t) private
Field Documentation
kBlockSize
constexpr uint8_t kBlockSize = 16 static
AES-128 block size (bytes).
mContext
otCryptoContext mContext private
Referenced by AesEcb::AesEcb(), AesEcb::Encrypt(), AesEcb::SetKey(), and AesEcb::~AesEcb().
The documentation for this class was generated from the following files:
aes_ecb.hpp
aes_ecb.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale