OpenThread: Output Class Reference
Output Class Reference
#include <cli_output.hpp>
Public Member Functions
otInstance * GetInstancePtr (void)
Output (otInstance *aInstance, otCliOutputCallback aCallback, void *aCallbackContext)
void OutputBytes (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytes (const uint8_t(&aBytes)[kBytesLength])
void OutputBytesLine (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytesLine (const uint8_t(&aBytes)[kBytesLength])
template<typename Cli , uint16_t kLength>
void OutputCommandTable (const CommandEntry< Cli >(&aCommandTable)[kLength])
void OutputEnabledDisabledStatus (bool aEnabled)
void OutputExtAddress (const otExtAddress &aExtAddress)
void OutputExtAddressLine (const otExtAddress &aExtAddress)
void OutputFormat (const char *aFormat,...)
void OutputFormat (uint8_t aIndentSize, const char *aFormat,...)
void OutputLine (const char *aFormat,...)
void OutputLine (uint8_t aIndentSize, const char *aFormat,...)
void OutputSpaces (uint8_t aCount)
template<uint8_t kTableNumColumns>
void OutputTableHeader (const char *const (&aTitles)[kTableNumColumns], const uint8_t(&aWidths)[kTableNumColumns])
template<uint8_t kTableNumColumns>
void OutputTableSeparator (const uint8_t(&aWidths)[kTableNumColumns])
Protected Member Functions
void LogInput (const Arg *)
void OutputFormatV (const char *aFormat, va_list aArguments)
void SetEmittingCommandOutput (bool)
Protected Member Functions inherited from OutputBase
OutputBase (void)=default
Private Member Functions
void OutputTableHeader (uint8_t aNumColumns, const char *const aTitles[], const uint8_t aWidths[])
void OutputTableSeparator (uint8_t aNumColumns, const uint8_t aWidths[])
Private Attributes
otCliOutputCallback mCallback
void * mCallbackContext
otInstance * mInstance
Static Private Attributes
static constexpr uint16_t kInputOutputLogStringSize = OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_LOG_STRING_SIZE
Additional Inherited Members
Public Types inherited from OutputBase
typedef Utils::CmdLineParser::Arg Arg
An argument.
Static Public Member Functions inherited from OutputBase
template<typename EnumType , uint16_t kLength>
static const char * Stringify (EnumType aEnum, const char *const (&aTable)[kLength], const char *aNotFound=kUnknownString)
Static Public Attributes inherited from OutputBase
static const char kUnknownString [] = "unknown"
Detailed Description
This class provides CLI output helper methods.
Constructor & Destructor Documentation
Output()
Output (otInstance * aInstance, otCliOutputCallback aCallback, void * aCallbackContext)
This constructor initializes the Output object.
Parameters
[in] aInstance A pointer to OpenThread instance.
[in] aCallback A pointer to an otCliOutputCallback to deliver strings to the CLI console.
[in] aCallbackContext An arbitrary context to pass in when invoking aCallback.
Member Function Documentation
GetInstancePtr()
otInstance* GetInstancePtr (void) inline
This method returns the pointer to OpenThread instance.
Returns
The pointer to the OpenThread instance.
Referenced by Interpreter::Interpreter(), Interpreter::LinkModeToString(), Interpreter::Process(), Interpreter::ProcessGet(), Interpreter::ProcessLine(), Interpreter::ProcessSet(), and Interpreter::SetUserCommands().
OutputFormat() [1/2]
void OutputFormat (const char * aFormat, ...)
This method delivers a formatted output string to the CLI console.
Parameters
[in] aFormat A pointer to the format string.
[in] ... A variable list of arguments to format.
References Output::OutputFormatV().
Referenced by Interpreter::LinkModeToString(), Output::OutputBytes(), Output::OutputEnabledDisabledStatus(), Output::OutputLine(), Interpreter::OutputPrompt(), Output::OutputSpaces(), Output::OutputTableHeader(), Output::OutputTableSeparator(), and Interpreter::SetUserCommands().
OutputFormat() [2/2]
void OutputFormat (uint8_t aIndentSize, const char * aFormat, ...)
This method delivers a formatted output string to the CLI console (to which it prepends a given number indentation space chars).
Parameters
[in] aIndentSize Number of indentation space chars to prepend to the string.
[in] aFormat A pointer to the format string.
[in] ... A variable list of arguments to format.
References Output::OutputFormatV(), and Output::OutputSpaces().
OutputLine() [1/2]
void OutputLine (const char * aFormat, ...)
This method delivers a formatted output string to the CLI console (to which it also appends newline "\r\n").
Parameters
[in] aFormat A pointer to the format string.
[in] ... A variable list of arguments to format.
References Output::OutputFormat(), and Output::OutputFormatV().
Referenced by otCliPlatLogv(), Output::OutputBytesLine(), Output::OutputEnabledDisabledStatus(), Interpreter::OutputResult(), Output::OutputTableHeader(), Output::OutputTableSeparator(), Interpreter::Process(), Interpreter::ProcessCommand(), Interpreter::ProcessGet(), Interpreter::ProcessLine(), and Interpreter::SetUserCommands().
OutputLine() [2/2]
void OutputLine (uint8_t aIndentSize, const char * aFormat, ...)
This method delivers a formatted output string to the CLI console (to which it prepends a given number indentation space chars and appends newline "\r\n").
Parameters
[in] aIndentSize Number of indentation space chars to prepend to the string.
[in] aFormat A pointer to the format string.
[in] ... A variable list of arguments to format.
References Output::OutputFormat(), Output::OutputFormatV(), and Output::OutputSpaces().
OutputSpaces()
void OutputSpaces (uint8_t aCount)
This method outputs a given number of space chars to the CLI console.
Parameters
[in] aCount Number of space chars to output.
References Output::OutputFormat().
Referenced by Output::OutputFormat(), and Output::OutputLine().
OutputBytes() [1/2]
void OutputBytes (const uint8_t * aBytes, uint16_t aLength)
This method outputs a number of bytes to the CLI console as a hex string.
Parameters
[in] aBytes A pointer to data which should be printed.
[in] aLength aBytes length.
References Output::OutputFormat().
Referenced by otCliOutputBytes(), Output::OutputBytesLine(), Output::OutputEnabledDisabledStatus(), and Interpreter::SetUserCommands().
OutputBytesLine() [1/2]
void OutputBytesLine (const uint8_t * aBytes, uint16_t aLength)
This method outputs a number of bytes to the CLI console as a hex string and at the end it also outputs newline "\r\n".
Parameters
[in] aBytes A pointer to data which should be printed.
[in] aLength aBytes length.
References Output::OutputBytes(), and Output::OutputLine().
Referenced by Interpreter::SetUserCommands().
OutputBytes() [2/2]
void OutputBytes (const uint8_t(&) aBytes[kBytesLength]) inline
This method outputs a number of bytes to the CLI console as a hex string.
Template Parameters
kBytesLength The length of aBytes array.
Parameters
[in] aBytes A array of kBytesLength bytes which should be printed.
OutputBytesLine() [2/2]
void OutputBytesLine (const uint8_t(&) aBytes[kBytesLength]) inline
This method outputs a number of bytes to the CLI console as a hex string and at the end it also outputs newline "\r\n".
Template Parameters
kBytesLength The length of aBytes array.
Parameters
[in] aBytes A array of kBytesLength bytes which should be printed.
OutputExtAddress()
void OutputExtAddress (const otExtAddress & aExtAddress) inline
This method outputs an Extended MAC Address to the CLI console.
param[in] aExtAddress The Extended MAC Address to output.
References otExtAddress::m8.
Referenced by Interpreter::SetUserCommands().
OutputExtAddressLine()
void OutputExtAddressLine (const otExtAddress & aExtAddress) inline
This method outputs an Extended MAC Address to the CLI console and at the end it also outputs newline "\r\n".
param[in] aExtAddress The Extended MAC Address to output.
References otExtAddress::m8.
Referenced by Interpreter::SetUserCommands().
OutputEnabledDisabledStatus()
void OutputEnabledDisabledStatus (bool aEnabled)
This method outputs "Enabled" or "Disabled" status to the CLI console (it also appends newline "\r\n").
Parameters
[in] aEnabled A boolean indicating the status. TRUE outputs "Enabled", FALSE outputs "Disabled".
References otIp6NetworkPrefix::m8, otDnsTxtEntry::mKey, otDnsTxtEntry::mValue, otDnsTxtEntry::mValueLength, OT_ERROR_NONE, OT_IP6_ADDRESS_STRING_SIZE, OT_IP6_PREFIX_STRING_SIZE, OT_IP6_SOCK_ADDR_STRING_SIZE, otDnsGetNextTxtEntry(), otDnsInitTxtEntryIterator(), otIp6AddressToString(), otIp6PrefixToString(), otIp6SockAddrToString(), Output::OutputBytes(), Output::OutputFormat(), and Output::OutputLine().
Referenced by Interpreter::SetUserCommands().
OutputTableHeader() [1/2]
void OutputTableHeader (const char *const (&) aTitles[kTableNumColumns], const uint8_t(&) aWidths[kTableNumColumns]) inline
This method outputs a table header to the CLI console.
An example of the table header format:
| Title1 | Title2 |Title3| Title4 | +--------—+-----—+---—+-------------------—+
The titles are left adjusted (extra white space is added at beginning if the column is width enough). The widths are specified as the number chars between two | chars (excluding the char | itself).
Template Parameters
kTableNumColumns The number columns in the table.
Parameters
[in] aTitles An array specifying the table column titles.
[in] aWidths An array specifying the table column widths (in number of chars).
Referenced by Interpreter::SetUserCommands().
OutputTableSeparator() [1/2]
void OutputTableSeparator (const uint8_t(&) aWidths[kTableNumColumns]) inline
This method outputs a table separator to the CLI console.
An example of the table separator:
+--------—+-----—+---—+-------------------—+
The widths are specified as number chars between two + chars (excluding the char + itself).
Template Parameters
kTableNumColumns The number columns in the table.
Parameters
[in] aWidths An array specifying the table column widths (in number of chars).
Referenced by Output::OutputTableHeader().
OutputCommandTable()
void OutputCommandTable (const CommandEntry< Cli >(&) aCommandTable[kLength]) inline
This method outputs the list of commands from a given command table.
Template Parameters
Cli The CLI module type.
kLength The length of command table array.
Parameters
[in] aCommandTable The command table array.
Referenced by Interpreter::ProcessCommand().
OutputFormatV()
void OutputFormatV (const char * aFormat, va_list aArguments) protected
References StringWriter::Append(), String< kSize >::AsCString(), Arg::GetCString(), Arg::IsEmpty(), Output::LogInput(), Output::mCallback, Output::mCallbackContext, OT_LOG_LEVEL_DEBG, otLogCli(), and VerifyOrExit.
Referenced by otCliOutputFormat(), otCliPlatLogv(), Output::OutputFormat(), and Output::OutputLine().
LogInput()
void LogInput (const Arg *) inline protected
Referenced by Output::OutputFormatV(), and Interpreter::ProcessLine().
SetEmittingCommandOutput()
void SetEmittingCommandOutput (bool) inline protected
Referenced by otCliPlatLogv(), and Interpreter::OutputPrompt().
OutputTableHeader() [2/2]
void OutputTableHeader (uint8_t aNumColumns, const char *const aTitles[], const uint8_t aWidths[]) private
References Output::OutputFormat(), Output::OutputLine(), and Output::OutputTableSeparator().
OutputTableSeparator() [2/2]
void OutputTableSeparator (uint8_t aNumColumns, const uint8_t aWidths[]) private
References Output::OutputFormat(), and Output::OutputLine().
Field Documentation
kInputOutputLogStringSize
constexpr uint16_t kInputOutputLogStringSize = OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_LOG_STRING_SIZE static private
mInstance
otInstance* mInstance private
mCallback
otCliOutputCallback mCallback private
Referenced by Output::OutputFormatV().
mCallbackContext
void* mCallbackContext private
Referenced by Output::OutputFormatV().
The documentation for this class was generated from the following files:
cli_output.hpp
cli_output.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale