OpenThread: Mpl Class Reference
Mpl Class Reference
Core-ipv6 » MPL
#include <ip6_mpl.hpp>
Data Structures
struct SeedEntry
Public Member Functions
uint16_t GetSeedId (void) const
void InitOption (OptionMpl &aOption, const Address &aAddress)
Mpl (Instance &aInstance)
Error ProcessOption (Message &aMessage, const Address &aAddress, bool aIsOutbound, bool &aReceive)
void SetMatchingAddress (const Address &aAddress)
void SetSeedId (uint16_t aSeedId)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void HandleSeedSetTimer (void)
Error UpdateSeedSet (uint16_t aSeedId, uint8_t aSequence)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleSeedSetTimer (Timer &aTimer)
Private Attributes
const Address * mMatchingAddress
uint16_t mSeedId
SeedEntry mSeedSet [kNumSeedEntries]
TimerMilli mSeedSetTimer
uint8_t mSequence
Static Private Attributes
static constexpr uint8_t kDataMessageInterval = 64
static constexpr uint16_t kNumSeedEntries = OPENTHREAD_CONFIG_MPL_SEED_SET_ENTRIES
static constexpr uint32_t kSeedEntryLifetime = OPENTHREAD_CONFIG_MPL_SEED_SET_ENTRY_LIFETIME
static constexpr uint32_t kSeedEntryLifetimeDt = 1000
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements MPL message processing.
Constructor & Destructor Documentation
Mpl()
Mpl (Instance & aInstance) explicit
This constructor initializes the MPL object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Mpl::mSeedSet.
Member Function Documentation
InitOption()
void InitOption (OptionMpl & aOption, const Address & aAddress)
This method initializes the MPL option.
Parameters
[in] aOption A reference to the MPL header to initialize.
[in] aAddress A reference to the IPv6 Source Address.
References OptionHeader::GetLength(), OptionMpl::Init(), OptionMpl::kSeedIdLength0, OptionMpl::kSeedIdLength2, Mpl::mMatchingAddress, Mpl::mSeedId, Mpl::mSequence, OptionHeader::SetLength(), OptionMpl::SetSeedId(), OptionMpl::SetSeedIdLength(), and OptionMpl::SetSequence().
Referenced by Ip6::AddMplOption(), and Ip6::InsertMplOption().
ProcessOption()
Error ProcessOption (Message & aMessage, const Address & aAddress, bool aIsOutbound, bool & aReceive)
This method processes an MPL option. When the MPL module acts as an MPL Forwarder it disseminates MPL Data Message using Trickle timer expirations. When acts as an MPL Seed it allows to send the first MPL Data Message directly, then sets up Trickle timer expirations for subsequent retransmissions.
Parameters
[in] aMessage A reference to the message.
[in] aAddress A reference to the IPv6 Source Address.
[in] aIsOutbound TRUE if this message was locally generated, FALSE otherwise.
[out] aReceive Set to FALSE if the MPL message is a duplicate and must not go through the receiving process again, untouched otherwise.
Return values
kErrorNone Successfully processed the MPL option.
kErrorDrop The MPL message is a duplicate and should be dropped.
References ExitNow, Message::GetOffset(), OptionMpl::GetSeedId(), OptionMpl::GetSeedIdLength(), OptionMpl::GetSequence(), ot::Encoding::BigEndian::HostSwap16(), ot::kErrorNone, ot::kErrorParse, OptionMpl::kMinLength, OptionMpl::kSeedIdLength0, OptionMpl::kSeedIdLength2, otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::mFields, Message::ReadBytes(), OptionMpl::SetSeedId(), Mpl::UpdateSeedSet(), and VerifyOrExit.
Referenced by Ip6::HandleOptions().
GetSeedId()
uint16_t GetSeedId (void) const inline
This method returns the MPL Seed Id value.
Returns
The MPL Seed Id value.
References OptionMpl::mSeedId.
SetSeedId()
void SetSeedId (uint16_t aSeedId) inline
This method sets the MPL Seed Id value.
Parameters
[in] aSeedId The MPL Seed Id value.
References OptionMpl::mSeedId.
SetMatchingAddress()
void SetMatchingAddress (const Address & aAddress) inline
This method sets the IPv6 matching address, that allows to elide MPL Seed Id.
Parameters
[in] aAddress The reference to the IPv6 matching address.
HandleSeedSetTimer() [1/2]
void HandleSeedSetTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and Mpl::HandleSeedSetTimer().
HandleSeedSetTimer() [2/2]
void HandleSeedSetTimer (void) private
References Message::Clone(), FreeMessageOnError, GetProvider< InstanceGetProvider >::Get(), Time::GetDistantFuture(), Message::GetLength(), TimerMilli::GetNow(), ot::Random::NonCrypto::GetUint8InRange(), IgnoreError(), Mpl::kDataMessageInterval, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNone, Header::kHopLimitFieldOffset, ot::Mle::kMaxRouters, Mpl::kNumSeedEntries, Mpl::kSeedEntryLifetimeDt, Message::kSubTypeMplRetransmission, Mpl::SeedEntry::mLifetime, Mpl::mSeedSet, Mpl::mSeedSetTimer, OT_ASSERT, Message::Read(), Message::SetLength(), Message::SetSubType(), TimerMilli::Start(), SuccessOrAssert, SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Mpl::HandleSeedSetTimer().
UpdateSeedSet()
Error UpdateSeedSet (uint16_t aSeedId, uint8_t aSequence) private
References ExitNow, SerialNumber::IsLess(), Timer::IsRunning(), ot::kErrorDrop, ot::kErrorNone, Mpl::kNumSeedEntries, Mpl::kSeedEntryLifetime, Mpl::kSeedEntryLifetimeDt, Mpl::SeedEntry::mLifetime, Mpl::SeedEntry::mSeedId, Mpl::mSeedId, Mpl::mSeedSet, Mpl::mSeedSetTimer, Mpl::SeedEntry::mSequence, Mpl::mSequence, OT_ASSERT, TimerMilli::Start(), and VerifyOrExit.
Referenced by Mpl::ProcessOption().
Field Documentation
kNumSeedEntries
constexpr uint16_t kNumSeedEntries = OPENTHREAD_CONFIG_MPL_SEED_SET_ENTRIES static private
Referenced by Mpl::HandleSeedSetTimer(), and Mpl::UpdateSeedSet().
kSeedEntryLifetime
constexpr uint32_t kSeedEntryLifetime = OPENTHREAD_CONFIG_MPL_SEED_SET_ENTRY_LIFETIME static private
Referenced by Mpl::UpdateSeedSet().
kSeedEntryLifetimeDt
constexpr uint32_t kSeedEntryLifetimeDt = 1000 static private
Referenced by Mpl::HandleSeedSetTimer(), and Mpl::UpdateSeedSet().
kDataMessageInterval
constexpr uint8_t kDataMessageInterval = 64 static private
Referenced by Mpl::HandleSeedSetTimer().
mSeedSet
SeedEntry mSeedSet[kNumSeedEntries] private
Referenced by Mpl::HandleSeedSetTimer(), Mpl::Mpl(), and Mpl::UpdateSeedSet().
mMatchingAddress
const Address* mMatchingAddress private
Referenced by Mpl::InitOption().
mSeedSetTimer
TimerMilli mSeedSetTimer private
Referenced by Mpl::HandleSeedSetTimer(), and Mpl::UpdateSeedSet().
mSeedId
uint16_t mSeedId private
Referenced by Mpl::InitOption(), and Mpl::UpdateSeedSet().
mSequence
uint8_t mSequence private
Referenced by Mpl::InitOption(), and Mpl::UpdateSeedSet().
The documentation for this class was generated from the following files:
ip6_mpl.hpp
ip6_mpl.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale