OpenThread: Appender Class Reference
Appender Class Reference
#include <appender.hpp>
Public Types
enum Type : uint8_t { kMessage, kBuffer }
Public Member Functions
template<typename ObjectType >
Error Append (const ObjectType &aObject)
Error AppendBytes (const void *aBuffer, uint16_t aLength)
Appender (Message &aMessage)
Appender (uint8_t *aBuffer, uint16_t aSize)
uint16_t GetAppendedLength (void) const
void GetAsData (Data< kWithUint16Length > &aData)
uint8_t * GetBufferStart (void)
Message & GetMessage (void)
Type GetType (void) const
Private Attributes
union {
FrameBuilder mFrameBuilder
struct {
Message * mMessage
uint16_t mStartOffset
} mMessage
} mShared
Type mType
Detailed Description
The Appender class acts as a wrapper over either a Message or a data buffer and provides different flavors of Append() method.
This class helps in construction of message content where the destination can be either a Message or a buffer.
Member Enumeration Documentation
Type
enum Type : uint8_t
This enumeration represent the Appender Type (whether appending to a Message or data buffer).
Enumerator
kMessage
Appender appends to a Message
kBuffer
Appender appends to a buffer.
Constructor & Destructor Documentation
Appender() [1/2]
Appender (Message & aMessage) explicit
This constructor initializes the Appender to append to a Message.
New content is appended to the end of aMessage, growing its length.
Parameters
[in] aMessage The message to append to.
References Message::GetLength(), and Appender::mShared.
Appender() [2/2]
Appender (uint8_t * aBuffer, uint16_t aSize)
This constructor initializes the Appender to append in a given a buffer
New content is append in the buffer starting from aBuffer up to is size aSize. Appender does not allow content to be appended beyond the size of the buffer.
Parameters
[in] aBuffer A pointer to start of buffer.
[in] aSize The maximum size of aBuffer (number of available bytes in buffer).
References Appender::mShared.
Member Function Documentation
GetType()
Type GetType (void) const inline
This method indicates the Appender type (whether appending to a Message or data buffer).
Returns
The type of Appender.
References Appender::AppendBytes(), and Appender::mType.
AppendBytes()
Error AppendBytes (const void * aBuffer, uint16_t aLength)
This method appends bytes to the Appender object
Parameters
[in] aBuffer A pointer to a data buffer (MUST NOT be nullptr) to append.
[in] aLength The number of bytes to append.
Return values
kErrorNone Successfully appended the bytes.
kErrorNoBufs Insufficient available buffers.
References Appender::kBuffer, ot::kErrorNone, Appender::kMessage, Appender::mShared, and Appender::mType.
Referenced by Appender::Append(), TxtEntry::AppendTo(), and Appender::GetType().
Append()
Error Append (const ObjectType & aObject) inline
This method appends an object to the end of the Appender object.
Template Parameters
ObjectType The object type to append to the message.
Parameters
[in] aObject A reference to the object to append to the message.
Return values
kErrorNone Successfully appended the object.
kErrorNoBufs Insufficient available buffers to append aObject.
References Appender::AppendBytes(), and Appender::GetAppendedLength().
Referenced by TxtEntry::AppendEntries(), and TxtEntry::AppendTo().
GetAppendedLength()
uint16_t GetAppendedLength (void) const
This method returns the number of bytes appended so far using Appender methods.
This method can be used independent of the Type of Appender.
Returns
The number of byes appended so far.
References Appender::kBuffer, Appender::kMessage, Appender::mShared, and Appender::mType.
Referenced by Appender::Append(), and TxtEntry::AppendEntries().
GetMessage()
Message& GetMessage (void) inline
This method returns the Message associated with Appender.
This method MUST be used when GetType() == kMessage. Otherwise its behavior is undefined.
Returns
The Message instance associated with Appender.
References Appender::mShared.
GetBufferStart()
uint8_t* GetBufferStart (void) inline
This method returns a pointer to the start of the data buffer associated with Appender.
This method MUST be used when GetType() == kBuffer. Otherwise its behavior is undefined.
Returns
A pointer to the start of the data buffer associated with Appender.
References ot::AsNonConst(), Appender::GetAsData(), and Appender::mShared.
GetAsData()
void GetAsData (Data< kWithUint16Length > & aData)
This method gets the data buffer associated with Appender as a Data.
This method MUST be used when GetType() == kBuffer. Otherwise its behavior is undefined.
[out] aData A reference to a Data to output the data buffer.
References Data< kDataLengthType >::Init(), and Appender::mShared.
Referenced by Appender::GetBufferStart().
Field Documentation
mType
Type mType private
Referenced by Appender::AppendBytes(), Appender::GetAppendedLength(), and Appender::GetType().
mMessage [1/2]
Message* mMessage
mStartOffset
uint16_t mStartOffset
mMessage [2/2]
struct { ... } mMessage
mFrameBuilder
FrameBuilder mFrameBuilder
mShared
union { ... } mShared
Referenced by Appender::AppendBytes(), Appender::Appender(), Appender::GetAppendedLength(), Appender::GetAsData(), Appender::GetBufferStart(), and Appender::GetMessage().
The documentation for this class was generated from the following files:
appender.hpp
appender.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale