OpenThread: MessageQueue Class Reference
MessageQueue Class Reference
Core-coap
#include <coap_message.hpp>
Public Member Functions
Message::Iterator begin (void)
Message::ConstIterator begin (void) const
void Dequeue (Message &aMessage)
void DequeueAndFree (Message &aMessage)
Message::Iterator end (void)
Message::ConstIterator end (void) const
void Enqueue (Message &aMessage)
void Enqueue (Message &aMessage, QueuePosition aPosition)
Message * GetHead (void)
const Message * GetHead (void) const
MessageQueue (void)=default
Public Member Functions inherited from MessageQueue
Message::Iterator begin (void)
Message::ConstIterator begin (void) const
void Dequeue (Message &aMessage)
void DequeueAndFree (Message &aMessage)
void DequeueAndFreeAll (void)
Message::Iterator end (void)
Message::ConstIterator end (void) const
void Enqueue (Message &aMessage)
void Enqueue (Message &aMessage, QueuePosition aPosition)
Message * GetHead (void)
const Message * GetHead (void) const
void GetInfo (Info &aInfo) const
MessageQueue (void)
Additional Inherited Members
Public Types inherited from MessageQueue
typedef otMessageQueueInfo Info
This struct represents info (number of messages/buffers) about a queue.
enum QueuePosition : uint8_t { kQueuePositionHead, kQueuePositionTail }
Data Fields inherited from otMessageQueue
void * mData
Opaque data used by the implementation.
Detailed Description
This class implements a CoAP message queue.
Constructor & Destructor Documentation
MessageQueue()
MessageQueue (void) default
This constructor initializes the message queue.
Member Function Documentation
GetHead() [1/2]
Message* GetHead (void) inline
This method returns a pointer to the first message.
Returns
A pointer to the first message.
References MessageQueue::GetHead().
Referenced by CoapBase::DequeueMessage().
GetHead() [2/2]
const Message* GetHead (void) const inline
This method returns a pointer to the first message.
Returns
A pointer to the first message.
References MessageQueue::GetHead().
Enqueue() [1/2]
void Enqueue (Message & aMessage) inline
This method adds a message to the end of the queue.
Parameters
[in] aMessage The message to add.
References MessageQueue::Enqueue().
Referenced by CoapBase::CopyAndEnqueueMessage(), MessageQueue::Enqueue(), and ResponsesQueue::EnqueueResponse().
Enqueue() [2/2]
void Enqueue (Message & aMessage, QueuePosition aPosition) inline
This method adds a message at a given position (head/tail) of the queue.
Parameters
[in] aMessage The message to add.
[in] aPosition The position (head or tail) where to add the message.
References MessageQueue::Enqueue().
Dequeue()
void Dequeue (Message & aMessage) inline
This method removes a message from the queue.
Parameters
[in] aMessage The message to remove.
References MessageQueue::Dequeue().
Referenced by CoapBase::DequeueMessage().
DequeueAndFree()
void DequeueAndFree (Message & aMessage) inline
This method removes a message from the queue and frees it.
Parameters
[in] aMessage The message to remove and free.
References MessageQueue::DequeueAndFree().
Referenced by ResponsesQueue::DequeueResponse().
begin() [1/2]
Message::Iterator begin (void)
end() [1/2]
Message::Iterator end (void) inline
begin() [2/2]
Message::ConstIterator begin (void) const
end() [2/2]
Message::ConstIterator end (void) const inline
The documentation for this class was generated from the following files:
coap_message.hpp
coap_message.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale