OpenThread: NetworkNameManager Class Reference
NetworkNameManager Class Reference
#include <network_name.hpp>
Public Member Functions
const DomainName & GetDomainName (void) const
const NetworkName & GetNetworkName (void) const
NetworkNameManager (Instance &aInstance)
Error SetDomainName (const char *aNameString)
Error SetDomainName (const NameData &aNameData)
Error SetNetworkName (const char *aNameString)
Error SetNetworkName (const NameData &aNameData)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
Error SignalNetworkNameChange (Error aError)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
DomainName mDomainName
NetworkName mNetworkName
Static Private Attributes
static const char sDomainNameInit [] = "DefaultDomain"
static const char sNetworkNameInit [] = "OpenThread"
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class manages the Network Name value.
Constructor & Destructor Documentation
NetworkNameManager()
NetworkNameManager (Instance & aInstance) explicit
Constructor.
Parameters
[in] aInstance A reference to the OpenThread instance.
References IgnoreError(), NetworkNameManager::sDomainNameInit, NetworkNameManager::SetDomainName(), NetworkNameManager::SetNetworkName(), and NetworkNameManager::sNetworkNameInit.
Member Function Documentation
GetNetworkName()
const NetworkName& GetNetworkName (void) const inline
This method returns the Network Name.
Returns
The Network Name.
SetNetworkName() [1/2]
Error SetNetworkName (const char * aNameString)
This method sets the Network Name.
Parameters
[in] aNameString A pointer to a string character array. Must be null terminated.
Return values
kErrorNone Successfully set the Network Name.
kErrorInvalidArgs Given name is too long.
References NetworkNameManager::mNetworkName, NetworkName::Set(), and NetworkNameManager::SignalNetworkNameChange().
Referenced by Dataset::ApplyConfiguration(), and NetworkNameManager::NetworkNameManager().
SetNetworkName() [2/2]
Error SetNetworkName (const NameData & aNameData)
This method sets the Network Name.
Parameters
[in] aNameData A name data (pointer to char buffer and length).
Return values
kErrorNone Successfully set the Network Name.
kErrorInvalidArgs Given name is too long.
References NetworkNameManager::mNetworkName, NetworkName::Set(), and NetworkNameManager::SignalNetworkNameChange().
GetDomainName()
const DomainName& GetDomainName (void) const inline
This method returns the Thread Domain Name.
Returns
The Thread Domain Name.
SetDomainName() [1/2]
Error SetDomainName (const char * aNameString)
This method sets the Thread Domain Name.
Parameters
[in] aNameString A pointer to a string character array. Must be null terminated.
Return values
kErrorNone Successfully set the Thread Domain Name.
kErrorInvalidArgs Given name is too long.
References ot::kErrorAlready, ot::kErrorNone, NetworkNameManager::mDomainName, and NetworkName::Set().
Referenced by NetworkNameManager::NetworkNameManager().
SetDomainName() [2/2]
Error SetDomainName (const NameData & aNameData)
This method sets the Thread Domain Name.
Parameters
[in] aNameData A name data (pointer to char buffer and length).
Return values
kErrorNone Successfully set the Thread Domain Name.
kErrorInvalidArgs Given name is too long.
References ot::kErrorAlready, ot::kErrorNone, NetworkNameManager::mDomainName, and NetworkName::Set().
SignalNetworkNameChange()
Error SignalNetworkNameChange (Error aError) private
References ot::kErrorAlready, ot::kErrorNone, and ot::kEventThreadNetworkNameChanged.
Referenced by NetworkNameManager::SetNetworkName().
Field Documentation
sNetworkNameInit
const char sNetworkNameInit = "OpenThread" static private
Referenced by NetworkNameManager::NetworkNameManager().
sDomainNameInit
const char sDomainNameInit = "DefaultDomain" static private
Referenced by NetworkNameManager::NetworkNameManager().
mNetworkName
NetworkName mNetworkName private
Referenced by NetworkNameManager::SetNetworkName().
mDomainName
DomainName mDomainName private
Referenced by NetworkNameManager::SetDomainName().
The documentation for this class was generated from the following files:
network_name.hpp
network_name.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale