OpenThread: ChildTableEntry Class Reference
ChildTableEntry Class Reference
MLE » TLVs
#include <network_diagnostic_tlvs.hpp>
Public Member Functions
ChildTableEntry (void)
uint16_t GetChildId (void) const
Mle::DeviceMode GetMode (void) const
uint8_t GetReserved (void) const
uint8_t GetTimeout (void) const
void SetChildId (uint16_t aChildId)
void SetMode (Mle::DeviceMode aMode)
void SetReserved (uint8_t aReserved)
void SetTimeout (uint8_t aTimeout)
Private Attributes
uint8_t mMode
uint16_t mTimeoutRsvChildId
Static Private Attributes
static constexpr uint16_t kChildIdMask = 0x1ff
static constexpr uint16_t kReservedMask = 0x0600
static constexpr uint8_t kReservedOffset = 9
static constexpr uint16_t kTimeoutMask = 0xf800
static constexpr uint8_t kTimeoutOffset = 11
Detailed Description
This class implements Child Table Entry generation and parsing.
Constructor & Destructor Documentation
ChildTableEntry()
ChildTableEntry (void) inline
Default constructor.
Member Function Documentation
GetTimeout()
uint8_t GetTimeout (void) const inline
This method returns the Timeout value.
Returns
The Timeout value.
References ot::Encoding::BigEndian::HostSwap16().
SetTimeout()
void SetTimeout (uint8_t aTimeout) inline
This method sets the Timeout value.
Parameters
[in] aTimeout The Timeout value.
References ot::Encoding::BigEndian::HostSwap16().
GetChildId()
uint16_t GetChildId (void) const inline
This method returns the Child ID value.
Returns
The Child ID value.
References ot::Encoding::BigEndian::HostSwap16().
SetChildId()
void SetChildId (uint16_t aChildId) inline
This method sets the Child ID value.
Parameters
[in] aChildId The Child ID value.
References ot::Encoding::BigEndian::HostSwap16().
GetMode()
Mle::DeviceMode GetMode (void) const inline
This method returns the Device Mode
Returns
The Device Mode
SetMode()
void SetMode (Mle::DeviceMode aMode) inline
This method sets the Device Mode.
Parameters
[in] aMode The Device Mode.
References DeviceMode::Get().
GetReserved()
uint8_t GetReserved (void) const inline
This method returns the Reserved value.
Returns
The Reserved value.
References ot::Encoding::BigEndian::HostSwap16().
SetReserved()
void SetReserved (uint8_t aReserved) inline
This method sets the Reserved value.
Parameters
[in] aReserved The Reserved value.
References ot::Encoding::BigEndian::HostSwap16().
Field Documentation
kTimeoutOffset
constexpr uint8_t kTimeoutOffset = 11 static private
kReservedOffset
constexpr uint8_t kReservedOffset = 9 static private
kTimeoutMask
constexpr uint16_t kTimeoutMask = 0xf800 static private
kReservedMask
constexpr uint16_t kReservedMask = 0x0600 static private
kChildIdMask
constexpr uint16_t kChildIdMask = 0x1ff static private
mTimeoutRsvChildId
uint16_t mTimeoutRsvChildId private
mMode
uint8_t mMode private
The documentation for this class was generated from the following file:
network_diagnostic_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale