OpenThread: Frame Class Reference
Frame Class Reference
Core-mac
#include <mac_frame.hpp>
Public Types
typedef String< kInfoStringSize > InfoString
Public Member Functions
bool GetAckRequest (void) const
uint8_t GetChannel (void) const
Error GetCommandId (uint8_t &aCommandId) const
Error GetDstAddr (Address &aAddress) const
Error GetDstPanId (PanId &aPanId) const
uint8_t GetFcsSize (void) const
uint8_t * GetFooter (void)
const uint8_t * GetFooter (void) const
uint8_t GetFooterLength (void) const
uint16_t GetFrameControlField (void) const
Error GetFrameCounter (uint32_t &aFrameCounter) const
bool GetFramePending (void) const
uint8_t * GetHeader (void)
const uint8_t * GetHeader (void) const
uint8_t GetHeaderLength (void) const
Error GetKeyId (uint8_t &aKeyId) const
Error GetKeyIdMode (uint8_t &aKeyIdMode) const
const uint8_t * GetKeySource (void) const
uint16_t GetLength (void) const
uint16_t GetMaxPayloadLength (void) const
uint16_t GetMtu (void) const
uint8_t * GetPayload (void)
const uint8_t * GetPayload (void) const
uint16_t GetPayloadLength (void) const
uint8_t * GetPsdu (void)
const uint8_t * GetPsdu (void) const
uint16_t GetPsduLength (void) const
Error GetSecurityControlField (uint8_t &aSecurityControlField) const
bool GetSecurityEnabled (void) const
Error GetSecurityLevel (uint8_t &aSecurityLevel) const
uint8_t GetSequence (void) const
Error GetSrcAddr (Address &aAddress) const
Error GetSrcPanId (PanId &aPanId) const
uint8_t GetType (void) const
uint16_t GetVersion (void) const
void InitMacHeader (uint16_t aFcf, uint8_t aSecurityControl)
bool IsAck (void) const
bool IsDataRequestCommand (void) const
bool IsDstAddrPresent () const
bool IsDstPanIdPresent (void) const
bool IsEmpty (void) const
bool IsIePresent (void) const
bool IsPanIdCompressed (void) const
bool IsSrcAddrPresent (void) const
bool IsSrcPanIdPresent (void) const
bool IsVersion2015 (void) const
void SetAckRequest (bool aAckRequest)
void SetChannel (uint8_t aChannel)
Error SetCommandId (uint8_t aCommandId)
void SetDstAddr (ShortAddress aShortAddress)
void SetDstAddr (const ExtAddress &aExtAddress)
void SetDstAddr (const Address &aAddress)
void SetDstPanId (PanId aPanId)
void SetFrameCounter (uint32_t aFrameCounter)
void SetFramePending (bool aFramePending)
void SetKeyId (uint8_t aKeyId)
void SetKeySource (const uint8_t *aKeySource)
void SetLength (uint16_t aLength)
void SetPayloadLength (uint16_t aLength)
void SetSecurityControlField (uint8_t aSecurityControlField)
void SetSequence (uint8_t aSequence)
void SetSrcAddr (ShortAddress aShortAddress)
void SetSrcAddr (const ExtAddress &aExtAddress)
void SetSrcAddr (const Address &aAddress)
Error SetSrcPanId (PanId aPanId)
InfoString ToInfoString (void) const
Error ValidatePsdu (void) const
Static Public Attributes
static constexpr uint8_t k154FcsSize = sizeof(uint16_t)
static constexpr uint8_t kCommandIdSize = sizeof(uint8_t)
static constexpr uint8_t kDsnSize = sizeof(uint8_t)
static constexpr uint16_t kFcfAckRequest = 1 << 5
static constexpr uint16_t kFcfDstAddrExt = 3 << 10
static constexpr uint16_t kFcfDstAddrMask = 3 << 10
static constexpr uint16_t kFcfDstAddrNone = 0 << 10
static constexpr uint16_t kFcfDstAddrShort = 2 << 10
static constexpr uint16_t kFcfFrameAck = 2 << 0
static constexpr uint16_t kFcfFrameBeacon = 0 << 0
static constexpr uint16_t kFcfFrameData = 1 << 0
static constexpr uint16_t kFcfFrameMacCmd = 3 << 0
static constexpr uint16_t kFcfFramePending = 1 << 4
static constexpr uint16_t kFcfFrameTypeMask = 7 << 0
static constexpr uint16_t kFcfFrameVersion2006 = 1 << 12
static constexpr uint16_t kFcfFrameVersion2015 = 2 << 12
static constexpr uint16_t kFcfFrameVersionMask = 3 << 12
static constexpr uint16_t kFcfIePresent = 1 << 9
static constexpr uint16_t kFcfPanidCompression = 1 << 6
static constexpr uint16_t kFcfSecurityEnabled = 1 << 3
static constexpr uint8_t kFcfSize = sizeof(uint16_t)
static constexpr uint16_t kFcfSrcAddrExt = 3 << 14
static constexpr uint16_t kFcfSrcAddrMask = 3 << 14
static constexpr uint16_t kFcfSrcAddrNone = 0 << 14
static constexpr uint16_t kFcfSrcAddrShort = 2 << 14
static constexpr uint8_t kFrameCounterSize = sizeof(uint32_t)
static constexpr uint8_t kImmAckLength = kFcfSize + kDsnSize + k154FcsSize
static constexpr uint16_t kInfoStringSize = 128
Max chars for InfoString (ToInfoString()).
static constexpr uint8_t kKeyIdMode0 = 0 << 3
static constexpr uint8_t kKeyIdMode1 = 1 << 3
static constexpr uint8_t kKeyIdMode2 = 2 << 3
static constexpr uint8_t kKeyIdMode3 = 3 << 3
static constexpr uint8_t kKeyIdModeMask = 3 << 3
static constexpr uint8_t kKeyIndexSize = sizeof(uint8_t)
static constexpr uint8_t kKeySourceSizeMode0 = 0
static constexpr uint8_t kKeySourceSizeMode1 = 0
static constexpr uint8_t kKeySourceSizeMode2 = 4
static constexpr uint8_t kKeySourceSizeMode3 = 8
static constexpr uint8_t kMacCmdAssociationRequest = 1
static constexpr uint8_t kMacCmdAssociationResponse = 2
static constexpr uint8_t kMacCmdBeaconRequest = 7
static constexpr uint8_t kMacCmdCoordinatorRealignment = 8
static constexpr uint8_t kMacCmdDataRequest = 4
static constexpr uint8_t kMacCmdDisassociationNotification = 3
static constexpr uint8_t kMacCmdGtsRequest = 9
static constexpr uint8_t kMacCmdOrphanNotification = 6
static constexpr uint8_t kMacCmdPanidConflictNotification = 5
static constexpr uint8_t kMaxMicSize = kMic128Size
static constexpr uint8_t kMic0Size = 0
static constexpr uint8_t kMic128Size = 128 / CHAR_BIT
static constexpr uint8_t kMic32Size = 32 / CHAR_BIT
static constexpr uint8_t kMic64Size = 64 / CHAR_BIT
static constexpr uint8_t kSecEnc = 4 << 0
static constexpr uint8_t kSecEncMic128 = 7 << 0
static constexpr uint8_t kSecEncMic32 = 5 << 0
static constexpr uint8_t kSecEncMic64 = 6 << 0
static constexpr uint8_t kSecLevelMask = 7 << 0
static constexpr uint8_t kSecMic128 = 3 << 0
static constexpr uint8_t kSecMic32 = 1 << 0
static constexpr uint8_t kSecMic64 = 2 << 0
static constexpr uint8_t kSecNone = 0 << 0
static constexpr uint8_t kSecurityControlSize = sizeof(uint8_t)
Protected Member Functions
uint8_t FindDstAddrIndex (void) const
uint8_t FindDstPanIdIndex (void) const
uint8_t FindPayloadIndex (void) const
uint8_t FindSecurityHeaderIndex (void) const
uint8_t FindSrcAddrIndex (void) const
uint8_t FindSrcPanIdIndex (void) const
uint8_t SkipAddrFieldIndex (void) const
uint8_t SkipSecurityHeaderIndex (void) const
Static Protected Member Functions
static uint8_t CalculateAddrFieldSize (uint16_t aFcf)
static uint8_t CalculateMicSize (uint8_t aSecurityControl)
static uint8_t CalculateSecurityHeaderSize (uint8_t aSecurityControl)
static uint8_t GetKeySourceLength (uint8_t aKeyIdMode)
static bool IsDstAddrPresent (uint16_t aFcf)
static bool IsDstPanIdPresent (uint16_t aFcf)
static bool IsSrcAddrPresent (uint16_t aFcf)
static bool IsSrcPanIdPresent (uint16_t aFcf)
static bool IsVersion2015 (uint16_t aFcf)
Static Protected Attributes
static constexpr uint8_t kInvalidIndex = 0xff
static constexpr uint8_t kInvalidSize = kInvalidIndex
static constexpr uint8_t kMaxPsduSize = kInvalidSize - 1
static constexpr uint8_t kSequenceIndex = kFcfSize
Additional Inherited Members
Data Fields inherited from otRadioFrame
uint8_t mChannel
Channel used to transmit/receive the frame.
union {
struct {
bool mAckedWithFramePending: 1
This indicates if this frame was acknowledged with frame pending set.
bool mAckedWithSecEnhAck: 1
This indicates if this frame was acknowledged with secured enhance ACK.
uint32_t mAckFrameCounter
ACK security frame counter (applicable when mAckedWithSecEnhAck is set).
uint8_t mAckKeyId
ACK security key index (applicable when mAckedWithSecEnhAck is set).
uint8_t mLqi
Link Quality Indicator for received frames.
int8_t mRssi
Received signal strength indicator in dBm for received frames.
uint64_t mTimestamp
} mRxInfo
struct {
const otMacKeyMaterial * mAesKey
The key material used for AES-CCM frame security.
bool mCslPresent: 1
Set to true if CSL header IE is present.
bool mCsmaCaEnabled: 1
Set to true to enable CSMA-CA for this packet, false otherwise.
otRadioIeInfo * mIeInfo
The pointer to the Header IE(s) related information.
bool mIsARetx: 1
Indicates whether the frame is a retransmission or not.
bool mIsHeaderUpdated: 1
bool mIsSecurityProcessed: 1
True if SubMac should skip the AES processing of this frame.
uint8_t mMaxCsmaBackoffs
Maximum number of backoffs attempts before declaring CCA failure.
uint8_t mMaxFrameRetries
Maximum number of retries allowed after a transmission failure.
uint32_t mTxDelay
The delay time for this transmission (based on mTxDelayBaseTime).
uint32_t mTxDelayBaseTime
The base time for the transmission delay.
} mTxInfo
} mInfo
uint16_t mLength
Length of the PSDU.
uint8_t * mPsdu
The PSDU.
uint8_t mRadioType
Radio link type - should be ignored by radio driver.
Detailed Description
This class implements IEEE 802.15.4 MAC frame generation and parsing.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToInfoString() method.
Member Function Documentation
IsEmpty()
bool IsEmpty (void) const inline
This method indicates whether the frame is empty (no payload).
Return values
TRUE The frame is empty (no PSDU payload).
FALSE The frame is not empty.
Referenced by Mac::BeginTransmit(), DataPollSender::HandlePollSent(), MeshForwarder::HandleSentFrame(), Mac::HandleTransmitDone(), and Mac::RecordFrameTransmitStatus().
InitMacHeader()
void InitMacHeader (uint16_t aFcf, uint8_t aSecurityControl)
This method initializes the MAC header.
Parameters
[in] aFcf The Frame Control field.
[in] aSecurityControl The Security Control field.
References OT_ASSERT, and ot::Encoding::BigEndian::WriteUint16().
Referenced by Mac::PrepareBeaconRequest(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
ValidatePsdu()
Error ValidatePsdu (void) const
This method validates the frame.
Return values
kErrorNone Successfully parsed the MAC header.
kErrorParse Failed to parse through the MAC header.
References ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by Mac::HandleReceivedFrame().
GetType()
uint8_t GetType (void) const inline
This method returns the IEEE 802.15.4 Frame Type.
Returns
The IEEE 802.15.4 Frame Type.
Referenced by MeshForwarder::CalcIePresent(), Mac::ConvertBeaconToActiveScanResult(), Mac::HandleReceivedFrame(), MeshForwarder::HandleReceivedFrame(), and Mac::RecordFrameTransmitStatus().
IsAck()
bool IsAck (void) const inline
This method returns whether the frame is an Ack frame.
Return values
TRUE If this is an Ack.
FALSE If this is not an Ack.
GetVersion()
uint16_t GetVersion (void) const inline
This method returns the IEEE 802.15.4 Frame Version.
Returns
The IEEE 802.15.4 Frame Version.
Referenced by TxFrame::GenerateImmAck(), Mac::HandleReceivedFrame(), and Mac::RecordFrameTransmitStatus().
IsVersion2015() [1/2]
bool IsVersion2015 (void) const inline
This method returns if this IEEE 802.15.4 frame's version is 2015.
Returns
TRUE if version is 2015, FALSE otherwise.
References Frame::IsVersion2015().
Referenced by Frame::IsVersion2015(), and Mac::ProcessEnhAckSecurity().
GetSecurityEnabled()
bool GetSecurityEnabled (void) const inline
This method indicates whether or not security is enabled.
Return values
TRUE If security is enabled.
FALSE If security is not enabled.
Referenced by TxFrame::GenerateEnhAck(), Mac::HandleReceivedFrame(), Mac::LogFrameTxFailure(), Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), SubMac::ProcessTransmitSecurity(), Mac::ProcessTransmitSecurity(), DataPollSender::ProcessTxDone(), ThreadLinkInfo::SetFrom(), and SubMac::SignalFrameCounterUsedOnTxDone().
GetFramePending()
bool GetFramePending (void) const inline
This method indicates whether or not the Frame Pending bit is set.
Return values
TRUE If the Frame Pending bit is set.
FALSE If the Frame Pending bit is not set.
Referenced by Mac::BeginTransmit(), Mac::HandleReceivedFrame(), Mac::HandleTransmitDone(), DataPollSender::ProcessRxFrame(), and DataPollSender::ProcessTxDone().
SetFramePending()
void SetFramePending (bool aFramePending)
This method sets the Frame Pending bit.
Parameters
[in] aFramePending The Frame Pending bit.
Referenced by MeshForwarder::PrepareDataFrame(), and MeshForwarder::PrepareEmptyFrame().
GetAckRequest()
bool GetAckRequest (void) const inline
This method indicates whether or not the Ack Request bit is set.
Return values
TRUE If the Ack Request bit is set.
FALSE If the Ack Request bit is not set.
Referenced by Mac::HandleTransmitDone(), SubMac::HandleTransmitStarted(), Mac::RecordFrameTransmitStatus(), SubMac::Send(), and MeshForwarder::UpdateNeighborOnSentFrame().
SetAckRequest()
void SetAckRequest (bool aAckRequest)
This method sets the Ack Request bit.
Parameters
[in] aAckRequest The Ack Request bit.
IsPanIdCompressed()
bool IsPanIdCompressed (void) const inline
This method indicates whether or not the PanId Compression bit is set.
Return values
TRUE If the PanId Compression bit is set.
FALSE If the PanId Compression bit is not set.
Referenced by TxFrame::GenerateEnhAck().
IsIePresent()
bool IsIePresent (void) const inline
This method indicates whether or not IEs present.
Return values
TRUE If IEs present.
FALSE If no IE present.
GetSequence()
uint8_t GetSequence (void) const inline
This method returns the Sequence Number value.
Returns
The Sequence Number value.
Referenced by TxFrame::GenerateEnhAck(), TxFrame::GenerateImmAck(), and Mac::LogFrameTxFailure().
SetSequence()
void SetSequence (uint8_t aSequence) inline
This method sets the Sequence Number value.
Parameters
[in] aSequence The Sequence Number value.
Referenced by Mac::BeginTransmit().
IsDstPanIdPresent() [1/2]
bool IsDstPanIdPresent (void) const inline
This method indicates whether or not the Destination PAN ID is present.
Returns
TRUE if the Destination PAN ID is present, FALSE otherwise.
References Frame::IsDstPanIdPresent().
Referenced by TxFrame::GenerateEnhAck(), Frame::IsDstPanIdPresent(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
GetDstPanId()
Error GetDstPanId (PanId & aPanId) const
This method gets the Destination PAN Identifier.
Parameters
[out] aPanId The Destination PAN Identifier.
Return values
kErrorNone Successfully retrieved the Destination PAN Identifier.
kErrorParse Failed to parse the PAN Identifier.
References ot::kErrorNone, ot::kErrorParse, ot::Encoding::BigEndian::ReadUint16(), and VerifyOrExit.
Referenced by Mac::ConvertBeaconToActiveScanResult(), TxFrame::GenerateEnhAck(), Mac::HandleReceivedFrame(), and ThreadLinkInfo::SetFrom().
SetDstPanId()
void SetDstPanId (PanId aPanId)
This method sets the Destination PAN Identifier.
Parameters
[in] aPanId The Destination PAN Identifier.
References OT_ASSERT, and ot::Encoding::BigEndian::WriteUint16().
Referenced by Mac::PrepareBeaconRequest(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
IsDstAddrPresent() [1/2]
bool IsDstAddrPresent () const inline
This method indicates whether or not the Destination Address is present for this object.
Return values
TRUE If the Destination Address is present.
FALSE If the Destination Address is not present.
References Frame::IsDstAddrPresent().
Referenced by Frame::IsDstAddrPresent().
GetDstAddr()
Error GetDstAddr (Address & aAddress) const
This method gets the Destination Address.
Parameters
[out] aAddress The Destination Address.
Return values
kErrorNone Successfully retrieved the Destination Address.
References ot::kErrorNone, ot::kErrorParse, ExtAddress::kReverseByteOrder, ot::Encoding::BigEndian::ReadUint16(), Address::SetExtended(), Address::SetNone(), Address::SetShort(), and VerifyOrExit.
Referenced by DataPollSender::HandlePollSent(), Mac::HandleReceivedFrame(), MeshForwarder::HandleReceivedFrame(), MeshForwarder::HandleSentFrame(), Mac::HandleTransmitDone(), Mac::ProcessEnhAckSecurity(), and Mac::RecordFrameTransmitStatus().
SetDstAddr() [1/3]
void SetDstAddr (ShortAddress aShortAddress)
This method sets the Destination Address.
Parameters
[in] aShortAddress The Destination Address.
References OT_ASSERT, and ot::Encoding::BigEndian::WriteUint16().
Referenced by Mac::PrepareBeaconRequest(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
SetDstAddr() [2/3]
void SetDstAddr (const ExtAddress & aExtAddress)
This method sets the Destination Address.
Parameters
[in] aExtAddress The Destination Address.
References ExtAddress::CopyTo(), ExtAddress::kReverseByteOrder, and OT_ASSERT.
SetDstAddr() [3/3]
void SetDstAddr (const Address & aAddress)
This method sets the Destination Address.
Parameters
[in] aAddress The Destination Address.
References Address::GetExtended(), Address::GetShort(), Address::GetType(), Address::kTypeExtended, Address::kTypeShort, OT_ASSERT, and OT_UNREACHABLE_CODE.
IsSrcPanIdPresent() [1/2]
bool IsSrcPanIdPresent (void) const inline
This method indicates whether or not the Source Address is present for this object.
Return values
TRUE If the Source Address is present.
FALSE If the Source Address is not present.
References Frame::IsSrcPanIdPresent().
Referenced by TxFrame::GenerateEnhAck(), and Frame::IsSrcPanIdPresent().
GetSrcPanId()
Error GetSrcPanId (PanId & aPanId) const
This method gets the Source PAN Identifier.
Parameters
[out] aPanId The Source PAN Identifier.
Return values
kErrorNone Successfully retrieved the Source PAN Identifier.
References ot::kErrorNone, ot::kErrorParse, ot::Encoding::BigEndian::ReadUint16(), and VerifyOrExit.
Referenced by Mac::ConvertBeaconToActiveScanResult(), TxFrame::GenerateEnhAck(), and ThreadLinkInfo::SetFrom().
SetSrcPanId()
Error SetSrcPanId (PanId aPanId)
This method sets the Source PAN Identifier.
Parameters
[in] aPanId The Source PAN Identifier.
Return values
kErrorNone Successfully set the Source PAN Identifier.
References ot::kErrorNone, ot::kErrorParse, VerifyOrExit, and ot::Encoding::BigEndian::WriteUint16().
Referenced by MeshForwarder::PrepareDataFrame(), and MeshForwarder::PrepareEmptyFrame().
IsSrcAddrPresent() [1/2]
bool IsSrcAddrPresent (void) const inline
This method indicates whether or not the Source Address is present for this object.
Return values
TRUE If the Source Address is present.
FALSE If the Source Address is not present.
References Frame::IsSrcAddrPresent().
Referenced by TxFrame::GenerateEnhAck(), and Frame::IsSrcAddrPresent().
GetSrcAddr()
Error GetSrcAddr (Address & aAddress) const
This method gets the Source Address.
Parameters
[out] aAddress The Source Address.
Return values
kErrorNone Successfully retrieved the Source Address.
References ot::kErrorNone, ot::kErrorParse, ExtAddress::kReverseByteOrder, ot::Encoding::BigEndian::ReadUint16(), Address::SetExtended(), Address::SetNone(), Address::SetShort(), and VerifyOrExit.
Referenced by Mac::ConvertBeaconToActiveScanResult(), TxFrame::GenerateEnhAck(), Mac::HandleReceivedFrame(), MeshForwarder::HandleReceivedFrame(), and Mac::ProcessEnhAckSecurity().
SetSrcAddr() [1/3]
void SetSrcAddr (ShortAddress aShortAddress)
This method sets the Source Address.
Parameters
[in] aShortAddress The Source Address.
References OT_ASSERT, and ot::Encoding::BigEndian::WriteUint16().
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
SetSrcAddr() [2/3]
void SetSrcAddr (const ExtAddress & aExtAddress)
This method sets the Source Address.
Parameters
[in] aExtAddress The Source Address.
References ExtAddress::CopyTo(), ExtAddress::kReverseByteOrder, and OT_ASSERT.
SetSrcAddr() [3/3]
void SetSrcAddr (const Address & aAddress)
This method sets the Source Address.
Parameters
[in] aAddress The Source Address.
References Address::GetExtended(), Address::GetShort(), Address::GetType(), Address::kTypeExtended, Address::kTypeShort, and OT_ASSERT.
GetSecurityControlField()
Error GetSecurityControlField (uint8_t & aSecurityControlField) const
This method gets the Security Control Field.
Parameters
[out] aSecurityControlField The Security Control Field.
Return values
kErrorNone Successfully retrieved the Security Level Identifier.
kErrorParse Failed to find the security control field in the frame.
References ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by TxFrame::GenerateEnhAck().
SetSecurityControlField()
void SetSecurityControlField (uint8_t aSecurityControlField)
This method sets the Security Control Field.
Parameters
[in] aSecurityControlField The Security Control Field.
References OT_ASSERT.
GetSecurityLevel()
Error GetSecurityLevel (uint8_t & aSecurityLevel) const
This method gets the Security Level Identifier.
Parameters
[out] aSecurityLevel The Security Level Identifier.
Return values
kErrorNone Successfully retrieved the Security Level Identifier.
References ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by Mac::ProcessEnhAckSecurity(), and Mac::ProcessReceiveSecurity().
GetKeyIdMode()
Error GetKeyIdMode (uint8_t & aKeyIdMode) const
This method gets the Key Identifier Mode.
Parameters
[out] aKeyIdMode The Key Identifier Mode.
Return values
kErrorNone Successfully retrieved the Key Identifier Mode.
References ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by Mac::HandleReceivedFrame(), Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), SubMac::ProcessTransmitSecurity(), Mac::ProcessTransmitSecurity(), and SubMac::SignalFrameCounterUsedOnTxDone().
GetFrameCounter()
Error GetFrameCounter (uint32_t & aFrameCounter) const
This method gets the Frame Counter.
Parameters
[out] aFrameCounter The Frame Counter.
Return values
kErrorNone Successfully retrieved the Frame Counter.
References ot::kErrorNone, ot::kErrorParse, ot::Encoding::BigEndian::ReadUint32(), and VerifyOrExit.
Referenced by Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), and SubMac::SignalFrameCounterUsedOnTxDone().
SetFrameCounter()
void SetFrameCounter (uint32_t aFrameCounter)
This method sets the Frame Counter.
Parameters
[in] aFrameCounter The Frame Counter.
References OT_ASSERT, and ot::Encoding::BigEndian::WriteUint32().
Referenced by Links::GetTemporaryMacKey(), SubMac::ProcessTransmitSecurity(), and Mac::ProcessTransmitSecurity().
GetKeySource()
const uint8_t * GetKeySource (void) const
This method returns a pointer to the Key Source.
Returns
A pointer to the Key Source.
References OT_ASSERT.
SetKeySource()
void SetKeySource (const uint8_t * aKeySource)
This method sets the Key Source.
Parameters
[in] aKeySource A pointer to the Key Source value.
References OT_ASSERT.
Referenced by Mac::ProcessTransmitSecurity().
GetKeyId()
Error GetKeyId (uint8_t & aKeyId) const
This method gets the Key Identifier.
Parameters
[out] aKeyId The Key Identifier.
Return values
kErrorNone Successfully retrieved the Key Identifier.
References ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by TxFrame::GenerateEnhAck(), Mac::ProcessEnhAckSecurity(), and Mac::ProcessReceiveSecurity().
SetKeyId()
void SetKeyId (uint8_t aKeyId)
This method sets the Key Identifier.
Parameters
[in] aKeyId The Key Identifier.
References OT_ASSERT.
Referenced by SubMac::ProcessTransmitSecurity(), and Mac::ProcessTransmitSecurity().
GetCommandId()
Error GetCommandId (uint8_t & aCommandId) const
This method gets the Command ID.
Parameters
[out] aCommandId The Command ID.
Return values
kErrorNone Successfully retrieved the Command ID.
References ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by Mac::HandleMacCommand().
SetCommandId()
Error SetCommandId (uint8_t aCommandId)
This method sets the Command ID.
Parameters
[in] aCommandId The Command ID.
Return values
kErrorNone Successfully set the Command ID.
References ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by Mac::PrepareBeaconRequest(), and DataPollSender::PrepareDataRequest().
IsDataRequestCommand()
bool IsDataRequestCommand (void) const
This method indicates whether the frame is a MAC Data Request command (data poll).
For 802.15.4-2015 and above frame, the frame should be already decrypted.
Returns
TRUE if frame is a MAC Data Request command, FALSE otherwise.
References SuccessOrExit, and VerifyOrExit.
Referenced by Mac::HandleReceivedFrame().
GetLength()
uint16_t GetLength (void) const inline
This method returns the MAC Frame Length.
Returns
The MAC Frame Length.
Referenced by Mac::HandleReceivedFrame(), and Mac::HandleTransmitDone().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the MAC Frame Length.
Parameters
[in] aLength The MAC Frame Length.
Referenced by Mac::BeginTransmit().
GetHeaderLength()
uint8_t GetHeaderLength (void) const
This method returns the MAC header size.
Returns
The MAC header size.
Referenced by MeshForwarder::PrepareDataFrame().
GetFooterLength()
uint8_t GetFooterLength (void) const
This method returns the MAC footer size.
Returns
The MAC footer size.
References VerifyOrExit.
Referenced by MeshForwarder::PrepareDataFrame().
GetPayloadLength()
uint16_t GetPayloadLength (void) const
This method returns the current MAC Payload length.
Returns
The current MAC Payload length.
Referenced by Mac::ConvertBeaconToActiveScanResult(), and MeshForwarder::HandleReceivedFrame().
GetMaxPayloadLength()
uint16_t GetMaxPayloadLength (void) const
This method returns the maximum MAC Payload length for the given MAC header and footer.
Returns
The maximum MAC Payload length for the given MAC header and footer.
Referenced by MeshForwarder::PrepareDataFrame().
SetPayloadLength()
void SetPayloadLength (uint16_t aLength)
This method sets the MAC Payload length.
Referenced by MeshForwarder::PrepareDataFrame(), and MeshForwarder::PrepareEmptyFrame().
GetChannel()
uint8_t GetChannel (void) const inline
This method returns the IEEE 802.15.4 channel used for transmission or reception.
Returns
The IEEE 802.15.4 channel used for transmission or reception.
Referenced by SubMac::BeginTransmit(), Mac::ConvertBeaconToActiveScanResult(), SubMac::HandleTimer(), SubMac::HandleTransmitDone(), ThreadLinkInfo::SetFrom(), and SubMac::StartTimerForBackoff().
SetChannel()
void SetChannel (uint8_t aChannel) inline
This method sets the IEEE 802.15.4 channel used for transmission or reception.
Parameters
[in] aChannel The IEEE 802.15.4 channel used for transmission or reception.
Referenced by Mac::BeginTransmit(), MeshForwarder::PrepareDataFrame(), and DiscoverScanner::PrepareDiscoveryRequestFrame().
GetPsduLength()
uint16_t GetPsduLength (void) const inline
This method returns the IEEE 802.15.4 PSDU length.
Returns
The IEEE 802.15.4 PSDU length.
Referenced by TxFrame::CopyFrom().
GetPsdu() [1/2]
uint8_t* GetPsdu (void) inline
This method returns a pointer to the PSDU.
Returns
A pointer to the PSDU.
Referenced by Mac::LogFrameTxFailure().
GetPsdu() [2/2]
const uint8_t* GetPsdu (void) const inline
This const method returns a pointer to the PSDU.
Returns
A pointer to the PSDU.
GetHeader() [1/2]
uint8_t* GetHeader (void) inline
This method returns a pointer to the MAC Header.
Returns
A pointer to the MAC Header.
Referenced by Mac::HandleReceivedFrame(), Mac::HandleTransmitDone(), and Mac::RecordFrameTransmitStatus().
GetHeader() [2/2]
const uint8_t* GetHeader (void) const inline
This const method returns a pointer to the MAC Header.
Returns
A pointer to the MAC Header.
GetPayload() [1/2]
uint8_t* GetPayload (void) inline
This method returns a pointer to the MAC Payload.
Returns
A pointer to the MAC Payload.
References ot::AsConst(), ot::AsNonConst(), and Frame::GetPayload().
Referenced by Mac::ConvertBeaconToActiveScanResult(), Frame::GetPayload(), MeshForwarder::HandleReceivedFrame(), and MeshForwarder::PrepareDataFrame().
GetPayload() [2/2]
const uint8_t * GetPayload (void) const
This const method returns a pointer to the MAC Payload.
Returns
A pointer to the MAC Payload.
References VerifyOrExit.
GetFooter() [1/2]
uint8_t* GetFooter (void) inline
This method returns a pointer to the MAC Footer.
Returns
A pointer to the MAC Footer.
References ot::AsConst(), ot::AsNonConst(), Frame::GetFooter(), and OT_RADIO_FRAME_MAX_SIZE.
Referenced by Frame::GetFooter().
GetFooter() [2/2]
const uint8_t * GetFooter (void) const
This const method returns a pointer to the MAC Footer.
Returns
A pointer to the MAC Footer.
References ExitNow, Frame::GetFcsSize(), HeaderIe::GetId(), HeaderIe::GetLength(), Frame::GetMtu(), HeaderIe::Init(), ot::kErrorNone, ot::kErrorNotFound, ot::Hdlc::kFcsSize, CslIe::kHeaderIeId, OT_ASSERT, OT_RADIO_FRAME_MAX_SIZE, OT_UNUSED_VARIABLE, CslIe::SetPeriod(), CslIe::SetPhase(), SuccessOrExit, and VerifyOrExit.
GetMtu()
uint16_t GetMtu (void) const
This method returns the maximum transmission unit size (MTU).
Returns
The maximum transmission unit (MTU).
Referenced by Frame::GetFooter(), and TxFrames::TxFrames().
GetFcsSize()
uint8_t GetFcsSize (void) const
This method returns the FCS size.
Returns
This method returns the FCS size.
Referenced by TxFrame::CopyFrom(), Frame::GetFooter(), and MeshForwarder::PrepareDataFrame().
ToInfoString()
InfoString ToInfoString (void) const
This method returns information about the frame object as an InfoString object.
Returns
An InfoString containing info about the frame.
Referenced by MeshForwarder::CalcFrameVersion(), RxFrame::ProcessReceiveAesCcm(), and Mac::SetPromiscuous().
GetFrameControlField()
uint16_t GetFrameControlField (void) const
This method returns the Frame Control field of the frame.
Returns
The Frame Control field.
References ot::Encoding::BigEndian::ReadUint16().
Referenced by TxFrame::GenerateEnhAck().
FindDstPanIdIndex()
uint8_t FindDstPanIdIndex (void) const protected
References VerifyOrExit.
FindDstAddrIndex()
uint8_t FindDstAddrIndex (void) const protected
FindSrcPanIdIndex()
uint8_t FindSrcPanIdIndex (void) const protected
References VerifyOrExit.
FindSrcAddrIndex()
uint8_t FindSrcAddrIndex (void) const protected
SkipAddrFieldIndex()
uint8_t SkipAddrFieldIndex (void) const protected
References VerifyOrExit.
FindSecurityHeaderIndex()
uint8_t FindSecurityHeaderIndex (void) const protected
References VerifyOrExit.
SkipSecurityHeaderIndex()
uint8_t SkipSecurityHeaderIndex (void) const protected
References VerifyOrExit.
FindPayloadIndex()
uint8_t FindPayloadIndex (void) const protected
References HeaderIe::GetId(), HeaderIe::GetLength(), Termination2Ie::kHeaderIeId, and VerifyOrExit.
GetKeySourceLength()
uint8_t GetKeySourceLength (uint8_t aKeyIdMode) static protected
IsDstAddrPresent() [2/2]
static bool IsDstAddrPresent (uint16_t aFcf) inline static protected
IsDstPanIdPresent() [2/2]
bool IsDstPanIdPresent (uint16_t aFcf) static protected
IsSrcAddrPresent() [2/2]
static bool IsSrcAddrPresent (uint16_t aFcf) inline static protected
IsSrcPanIdPresent() [2/2]
bool IsSrcPanIdPresent (uint16_t aFcf) static protected
IsVersion2015() [2/2]
static bool IsVersion2015 (uint16_t aFcf) inline static protected
CalculateAddrFieldSize()
uint8_t CalculateAddrFieldSize (uint16_t aFcf) static protected
References ExitNow.
CalculateSecurityHeaderSize()
uint8_t CalculateSecurityHeaderSize (uint8_t aSecurityControl) static protected
References VerifyOrExit.
CalculateMicSize()
uint8_t CalculateMicSize (uint8_t aSecurityControl) static protected
Field Documentation
kFcfSize
constexpr uint8_t kFcfSize = sizeof(uint16_t) static
kDsnSize
constexpr uint8_t kDsnSize = sizeof(uint8_t) static
kSecurityControlSize
constexpr uint8_t kSecurityControlSize = sizeof(uint8_t) static
kFrameCounterSize
constexpr uint8_t kFrameCounterSize = sizeof(uint32_t) static
kCommandIdSize
constexpr uint8_t kCommandIdSize = sizeof(uint8_t) static
k154FcsSize
constexpr uint8_t k154FcsSize = sizeof(uint16_t) static
kFcfFrameBeacon
constexpr uint16_t kFcfFrameBeacon = 0 << 0 static
Referenced by Mac::ConvertBeaconToActiveScanResult(), Mac::HandleReceivedFrame(), MeshForwarder::HandleReceivedFrame(), and Mac::PrepareBeacon().
kFcfFrameData
constexpr uint16_t kFcfFrameData = 1 << 0 static
Referenced by Mac::HandleReceivedFrame(), MeshForwarder::HandleReceivedFrame(), MeshForwarder::PrepareDataFrame(), and MeshForwarder::PrepareEmptyFrame().
kFcfFrameAck
constexpr uint16_t kFcfFrameAck = 2 << 0 static
kFcfFrameMacCmd
constexpr uint16_t kFcfFrameMacCmd = 3 << 0 static
Referenced by MeshForwarder::CalcIePresent(), Mac::HandleReceivedFrame(), Mac::PrepareBeaconRequest(), and DataPollSender::PrepareDataRequest().
kFcfFrameTypeMask
constexpr uint16_t kFcfFrameTypeMask = 7 << 0 static
kFcfSecurityEnabled
constexpr uint16_t kFcfSecurityEnabled = 1 << 3 static
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfFramePending
constexpr uint16_t kFcfFramePending = 1 << 4 static
kFcfAckRequest
constexpr uint16_t kFcfAckRequest = 1 << 5 static
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfPanidCompression
constexpr uint16_t kFcfPanidCompression = 1 << 6 static
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfIePresent
constexpr uint16_t kFcfIePresent = 1 << 9 static
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfDstAddrNone
constexpr uint16_t kFcfDstAddrNone = 0 << 10 static
Referenced by Mac::PrepareBeacon().
kFcfDstAddrShort
constexpr uint16_t kFcfDstAddrShort = 2 << 10 static
Referenced by Mac::PrepareBeaconRequest(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfDstAddrExt
constexpr uint16_t kFcfDstAddrExt = 3 << 10 static
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfDstAddrMask
constexpr uint16_t kFcfDstAddrMask = 3 << 10 static
Referenced by MeshForwarder::PrepareDataFrame().
kFcfFrameVersion2006
constexpr uint16_t kFcfFrameVersion2006 = 1 << 12 static
Referenced by MeshForwarder::CalcFrameVersion(), and MeshForwarder::PrepareDataFrame().
kFcfFrameVersion2015
constexpr uint16_t kFcfFrameVersion2015 = 2 << 12 static
Referenced by MeshForwarder::CalcFrameVersion(), Mac::HandleReceivedFrame(), MeshForwarder::PrepareDataFrame(), and Mac::RecordFrameTransmitStatus().
kFcfFrameVersionMask
constexpr uint16_t kFcfFrameVersionMask = 3 << 12 static
Referenced by MeshForwarder::PrepareDataFrame().
kFcfSrcAddrNone
constexpr uint16_t kFcfSrcAddrNone = 0 << 14 static
Referenced by Mac::PrepareBeaconRequest().
kFcfSrcAddrShort
constexpr uint16_t kFcfSrcAddrShort = 2 << 14 static
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfSrcAddrExt
constexpr uint16_t kFcfSrcAddrExt = 3 << 14 static
Referenced by Mac::PrepareBeacon(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), and MeshForwarder::PrepareEmptyFrame().
kFcfSrcAddrMask
constexpr uint16_t kFcfSrcAddrMask = 3 << 14 static
Referenced by MeshForwarder::PrepareDataFrame().
kSecNone
constexpr uint8_t kSecNone = 0 << 0 static
Referenced by Mac::PrepareBeacon(), Mac::PrepareBeaconRequest(), and MeshForwarder::PrepareDataFrame().
kSecMic32
constexpr uint8_t kSecMic32 = 1 << 0 static
kSecMic64
constexpr uint8_t kSecMic64 = 2 << 0 static
kSecMic128
constexpr uint8_t kSecMic128 = 3 << 0 static
kSecEnc
constexpr uint8_t kSecEnc = 4 << 0 static
kSecEncMic32
constexpr uint8_t kSecEncMic32 = 5 << 0 static
Referenced by MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), MeshForwarder::PrepareEmptyFrame(), Mac::ProcessEnhAckSecurity(), Mle::ProcessMessageSecurity(), and Mac::ProcessReceiveSecurity().
kSecEncMic64
constexpr uint8_t kSecEncMic64 = 6 << 0 static
kSecEncMic128
constexpr uint8_t kSecEncMic128 = 7 << 0 static
kSecLevelMask
constexpr uint8_t kSecLevelMask = 7 << 0 static
kMic0Size
constexpr uint8_t kMic0Size = 0 static
kMic32Size
constexpr uint8_t kMic32Size = 32 / CHAR_BIT static
kMic64Size
constexpr uint8_t kMic64Size = 64 / CHAR_BIT static
kMic128Size
constexpr uint8_t kMic128Size = 128 / CHAR_BIT static
kMaxMicSize
constexpr uint8_t kMaxMicSize = kMic128Size static
kKeyIdMode0
constexpr uint8_t kKeyIdMode0 = 0 << 3 static
Referenced by MeshForwarder::PrepareDataFrame(), Mac::ProcessReceiveSecurity(), Mac::ProcessTransmitSecurity(), and SubMac::SetMacKey().
kKeyIdMode1
constexpr uint8_t kKeyIdMode1 = 1 << 3 static
Referenced by Mac::HandleReceivedFrame(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), MeshForwarder::PrepareEmptyFrame(), Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), SubMac::ProcessTransmitSecurity(), Mac::ProcessTransmitSecurity(), SubMac::SetMacKey(), SubMac::SignalFrameCounterUsedOnTxDone(), and KeyManager::UpdateKeyMaterial().
kKeyIdMode2
constexpr uint8_t kKeyIdMode2 = 2 << 3 static
Referenced by MeshForwarder::PrepareDataFrame(), Mac::ProcessReceiveSecurity(), Mac::ProcessTransmitSecurity(), and SubMac::SetMacKey().
kKeyIdMode3
constexpr uint8_t kKeyIdMode3 = 3 << 3 static
kKeyIdModeMask
constexpr uint8_t kKeyIdModeMask = 3 << 3 static
kKeySourceSizeMode0
constexpr uint8_t kKeySourceSizeMode0 = 0 static
kKeySourceSizeMode1
constexpr uint8_t kKeySourceSizeMode1 = 0 static
kKeySourceSizeMode2
constexpr uint8_t kKeySourceSizeMode2 = 4 static
kKeySourceSizeMode3
constexpr uint8_t kKeySourceSizeMode3 = 8 static
kKeyIndexSize
constexpr uint8_t kKeyIndexSize = sizeof(uint8_t) static
kMacCmdAssociationRequest
constexpr uint8_t kMacCmdAssociationRequest = 1 static
kMacCmdAssociationResponse
constexpr uint8_t kMacCmdAssociationResponse = 2 static
kMacCmdDisassociationNotification
constexpr uint8_t kMacCmdDisassociationNotification = 3 static
kMacCmdDataRequest
constexpr uint8_t kMacCmdDataRequest = 4 static
Referenced by Mac::HandleMacCommand(), and DataPollSender::PrepareDataRequest().
kMacCmdPanidConflictNotification
constexpr uint8_t kMacCmdPanidConflictNotification = 5 static
kMacCmdOrphanNotification
constexpr uint8_t kMacCmdOrphanNotification = 6 static
kMacCmdBeaconRequest
constexpr uint8_t kMacCmdBeaconRequest = 7 static
Referenced by Mac::HandleMacCommand(), and Mac::PrepareBeaconRequest().
kMacCmdCoordinatorRealignment
constexpr uint8_t kMacCmdCoordinatorRealignment = 8 static
kMacCmdGtsRequest
constexpr uint8_t kMacCmdGtsRequest = 9 static
kImmAckLength
constexpr uint8_t kImmAckLength = kFcfSize + kDsnSize + k154FcsSize static
kInfoStringSize
constexpr uint16_t kInfoStringSize = 128 static
Max chars for InfoString (ToInfoString()).
kInvalidIndex
constexpr uint8_t kInvalidIndex = 0xff static protected
kInvalidSize
constexpr uint8_t kInvalidSize = kInvalidIndex static protected
kMaxPsduSize
constexpr uint8_t kMaxPsduSize = kInvalidSize - 1 static protected
kSequenceIndex
constexpr uint8_t kSequenceIndex = kFcfSize static protected
The documentation for this class was generated from the following files:
mac_frame.hpp
mac_frame.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale