OpenThread: NeighborTable Class Reference
NeighborTable Class Reference
#include <neighbor_table.hpp>
Public Types
typedef otNeighborTableCallback Callback
typedef otNeighborTableEntryInfo EntryInfo
enum Event : uint8_t {
kChildAdded = OT_NEIGHBOR_TABLE_EVENT_CHILD_ADDED, kChildRemoved = OT_NEIGHBOR_TABLE_EVENT_CHILD_REMOVED, kChildModeChanged = OT_NEIGHBOR_TABLE_EVENT_CHILD_MODE_CHANGED, kRouterAdded = OT_NEIGHBOR_TABLE_EVENT_ROUTER_ADDED,
kRouterRemoved = OT_NEIGHBOR_TABLE_EVENT_ROUTER_REMOVED
}
Public Member Functions
Neighbor * FindNeighbor (Mac::ShortAddress aShortAddress, Neighbor::StateFilter aFilter=Neighbor::kInStateValidOrRestoring)
Neighbor * FindNeighbor (const Mac::ExtAddress &aExtAddress, Neighbor::StateFilter aFilter=Neighbor::kInStateValidOrRestoring)
Neighbor * FindNeighbor (const Mac::Address &aMacAddress, Neighbor::StateFilter aFilter=Neighbor::kInStateValidOrRestoring)
Neighbor * FindParent (Mac::ShortAddress aShortAddress, Neighbor::StateFilter aFilter=Neighbor::kInStateValidOrRestoring)
Neighbor * FindParent (const Mac::ExtAddress &aExtAddress, Neighbor::StateFilter aFilter=Neighbor::kInStateValidOrRestoring)
Neighbor * FindParent (const Mac::Address &aMacAddress, Neighbor::StateFilter aFilter=Neighbor::kInStateValidOrRestoring)
Error GetNextNeighborInfo (otNeighborInfoIterator &aIterator, Neighbor::Info &aNeighInfo)
NeighborTable (Instance &aInstance)
void RegisterCallback (Callback aCallback)
void Signal (Event aEvent, const Neighbor &aNeighbor)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
Neighbor * FindNeighbor (const Neighbor::AddressMatcher &aMatcher)
Neighbor * FindParent (const Neighbor::AddressMatcher &aMatcher)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
Callback mCallback
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class represents the Thread neighbor table.
Member Typedef Documentation
Callback
typedef otNeighborTableCallback Callback
This function pointer is called to notify that a child or router neighbor is being added to or removed from neighbor table.
Note that this callback in invoked while the neighbor/child table is being updated and always before the related Notifier event.
EntryInfo
typedef otNeighborTableEntryInfo EntryInfo
This type represents a neighbor table entry info (child or router) and is used as a parameter in the neighbor table callback.
Member Enumeration Documentation
Event
enum Event : uint8_t
This enumeration defines the constants used in NeighborTable::Callback to indicate whether a child or router neighbor is being added or removed.
Enumerator
kChildAdded
A child is being added.
kChildRemoved
A child is being removed.
kChildModeChanged
An existing child's mode changed.
kRouterAdded
A router is being added.
kRouterRemoved
A router is being removed.
Constructor & Destructor Documentation
NeighborTable()
NeighborTable (Instance & aInstance) explicit
This constructor initializes the NeighborTable instance.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
FindParent() [1/4]
Neighbor * FindParent (Mac::ShortAddress aShortAddress, Neighbor::StateFilter aFilter = Neighbor::kInStateValidOrRestoring)
This method searches among parent and parent candidate to find a Neighbor corresponding to a given short address.
Parameters
[in] aShortAddress A short address.
[in] aFilter A neighbor state filter
Returns
A pointer to the Neighbor corresponding to aShortAddress, nullptr otherwise.
Referenced by NeighborTable::FindNeighbor(), NeighborTable::FindParent(), Mle::HandleUdpReceive(), and NeighborTable::RegisterCallback().
FindParent() [2/4]
Neighbor * FindParent (const Mac::ExtAddress & aExtAddress, Neighbor::StateFilter aFilter = Neighbor::kInStateValidOrRestoring)
This method searches in parent and parent candidate to find a Neighbor corresponding to a given MAC Extended Address.
Parameters
[in] aExtAddress A MAC Extended Address.
[in] aFilter A neighbor state filter
Returns
A pointer to the Neighbor corresponding to aExtAddress, nullptr otherwise.
References NeighborTable::FindParent().
FindParent() [3/4]
Neighbor * FindParent (const Mac::Address & aMacAddress, Neighbor::StateFilter aFilter = Neighbor::kInStateValidOrRestoring)
This method searches among parent and parent candidate to find a Neighbor object corresponding to a given MAC address.
Parameters
[in] aMacAddress A MAC address.
[in] aFilter A neighbor state filter
Returns
A pointer to the Neighbor corresponding to aMacAddress, nullptr otherwise.
References NeighborTable::FindParent().
FindNeighbor() [1/4]
Neighbor * FindNeighbor (Mac::ShortAddress aShortAddress, Neighbor::StateFilter aFilter = Neighbor::kInStateValidOrRestoring)
This method searches in the neighbor table to find a Neighbor corresponding to a given short address.
Parameters
[in] aShortAddress A short address.
[in] aFilter A neighbor state filter.
Returns
A pointer to the Neighbor corresponding to aShortAddress, nullptr otherwise.
References ot::Mac::kShortAddrBroadcast, ot::Mac::kShortAddrInvalid, and VerifyOrExit.
Referenced by NeighborTable::FindNeighbor(), Mle::HandleUdpReceive(), and NeighborTable::RegisterCallback().
FindNeighbor() [2/4]
Neighbor * FindNeighbor (const Mac::ExtAddress & aExtAddress, Neighbor::StateFilter aFilter = Neighbor::kInStateValidOrRestoring)
This method searches in the neighbor table to find a Neighbor corresponding to a given MAC Extended Address.
Parameters
[in] aExtAddress A MAC Extended Address.
[in] aFilter A neighbor state filter.
Returns
A pointer to the Neighbor corresponding to aExtAddress, nullptr otherwise.
References NeighborTable::FindNeighbor().
FindNeighbor() [3/4]
Neighbor * FindNeighbor (const Mac::Address & aMacAddress, Neighbor::StateFilter aFilter = Neighbor::kInStateValidOrRestoring)
This method searches in the neighbor table to find a Neighbor object corresponding to a given MAC address.
Parameters
[in] aMacAddress A MAC address.
[in] aFilter A neighbor state filter.
Returns
A pointer to the Neighbor corresponding to aMacAddress, nullptr otherwise.
References InterfaceIdentifier::ConvertToMacAddress(), ExitNow, NeighborTable::FindNeighbor(), Address::GetIid(), InterfaceIdentifier::GetLocator(), NeighborTable::GetNextNeighborInfo(), Address::IsLinkLocal(), Address::IsNone(), Neighbor::IsStateValid(), ot::kErrorNone, ot::kErrorNotFound, ot::Mle::kMaxRouterId, otNeighborInfo::mIsChild, OT_NEIGHBOR_INFO_ITERATOR_INIT, Neighbor::Info::SetFrom(), Address::SetShort(), and VerifyOrExit.
GetNextNeighborInfo()
Error GetNextNeighborInfo (otNeighborInfoIterator & aIterator, Neighbor::Info & aNeighInfo)
This method gets the next neighbor information. It is used to iterate through the entries of the neighbor table.
Parameters
[in,out] aIterator A reference to the iterator context. To get the first neighbor entry it should be set to OT_NEIGHBOR_INFO_ITERATOR_INIT.
[out] aNeighInfo The neighbor information.
Return values
kErrorNone Successfully found the next neighbor entry in table.
kErrorNotFound No subsequent neighbor entry exists in the table.
Referenced by NeighborTable::FindNeighbor().
RegisterCallback()
void RegisterCallback (Callback aCallback) inline
This method registers the "neighbor table changed" callback function.
The provided callback (if non-nullptr) will be invoked when a child/router entry is being added/remove to/from the neighbor table. Subsequent calls to this method will overwrite the previous callback.
Parameters
[in] aCallback A pointer to callback handler function.
References NeighborTable::FindNeighbor(), NeighborTable::FindParent(), NeighborTable::mCallback, and NeighborTable::Signal().
Signal()
void Signal (Event aEvent, const Neighbor & aNeighbor)
This method signals a "neighbor table changed" event.
This method invokes the NeighborTable::Callback and also signals the change through a related Notifier event.
Parameters
[in] aEvent The event to emit (child/router added/removed, or child mode changed).
[in] aNeighbor The neighbor that is being added/removed.
References InstanceLocator::GetInstance(), NeighborTable::kChildAdded, NeighborTable::kChildModeChanged, NeighborTable::kChildRemoved, ot::kEventThreadChildAdded, ot::kEventThreadChildRemoved, ot::Mle::kRemoved, NeighborTable::kRouterAdded, NeighborTable::kRouterRemoved, NeighborTable::mCallback, otNeighborTableEntryInfo::mChild, otNeighborTableEntryInfo::mInfo, otNeighborTableEntryInfo::mInstance, and otNeighborTableEntryInfo::mRouter.
Referenced by NeighborTable::RegisterCallback().
FindParent() [4/4]
Neighbor * FindParent (const Neighbor::AddressMatcher & aMatcher) private
References Mle::GetParent(), Mle::GetParentCandidate(), and Neighbor::Matches().
FindNeighbor() [4/4]
Neighbor * FindNeighbor (const Neighbor::AddressMatcher & aMatcher) private
References NeighborTable::FindParent().
Field Documentation
mCallback
Callback mCallback private
Referenced by NeighborTable::RegisterCallback(), and NeighborTable::Signal().
The documentation for this class was generated from the following files:
neighbor_table.hpp
neighbor_table.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale