OpenThread: Radio Class Reference
Radio Class Reference
#include <radio.hpp>
Public Member Functions
void Init (void)
Radio (const char *aUrl)
Private Attributes
RadioUrl mRadioUrl
Detailed Description
This class manages Thread radio.
Constructor & Destructor Documentation
Radio()
Radio (const char * aUrl) explicit
This method creates the radio manager.
Parameters
[in] aUrl A pointer to the null-terminated URL.
References Url::GetPath(), Radio::mRadioUrl, OT_EXIT_INVALID_ARGUMENTS, and VerifyOrDie.
Member Function Documentation
Init()
void Init (void)
This method initialize the Thread radio.
References DieNow, RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), Url::GetValue(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), Radio::mRadioUrl, OT_ERROR_FAILED, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_EXIT_INVALID_ARGUMENTS, RadioSpinel< InterfaceType, ProcessContextType >::SetCcaEnergyDetectThreshold(), RadioSpinel< InterfaceType, ProcessContextType >::SetChannelMaxTransmitPower(), RadioSpinel< InterfaceType, ProcessContextType >::SetFemLnaGain(), RadioSpinel< InterfaceType, ProcessContextType >::SetRadioRegion(), SuccessOrDie, VerifyOrDie, and virtualTimeInit().
Field Documentation
mRadioUrl
RadioUrl mRadioUrl private
Referenced by Radio::Init(), and Radio::Radio().
The documentation for this class was generated from the following files:
posix/platform/radio.hpp
posix/platform/radio.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale