OpenThread: Icmp::Handler Class Reference
Icmp::Handler Class Reference
#include <icmp6.hpp>
Public Member Functions
Handler (otIcmp6ReceiveCallback aCallback, void *aContext)
Public Member Functions inherited from LinkedListEntry< Handler >
const Handler * GetNext (void) const
Handler * GetNext (void)
void SetNext (Handler *aNext)
Private Member Functions
void HandleReceiveMessage (Message &aMessage, const MessageInfo &aMessageInfo, const Header &aIcmp6Header)
Friends
class Icmp
Additional Inherited Members
Data Fields inherited from otIcmp6Handler
void * mContext
A pointer to arbitrary context information.
struct otIcmp6Handler * mNext
A pointer to the next handler in the list.
otIcmp6ReceiveCallback mReceiveCallback
The ICMPv6 received callback.
Detailed Description
This class implements ICMPv6 message handlers.
Constructor & Destructor Documentation
Handler()
Handler (otIcmp6ReceiveCallback aCallback, void * aContext) inline
This constructor creates an ICMPv6 message handler.
Parameters
[in] aCallback A pointer to the function that is called when receiving an ICMPv6 message.
[in] aContext A pointer to arbitrary context information.
Member Function Documentation
HandleReceiveMessage()
void HandleReceiveMessage (Message & aMessage, const MessageInfo & aMessageInfo, const Header & aIcmp6Header) inline private
References Icmp::HandleMessage(), Icmp::Icmp(), Icmp::NewMessage(), Icmp::RegisterHandler(), Icmp::SendEchoRequest(), and Icmp::SendError().
Friends And Related Function Documentation
Icmp
friend class Icmp friend
The documentation for this class was generated from the following file:
icmp6.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale