OpenThread: ChangedPropsSet Class Reference
ChangedPropsSet Class Reference
#include <changed_props_set.hpp>
Data Structures
struct Entry
Public Member Functions
void AddLastStatus (spinel_status_t aStatus)
void AddProperty (spinel_prop_key_t aPropKey)
ChangedPropsSet (void)
void Clear (void)
void ClearFilter (void)
otError EnablePropertyFilter (spinel_prop_key_t aPropKey, bool aEnable)
const Entry * GetEntry (uint8_t aIndex) const
const Entry * GetSupportedEntries (uint8_t &aNumEntries) const
bool IsEmpty (void) const
bool IsEntryChanged (uint8_t aIndex) const
bool IsEntryFiltered (uint8_t aIndex) const
bool IsPropertyFiltered (spinel_prop_key_t aPropKey) const
void RemoveEntry (uint8_t aIndex)
Private Member Functions
void Add (spinel_prop_key_t aPropKey, spinel_status_t aStatus)
uint8_t GetNumEntries (void) const
Static Private Member Functions
static void ClearBit (uint64_t &aBitset, uint8_t aBitIndex)
static bool IsBitSet (uint64_t aBitset, uint8_t aBitIndex)
static void SetBit (uint64_t &aBitset, uint8_t aBitIndex)
Private Attributes
uint64_t mChangedSet
uint64_t mFilterSet
Static Private Attributes
static const Entry mSupportedProps []
Detailed Description
Defines a class to track a set of property/status changes that require update to host. The properties that can be added to this set must support sending unsolicited updates. This class also provides mechanism for user to block certain filterable properties disallowing the unsolicited update from them.
Constructor & Destructor Documentation
ChangedPropsSet()
ChangedPropsSet (void) inline
This constructor initializes the set.
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the set.
References ChangedPropsSet::mChangedSet.
IsEmpty()
bool IsEmpty (void) const inline
This method indicates if the set is empty or not.
Returns
TRUE if the set if empty, FALSE otherwise.
References ChangedPropsSet::mChangedSet.
Referenced by NcpBase::UpdateChangedProps().
AddProperty()
void AddProperty (spinel_prop_key_t aPropKey) inline
This method adds a property to the set. The property added must be in the list of supported properties capable of sending unsolicited update, otherwise the input is ignored.
Note that if the property is already in the set, adding it again does not change the set.
Parameters
[in] aPropKey The spinel property key to be added to the set
References ChangedPropsSet::Add(), and SPINEL_STATUS_OK.
AddLastStatus()
void AddLastStatus (spinel_status_t aStatus) inline
This method adds a LAST_STATUS update to the set. The update must be in list of supported entries.
Parameters
[in] aStatus The spinel status update to be added to set.
References ChangedPropsSet::Add(), and SPINEL_PROP_LAST_STATUS.
Referenced by NcpBase::EnqueueResponse(), NcpBase::Log(), NcpBase::NcpBase(), and NcpBase::StreamWrite().
GetSupportedEntries()
const Entry* GetSupportedEntries (uint8_t & aNumEntries) const inline
This method returns a pointer to array of entries of supported property/status updates. The list includes all properties that can generate unsolicited update.
Parameters
[out] aNumEntries A reference to output the number of entries in the list.
Returns
A pointer to the supported entries array.
References ChangedPropsSet::GetNumEntries(), and ChangedPropsSet::mSupportedProps.
Referenced by ChangedPropsSet::Add(), ChangedPropsSet::EnablePropertyFilter(), NcpBase::HandlePropertyGet(), ChangedPropsSet::IsPropertyFiltered(), and NcpBase::UpdateChangedProps().
GetEntry()
const Entry* GetEntry (uint8_t aIndex) const inline
This method returns a pointer to the entry associated with a given index.
Parameters
[in] aIndex The index to an entry.
Returns
A pointer to the entry associated with aIndex, or nullptr if the index is beyond end of array.
References ChangedPropsSet::GetNumEntries(), and ChangedPropsSet::mSupportedProps.
IsEntryChanged()
bool IsEntryChanged (uint8_t aIndex) const inline
This method indicates if the entry associated with an index is in the set (i.e., it has been changed and requires an unsolicited update).
Parameters
[in] aIndex The index to an entry.
Returns
TRUE if the entry is in the set, FALSE otherwise.
References ChangedPropsSet::IsBitSet(), and ChangedPropsSet::mChangedSet.
Referenced by NcpBase::UpdateChangedProps().
RemoveEntry()
void RemoveEntry (uint8_t aIndex) inline
This method removes an entry associated with an index in the set.
Note that if the property/entry is not in the set, removing it simply does nothing.
Parameters
[in] aIndex Index of entry to be removed.
References ChangedPropsSet::ClearBit(), ChangedPropsSet::EnablePropertyFilter(), and ChangedPropsSet::mChangedSet.
Referenced by NcpBase::UpdateChangedProps().
EnablePropertyFilter()
otError EnablePropertyFilter (spinel_prop_key_t aPropKey, bool aEnable)
This method enables/disables filtering of a given property.
Parameters
[in] aPropKey The property key to filter.
[in] aEnable TRUE to enable filtering, FALSE to disable.
Return values
OT_ERROR_NONE Filter state for given property updated successfully.
OT_ERROR_INVALID_ARGS The given property is not valid (i.e., not capable of unsolicited update).
References ChangedPropsSet::ClearBit(), ChangedPropsSet::GetSupportedEntries(), ChangedPropsSet::mChangedSet, ChangedPropsSet::Entry::mFilterable, ChangedPropsSet::mFilterSet, ChangedPropsSet::Entry::mPropKey, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, ChangedPropsSet::SetBit(), and SPINEL_PROP_LAST_STATUS.
Referenced by NcpBase::HandlePropertyInsert(), NcpBase::HandlePropertyRemove(), NcpBase::HandlePropertySet(), and ChangedPropsSet::RemoveEntry().
IsEntryFiltered()
bool IsEntryFiltered (uint8_t aIndex) const inline
This method determines whether filtering is enabled for an entry associated with an index.
Parameters
[in] aIndex Index of entry to be checked.
Returns
TRUE if the filter is enabled for the given entry, FALSE otherwise.
References ChangedPropsSet::IsBitSet(), ChangedPropsSet::IsPropertyFiltered(), and ChangedPropsSet::mFilterSet.
Referenced by ChangedPropsSet::Add(), NcpBase::HandlePropertyGet(), and ChangedPropsSet::IsPropertyFiltered().
IsPropertyFiltered()
bool IsPropertyFiltered (spinel_prop_key_t aPropKey) const
This method determines whether filtering is enabled for a given property key.
Parameters
[in] aPropKey The property key to check.
Returns
TRUE if the filter is enabled for the given property, FALSE if the property is not filtered or if it is not filterable.
References ChangedPropsSet::GetSupportedEntries(), ChangedPropsSet::IsEntryFiltered(), ChangedPropsSet::Entry::mFilterable, and ChangedPropsSet::Entry::mPropKey.
Referenced by ChangedPropsSet::IsEntryFiltered(), NcpBase::Log(), and NcpBase::StreamWrite().
ClearFilter()
void ClearFilter (void) inline
This method clears the filter.
References ChangedPropsSet::Add(), ChangedPropsSet::GetNumEntries(), and ChangedPropsSet::mFilterSet.
Referenced by NcpBase::HandlePropertySet().
GetNumEntries()
uint8_t GetNumEntries (void) const private
References ChangedPropsSet::mChangedSet, ChangedPropsSet::mSupportedProps, and OT_ARRAY_LENGTH.
Referenced by ChangedPropsSet::ClearFilter(), ChangedPropsSet::GetEntry(), and ChangedPropsSet::GetSupportedEntries().
Add()
void Add (spinel_prop_key_t aPropKey, spinel_status_t aStatus) private
References ChangedPropsSet::GetSupportedEntries(), ChangedPropsSet::IsEntryFiltered(), ChangedPropsSet::mChangedSet, ChangedPropsSet::Entry::mPropKey, ChangedPropsSet::Entry::mStatus, and ChangedPropsSet::SetBit().
Referenced by ChangedPropsSet::AddLastStatus(), ChangedPropsSet::AddProperty(), and ChangedPropsSet::ClearFilter().
SetBit()
static void SetBit (uint64_t & aBitset, uint8_t aBitIndex) inline static private
Referenced by ChangedPropsSet::Add(), and ChangedPropsSet::EnablePropertyFilter().
ClearBit()
static void ClearBit (uint64_t & aBitset, uint8_t aBitIndex) inline static private
Referenced by ChangedPropsSet::EnablePropertyFilter(), and ChangedPropsSet::RemoveEntry().
IsBitSet()
static bool IsBitSet (uint64_t aBitset, uint8_t aBitIndex) inline static private
Referenced by ChangedPropsSet::IsEntryChanged(), and ChangedPropsSet::IsEntryFiltered().
Field Documentation
mSupportedProps
const ChangedPropsSet::Entry mSupportedProps static private
Referenced by ChangedPropsSet::GetEntry(), ChangedPropsSet::GetNumEntries(), and ChangedPropsSet::GetSupportedEntries().
mChangedSet
uint64_t mChangedSet private
Referenced by ChangedPropsSet::Add(), ChangedPropsSet::Clear(), ChangedPropsSet::EnablePropertyFilter(), ChangedPropsSet::GetNumEntries(), ChangedPropsSet::IsEmpty(), ChangedPropsSet::IsEntryChanged(), and ChangedPropsSet::RemoveEntry().
mFilterSet
uint64_t mFilterSet private
Referenced by ChangedPropsSet::ClearFilter(), ChangedPropsSet::EnablePropertyFilter(), and ChangedPropsSet::IsEntryFiltered().
The documentation for this class was generated from the following files:
changed_props_set.hpp
changed_props_set.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale