OpenThread: DiscoverScanner Class Reference
DiscoverScanner Class Reference
#include <discover_scanner.hpp>
Public Types
typedef MeshCoP::SteeringData::HashBitIndexes FilterIndexes
typedef otHandleActiveScanResult Handler
typedef otActiveScanResult ScanResult
Public Member Functions
Error Discover (const Mac::ChannelMask &aScanChannels, Mac::PanId aPanId, bool aJoiner, bool aEnableFiltering, const FilterIndexes *aFilterIndexes, Handler aCallback, void *aContext)
DiscoverScanner (Instance &aInstance)
bool IsInProgress (void) const
Error SetJoinerAdvertisement (uint32_t aOui, const uint8_t *aAdvData, uint8_t aAdvDataLength)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Attributes
static constexpr uint32_t kDefaultScanDuration = Mac::kScanDurationDefault
Private Types
enum State : uint8_t { kStateIdle, kStateScanning, kStateScanDone }
Private Member Functions
void HandleDiscoverComplete (void)
void HandleDiscoveryRequestFrameTxDone (Message &aMessage)
void HandleDiscoveryResponse (Mle::RxInfo &aRxInfo) const
void HandleTimer (void)
Mac::TxFrame * PrepareDiscoveryRequestFrame (Mac::TxFrame &aFrame)
void Stop (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleTimer (Timer &aTimer)
Private Attributes
uint8_t mAdvData [MeshCoP::JoinerAdvertisementTlv::kAdvDataMaxLength]
uint8_t mAdvDataLength
bool mEnableFiltering: 1
FilterIndexes mFilterIndexes
Handler mHandler
void * mHandlerContext
uint32_t mOui
uint8_t mScanChannel
Mac::ChannelMask mScanChannels
bool mShouldRestorePanId: 1
State mState
TimerMilli mTimer
Static Private Attributes
static constexpr uint32_t kMaxOui = 0xffffff
Friends
class Mle
class ot::Instance
class ot::MeshForwarder
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements MLE Discover Scan.
Member Typedef Documentation
ScanResult
typedef otActiveScanResult ScanResult
This type represents Discover Scan result.
Handler
typedef otHandleActiveScanResult Handler
This type represents the handler function pointer called with any Discover Scan result or when the scan completes.
The handler function format is void (*oHandler)(ScanResult *aResult, void *aContext);. End of scan is indicated by aResult pointer being set to nullptr.
FilterIndexes
typedef MeshCoP::SteeringData::HashBitIndexes FilterIndexes
This type represents the filter indexes, i.e., hash bit index values for the bloom filter (calculated from a Joiner ID).
This is used when filtering is enabled during Discover Scan, i.e., received MLE Discovery Responses with steering data (bloom filter) not containing the given indexes are filtered.
Member Enumeration Documentation
State
enum State : uint8_t private
Enumerator
kStateIdle
kStateScanning
kStateScanDone
Constructor & Destructor Documentation
DiscoverScanner()
DiscoverScanner (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Discover()
Error Discover (const Mac::ChannelMask & aScanChannels, Mac::PanId aPanId, bool aJoiner, bool aEnableFiltering, const FilterIndexes * aFilterIndexes, Handler aCallback, void * aContext)
This method starts a Thread Discovery Scan.
Parameters
[in] aScanChannels Channel mask listing channels to scan (if empty, use all supported channels).
[in] aPanId The PAN ID filter (set to Broadcast PAN to disable filter).
[in] aJoiner Value of the Joiner Flag in the Discovery Request TLV.
[in] aEnableFiltering Enable filtering MLE Discovery Responses with steering data not containing a given filter indexes.
[in] aFilterIndexes A pointer to FilterIndexes to use for filtering (when enabled). If set to nullptr, filter indexes are derived from hash of factory-assigned EUI64.
[in] aCallback A pointer to a function that is called on receiving an MLE Discovery Response.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Successfully started a Thread Discovery Scan.
kErrorInvalidState The IPv6 interface is not enabled (netif is not up).
kErrorNoBufs Could not allocate message for Discovery Request.
kErrorBusy Thread Discovery Scan is already in progress.
References Message::Append(), Tlv::AppendTo(), SteeringData::CalculateHashBitIndexes(), ot::MeshCoP::ComputeJoinerId(), FreeMessageOnError, ot::Mac::GenerateRandomPanId(), ChannelMask::GetNextChannel(), Tlv::GetSize(), DiscoveryRequestTlv::Init(), JoinerAdvertisementTlv::Init(), ChannelMask::Intersect(), ChannelMask::IsEmpty(), ChannelMask::kChannelIteratorFirst, Mle::kCommandDiscoveryRequest, Tlv::kDiscovery, ot::kErrorBusy, ot::kErrorInvalidState, ot::kErrorNoBufs, ot::kErrorNone, Mle::kMessageSend, ot::Mac::kPanIdBroadcast, DiscoverScanner::kStateIdle, DiscoverScanner::kStateScanDone, DiscoverScanner::kStateScanning, ot::kThreadVersion, Mle::kTypeDiscoveryRequest, Mle::Log(), DiscoverScanner::mAdvData, DiscoverScanner::mAdvDataLength, DiscoverScanner::mEnableFiltering, DiscoverScanner::mFilterIndexes, DiscoverScanner::mHandler, DiscoverScanner::mHandlerContext, DiscoverScanner::mOui, DiscoverScanner::mScanChannel, DiscoverScanner::mScanChannels, DiscoverScanner::mShouldRestorePanId, DiscoverScanner::mState, Mle::TxMessage::SendTo(), JoinerAdvertisementTlv::SetAdvData(), DiscoveryRequestTlv::SetJoiner(), Tlv::SetLength(), JoinerAdvertisementTlv::SetOui(), Message::SetPanId(), Address::SetToLinkLocalAllRoutersMulticast(), Tlv::SetType(), DiscoveryRequestTlv::SetVersion(), SuccessOrExit, and VerifyOrExit.
IsInProgress()
bool IsInProgress (void) const inline
This method indicates whether or not an MLE Thread Discovery Scan is currently in progress.
Returns
true if an MLE Thread Discovery Scan is in progress, false otherwise.
References DiscoverScanner::kStateIdle, DiscoverScanner::mState, and DiscoverScanner::SetJoinerAdvertisement().
SetJoinerAdvertisement()
Error SetJoinerAdvertisement (uint32_t aOui, const uint8_t * aAdvData, uint8_t aAdvDataLength)
This method sets Joiner Advertisement.
Parameters
[in] aOui The Vendor OUI for Joiner Advertisement.
[in] aAdvData A pointer to AdvData for Joiner Advertisement.
[in] aAdvDataLength The length of AdvData.
Return values
kErrorNone Successfully set Joiner Advertisement.
kErrorInvalidArgs Invalid AdvData.
References JoinerAdvertisementTlv::kAdvDataMaxLength, ot::kErrorInvalidArgs, ot::kErrorNone, DiscoverScanner::kMaxOui, DiscoverScanner::mAdvData, DiscoverScanner::mAdvDataLength, DiscoverScanner::mOui, and VerifyOrExit.
Referenced by DiscoverScanner::IsInProgress().
PrepareDiscoveryRequestFrame()
Mac::TxFrame * PrepareDiscoveryRequestFrame (Mac::TxFrame & aFrame) private
References IgnoreError(), DiscoverScanner::kStateIdle, DiscoverScanner::kStateScanDone, DiscoverScanner::kStateScanning, DiscoverScanner::mScanChannel, DiscoverScanner::mState, and Frame::SetChannel().
HandleDiscoveryRequestFrameTxDone()
void HandleDiscoveryRequestFrameTxDone (Message & aMessage) private
References DiscoverScanner::HandleDiscoverComplete(), DiscoverScanner::kDefaultScanDuration, DiscoverScanner::kStateIdle, DiscoverScanner::kStateScanDone, DiscoverScanner::kStateScanning, DiscoverScanner::mState, DiscoverScanner::mTimer, Message::SetDirectTransmission(), Message::SetTimestampToNow(), and TimerMilli::Start().
Stop()
void Stop (void) inline private
References DiscoverScanner::HandleDiscoverComplete(), DiscoverScanner::HandleDiscoveryResponse(), and DiscoverScanner::HandleTimer().
HandleDiscoveryResponse()
void HandleDiscoveryResponse (Mle::RxInfo & aRxInfo) const private
References ot::AsCoreType(), SteeringData::Contains(), InterfaceIdentifier::ConvertToExtAddress(), Tlv::FindTlvOffset(), SteeringData::GetData(), Address::GetIid(), Tlv::GetLength(), NetworkNameTlv::GetNetworkName(), MessageInfo::GetPeerAddr(), MessageInfo::GetThreadLinkInfo(), Tlv::GetType(), DiscoveryResponseTlv::GetVersion(), IgnoreError(), SteeringData::Init(), DiscoveryResponseTlv::IsNativeCommissioner(), NetworkNameTlv::IsValid(), DiscoveryResponseTlv::IsValid(), Tlv::kDiscovery, Tlv::kDiscoveryResponse, ot::kErrorDrop, ot::kErrorNone, ot::kErrorParse, Tlv::kExtendedPanId, Tlv::kJoinerUdpPort, SteeringData::kMaxLength, Mle::kMessageReceive, Tlv::kNetworkName, DiscoverScanner::kStateScanning, Tlv::kSteeringData, Mle::kTypeDiscoveryResponse, Mle::Log(), Mle::LogProcessError(), otThreadLinkInfo::mChannel, otActiveScanResult::mChannel, otActiveScanResult::mDiscover, DiscoverScanner::mEnableFiltering, otActiveScanResult::mExtAddress, otActiveScanResult::mExtendedPanId, DiscoverScanner::mFilterIndexes, DiscoverScanner::mHandler, DiscoverScanner::mHandlerContext, otActiveScanResult::mIsNative, otActiveScanResult::mJoinerUdpPort, otThreadLinkInfo::mLqi, otActiveScanResult::mLqi, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, otActiveScanResult::mNetworkName, otThreadLinkInfo::mPanId, otActiveScanResult::mPanId, otThreadLinkInfo::mRss, otActiveScanResult::mRssi, DiscoverScanner::mState, otActiveScanResult::mSteeringData, otActiveScanResult::mVersion, Message::Read(), Tlv::ReadTlv(), SuccessOrExit, and VerifyOrExit.
Referenced by DiscoverScanner::Stop().
HandleDiscoverComplete()
void HandleDiscoverComplete (void) private
References ot::Mac::kPanIdBroadcast, DiscoverScanner::kStateIdle, DiscoverScanner::kStateScanDone, DiscoverScanner::kStateScanning, DiscoverScanner::mHandler, DiscoverScanner::mHandlerContext, DiscoverScanner::mShouldRestorePanId, DiscoverScanner::mState, DiscoverScanner::mTimer, OT_FALL_THROUGH, and TimerMilli::Stop().
Referenced by DiscoverScanner::HandleDiscoveryRequestFrameTxDone(), and DiscoverScanner::Stop().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and DiscoverScanner::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References ChannelMask::GetNextChannel(), ot::kErrorNone, DiscoverScanner::kStateScanDone, DiscoverScanner::kStateScanning, DiscoverScanner::mScanChannel, DiscoverScanner::mScanChannels, DiscoverScanner::mState, and VerifyOrExit.
Referenced by DiscoverScanner::HandleTimer(), and DiscoverScanner::Stop().
Friends And Related Function Documentation
ot::Instance
friend class ot::Instance friend
ot::MeshForwarder
friend class ot::MeshForwarder friend
Mle
friend class Mle friend
Field Documentation
kDefaultScanDuration
constexpr uint32_t kDefaultScanDuration = Mac::kScanDurationDefault static
Default scan duration (per channel), in milliseconds.
Referenced by DiscoverScanner::HandleDiscoveryRequestFrameTxDone().
kMaxOui
constexpr uint32_t kMaxOui = 0xffffff static private
Referenced by DiscoverScanner::SetJoinerAdvertisement().
mHandler
Handler mHandler private
Referenced by DiscoverScanner::Discover(), DiscoverScanner::HandleDiscoverComplete(), and DiscoverScanner::HandleDiscoveryResponse().
mHandlerContext
void* mHandlerContext private
Referenced by DiscoverScanner::Discover(), DiscoverScanner::HandleDiscoverComplete(), and DiscoverScanner::HandleDiscoveryResponse().
mTimer
TimerMilli mTimer private
Referenced by DiscoverScanner::HandleDiscoverComplete(), and DiscoverScanner::HandleDiscoveryRequestFrameTxDone().
mFilterIndexes
FilterIndexes mFilterIndexes private
Referenced by DiscoverScanner::Discover(), and DiscoverScanner::HandleDiscoveryResponse().
mScanChannels
Mac::ChannelMask mScanChannels private
Referenced by DiscoverScanner::Discover(), and DiscoverScanner::HandleTimer().
mState
State mState private
Referenced by DiscoverScanner::Discover(), DiscoverScanner::HandleDiscoverComplete(), DiscoverScanner::HandleDiscoveryRequestFrameTxDone(), DiscoverScanner::HandleDiscoveryResponse(), DiscoverScanner::HandleTimer(), DiscoverScanner::IsInProgress(), and DiscoverScanner::PrepareDiscoveryRequestFrame().
mOui
uint32_t mOui private
Referenced by DiscoverScanner::Discover(), and DiscoverScanner::SetJoinerAdvertisement().
mScanChannel
uint8_t mScanChannel private
Referenced by DiscoverScanner::Discover(), DiscoverScanner::HandleTimer(), and DiscoverScanner::PrepareDiscoveryRequestFrame().
mAdvDataLength
uint8_t mAdvDataLength private
Referenced by DiscoverScanner::Discover(), and DiscoverScanner::SetJoinerAdvertisement().
mAdvData
uint8_t mAdvData[MeshCoP::JoinerAdvertisementTlv::kAdvDataMaxLength] private
Referenced by DiscoverScanner::Discover(), and DiscoverScanner::SetJoinerAdvertisement().
mEnableFiltering
bool mEnableFiltering private
Referenced by DiscoverScanner::Discover(), and DiscoverScanner::HandleDiscoveryResponse().
mShouldRestorePanId
bool mShouldRestorePanId private
Referenced by DiscoverScanner::Discover(), and DiscoverScanner::HandleDiscoverComplete().
The documentation for this class was generated from the following files:
discover_scanner.hpp
discover_scanner.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale