OpenThread: BitVector< N > Class Template Reference
BitVector< N > Class Template Reference
Core-bit-vector
#include <bit_vector.hpp>
Public Member Functions
bool Get (uint16_t aIndex) const
bool HasAny (void) const
void Set (uint16_t aIndex, bool aValue)
Public Member Functions inherited from Equatable< BitVector< N > >
bool operator== (const BitVector< N > &aOther) const
Public Member Functions inherited from Unequatable< BitVector< N > >
bool operator!= (const BitVector< N > &aOther) const
Public Member Functions inherited from Clearable< BitVector< N > >
void Clear (void)
Private Attributes
uint8_t mMask [BitVectorBytes(N)]
Detailed Description
template<uint16_t N>
class ot::BitVector< N >
This class represents a bit-vector.
Template Parameters
N Specifies the number of bits.
Member Function Documentation
Get()
bool Get (uint16_t aIndex) const inline
This method indicates whether a given index is included in the mask.
Parameters
[in] aIndex The index.
Return values
TRUE If the given index is set.
FALSE If the given index is clear.
Set()
void Set (uint16_t aIndex, bool aValue) inline
This method sets the mask of a given index.
Parameters
[in] aIndex The index.
[in] aValue TRUE to set the mask, or FALSE to clear the mask.
HasAny()
bool HasAny (void) const inline
This method returns if any mask is set.
Return values
TRUE If any index is set.
FALSE If all indexes are clear.
Field Documentation
mMask
uint8_t mMask[BitVectorBytes(N)] private
Referenced by BitVector< OPENTHREAD_CONFIG_MLE_MAX_CHILDREN >::Get(), BitVector< OPENTHREAD_CONFIG_MLE_MAX_CHILDREN >::HasAny(), and BitVector< OPENTHREAD_CONFIG_MLE_MAX_CHILDREN >::Set().
The documentation for this class was generated from the following file:
bit_vector.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale