OpenThread: ExtAddress Class Reference
ExtAddress Class Reference
Core-mac
#include <mac_types.hpp>
Public Types
enum CopyByteOrder : uint8_t { kNormalByteOrder, kReverseByteOrder }
typedef String< kInfoStringSize > InfoString
Public Member Functions
void CopyTo (uint8_t *aBuffer, CopyByteOrder aByteOrder=kNormalByteOrder) const
void Fill (uint8_t aByte)
void GenerateRandom (void)
bool IsGroup (void) const
bool IsLocal (void) const
void Set (const uint8_t *aBuffer, CopyByteOrder aByteOrder=kNormalByteOrder)
void SetGroup (bool aGroup)
void SetLocal (bool aLocal)
void ToggleGroup (void)
void ToggleLocal (void)
InfoString ToString (void) const
Public Member Functions inherited from Equatable< ExtAddress >
bool operator== (const ExtAddress &aOther) const
Public Member Functions inherited from Unequatable< ExtAddress >
bool operator!= (const ExtAddress &aOther) const
Public Member Functions inherited from Clearable< ExtAddress >
void Clear (void)
Static Public Attributes
static constexpr uint16_t kInfoStringSize = 17
Max chars for the info string (ToString()).
Static Private Member Functions
static void CopyAddress (uint8_t *aDst, const uint8_t *aSrc, CopyByteOrder aByteOrder)
Static Private Attributes
static constexpr uint8_t kGroupFlag = (1 << 0)
static constexpr uint8_t kLocalFlag = (1 << 1)
Additional Inherited Members
Data Fields inherited from otExtAddress
uint8_t m8 [OT_EXT_ADDRESS_SIZE]
IEEE 802.15.4 Extended Address bytes.
Detailed Description
This structure represents an IEEE 802.15.4 Extended Address.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Enumeration Documentation
CopyByteOrder
enum CopyByteOrder : uint8_t
This enumeration type specifies the copy byte order when Extended Address is being copied to/from a buffer.
Enumerator
kNormalByteOrder
Copy address bytes in normal order (as provided in array buffer).
kReverseByteOrder
Copy address bytes in reverse byte order.
Member Function Documentation
Fill()
void Fill (uint8_t aByte) inline
This method fills all bytes of address with a given byte value.
Parameters
[in] aByte A byte value to fill address with.
References ExtAddress::GenerateRandom().
GenerateRandom()
void GenerateRandom (void)
This method generates a random IEEE 802.15.4 Extended Address.
References ot::Random::Crypto::FillBuffer(), IgnoreError(), otExtAddress::m8, ExtAddress::SetGroup(), and ExtAddress::SetLocal().
Referenced by ExtAddress::Fill(), JoinerDiscerner::GenerateJoinerId(), and Mac::Mac().
Set()
void Set (const uint8_t * aBuffer, CopyByteOrder aByteOrder = kNormalByteOrder) inline
This method sets the Extended Address from a given byte array.
Parameters
[in] aBuffer Pointer to an array containing the Extended Address. OT_EXT_ADDRESS_SIZE bytes from buffer are copied to form the Extended Address.
[in] aByteOrder The byte order to use when copying the address.
References ExtAddress::CopyAddress(), and otExtAddress::m8.
Referenced by InterfaceIdentifier::ConvertToExtAddress(), LinkFrameCounters::Reset(), and SubMac::SetExtAddress().
IsGroup()
bool IsGroup (void) const inline
This method indicates whether or not the Group bit is set.
Return values
TRUE If the group bit is set.
FALSE If the group bit is not set.
References ExtAddress::kGroupFlag, and otExtAddress::m8.
SetGroup()
void SetGroup (bool aGroup) inline
This method sets the Group bit.
Parameters
[in] aGroup TRUE if group address, FALSE otherwise.
References ExtAddress::kGroupFlag, and otExtAddress::m8.
Referenced by ExtAddress::GenerateRandom().
ToggleGroup()
void ToggleGroup (void) inline
This method toggles the Group bit.
References ExtAddress::kGroupFlag, and otExtAddress::m8.
IsLocal()
bool IsLocal (void) const inline
This method indicates whether or not the Local bit is set.
Return values
TRUE If the local bit is set.
FALSE If the local bit is not set.
References ExtAddress::kLocalFlag, and otExtAddress::m8.
SetLocal()
void SetLocal (bool aLocal) inline
This method sets the Local bit.
Parameters
[in] aLocal TRUE if locally administered, FALSE otherwise.
References ExtAddress::kLocalFlag, and otExtAddress::m8.
Referenced by ot::MeshCoP::ComputeJoinerId(), JoinerDiscerner::GenerateJoinerId(), and ExtAddress::GenerateRandom().
ToggleLocal()
void ToggleLocal (void) inline
This method toggles the Local bit.
References ExtAddress::kLocalFlag, and otExtAddress::m8.
Referenced by InterfaceIdentifier::ConvertToExtAddress(), InterfaceIdentifier::ConvertToMacAddress(), and InterfaceIdentifier::SetFromExtAddress().
CopyTo()
void CopyTo (uint8_t * aBuffer, CopyByteOrder aByteOrder = kNormalByteOrder) const inline
This method copies the Extended Address into a given buffer.
Parameters
[out] aBuffer A pointer to a buffer to copy the Extended Address into.
[in] aByteOrder The byte order to copy the address.
References ExtAddress::CopyAddress(), otExtAddress::m8, and ExtAddress::ToString().
Referenced by Frame::SetDstAddr(), InterfaceIdentifier::SetFromExtAddress(), and Frame::SetSrcAddr().
ToString()
ExtAddress::InfoString ToString (void) const
This method converts an address to a string.
Returns
An InfoString containing the string representation of the Extended Address.
References StringWriter::AppendHexBytes(), and otExtAddress::m8.
Referenced by ExtAddress::CopyTo(), Address::IsShortAddrInvalid(), SubMac::SetExtAddress(), KeyMaterial::SetKey(), and MeshForwarder::UpdateNeighborLinkFailures().
CopyAddress()
void CopyAddress (uint8_t * aDst, const uint8_t * aSrc, CopyByteOrder aByteOrder) static private
References ExtAddress::kNormalByteOrder, and ExtAddress::kReverseByteOrder.
Referenced by ExtAddress::CopyTo(), and ExtAddress::Set().
Field Documentation
kInfoStringSize
constexpr uint16_t kInfoStringSize = 17 static
Max chars for the info string (ToString()).
Referenced by KeyMaterial::SetKey().
kGroupFlag
constexpr uint8_t kGroupFlag = (1 << 0) static private
Referenced by ExtAddress::IsGroup(), ExtAddress::SetGroup(), and ExtAddress::ToggleGroup().
kLocalFlag
constexpr uint8_t kLocalFlag = (1 << 1) static private
Referenced by ExtAddress::IsLocal(), ExtAddress::SetLocal(), and ExtAddress::ToggleLocal().
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale