OpenThread: ThreadNetif Class Reference
ThreadNetif Class Reference
Core-netif
#include <thread_netif.hpp>
Public Member Functions
void Down (void)
bool IsOnMesh (const Ip6::Address &aAddress) const
bool IsUp (void) const
Error RouteLookup (const Ip6::Address &aSource, const Ip6::Address &aDestination, uint8_t *aPrefixMatch)
Error SendMessage (Message &aMessage)
ThreadNetif (Instance &aInstance)
void Up (void)
Public Member Functions inherited from Netif
Error AddExternalUnicastAddress (const UnicastAddress &aAddress)
void AddUnicastAddress (UnicastAddress &aAddress)
const LinkedList< MulticastAddress > & GetMulticastAddresses (void) const
const LinkedList< UnicastAddress > & GetUnicastAddresses (void) const
bool HasAnyExternalMulticastAddress (void) const
bool HasUnicastAddress (const Address &aAddress) const
bool HasUnicastAddress (const UnicastAddress &aAddress) const
bool IsMulticastAddressExternal (const MulticastAddress &aAddress) const
bool IsMulticastPromiscuousEnabled (void) const
bool IsMulticastSubscribed (const Address &aAddress) const
bool IsUnicastAddressExternal (const UnicastAddress &aAddress) const
ExternalMulticastAddress::Iterator::Builder IterateExternalMulticastAddresses (Address::TypeFilter aFilter=Address::kTypeAny)
Netif (Instance &aInstance)
void RemoveAllExternalUnicastAddresses (void)
Error RemoveExternalUnicastAddress (const Address &aAddress)
void RemoveUnicastAddress (const UnicastAddress &aAddress)
void SetAddressCallback (otIp6AddressCallback aCallback, void *aCallbackContext)
void SetMulticastPromiscuous (bool aEnabled)
void SubscribeAllRoutersMulticast (void)
Error SubscribeExternalMulticast (const Address &aAddress)
void SubscribeMulticast (MulticastAddress &aAddress)
void UnsubscribeAllExternalMulticastAddresses (void)
void UnsubscribeAllRoutersMulticast (void)
Error UnsubscribeExternalMulticast (const Address &aAddress)
void UnsubscribeMulticast (const MulticastAddress &aAddress)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Attributes
bool mIsUp
Additional Inherited Members
Public Types inherited from Netif
enum AddressEvent : bool { kAddressRemoved = false, kAddressAdded = true }
enum AddressOrigin : uint8_t { kOriginThread = OT_ADDRESS_ORIGIN_THREAD, kOriginSlaac = OT_ADDRESS_ORIGIN_SLAAC, kOriginDhcp6 = OT_ADDRESS_ORIGIN_DHCPV6, kOriginManual = OT_ADDRESS_ORIGIN_MANUAL }
Protected Member Functions inherited from Netif
void SubscribeAllNodesMulticast (void)
void UnsubscribeAllNodesMulticast (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Constructor & Destructor Documentation
ThreadNetif()
ThreadNetif (Instance & aInstance) explicit
This constructor initializes the Thread network interface.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Up()
void Up (void)
This method enables the Thread network interface.
References IgnoreError(), ot::kEventThreadNetifStateChanged, ThreadNetif::mIsUp, Netif::SubscribeAllNodesMulticast(), and VerifyOrExit.
Down()
void Down (void)
This method disables the Thread network interface.
References IgnoreError(), ot::kEventThreadNetifStateChanged, ThreadNetif::mIsUp, Netif::RemoveAllExternalUnicastAddresses(), Netif::UnsubscribeAllExternalMulticastAddresses(), Netif::UnsubscribeAllNodesMulticast(), Netif::UnsubscribeAllRoutersMulticast(), and VerifyOrExit.
IsUp()
bool IsUp (void) const inline
This method indicates whether or not the Thread network interface is enabled.
Return values
TRUE If the Thread network interface is enabled.
FALSE If the Thread network interface is not enabled.
References ThreadNetif::IsOnMesh(), ThreadNetif::mIsUp, ThreadNetif::RouteLookup(), and ThreadNetif::SendMessage().
Referenced by otLinkSetEnabled(), and otLinkSetPromiscuous().
SendMessage()
Error SendMessage (Message & aMessage)
This method submits a message to the network interface.
Parameters
[in] aMessage A reference to the message.
Return values
kErrorNone Successfully submitted the message to the interface.
Referenced by ThreadNetif::IsUp().
RouteLookup()
Error RouteLookup (const Ip6::Address & aSource, const Ip6::Address & aDestination, uint8_t * aPrefixMatch)
This method performs a route lookup.
Parameters
[in] aSource A reference to the IPv6 source address.
[in] aDestination A reference to the IPv6 destination address.
[out] aPrefixMatch A pointer where the number of prefix match bits for the chosen route is stored.
Return values
kErrorNone Successfully found a route.
kErrorNoRoute Could not find a valid route.
References ot::kErrorNoRoute, and SuccessOrExit.
Referenced by ThreadNetif::IsUp().
IsOnMesh()
bool IsOnMesh (const Ip6::Address & aAddress) const
This method indicates whether aAddress matches an on-mesh prefix.
Parameters
[in] aAddress The IPv6 address.
Return values
TRUE If aAddress matches an on-mesh prefix.
FALSE If aAddress does not match an on-mesh prefix.
Referenced by ThreadNetif::IsUp().
Field Documentation
mIsUp
bool mIsUp private
Referenced by ThreadNetif::Down(), ThreadNetif::IsUp(), and ThreadNetif::Up().
The documentation for this class was generated from the following files:
thread_netif.hpp
thread_netif.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale