OpenThread: Manager Class Reference
Manager Class Reference
#include <mainloop.hpp>
Public Member Functions
void Add (Source &aSource)
void Process (const otSysMainloopContext &aContext)
void Remove (Source &aSource)
void Update (otSysMainloopContext &aContext)
Static Public Member Functions
static Manager & Get (void)
Private Attributes
Source * mSources = nullptr
Detailed Description
This class manages mainloop.
Member Function Documentation
Update()
void Update (otSysMainloopContext & aContext)
This method updates event polls in the mainloop context.
Parameters
[in,out] aContext A reference to the mainloop context.
References Source::mNext, and Manager::mSources.
Referenced by otSysMainloopUpdate().
Process()
void Process (const otSysMainloopContext & aContext)
This method processes events in the mainloop context.
Parameters
[in] aContext A reference to the mainloop context.
References Source::mNext, and Manager::mSources.
Referenced by otSysMainloopProcess().
Add()
void Add (Source & aSource)
This method adds a new event source into the mainloop.
Parameters
[in] aSource A reference to the event source.
References Source::mNext, and Manager::mSources.
Remove()
void Remove (Source & aSource)
This method removes an event source from the mainloop.
Parameters
[in] aSource A reference to the event source.
References Source::mNext, and Manager::mSources.
Get()
Manager & Get (void) static
This function returns the Mainloop singleton.
Returns
A refernce to the Mainloop singleton.
Referenced by otSysMainloopProcess(), and otSysMainloopUpdate().
Field Documentation
mSources
Source* mSources = nullptr private
Referenced by Manager::Add(), Manager::Process(), Manager::Remove(), and Manager::Update().
The documentation for this class was generated from the following files:
mainloop.hpp
mainloop.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale