OpenThread: Data< kDataLengthType > Class Template Reference
Data< kDataLengthType > Class Template Reference
#include <data.hpp>
Public Types
using LengthType = typename TypeTraits::Conditional< kDataLengthType==kWithUint8Length, uint8_t, uint16_t >::Type
Public Member Functions
void CopyBytesTo (void *aBuffer) const
const uint8_t * GetBytes (void) const
LengthType GetLength (void) const
void Init (const void *aBuffer, LengthType aLength)
template<typename ObjectType >
void InitFrom (const ObjectType &aObject)
void InitFromRange (const uint8_t *aStart, const uint8_t *aEnd)
bool MatchesBytesIn (const void *aBuffer) const
bool MatchesBytesIn (const void *aBuffer, ByteMatcher aMatcher)
bool operator== (const Data &aOtherData) const
void SetLength (LengthType aLength)
bool StartsWith (const Data &aOtherData) const
Public Member Functions inherited from Clearable< Data< kDataLengthType > >
void Clear (void)
Public Member Functions inherited from Unequatable< Data< kDataLengthType > >
bool operator!= (const Data< kDataLengthType > &aOther) const
Private Attributes
const uint8_t * mBuffer
LengthType mLength
Friends
class MutableData< kDataLengthType >
Additional Inherited Members
Private Member Functions inherited from DataUtils
DataUtils (void)=default
Static Private Member Functions inherited from DataUtils
static bool MatchBytes (const uint8_t *aFirstBuffer, const uint8_t *aSecondBuffer, uint16_t aLength, ByteMatcher aMatcher)
Detailed Description
template<DataLengthType kDataLengthType>
class ot::Data< kDataLengthType >
This type represents a generic Data which is simply a wrapper over a pointer to a buffer with a given data length.
The data length can be either uint8_t or uint16_t (determined by the template parameter kDataLengthType).
While a Data instance itself can change (for example, it can be updated to point to another buffer), it always treats the content of the buffer as immutable.
A Data instance MUST be initialized (using any of the Init() methods) before calling any other methods on the instance (e.g., GetBytes() or GetLength()), otherwise the behavior is undefined.
Template Parameters
kDataLengthType Determines the data length type (uint8_t or uint16_t).
Member Typedef Documentation
LengthType
using LengthType = typename TypeTraits::Conditional<kDataLengthType == kWithUint8Length, uint8_t, uint16_t>::Type
This type represents the data length type (uint8_t or uint16_t).
Member Function Documentation
Init()
void Init (const void * aBuffer, LengthType aLength) inline
This method initializes the Data to point to a given buffer with a given length.
Parameters
[in] aBuffer A pointer to a buffer containing the data.
[in] aLength The data length (number of bytes in aBuffer)
Referenced by Headers::DecompressFrom(), Appender::GetAsData(), Manager::GetBackboneRouterPrimary(), ServiceConfig::ServerConfig::GetServerData(), ServerTlv::GetServerData(), ServiceConfig::GetServiceData(), ServiceTlv::GetServiceData(), Manager::GetServiceId(), and MeshForwarder::HandleReceivedFrame().
InitFromRange()
void InitFromRange (const uint8_t * aStart, const uint8_t * aEnd) inline
This method initializes the Data to point to a range of bytes in a given buffer.
The range is specified by the pointers to its start aStart and its end aEnd. Data will point to the bytes in the buffer from aStart up to but excluding aEnd (i.e., aStart <= bytes < aEnd).
Parameters
[in] aStart Pointer to the start of the range.
[in] aEnd Pointer to the end of the range.
InitFrom()
void InitFrom (const ObjectType & aObject) inline
This template method initializes the Data to point to the content of an object.
ObjectType The object type (MUST not be a pointer type).
Parameters
[in] aObject The object to initialize the Data with.
Referenced by Manager::GetNextDnsSrpAnycastInfo(), and Manager::GetNextDnsSrpUnicastInfo().
GetBytes()
const uint8_t* GetBytes (void) const inline
This method returns a pointer to the data bytes buffer.
Returns
A pointer to the data bytes buffer (can be nullptr if Data is cleared).
Referenced by Message::AppendData(), Checksum::Calculate(), MutableData< kWithUint16Length >::CopyBytesFrom(), Lowpan::Decompress(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressExtensionHeader(), Manager::GetBackboneRouterPrimary(), Manager::GetNextDnsSrpAnycastInfo(), Manager::GetNextDnsSrpUnicastInfo(), FragmentHeader::IsFragmentHeader(), Lowpan::IsLowpanHc(), MeshHeader::IsMeshHeader(), MeshHeader::ParseFrom(), FragmentHeader::ParseFrom(), HmacSha256::Update(), Sha256::Update(), and Message::WriteData().
GetLength()
LengthType GetLength (void) const inline
This method returns the data length.
Returns
The data length (number of bytes).
Referenced by Message::AppendData(), TxtEntry::AppendEntries(), Checksum::Calculate(), MutableData< kWithUint16Length >::CopyBytesFrom(), Data::CopyBytesTo(), NameData::CopyTo(), Lowpan::Decompress(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressUdpHeader(), MeshForwarder::FrameToMessage(), Manager::GetBackboneRouterPrimary(), NameData::GetLength(), Data::GetLength(), Manager::GetNextDnsSrpUnicastInfo(), MeshForwarder::HandleFragment(), MeshForwarder::HandleLowpanHC(), MeshForwarder::HandleReceivedFrame(), ServiceTlv::Init(), ServerTlv::Init(), FragmentHeader::IsFragmentHeader(), Lowpan::IsLowpanHc(), MeshHeader::IsMeshHeader(), MeshHeader::ParseFrom(), FragmentHeader::ParseFrom(), AesCcm::Payload(), ServiceConfig::ServerConfig::SetFrom(), ServiceConfig::SetFrom(), HmacSha256::Update(), Sha256::Update(), Data::UpdateBuffer(), and Message::WriteData().
SetLength()
void SetLength (LengthType aLength) inline
This method sets the data length.
Parameters
[in] aLength The data length (number of bytes).
Referenced by NetworkName::Set().
CopyBytesTo()
void CopyBytesTo (void * aBuffer) const inline
This method copies the Data bytes to a given buffer.
It is up to the caller to ensure that aBuffer has enough space for the current data length.
Parameters
[out] aBuffer The buffer to copy the bytes into.
Referenced by Data::CopyBytesTo(), ServiceTlv::Init(), ServerTlv::Init(), NetworkName::Set(), ServiceConfig::ServerConfig::SetFrom(), and ServiceConfig::SetFrom().
MatchesBytesIn() [1/2]
bool MatchesBytesIn (const void * aBuffer) const inline
This method compares the Data content with the bytes from a given buffer.
It is up to the caller to ensure that aBuffer has enough bytes to compare with the current data length.
Parameters
[in] aBuffer A pointer to a buffer to compare with the data.
Return values
TRUE The Data content matches the bytes in aBuffer.
FALSE The Data content does not match the byes in aBuffer.
Referenced by NetworkName::Set(), and Data< kWithUint8Length >::StartsWith().
MatchesBytesIn() [2/2]
bool MatchesBytesIn (const void * aBuffer, ByteMatcher aMatcher) inline
This method compares the Data content with the bytes from a given buffer using a given Matcher function.
It is up to the caller to ensure that aBuffer has enough bytes to compare with the current data length.
Parameters
[in] aBuffer A pointer to a buffer to compare with the data.
[in] aMatcher A ByteMatcher function to match the bytes. If nullptr, bytes are compared directly.
Return values
TRUE The Data content matches the bytes in aBuffer.
FALSE The Data content does not match the byes in aBuffer.
operator==()
bool operator== (const Data< kDataLengthType > & aOtherData) const inline
This method overloads operator == to compare the Data content with the content from another one.
Parameters
[in] aOtherData The other Data to compare with.
Return values
TRUE The two Data instances have matching content (same length and same bytes).
FALSE The two Data instances do not have matching content.
StartsWith()
bool StartsWith (const Data< kDataLengthType > & aOtherData) const inline
This method checks whether the Data starts with the same byte content as from another Data instance.
This method checks that the Data instance contains the same bytes as aOtherData but allows it to have additional bytes at the end.
Parameters
[in] aOtherData The other Data to compare with.
Return values
TRUE This Data starts with the same byte content as in aOtherData.
FALSE This Data does not start with the same byte content as in aOtherData.
Referenced by NetworkData::MatchService().
Friends And Related Function Documentation
MutableData< kDataLengthType >
friend class MutableData< kDataLengthType > friend
Field Documentation
mBuffer
const uint8_t* mBuffer private
Referenced by Data< kWithUint8Length >::operator==().
mLength
LengthType mLength private
Referenced by Data< kWithUint8Length >::operator==(), and Data< kWithUint8Length >::StartsWith().
The documentation for this class was generated from the following file:
data.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale