OpenThread: Dataset::Components Class Reference
Dataset::Components Class Reference
#include <dataset.hpp>
Public Member Functions
bool IsActiveTimestampPresent (void) const
bool IsChannelMaskPresent (void) const
bool IsChannelPresent (void) const
bool IsDelayPresent (void) const
bool IsExtendedPanIdPresent (void) const
bool IsMeshLocalPrefixPresent (void) const
bool IsNetworkKeyPresent (void) const
bool IsNetworkNamePresent (void) const
bool IsPanIdPresent (void) const
bool IsPendingTimestampPresent (void) const
bool IsPskcPresent (void) const
bool IsSecurityPolicyPresent (void) const
Public Member Functions inherited from Clearable< Components >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otOperationalDatasetComponents
bool mIsActiveTimestampPresent: 1
TRUE if Active Timestamp is present, FALSE otherwise.
bool mIsChannelMaskPresent: 1
TRUE if Channel Mask is present, FALSE otherwise.
bool mIsChannelPresent: 1
TRUE if Channel is present, FALSE otherwise.
bool mIsDelayPresent: 1
TRUE if Delay Timer is present, FALSE otherwise.
bool mIsExtendedPanIdPresent: 1
TRUE if Extended PAN ID is present, FALSE otherwise.
bool mIsMeshLocalPrefixPresent: 1
TRUE if Mesh Local Prefix is present, FALSE otherwise.
bool mIsNetworkKeyPresent: 1
TRUE if Network Key is present, FALSE otherwise.
bool mIsNetworkNamePresent: 1
TRUE if Network Name is present, FALSE otherwise.
bool mIsPanIdPresent: 1
TRUE if PAN ID is present, FALSE otherwise.
bool mIsPendingTimestampPresent: 1
TRUE if Pending Timestamp is present, FALSE otherwise.
bool mIsPskcPresent: 1
TRUE if PSKc is present, FALSE otherwise.
bool mIsSecurityPolicyPresent: 1
TRUE if Security Policy is present, FALSE otherwise.
Detailed Description
This class represents presence of different components in Active or Pending Operational Dataset.
Member Function Documentation
IsActiveTimestampPresent()
bool IsActiveTimestampPresent (void) const inline
This method indicates whether or not the Active Timestamp is present in the Dataset.
Returns
TRUE if Active Timestamp is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsActiveTimestampPresent.
Referenced by DatasetManager::SendGetRequest().
IsPendingTimestampPresent()
bool IsPendingTimestampPresent (void) const inline
This method indicates whether or not the Pending Timestamp is present in the Dataset.
Returns
TRUE if Pending Timestamp is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsPendingTimestampPresent.
Referenced by DatasetManager::SendGetRequest().
IsNetworkKeyPresent()
bool IsNetworkKeyPresent (void) const inline
This method indicates whether or not the Network Key is present in the Dataset.
Returns
TRUE if Network Key is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsNetworkKeyPresent.
Referenced by DatasetManager::SendGetRequest().
IsNetworkNamePresent()
bool IsNetworkNamePresent (void) const inline
This method indicates whether or not the Network Name is present in the Dataset.
Returns
TRUE if Network Name is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsNetworkNamePresent.
Referenced by DatasetManager::SendGetRequest().
IsExtendedPanIdPresent()
bool IsExtendedPanIdPresent (void) const inline
This method indicates whether or not the Extended PAN ID is present in the Dataset.
Returns
TRUE if Extended PAN ID is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsExtendedPanIdPresent.
Referenced by DatasetManager::SendGetRequest().
IsMeshLocalPrefixPresent()
bool IsMeshLocalPrefixPresent (void) const inline
This method indicates whether or not the Mesh Local Prefix is present in the Dataset.
Returns
TRUE if Mesh Local Prefix is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsMeshLocalPrefixPresent.
Referenced by DatasetManager::SendGetRequest().
IsDelayPresent()
bool IsDelayPresent (void) const inline
This method indicates whether or not the Delay Timer is present in the Dataset.
Returns
TRUE if Delay Timer is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsDelayPresent.
Referenced by DatasetManager::SendGetRequest().
IsPanIdPresent()
bool IsPanIdPresent (void) const inline
This method indicates whether or not the PAN ID is present in the Dataset.
Returns
TRUE if PAN ID is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsPanIdPresent.
Referenced by DatasetManager::SendGetRequest().
IsChannelPresent()
bool IsChannelPresent (void) const inline
This method indicates whether or not the Channel is present in the Dataset.
Returns
TRUE if Channel is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsChannelPresent.
Referenced by DatasetManager::SendGetRequest().
IsPskcPresent()
bool IsPskcPresent (void) const inline
This method indicates whether or not the PSKc is present in the Dataset.
Returns
TRUE if PSKc is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsPskcPresent.
Referenced by DatasetManager::SendGetRequest().
IsSecurityPolicyPresent()
bool IsSecurityPolicyPresent (void) const inline
This method indicates whether or not the Security Policy is present in the Dataset.
Returns
TRUE if Security Policy is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsSecurityPolicyPresent.
Referenced by DatasetManager::SendGetRequest().
IsChannelMaskPresent()
bool IsChannelMaskPresent (void) const inline
This method indicates whether or not the Channel Mask is present in the Dataset.
Returns
TRUE if Channel Mask is present, FALSE otherwise.
References otOperationalDatasetComponents::mIsChannelMaskPresent.
Referenced by DatasetManager::SendGetRequest().
The documentation for this class was generated from the following file:
dataset.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale