OpenThread: AddressResolver Class Reference
AddressResolver Class Reference
Core-arp
#include <address_resolver.hpp>
Public Types
typedef otCacheEntryInfo EntryInfo
typedef otCacheEntryIterator Iterator
Public Member Functions
AddressResolver (Instance &aInstance)
void HandleAddressError (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Member Functions
static void HandleAddressError (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Data Fields
Coap::Resource mAddressError
Friends
class TimeTicker
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Detailed Description
This class implements the EID-to-RLOC mapping and caching.
Member Typedef Documentation
Iterator
typedef otCacheEntryIterator Iterator
This type represents an iterator used for iterating through the EID cache table entries.
EntryInfo
typedef otCacheEntryInfo EntryInfo
This type represents an EID cache entry.
Constructor & Destructor Documentation
AddressResolver()
AddressResolver (Instance & aInstance) explicit
This constructor initializes the object.
References Message::AppendUriPathOptions(), ot::AsCoapMessage(), ot::AsCoreType(), String< kSize >::AsCString(), ot::ErrorToString(), ExitNow, FreeMessage, FreeMessageOnError, Address::GetIid(), InstanceLocator::GetInstance(), InterfaceIdentifier::GetLocator(), MessageInfo::GetPeerAddr(), IgnoreError(), Message::Init(), Message::IsConfirmablePostRequest(), UriPath::kAddressError, UriPath::kAddressQuery, TimeTicker::kAddressResolver, ot::Coap::kCodePost, ot::kErrorAddressQuery, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNotFound, ot::Mac::kShortAddrInvalid, ot::Coap::kTypeConfirmable, ot::Coap::kTypeNonConfirmable, LogInfo, AddressResolver::mAddressError, otCacheEntryInfo::mCanEvict, otCacheEntryIterator::mData, otCacheEntryInfo::mLastTransTime, otCacheEntryInfo::mMeshLocalEid, otCacheEntryInfo::mRetryDelay, otCacheEntryInfo::mRloc16, otCacheEntryInfo::mState, otCacheEntryInfo::mTarget, otCacheEntryInfo::mTimeout, otCacheEntryInfo::mValidLastTrans, OT_CACHE_ENTRY_STATE_CACHED, OT_CACHE_ENTRY_STATE_QUERY, OT_CACHE_ENTRY_STATE_RETRY_QUERY, OT_CACHE_ENTRY_STATE_SNOOPED, Mle::Rloc16FromRouterId(), Mle::RouterIdMatch(), Message::SetPayloadMarker(), MessageInfo::SetSockAddrToRlocPeerAddrTo(), MessageInfo::SetSockAddrToRlocPeerAddrToRealmLocalAllRoutersMulticast(), SuccessOrExit, Address::ToString(), and VerifyOrExit.
Member Function Documentation
HandleAddressError() [1/2]
void HandleAddressError (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
References ot::AsCoapMessage(), and ot::AsCoreType().
HandleAddressError() [2/2]
void HandleAddressError (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo)
References ot::AsCoapMessage(), ot::AsCoreType(), String< kSize >::AsCString(), InterfaceIdentifier::ConvertToExtAddress(), ot::ErrorToString(), ExitNow, FreeMessageOnError, Icmp::Header::GetCode(), Header::GetDestination(), Address::GetIid(), InstanceLocator::GetInstance(), InterfaceIdentifier::GetLocator(), TimerMilli::GetNow(), Message::GetOffset(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Icmp::Header::GetType(), IgnoreError(), InstanceLocatorInit::Init(), Message::IsConfirmable(), Address::IsMulticast(), Message::IsNonConfirmablePostRequest(), Message::IsPostRequest(), UriPath::kAddressNotify, TimeTicker::kAddressResolver, Icmp::Header::kCodeDstUnreachNoRoute, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNone, ot::Mle::kFailedChildTransmissions, Icmp::Header::kTypeDstUnreach, LogInfo, LogWarn, Time::MsecToSec(), OT_ASSERT, OT_UNUSED_VARIABLE, Message::Read(), MessageInfo::SetSockAddrToRlocPeerAddrTo(), SuccessOrExit, Address::ToString(), and VerifyOrExit.
Friends And Related Function Documentation
TimeTicker
friend class TimeTicker friend
Field Documentation
mAddressError
Coap::Resource mAddressError
Referenced by AddressResolver::AddressResolver().
The documentation for this class was generated from the following files:
address_resolver.hpp
address_resolver.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale