OpenThread: NcpBase Class Reference
NcpBase Class Reference
#include <ncp_base.hpp>
Data Structures
struct HandlerEntry
struct ResponseEntry
Public Types
enum { kSpinelCmdHeaderSize = 2, kSpinelPropIdSize = 3 }
Public Member Functions
void HandleReceive (const uint8_t *aBuf, uint16_t aBufLength)
void IncrementFrameErrorCounter (void)
void Log (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aLogString)
NcpBase (Instance *aInstance)
bool ShouldDeferHostSend (void)
bool ShouldWakeHost (void)
otError StreamWrite (int aStreamId, const uint8_t *aDataPtr, int aDataLen)
Static Public Member Functions
static NcpBase * GetNcpInstance (void)
Protected Types
enum { kTxBufferSize = OPENTHREAD_CONFIG_NCP_TX_BUFFER_SIZE, kResponseQueueSize = OPENTHREAD_CONFIG_NCP_SPINEL_RESPONSE_QUEUE_SIZE, kInvalidScanChannel = -1 }
typedef otError(NcpBase::* PropertyHandler) (void)
enum ResponseType { kResponseTypeGet = 0, kResponseTypeSet, kResponseTypeLastStatus }
Protected Member Functions
otError CommandHandler_NOOP (uint8_t aHeader)
otError CommandHandler_PROP_VALUE_update (uint8_t aHeader, unsigned int aCommand)
otError CommandHandler_RESET (uint8_t aHeader)
otError DecodeChannelMask (uint32_t &aChannelMask)
otError EncodeChannelMask (uint32_t aChannelMask)
otError EnqueueResponse (uint8_t aHeader, ResponseType aType, unsigned int aPropKeyOrStatus)
Spinel::Buffer::FrameTag GetLastOutboundFrameTag (void)
otError HandleCommand (uint8_t aHeader)
otError HandleCommandPropertyInsertRemove (uint8_t aHeader, spinel_prop_key_t aKey, unsigned int aCommand)
otError HandleCommandPropertySet (uint8_t aHeader, spinel_prop_key_t aKey)
void HandleFrameRemovedFromNcpBuffer (Spinel::Buffer::FrameTag aFrameTag)
template<spinel_prop_key_t aKey>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<>
otError HandlePropertyGet (void)
template<spinel_prop_key_t aKey>
otError HandlePropertyInsert (void)
template<>
otError HandlePropertyInsert (void)
template<spinel_prop_key_t aKey>
otError HandlePropertyRemove (void)
template<>
otError HandlePropertyRemove (void)
template<spinel_prop_key_t aKey>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
template<>
otError HandlePropertySet (void)
otError HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE (uint8_t aHeader)
bool HandlePropertySetForSpecialProperties (uint8_t aHeader, spinel_prop_key_t aKey, otError &aError)
bool IsResponseQueueEmpty (void) const
otError PrepareGetResponse (uint8_t aHeader, spinel_prop_key_t aPropKey)
otError PrepareLastStatusResponse (uint8_t aHeader, spinel_status_t aStatus)
otError PrepareSetResponse (uint8_t aHeader, spinel_prop_key_t aPropKey)
void ResetCounters (void)
otError SendQueuedResponses (void)
void StartLegacy (void)
void StopLegacy (void)
void UpdateChangedProps (void)
otError WriteLastStatusFrame (uint8_t aHeader, spinel_status_t aLastStatus)
otError WritePropertyValueInsertedRemovedFrame (uint8_t aHeader, unsigned int aResponseCommand, spinel_prop_key_t aPropKey, const uint8_t *aValuePtr, uint16_t aValueLen)
otError WritePropertyValueIsFrame (uint8_t aHeader, spinel_prop_key_t aPropKey, bool aIsGetResponse=true)
Static Protected Member Functions
static uint8_t ConvertLogLevel (otLogLevel aLogLevel)
static unsigned int ConvertLogRegion (otLogRegion aLogRegion)
static PropertyHandler FindGetPropertyHandler (spinel_prop_key_t aKey)
static PropertyHandler FindInsertPropertyHandler (spinel_prop_key_t aKey)
static PropertyHandler FindPropertyHandler (const HandlerEntry *aHandlerEntries, size_t aSize, spinel_prop_key_t aKey)
static PropertyHandler FindRemovePropertyHandler (spinel_prop_key_t aKey)
static PropertyHandler FindSetPropertyHandler (spinel_prop_key_t aKey)
static uint8_t GetWrappedResponseQueueIndex (uint8_t aPosition)
static void HandleFrameRemovedFromNcpBuffer (void *aContext, Spinel::Buffer::FrameTag aFrameTag, Spinel::Buffer::Priority aPriority, Spinel::Buffer *aNcpBuffer)
static uint8_t LinkFlagsToFlagByte (bool aRxOnWhenIdle, bool aDeviceType, bool aNetworkData)
static spinel_status_t ThreadErrorToSpinelStatus (otError aError)
static void UpdateChangedProps (Tasklet &aTasklet)
Protected Attributes
bool mAllowLocalNetworkDataChange
ChangedPropsSet mChangedPropsSet
Spinel::Decoder mDecoder
bool mDidInitialUpdates
bool mDisableStreamWrite
bool mDiscoveryScanEnableFiltering
bool mDiscoveryScanJoinerFlag
uint16_t mDiscoveryScanPanId
Spinel::Encoder mEncoder
uint32_t mFramingErrorCounter
Spinel::Buffer::FrameTag mHostPowerReplyFrameTag
spinel_host_power_state_t mHostPowerState
uint8_t mHostPowerStateHeader
bool mHostPowerStateInProgress
Instance * mInstance
bool mIsRawStreamEnabled
spinel_status_t mLastStatus
uint64_t mLogTimestampBase
spinel_tid_t mNextExpectedTid
bool mPcapEnabled
bool mRequireJoinExistingNetwork
ResponseEntry mResponseQueue [kResponseQueueSize]
uint8_t mResponseQueueHead
uint8_t mResponseQueueTail
uint32_t mRxSpinelFrameCounter
uint32_t mRxSpinelOutOfOrderTidCounter
uint32_t mScanChannelMask
uint16_t mScanPeriod
bool mShouldEmitChildTableUpdate
uint32_t mThreadChangedFlags
uint8_t mTxBuffer [kTxBufferSize]
Spinel::Buffer mTxFrameBuffer
uint32_t mTxSpinelFrameCounter
Tasklet mUpdateChangedPropsTask
Static Protected Attributes
static NcpBase * sNcpInstance = nullptr
Member Typedef Documentation
PropertyHandler
typedef otError(NcpBase::* PropertyHandler) (void) protected
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kSpinelCmdHeaderSize
Size of spinel command header (in bytes).
kSpinelPropIdSize
Size of spinel property identifier (in bytes).
ResponseType
enum ResponseType protected
This enumeration represents the ResponseEntry type.
Enumerator
kResponseTypeGet
Response entry is for a VALUE_GET command.
kResponseTypeSet
Response entry is for a VALUE_SET command.
kResponseTypeLastStatus
Response entry is a VALUE_IS(LAST_STATUS).
anonymous enum
anonymous enum protected
Enumerator
kTxBufferSize
kResponseQueueSize
kInvalidScanChannel
Constructor & Destructor Documentation
NcpBase()
NcpBase (Instance * aInstance) explicit
This constructor creates and initializes an NcpBase instance.
Parameters
[in] aInstance The OpenThread instance structure.
References ChangedPropsSet::AddLastStatus(), Instance::Get(), NcpBase::HandleFrameRemovedFromNcpBuffer(), IgnoreError(), NcpBase::mChangedPropsSet, NcpBase::mInstance, NcpBase::mResponseQueue, NcpBase::mTxFrameBuffer, NcpBase::mUpdateChangedPropsTask, OT_ASSERT, OT_ICMP6_ECHO_HANDLER_DISABLED, otIcmp6SetEchoMode(), otIp6SetReceiveCallback(), otIp6SetReceiveFilterEnabled(), otMessageQueueInit(), otNetworkTimeSyncSetCallback(), otSetStateChangedCallback(), otSrpClientSetCallback(), otThreadRegisterNeighborTableCallback(), otThreadRegisterParentResponseCallback(), otUdpForwardSetForwarder(), Tasklet::Post(), Buffer::SetFrameRemovedCallback(), NcpBase::sNcpInstance, and SPINEL_STATUS_RESET_UNKNOWN.
Member Function Documentation
GetNcpInstance()
NcpBase * GetNcpInstance (void) static
This static method returns the pointer to the single NCP instance.
Returns
Pointer to the single NCP instance.
References NcpBase::sNcpInstance.
Referenced by NcpBase::HandlePropertyGet(), otNcpStreamWrite(), otPlatLog(), and NcpBase::UpdateChangedProps().
StreamWrite()
otError StreamWrite (int aStreamId, const uint8_t * aDataPtr, int aDataLen)
This method sends data to host via specific stream.
Parameters
[in] aStreamId A numeric identifier for the stream to write to. If set to '0', will default to the debug stream.
[in] aDataPtr A pointer to the data to send on the stream. If aDataLen is non-zero, this param MUST NOT be nullptr.
[in] aDataLen The number of bytes of data from aDataPtr to send.
Return values
OT_ERROR_NONE The data was queued for delivery to the host.
OT_ERROR_BUSY There are not enough resources to complete this request. This is usually a temporary condition.
OT_ERROR_INVALID_ARGS The given aStreamId was invalid.
References ChangedPropsSet::AddLastStatus(), Encoder::BeginFrame(), Encoder::EndFrame(), ChangedPropsSet::IsPropertyFiltered(), NcpBase::IsResponseQueueEmpty(), NcpBase::mChangedPropsSet, NcpBase::mDisableStreamWrite, NcpBase::mEncoder, NcpBase::mUpdateChangedPropsTask, OT_ERROR_INVALID_STATE, OT_ERROR_NO_BUFS, OT_ERROR_NONE, Tasklet::Post(), SPINEL_CMD_PROP_VALUE_IS, SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, SPINEL_PROP_STREAM_DEBUG, SPINEL_STATUS_NOMEM, SuccessOrExit, VerifyOrExit, and Encoder::WriteData().
Referenced by otNcpStreamWrite().
Log()
void Log (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aLogString)
This method send an OpenThread log message to host via SPINEL_PROP_STREAM_LOG property.
Parameters
[in] aLogLevel The log level
[in] aLogRegion The log region
[in] aLogString The log string
References ChangedPropsSet::AddLastStatus(), Encoder::BeginFrame(), NcpBase::ConvertLogLevel(), NcpBase::ConvertLogRegion(), Encoder::EndFrame(), ChangedPropsSet::IsPropertyFiltered(), NcpBase::IsResponseQueueEmpty(), NcpBase::mChangedPropsSet, NcpBase::mDisableStreamWrite, NcpBase::mEncoder, NcpBase::mLogTimestampBase, NcpBase::mUpdateChangedPropsTask, OT_ERROR_INVALID_STATE, OT_ERROR_NO_BUFS, OT_ERROR_NONE, otPlatAlarmMilliGetNow(), Tasklet::Post(), SPINEL_CMD_PROP_VALUE_IS, SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, SPINEL_PROP_STREAM_LOG, SPINEL_STATUS_NOMEM, SuccessOrExit, VerifyOrExit, Encoder::WriteUint64(), Encoder::WriteUint8(), Encoder::WriteUintPacked(), and Encoder::WriteUtf8().
Referenced by otPlatLog().
IncrementFrameErrorCounter()
void IncrementFrameErrorCounter (void)
This method is called by the framer whenever a framing error is detected.
References NcpBase::mFramingErrorCounter.
HandleReceive()
void HandleReceive (const uint8_t * aBuf, uint16_t aBufLength)
Called by the subclass to indicate when a frame has been received.
References ExitNow, NcpBase::HandleCommand(), IgnoreError(), Decoder::Init(), NcpBase::IsResponseQueueEmpty(), NcpBase::mDecoder, NcpBase::mDisableStreamWrite, NcpBase::mHostPowerState, NcpBase::mHostPowerStateInProgress, NcpBase::mNextExpectedTid, NcpBase::mRxSpinelFrameCounter, NcpBase::mRxSpinelOutOfOrderTidCounter, OT_ERROR_NONE, NcpBase::PrepareLastStatusResponse(), Decoder::ReadUint8(), NcpBase::SendQueuedResponses(), SPINEL_GET_NEXT_TID, SPINEL_HEADER_FLAG, SPINEL_HEADER_GET_IID, SPINEL_HEADER_GET_TID, SPINEL_HOST_POWER_STATE_ONLINE, SPINEL_STATUS_INVALID_INTERFACE, SuccessOrExit, NcpBase::ThreadErrorToSpinelStatus(), VerifyOrExit, and NcpBase::WriteLastStatusFrame().
ShouldWakeHost()
bool ShouldWakeHost (void)
Called by the subclass to learn when the host wake operation must be issued.
References NcpBase::mHostPowerState, NcpBase::mHostPowerStateInProgress, and SPINEL_HOST_POWER_STATE_ONLINE.
ShouldDeferHostSend()
bool ShouldDeferHostSend (void)
Called by the subclass to learn when the transfer to the host should be deferred.
References NcpBase::mHostPowerState, NcpBase::mHostPowerStateInProgress, and SPINEL_HOST_POWER_STATE_DEEP_SLEEP.
GetLastOutboundFrameTag()
Spinel::Buffer::FrameTag GetLastOutboundFrameTag (void) protected
References Buffer::InFrameGetLastTag(), and NcpBase::mTxFrameBuffer.
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), and NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE().
HandleCommand()
otError HandleCommand (uint8_t aHeader) protected
References NcpBase::CommandHandler_NOOP(), NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::CommandHandler_RESET(), NcpBase::mDecoder, OT_ERROR_NONE, OT_ERROR_NOT_IMPLEMENTED, NcpBase::PrepareLastStatusResponse(), Decoder::ReadUintPacked(), SPINEL_CMD_NET_CLEAR, SPINEL_CMD_NET_RECALL, SPINEL_CMD_NET_SAVE, SPINEL_CMD_NOOP, SPINEL_CMD_PEEK, SPINEL_CMD_POKE, SPINEL_CMD_PROP_VALUE_GET, SPINEL_CMD_PROP_VALUE_INSERT, SPINEL_CMD_PROP_VALUE_REMOVE, SPINEL_CMD_PROP_VALUE_SET, SPINEL_CMD_RESET, SPINEL_CMD_VENDOR__BEGIN, SPINEL_CMD_VENDOR__END, SPINEL_STATUS_INVALID_COMMAND, and SuccessOrExit.
Referenced by NcpBase::HandleReceive().
FindPropertyHandler()
NcpBase::PropertyHandler FindPropertyHandler (const HandlerEntry * aHandlerEntries, size_t aSize, spinel_prop_key_t aKey) static protected
References NcpBase::HandlerEntry::mHandler, NcpBase::HandlerEntry::mKey, and OT_ASSERT.
Referenced by NcpBase::FindGetPropertyHandler(), NcpBase::FindInsertPropertyHandler(), NcpBase::FindRemovePropertyHandler(), and NcpBase::FindSetPropertyHandler().
FindGetPropertyHandler()
NcpBase::PropertyHandler FindGetPropertyHandler (spinel_prop_key_t aKey) static protected
References NcpBase::FindPropertyHandler(), OT_ARRAY_LENGTH, OT_NCP_GET_HANDLER_ENTRY, SPINEL_PROP_CAPS, SPINEL_PROP_CHANNEL_MANAGER_AUTO_SELECT_ENABLED, SPINEL_PROP_CHANNEL_MANAGER_AUTO_SELECT_INTERVAL, SPINEL_PROP_CHANNEL_MANAGER_CHANNEL_SELECT, SPINEL_PROP_CHANNEL_MANAGER_DELAY, SPINEL_PROP_CHANNEL_MANAGER_FAVORED_CHANNELS, SPINEL_PROP_CHANNEL_MANAGER_NEW_CHANNEL, SPINEL_PROP_CHANNEL_MANAGER_SUPPORTED_CHANNELS, SPINEL_PROP_CHANNEL_MONITOR_CHANNEL_OCCUPANCY, SPINEL_PROP_CHANNEL_MONITOR_RSSI_THRESHOLD, SPINEL_PROP_CHANNEL_MONITOR_SAMPLE_COUNT, SPINEL_PROP_CHANNEL_MONITOR_SAMPLE_INTERVAL, SPINEL_PROP_CHANNEL_MONITOR_SAMPLE_WINDOW, SPINEL_PROP_CHILD_SUPERVISION_CHECK_TIMEOUT, SPINEL_PROP_CHILD_SUPERVISION_INTERVAL, SPINEL_PROP_CNTR_ALL_IP_COUNTERS, SPINEL_PROP_CNTR_ALL_MAC_COUNTERS, SPINEL_PROP_CNTR_IP_RX_FAILURE, SPINEL_PROP_CNTR_IP_RX_SUCCESS, SPINEL_PROP_CNTR_IP_TX_FAILURE, SPINEL_PROP_CNTR_IP_TX_SUCCESS, SPINEL_PROP_CNTR_MAC_RETRY_HISTOGRAM, SPINEL_PROP_CNTR_MLE_COUNTERS, SPINEL_PROP_CNTR_RX_ERR_BAD_FCS, SPINEL_PROP_CNTR_RX_ERR_EMPTY, SPINEL_PROP_CNTR_RX_ERR_NVLD_SADDR, SPINEL_PROP_CNTR_RX_ERR_OTHER, SPINEL_PROP_CNTR_RX_ERR_SECURITY, SPINEL_PROP_CNTR_RX_ERR_UKWN_NBR, SPINEL_PROP_CNTR_RX_IP_DROPPED, SPINEL_PROP_CNTR_RX_IP_INSEC_TOTAL, SPINEL_PROP_CNTR_RX_IP_SEC_TOTAL, SPINEL_PROP_CNTR_RX_PKT_BEACON, SPINEL_PROP_CNTR_RX_PKT_BEACON_REQ, SPINEL_PROP_CNTR_RX_PKT_BROADCAST, SPINEL_PROP_CNTR_RX_PKT_DATA, SPINEL_PROP_CNTR_RX_PKT_DATA_POLL, SPINEL_PROP_CNTR_RX_PKT_DUP, SPINEL_PROP_CNTR_RX_PKT_FILT_DA, SPINEL_PROP_CNTR_RX_PKT_FILT_WL, SPINEL_PROP_CNTR_RX_PKT_OTHER, SPINEL_PROP_CNTR_RX_PKT_TOTAL, SPINEL_PROP_CNTR_RX_PKT_UNICAST, SPINEL_PROP_CNTR_RX_SPINEL_ERR, SPINEL_PROP_CNTR_RX_SPINEL_TOTAL, SPINEL_PROP_CNTR_TX_ERR_ABORT, SPINEL_PROP_CNTR_TX_ERR_CCA, SPINEL_PROP_CNTR_TX_IP_DROPPED, SPINEL_PROP_CNTR_TX_IP_INSEC_TOTAL, SPINEL_PROP_CNTR_TX_IP_SEC_TOTAL, SPINEL_PROP_CNTR_TX_PKT_ACK_REQ, SPINEL_PROP_CNTR_TX_PKT_ACKED, SPINEL_PROP_CNTR_TX_PKT_BEACON, SPINEL_PROP_CNTR_TX_PKT_BEACON_REQ, SPINEL_PROP_CNTR_TX_PKT_BROADCAST, SPINEL_PROP_CNTR_TX_PKT_DATA, SPINEL_PROP_CNTR_TX_PKT_DATA_POLL, SPINEL_PROP_CNTR_TX_PKT_NO_ACK_REQ, SPINEL_PROP_CNTR_TX_PKT_OTHER, SPINEL_PROP_CNTR_TX_PKT_RETRY, SPINEL_PROP_CNTR_TX_PKT_TOTAL, SPINEL_PROP_CNTR_TX_PKT_UNICAST, SPINEL_PROP_CNTR_TX_SPINEL_TOTAL, SPINEL_PROP_DEBUG_LOG_TIMESTAMP_BASE, SPINEL_PROP_DEBUG_NCP_LOG_LEVEL, SPINEL_PROP_DEBUG_TEST_ASSERT, SPINEL_PROP_DEBUG_TEST_WATCHDOG, SPINEL_PROP_DEBUG_TREL_TEST_MODE_ENABLE, SPINEL_PROP_HOST_POWER_STATE, SPINEL_PROP_HWADDR, SPINEL_PROP_INTERFACE_COUNT, SPINEL_PROP_INTERFACE_TYPE, SPINEL_PROP_IPV6_ADDRESS_TABLE, SPINEL_PROP_IPV6_ICMP_PING_OFFLOAD, SPINEL_PROP_IPV6_ICMP_PING_OFFLOAD_MODE, SPINEL_PROP_IPV6_LL_ADDR, SPINEL_PROP_IPV6_ML_ADDR, SPINEL_PROP_IPV6_ML_PREFIX, SPINEL_PROP_IPV6_MULTICAST_ADDRESS_TABLE, SPINEL_PROP_IPV6_ROUTE_TABLE, SPINEL_PROP_JAM_DETECT_BUSY, SPINEL_PROP_JAM_DETECT_ENABLE, SPINEL_PROP_JAM_DETECT_HISTORY_BITMAP, SPINEL_PROP_JAM_DETECT_RSSI_THRESHOLD, SPINEL_PROP_JAM_DETECT_WINDOW, SPINEL_PROP_JAM_DETECTED, SPINEL_PROP_LAST_STATUS, SPINEL_PROP_LOCK, SPINEL_PROP_MAC_15_4_LADDR, SPINEL_PROP_MAC_15_4_PANID, SPINEL_PROP_MAC_15_4_SADDR, SPINEL_PROP_MAC_ALLOWLIST, SPINEL_PROP_MAC_ALLOWLIST_ENABLED, SPINEL_PROP_MAC_CCA_FAILURE_RATE, SPINEL_PROP_MAC_DATA_POLL_PERIOD, SPINEL_PROP_MAC_DENYLIST, SPINEL_PROP_MAC_DENYLIST_ENABLED, SPINEL_PROP_MAC_EXTENDED_ADDR, SPINEL_PROP_MAC_FIXED_RSS, SPINEL_PROP_MAC_MAX_RETRY_NUMBER_DIRECT, SPINEL_PROP_MAC_MAX_RETRY_NUMBER_INDIRECT, SPINEL_PROP_MAC_PROMISCUOUS_MODE, SPINEL_PROP_MAC_RAW_STREAM_ENABLED, SPINEL_PROP_MAC_SCAN_MASK, SPINEL_PROP_MAC_SCAN_PERIOD, SPINEL_PROP_MAC_SCAN_STATE, SPINEL_PROP_MAC_SRC_MATCH_ENABLED, SPINEL_PROP_MCU_POWER_STATE, SPINEL_PROP_MESHCOP_COMMISSIONER_JOINERS, SPINEL_PROP_MESHCOP_COMMISSIONER_PROVISIONING_URL, SPINEL_PROP_MESHCOP_COMMISSIONER_SESSION_ID, SPINEL_PROP_MESHCOP_COMMISSIONER_STATE, SPINEL_PROP_MESHCOP_JOINER_DISCERNER, SPINEL_PROP_MESHCOP_JOINER_STATE, SPINEL_PROP_MSG_BUFFER_COUNTERS, SPINEL_PROP_NCP_VERSION, SPINEL_PROP_NEIGHBOR_TABLE_MULTI_RADIO_INFO, SPINEL_PROP_NEST_LEGACY_LAST_NODE_JOINED, SPINEL_PROP_NEST_LEGACY_ULA_PREFIX, SPINEL_PROP_NET_IF_UP, SPINEL_PROP_NET_KEY_SEQUENCE_COUNTER, SPINEL_PROP_NET_KEY_SWITCH_GUARDTIME, SPINEL_PROP_NET_NETWORK_KEY, SPINEL_PROP_NET_NETWORK_NAME, SPINEL_PROP_NET_PARTITION_ID, SPINEL_PROP_NET_PSKC, SPINEL_PROP_NET_REQUIRE_JOIN_EXISTING, SPINEL_PROP_NET_ROLE, SPINEL_PROP_NET_SAVED, SPINEL_PROP_NET_STACK_UP, SPINEL_PROP_NET_XPANID, SPINEL_PROP_PHY_CCA_THRESHOLD, SPINEL_PROP_PHY_CHAN, SPINEL_PROP_PHY_CHAN_PREFERRED, SPINEL_PROP_PHY_CHAN_SUPPORTED, SPINEL_PROP_PHY_ENABLED, SPINEL_PROP_PHY_FEM_LNA_GAIN, SPINEL_PROP_PHY_FREQ, SPINEL_PROP_PHY_PCAP_ENABLED, SPINEL_PROP_PHY_REGION_CODE, SPINEL_PROP_PHY_RSSI, SPINEL_PROP_PHY_RX_SENSITIVITY, SPINEL_PROP_PHY_TX_POWER, SPINEL_PROP_POWER_STATE, SPINEL_PROP_PROTOCOL_VERSION, SPINEL_PROP_RADIO_CAPS, SPINEL_PROP_RADIO_COEX_ENABLE, SPINEL_PROP_RADIO_COEX_METRICS, SPINEL_PROP_RCP_API_VERSION, SPINEL_PROP_RCP_CSL_ACCURACY, SPINEL_PROP_RCP_CSL_UNCERTAINTY, SPINEL_PROP_RCP_TIMESTAMP, SPINEL_PROP_RCP_VERSION, SPINEL_PROP_SERVER_ALLOW_LOCAL_DATA_CHANGE, SPINEL_PROP_SERVER_LEADER_SERVICES, SPINEL_PROP_SERVER_SERVICES, SPINEL_PROP_SLAAC_ENABLED, SPINEL_PROP_SRP_CLIENT_HOST_ADDRESSES, SPINEL_PROP_SRP_CLIENT_HOST_INFO, SPINEL_PROP_SRP_CLIENT_HOST_NAME, SPINEL_PROP_SRP_CLIENT_KEY_LEASE_INTERVAL, SPINEL_PROP_SRP_CLIENT_LEASE_INTERVAL, SPINEL_PROP_SRP_CLIENT_SERVICE_KEY_ENABLED, SPINEL_PROP_SRP_CLIENT_SERVICES, SPINEL_PROP_SUPPORTED_RADIO_LINKS, SPINEL_PROP_THREAD_ACTIVE_DATASET, SPINEL_PROP_THREAD_ADDRESS_CACHE_TABLE, SPINEL_PROP_THREAD_ALLOW_LOCAL_NET_DATA_CHANGE, SPINEL_PROP_THREAD_ASSISTING_PORTS, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_CONFIG, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_REGISTRATION_JITTER, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_STATE, SPINEL_PROP_THREAD_BACKBONE_ROUTER_PRIMARY, SPINEL_PROP_THREAD_CHILD_COUNT_MAX, SPINEL_PROP_THREAD_CHILD_TABLE, SPINEL_PROP_THREAD_CHILD_TABLE_ADDRESSES, SPINEL_PROP_THREAD_CHILD_TIMEOUT, SPINEL_PROP_THREAD_COMMISSIONER_ENABLED, SPINEL_PROP_THREAD_CONTEXT_REUSE_DELAY, SPINEL_PROP_THREAD_CSL_CHANNEL, SPINEL_PROP_THREAD_CSL_PERIOD, SPINEL_PROP_THREAD_CSL_TIMEOUT, SPINEL_PROP_THREAD_DISCOVERY_SCAN_ENABLE_FILTERING, SPINEL_PROP_THREAD_DISCOVERY_SCAN_JOINER_FLAG, SPINEL_PROP_THREAD_DISCOVERY_SCAN_PANID, SPINEL_PROP_THREAD_DOMAIN_NAME, SPINEL_PROP_THREAD_DUA_ID, SPINEL_PROP_THREAD_LEADER_ADDR, SPINEL_PROP_THREAD_LEADER_NETWORK_DATA, SPINEL_PROP_THREAD_LEADER_RID, SPINEL_PROP_THREAD_LEADER_WEIGHT, SPINEL_PROP_THREAD_LOCAL_LEADER_WEIGHT, SPINEL_PROP_THREAD_MODE, SPINEL_PROP_THREAD_NEIGHBOR_TABLE, SPINEL_PROP_THREAD_NEIGHBOR_TABLE_ERROR_RATES, SPINEL_PROP_THREAD_NETWORK_DATA, SPINEL_PROP_THREAD_NETWORK_DATA_VERSION, SPINEL_PROP_THREAD_NETWORK_ID_TIMEOUT, SPINEL_PROP_THREAD_NETWORK_TIME, SPINEL_PROP_THREAD_NEW_DATASET, SPINEL_PROP_THREAD_OFF_MESH_ROUTES, SPINEL_PROP_THREAD_ON_MESH_NETS, SPINEL_PROP_THREAD_PARENT, SPINEL_PROP_THREAD_PENDING_DATASET, SPINEL_PROP_THREAD_PREFERRED_ROUTER_ID, SPINEL_PROP_THREAD_RLOC16, SPINEL_PROP_THREAD_RLOC16_DEBUG_PASSTHRU, SPINEL_PROP_THREAD_ROUTER_DOWNGRADE_THRESHOLD, SPINEL_PROP_THREAD_ROUTER_ROLE_ENABLED, SPINEL_PROP_THREAD_ROUTER_SELECTION_JITTER, SPINEL_PROP_THREAD_ROUTER_TABLE, SPINEL_PROP_THREAD_ROUTER_UPGRADE_THRESHOLD, SPINEL_PROP_THREAD_STABLE_LEADER_NETWORK_DATA, SPINEL_PROP_THREAD_STABLE_NETWORK_DATA, SPINEL_PROP_THREAD_STABLE_NETWORK_DATA_VERSION, SPINEL_PROP_THREAD_STEERING_DATA, SPINEL_PROP_TIME_SYNC_PERIOD, SPINEL_PROP_TIME_SYNC_XTAL_THRESHOLD, SPINEL_PROP_UNSOL_UPDATE_FILTER, SPINEL_PROP_UNSOL_UPDATE_LIST, and SPINEL_PROP_VENDOR_ID.
Referenced by NcpBase::WritePropertyValueIsFrame().
FindSetPropertyHandler()
NcpBase::PropertyHandler FindSetPropertyHandler (spinel_prop_key_t aKey) static protected
References NcpBase::FindPropertyHandler(), OT_ARRAY_LENGTH, OT_NCP_SET_HANDLER_ENTRY, SPINEL_PROP_CHANNEL_MANAGER_AUTO_SELECT_ENABLED, SPINEL_PROP_CHANNEL_MANAGER_AUTO_SELECT_INTERVAL, SPINEL_PROP_CHANNEL_MANAGER_CHANNEL_SELECT, SPINEL_PROP_CHANNEL_MANAGER_DELAY, SPINEL_PROP_CHANNEL_MANAGER_FAVORED_CHANNELS, SPINEL_PROP_CHANNEL_MANAGER_NEW_CHANNEL, SPINEL_PROP_CHANNEL_MANAGER_SUPPORTED_CHANNELS, SPINEL_PROP_CHILD_SUPERVISION_CHECK_TIMEOUT, SPINEL_PROP_CHILD_SUPERVISION_INTERVAL, SPINEL_PROP_CNTR_ALL_IP_COUNTERS, SPINEL_PROP_CNTR_ALL_MAC_COUNTERS, SPINEL_PROP_CNTR_MAC_RETRY_HISTOGRAM, SPINEL_PROP_CNTR_MLE_COUNTERS, SPINEL_PROP_CNTR_RESET, SPINEL_PROP_DEBUG_LOG_TIMESTAMP_BASE, SPINEL_PROP_DEBUG_NCP_LOG_LEVEL, SPINEL_PROP_DEBUG_TREL_TEST_MODE_ENABLE, SPINEL_PROP_IPV6_ICMP_PING_OFFLOAD, SPINEL_PROP_IPV6_ICMP_PING_OFFLOAD_MODE, SPINEL_PROP_IPV6_ML_PREFIX, SPINEL_PROP_JAM_DETECT_BUSY, SPINEL_PROP_JAM_DETECT_ENABLE, SPINEL_PROP_JAM_DETECT_RSSI_THRESHOLD, SPINEL_PROP_JAM_DETECT_WINDOW, SPINEL_PROP_MAC_15_4_LADDR, SPINEL_PROP_MAC_15_4_PANID, SPINEL_PROP_MAC_15_4_SADDR, SPINEL_PROP_MAC_ALLOWLIST, SPINEL_PROP_MAC_ALLOWLIST_ENABLED, SPINEL_PROP_MAC_DATA_POLL_PERIOD, SPINEL_PROP_MAC_DENYLIST, SPINEL_PROP_MAC_DENYLIST_ENABLED, SPINEL_PROP_MAC_FIXED_RSS, SPINEL_PROP_MAC_MAX_RETRY_NUMBER_DIRECT, SPINEL_PROP_MAC_MAX_RETRY_NUMBER_INDIRECT, SPINEL_PROP_MAC_PROMISCUOUS_MODE, SPINEL_PROP_MAC_RAW_STREAM_ENABLED, SPINEL_PROP_MAC_SCAN_MASK, SPINEL_PROP_MAC_SCAN_PERIOD, SPINEL_PROP_MAC_SCAN_STATE, SPINEL_PROP_MAC_SRC_MATCH_ENABLED, SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, SPINEL_PROP_MCU_POWER_STATE, SPINEL_PROP_MESHCOP_COMMISSIONER_ANNOUNCE_BEGIN, SPINEL_PROP_MESHCOP_COMMISSIONER_ENERGY_SCAN, SPINEL_PROP_MESHCOP_COMMISSIONER_MGMT_GET, SPINEL_PROP_MESHCOP_COMMISSIONER_MGMT_SET, SPINEL_PROP_MESHCOP_COMMISSIONER_PAN_ID_QUERY, SPINEL_PROP_MESHCOP_COMMISSIONER_PROVISIONING_URL, SPINEL_PROP_MESHCOP_COMMISSIONER_STATE, SPINEL_PROP_MESHCOP_JOINER_COMMISSIONING, SPINEL_PROP_MESHCOP_JOINER_DISCERNER, SPINEL_PROP_NEST_LEGACY_ULA_PREFIX, SPINEL_PROP_NET_IF_UP, SPINEL_PROP_NET_KEY_SEQUENCE_COUNTER, SPINEL_PROP_NET_KEY_SWITCH_GUARDTIME, SPINEL_PROP_NET_NETWORK_KEY, SPINEL_PROP_NET_NETWORK_NAME, SPINEL_PROP_NET_PARTITION_ID, SPINEL_PROP_NET_PSKC, SPINEL_PROP_NET_REQUIRE_JOIN_EXISTING, SPINEL_PROP_NET_ROLE, SPINEL_PROP_NET_STACK_UP, SPINEL_PROP_NET_XPANID, SPINEL_PROP_PHY_CCA_THRESHOLD, SPINEL_PROP_PHY_CHAN, SPINEL_PROP_PHY_CHAN_MAX_POWER, SPINEL_PROP_PHY_CHAN_SUPPORTED, SPINEL_PROP_PHY_ENABLED, SPINEL_PROP_PHY_FEM_LNA_GAIN, SPINEL_PROP_PHY_PCAP_ENABLED, SPINEL_PROP_PHY_REGION_CODE, SPINEL_PROP_PHY_TX_POWER, SPINEL_PROP_POWER_STATE, SPINEL_PROP_RADIO_COEX_ENABLE, SPINEL_PROP_RCP_ENH_ACK_PROBING, SPINEL_PROP_RCP_MAC_FRAME_COUNTER, SPINEL_PROP_RCP_MAC_KEY, SPINEL_PROP_SERVER_ALLOW_LOCAL_DATA_CHANGE, SPINEL_PROP_SLAAC_ENABLED, SPINEL_PROP_SRP_CLIENT_HOST_ADDRESSES, SPINEL_PROP_SRP_CLIENT_HOST_NAME, SPINEL_PROP_SRP_CLIENT_HOST_SERVICES_CLEAR, SPINEL_PROP_SRP_CLIENT_HOST_SERVICES_REMOVE, SPINEL_PROP_SRP_CLIENT_KEY_LEASE_INTERVAL, SPINEL_PROP_SRP_CLIENT_LEASE_INTERVAL, SPINEL_PROP_SRP_CLIENT_SERVICE_KEY_ENABLED, SPINEL_PROP_SRP_CLIENT_START, SPINEL_PROP_STREAM_NET, SPINEL_PROP_STREAM_NET_INSECURE, SPINEL_PROP_THREAD_ACTIVE_DATASET, SPINEL_PROP_THREAD_ALLOW_LOCAL_NET_DATA_CHANGE, SPINEL_PROP_THREAD_ASSISTING_PORTS, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_CONFIG, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_REGISTER, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_REGISTRATION_JITTER, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_STATE, SPINEL_PROP_THREAD_CHILD_COUNT_MAX, SPINEL_PROP_THREAD_CHILD_TIMEOUT, SPINEL_PROP_THREAD_CONTEXT_REUSE_DELAY, SPINEL_PROP_THREAD_CSL_CHANNEL, SPINEL_PROP_THREAD_CSL_PERIOD, SPINEL_PROP_THREAD_CSL_TIMEOUT, SPINEL_PROP_THREAD_DISCOVERY_SCAN_ENABLE_FILTERING, SPINEL_PROP_THREAD_DISCOVERY_SCAN_JOINER_FLAG, SPINEL_PROP_THREAD_DISCOVERY_SCAN_PANID, SPINEL_PROP_THREAD_DOMAIN_NAME, SPINEL_PROP_THREAD_DUA_ID, SPINEL_PROP_THREAD_LINK_METRICS_MGMT_ENH_ACK, SPINEL_PROP_THREAD_LINK_METRICS_MGMT_FORWARD, SPINEL_PROP_THREAD_LINK_METRICS_PROBE, SPINEL_PROP_THREAD_LINK_METRICS_QUERY, SPINEL_PROP_THREAD_LOCAL_LEADER_WEIGHT, SPINEL_PROP_THREAD_MGMT_GET_ACTIVE_DATASET, SPINEL_PROP_THREAD_MGMT_GET_PENDING_DATASET, SPINEL_PROP_THREAD_MGMT_SET_ACTIVE_DATASET, SPINEL_PROP_THREAD_MGMT_SET_PENDING_DATASET, SPINEL_PROP_THREAD_MLR_REQUEST, SPINEL_PROP_THREAD_MODE, SPINEL_PROP_THREAD_NETWORK_ID_TIMEOUT, SPINEL_PROP_THREAD_PENDING_DATASET, SPINEL_PROP_THREAD_PREFERRED_ROUTER_ID, SPINEL_PROP_THREAD_RLOC16_DEBUG_PASSTHRU, SPINEL_PROP_THREAD_ROUTER_DOWNGRADE_THRESHOLD, SPINEL_PROP_THREAD_ROUTER_ROLE_ENABLED, SPINEL_PROP_THREAD_ROUTER_SELECTION_JITTER, SPINEL_PROP_THREAD_ROUTER_UPGRADE_THRESHOLD, SPINEL_PROP_THREAD_STEERING_DATA, SPINEL_PROP_THREAD_UDP_FORWARD_STREAM, SPINEL_PROP_TIME_SYNC_PERIOD, SPINEL_PROP_TIME_SYNC_XTAL_THRESHOLD, and SPINEL_PROP_UNSOL_UPDATE_FILTER.
Referenced by NcpBase::HandleCommandPropertySet().
FindInsertPropertyHandler()
NcpBase::PropertyHandler FindInsertPropertyHandler (spinel_prop_key_t aKey) static protected
References NcpBase::FindPropertyHandler(), OT_ARRAY_LENGTH, OT_NCP_INSERT_HANDLER_ENTRY, SPINEL_PROP_IPV6_ADDRESS_TABLE, SPINEL_PROP_IPV6_MULTICAST_ADDRESS_TABLE, SPINEL_PROP_MAC_ALLOWLIST, SPINEL_PROP_MAC_DENYLIST, SPINEL_PROP_MAC_FIXED_RSS, SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, SPINEL_PROP_MESHCOP_COMMISSIONER_JOINERS, SPINEL_PROP_SERVER_SERVICES, SPINEL_PROP_SRP_CLIENT_SERVICES, SPINEL_PROP_THREAD_ASSISTING_PORTS, SPINEL_PROP_THREAD_JOINERS, SPINEL_PROP_THREAD_OFF_MESH_ROUTES, SPINEL_PROP_THREAD_ON_MESH_NETS, and SPINEL_PROP_UNSOL_UPDATE_FILTER.
Referenced by NcpBase::HandleCommandPropertyInsertRemove().
FindRemovePropertyHandler()
NcpBase::PropertyHandler FindRemovePropertyHandler (spinel_prop_key_t aKey) static protected
References NcpBase::FindPropertyHandler(), OT_ARRAY_LENGTH, OT_NCP_REMOVE_HANDLER_ENTRY, SPINEL_PROP_IPV6_ADDRESS_TABLE, SPINEL_PROP_IPV6_MULTICAST_ADDRESS_TABLE, SPINEL_PROP_MAC_ALLOWLIST, SPINEL_PROP_MAC_DENYLIST, SPINEL_PROP_MAC_FIXED_RSS, SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, SPINEL_PROP_MESHCOP_COMMISSIONER_JOINERS, SPINEL_PROP_SERVER_SERVICES, SPINEL_PROP_SRP_CLIENT_SERVICES, SPINEL_PROP_THREAD_ACTIVE_ROUTER_IDS, SPINEL_PROP_THREAD_ASSISTING_PORTS, SPINEL_PROP_THREAD_OFF_MESH_ROUTES, SPINEL_PROP_THREAD_ON_MESH_NETS, and SPINEL_PROP_UNSOL_UPDATE_FILTER.
Referenced by NcpBase::HandleCommandPropertyInsertRemove().
HandlePropertySetForSpecialProperties()
bool HandlePropertySetForSpecialProperties (uint8_t aHeader, spinel_prop_key_t aKey, otError & aError) protected
References ExitNow, NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), SPINEL_PROP_HOST_POWER_STATE, SPINEL_PROP_MESHCOP_COMMISSIONER_GENERATE_PSKC, SPINEL_PROP_NEST_STREAM_MFG, SPINEL_PROP_STREAM_RAW, and SPINEL_PROP_THREAD_COMMISSIONER_ENABLED.
Referenced by NcpBase::HandleCommandPropertySet().
HandleCommandPropertySet()
otError HandleCommandPropertySet (uint8_t aHeader, spinel_prop_key_t aKey) protected
References NcpBase::FindSetPropertyHandler(), NcpBase::HandlePropertySetForSpecialProperties(), NcpBase::mDisableStreamWrite, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, NcpBase::PrepareLastStatusResponse(), NcpBase::PrepareSetResponse(), SPINEL_PROP_VENDOR__BEGIN, SPINEL_PROP_VENDOR__END, SPINEL_STATUS_PROP_NOT_FOUND, NcpBase::ThreadErrorToSpinelStatus(), and VerifyOrExit.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update().
HandleCommandPropertyInsertRemove()
otError HandleCommandPropertyInsertRemove (uint8_t aHeader, spinel_prop_key_t aKey, unsigned int aCommand) protected
References NcpBase::FindInsertPropertyHandler(), NcpBase::FindRemovePropertyHandler(), IgnoreError(), NcpBase::mDecoder, NcpBase::mDisableStreamWrite, OT_ASSERT, OT_ERROR_NONE, OT_UNREACHABLE_CODE, NcpBase::PrepareLastStatusResponse(), Decoder::ReadData(), Decoder::ResetToSaved(), Decoder::SavePosition(), SPINEL_CMD_PROP_VALUE_INSERT, SPINEL_CMD_PROP_VALUE_INSERTED, SPINEL_CMD_PROP_VALUE_REMOVE, SPINEL_CMD_PROP_VALUE_REMOVED, SPINEL_STATUS_OK, SPINEL_STATUS_PROP_NOT_FOUND, NcpBase::ThreadErrorToSpinelStatus(), VerifyOrExit, and NcpBase::WritePropertyValueInsertedRemovedFrame().
Referenced by NcpBase::CommandHandler_PROP_VALUE_update().
WriteLastStatusFrame()
otError WriteLastStatusFrame (uint8_t aHeader, spinel_status_t aLastStatus) protected
References Encoder::BeginFrame(), Encoder::EndFrame(), NcpBase::mEncoder, NcpBase::mLastStatus, OT_ERROR_NONE, SPINEL_CMD_PROP_VALUE_IS, SPINEL_HEADER_GET_IID, SPINEL_PROP_LAST_STATUS, SuccessOrExit, and Encoder::WriteUintPacked().
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::CommandHandler_RESET(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), NcpBase::HandleReceive(), NcpBase::SendQueuedResponses(), NcpBase::UpdateChangedProps(), and NcpBase::WritePropertyValueIsFrame().
WritePropertyValueIsFrame()
otError WritePropertyValueIsFrame (uint8_t aHeader, spinel_prop_key_t aPropKey, bool aIsGetResponse = true) protected
References Encoder::BeginFrame(), Encoder::EndFrame(), ExitNow, NcpBase::FindGetPropertyHandler(), NcpBase::mEncoder, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, SPINEL_CMD_PROP_VALUE_IS, SPINEL_PROP_VENDOR__BEGIN, SPINEL_PROP_VENDOR__END, SPINEL_STATUS_OK, SPINEL_STATUS_PROP_NOT_FOUND, SuccessOrExit, and NcpBase::WriteLastStatusFrame().
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), NcpBase::HandlePropertySet(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), NcpBase::SendQueuedResponses(), and NcpBase::UpdateChangedProps().
WritePropertyValueInsertedRemovedFrame()
otError WritePropertyValueInsertedRemovedFrame (uint8_t aHeader, unsigned int aResponseCommand, spinel_prop_key_t aPropKey, const uint8_t * aValuePtr, uint16_t aValueLen) protected
References Encoder::BeginFrame(), Encoder::EndFrame(), NcpBase::mEncoder, OT_ERROR_NONE, SuccessOrExit, and Encoder::WriteData().
Referenced by NcpBase::HandleCommandPropertyInsertRemove().
SendQueuedResponses()
otError SendQueuedResponses (void) protected
References NcpBase::GetWrappedResponseQueueIndex(), NcpBase::kResponseQueueSize, NcpBase::kResponseTypeGet, NcpBase::kResponseTypeLastStatus, NcpBase::ResponseEntry::mIsInUse, NcpBase::ResponseEntry::mPropKeyOrStatus, NcpBase::mResponseQueue, NcpBase::mResponseQueueHead, NcpBase::mResponseQueueTail, NcpBase::ResponseEntry::mTid, NcpBase::ResponseEntry::mType, OT_ERROR_NONE, SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, SPINEL_HEADER_TID_SHIFT, SuccessOrExit, NcpBase::WriteLastStatusFrame(), and NcpBase::WritePropertyValueIsFrame().
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), and NcpBase::HandleReceive().
IsResponseQueueEmpty()
bool IsResponseQueueEmpty (void) const inline protected
References NcpBase::EnqueueResponse(), NcpBase::mResponseQueueHead, and NcpBase::mResponseQueueTail.
Referenced by NcpBase::HandleReceive(), NcpBase::Log(), and NcpBase::StreamWrite().
EnqueueResponse()
otError EnqueueResponse (uint8_t aHeader, ResponseType aType, unsigned int aPropKeyOrStatus) protected
References ChangedPropsSet::AddLastStatus(), ExitNow, NcpBase::GetWrappedResponseQueueIndex(), NcpBase::kResponseQueueSize, NcpBase::kResponseTypeLastStatus, NcpBase::mChangedPropsSet, NcpBase::ResponseEntry::mIsInUse, NcpBase::mNextExpectedTid, NcpBase::ResponseEntry::mPropKeyOrStatus, NcpBase::mResponseQueue, NcpBase::mResponseQueueHead, NcpBase::mResponseQueueTail, NcpBase::ResponseEntry::mTid, NcpBase::ResponseEntry::mType, OT_ERROR_NO_BUFS, OT_ERROR_NONE, SPINEL_HEADER_GET_TID, and SPINEL_STATUS_DROPPED.
Referenced by NcpBase::IsResponseQueueEmpty(), NcpBase::PrepareGetResponse(), NcpBase::PrepareLastStatusResponse(), and NcpBase::PrepareSetResponse().
PrepareGetResponse()
otError PrepareGetResponse (uint8_t aHeader, spinel_prop_key_t aPropKey) inline protected
References NcpBase::EnqueueResponse(), and NcpBase::kResponseTypeGet.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update().
PrepareSetResponse()
otError PrepareSetResponse (uint8_t aHeader, spinel_prop_key_t aPropKey) inline protected
References NcpBase::EnqueueResponse(), and NcpBase::kResponseTypeSet.
Referenced by NcpBase::HandleCommandPropertySet().
PrepareLastStatusResponse()
otError PrepareLastStatusResponse (uint8_t aHeader, spinel_status_t aStatus) inline protected
References NcpBase::CommandHandler_NOOP(), NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::CommandHandler_RESET(), NcpBase::DecodeChannelMask(), NcpBase::EncodeChannelMask(), NcpBase::EnqueueResponse(), NcpBase::GetWrappedResponseQueueIndex(), NcpBase::HandleFrameRemovedFromNcpBuffer(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertyInsert(), NcpBase::HandlePropertyRemove(), NcpBase::HandlePropertySet(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), NcpBase::kResponseTypeLastStatus, NcpBase::kSpinelCmdHeaderSize, NcpBase::kSpinelPropIdSize, OPENTHREAD_CONFIG_DIAG_OUTPUT_BUFFER_SIZE, OPENTHREAD_CONFIG_NCP_TX_BUFFER_SIZE, NcpBase::ResetCounters(), NcpBase::StartLegacy(), NcpBase::StopLegacy(), and NcpBase::UpdateChangedProps().
Referenced by NcpBase::CommandHandler_NOOP(), NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandleCommand(), NcpBase::HandleCommandPropertyInsertRemove(), NcpBase::HandleCommandPropertySet(), and NcpBase::HandleReceive().
GetWrappedResponseQueueIndex()
uint8_t GetWrappedResponseQueueIndex (uint8_t aPosition) static protected
References NcpBase::kResponseQueueSize.
Referenced by NcpBase::EnqueueResponse(), NcpBase::PrepareLastStatusResponse(), and NcpBase::SendQueuedResponses().
UpdateChangedProps() [1/2]
void UpdateChangedProps (Tasklet & aTasklet) static protected
References NcpBase::GetNcpInstance(), OT_UNUSED_VARIABLE, and NcpBase::UpdateChangedProps().
Referenced by NcpBase::UpdateChangedProps().
UpdateChangedProps() [2/2]
void UpdateChangedProps (void) protected
References ChangedPropsSet::GetSupportedEntries(), ChangedPropsSet::IsEmpty(), ChangedPropsSet::IsEntryChanged(), NcpBase::mChangedPropsSet, NcpBase::mDidInitialUpdates, NcpBase::mInstance, ChangedPropsSet::Entry::mPropKey, otPlatGetResetReason(), ChangedPropsSet::RemoveEntry(), ot::Ncp::ResetReasonToSpinelStatus(), SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, SPINEL_PROP_LAST_STATUS, SPINEL_STATUS_RESET_UNKNOWN, SuccessOrExit, VerifyOrExit, NcpBase::WriteLastStatusFrame(), and NcpBase::WritePropertyValueIsFrame().
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), and NcpBase::PrepareLastStatusResponse().
HandleFrameRemovedFromNcpBuffer() [1/2]
void HandleFrameRemovedFromNcpBuffer (void * aContext, Spinel::Buffer::FrameTag aFrameTag, Spinel::Buffer::Priority aPriority, Spinel::Buffer * aNcpBuffer) static protected
References OT_UNUSED_VARIABLE.
Referenced by NcpBase::NcpBase(), and NcpBase::PrepareLastStatusResponse().
HandleFrameRemovedFromNcpBuffer() [2/2]
void HandleFrameRemovedFromNcpBuffer (Spinel::Buffer::FrameTag aFrameTag) protected
References NcpBase::GetLastOutboundFrameTag(), NcpBase::mHostPowerReplyFrameTag, NcpBase::mHostPowerState, NcpBase::mHostPowerStateHeader, NcpBase::mHostPowerStateInProgress, NcpBase::SendQueuedResponses(), SPINEL_HOST_POWER_STATE_ONLINE, SPINEL_PROP_HOST_POWER_STATE, SuccessOrExit, NcpBase::UpdateChangedProps(), and NcpBase::WritePropertyValueIsFrame().
EncodeChannelMask()
otError EncodeChannelMask (uint32_t aChannelMask) protected
References NcpBase::mEncoder, OT_ERROR_NONE, SuccessOrExit, and Encoder::WriteUint8().
Referenced by NcpBase::HandlePropertyGet(), and NcpBase::PrepareLastStatusResponse().
DecodeChannelMask()
otError DecodeChannelMask (uint32_t & aChannelMask) protected
References Decoder::IsAllReadInStruct(), NcpBase::mDecoder, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Decoder::ReadUint8(), SuccessOrExit, and VerifyOrExit.
Referenced by NcpBase::HandlePropertySet(), and NcpBase::PrepareLastStatusResponse().
CommandHandler_NOOP()
otError CommandHandler_NOOP (uint8_t aHeader) protected
References NcpBase::PrepareLastStatusResponse(), and SPINEL_STATUS_OK.
Referenced by NcpBase::HandleCommand(), and NcpBase::PrepareLastStatusResponse().
CommandHandler_RESET()
otError CommandHandler_RESET (uint8_t aHeader) protected
References Decoder::GetRemainingLengthInStruct(), IgnoreError(), NcpBase::kInvalidScanChannel, NcpBase::mDecoder, NcpBase::mInstance, NcpBase::mIsRawStreamEnabled, OT_ERROR_NONE, OT_UNUSED_VARIABLE, otInstanceReset(), otInstanceResetRadioStack(), otIp6SetEnabled(), otThreadSetEnabled(), Decoder::ReadUint8(), NcpBase::ResetCounters(), NcpBase::sNcpInstance, SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, SPINEL_RESET_STACK, SPINEL_STATUS_RESET_POWER_ON, SuccessOrAssert, and NcpBase::WriteLastStatusFrame().
Referenced by NcpBase::HandleCommand(), and NcpBase::PrepareLastStatusResponse().
CommandHandler_PROP_VALUE_update()
otError CommandHandler_PROP_VALUE_update (uint8_t aHeader, unsigned int aCommand) protected
References Encoder::BeginFrame(), Encoder::EndFrame(), NcpBase::HandleCommandPropertyInsertRemove(), NcpBase::HandleCommandPropertySet(), NcpBase::mDecoder, NcpBase::mEncoder, NcpBase::mInstance, OPENTHREAD_CONFIG_DIAG_OUTPUT_BUFFER_SIZE, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDiagProcessCmdLine(), NcpBase::PrepareGetResponse(), NcpBase::PrepareLastStatusResponse(), Decoder::ReadData(), Decoder::ReadUint16(), Decoder::ReadUint32(), Decoder::ReadUintPacked(), Decoder::ReadUtf8(), SPINEL_CMD_PEEK_RET, SPINEL_CMD_PROP_VALUE_GET, SPINEL_CMD_PROP_VALUE_INSERT, SPINEL_CMD_PROP_VALUE_IS, SPINEL_CMD_PROP_VALUE_REMOVE, SPINEL_CMD_PROP_VALUE_SET, SPINEL_PROP_NEST_STREAM_MFG, SuccessOrExit, NcpBase::ThreadErrorToSpinelStatus(), VerifyOrExit, Encoder::WriteData(), NcpBase::WriteLastStatusFrame(), Encoder::WriteUint16(), Encoder::WriteUint32(), and Encoder::WriteUtf8().
Referenced by NcpBase::HandleCommand(), and NcpBase::PrepareLastStatusResponse().
HandlePropertyGet() [1/38]
otError HandlePropertyGet (void) protected
Referenced by NcpBase::PrepareLastStatusResponse().
HandlePropertySet() [1/17]
otError HandlePropertySet (void) protected
Referenced by NcpBase::PrepareLastStatusResponse().
HandlePropertyInsert() [1/2]
otError HandlePropertyInsert (void) protected
Referenced by NcpBase::PrepareLastStatusResponse().
HandlePropertyRemove() [1/2]
otError HandlePropertyRemove (void) protected
Referenced by NcpBase::PrepareLastStatusResponse().
HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE()
otError HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE (uint8_t aHeader) protected
References NcpBase::GetLastOutboundFrameTag(), Buffer::kInvalidTag, NcpBase::mDecoder, NcpBase::mHostPowerReplyFrameTag, NcpBase::mHostPowerState, NcpBase::mHostPowerStateHeader, NcpBase::mHostPowerStateInProgress, OT_ERROR_NONE, Decoder::ReadUint8(), SPINEL_HOST_POWER_STATE_DEEP_SLEEP, SPINEL_HOST_POWER_STATE_LOW_POWER, SPINEL_HOST_POWER_STATE_OFFLINE, SPINEL_HOST_POWER_STATE_ONLINE, SPINEL_HOST_POWER_STATE_RESERVED, SPINEL_PROP_HOST_POWER_STATE, NcpBase::ThreadErrorToSpinelStatus(), NcpBase::WriteLastStatusFrame(), and NcpBase::WritePropertyValueIsFrame().
Referenced by NcpBase::HandlePropertySetForSpecialProperties(), and NcpBase::PrepareLastStatusResponse().
ResetCounters()
void ResetCounters (void) protected
References NcpBase::mFramingErrorCounter, NcpBase::mRxSpinelFrameCounter, NcpBase::mRxSpinelOutOfOrderTidCounter, and NcpBase::mTxSpinelFrameCounter.
Referenced by NcpBase::CommandHandler_RESET(), and NcpBase::PrepareLastStatusResponse().
StartLegacy()
void StartLegacy (void) inline protected
Referenced by NcpBase::PrepareLastStatusResponse().
StopLegacy()
void StopLegacy (void) inline protected
References NcpBase::ConvertLogLevel(), and NcpBase::ConvertLogRegion().
Referenced by NcpBase::HandlePropertyGet(), and NcpBase::PrepareLastStatusResponse().
ConvertLogLevel()
uint8_t ConvertLogLevel (otLogLevel aLogLevel) static protected
References OT_LOG_LEVEL_CRIT, OT_LOG_LEVEL_DEBG, OT_LOG_LEVEL_INFO, OT_LOG_LEVEL_NONE, OT_LOG_LEVEL_NOTE, OT_LOG_LEVEL_WARN, SPINEL_NCP_LOG_LEVEL_CRIT, SPINEL_NCP_LOG_LEVEL_DEBUG, SPINEL_NCP_LOG_LEVEL_EMERG, SPINEL_NCP_LOG_LEVEL_INFO, SPINEL_NCP_LOG_LEVEL_NOTICE, and SPINEL_NCP_LOG_LEVEL_WARN.
Referenced by NcpBase::HandlePropertyGet(), NcpBase::Log(), and NcpBase::StopLegacy().
ConvertLogRegion()
unsigned int ConvertLogRegion (otLogRegion aLogRegion) static protected
References OT_LOG_REGION_API, OT_LOG_REGION_ARP, OT_LOG_REGION_BBR, OT_LOG_REGION_BR, OT_LOG_REGION_CLI, OT_LOG_REGION_COAP, OT_LOG_REGION_CORE, OT_LOG_REGION_DNS, OT_LOG_REGION_DUA, OT_LOG_REGION_ICMP, OT_LOG_REGION_IP6, OT_LOG_REGION_MAC, OT_LOG_REGION_MEM, OT_LOG_REGION_MESH_COP, OT_LOG_REGION_MLE, OT_LOG_REGION_MLR, OT_LOG_REGION_NCP, OT_LOG_REGION_NET_DATA, OT_LOG_REGION_NET_DIAG, OT_LOG_REGION_PLATFORM, OT_LOG_REGION_SRP, OT_LOG_REGION_TCP, OT_LOG_REGION_UTIL, SPINEL_NCP_LOG_REGION_NONE, SPINEL_NCP_LOG_REGION_OT_API, SPINEL_NCP_LOG_REGION_OT_ARP, SPINEL_NCP_LOG_REGION_OT_BBR, SPINEL_NCP_LOG_REGION_OT_BR, SPINEL_NCP_LOG_REGION_OT_CLI, SPINEL_NCP_LOG_REGION_OT_COAP, SPINEL_NCP_LOG_REGION_OT_CORE, SPINEL_NCP_LOG_REGION_OT_DNS, SPINEL_NCP_LOG_REGION_OT_DUA, SPINEL_NCP_LOG_REGION_OT_ICMP, SPINEL_NCP_LOG_REGION_OT_IP6, SPINEL_NCP_LOG_REGION_OT_MAC, SPINEL_NCP_LOG_REGION_OT_MEM, SPINEL_NCP_LOG_REGION_OT_MESH_COP, SPINEL_NCP_LOG_REGION_OT_MLE, SPINEL_NCP_LOG_REGION_OT_MLR, SPINEL_NCP_LOG_REGION_OT_NCP, SPINEL_NCP_LOG_REGION_OT_NET_DATA, SPINEL_NCP_LOG_REGION_OT_NET_DIAG, SPINEL_NCP_LOG_REGION_OT_PLATFORM, SPINEL_NCP_LOG_REGION_OT_SRP, SPINEL_NCP_LOG_REGION_OT_TCP, and SPINEL_NCP_LOG_REGION_OT_UTIL.
Referenced by NcpBase::Log(), and NcpBase::StopLegacy().
ThreadErrorToSpinelStatus()
spinel_status_t ThreadErrorToSpinelStatus (otError aError) static protected
References OT_ERROR_ALREADY, OT_ERROR_BUSY, OT_ERROR_CHANNEL_ACCESS_FAILURE, OT_ERROR_DROP, OT_ERROR_FAILED, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_STATE, OT_ERROR_NO_ACK, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_NOT_CAPABLE, OT_ERROR_NOT_FOUND, OT_ERROR_NOT_IMPLEMENTED, OT_ERROR_PARSE, OT_ERROR_RESPONSE_TIMEOUT, OT_ERROR_UNKNOWN_NEIGHBOR, SPINEL_STATUS_ALREADY, SPINEL_STATUS_BUSY, SPINEL_STATUS_CCA_FAILURE, SPINEL_STATUS_DROPPED, SPINEL_STATUS_FAILURE, SPINEL_STATUS_INVALID_ARGUMENT, SPINEL_STATUS_INVALID_STATE, SPINEL_STATUS_ITEM_NOT_FOUND, SPINEL_STATUS_NO_ACK, SPINEL_STATUS_NOMEM, SPINEL_STATUS_NOT_CAPABLE, SPINEL_STATUS_OK, SPINEL_STATUS_PARSE_ERROR, SPINEL_STATUS_RESPONSE_TIMEOUT, SPINEL_STATUS_STACK_NATIVE__BEGIN, SPINEL_STATUS_UNIMPLEMENTED, and SPINEL_STATUS_UNKNOWN_NEIGHBOR.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::HandleCommandPropertyInsertRemove(), NcpBase::HandleCommandPropertySet(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), and NcpBase::HandleReceive().
LinkFlagsToFlagByte()
static uint8_t LinkFlagsToFlagByte (bool aRxOnWhenIdle, bool aDeviceType, bool aNetworkData) static protected
HandlePropertyGet() [2/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkRawIsEnabled(), and Encoder::WriteBool().
HandlePropertyGet() [3/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkGetChannel(), and Encoder::WriteUint8().
HandlePropertySet() [2/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, NcpBase::mIsRawStreamEnabled, OT_ERROR_NONE, otLinkRawIsEnabled(), otLinkRawReceive(), otLinkSetChannel(), Decoder::ReadUintPacked(), and SuccessOrExit.
HandlePropertyGet() [4/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkIsPromiscuous(), otLinkRawGetPromiscuous(), SPINEL_MAC_PROMISCUOUS_MODE_FULL, SPINEL_MAC_PROMISCUOUS_MODE_OFF, and Encoder::WriteUint8().
HandlePropertySet() [3/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otLinkRawSetPromiscuous(), otLinkSetPromiscuous(), Decoder::ReadUint8(), SPINEL_MAC_PROMISCUOUS_MODE_FULL, SPINEL_MAC_PROMISCUOUS_MODE_NETWORK, SPINEL_MAC_PROMISCUOUS_MODE_OFF, and SuccessOrExit.
HandlePropertyGet() [5/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkGetPanId(), and Encoder::WriteUint16().
HandlePropertySet() [4/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_NONE, otLinkSetPanId(), Decoder::ReadUint16(), and SuccessOrExit.
HandlePropertyGet() [6/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkGetExtendedAddress(), and Encoder::WriteEui64().
HandlePropertySet() [5/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_NONE, otLinkSetExtendedAddress(), Decoder::ReadEui64(), and SuccessOrExit.
HandlePropertyGet() [7/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkGetShortAddress(), and Encoder::WriteUint16().
HandlePropertyGet() [8/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mIsRawStreamEnabled, and Encoder::WriteBool().
HandlePropertySet() [6/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mEncoder, NcpBase::mInstance, NcpBase::mIsRawStreamEnabled, OT_ERROR_NONE, otLinkRawIsEnabled(), otLinkRawReceive(), otLinkRawSleep(), otPlatRadioGetCslAccuracy(), otPlatRadioGetCslUncertainty(), Decoder::ReadBool(), SuccessOrExit, and Encoder::WriteUint8().
HandlePropertyGet() [9/38]
otError HandlePropertyGet (void) protected
References NcpBase::EncodeChannelMask(), and NcpBase::mScanChannelMask.
HandlePropertySet() [7/17]
otError HandlePropertySet (void) protected
References NcpBase::DecodeChannelMask(), NcpBase::mScanChannelMask, OT_ERROR_NONE, and SuccessOrExit.
HandlePropertyGet() [10/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mScanPeriod, and Encoder::WriteUint16().
HandlePropertySet() [8/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mScanPeriod, and Decoder::ReadUint16().
HandlePropertyGet() [11/38]
otError HandlePropertyGet (void) protected
References NcpBase::kInvalidScanChannel, NcpBase::mEncoder, NcpBase::mInstance, otLinkIsActiveScanInProgress(), otLinkIsEnergyScanInProgress(), otLinkRawIsEnabled(), otThreadIsDiscoverInProgress(), SPINEL_SCAN_STATE_BEACON, SPINEL_SCAN_STATE_DISCOVER, SPINEL_SCAN_STATE_ENERGY, SPINEL_SCAN_STATE_IDLE, and Encoder::WriteUint8().
HandlePropertySet() [9/17]
otError HandlePropertySet (void) protected
References NcpBase::kInvalidScanChannel, NcpBase::mDecoder, NcpBase::mDiscoveryScanEnableFiltering, NcpBase::mDiscoveryScanJoinerFlag, NcpBase::mDiscoveryScanPanId, NcpBase::mInstance, NcpBase::mScanChannelMask, NcpBase::mScanPeriod, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_ERROR_NOT_IMPLEMENTED, otLinkActiveScan(), otLinkEnergyScan(), otLinkRawEnergyScan(), otLinkRawIsEnabled(), otThreadDiscover(), Decoder::ReadUint8(), SPINEL_SCAN_STATE_BEACON, SPINEL_SCAN_STATE_DISCOVER, SPINEL_SCAN_STATE_ENERGY, SPINEL_SCAN_STATE_IDLE, SuccessOrExit, and VerifyOrExit.
HandlePropertyGet() [12/38]
otError HandlePropertyGet (void) protected
References ChangedPropsSet::GetSupportedEntries(), ChangedPropsSet::IsEntryFiltered(), NcpBase::mChangedPropsSet, NcpBase::mEncoder, ChangedPropsSet::Entry::mPropKey, OT_ERROR_NONE, SuccessOrExit, and Encoder::WriteUintPacked().
HandlePropertySet() [10/17]
otError HandlePropertySet (void) protected
References ChangedPropsSet::ClearFilter(), ChangedPropsSet::EnablePropertyFilter(), Decoder::GetRemainingLengthInStruct(), IgnoreError(), NcpBase::mChangedPropsSet, NcpBase::mDecoder, OT_ERROR_NONE, Decoder::ReadUintPacked(), SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, SPINEL_PROP_UNSOL_UPDATE_FILTER, SuccessOrExit, and NcpBase::WritePropertyValueIsFrame().
HandlePropertyInsert() [2/2]
otError HandlePropertyInsert (void) protected
References ChangedPropsSet::EnablePropertyFilter(), NcpBase::mChangedPropsSet, NcpBase::mDecoder, OT_ERROR_NONE, Decoder::ReadUintPacked(), and SuccessOrExit.
HandlePropertyRemove() [2/2]
otError HandlePropertyRemove (void) protected
References ChangedPropsSet::EnablePropertyFilter(), NcpBase::mChangedPropsSet, NcpBase::mDecoder, OT_ERROR_NONE, Decoder::ReadUintPacked(), and SuccessOrExit.
HandlePropertyGet() [13/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mLastStatus, and Encoder::WriteUintPacked().
HandlePropertyGet() [14/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, OT_ERROR_NONE, SPINEL_PROTOCOL_VERSION_THREAD_MAJOR, SPINEL_PROTOCOL_VERSION_THREAD_MINOR, SuccessOrExit, and Encoder::WriteUintPacked().
HandlePropertyGet() [15/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, SPINEL_PROTOCOL_TYPE_THREAD, and Encoder::WriteUintPacked().
HandlePropertyGet() [16/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, and Encoder::WriteUintPacked().
HandlePropertyGet() [17/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, OT_ERROR_NONE, SPINEL_CAP_802_15_4_2450MHZ_OQPSK, SPINEL_CAP_802_15_4_915MHZ_OQPSK, SPINEL_CAP_CHANNEL_MANAGER, SPINEL_CAP_CHANNEL_MONITOR, SPINEL_CAP_CHILD_SUPERVISION, SPINEL_CAP_CONFIG_FTD, SPINEL_CAP_CONFIG_MTD, SPINEL_CAP_CONFIG_RADIO, SPINEL_CAP_COUNTERS, SPINEL_CAP_DUA, SPINEL_CAP_ERROR_RATE_TRACKING, SPINEL_CAP_JAM_DETECT, SPINEL_CAP_MAC_ALLOWLIST, SPINEL_CAP_MAC_RAW, SPINEL_CAP_MAC_RETRY_HISTOGRAM, SPINEL_CAP_MCU_POWER_STATE, SPINEL_CAP_MULTI_RADIO, SPINEL_CAP_NEST_LEGACY_INTERFACE, SPINEL_CAP_NET_THREAD_1_1, SPINEL_CAP_NET_THREAD_1_2, SPINEL_CAP_OOB_STEERING_DATA, SPINEL_CAP_OPENTHREAD_LOG_METADATA, SPINEL_CAP_PCAP, SPINEL_CAP_PEEK_POKE, SPINEL_CAP_POSIX, SPINEL_CAP_RADIO_COEX, SPINEL_CAP_RCP_API_VERSION, SPINEL_CAP_REFERENCE_DEVICE, SPINEL_CAP_ROLE_ROUTER, SPINEL_CAP_ROLE_SLEEPY, SPINEL_CAP_SLAAC, SPINEL_CAP_SRP_CLIENT, SPINEL_CAP_THREAD_BACKBONE_ROUTER, SPINEL_CAP_THREAD_BORDER_ROUTER, SPINEL_CAP_THREAD_COMMISSIONER, SPINEL_CAP_THREAD_CSL_RECEIVER, SPINEL_CAP_THREAD_JOINER, SPINEL_CAP_THREAD_LINK_METRICS, SPINEL_CAP_THREAD_SERVICE, SPINEL_CAP_THREAD_UDP_FORWARD, SPINEL_CAP_TIME_SYNC, SPINEL_CAP_UNSOL_UPDATE_FILTER, SuccessOrExit, and Encoder::WriteUintPacked().
HandlePropertyGet() [18/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, otGetVersionString(), and Encoder::WriteUtf8().
HandlePropertyGet() [19/38]
otError HandlePropertyGet (void) protected
References ExitNow, IgnoreError(), NcpBase::mDecoder, NcpBase::mEncoder, NcpBase::mInstance, OT_DEVICE_ROLE_DISABLED, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_PLAT_MCU_POWER_STATE_LOW_POWER, OT_PLAT_MCU_POWER_STATE_OFF, OT_PLAT_MCU_POWER_STATE_ON, otIp6IsEnabled(), otIp6SetEnabled(), otPlatGetMcuPowerState(), otPlatSetMcuPowerState(), otThreadGetDeviceRole(), otThreadSetEnabled(), Decoder::ReadUint8(), SPINEL_MCU_POWER_STATE_LOW_POWER, SPINEL_MCU_POWER_STATE_OFF, SPINEL_MCU_POWER_STATE_ON, NcpBase::StopLegacy(), SuccessOrExit, and Encoder::WriteUint8().
HandlePropertyGet() [20/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, SPINEL_MCU_POWER_STATE_ON, and Encoder::WriteUint8().
HandlePropertyGet() [21/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, SPINEL_POWER_STATE_ONLINE, and Encoder::WriteUint8().
HandlePropertySet() [11/17]
otError HandlePropertySet (void) protected
References OT_ERROR_NOT_IMPLEMENTED.
HandlePropertyGet() [22/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkGetFactoryAssignedIeeeEui64(), and Encoder::WriteEui64().
HandlePropertyGet() [23/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, Encoder::OverwriteWithLastStatusError(), and SPINEL_STATUS_UNIMPLEMENTED.
HandlePropertyGet() [24/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mHostPowerState, and Encoder::WriteUint8().
HandlePropertyGet() [25/38]
otError HandlePropertyGet (void) protected
References ChangedPropsSet::GetSupportedEntries(), NcpBase::mChangedPropsSet, NcpBase::mEncoder, ChangedPropsSet::Entry::mFilterable, ChangedPropsSet::Entry::mPropKey, OT_ERROR_NONE, SuccessOrExit, and Encoder::WriteUintPacked().
HandlePropertyGet() [26/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otPlatRadioGetRssi(), and Encoder::WriteInt8().
HandlePropertyGet() [27/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otPlatRadioGetReceiveSensitivity(), and Encoder::WriteInt8().
HandlePropertyGet() [28/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, otLinkGetChannel(), and Encoder::WriteUint32().
HandlePropertyGet() [29/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioGetCcaEnergyDetectThreshold(), Encoder::OverwriteWithLastStatusError(), NcpBase::ThreadErrorToSpinelStatus(), and Encoder::WriteInt8().
HandlePropertySet() [12/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioSetCcaEnergyDetectThreshold(), Decoder::ReadInt8(), and SuccessOrExit.
HandlePropertyGet() [30/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioGetTransmitPower(), Encoder::OverwriteWithLastStatusError(), NcpBase::ThreadErrorToSpinelStatus(), and Encoder::WriteInt8().
HandlePropertySet() [13/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioSetTransmitPower(), Decoder::ReadInt8(), and SuccessOrExit.
HandlePropertyGet() [31/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioGetFemLnaGain(), Encoder::OverwriteWithLastStatusError(), NcpBase::ThreadErrorToSpinelStatus(), and Encoder::WriteInt8().
HandlePropertySet() [14/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioSetFemLnaGain(), Decoder::ReadInt8(), and SuccessOrExit.
HandlePropertySet() [15/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioSetChannelMaxTransmitPower(), Decoder::ReadInt8(), Decoder::ReadUint8(), and SuccessOrExit.
HandlePropertyGet() [32/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioGetRegion(), Encoder::OverwriteWithLastStatusError(), NcpBase::ThreadErrorToSpinelStatus(), and Encoder::WriteUint16().
HandlePropertySet() [16/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mInstance, OT_ERROR_NONE, otPlatRadioSetRegion(), Decoder::ReadUint16(), and SuccessOrExit.
HandlePropertyGet() [33/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, OT_ASSERT, OT_UNREACHABLE_CODE, and Encoder::WriteBool().
HandlePropertyGet() [34/38]
otError HandlePropertyGet (void) protected
References OT_ERROR_NONE, and OT_UNREACHABLE_CODE.
HandlePropertyGet() [35/38]
otError HandlePropertyGet (void) protected
References NcpBase::ConvertLogLevel(), ExitNow, IgnoreError(), NcpBase::mDecoder, NcpBase::mEncoder, OT_ERROR_INVALID_ARGS, OT_LOG_LEVEL_CRIT, OT_LOG_LEVEL_DEBG, OT_LOG_LEVEL_INFO, OT_LOG_LEVEL_NONE, OT_LOG_LEVEL_NOTE, OT_LOG_LEVEL_WARN, OT_UNREACHABLE_CODE, otLoggingGetLevel(), otLoggingSetLevel(), Decoder::ReadUint8(), SPINEL_NCP_LOG_LEVEL_ALERT, SPINEL_NCP_LOG_LEVEL_CRIT, SPINEL_NCP_LOG_LEVEL_DEBUG, SPINEL_NCP_LOG_LEVEL_EMERG, SPINEL_NCP_LOG_LEVEL_ERR, SPINEL_NCP_LOG_LEVEL_INFO, SPINEL_NCP_LOG_LEVEL_NOTICE, SPINEL_NCP_LOG_LEVEL_WARN, SuccessOrExit, and Encoder::WriteUint8().
HandlePropertySet() [17/17]
otError HandlePropertySet (void) protected
References NcpBase::mDecoder, NcpBase::mLogTimestampBase, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otPlatAlarmMilliGetNow(), Decoder::ReadUint64(), SuccessOrExit, and VerifyOrExit.
HandlePropertyGet() [36/38]
otError HandlePropertyGet (void) protected
References NcpBase::mEncoder, NcpBase::mLogTimestampBase, and Encoder::WriteUint64().
HandlePropertyGet() [37/38]
otError HandlePropertyGet (void) protected
References NcpBase::EncodeChannelMask(), NcpBase::mInstance, otLinkGetSupportedChannelMask(), and otPlatRadioGetSupportedChannelMask().
HandlePropertyGet() [38/38]
otError HandlePropertyGet (void) protected
References Encoder::CloseStruct(), NcpBase::EncodeChannelMask(), ExitNow, NcpBase::GetNcpInstance(), otRadioCoexMetrics::mAvgRxRequestToGrantTime, otRadioCoexMetrics::mAvgTxRequestToGrantTime, NcpBase::mDecoder, NcpBase::mEncoder, NcpBase::mInstance, otLinkMetrics::mLinkMargin, otLinkMetrics::mLqi, otRadioCoexMetrics::mNumGrantGlitch, otRadioCoexMetrics::mNumRxDelayedGrant, otRadioCoexMetrics::mNumRxGrantDeactivatedDuringRequest, otRadioCoexMetrics::mNumRxGrantImmediate, otRadioCoexMetrics::mNumRxGrantNone, otRadioCoexMetrics::mNumRxGrantWait, otRadioCoexMetrics::mNumRxGrantWaitActivated, otRadioCoexMetrics::mNumRxGrantWaitTimeout, otRadioCoexMetrics::mNumRxRequest, otRadioCoexMetrics::mNumTxDelayedGrant, otRadioCoexMetrics::mNumTxGrantDeactivatedDuringRequest, otRadioCoexMetrics::mNumTxGrantImmediate, otRadioCoexMetrics::mNumTxGrantWait, otRadioCoexMetrics::mNumTxGrantWaitActivated, otRadioCoexMetrics::mNumTxGrantWaitTimeout, otRadioCoexMetrics::mNumTxRequest, otLinkMetrics::mPduCount, otLinkMetrics::mRssi, otRadioCoexMetrics::mStopped, Encoder::OpenStruct(), OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otNcpRegisterPeekPokeDelagates(), otPlatRadioGetCoexMetrics(), otPlatRadioGetPreferredChannelMask(), otPlatRadioIsCoexEnabled(), otPlatRadioSetCoexEnabled(), Encoder::OverwriteWithLastStatusError(), Decoder::ReadBool(), Decoder::ReadUint8(), SPINEL_THREAD_LINK_METRIC_LINK_MARGIN, SPINEL_THREAD_LINK_METRIC_LQI, SPINEL_THREAD_LINK_METRIC_PDU_COUNT, SPINEL_THREAD_LINK_METRIC_RSSI, SuccessOrExit, NcpBase::ThreadErrorToSpinelStatus(), VerifyOrExit, Encoder::WriteBool(), and Encoder::WriteUint32().
Field Documentation
sNcpInstance
NcpBase * sNcpInstance = nullptr static protected
Referenced by NcpBase::CommandHandler_RESET(), NcpBase::GetNcpInstance(), NcpBase::NcpBase(), and ot::Ncp::ResetReasonToSpinelStatus().
mInstance
Instance* mInstance protected
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::CommandHandler_RESET(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet(), NcpBase::NcpBase(), and NcpBase::UpdateChangedProps().
mTxFrameBuffer
Spinel::Buffer mTxFrameBuffer protected
Referenced by NcpBase::GetLastOutboundFrameTag(), and NcpBase::NcpBase().
mEncoder
Spinel::Encoder mEncoder protected
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::EncodeChannelMask(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet(), NcpBase::Log(), NcpBase::StreamWrite(), NcpBase::WriteLastStatusFrame(), NcpBase::WritePropertyValueInsertedRemovedFrame(), and NcpBase::WritePropertyValueIsFrame().
mDecoder
Spinel::Decoder mDecoder protected
Referenced by NcpBase::CommandHandler_PROP_VALUE_update(), NcpBase::CommandHandler_RESET(), NcpBase::DecodeChannelMask(), NcpBase::HandleCommand(), NcpBase::HandleCommandPropertyInsertRemove(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertyInsert(), NcpBase::HandlePropertyRemove(), NcpBase::HandlePropertySet(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), and NcpBase::HandleReceive().
mHostPowerStateInProgress
bool mHostPowerStateInProgress protected
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), NcpBase::HandleReceive(), NcpBase::ShouldDeferHostSend(), and NcpBase::ShouldWakeHost().
mLastStatus
spinel_status_t mLastStatus protected
Referenced by NcpBase::HandlePropertyGet(), and NcpBase::WriteLastStatusFrame().
mScanChannelMask
uint32_t mScanChannelMask protected
Referenced by NcpBase::HandlePropertyGet(), and NcpBase::HandlePropertySet().
mScanPeriod
uint16_t mScanPeriod protected
Referenced by NcpBase::HandlePropertyGet(), and NcpBase::HandlePropertySet().
mDiscoveryScanJoinerFlag
bool mDiscoveryScanJoinerFlag protected
Referenced by NcpBase::HandlePropertySet().
mDiscoveryScanEnableFiltering
bool mDiscoveryScanEnableFiltering protected
Referenced by NcpBase::HandlePropertySet().
mDiscoveryScanPanId
uint16_t mDiscoveryScanPanId protected
Referenced by NcpBase::HandlePropertySet().
mUpdateChangedPropsTask
Tasklet mUpdateChangedPropsTask protected
Referenced by NcpBase::Log(), NcpBase::NcpBase(), and NcpBase::StreamWrite().
mThreadChangedFlags
uint32_t mThreadChangedFlags protected
mChangedPropsSet
ChangedPropsSet mChangedPropsSet protected
Referenced by NcpBase::EnqueueResponse(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertyInsert(), NcpBase::HandlePropertyRemove(), NcpBase::HandlePropertySet(), NcpBase::Log(), NcpBase::NcpBase(), NcpBase::StreamWrite(), and NcpBase::UpdateChangedProps().
mHostPowerState
spinel_host_power_state_t mHostPowerState protected
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE(), NcpBase::HandleReceive(), NcpBase::ShouldDeferHostSend(), and NcpBase::ShouldWakeHost().
mHostPowerReplyFrameTag
Spinel::Buffer::FrameTag mHostPowerReplyFrameTag protected
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), and NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE().
mHostPowerStateHeader
uint8_t mHostPowerStateHeader protected
Referenced by NcpBase::HandleFrameRemovedFromNcpBuffer(), and NcpBase::HandlePropertySet_SPINEL_PROP_HOST_POWER_STATE().
mTxBuffer
uint8_t mTxBuffer[kTxBufferSize] protected
mNextExpectedTid
spinel_tid_t mNextExpectedTid protected
Referenced by NcpBase::EnqueueResponse(), and NcpBase::HandleReceive().
mResponseQueueHead
uint8_t mResponseQueueHead protected
Referenced by NcpBase::EnqueueResponse(), NcpBase::IsResponseQueueEmpty(), and NcpBase::SendQueuedResponses().
mResponseQueueTail
uint8_t mResponseQueueTail protected
Referenced by NcpBase::EnqueueResponse(), NcpBase::IsResponseQueueEmpty(), and NcpBase::SendQueuedResponses().
mResponseQueue
ResponseEntry mResponseQueue[kResponseQueueSize] protected
Referenced by NcpBase::EnqueueResponse(), NcpBase::NcpBase(), and NcpBase::SendQueuedResponses().
mAllowLocalNetworkDataChange
bool mAllowLocalNetworkDataChange protected
mRequireJoinExistingNetwork
bool mRequireJoinExistingNetwork protected
mIsRawStreamEnabled
bool mIsRawStreamEnabled protected
Referenced by NcpBase::CommandHandler_RESET(), NcpBase::HandlePropertyGet(), and NcpBase::HandlePropertySet().
mPcapEnabled
bool mPcapEnabled protected
mDisableStreamWrite
bool mDisableStreamWrite protected
Referenced by NcpBase::HandleCommandPropertyInsertRemove(), NcpBase::HandleCommandPropertySet(), NcpBase::HandleReceive(), NcpBase::Log(), and NcpBase::StreamWrite().
mShouldEmitChildTableUpdate
bool mShouldEmitChildTableUpdate protected
mFramingErrorCounter
uint32_t mFramingErrorCounter protected
Referenced by NcpBase::IncrementFrameErrorCounter(), and NcpBase::ResetCounters().
mRxSpinelFrameCounter
uint32_t mRxSpinelFrameCounter protected
Referenced by NcpBase::HandleReceive(), and NcpBase::ResetCounters().
mRxSpinelOutOfOrderTidCounter
uint32_t mRxSpinelOutOfOrderTidCounter protected
Referenced by NcpBase::HandleReceive(), and NcpBase::ResetCounters().
mTxSpinelFrameCounter
uint32_t mTxSpinelFrameCounter protected
Referenced by NcpBase::ResetCounters().
mDidInitialUpdates
bool mDidInitialUpdates protected
Referenced by NcpBase::UpdateChangedProps().
mLogTimestampBase
uint64_t mLogTimestampBase protected
Referenced by NcpBase::HandlePropertyGet(), NcpBase::HandlePropertySet(), and NcpBase::Log().
The documentation for this class was generated from the following files:
ncp_base.hpp
ncp_base.cpp
ncp_base_dispatcher.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale