OpenThread: FrameBuilder Class Reference
FrameBuilder Class Reference
#include <frame_builder.hpp>
Public Member Functions
template<typename ObjectType >
Error Append (const ObjectType &aObject)
Error AppendBigEndianUint16 (uint16_t aUint16)
Error AppendBigEndianUint32 (uint32_t aUint32)
Error AppendBytes (const void *aBuffer, uint16_t aLength)
Error AppendBytesFromMessage (const Message &aMessage, uint16_t aOffset, uint16_t aLength)
Error AppendLittleEndianUint16 (uint16_t aUint16)
Error AppendLittleEndianUint32 (uint32_t aUint32)
Error AppendUint8 (uint8_t aUint8)
bool CanAppend (uint16_t aLength) const
const uint8_t * GetBytes (void) const
uint16_t GetLength (void) const
uint16_t GetMaxLength (void) const
uint16_t GetRemainingLength (void) const
void Init (void *aBuffer, uint16_t aLength)
template<typename ObjectType >
Error Insert (uint16_t aOffset, const ObjectType &aObject)
Error InsertBytes (uint16_t aOffset, const void *aBuffer, uint16_t aLength)
void RemoveBytes (uint16_t aOffset, uint16_t aLength)
void SetMaxLength (uint16_t aLength)
template<typename ObjectType >
void Write (uint16_t aOffset, const ObjectType &aObject)
void WriteBytes (uint16_t aOffset, const void *aBuffer, uint16_t aLength)
Private Attributes
uint8_t * mBuffer
uint16_t mLength
uint16_t mMaxLength
Detailed Description
The FrameBuilder can be used to construct frame content in a given data buffer.
Member Function Documentation
Init()
void Init (void * aBuffer, uint16_t aLength)
This method initializes the FrameBuilder to use a given buffer.
FrameBuilder MUST be initialized before its other methods are used.
Parameters
[in] aBuffer A pointer to a buffer.
[in] aLength The data length (number of bytes in aBuffer).
References FrameBuilder::mBuffer, FrameBuilder::mLength, and FrameBuilder::mMaxLength.
Referenced by MeshHeader::AppendTo(), and MeshForwarder::PrepareDataFrame().
GetBytes()
const uint8_t* GetBytes (void) const inline
This method returns a pointer to the start of FrameBuilder buffer.
Returns
A pointer to the frame buffer.
References FrameBuilder::mBuffer.
Referenced by MeshHeader::AppendTo().
GetLength()
uint16_t GetLength (void) const inline
This method returns the current length of frame (number of bytes appended so far).
Returns
The current frame length.
References FrameBuilder::mLength.
Referenced by MeshHeader::AppendTo(), Lowpan::Compress(), and MeshForwarder::PrepareDataFrame().
GetMaxLength()
uint16_t GetMaxLength (void) const inline
This method returns the maximum length of the frame.
Returns
The maximum frame length (max number of bytes in the frame buffer).
References FrameBuilder::mMaxLength.
Referenced by MeshForwarder::PrepareDataFrame().
SetMaxLength()
void SetMaxLength (uint16_t aLength) inline
This method sets the maximum length of the frame.
This method does not perform any checks on the new given length. The caller MUST ensure that the specified max length is valid for the frame buffer.
Parameters
[in] aLength The maximum frame length.
References FrameBuilder::mMaxLength.
Referenced by MeshForwarder::PrepareDataFrame().
GetRemainingLength()
uint16_t GetRemainingLength (void) const inline
This method returns the remaining length (number of bytes that can be appended) in the frame.
Returns
The remaining length.
References FrameBuilder::mLength, and FrameBuilder::mMaxLength.
Referenced by MeshForwarder::PrepareDataFrame().
CanAppend()
bool CanAppend (uint16_t aLength) const inline
This method indicates whether or not there are enough bytes remaining in the FrameBuilder buffer to append a given number of bytes.
Parameters
[in] aLength The append length.
Return values
TRUE There are enough remaining bytes to append aLength bytes.
FALSE There are not enough remaining bytes to append aLength bytes.
References FrameBuilder::AppendBigEndianUint16(), FrameBuilder::AppendBigEndianUint32(), FrameBuilder::AppendBytes(), FrameBuilder::AppendBytesFromMessage(), FrameBuilder::AppendLittleEndianUint16(), FrameBuilder::AppendLittleEndianUint32(), FrameBuilder::AppendUint8(), FrameBuilder::mLength, and FrameBuilder::mMaxLength.
Referenced by FrameBuilder::AppendBytes(), FrameBuilder::AppendBytesFromMessage(), and FrameBuilder::InsertBytes().
AppendUint8()
Error AppendUint8 (uint8_t aUint8)
This method appends an uint8_t value to the FrameBuilder.
Parameters
[in] aUint8 The uint8_t value to append.
Return values
kErrorNone Successfully appended the value.
kErrorNoBufs Insufficient available buffers.
Referenced by MeshHeader::AppendTo(), FrameBuilder::CanAppend(), Lowpan::Compress(), Lowpan::CompressExtensionHeader(), Lowpan::CompressMulticast(), and Lowpan::CompressUdp().
AppendBigEndianUint16()
Error AppendBigEndianUint16 (uint16_t aUint16)
This method appends an uint16_t value assuming big endian encoding to the FrameBuilder.
Parameters
[in] aUint16 The uint16_t value to append.
Return values
kErrorNone Successfully appended the value.
kErrorNoBufs Insufficient available buffers.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by MeshHeader::AppendTo(), FrameBuilder::CanAppend(), Lowpan::Compress(), Lowpan::CompressDestinationIid(), Lowpan::CompressSourceIid(), and Lowpan::CompressUdp().
AppendBigEndianUint32()
Error AppendBigEndianUint32 (uint32_t aUint32)
This method appends an uint32_t value assuming big endian encoding to the FrameBuilder.
Parameters
[in] aUint32 The uint32_t value to append.
Return values
kErrorNone Successfully appended the value.
kErrorNoBufs Insufficient available buffers.
References ot::Encoding::BigEndian::HostSwap32().
Referenced by FrameBuilder::CanAppend().
AppendLittleEndianUint16()
Error AppendLittleEndianUint16 (uint16_t aUint16)
This method appends an uint16_t value assuming little endian encoding to the FrameBuilder.
Parameters
[in] aUint16 The uint16_t value to append.
Return values
kErrorNone Successfully appended the value.
kErrorNoBufs Insufficient available buffers.
References ot::Encoding::LittleEndian::HostSwap16().
Referenced by FrameBuilder::CanAppend().
AppendLittleEndianUint32()
Error AppendLittleEndianUint32 (uint32_t aUint32)
This method appends an uint32_t value assuming little endian encoding to the FrameBuilder.
Parameters
[in] aUint32 The uint32_t value to append.
Return values
kErrorNone Successfully appended the value.
kErrorNoBufs Insufficient available buffers.
References ot::Encoding::LittleEndian::HostSwap32().
Referenced by FrameBuilder::CanAppend().
AppendBytes()
Error AppendBytes (const void * aBuffer, uint16_t aLength)
This method appends bytes from a given buffer to the FrameBuilder.
Parameters
[in] aBuffer A pointer to a data bytes to append.
[in] aLength Number of bytes in aBuffer.
Return values
kErrorNone Successfully appended the bytes.
kErrorNoBufs Insufficient available buffers.
References FrameBuilder::CanAppend(), ot::kErrorNoBufs, ot::kErrorNone, FrameBuilder::mBuffer, FrameBuilder::mLength, and VerifyOrExit.
Referenced by FrameBuilder::Append(), FrameBuilder::CanAppend(), Lowpan::Compress(), Lowpan::CompressMulticast(), and Lowpan::CompressUdp().
AppendBytesFromMessage()
Error AppendBytesFromMessage (const Message & aMessage, uint16_t aOffset, uint16_t aLength)
This method appends bytes read from a given message to the FrameBuilder.
Parameters
[in] aMessage The message to read the bytes from.
[in] aOffset The offset in aMessage to start reading the bytes from.
[in] aLength Number of bytes to read from aMessage and append.
Return values
kErrorNone Successfully appended the bytes.
kErrorNoBufs Insufficient available buffers to append the requested aLength bytes.
kErrorParse Not enough bytes in aMessage to read aLength bytes from aOffset.
References FrameBuilder::CanAppend(), ot::kErrorNoBufs, ot::kErrorNone, FrameBuilder::mBuffer, FrameBuilder::mLength, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by FrameBuilder::CanAppend(), Lowpan::CompressExtensionHeader(), and MeshForwarder::PrepareDataFrame().
Append()
Error Append (const ObjectType & aObject) inline
This method appends an object to the FrameBuilder.
Template Parameters
ObjectType The object type to append.
Parameters
[in] aObject A reference to the object to append.
Return values
kErrorNone Successfully appended the object.
kErrorNoBufs Insufficient available buffers to append aObject.
References FrameBuilder::AppendBytes(), and FrameBuilder::WriteBytes().
Referenced by Lowpan::Compress(), Lowpan::CompressDestinationIid(), Lowpan::CompressMulticast(), Lowpan::CompressSourceIid(), and MeshForwarder::PrepareDataFrame().
WriteBytes()
void WriteBytes (uint16_t aOffset, const void * aBuffer, uint16_t aLength)
This method writes bytes in FrameBuilder at a given offset overwriting the previously appended content.
This method does not perform any bound checks. The caller MUST ensure that the given data length fits within the previously appended content. Otherwise the behavior of this method is undefined.
Parameters
[in] aOffset The offset to begin writing.
[in] aBuffer A pointer to a data buffer to write.
[in] aLength Number of bytes in aBuffer.
References FrameBuilder::mBuffer.
Referenced by FrameBuilder::Append(), and FrameBuilder::Write().
Write()
void Write (uint16_t aOffset, const ObjectType & aObject) inline
This methods writes an object to the FrameBuilder at a given offset overwriting previously appended content.
This method does not perform any bound checks. The caller MUST ensure the given data length fits within the previously appended content. Otherwise the behavior of this method is undefined.
Template Parameters
ObjectType The object type to write.
Parameters
[in] aOffset The offset to begin writing.
[in] aObject A reference to the object to write.
References FrameBuilder::InsertBytes(), and FrameBuilder::WriteBytes().
Referenced by Lowpan::Compress().
InsertBytes()
Error InsertBytes (uint16_t aOffset, const void * aBuffer, uint16_t aLength)
This method inserts bytes in FrameBuilder at a given offset, moving previous content forward.
The caller MUST ensure that aOffset is within the current frame length (from 0 up to and including GetLength()). Otherwise the behavior of this method is undefined.
Parameters
[in] aOffset The offset to insert bytes.
[in] aBuffer A pointer to a data buffer to insert.
[in] aLength Number of bytes in aBuffer.
Return values
kErrorNone Successfully inserted the bytes.
kErrorNoBufs Insufficient available buffers to insert the bytes.
References FrameBuilder::CanAppend(), ot::kErrorNoBufs, ot::kErrorNone, FrameBuilder::mBuffer, FrameBuilder::mLength, OT_ASSERT, and VerifyOrExit.
Referenced by FrameBuilder::Insert(), and FrameBuilder::Write().
Insert()
Error Insert (uint16_t aOffset, const ObjectType & aObject) inline
This method inserts an object in FrameBuilder at a given offset, moving previous content forward.
The caller MUST ensure that aOffset is within the current frame length (from 0 up to and including GetLength()). Otherwise the behavior of this method is undefined.
Template Parameters
ObjectType The object type to insert.
Parameters
[in] aOffset The offset to insert bytes.
[in] aObject A reference to the object to insert.
Return values
kErrorNone Successfully inserted the bytes.
kErrorNoBufs Insufficient available buffers to insert the bytes.
References FrameBuilder::InsertBytes(), and FrameBuilder::RemoveBytes().
Referenced by MeshForwarder::PrepareDataFrame().
RemoveBytes()
void RemoveBytes (uint16_t aOffset, uint16_t aLength)
This method removes a given number of bytes in FrameBuilder at a given offset, moving existing content after removed bytes backward.
This method does not perform any bound checks. The caller MUST ensure that the given length and offset fits within the previously appended content. Otherwise the behavior of this method is undefined.
Parameters
[in] aOffset The offset to remove bytes from.
[in] aLength The number of bytes to remove.
References FrameBuilder::mBuffer, and FrameBuilder::mLength.
Referenced by FrameBuilder::Insert().
Field Documentation
mBuffer
uint8_t* mBuffer private
Referenced by FrameBuilder::AppendBytes(), FrameBuilder::AppendBytesFromMessage(), FrameBuilder::GetBytes(), FrameBuilder::Init(), FrameBuilder::InsertBytes(), FrameBuilder::RemoveBytes(), and FrameBuilder::WriteBytes().
mLength
uint16_t mLength private
Referenced by FrameBuilder::AppendBytes(), FrameBuilder::AppendBytesFromMessage(), FrameBuilder::CanAppend(), FrameBuilder::GetLength(), FrameBuilder::GetRemainingLength(), FrameBuilder::Init(), FrameBuilder::InsertBytes(), and FrameBuilder::RemoveBytes().
mMaxLength
uint16_t mMaxLength private
Referenced by FrameBuilder::CanAppend(), FrameBuilder::GetMaxLength(), FrameBuilder::GetRemainingLength(), FrameBuilder::Init(), and FrameBuilder::SetMaxLength().
The documentation for this class was generated from the following files:
frame_builder.hpp
frame_builder.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale