OpenThread: ExternalRouteConfig Class Reference
ExternalRouteConfig Class Reference
#include <network_data_types.hpp>
Public Member Functions
const Ip6::Prefix & GetPrefix (void) const
Ip6::Prefix & GetPrefix (void)
void SetPrefix (const Ip6::Prefix &aPrefix)
Public Member Functions inherited from Clearable< ExternalRouteConfig >
void Clear (void)
Public Member Functions inherited from Equatable< ExternalRouteConfig >
bool operator== (const ExternalRouteConfig &aOther) const
Public Member Functions inherited from Unequatable< ExternalRouteConfig >
bool operator!= (const ExternalRouteConfig &aOther) const
Private Member Functions
void SetFrom (Instance &aInstance, const PrefixTlv &aPrefixTlv, const HasRouteTlv &aHasRouteTlv, const HasRouteEntry &aHasRouteEntry)
void SetFromTlvFlags (uint8_t aFlags)
Friends
class Local
class NetworkData
class Publisher
Additional Inherited Members
Data Fields inherited from otExternalRouteConfig
bool mNat64: 1
Whether this is a NAT64 prefix.
bool mNextHopIsThisDevice: 1
Whether the next hop is this device (value ignored on config add).
signed int mPreference: 2
A 2-bit signed int preference (OT_ROUTE_PREFERENCE_* values).
otIp6Prefix mPrefix
The IPv6 prefix.
uint16_t mRloc16
The border router's RLOC16 (value ignored on config add).
bool mStable: 1
Whether this configuration is considered Stable Network Data.
Detailed Description
This class represents an External Route configuration.
Member Function Documentation
GetPrefix() [1/2]
const Ip6::Prefix& GetPrefix (void) const inline
This method gets the prefix.
Returns
The prefix.
References ot::AsCoreType(), and otBorderRouterConfig::mPrefix.
Referenced by LeaderBase::GetPreferredNat64Prefix().
GetPrefix() [2/2]
Ip6::Prefix& GetPrefix (void) inline
This method gets the prefix.
Returns
The prefix.
References ot::AsCoreType(), and otBorderRouterConfig::mPrefix.
SetPrefix()
void SetPrefix (const Ip6::Prefix & aPrefix) inline
This method sets the prefix.
Parameters
[in] aPrefix The prefix to set to.
References otBorderRouterConfig::mPrefix, OnMeshPrefixConfig::SetFrom(), and OnMeshPrefixConfig::SetFromTlvFlags().
SetFrom()
void SetFrom (Instance & aInstance, const PrefixTlv & aPrefixTlv, const HasRouteTlv & aHasRouteTlv, const HasRouteEntry & aHasRouteEntry) private
References Clearable< OnMeshPrefixConfig >::Clear(), PrefixTlv::CopyPrefixTo(), Instance::Get(), HasRouteEntry::GetFlags(), OnMeshPrefixConfig::GetPrefix(), HasRouteEntry::GetRloc(), NetworkDataTlv::IsStable(), otBorderRouterConfig::mRloc16, otBorderRouterConfig::mStable, and OnMeshPrefixConfig::SetFromTlvFlags().
Referenced by NetworkData::Iterate().
SetFromTlvFlags()
void SetFromTlvFlags (uint8_t aFlags) private
References HasRouteEntry::kNat64Flag, HasRouteEntry::kPreferenceOffset, otBorderRouterConfig::mPreference, and ot::NetworkData::RoutePreferenceFromValue().
Friends And Related Function Documentation
NetworkData
friend class NetworkData friend
Local
friend class Local friend
Publisher
friend class Publisher friend
The documentation for this class was generated from the following files:
network_data_types.hpp
network_data_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale