OpenThread: LiteralKey Class Reference
LiteralKey Class Reference
#include <storage.hpp>
Public Member Functions
const uint8_t * GetBytes (void) const
uint16_t GetLength (void) const
LiteralKey (const Key &aKey)
Public Member Functions inherited from Clearable< LiteralKey >
void Clear (void)
Static Public Attributes
static constexpr uint16_t kMaxSize = 32
Maximum size of the key.
Private Attributes
const uint8_t * mKey
uint16_t mLength
Additional Inherited Members
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Detailed Description
This class represents a literal key derived from a Key.
Constructor & Destructor Documentation
LiteralKey()
LiteralKey (const Key & aKey) explicit
This constructor initializes the LiteralKey from a given Key.
If the aKey is itself represents a literal key the same key buffer pointers are used. If the aKey is a KeyRef then the literal key is extracted. In this case, the extracted key MUST be smaller than kMaxSize.
Parameters
[in] aKey The key to convert from.
References LiteralKey::mKey, LiteralKey::mLength, and SuccessOrAssert.
Member Function Documentation
GetBytes()
const uint8_t* GetBytes (void) const inline
Referenced by otPlatCryptoAesSetKey(), otPlatCryptoHkdfExtract(), and otPlatCryptoHmacSha256Start().
GetLength()
uint16_t GetLength (void) const inline
This method gets the key length.
Returns
The key length (number of bytes in the byte array from GetBytes()).
Referenced by otPlatCryptoAesSetKey(), otPlatCryptoHkdfExtract(), and otPlatCryptoHmacSha256Start().
Field Documentation
kMaxSize
constexpr uint16_t kMaxSize = 32 static
Maximum size of the key.
mKey
const uint8_t* mKey private
Referenced by LiteralKey::LiteralKey().
mLength
uint16_t mLength private
Referenced by LiteralKey::LiteralKey().
The documentation for this class was generated from the following files:
storage.hpp
storage.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale