OpenThread: TlvIterator Class Reference
TlvIterator Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Member Functions
template<typename TlvType >
const TlvType * Iterate (void)
template<typename TlvType >
const TlvType * Iterate (bool aStable)
TlvIterator (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
TlvIterator (const uint8_t *aBuffer, uint8_t aLength)
TlvIterator (const PrefixTlv &aPrefixTlv)
TlvIterator (const ServiceTlv &aServiceTlv)
Private Member Functions
const NetworkDataTlv * Iterate (NetworkDataTlv::Type aType)
const NetworkDataTlv * Iterate (NetworkDataTlv::Type aType, bool aStable)
Private Attributes
const NetworkDataTlv * mEnd
const NetworkDataTlv * mStart
Detailed Description
This class represents a Network Data TLV iterator.
Constructor & Destructor Documentation
TlvIterator() [1/4]
TlvIterator (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd) inline
This constructor initializes the TlvIterator to iterate over a given sequence of TLVs.
Parameters
[in] aStart A pointer to the start of the TLV sequence.
[in] aEnd A pointer to the end of the TLV sequence.
TlvIterator() [2/4]
TlvIterator (const uint8_t * aBuffer, uint8_t aLength) inline
This constructor initializes the TlvIterator to iterate over TLVs from a given buffer.
Parameters
[in] aBuffer A pointer to a buffer containing the TLVs.
[in] aLength The length (number of bytes) of aBuffer.
TlvIterator() [3/4]
TlvIterator (const PrefixTlv & aPrefixTlv) inline explicit
This constructor initializes the TlvIterator to iterate over sub-TLVs of a given Prefix TLV.
Parameters
[in] aPrefixTlv A Prefix TLV to iterate over its sub-TLVs.
TlvIterator() [4/4]
TlvIterator (const ServiceTlv & aServiceTlv) inline explicit
This constructor initializes the TlvIterator to iterate over sub-TLVs of a given Service TLV.
Parameters
[in] aServiceTlv A Service TLV to iterate over its sub-TLVs.
Member Function Documentation
Iterate() [1/4]
const TlvType* Iterate (void) inline
This template method iterates to the next TLV with a given type.
Template Parameters
TlvType The TLV Type to search for (MUST be a sub-class of NetworkDataTlv).
Returns
A pointer to the next TLV, or nullptr if it can not be found.
References TlvIterator::Iterate().
Referenced by LeaderBase::DefaultRouteLookup(), LeaderBase::ExternalRouteLookup(), NetworkData::FindPrefix(), NetworkData::FindService(), LeaderBase::GetContext(), and TlvIterator::Iterate().
Iterate() [2/4]
const TlvType* Iterate (bool aStable) inline
This template method iterates to the next TLV with a given type and stable flag.
Template Parameters
TlvType The TLV Type to search for (MUST be a sub-class of NetworkDataTlv).
Parameters
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the next TLV, or nullptr if it can not be found.
Iterate() [3/4]
const NetworkDataTlv * Iterate (NetworkDataTlv::Type aType) private
References NetworkDataTlv::Find(), NetworkDataTlv::GetNext(), and VerifyOrExit.
Iterate() [4/4]
const NetworkDataTlv * Iterate (NetworkDataTlv::Type aType, bool aStable) private
References NetworkDataTlv::Find(), NetworkDataTlv::GetNext(), and VerifyOrExit.
Field Documentation
mStart
const NetworkDataTlv* mStart private
mEnd
const NetworkDataTlv* mEnd private
The documentation for this class was generated from the following files:
network_data_tlvs.hpp
network_data_tlvs.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale