OpenThread: DnsSrpUnicast::ServerData Class Reference
DnsSrpUnicast::ServerData Class Reference
#include <network_data_service.hpp>
Public Member Functions
const Ip6::Address & GetAddress (void) const
uint8_t GetLength (void) const
uint16_t GetPort (void) const
ServerData (const Ip6::Address &aAddress, uint16_t aPort)
Private Attributes
Ip6::Address mAddress
uint16_t mPort
Detailed Description
This class represents long version of "DNS/SRP Service (Unicast)" server data.
Constructor & Destructor Documentation
ServerData()
ServerData (const Ip6::Address & aAddress, uint16_t aPort) inline
This constructor initializes the ServerData object.
Parameters
[in] aAddress The IPv6 address of DNS/SRP server.
[in] aPort The port number of DNS/SRP server.
Member Function Documentation
GetLength()
uint8_t GetLength (void) const inline
This method returns the length (in bytes) of server data.
Returns
The data length in bytes.
GetAddress()
const Ip6::Address& GetAddress (void) const inline
This method returns the IPv6 address.
Returns
The IPv6 address
Referenced by Manager::GetNextDnsSrpUnicastInfo().
GetPort()
uint16_t GetPort (void) const inline
This method returns the port number.
Returns
The port number.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Manager::GetNextDnsSrpUnicastInfo().
Field Documentation
mAddress
Ip6::Address mAddress private
mPort
uint16_t mPort private
The documentation for this class was generated from the following file:
network_data_service.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale