OpenThread: Cidr Class Reference
Cidr Class Reference
Core-ip4-ip4
#include <ip4_types.hpp>
Public Types
typedef String< Address::kAddressStringSize+kCidrSuffixSize > InfoString
Public Member Functions
const uint8_t * GetBytes (void) const
bool operator== (const Cidr &aOther) const
void Set (const uint8_t *aAddress, uint8_t aLength)
InfoString ToString (void) const
Public Member Functions inherited from Unequatable< Cidr >
bool operator!= (const Cidr &aOther) const
Public Member Functions inherited from Clearable< Address >
void Clear (void)
Static Public Attributes
static constexpr uint16_t kCidrSuffixSize = 3
Suffix to represent CIDR (/dd).
Private Member Functions
uint32_t HostMask (void) const
uint32_t SubnetMask (void) const
Friends
class Address
Additional Inherited Members
Data Fields inherited from otIp4Cidr
otIp4Address mAddress
uint8_t mLength
Detailed Description
This class represents an IPv4 CIDR block.
Member Typedef Documentation
InfoString
typedef String<Address::kAddressStringSize + kCidrSuffixSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Function Documentation
ToString()
Cidr::InfoString ToString (void) const
This method converts the IPv4 CIDR to a string.
The string format uses quad-dotted notation of four bytes in the address with the length of prefix (e.g., "127.0.0.1/32").
Returns
An InfoString representing the IPv4 cidr.
References StringWriter::Append(), ot::AsCoreType(), and Address::ToString().
GetBytes()
const uint8_t* GetBytes (void) const inline
This method gets the prefix as a pointer to a byte array.
Returns
A pointer to a byte array containing the Prefix.
Referenced by Cidr::operator==().
operator==()
bool operator== (const Cidr & aOther) const
This method overloads operator == to evaluate whether or not two prefixes are equal.
Parameters
[in] aOther The other prefix to compare with.
Return values
TRUE If the two prefixes are equal.
FALSE If the two prefixes are not equal.
References Address::GetBytes(), Cidr::GetBytes(), Address::kSize, Prefix::MatchLength(), and otIp4Cidr::mLength.
Set()
void Set (const uint8_t * aAddress, uint8_t aLength)
This method sets the CIDR.
Parameters
[in] aAddress A pointer to buffer containing the CIDR bytes. The length of aAddress should be 4 bytes.
[in] aLength The length of CIDR in bits.
References Address::kSize.
HostMask()
uint32_t HostMask (void) const inline private
References ot::Encoding::BigEndian::HostSwap32().
Referenced by Address::SynthesizeFromCidrAndHost().
SubnetMask()
uint32_t SubnetMask (void) const inline private
References OT_TOOL_PACKED_BEGIN.
Referenced by Address::SynthesizeFromCidrAndHost().
Friends And Related Function Documentation
Address
friend class Address friend
Field Documentation
kCidrSuffixSize
constexpr uint16_t kCidrSuffixSize = 3 static
Suffix to represent CIDR (/dd).
The documentation for this class was generated from the following files:
ip4_types.hpp
ip4_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale