OpenThread: Crc16 Class Reference
Crc16 Class Reference
#include <crc16.hpp>
Public Types
enum Polynomial : uint16_t { kCcitt = 0x1021, kAnsi = 0x8005 }
Public Member Functions
Crc16 (Polynomial aPolynomial)
uint16_t Get (void) const
void Init (void)
void Update (uint8_t aByte)
Private Attributes
uint16_t mCrc
uint16_t mPolynomial
Detailed Description
This class implements CRC16 computations.
Member Enumeration Documentation
Polynomial
enum Polynomial : uint16_t
Enumerator
kCcitt
CRC16_CCITT.
kAnsi
CRC16-ANSI.
Constructor & Destructor Documentation
Crc16()
Crc16 (Polynomial aPolynomial) explicit
This constructor initializes the object.
Parameters
[in] aPolynomial The polynomial value.
References Crc16::Init(), and Crc16::mPolynomial.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the CRC16 computation.
References Crc16::mCrc, and Crc16::Update().
Referenced by Crc16::Crc16().
Update()
void Update (uint8_t aByte)
References Crc16::mCrc, and Crc16::mPolynomial.
Referenced by SteeringData::CalculateHashBitIndexes(), and Crc16::Init().
Get()
uint16_t Get (void) const inline
This method gets the current CRC16 value.
Returns
The current CRC16 value.
References Crc16::mCrc.
Referenced by SteeringData::CalculateHashBitIndexes().
Field Documentation
mPolynomial
uint16_t mPolynomial private
Referenced by Crc16::Crc16(), and Crc16::Update().
mCrc
uint16_t mCrc private
Referenced by Crc16::Get(), Crc16::Init(), and Crc16::Update().
The documentation for this class was generated from the following files:
crc16.hpp
crc16.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale