OpenThread: GetProvider< InstanceGetProvider > Class Template Reference
GetProvider< InstanceGetProvider > Class Template Reference
Core-locator
#include <locator.hpp>
Public Member Functions
template<typename Type >
Type & Get (void) const
Protected Member Functions
GetProvider (void)=default
Detailed Description
template<class InstanceGetProvider>
class ot::GetProvider< InstanceGetProvider >
This template class implements Get<Type>() method for different Type objects belonging to the OpenThread instance.
Users of this class MUST follow CRTP-style inheritance, i.e., the class Class itself should publicly inherit from GetProvider<Class>.
Template Parameters
InstanceGetProvider The template sub-lass used in CRTP style inheritance. InstanceGetProvider MUST provide a method with the following signature: Instance &GetInstance(void) const
Constructor & Destructor Documentation
GetProvider()
GetProvider (void) protected default
Member Function Documentation
Get()
Type & Get (void) const inline
This template method returns a reference to a given Type object belonging to the OpenThread instance.
For example, Get<MeshForwarder>() returns a reference to the MeshForwarder object of the instance.
Note that any Type for which the Get<Type> is defined MUST be uniquely accessible from the OpenThread Instance through the member variable property hierarchy.
Returns
A reference to the Type object of the instance.
Referenced by Mle::CheckReachability(), Notifier::EmitEvents(), ot::MeshCoP::GetBorderAgentRloc(), Mle::HandleAttachTimer(), Mle::HandleDelayedResponseTimer(), PendingDatasetManager::HandleDelayTimer(), Mle::HandleDetachGracefullyTimer(), KeyManager::HandleKeyRotationTimer(), Mle::HandleMessageTransmissionTimer(), Mac::HandleOperationTask(), DataPollSender::HandlePollTimer(), Mpl::HandleSeedSetTimer(), Ip6::HandleSendQueue(), PanIdQueryServer::HandleTimer(), EnergyScanServer::HandleTimer(), AnnounceBeginServer::HandleTimer(), TimeTicker::HandleTimer(), DiscoverScanner::HandleTimer(), AnnounceSenderBase::HandleTimer(), ActiveDatasetManager::HandleTimer(), SubMac::HandleTimer(), PendingDatasetManager::HandleTimer(), Mac::HandleTimer(), MeshForwarder::ResumeMessageTransmissions(), MeshForwarder::ScheduleTransmissionTask(), and SubMac::StateToString().
The documentation for this class was generated from the following files:
locator.hpp
locator_getters.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale