OpenThread: NameData Class Reference
NameData Class Reference
#include <network_name.hpp>
Public Member Functions
uint8_t CopyTo (char *aBuffer, uint8_t aMaxSize) const
const char * GetBuffer (void) const
uint8_t GetLength (void) const
NameData (const char *aBuffer, uint8_t aLength)
Friends
class NetworkName
Additional Inherited Members
Private Types inherited from Data< kWithUint8Length >
using LengthType = typename TypeTraits::Conditional< kDataLengthType==kWithUint8Length, uint8_t, uint16_t >::Type
Private Member Functions inherited from Data< kWithUint8Length >
void CopyBytesTo (void *aBuffer) const
const uint8_t * GetBytes (void) const
LengthType GetLength (void) const
void Init (const void *aBuffer, LengthType aLength)
void InitFrom (const ObjectType &aObject)
void InitFromRange (const uint8_t *aStart, const uint8_t *aEnd)
bool MatchesBytesIn (const void *aBuffer) const
bool MatchesBytesIn (const void *aBuffer, ByteMatcher aMatcher)
bool operator== (const Data &aOtherData) const
void SetLength (LengthType aLength)
bool StartsWith (const Data &aOtherData) const
Private Member Functions inherited from Clearable< Data< kDataLengthType > >
void Clear (void)
Private Member Functions inherited from Unequatable< Data< kDataLengthType > >
bool operator!= (const Data< kDataLengthType > &aOther) const
Detailed Description
This class represents a name string as data (pointer to a char buffer along with a length).
Note
The char array does NOT need to be null terminated.
Constructor & Destructor Documentation
NameData()
NameData (const char * aBuffer, uint8_t aLength) inline
This constructor initializes the NameData object.
Parameters
[in] aBuffer A pointer to a char buffer (does not need to be null terminated).
[in] aLength The length (number of chars) in the buffer.
References Data< kWithUint8Length >::Init().
Referenced by NetworkName::GetAsData().
Member Function Documentation
GetBuffer()
const char* GetBuffer (void) const inline
This method returns the pointer to char buffer (not necessarily null terminated).
Returns
The pointer to the char buffer.
References Data< kWithUint8Length >::GetBytes().
Referenced by NetworkName::Set(), and Dataset::SetFrom().
GetLength()
uint8_t GetLength (void) const inline
This method returns the length (number of chars in buffer).
Returns
The name length.
References NameData::CopyTo(), and Data< kDataLengthType >::GetLength().
Referenced by NetworkName::Set(), and Dataset::SetFrom().
CopyTo()
uint8_t CopyTo (char * aBuffer, uint8_t aMaxSize) const
This method copies the name data into a given char buffer with a given size.
The given buffer is cleared (memset to zero) before copying the name into it. The copied string in aBuffer is NOT necessarily null terminated.
Parameters
[out] aBuffer A pointer to a buffer where to copy the name into.
[in] aMaxSize Size of aBuffer (maximum number of chars to write into aBuffer).
Returns
The actual number of chars copied into aBuffer.
References MutableData< kDataLengthType >::ClearBytes(), MutableData< kDataLengthType >::CopyBytesFrom(), Data< kDataLengthType >::GetLength(), IgnoreError(), and MutableData< kDataLengthType >::Init().
Referenced by NameData::GetLength(), NetworkNameTlv::SetNetworkName(), and BeaconPayload::SetNetworkName().
Friends And Related Function Documentation
NetworkName
friend class NetworkName friend
The documentation for this class was generated from the following files:
network_name.hpp
network_name.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale