OpenThread: Neighbor::AddressMatcher Class Reference
Neighbor::AddressMatcher Class Reference
#include <topology.hpp>
Public Member Functions
AddressMatcher (Mac::ShortAddress aShortAddress, StateFilter aStateFilter)
AddressMatcher (const Mac::ExtAddress &aExtAddress, StateFilter aStateFilter)
AddressMatcher (const Mac::Address &aMacAddress, StateFilter aStateFilter)
AddressMatcher (StateFilter aStateFilter)
bool Matches (const Neighbor &aNeighbor) const
Private Member Functions
AddressMatcher (StateFilter aStateFilter, Mac::ShortAddress aShortAddress, const Mac::ExtAddress *aExtAddress)
Private Attributes
const Mac::ExtAddress * mExtAddress
Mac::ShortAddress mShortAddress
StateFilter mStateFilter
Detailed Description
This class represents an Address Matcher used to find a neighbor (child/router) with a given MAC address also matching a given state filter.
Constructor & Destructor Documentation
AddressMatcher() [1/5]
AddressMatcher (Mac::ShortAddress aShortAddress, StateFilter aStateFilter) inline
This constructor initializes the AddressMatcher with a given MAC short address (RCOC16) and state filter.
Parameters
[in] aShortAddress A MAC short address (RLOC16).
[in] aStateFilter A state filter.
AddressMatcher() [2/5]
AddressMatcher (const Mac::ExtAddress & aExtAddress, StateFilter aStateFilter) inline
This constructor initializes the AddressMatcher with a given MAC extended address and state filter.
Parameters
[in] aExtAddress A MAC extended address.
[in] aStateFilter A state filter.
AddressMatcher() [3/5]
AddressMatcher (const Mac::Address & aMacAddress, StateFilter aStateFilter) inline
This constructor initializes the AddressMatcher with a given MAC address and state filter.
Parameters
[in] aMacAddress A MAC address.
[in] aStateFilter A state filter.
AddressMatcher() [4/5]
AddressMatcher (StateFilter aStateFilter) inline explicit
This constructor initializes the AddressMatcher with a given state filter (it accepts any address).
Parameters
[in] aStateFilter A state filter.
References Neighbor::AddressMatcher::Matches().
AddressMatcher() [5/5]
AddressMatcher (StateFilter aStateFilter, Mac::ShortAddress aShortAddress, const Mac::ExtAddress * aExtAddress) inline private
Member Function Documentation
Matches()
bool Matches (const Neighbor & aNeighbor) const
This method indicates if a given neighbor matches the address and state filter of AddressMatcher.
Parameters
[in] aNeighbor A neighbor.
Return values
TRUE Neighbor aNeighbor matches the address and state filter.
FALSE Neighbor aNeighbor does not match the address or state filter.
References Neighbor::GetExtAddress(), Neighbor::GetRloc16(), ot::Mac::kShortAddrInvalid, Neighbor::MatchesFilter(), Neighbor::AddressMatcher::mExtAddress, Neighbor::AddressMatcher::mShortAddress, Neighbor::AddressMatcher::mStateFilter, and VerifyOrExit.
Referenced by Neighbor::AddressMatcher::AddressMatcher(), and Neighbor::Matches().
Field Documentation
mStateFilter
StateFilter mStateFilter private
Referenced by Neighbor::AddressMatcher::Matches().
mShortAddress
Mac::ShortAddress mShortAddress private
Referenced by Neighbor::AddressMatcher::Matches().
mExtAddress
const Mac::ExtAddress* mExtAddress private
Referenced by Neighbor::AddressMatcher::Matches(), Neighbor::Info::SetFrom(), Router::Info::SetFrom(), and Neighbor::StateToString().
The documentation for this class was generated from the following files:
topology.hpp
topology.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale