OpenThread: FrameData Class Reference
FrameData Class Reference
#include <frame_data.hpp>
Public Member Functions
bool CanRead (uint16_t aLength) const
template<typename ObjectType >
Error Read (ObjectType &aObject)
Error ReadBigEndianUint16 (uint16_t &aUint16)
Error ReadBigEndianUint32 (uint32_t &aUint32)
Error ReadBytes (void *aBuffer, uint16_t aLength)
Error ReadLittleEndianUint16 (uint16_t &aUint16)
Error ReadLittleEndianUint32 (uint32_t &aUint32)
Error ReadUint8 (uint8_t &aUint8)
void SkipOver (uint16_t aLength)
Public Member Functions inherited from Data< kWithUint16Length >
void CopyBytesTo (void *aBuffer) const
const uint8_t * GetBytes (void) const
LengthType GetLength (void) const
void Init (const void *aBuffer, LengthType aLength)
void InitFrom (const ObjectType &aObject)
void InitFromRange (const uint8_t *aStart, const uint8_t *aEnd)
bool MatchesBytesIn (const void *aBuffer) const
bool MatchesBytesIn (const void *aBuffer, ByteMatcher aMatcher)
bool operator== (const Data &aOtherData) const
void SetLength (LengthType aLength)
bool StartsWith (const Data &aOtherData) const
Public Member Functions inherited from Clearable< Data< kDataLengthType > >
void Clear (void)
Public Member Functions inherited from Unequatable< Data< kDataLengthType > >
bool operator!= (const Data< kDataLengthType > &aOther) const
Additional Inherited Members
Public Types inherited from Data< kWithUint16Length >
using LengthType = typename TypeTraits::Conditional< kDataLengthType==kWithUint8Length, uint8_t, uint16_t >::Type
Detailed Description
This class represents a frame Data which is simply a wrapper over a pointer to a buffer with a given frame length.
It provide helper method to parse the content. As data is parsed and read, the FrameData is updated to skip over the read content.
Member Function Documentation
CanRead()
bool CanRead (uint16_t aLength) const inline
This method indicates whether or not there are enough bytes remaining in the FrameData to read a given number of bytes.
Parameters
[in] aLength The read length to check.
Return values
TRUE There are enough remaining bytes to read aLength bytes.
FALSE There are not enough remaining bytes to read aLength bytes.
References Data< kWithUint16Length >::GetLength(), FrameData::ReadBigEndianUint16(), FrameData::ReadBigEndianUint32(), FrameData::ReadBytes(), FrameData::ReadLittleEndianUint16(), FrameData::ReadLittleEndianUint32(), and FrameData::ReadUint8().
Referenced by Lowpan::DecompressExtensionHeader(), and FrameData::ReadBytes().
ReadUint8()
Error ReadUint8 (uint8_t & aUint8)
This method reads an uint8_t value from the FrameData.
If read successfully, the FrameData is updated to skip over the read content.
Parameters
[out] aUint8 A reference to an uint8_t to return the read value.
Return values
kErrorNone Successfully read uint8_t value and skipped over it.
kErrorParse Not enough bytes remaining to read.
References FrameData::ReadBytes().
Referenced by FrameData::CanRead(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressExtensionHeader(), and Lowpan::DecompressUdpHeader().
ReadBigEndianUint16()
Error ReadBigEndianUint16 (uint16_t & aUint16)
This method reads an uint16_t value assuming big endian encoding from the FrameData.
If read successfully, the FrameData is updated to skip over the read content.
Parameters
[out] aUint16 A reference to an uint16_t to return the read value.
Return values
kErrorNone Successfully read uint16_t value and skipped over it.
kErrorParse Not enough bytes remaining to read.
References ot::Encoding::BigEndian::HostSwap16(), FrameData::ReadBytes(), and SuccessOrExit.
Referenced by FrameData::CanRead(), Lowpan::DecompressBaseHeader(), and Lowpan::DecompressUdpHeader().
ReadBigEndianUint32()
Error ReadBigEndianUint32 (uint32_t & aUint32)
This method reads an uint32_t value assuming big endian encoding from the FrameData.
If read successfully, the FrameData is updated to skip over the read content.
Parameters
[out] aUint32 A reference to an uint32_t to return the read value.
Return values
kErrorNone Successfully read uint32_t value and skipped over it.
kErrorParse Not enough bytes remaining to read.
References ot::Encoding::BigEndian::HostSwap32(), FrameData::ReadBytes(), and SuccessOrExit.
Referenced by FrameData::CanRead().
ReadLittleEndianUint16()
Error ReadLittleEndianUint16 (uint16_t & aUint16)
This method reads an uint16_t value assuming little endian encoding from the FrameData.
If read successfully, the FrameData is updated to skip over the read content.
Parameters
[out] aUint16 A reference to an uint16_t to return the read value.
Return values
kErrorNone Successfully read uint16_t value and skipped over it.
kErrorParse Not enough bytes remaining to read.
References ot::Encoding::LittleEndian::HostSwap16(), FrameData::ReadBytes(), and SuccessOrExit.
Referenced by FrameData::CanRead().
ReadLittleEndianUint32()
Error ReadLittleEndianUint32 (uint32_t & aUint32)
This method reads an uint32_t value assuming little endian encoding from the FrameData.
If read successfully, the FrameData is updated to skip over the read content.
Parameters
[out] aUint32 A reference to an uint32_t to return the read value.
Return values
kErrorNone Successfully read uint32_t value and skipped over it.
kErrorParse Not enough bytes remaining to read.
References ot::Encoding::LittleEndian::HostSwap32(), FrameData::ReadBytes(), and SuccessOrExit.
Referenced by FrameData::CanRead().
ReadBytes()
Error ReadBytes (void * aBuffer, uint16_t aLength)
This method reads a given number of bytes from the FrameData.
If read successfully, the FrameData is updated to skip over the read content.
Parameters
[out] aBuffer The buffer to copy the read bytes into.
[in] aLength Number of bytes to read.
Return values
kErrorNone Successfully read aLength bytes into aBuffer and skipped over them.
kErrorParse Not enough bytes remaining to read aLength.
References FrameData::CanRead(), Data< kWithUint16Length >::GetBytes(), ot::kErrorNone, ot::kErrorParse, FrameData::SkipOver(), and VerifyOrExit.
Referenced by FrameData::CanRead(), Lowpan::DecompressBaseHeader(), FrameData::Read(), FrameData::ReadBigEndianUint16(), FrameData::ReadBigEndianUint32(), FrameData::ReadLittleEndianUint16(), FrameData::ReadLittleEndianUint32(), and FrameData::ReadUint8().
Read()
Error Read (ObjectType & aObject) inline
This template method reads an object from the FrameData.
Template Parameters
ObjectType The object type to read from the message.
Parameters
[out] aObject A reference to the object to read into.
Return values
kErrorNone Successfully read aObject and skipped over the read content.
kErrorParse Not enough bytes remaining to read the entire object.
References FrameData::ReadBytes(), and FrameData::SkipOver().
Referenced by Lowpan::DecompressBaseHeader(), and Headers::DecompressFrom().
SkipOver()
void SkipOver (uint16_t aLength)
This method skips over a given number of bytes from FrameData.
The caller MUST make sure that the aLength is smaller than current data length. Otherwise the behavior of this method is undefined.
Parameters
[in] aLength The length (number of bytes) to skip over.
References Data< kWithUint16Length >::GetBytes(), Data< kWithUint16Length >::GetLength(), and Data< kWithUint16Length >::Init().
Referenced by Lowpan::Decompress(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressExtensionHeader(), MeshHeader::ParseFrom(), FragmentHeader::ParseFrom(), FrameData::Read(), and FrameData::ReadBytes().
The documentation for this class was generated from the following files:
frame_data.hpp
frame_data.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale