OpenThread: Address Class Reference
Address Class Reference
Core-ip4-ip4
#include <ip4_types.hpp>
Public Types
typedef String< kAddressStringSize > InfoString
Public Member Functions
void ExtractFromIp6Address (uint8_t aPrefixLength, const Ip6::Address &aIp6Address)
Error FromString (const char *aString)
const uint8_t * GetBytes (void) const
void SetBytes (const uint8_t *aBuffer)
void SynthesizeFromCidrAndHost (const Cidr &aCidr, uint32_t aHost)
InfoString ToString (void) const
Public Member Functions inherited from Equatable< Address >
bool operator== (const Address &aOther) const
Public Member Functions inherited from Unequatable< Address >
bool operator!= (const Address &aOther) const
Public Member Functions inherited from Clearable< Address >
void Clear (void)
Static Public Attributes
static constexpr uint16_t kAddressStringSize = 17
String size used by ToString().
static constexpr uint16_t kSize = 4
Size of an IPv4 Address (in bytes).
Additional Inherited Members
Data Fields inherited from otIp4Address
union otIp4Address::OT_TOOL_PACKED_FIELD mFields
Detailed Description
This class represents an IPv4 address.
Member Typedef Documentation
InfoString
typedef String<kAddressStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Function Documentation
GetBytes()
const uint8_t* GetBytes (void) const inline
This method gets the IPv4 address as a pointer to a byte array.
Returns
A pointer to a byte array containing the IPv4 address.
Referenced by Checksum::Calculate(), Address::FromString(), Cidr::operator==(), and Address::SynthesizeFromIp4Address().
SetBytes()
void SetBytes (const uint8_t * aBuffer) inline
This method sets the IPv4 address from a given byte array.
Parameters
[in] aBuffer Pointer to an array containing the IPv4 address. kSize bytes from the buffer are copied to form the IPv4 address.
References ot::Ip6::OT_TOOL_PACKED_END.
ExtractFromIp6Address()
void ExtractFromIp6Address (uint8_t aPrefixLength, const Ip6::Address & aIp6Address)
This method sets the IPv4 address by performing NAT64 address translation from a given IPv6 address as specified in RFC 6052.
The NAT64 aPrefixLength MUST be one of the following values: 32, 40, 48, 56, 64, or 96, otherwise the behavior of this method is undefined.
Parameters
[in] aPrefixLength The prefix length to use for IPv4/IPv6 translation.
[in] aIp6Address The IPv6 address to translate to IPv4.
References Address::GetBytes(), Prefix::IsValidNat64PrefixLength(), Address::kSize, otIp4Address::OT_TOOL_PACKED_FIELD::m8, otIp4Address::mFields, and OT_ASSERT.
SynthesizeFromCidrAndHost()
void SynthesizeFromCidrAndHost (const Cidr & aCidr, uint32_t aHost)
This method sets the IPv4 address from the given CIDR and the host field.
Parameters
[in] aCidr The CIDR for the IPv4 address.
[in] aHost The host bits of the IPv4 address in host byte order. The aHost will be masked by host mask.
References Cidr::HostMask(), ot::Encoding::BigEndian::HostSwap32(), otIp4Address::OT_TOOL_PACKED_FIELD::m32, otIp4Cidr::mAddress, otIp4Address::mFields, and Cidr::SubnetMask().
FromString()
Error FromString (const char * aString)
This method parses an IPv4 address string.
The string MUST follow the quad-dotted notation of four decimal values (ranging from 0 to 255 each). For example, "127.0.0.1"
Parameters
[in] aString A pointer to the null-terminated string.
Return values
kErrorNone Successfully parsed the IPv4 address string.
kErrorParse Failed to parse the IPv4 address string.
References ot::kErrorNone, ot::kErrorParse, ot::kNullChar, otIp4Address::OT_TOOL_PACKED_FIELD::m8, otIp4Address::mFields, and VerifyOrExit.
Referenced by Address::FromString().
ToString()
Address::InfoString ToString (void) const
This method converts the IPv4 address to a string.
The string format uses quad-dotted notation of four bytes in the address (e.g., "127.0.0.1").
Returns
An InfoString representing the IPv4 address.
References StringWriter::Append(), otIp4Address::OT_TOOL_PACKED_FIELD::m8, and otIp4Address::mFields.
Referenced by Cidr::ToString().
Field Documentation
kSize
constexpr uint16_t kSize = 4 static
Size of an IPv4 Address (in bytes).
Referenced by Address::ExtractFromIp6Address(), Address::FromString(), Cidr::operator==(), Cidr::Set(), and Address::SynthesizeFromIp4Address().
kAddressStringSize
constexpr uint16_t kAddressStringSize = 17 static
String size used by ToString().
The documentation for this class was generated from the following files:
ip4_types.hpp
ip4_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale