OpenThread: MessageInfo Class Reference
MessageInfo Class Reference
#include <tmf.hpp>
Public Member Functions
MessageInfo (Instance &aInstance)
void SetSockAddrToRloc (void)
void SetSockAddrToRlocPeerAddrTo (uint16_t aRloc16)
void SetSockAddrToRlocPeerAddrTo (const Ip6::Address &aPeerAddress)
Error SetSockAddrToRlocPeerAddrToLeaderAloc (void)
Error SetSockAddrToRlocPeerAddrToLeaderRloc (void)
void SetSockAddrToRlocPeerAddrToRealmLocalAllRoutersMulticast (void)
void SetSockPortToTmf (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Public Member Functions inherited from MessageInfo
Ecn GetEcn (void) const
uint8_t GetHopLimit (void) const
const void * GetLinkInfo (void) const
bool GetMulticastLoop (void) const
Address & GetPeerAddr (void)
const Address & GetPeerAddr (void) const
uint16_t GetPeerPort (void) const
Address & GetSockAddr (void)
const Address & GetSockAddr (void) const
uint16_t GetSockPort (void) const
const ThreadLinkInfo * GetThreadLinkInfo (void) const
bool IsHostInterface (void) const
MessageInfo (void)
void SetEcn (Ecn aEcn)
void SetHopLimit (uint8_t aHopLimit)
void SetIsHostInterface (bool aIsHost)
void SetLinkInfo (const void *aLinkInfo)
void SetMulticastLoop (bool aMulticastLoop)
void SetPeerAddr (const Address &aAddress)
void SetPeerPort (uint16_t aPort)
void SetSockAddr (const Address &aAddress)
void SetSockPort (uint16_t aPort)
bool ShouldAllowZeroHopLimit (void) const
Public Member Functions inherited from Clearable< MessageInfo >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otMessageInfo
bool mAllowZeroHopLimit: 1
TRUE to allow IPv6 Hop Limit 0 in mHopLimit, FALSE otherwise.
uint8_t mEcn: 2
The ECN status of the packet, represented as in the IPv6 header.
uint8_t mHopLimit
bool mIsHostInterface: 1
TRUE if packets sent/received via host interface, FALSE otherwise.
const void * mLinkInfo
A pointer to link-specific information.
bool mMulticastLoop: 1
TRUE to allow looping back multicast, FALSE otherwise.
otIp6Address mPeerAddr
The peer IPv6 address.
uint16_t mPeerPort
The peer transport-layer port.
otIp6Address mSockAddr
The local IPv6 address.
uint16_t mSockPort
The local transport-layer port.
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class represents message information for a TMF message.
This is sub-class of Ip6::MessageInfo intended for use when sending TMF messages.
Constructor & Destructor Documentation
MessageInfo()
MessageInfo (Instance & aInstance) inline explicit
This constructor initializes the MessageInfo.
The peer port is set to Tmf::kUdpPort and all other properties are cleared (set to zero).
Parameters
[in] aInstance The OpenThread instance.
References MessageInfo::SetPeerPort().
Member Function Documentation
SetSockPortToTmf()
void SetSockPortToTmf (void) inline
This method sets the local socket port to TMF port.
References MessageInfo::SetSockAddrToRloc(), MessageInfo::SetSockAddrToRlocPeerAddrTo(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderAloc(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderRloc(), MessageInfo::SetSockAddrToRlocPeerAddrToRealmLocalAllRoutersMulticast(), and MessageInfo::SetSockPort().
SetSockAddrToRloc()
void SetSockAddrToRloc (void)
This method sets the local socket address to mesh-local RLOC address.
References MessageInfo::SetSockAddr().
Referenced by MessageInfo::SetSockAddrToRlocPeerAddrTo(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderAloc(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderRloc(), MessageInfo::SetSockAddrToRlocPeerAddrToRealmLocalAllRoutersMulticast(), and MessageInfo::SetSockPortToTmf().
SetSockAddrToRlocPeerAddrToLeaderAloc()
Error SetSockAddrToRlocPeerAddrToLeaderAloc (void)
This method sets the local socket address to RLOC address and the peer socket address to leader ALOC.
Return values
kErrorNone Successfully set the addresses.
kErrorDetached Cannot set leader ALOC since device is currently detached.
References MessageInfo::GetPeerAddr(), and MessageInfo::SetSockAddrToRloc().
Referenced by DatasetManager::SendGetRequest(), NetworkData::SendServerDataNotification(), DatasetManager::SendSet(), DatasetManager::SendSetRequest(), and MessageInfo::SetSockPortToTmf().
SetSockAddrToRlocPeerAddrToLeaderRloc()
Error SetSockAddrToRlocPeerAddrToLeaderRloc (void)
This method sets the local socket address to RLOC address and the peer socket address to leader RLOC.
Return values
kErrorNone Successfully set the addresses.
kErrorDetached Cannot set leader RLOC since device is currently detached.
References MessageInfo::GetPeerAddr(), and MessageInfo::SetSockAddrToRloc().
Referenced by MessageInfo::SetSockPortToTmf().
SetSockAddrToRlocPeerAddrToRealmLocalAllRoutersMulticast()
void SetSockAddrToRlocPeerAddrToRealmLocalAllRoutersMulticast (void)
This method sets the local socket address to RLOC address and the peer socket address to realm-local all routers multicast address.
References MessageInfo::GetPeerAddr(), MessageInfo::SetSockAddrToRloc(), and Address::SetToRealmLocalAllRoutersMulticast().
Referenced by AddressResolver::AddressResolver(), and MessageInfo::SetSockPortToTmf().
SetSockAddrToRlocPeerAddrTo() [1/2]
void SetSockAddrToRlocPeerAddrTo (uint16_t aRloc16)
This method sets the local socket address to RLOC address and the peer socket address to a router RLOC based on a given RLOC16.
Parameters
[in] aRloc16 The RLOC16 to use for peer address.
References Address::GetIid(), MessageInfo::GetPeerAddr(), InterfaceIdentifier::SetLocator(), MessageInfo::SetPeerAddr(), and MessageInfo::SetSockAddrToRloc().
Referenced by AddressResolver::AddressResolver(), AddressResolver::HandleAddressError(), PanIdQueryServer::SendConflict(), EnergyScanServer::SendReport(), and MessageInfo::SetSockPortToTmf().
SetSockAddrToRlocPeerAddrTo() [2/2]
void SetSockAddrToRlocPeerAddrTo (const Ip6::Address & aPeerAddress)
This method sets the local socket address to RLOC address and the peer socket address to a given address.
Parameters
[in] aPeerAddress The peer address.
References MessageInfo::SetPeerAddr(), and MessageInfo::SetSockAddrToRloc().
The documentation for this class was generated from the following files:
tmf.hpp
tmf.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale