OpenThread: Router::Info Class Reference
Router::Info Class Reference
#include <topology.hpp>
Public Member Functions
void SetFrom (const Router &aRouter)
void SetFrom (const Parent &aParent)
Public Member Functions inherited from Clearable< Info >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otRouterInfo
uint8_t mAge
Time last heard.
bool mAllocated: 1
Router ID allocated or not.
uint8_t mCslClockAccuracy
CSL clock accuracy, in ± ppm.
uint8_t mCslUncertainty
CSL uncertainty, in ±10 us.
otExtAddress mExtAddress
IEEE 802.15.4 Extended Address.
bool mLinkEstablished: 1
Link established with Router ID or not.
uint8_t mLinkQualityIn
Link Quality In.
uint8_t mLinkQualityOut
Link Quality Out.
uint8_t mNextHop
Next hop to router.
uint8_t mPathCost
Path cost to router.
uint16_t mRloc16
RLOC16.
uint8_t mRouterId
Router ID.
uint8_t mVersion
Thread version.
Detailed Description
This class represents diagnostic information for a Thread Router.
Member Function Documentation
SetFrom() [1/2]
void SetFrom (const Router & aRouter)
This method sets the Info instance from a given Router.
Parameters
[in] aRouter A router.
References ot::ClampToUint8(), Router::GetCost(), Neighbor::GetExtAddress(), Neighbor::GetLastHeard(), Neighbor::GetLinkInfo(), LinkQualityInfo::GetLinkQuality(), Router::GetLinkQualityOut(), Router::GetNextHop(), TimerMilli::GetNow(), Neighbor::GetRloc16(), Neighbor::GetVersion(), Neighbor::IsStateValid(), Neighbor::AddressMatcher::mExtAddress, Neighbor::mRloc16, Time::MsecToSec(), Neighbor::mVersion, and Mle::RouterIdFromRloc16().
Referenced by Mle::GetParentInfo().
SetFrom() [2/2]
void SetFrom (const Parent & aParent)
This method sets the Info instance from a given Parent.
Parameters
[in] aParent A parent.
The documentation for this class was generated from the following files:
topology.hpp
topology.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale