OpenThread: Tlv Class Reference
Tlv Class Reference
#include <meshcop_tlvs.hpp>
Public Types
enum Type : uint8_t {
kChannel = OT_MESHCOP_TLV_CHANNEL, kPanId = OT_MESHCOP_TLV_PANID, kExtendedPanId = OT_MESHCOP_TLV_EXTPANID, kNetworkName = OT_MESHCOP_TLV_NETWORKNAME,
kPskc = OT_MESHCOP_TLV_PSKC, kNetworkKey = OT_MESHCOP_TLV_NETWORKKEY, kNetworkKeySequence = OT_MESHCOP_TLV_NETWORK_KEY_SEQUENCE, kMeshLocalPrefix = OT_MESHCOP_TLV_MESHLOCALPREFIX,
kSteeringData = OT_MESHCOP_TLV_STEERING_DATA, kBorderAgentLocator = OT_MESHCOP_TLV_BORDER_AGENT_RLOC, kCommissionerId = OT_MESHCOP_TLV_COMMISSIONER_ID, kCommissionerSessionId = OT_MESHCOP_TLV_COMM_SESSION_ID,
kSecurityPolicy = OT_MESHCOP_TLV_SECURITYPOLICY, kGet = OT_MESHCOP_TLV_GET, kActiveTimestamp = OT_MESHCOP_TLV_ACTIVETIMESTAMP, kCommissionerUdpPort = OT_MESHCOP_TLV_COMMISSIONER_UDP_PORT,
kState = OT_MESHCOP_TLV_STATE, kJoinerDtlsEncapsulation = OT_MESHCOP_TLV_JOINER_DTLS, kJoinerUdpPort = OT_MESHCOP_TLV_JOINER_UDP_PORT, kJoinerIid = OT_MESHCOP_TLV_JOINER_IID,
kJoinerRouterLocator = OT_MESHCOP_TLV_JOINER_RLOC, kJoinerRouterKek = OT_MESHCOP_TLV_JOINER_ROUTER_KEK, kProvisioningUrl = OT_MESHCOP_TLV_PROVISIONING_URL, kVendorName = OT_MESHCOP_TLV_VENDOR_NAME_TLV,
kVendorModel = OT_MESHCOP_TLV_VENDOR_MODEL_TLV, kVendorSwVersion = OT_MESHCOP_TLV_VENDOR_SW_VERSION_TLV, kVendorData = OT_MESHCOP_TLV_VENDOR_DATA_TLV, kVendorStackVersion = OT_MESHCOP_TLV_VENDOR_STACK_VERSION_TLV,
kUdpEncapsulation = OT_MESHCOP_TLV_UDP_ENCAPSULATION_TLV, kIp6Address = OT_MESHCOP_TLV_IPV6_ADDRESS_TLV, kPendingTimestamp = OT_MESHCOP_TLV_PENDINGTIMESTAMP, kDelayTimer = OT_MESHCOP_TLV_DELAYTIMER,
kChannelMask = OT_MESHCOP_TLV_CHANNELMASK, kCount = OT_MESHCOP_TLV_COUNT, kPeriod = OT_MESHCOP_TLV_PERIOD, kScanDuration = OT_MESHCOP_TLV_SCAN_DURATION,
kEnergyList = OT_MESHCOP_TLV_ENERGY_LIST, kDiscoveryRequest = OT_MESHCOP_TLV_DISCOVERYREQUEST, kDiscoveryResponse = OT_MESHCOP_TLV_DISCOVERYRESPONSE, kJoinerAdvertisement = OT_MESHCOP_TLV_JOINERADVERTISEMENT
}
Public Member Functions
Tlv * GetNext (void)
const Tlv * GetNext (void) const
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Member Functions
static Error FindTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Tlv * FindTlv (uint8_t *aTlvsStart, uint16_t aTlvsLength, Type aType)
static const Tlv * FindTlv (const uint8_t *aTlvsStart, uint16_t aTlvsLength, Type aType)
template<typename TlvType >
static TlvType * FindTlv (uint8_t *aTlvsStart, uint16_t aTlvsLength)
template<typename TlvType >
static const TlvType * FindTlv (const uint8_t *aTlvsStart, uint16_t aTlvsLength)
static bool IsValid (const Tlv &aTlv)
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Additional Inherited Members
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements MeshCoP TLV generation and parsing.
Member Enumeration Documentation
Type
enum Type : uint8_t
MeshCoP TLV Types.
Enumerator
kChannel
Channel TLV.
kPanId
PAN ID TLV.
kExtendedPanId
Extended PAN ID TLV.
kNetworkName
Network Name TLV.
kPskc
PSKc TLV.
kNetworkKey
Network Network Key TLV.
kNetworkKeySequence
Network Key Sequence TLV.
kMeshLocalPrefix
Mesh Local Prefix TLV.
kSteeringData
Steering Data TLV.
kBorderAgentLocator
Border Agent Locator TLV.
kCommissionerId
Commissioner ID TLV.
kCommissionerSessionId
Commissioner Session ID TLV.
kSecurityPolicy
Security Policy TLV.
kGet
Get TLV.
kActiveTimestamp
Active Timestamp TLV.
kCommissionerUdpPort
Commissioner UDP Port TLV.
kState
State TLV.
kJoinerDtlsEncapsulation
Joiner DTLS Encapsulation TLV.
kJoinerUdpPort
Joiner UDP Port TLV.
kJoinerIid
Joiner IID TLV.
kJoinerRouterLocator
Joiner Router Locator TLV.
kJoinerRouterKek
Joiner Router KEK TLV.
kProvisioningUrl
Provisioning URL TLV.
kVendorName
meshcop Vendor Name TLV
kVendorModel
meshcop Vendor Model TLV
kVendorSwVersion
meshcop Vendor SW Version TLV
kVendorData
meshcop Vendor Data TLV
kVendorStackVersion
meshcop Vendor Stack Version TLV
kUdpEncapsulation
meshcop UDP encapsulation TLV
kIp6Address
meshcop IPv6 address TLV
kPendingTimestamp
Pending Timestamp TLV.
kDelayTimer
Delay Timer TLV.
kChannelMask
Channel Mask TLV.
kCount
Count TLV.
kPeriod
Period TLV.
kScanDuration
Scan Duration TLV.
kEnergyList
Energy List TLV.
kDiscoveryRequest
Discovery Request TLV.
kDiscoveryResponse
Discovery Response TLV.
kJoinerAdvertisement
Joiner Advertisement TLV.
Member Function Documentation
GetType()
Type GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Tlv::GetType().
Referenced by DiscoverScanner::HandleDiscoveryResponse(), DatasetManager::HandleGet(), DatasetManager::IsActiveDataset(), DatasetManager::IsPendingDataset(), Tlv::IsValid(), ProvisioningUrlTlv::IsValid(), and Dataset::SetTlv().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Tlv::SetType().
Referenced by ChannelTlv::Init(), PanIdTlv::Init(), ExtendedPanIdTlv::Init(), NetworkNameTlv::Init(), PskcTlv::Init(), NetworkKeyTlv::Init(), NetworkKeySequenceTlv::Init(), MeshLocalPrefixTlv::Init(), SteeringDataTlv::Init(), BorderAgentLocatorTlv::Init(), CommissionerIdTlv::Init(), CommissionerSessionIdTlv::Init(), SecurityPolicyTlv::Init(), ActiveTimestampTlv::Init(), StateTlv::Init(), JoinerUdpPortTlv::Init(), PendingTimestampTlv::Init(), DelayTimerTlv::Init(), ChannelMaskBaseTlv::Init(), ChannelMaskTlv::Init(), EnergyListTlv::Init(), ProvisioningUrlTlv::Init(), VendorNameTlv::Init(), VendorModelTlv::Init(), VendorSwVersionTlv::Init(), VendorDataTlv::Init(), VendorStackVersionTlv::Init(), UdpEncapsulationTlv::Init(), DiscoveryRequestTlv::Init(), DiscoveryResponseTlv::Init(), JoinerAdvertisementTlv::Init(), DatasetManager::SendGetRequest(), and Dataset::SetTlv().
GetNext() [1/2]
Tlv* GetNext (void) inline
This method returns a pointer to the next TLV.
Returns
A pointer to the next TLV.
References Tlv::GetNext().
Referenced by Tlv::FindTlv(), ChannelMaskTlv::GetChannelMask(), Dataset::IsValid(), ChannelMaskBaseTlv::IsValid(), DatasetManager::SendGetResponse(), and DatasetManager::SendSetRequest().
GetNext() [2/2]
const Tlv* GetNext (void) const inline
This method returns a pointer to the next TLV.
Returns
A pointer to the next TLV.
References Tlv::GetNext().
FindTlv() [1/6]
static Error FindTlv (const Message & aMessage, Type aType, uint16_t aMaxLength, Tlv & aTlv) inline static
This static method reads the requested TLV out of aMessage.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[in] aMaxLength Maximum number of bytes to read.
[out] aTlv A reference to the TLV that will be copied to.
Return values
kErrorNone Successfully copied the TLV.
kErrorNotFound Could not find the TLV with Type aType.
References Tlv::FindTlv().
Referenced by Tlv::FindTlv(), LeaderBase::GetCommissioningDataSubTlv(), Dataset::GetTlv(), and DatasetManager::HandleMgmtSetResponse().
FindTlv() [2/6]
static Error FindTlv (const Message & aMessage, TlvType & aTlv) inline static
This static method reads the requested TLV out of aMessage.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Template Parameters
TlvType The TlvType to search for (must be a sub-class of Tlv).
Parameters
[in] aMessage A reference to the message.
[out] aTlv A reference to the TLV that will be copied to.
Return values
kErrorNone Successfully copied the TLV.
kErrorNotFound Could not find the TLV with Type aType.
References Tlv::FindTlv(), and Tlv::IsValid().
IsValid()
bool IsValid (const Tlv & aTlv) static
This static method indicates whether a TLV appears to be well-formed.
Parameters
[in] aTlv A reference to the TLV.
Returns
TRUE if the TLV appears to be well-formed, FALSE otherwise.
References Tlv::GetType(), Tlv::kChannel, Tlv::kChannelMask, Tlv::kExtendedPanId, Tlv::kMeshLocalPrefix, Tlv::kNetworkKey, Tlv::kNetworkName, Tlv::kPanId, Tlv::kPskc, and Tlv::kSecurityPolicy.
Referenced by Tlv::FindTlv(), ChannelTlv::Init(), NetworkNameTlv::Init(), SecurityPolicyTlv::Init(), ChannelMaskBaseTlv::Init(), Dataset::IsValid(), and ChannelMaskBaseTlv::IsValid().
FindTlv() [3/6]
static Tlv* FindTlv (uint8_t * aTlvsStart, uint16_t aTlvsLength, Type aType) inline static
This static method searches in a given sequence of TLVs to find the first TLV with a given template Type.
Parameters
[in] aTlvsStart A pointer to the start of the sequence of TLVs to search within.
[in] aTlvsLength The length (number of bytes) in TLV sequence.
[in] aType The TLV Type to search for.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ot::AsConst(), ot::AsNonConst(), and Tlv::FindTlv().
FindTlv() [4/6]
const Tlv * FindTlv (const uint8_t * aTlvsStart, uint16_t aTlvsLength, Type aType) static
This static method searches in a given sequence of TLVs to find the first TLV with a given template Type.
Parameters
[in] aTlvsStart A pointer to the start of the sequence of TLVs to search within.
[in] aTlvsLength The length (number of bytes) in TLV sequence.
[in] aType The TLV Type to search for.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ExitNow, Tlv::GetNext(), Tlv::IsExtended(), and VerifyOrExit.
FindTlv() [5/6]
static TlvType* FindTlv (uint8_t * aTlvsStart, uint16_t aTlvsLength) inline static
This static template method searches in a given sequence of TLVs to find the first TLV with a give template TlvType.
Parameters
[in] aTlvsStart A pointer to the start of the sequence of TLVs to search within.
[in] aTlvsLength The length (number of bytes) in TLV sequence.
Returns
A pointer to the TLV if found, or nullptr if not found.
References Tlv::FindTlv().
FindTlv() [6/6]
static const TlvType* FindTlv (const uint8_t * aTlvsStart, uint16_t aTlvsLength) inline static
This static template method searches in a given sequence of TLVs to find the first TLV with a give template TlvType.
Parameters
[in] aTlvsStart A pointer to the start of the sequence of TLVs to search within.
[in] aTlvsLength The length (number of bytes) in TLV sequence.
Returns
A pointer to the TLV if found, or nullptr if not found.
References Tlv::FindTlv(), OT_TOOL_PACKED_BEGIN, and ot::MeshCoP::OT_TOOL_PACKED_END.
The documentation for this class was generated from the following files:
meshcop_tlvs.hpp
meshcop_tlvs.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale