OpenThread: Netif::ExternalMulticastAddress::Iterator Class Reference
Netif::ExternalMulticastAddress::Iterator Class Reference
#include <netif.hpp>
Data Structures
class Builder
Public Member Functions
Iterator (const Netif &aNetif, Address::TypeFilter aFilter=Address::kTypeAny)
Public Member Functions inherited from ItemPtrIterator< ExternalMulticastAddress, Iterator >
bool IsDone (void) const
bool operator!= (const Iterator &aOther) const
ExternalMulticastAddress & operator* (void)
void operator++ (void)
void operator++ (int)
ExternalMulticastAddress * operator-> (void)
bool operator== (const Iterator &aOther) const
Private Types
enum IteratorType : uint8_t { kEndIterator }
Private Member Functions
void Advance (void)
void AdvanceFrom (const MulticastAddress *aAddr)
Iterator (const Netif &aNetif, IteratorType)
Private Attributes
Address::TypeFilter mFilter
const Netif & mNetif
Friends
class ItemPtrIterator< ExternalMulticastAddress, Iterator >
class Netif
Additional Inherited Members
Protected Member Functions inherited from ItemPtrIterator< ExternalMulticastAddress, Iterator >
ItemPtrIterator (void)
ItemPtrIterator (ExternalMulticastAddress *item)
Protected Attributes inherited from ItemPtrIterator< ExternalMulticastAddress, Iterator >
ExternalMulticastAddress * mItem
Detailed Description
This class represents an iterator for iterating external multicast addresses in a Netif instance.
Member Enumeration Documentation
IteratorType
enum IteratorType : uint8_t private
Enumerator
kEndIterator
Constructor & Destructor Documentation
Iterator() [1/2]
Iterator (const Netif & aNetif, Address::TypeFilter aFilter = Address::kTypeAny) explicit
This constructor initializes an Iterator instance to start from the first external multicast address that matches a given IPv6 address type filter.
Parameters
[in] aNetif A reference to the Netif instance.
[in] aFilter The IPv6 address type filter.
References Netif::ExternalMulticastAddress::Iterator::AdvanceFrom(), Netif::GetMulticastAddresses(), and Netif::ExternalMulticastAddress::Iterator::mNetif.
Iterator() [2/2]
Iterator (const Netif & aNetif, IteratorType) inline private
Member Function Documentation
AdvanceFrom()
void AdvanceFrom (const MulticastAddress * aAddr) private
References ot::AsNonConst(), Netif::MulticastAddress::GetAddress(), Netif::MulticastAddress::GetNext(), Netif::IsMulticastAddressExternal(), Address::MatchesFilter(), Netif::ExternalMulticastAddress::Iterator::mFilter, ItemPtrIterator< ExternalMulticastAddress, Iterator >::mItem, and Netif::ExternalMulticastAddress::Iterator::mNetif.
Referenced by Netif::ExternalMulticastAddress::Iterator::Iterator().
Advance()
void Advance (void) inline private
Friends And Related Function Documentation
ItemPtrIterator< ExternalMulticastAddress, Iterator >
friend class ItemPtrIterator< ExternalMulticastAddress, Iterator > friend
Netif
friend class Netif friend
Field Documentation
mNetif
const Netif& mNetif private
Referenced by Netif::ExternalMulticastAddress::Iterator::AdvanceFrom(), and Netif::ExternalMulticastAddress::Iterator::Iterator().
mFilter
Address::TypeFilter mFilter private
Referenced by Netif::ExternalMulticastAddress::Iterator::AdvanceFrom().
The documentation for this class was generated from the following files:
netif.hpp
core/net/netif.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale