OpenThread: Netif::UnicastAddress Class Reference
Netif::UnicastAddress Class Reference
#include <netif.hpp>
Public Member Functions
const Address & GetAddress (void) const
Address & GetAddress (void)
AddressOrigin GetOrigin (void) const
uint8_t GetPrefixLength (void) const
uint8_t GetScope (void) const
bool HasPrefix (const Prefix &aPrefix) const
void InitAsSlaacOrigin (uint8_t aPrefixLength, bool aPreferred)
void InitAsThreadOrigin (bool aPreferred=false)
void InitAsThreadOriginGlobalScope (void)
void InitAsThreadOriginRealmLocalScope (void)
void SetScopeOverride (uint8_t aScope)
Public Member Functions inherited from LinkedListEntry< UnicastAddress >
const UnicastAddress * GetNext (void) const
UnicastAddress * GetNext (void)
void SetNext (UnicastAddress *aNext)
Public Member Functions inherited from Clearable< UnicastAddress >
void Clear (void)
Private Member Functions
bool Matches (const Address &aAddress) const
Friends
class LinkedList< UnicastAddress >
Additional Inherited Members
Data Fields inherited from otNetifAddress
otIp6Address mAddress
The IPv6 unicast address.
uint8_t mAddressOrigin
The IPv6 address origin.
struct otNetifAddress * mNext
A pointer to the next network interface address.
bool mPreferred: 1
TRUE if the address is preferred, FALSE otherwise.
uint8_t mPrefixLength
The Prefix length (in bits).
bool mRloc: 1
TRUE if the address is an RLOC, FALSE otherwise.
unsigned int mScopeOverride: 4
The IPv6 scope of this address.
bool mScopeOverrideValid: 1
TRUE if the mScopeOverride value is valid, FALSE otherwise.
bool mValid: 1
TRUE if the address is valid, FALSE otherwise.
Detailed Description
This class implements an IPv6 network interface unicast address.
Member Function Documentation
InitAsThreadOrigin()
void InitAsThreadOrigin (bool aPreferred = false)
This method clears and initializes the unicast address as a preferred, valid, thread-origin address with 64-bit prefix length.
Parameters
[in] aPreferred Whether to initialize as a preferred address.
References NetworkPrefix::kLength, and Netif::kOriginThread.
Referenced by Mle::Mle().
InitAsThreadOriginRealmLocalScope()
void InitAsThreadOriginRealmLocalScope (void)
This method clears and initializes the unicast address as a valid (but not preferred), thread-origin, realm-local scope (overridden) address with 64-bit prefix length.
References Address::kRealmLocalScope.
Referenced by Mle::Mle().
InitAsThreadOriginGlobalScope()
void InitAsThreadOriginGlobalScope (void)
This method clears and initializes the unicast address as a valid (but not preferred), thread-origin, global scope address.
References Address::kGlobalScope, and Netif::kOriginThread.
InitAsSlaacOrigin()
void InitAsSlaacOrigin (uint8_t aPrefixLength, bool aPreferred)
This method clears and initializes the unicast address as a valid, SLAAC-origin address with a given preferred flag and a given prefix length.
Parameters
[in] aPrefixLength The prefix length (in bits).
[in] aPreferred The preferred flag.
References Netif::kOriginSlaac.
GetAddress() [1/2]
const Address& GetAddress (void) const inline
This method returns the unicast address.
Returns
The unicast address.
References ot::AsCoreType(), and otNetifAddress::mAddress.
Referenced by Netif::AddExternalUnicastAddress(), Ip6::AddTunneledMplOption(), Mle::GetLinkLocalAddress(), Mle::GetLocatorAddress(), Mle::GetMeshLocal16(), Mle::GetMeshLocal64(), Mle::GetMeshLocalPrefix(), Netif::UnicastAddress::GetScope(), Mle::HandleNotifierEvents(), Netif::UnicastAddress::HasPrefix(), Netif::UnicastAddress::Matches(), Netif::MulticastAddress::Matches(), Mle::Mle(), otIp6SelectSourceAddress(), Mle::Restore(), Ip6::SendDatagram(), Mle::TxMessage::SendTo(), Mle::SetMeshLocalPrefix(), Mle::SetRloc16(), Mle::Store(), and Mle::UpdateLinkLocalAddress().
GetAddress() [2/2]
Address& GetAddress (void) inline
This method returns the unicast address.
Returns
The unicast address.
References ot::AsCoreType(), and otNetifAddress::mAddress.
GetPrefixLength()
uint8_t GetPrefixLength (void) const inline
This method returns the address's prefix length (in bits).
Returns
The prefix length (in bits).
References otNetifAddress::mPrefixLength.
HasPrefix()
bool HasPrefix (const Prefix & aPrefix) const inline
This method indicates whether the address has a given prefix (i.e. same prefix length and matches the prefix).
Parameters
[in] aPrefix A prefix to check against.
Return values
TRUE The address has and fully matches the aPrefix.
FALSE The address does not contain or match the aPrefix.
References Netif::UnicastAddress::GetAddress(), Prefix::GetLength(), Address::MatchesPrefix(), and otNetifAddress::mPrefixLength.
GetScope()
uint8_t GetScope (void) const inline
This method returns the IPv6 scope value.
Returns
The IPv6 scope value.
References Netif::UnicastAddress::GetAddress(), Address::GetScope(), otNetifAddress::mScopeOverride, and otNetifAddress::mScopeOverrideValid.
Referenced by Ip6::SelectSourceAddress().
SetScopeOverride()
void SetScopeOverride (uint8_t aScope) inline
This method sets the IPv6 scope override value.
Parameters
[in] aScope The IPv6 scope value.
References otNetifAddress::mScopeOverride, and otNetifAddress::mScopeOverrideValid.
GetOrigin()
AddressOrigin GetOrigin (void) const inline
This method gets the IPv6 address origin.
Returns
The address origin.
References otNetifAddress::mAddressOrigin.
Matches()
bool Matches (const Address & aAddress) const inline private
References Netif::UnicastAddress::GetAddress().
Friends And Related Function Documentation
LinkedList< UnicastAddress >
friend class LinkedList< UnicastAddress > friend
The documentation for this class was generated from the following files:
netif.hpp
core/net/netif.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale