OpenThread: BorderRouterEntry Class Reference
BorderRouterEntry Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Member Functions
uint16_t GetFlags (void) const
BorderRouterEntry * GetNext (void)
const BorderRouterEntry * GetNext (void) const
int8_t GetPreference (void) const
uint16_t GetRloc (void) const
void Init (void)
bool IsConfigure (void) const
bool IsDefaultRoute (void) const
bool IsDhcp (void) const
bool IsDp (void) const
bool IsNdDns (void) const
bool IsOnMesh (void) const
bool IsPreferred (void) const
bool IsSlaac (void) const
void SetFlags (uint16_t aFlags)
void SetRloc (uint16_t aRloc16)
Public Member Functions inherited from Equatable< BorderRouterEntry >
bool operator== (const BorderRouterEntry &aOther) const
Public Member Functions inherited from Unequatable< BorderRouterEntry >
bool operator!= (const BorderRouterEntry &aOther) const
Static Public Member Functions
static uint16_t FlagsWithoutPreference (uint16_t aFlags)
static int8_t PreferenceFromFlags (uint16_t aFlags)
Private Attributes
uint16_t mFlags
uint16_t mRloc
Static Private Attributes
static constexpr uint16_t kConfigureFlag = 1 << 10
static constexpr uint16_t kDefaultRouteFlag = 1 << 9
static constexpr uint16_t kDhcpFlag = 1 << 11
static constexpr uint16_t kDpFlag = 1 << 6
static constexpr uint16_t kNdDnsFlag = 1 << 7
static constexpr uint16_t kOnMeshFlag = 1 << 8
static constexpr uint16_t kPreferenceMask = 3 << kPreferenceOffset
static constexpr uint8_t kPreferenceOffset = 14
static constexpr uint16_t kPreferredFlag = 1 << 13
static constexpr uint16_t kSlaacFlag = 1 << 12
Friends
class OnMeshPrefixConfig
Detailed Description
This class implements Border Router Entry generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References ot::Mac::kShortAddrInvalid.
GetRloc()
uint16_t GetRloc (void) const inline
This method returns the RLOC16 value.
Returns
The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by LeaderBase::DefaultRouteLookup(), NetworkData::Iterate(), and OnMeshPrefixConfig::SetFrom().
SetRloc()
void SetRloc (uint16_t aRloc16) inline
This method sets the RLOC16 value.
Parameters
[in] aRloc16 The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
GetFlags()
uint16_t GetFlags (void) const inline
This method returns the Flags value.
Returns
The Flags value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by OnMeshPrefixConfig::SetFrom().
SetFlags()
void SetFlags (uint16_t aFlags) inline
This method sets the Flags value.
Parameters
[in] aFlags The Flags value.
References ot::Encoding::BigEndian::HostSwap16().
GetPreference()
int8_t GetPreference (void) const inline
This method returns the Preference value.
Returns
the Preference value.
Referenced by LeaderBase::DefaultRouteLookup().
IsPreferred()
bool IsPreferred (void) const inline
This method indicates whether or not the Preferred flag is set.
Return values
TRUE If the Preferred flag is set.
FALSE If the Preferred flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
IsSlaac()
bool IsSlaac (void) const inline
This method indicates whether or not the SLAAC flag is set.
Return values
TRUE If the SLAAC flag is set.
FALSE If the SLAAC flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
IsDhcp()
bool IsDhcp (void) const inline
This method indicates whether or not the DHCP flag is set.
Return values
TRUE If the DHCP flag is set.
FALSE If the DHCP flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
IsConfigure()
bool IsConfigure (void) const inline
This method indicates whether or not the Configure flag is set.
Return values
TRUE If the Configure flag is set.
FALSE If the Configure flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
IsDefaultRoute()
bool IsDefaultRoute (void) const inline
This method indicates whether or not the Default Route flag is set.
Return values
TRUE If the Default Route flag is set.
FALSE If the Default Route flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
IsOnMesh()
bool IsOnMesh (void) const inline
This method indicates whether or not the On-Mesh flag is set.
Return values
TRUE If the On-Mesh flag is set.
FALSE If the On-Mesh flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
IsNdDns()
bool IsNdDns (void) const inline
This method indicates whether or not the Nd-Dns flag is set.
Return values
TRUE If the Nd-Dns flag is set.
FALSE If the Nd-Dns flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
IsDp()
bool IsDp (void) const inline
This method indicates whether or not the Domain Prefix flag is set.
Return values
TRUE If the Domain Prefix flag is set.
FALSE If the Domain Prefix flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
GetNext() [1/2]
BorderRouterEntry* GetNext (void) inline
This method returns a pointer to the next BorderRouterEntry
Returns
A pointer to the next BorderRouterEntry.
Referenced by LeaderBase::DefaultRouteLookup(), LeaderBase::IsOnMesh(), and MutableNetworkData::RemoveTemporaryDataIn().
GetNext() [2/2]
const BorderRouterEntry* GetNext (void) const inline
This method returns a pointer to the next BorderRouterEntry
Returns
A pointer to the next BorderRouterEntry.
FlagsWithoutPreference()
static uint16_t FlagsWithoutPreference (uint16_t aFlags) inline static
This static method returns an updated flags bitmask by removing the preference bits (sets them to zero) from a given flags bitmask.
Parameters
[in] aFlags The flags bitmask.
Returns
An updated version aFlags with preference bits cleared.
PreferenceFromFlags()
static int8_t PreferenceFromFlags (uint16_t aFlags) inline static
This static method gets the preference field from a flags bitmask.
Parameters
[in] aFlags The flags.
Returns
The preference field from the aFlags.
References ot::NetworkData::RoutePreferenceFromValue().
Friends And Related Function Documentation
OnMeshPrefixConfig
friend class OnMeshPrefixConfig friend
Field Documentation
kPreferenceOffset
constexpr uint8_t kPreferenceOffset = 14 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kPreferenceMask
constexpr uint16_t kPreferenceMask = 3 << kPreferenceOffset static private
kPreferredFlag
constexpr uint16_t kPreferredFlag = 1 << 13 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kSlaacFlag
constexpr uint16_t kSlaacFlag = 1 << 12 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kDhcpFlag
constexpr uint16_t kDhcpFlag = 1 << 11 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kConfigureFlag
constexpr uint16_t kConfigureFlag = 1 << 10 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kDefaultRouteFlag
constexpr uint16_t kDefaultRouteFlag = 1 << 9 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kOnMeshFlag
constexpr uint16_t kOnMeshFlag = 1 << 8 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kNdDnsFlag
constexpr uint16_t kNdDnsFlag = 1 << 7 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
kDpFlag
constexpr uint16_t kDpFlag = 1 << 6 static private
Referenced by OnMeshPrefixConfig::SetFromTlvFlags().
mRloc
uint16_t mRloc private
mFlags
uint16_t mFlags private
The documentation for this class was generated from the following file:
network_data_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale