OpenThread: Udp::SocketHandle Class Reference
Udp::SocketHandle Class Reference
#include <udp6.hpp>
Public Member Functions
SockAddr & GetPeerName (void)
const SockAddr & GetPeerName (void) const
SockAddr & GetSockName (void)
const SockAddr & GetSockName (void) const
bool IsBound (void) const
Public Member Functions inherited from LinkedListEntry< SocketHandle >
const SocketHandle * GetNext (void) const
SocketHandle * GetNext (void)
void SetNext (SocketHandle *aNext)
Public Member Functions inherited from Clearable< SocketHandle >
void Clear (void)
Private Member Functions
void HandleUdpReceive (Message &aMessage, const MessageInfo &aMessageInfo)
bool Matches (const MessageInfo &aMessageInfo) const
Friends
class LinkedList< SocketHandle >
class Udp
Additional Inherited Members
Data Fields inherited from otUdpSocket
void * mContext
A pointer to application-specific context.
void * mHandle
A handle to platform's UDP.
otUdpReceive mHandler
A function pointer to the application callback.
struct otUdpSocket * mNext
A pointer to the next UDP socket (internal use only).
otSockAddr mPeerName
The peer IPv6 socket address.
otSockAddr mSockName
The local IPv6 socket address.
Detailed Description
This class implements a UDP/IPv6 socket.
Member Function Documentation
IsBound()
bool IsBound (void) const inline
This method indicates whether or not the socket is bound.
Return values
TRUE if the socket is bound (i.e. source port is non-zero).
FALSE if the socket is not bound (source port is zero).
References otSockAddr::mPort, and otUdpSocket::mSockName.
Referenced by Udp::Bind(), Udp::Connect(), Coap::Send(), Udp::SendTo(), Coap::Start(), and Coap::Stop().
GetSockName() [1/2]
SockAddr& GetSockName (void) inline
This method returns the local socket address.
Returns
A reference to the local socket address.
References ot::AsCoreType(), and otUdpSocket::mSockName.
Referenced by Udp::Close(), Udp::Connect(), Udp::SocketHandle::Matches(), Udp::Open(), and Udp::SendTo().
GetSockName() [2/2]
const SockAddr& GetSockName (void) const inline
This method returns the local socket address.
Returns
A reference to the local socket address.
References ot::AsCoreType(), and otUdpSocket::mSockName.
GetPeerName() [1/2]
SockAddr& GetPeerName (void) inline
This method returns the peer's socket address.
Returns
A reference to the peer's socket address.
References ot::AsCoreType(), and otUdpSocket::mPeerName.
Referenced by Udp::Close(), Udp::SocketHandle::Matches(), Udp::Open(), and Udp::SendTo().
GetPeerName() [2/2]
const SockAddr& GetPeerName (void) const inline
This method returns the peer's socket address.
Returns
A reference to the peer's socket address.
References ot::AsCoreType(), Udp::SocketHandle::Matches(), and otUdpSocket::mPeerName.
Matches()
bool Matches (const MessageInfo & aMessageInfo) const private
References SockAddr::GetAddress(), MessageInfo::GetPeerAddr(), Udp::SocketHandle::GetPeerName(), MessageInfo::GetPeerPort(), MessageInfo::GetSockAddr(), Udp::SocketHandle::GetSockName(), MessageInfo::GetSockPort(), Address::IsMulticast(), Address::IsUnspecified(), otSockAddr::mPort, and VerifyOrExit.
Referenced by Udp::SocketHandle::GetPeerName().
HandleUdpReceive()
void HandleUdpReceive (Message & aMessage, const MessageInfo & aMessageInfo) inline private
References otUdpSocket::mContext, and otUdpSocket::mHandler.
Referenced by Udp::HandlePayload().
Friends And Related Function Documentation
Udp
friend class Udp friend
LinkedList< SocketHandle >
friend class LinkedList< SocketHandle > friend
The documentation for this class was generated from the following files:
udp6.hpp
udp6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale