OpenThread: MaxPowerTable Class Reference
MaxPowerTable Class Reference
#include <max_power_table.hpp>
Public Member Functions
uint32_t GetSupportedChannelMask (void) const
int8_t GetTransmitPower (uint8_t aChannel) const
MaxPowerTable (void)
void SetTransmitPower (uint8_t aChannel, int8_t aPower)
Static Public Attributes
static constexpr int8_t kPowerDefault = 30
Default power 1 watt (30 dBm).
Private Attributes
int8_t mPowerTable [Radio::kChannelMax - Radio::kChannelMin+1]
Constructor & Destructor Documentation
MaxPowerTable()
MaxPowerTable (void) inline
References MaxPowerTable::mPowerTable.
Member Function Documentation
GetTransmitPower()
int8_t GetTransmitPower (uint8_t aChannel) const inline
This method gets the max allowed transmit power of channel aChannel.
Parameters
[in] aChannel The radio channel number.
Returns
The max supported transmit power in dBm.
References MaxPowerTable::mPowerTable.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
SetTransmitPower()
void SetTransmitPower (uint8_t aChannel, int8_t aPower) inline
This method sets the max allowed transmit power of channel aChannel.
Parameters
[in] aChannel The radio channel number.
[in] aPower The max supported transmit power in dBm.
References MaxPowerTable::mPowerTable.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::SetChannelMaxTransmitPower().
GetSupportedChannelMask()
uint32_t GetSupportedChannelMask (void) const inline
This method gets the supported channel masks.
References MaxPowerTable::mPowerTable, and OT_RADIO_POWER_INVALID.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetRadioChannelMask().
Field Documentation
kPowerDefault
constexpr int8_t kPowerDefault = 30 static
Default power 1 watt (30 dBm).
mPowerTable
int8_t mPowerTable[Radio::kChannelMax - Radio::kChannelMin+1] private
Referenced by MaxPowerTable::GetSupportedChannelMask(), MaxPowerTable::GetTransmitPower(), MaxPowerTable::MaxPowerTable(), and MaxPowerTable::SetTransmitPower().
The documentation for this class was generated from the following file:
max_power_table.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale