OpenThread: Key Class Reference
Key Class Reference
#include <storage.hpp>
Public Member Functions
const uint8_t * GetBytes (void) const
uint16_t GetLength (void) const
void Set (const uint8_t *aKeyBytes, uint16_t aKeyLength)
Public Member Functions inherited from Clearable< Key >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otCryptoKey
const uint8_t * mKey
Pointer to the buffer containing key. NULL indicates to use mKeyRef.
uint16_t mKeyLength
The key length in bytes (applicable when mKey is not NULL).
uint32_t mKeyRef
The PSA key ref (requires mKey to be NULL).
Detailed Description
This class represents a crypto key.
The Key can represent a literal key (i.e., a pointer to a byte array containing the key along with a key length) or a KeyRef (if OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE is enabled).
Member Function Documentation
Set()
void Set (const uint8_t * aKeyBytes, uint16_t aKeyLength) inline
This method sets the Key as a literal key from a given byte array and length.
Parameters
[in] aKeyBytes A pointer to buffer containing the key.
[in] aKeyLength The key length (number of bytes in akeyBytes).
Referenced by KeyManager::ComputeKeys(), KeyMaterial::ConvertToCryptoKey(), otPlatCryptoHkdfExpand(), otPlatCryptoHkdfExtract(), and AesCcm::SetKey().
GetBytes()
const uint8_t* GetBytes (void) const inline
This method gets the pointer to the bye array containing the key.
If OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE is enabled and IsKeyRef() returns true, then this method returns nullptr.
Returns
The pointer to the byte array containing the key, or nullptr if the Key represents a KeyRef
GetLength()
uint16_t GetLength (void) const inline
This method gets the key length (number of bytes).
If OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE is enabled and IsKeyRef() returns true, then this method returns zero.
Returns
The key length (number of bytes in the byte array from GetBytes()), or zero if Key represents a keyRef.
The documentation for this class was generated from the following file:
storage.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale