OpenThread: BorderRouterTlv Class Reference
BorderRouterTlv Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Member Functions
BorderRouterEntry * GetEntry (uint8_t aIndex)
const BorderRouterEntry * GetEntry (uint8_t aIndex) const
BorderRouterEntry * GetFirstEntry (void)
const BorderRouterEntry * GetFirstEntry (void) const
BorderRouterEntry * GetLastEntry (void)
const BorderRouterEntry * GetLastEntry (void) const
uint8_t GetNumEntries (void) const
void Init (void)
Public Member Functions inherited from NetworkDataTlv
void ClearStable (void)
void DecreaseLength (uint8_t aDecrement)
uint8_t GetLength (void) const
NetworkDataTlv * GetNext (void)
const NetworkDataTlv * GetNext (void) const
uint8_t GetSize (void) const
Type GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
void IncreaseLength (uint8_t aIncrement)
void Init (void)
bool IsStable (void) const
void SetLength (uint8_t aLength)
void SetStable (void)
void SetType (Type aType)
Static Public Attributes
static constexpr Type kType = kTypeBorderRouter
The TLV Type.
Additional Inherited Members
Public Types inherited from NetworkDataTlv
enum Type : uint8_t {
kTypeHasRoute = 0, kTypePrefix = 1, kTypeBorderRouter = 2, kTypeContext = 3,
kTypeCommissioningData = 4, kTypeService = 5, kTypeServer = 6
}
Static Public Member Functions inherited from NetworkDataTlv
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType, bool aStable)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType, bool aStable)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, bool aStable)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, bool aStable)
Detailed Description
This class implements Border Router TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References NetworkDataTlv::Init(), NetworkDataTlv::kTypeBorderRouter, NetworkDataTlv::SetLength(), and NetworkDataTlv::SetType().
GetNumEntries()
uint8_t GetNumEntries (void) const inline
This method returns the number of Border Router entries.
Returns
The number of Border Router entries.
References NetworkDataTlv::GetLength().
Referenced by NetworkData::Iterate().
GetEntry() [1/2]
BorderRouterEntry* GetEntry (uint8_t aIndex) inline
This method returns a pointer to the Border Router entry at a given index
Parameters
[in] aIndex The index.
Returns
A pointer to the Border Router entry at aIndex.
References NetworkDataTlv::GetValue().
Referenced by NetworkData::Iterate().
GetEntry() [2/2]
const BorderRouterEntry* GetEntry (uint8_t aIndex) const inline
This method returns a pointer to the Border Router entry at a given index.
Parameters
[in] aIndex The index.
Returns
A pointer to the Border Router entry at aIndex
References NetworkDataTlv::GetValue().
GetFirstEntry() [1/2]
BorderRouterEntry* GetFirstEntry (void) inline
This method returns a pointer to the first BorderRouterEntry (at index 0'th).
Returns
A pointer to the first BorderRouterEntry.
References NetworkDataTlv::GetValue().
Referenced by LeaderBase::DefaultRouteLookup(), LeaderBase::IsOnMesh(), and MutableNetworkData::RemoveTemporaryDataIn().
GetFirstEntry() [2/2]
const BorderRouterEntry* GetFirstEntry (void) const inline
This method returns a pointer to the first BorderRouterEntry (at index 0'th).
Returns
A pointer to the first BorderRouterEntry.
References NetworkDataTlv::GetValue().
GetLastEntry() [1/2]
BorderRouterEntry* GetLastEntry (void) inline
This method returns a pointer to the last BorderRouterEntry.
If there are no entries the pointer will be invalid but guaranteed to be before the GetFirstEntry() pointer.
Returns
A pointer to the last BorderRouterEntry.
References NetworkDataTlv::GetLength(), and NetworkDataTlv::GetValue().
Referenced by LeaderBase::DefaultRouteLookup(), LeaderBase::IsOnMesh(), and MutableNetworkData::RemoveTemporaryDataIn().
GetLastEntry() [2/2]
const BorderRouterEntry* GetLastEntry (void) const inline
This method returns a pointer to the last BorderRouterEntry.
If there are no entries the pointer will be invalid but guaranteed to be before the GetFirstEntry() pointer.
Returns
A pointer to the last BorderRouterEntry.
References NetworkDataTlv::GetLength(), NetworkDataTlv::GetValue(), OT_TOOL_PACKED_BEGIN, and ot::NetworkData::OT_TOOL_PACKED_END.
Field Documentation
kType
constexpr Type kType = kTypeBorderRouter static
The TLV Type.
The documentation for this class was generated from the following file:
network_data_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale