OpenThread: EnergyScanServer Class Reference
EnergyScanServer Class Reference
#include <energy_scan_server.hpp>
Public Member Functions
EnergyScanServer (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void HandleNotifierEvents (Events aEvents)
void HandleRequest (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleScanResult (Mac::EnergyScanResult *aResult)
void HandleTimer (void)
void SendReport (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleRequest (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleScanResult (Mac::EnergyScanResult *aResult, void *aContext)
static void HandleTimer (Timer &aTimer)
Private Attributes
bool mActive
uint32_t mChannelMask
uint32_t mChannelMaskCurrent
Ip6::Address mCommissioner
uint8_t mCount
Coap::Resource mEnergyScan
uint16_t mPeriod
uint16_t mScanDuration
int8_t mScanResults [OPENTHREAD_CONFIG_TMF_ENERGY_SCAN_MAX_RESULTS]
uint8_t mScanResultsLength
TimerMilli mTimer
Static Private Attributes
static constexpr uint32_t kReportDelay = 500
Delay before sending a report (milliseconds)
static constexpr uint32_t kScanDelay = 1000
SCAN_DELAY (milliseconds)
Friends
class ot::Notifier
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements handling Energy Scan Requests.
Constructor & Destructor Documentation
EnergyScanServer()
EnergyScanServer (Instance & aInstance) explicit
This constructor initializes the object.
References EnergyScanServer::mEnergyScan.
Member Function Documentation
HandleRequest() [1/2]
void HandleRequest (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References ot::AsCoapMessage(), ot::AsCoreType(), and EnergyScanServer::HandleRequest().
Referenced by EnergyScanServer::HandleRequest().
HandleRequest() [2/2]
void HandleRequest (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ChannelMaskTlv::GetChannelMask(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Message::IsConfirmable(), Address::IsMulticast(), Message::IsPostRequest(), EnergyScanServer::kScanDelay, LogInfo, EnergyScanServer::mActive, EnergyScanServer::mChannelMask, EnergyScanServer::mChannelMaskCurrent, EnergyScanServer::mCommissioner, EnergyScanServer::mCount, EnergyScanServer::mPeriod, EnergyScanServer::mScanDuration, EnergyScanServer::mScanResultsLength, EnergyScanServer::mTimer, TimerMilli::Start(), SuccessOrExit, and VerifyOrExit.
HandleScanResult() [1/2]
void HandleScanResult (Mac::EnergyScanResult * aResult, void * aContext) static private
Referenced by EnergyScanServer::HandleTimer().
HandleScanResult() [2/2]
void HandleScanResult (Mac::EnergyScanResult * aResult) private
References EnergyScanServer::kReportDelay, EnergyScanServer::mActive, EnergyScanServer::mChannelMask, EnergyScanServer::mChannelMaskCurrent, EnergyScanServer::mCount, otEnergyScanResult::mMaxRssi, EnergyScanServer::mPeriod, EnergyScanServer::mScanResults, EnergyScanServer::mScanResultsLength, EnergyScanServer::mTimer, OPENTHREAD_CONFIG_TMF_ENERGY_SCAN_MAX_RESULTS, TimerMilli::Start(), and VerifyOrExit.
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and EnergyScanServer::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References EnergyScanServer::HandleScanResult(), IgnoreError(), EnergyScanServer::mActive, EnergyScanServer::mChannelMaskCurrent, EnergyScanServer::mCount, EnergyScanServer::mScanDuration, EnergyScanServer::SendReport(), and VerifyOrExit.
Referenced by EnergyScanServer::HandleTimer().
HandleNotifierEvents()
void HandleNotifierEvents (Events aEvents) private
References Events::Contains(), ot::kEventThreadNetdataChanged, EnergyScanServer::mActive, EnergyScanServer::mTimer, and TimerMilli::Stop().
SendReport()
void SendReport (void) private
References Message::Append(), Message::AppendBytes(), Tlv::AppendTo(), FreeMessageOnError, InstanceLocator::GetInstance(), ChannelMaskTlv::Init(), EnergyListTlv::Init(), UriPath::kEnergyReport, ot::kErrorNoBufs, ot::kErrorNone, ot::MeshCoP::LogError(), LogInfo, EnergyScanServer::mActive, EnergyScanServer::mChannelMask, EnergyScanServer::mCommissioner, EnergyScanServer::mScanResults, EnergyScanServer::mScanResultsLength, ChannelMaskTlv::SetChannelMask(), Tlv::SetLength(), MessageInfo::SetSockAddrToRlocPeerAddrTo(), SuccessOrExit, and VerifyOrExit.
Referenced by EnergyScanServer::HandleTimer().
Friends And Related Function Documentation
ot::Notifier
friend class ot::Notifier friend
Field Documentation
kScanDelay
constexpr uint32_t kScanDelay = 1000 static private
SCAN_DELAY (milliseconds)
Referenced by EnergyScanServer::HandleRequest().
kReportDelay
constexpr uint32_t kReportDelay = 500 static private
Delay before sending a report (milliseconds)
Referenced by EnergyScanServer::HandleScanResult().
mCommissioner
Ip6::Address mCommissioner private
Referenced by EnergyScanServer::HandleRequest(), and EnergyScanServer::SendReport().
mChannelMask
uint32_t mChannelMask private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::SendReport().
mChannelMaskCurrent
uint32_t mChannelMaskCurrent private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::HandleTimer().
mPeriod
uint16_t mPeriod private
Referenced by EnergyScanServer::HandleRequest(), and EnergyScanServer::HandleScanResult().
mScanDuration
uint16_t mScanDuration private
Referenced by EnergyScanServer::HandleRequest(), and EnergyScanServer::HandleTimer().
mCount
uint8_t mCount private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::HandleTimer().
mActive
bool mActive private
Referenced by EnergyScanServer::HandleNotifierEvents(), EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), EnergyScanServer::HandleTimer(), and EnergyScanServer::SendReport().
mScanResults
int8_t mScanResults[OPENTHREAD_CONFIG_TMF_ENERGY_SCAN_MAX_RESULTS] private
Referenced by EnergyScanServer::HandleScanResult(), and EnergyScanServer::SendReport().
mScanResultsLength
uint8_t mScanResultsLength private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::SendReport().
mTimer
TimerMilli mTimer private
Referenced by EnergyScanServer::HandleNotifierEvents(), EnergyScanServer::HandleRequest(), and EnergyScanServer::HandleScanResult().
mEnergyScan
Coap::Resource mEnergyScan private
Referenced by EnergyScanServer::EnergyScanServer().
The documentation for this class was generated from the following files:
energy_scan_server.hpp
energy_scan_server.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale