OpenThread: Question Class Reference
Question Class Reference
Core-dns
#include <dns_types.hpp>
Public Member Functions
uint16_t GetClass (void) const
uint16_t GetType (void) const
Question (void)=default
Question (uint16_t aType, uint16_t aClass=ResourceRecord::kClassInternet)
void SetClass (uint16_t aClass)
void SetType (uint16_t aType)
Private Attributes
uint16_t mClass
uint16_t mType
Detailed Description
This class implements Question format.
Constructor & Destructor Documentation
Question() [1/2]
Question (void) default
Default constructor for Question
Question() [2/2]
Question (uint16_t aType, uint16_t aClass = ResourceRecord::kClassInternet) inline explicit
Constructor for Question.
References Header::SetType().
Member Function Documentation
GetType()
uint16_t GetType (void) const inline
This method returns the type of the question.
Returns
The type of the question.
References ot::Encoding::BigEndian::HostSwap16().
SetType()
void SetType (uint16_t aType) inline
This method sets the type of the question.
Parameters
[in] aType The type of the question.
References ot::Encoding::BigEndian::HostSwap16().
GetClass()
uint16_t GetClass (void) const inline
This method returns the class of the question.
Returns
The class of the question.
References ot::Encoding::BigEndian::HostSwap16().
SetClass()
void SetClass (uint16_t aClass) inline
This method sets the class of the question.
Parameters
[in] aClass The class of the question.
References ot::Encoding::BigEndian::HostSwap16().
Field Documentation
mType
uint16_t mType private
mClass
uint16_t mClass private
The documentation for this class was generated from the following file:
dns_types.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale