OpenThread: Timestamp Class Reference
Timestamp Class Reference
#include <timestamp.hpp>
Public Member Functions
void AdvanceRandomTicks (void)
void ConvertTo (otTimestamp &aTimestamp) const
bool GetAuthoritative (void) const
uint64_t GetSeconds (void) const
uint16_t GetTicks (void) const
bool IsOrphanTimestamp (void) const
void SetAuthoritative (bool aAuthoritative)
void SetFromTimestamp (const otTimestamp &aTimestamp)
void SetSeconds (uint64_t aSeconds)
void SetTicks (uint16_t aTicks)
Public Member Functions inherited from Clearable< Timestamp >
void Clear (void)
Static Public Member Functions
static int Compare (const Timestamp *aFirst, const Timestamp *aSecond)
static int Compare (const Timestamp &aFirst, const Timestamp &aSecond)
Private Attributes
uint16_t mSeconds16
uint32_t mSeconds32
uint16_t mTicks
Static Private Attributes
static constexpr uint16_t kAuthoritativeMask = 1 << kAuthoritativeOffset
static constexpr uint8_t kAuthoritativeOffset = 0
static constexpr uint16_t kMaxRandomTicks = 0x7fff
static constexpr uint16_t kTicksMask = 0x7fff << kTicksOffset
static constexpr uint8_t kTicksOffset = 1
Detailed Description
This class implements Timestamp generation and parsing.
Member Function Documentation
ConvertTo()
void ConvertTo (otTimestamp & aTimestamp) const
This method converts the timestamp to otTimestamp.
References Timestamp::GetAuthoritative(), Timestamp::GetSeconds(), Timestamp::GetTicks(), otTimestamp::mAuthoritative, otTimestamp::mSeconds, and otTimestamp::mTicks.
Referenced by Dataset::Info::SetActiveTimestamp(), and Dataset::Info::SetPendingTimestamp().
SetFromTimestamp()
void SetFromTimestamp (const otTimestamp & aTimestamp)
This method sets the timestamp from otTimestamp.
References otTimestamp::mAuthoritative, otTimestamp::mSeconds, otTimestamp::mTicks, Timestamp::SetAuthoritative(), Timestamp::SetSeconds(), and Timestamp::SetTicks().
Referenced by Dataset::Info::GetActiveTimestamp(), and Dataset::Info::GetPendingTimestamp().
GetSeconds()
uint64_t GetSeconds (void) const inline
This method returns the Seconds value.
Returns
The Seconds value.
References ot::Encoding::BigEndian::HostSwap16(), ot::Encoding::BigEndian::HostSwap32(), Timestamp::mSeconds16, and Timestamp::mSeconds32.
Referenced by Timestamp::AdvanceRandomTicks(), Mle::TxMessage::AppendPendingTimestampTlv(), Timestamp::Compare(), Timestamp::ConvertTo(), Mle::HandleAnnounce(), and Timestamp::IsOrphanTimestamp().
SetSeconds()
void SetSeconds (uint64_t aSeconds) inline
This method sets the Seconds value.
Parameters
[in] aSeconds The Seconds value.
References ot::Encoding::BigEndian::HostSwap16(), ot::Encoding::BigEndian::HostSwap32(), Timestamp::mSeconds16, and Timestamp::mSeconds32.
Referenced by Timestamp::AdvanceRandomTicks(), and Timestamp::SetFromTimestamp().
GetTicks()
uint16_t GetTicks (void) const inline
This method returns the Ticks value.
Returns
The Ticks value.
References ot::Encoding::BigEndian::HostSwap16(), Timestamp::kTicksOffset, and Timestamp::mTicks.
Referenced by Timestamp::AdvanceRandomTicks(), Timestamp::Compare(), Timestamp::ConvertTo(), and Timestamp::IsOrphanTimestamp().
SetTicks()
void SetTicks (uint16_t aTicks) inline
This method sets the Ticks value.
Parameters
[in] aTicks The Ticks value.
References ot::Encoding::BigEndian::HostSwap16(), Timestamp::kTicksMask, Timestamp::kTicksOffset, and Timestamp::mTicks.
Referenced by Timestamp::AdvanceRandomTicks(), and Timestamp::SetFromTimestamp().
GetAuthoritative()
bool GetAuthoritative (void) const inline
This method returns the Authoritative value.
Returns
The Authoritative value.
References ot::Encoding::BigEndian::HostSwap16(), Timestamp::kAuthoritativeMask, and Timestamp::mTicks.
Referenced by Timestamp::Compare(), Timestamp::ConvertTo(), and Timestamp::IsOrphanTimestamp().
SetAuthoritative()
void SetAuthoritative (bool aAuthoritative) inline
This method sets the Authoritative value.
Parameters
[in] aAuthoritative The Authoritative value.
References Timestamp::AdvanceRandomTicks(), ot::Encoding::BigEndian::HostSwap16(), Timestamp::kAuthoritativeMask, Timestamp::kAuthoritativeOffset, Timestamp::kTicksMask, and Timestamp::mTicks.
Referenced by Mle::SendAnnounce(), and Timestamp::SetFromTimestamp().
AdvanceRandomTicks()
void AdvanceRandomTicks (void)
This method increments the timestamp by a random number of ticks [0, 32767].
References Timestamp::GetSeconds(), Timestamp::GetTicks(), ot::Random::NonCrypto::GetUint32InRange(), Timestamp::kMaxRandomTicks, Timestamp::kTicksMask, Timestamp::kTicksOffset, Timestamp::SetSeconds(), and Timestamp::SetTicks().
Referenced by Timestamp::SetAuthoritative().
IsOrphanTimestamp()
bool IsOrphanTimestamp (void) const inline
This method indicates whether the timestamp indicates an MLE Orphan Announce message.
Return values
TRUE The timestamp indicates an Orphan Announce message.
FALSE If the timestamp does not indicate an Orphan Announce message.
References Timestamp::Compare(), Timestamp::GetAuthoritative(), Timestamp::GetSeconds(), and Timestamp::GetTicks().
Referenced by Mle::HandleAnnounce().
Compare() [1/2]
int Compare (const Timestamp * aFirst, const Timestamp * aSecond) static
This static method compares two timestamps.
Either one or both aFirst or aSecond can be nullptr. A non-null timestamp is considered greater than a null one. If both are null, they are considered as equal.
Parameters
[in] aFirst A pointer to the first timestamp to compare (can be nullptr).
[in] aSecond A pointer to the second timestamp to compare (can be nullptr).
Return values
-1 if aFirst is less than aSecond (aFirst < aSecond).
0 if aFirst is equal to aSecond (aFirst == aSecond).
1 if aFirst is greater than aSecond (aFirst > aSecond).
References ExitNow.
Referenced by Mle::HandleAnnounce(), Mle::HandleLeaderData(), Timestamp::IsOrphanTimestamp(), DatasetManager::Save(), and DatasetManager::SendSet().
Compare() [2/2]
int Compare (const Timestamp & aFirst, const Timestamp & aSecond) static
This static method compares two timestamps.
Parameters
[in] aFirst A reference to the first timestamp to compare.
[in] aSecond A reference to the second timestamp to compare.
Return values
-1 if aFirst is less than aSecond (aFirst < aSecond).
0 if aFirst is equal to aSecond (aFirst == aSecond).
1 if aFirst is greater than aSecond (aFirst > aSecond).
References ExitNow, Timestamp::GetAuthoritative(), Timestamp::GetSeconds(), and Timestamp::GetTicks().
Field Documentation
kTicksOffset
constexpr uint8_t kTicksOffset = 1 static private
Referenced by Timestamp::AdvanceRandomTicks(), Timestamp::GetTicks(), and Timestamp::SetTicks().
kTicksMask
constexpr uint16_t kTicksMask = 0x7fff << kTicksOffset static private
Referenced by Timestamp::AdvanceRandomTicks(), Timestamp::SetAuthoritative(), and Timestamp::SetTicks().
kMaxRandomTicks
constexpr uint16_t kMaxRandomTicks = 0x7fff static private
Referenced by Timestamp::AdvanceRandomTicks().
kAuthoritativeOffset
constexpr uint8_t kAuthoritativeOffset = 0 static private
Referenced by Timestamp::SetAuthoritative().
kAuthoritativeMask
constexpr uint16_t kAuthoritativeMask = 1 << kAuthoritativeOffset static private
Referenced by Timestamp::GetAuthoritative(), and Timestamp::SetAuthoritative().
mSeconds16
uint16_t mSeconds16 private
Referenced by Timestamp::GetSeconds(), and Timestamp::SetSeconds().
mSeconds32
uint32_t mSeconds32 private
Referenced by Timestamp::GetSeconds(), and Timestamp::SetSeconds().
mTicks
uint16_t mTicks private
Referenced by Timestamp::GetAuthoritative(), Timestamp::GetTicks(), Timestamp::SetAuthoritative(), and Timestamp::SetTicks().
The documentation for this class was generated from the following files:
timestamp.hpp
timestamp.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale