OpenThread: Timer::Scheduler Class Reference
Timer::Scheduler Class Reference
#include <timer.hpp>
Data Structures
struct AlarmApi
Protected Member Functions
void Add (Timer &aTimer, const AlarmApi &aAlarmApi)
void ProcessTimers (const AlarmApi &aAlarmApi)
void Remove (Timer &aTimer, const AlarmApi &aAlarmApi)
void RemoveAll (const AlarmApi &aAlarmApi)
Scheduler (Instance &aInstance)
void SetAlarm (const AlarmApi &aAlarmApi)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Protected Attributes
LinkedList< Timer > mTimerList
Friends
class Timer
Additional Inherited Members
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Constructor & Destructor Documentation
Scheduler()
Scheduler (Instance & aInstance) inline explicit protected
References Timer::Scheduler::Add(), Timer::Scheduler::ProcessTimers(), Timer::Scheduler::Remove(), Timer::Scheduler::RemoveAll(), and Timer::Scheduler::SetAlarm().
Member Function Documentation
Add()
void Add (Timer & aTimer, const AlarmApi & aAlarmApi) protected
References Timer::Scheduler::AlarmApi::AlarmGetNow, and Timer::DoesFireBefore().
Referenced by TimerMilli::Scheduler::Add(), and Timer::Scheduler::Scheduler().
Remove()
void Remove (Timer & aTimer, const AlarmApi & aAlarmApi) protected
References IgnoreError(), Timer::IsRunning(), LinkedListEntry< Type >::SetNext(), and VerifyOrExit.
Referenced by TimerMilli::Scheduler::Remove(), and Timer::Scheduler::Scheduler().
RemoveAll()
void RemoveAll (const AlarmApi & aAlarmApi) protected
References LinkedListEntry< Type >::SetNext().
Referenced by TimerMilli::GetNow(), TimerMilli::Scheduler::RemoveAll(), and Timer::Scheduler::Scheduler().
ProcessTimers()
void ProcessTimers (const AlarmApi & aAlarmApi) protected
References Timer::Scheduler::AlarmApi::AlarmGetNow, ExitNow, Timer::Fired(), and Timer::mFireTime.
Referenced by TimerMilli::Scheduler::ProcessTimers(), and Timer::Scheduler::Scheduler().
SetAlarm()
void SetAlarm (const AlarmApi & aAlarmApi) protected
References Timer::Scheduler::AlarmApi::AlarmGetNow, Timer::Scheduler::AlarmApi::AlarmStartAt, Timer::Scheduler::AlarmApi::AlarmStop, InstanceLocator::GetInstance(), and Timer::mFireTime.
Referenced by Timer::Scheduler::Scheduler().
Friends And Related Function Documentation
Timer
friend class Timer friend
Field Documentation
mTimerList
LinkedList<Timer> mTimerList protected
The documentation for this class was generated from the following files:
timer.hpp
timer.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale