OpenThread: Manager Class Reference
Manager Class Reference
#include <random.hpp>
Data Structures
class NonCryptoPrng
Public Member Functions
Manager (void)
~Manager (void)
Static Public Member Functions
static Error CryptoFillBuffer (uint8_t *aBuffer, uint16_t aSize)
static uint32_t NonCryptoGetUint32 (void)
Static Private Attributes
static uint16_t sInitCount = 0
static NonCryptoPrng sPrng
Additional Inherited Members
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Detailed Description
This class manages random number generator initialization/deinitialization.
Constructor & Destructor Documentation
Manager()
Manager (void)
This constructor initializes the object.
References ot::Random::Crypto::FillBuffer(), Manager::NonCryptoPrng::Init(), OT_ASSERT, otPlatCryptoRandomInit(), otPlatEntropyGet(), Manager::sInitCount, Manager::sPrng, SuccessOrAssert, and VerifyOrExit.
~Manager()
~Manager (void)
This destructor deinitializes the object.
References OT_ASSERT, otPlatCryptoRandomDeinit(), Manager::sInitCount, and VerifyOrExit.
Member Function Documentation
NonCryptoGetUint32()
uint32_t NonCryptoGetUint32 (void) static
This static method generates and returns a random value using a non-crypto Pseudo Random Number Generator.
Returns
A random uint32_t value.
References Manager::NonCryptoPrng::GetNext(), OT_ASSERT, Manager::sInitCount, and Manager::sPrng.
Referenced by ot::Random::NonCrypto::GetUint32().
CryptoFillBuffer()
static Error CryptoFillBuffer (uint8_t * aBuffer, uint16_t aSize) inline static
This static method fills a given buffer with cryptographically secure random bytes.
Parameters
[out] aBuffer A pointer to a buffer to fill with the random bytes.
[in] aSize Size of buffer (number of bytes to fill).
Return values
kErrorNone Successfully filled buffer with random values.
References otPlatCryptoRandomGet().
Referenced by ot::Random::Crypto::FillBuffer().
Field Documentation
sInitCount
uint16_t sInitCount = 0 static private
Referenced by Manager::Manager(), Manager::NonCryptoGetUint32(), and Manager::~Manager().
sPrng
Manager::NonCryptoPrng sPrng static private
Referenced by Manager::Manager(), and Manager::NonCryptoGetUint32().
The documentation for this class was generated from the following files:
random.hpp
random.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale