OpenThread: LinkQualityInfo Class Reference
LinkQualityInfo Class Reference
Core-link-quality
#include <link_quality.hpp>
Public Types
typedef String< kInfoStringSize > InfoString
Public Member Functions
void AddFrameTxStatus (bool aTxStatus)
void AddMessageTxStatus (bool aTxStatus)
void AddRss (int8_t aRss)
void Clear (void)
int8_t GetAverageRss (void) const
uint16_t GetAverageRssRaw (void) const
uint16_t GetFrameErrorRate (void) const
int8_t GetLastRss (void) const
uint8_t GetLinkMargin (void) const
LinkQuality GetLinkQuality (void) const
uint16_t GetMessageErrorRate (void) const
void Init (Instance &aInstance)
InfoString ToInfoString (void) const
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Member Functions
static LinkQuality ConvertLinkMarginToLinkQuality (uint8_t aLinkMargin)
static int8_t ConvertLinkQualityToRss (int8_t aNoiseFloor, LinkQuality aLinkQuality)
static uint8_t ConvertRssToLinkMargin (int8_t aNoiseFloor, int8_t aRss)
static LinkQuality ConvertRssToLinkQuality (int8_t aNoiseFloor, int8_t aRss)
Static Public Attributes
static constexpr uint16_t kInfoStringSize = 50
InfoString size (
Private Member Functions
void SetLinkQuality (LinkQuality aLinkQuality)
Static Private Member Functions
static LinkQuality CalculateLinkQuality (uint8_t aLinkMargin, uint8_t aLastLinkQuality)
Private Attributes
SuccessRateTracker mFrameErrorRate
int8_t mLastRss
LinkQuality mLinkQuality
SuccessRateTracker mMessageErrorRate
RssAverager mRssAverager
Static Private Attributes
static constexpr uint8_t kHysteresisThreshold = 2
static constexpr int8_t kLinkQuality0LinkMargin = 0
static constexpr int8_t kLinkQuality1LinkMargin = 5
static constexpr int8_t kLinkQuality2LinkMargin = 15
static constexpr int8_t kLinkQuality3LinkMargin = 50
static constexpr uint8_t kNoLinkQuality = 0xff
static constexpr uint8_t kThreshold1 = 2
static constexpr uint8_t kThreshold2 = 10
static constexpr uint8_t kThreshold3 = 20
Additional Inherited Members
Protected Member Functions inherited from InstanceLocatorInit
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class encapsulates/stores all relevant information about quality of a link, including average received signal strength (RSS), last RSS, link margin, and link quality.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToInfoString().
Member Function Documentation
Init()
void Init (Instance & aInstance) inline
This method initializes the LinkQualityInfo object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Clearable< SuccessRateTracker >::Clear(), and InstanceLocatorInit::Init().
Referenced by Neighbor::Init().
Clear()
void Clear (void)
This method clears the all the data in the object.
References ot::kLinkQuality0, and OT_RADIO_RSSI_INVALID.
Referenced by Mle::HandleParentResponse().
AddRss()
void AddRss (int8_t aRss)
This method adds a new received signal strength (RSS) value to the average.
Parameters
[in] aRss A new received signal strength value (in dBm) to be added to the average.
References OT_RADIO_RSSI_INVALID, SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleParentResponse().
GetAverageRss()
int8_t GetAverageRss (void) const inline
This method returns the current average received signal strength value.
Returns
The current average value or OT_RADIO_RSSI_INVALID if no average is available.
Referenced by Mle::CheckReachability(), and Neighbor::Info::SetFrom().
GetAverageRssRaw()
uint16_t GetAverageRssRaw (void) const inline
This method returns an encoded version of current average signal strength value. The encoded value is the average multiplied by a precision factor (currently -8).
Returns
The current average multiplied by precision factor or zero if no average is available.
ToInfoString()
LinkQualityInfo::InfoString ToInfoString (void) const
This method converts the link quality info to info/debug human-readable string.
Returns
An InfoString representing the link quality info.
References StringWriter::Append().
GetLinkMargin()
uint8_t GetLinkMargin (void) const
This method returns the link margin. The link margin is calculated using the link's current average received signal strength (RSS) and average noise floor.
Returns
Link margin derived from average received signal strength and average noise floor.
GetLinkQuality()
LinkQuality GetLinkQuality (void) const inline
Returns the current one-way link quality value. The link quality value is a number 0-3.
The link quality is calculated by comparing the current link margin with a set of thresholds (per Thread spec). More specifically, link margin > 20 dB gives link quality 3, link margin > 10 dB gives link quality 2, link margin > 2 dB gives link quality 1, and link margin below or equal to 2 dB yields link quality of 0.
In order to ensure that a link margin near the boundary of two different link quality values does not cause frequent changes, a hysteresis of 2 dB is applied when determining the link quality. For example, the average link margin must be at least 12 dB to change a quality 1 link to a quality 2 link.
Returns
The current link quality value (value 0-3 as per Thread specification).
Referenced by Mle::HasAcceptableParentCandidate(), Mle::IsBetterParent(), Neighbor::Info::SetFrom(), and Router::Info::SetFrom().
GetLastRss()
int8_t GetLastRss (void) const inline
Returns the most recent RSS value.
Returns
The most recent RSS
Referenced by Neighbor::Info::SetFrom().
AddFrameTxStatus()
void AddFrameTxStatus (bool aTxStatus) inline
This method adds a MAC frame transmission status (success/failure) and updates the frame tx error rate.
Parameters
[in] aTxStatus Success/Failure of MAC frame transmission (true -> success, false -> failure).
References OPENTHREAD_CONFIG_FRAME_TX_ERR_RATE_AVERAGING_WINDOW.
AddMessageTxStatus()
void AddMessageTxStatus (bool aTxStatus) inline
This method adds a message transmission status (success/failure) and updates the message error rate.
Parameters
[in] aTxStatus Success/Failure of message (true -> success, false -> message tx failed). A larger (IPv6) message may be fragmented and sent as multiple MAC frames. The message transmission is considered a failure, if any of its fragments fail after all MAC retry attempts.
References OPENTHREAD_CONFIG_IPV6_TX_ERR_RATE_AVERAGING_WINDOW.
Referenced by MeshForwarder::UpdateSendMessage().
GetFrameErrorRate()
uint16_t GetFrameErrorRate (void) const inline
This method returns the MAC frame transmission error rate for the link.
The rate is maintained over a window of (roughly) last OPENTHREAD_CONFIG_FRAME_TX_ERR_RATE_AVERAGING_WINDOW frame transmissions.
Returns
The error rate with maximum value 0xffff corresponding to 100% failure rate.
Referenced by Neighbor::Info::SetFrom().
GetMessageErrorRate()
uint16_t GetMessageErrorRate (void) const inline
This method returns the message error rate for the link.
The rate is maintained over a window of (roughly) last OPENTHREAD_CONFIG_IPV6_TX_ERR_RATE_AVERAGING_WINDOW (IPv6) messages.
Note that a larger (IPv6) message can be fragmented and sent as multiple MAC frames. The message transmission is considered a failure, if any of its fragments fail after all MAC retry attempts.
Returns
The error rate with maximum value 0xffff corresponding to 100% failure rate.
Referenced by Neighbor::Info::SetFrom().
ConvertRssToLinkMargin()
uint8_t ConvertRssToLinkMargin (int8_t aNoiseFloor, int8_t aRss) static
This method converts a received signal strength value to a link margin value.
Parameters
[in] aNoiseFloor The noise floor value (in dBm).
[in] aRss The received signal strength value (in dBm).
Returns
The link margin value.
References OT_RADIO_RSSI_INVALID.
Referenced by Mle::HandleParentResponse().
ConvertLinkMarginToLinkQuality()
LinkQuality ConvertLinkMarginToLinkQuality (uint8_t aLinkMargin) static
This method converts a link margin value to a link quality value.
Parameters
[in] aLinkMargin The Link Margin in dB.
Returns
The link quality value (0-3).
Referenced by Mle::HandleParentResponse().
ConvertRssToLinkQuality()
LinkQuality ConvertRssToLinkQuality (int8_t aNoiseFloor, int8_t aRss) static
This method converts a received signal strength value to a link quality value.
Parameters
[in] aNoiseFloor The noise floor value (in dBm).
[in] aRss The received signal strength value (in dBm).
Returns
The link quality value (0-3).
Referenced by otLinkConvertRssToLinkQuality().
ConvertLinkQualityToRss()
int8_t ConvertLinkQualityToRss (int8_t aNoiseFloor, LinkQuality aLinkQuality) static
This method converts a link quality value to a typical received signal strength value.
Note
only for test.
Parameters
[in] aNoiseFloor The noise floor value (in dBm).
[in] aLinkQuality The link quality value in [0, 3].
Returns
The typical platform RSSI.
References ot::kLinkQuality1, ot::kLinkQuality2, and ot::kLinkQuality3.
Referenced by otLinkConvertLinkQualityToRss().
SetLinkQuality()
void SetLinkQuality (LinkQuality aLinkQuality) inline private
CalculateLinkQuality()
LinkQuality CalculateLinkQuality (uint8_t aLinkMargin, uint8_t aLastLinkQuality) static private
References ot::kLinkQuality0, ot::kLinkQuality1, ot::kLinkQuality2, ot::kLinkQuality3, and OT_FALL_THROUGH.
Field Documentation
kInfoStringSize
constexpr uint16_t kInfoStringSize = 50 static
InfoString size (
See also
ToInfoString()).
kThreshold3
constexpr uint8_t kThreshold3 = 20 static private
kThreshold2
constexpr uint8_t kThreshold2 = 10 static private
kThreshold1
constexpr uint8_t kThreshold1 = 2 static private
kHysteresisThreshold
constexpr uint8_t kHysteresisThreshold = 2 static private
kLinkQuality3LinkMargin
constexpr int8_t kLinkQuality3LinkMargin = 50 static private
kLinkQuality2LinkMargin
constexpr int8_t kLinkQuality2LinkMargin = 15 static private
kLinkQuality1LinkMargin
constexpr int8_t kLinkQuality1LinkMargin = 5 static private
kLinkQuality0LinkMargin
constexpr int8_t kLinkQuality0LinkMargin = 0 static private
kNoLinkQuality
constexpr uint8_t kNoLinkQuality = 0xff static private
mRssAverager
RssAverager mRssAverager private
mLinkQuality
LinkQuality mLinkQuality private
mLastRss
int8_t mLastRss private
mFrameErrorRate
SuccessRateTracker mFrameErrorRate private
mMessageErrorRate
SuccessRateTracker mMessageErrorRate private
The documentation for this class was generated from the following files:
link_quality.hpp
link_quality.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale