OpenThread: SettingsBase::NetworkInfo Class Reference
SettingsBase::NetworkInfo Class Reference
#include <settings.hpp>
Public Member Functions
uint8_t GetDeviceMode (void) const
const Mac::ExtAddress & GetExtAddress (void) const
uint32_t GetKeySequence (void) const
uint32_t GetMacFrameCounter (void) const
const Ip6::InterfaceIdentifier & GetMeshLocalIid (void) const
uint32_t GetMleFrameCounter (void) const
uint32_t GetPreviousPartitionId (void) const
uint16_t GetRloc16 (void) const
uint8_t GetRole (void) const
uint16_t GetVersion (void) const
void Init (void)
void SetDeviceMode (uint8_t aDeviceMode)
void SetExtAddress (const Mac::ExtAddress &aExtAddress)
void SetKeySequence (uint32_t aKeySequence)
void SetMacFrameCounter (uint32_t aMacFrameCounter)
void SetMeshLocalIid (const Ip6::InterfaceIdentifier &aMeshLocalIid)
void SetMleFrameCounter (uint32_t aMleFrameCounter)
void SetPreviousPartitionId (uint32_t aPreviousPartitionId)
void SetRloc16 (uint16_t aRloc16)
void SetRole (uint8_t aRole)
void SetVersion (uint16_t aVersion)
Static Public Attributes
static constexpr Key kKey = kKeyNetworkInfo
The associated key.
Private Member Functions
void Log (Action aAction) const
Private Member Functions inherited from Clearable< NetworkInfo >
void Clear (void)
Private Attributes
uint8_t mDeviceMode
Device mode setting.
Mac::ExtAddress mExtAddress
Extended Address.
uint32_t mKeySequence
Key Sequence.
uint32_t mMacFrameCounter
MAC Frame Counter.
uint32_t mMleFrameCounter
MLE Frame Counter.
Ip6::InterfaceIdentifier mMlIid
IID from ML-EID.
uint32_t mPreviousPartitionId
PartitionId.
uint16_t mRloc16
RLOC16.
uint8_t mRole
Current Thread role.
uint16_t mVersion
Version.
Friends
class Settings
Detailed Description
This structure represents the device's own network information for settings storage.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the NetworkInfo object.
References Clearable< NetworkInfo >::Clear(), ot::kThreadVersion1p1, and SettingsBase::NetworkInfo::SetVersion().
Referenced by Settings::Init(), Settings::Settings(), and Mle::Store().
GetRole()
uint8_t GetRole (void) const inline
This method returns the Thread role.
Returns
The Thread role.
References SettingsBase::NetworkInfo::mRole.
Referenced by Mle::Restore().
SetRole()
void SetRole (uint8_t aRole) inline
This method sets the Thread role.
Parameters
[in] aRole The Thread Role.
References SettingsBase::NetworkInfo::mRole.
Referenced by Mle::Store().
GetDeviceMode()
uint8_t GetDeviceMode (void) const inline
This method returns the Thread device mode.
Returns
the Thread device mode.
References SettingsBase::NetworkInfo::mDeviceMode.
Referenced by Mle::Restore().
SetDeviceMode()
void SetDeviceMode (uint8_t aDeviceMode) inline
This method sets the Thread device mode.
Parameters
[in] aDeviceMode The Thread device mode.
References SettingsBase::NetworkInfo::mDeviceMode.
Referenced by Mle::Store().
GetRloc16()
uint16_t GetRloc16 (void) const inline
This method returns the RLOC16.
Returns
The RLOC16.
References ot::Encoding::LittleEndian::HostSwap16(), and SettingsBase::NetworkInfo::mRloc16.
Referenced by Mle::Restore().
SetRloc16()
void SetRloc16 (uint16_t aRloc16) inline
This method sets the RLOC16.
Parameters
[in] aRloc16 The RLOC16.
References ot::Encoding::LittleEndian::HostSwap16(), and SettingsBase::NetworkInfo::mRloc16.
Referenced by Mle::Store().
GetKeySequence()
uint32_t GetKeySequence (void) const inline
This method returns the key sequence.
Returns
The key sequence.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mKeySequence.
Referenced by Mle::Restore().
SetKeySequence()
void SetKeySequence (uint32_t aKeySequence) inline
This method sets the key sequence.
Parameters
[in] aKeySequence The key sequence.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mKeySequence.
Referenced by Mle::Store().
GetMleFrameCounter()
uint32_t GetMleFrameCounter (void) const inline
This method returns the MLE frame counter.
Returns
The MLE frame counter.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mMleFrameCounter.
Referenced by Mle::Restore(), and Mle::Store().
SetMleFrameCounter()
void SetMleFrameCounter (uint32_t aMleFrameCounter) inline
This method sets the MLE frame counter.
Parameters
[in] aMleFrameCounter The MLE frame counter.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mMleFrameCounter.
Referenced by Mle::Store().
GetMacFrameCounter()
uint32_t GetMacFrameCounter (void) const inline
This method returns the MAC frame counter.
Returns
The MAC frame counter.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mMacFrameCounter.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), Mle::Restore(), and Mle::Store().
SetMacFrameCounter()
void SetMacFrameCounter (uint32_t aMacFrameCounter) inline
This method sets the MAC frame counter.
Parameters
[in] aMacFrameCounter The MAC frame counter.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mMacFrameCounter.
Referenced by Mle::Store().
GetPreviousPartitionId()
uint32_t GetPreviousPartitionId (void) const inline
This method returns the previous partition ID.
Returns
The previous partition ID.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mPreviousPartitionId.
Referenced by Mle::Restore().
SetPreviousPartitionId()
void SetPreviousPartitionId (uint32_t aPreviousPartitionId) inline
This method sets the previous partition id.
Parameters
[in] aPreviousPartitionId The previous partition ID.
References ot::Encoding::LittleEndian::HostSwap32(), and SettingsBase::NetworkInfo::mPreviousPartitionId.
Referenced by Mle::Store().
GetExtAddress()
const Mac::ExtAddress& GetExtAddress (void) const inline
This method returns the extended address.
Returns
The extended address.
References SettingsBase::NetworkInfo::mExtAddress.
Referenced by Mle::Restore().
SetExtAddress()
void SetExtAddress (const Mac::ExtAddress & aExtAddress) inline
This method sets the extended address.
Parameters
[in] aExtAddress The extended address.
References SettingsBase::NetworkInfo::mExtAddress.
Referenced by Mle::Store().
GetMeshLocalIid()
const Ip6::InterfaceIdentifier& GetMeshLocalIid (void) const inline
This method returns the Mesh Local Interface Identifier.
Returns
The Mesh Local Interface Identifier.
References SettingsBase::NetworkInfo::mMlIid.
Referenced by Mle::Restore().
SetMeshLocalIid()
void SetMeshLocalIid (const Ip6::InterfaceIdentifier & aMeshLocalIid) inline
This method sets the Mesh Local Interface Identifier.
Parameters
[in] aMeshLocalIid The Mesh Local Interface Identifier.
References SettingsBase::NetworkInfo::mMlIid.
Referenced by Mle::Store().
GetVersion()
uint16_t GetVersion (void) const inline
This method returns the Thread version.
Returns
The Thread version.
References ot::Encoding::LittleEndian::HostSwap16(), and SettingsBase::NetworkInfo::mVersion.
Referenced by Mle::Restore().
SetVersion()
void SetVersion (uint16_t aVersion) inline
This method sets the Thread version.
Parameters
[in] aVersion The Thread version.
References ot::Encoding::LittleEndian::HostSwap16(), SettingsBase::NetworkInfo::Log(), and SettingsBase::NetworkInfo::mVersion.
Referenced by SettingsBase::NetworkInfo::Init(), SettingsBase::ParentInfo::Init(), and Mle::Store().
Log()
void Log (Action aAction) const private
Referenced by Settings::Delete(), Settings::DeleteEntry(), Settings::DeleteOperationalDataset(), Settings::Log(), Settings::ReadEntry(), Settings::SaveEntry(), Settings::SaveOperationalDataset(), SettingsBase::NetworkInfo::SetVersion(), and SettingsBase::ParentInfo::SetVersion().
Friends And Related Function Documentation
Settings
friend class Settings friend
Field Documentation
kKey
constexpr Key kKey = kKeyNetworkInfo static
The associated key.
mRole
uint8_t mRole private
Current Thread role.
Referenced by SettingsBase::NetworkInfo::GetRole(), and SettingsBase::NetworkInfo::SetRole().
mDeviceMode
uint8_t mDeviceMode private
Device mode setting.
Referenced by SettingsBase::NetworkInfo::GetDeviceMode(), and SettingsBase::NetworkInfo::SetDeviceMode().
mRloc16
uint16_t mRloc16 private
RLOC16.
Referenced by SettingsBase::NetworkInfo::GetRloc16(), and SettingsBase::NetworkInfo::SetRloc16().
mKeySequence
uint32_t mKeySequence private
Key Sequence.
Referenced by SettingsBase::NetworkInfo::GetKeySequence(), and SettingsBase::NetworkInfo::SetKeySequence().
mMleFrameCounter
uint32_t mMleFrameCounter private
MLE Frame Counter.
Referenced by SettingsBase::NetworkInfo::GetMleFrameCounter(), and SettingsBase::NetworkInfo::SetMleFrameCounter().
mMacFrameCounter
uint32_t mMacFrameCounter private
MAC Frame Counter.
Referenced by SettingsBase::NetworkInfo::GetMacFrameCounter(), and SettingsBase::NetworkInfo::SetMacFrameCounter().
mPreviousPartitionId
uint32_t mPreviousPartitionId private
PartitionId.
Referenced by SettingsBase::NetworkInfo::GetPreviousPartitionId(), and SettingsBase::NetworkInfo::SetPreviousPartitionId().
mExtAddress
Mac::ExtAddress mExtAddress private
Extended Address.
Referenced by SettingsBase::NetworkInfo::GetExtAddress(), SettingsBase::ParentInfo::GetExtAddress(), SettingsBase::NetworkInfo::SetExtAddress(), and SettingsBase::ParentInfo::SetExtAddress().
mMlIid
Ip6::InterfaceIdentifier mMlIid private
IID from ML-EID.
Referenced by SettingsBase::NetworkInfo::GetMeshLocalIid(), and SettingsBase::NetworkInfo::SetMeshLocalIid().
mVersion
uint16_t mVersion private
Version.
Referenced by SettingsBase::NetworkInfo::GetVersion(), SettingsBase::ParentInfo::GetVersion(), SettingsBase::NetworkInfo::SetVersion(), and SettingsBase::ParentInfo::SetVersion().
The documentation for this class was generated from the following file:
core/common/settings.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale