OpenThread: Router Class Reference
Router Class Reference
#include <topology.hpp>
Data Structures
class Info
Public Member Functions
void Clear (void)
uint8_t GetCost (void) const
LinkQuality GetLinkQualityOut (void) const
uint8_t GetNextHop (void) const
void Init (Instance &aInstance)
void SetCost (uint8_t aCost)
void SetFrom (const Parent &aParent)
void SetLinkQualityOut (LinkQuality aLinkQuality)
void SetNextHop (uint8_t aRouterId)
Public Member Functions inherited from Neighbor
void ClearExtAddress (void)
void GenerateChallenge (void)
const uint8_t * GetChallenge (void) const
uint8_t GetChallengeSize (void) const
Mle::DeviceMode GetDeviceMode (void) const
const Mac::ExtAddress & GetExtAddress (void) const
uint32_t GetKeySequence (void) const
TimeMilli GetLastHeard (void) const
uint32_t GetLinkAckFrameCounter (void) const
uint8_t GetLinkFailures (void) const
Mac::LinkFrameCounters & GetLinkFrameCounters (void)
const Mac::LinkFrameCounters & GetLinkFrameCounters (void) const
LinkQualityInfo & GetLinkInfo (void)
const LinkQualityInfo & GetLinkInfo (void) const
uint32_t GetMleFrameCounter (void) const
NetworkData::Type GetNetworkDataType (void) const
uint16_t GetRloc16 (void) const
uint8_t GetRouterId (void) const
State GetState (void) const
uint16_t GetVersion (void) const
void IncrementLinkFailures (void)
bool IsEnhancedKeepAliveSupported (void) const
bool IsFullThreadDevice (void) const
bool IsRxOnWhenIdle (void) const
bool IsStateChildIdRequest (void) const
bool IsStateInvalid (void) const
bool IsStateLinkRequest (void) const
bool IsStateParentResponse (void) const
bool IsStateRestored (void) const
bool IsStateRestoring (void) const
bool IsStateValid (void) const
bool IsStateValidOrAttaching (void) const
bool IsStateValidOrRestoring (void) const
bool IsThreadVersion1p1 (void) const
bool IsThreadVersion1p2OrHigher (void) const
bool IsThreadVersionCslCapable (void) const
bool Matches (const AddressMatcher &aMatcher) const
bool MatchesFilter (StateFilter aFilter) const
void ResetLinkFailures (void)
void SetDeviceMode (Mle::DeviceMode aMode)
void SetExtAddress (const Mac::ExtAddress &aAddress)
void SetKeySequence (uint32_t aKeySequence)
void SetLastHeard (TimeMilli aLastHeard)
void SetLinkAckFrameCounter (uint32_t aAckFrameCounter)
void SetMleFrameCounter (uint32_t aFrameCounter)
void SetRloc16 (uint16_t aRloc16)
void SetState (State aState)
void SetVersion (uint16_t aVersion)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Attributes
uint8_t mCost: 4
The cost to this router via neighbor router.
uint8_t mLinkQualityOut: 2
The link quality out for this router.
uint8_t mNextHop
The next hop towards this router.
Additional Inherited Members
Public Types inherited from Neighbor
enum State : uint8_t {
kStateInvalid, kStateRestored, kStateParentRequest, kStateParentResponse,
kStateChildIdRequest, kStateLinkRequest, kStateChildUpdateRequest, kStateValid
}
enum StateFilter : uint8_t {
kInStateValid, kInStateValidOrRestoring, kInStateChildIdRequest, kInStateValidOrAttaching,
kInStateInvalid, kInStateAnyExceptInvalid, kInStateAnyExceptValidOrRestoring, kInStateAny
}
Static Public Member Functions inherited from Neighbor
static const char * StateToString (State aState)
Protected Member Functions inherited from Neighbor
void Init (Instance &aInstance)
Protected Member Functions inherited from InstanceLocatorInit
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class represents a Thread Router
Member Function Documentation
Init()
void Init (Instance & aInstance) inline
This method initializes the Router object.
Parameters
[in] aInstance A reference to OpenThread instance.
References Neighbor::Init().
Clear()
void Clear (void)
This method clears the router entry.
References InstanceLocator::GetInstance(), and Neighbor::Init().
SetFrom()
void SetFrom (const Parent & aParent)
This method sets the Router entry from a Parent
GetNextHop()
uint8_t GetNextHop (void) const inline
This method gets the router ID of the next hop to this router.
Returns
The router ID of the next hop to this router.
Referenced by Router::Info::SetFrom().
SetNextHop()
void SetNextHop (uint8_t aRouterId) inline
This method sets the router ID of the next hop to this router.
Parameters
[in] aRouterId The router ID of the next hop to this router.
GetLinkQualityOut()
LinkQuality GetLinkQualityOut (void) const inline
This method gets the link quality out value for this router.
Returns
The link quality out value for this router.
Referenced by Mle::HasAcceptableParentCandidate(), Mle::IsBetterParent(), and Router::Info::SetFrom().
SetLinkQualityOut()
void SetLinkQualityOut (LinkQuality aLinkQuality) inline
This method sets the link quality out value for this router.
Parameters
[in] aLinkQuality The link quality out value for this router.
Referenced by Mle::HandleParentResponse().
GetCost()
uint8_t GetCost (void) const inline
This method get the route cost to this router.
Returns
The route cost to this router.
Referenced by Router::Info::SetFrom().
SetCost()
void SetCost (uint8_t aCost) inline
This method sets the router cost to this router.
Parameters
[in] aCost The router cost to this router.
Field Documentation
mNextHop
uint8_t mNextHop private
The next hop towards this router.
mLinkQualityOut
uint8_t mLinkQualityOut private
The link quality out for this router.
mCost
uint8_t mCost private
The cost to this router via neighbor router.
The documentation for this class was generated from the following files:
topology.hpp
topology.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale