OpenThread: Beacon Class Reference
Beacon Class Reference
Core-mac
#include <mac_frame.hpp>
Public Member Functions
uint8_t * GetPayload (void)
const uint8_t * GetPayload (void) const
void Init (void)
bool IsValid (void) const
Static Public Attributes
static constexpr uint16_t kSuperFrameSpec = 0x0fff
Superframe Specification value.
Private Attributes
uint8_t mGtsSpec
uint8_t mPendingAddressSpec
uint16_t mSuperframeSpec
Member Function Documentation
Init()
void Init (void) inline
This method initializes the Beacon message.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Mac::PrepareBeacon().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the beacon appears to be a valid Thread Beacon message.
Return values
TRUE If the beacon appears to be a valid Thread Beacon message.
FALSE If the beacon does not appear to be a valid Thread Beacon message.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Mac::ConvertBeaconToActiveScanResult().
GetPayload() [1/2]
uint8_t* GetPayload (void) inline
This method returns the pointer to the beacon payload.
Returns
A pointer to the beacon payload.
Referenced by Mac::ConvertBeaconToActiveScanResult(), and Mac::PrepareBeacon().
GetPayload() [2/2]
const uint8_t* GetPayload (void) const inline
This method returns the pointer to the beacon payload.
Returns
A pointer to the beacon payload.
Field Documentation
kSuperFrameSpec
constexpr uint16_t kSuperFrameSpec = 0x0fff static
Superframe Specification value.
mSuperframeSpec
uint16_t mSuperframeSpec private
mGtsSpec
uint8_t mGtsSpec private
mPendingAddressSpec
uint8_t mPendingAddressSpec private
The documentation for this class was generated from the following file:
mac_frame.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale