OpenThread: Ip6 Class Reference
Ip6 Class Reference
Core-ipv6 » IPv6
#include <ip6.hpp>
Public Types
enum MessageOrigin : uint8_t { kFromThreadNetif, kFromHostDisallowLoopBack, kFromHostAllowLoopBack }
Public Member Functions
const PriorityQueue & GetSendQueue (void) const
Error HandleDatagram (Message &aMessage, MessageOrigin aOrigin, const void *aLinkMessageInfo=nullptr)
Ip6 (Instance &aInstance)
bool IsForwardingEnabled (void) const
bool IsReceiveIp6FilterEnabled (void) const
Message * NewMessage (uint16_t aReserved, const Message::Settings &aSettings=Message::Settings::GetDefault())
Message * NewMessage (const uint8_t *aData, uint16_t aDataLength, const Message::Settings &aSettings)
Message * NewMessage (const uint8_t *aData, uint16_t aDataLength)
const Netif::UnicastAddress * SelectSourceAddress (MessageInfo &aMessageInfo)
Error SendDatagram (Message &aMessage, MessageInfo &aMessageInfo, uint8_t aIpProto)
Error SendRaw (Message &aMessage, bool aAllowLoopBackToHost)
void SetForwardingEnabled (bool aEnable)
void SetReceiveDatagramCallback (otIp6ReceiveCallback aCallback, void *aCallbackContext)
void SetReceiveIp6FilterEnabled (bool aEnabled)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Member Functions
static Message::Priority DscpToPriority (uint8_t aDscp)
static const char * EcnToString (Ecn aEcn)
static const char * IpProtoToString (uint8_t aIpProto)
Private Member Functions
Error AddMplOption (Message &aMessage, Header &aHeader)
Error AddTunneledMplOption (Message &aMessage, Header &aHeader, MessageInfo &aMessageInfo)
void EnqueueDatagram (Message &aMessage)
Error FragmentDatagram (Message &aMessage, uint8_t aIpProto)
Error HandleExtensionHeaders (Message &aMessage, MessageOrigin aOrigin, MessageInfo &aMessageInfo, Header &aHeader, uint8_t &aNextHeader, bool &aReceive)
Error HandleFragment (Message &aMessage, MessageOrigin aOrigin, MessageInfo &aMessageInfo)
Error HandleOptions (Message &aMessage, Header &aHeader, bool aIsOutbound, bool &aReceive)
Error HandlePayload (Header &aIp6Header, Message &aMessage, MessageInfo &aMessageInfo, uint8_t aIpProto, Message::Ownership aMessageOwnership)
void HandleSendQueue (void)
Error InsertMplOption (Message &aMessage, Header &aHeader, MessageInfo &aMessageInfo)
bool IsOnLink (const Address &aAddress) const
Error ProcessReceiveCallback (Message &aMessage, MessageOrigin aOrigin, const MessageInfo &aMessageInfo, uint8_t aIpProto, bool aAllowReceiveFilter, Message::Ownership aMessageOwnership)
Error RemoveMplOption (Message &aMessage)
bool ShouldForwardToThread (const MessageInfo &aMessageInfo, MessageOrigin aOrigin) const
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static Error GetDatagramPriority (const uint8_t *aData, uint16_t aDataLen, Message::Priority &aPriority)
static void HandleSendQueue (Tasklet &aTasklet)
static uint8_t PriorityToDscp (Message::Priority aPriority)
Private Attributes
bool mForwardingEnabled
Icmp mIcmp
bool mIsReceiveIp6FilterEnabled
Mpl mMpl
otIp6ReceiveCallback mReceiveIp6DatagramCallback
void * mReceiveIp6DatagramCallbackContext
PriorityQueue mSendQueue
Tasklet mSendQueueTask
Udp mUdp
Static Private Attributes
static constexpr uint8_t kDefaultHopLimit = OPENTHREAD_CONFIG_IP6_HOP_LIMIT_DEFAULT
static constexpr uint8_t kIp6ReassemblyTimeout = OPENTHREAD_CONFIG_IP6_REASSEMBLY_TIMEOUT
static constexpr uint16_t kMinimalMtu = 1280
Friends
class Mpl
class ot::Instance
class ot::TimeTicker
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements the core IPv6 message processing.
Member Enumeration Documentation
MessageOrigin
enum MessageOrigin : uint8_t
This enumeration represents an IPv6 message origin.
In case the message is originating from host, it also indicates whether or not it is allowed to passed back the message to the host.
Enumerator
kFromThreadNetif
Message originates from Thread Netif.
kFromHostDisallowLoopBack
Message originates from host and should not be passed back to host.
kFromHostAllowLoopBack
Message originates from host and can be passed back to host.
Constructor & Destructor Documentation
Ip6()
Ip6 (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the otInstance object.
Member Function Documentation
NewMessage() [1/3]
Message * NewMessage (uint16_t aReserved, const Message::Settings & aSettings = Message::Settings::GetDefault())
This method allocates a new message buffer from the buffer pool.
Parameters
[in] aReserved The number of header bytes to reserve following the IPv6 header.
[in] aSettings The message settings.
Returns
A pointer to the message or nullptr if insufficient message buffers are available.
References Message::kTypeIp6.
Referenced by Ip6::HandleOptions(), and Ip6::NewMessage().
NewMessage() [2/3]
Message * NewMessage (const uint8_t * aData, uint16_t aDataLength, const Message::Settings & aSettings)
This method allocates a new message buffer from the buffer pool and writes the IPv6 datagram to the message.
Parameters
[in] aData A pointer to the IPv6 datagram buffer.
[in] aDataLength The size of the IPV6 datagram buffer pointed by aData.
[in] aSettings The message settings.
Returns
A pointer to the message or nullptr if malformed IPv6 header or insufficient message buffers are available.
References Message::AppendBytes(), Message::Free(), ot::kErrorNone, Message::kTypeIp6, and VerifyOrExit.
NewMessage() [3/3]
Message * NewMessage (const uint8_t * aData, uint16_t aDataLength)
This method allocates a new message buffer from the buffer pool and writes the IPv6 datagram to the message.
Note
The link layer security is enabled and the message priority is obtained from IPv6 message itself.
Parameters
[in] aData A pointer to the IPv6 datagram buffer.
[in] aDataLength The size of the IPV6 datagram buffer pointed by aData.
Returns
A pointer to the message or nullptr if malformed IPv6 header or insufficient message buffers are available.
References Ip6::GetDatagramPriority(), Message::kWithLinkSecurity, Ip6::NewMessage(), and SuccessOrExit.
DscpToPriority()
Message::Priority DscpToPriority (uint8_t aDscp) static
This method converts the IPv6 DSCP value to message priority level.
Parameters
[in] aDscp The IPv6 DSCP value.
Returns
The message priority level.
References ot::Ip6::kDscpCs0, ot::Ip6::kDscpCs1, ot::Ip6::kDscpCs2, ot::Ip6::kDscpCs3, ot::Ip6::kDscpCs4, ot::Ip6::kDscpCs5, ot::Ip6::kDscpCs6, ot::Ip6::kDscpCs7, ot::Ip6::kDscpCsMask, Message::kPriorityHigh, Message::kPriorityLow, and Message::kPriorityNormal.
Referenced by Ip6::GetDatagramPriority(), and MeshForwarder::GetFramePriority().
SendDatagram()
Error SendDatagram (Message & aMessage, MessageInfo & aMessageInfo, uint8_t aIpProto)
This method sends an IPv6 datagram.
Parameters
[in] aMessage A reference to the message.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aIpProto The Internet Protocol value.
Return values
kErrorNone Successfully enqueued the message into an output interface.
kErrorNoBufs Insufficient available buffer to add the IPv6 headers.
References Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Message::Clone(), Ip6::EnqueueDatagram(), Ip6::FragmentDatagram(), Netif::UnicastAddress::GetAddress(), Header::GetDestination(), MessageInfo::GetEcn(), MessageInfo::GetHopLimit(), Message::GetLength(), MessageInfo::GetMulticastLoop(), MessageInfo::GetPeerAddr(), Message::GetPriority(), MessageInfo::GetSockAddr(), Header::GetSource(), Header::InitVersionTrafficClassFlow(), Address::IsMulticast(), Address::IsMulticastLargerThanRealmLocal(), Address::IsRealmLocalMulticast(), Address::IsUnspecified(), Ip6::kDefaultHopLimit, ot::kErrorInvalidSourceAddress, ot::kErrorNone, ot::Ip6::kMaxDatagramLength, LogInfo, LogWarn, Message::Prepend(), Ip6::PriorityToDscp(), Ip6::SelectSourceAddress(), Header::SetDestination(), Header::SetDscp(), Header::SetEcn(), Header::SetHopLimit(), Message::SetMulticastLoop(), Header::SetNextHeader(), Header::SetPayloadLength(), Header::SetSource(), MessageInfo::ShouldAllowZeroHopLimit(), SuccessOrExit, Checksum::UpdateMessageChecksum(), and VerifyOrExit.
SendRaw()
Error SendRaw (Message & aMessage, bool aAllowLoopBackToHost)
This method sends a raw IPv6 datagram with a fully formed IPv6 header.
The caller transfers ownership of aMessage when making this call. OpenThread will free aMessage when processing is complete, including when a value other than kErrorNone is returned.
Parameters
[in] aMessage A reference to the message.
[in] aAllowLoopBackToHost Indicate whether or not the message is allowed to be passed back to host.
Return values
kErrorNone Successfully processed the message.
kErrorDrop Message was well-formed but not fully processed due to packet processing rules.
kErrorNoBufs Could not allocate necessary message buffers when processing the datagram.
kErrorNoRoute No route to host.
kErrorParse Encountered a malformed header when processing the message.
References Message::Free(), Header::GetDestination(), Header::GetHopLimit(), Header::GetSource(), Ip6::HandleDatagram(), Ip6::InsertMplOption(), Address::IsMulticast(), ot::kErrorInvalidSourceAddress, ot::kErrorNone, Ip6::kFromHostAllowLoopBack, Ip6::kFromHostDisallowLoopBack, Header::ParseFrom(), MessageInfo::SetHopLimit(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), SuccessOrExit, and VerifyOrExit.
HandleDatagram()
Error HandleDatagram (Message & aMessage, MessageOrigin aOrigin, const void * aLinkMessageInfo = nullptr)
This method processes a received IPv6 datagram.
Parameters
[in] aMessage A reference to the message.
[in] aOrigin The message oirgin.
[in] aLinkMessageInfo A pointer to link-specific message information.
Return values
kErrorNone Successfully processed the message.
kErrorDrop Message was well-formed but not fully processed due to packet processing rules.
kErrorNoBufs Could not allocate necessary message buffers when processing the datagram.
kErrorNoRoute No route to host.
kErrorParse Encountered a malformed header when processing the message.
References Clearable< Type >::Clear(), Message::Free(), Header::GetDestination(), Header::GetEcn(), Header::GetHopLimit(), Message::GetMulticastLoop(), Header::GetNextHeader(), Message::GetOffset(), Header::GetSource(), Ip6::HandleExtensionHeaders(), Ip6::HandlePayload(), ot::Encoding::BigEndian::HostSwap16(), Address::IsLinkLocal(), Address::IsMulticast(), Address::IsMulticastLargerThanRealmLocal(), Message::kCopyToUse, Udp::Header::kDestPortFieldOffset, ot::kErrorDrop, ot::kErrorNone, ot::kErrorNoRoute, Ip6::kFromHostDisallowLoopBack, Ip6::kFromThreadNetif, Header::kHopLimitFieldOffset, MeshForwarder::kMessageReceive, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoIp6, ot::Ip6::kProtoUdp, Message::kTakeCustody, Ip6::mForwardingEnabled, Header::ParseFrom(), Ip6::ProcessReceiveCallback(), Message::Read(), Message::RemoveHeader(), MessageInfo::SetEcn(), MessageInfo::SetHopLimit(), Header::SetHopLimit(), MessageInfo::SetLinkInfo(), Message::SetOffset(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), sForwardICMPTypes, Ip6::ShouldForwardToThread(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Ip6::HandleOptions(), Ip6::HandleSendQueue(), Ip6::InsertMplOption(), and Ip6::SendRaw().
SetReceiveDatagramCallback()
void SetReceiveDatagramCallback (otIp6ReceiveCallback aCallback, void * aCallbackContext)
This method registers a callback to provide received raw IPv6 datagrams.
By default, this callback does not pass Thread control traffic. See SetReceiveIp6FilterEnabled() to change the Thread control traffic filter setting.
Parameters
[in] aCallback A pointer to a function that is called when an IPv6 datagram is received or nullptr to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
See also
IsReceiveIp6FilterEnabled
SetReceiveIp6FilterEnabled
References Ip6::mReceiveIp6DatagramCallback, and Ip6::mReceiveIp6DatagramCallbackContext.
IsReceiveIp6FilterEnabled()
bool IsReceiveIp6FilterEnabled (void) const inline
This method indicates whether or not Thread control traffic is filtered out when delivering IPv6 datagrams via the callback specified in SetReceiveIp6DatagramCallback().
Returns
TRUE if Thread control traffic is filtered out, FALSE otherwise.
See also
SetReceiveDatagramCallback
SetReceiveIp6FilterEnabled
References Ip6::mIsReceiveIp6FilterEnabled.
SetReceiveIp6FilterEnabled()
void SetReceiveIp6FilterEnabled (bool aEnabled) inline
This method sets whether or not Thread control traffic is filtered out when delivering IPv6 datagrams via the callback specified in SetReceiveIp6DatagramCallback().
Parameters
[in] aEnabled TRUE if Thread control traffic is filtered out, FALSE otherwise.
See also
SetReceiveDatagramCallback
IsReceiveIp6FilterEnabled
References Ip6::mIsReceiveIp6FilterEnabled.
IsForwardingEnabled()
bool IsForwardingEnabled (void) const inline
This method indicates whether or not IPv6 forwarding is enabled.
Returns
TRUE if IPv6 forwarding is enabled, FALSE otherwise.
References Ip6::mForwardingEnabled.
SetForwardingEnabled()
void SetForwardingEnabled (bool aEnable) inline
This method enables/disables IPv6 forwarding.
Parameters
[in] aEnable TRUE to enable IPv6 forwarding, FALSE otherwise.
References Ip6::mForwardingEnabled, and Ip6::SelectSourceAddress().
SelectSourceAddress()
const Netif::UnicastAddress * SelectSourceAddress (MessageInfo & aMessageInfo)
This method perform default source address selection.
Parameters
[in] aMessageInfo A reference to the message information.
Returns
A pointer to the selected IPv6 source address or nullptr if no source address was found.
References ExitNow, MessageInfo::GetPeerAddr(), Netif::UnicastAddress::GetScope(), Address::GetScope(), otNetifAddress::mPreferred, otNetifAddress::mPrefixLength, and Address::PrefixMatch().
Referenced by Ip6::AddTunneledMplOption(), Ip6::SendDatagram(), and Ip6::SetForwardingEnabled().
GetSendQueue()
const PriorityQueue& GetSendQueue (void) const inline
This method returns a reference to the send queue.
Returns
A reference to the send queue.
References Ip6::EcnToString(), Ip6::IpProtoToString(), and Ip6::mSendQueue.
IpProtoToString()
const char * IpProtoToString (uint8_t aIpProto) static
This static method converts an IP protocol number to a string.
Parameters
[in] aIpProto An IP protocol number.
Returns
The string representation of aIpProto.
References BinarySearch::IsSorted(), ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoFragment, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoIp6, ot::Ip6::kProtoNone, ot::Ip6::kProtoRouting, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, and Stringify::Lookup().
Referenced by MeshForwarder::CalcFrameVersion(), Ip6::GetSendQueue(), and otIp6ProtoToString().
EcnToString()
const char * EcnToString (Ecn aEcn) static
This static method converts an IP header ECN value to a string.
Parameters
[in] aEcn The 2-bit ECN value.
Returns
The string representation of aEcn.
References ot::Ip6::kEcnCapable0, ot::Ip6::kEcnCapable1, ot::Ip6::kEcnMarked, and ot::Ip6::kEcnNotCapable.
Referenced by MeshForwarder::CalcFrameVersion(), and Ip6::GetSendQueue().
HandleSendQueue() [1/2]
void HandleSendQueue (Tasklet & aTasklet) static private
References GetProvider< InstanceGetProvider >::Get(), and Ip6::HandleSendQueue().
HandleSendQueue() [2/2]
void HandleSendQueue (void) private
References PriorityQueue::Dequeue(), PriorityQueue::GetHead(), Ip6::HandleDatagram(), IgnoreError(), Ip6::kFromHostAllowLoopBack, and Ip6::mSendQueue.
Referenced by Ip6::HandleSendQueue().
PriorityToDscp()
uint8_t PriorityToDscp (Message::Priority aPriority) static private
References ot::Ip6::kDscpCs0, ot::Ip6::kDscpCs1, ot::Ip6::kDscpCs4, Message::kPriorityHigh, Message::kPriorityLow, Message::kPriorityNet, and Message::kPriorityNormal.
Referenced by Ip6::SendDatagram().
GetDatagramPriority()
Error GetDatagramPriority (const uint8_t * aData, uint16_t aDataLen, Message::Priority & aPriority) static private
References Ip6::DscpToPriority(), Header::GetDscp(), Header::GetPayloadLength(), Header::IsValid(), ot::kErrorInvalidArgs, ot::kErrorNone, ot::kErrorParse, and VerifyOrExit.
Referenced by Ip6::NewMessage().
EnqueueDatagram()
void EnqueueDatagram (Message & aMessage) private
References PriorityQueue::Enqueue(), Ip6::mSendQueue, Ip6::mSendQueueTask, and Tasklet::Post().
Referenced by Ip6::FragmentDatagram(), Ip6::HandleOptions(), and Ip6::SendDatagram().
ProcessReceiveCallback()
Error ProcessReceiveCallback (Message & aMessage, MessageOrigin aOrigin, const MessageInfo & aMessageInfo, uint8_t aIpProto, bool aAllowReceiveFilter, Message::Ownership aMessageOwnership) private
References Message::Clone(), ExitNow, Message::Free(), Udp::Header::GetDestinationPort(), Address::GetIid(), Message::GetLength(), Message::GetOffset(), MessageInfo::GetSockAddr(), Icmp::Header::GetType(), IgnoreError(), InterfaceIdentifier::IsAnycastServiceLocator(), InterfaceIdentifier::IsLocator(), Message::kCopyToUse, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNoRoute, Ip6::kFromHostDisallowLoopBack, Ip6::kMinimalMtu, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoUdp, Message::kTakeCustody, Icmp::Header::kTypeEchoRequest, LogWarn, Ip6::mIcmp, Ip6::mIsReceiveIp6FilterEnabled, Ip6::mReceiveIp6DatagramCallback, Ip6::mReceiveIp6DatagramCallbackContext, Message::Read(), Ip6::RemoveMplOption(), Icmp::ShouldHandleEchoRequest(), and VerifyOrExit.
Referenced by Ip6::HandleDatagram(), and Ip6::HandleExtensionHeaders().
HandleExtensionHeaders()
Error HandleExtensionHeaders (Message & aMessage, MessageOrigin aOrigin, MessageInfo & aMessageInfo, Header & aHeader, uint8_t & aNextHeader, bool & aReceive) private
References ExitNow, ExtensionHeader::GetNextHeader(), Message::GetOffset(), Ip6::HandleFragment(), Ip6::HandleOptions(), IgnoreError(), Message::kCopyToUse, ot::kErrorDrop, ot::kErrorNone, Ip6::kFromThreadNetif, ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoFragment, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoNone, ot::Ip6::kProtoRouting, Ip6::ProcessReceiveCallback(), Message::Read(), and SuccessOrExit.
Referenced by Ip6::HandleDatagram().
FragmentDatagram()
Error FragmentDatagram (Message & aMessage, uint8_t aIpProto) private
References Ip6::EnqueueDatagram(), ot::kErrorNone, and OT_UNUSED_VARIABLE.
Referenced by Ip6::HandleOptions(), and Ip6::SendDatagram().
HandleFragment()
Error HandleFragment (Message & aMessage, MessageOrigin aOrigin, MessageInfo & aMessageInfo) private
References Message::GetOffset(), FragmentHeader::GetOffset(), FragmentHeader::IsMoreFlagSet(), ot::kErrorDrop, ot::kErrorNone, Message::MoveOffset(), OT_UNUSED_VARIABLE, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by Ip6::HandleExtensionHeaders(), and Ip6::HandleOptions().
AddMplOption()
Error AddMplOption (Message & aMessage, Header & aHeader) private
References Header::GetNextHeader(), Header::GetPayloadLength(), Header::GetSource(), OptionMpl::GetTotalLength(), OptionPadN::GetTotalLength(), OptionPadN::Init(), Mpl::InitOption(), ot::kErrorNone, ot::Ip6::kProtoHopOpts, Ip6::mMpl, Message::Prepend(), Message::PrependBytes(), ExtensionHeader::SetLength(), Header::SetNextHeader(), ExtensionHeader::SetNextHeader(), Header::SetPayloadLength(), and SuccessOrExit.
Referenced by Ip6::AddTunneledMplOption(), Ip6::InsertMplOption(), and Ip6::SendDatagram().
AddTunneledMplOption()
Error AddTunneledMplOption (Message & aMessage, Header & aHeader, MessageInfo & aMessageInfo) private
References Ip6::AddMplOption(), Netif::UnicastAddress::GetAddress(), Header::GetPayloadLength(), MessageInfo::GetPeerAddr(), Header::InitVersionTrafficClassFlow(), Ip6::kDefaultHopLimit, ot::kErrorInvalidSourceAddress, ot::kErrorNone, ot::Ip6::kProtoIp6, Message::Prepend(), Ip6::SelectSourceAddress(), Header::SetDestination(), Header::SetHopLimit(), Header::SetNextHeader(), Header::SetPayloadLength(), Header::SetSource(), Address::SetToRealmLocalAllMplForwarders(), SuccessOrExit, and VerifyOrExit.
Referenced by Ip6::InsertMplOption(), and Ip6::SendDatagram().
InsertMplOption()
Error InsertMplOption (Message & aMessage, Header & aHeader, MessageInfo & aMessageInfo) private
References Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Message::Clone(), Message::CopyTo(), Header::GetDestination(), ExtensionHeader::GetLength(), Header::GetNextHeader(), Header::GetPayloadLength(), Address::GetScope(), Header::GetSource(), OptionMpl::GetTotalLength(), OptionPadN::GetTotalLength(), Ip6::HandleDatagram(), IgnoreError(), OptionPadN::Init(), Mpl::InitOption(), Address::IsMulticast(), Address::IsMulticastLargerThanRealmLocal(), Address::IsRealmLocalMulticast(), ot::kErrorNone, ot::kErrorParse, Ip6::kFromHostDisallowLoopBack, ot::Ip6::kProtoHopOpts, Address::kRealmLocalScope, LogInfo, LogWarn, Ip6::mMpl, Message::Prepend(), Message::PrependBytes(), Message::Read(), Message::RemoveHeader(), ExtensionHeader::SetLength(), Header::SetPayloadLength(), SuccessOrExit, VerifyOrExit, Message::Write(), and Message::WriteBytes().
Referenced by Ip6::SendRaw().
RemoveMplOption()
Error RemoveMplOption (Message & aMessage) private
References ExtensionHeader::GetLength(), Message::GetLength(), OptionHeader::GetLength(), Header::GetNextHeader(), ExtensionHeader::GetNextHeader(), Header::GetPayloadLength(), OptionPadN::GetTotalLength(), OptionHeader::GetType(), IgnoreError(), OptionPadN::Init(), ot::kErrorNone, ot::kErrorParse, ot::Ip6::kProtoHopOpts, OptionMpl::kType, OptionPadN::kType, OptionPad1::kType, Message::Read(), Message::RemoveHeader(), ExtensionHeader::SetLength(), Header::SetNextHeader(), Header::SetPayloadLength(), VerifyOrExit, Message::Write(), and Message::WriteBytes().
Referenced by Ip6::ProcessReceiveCallback().
HandleOptions()
Error HandleOptions (Message & aMessage, Header & aHeader, bool aIsOutbound, bool & aReceive) private
References FragmentHeader::BytesToFragmentOffset(), FragmentHeader::ClearMoreFlag(), Message::CopyTo(), Ip6::EnqueueDatagram(), ot::ErrorToString(), ExitNow, Ip6::FragmentDatagram(), FragmentHeader::FragmentOffsetToBytes(), Message::Free(), FreeMessageOnError, OptionHeader::GetAction(), Header::GetDestination(), Header::GetHopLimit(), FragmentHeader::GetIdentification(), ExtensionHeader::GetLength(), Message::GetLength(), OptionHeader::GetLength(), FragmentHeader::GetNextHeader(), TimerMilli::GetNow(), Message::GetOffset(), FragmentHeader::GetOffset(), Message::GetPriority(), Header::GetSource(), OptionHeader::GetType(), ot::Random::NonCrypto::GetUint32(), Ip6::HandleDatagram(), Ip6::HandleFragment(), IgnoreError(), FragmentHeader::Init(), FragmentHeader::IsMoreFlagSet(), OptionHeader::kActionDiscard, OptionHeader::kActionForceIcmp, OptionHeader::kActionIcmp, OptionHeader::kActionSkip, Icmp::Header::kCodeFragmReasTimeEx, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorParse, TimeTicker::kIp6FragmentReassembler, Ip6::kIp6ReassemblyTimeout, ot::Ip6::kMaxAssembledDatagramLength, Ip6::kMinimalMtu, ot::Ip6::kProtoFragment, OptionMpl::kType, OptionPad1::kType, Icmp::Header::kTypeTimeExceeded, LogDebg, LogInfo, LogNote, LogWarn, FragmentHeader::MakeDivisibleByEight(), Ip6::mIcmp, otMessageInfo::mLinkInfo, Ip6::mMpl, Message::MoveOffset(), Ip6::NewMessage(), OT_ASSERT, OT_UNUSED_VARIABLE, Mpl::ProcessOption(), Message::Read(), Time::SecToMsec(), Icmp::SendError(), Message::SetDatagramTag(), MessageInfo::SetHopLimit(), FragmentHeader::SetIdentification(), Message::SetLength(), MessageInfo::SetLinkInfo(), FragmentHeader::SetMoreFlag(), Header::SetNextHeader(), FragmentHeader::SetNextHeader(), Message::SetOffset(), FragmentHeader::SetOffset(), Header::SetPayloadLength(), MessageInfo::SetPeerAddr(), Message::SetPriority(), MessageInfo::SetSockAddr(), Message::SetTimestampToNow(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Ip6::HandleExtensionHeaders().
HandlePayload()
Error HandlePayload (Header & aIp6Header, Message & aMessage, MessageInfo & aMessageInfo, uint8_t aIpProto, Message::Ownership aMessageOwnership) private
References Message::Clone(), ot::ErrorToString(), ExitNow, FreeMessage, Icmp::HandleMessage(), Udp::HandleMessage(), Message::kCopyToUse, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNone, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, Message::kTakeCustody, LogNote, Ip6::mIcmp, Ip6::mUdp, OT_UNUSED_VARIABLE, and VerifyOrExit.
Referenced by Ip6::HandleDatagram().
ShouldForwardToThread()
bool ShouldForwardToThread (const MessageInfo & aMessageInfo, MessageOrigin aOrigin) const private
References MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Address::IsLinkLocal(), Address::IsMulticast(), Ip6::IsOnLink(), ot::kErrorNone, Ip6::kFromHostDisallowLoopBack, and OT_UNUSED_VARIABLE.
Referenced by Ip6::HandleDatagram().
IsOnLink()
bool IsOnLink (const Address & aAddress) const private
References ExitNow.
Referenced by Ip6::ShouldForwardToThread().
Friends And Related Function Documentation
ot::Instance
friend class ot::Instance friend
ot::TimeTicker
friend class ot::TimeTicker friend
Mpl
friend class Mpl friend
Field Documentation
kDefaultHopLimit
constexpr uint8_t kDefaultHopLimit = OPENTHREAD_CONFIG_IP6_HOP_LIMIT_DEFAULT static private
Referenced by Ip6::AddTunneledMplOption(), and Ip6::SendDatagram().
kIp6ReassemblyTimeout
constexpr uint8_t kIp6ReassemblyTimeout = OPENTHREAD_CONFIG_IP6_REASSEMBLY_TIMEOUT static private
Referenced by Ip6::HandleOptions().
kMinimalMtu
constexpr uint16_t kMinimalMtu = 1280 static private
Referenced by Ip6::HandleOptions(), and Ip6::ProcessReceiveCallback().
mForwardingEnabled
bool mForwardingEnabled private
Referenced by Ip6::HandleDatagram(), Ip6::IsForwardingEnabled(), and Ip6::SetForwardingEnabled().
mIsReceiveIp6FilterEnabled
bool mIsReceiveIp6FilterEnabled private
Referenced by Ip6::IsReceiveIp6FilterEnabled(), Ip6::ProcessReceiveCallback(), and Ip6::SetReceiveIp6FilterEnabled().
mReceiveIp6DatagramCallback
otIp6ReceiveCallback mReceiveIp6DatagramCallback private
Referenced by Ip6::ProcessReceiveCallback(), and Ip6::SetReceiveDatagramCallback().
mReceiveIp6DatagramCallbackContext
void* mReceiveIp6DatagramCallbackContext private
Referenced by Ip6::ProcessReceiveCallback(), and Ip6::SetReceiveDatagramCallback().
mSendQueue
PriorityQueue mSendQueue private
Referenced by Ip6::EnqueueDatagram(), Ip6::GetSendQueue(), and Ip6::HandleSendQueue().
mSendQueueTask
Tasklet mSendQueueTask private
Referenced by Ip6::EnqueueDatagram().
mIcmp
Icmp mIcmp private
Referenced by Ip6::HandleOptions(), Ip6::HandlePayload(), and Ip6::ProcessReceiveCallback().
mUdp
Udp mUdp private
Referenced by Ip6::HandlePayload().
mMpl
Mpl mMpl private
Referenced by Ip6::AddMplOption(), Ip6::HandleOptions(), and Ip6::InsertMplOption().
The documentation for this class was generated from the following files:
ip6.hpp
ip6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale