OpenThread: MacCountersTlv Class Reference
MacCountersTlv Class Reference
MLE » TLVs
#include <network_diagnostic_tlvs.hpp>
Public Member Functions
uint32_t GetIfInBroadcastPkts (void) const
uint32_t GetIfInDiscards (void) const
uint32_t GetIfInErrors (void) const
uint32_t GetIfInUcastPkts (void) const
uint32_t GetIfInUnknownProtos (void) const
uint32_t GetIfOutBroadcastPkts (void) const
uint32_t GetIfOutDiscards (void) const
uint32_t GetIfOutErrors (void) const
uint32_t GetIfOutUcastPkts (void) const
void Init (void)
bool IsValid (void) const
void SetIfInBroadcastPkts (const uint32_t aIfInBroadcastPkts)
void SetIfInDiscards (const uint32_t aIfInDiscards)
void SetIfInErrors (const uint32_t aIfInErrors)
void SetIfInUcastPkts (const uint32_t aIfInUcastPkts)
void SetIfInUnknownProtos (const uint32_t aIfInUnknownProtos)
void SetIfOutBroadcastPkts (const uint32_t aIfOutBroadcastPkts)
void SetIfOutDiscards (const uint32_t aIfOutDiscards)
void SetIfOutErrors (const uint32_t aIfOutErrors)
void SetIfOutUcastPkts (const uint32_t aIfOutUcastPkts)
Public Member Functions inherited from NetworkDiagnosticTlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint32_t mIfInBroadcastPkts
uint32_t mIfInDiscards
uint32_t mIfInErrors
uint32_t mIfInUcastPkts
uint32_t mIfInUnknownProtos
uint32_t mIfOutBroadcastPkts
uint32_t mIfOutDiscards
uint32_t mIfOutErrors
uint32_t mIfOutUcastPkts
Additional Inherited Members
Public Types inherited from NetworkDiagnosticTlv
enum Type : uint8_t {
kExtMacAddress = OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS, kAddress16 = OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS, kMode = OT_NETWORK_DIAGNOSTIC_TLV_MODE, kTimeout = OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT,
kConnectivity = OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY, kRoute = OT_NETWORK_DIAGNOSTIC_TLV_ROUTE, kLeaderData = OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA, kNetworkData = OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA,
kIp6AddressList = OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST, kMacCounters = OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS, kBatteryLevel = OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL, kSupplyVoltage = OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE,
kChildTable = OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE, kChannelPages = OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES, kTypeList = OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST, kMaxChildTimeout = OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
}
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< NetworkDiagnosticTlv::kMacCounters >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements Mac Counters TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References NetworkDiagnosticTlv::kMacCounters, Tlv::SetLength(), and NetworkDiagnosticTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
GetIfInUnknownProtos()
uint32_t GetIfInUnknownProtos (void) const inline
This method returns the IfInUnknownProtos counter.
Returns
The IfInUnknownProtos counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfInUnknownProtos()
void SetIfInUnknownProtos (const uint32_t aIfInUnknownProtos) inline
This method sets the IfInUnknownProtos counter.
Parameters
[in] aIfInUnknownProtos The IfInUnknownProtos counter
References ot::Encoding::BigEndian::HostSwap32().
GetIfInErrors()
uint32_t GetIfInErrors (void) const inline
This method returns the IfInErrors counter.
Returns
The IfInErrors counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfInErrors()
void SetIfInErrors (const uint32_t aIfInErrors) inline
This method sets the IfInErrors counter.
Parameters
[in] aIfInErrors The IfInErrors counter
References ot::Encoding::BigEndian::HostSwap32().
GetIfOutErrors()
uint32_t GetIfOutErrors (void) const inline
This method returns the IfOutErrors counter.
Returns
The IfOutErrors counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfOutErrors()
void SetIfOutErrors (const uint32_t aIfOutErrors) inline
This method sets the IfOutErrors counter.
Parameters
[in] aIfOutErrors The IfOutErrors counter.
References ot::Encoding::BigEndian::HostSwap32().
GetIfInUcastPkts()
uint32_t GetIfInUcastPkts (void) const inline
This method returns the IfInUcastPkts counter.
Returns
The IfInUcastPkts counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfInUcastPkts()
void SetIfInUcastPkts (const uint32_t aIfInUcastPkts) inline
This method sets the IfInUcastPkts counter.
Parameters
[in] aIfInUcastPkts The IfInUcastPkts counter.
References ot::Encoding::BigEndian::HostSwap32().
GetIfInBroadcastPkts()
uint32_t GetIfInBroadcastPkts (void) const inline
This method returns the IfInBroadcastPkts counter.
Returns
The IfInBroadcastPkts counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfInBroadcastPkts()
void SetIfInBroadcastPkts (const uint32_t aIfInBroadcastPkts) inline
This method sets the IfInBroadcastPkts counter.
Parameters
[in] aIfInBroadcastPkts The IfInBroadcastPkts counter.
References ot::Encoding::BigEndian::HostSwap32().
GetIfInDiscards()
uint32_t GetIfInDiscards (void) const inline
This method returns the IfInDiscards counter.
Returns
The IfInDiscards counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfInDiscards()
void SetIfInDiscards (const uint32_t aIfInDiscards) inline
This method sets the IfInDiscards counter.
Parameters
[in] aIfInDiscards The IfInDiscards counter.
References ot::Encoding::BigEndian::HostSwap32().
GetIfOutUcastPkts()
uint32_t GetIfOutUcastPkts (void) const inline
This method returns the IfOutUcastPkts counter.
Returns
The IfOutUcastPkts counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfOutUcastPkts()
void SetIfOutUcastPkts (const uint32_t aIfOutUcastPkts) inline
This method sets the IfOutUcastPkts counter.
Parameters
[in] aIfOutUcastPkts The IfOutUcastPkts counter.
References ot::Encoding::BigEndian::HostSwap32().
GetIfOutBroadcastPkts()
uint32_t GetIfOutBroadcastPkts (void) const inline
This method returns the IfOutBroadcastPkts counter.
Returns
The IfOutBroadcastPkts counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfOutBroadcastPkts()
void SetIfOutBroadcastPkts (const uint32_t aIfOutBroadcastPkts) inline
This method sets the IfOutBroadcastPkts counter.
Parameters
[in] aIfOutBroadcastPkts The IfOutBroadcastPkts counter.
References ot::Encoding::BigEndian::HostSwap32().
GetIfOutDiscards()
uint32_t GetIfOutDiscards (void) const inline
This method returns the IfOutDiscards counter.
Returns
The IfOutDiscards counter
References ot::Encoding::BigEndian::HostSwap32().
SetIfOutDiscards()
void SetIfOutDiscards (const uint32_t aIfOutDiscards) inline
This method sets the IfOutDiscards counter.
Parameters
[in] aIfOutDiscards The IfOutDiscards counter.
References ot::Encoding::BigEndian::HostSwap32().
Field Documentation
mIfInUnknownProtos
uint32_t mIfInUnknownProtos private
mIfInErrors
uint32_t mIfInErrors private
mIfOutErrors
uint32_t mIfOutErrors private
mIfInUcastPkts
uint32_t mIfInUcastPkts private
mIfInBroadcastPkts
uint32_t mIfInBroadcastPkts private
mIfInDiscards
uint32_t mIfInDiscards private
mIfOutUcastPkts
uint32_t mIfOutUcastPkts private
mIfOutBroadcastPkts
uint32_t mIfOutBroadcastPkts private
mIfOutDiscards
uint32_t mIfOutDiscards private
The documentation for this class was generated from the following file:
network_diagnostic_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale