OpenThread: RetainPtr< Type > Class Template Reference
RetainPtr< Type > Class Template Reference
#include <retain_ptr.hpp>
Public Member Functions
RetainPtr & operator= (const RetainPtr &aOther)
Type * Release (void)
void Reset (Type *aPointer=nullptr)
RetainPtr (void)=default
RetainPtr (Type *aPointer)
RetainPtr (const RetainPtr &aOther)
~RetainPtr (void)
Public Member Functions inherited from Ptr< Type >
Type * Get (void)
const Type * Get (void) const
bool IsNull (void) const
bool operator!= (const Type *aPointer) const
bool operator!= (const Ptr &aOther) const
Type & operator* (void)
const Type & operator* (void) const
Type * operator-> (void)
const Type * operator-> (void) const
bool operator== (const Type *aPointer) const
bool operator== (const Ptr &aOther) const
Ptr (void)
Ptr (Type *aPointer)
Private Member Functions
void DecrementRetainCount (void)
void IncrementRetainCount (void)
Additional Inherited Members
Protected Attributes inherited from Ptr< Type >
Type * mPointer
Detailed Description
template<class Type>
class ot::RetainPtr< Type >
This template class represents a retain (reference counted) smart pointer.
The Type class MUST provide mechanism to track its current retain count. It MUST provide the following three methods:
void IncrementRetainCount(void); (Increment the retain count).
uint16_t DecrementRetainCount(void); (Decrement the retain count and return the value after decrement).
void Free(void); (Free the Type instance).
The Type can inherit from RetainCountable which provides the retain counting methods.
Template Parameters
Type The pointer type.
Constructor & Destructor Documentation
RetainPtr() [1/3]
RetainPtr (void) default
This is the default constructor for RetainPtr initializing it as null.
RetainPtr() [2/3]
RetainPtr (Type * aPointer) inline explicit
This constructor initializes the RetainPtr with a given pointer.
Upon construction the RetainPtr will increment the retain count on aPointer (if not null).
Parameters
[in] aPointer A pointer to object to initialize with.
References RetainPtr< Type >::IncrementRetainCount().
RetainPtr() [3/3]
RetainPtr (const RetainPtr< Type > & aOther) inline
This constructor initializes the RetainPtr from another RetainPtr.
Parameters
[in] aOther Another RetainPtr.
References RetainPtr< Type >::IncrementRetainCount().
~RetainPtr()
~RetainPtr (void) inline
This is the destructor for RetainPtr.
Upon destruction, the RetainPtr will decrement the retain count on the managed object (if not null) and free the object if its retain count reaches zero.
References RetainPtr< Type >::DecrementRetainCount().
Member Function Documentation
Reset()
void Reset (Type * aPointer = nullptr) inline
This method replaces the managed object by RetainPtr with a new one.
The method correctly handles a self Reset() (i.e., aPointer being the same pointer as the one currently managed by RetainPtr).
Parameters
[in] aPointer A pointer to a new object to replace with.
References RetainPtr< Type >::DecrementRetainCount(), RetainPtr< Type >::IncrementRetainCount(), and Ptr< Type >::mPointer.
Referenced by RetainPtr< Type >::operator=().
Release()
Type* Release (void) inline
This method releases the ownership of the current pointer in RetainPtr (if any) without changing its retain count.
After this call, the RetainPtr will be null.
Returns
The pointer to the object managed by RetainPtr or nullptr if RetainPtr was null.
References Ptr< Type >::mPointer.
operator=()
RetainPtr& operator= (const RetainPtr< Type > & aOther) inline
This method overloads the assignment operator =.
The RetainPtr first frees its current managed object (if there is any and it is different from aOther) before taking over the ownership of the object from aOther. This method correctly handles a self assignment (i.e., assigning the pointer to itself).
Parameters
[in] aOther A reference to another RetainPtr.
Returns
A reference to this RetainPtr.
References Ptr< Type >::mPointer, and RetainPtr< Type >::Reset().
IncrementRetainCount()
void IncrementRetainCount (void) inline private
References Ptr< Type >::mPointer.
Referenced by RetainPtr< Type >::Reset(), and RetainPtr< Type >::RetainPtr().
DecrementRetainCount()
void DecrementRetainCount (void) inline private
References Ptr< Type >::mPointer.
Referenced by RetainPtr< Type >::Reset(), and RetainPtr< Type >::~RetainPtr().
The documentation for this class was generated from the following file:
retain_ptr.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale