OpenThread: ExtendedTlv Class Reference
ExtendedTlv Class Reference
#include <tlvs.hpp>
Public Member Functions
uint16_t GetLength (void) const
void SetLength (uint16_t aLength)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint16_t mLength
Additional Inherited Members
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Member Function Documentation
GetLength()
uint16_t GetLength (void) const inline
This method returns the Length value.
References ot::Encoding::BigEndian::HostSwap16(), and Tlv::mLength.
Referenced by Tlv::Find().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the Length value.
Parameters
[in] aLength The Length value.
References ot::Encoding::BigEndian::HostSwap16(), Tlv::kExtendedLength, Tlv::mLength, and Tlv::SetLength().
Field Documentation
mLength
uint16_t mLength private
The documentation for this class was generated from the following file:
tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale