OpenThread: ServiceTlv Class Reference
ServiceTlv Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Data Structures
union OT_TOOL_PACKED_FIELD
Public Member Functions
uint32_t GetEnterpriseNumber (void) const
void GetServiceData (ServiceData &aServiceData) const
uint8_t GetServiceDataLength (void) const
uint8_t GetServiceId (void) const
NetworkDataTlv * GetSubTlvs (void)
const NetworkDataTlv * GetSubTlvs (void) const
uint8_t GetSubTlvsLength (void)
void Init (uint8_t aServiceId, uint32_t aEnterpriseNumber, const ServiceData &aServiceData)
bool IsValid (void) const
void SetSubTlvsLength (uint8_t aLength)
Public Member Functions inherited from NetworkDataTlv
void ClearStable (void)
void DecreaseLength (uint8_t aDecrement)
uint8_t GetLength (void) const
NetworkDataTlv * GetNext (void)
const NetworkDataTlv * GetNext (void) const
uint8_t GetSize (void) const
Type GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
void IncreaseLength (uint8_t aIncrement)
void Init (void)
bool IsStable (void) const
void SetLength (uint8_t aLength)
void SetStable (void)
void SetType (Type aType)
Static Public Member Functions
static uint16_t CalculateSize (uint32_t aEnterpriseNumber, uint8_t aServiceDataLength)
Static Public Member Functions inherited from NetworkDataTlv
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType, bool aStable)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType, bool aStable)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, bool aStable)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, bool aStable)
Static Public Attributes
static constexpr uint32_t kThreadEnterpriseNumber = 44970
Thread enterprise number.
static constexpr Type kType = kTypeService
The TLV Type.
Private Member Functions
uint8_t GetFieldsLength (void) const
const uint8_t * GetServiceData (void) const
bool IsThreadEnterprise (void) const
Private Attributes
uint8_t mFlagsServiceId
uint8_t mServiceDataLength
union ot::NetworkData::ServiceTlv::OT_TOOL_PACKED_FIELD mShared
Static Private Attributes
static constexpr uint8_t kMinLength = sizeof(uint8_t) + sizeof(uint8_t)
static constexpr uint8_t kServiceIdMask = 0xf
static constexpr uint8_t kThreadEnterpriseFlag = (1 << 7)
Additional Inherited Members
Public Types inherited from NetworkDataTlv
enum Type : uint8_t {
kTypeHasRoute = 0, kTypePrefix = 1, kTypeBorderRouter = 2, kTypeContext = 3,
kTypeCommissioningData = 4, kTypeService = 5, kTypeServer = 6
}
Detailed Description
This class implements Service Data TLV generation and parsing.
Member Function Documentation
Init()
void Init (uint8_t aServiceId, uint32_t aEnterpriseNumber, const ServiceData & aServiceData)
This method initializes the TLV.
Parameters
[in] aServiceId The Service Id value.
[in] aEnterpriseNumber The Enterprise Number.
[in] aServiceData The Service Data.
References Data< kDataLengthType >::CopyBytesTo(), Data< kDataLengthType >::GetLength(), ot::Encoding::BigEndian::HostSwap32(), NetworkDataTlv::Init(), ot::NetworkData::Service::kThreadEnterpriseNumber, NetworkDataTlv::kTypeService, NetworkDataTlv::SetLength(), and NetworkDataTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References NetworkDataTlv::GetLength().
GetServiceId()
uint8_t GetServiceId (void) const inline
This method returns the Service ID. It is in range 0x00-0x0f.
Returns
the Service ID.
Referenced by Manager::GetNextDnsSrpAnycastInfo(), MutableNetworkData::RemoveTemporaryDataIn(), and ServiceConfig::SetFrom().
GetEnterpriseNumber()
uint32_t GetEnterpriseNumber (void) const inline
This method returns Enterprise Number field.
Returns
The Enterprise Number.
References ot::Encoding::BigEndian::HostSwap32(), and ot::NetworkData::Service::kThreadEnterpriseNumber.
Referenced by NetworkData::MatchService(), and ServiceConfig::SetFrom().
GetServiceData() [1/2]
void GetServiceData (ServiceData & aServiceData) const inline
This method gets the Service Data.
Parameters
[out] aServiceData A reference to aServiceData to return the data.
References Data< kDataLengthType >::Init().
Referenced by Manager::GetNextDnsSrpAnycastInfo(), Manager::GetNextDnsSrpUnicastInfo(), NetworkData::MatchService(), and ServiceConfig::SetFrom().
GetServiceDataLength()
uint8_t GetServiceDataLength (void) const inline
This method gets Service Data length.
Returns
length of the Service Data field in bytes.
Referenced by Manager::GetNextDnsSrpAnycastInfo(), and Manager::GetNextDnsSrpUnicastInfo().
GetSubTlvsLength()
uint8_t GetSubTlvsLength (void) inline
This method returns the Sub-TLVs length in bytes.
Returns
The Sub-TLVs length in bytes.
References NetworkDataTlv::GetLength().
Referenced by MutableNetworkData::RemoveTemporaryData(), and MutableNetworkData::RemoveTemporaryDataIn().
SetSubTlvsLength()
void SetSubTlvsLength (uint8_t aLength) inline
This method sets the Sub-TLVs length in bytes.
Parameters
[in] aLength The Sub-TLVs length in bytes.
References NetworkDataTlv::SetLength().
Referenced by MutableNetworkData::RemoveTemporaryDataIn().
GetSubTlvs() [1/2]
NetworkDataTlv* GetSubTlvs (void) inline
This method returns a pointer to the Sub-TLVs.
Returns
A pointer to the Sub-TLVs.
References NetworkDataTlv::GetValue().
Referenced by Manager::IterateToNextServer(), and MutableNetworkData::RemoveTemporaryDataIn().
GetSubTlvs() [2/2]
const NetworkDataTlv* GetSubTlvs (void) const inline
This method returns a pointer to the Sub-TLVs.
Returns
A pointer to the Sub-TLVs.
References NetworkDataTlv::GetValue().
CalculateSize()
static uint16_t CalculateSize (uint32_t aEnterpriseNumber, uint8_t aServiceDataLength) inline static
This static method calculates the total size (number of bytes) of a Service TLV with a given Enterprise Number and Service Data length.
Note that the returned size does include the Type and Length fields in the TLV, but does not account for any sub-TLVs of the Service TLV.
Parameters
[in] aEnterpriseNumber A Enterprise Number.
[in] aServiceDataLength A Service Data length.
Returns
The size (number of bytes) of the Service TLV.
IsThreadEnterprise()
bool IsThreadEnterprise (void) const inline private
GetServiceData() [2/2]
const uint8_t* GetServiceData (void) const inline private
GetFieldsLength()
uint8_t GetFieldsLength (void) const inline private
Field Documentation
kType
constexpr Type kType = kTypeService static
The TLV Type.
kThreadEnterpriseNumber
constexpr uint32_t kThreadEnterpriseNumber = 44970 static
Thread enterprise number.
Referenced by NetworkData::FindNextThreadService().
kThreadEnterpriseFlag
constexpr uint8_t kThreadEnterpriseFlag = (1 << 7) static private
kServiceIdMask
constexpr uint8_t kServiceIdMask = 0xf static private
kMinLength
constexpr uint8_t kMinLength = sizeof(uint8_t) + sizeof(uint8_t) static private
mFlagsServiceId
uint8_t mFlagsServiceId private
mShared
union ot::NetworkData::ServiceTlv::OT_TOOL_PACKED_FIELD mShared private
mServiceDataLength
uint8_t mServiceDataLength private
The documentation for this class was generated from the following files:
network_data_tlvs.hpp
network_data_tlvs.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale