OpenThread: CslIe Class Reference
CslIe Class Reference
Core-mac
#include <mac_frame.hpp>
Public Member Functions
uint16_t GetPeriod (void) const
uint16_t GetPhase (void) const
void SetPeriod (uint16_t aPeriod)
void SetPhase (uint16_t aPhase)
Static Public Attributes
static constexpr uint8_t kHeaderIeId = 0x1a
static constexpr uint8_t kIeContentSize = sizeof(uint16_t) * 2
Private Attributes
uint16_t mPeriod
uint16_t mPhase
Detailed Description
This class implements CSL IE data structure.
Member Function Documentation
GetPeriod()
uint16_t GetPeriod (void) const inline
This method returns the CSL Period.
Returns
the CSL Period.
References ot::Encoding::BigEndian::HostSwap16().
SetPeriod()
void SetPeriod (uint16_t aPeriod) inline
This method sets the CSL Period.
Parameters
[in] aPeriod The CSL Period.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Frame::GetFooter().
GetPhase()
uint16_t GetPhase (void) const inline
This method returns the CSL Phase.
Returns
the CSL Phase.
References ot::Encoding::BigEndian::HostSwap16().
SetPhase()
void SetPhase (uint16_t aPhase) inline
This method sets the CSL Phase.
Parameters
[in] aPhase The CSL Phase.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Frame::GetFooter().
Field Documentation
kHeaderIeId
constexpr uint8_t kHeaderIeId = 0x1a static
Referenced by Frame::GetFooter(), DataPollSender::HandlePollSent(), Mac::LogFrameTxFailure(), DataPollSender::PrepareDataRequest(), DataPollSender::ProcessTxDone(), and MeshForwarder::UpdateNeighborOnSentFrame().
kIeContentSize
constexpr uint8_t kIeContentSize = sizeof(uint16_t) * 2 static
mPhase
uint16_t mPhase private
mPeriod
uint16_t mPeriod private
The documentation for this class was generated from the following file:
mac_frame.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale