OpenThread: Lowpan Class Reference
Lowpan Class Reference
Core-6lowpan
#include <lowpan.hpp>
Public Member Functions
Error Compress (Message &aMessage, const Mac::Addresses &aMacAddrs, FrameBuilder &aFrameBuilder)
Error Decompress (Message &aMessage, const Mac::Addresses &aMacAddrs, FrameData &aFrameData, uint16_t aDatagramLength)
Error DecompressBaseHeader (Ip6::Header &aIp6Header, bool &aCompressedNextHeader, const Mac::Addresses &aMacAddrs, FrameData &aFrameData)
Ip6::Ecn DecompressEcn (const Message &aMessage, uint16_t aOffset) const
Error DecompressUdpHeader (Ip6::Udp::Header &aUdpHeader, FrameData &aFrameData)
Lowpan (Instance &aInstance)
void MarkCompressedEcn (Message &aMessage, uint16_t aOffset)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Member Functions
static bool IsLowpanHc (const uint8_t *aHeader)
static bool IsLowpanHc (const FrameData &aFrameData)
Private Member Functions
Error Compress (Message &aMessage, const Mac::Addresses &aMacAddrs, FrameBuilder &aFrameBuilder, uint8_t &aHeaderDepth)
Error CompressDestinationIid (const Mac::Address &aMacAddr, const Ip6::Address &aIpAddr, const Context &aContext, uint16_t &aHcCtl, FrameBuilder &aFrameBuilder)
Error CompressExtensionHeader (Message &aMessage, FrameBuilder &aFrameBuilder, uint8_t &aNextHeader)
Error CompressMulticast (const Ip6::Address &aIpAddr, uint16_t &aHcCtl, FrameBuilder &aFrameBuilder)
Error CompressSourceIid (const Mac::Address &aMacAddr, const Ip6::Address &aIpAddr, const Context &aContext, uint16_t &aHcCtl, FrameBuilder &aFrameBuilder)
Error CompressUdp (Message &aMessage, FrameBuilder &aFrameBuilder)
Error DecompressExtensionHeader (Message &aMessage, FrameData &aFrameData)
Error DecompressUdpHeader (Message &aMessage, FrameData &aFrameData, uint16_t aDatagramLength)
Error DispatchToNextHeader (uint8_t aDispatch, uint8_t &aNextHeader)
void FindContextForId (uint8_t aContextId, Context &aContext) const
void FindContextToCompressAddress (const Ip6::Address &aIp6Address, Context &aContext) const
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static Error ComputeIid (const Mac::Address &aMacAddr, const Context &aContext, Ip6::InterfaceIdentifier &aIid)
Static Private Attributes
static constexpr uint8_t kEcnMask = 3 << kEcnOffset
static constexpr uint8_t kEcnOffset = 6
static constexpr uint8_t kExtHdrDispatch = 0xe0
static constexpr uint8_t kExtHdrDispatchMask = 0xf0
static constexpr uint8_t kExtHdrEidDst = 0x06
static constexpr uint8_t kExtHdrEidFragment = 0x04
static constexpr uint8_t kExtHdrEidHbh = 0x00
static constexpr uint8_t kExtHdrEidIp6 = 0x0e
static constexpr uint8_t kExtHdrEidMask = 0x0e
static constexpr uint8_t kExtHdrEidMobility = 0x08
static constexpr uint8_t kExtHdrEidRouting = 0x02
static constexpr uint16_t kExtHdrMaxLength = 255
static constexpr uint8_t kExtHdrNextHeader = 0x01
static constexpr uint16_t kHcContextId = 1 << 7
static constexpr uint16_t kHcDispatch = 3 << 13
static constexpr uint16_t kHcDispatchMask = 7 << 13
static constexpr uint16_t kHcDstAddrContext = 1 << 2
static constexpr uint16_t kHcDstAddrMode0 = 0 << 0
static constexpr uint16_t kHcDstAddrMode1 = 1 << 0
static constexpr uint16_t kHcDstAddrMode2 = 2 << 0
static constexpr uint16_t kHcDstAddrMode3 = 3 << 0
static constexpr uint16_t kHcDstAddrModeMask = 3 << 0
static constexpr uint16_t kHcFlowLabel = 2 << 11
static constexpr uint16_t kHcHopLimit1 = 1 << 8
static constexpr uint16_t kHcHopLimit255 = 3 << 8
static constexpr uint16_t kHcHopLimit64 = 2 << 8
static constexpr uint16_t kHcHopLimitMask = 3 << 8
static constexpr uint16_t kHcMulticast = 1 << 3
static constexpr uint16_t kHcNextHeader = 1 << 10
static constexpr uint16_t kHcSrcAddrContext = 1 << 6
static constexpr uint16_t kHcSrcAddrMode0 = 0 << 4
static constexpr uint16_t kHcSrcAddrMode1 = 1 << 4
static constexpr uint16_t kHcSrcAddrMode2 = 2 << 4
static constexpr uint16_t kHcSrcAddrMode3 = 3 << 4
static constexpr uint16_t kHcSrcAddrModeMask = 3 << 4
static constexpr uint16_t kHcTrafficClass = 1 << 11
static constexpr uint16_t kHcTrafficFlow = 3 << 11
static constexpr uint16_t kHcTrafficFlowMask = 3 << 11
static constexpr uint8_t kUdpChecksum = 1 << 2
static constexpr uint8_t kUdpDispatch = 0xf0
static constexpr uint8_t kUdpDispatchMask = 0xf8
static constexpr uint8_t kUdpPortMask = 3 << 0
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements LOWPAN_IPHC header compression.
Constructor & Destructor Documentation
Lowpan()
Lowpan (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
IsLowpanHc() [1/2]
static bool IsLowpanHc (const uint8_t * aHeader) inline static
This method indicates whether or not the header is a LOWPAN_IPHC header.
Parameters
[in] aHeader A pointer to the header.
Return values
TRUE If the header matches the LOWPAN_IPHC dispatch value.
FALSE If the header does not match the LOWPAN_IPHC dispatch value.
References Lowpan::kHcDispatch, and Lowpan::kHcDispatchMask.
Referenced by Headers::DecompressFrom(), and MeshForwarder::HandleReceivedFrame().
IsLowpanHc() [2/2]
static bool IsLowpanHc (const FrameData & aFrameData) inline static
This method indicates whether or not header in a given frame is a LOWPAN_IPHC header.
Parameters
[in] aFrameData The frame data.
Return values
TRUE If the header matches the LOWPAN_IPHC dispatch value.
FALSE If the header does not match the LOWPAN_IPHC dispatch value.
References Data< kDataLengthType >::GetBytes(), and Data< kDataLengthType >::GetLength().
Compress() [1/2]
Error Compress (Message & aMessage, const Mac::Addresses & aMacAddrs, FrameBuilder & aFrameBuilder)
This method compresses an IPv6 header.
Parameters
[in] aMessage A reference to the IPv6 message.
[in] aMacAddrs The MAC source and destination addresses.
[in] aFrameBuilder The FrameBuilder to use to append the compressed headers.
Returns
The size of the compressed header in bytes.
References ot::kErrorNone, and VerifyOrExit.
Referenced by Lowpan::Compress().
Decompress()
Error Decompress (Message & aMessage, const Mac::Addresses & aMacAddrs, FrameData & aFrameData, uint16_t aDatagramLength)
This method decompresses a LOWPAN_IPHC header.
If the header is parsed successfully the aFrameData is updated to skip over the parsed header bytes.
Parameters
[out] aMessage A reference where the IPv6 header will be placed.
[in] aMacAddrs The MAC source and destination addresses.
[in,out] aFrameData A frame data containing the LOWPAN_IPHC header.
[in] aDatagramLength The IPv6 datagram length.
Return values
kErrorNone The header was decompressed successfully. aMessage and aFrameData are updated.
kErrorParse Failed to parse the lowpan header.
kErrorNoBufs Could not grow aMessage to write the parsed IPv6 header.
References Message::Append(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressExtensionHeader(), Lowpan::DecompressUdpHeader(), ExitNow, Data< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), Message::GetOffset(), ot::Encoding::BigEndian::HostSwap16(), ot::kErrorNone, ot::kErrorParse, Lowpan::kExtHdrDispatch, Lowpan::kExtHdrDispatchMask, Lowpan::kExtHdrEidIp6, Lowpan::kExtHdrEidMask, Lowpan::kExtHdrNextHeader, Header::kPayloadLengthFieldOffset, Lowpan::kUdpDispatch, Lowpan::kUdpDispatchMask, Message::MoveOffset(), FrameData::SkipOver(), SuccessOrExit, VerifyOrExit, and Message::Write().
DecompressBaseHeader()
Error DecompressBaseHeader (Ip6::Header & aIp6Header, bool & aCompressedNextHeader, const Mac::Addresses & aMacAddrs, FrameData & aFrameData)
This method decompresses a LOWPAN_IPHC header.
If the header is parsed successfully the aFrameData is updated to skip over the parsed header bytes.
Parameters
[out] aIp6Header A reference where the IPv6 header will be placed.
[out] aCompressedNextHeader A boolean reference to output whether next header is compressed or not.
[in] aMacAddrs The MAC source and destination addresses
[in,out] aFrameData A frame data containing the LOWPAN_IPHC header.
Return values
kErrorNone The header was decompressed successfully. aIp6Headre and aFrameData are updated.
kErrorParse Failed to parse the lowpan header.
References Clearable< Type >::Clear(), Lowpan::ComputeIid(), Lowpan::DispatchToNextHeader(), ExitNow, Lowpan::FindContextForId(), Prefix::GetBytes(), Data< kDataLengthType >::GetBytes(), Header::GetDestination(), Address::GetIid(), Prefix::GetLength(), Data< kDataLengthType >::GetLength(), Header::GetSource(), ot::Encoding::BigEndian::HostSwap16(), IgnoreError(), Header::InitVersionTrafficClassFlow(), ot::kErrorNone, ot::kErrorParse, Lowpan::kHcContextId, Lowpan::kHcDispatch, Lowpan::kHcDispatchMask, Lowpan::kHcDstAddrContext, Lowpan::kHcDstAddrMode0, Lowpan::kHcDstAddrMode1, Lowpan::kHcDstAddrMode2, Lowpan::kHcDstAddrMode3, Lowpan::kHcDstAddrModeMask, Lowpan::kHcFlowLabel, Lowpan::kHcHopLimit1, Lowpan::kHcHopLimit255, Lowpan::kHcHopLimit64, Lowpan::kHcHopLimitMask, Lowpan::kHcMulticast, Lowpan::kHcNextHeader, Lowpan::kHcSrcAddrContext, Lowpan::kHcSrcAddrMode0, Lowpan::kHcSrcAddrMode1, Lowpan::kHcSrcAddrMode2, Lowpan::kHcSrcAddrMode3, Lowpan::kHcSrcAddrModeMask, Lowpan::kHcTrafficClass, Lowpan::kHcTrafficFlow, Lowpan::kHcTrafficFlowMask, otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::OT_TOOL_PACKED_FIELD::m8, Addresses::mDestination, otIp6Address::mFields, Context::mIsValid, Context::mPrefix, Addresses::mSource, FrameData::Read(), FrameData::ReadBigEndianUint16(), FrameData::ReadBytes(), FrameData::ReadUint8(), Header::SetHopLimit(), Header::SetNextHeader(), Address::SetPrefix(), FrameData::SkipOver(), SuccessOrExit, and VerifyOrExit.
Referenced by Lowpan::Decompress(), and Headers::DecompressFrom().
DecompressUdpHeader() [1/2]
Error DecompressUdpHeader (Ip6::Udp::Header & aUdpHeader, FrameData & aFrameData)
This method decompresses a LOWPAN_NHC UDP header.
If the header is parsed successfully the aFrameData is updated to skip over the parsed header bytes.
Parameters
[out] aUdpHeader A reference where the UDP header will be placed.
[in,out] aFrameData A frame data containing the LOWPAN_NHC header.
Return values
kErrorNone The header was decompressed successfully. aUdpHeader and aFrameData are updated.
kErrorParse Failed to parse the lowpan header.
References Clearable< Type >::Clear(), ExitNow, ot::kErrorNone, ot::kErrorParse, Lowpan::kUdpChecksum, Lowpan::kUdpDispatch, Lowpan::kUdpDispatchMask, Lowpan::kUdpPortMask, FrameData::ReadBigEndianUint16(), FrameData::ReadUint8(), Udp::Header::SetChecksum(), Udp::Header::SetDestinationPort(), Udp::Header::SetSourcePort(), SuccessOrExit, and VerifyOrExit.
Referenced by Lowpan::Decompress(), Headers::DecompressFrom(), and Lowpan::DecompressUdpHeader().
DecompressEcn()
Ip6::Ecn DecompressEcn (const Message & aMessage, uint16_t aOffset) const
This method decompresses the IPv6 ECN field in a LOWPAN_IPHC header.
Parameters
[in] aMessage The message to read the IPHC header from.
[in] aOffset The offset in aMessage to start of IPHC header.
Returns
The decompressed ECN field. If the IPHC header is not valid kEcnNotCapable is returned.
References ExitNow, ot::Encoding::BigEndian::HostSwap16(), Lowpan::kEcnMask, ot::Ip6::kEcnNotCapable, Lowpan::kEcnOffset, Lowpan::kHcDispatch, Lowpan::kHcDispatchMask, Lowpan::kHcTrafficFlow, Lowpan::kHcTrafficFlowMask, Message::Read(), SuccessOrExit, and VerifyOrExit.
MarkCompressedEcn()
void MarkCompressedEcn (Message & aMessage, uint16_t aOffset)
This method updates the compressed ECN field in a LOWPAN_IPHC header to kEcnMarked.
This method MUST be used when the ECN field is not elided in the IPHC header. Note that the ECN is not elided when it is not zero (kEcnNotCapable).
Parameters
[in,out] aMessage The message containing the IPHC header and to update.
[in] aOffset The offset in aMessage to start of IPHC header.
References IgnoreError(), ot::Ip6::kEcnMarked, Lowpan::kEcnMask, Lowpan::kEcnOffset, Message::Read(), and Message::Write().
FindContextForId()
void FindContextForId (uint8_t aContextId, Context & aContext) const private
References Clearable< Type >::Clear(), and ot::kErrorNone.
Referenced by Lowpan::CompressMulticast(), and Lowpan::DecompressBaseHeader().
FindContextToCompressAddress()
void FindContextToCompressAddress (const Ip6::Address & aIp6Address, Context & aContext) const private
References Clearable< Type >::Clear(), ot::kErrorNone, and Context::mCompressFlag.
Referenced by Lowpan::Compress().
Compress() [2/2]
Error Compress (Message & aMessage, const Mac::Addresses & aMacAddrs, FrameBuilder & aFrameBuilder, uint8_t & aHeaderDepth) private
References FrameBuilder::Append(), FrameBuilder::AppendBigEndianUint16(), FrameBuilder::AppendBytes(), FrameBuilder::AppendUint8(), Lowpan::Compress(), Lowpan::CompressDestinationIid(), Lowpan::CompressExtensionHeader(), Lowpan::CompressMulticast(), Lowpan::CompressSourceIid(), Lowpan::CompressUdp(), ExitNow, Lowpan::FindContextToCompressAddress(), Header::GetDestination(), Header::GetHopLimit(), FrameBuilder::GetLength(), Header::GetNextHeader(), Message::GetOffset(), Header::GetSource(), ot::Encoding::BigEndian::HostSwap16(), Address::IsLinkLocal(), Address::IsMulticast(), Address::IsUnspecified(), ot::kErrorNone, Lowpan::kExtHdrDispatch, Lowpan::kExtHdrEidIp6, Lowpan::kHcContextId, Lowpan::kHcDispatch, Lowpan::kHcDstAddrContext, Lowpan::kHcFlowLabel, Lowpan::kHcHopLimit1, Lowpan::kHcHopLimit255, Lowpan::kHcHopLimit64, Lowpan::kHcNextHeader, Lowpan::kHcSrcAddrContext, Lowpan::kHcTrafficClass, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoUdp, Context::mContextId, Addresses::mDestination, Context::mIsValid, Message::MoveOffset(), Addresses::mSource, OT_FALL_THROUGH, Message::Read(), Message::SetOffset(), SuccessOrExit, and FrameBuilder::Write().
CompressExtensionHeader()
Error CompressExtensionHeader (Message & aMessage, FrameBuilder & aFrameBuilder, uint8_t & aNextHeader) private
References FrameBuilder::AppendBytesFromMessage(), FrameBuilder::AppendUint8(), ExtensionHeader::GetLength(), Message::GetLength(), OptionHeader::GetLength(), ExtensionHeader::GetNextHeader(), Message::GetOffset(), OptionHeader::GetType(), ot::kErrorFailed, ot::kErrorNone, ot::kErrorParse, Lowpan::kExtHdrDispatch, Lowpan::kExtHdrEidHbh, Lowpan::kExtHdrMaxLength, Lowpan::kExtHdrNextHeader, ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoUdp, OptionPadN::kType, OptionPad1::kType, Message::MoveOffset(), Message::Read(), Message::SetOffset(), SuccessOrExit, and VerifyOrExit.
Referenced by Lowpan::Compress().
CompressSourceIid()
Error CompressSourceIid (const Mac::Address & aMacAddr, const Ip6::Address & aIpAddr, const Context & aContext, uint16_t & aHcCtl, FrameBuilder & aFrameBuilder) private
References FrameBuilder::Append(), FrameBuilder::AppendBigEndianUint16(), Lowpan::ComputeIid(), Address::GetIid(), InterfaceIdentifier::GetLocator(), IgnoreError(), InterfaceIdentifier::IsLocator(), ot::kErrorNone, Lowpan::kHcSrcAddrMode1, Lowpan::kHcSrcAddrMode2, and Lowpan::kHcSrcAddrMode3.
Referenced by Lowpan::Compress().
CompressDestinationIid()
Error CompressDestinationIid (const Mac::Address & aMacAddr, const Ip6::Address & aIpAddr, const Context & aContext, uint16_t & aHcCtl, FrameBuilder & aFrameBuilder) private
References FrameBuilder::Append(), FrameBuilder::AppendBigEndianUint16(), Lowpan::ComputeIid(), Address::GetIid(), InterfaceIdentifier::GetLocator(), IgnoreError(), InterfaceIdentifier::IsLocator(), ot::kErrorNone, Lowpan::kHcDstAddrMode1, Lowpan::kHcDstAddrMode2, and Lowpan::kHcDstAddrMode3.
Referenced by Lowpan::Compress().
CompressMulticast()
Error CompressMulticast (const Ip6::Address & aIpAddr, uint16_t & aHcCtl, FrameBuilder & aFrameBuilder) private
References FrameBuilder::Append(), FrameBuilder::AppendBytes(), FrameBuilder::AppendUint8(), Lowpan::FindContextForId(), Prefix::GetBytes(), Prefix::GetLength(), ot::kErrorNone, Lowpan::kHcDstAddrContext, Lowpan::kHcDstAddrMode0, Lowpan::kHcDstAddrMode1, Lowpan::kHcDstAddrMode2, Lowpan::kHcDstAddrMode3, Lowpan::kHcMulticast, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Context::mPrefix, and SuccessOrExit.
Referenced by Lowpan::Compress().
CompressUdp()
Error CompressUdp (Message & aMessage, FrameBuilder & aFrameBuilder) private
References FrameBuilder::AppendBigEndianUint16(), FrameBuilder::AppendBytes(), FrameBuilder::AppendUint8(), Udp::Header::GetChecksum(), Udp::Header::GetDestinationPort(), Message::GetOffset(), Udp::Header::GetSourcePort(), ot::kErrorNone, Udp::Header::kLengthFieldOffset, Lowpan::kUdpDispatch, Message::MoveOffset(), Message::Read(), Message::SetOffset(), and SuccessOrExit.
Referenced by Lowpan::Compress().
DecompressExtensionHeader()
Error DecompressExtensionHeader (Message & aMessage, FrameData & aFrameData) private
References Message::AppendBytes(), BitVectorBytes, FrameData::CanRead(), Lowpan::DispatchToNextHeader(), Data< kDataLengthType >::GetBytes(), OptionPadN::Init(), OptionPad1::Init(), ot::kErrorNone, ot::kErrorParse, Lowpan::kExtHdrNextHeader, Message::MoveOffset(), FrameData::ReadUint8(), FrameData::SkipOver(), SuccessOrExit, and VerifyOrExit.
Referenced by Lowpan::Decompress().
DecompressUdpHeader() [2/2]
Error DecompressUdpHeader (Message & aMessage, FrameData & aFrameData, uint16_t aDatagramLength) private
References Message::Append(), Lowpan::DecompressUdpHeader(), Data< kDataLengthType >::GetLength(), Message::GetOffset(), Message::MoveOffset(), Udp::Header::SetLength(), and SuccessOrExit.
DispatchToNextHeader()
Error DispatchToNextHeader (uint8_t aDispatch, uint8_t & aNextHeader) private
References ExitNow, ot::kErrorNone, ot::kErrorParse, Lowpan::kExtHdrDispatch, Lowpan::kExtHdrDispatchMask, Lowpan::kExtHdrEidDst, Lowpan::kExtHdrEidFragment, Lowpan::kExtHdrEidHbh, Lowpan::kExtHdrEidIp6, Lowpan::kExtHdrEidMask, Lowpan::kExtHdrEidRouting, ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoFragment, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoRouting, ot::Ip6::kProtoUdp, Lowpan::kUdpDispatch, and Lowpan::kUdpDispatchMask.
Referenced by Lowpan::DecompressBaseHeader(), and Lowpan::DecompressExtensionHeader().
ComputeIid()
Error ComputeIid (const Mac::Address & aMacAddr, const Context & aContext, Ip6::InterfaceIdentifier & aIid) static private
References InterfaceIdentifier::ApplyPrefix(), ExitNow, Address::GetExtended(), Address::GetShort(), Address::GetType(), ot::kErrorNone, ot::kErrorParse, Address::kTypeExtended, Address::kTypeShort, Context::mPrefix, InterfaceIdentifier::SetFromExtAddress(), and InterfaceIdentifier::SetToLocator().
Referenced by Lowpan::CompressDestinationIid(), Lowpan::CompressSourceIid(), and Lowpan::DecompressBaseHeader().
Field Documentation
kHcDispatch
constexpr uint16_t kHcDispatch = 3 << 13 static private
Referenced by Lowpan::Compress(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressEcn(), and Lowpan::IsLowpanHc().
kHcDispatchMask
constexpr uint16_t kHcDispatchMask = 7 << 13 static private
Referenced by Lowpan::DecompressBaseHeader(), Lowpan::DecompressEcn(), and Lowpan::IsLowpanHc().
kHcTrafficClass
constexpr uint16_t kHcTrafficClass = 1 << 11 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcFlowLabel
constexpr uint16_t kHcFlowLabel = 2 << 11 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcTrafficFlow
constexpr uint16_t kHcTrafficFlow = 3 << 11 static private
Referenced by Lowpan::DecompressBaseHeader(), and Lowpan::DecompressEcn().
kHcTrafficFlowMask
constexpr uint16_t kHcTrafficFlowMask = 3 << 11 static private
Referenced by Lowpan::DecompressBaseHeader(), and Lowpan::DecompressEcn().
kHcNextHeader
constexpr uint16_t kHcNextHeader = 1 << 10 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcHopLimit1
constexpr uint16_t kHcHopLimit1 = 1 << 8 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcHopLimit64
constexpr uint16_t kHcHopLimit64 = 2 << 8 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcHopLimit255
constexpr uint16_t kHcHopLimit255 = 3 << 8 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcHopLimitMask
constexpr uint16_t kHcHopLimitMask = 3 << 8 static private
Referenced by Lowpan::DecompressBaseHeader().
kHcContextId
constexpr uint16_t kHcContextId = 1 << 7 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcSrcAddrContext
constexpr uint16_t kHcSrcAddrContext = 1 << 6 static private
Referenced by Lowpan::Compress(), and Lowpan::DecompressBaseHeader().
kHcSrcAddrMode0
constexpr uint16_t kHcSrcAddrMode0 = 0 << 4 static private
Referenced by Lowpan::DecompressBaseHeader().
kHcSrcAddrMode1
constexpr uint16_t kHcSrcAddrMode1 = 1 << 4 static private
Referenced by Lowpan::CompressSourceIid(), and Lowpan::DecompressBaseHeader().
kHcSrcAddrMode2
constexpr uint16_t kHcSrcAddrMode2 = 2 << 4 static private
Referenced by Lowpan::CompressSourceIid(), and Lowpan::DecompressBaseHeader().
kHcSrcAddrMode3
constexpr uint16_t kHcSrcAddrMode3 = 3 << 4 static private
Referenced by Lowpan::CompressSourceIid(), and Lowpan::DecompressBaseHeader().
kHcSrcAddrModeMask
constexpr uint16_t kHcSrcAddrModeMask = 3 << 4 static private
Referenced by Lowpan::DecompressBaseHeader().
kHcMulticast
constexpr uint16_t kHcMulticast = 1 << 3 static private
Referenced by Lowpan::CompressMulticast(), and Lowpan::DecompressBaseHeader().
kHcDstAddrContext
constexpr uint16_t kHcDstAddrContext = 1 << 2 static private
Referenced by Lowpan::Compress(), Lowpan::CompressMulticast(), and Lowpan::DecompressBaseHeader().
kHcDstAddrMode0
constexpr uint16_t kHcDstAddrMode0 = 0 << 0 static private
Referenced by Lowpan::CompressMulticast(), and Lowpan::DecompressBaseHeader().
kHcDstAddrMode1
constexpr uint16_t kHcDstAddrMode1 = 1 << 0 static private
Referenced by Lowpan::CompressDestinationIid(), Lowpan::CompressMulticast(), and Lowpan::DecompressBaseHeader().
kHcDstAddrMode2
constexpr uint16_t kHcDstAddrMode2 = 2 << 0 static private
Referenced by Lowpan::CompressDestinationIid(), Lowpan::CompressMulticast(), and Lowpan::DecompressBaseHeader().
kHcDstAddrMode3
constexpr uint16_t kHcDstAddrMode3 = 3 << 0 static private
Referenced by Lowpan::CompressDestinationIid(), Lowpan::CompressMulticast(), and Lowpan::DecompressBaseHeader().
kHcDstAddrModeMask
constexpr uint16_t kHcDstAddrModeMask = 3 << 0 static private
Referenced by Lowpan::DecompressBaseHeader().
kEcnOffset
constexpr uint8_t kEcnOffset = 6 static private
Referenced by Lowpan::DecompressEcn(), and Lowpan::MarkCompressedEcn().
kEcnMask
constexpr uint8_t kEcnMask = 3 << kEcnOffset static private
Referenced by Lowpan::DecompressEcn(), and Lowpan::MarkCompressedEcn().
kExtHdrDispatch
constexpr uint8_t kExtHdrDispatch = 0xe0 static private
Referenced by Lowpan::Compress(), Lowpan::CompressExtensionHeader(), Lowpan::Decompress(), and Lowpan::DispatchToNextHeader().
kExtHdrDispatchMask
constexpr uint8_t kExtHdrDispatchMask = 0xf0 static private
Referenced by Lowpan::Decompress(), and Lowpan::DispatchToNextHeader().
kExtHdrEidHbh
constexpr uint8_t kExtHdrEidHbh = 0x00 static private
Referenced by Lowpan::CompressExtensionHeader(), and Lowpan::DispatchToNextHeader().
kExtHdrEidRouting
constexpr uint8_t kExtHdrEidRouting = 0x02 static private
Referenced by Lowpan::DispatchToNextHeader().
kExtHdrEidFragment
constexpr uint8_t kExtHdrEidFragment = 0x04 static private
Referenced by Lowpan::DispatchToNextHeader().
kExtHdrEidDst
constexpr uint8_t kExtHdrEidDst = 0x06 static private
Referenced by Lowpan::DispatchToNextHeader().
kExtHdrEidMobility
constexpr uint8_t kExtHdrEidMobility = 0x08 static private
kExtHdrEidIp6
constexpr uint8_t kExtHdrEidIp6 = 0x0e static private
Referenced by Lowpan::Compress(), Lowpan::Decompress(), and Lowpan::DispatchToNextHeader().
kExtHdrEidMask
constexpr uint8_t kExtHdrEidMask = 0x0e static private
Referenced by Lowpan::Decompress(), and Lowpan::DispatchToNextHeader().
kExtHdrNextHeader
constexpr uint8_t kExtHdrNextHeader = 0x01 static private
Referenced by Lowpan::CompressExtensionHeader(), Lowpan::Decompress(), and Lowpan::DecompressExtensionHeader().
kExtHdrMaxLength
constexpr uint16_t kExtHdrMaxLength = 255 static private
Referenced by Lowpan::CompressExtensionHeader().
kUdpDispatch
constexpr uint8_t kUdpDispatch = 0xf0 static private
Referenced by Lowpan::CompressUdp(), Lowpan::Decompress(), Lowpan::DecompressUdpHeader(), and Lowpan::DispatchToNextHeader().
kUdpDispatchMask
constexpr uint8_t kUdpDispatchMask = 0xf8 static private
Referenced by Lowpan::Decompress(), Lowpan::DecompressUdpHeader(), and Lowpan::DispatchToNextHeader().
kUdpChecksum
constexpr uint8_t kUdpChecksum = 1 << 2 static private
Referenced by Lowpan::DecompressUdpHeader().
kUdpPortMask
constexpr uint8_t kUdpPortMask = 3 << 0 static private
Referenced by Lowpan::DecompressUdpHeader().
The documentation for this class was generated from the following files:
lowpan.hpp
lowpan.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale