OpenThread: FragmentHeader Class Reference
FragmentHeader Class Reference
Core-ipv6 » IPv6
#include <ip6_headers.hpp>
Public Member Functions
void ClearMoreFlag (void)
uint32_t GetIdentification (void) const
uint8_t GetNextHeader (void) const
uint16_t GetOffset (void) const
void Init (void)
bool IsMoreFlagSet (void) const
void SetIdentification (uint32_t aIdentification)
void SetMoreFlag (void)
void SetNextHeader (uint8_t aNextHeader)
void SetOffset (uint16_t aOffset)
Static Public Member Functions
static uint16_t BytesToFragmentOffset (uint16_t aOffset)
static uint16_t FragmentOffsetToBytes (uint16_t aOffset)
static uint16_t MakeDivisibleByEight (uint16_t aLength)
Private Attributes
uint32_t mIdentification
uint8_t mNextHeader
uint16_t mOffsetMore
uint8_t mReserved
Static Private Attributes
static constexpr uint16_t kMoreFlag = 1
static constexpr uint16_t kOffsetMask = 0xfff8
static constexpr uint8_t kOffsetOffset = 3
Detailed Description
This class implements IPv6 Fragment Header generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the IPv6 Fragment header.
Referenced by Ip6::HandleOptions().
GetNextHeader()
uint8_t GetNextHeader (void) const inline
This method returns the IPv6 Next Header value.
Returns
The IPv6 Next Header value.
References Header::mNextHeader.
Referenced by Ip6::HandleOptions().
SetNextHeader()
void SetNextHeader (uint8_t aNextHeader) inline
This method sets the IPv6 Next Header value.
Parameters
[in] aNextHeader The IPv6 Next Header value.
References Header::mNextHeader.
Referenced by Ip6::HandleOptions().
GetOffset()
uint16_t GetOffset (void) const inline
This method returns the Fragment Offset value.
Returns
The Fragment Offset value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Ip6::HandleFragment(), and Ip6::HandleOptions().
SetOffset()
void SetOffset (uint16_t aOffset) inline
This method sets the Fragment Offset value.
Parameters
[in] aOffset The Fragment Offset value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Ip6::HandleOptions().
IsMoreFlagSet()
bool IsMoreFlagSet (void) const inline
This method returns the M flag value.
Returns
The M flag value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Ip6::HandleFragment(), and Ip6::HandleOptions().
ClearMoreFlag()
void ClearMoreFlag (void) inline
This method clears the M flag value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Ip6::HandleOptions().
SetMoreFlag()
void SetMoreFlag (void) inline
This method sets the M flag value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Ip6::HandleOptions().
GetIdentification()
uint32_t GetIdentification (void) const inline
This method returns the frame identification.
Returns
The frame identification.
Referenced by Ip6::HandleOptions().
SetIdentification()
void SetIdentification (uint32_t aIdentification) inline
This method sets the frame identification.
Parameters
[in] aIdentification The fragment identification value.
Referenced by Ip6::HandleOptions().
MakeDivisibleByEight()
static uint16_t MakeDivisibleByEight (uint16_t aLength) inline static
This method returns the next valid payload length for a fragment.
Parameters
[in] aLength The payload length to be validated for a fragment.
Returns
Valid IPv6 fragment payload length.
Referenced by Ip6::HandleOptions().
FragmentOffsetToBytes()
static uint16_t FragmentOffsetToBytes (uint16_t aOffset) inline static
This method converts the fragment offset of 8-octet units into bytes.
Parameters
[in] aOffset The fragment offset in 8-octet units.
Returns
The fragment offset in bytes.
Referenced by Ip6::HandleOptions().
BytesToFragmentOffset()
static uint16_t BytesToFragmentOffset (uint16_t aOffset) inline static
This method converts a fragment offset in bytes into a fragment offset in 8-octet units.
Parameters
[in] aOffset The fragment offset in bytes.
Returns
The fragment offset in 8-octet units.
Referenced by Ip6::HandleOptions().
Field Documentation
kOffsetOffset
constexpr uint8_t kOffsetOffset = 3 static private
kOffsetMask
constexpr uint16_t kOffsetMask = 0xfff8 static private
kMoreFlag
constexpr uint16_t kMoreFlag = 1 static private
mNextHeader
uint8_t mNextHeader private
mReserved
uint8_t mReserved private
mOffsetMore
uint16_t mOffsetMore private
mIdentification
uint32_t mIdentification private
The documentation for this class was generated from the following file:
ip6_headers.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale