OpenThread: JoinerDiscerner Class Reference
JoinerDiscerner Class Reference
#include <meshcop.hpp>
Public Types
typedef String< kInfoStringSize > InfoString
Public Member Functions
void Clear (void)
void GenerateJoinerId (Mac::ExtAddress &aJoinerId) const
uint8_t GetLength (void) const
uint64_t GetValue (void) const
bool IsEmpty (void) const
bool IsValid (void) const
bool Matches (const Mac::ExtAddress &aJoinerId) const
bool operator== (const JoinerDiscerner &aOther) const
InfoString ToString (void) const
Public Member Functions inherited from Unequatable< JoinerDiscerner >
bool operator!= (const JoinerDiscerner &aOther) const
Static Public Attributes
static constexpr uint16_t kInfoStringSize = 45
Size of InfoString to use with `ToString()
static constexpr uint8_t kMaxLength = OT_JOINER_MAX_DISCERNER_LENGTH
Max length of a Discerner in bits.
Private Member Functions
void CopyTo (Mac::ExtAddress &aExtAddress) const
uint64_t GetMask (void) const
Friends
class SteeringData
Additional Inherited Members
Data Fields inherited from otJoinerDiscerner
uint8_t mLength
Length (number of bits) - must be non-zero and at most OT_JOINER_MAX_DISCERNER_LENGTH.
uint64_t mValue
Discerner value (the lowest mLength bits specify the discerner).
Detailed Description
This type represents a Joiner Discerner.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the Joiner Discerner.
IsEmpty()
bool IsEmpty (void) const inline
This method indicates whether the Joiner Discerner is empty (no value set).
Returns
TRUE if empty, FALSE otherwise.
GetValue()
uint64_t GetValue (void) const inline
This method gets the Joiner Discerner's value.
Returns
The Joiner Discerner value.
GetLength()
uint8_t GetLength (void) const inline
This method gets the Joiner Discerner's length (in bits).
Returns
The Joiner Discerner length.
IsValid()
bool IsValid (void) const inline
This method indicates whether the Joiner Discerner is valid (i.e. it not empty and its length is within valid range).
Returns
TRUE if Joiner Discerner is valid, FALSE otherwise.
References JoinerPskd::kMaxLength, and JoinerPskd::operator==().
GenerateJoinerId()
void GenerateJoinerId (Mac::ExtAddress & aJoinerId) const
This method generates a Joiner ID from the Discerner.
Parameters
[out] aJoinerId A reference to Mac::ExtAddress to output the generated Joiner ID.
References ExtAddress::GenerateRandom(), and ExtAddress::SetLocal().
Matches()
bool Matches (const Mac::ExtAddress & aJoinerId) const
This method indicates whether a given Joiner ID matches the Discerner.
Parameters
[in] aJoinerId A Joiner ID to match with the Discerner.
Returns
TRUE if the Joiner ID matches the Discerner, FALSE otherwise.
References JoinerPskd::IsValid(), otExtAddress::m8, OT_ASSERT, and ot::Encoding::BigEndian::ReadUint64().
operator==()
bool operator== (const JoinerDiscerner & aOther) const
This method overloads operator == to evaluate whether or not two Joiner Discerner instances are equal.
Parameters
[in] aOther The other Joiner Discerner to compare with.
Return values
TRUE If the two are equal.
FALSE If the two are not equal.
References JoinerPskd::IsValid(), otJoinerDiscerner::mLength, and otJoinerDiscerner::mValue.
ToString()
JoinerDiscerner::InfoString ToString (void) const
This method converts the Joiner Discerner to a string.
Returns
An InfoString representation of Joiner Discerner.
References StringWriter::Append().
GetMask()
uint64_t GetMask (void) const inline private
CopyTo()
void CopyTo (Mac::ExtAddress & aExtAddress) const private
References JoinerPskd::IsValid(), otExtAddress::m8, and OT_ASSERT.
Referenced by SteeringData::CalculateHashBitIndexes().
Friends And Related Function Documentation
SteeringData
friend class SteeringData friend
Field Documentation
kMaxLength
constexpr uint8_t kMaxLength = OT_JOINER_MAX_DISCERNER_LENGTH static
Max length of a Discerner in bits.
kInfoStringSize
constexpr uint16_t kInfoStringSize = 45 static
Size of InfoString to use with `ToString()
The documentation for this class was generated from the following files:
meshcop.hpp
meshcop.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale