OpenThread: Settings Class Reference
Settings Class Reference
#include <settings.hpp>
Public Member Functions
void Deinit (void)
template<typename EntryType >
Error Delete (void)
Error DeleteOperationalDataset (MeshCoP::Dataset::Type aType)
void Init (void)
template<typename EntryType >
Error Read (EntryType &aEntry) const
template<typename EntryType >
Error Read (typename EntryType::ValueType &aValue) const
Error ReadOperationalDataset (MeshCoP::Dataset::Type aType, MeshCoP::Dataset &aDataset) const
template<typename EntryType >
Error Save (const EntryType &aEntry)
template<typename EntryType >
Error Save (const typename EntryType::ValueType &aValue)
Error SaveOperationalDataset (MeshCoP::Dataset::Type aType, const MeshCoP::Dataset &aDataset)
Settings (Instance &aInstance)
void Wipe (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
Error DeleteEntry (Key aKey)
Error ReadEntry (Key aKey, void *aValue, uint16_t aMaxLength) const
Error SaveEntry (Key aKey, const void *aValue, void *aPrev, uint16_t aLength)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static Key KeyForDatasetType (MeshCoP::Dataset::Type aType)
static void Log (Action aAction, Error aError, Key aKey, const void *aValue=nullptr)
Static Private Attributes
static const uint16_t kSensitiveKeys []
Additional Inherited Members
Public Types inherited from SettingsBase
enum Key : uint16_t {
kKeyActiveDataset = OT_SETTINGS_KEY_ACTIVE_DATASET, kKeyPendingDataset = OT_SETTINGS_KEY_PENDING_DATASET, kKeyNetworkInfo = OT_SETTINGS_KEY_NETWORK_INFO, kKeyParentInfo = OT_SETTINGS_KEY_PARENT_INFO,
kKeyChildInfo = OT_SETTINGS_KEY_CHILD_INFO, kKeySlaacIidSecretKey = OT_SETTINGS_KEY_SLAAC_IID_SECRET_KEY, kKeyDadInfo = OT_SETTINGS_KEY_DAD_INFO, kKeySrpEcdsaKey = OT_SETTINGS_KEY_SRP_ECDSA_KEY,
kKeySrpClientInfo = OT_SETTINGS_KEY_SRP_CLIENT_INFO, kKeySrpServerInfo = OT_SETTINGS_KEY_SRP_SERVER_INFO, kKeyBrUlaPrefix = OT_SETTINGS_KEY_BR_ULA_PREFIX
}
Data Fields inherited from SettingsBase
ot::SettingsBase::NetworkInfo OT_TOOL_PACKED_END
ot::SettingsBase::ParentInfo OT_TOOL_PACKED_END
Static Public Attributes inherited from SettingsBase
static constexpr Key kLastKey = kKeyBrUlaPrefix
The last (numerically) enumerator value in Key.
Protected Types inherited from SettingsBase
enum Action : uint8_t { kActionRead, kActionSave, kActionResave, kActionDelete }
Protected Member Functions inherited from SettingsBase
SettingsBase (Instance &aInstance)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class defines methods related to non-volatile storage of settings.
Constructor & Destructor Documentation
Settings()
Settings (Instance & aInstance) inline explicit
This constructor initializes a Settings object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References SettingsBase::NetworkInfo::Init().
Member Function Documentation
Init()
void Init (void)
This method initializes the platform settings (non-volatile) module.
This should be called before any other method from this class.
References ot::GetArrayLength(), and SettingsBase::NetworkInfo::Init().
Deinit()
void Deinit (void)
This method de-initializes the platform settings (non-volatile) module.
This method should be called when OpenThread instance is no longer in use.
Wipe()
void Wipe (void)
This method removes all settings from the non-volatile store.
References LogInfo.
SaveOperationalDataset()
Error SaveOperationalDataset (MeshCoP::Dataset::Type aType, const MeshCoP::Dataset & aDataset)
This method saves the Operational Dataset (active or pending).
Parameters
[in] aType The Dataset type (active or pending) to save.
[in] aDataset A reference to a Dataset object to be saved.
Return values
kErrorNone Successfully saved the Dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References Dataset::GetBytes(), Dataset::GetSize(), SettingsBase::kActionSave, and SettingsBase::NetworkInfo::Log().
ReadOperationalDataset()
Error ReadOperationalDataset (MeshCoP::Dataset::Type aType, MeshCoP::Dataset & aDataset) const
This method reads the Operational Dataset (active or pending).
Parameters
[in] aType The Dataset type (active or pending) to read.
[out] aDataset A reference to a Dataset object to output the read content.
Return values
kErrorNone Successfully read the Dataset.
kErrorNotFound No corresponding value in the setting store.
kErrorNotImplemented The platform does not implement settings functionality.
References GetProvider< InstanceLocator >::Get(), Dataset::GetBytes(), ot::kErrorNone, ot::kErrorNotFound, Dataset::kMaxSize, Dataset::SetSize(), SuccessOrExit, and VerifyOrExit.
DeleteOperationalDataset()
Error DeleteOperationalDataset (MeshCoP::Dataset::Type aType)
This method deletes the Operational Dataset (active/pending) from settings.
Parameters
[in] aType The Dataset type (active or pending) to delete.
Return values
kErrorNone Successfully deleted the Dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References GetProvider< InstanceLocator >::Get(), SettingsBase::kActionDelete, SettingsBase::kActionRead, ot::kErrorInvalidState, ot::kErrorNone, SettingsBase::kKeyChildInfo, SettingsBase::NetworkInfo::Log(), SettingsBase::SettingsBase(), SuccessOrExit, and VerifyOrExit.
Read() [1/2]
Error Read (EntryType & aEntry) const inline
This template method reads a specified settings entry.
The template type EntryType specifies the entry's value data structure. It must provide the following:
It must provide a constant EntryType::kKey to specify the associated entry settings key.
It must provide method Init() to initialize the aEntry object.
This version of Read<EntryType> is intended for use with entries that define a data structure which represents the entry's value, e.g., NetworkInfo, ParentInfo, DadInfo, etc.
Template Parameters
EntryType The settings entry type.
Parameters
[out] aEntry A reference to a entry data structure to output the read content.
Return values
kErrorNone Successfully read the entry.
kErrorNotFound No corresponding value in the setting store.
kErrorNotImplemented The platform does not implement settings functionality.
Read() [2/2]
Error Read (typename EntryType::ValueType & aValue) const inline
This template method reads a specified settings entry.
The template type EntryType provides information about the entry's value type. It must provide the following:
It must provide a constant EntryType::kKey to specify the associated entry settings key.
It must provide a nested type EntryType::ValueType to specify the associated entry value type.
This version of Read<EntryType> is intended for use with entries that have a simple entry value type (which can be represented by an existing type), e.g., OmrPrefix (using Ip6::Prefix as the value type).
Template Parameters
EntryType The settings entry type.
Parameters
[out] aValue A reference to a value type object to output the read content.
Return values
kErrorNone Successfully read the value.
kErrorNotFound No corresponding value in the setting store.
kErrorNotImplemented The platform does not implement settings functionality.
Save() [1/2]
Error Save (const EntryType & aEntry) inline
This template method saves a specified settings entry.
The template type EntryType specifies the entry's value data structure. It must provide the following:
It must provide a constant EntryType::kKey to specify the associated entry settings key.
This version of Save<EntryType> is intended for use with entries that define a data structure which represents the entry's value, e.g., NetworkInfo, ParentInfo, DadInfo, etc.
Template Parameters
EntryType The settings entry type.
Parameters
[in] aEntry The entry value to be saved.
Return values
kErrorNone Successfully saved Network Info in settings.
kErrorNotImplemented The platform does not implement settings functionality.
Save() [2/2]
Error Save (const typename EntryType::ValueType & aValue) inline
This template method saves a specified settings entry.
The template type EntryType provides information about the entry's value type. It must provide the following:
It must provide a constant EntryType::kKey to specify the associated entry settings key.
It must provide a nested type EntryType::ValueType to specify the associated entry value type.
This version of Save<EntryType> is intended for use with entries that have a simple entry value type (which can be represented by an existing type), e.g., OmrPrefix (using Ip6::Prefix as the value type).
Template Parameters
EntryType The settings entry type.
Parameters
[in] aValue The entry value to be saved.
Return values
kErrorNone Successfully saved Network Info in settings.
kErrorNotImplemented The platform does not implement settings functionality.
Delete()
Error Delete (void) inline
This template method deletes a specified setting entry.
The template type EntryType provides information about the entry's key.
It must provide a constant EntryType::kKey to specify the associated entry settings key.
Template Parameters
EntryType The settings entry type.
Return values
kErrorNone Successfully deleted the value.
kErrorNotImplemented The platform does not implement settings functionality.
References InstanceLocator::GetInstance(), InstanceLocator::InstanceLocator(), SettingsBase::NetworkInfo::Log(), and SettingsBase::SettingsBase().
KeyForDatasetType()
Settings::Key KeyForDatasetType (MeshCoP::Dataset::Type aType) static private
References Dataset::kActive, SettingsBase::kKeyActiveDataset, and SettingsBase::kKeyPendingDataset.
ReadEntry()
Error ReadEntry (Key aKey, void * aValue, uint16_t aMaxLength) const private
References GetProvider< InstanceLocator >::Get(), SettingsBase::kActionRead, and SettingsBase::NetworkInfo::Log().
SaveEntry()
Error SaveEntry (Key aKey, const void * aValue, void * aPrev, uint16_t aLength) private
References GetProvider< InstanceLocator >::Get(), SettingsBase::kActionResave, SettingsBase::kActionSave, ot::kErrorNone, and SettingsBase::NetworkInfo::Log().
DeleteEntry()
Error DeleteEntry (Key aKey) private
References SettingsBase::kActionDelete, and SettingsBase::NetworkInfo::Log().
Log()
void Log (Action aAction, Error aError, Key aKey, const void * aValue = nullptr) static private
References ot::ErrorToString(), ExitNow, SettingsBase::kActionDelete, SettingsBase::kActionRead, SettingsBase::kActionResave, SettingsBase::kActionSave, ot::kErrorNone, ot::kErrorNotFound, SettingsBase::kKeyBrUlaPrefix, SettingsBase::kKeyChildInfo, SettingsBase::kKeyDadInfo, SettingsBase::kKeyNetworkInfo, SettingsBase::kKeyParentInfo, SettingsBase::kKeySrpClientInfo, SettingsBase::kKeySrpServerInfo, SettingsBase::NetworkInfo::Log(), LogInfo, LogWarn, OT_UNUSED_VARIABLE, and VerifyOrExit.
Field Documentation
kSensitiveKeys
const uint16_t kSensitiveKeys static private
Initial value:
= {
    SettingsBase::kKeyActiveDataset,
    SettingsBase::kKeyPendingDataset,
    SettingsBase::kKeySrpEcdsaKey,
}
The documentation for this class was generated from the following files:
core/common/settings.hpp
core/common/settings.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale