OpenThread: ThreadLinkInfo Class Reference
ThreadLinkInfo Class Reference
Core-mesh-forwarding
#include <mesh_forwarder.hpp>
Public Member Functions
uint8_t GetChannel (void) const
uint8_t GetLqi (void) const
Mac::PanId GetPanId (void) const
int8_t GetRss (void) const
bool IsDstPanIdBroadcast (void) const
bool IsLinkSecurityEnabled (void) const
void SetFrom (const Mac::RxFrame &aFrame)
Public Member Functions inherited from Clearable< ThreadLinkInfo >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otThreadLinkInfo
uint8_t mChannel
802.15.4 Channel
bool mIsDstPanIdBroadcast: 1
Indicates whether or not destination PAN ID is broadcast.
bool mLinkSecurity: 1
Indicates whether or not link security is enabled.
uint8_t mLqi
Link Quality Indicator for a received message.
int64_t mNetworkTimeOffset
The time offset to the Thread network time, in microseconds.
uint16_t mPanId
Source PAN ID.
uint8_t mRadioType
Radio link type.
int8_t mRss
Received Signal Strength in dBm.
uint8_t mTimeSyncSeq
The time sync sequence.
Detailed Description
This class represents link-specific information for messages received from the Thread radio.
Member Function Documentation
GetPanId()
Mac::PanId GetPanId (void) const inline
This method returns the IEEE 802.15.4 Source PAN ID.
Returns
The IEEE 802.15.4 Source PAN ID.
GetChannel()
uint8_t GetChannel (void) const inline
This method returns the IEEE 802.15.4 Channel.
Returns
The IEEE 802.15.4 Channel.
IsDstPanIdBroadcast()
bool IsDstPanIdBroadcast (void) const inline
This method returns whether the Destination PAN ID is broadcast.
Return values
TRUE If Destination PAN ID is broadcast.
FALSE If Destination PAN ID is not broadcast.
Referenced by Mle::HandleUdpReceive().
IsLinkSecurityEnabled()
bool IsLinkSecurityEnabled (void) const inline
This method indicates whether or not link security is enabled.
Return values
TRUE If link security is enabled.
FALSE If link security is not enabled.
Referenced by MeshForwarder::HandleFragment(), MeshForwarder::HandleLowpanHC(), and MeshForwarder::HandleReceivedFrame().
GetRss()
int8_t GetRss (void) const inline
This method returns the Received Signal Strength (RSS) in dBm.
Returns
The Received Signal Strength (RSS) in dBm.
Referenced by MeshForwarder::HandleFragment(), and Mle::HandleParentResponse().
GetLqi()
uint8_t GetLqi (void) const inline
This method returns the frame/radio Link Quality Indicator (LQI) value.
Returns
The Link Quality Indicator value.
Referenced by MeshForwarder::HandleFragment().
SetFrom()
void SetFrom (const Mac::RxFrame & aFrame)
This method sets the ThreadLinkInfo from a given received frame.
Parameters
[in] aFrame A received frame.
References Clearable< ThreadLinkInfo >::Clear(), Frame::GetChannel(), Frame::GetDstPanId(), RxFrame::GetLqi(), RxFrame::GetRssi(), Frame::GetSecurityEnabled(), Frame::GetSrcPanId(), IgnoreError(), ot::kErrorNone, ot::Mac::kPanIdBroadcast, otThreadLinkInfo::mChannel, otThreadLinkInfo::mIsDstPanIdBroadcast, otThreadLinkInfo::mLinkSecurity, otThreadLinkInfo::mLqi, otThreadLinkInfo::mNetworkTimeOffset, otThreadLinkInfo::mPanId, otThreadLinkInfo::mRadioType, otThreadLinkInfo::mRss, and otThreadLinkInfo::mTimeSyncSeq.
Referenced by MeshForwarder::HandleReceivedFrame().
The documentation for this class was generated from the following files:
mesh_forwarder.hpp
mesh_forwarder.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale