OpenThread: AnnounceBeginServer Class Reference
AnnounceBeginServer Class Reference
#include <announce_begin_server.hpp>
Public Member Functions
AnnounceBeginServer (Instance &aInstance)
void SendAnnounce (uint32_t aChannelMask, uint8_t aCount=kDefaultCount, uint16_t aPeriod=kDefaultPeriod)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void HandleRequest (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Static Private Member Functions
static void HandleRequest (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleTimer (Timer &aTimer)
Private Attributes
Coap::Resource mAnnounceBegin
Static Private Attributes
static constexpr uint8_t kDefaultCount = 3
static constexpr uint16_t kDefaultJitter = 0
static constexpr uint16_t kDefaultPeriod = 1000
Additional Inherited Members
Protected Member Functions inherited from AnnounceSenderBase
AnnounceSenderBase (Instance &aInstance, Timer::Handler aHandler)
const Mac::ChannelMask GetChannelMask (void) const
uint16_t GetJitter (void) const
uint32_t GetPeriod (void) const
uint8_t GetStartingChannel (void) const
void HandleTimer (void)
bool IsRunning (void) const
void SendAnnounce (uint8_t aCount)
void SetChannelMask (Mac::ChannelMask aChannelMask)
void SetJitter (uint16_t aJitter)
void SetPeriod (uint32_t aPeriod)
void SetStartingChannel (uint8_t aStartingChannel)
void Stop (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Static Protected Attributes inherited from AnnounceSenderBase
static constexpr uint8_t kChannelIteratorFirst = Mac::ChannelMask::kChannelIteratorFirst
Detailed Description
This class implements handling Announce Begin Requests.
Constructor & Destructor Documentation
AnnounceBeginServer()
AnnounceBeginServer (Instance & aInstance) explicit
This constructor initializes the object.
References AnnounceBeginServer::mAnnounceBegin.
Member Function Documentation
SendAnnounce()
void SendAnnounce (uint32_t aChannelMask, uint8_t aCount = kDefaultCount, uint16_t aPeriod = kDefaultPeriod)
This method begins the MLE Announce transmission process.
Parameters
[in] aChannelMask The channels to use for transmission.
[in] aCount The number of transmissions per channel.
[in] aPeriod The time between transmissions (milliseconds).
References AnnounceBeginServer::kDefaultJitter, AnnounceSenderBase::SendAnnounce(), AnnounceSenderBase::SetChannelMask(), AnnounceSenderBase::SetJitter(), and AnnounceSenderBase::SetPeriod().
Referenced by AnnounceBeginServer::HandleRequest().
HandleRequest() [1/2]
void HandleRequest (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References ot::AsCoapMessage(), and ot::AsCoreType().
HandleRequest() [2/2]
void HandleRequest (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ChannelMaskTlv::GetChannelMask(), MessageInfo::GetSockAddr(), Message::IsConfirmable(), Address::IsMulticast(), Message::IsPostRequest(), LogInfo, AnnounceBeginServer::SendAnnounce(), SuccessOrExit, and VerifyOrExit.
HandleTimer()
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and AnnounceSenderBase::HandleTimer().
Field Documentation
kDefaultCount
constexpr uint8_t kDefaultCount = 3 static private
kDefaultPeriod
constexpr uint16_t kDefaultPeriod = 1000 static private
kDefaultJitter
constexpr uint16_t kDefaultJitter = 0 static private
Referenced by AnnounceBeginServer::SendAnnounce().
mAnnounceBegin
Coap::Resource mAnnounceBegin private
Referenced by AnnounceBeginServer::AnnounceBeginServer().
The documentation for this class was generated from the following files:
announce_begin_server.hpp
announce_begin_server.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale