OpenThread: ConnectivityTlv Class Reference
ConnectivityTlv Class Reference
MLE » TLVs
#include <network_diagnostic_tlvs.hpp>
Public Member Functions
uint8_t GetActiveRouters (void) const
uint8_t GetIdSequence (void) const
uint8_t GetLeaderCost (void) const
uint8_t GetLinkQuality1 (void) const
uint8_t GetLinkQuality2 (void) const
uint8_t GetLinkQuality3 (void) const
int8_t GetParentPriority (void) const
uint16_t GetSedBufferSize (void) const
uint8_t GetSedDatagramCount (void) const
void Init (void)
bool IsSedBufferingIncluded (void) const
bool IsValid (void) const
void SetActiveRouters (uint8_t aActiveRouters)
void SetIdSequence (uint8_t aSequence)
void SetLeaderCost (uint8_t aCost)
void SetLinkQuality1 (uint8_t aLinkQuality)
void SetLinkQuality2 (uint8_t aLinkQuality)
void SetLinkQuality3 (uint8_t aLinkQuality)
void SetParentPriority (int8_t aParentPriority)
void SetSedBufferSize (uint16_t aSedBufferSize)
void SetSedDatagramCount (uint8_t aSedDatagramCount)
Public Member Functions inherited from NetworkDiagnosticTlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint8_t mActiveRouters
uint8_t mIdSequence
uint8_t mLeaderCost
uint8_t mLinkQuality1
uint8_t mLinkQuality2
uint8_t mLinkQuality3
uint8_t mParentPriority
uint16_t mSedBufferSize
uint8_t mSedDatagramCount
Static Private Attributes
static constexpr uint8_t kParentPriorityMask = 3 << kParentPriorityOffset
static constexpr uint8_t kParentPriorityOffset = 6
Additional Inherited Members
Public Types inherited from NetworkDiagnosticTlv
enum Type : uint8_t {
kExtMacAddress = OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS, kAddress16 = OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS, kMode = OT_NETWORK_DIAGNOSTIC_TLV_MODE, kTimeout = OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT,
kConnectivity = OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY, kRoute = OT_NETWORK_DIAGNOSTIC_TLV_ROUTE, kLeaderData = OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA, kNetworkData = OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA,
kIp6AddressList = OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST, kMacCounters = OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS, kBatteryLevel = OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL, kSupplyVoltage = OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE,
kChildTable = OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE, kChannelPages = OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES, kTypeList = OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST, kMaxChildTimeout = OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
}
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< NetworkDiagnosticTlv::kConnectivity >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements Connectivity TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References NetworkDiagnosticTlv::kConnectivity, Tlv::SetLength(), and NetworkDiagnosticTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
IsSedBufferingIncluded()
bool IsSedBufferingIncluded (void) const inline
This method indicates whether or not the sed buffer size and datagram count are included.
Return values
TRUE If the sed buffer size and datagram count are included.
FALSE If the sed buffer size and datagram count are not included.
References Tlv::GetLength().
GetParentPriority()
int8_t GetParentPriority (void) const inline
This method returns the Parent Priority value.
Returns
The Parent Priority value.
SetParentPriority()
void SetParentPriority (int8_t aParentPriority) inline
This method sets the Parent Priority value.
Parameters
[in] aParentPriority The Parent Priority value.
GetLinkQuality3()
uint8_t GetLinkQuality3 (void) const inline
This method returns the Link Quality 3 value.
Returns
The Link Quality 3 value.
SetLinkQuality3()
void SetLinkQuality3 (uint8_t aLinkQuality) inline
This method sets the Link Quality 3 value.
Parameters
[in] aLinkQuality The Link Quality 3 value.
GetLinkQuality2()
uint8_t GetLinkQuality2 (void) const inline
This method returns the Link Quality 2 value.
Returns
The Link Quality 2 value.
SetLinkQuality2()
void SetLinkQuality2 (uint8_t aLinkQuality) inline
This method sets the Link Quality 2 value.
Parameters
[in] aLinkQuality The Link Quality 2 value.
GetLinkQuality1()
uint8_t GetLinkQuality1 (void) const inline
This method sets the Link Quality 1 value.
Returns
The Link Quality 1 value.
SetLinkQuality1()
void SetLinkQuality1 (uint8_t aLinkQuality) inline
This method sets the Link Quality 1 value.
Parameters
[in] aLinkQuality The Link Quality 1 value.
GetActiveRouters()
uint8_t GetActiveRouters (void) const inline
This method sets the Active Routers value.
Returns
The Active Routers value.
SetActiveRouters()
void SetActiveRouters (uint8_t aActiveRouters) inline
This method sets the Active Routers value.
Parameters
[in] aActiveRouters The Active Routers value.
GetLeaderCost()
uint8_t GetLeaderCost (void) const inline
This method returns the Leader Cost value.
Returns
The Leader Cost value.
SetLeaderCost()
void SetLeaderCost (uint8_t aCost) inline
This method sets the Leader Cost value.
Parameters
[in] aCost The Leader Cost value.
GetIdSequence()
uint8_t GetIdSequence (void) const inline
This method returns the ID Sequence value.
Returns
The ID Sequence value.
SetIdSequence()
void SetIdSequence (uint8_t aSequence) inline
This method sets the ID Sequence value.
Parameters
[in] aSequence The ID Sequence value.
GetSedBufferSize()
uint16_t GetSedBufferSize (void) const inline
This method returns the SED Buffer Size value.
Returns
The SED Buffer Size value.
References ot::Encoding::BigEndian::HostSwap16(), and OPENTHREAD_CONFIG_DEFAULT_SED_BUFFER_SIZE.
SetSedBufferSize()
void SetSedBufferSize (uint16_t aSedBufferSize) inline
This method sets the SED Buffer Size value.
Parameters
[in] aSedBufferSize The SED Buffer Size value.
References ot::Encoding::BigEndian::HostSwap16().
GetSedDatagramCount()
uint8_t GetSedDatagramCount (void) const inline
This method returns the SED Datagram Count value.
Returns
The SED Datagram Count value.
References OPENTHREAD_CONFIG_DEFAULT_SED_DATAGRAM_COUNT.
SetSedDatagramCount()
void SetSedDatagramCount (uint8_t aSedDatagramCount) inline
This method sets the SED Datagram Count value.
Parameters
[in] aSedDatagramCount The SED Datagram Count value.
Field Documentation
kParentPriorityOffset
constexpr uint8_t kParentPriorityOffset = 6 static private
kParentPriorityMask
constexpr uint8_t kParentPriorityMask = 3 << kParentPriorityOffset static private
mParentPriority
uint8_t mParentPriority private
mLinkQuality3
uint8_t mLinkQuality3 private
mLinkQuality2
uint8_t mLinkQuality2 private
mLinkQuality1
uint8_t mLinkQuality1 private
mLeaderCost
uint8_t mLeaderCost private
mIdSequence
uint8_t mIdSequence private
mActiveRouters
uint8_t mActiveRouters private
mSedBufferSize
uint16_t mSedBufferSize private
mSedDatagramCount
uint8_t mSedDatagramCount private
The documentation for this class was generated from the following file:
network_diagnostic_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale