OpenThread: Timer Class Reference
Timer Class Reference
Core-timer
#include <timer.hpp>
Data Structures
class Scheduler
Public Types
typedef void(&) Handler(Timer &aTimer)
Public Member Functions
Time GetFireTime (void) const
bool IsRunning (void) const
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Public Member Functions inherited from LinkedListEntry< Timer >
const Timer * GetNext (void) const
Timer * GetNext (void)
void SetNext (Timer *aNext)
Static Public Attributes
static const uint32_t kMaxDelay = (Time::kMaxDuration >> 1)
Protected Member Functions
bool DoesFireBefore (const Timer &aSecondTimer, Time aNow) const
void Fired (void)
Timer (Instance &aInstance, Handler aHandler)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Protected Attributes
Time mFireTime
Handler mHandler
Timer * mNext
Friends
class LinkedListEntry< Timer >
Detailed Description
This class implements a timer.
Member Typedef Documentation
Handler
typedef void(&) Handler(Timer &aTimer)
This type defines a function reference which is invoked when the timer expires.
Parameters
[in] aTimer A reference to the expired timer instance.
Constructor & Destructor Documentation
Timer()
Timer (Instance & aInstance, Handler aHandler) inline protected
References Timer::DoesFireBefore().
Member Function Documentation
GetFireTime()
Time GetFireTime (void) const inline
This method returns the fire time of the timer.
Returns
The fire time.
References Timer::mFireTime.
Referenced by Timer::DoesFireBefore(), PendingDatasetManager::HandleDelayTimer(), KeyManager::HandleKeyRotationTimer(), TimeTicker::HandleTimer(), and SubMac::SampleRssi().
IsRunning()
bool IsRunning (void) const inline
This method indicates whether or not the timer instance is running.
Return values
TRUE If the timer is running.
FALSE If the timer is not running.
References Timer::mNext.
Referenced by CoapBase::DequeueMessage(), TimerMilli::FireAtIfEarlier(), Mle::IsDetachingGracefully(), TrickleTimer::IsRunning(), AnnounceSenderBase::IsRunning(), TimeTicker::RegisterReceiver(), Timer::Scheduler::Remove(), DataPollSender::ResetKeepAliveTimer(), DataPollSender::ScheduleNextPoll(), KeyManager::SetCurrentKeySequence(), and Mpl::UpdateSeedSet().
DoesFireBefore()
bool DoesFireBefore (const Timer & aSecondTimer, Time aNow) const protected
References Timer::GetFireTime().
Referenced by Timer::Scheduler::Add(), and Timer::Timer().
Fired()
void Fired (void) inline protected
References Timer::mHandler.
Referenced by Timer::Scheduler::ProcessTimers().
Friends And Related Function Documentation
LinkedListEntry< Timer >
friend class LinkedListEntry< Timer > friend
Field Documentation
kMaxDelay
const uint32_t kMaxDelay = (Time::kMaxDuration >> 1) static
This constant defines maximum delay allowed when starting a timer.
Referenced by otPlatAlarmMilliFired(), TimerMilli::StartAt(), and PendingDatasetManager::StartDelayTimer().
mHandler
Handler mHandler protected
Referenced by Timer::Fired().
mFireTime
Time mFireTime protected
Referenced by TimerMilli::FireAt(), TimerMilli::FireAtIfEarlier(), Timer::GetFireTime(), otPlatAlarmMilliFired(), Timer::Scheduler::ProcessTimers(), and Timer::Scheduler::SetAlarm().
mNext
Timer* mNext protected
Referenced by Timer::IsRunning().
The documentation for this class was generated from the following files:
timer.hpp
timer.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale