OpenThread: MeshHeader Class Reference
MeshHeader Class Reference
Core-6lowpan
#include <lowpan.hpp>
Public Member Functions
Error AppendTo (FrameBuilder &aFrameBuilder) const
Error AppendTo (Message &aMessage) const
void DecrementHopsLeft (void)
uint16_t GetDestination (void) const
uint16_t GetHeaderLength (void) const
uint8_t GetHopsLeft (void) const
uint16_t GetSource (void) const
void Init (uint16_t aSource, uint16_t aDestination, uint8_t aHopsLeft)
Error ParseFrom (const uint8_t *aFrame, uint16_t aFrameLength, uint16_t &aHeaderLength)
Error ParseFrom (FrameData &aFrameData)
Error ParseFrom (const Message &aMessage)
Error ParseFrom (const Message &aMessage, uint16_t &aHeaderLength)
Static Public Member Functions
static bool IsMeshHeader (const FrameData &aFrameData)
Static Public Attributes
static constexpr uint8_t kAdditionalHopsLeft = 1
Private Attributes
uint16_t mDestination
uint8_t mHopsLeft
uint16_t mSource
Static Private Attributes
static constexpr uint16_t kDeepHopsHeaderLength = kMinHeaderLength + sizeof(uint8_t)
static constexpr uint8_t kDeepHopsLeft = 0x0f
static constexpr uint8_t kDestShort = 1 << 4
static constexpr uint8_t kDispatch = 2 << 6
static constexpr uint8_t kDispatchMask = 3 << 6
static constexpr uint8_t kHopsLeftMask = 0x0f
static constexpr uint16_t kMinHeaderLength = sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t)
static constexpr uint8_t kSourceShort = 1 << 5
Detailed Description
This class implements Mesh Header generation and processing.
Member Function Documentation
Init()
void Init (uint16_t aSource, uint16_t aDestination, uint8_t aHopsLeft)
This method initializes the Mesh Header with a given Mesh Source, Mesh Destination and Hops Left value.
Parameters
[in] aSource The Mesh Source address.
[in] aDestination The Mesh Destination address.
[in] aHopsLeft The Hops Left value.
IsMeshHeader()
bool IsMeshHeader (const FrameData & aFrameData) static
This static method indicates whether or not the header (in a given frame) is a Mesh Header.
Note
This method checks whether the first byte in header/frame (dispatch byte) matches the Mesh Header dispatch It does not fully parse and validate the Mesh Header. ParseFrom() method can be used to fully parse and validate the header.
Return values
TRUE If the header matches the Mesh Header dispatch value.
FALSE If the header does not match the Mesh Header dispatch value.
References Data< kDataLengthType >::GetBytes(), and Data< kDataLengthType >::GetLength().
Referenced by MeshForwarder::HandleReceivedFrame().
ParseFrom() [1/4]
Error ParseFrom (const uint8_t * aFrame, uint16_t aFrameLength, uint16_t & aHeaderLength)
This method parses the Mesh Header from a frame aFrame.
Parameters
[in] aFrame The pointer to the frame.
[in] aFrameLength The length of the frame.
[out] aHeaderLength A reference to a variable to output the parsed header length (on success).
Return values
kErrorNone Mesh Header parsed successfully.
kErrorParse Mesh Header could not be parsed.
References ot::kErrorNone, ot::kErrorParse, ot::Encoding::BigEndian::ReadUint16(), and VerifyOrExit.
Referenced by MeshForwarder::ResumeMessageTransmissions().
ParseFrom() [2/4]
Error ParseFrom (FrameData & aFrameData)
This method parses the Mesh Header from a given frame data.
If the Mesh Header is parsed successfully the aFrameData is updated to skip over the parsed header bytes.
Parameters
[in,out] aFrameData The frame data to parse from.
Return values
kErrorNone Mesh Header parsed successfully. aFrameData is updated to skip over parsed header.
kErrorParse Mesh Header could not be parsed.
References Data< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), FrameData::SkipOver(), and SuccessOrExit.
ParseFrom() [3/4]
Error ParseFrom (const Message & aMessage)
This method parses the Mesh Header from a given message.
Note
The Mesh Header is read from offset zero within the aMessage.
Parameters
[in] aMessage The message to read from.
Return values
kErrorNone Mesh Header parsed successfully.
kErrorParse Mesh Header could not be parsed.
ParseFrom() [4/4]
Error ParseFrom (const Message & aMessage, uint16_t & aHeaderLength)
This method parses the Mesh Header from a given message.
Note
The Mesh Header is read from offset zero within the aMessage.
Parameters
[in] aMessage The message to read from.
[out] aHeaderLength A reference to a variable to output the parsed header length (on success).
Return values
kErrorNone Mesh Header parsed successfully.
kErrorParse Mesh Header could not be parsed.
References Message::ReadBytes().
GetHeaderLength()
uint16_t GetHeaderLength (void) const
This method returns the the Mesh Header length when written to a frame.
Note
The returned value from this method gives the header length (number of bytes) when the header is written to a frame or message. This should not be used to determine the parsed length (number of bytes read) when the Mesh Header is parsed from a frame/message (using ParseFrom() methods).
Returns
The length of the Mesh Header (in bytes) when written to a frame.
GetHopsLeft()
uint8_t GetHopsLeft (void) const inline
This method returns the Hops Left value.
Returns
The Hops Left value.
DecrementHopsLeft()
void DecrementHopsLeft (void)
This method decrements the Hops Left value (if it is not zero).
GetSource()
uint16_t GetSource (void) const inline
This method returns the Mesh Source address.
Returns
The Mesh Source address.
Referenced by MeshForwarder::ResumeMessageTransmissions().
GetDestination()
uint16_t GetDestination (void) const inline
This method returns the Mesh Destination address.
Returns
The Mesh Destination address.
AppendTo() [1/2]
Error AppendTo (FrameBuilder & aFrameBuilder) const
This method appends the Mesh Header into a given frame.
Parameters
[out] aFrameBuilder The FrameBuidler to append to.
Return values
kErrorNone Successfully appended the MeshHeader to aFrameBuildr.
kErrorNoBufs Insufficient available buffers.
References FrameBuilder::AppendBigEndianUint16(), FrameBuilder::AppendUint8(), and SuccessOrExit.
AppendTo() [2/2]
Error AppendTo (Message & aMessage) const
This method appends the Mesh Header to a given message.
Parameters
[out] aMessage A message to append the Mesh Header to.
Return values
kErrorNone Successfully appended the Mesh Header to aMessage.
kErrorNoBufs Insufficient available buffers to grow aMessage.
References Message::AppendBytes(), FrameBuilder::GetBytes(), FrameBuilder::GetLength(), IgnoreError(), and FrameBuilder::Init().
Field Documentation
kAdditionalHopsLeft
constexpr uint8_t kAdditionalHopsLeft = 1 static
The additional value that is added to predicted value of the route cost.
Referenced by MeshForwarder::PrepareDataFrame().
kDispatch
constexpr uint8_t kDispatch = 2 << 6 static private
kDispatchMask
constexpr uint8_t kDispatchMask = 3 << 6 static private
kHopsLeftMask
constexpr uint8_t kHopsLeftMask = 0x0f static private
kSourceShort
constexpr uint8_t kSourceShort = 1 << 5 static private
kDestShort
constexpr uint8_t kDestShort = 1 << 4 static private
kDeepHopsLeft
constexpr uint8_t kDeepHopsLeft = 0x0f static private
kMinHeaderLength
constexpr uint16_t kMinHeaderLength = sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) static private
kDeepHopsHeaderLength
constexpr uint16_t kDeepHopsHeaderLength = kMinHeaderLength + sizeof(uint8_t) static private
mSource
uint16_t mSource private
mDestination
uint16_t mDestination private
mHopsLeft
uint8_t mHopsLeft private
The documentation for this class was generated from the following files:
lowpan.hpp
lowpan.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale