OpenThread: Header Class Reference
Header Class Reference
Core-ipv6 » IPv6
#include <ip6_headers.hpp>
Data Structures
union OT_TOOL_PACKED_FIELD
Public Member Functions
Address & GetDestination (void)
const Address & GetDestination (void) const
uint8_t GetDscp (void) const
Ecn GetEcn (void) const
uint32_t GetFlow (void) const
uint8_t GetHopLimit (void) const
uint8_t GetNextHeader (void) const
uint16_t GetPayloadLength (void) const
Address & GetSource (void)
const Address & GetSource (void) const
uint8_t GetTrafficClass (void) const
uint32_t GetVerionTrafficClassFlow (void) const
void InitVersionTrafficClassFlow (void)
bool IsValid (void) const
bool IsVersion6 (void) const
Error ParseFrom (const Message &aMessage)
void SetDestination (const Address &aDestination)
void SetDscp (uint8_t aDscp)
void SetEcn (Ecn aEcn)
void SetFlow (uint32_t aFlow)
void SetHopLimit (uint8_t aHopLimit)
void SetNextHeader (uint8_t aNextHeader)
void SetPayloadLength (uint16_t aLength)
void SetSource (const Address &aSource)
void SetTrafficClass (uint8_t aTc)
void SetVerionTrafficClassFlow (uint32_t aVerTcFlow)
Public Member Functions inherited from Clearable< Header >
void Clear (void)
Static Public Attributes
static constexpr uint8_t kDestinationFieldOffset = 24
Offset of Destination Address field in IPv6 header.
static constexpr uint8_t kHopLimitFieldOffset = 7
Offset of Hop Limit field in IPv6 header.
static constexpr uint8_t kNextHeaderFieldOffset = 6
Offset of Next Header field in IPv6 header.
static constexpr uint8_t kPayloadLengthFieldOffset = 4
Offset of Payload Length field in IPv6 header.
static constexpr uint8_t kSourceFieldOffset = 8
Offset of Source Address field in IPv6 header.
Private Attributes
Address mDestination
uint8_t mHopLimit
uint8_t mNextHeader
uint16_t mPayloadLength
Address mSource
union ot::Ip6::Header::OT_TOOL_PACKED_FIELD mVerTcFlow
Static Private Attributes
static constexpr uint16_t kDscpMask = 0x0fc0
static constexpr uint8_t kDscpOffset = 6
static constexpr uint8_t kEcnMask = 0x30
static constexpr uint8_t kEcnOffset = 4
static constexpr uint32_t kFlowMask = 0x000fffff
static constexpr uint16_t kTrafficClassMask = 0x0ff0
static constexpr uint8_t kTrafficClassOffset = 4
static constexpr uint8_t kVersion6 = 0x60
static constexpr uint8_t kVersionMask = 0xf0
static constexpr uint32_t kVersTcFlowInit = 0x60000000
Detailed Description
This class implements IPv6 header generation and parsing.
Member Function Documentation
InitVersionTrafficClassFlow()
void InitVersionTrafficClassFlow (void) inline
This method initializes the Version to 6 and sets Traffic Class and Flow fields to zero.
The other fields in the IPv6 header remain unchanged.
References Header::IsValid(), Header::kVersTcFlowInit, and Header::SetVerionTrafficClassFlow().
Referenced by Ip6::AddTunneledMplOption(), Lowpan::DecompressBaseHeader(), and Ip6::SendDatagram().
IsValid()
bool IsValid (void) const
This method indicates whether or not the header appears to be well-formed.
Return values
TRUE If the header appears to be well-formed.
FALSE If the header does not appear to be well-formed.
References Header::GetPayloadLength(), Header::IsVersion6(), ot::Ip6::kMaxAssembledDatagramLength, and ot::Ip6::kMaxDatagramLength.
Referenced by Ip6::GetDatagramPriority(), Header::InitVersionTrafficClassFlow(), and Header::ParseFrom().
IsVersion6()
bool IsVersion6 (void) const inline
This method indicates whether or not the IPv6 Version is set to 6.
Return values
TRUE If the IPv6 Version is set to 6.
FALSE If the IPv6 Version is not set to 6.
References Header::kVersion6, Header::kVersionMask, Header::OT_TOOL_PACKED_FIELD::m8, and Header::mVerTcFlow.
Referenced by Header::IsValid().
GetVerionTrafficClassFlow()
uint32_t GetVerionTrafficClassFlow (void) const inline
This method gets the combination of Version, Traffic Class, and Flow fields as a 32-bit value.
Returns
The Version, Traffic Class, and Flow fields as a 32-bit value.
References ot::Encoding::BigEndian::HostSwap32(), Header::OT_TOOL_PACKED_FIELD::m32, and Header::mVerTcFlow.
SetVerionTrafficClassFlow()
void SetVerionTrafficClassFlow (uint32_t aVerTcFlow) inline
This method sets the combination of Version, Traffic Class, and Flow fields as a 32-bit value.
Parameters
[in] aVerTcFlow The Version, Traffic Class, and Flow fields as a 32-bit value.
References ot::Encoding::BigEndian::HostSwap32(), Header::OT_TOOL_PACKED_FIELD::m32, and Header::mVerTcFlow.
Referenced by Header::InitVersionTrafficClassFlow().
GetTrafficClass()
uint8_t GetTrafficClass (void) const inline
This method gets the Traffic Class field.
Returns
The Traffic Class field.
References ot::Encoding::BigEndian::HostSwap16(), Header::kTrafficClassMask, Header::kTrafficClassOffset, Header::OT_TOOL_PACKED_FIELD::m16, and Header::mVerTcFlow.
SetTrafficClass()
void SetTrafficClass (uint8_t aTc) inline
This method sets the Traffic Class filed.
Parameters
[in] aTc The Traffic Class value.
References ot::Encoding::BigEndian::HostSwap16(), Header::kTrafficClassMask, Header::kTrafficClassOffset, Header::OT_TOOL_PACKED_FIELD::m16, and Header::mVerTcFlow.
GetDscp()
uint8_t GetDscp (void) const inline
This method gets the 6-bit Differentiated Services Code Point (DSCP) from Traffic Class field.
Returns
The DSCP value.
References ot::Encoding::BigEndian::HostSwap16(), Header::kDscpMask, Header::kDscpOffset, Header::OT_TOOL_PACKED_FIELD::m16, and Header::mVerTcFlow.
Referenced by Ip6::GetDatagramPriority(), and MeshForwarder::GetFramePriority().
SetDscp()
void SetDscp (uint8_t aDscp) inline
This method sets 6-bit Differentiated Services Code Point (DSCP) in IPv6 header.
Parameters
[in] aDscp The DSCP value.
References ot::Encoding::BigEndian::HostSwap16(), Header::kDscpMask, Header::kDscpOffset, Header::OT_TOOL_PACKED_FIELD::m16, and Header::mVerTcFlow.
Referenced by Ip6::SendDatagram().
GetEcn()
Ecn GetEcn (void) const inline
This method gets the 2-bit Explicit Congestion Notification (ECN) from Traffic Class field.
Returns
The ECN value.
References Header::kEcnMask, Header::kEcnOffset, Header::OT_TOOL_PACKED_FIELD::m8, and Header::mVerTcFlow.
Referenced by Ip6::HandleDatagram(), and MeshForwarder::ResumeMessageTransmissions().
SetEcn()
void SetEcn (Ecn aEcn) inline
This method sets the 2-bit Explicit Congestion Notification (ECN) in IPv6 header..
Parameters
[in] aEcn The ECN value.
References Header::kEcnMask, Header::kEcnOffset, Header::OT_TOOL_PACKED_FIELD::m8, and Header::mVerTcFlow.
Referenced by MeshForwarder::ResumeMessageTransmissions(), and Ip6::SendDatagram().
GetFlow()
uint32_t GetFlow (void) const inline
This method gets the 20-bit Flow field.
Returns
The Flow value.
References ot::Encoding::BigEndian::HostSwap32(), Header::kFlowMask, Header::OT_TOOL_PACKED_FIELD::m32, and Header::mVerTcFlow.
SetFlow()
void SetFlow (uint32_t aFlow) inline
This method sets the 20-bit Flow field in IPv6 header.
Parameters
[in] aFlow The Flow value.
References ot::Encoding::BigEndian::HostSwap32(), Header::kFlowMask, Header::OT_TOOL_PACKED_FIELD::m32, and Header::mVerTcFlow.
GetPayloadLength()
uint16_t GetPayloadLength (void) const inline
This method returns the IPv6 Payload Length value.
Returns
The IPv6 Payload Length value.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mPayloadLength.
Referenced by Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Ip6::GetDatagramPriority(), Ip6::InsertMplOption(), Header::IsValid(), Header::ParseFrom(), and Ip6::RemoveMplOption().
SetPayloadLength()
void SetPayloadLength (uint16_t aLength) inline
This method sets the IPv6 Payload Length value.
Parameters
[in] aLength The IPv6 Payload Length value.
References ot::Encoding::BigEndian::HostSwap16(), and Header::mPayloadLength.
Referenced by Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Ip6::HandleOptions(), Ip6::InsertMplOption(), Ip6::RemoveMplOption(), and Ip6::SendDatagram().
GetNextHeader()
uint8_t GetNextHeader (void) const inline
This method returns the IPv6 Next Header value.
Returns
The IPv6 Next Header value.
References Header::mNextHeader.
Referenced by Ip6::AddMplOption(), Lowpan::Compress(), Ip6::HandleDatagram(), Ip6::InsertMplOption(), and Ip6::RemoveMplOption().
SetNextHeader()
void SetNextHeader (uint8_t aNextHeader) inline
This method sets the IPv6 Next Header value.
Parameters
[in] aNextHeader The IPv6 Next Header value.
References Header::mNextHeader.
Referenced by Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Lowpan::DecompressBaseHeader(), Ip6::HandleOptions(), Ip6::RemoveMplOption(), and Ip6::SendDatagram().
GetHopLimit()
uint8_t GetHopLimit (void) const inline
This method returns the IPv6 Hop Limit value.
Returns
The IPv6 Hop Limit value.
References Header::mHopLimit.
Referenced by Lowpan::Compress(), Ip6::HandleDatagram(), Ip6::HandleOptions(), and Ip6::SendRaw().
SetHopLimit()
void SetHopLimit (uint8_t aHopLimit) inline
This method sets the IPv6 Hop Limit value.
Parameters
[in] aHopLimit The IPv6 Hop Limit value.
References Header::mHopLimit.
Referenced by Ip6::AddTunneledMplOption(), Lowpan::DecompressBaseHeader(), Ip6::HandleDatagram(), and Ip6::SendDatagram().
GetSource() [1/2]
Address& GetSource (void) inline
This method returns the IPv6 Source address.
Returns
A reference to the IPv6 Source address.
References Header::mSource.
Referenced by Ip6::AddMplOption(), Lowpan::Compress(), Lowpan::DecompressBaseHeader(), Ip6::HandleDatagram(), Ip6::HandleOptions(), Ip6::InsertMplOption(), MeshForwarder::ResumeMessageTransmissions(), Ip6::SendDatagram(), Ip6::SendRaw(), and MeshForwarder::UpdateIp6Route().
GetSource() [2/2]
const Address& GetSource (void) const inline
This method returns the IPv6 Source address.
Returns
A reference to the IPv6 Source address.
References Header::mSource.
SetSource()
void SetSource (const Address & aSource) inline
This method sets the IPv6 Source address.
Parameters
[in] aSource A reference to the IPv6 Source address.
References Header::mSource.
Referenced by Ip6::AddTunneledMplOption(), and Ip6::SendDatagram().
GetDestination() [1/2]
Address& GetDestination (void) inline
This method returns the IPv6 Destination address.
Returns
A reference to the IPv6 Destination address.
References Header::mDestination.
Referenced by Mle::CheckReachability(), Lowpan::Compress(), Lowpan::DecompressBaseHeader(), AddressResolver::HandleAddressError(), Ip6::HandleDatagram(), Ip6::HandleOptions(), Ip6::InsertMplOption(), Ip6::SendDatagram(), Ip6::SendRaw(), and MeshForwarder::UpdateIp6Route().
GetDestination() [2/2]
const Address& GetDestination (void) const inline
This method returns the IPv6 Destination address.
Returns
A reference to the IPv6 Destination address.
References Header::mDestination.
SetDestination()
void SetDestination (const Address & aDestination) inline
This method sets the IPv6 Destination address.
Parameters
[in] aDestination A reference to the IPv6 Destination address.
References Header::mDestination, and Header::ParseFrom().
Referenced by Ip6::AddTunneledMplOption(), and Ip6::SendDatagram().
ParseFrom()
Error ParseFrom (const Message & aMessage)
This method parses and validates the IPv6 header from a given message.
The header is read from aMessage at offset zero.
Parameters
[in] aMessage The IPv6 message.
Return values
kErrorNone Successfully parsed the IPv6 header from aMessage.
kErrorParse Malformed IPv6 header or message (e.g., message does not contained expected payload length).
References Message::GetLength(), Header::GetPayloadLength(), Header::IsValid(), ot::kErrorNone, ot::kErrorParse, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by Ip6::HandleDatagram(), Ip6::SendRaw(), and Header::SetDestination().
Field Documentation
kPayloadLengthFieldOffset
constexpr uint8_t kPayloadLengthFieldOffset = 4 static
Offset of Payload Length field in IPv6 header.
Referenced by Lowpan::Decompress().
kNextHeaderFieldOffset
constexpr uint8_t kNextHeaderFieldOffset = 6 static
Offset of Next Header field in IPv6 header.
kHopLimitFieldOffset
constexpr uint8_t kHopLimitFieldOffset = 7 static
Offset of Hop Limit field in IPv6 header.
Referenced by Ip6::HandleDatagram(), and Mpl::HandleSeedSetTimer().
kSourceFieldOffset
constexpr uint8_t kSourceFieldOffset = 8 static
Offset of Source Address field in IPv6 header.
kDestinationFieldOffset
constexpr uint8_t kDestinationFieldOffset = 24 static
Offset of Destination Address field in IPv6 header.
kVersion6
constexpr uint8_t kVersion6 = 0x60 static private
Referenced by Header::IsVersion6().
kVersionMask
constexpr uint8_t kVersionMask = 0xf0 static private
Referenced by Header::IsVersion6().
kTrafficClassOffset
constexpr uint8_t kTrafficClassOffset = 4 static private
Referenced by Header::GetTrafficClass(), and Header::SetTrafficClass().
kTrafficClassMask
constexpr uint16_t kTrafficClassMask = 0x0ff0 static private
Referenced by Header::GetTrafficClass(), and Header::SetTrafficClass().
kDscpOffset
constexpr uint8_t kDscpOffset = 6 static private
Referenced by Header::GetDscp(), and Header::SetDscp().
kDscpMask
constexpr uint16_t kDscpMask = 0x0fc0 static private
Referenced by Header::GetDscp(), and Header::SetDscp().
kEcnOffset
constexpr uint8_t kEcnOffset = 4 static private
Referenced by Header::GetEcn(), and Header::SetEcn().
kEcnMask
constexpr uint8_t kEcnMask = 0x30 static private
Referenced by Header::GetEcn(), and Header::SetEcn().
kFlowMask
constexpr uint32_t kFlowMask = 0x000fffff static private
Referenced by Header::GetFlow(), and Header::SetFlow().
kVersTcFlowInit
constexpr uint32_t kVersTcFlowInit = 0x60000000 static private
Referenced by Header::InitVersionTrafficClassFlow().
mVerTcFlow
union ot::Ip6::Header::OT_TOOL_PACKED_FIELD mVerTcFlow private
Referenced by Header::GetDscp(), Header::GetEcn(), Header::GetFlow(), Header::GetTrafficClass(), Header::GetVerionTrafficClassFlow(), Header::IsVersion6(), Header::SetDscp(), Header::SetEcn(), Header::SetFlow(), Header::SetTrafficClass(), and Header::SetVerionTrafficClassFlow().
mPayloadLength
uint16_t mPayloadLength private
Referenced by Header::GetPayloadLength(), and Header::SetPayloadLength().
mNextHeader
uint8_t mNextHeader private
Referenced by Header::GetNextHeader(), ExtensionHeader::GetNextHeader(), FragmentHeader::GetNextHeader(), Header::SetNextHeader(), ExtensionHeader::SetNextHeader(), and FragmentHeader::SetNextHeader().
mHopLimit
uint8_t mHopLimit private
Referenced by Header::GetHopLimit(), and Header::SetHopLimit().
mSource
Address mSource private
Referenced by Header::GetSource(), and Header::SetSource().
mDestination
Address mDestination private
Referenced by Header::GetDestination(), and Header::SetDestination().
The documentation for this class was generated from the following files:
ip6_headers.hpp
ip6_headers.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale