OpenThread: BinarySearch Class Reference
BinarySearch Class Reference
#include <binary_search.hpp>
Static Public Member Functions
template<typename Key , typename Entry , uint16_t kLength>
static const Entry * Find (const Key &aKey, const Entry(&aTable)[kLength])
template<typename Entry , uint16_t kLength>
static constexpr bool IsSorted (const Entry(&aTable)[kLength])
Private Types
typedef int(&) Comparator(const void *aKey, const void *aEntry)
Static Private Member Functions
template<typename Key , typename Entry >
static int Compare (const void *aKey, const void *aEntry)
static const void * Find (const void *aKey, const void *aTable, uint16_t aLength, uint16_t aEntrySize, Comparator aComparator)
template<typename Entry >
static constexpr bool IsSorted (const Entry *aTable, uint16_t aLength)
Member Typedef Documentation
Comparator
typedef int(&) Comparator(const void *aKey, const void *aEntry) private
Member Function Documentation
Find() [1/2]
static const Entry* Find (const Key & aKey, const Entry(&) aTable[kLength]) inline static
This template method performs binary search in a given sorted table array to find an entry matching a given key.
Note
This method requires the array to be sorted, otherwise its behavior is undefined.
Template Parameters
Key The type of Key to search for.
Entry The table Entry type.
kLength The array length (number of entries in the array).
The Entry class MUST provide the following method to compare the entry against a given key.
int Entry::Compare(const Key &aKey) const;
The return value indicates the comparison result between aKey and the entry (similar to strcmp()), i.e., zero means perfect match, positive (> 0) indicates aKey is larger than entry, and negative indicates aKey is smaller than entry.
Note
In the common use of this method as Find(key, kTable) where kTable is a fixed size array, the template types/parameters do not need to be explicitly specified and can be inferred from the passed-in argument.
Parameters
[in] aKey The key to search for within the table.
[in] aTable A reference to an array of kLength entries of type Entry
Returns
A pointer to the entry in the table if a match is found, otherwise nullptr (no match in table).
Referenced by BinarySearch::Compare(), Stringify::Lookup(), Dataset::Process(), UdpExample::Process(), NetworkData::Process(), and Interpreter::ProcessCommand().
IsSorted() [1/2]
static constexpr bool IsSorted (const Entry(&) aTable[kLength]) inline static
This template method indicates whether a given table array is sorted based or not.
This method is constexpr and is intended for use in static_asserts to verify that a constexpr lookup table array is sorted. It is not recommended for use in other situations.
Template Parameters
Entry The table entry type.
kLength The array length (number of entries in the array).
The Entry class MUST provide the following static and constexpr method to compare two entries.
constexpr static bool Entry::AreInOrder(const Entry &aFirst, const Entry &aSecond);
The return value MUST be TRUE if the entries are in order, i.e. aFirst < aSecond and FALSE otherwise.
Parameters
[in] aTable A reference to an array of kLength entries on type Entry
Return values
TRUE If the entries in aTable are sorted.
FALSE If the entries in aTable are not sorted.
Referenced by Message::Clone(), Ip6::IpProtoToString(), BinarySearch::IsSorted(), Dataset::Process(), NetworkData::Process(), and Interpreter::ProcessCommand().
IsSorted() [2/2]
static constexpr bool IsSorted (const Entry * aTable, uint16_t aLength) inline static private
References BinarySearch::IsSorted().
Compare()
static int Compare (const void * aKey, const void * aEntry) inline static private
References BinarySearch::Find().
Find() [2/2]
const void * Find (const void * aKey, const void * aTable, uint16_t aLength, uint16_t aEntrySize, Comparator aComparator) static private
References ExitNow.
The documentation for this class was generated from the following files:
binary_search.hpp
binary_search.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale