OpenThread: Links Class Reference
Links Class Reference
Core-mac
#include <mac_links.hpp>
Public Member Functions
void Disable (void)
void Enable (void)
Error EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
const KeyMaterial * GetCurrentMacKey (const Frame &aFrame) const
const ExtAddress & GetExtAddress (void) const
int8_t GetNoiseFloor (void)
int8_t GetRssi (void) const
ShortAddress GetShortAddress (void) const
SubMac & GetSubMac (void)
const SubMac & GetSubMac (void) const
const KeyMaterial * GetTemporaryMacKey (const Frame &aFrame, uint32_t aKeySequence) const
uint8_t GetTransmitRetries (void) const
TxFrames & GetTxFrames (void)
Links (Instance &aInstance)
void Receive (uint8_t aChannel)
void Send (void)
void SetExtAddress (const ExtAddress &aExtAddress)
void SetPanId (PanId aPanId)
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void *aCallbackContext)
void SetRxOnWhenBackoff (bool aRxOnWhenBackoff)
void SetShortAddress (ShortAddress aShortAddress)
void Sleep (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Attributes
static const int8_t kInvalidRssiValue = SubMac::kInvalidRssiValue
Invalid RSSI value.
Private Attributes
ExtAddress mExtAddress
ShortAddress mShortAddress
SubMac mSubMac
TxFrames mTxFrames
Static Private Attributes
static constexpr int8_t kDefaultNoiseFloor = -100
Friends
class ot::Instance
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class represents MAC radio links (multi radio).
Constructor & Destructor Documentation
Links()
Links (Instance & aInstance) explicit
This constructor initializes the Links object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Clearable< Type >::Clear(), Links::mExtAddress, Links::mSubMac, Links::mTxFrames, SubMac::Send(), Links::Send(), and SuccessOrAssert.
Member Function Documentation
SetPanId()
void SetPanId (PanId aPanId) inline
This method sets the PAN ID.
Parameters
[in] aPanId The PAN ID.
Referenced by Mac::BeginTransmit(), Mac::PerformActiveScan(), and Mac::SetPanId().
GetShortAddress()
ShortAddress GetShortAddress (void) const inline
This method gets the MAC Short Address.
Returns
The MAC Short Address.
Referenced by Mac::GetShortAddress().
SetShortAddress()
void SetShortAddress (ShortAddress aShortAddress) inline
This method sets the MAC Short Address.
Parameters
[in] aShortAddress A MAC Short Address.
Referenced by Mac::SetShortAddress().
GetExtAddress()
const ExtAddress& GetExtAddress (void) const inline
This method gets the MAC Extended Address.
Returns
The MAC Extended Address.
Referenced by Mac::GetExtAddress().
SetExtAddress()
void SetExtAddress (const ExtAddress & aExtAddress) inline
This method sets the MAC Extended Address.
Parameters
[in] aExtAddress A MAC Extended Address.
Referenced by Mac::SetExtAddress().
SetPcapCallback()
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void * aCallbackContext) inline
This method registers a callback to provide received packet capture for IEEE 802.15.4 frames.
Parameters
[in] aPcapCallback A pointer to a function that is called when receiving an IEEE 802.15.4 link frame or nullptr to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
References OT_UNUSED_VARIABLE.
Referenced by Mac::SetPcapCallback().
SetRxOnWhenBackoff()
void SetRxOnWhenBackoff (bool aRxOnWhenBackoff) inline
This method indicates whether radio should stay in Receive or Sleep during CSMA backoff.
Parameters
[in] aRxOnWhenBackoff TRUE to keep radio in Receive, FALSE to put to Sleep during CSMA backoff.
References OT_UNUSED_VARIABLE.
Referenced by Mac::SetPromiscuous(), and Mac::SetRxOnWhenIdle().
Enable()
void Enable (void) inline
This method enables all radio links.
References IgnoreError().
Referenced by Mac::Mac().
Disable()
void Disable (void) inline
This method disables all radio links.
References IgnoreError().
Sleep()
void Sleep (void) inline
This method transitions all radio links to Sleep.
References IgnoreError(), and OT_UNUSED_VARIABLE.
Referenced by Mac::UpdateIdleMode().
Receive()
void Receive (uint8_t aChannel) inline
This method transitions all radio links to Receive.
Parameters
[in] aChannel The channel to use for receiving.
References IgnoreError().
Referenced by Mac::PerformEnergyScan(), Mac::PerformNextOperation(), and Mac::UpdateIdleMode().
GetTxFrames()
TxFrames& GetTxFrames (void) inline
This method gets the radio transmit frames.
Returns
The transmit frames.
Referenced by Mac::BeginTransmit(), Mac::HandleTransmitDone(), Mac::PrepareBeacon(), and Mac::PrepareBeaconRequest().
Send()
void Send (void) inline
This method sends a prepared frame.
The prepared frame is from GetTxFrames(). This method is available only in single radio link mode.
References SuccessOrAssert.
Referenced by Mac::BeginTransmit(), Mac::HandleTransmitDone(), and Links::Links().
GetTransmitRetries()
uint8_t GetTransmitRetries (void) const inline
This method gets the number of transmit retries for the last transmitted frame.
Returns
Number of transmit retries.
Referenced by Mac::HandleTransmitDone().
GetRssi()
int8_t GetRssi (void) const inline
This method gets the most recent RSSI measurement from radio link.
Returns
The RSSI in dBm when it is valid. kInvalidRssiValue when RSSI is invalid.
Referenced by Mac::PerformEnergyScan().
EnergyScan()
Error EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration) inline
This method begins energy scan.
Parameters
[in] aScanChannel The channel to perform the energy scan on.
[in] aScanDuration The duration, in milliseconds, for the channel to be scanned.
Return values
kErrorNone Successfully started scanning the channel.
kErrorBusy The radio is performing energy scanning.
kErrorInvalidState The radio was disabled or transmitting.
kErrorNotImplemented Energy scan is not supported by radio link.
References ot::kErrorNotImplemented, and OT_UNUSED_VARIABLE.
Referenced by Mac::PerformEnergyScan().
GetNoiseFloor()
int8_t GetNoiseFloor (void) inline
This method returns the noise floor value (currently use the radio receive sensitivity value).
Returns
The noise floor value in dBm.
Referenced by Mac::GetNoiseFloor().
GetSubMac() [1/2]
SubMac& GetSubMac (void) inline
This methods gets a reference to the SubMac instance.
Returns
A reference to the SubMac instance.
Referenced by Mac::IsEnabled(), Mac::LogFrameTxFailure(), and Mac::ProcessEnhAckSecurity().
GetSubMac() [2/2]
const SubMac& GetSubMac (void) const inline
This methods gets a reference to the SubMac instance.
Returns
A reference to the SubMac instance.
GetCurrentMacKey()
const KeyMaterial * GetCurrentMacKey (const Frame & aFrame) const
This method returns a reference to the current MAC key (for Key Mode 1) for a given Frame.
Parameters
[in] aFrame The frame for which to get the MAC key.
Returns
A reference to the current MAC key.
References ExitNow, and OT_UNUSED_VARIABLE.
Referenced by Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
GetTemporaryMacKey()
const KeyMaterial * GetTemporaryMacKey (const Frame & aFrame, uint32_t aKeySequence) const
This method returns a reference to the temporary MAC key (for Key Mode 1) for a given Frame based on a given Key Sequence.
Parameters
[in] aFrame The frame for which to get the MAC key.
[in] aKeySequence The Key Sequence number (MUST be one off (+1 or -1) from current key sequence number).
Returns
A reference to the temporary MAC key.
References ExitNow, OT_ASSERT, OT_UNUSED_VARIABLE, and Frame::SetFrameCounter().
Referenced by Mac::ProcessReceiveSecurity().
Friends And Related Function Documentation
ot::Instance
friend class ot::Instance friend
Field Documentation
kInvalidRssiValue
const int8_t kInvalidRssiValue = SubMac::kInvalidRssiValue static
Invalid RSSI value.
kDefaultNoiseFloor
constexpr int8_t kDefaultNoiseFloor = -100 static private
mSubMac
SubMac mSubMac private
Referenced by Links::Links().
mTxFrames
TxFrames mTxFrames private
Referenced by Links::Links().
mShortAddress
ShortAddress mShortAddress private
mExtAddress
ExtAddress mExtAddress private
Referenced by Links::Links().
The documentation for this class was generated from the following files:
mac_links.hpp
mac_links.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale