OpenThread: UdpExample Class Reference
UdpExample Class Reference
#include <cli_udp.hpp>
Public Types
typedef Utils::CmdLineParser::Arg Arg
Public Member Functions
otError Process (Arg aArgs[])
UdpExample (Output &aOutput)
Private Types
using Command = CommandEntry< UdpExample >
Private Types inherited from OutputBase
typedef Utils::CmdLineParser::Arg Arg
An argument.
Private Member Functions
void HandleUdpReceive (otMessage *aMessage, const otMessageInfo *aMessageInfo)
otError ProcessBind (Arg aArgs[])
otError ProcessClose (Arg aArgs[])
otError ProcessConnect (Arg aArgs[])
otError ProcessHelp (Arg aArgs[])
otError ProcessLinkSecurity (Arg aArgs[])
otError ProcessOpen (Arg aArgs[])
otError ProcessSend (Arg aArgs[])
Private Member Functions inherited from OutputWrapper
otInstance * GetInstancePtr (void)
template<uint8_t kBytesLength>
void OutputBytes (const uint8_t(&aBytes)[kBytesLength])
void OutputBytes (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytesLine (const uint8_t(&aBytes)[kBytesLength])
void OutputBytesLine (const uint8_t *aBytes, uint16_t aLength)
template<typename Cli , uint16_t kLength>
void OutputCommandTable (const CommandEntry< Cli >(&aCommandTable)[kLength])
void OutputEnabledDisabledStatus (bool aEnabled)
void OutputExtAddress (const otExtAddress &aExtAddress)
void OutputExtAddressLine (const otExtAddress &aExtAddress)
template<typename... Args>
void OutputFormat (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputFormat (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
void OutputSpaces (uint8_t aCount)
template<uint8_t kTableNumColumns>
void OutputTableHeader (const char *const (&aTitles)[kTableNumColumns], const uint8_t(&aWidths)[kTableNumColumns])
template<uint8_t kTableNumColumns>
void OutputTableSeparator (const uint8_t(&aWidths)[kTableNumColumns])
OutputWrapper (Output &aOutput)
Private Member Functions inherited from OutputBase
OutputBase (void)=default
Static Private Member Functions
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static otError PrepareAutoGeneratedPayload (otMessage &aMessage, uint16_t aPayloadLength)
static otError PrepareHexStringPaylod (otMessage &aMessage, const char *aHexString)
Static Private Member Functions inherited from OutputBase
template<typename EnumType , uint16_t kLength>
static const char * Stringify (EnumType aEnum, const char *const (&aTable)[kLength], const char *aNotFound=kUnknownString)
Private Attributes
bool mLinkSecurityEnabled
otUdpSocket mSocket
Static Private Attributes
static constexpr Command sCommands []
Static Private Attributes inherited from OutputBase
static const char kUnknownString [] = "unknown"
Detailed Description
This class implements a CLI-based UDP example.
Member Typedef Documentation
Arg
typedef Utils::CmdLineParser::Arg Arg
Command
using Command = CommandEntry<UdpExample> private
Constructor & Destructor Documentation
UdpExample()
UdpExample (Output & aOutput) explicit
Constructor
Parameters
[in] aOutput The CLI console output context.
References UdpExample::mSocket.
Member Function Documentation
Process()
otError Process (Arg aArgs[])
This method interprets a list of CLI arguments.
Parameters
[in] aArgs An array of command line arguments.
References ExitNow, BinarySearch::Find(), IgnoreError(), OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_COMMAND, UdpExample::ProcessHelp(), UdpExample::sCommands, and VerifyOrExit.
ProcessHelp()
otError ProcessHelp (Arg aArgs[]) private
References OT_ERROR_NONE, OT_UNUSED_VARIABLE, OutputWrapper::OutputLine(), and UdpExample::sCommands.
Referenced by UdpExample::Process().
ProcessBind()
otError ProcessBind (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), otSockAddr::mAddress, otSockAddr::mPort, UdpExample::mSocket, OT_ERROR_INVALID_ARGS, OT_NETIF_BACKBONE, OT_NETIF_THREAD, OT_NETIF_UNSPECIFIED, otUdpBind(), ot::Utils::CmdLineParser::ParseAsUint16(), SuccessOrExit, and VerifyOrExit.
ProcessClose()
otError ProcessClose (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), UdpExample::mSocket, OT_UNUSED_VARIABLE, and otUdpClose().
ProcessConnect()
otError ProcessConnect (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), otSockAddr::mAddress, otSockAddr::mPort, UdpExample::mSocket, OT_ERROR_INVALID_ARGS, otUdpConnect(), ot::Utils::CmdLineParser::ParseAsUint16(), SuccessOrExit, and VerifyOrExit.
ProcessOpen()
otError ProcessOpen (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), UdpExample::HandleUdpReceive(), UdpExample::mSocket, OT_ERROR_ALREADY, OT_UNUSED_VARIABLE, otUdpIsOpen(), otUdpOpen(), and VerifyOrExit.
ProcessSend()
otError ProcessSend (Arg aArgs[]) private
References OutputWrapper::GetInstancePtr(), UdpExample::mLinkSecurityEnabled, otMessageInfo::mPeerAddr, otMessageInfo::mPeerPort, UdpExample::mSocket, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_MESSAGE_PRIORITY_NORMAL, otMessageAppend(), otMessageFree(), otUdpNewMessage(), otUdpSend(), ot::Utils::CmdLineParser::ParseAsUint16(), UdpExample::PrepareAutoGeneratedPayload(), UdpExample::PrepareHexStringPaylod(), SuccessOrExit, and VerifyOrExit.
ProcessLinkSecurity()
otError ProcessLinkSecurity (Arg aArgs[]) private
References UdpExample::mLinkSecurityEnabled, OT_ERROR_NONE, OutputWrapper::OutputEnabledDisabledStatus(), and Interpreter::ParseEnableOrDisable().
PrepareAutoGeneratedPayload()
otError PrepareAutoGeneratedPayload (otMessage & aMessage, uint16_t aPayloadLength) static private
References OT_ERROR_NONE, otMessageAppend(), and SuccessOrExit.
Referenced by UdpExample::ProcessSend().
PrepareHexStringPaylod()
otError PrepareHexStringPaylod (otMessage & aMessage, const char * aHexString) static private
References ot::kBufferSize, OT_ERROR_NONE, OT_ERROR_PENDING, otMessageAppend(), ot::Utils::CmdLineParser::ParseAsHexStringSegment(), SuccessOrExit, and VerifyOrExit.
Referenced by UdpExample::ProcessSend().
HandleUdpReceive() [1/2]
void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
Referenced by UdpExample::ProcessOpen().
HandleUdpReceive() [2/2]
void HandleUdpReceive (otMessage * aMessage, const otMessageInfo * aMessageInfo) private
References otMessageInfo::mPeerAddr, otMessageInfo::mPeerPort, otMessageGetLength(), otMessageGetOffset(), otMessageRead(), OutputWrapper::OutputFormat(), and OutputWrapper::OutputLine().
Field Documentation
sCommands
constexpr UdpExample::Command sCommands static private
Initial value:
= {
        {"bind", &UdpExample::ProcessBind},
        {"close", &UdpExample::ProcessClose},
        {"connect", &UdpExample::ProcessConnect},
        {"help", &UdpExample::ProcessHelp},
        {"linksecurity", &UdpExample::ProcessLinkSecurity},
        {"open", &UdpExample::ProcessOpen},
        {"send", &UdpExample::ProcessSend},
    }
Referenced by UdpExample::Process(), and UdpExample::ProcessHelp().
mLinkSecurityEnabled
bool mLinkSecurityEnabled private
Referenced by UdpExample::ProcessLinkSecurity(), and UdpExample::ProcessSend().
mSocket
otUdpSocket mSocket private
Referenced by UdpExample::ProcessBind(), UdpExample::ProcessClose(), UdpExample::ProcessConnect(), UdpExample::ProcessOpen(), UdpExample::ProcessSend(), and UdpExample::UdpExample().
The documentation for this class was generated from the following files:
cli_udp.hpp
cli_udp.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale