OpenThread: SettingsBase::ParentInfo Class Reference
SettingsBase::ParentInfo Class Reference
#include <settings.hpp>
Public Member Functions
const Mac::ExtAddress & GetExtAddress (void) const
uint16_t GetVersion (void) const
void Init (void)
void SetExtAddress (const Mac::ExtAddress &aExtAddress)
void SetVersion (uint16_t aVersion)
Static Public Attributes
static constexpr Key kKey = kKeyParentInfo
The associated key.
Private Member Functions
void Log (Action aAction) const
Private Member Functions inherited from Clearable< ParentInfo >
void Clear (void)
Private Attributes
Mac::ExtAddress mExtAddress
Extended Address.
uint16_t mVersion
Version.
Friends
class Settings
Detailed Description
This structure represents the parent information for settings storage.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the ParentInfo object.
References Clearable< NetworkInfo >::Clear(), ot::kThreadVersion1p1, and SettingsBase::NetworkInfo::SetVersion().
Referenced by Mle::Store().
GetExtAddress()
const Mac::ExtAddress& GetExtAddress (void) const inline
This method returns the extended address.
Returns
The extended address.
References SettingsBase::NetworkInfo::mExtAddress.
Referenced by Mle::Restore().
SetExtAddress()
void SetExtAddress (const Mac::ExtAddress & aExtAddress) inline
This method sets the extended address.
Parameters
[in] aExtAddress The extended address.
References SettingsBase::NetworkInfo::mExtAddress.
Referenced by Mle::Store().
GetVersion()
uint16_t GetVersion (void) const inline
This method returns the Thread version.
Returns
The Thread version.
References ot::Encoding::LittleEndian::HostSwap16(), and SettingsBase::NetworkInfo::mVersion.
Referenced by Mle::Restore().
SetVersion()
void SetVersion (uint16_t aVersion) inline
This method sets the Thread version.
Parameters
[in] aVersion The Thread version.
References ot::Encoding::LittleEndian::HostSwap16(), SettingsBase::NetworkInfo::Log(), and SettingsBase::NetworkInfo::mVersion.
Referenced by Mle::Store().
Log()
void Log (Action aAction) const private
Friends And Related Function Documentation
Settings
friend class Settings friend
Field Documentation
kKey
constexpr Key kKey = kKeyParentInfo static
The associated key.
mExtAddress
Mac::ExtAddress mExtAddress private
Extended Address.
mVersion
uint16_t mVersion private
Version.
The documentation for this class was generated from the following file:
core/common/settings.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale