OpenThread: Tlv Class Reference
Tlv Class Reference
#include <tlvs.hpp>
Public Member Functions
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Member Functions
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Protected Attributes
static const uint8_t kExtendedLength = 255
Static Private Member Functions
static Error AppendTlv (Message &aMessage, uint8_t aType, const void *aValue, uint8_t aLength)
template<typename UintType >
static Error AppendUintTlv (Message &aMessage, uint8_t aType, UintType aValue)
static Error Find (const Message &aMessage, uint8_t aType, uint16_t *aOffset, uint16_t *aSize, bool *aIsExtendedTlv)
static Error FindTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
template<typename UintType >
static Error FindUintTlv (const Message &aMessage, uint8_t aType, UintType &aValue)
template<typename UintType >
static Error ReadUintTlv (const Message &aMessage, uint16_t aOffset, UintType &aValue)
Private Attributes
uint8_t mLength
uint8_t mType
Detailed Description
This class implements TLV generation and parsing.
Member Function Documentation
GetType()
uint8_t GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Tlv::mType.
Referenced by Tlv::Find(), ThreadTlv::GetType(), NetworkDiagnosticTlv::GetType(), Tlv::GetType(), and ExtendedTlv::GetType().
SetType()
void SetType (uint8_t aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Tlv::mType.
Referenced by Tlv::AppendTlv(), Mle::HasMoreChannelsToAnnouce(), ThreadTlv::SetType(), NetworkDiagnosticTlv::SetType(), Tlv::SetType(), and ExtendedTlv::SetType().
IsExtended()
bool IsExtended (void) const inline
This method indicates whether the TLV is an Extended TLV.
Return values
TRUE If the TLV is an Extended TLV.
FALSE If the TLV is not an Extended TLV.
References Tlv::kExtendedLength, and Tlv::mLength.
Referenced by Tlv::FindTlv(), Tlv::GetSize(), Tlv::GetValue(), Ip6AddressListTlv::IsValid(), and Tlv::ReadTlv().
GetLength()
uint8_t GetLength (void) const inline
This method returns the Length value.
Note
This method should be used when TLV is not an Extended TLV, otherwise the returned length from this method would not be correct. When TLV is an Extended TLV, the TLV should be down-casted to the ExtendedTlv type and the ExtendedTlv::GetLength() should be used instead.
Returns
The Length value.
References Tlv::mLength.
Referenced by JoinerAdvertisementTlv::GetAdvDataLength(), CommissionerIdTlv::GetCommissionerIdLength(), ChannelMaskBaseTlv::GetFirstEntry(), SecurityPolicyTlv::GetFlagsLength(), NetworkNameTlv::GetNetworkName(), ChildTableTlv::GetNumEntries(), ProvisioningUrlTlv::GetProvisioningUrlLength(), RouteTlv::GetRouteDataLength(), Tlv::GetSize(), SteeringDataTlv::GetSteeringDataLength(), UdpEncapsulationTlv::GetUdpLength(), VendorDataTlv::GetVendorDataLength(), VendorModelTlv::GetVendorModelLength(), VendorNameTlv::GetVendorNameLength(), VendorSwVersionTlv::GetVendorSwVersionLength(), Mle::HandleChildIdResponse(), DiscoverScanner::HandleDiscoveryResponse(), DatasetManager::HandleGet(), Mle::HandleLeaderData(), LeaderBase::IsJoiningEnabled(), ConnectivityTlv::IsSedBufferingIncluded(), ThreadRouterMaskTlv::IsValid(), RouteTlv::IsValid(), Ip6AddressesTlv::IsValid(), ChannelTlv::IsValid(), PanIdTlv::IsValid(), ExtendedPanIdTlv::IsValid(), NetworkNameTlv::IsValid(), PskcTlv::IsValid(), NetworkKeyTlv::IsValid(), NetworkKeySequenceTlv::IsValid(), LeaderDataTlv::IsValid(), NetworkDataTlv::IsValid(), MeshLocalPrefixTlv::IsValid(), Ip6AddressListTlv::IsValid(), SteeringDataTlv::IsValid(), ConnectivityTlv::IsValid(), MacCountersTlv::IsValid(), BorderAgentLocatorTlv::IsValid(), CommissionerSessionIdTlv::IsValid(), SecurityPolicyTlv::IsValid(), ActiveTimestampTlv::IsValid(), ChildTableTlv::IsValid(), StateTlv::IsValid(), ChannelPagesTlv::IsValid(), JoinerUdpPortTlv::IsValid(), PendingTimestampTlv::IsValid(), DelayTimerTlv::IsValid(), VendorStackVersionTlv::IsValid(), UdpEncapsulationTlv::IsValid(), DiscoveryRequestTlv::IsValid(), DiscoveryResponseTlv::IsValid(), JoinerAdvertisementTlv::IsValid(), Tlv::ReadTlv(), Dataset::RemoveTlv(), LeaderBase::SetNetworkData(), NetworkDataTlv::SetNetworkData(), and Dataset::SetTlv().
SetLength()
void SetLength (uint8_t aLength) inline
This method sets the Length value.
Parameters
[in] aLength The Length value.
References Tlv::GetSize(), Tlv::GetValue(), and Tlv::mLength.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), Dataset::AppendMleDatasetTlv(), Tlv::AppendTlv(), DiscoverScanner::Discover(), Mle::HasMoreChannelsToAnnouce(), ThreadRouterMaskTlv::Init(), RouteTlv::Init(), ThreadNetworkDataTlv::Init(), ChannelTlv::Init(), PanIdTlv::Init(), ExtendedPanIdTlv::Init(), NetworkNameTlv::Init(), PskcTlv::Init(), NetworkKeyTlv::Init(), NetworkKeySequenceTlv::Init(), LeaderDataTlv::Init(), NetworkDataTlv::Init(), MeshLocalPrefixTlv::Init(), Ip6AddressListTlv::Init(), SteeringDataTlv::Init(), ConnectivityTlv::Init(), MacCountersTlv::Init(), BorderAgentLocatorTlv::Init(), CommissionerIdTlv::Init(), CommissionerSessionIdTlv::Init(), SecurityPolicyTlv::Init(), ActiveTimestampTlv::Init(), ChildTableTlv::Init(), StateTlv::Init(), ChannelPagesTlv::Init(), JoinerUdpPortTlv::Init(), TypeListTlv::Init(), PendingTimestampTlv::Init(), DelayTimerTlv::Init(), ChannelMaskBaseTlv::Init(), ChannelMaskTlv::Init(), EnergyListTlv::Init(), ProvisioningUrlTlv::Init(), VendorNameTlv::Init(), VendorModelTlv::Init(), VendorSwVersionTlv::Init(), VendorDataTlv::Init(), VendorStackVersionTlv::Init(), UdpEncapsulationTlv::Init(), DiscoveryRequestTlv::Init(), DiscoveryResponseTlv::Init(), JoinerAdvertisementTlv::Init(), Mle::RoleToString(), Mle::TxMessage::SendAfterDelay(), DatasetManager::SendGetRequest(), EnergyScanServer::SendReport(), NetworkData::SendServerDataNotification(), JoinerAdvertisementTlv::SetAdvData(), ChannelMaskTlv::SetChannelMask(), CommissionerIdTlv::SetCommissionerId(), ExtendedTlv::SetLength(), NetworkNameTlv::SetNetworkName(), ProvisioningUrlTlv::SetProvisioningUrl(), RouteTlv::SetRouteDataLength(), Dataset::SetTlv(), UdpEncapsulationTlv::SetUdpLength(), VendorDataTlv::SetVendorData(), VendorModelTlv::SetVendorModel(), VendorNameTlv::SetVendorName(), and VendorSwVersionTlv::SetVendorSwVersion().
GetSize()
uint32_t GetSize (void) const
This method returns the TLV's total size (number of bytes) including Type, Length, and Value fields.
This method correctly returns the TLV size independent of whether the TLV is an Extended TLV or not.
Returns
The total size include Type, Length, and Value fields.
References Tlv::GetLength(), and Tlv::IsExtended().
Referenced by Tlv::AppendTo(), DiscoverScanner::Discover(), Tlv::Find(), Tlv::GetNext(), Mle::HasMoreChannelsToAnnouce(), Tlv::ReadTlv(), and Tlv::SetLength().
GetValue() [1/2]
uint8_t * GetValue (void)
This method returns a pointer to the Value.
This method can be used independent of whether the TLV is an Extended TLV or not.
Returns
A pointer to the value.
References Tlv::IsExtended().
Referenced by ChildTableTlv::GetEntry(), ChannelMaskBaseTlv::GetFirstEntry(), Ip6AddressesTlv::GetIp6Address(), Ip6AddressListTlv::GetIp6Address(), LeaderBase::IsJoiningEnabled(), Tlv::SetLength(), and Dataset::SetTlv().
GetValue() [2/2]
const uint8_t * GetValue (void) const
This method returns a pointer to the Value.
This method can be used independent of whether the TLV is an Extended TLV or not.
Returns
A pointer to the value.
References Tlv::IsExtended().
GetNext() [1/2]
Tlv* GetNext (void) inline
This method returns a pointer to the next TLV.
This method correctly returns the next TLV independent of whether the current TLV is an Extended TLV or not.
Returns
A pointer to the next TLV.
References Tlv::GetSize().
Referenced by Tlv::GetNext().
GetNext() [2/2]
const Tlv* GetNext (void) const inline
This method returns a pointer to the next TLV.
This method correctly returns the next TLV independent of whether the current TLV is an Extended TLV or not.
Returns
A pointer to the next TLV.
References Tlv::AppendTo(), Tlv::GetSize(), and Tlv::ReadTlv().
AppendTo()
Error AppendTo (Message & aMessage) const
This method appends a TLV to the end of the message.
On success, this method grows the message by the size of the TLV.
Parameters
[in] aMessage A reference to the message to append to.
Return values
kErrorNone Successfully appended the TLV to the message.
kErrorNoBufs Insufficient available buffers to grow the message.
References Message::AppendBytes(), and Tlv::GetSize().
Referenced by Mle::TxMessage::AppendLeaderDataTlv(), Dataset::AppendMleDatasetTlv(), DiscoverScanner::Discover(), Tlv::GetNext(), Mle::TxMessage::SendAfterDelay(), Mle::SendAnnounce(), PanIdQueryServer::SendConflict(), DatasetManager::SendGetResponse(), and EnergyScanServer::SendReport().
ReadTlv()
Error ReadTlv (const Message & aMessage, uint16_t aOffset, void * aValue, uint8_t aMinLength) static
This static method reads a TLV in a message at a given offset expecting a minimum length for the value.
Parameters
[in] aMessage The message to read from.
[in] aOffset The offset into the message pointing to the start of the TLV.
[out] aValue A buffer to output the TLV's value, must contain (at least) aMinLength bytes.
[in] aMinLength The minimum expected length of TLV and number of bytes to copy into aValue buffer.
Return values
kErrorNone Successfully read the TLV and copied aMinLength into aValue.
kErrorParse The TLV was not well-formed and could not be parsed.
References Tlv::GetLength(), Message::GetLength(), Tlv::GetSize(), Tlv::IsExtended(), ot::kErrorNone, ot::kErrorParse, Message::Read(), Message::ReadBytes(), SuccessOrExit, and VerifyOrExit.
Referenced by Tlv::GetNext(), DiscoverScanner::HandleDiscoveryResponse(), Tlv::Read(), and Tlv::ReadUintTlv().
Read() [1/2]
static Error Read (const Message & aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType & aValue) inline static
This static method reads a simple TLV with a single non-integral value in a message at a given offset.
Template Parameters
SimpleTlvType The simple TLV type to read (must be a sub-class of SimpleTlvInfo).
Parameters
[in] aMessage The message to read from.
[in] aOffset The offset into the message pointing to the start of the TLV.
[out] aValue A reference to the value object to output the read value.
Return values
kErrorNone Successfully read the TLV and updated the aValue.
kErrorParse The TLV was not well-formed and could not be parsed.
References Tlv::ReadTlv().
Read() [2/2]
static Error Read (const Message & aMessage, uint16_t aOffset, typename UintTlvType::UintValueType & aValue) inline static
This static method reads a simple TLV with a single integral value in a message at a given offset.
Template Parameters
UintTlvType The simple TLV type to read (must be a sub-class of UintTlvInfo).
Parameters
[in] aMessage The message to read from.
[in] aOffset The offset into the message pointing to the start of the TLV.
[out] aValue A reference to an unsigned int to output the read value.
Return values
kErrorNone Successfully read the TLV and updated the aValue.
kErrorParse The TLV was not well-formed and could not be parsed.
References Tlv::FindTlv(), and Tlv::ReadUintTlv().
FindTlv() [1/3]
Error FindTlv (const Message & aMessage, uint8_t aType, uint16_t aMaxSize, Tlv & aTlv) static
This static method searches for and reads a requested TLV out of a given message.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[in] aMaxSize Maximum number of bytes to read.
[out] aTlv A reference to the TLV that will be copied to.
Return values
kErrorNone Successfully copied the TLV.
kErrorNotFound Could not find the TLV with Type aType.
References Tlv::Find(), Message::ReadBytes(), and SuccessOrExit.
Referenced by Tlv::Find(), Tlv::FindTlv(), Mle::HandleAnnounce(), Mle::HandleParentResponse(), Tlv::Read(), Mle::RxMessage::ReadLeaderDataTlv(), and Mle::RxMessage::ReadTlvRequestTlv().
FindTlv() [2/3]
static Error FindTlv (const Message & aMessage, TlvType & aTlv) inline static
This static method searches for and reads a requested TLV out of a given message.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Template Parameters
TlvType The TlvType to search for (must be a sub-class of Tlv).
Parameters
[in] aMessage A reference to the message.
[out] aTlv A reference to the TLV that will be copied to.
Return values
kErrorNone Successfully copied the TLV.
kErrorNotFound Could not find the TLV with Type aType.
References Tlv::FindTlv(), Tlv::FindTlvOffset(), and Tlv::FindTlvValueOffset().
FindTlvOffset()
Error FindTlvOffset (const Message & aMessage, uint8_t aType, uint16_t & aOffset) static
This static method obtains the offset of a TLV within aMessage.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[out] aOffset A reference to the offset of the TLV.
Return values
kErrorNone Successfully copied the TLV.
kErrorNotFound Could not find the TLV with Type aType.
References Tlv::Find().
Referenced by Tlv::FindTlv(), Tlv::FindUintTlv(), Mle::HandleChildIdResponse(), DiscoverScanner::HandleDiscoveryResponse(), and Mle::HandleLeaderData().
FindTlvValueOffset()
Error FindTlvValueOffset (const Message & aMessage, uint8_t aType, uint16_t & aValueOffset, uint16_t & aLength) static
This static method finds the offset and length of a given TLV type.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[out] aValueOffset The offset where the value starts.
[out] aLength The length of the value.
Return values
kErrorNone Successfully found the TLV.
kErrorNotFound Could not find the TLV with Type aType.
References Tlv::Find(), and SuccessOrExit.
Referenced by Tlv::FindTlv(), ChannelMaskTlv::GetChannelMask(), Mle::HandleDataResponse(), Mle::RxMessage::ReadChallengeOrResponse(), and Mle::RxMessage::ReadTlvRequestTlv().
Find() [1/4]
static Error Find (const Message & aMessage, void * aValue, uint8_t aLength) inline static
This static method searches for a TLV with a given type in a message, ensures its length is same or larger than an expected minimum value, and then reads its value into a given buffer.
If the TLV length is smaller than the minimum length aLength, the TLV is considered invalid. In this case, this method returns kErrorParse and the aValue buffer is not updated.
If the TLV length is larger than aLength, the TLV is considered valid, but only the first aLength bytes of the value are read and copied into the aValue buffer.
Template Parameters
TlvType The TLV type to find.
Parameters
[in] aMessage A reference to the message.
[out] aValue A buffer to output the value (must contain at least aLength bytes).
[in] aLength The expected (minimum) length of the TLV value.
Return values
kErrorNone The TLV was found and read successfully. aValue is updated.
kErrorNotFound Could not find the TLV with Type aType.
kErrorParse TLV was found but it was not well-formed and could not be parsed.
References Tlv::FindTlv().
Referenced by Tlv::FindTlv(), Tlv::FindTlvOffset(), and Tlv::FindTlvValueOffset().
Find() [2/4]
static Error Find (const Message & aMessage, typename SimpleTlvType::ValueType & aValue) inline static
This static method searches for a simple TLV with a single non-integral value in a message, ensures its length is same or larger than the expected ValueType object size, and then reads its value into a value object reference.
If the TLV length is smaller than the size of aValue, the TLV is considered invalid. In this case, this method returns kErrorParse and the aValue is not updated.
If the TLV length is larger than the size of aValue, the TLV is considered valid, but the size of ValueType bytes are read and copied into the aValue.
Template Parameters
SimpleTlvType The simple TLV type to find (must be a sub-class of SimpleTlvInfo)
Parameters
[in] aMessage A reference to the message.
[out] aValue A reference to the value object to output the read value.
Return values
kErrorNone The TLV was found and read successfully. aValue is updated.
kErrorNotFound Could not find the TLV with Type aType.
kErrorParse TLV was found but it was not well-formed and could not be parsed.
References Tlv::FindTlv().
Find() [3/4]
static Error Find (const Message & aMessage, typename UintTlvType::UintValueType & aValue) inline static
This static method searches for a simple TLV with a single integral value in a message, and then reads its value into a given uint reference variable.
If the TLV length is smaller than size of integral value, the TLV is considered invalid. In this case, this method returns kErrorParse and the aValue is not updated.
Template Parameters
UintTlvType The simple TLV type to find (must be a sub-class of UintTlvInfo)
Parameters
[in] aMessage A reference to the message.
[out] aValue A reference to an unsigned int value to output the TLV's value.
Return values
kErrorNone The TLV was found and read successfully. aValue is updated.
kErrorNotFound Could not find the TLV with Type aType.
kErrorParse TLV was found but it was not well-formed and could not be parsed.
References Tlv::FindUintTlv().
Append() [1/3]
static Error Append (Message & aMessage, const void * aValue, uint8_t aLength) inline static
This static method appends a TLV with a given type and value to a message.
On success this method grows the message by the size of the TLV.
Template Parameters
TlvType The TLV type to append.
Parameters
[in] aMessage A reference to the message to append to.
[in] aValue A buffer containing the TLV value.
[in] aLength The value length (in bytes).
Return values
kErrorNone Successfully appended the TLV to the message.
kErrorNoBufs Insufficient available buffers to grow the message.
References Tlv::AppendTlv().
Append() [2/3]
static Error Append (Message & aMessage, const typename SimpleTlvType::ValueType & aValue) inline static
This static method appends a simple TLV with a single (non-integral) value to a message.
On success this method grows the message by the size of the TLV.
Template Parameters
SimpleTlvType The simple TLV type to append (must be a sub-class of SimpleTlvInfo)
Parameters
[in] aMessage A reference to the message to append to.
[in] aValue A reference to the object containing TLV's value.
Return values
kErrorNone Successfully appended the TLV to the message.
kErrorNoBufs Insufficient available buffers to grow the message.
References Tlv::AppendTlv().
Append() [3/3]
static Error Append (Message & aMessage, typename UintTlvType::UintValueType aValue) inline static
This static method appends a simple TLV with a single integral value to a message.
On success this method grows the message by the size of the TLV.
Template Parameters
UintTlvType The simple TLV type to append (must be a sub-class of UintTlvInfo)
Parameters
[in] aMessage A reference to the message to append to.
[in] aValue An unsigned int value to use as TLV's value.
Return values
kErrorNone Successfully appended the TLV to the message.
kErrorNoBufs Insufficient available buffers to grow the message.
References Tlv::AppendUintTlv().
Find() [4/4]
Error Find (const Message & aMessage, uint8_t aType, uint16_t * aOffset, uint16_t * aSize, bool * aIsExtendedTlv) static private
References ExitNow, Message::GetLength(), ExtendedTlv::GetLength(), Message::GetOffset(), Tlv::GetSize(), Tlv::GetType(), ot::kErrorNone, ot::kErrorNotFound, Tlv::kExtendedLength, Tlv::mLength, Message::Read(), SuccessOrExit, and VerifyOrExit.
FindTlv() [3/3]
Error FindTlv (const Message & aMessage, uint8_t aType, void * aValue, uint8_t aLength) static private
References Tlv::FindTlvValueOffset(), ot::kErrorParse, Message::ReadBytes(), SuccessOrExit, and VerifyOrExit.
AppendTlv()
Error AppendTlv (Message & aMessage, uint8_t aType, const void * aValue, uint8_t aLength) static private
References Message::Append(), Message::AppendBytes(), Tlv::kBaseTlvMaxLength, ot::kErrorNone, OT_ASSERT, Tlv::SetLength(), Tlv::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by Tlv::Append(), and Tlv::AppendUintTlv().
ReadUintTlv()
template Error ReadUintTlv< uint32_t > (const Message & aMessage, uint16_t aOffset, UintType & aValue) static private
References Tlv::ReadTlv(), and SuccessOrExit.
Referenced by Tlv::Read().
FindUintTlv()
template Error FindUintTlv< uint32_t > (const Message & aMessage, uint8_t aType, UintType & aValue) static private
References Tlv::FindTlvOffset(), ot::kErrorNone, and SuccessOrExit.
Referenced by Tlv::Find().
AppendUintTlv()
template Error AppendUintTlv< uint32_t > (Message & aMessage, uint8_t aType, UintType aValue) static private
References Tlv::AppendTlv().
Referenced by Tlv::Append().
Field Documentation
kBaseTlvMaxLength
constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH static
The maximum length of the Base TLV format.
Referenced by Tlv::AppendTlv().
kExtendedLength
const uint8_t kExtendedLength = 255 static protected
Referenced by Tlv::Find(), Tlv::IsExtended(), and ExtendedTlv::SetLength().
mType
uint8_t mType private
Referenced by Tlv::GetType(), and Tlv::SetType().
mLength
uint8_t mLength private
Referenced by Tlv::Find(), Tlv::GetLength(), ExtendedTlv::GetLength(), Tlv::IsExtended(), Tlv::SetLength(), and ExtendedTlv::SetLength().
The documentation for this class was generated from the following files:
tlvs.hpp
tlvs.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale