OpenThread: Name Class Reference
Name Class Reference
Core-dns
#include <dns_types.hpp>
Data Structures
struct LabelIterator
Public Types
enum Type : uint8_t { kTypeEmpty, kTypeCString, kTypeMessage }
Public Member Functions
Error AppendTo (Message &aMessage) const
const char * GetAsCString (void) const
const Message & GetAsMessage (uint16_t &aOffset) const
Type GetFromType (void) const
bool IsEmpty (void) const
bool IsFromCString (void) const
bool IsFromMessage (void) const
Name (void)
Name (const char *aString)
Name (const Message &aMessage, uint16_t aOffset)
void Set (const char *aString)
void SetFromMessage (const Message &aMessage, uint16_t aOffset)
Public Member Functions inherited from Clearable< Name >
void Clear (void)
Static Public Member Functions
static Error AppendLabel (const char *aLabel, Message &aMessage)
static Error AppendLabel (const char *aLabel, uint8_t aLength, Message &aMessage)
static Error AppendMultipleLabels (const char *aLabels, Message &aMessage)
static Error AppendMultipleLabels (const char *aLabels, uint8_t aLength, Message &aMessage)
static Error AppendName (const char *aName, Message &aMessage)
static Error AppendPointerLabel (uint16_t aOffset, Message &aMessage)
static Error AppendTerminator (Message &aMessage)
static Error CompareLabel (const Message &aMessage, uint16_t &aOffset, const char *aLabel)
static Error CompareName (const Message &aMessage, uint16_t &aOffset, const char *aName)
static Error CompareName (const Message &aMessage, uint16_t &aOffset, const Message &aMessage2, uint16_t aOffset2)
static Error CompareName (const Message &aMessage, uint16_t &aOffset, const Name &aName)
static bool IsSubDomainOf (const char *aName, const char *aDomain)
static Error ParseName (const Message &aMessage, uint16_t &aOffset)
static Error ReadLabel (const Message &aMessage, uint16_t &aOffset, char *aLabelBuffer, uint8_t &aLabelLength)
static Error ReadName (const Message &aMessage, uint16_t &aOffset, char *aNameBuffer, uint16_t aNameBufferSize)
Static Public Attributes
static constexpr char kLabelSeperatorChar = '.'
static constexpr uint8_t kMaxLabelLength = kMaxLabelSize - 1
static constexpr uint8_t kMaxLabelSize = OT_DNS_MAX_LABEL_SIZE
static constexpr uint8_t kMaxNameLength = kMaxNameSize - 1
static constexpr uint8_t kMaxNameSize = OT_DNS_MAX_NAME_SIZE
Private Member Functions
Name (const char *aString, const Message *aMessage, uint16_t aOffset)
Private Attributes
const Message * mMessage
uint16_t mOffset
const char * mString
Static Private Attributes
static constexpr bool kIsSingleLabel = true
static constexpr uint8_t kLabelTypeMask = 0xc0
static constexpr uint8_t kMaxEncodedLength = 255
Max length of an encoded name.
static constexpr uint16_t kPointerLabelOffsetMask = 0x3fff
static constexpr uint8_t kPointerLabelType = 0xc0
static constexpr uint16_t kPointerLabelTypeUint16 = 0xc000
static constexpr uint8_t kTextLabelType = 0x00
Detailed Description
This class represents a DNS name and implements helper methods for encoding/decoding of DNS Names.
Member Enumeration Documentation
Type
enum Type : uint8_t
This enumeration represents the name type.
Enumerator
kTypeEmpty
The name is empty (not specified).
kTypeCString
The name is given as a C string (dot '.' separated sequence of labels).
kTypeMessage
The name is specified from a message at a given offset (encoded in the message).
Constructor & Destructor Documentation
Name() [1/4]
Name (void) inline
This constructor initializes the Name object as empty (not specified).
Name() [2/4]
Name (const char * aString) inline explicit
This constructor initializes the Name object with a given string.
Parameters
[in] aString A C string specifying the name (dot '.' separated sequence of labels').
Name() [3/4]
Name (const Message & aMessage, uint16_t aOffset) inline
This constructor initializes the Name object from a message at a given offset.
Parameters
[in] aMessage The message containing the encoded name. aMessage.GetOffset() MUST point to the start of the DNS header in the message (used to parse compressed name).
[in] aOffset The offset in aMessage pointing to the start of the name.
Name() [4/4]
Name (const char * aString, const Message * aMessage, uint16_t aOffset) inline private
Member Function Documentation
IsEmpty()
bool IsEmpty (void) const inline
This method indicates whether the name is empty (not specified).
Returns
TRUE if the name is empty, FALSE otherwise.
IsFromCString()
bool IsFromCString (void) const inline
This method indicates whether the name is specified from a C string.
Returns
TRUE if the name is specified from a string, FALSE otherwise.
Referenced by Name::CompareName().
IsFromMessage()
bool IsFromMessage (void) const inline
This method indicates whether the name is specified from a message.
Returns
TRUE if the name is specified from a message, FALSE otherwise.
Referenced by Name::CompareName().
GetFromType()
Type GetFromType (void) const inline
This method gets the type of Name object indicating whether it is empty, specified by a C string or from a message
Returns
The name type.
Set()
void Set (const char * aString) inline
This method sets the name from a given C string.
Parameters
[in] aString A C string specifying the name (dot '.' separated sequence of labels).
SetFromMessage()
void SetFromMessage (const Message & aMessage, uint16_t aOffset) inline
This method sets the name from a message at a given offset.
Parameters
[in] aMessage The message containing the encoded name. aMessage.GetOffset() MUST point to the start of the DNS header in the message (used to parse compressed name).
[in] aOffset The offset in aMessage pointing to the start of the name.
GetAsCString()
const char* GetAsCString (void) const inline
This method gets the name as a C string.
This method MUST be used only when the type is kTypeString. Otherwise its behavior is undefined.
Returns
A pointer to the C string.
GetAsMessage()
const Message& GetAsMessage (uint16_t & aOffset) const inline
This method gets the name message and offset.
This method MUST be used only when the type is kTypeMessage. Otherwise its behavior is undefined.
Parameters
[out] aOffset A reference to a variable to output the offset of the start of the name in the message.
Returns
A reference to the message containing the name.
AppendTo()
Error AppendTo (Message & aMessage) const
This method encodes and appends the name to a message.
If the name is empty (not specified), then root "." is appended to aMessage. If the name is from a C string then the string is checked and appended (similar to static AppendName(const char *aName, Message &) method). If the the name is from a message, then it is read from the message and appended to aMessage. Note that in this case independent of whether the name is compressed or not in its original message, the name is appended as full (uncompressed) in aMessage.
Parameters
[in] aMessage The message to append to.
Return values
kErrorNone Successfully encoded and appended the name to aMessage.
kErrorInvalidArgs Name is not valid.
kErrorNoBufs Insufficient available buffers to grow the message.
References Name::LabelIterator::AppendLabel(), ExitNow, Name::LabelIterator::GetNextLabel(), ot::kErrorNone, ot::kErrorNotFound, OT_FALL_THROUGH, and SuccessOrExit.
AppendLabel() [1/2]
Error AppendLabel (const char * aLabel, Message & aMessage) static
This static method encodes and appends a single name label to a message.
The aLabel is assumed to contain a single name label as a C string (null-terminated). Unlike AppendMultipleLabels() which parses the label string and treats it as sequence of multiple (dot-separated) labels, this method always appends aLabel as a single whole label. This allows the label string to even contain dot '.' character, which, for example, is useful for "Service Instance Names" where <Instance> portion is a user-friendly name and can contain dot characters.
Parameters
[in] aLabel The label string to append. MUST NOT be nullptr.
[in] aMessage The message to append to.
Return values
kErrorNone Successfully encoded and appended the name label to aMessage.
kErrorInvalidArgs aLabel is not valid (e.g., label length is not within valid range).
kErrorNoBufs Insufficient available buffers to grow the message.
References ot::StringLength().
AppendLabel() [2/2]
Error AppendLabel (const char * aLabel, uint8_t aLength, Message & aMessage) static
This static method encodes and appends a single name label of specified length to a message.
The aLabel is assumed to contain a single name label of given aLength. aLabel must not contain '\0' characters within the length aLength. Unlike AppendMultipleLabels() which parses the label string and treats it as sequence of multiple (dot-separated) labels, this method always appends aLabel as a single whole label. This allows the label string to even contain dot '.' character, which, for example, is useful for "Service Instance Names" where <Instance> portion is a user-friendly name and can contain dot characters.
Parameters
[in] aLabel The label string to append. MUST NOT be nullptr.
[in] aLength The length of the label to append.
[in] aMessage The message to append to.
Return values
kErrorNone Successfully encoded and appended the name label to aMessage.
kErrorInvalidArgs aLabel is not valid (e.g., label length is not within valid range).
kErrorNoBufs Insufficient available buffers to grow the message.
References Message::Append(), Message::AppendBytes(), ot::kErrorInvalidArgs, ot::kErrorNone, SuccessOrExit, and VerifyOrExit.
AppendMultipleLabels() [1/2]
Error AppendMultipleLabels (const char * aLabels, Message & aMessage) static
This static method encodes and appends a sequence of name labels to a given message.
The aLabels must follow "<label1>.<label2>.<label3>", i.e., a sequence of labels separated by dot '.' char. E.g., "_http._tcp", "_http._tcp." (same as previous one), "host-1.test".
This method validates that the aLabels is a valid name format, i.e., no empty label, and labels are kMaxLabelLength (63) characters or less.
Note
This method NEVER adds a label terminator (empty label) to the message, even in the case where aLabels ends with a dot character, e.g., "host-1.test." is treated same as "host-1.test".
Parameters
[in] aLabels A name label string. Can be nullptr (then treated as "").
[in] aMessage The message to which to append the encoded name.
Return values
kErrorNone Successfully encoded and appended the name label(s) to aMessage.
kErrorInvalidArgs Name label aLabels is not valid.
kErrorNoBufs Insufficient available buffers to grow the message.
AppendMultipleLabels() [2/2]
Error AppendMultipleLabels (const char * aLabels, uint8_t aLength, Message & aMessage) static
This static method encodes and appends a sequence of name labels within the specified length to a given message. This method stops appending labels if aLength characters are read or '\0' is found before aLength characters.
This method is useful for appending a number of labels of the name instead of appending all labels.
The aLabels must follow "<label1>.<label2>.<label3>", i.e., a sequence of labels separated by dot '.' char. E.g., "_http._tcp", "_http._tcp." (same as previous one), "host-1.test".
This method validates that the aLabels is a valid name format, i.e., no empty label, and labels are kMaxLabelLength (63) characters or less.
Note
This method NEVER adds a label terminator (empty label) to the message, even in the case where aLabels ends with a dot character, e.g., "host-1.test." is treated same as "host-1.test".
Parameters
[in] aLabels A name label string. Can be nullptr (then treated as "").
[in] aLength The max length of the name labels to encode.
[in] aMessage The message to which to append the encoded name.
Return values
kErrorNone Successfully encoded and appended the name label(s) to aMessage.
kErrorInvalidArgs Name label aLabels is not valid.
kErrorNoBufs Insufficient available buffers to grow the message.
References ExitNow, ot::kErrorInvalidArgs, ot::kErrorNone, ot::kNullChar, SuccessOrExit, and VerifyOrExit.
AppendTerminator()
Error AppendTerminator (Message & aMessage) static
This static method appends a name label terminator to a message.
An encoded name is terminated by an empty label (a zero byte).
Parameters
[in] aMessage The message to append to.
Return values
kErrorNone Successfully encoded and appended the terminator label to aMessage.
kErrorNoBufs Insufficient available buffers to grow the message.
References Message::Append().
AppendPointerLabel()
Error AppendPointerLabel (uint16_t aOffset, Message & aMessage) static
This static method appends a pointer type name label to a message.
Pointer label is used for name compression. It allows an entire name or a list of labels at the end of an encoded name to be replaced with a pointer to a prior occurrence of the same name within the message.
Parameters
[in] aOffset The offset from the start of DNS header to use for pointer value.
[in] aMessage The message to append to.
Return values
kErrorNone Successfully encoded and appended the pointer label to aMessage.
kErrorNoBufs Insufficient available buffers to grow the message.
References Message::Append(), ExitNow, Message::GetOffset(), ot::Encoding::BigEndian::HostSwap16(), and OT_ASSERT.
AppendName()
Error AppendName (const char * aName, Message & aMessage) static
This static method encodes and appends a full name to a message.
The aName must follow "<label1>.<label2>.<label3>", i.e., a sequence of labels separated by dot '.' char. E.g., "example.com", "example.com." (same as previous one), "local.", "default.service.arpa", "." or "" (root).
This method validates that the aName is a valid name format, i.e. no empty labels, and labels are kMaxLabelLength (63) characters or less, and the name is kMaxLength (255) characters or less.
Parameters
[in] aName A name string. Can be nullptr (then treated as "." or root).
[in] aMessage The message to append to.
Return values
kErrorNone Successfully encoded and appended the name to aMessage.
kErrorInvalidArgs Name aName is not valid.
kErrorNoBufs Insufficient available buffers to grow the message.
References SuccessOrExit.
ParseName()
Error ParseName (const Message & aMessage, uint16_t & aOffset) static
This static method parses and skips over a full name in a message.
Parameters
[in] aMessage The message to parse the name from. aMessage.GetOffset() MUST point to the start of DNS header (this is used to handle compressed names).
[in,out] aOffset On input the offset in aMessage pointing to the start of the name field. On exit (when parsed successfully), aOffset is updated to point to the byte after the end of name field.
Return values
kErrorNone Successfully parsed and skipped over name, Offset is updated.
kErrorParse Name could not be parsed (invalid format).
References ExitNow, Name::LabelIterator::GetNextLabel(), ot::kErrorNone, ot::kErrorNotFound, Name::LabelIterator::mNameEndOffset, and OT_FALL_THROUGH.
Referenced by ResourceRecord::ParseRecords(), and PtrRecord::ReadPtrName().
ReadLabel()
Error ReadLabel (const Message & aMessage, uint16_t & aOffset, char * aLabelBuffer, uint8_t & aLabelLength) static
This static method reads a name label from a message.
This method can be used to read labels one by one in a name. After a successful label read, aOffset is updated to point to the start of the next label. When we reach the end of the name, kErrorNotFound is returned. This method handles compressed names which use pointer labels. So as the labels in a name are read, the aOffset may jump back in the message and at the end the aOffset does not necessarily point to the end of the original name field.
Unlike ReadName() which requires and verifies that the read label to contain no dot '.' character, this method allows the read label to include any character.
Parameters
[in] aMessage The message to read the label from. aMessage.GetOffset() MUST point to the start of DNS header (this is used to handle compressed names).
[in,out] aOffset On input, the offset in aMessage pointing to the start of the label to read. On exit, when successfully read, aOffset is updated to point to the start of the next label.
[out] aLabelBuffer A pointer to a char array to output the read label as a null-terminated C string.
[in,out] aLabelLength On input, the maximum number chars in aLabelBuffer array. On output, when label is successfully read, aLabelLength is updated to return the label's length (number of chars in the label string, excluding the null char).
Return values
kErrorNone Successfully read the label and updated aLabelBuffer, aLabelLength, and aOffset.
kErrorNotFound Reached the end of name and no more label to read.
kErrorParse Name could not be parsed (invalid format).
kErrorNoBufs Label could not fit in aLabelLength chars.
References Name::LabelIterator::GetNextLabel(), Name::LabelIterator::mNextLabelOffset, Name::LabelIterator::ReadLabel(), and SuccessOrExit.
Referenced by PtrRecord::ReadPtrName().
ReadName()
Error ReadName (const Message & aMessage, uint16_t & aOffset, char * aNameBuffer, uint16_t aNameBufferSize) static
This static method reads a full name from a message.
On successful read, the read name follows "<label1>.<label2>.<label3>.", i.e., a sequence of labels separated by dot '.' character. The read name will ALWAYS end with a dot.
This method verifies that the read labels in message do not contain any dot character, otherwise it returns kErrorParse).
Parameters
[in] aMessage The message to read the name from. aMessage.GetOffset() MUST point to the start of DNS header (this is used to handle compressed names).
[in,out] aOffset On input, the offset in aMessage pointing to the start of the name field. On exit (when parsed successfully), aOffset is updated to point to the byte after the end of name field.
[out] aNameBuffer A pointer to a char array to output the read name as a null-terminated C string.
[in,out] aNameBufferSize The maximum number of chars in aNameBuffer array.
Return values
kErrorNone Successfully read the name, aNameBuffer and Offset are updated.
kErrorParse Name could not be parsed (invalid format).
kErrorNoBufs Name could not fit in aNameBufferSize chars.
References ExitNow, Name::LabelIterator::GetNextLabel(), ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNotFound, ot::kNullChar, ot::Min(), Name::LabelIterator::mNameEndOffset, OT_FALL_THROUGH, Name::LabelIterator::ReadLabel(), SuccessOrExit, and VerifyOrExit.
Referenced by ResourceRecord::ReadName(), and PtrRecord::ReadPtrName().
CompareLabel()
Error CompareLabel (const Message & aMessage, uint16_t & aOffset, const char * aLabel) static
This static method compares a single name label from a message with a given label string.
This method can be used to compare labels one by one. It checks whether the label read from aMessage matches aLabel string (case-insensitive comparison).
Unlike CompareName() which requires the labels in the the name string to contain no dot '.' character, this method allows aLabel to include any character.
Parameters
[in] aMessage The message to read the label from to compare. aMessage.GetOffset() MUST point to the start of DNS header (this is used to handle compressed names).
[in,out] aOffset On input, the offset in aMessage pointing to the start of the label to read. On exit and only when label is successfully read and does match aLabel, aOffset is updated to point to the start of the next label.
[in] aLabel A pointer to a null terminated string containing the label to compare with.
Return values
kErrorNone The label from aMessage matches aLabel. aOffset is updated.
kErrorNotFound The label from aMessage does not match aLabel (note that aOffset is not updated in this case).
kErrorParse Name could not be parsed (invalid format).
References Name::LabelIterator::CompareLabel(), Name::LabelIterator::GetNextLabel(), ot::kErrorNotFound, Name::LabelIterator::mNextLabelOffset, SuccessOrExit, and VerifyOrExit.
CompareName() [1/3]
Error CompareName (const Message & aMessage, uint16_t & aOffset, const char * aName) static
This static method parses and compares a full name from a message with a given name.
This method checks whether the encoded name in a message matches a given name string (using case-insensitive comparison). It checks the name in the message in place and handles compressed names. If the name read from the message does not match aName, it returns kErrorNotFound. kErrorNone indicates that the name matches aName.
The aName must follow "<label1>.<label2>.<label3>", i.e., a sequence of labels separated by dot '.' char. E.g., "example.com", "example.com." (same as previous one), "local.", "default.service.arpa", "." or "" (root).
Parameters
[in] aMessage The message to read the name from and compare with aName. aMessage.GetOffset() MUST point to the start of DNS header (this is used to handle compressed names).
[in,out] aOffset On input, the offset in aMessage pointing to the start of the name field. On exit (when parsed successfully independent of whether the read name matches aName or not), aOffset is updated to point to the byte after the end of the name field.
[in] aName A pointer to a null terminated string containing the name to compare with.
Return values
kErrorNone The name from aMessage matches aName. aOffset is updated.
kErrorNotFound The name from aMessage does not match aName. aOffset is updated.
kErrorParse Name could not be parsed (invalid format).
kErrorInvalidArgs The aName is not a valid name (e.g. back to back "." chars)
References Name::LabelIterator::CompareLabel(), ExitNow, Name::LabelIterator::GetNextLabel(), ot::kErrorInvalidArgs, ot::kErrorNone, ot::kErrorNotFound, ot::kNullChar, Name::LabelIterator::mNameEndOffset, OT_FALL_THROUGH, and VerifyOrExit.
Referenced by ResourceRecord::FindRecord().
CompareName() [2/3]
Error CompareName (const Message & aMessage, uint16_t & aOffset, const Message & aMessage2, uint16_t aOffset2) static
This static method parses and compares a full name from a message with a name from another message.
This method checks whether the encoded name in aMessage matches the name from aMessage2 (using case-insensitive comparison). It compares the names in both messages in place and handles compressed names. Note that this method works correctly even when the same message instance is used for both aMessage and aMessage2 (e.g., at different offsets).
Only the name in aMessage is fully parsed and checked for parse errors. This method assumes that the name in aMessage2 was previously parsed and validated before calling this method (if there is a parse error in aMessage2, it is treated as a name mismatch with aMessage).
If the name in aMessage can be parsed fully (independent of whether the name matches or not with the name from aMessage2), the aOffset is updated (note that aOffset2 for aMessage2 is not changed).
Parameters
[in] aMessage The message to read the name from and compare. aMessage.GetOffset() MUST point to the start of DNS header (this is used to handle compressed names).
[in,out] aOffset On input, the offset in aMessage pointing to the start of the name field. On exit (when parsed successfully independent of whether the read name matches or not), aOffset is updated to point to the byte after the end of the name field.
[in] aMessage2 The second message to read the name from and compare with name from aMessage. aMessage2.GetOffset() MUST point to the start of DNS header.
[in] aOffset2 The offset in aMessage2 pointing to the start of the name field.
Return values
kErrorNone The name from aMessage matches the name from aMessage2. aOffset is updated.
kErrorNotFound The name from aMessage does not match the name from aMessage2. aOffset is updated.
kErrorParse Name in aMessage could not be parsed (invalid format).
References Name::LabelIterator::CompareLabel(), ExitNow, Name::LabelIterator::GetNextLabel(), ot::kErrorNone, ot::kErrorNotFound, Name::LabelIterator::mNameEndOffset, and OT_FALL_THROUGH.
CompareName() [3/3]
Error CompareName (const Message & aMessage, uint16_t & aOffset, const Name & aName) static
This static method parses and compares a full name from a message with a given name (using case-insensitive comparison).
If aName is empty (not specified), then any name in aMessage is considered a match to it.
Parameters
[in] aMessage The message to read the name from and compare. aMessage.GetOffset() MUST point to the start of DNS header (this is used to handle compressed names).
[in,out] aOffset On input, the offset in aMessage pointing to the start of the name field. On exit (when parsed successfully independent of whether the read name matches or not), aOffset is updated to point to the byte after the end of the name field.
[in] aName A reference to a name to compare with.
Return values
kErrorNone The name from aMessage matches aName. aOffset is updated.
kErrorNotFound The name from aMessage does not match aName. aOffset is updated.
kErrorParse Name in aMessage could not be parsed (invalid format).
References Name::IsFromCString(), Name::IsFromMessage(), Name::mMessage, Name::mOffset, and Name::mString.
IsSubDomainOf()
bool IsSubDomainOf (const char * aName, const char * aDomain) static
This static method tests if a DNS name is a sub-domain of a given domain.
Both aName and aDomain can end without dot ('.').
Parameters
[in] aName The dot-separated name.
[in] aDomain The dot-separated domain.
Returns
TRUE if the name is a sub-domain of aDomain, FALSE if is not.
References ot::kStringCaseInsensitiveMatch, ot::StringLength(), ot::StringMatch(), ot::StringStartsWith(), and VerifyOrExit.
Field Documentation
kMaxNameSize
constexpr uint8_t kMaxNameSize = OT_DNS_MAX_NAME_SIZE static
Max size (number of chars) in a name string array (includes null char at the end of string).
kMaxNameLength
constexpr uint8_t kMaxNameLength = kMaxNameSize - 1 static
Maximum length in a name string (does not include null char at the end of string).
kMaxLabelSize
constexpr uint8_t kMaxLabelSize = OT_DNS_MAX_LABEL_SIZE static
Max size (number of chars) in a label string array (includes null char at the end of the string).
kMaxLabelLength
constexpr uint8_t kMaxLabelLength = kMaxLabelSize - 1 static
Maximum length in a label string (does not include null char at the end of string).
kLabelSeperatorChar
constexpr char kLabelSeperatorChar = '.' static
kLabelTypeMask
constexpr uint8_t kLabelTypeMask = 0xc0 static private
kTextLabelType
constexpr uint8_t kTextLabelType = 0x00 static private
kPointerLabelType
constexpr uint8_t kPointerLabelType = 0xc0 static private
kMaxEncodedLength
constexpr uint8_t kMaxEncodedLength = 255 static private
Max length of an encoded name.
kPointerLabelTypeUint16
constexpr uint16_t kPointerLabelTypeUint16 = 0xc000 static private
kPointerLabelOffsetMask
constexpr uint16_t kPointerLabelOffsetMask = 0x3fff static private
kIsSingleLabel
constexpr bool kIsSingleLabel = true static private
mString
const char* mString private
Referenced by Name::CompareName().
mMessage
const Message* mMessage private
Referenced by Name::CompareName().
mOffset
uint16_t mOffset private
Referenced by Name::CompareName().
The documentation for this class was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale