OpenThread: ServiceConfig::ServerConfig Class Reference
ServiceConfig::ServerConfig Class Reference
#include <network_data_types.hpp>
Public Member Functions
void GetServerData (ServerData &aServerData) const
bool operator== (const ServerConfig &aOther) const
Public Member Functions inherited from Unequatable< ServerConfig >
bool operator!= (const ServerConfig &aOther) const
Private Member Functions
void SetFrom (const ServerTlv &aServerTlv)
Friends
class ServiceConfig
Additional Inherited Members
Data Fields inherited from otServerConfig
uint16_t mRloc16
The Server RLOC16.
uint8_t mServerData [OT_SERVER_DATA_MAX_SIZE]
Server data bytes.
uint8_t mServerDataLength
Length of server data.
bool mStable: 1
Whether this config is considered Stable Network Data.
Detailed Description
This class represents a Server configuration.
Member Function Documentation
GetServerData()
void GetServerData (ServerData & aServerData) const inline
This method gets the Server Data.
Parameters
[out] aServerData A reference to aServerData to return the data.
References Data< kDataLengthType >::Init(), Equatable< OnMeshPrefixConfig >::operator==(), and OnMeshPrefixConfig::SetFrom().
operator==()
bool operator== (const ServerConfig & aOther) const
This method overloads operator == to evaluate whether or not two ServerConfig instances are equal.
Parameters
[in] aOther The other ServerConfig instance to compare with.
Return values
TRUE If the two ServerConfig instances are equal.
FALSE If the two ServerConfig instances are not equal.
References otServerConfig::mServerData, otServerConfig::mServerDataLength, otBorderRouterConfig::mStable, and otServerConfig::mStable.
SetFrom()
void SetFrom (const ServerTlv & aServerTlv) private
References Data< kDataLengthType >::CopyBytesTo(), Data< kDataLengthType >::GetLength(), ServerTlv::GetServer16(), ServerTlv::GetServerData(), NetworkDataTlv::IsStable(), otBorderRouterConfig::mRloc16, and otBorderRouterConfig::mStable.
Friends And Related Function Documentation
ServiceConfig
friend class ServiceConfig friend
The documentation for this class was generated from the following files:
network_data_types.hpp
network_data_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale