OpenThread: InterfaceIdentifier Class Reference
InterfaceIdentifier Class Reference
Core-ipv6 » IPv6
#include <ip6_address.hpp>
Public Types
typedef String< kInfoStringSize > InfoString
Public Member Functions
void ApplyPrefix (const Prefix &aPrefix)
void ConvertToExtAddress (Mac::ExtAddress &aExtAddress) const
void ConvertToMacAddress (Mac::Address &aMacAddress) const
void GenerateRandom (void)
const uint8_t * GetBytes (void) const
uint16_t GetLocator (void) const
bool IsAnycastLocator (void) const
bool IsAnycastServiceLocator (void) const
bool IsLocator (void) const
bool IsReserved (void) const
bool IsReservedSubnetAnycast (void) const
bool IsRoutingLocator (void) const
bool IsSubnetRouterAnycast (void) const
bool IsUnspecified (void) const
void SetBytes (const uint8_t *aBuffer)
void SetFromExtAddress (const Mac::ExtAddress &aExtAddress)
void SetLocator (uint16_t aLocator)
void SetToLocator (uint16_t aLocator)
InfoString ToString (void) const
Public Member Functions inherited from Equatable< InterfaceIdentifier >
bool operator== (const InterfaceIdentifier &aOther) const
Public Member Functions inherited from Unequatable< InterfaceIdentifier >
bool operator!= (const InterfaceIdentifier &aOther) const
Public Member Functions inherited from Clearable< InterfaceIdentifier >
void Clear (void)
Static Public Attributes
static constexpr uint16_t kInfoStringSize = 17
Max chars for the info string (ToString()).
static constexpr uint8_t kSize = OT_IP6_IID_SIZE
Size of an IPv6 Interface Identifier (in bytes).
Static Private Attributes
static constexpr uint8_t kAloc16Mask = 0xfc
static constexpr uint8_t kRloc16ReservedBitMask = 0x02
Friends
class Address
Additional Inherited Members
Data Fields inherited from otIp6InterfaceIdentifier
union otIp6InterfaceIdentifier::OT_TOOL_PACKED_FIELD mFields
The Interface Identifier accessor fields.
Detailed Description
This class represents the Interface Identifier of an IPv6 address.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Function Documentation
IsUnspecified()
bool IsUnspecified (void) const
This method indicates whether or not the Interface Identifier is unspecified.
Return values
true If the Interface Identifier is unspecified.
false If the Interface Identifier is not unspecified.
IsReserved()
bool IsReserved (void) const
This method indicates whether or not the Interface Identifier is reserved (RFC 5453).
Return values
true If the Interface Identifier is reserved.
false If the Interface Identifier is not reserved.
IsSubnetRouterAnycast()
bool IsSubnetRouterAnycast (void) const
This method indicates whether or not the Interface Identifier is Subnet-Router Anycast (RFC 4291).
Return values
TRUE If the Interface Identifier is a Subnet-Router Anycast address.
FALSE If the Interface Identifier is not a Subnet-Router Anycast address.
IsReservedSubnetAnycast()
bool IsReservedSubnetAnycast (void) const
This method indicates whether or not the Interface Identifier is Reserved Subnet Anycast (RFC 2526).
Return values
TRUE If the Interface Identifier is a Reserved Subnet Anycast address.
FALSE If the Interface Identifier is not a Reserved Subnet Anycast address.
References ot::Encoding::BigEndian::HostSwap16(), and ot::Encoding::BigEndian::HostSwap32().
GenerateRandom()
void GenerateRandom (void)
This method generates and sets the Interface Identifier to a crypto-secure random byte sequence.
References ot::Random::Crypto::FillBuffer(), NetworkPrefix::kSize, and SuccessOrAssert.
Referenced by Mle::HandleNotifierEvents(), and Mle::Mle().
GetBytes()
const uint8_t* GetBytes (void) const inline
This method gets the Interface Identifier as a pointer to a byte array.
Returns
A pointer to a byte array (of size kSize) containing the Interface Identifier.
SetBytes()
void SetBytes (const uint8_t * aBuffer)
This method sets the Interface Identifier from a given byte array.
Parameters
[in] aBuffer Pointer to an array containing the Interface Identifier. kSize bytes from the buffer are copied to form the Interface Identifier.
References NetworkPrefix::kSize.
SetFromExtAddress()
void SetFromExtAddress (const Mac::ExtAddress & aExtAddress)
This method sets the Interface Identifier from a given IEEE 802.15.4 Extended Address.
Parameters
[in] aExtAddress An Extended Address.
References ExtAddress::CopyTo(), and ExtAddress::ToggleLocal().
Referenced by Lowpan::ComputeIid(), and Mle::UpdateLinkLocalAddress().
ConvertToExtAddress()
void ConvertToExtAddress (Mac::ExtAddress & aExtAddress) const
This method converts the Interface Identifier to an IEEE 802.15.4 Extended Address.
Parameters
[out] aExtAddress A reference to an Extended Address where the converted address is placed.
References ExtAddress::Set(), and ExtAddress::ToggleLocal().
Referenced by AddressResolver::HandleAddressError(), DiscoverScanner::HandleDiscoveryResponse(), Mle::HandleParentResponse(), Mle::HandleUdpReceive(), and Mle::ProcessMessageSecurity().
ConvertToMacAddress()
void ConvertToMacAddress (Mac::Address & aMacAddress) const
This method converts the Interface Identifier to an IEEE 802.15.4 MAC Address.
Parameters
[out] aMacAddress A reference to a MAC Address where the converted address is placed.
References Address::GetExtended(), Address::SetExtended(), and ExtAddress::ToggleLocal().
Referenced by NeighborTable::FindNeighbor(), MeshForwarder::GetMacDestinationAddress(), and MeshForwarder::GetMacSourceAddress().
SetToLocator()
void SetToLocator (uint16_t aLocator)
This method sets the Interface Identifier to Routing/Anycast Locator pattern 0000:00ff:fe00:xxxx with a given locator (RLOC16 or ALOC16) value.
Parameters
[in] aLocator RLOC16 or ALOC16.
References ot::Encoding::BigEndian::HostSwap16(), and ot::Encoding::BigEndian::HostSwap32().
Referenced by Lowpan::ComputeIid(), and Mle::Mle().
IsLocator()
bool IsLocator (void) const
This method indicates whether or not the Interface Identifier matches the locator pattern 0000:00ff:fe00:xxxx.
Return values
TRUE If the IID matches the locator pattern.
FALSE If the IID does not match the locator pattern.
References ot::Encoding::BigEndian::HostSwap16(), and ot::Encoding::BigEndian::HostSwap32().
Referenced by Lowpan::CompressDestinationIid(), Lowpan::CompressSourceIid(), Icmp::HandleEchoRequest(), and Ip6::ProcessReceiveCallback().
IsRoutingLocator()
bool IsRoutingLocator (void) const
This method indicates whether or not the Interface Identifier (IID) matches a Routing Locator (RLOC).
In addition to checking that the IID matches the locator pattern (0000:00ff:fe00:xxxx), this method also checks that the locator value is a valid RLOC16.
Return values
TRUE If the IID matches a RLOC address.
FALSE If the IID does not match a RLOC address.
Referenced by Mle::IsRoutingLocator().
IsAnycastLocator()
bool IsAnycastLocator (void) const
This method indicates whether or not the Interface Identifier (IID) matches an Anycast Locator (ALOC).
In addition to checking that the IID matches the locator pattern (0000:00ff:fe00:xxxx), this method also checks that the locator value is any valid ALOC16 (0xfc00 - 0xfcff).
Return values
TRUE If the IID matches a ALOC address.
FALSE If the IID does not match a ALOC address.
Referenced by CoapBase::FindRelatedRequest(), and Mle::IsAnycastLocator().
IsAnycastServiceLocator()
bool IsAnycastServiceLocator (void) const
This method indicates whether or not the Interface Identifier (IID) matches a Service Anycast Locator (ALOC).
In addition to checking that the IID matches the locator pattern (0000:00ff:fe00:xxxx), this method also checks that the locator value is a valid Service ALOC16 (0xfc10 – 0xfc2f).
Return values
TRUE If the IID matches a ALOC address.
FALSE If the IID does not match a ALOC address.
References ot::Mle::kAloc16ServiceEnd, and ot::Mle::kAloc16ServiceStart.
Referenced by Ip6::ProcessReceiveCallback().
GetLocator()
uint16_t GetLocator (void) const inline
This method gets the Interface Identifier (IID) address locator fields.
This method assumes the IID to match the locator pattern 0000:00ff:fe00:xxxx (does not explicitly check this) and returns the last uint16 portion of the IID.
Returns
The RLOC16 or ALOC16.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by AddressResolver::AddressResolver(), Lowpan::CompressDestinationIid(), Lowpan::CompressSourceIid(), NeighborTable::FindNeighbor(), MeshForwarder::GetMacDestinationAddress(), AddressResolver::HandleAddressError(), and Mle::SetRloc16().
SetLocator()
void SetLocator (uint16_t aLocator) inline
This method sets the Interface Identifier (IID) address locator field.
Unlike SetToLocator(), this method only changes the last 2 bytes of the IID and keeps the rest of the address as before.
Parameters
[in] aLocator RLOC16 or ALOC16.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Mle::CheckReachability(), Mle::GetLocatorAddress(), Mle::SetRloc16(), and MessageInfo::SetSockAddrToRlocPeerAddrTo().
ApplyPrefix()
void ApplyPrefix (const Prefix & aPrefix)
This method applies a prefix to IID.
If the prefix length is longer than 64 bits, the prefix bits after 64 are written into the IID. This method only changes the bits in IID up the prefix length and keeps the rest of the bits in IID as before.
Parameters
[in] aPrefix An IPv6 prefix.
References Address::CopyBits(), Prefix::GetBytes(), Prefix::GetLength(), NetworkPrefix::kLength, and NetworkPrefix::kSize.
Referenced by Lowpan::ComputeIid().
ToString()
InterfaceIdentifier::InfoString ToString (void) const
This method converts an Interface Identifier to a string.
Returns
An InfoString containing the string representation of the Interface Identifier.
References StringWriter::AppendHexBytes(), and NetworkPrefix::kSize.
Friends And Related Function Documentation
Address
friend class Address friend
Field Documentation
kSize
constexpr uint8_t kSize = OT_IP6_IID_SIZE static
Size of an IPv6 Interface Identifier (in bytes).
kInfoStringSize
constexpr uint16_t kInfoStringSize = 17 static
Max chars for the info string (ToString()).
kAloc16Mask
constexpr uint8_t kAloc16Mask = 0xfc static private
kRloc16ReservedBitMask
constexpr uint8_t kRloc16ReservedBitMask = 0x02 static private
The documentation for this class was generated from the following files:
ip6_address.hpp
ip6_address.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale