OpenThread: Arg Class Reference
Arg Class Reference
Utils-parse-cmd-line
#include <parse_cmdline.hpp>
Public Member Functions
void Clear (void)
const char * GetCString (void) const
char * GetCString (void)
uint16_t GetLength (void) const
bool IsEmpty (void) const
bool operator!= (const char *aString) const
bool operator== (const char *aString) const
template<typename Type >
otError ParseAs (Type &aValue) const
template<>
otError ParseAs (uint8_t &aValue) const
template<>
otError ParseAs (uint16_t &aValue) const
template<>
otError ParseAs (uint32_t &aValue) const
template<>
otError ParseAs (uint64_t &aValue) const
template<>
otError ParseAs (bool &aValue) const
template<>
otError ParseAs (int8_t &aValue) const
template<>
otError ParseAs (int16_t &aValue) const
template<>
otError ParseAs (int32_t &aValue) const
otError ParseAsBool (bool &aBool) const
otError ParseAsHexString (uint8_t *aBuffer, uint16_t aSize) const
template<uint16_t kBufferSize>
otError ParseAsHexString (uint8_t(&aBuffer)[kBufferSize])
otError ParseAsHexString (uint16_t &aSize, uint8_t *aBuffer)
otError ParseAsInt16 (int16_t &aInt16) const
otError ParseAsInt32 (int32_t &aInt32) const
otError ParseAsInt8 (int8_t &aInt8) const
otError ParseAsUint16 (uint16_t &aUint16) const
otError ParseAsUint32 (uint32_t &aUint32) const
otError ParseAsUint64 (uint64_t &aUint64) const
otError ParseAsUint8 (uint8_t &aUint8) const
void SetCString (char *aString)
Static Public Member Functions
static void CopyArgsToStringArray (Arg aArgs[], char *aStrings[])
static uint8_t GetArgsLength (Arg aArgs[])
Private Attributes
char * mString
Detailed Description
This class represents a single argument from an argument list.
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the argument.
References Arg::mString.
Referenced by ot::Utils::CmdLineParser::ParseCmd().
IsEmpty()
bool IsEmpty (void) const inline
This method indicates whether or not the argument is empty (i.e., reached the end of argument list).
Return values
TRUE The argument is empty.
FALSE The argument is not empty.
References Arg::GetLength(), and Arg::mString.
Referenced by Arg::CopyArgsToStringArray(), Arg::GetArgsLength(), Arg::GetLength(), Arg::operator==(), Output::OutputFormatV(), Dataset::Process(), and Interpreter::SetUserCommands().
GetLength()
uint16_t GetLength (void) const
This method returns the length (number of characters) in the argument C string.
Returns
The argument string length if argument is not empty, zero otherwise.
References Arg::IsEmpty(), and Arg::mString.
Referenced by Arg::IsEmpty().
GetCString() [1/2]
const char* GetCString (void) const inline
This method gets the argument as a C string.
Returns
A pointer to the argument as a C string, or nullptr if argument is empty.
References Arg::mString.
Referenced by Arg::CopyArgsToStringArray(), Output::OutputFormatV(), and Interpreter::SetUserCommands().
GetCString() [2/2]
char* GetCString (void) inline
This method gets the argument as C string.
Returns
A pointer to the argument as a C string, or nullptr if argument is empty.
References Arg::mString.
SetCString()
void SetCString (char * aString) inline
This method sets the argument with a given C string.
Parameters
[in] aString A pointer to the new C string.
References Arg::mString, and Arg::operator==().
Referenced by ot::Utils::CmdLineParser::ParseCmd().
operator==()
bool operator== (const char * aString) const
This method overload the operator == to evaluate whether the argument is equal to a given C string.
If the argument is empty (IsEmpty() is true) then comparing it using operator == with any C string will return false.
Parameters
[in] aString The C string to compare with (MUST not be nullptr).
Return values
TRUE If the argument is not empty and is equal to aString.
FALSE If the argument is not equal to aString, or if the argument is empty.
References Arg::IsEmpty(), and Arg::mString.
Referenced by Arg::SetCString().
operator!=()
bool operator!= (const char * aString) const inline
This method overload the operator != to evaluate whether the argument is unequal to a given C string.
Parameters
[in] aString The C string to compare with (MUST not be nullptr).
Return values
TRUE If the argument is not equal to aString, or if the argument is empty.
FALSE If the argument is not empty and equal to aString.
ParseAsUint8()
otError ParseAsUint8 (uint8_t & aUint8) const inline
This method parses the argument as a uint8_t value.
The number is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[out] aUint8 A reference to an uint8_t variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number (e.g., value out of range).
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsUint8().
Referenced by Arg::ParseAs(), and Interpreter::SetUserCommands().
ParseAsUint16()
otError ParseAsUint16 (uint16_t & aUint16) const inline
This method parses the argument as a uint16_t value.
The number is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[out] aUint16 A reference to an uint16_t variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number (e.g., value out of range).
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsUint16().
Referenced by Arg::ParseAs(), Dataset::ParseSecurityPolicy(), and Interpreter::SetUserCommands().
ParseAsUint32()
otError ParseAsUint32 (uint32_t & aUint32) const inline
This method parses the argument as a uint32_t value.
The number is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[out] aUint32 A reference to an uint32_t variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number (e.g., value out of range).
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsUint32().
Referenced by Arg::ParseAs(), and Interpreter::SetUserCommands().
ParseAsUint64()
otError ParseAsUint64 (uint64_t & aUint64) const inline
This method parses the argument as a uint64_t value.
The number is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[out] aUint64 A reference to an uint64_t variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number (e.g., value out of range).
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsUint64().
Referenced by Arg::ParseAs(), and Interpreter::SetUserCommands().
ParseAsInt8()
otError ParseAsInt8 (int8_t & aInt8) const inline
This method parses the argument as a int8_t value.
The number is parsed as decimal or hex format (if contains 0x or 0X prefix). The string can start with +/- sign.
Parameters
[out] aInt8 A reference to an int8_t variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number (e.g., value out of range).
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsInt8().
Referenced by Arg::ParseAs().
ParseAsInt16()
otError ParseAsInt16 (int16_t & aInt16) const inline
This method parses the argument as a int16_t value.
The number is parsed as decimal or hex format (if contains 0x or 0X prefix). The string can start with +/- sign.
Parameters
[out] aInt16 A reference to an int16_t variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number (e.g., value out of range).
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsInt16().
Referenced by Arg::ParseAs().
ParseAsInt32()
otError ParseAsInt32 (int32_t & aInt32) const inline
This method parses the argument as a int32_t value.
The number is parsed as decimal or hex format (if contains 0x or 0X prefix). The string can start with +/- sign.
Parameters
[out] aInt32 A reference to an int32_t variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number (e.g., value out of range).
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsInt32().
Referenced by Arg::ParseAs().
ParseAsBool()
otError ParseAsBool (bool & aBool) const inline
This method parses the argument as a bool value.
Zero value is treated as false, non-zero value as true.
Parameters
[out] aBool A reference to a bool variable to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid number.
References Arg::mString, Arg::ParseAs(), and ot::Utils::CmdLineParser::ParseAsBool().
Referenced by Arg::ParseAs().
ParseAs()
otError ParseAs (Type & aValue) const
This template method parses the argument as a specified value type.
Template Parameters
Type The value type.
Parameters
[out] aValue A reference to output the parsed value.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain a valid value.
Referenced by Arg::ParseAs(), and Arg::ParseAsBool().
ParseAsHexString() [1/3]
otError ParseAsHexString (uint8_t * aBuffer, uint16_t aSize) const inline
This method parses the argument as a hex string into a byte array of fixed expected size.
This method returns kErrorNone only when the hex string contains exactly aSize bytes (after parsing). If there are fewer or more bytes in hex string that aSize, the parsed bytes (up to aSize) are copied into the aBuffer and kErrorInvalidArgs is returned.
Parameters
[out] aBuffer A pointer to a buffer to output the parsed byte sequence.
[in] aSize The expected size of byte sequence (number of bytes after parsing).
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid hex bytes and/or not aSize bytes.
References Arg::mString, and ot::Utils::CmdLineParser::ParseAsHexString().
Referenced by Arg::ParseAsHexString().
ParseAsHexString() [2/3]
otError ParseAsHexString (uint8_t(&) aBuffer[kBufferSize]) inline
This template method parses the argument as a hex string into a a given fixed size array.
This method returns kErrorNone only when the hex string contains exactly kBufferSize bytes (after parsing). If there are fewer or more bytes in hex string that kBufferSize, the parsed bytes (up to kBufferSize) are copied into the aBuffer and kErrorInvalidArgs is returned.
Template Parameters
kBufferSize The byte array size (number of bytes).
Parameters
[out] aBuffer A reference to a byte array to output the parsed byte sequence.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument is empty or does not contain valid hex bytes and/or not aSize bytes.
References Arg::ParseAsHexString().
ParseAsHexString() [3/3]
otError ParseAsHexString (uint16_t & aSize, uint8_t * aBuffer) inline
This method parses the argument as a hex string into a byte array.
This method verifies that the parsed hex string bytes fit in aBuffer with its given aSize.
Parameters
[in,out] aSize On entry indicates the number of bytes in aBuffer (max size of aBuffer). On exit provides number of bytes parsed and copied into aBuffer.
[out] aBuffer A pointer to a buffer to output the parsed byte sequence.
Return values
kErrorNone The argument was parsed successfully.
kErrorInvalidArgs The argument does not contain valid format or too many bytes.
References Arg::CopyArgsToStringArray(), Arg::GetArgsLength(), Arg::mString, and ot::Utils::CmdLineParser::ParseAsHexString().
CopyArgsToStringArray()
void CopyArgsToStringArray (Arg aArgs[], char * aStrings[]) static
This static method copies the argument string pointers from an Arg array to a C string array.
Note
this method only copies the string pointer value (i.e., GetString() pointer) from aArgs array to the aStrings array (the content of strings are not copied).
Parameters
[in] aArgs An Arg array.
[out] aStrings An char * array to populate with the argument string pointers. The aString array MUST contain at least same number of entries as in aArgs array.
References Arg::GetCString(), and Arg::IsEmpty().
Referenced by Interpreter::LinkModeToString(), Arg::ParseAsHexString(), and Interpreter::ProcessUserCommands().
GetArgsLength()
uint8_t GetArgsLength (Arg aArgs[]) static
This static method returns the length of argument array, i.e. number of consecutive non-empty arguments.
Parameters
[in] aArgs An Arg array.
Returns
Number of non-empty arguments in the array.
References Arg::IsEmpty().
Referenced by Interpreter::LinkModeToString(), Arg::ParseAsHexString(), and Interpreter::ProcessUserCommands().
Field Documentation
mString
char* mString private
Referenced by Arg::Clear(), Arg::GetCString(), Arg::GetLength(), Arg::IsEmpty(), Arg::operator==(), Arg::ParseAsBool(), Arg::ParseAsHexString(), Arg::ParseAsInt16(), Arg::ParseAsInt32(), Arg::ParseAsInt8(), Arg::ParseAsUint16(), Arg::ParseAsUint32(), Arg::ParseAsUint64(), Arg::ParseAsUint8(), and Arg::SetCString().
The documentation for this class was generated from the following files:
parse_cmdline.hpp
parse_cmdline.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale