OpenThread: Stringify Class Reference
Stringify Class Reference
Core-string
#include <string.hpp>
Data Structures
class Entry
Public Member Functions
Stringify (void)=delete
Static Public Member Functions
template<uint16_t kLength>
static const char * Lookup (uint16_t aKey, const Entry(&aTable)[kLength], const char *aNotFound="unknown")
Static Public Member Functions inherited from BinarySearch
template<typename Key , typename Entry , uint16_t kLength>
static const Entry * Find (const Key &aKey, const Entry(&aTable)[kLength])
template<typename Entry , uint16_t kLength>
static constexpr bool IsSorted (const Entry(&aTable)[kLength])
Detailed Description
This class provides helper methods to convert from a set of uint16_t values (e.g., a non-sequential enum) to string using binary search in a lookup table.
Constructor & Destructor Documentation
Stringify()
Stringify (void) delete
Member Function Documentation
Lookup()
static const char* Lookup (uint16_t aKey, const Entry(&) aTable[kLength], const char * aNotFound = "unknown") inline static
This static method looks up a key in a given sorted table array (using binary search) and return the associated strings with the key.
Note
This method requires the array to be sorted, otherwise its behavior is undefined.
Template Parameters
kLength The array length (number of entries in the array).
Parameters
[in] aKey The key to search for within the table.
[in] aTable A reference to an array of kLength entries.
[in] aNotFound A C string to return if aKey was not found in the table.
Returns
The associated string with aKey in aTable if found, or aNotFound otherwise.
References BinarySearch::Find(), and Stringify::Entry::mString.
Referenced by Message::Clone(), and Ip6::IpProtoToString().
The documentation for this class was generated from the following file:
string.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale