OpenThread: NetworkDataTlv Class Reference
NetworkDataTlv Class Reference
MLE » TLVs
#include <network_diagnostic_tlvs.hpp>
Public Member Functions
uint8_t * GetNetworkData (void)
void Init (void)
bool IsValid (void) const
void SetNetworkData (const uint8_t *aNetworkData)
Public Member Functions inherited from NetworkDiagnosticTlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint8_t mNetworkData [255]
Additional Inherited Members
Public Types inherited from NetworkDiagnosticTlv
enum Type : uint8_t {
kExtMacAddress = OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS, kAddress16 = OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS, kMode = OT_NETWORK_DIAGNOSTIC_TLV_MODE, kTimeout = OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT,
kConnectivity = OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY, kRoute = OT_NETWORK_DIAGNOSTIC_TLV_ROUTE, kLeaderData = OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA, kNetworkData = OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA,
kIp6AddressList = OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST, kMacCounters = OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS, kBatteryLevel = OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL, kSupplyVoltage = OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE,
kChildTable = OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE, kChannelPages = OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES, kTypeList = OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST, kMaxChildTimeout = OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
}
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< NetworkDiagnosticTlv::kNetworkData >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements Network Data TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References NetworkDiagnosticTlv::kNetworkData, Tlv::SetLength(), and NetworkDiagnosticTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
GetNetworkData()
uint8_t* GetNetworkData (void) inline
This method returns a pointer to the Network Data.
Returns
A pointer to the Network Data.
SetNetworkData()
void SetNetworkData (const uint8_t * aNetworkData) inline
This method sets the Network Data.
Parameters
[in] aNetworkData A pointer to the Network Data.
References Tlv::GetLength().
Field Documentation
mNetworkData
uint8_t mNetworkData[255] private
The documentation for this class was generated from the following file:
network_diagnostic_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale