OpenThread: Neighbor::Info Class Reference
Neighbor::Info Class Reference
#include <topology.hpp>
Public Member Functions
void SetFrom (const Neighbor &aNeighbor)
Public Member Functions inherited from Clearable< Info >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otNeighborInfo
uint32_t mAge
Time last heard.
int8_t mAverageRssi
Average RSSI.
otExtAddress mExtAddress
IEEE 802.15.4 Extended Address.
uint16_t mFrameErrorRate
Frame error rate (0xffff->100%). Requires error tracking feature.
bool mFullNetworkData: 1
Full Network Data.
bool mFullThreadDevice: 1
Full Thread Device.
bool mIsChild: 1
Is the neighbor a child.
int8_t mLastRssi
Last observed RSSI.
uint32_t mLinkFrameCounter
Link Frame Counter.
uint8_t mLinkQualityIn
Link Quality In.
uint16_t mMessageErrorRate
(IPv6) msg error rate (0xffff->100%). Requires error tracking feature.
uint32_t mMleFrameCounter
MLE Frame Counter.
uint16_t mRloc16
RLOC16.
bool mRxOnWhenIdle: 1
rx-on-when-idle
Detailed Description
This type represents diagnostic information for a neighboring node.
Member Function Documentation
SetFrom()
void SetFrom (const Neighbor & aNeighbor)
This method sets the Info instance from a given Neighbor.
Parameters
[in] aNeighbor A neighbor.
References LinkQualityInfo::GetAverageRss(), Neighbor::GetExtAddress(), LinkQualityInfo::GetFrameErrorRate(), Neighbor::GetLastHeard(), LinkQualityInfo::GetLastRss(), Neighbor::GetLinkFrameCounters(), Neighbor::GetLinkInfo(), LinkQualityInfo::GetLinkQuality(), LinkQualityInfo::GetMessageErrorRate(), Neighbor::GetMleFrameCounter(), Neighbor::GetNetworkDataType(), TimerMilli::GetNow(), Neighbor::GetRloc16(), Neighbor::IsFullThreadDevice(), Neighbor::IsRxOnWhenIdle(), ot::NetworkData::kFullSet, Neighbor::AddressMatcher::mExtAddress, Neighbor::mMleFrameCounter, Neighbor::mRloc16, and Time::MsecToSec().
Referenced by NeighborTable::FindNeighbor().
The documentation for this class was generated from the following files:
topology.hpp
topology.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale