OpenThread: Netif::MulticastAddress Class Reference
Netif::MulticastAddress Class Reference
#include <netif.hpp>
Public Member Functions
const Address & GetAddress (void) const
Address & GetAddress (void)
const MulticastAddress * GetNext (void) const
MulticastAddress * GetNext (void)
Public Member Functions inherited from LinkedListEntry< MulticastAddress >
const MulticastAddress * GetNext (void) const
MulticastAddress * GetNext (void)
void SetNext (MulticastAddress *aNext)
Public Member Functions inherited from Clearable< MulticastAddress >
void Clear (void)
Private Member Functions
bool Matches (const Address &aAddress) const
Friends
class LinkedList< MulticastAddress >
Additional Inherited Members
Data Fields inherited from otNetifMulticastAddress
otIp6Address mAddress
The IPv6 multicast address.
const struct otNetifMulticastAddress * mNext
A pointer to the next network interface multicast address.
Detailed Description
This class implements an IPv6 network interface multicast address.
Member Function Documentation
GetAddress() [1/2]
const Address& GetAddress (void) const inline
This method returns the multicast address.
Returns
The multicast address.
References ot::AsCoreType(), and otNetifAddress::mAddress.
Referenced by Netif::ExternalMulticastAddress::Iterator::AdvanceFrom(), Mle::ApplyMeshLocalPrefix(), Mle::GetLinkLocalAllThreadNodesAddress(), Mle::GetRealmLocalAllThreadNodesAddress(), and Mle::Mle().
GetAddress() [2/2]
Address& GetAddress (void) inline
This method returns the multicast address.
Returns
The multicast address.
References ot::AsCoreType(), and otNetifAddress::mAddress.
GetNext() [1/2]
const MulticastAddress* GetNext (void) const inline
This method returns the next multicast address subscribed to the interface.
Returns
A pointer to the next multicast address.
References otNetifAddress::mNext.
Referenced by Netif::ExternalMulticastAddress::Iterator::AdvanceFrom(), Netif::SubscribeAllNodesMulticast(), Netif::SubscribeAllRoutersMulticast(), Netif::SubscribeExternalMulticast(), Netif::UnsubscribeAllExternalMulticastAddresses(), Netif::UnsubscribeAllNodesMulticast(), and Netif::UnsubscribeAllRoutersMulticast().
GetNext() [2/2]
MulticastAddress* GetNext (void) inline
This method returns the next multicast address subscribed to the interface.
Returns
A pointer to the next multicast address.
References ot::AsNonConst(), and otNetifAddress::mNext.
Matches()
bool Matches (const Address & aAddress) const inline private
References Netif::UnicastAddress::GetAddress().
Friends And Related Function Documentation
LinkedList< MulticastAddress >
friend class LinkedList< MulticastAddress > friend
The documentation for this class was generated from the following file:
netif.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale