OpenThread: TxtEntry Class Reference
TxtEntry Class Reference
Core-dns
#include <dns_types.hpp>
Data Structures
class Iterator
Public Member Functions
Error AppendTo (Message &aMessage) const
void Init (const char *aKey, const uint8_t *aValue, uint8_t aValueLength)
TxtEntry (void)=default
TxtEntry (const char *aKey, const uint8_t *aValue, uint8_t aValueLength)
Static Public Member Functions
static Error AppendEntries (const TxtEntry *aEntries, uint8_t aNumEntries, Message &aMessage)
static Error AppendEntries (const TxtEntry *aEntries, uint8_t aNumEntries, MutableData< kWithUint16Length > &aData)
Static Public Attributes
static constexpr uint8_t kMaxKeyLength = OT_DNS_TXT_KEY_MAX_LENGTH
static constexpr uint8_t kMinKeyLength = OT_DNS_TXT_KEY_MIN_LENGTH
Private Member Functions
Error AppendTo (Appender &aAppender) const
Static Private Member Functions
static Error AppendEntries (const TxtEntry *aEntries, uint8_t aNumEntries, Appender &aAppender)
Static Private Attributes
static constexpr char kKeyValueSeparator = '='
static constexpr uint8_t kMaxKeyValueEncodedSize = 255
Friends
class TxtRecord
Additional Inherited Members
Data Fields inherited from otDnsTxtEntry
const char * mKey
const uint8_t * mValue
The TXT record value or already encoded TXT-DATA (depending on mKey).
uint16_t mValueLength
Number of bytes in mValue buffer.
Detailed Description
This type represents a TXT record entry representing a key/value pair (RFC 6763 - section 6.3).
Constructor & Destructor Documentation
TxtEntry() [1/2]
TxtEntry (void) default
This is the default constructor for a TxtEntry object.
TxtEntry() [2/2]
TxtEntry (const char * aKey, const uint8_t * aValue, uint8_t aValueLength) inline
This constructor initializes a TxtEntry object.
Parameters
[in] aKey A pointer to the key string.
[in] aValue A pointer to a buffer containing the value.
[in] aValueLength Number of bytes in aValue buffer.
Member Function Documentation
Init()
void Init (const char * aKey, const uint8_t * aValue, uint8_t aValueLength) inline
This method initializes a TxtEntry object.
Parameters
[in] aKey A pointer to the key string.
[in] aValue A pointer to a buffer containing the value.
[in] aValueLength Number of bytes in aValue buffer.
AppendTo() [1/2]
Error AppendTo (Message & aMessage) const
This method encodes and appends the TxtEntry to a message.
Parameters
[in] aMessage The message to append to.
Return values
kErrorNone Entry was appended successfully to aMessage.
kErrorInvalidArgs The TxTEntry info is not valid.
kErrorNoBufs Insufficient available buffers to grow the message.
AppendEntries() [1/3]
Error AppendEntries (const TxtEntry * aEntries, uint8_t aNumEntries, Message & aMessage) static
This static method appends an array of TxtEntry items to a message.
Parameters
[in] aEntries A pointer to array of TxtEntry items.
[in] aNumEntries The number of entries in aEntries array.
[in] aMessage The message to append to.
Return values
kErrorNone Entries appended successfully to aMessage.
kErrorInvalidArgs The TxTEntry info is not valid.
kErrorNoBufs Insufficient available buffers to grow the message.
AppendEntries() [2/3]
Error AppendEntries (const TxtEntry * aEntries, uint8_t aNumEntries, MutableData< kWithUint16Length > & aData) static
This static method appends an array of TxtEntry items to a MutableData buffer.
Parameters
[in] aEntries A pointer to array of TxtEntry items.
[in] aNumEntries The number of entries in aEntries array.
[in] aData The MutableData to append in.
Return values
kErrorNone Entries appended successfully .
kErrorInvalidArgs The TxTEntry info is not valid.
kErrorNoBufs Insufficient available buffers.
References MutableData< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), and SuccessOrExit.
AppendTo() [2/2]
Error AppendTo (Appender & aAppender) const private
References Appender::Append(), Appender::AppendBytes(), ExitNow, ot::kErrorInvalidArgs, ot::kErrorNone, ot::StringLength(), SuccessOrExit, and VerifyOrExit.
AppendEntries() [3/3]
Error AppendEntries (const TxtEntry * aEntries, uint8_t aNumEntries, Appender & aAppender) static private
References Appender::Append(), Appender::GetAppendedLength(), ot::kErrorNone, and SuccessOrExit.
Friends And Related Function Documentation
TxtRecord
friend class TxtRecord friend
Field Documentation
kMinKeyLength
constexpr uint8_t kMinKeyLength = OT_DNS_TXT_KEY_MIN_LENGTH static
Minimum length of key string (RFC 6763 - section 6.4).
kMaxKeyLength
constexpr uint8_t kMaxKeyLength = OT_DNS_TXT_KEY_MAX_LENGTH static
Recommended max length of key string (RFC 6763 - section 6.4).
Referenced by TxtEntry::Iterator::GetNextEntry().
kMaxKeyValueEncodedSize
constexpr uint8_t kMaxKeyValueEncodedSize = 255 static private
kKeyValueSeparator
constexpr char kKeyValueSeparator = '=' static private
The documentation for this class was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale