OpenThread: UpdateHeader Class Reference
UpdateHeader Class Reference
Core-dns
#include <dns_types.hpp>
Public Member Functions
uint16_t GetPrerequisiteRecordCount (void) const
uint16_t GetUpdateRecordCount (void) const
uint16_t GetZoneRecordCount (void) const
void SetPrerequisiteRecordCount (uint16_t aCount)
void SetUpdateRecordCount (uint16_t aCount)
void SetZoneRecordCount (uint16_t aCount)
UpdateHeader (void)
Public Member Functions inherited from Header
void ClearAuthoritativeAnswerFlag (void)
void ClearRecursionAvailableFlag (void)
void ClearRecursionDesiredFlag (void)
void ClearTruncationFlag (void)
uint16_t GetAdditionalRecordCount (void) const
uint16_t GetAnswerCount (void) const
uint16_t GetAuthorityRecordCount (void) const
uint16_t GetMessageId (void) const
QueryType GetQueryType (void) const
uint16_t GetQuestionCount (void) const
Response GetResponseCode (void) const
Type GetType (void) const
Header (void)
bool IsAuthoritativeAnswerFlagSet (void) const
bool IsRecursionAvailableFlagSet (void) const
bool IsRecursionDesiredFlagSet (void) const
bool IsTruncationFlagSet (void) const
void SetAdditionalRecordCount (uint16_t aCount)
void SetAnswerCount (uint16_t aCount)
void SetAuthoritativeAnswerFlag (void)
void SetAuthorityRecordCount (uint16_t aCount)
void SetMessageId (uint16_t aMessageId)
void SetQueryType (QueryType aType)
void SetQuestionCount (uint16_t aCount)
Error SetRandomMessageId (void)
void SetRecursionAvailableFlag (void)
void SetRecursionDesiredFlag (void)
void SetResponseCode (Response aResponse)
void SetTruncationFlag (void)
void SetType (Type aType)
Public Member Functions inherited from Clearable< Header >
void Clear (void)
Additional Inherited Members
Public Types inherited from Header
enum QueryType : uint8_t {
kQueryTypeStandard = 0, kQueryTypeInverse = 1, kQueryTypeStatus = 2, kQueryTypeNotify = 4,
kQueryTypeUpdate = 5, kQueryTypeDso = 6
}
enum Response : uint8_t {
kResponseSuccess = 0, kResponseFormatError = 1, kResponseServerFailure = 2, kResponseNameError = 3,
kResponseNotImplemented = 4, kResponseRefused = 5, kResponseNameExists = 6, kResponseRecordExists = 7,
kResponseRecordNotExists = 8, kResponseNotAuth = 9, kResponseNotZone = 10, kDsoTypeNotImplemented = 11,
kResponseBadName = 20, kResponseBadAlg = 21, kResponseBadTruncation = 22
}
enum Type : uint8_t { kTypeQuery = 0, kTypeResponse = 1 }
Static Public Member Functions inherited from Header
static Error ResponseCodeToError (Response aResponse)
Detailed Description
This class implements DNS Update message header generation and parsing.
The DNS header specifies record counts for its four sections: Question, Answer, Authority, and Additional. A DNS Update header uses the same fields, and the same section formats, but the naming and use of these sections differs: DNS Update header uses Zone, Prerequisite, Update, Additional Data sections.
Constructor & Destructor Documentation
UpdateHeader()
UpdateHeader (void) inline
Default constructor for DNS Update message header.
References Header::kQueryTypeUpdate, and Header::SetQueryType().
Member Function Documentation
GetZoneRecordCount()
uint16_t GetZoneRecordCount (void) const inline
This method returns the number of records in Zone section.
Returns
The number of records in Zone section.
References Header::GetQuestionCount().
SetZoneRecordCount()
void SetZoneRecordCount (uint16_t aCount) inline
This method sets the number of records in Zone section.
Parameters
[in] aCount The number of records in Zone section.
References Header::SetQuestionCount().
GetPrerequisiteRecordCount()
uint16_t GetPrerequisiteRecordCount (void) const inline
This method returns the number of records in Prerequisite section.
Returns
The number of records in Prerequisite section.
References Header::GetAnswerCount().
SetPrerequisiteRecordCount()
void SetPrerequisiteRecordCount (uint16_t aCount) inline
This method sets the number of records in Prerequisite section.
Parameters
[in] aCount The number of records in Prerequisite section.
References Header::SetAnswerCount().
GetUpdateRecordCount()
uint16_t GetUpdateRecordCount (void) const inline
This method returns the number of records in Update section.
Returns
The number of records in Update section.
References Header::GetAuthorityRecordCount().
SetUpdateRecordCount()
void SetUpdateRecordCount (uint16_t aCount) inline
This method sets the number of records in Update section.
Parameters
[in] aCount The number of records in Update section.
References ot::Dns::OT_TOOL_PACKED_END, and Header::SetAuthorityRecordCount().
The documentation for this class was generated from the following file:
dns_types.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale