OpenThread: ResourceRecord Class Reference
ResourceRecord Class Reference
Core-dns
#include <dns_types.hpp>
Public Member Functions
uint16_t GetClass (void) const
uint16_t GetLength (void) const
uint32_t GetSize (void) const
uint32_t GetTtl (void) const
uint16_t GetType (void) const
void Init (uint16_t aType, uint16_t aClass=kClassInternet)
bool Matches (uint16_t aType, uint16_t aClass=kClassInternet)
void SetClass (uint16_t aClass)
void SetLength (uint16_t aLength)
void SetTtl (uint32_t aTtl)
void SetType (uint16_t aType)
Static Public Member Functions
static Error FindRecord (const Message &aMessage, uint16_t &aOffset, uint16_t &aNumRecords, const Name &aName)
template<class RecordType >
static Error FindRecord (const Message &aMessage, uint16_t &aOffset, uint16_t aNumRecords, uint16_t aIndex, const Name &aName, RecordType &aRecord)
static Error ParseRecords (const Message &aMessage, uint16_t &aOffset, uint16_t aNumRecords)
template<class RecordType >
static Error ReadRecord (const Message &aMessage, uint16_t &aOffset, RecordType &aRecord)
Static Public Attributes
static constexpr uint16_t kClassAny = 255
Class code Any (ANY).
static constexpr uint16_t kClassInternet = 1
Class code Internet (IN).
static constexpr uint16_t kClassNone = 254
Class code None (NONE) - RFC 2136.
static constexpr uint16_t kTypeA = 1
Address record (IPv4).
static constexpr uint16_t kTypeAaaa = 28
IPv6 address record.
static constexpr uint16_t kTypeAny = 255
ANY record.
static constexpr uint16_t kTypeCname = 5
CNAME record.
static constexpr uint16_t kTypeKey = 25
KEY record.
static constexpr uint16_t kTypeOpt = 41
Option record.
static constexpr uint16_t kTypePtr = 12
PTR record.
static constexpr uint16_t kTypeSig = 24
SIG record.
static constexpr uint16_t kTypeSoa = 6
Start of (zone of) authority.
static constexpr uint16_t kTypeSrv = 33
SRV locator record.
static constexpr uint16_t kTypeTxt = 16
TXT record.
static constexpr uint16_t kTypeZero = 0
Zero as special indicator for the SIG RR (SIG(0) from RFC 2931).
Protected Member Functions
Error ReadName (const Message &aMessage, uint16_t &aOffset, uint16_t aStartOffset, char *aNameBuffer, uint16_t aNameBufferSize, bool aSkipRecord) const
Error SkipRecord (const Message &aMessage, uint16_t &aOffset) const
Private Member Functions
Error CheckRecord (const Message &aMessage, uint16_t aOffset) const
Error ReadFrom (const Message &aMessage, uint16_t aOffset)
Static Private Member Functions
static Error FindRecord (const Message &aMessage, uint16_t &aOffset, uint16_t aNumRecords, uint16_t aIndex, const Name &aName, uint16_t aType, ResourceRecord &aRecord, uint16_t aMinRecordSize)
static Error ReadRecord (const Message &aMessage, uint16_t &aOffset, uint16_t aType, ResourceRecord &aRecord, uint16_t aMinRecordSize)
Private Attributes
uint16_t mClass
uint16_t mLength
uint32_t mTtl
uint16_t mType
Static Private Attributes
static constexpr uint16_t kType = kTypeAny
Friends
class OptRecord
Detailed Description
This class implements Resource Record (RR) body format.
Member Function Documentation
Init()
void Init (uint16_t aType, uint16_t aClass = kClassInternet) inline
This method initializes the resource record by setting its type and class.
This method only sets the type and class fields. Other fields (TTL and length) remain unchanged/uninitialized.
Parameters
[in] aType The type of the resource record.
[in] aClass The class of the resource record (default is kClassInternet).
References Header::SetType().
Referenced by ARecord::Init(), CnameRecord::Init(), PtrRecord::Init(), TxtRecord::Init(), AaaaRecord::Init(), SrvRecord::Init(), KeyRecord::Init(), and SigRecord::Init().
Matches()
bool Matches (uint16_t aType, uint16_t aClass = kClassInternet) inline
This method indicates whether the resources records matches a given type and class code.
Parameters
[in] aType The resource record type to compare with.
[in] aClass The resource record class code to compare with (default is kClassInternet).
Returns
TRUE if the resources records matches aType and aClass, FALSE otherwise.
References ot::Encoding::BigEndian::HostSwap16().
GetType()
uint16_t GetType (void) const inline
This method returns the type of the resource record.
Returns
The type of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by ResourceRecord::ReadRecord().
SetType()
void SetType (uint16_t aType) inline
This method sets the type of the resource record.
Parameters
[in] aType The type of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
GetClass()
uint16_t GetClass (void) const inline
This method returns the class of the resource record.
Returns
The class of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
SetClass()
void SetClass (uint16_t aClass) inline
This method sets the class of the resource record.
Parameters
[in] aClass The class of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
GetTtl()
uint32_t GetTtl (void) const inline
This method returns the time to live field of the resource record.
Returns
The time to live field of the resource record.
References ot::Encoding::BigEndian::HostSwap32().
SetTtl()
void SetTtl (uint32_t aTtl) inline
This method sets the time to live field of the resource record.
Parameters
[in] aTtl The time to live field of the resource record.
References ot::Encoding::BigEndian::HostSwap32().
GetLength()
uint16_t GetLength (void) const inline
This method returns the length of the resource record data.
Returns
The length of the resource record data.
References ot::Encoding::BigEndian::HostSwap16().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the length of the resource record data.
Parameters
[in] aLength The length of the resource record data.
References ot::Encoding::BigEndian::HostSwap16().
GetSize()
uint32_t GetSize (void) const inline
This method returns the size of (number of bytes) in resource record and its data RDATA section (excluding the name field).
Returns
Size (number of bytes) of resource record and its data section (excluding the name field)
Referenced by ResourceRecord::FindRecord(), ResourceRecord::ParseRecords(), and ResourceRecord::ReadRecord().
ParseRecords()
Error ParseRecords (const Message & aMessage, uint16_t & aOffset, uint16_t aNumRecords) static
This static method parses and skips over a given number of resource records in a message from a given offset.
Parameters
[in] aMessage The message from which to parse/read the resource records. aMessage.GetOffset() MUST point to the start of DNS header.
[in,out] aOffset On input the offset in aMessage pointing to the start of the first record. On exit (when parsed successfully), aOffset is updated to point to the byte after the last parsed record.
[in] aNumRecords Number of resource records to parse.
Return values
kErrorNone Parsed records successfully. aOffset is updated.
kErrorParse Could not parse the records from aMessage (e.g., ran out of bytes in aMessage).
References ResourceRecord::GetSize(), ot::kErrorNone, Name::ParseName(), ResourceRecord::ReadFrom(), and SuccessOrExit.
FindRecord() [1/3]
Error FindRecord (const Message & aMessage, uint16_t & aOffset, uint16_t & aNumRecords, const Name & aName) static
This static method searches in a given message to find the first resource record matching a given record name.
Parameters
[in] aMessage The message in which to search for a matching resource record. aMessage.GetOffset() MUST point to the start of DNS header.
[in,out] aOffset On input, the offset in aMessage pointing to the start of the first record. On exit, if a matching record is found, aOffset is updated to point to the byte after the record name. If a matching record could not be found, aOffset is updated to point to the byte after the last record that was checked.
[in,out] aNumRecords On input, the maximum number of records to check (starting from aOffset). On exit and if a matching record is found, aNumRecords is updated to give the number of remaining records after aOffset (excluding the matching record).
[in] aName The record name to match against.
Return values
kErrorNone A matching record was found. aOffset, aNumRecords are updated.
kErrorNotFound A matching record could not be found. aOffset and aNumRecords are updated.
kErrorParse Could not parse records from aMessage (e.g., ran out of bytes in aMessage).
References Name::CompareName(), ExitNow, ResourceRecord::GetSize(), ot::kErrorNone, ot::kErrorNotFound, ResourceRecord::ReadFrom(), SuccessOrExit, and VerifyOrExit.
FindRecord() [2/3]
static Error FindRecord (const Message & aMessage, uint16_t & aOffset, uint16_t aNumRecords, uint16_t aIndex, const Name & aName, RecordType & aRecord) inline static
This template static method searches in a message to find the i-th occurrence of resource records of specific type with a given record name and if found, reads the record from the message.
This method searches in aMessage starting from aOffset up to maximum of aNumRecords, for the (aIndex+1)th occurrence of a resource record of RecordType with record name aName.
On success (i.e., when a matching record is found and read from the message), aOffset is updated to point to after the last byte read from the message and copied into aRecord. This allows the caller to read any remaining fields in the record data.
Template Parameters
RecordType The resource record type (i.e., a sub-class of ResourceRecord).
Parameters
[in] aMessage The message to search within for matching resource records. aMessage.GetOffset() MUST point to the start of DNS header.
[in,out] aOffset On input, the offset in aMessage pointing to the start of the first record. On exit and only if a matching record is found, aOffset is updated to point to the last read byte in the record (allowing caller to read any remaining fields in the record data from the message).
[in] aNumRecords The maximum number of records to check (starting from aOffset).
[in] aIndex The matching record index to find. aIndex value of zero returns the first matching record.
[in] aName The record name to match against.
[in] aRecord A reference to a record object to read a matching record into. If a matching record is found, sizeof(RecordType) bytes from aMessage are read and copied into aRecord.
Return values
kErrorNone A matching record was found. aOffset is updated.
kErrorNotFound A matching record could not be found.
kErrorParse Could not parse records from aMessage (e.g., ran out of bytes in aMessage).
ReadRecord() [1/2]
static Error ReadRecord (const Message & aMessage, uint16_t & aOffset, RecordType & aRecord) inline static
This template static method tries to read a resource record of a given type from a message. If the record type does not matches the type, it skips over the record.
This method requires the record name to be already parsed/read from the message. On input, aOffset should point to the start of the ResourceRecord fields (type, class, TTL, data length) in aMessage.
This method verifies that the record is well-formed in the message. It then reads the record type and compares it with RecordType::kType and ensures that the record size is at least sizeof(RecordType). If it all matches, the record is read into aRecord.
On success (i.e., when a matching record is read from the message), the aOffset is updated to point to after the last byte read from the message and copied into aRecord and not necessarily the end of the record. Depending on the RecordType format, there may still be more data bytes left in the record to be read. For example, when reading a SRV record using SrvRecord type, aOffset would point to after the last field in SrvRecord which is the start of "target host domain name" field.
Template Parameters
RecordType The resource record type (i.e., a sub-class of ResourceRecord).
Parameters
[in] aMessage The message from which to read the record.
[in,out] aOffset On input, the offset in aMessage pointing to the byte after the record name. On exit, if a matching record is read, aOffset is updated to point to the last read byte in the record. If a matching record could not be read, aOffset is updated to point to the byte after the entire record (skipping over the record).
[out] aRecord A reference to a record to read a matching record into. If a matching record is found, sizeof(RecordType) bytes from aMessage are read and copied into aRecord.
Return values
kErrorNone A matching record was read successfully. aOffset, and aRecord are updated.
kErrorNotFound A matching record could not be found. aOffset is updated.
kErrorParse Could not parse records from aMessage (e.g., ran out of bytes in aMessage).
ReadName()
Error ReadName (const Message & aMessage, uint16_t & aOffset, uint16_t aStartOffset, char * aNameBuffer, uint16_t aNameBufferSize, bool aSkipRecord) const protected
References ot::kErrorNone, ot::kErrorParse, Name::ReadName(), SuccessOrExit, and VerifyOrExit.
Referenced by CnameRecord::ReadCanonicalName(), PtrRecord::ReadPtrName(), SigRecord::ReadSignerName(), and SrvRecord::ReadTargetHostName().
SkipRecord()
Error SkipRecord (const Message & aMessage, uint16_t & aOffset) const protected
References SuccessOrExit.
FindRecord() [3/3]
Error FindRecord (const Message & aMessage, uint16_t & aOffset, uint16_t aNumRecords, uint16_t aIndex, const Name & aName, uint16_t aType, ResourceRecord & aRecord, uint16_t aMinRecordSize) static private
References ExitNow, ResourceRecord::GetSize(), ot::kErrorNotFound, and SuccessOrExit.
ReadRecord() [2/2]
Error ReadRecord (const Message & aMessage, uint16_t & aOffset, uint16_t aType, ResourceRecord & aRecord, uint16_t aMinRecordSize) static private
References ResourceRecord::GetSize(), ResourceRecord::GetType(), IgnoreError(), ot::kErrorNotFound, Message::Read(), ResourceRecord::ReadFrom(), and SuccessOrExit.
CheckRecord()
Error CheckRecord (const Message & aMessage, uint16_t aOffset) const private
References Message::GetLength(), ot::kErrorNone, and ot::kErrorParse.
ReadFrom()
Error ReadFrom (const Message & aMessage, uint16_t aOffset) private
References Message::Read(), and SuccessOrExit.
Referenced by ResourceRecord::FindRecord(), ResourceRecord::ParseRecords(), and ResourceRecord::ReadRecord().
Friends And Related Function Documentation
OptRecord
friend class OptRecord friend
Field Documentation
kTypeZero
constexpr uint16_t kTypeZero = 0 static
Zero as special indicator for the SIG RR (SIG(0) from RFC 2931).
kTypeA
constexpr uint16_t kTypeA = 1 static
Address record (IPv4).
kTypeSoa
constexpr uint16_t kTypeSoa = 6 static
Start of (zone of) authority.
kTypeCname
constexpr uint16_t kTypeCname = 5 static
CNAME record.
kTypePtr
constexpr uint16_t kTypePtr = 12 static
PTR record.
kTypeTxt
constexpr uint16_t kTypeTxt = 16 static
TXT record.
kTypeSig
constexpr uint16_t kTypeSig = 24 static
SIG record.
Referenced by SigRecord::IsValid().
kTypeKey
constexpr uint16_t kTypeKey = 25 static
KEY record.
Referenced by KeyRecord::IsValid().
kTypeAaaa
constexpr uint16_t kTypeAaaa = 28 static
IPv6 address record.
Referenced by AaaaRecord::IsValid().
kTypeSrv
constexpr uint16_t kTypeSrv = 33 static
SRV locator record.
kTypeOpt
constexpr uint16_t kTypeOpt = 41 static
Option record.
kTypeAny
constexpr uint16_t kTypeAny = 255 static
ANY record.
kClassInternet
constexpr uint16_t kClassInternet = 1 static
Class code Internet (IN).
kClassNone
constexpr uint16_t kClassNone = 254 static
Class code None (NONE) - RFC 2136.
kClassAny
constexpr uint16_t kClassAny = 255 static
Class code Any (ANY).
kType
constexpr uint16_t kType = kTypeAny static private
mType
uint16_t mType private
mClass
uint16_t mClass private
mTtl
uint32_t mTtl private
mLength
uint16_t mLength private
The documentation for this class was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale