OpenThread: Message::Settings Class Reference
Message::Settings Class Reference
#include <message.hpp>
Public Member Functions
Priority GetPriority (void) const
bool IsLinkSecurityEnabled (void) const
Settings (LinkSecurityMode aSecurityMode, Priority aPriority)
Settings (Priority aPriority)
Static Public Member Functions
static const Settings & From (const otMessageSettings *aSettings)
static const Settings & GetDefault (void)
Static Private Attributes
static const otMessageSettings kDefault
Additional Inherited Members
Data Fields inherited from otMessageSettings
bool mLinkSecurityEnabled
TRUE if the message should be secured at Layer 2.
uint8_t mPriority
Priority level (MUST be a OT_MESSAGE_PRIORITY_* from otMessagePriority).
Detailed Description
This class represents settings used for creating a new message.
Constructor & Destructor Documentation
Settings() [1/2]
Settings (LinkSecurityMode aSecurityMode, Priority aPriority)
This constructor initializes the Settings object.
Parameters
[in] aSecurityMode A link security mode.
[in] aPriority A message priority.
Settings() [2/2]
Settings (Priority aPriority) inline explicit
This constructor initializes the Settings with a given message priority and link security enabled.
Parameters
[in] aPriority A message priority.
Member Function Documentation
GetPriority()
Priority GetPriority (void) const inline
This method gets the message priority.
Returns
The message priority.
IsLinkSecurityEnabled()
bool IsLinkSecurityEnabled (void) const inline
This method indicates whether the link security should be enabled.
Returns
TRUE if link security should be enabled, FALSE otherwise.
From()
static const Settings& From (const otMessageSettings * aSettings) static
This static method converts a pointer to an otMessageSettings to a Settings.
Parameters
[in] aSettings A pointer to otMessageSettings to covert from. If it is nullptr, then the default settings GetDefault() will be used.
Returns
A reference to the converted Settings or the default if aSettings is nullptr.
Referenced by otIp6NewMessage(), and otUdpNewMessage().
GetDefault()
static const Settings& GetDefault (void) inline static
This static method returns the default settings with link security enabled and kPriorityNormal priority.
Returns
A reference to the default settings (link security enable and kPriorityNormal priority).
Referenced by Udp::IsOpen().
Field Documentation
kDefault
const otMessageSettings kDefault static private
The documentation for this class was generated from the following file:
message.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale