OpenThread: NetworkDataTlv Class Reference
NetworkDataTlv Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Types
enum Type : uint8_t {
kTypeHasRoute = 0, kTypePrefix = 1, kTypeBorderRouter = 2, kTypeContext = 3,
kTypeCommissioningData = 4, kTypeService = 5, kTypeServer = 6
}
Public Member Functions
void ClearStable (void)
void DecreaseLength (uint8_t aDecrement)
uint8_t GetLength (void) const
NetworkDataTlv * GetNext (void)
const NetworkDataTlv * GetNext (void) const
uint8_t GetSize (void) const
Type GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
void IncreaseLength (uint8_t aIncrement)
void Init (void)
bool IsStable (void) const
void SetLength (uint8_t aLength)
void SetStable (void)
void SetType (Type aType)
Static Public Member Functions
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
static NetworkDataTlv * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, Type aType, bool aStable)
static const NetworkDataTlv * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, Type aType, bool aStable)
template<typename TlvType >
static TlvType * Find (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, bool aStable)
template<typename TlvType >
static const TlvType * Find (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, bool aStable)
Private Attributes
uint8_t mLength
uint8_t mType
Static Private Attributes
static constexpr uint8_t kStableMask = 1 << 0
static constexpr uint8_t kTypeMask = 0x7f << kTypeOffset
static constexpr uint8_t kTypeOffset = 1
Detailed Description
This class implements Thread Network Data TLV generation and parsing.
Member Enumeration Documentation
Type
enum Type : uint8_t
Thread Network Data Type values.
Enumerator
kTypeHasRoute
Has Route TLV.
kTypePrefix
Prefix TLV.
kTypeBorderRouter
Border Router TLV.
kTypeContext
Context TLV.
kTypeCommissioningData
Commissioning Dataset TLV.
kTypeService
Service TLV.
kTypeServer
Server TLV.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References NetworkDataTlv::mLength, and NetworkDataTlv::mType.
Referenced by HasRouteTlv::Init(), PrefixTlv::Init(), BorderRouterTlv::Init(), ContextTlv::Init(), CommissioningDataTlv::Init(), ServiceTlv::Init(), and ServerTlv::Init().
GetType()
Type GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References NetworkDataTlv::kTypeOffset, and NetworkDataTlv::mType.
Referenced by NetworkDataTlv::Find(), MutableNetworkData::RemoveTemporaryData(), and MutableNetworkData::RemoveTemporaryDataIn().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References NetworkDataTlv::kTypeMask, NetworkDataTlv::kTypeOffset, and NetworkDataTlv::mType.
Referenced by HasRouteTlv::Init(), PrefixTlv::Init(), BorderRouterTlv::Init(), ContextTlv::Init(), CommissioningDataTlv::Init(), ServiceTlv::Init(), and ServerTlv::Init().
GetLength()
uint8_t GetLength (void) const inline
This method returns the Length value.
Returns
The Length value.
References NetworkDataTlv::mLength.
Referenced by LeaderBase::GetCommissioningDataSubTlv(), HasRouteTlv::GetLastEntry(), BorderRouterTlv::GetLastEntry(), HasRouteTlv::GetNumEntries(), BorderRouterTlv::GetNumEntries(), ServerTlv::GetServerDataLength(), PrefixTlv::GetSubTlvsLength(), ServiceTlv::GetSubTlvsLength(), PrefixTlv::IsValid(), ServiceTlv::IsValid(), ServerTlv::IsValid(), and ServerTlv::operator==().
SetLength()
void SetLength (uint8_t aLength) inline
This method sets the Length value.
Parameters
[in] aLength The Length value.
References NetworkDataTlv::mLength.
Referenced by HasRouteTlv::Init(), BorderRouterTlv::Init(), ContextTlv::Init(), CommissioningDataTlv::Init(), ServiceTlv::Init(), ServerTlv::Init(), LeaderBase::SetCommissioningData(), PrefixTlv::SetSubTlvsLength(), and ServiceTlv::SetSubTlvsLength().
IncreaseLength()
void IncreaseLength (uint8_t aIncrement) inline
This methods increases the Length value by a given amount.
Parameters
[in] aIncrement The increment amount to increase the length.
References NetworkDataTlv::mLength.
DecreaseLength()
void DecreaseLength (uint8_t aDecrement) inline
This methods decreases the Length value by a given amount.
Parameters
[in] aDecrement The decrement amount to decrease the length.
References NetworkDataTlv::mLength.
GetSize()
uint8_t GetSize (void) const inline
This method returns the TLV's total size (number of bytes) including Type, Length, and Value fields.
Returns
The total size include Type, Length, and Value fields.
References NetworkDataTlv::mLength.
Referenced by MutableNetworkData::RemoveTemporaryDataIn(), and MutableNetworkData::RemoveTlv().
GetValue() [1/2]
uint8_t* GetValue (void) inline
This method returns a pointer to the Value.
Returns
A pointer to the value.
Referenced by LeaderBase::GetCommissioningDataSubTlv(), HasRouteTlv::GetEntry(), BorderRouterTlv::GetEntry(), HasRouteTlv::GetFirstEntry(), BorderRouterTlv::GetFirstEntry(), HasRouteTlv::GetLastEntry(), BorderRouterTlv::GetLastEntry(), ServiceTlv::GetSubTlvs(), ServerTlv::operator==(), and LeaderBase::SetCommissioningData().
GetValue() [2/2]
const uint8_t* GetValue (void) const inline
This method returns a pointer to the Value.
Returns
A pointer to the value.
GetNext() [1/2]
NetworkDataTlv* GetNext (void) inline
This method returns a pointer to the next Network Data TLV.
Returns
A pointer to the next Network Data TLV.
References NetworkDataTlv::mLength.
Referenced by NetworkDataTlv::Find(), LeaderBase::FindNextMatchingPrefix(), NetworkData::FindNextService(), TlvIterator::Iterate(), Manager::IterateToNextServer(), MutableNetworkData::RemoveTemporaryData(), and MutableNetworkData::RemoveTemporaryDataIn().
GetNext() [2/2]
const NetworkDataTlv* GetNext (void) const inline
This method returns a pointer to the next Network Data TLV.
Returns
A pointer to the next Network Data TLV.
References NetworkDataTlv::mLength.
ClearStable()
void ClearStable (void) inline
This method clears the Stable bit.
References NetworkDataTlv::kStableMask, and NetworkDataTlv::mType.
IsStable()
bool IsStable (void) const inline
This method indicates whether or not the Stable bit is set.
Return values
TRUE If the Stable bit is set.
FALSE If the Stable bit is not set.
References NetworkDataTlv::kStableMask, and NetworkDataTlv::mType.
Referenced by NetworkDataTlv::Find(), MutableNetworkData::RemoveTemporaryData(), MutableNetworkData::RemoveTemporaryDataIn(), OnMeshPrefixConfig::SetFrom(), ExternalRouteConfig::SetFrom(), and ServiceConfig::ServerConfig::SetFrom().
SetStable()
void SetStable (void) inline
This method sets the Stable bit.
References NetworkDataTlv::kStableMask, and NetworkDataTlv::mType.
Find() [1/8]
static NetworkDataTlv* Find (NetworkDataTlv * aStart, NetworkDataTlv * aEnd, Type aType) inline static
This static method searches in a given sequence of TLVs to find the first TLV with a given type.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ot::AsConst(), and ot::AsNonConst().
Referenced by NetworkDataTlv::Find(), and TlvIterator::Iterate().
Find() [2/8]
const NetworkDataTlv * Find (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd, Type aType) static
This static method searches in a given sequence of TLVs to find the first TLV with a given type.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ExitNow, NetworkDataTlv::GetNext(), and NetworkDataTlv::GetType().
Find() [3/8]
static TlvType* Find (NetworkDataTlv * aStart, NetworkDataTlv * aEnd) inline static
This template static method searches in a given sequence of TLVs to find the first TLV with a given type.
Template Parameters
TlvType The TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
Returns
A pointer to the TLV if found, or nullptr if not found.
References NetworkDataTlv::Find().
Find() [4/8]
static const TlvType* Find (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd) inline static
This template static method searches in a given sequence of TLVs to find the first TLV with a given type.
Template Parameters
TlvType The TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
Returns
A pointer to the TLV if found, or nullptr if not found.
References NetworkDataTlv::Find().
Find() [5/8]
static NetworkDataTlv* Find (NetworkDataTlv * aStart, NetworkDataTlv * aEnd, Type aType, bool aStable) inline static
This static method searches in a given sequence of TLVs to find the first TLV with a given TLV type and stable flag.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ot::AsConst(), ot::AsNonConst(), and NetworkDataTlv::Find().
Find() [6/8]
const NetworkDataTlv * Find (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd, Type aType, bool aStable) static
This static method searches in a given sequence of TLVs to find the first TLV with a given TLV type and stable flag.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
References ExitNow, NetworkDataTlv::Find(), PrefixTlv::FindSubTlv(), NetworkDataTlv::GetNext(), NetworkDataTlv::GetType(), and NetworkDataTlv::IsStable().
Find() [7/8]
static TlvType* Find (NetworkDataTlv * aStart, NetworkDataTlv * aEnd, bool aStable) inline static
This template static method searches in a given sequence of TLVs to find the first TLV with a given TLV type and stable flag.
Template Parameters
TlvType The TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
References NetworkDataTlv::Find().
Find() [8/8]
static const TlvType* Find (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd, bool aStable) inline static
This template static method searches in a given sequence of TLVs to find the first TLV with a given TLV type and stable flag.
Template Parameters
TlvType The TLV type to search for (MUST be a sub-class of NetworkDataTlv).
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or nullptr if not found.
References NetworkDataTlv::Find().
Field Documentation
kTypeOffset
constexpr uint8_t kTypeOffset = 1 static private
Referenced by NetworkDataTlv::GetType(), and NetworkDataTlv::SetType().
kTypeMask
constexpr uint8_t kTypeMask = 0x7f << kTypeOffset static private
Referenced by NetworkDataTlv::SetType().
kStableMask
constexpr uint8_t kStableMask = 1 << 0 static private
Referenced by NetworkDataTlv::ClearStable(), NetworkDataTlv::IsStable(), and NetworkDataTlv::SetStable().
mType
uint8_t mType private
Referenced by NetworkDataTlv::ClearStable(), NetworkDataTlv::GetType(), NetworkDataTlv::Init(), NetworkDataTlv::IsStable(), NetworkDataTlv::SetStable(), and NetworkDataTlv::SetType().
mLength
uint8_t mLength private
Referenced by NetworkDataTlv::DecreaseLength(), NetworkDataTlv::GetLength(), NetworkDataTlv::GetNext(), NetworkDataTlv::GetSize(), NetworkDataTlv::IncreaseLength(), NetworkDataTlv::Init(), and NetworkDataTlv::SetLength().
The documentation for this class was generated from the following files:
network_data_tlvs.hpp
network_data_tlvs.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale