OpenThread: PanIdQueryServer Class Reference
PanIdQueryServer Class Reference
#include <panid_query_server.hpp>
Public Member Functions
PanIdQueryServer (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void HandleQuery (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleScanResult (Mac::ActiveScanResult *aScanResult)
void HandleTimer (void)
void SendConflict (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleQuery (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleScanResult (Mac::ActiveScanResult *aScanResult, void *aContext)
static void HandleTimer (Timer &aTimer)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Private Attributes
uint32_t mChannelMask
Ip6::Address mCommissioner
uint16_t mPanId
Coap::Resource mPanIdQuery
TimerMilli mTimer
Static Private Attributes
static constexpr uint32_t kScanDelay = 1000
SCAN_DELAY (in msec)
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements handling PANID Query Requests.
Constructor & Destructor Documentation
PanIdQueryServer()
PanIdQueryServer (Instance & aInstance) explicit
This constructor initializes the object.
References PanIdQueryServer::mPanIdQuery.
Member Function Documentation
HandleQuery() [1/2]
void HandleQuery (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References ot::AsCoapMessage(), and ot::AsCoreType().
HandleQuery() [2/2]
void HandleQuery (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ChannelMaskTlv::GetChannelMask(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Message::IsConfirmable(), Address::IsMulticast(), Message::IsPostRequest(), PanIdQueryServer::kScanDelay, LogInfo, PanIdQueryServer::mChannelMask, PanIdQueryServer::mCommissioner, PanIdQueryServer::mPanId, PanIdQueryServer::mTimer, TimerMilli::Start(), SuccessOrExit, and VerifyOrExit.
HandleScanResult() [1/2]
void HandleScanResult (Mac::ActiveScanResult * aScanResult, void * aContext) static private
Referenced by PanIdQueryServer::HandleTimer().
HandleScanResult() [2/2]
void HandleScanResult (Mac::ActiveScanResult * aScanResult) private
References otActiveScanResult::mChannel, PanIdQueryServer::mChannelMask, PanIdQueryServer::mPanId, otActiveScanResult::mPanId, and PanIdQueryServer::SendConflict().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and PanIdQueryServer::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References PanIdQueryServer::HandleScanResult(), IgnoreError(), and PanIdQueryServer::mChannelMask.
Referenced by PanIdQueryServer::HandleTimer().
HandleUdpReceive()
static void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
SendConflict()
void SendConflict (void) private
References Tlv::AppendTo(), FreeMessageOnError, InstanceLocator::GetInstance(), ChannelMaskTlv::Init(), ot::kErrorNoBufs, ot::kErrorNone, UriPath::kPanIdConflict, ot::MeshCoP::LogError(), LogInfo, PanIdQueryServer::mChannelMask, PanIdQueryServer::mCommissioner, PanIdQueryServer::mPanId, ChannelMaskTlv::SetChannelMask(), MessageInfo::SetSockAddrToRlocPeerAddrTo(), SuccessOrExit, and VerifyOrExit.
Referenced by PanIdQueryServer::HandleScanResult().
Field Documentation
kScanDelay
constexpr uint32_t kScanDelay = 1000 static private
SCAN_DELAY (in msec)
Referenced by PanIdQueryServer::HandleQuery().
mCommissioner
Ip6::Address mCommissioner private
Referenced by PanIdQueryServer::HandleQuery(), and PanIdQueryServer::SendConflict().
mChannelMask
uint32_t mChannelMask private
Referenced by PanIdQueryServer::HandleQuery(), PanIdQueryServer::HandleScanResult(), PanIdQueryServer::HandleTimer(), and PanIdQueryServer::SendConflict().
mPanId
uint16_t mPanId private
Referenced by PanIdQueryServer::HandleQuery(), PanIdQueryServer::HandleScanResult(), and PanIdQueryServer::SendConflict().
mTimer
TimerMilli mTimer private
Referenced by PanIdQueryServer::HandleQuery().
mPanIdQuery
Coap::Resource mPanIdQuery private
Referenced by PanIdQueryServer::PanIdQueryServer().
The documentation for this class was generated from the following files:
panid_query_server.hpp
panid_query_server.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale