OpenThread: CslAccuracy Class Reference
CslAccuracy Class Reference
Core-mac
#include <mac_types.hpp>
Public Member Functions
uint8_t GetClockAccuracy (void) const
uint8_t GetUncertainty (void) const
uint16_t GetUncertaintyInMicrosec (void) const
void Init (void)
void SetClockAccuracy (uint8_t aClockAccuracy)
void SetUncertainty (uint8_t aUncertainty)
Static Public Attributes
static constexpr uint8_t kWorstClockAccuracy = 255
Worst possible crystal accuracy, in units of ± ppm.
static constexpr uint8_t kWorstUncertainty = 255
Worst possible uncertainty, in units of 10 microseconds.
Private Attributes
uint8_t mClockAccuracy
uint8_t mUncertainty
Static Private Attributes
static constexpr uint8_t kUsPerUncertUnit = 10
Detailed Description
This class represents CSL accuracy.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the CSL accuracy using kWorstClockAccuracy and kWorstUncertainty values.
Referenced by Mle::HandleParentResponse().
GetClockAccuracy()
uint8_t GetClockAccuracy (void) const inline
This method returns the CSL clock accuracy.
Returns
The CSL clock accuracy in ± ppm.
Referenced by Mle::RegisterParentResponseStatsCallback().
SetClockAccuracy()
void SetClockAccuracy (uint8_t aClockAccuracy) inline
This method sets the CSL clock accuracy.
Parameters
[in] aClockAccuracy The CSL clock accuracy in ± ppm.
Referenced by Mle::RxMessage::ReadTlvRequestTlv().
GetUncertainty()
uint8_t GetUncertainty (void) const inline
This method returns the CSL uncertainty.
Returns
The uncertainty in units 10 microseconds.
GetUncertaintyInMicrosec()
uint16_t GetUncertaintyInMicrosec (void) const inline
This method gets the CLS uncertainty in microseconds.
Returns
the CLS uncertainty in microseconds.
Referenced by Mle::RegisterParentResponseStatsCallback().
SetUncertainty()
void SetUncertainty (uint8_t aUncertainty) inline
This method sets the CSL uncertainty.
Parameters
[in] aUncertainty The CSL uncertainty in units 10 microseconds.
Referenced by Mle::RxMessage::ReadTlvRequestTlv().
Field Documentation
kWorstClockAccuracy
constexpr uint8_t kWorstClockAccuracy = 255 static
Worst possible crystal accuracy, in units of ± ppm.
kWorstUncertainty
constexpr uint8_t kWorstUncertainty = 255 static
Worst possible uncertainty, in units of 10 microseconds.
kUsPerUncertUnit
constexpr uint8_t kUsPerUncertUnit = 10 static private
mClockAccuracy
uint8_t mClockAccuracy private
mUncertainty
uint8_t mUncertainty private
The documentation for this class was generated from the following file:
mac_types.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale