OpenThread: Headers Class Reference
Headers Class Reference
Core-ipv6 » IPv6
#include <ip6.hpp>
Public Member Functions
Error DecompressFrom (const Message &aMessage, uint16_t aOffset, const Mac::Addresses &aMacAddrs)
Error DecompressFrom (const FrameData &aFrameData, const Mac::Addresses &aMacAddrs, Instance &aInstance)
uint16_t GetChecksum (void) const
const Address & GetDestinationAddress (void) const
uint16_t GetDestinationPort (void) const
Ecn GetEcn (void) const
const Icmp::Header & GetIcmpHeader (void) const
const Header & GetIp6Header (void) const
uint8_t GetIpProto (void) const
const Address & GetSourceAddress (void) const
uint16_t GetSourcePort (void) const
const Tcp::Header & GetTcpHeader (void) const
const Udp::Header & GetUdpHeader (void) const
bool IsIcmp6 (void) const
bool IsTcp (void) const
bool IsUdp (void) const
Error ParseFrom (const Message &aMessage)
Private Attributes
union {
Icmp::Header mIcmp
Tcp::Header mTcp
Udp::Header mUdp
} mHeader
Header mIp6Header
Additional Inherited Members
Private Member Functions inherited from Clearable< Headers >
void Clear (void)
Detailed Description
This class represents parsed IPv6 header along with UDP/TCP/ICMP6 headers from a received message/frame.
Member Function Documentation
ParseFrom()
Error ParseFrom (const Message & aMessage)
This method parses the IPv6 and UDP/TCP/ICMP6 headers from a given message.
Parameters
[in] aMessage The message to parse the headers from.
Return values
kErrorNone The headers are parsed successfully.
kErrorParse Failed to parse the headers.
References ot::kErrorNone, ot::kErrorParse, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, Message::Read(), and SuccessOrExit.
Referenced by Filter::Accept(), MeshForwarder::CalcFrameVersion(), and Icmp::SendError().
DecompressFrom() [1/2]
Error DecompressFrom (const Message & aMessage, uint16_t aOffset, const Mac::Addresses & aMacAddrs)
This method decompresses lowpan frame and parses the IPv6 and UDP/TCP/ICMP6 headers.
Parameters
[in] aMessage The message from which to read the lowpan frame.
[in] aOffset The offset in aMessage to start reading the frame.
[in] aMacAddrs The MAC source and destination addresses.
Return values
kErrorNone Successfully decompressed and parsed IPv6 and UDP/TCP/ICMP6 headers.
kErrorNotFound Lowpan frame is a next fragment and does not contain IPv6 headers.
kErrorParse Failed to parse the headers.
References Message::GetInstance(), Data< kDataLengthType >::Init(), and Message::ReadBytes().
Referenced by MeshForwarder::GetFramePriority().
DecompressFrom() [2/2]
Error DecompressFrom (const FrameData & aFrameData, const Mac::Addresses & aMacAddrs, Instance & aInstance)
This method decompresses lowpan frame and parses the IPv6 and UDP/TCP/ICMP6 headers.
Parameters
[in] aFrameData The lowpan frame data.
[in] aMacAddrs The MAC source and destination addresses.
[in] aInstance The OpenThread instance.
Return values
kErrorNone Successfully decompressed and parsed IPv6 and UDP/TCP/ICMP6 headers.
kErrorNotFound Lowpan frame is a next fragment and does not contain IPv6 headers.
kErrorParse Failed to parse the headers.
References Lowpan::DecompressBaseHeader(), Lowpan::DecompressUdpHeader(), Instance::Get(), FragmentHeader::GetDatagramOffset(), Lowpan::IsLowpanHc(), ot::kErrorNone, ot::kErrorNotFound, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, FragmentHeader::ParseFrom(), FrameData::Read(), SuccessOrExit, and VerifyOrExit.
GetIp6Header()
const Header& GetIp6Header (void) const inline
This method returns the IPv6 header.
Returns
The IPv6 header.
Referenced by MeshForwarder::GetFramePriority(), and Icmp::SendError().
GetIpProto()
uint8_t GetIpProto (void) const inline
This method returns the IP protocol number from IPv6 Next Header field.
Returns
The IP protocol number.
Referenced by Filter::Accept(), MeshForwarder::CalcFrameVersion(), and Icmp::SendError().
GetEcn()
Ecn GetEcn (void) const inline
This method returns the 2-bit Explicit Congestion Notification (ECN) from Traffic Class field from IPv6 header.
Returns
The ECN value.
Referenced by MeshForwarder::CalcFrameVersion().
IsUdp()
bool IsUdp (void) const inline
This method indicates if the protocol number from IPv6 header is UDP.
Return values
TRUE If the protocol number in IPv6 header is UDP.
FALSE If the protocol number in IPv6 header is not UDP.
References ot::Ip6::kProtoUdp.
Referenced by MeshForwarder::GetFramePriority().
IsTcp()
bool IsTcp (void) const inline
This method indicates if the protocol number from IPv6 header is TCP.
Return values
TRUE If the protocol number in IPv6 header is TCP.
FALSE If the protocol number in IPv6 header is not TCP.
References ot::Ip6::kProtoTcp.
IsIcmp6()
bool IsIcmp6 (void) const inline
This method indicates if the protocol number from IPv6 header is ICMPv6.
Return values
TRUE If the protocol number in IPv6 header is ICMPv6.
FALSE If the protocol number in IPv6 header is not ICMPv6.
References ot::Ip6::kProtoIcmp6.
Referenced by MeshForwarder::GetFramePriority().
GetSourceAddress()
const Address& GetSourceAddress (void) const inline
This method returns the source IPv6 address from IPv6 header.
Returns
The source IPv6 address.
Referenced by MeshForwarder::CalcFrameVersion().
GetDestinationAddress()
const Address& GetDestinationAddress (void) const inline
This method returns the destination IPv6 address from IPv6 header.
Returns
The destination IPv6 address.
Referenced by Filter::Accept(), and MeshForwarder::CalcFrameVersion().
GetUdpHeader()
const Udp::Header& GetUdpHeader (void) const inline
This method returns the UDP header.
This method MUST be used when IsUdp() == true. Otherwise its behavior is undefined
Returns
The UDP header.
Referenced by MeshForwarder::GetFramePriority().
GetTcpHeader()
const Tcp::Header& GetTcpHeader (void) const inline
This method returns the TCP header.
This method MUST be used when IsTcp() == true. Otherwise its behavior is undefined
Returns
The TCP header.
GetIcmpHeader()
const Icmp::Header& GetIcmpHeader (void) const inline
This method returns the ICMPv6 header.
This method MUST be used when IsIcmp6() == true. Otherwise its behavior is undefined
Returns
The ICMPv6 header.
Referenced by MeshForwarder::GetFramePriority(), and Icmp::SendError().
GetSourcePort()
uint16_t GetSourcePort (void) const
This method returns the source port number if header is UDP or TCP, or zero otherwise
Returns
The source port number under UDP / TCP or zero.
References ot::Ip6::kProtoTcp, and ot::Ip6::kProtoUdp.
Referenced by MeshForwarder::CalcFrameVersion().
GetDestinationPort()
uint16_t GetDestinationPort (void) const
This method returns the destination port number if header is UDP or TCP, or zero otherwise.
Returns
The destination port number under UDP / TCP or zero.
References ot::Ip6::kProtoTcp, and ot::Ip6::kProtoUdp.
Referenced by Filter::Accept(), and MeshForwarder::CalcFrameVersion().
GetChecksum()
uint16_t GetChecksum (void) const
This method returns the checksum values from corresponding UDP, TCP, or ICMPv6 header.
Returns
The checksum value.
References ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoTcp, and ot::Ip6::kProtoUdp.
Referenced by MeshForwarder::CalcFrameVersion().
Field Documentation
mIp6Header
Header mIp6Header private
mUdp
Udp::Header mUdp
mTcp
Tcp::Header mTcp
mIcmp
Icmp::Header mIcmp
mHeader
union { ... } mHeader
The documentation for this class was generated from the following files:
ip6.hpp
ip6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale