OpenThread: KeyRecord Class Reference
KeyRecord Class Reference
Core-dns
#include <dns_types.hpp>
Public Types
enum OwnerFlags : uint8_t { kOwnerUser = 0x00, kOwnerZone = 0x01, kOwnerNonZone = 0x02, kOwnerReserved = 0x03 }
enum UseFlags : uint8_t { kAuthConfidPermitted = 0x00, kAuthPermitted = 0x40, kConfidPermitted = 0x80, kNoKey = 0xc0 }
Public Member Functions
uint8_t GetAlgorithm (void) const
OwnerFlags GetOwnerFlags (void) const
uint8_t GetProtocol (void) const
uint8_t GetSignatoryFlags (void) const
UseFlags GetUseFlags (void) const
void Init (uint16_t aClass=kClassInternet)
bool IsValid (void) const
void SetAlgorithm (uint8_t aAlgorithm)
void SetFlags (UseFlags aUseFlags, OwnerFlags aOwnerFlags, uint8_t aSignatoryFlags)
void SetProtocol (uint8_t aProtocol)
Public Member Functions inherited from ResourceRecord
uint16_t GetClass (void) const
uint16_t GetLength (void) const
uint32_t GetSize (void) const
uint32_t GetTtl (void) const
uint16_t GetType (void) const
void Init (uint16_t aType, uint16_t aClass=kClassInternet)
bool Matches (uint16_t aType, uint16_t aClass=kClassInternet)
void SetClass (uint16_t aClass)
void SetLength (uint16_t aLength)
void SetTtl (uint32_t aTtl)
void SetType (uint16_t aType)
Static Public Attributes
static constexpr uint8_t kAlgorithmEcdsaP256Sha256 = 13
ECDSA-P256-SHA256 algorithm.
static constexpr uint8_t kAlgorithmEcdsaP384Sha384 = 14
ECDSA-P384-SHA384 algorithm.
static constexpr uint8_t kAlgorithmEd25519 = 15
ED25519 algorithm.
static constexpr uint8_t kAlgorithmEd448 = 16
ED448 algorithm.
static constexpr uint8_t kProtocolDnsSec = 3
DNS security protocol code.
static constexpr uint8_t kProtocolTls = 1
TLS protocol code.
static constexpr uint8_t kSignatoryFlagGeneral = 1 << 0
static constexpr uint8_t kSignatoryFlagStrong = 1 << 2
static constexpr uint8_t kSignatoryFlagUnique = 1 << 1
static constexpr uint8_t kSignatoryFlagZone = 1 << 3
static constexpr uint16_t kType = kTypeKey
The KEY record type.
Static Public Attributes inherited from ResourceRecord
static constexpr uint16_t kClassAny = 255
Class code Any (ANY).
static constexpr uint16_t kClassInternet = 1
Class code Internet (IN).
static constexpr uint16_t kClassNone = 254
Class code None (NONE) - RFC 2136.
static constexpr uint16_t kTypeA = 1
Address record (IPv4).
static constexpr uint16_t kTypeAaaa = 28
IPv6 address record.
static constexpr uint16_t kTypeAny = 255
ANY record.
static constexpr uint16_t kTypeCname = 5
CNAME record.
static constexpr uint16_t kTypeKey = 25
KEY record.
static constexpr uint16_t kTypeOpt = 41
Option record.
static constexpr uint16_t kTypePtr = 12
PTR record.
static constexpr uint16_t kTypeSig = 24
SIG record.
static constexpr uint16_t kTypeSoa = 6
Start of (zone of) authority.
static constexpr uint16_t kTypeSrv = 33
SRV locator record.
static constexpr uint16_t kTypeTxt = 16
TXT record.
static constexpr uint16_t kTypeZero = 0
Zero as special indicator for the SIG RR (SIG(0) from RFC 2931).
Private Attributes
uint8_t mAlgorithm
uint8_t mFlags [2]
uint8_t mProtocol
Static Private Attributes
static constexpr uint8_t kOwnerFlagsMask = 0x03
static constexpr uint8_t kSignatoryFlagsMask = 0x0f
static constexpr uint8_t kUseFlagsMask = 0xc0
Additional Inherited Members
Static Public Member Functions inherited from ResourceRecord
static Error FindRecord (const Message &aMessage, uint16_t &aOffset, uint16_t &aNumRecords, const Name &aName)
template<class RecordType >
static Error FindRecord (const Message &aMessage, uint16_t &aOffset, uint16_t aNumRecords, uint16_t aIndex, const Name &aName, RecordType &aRecord)
static Error ParseRecords (const Message &aMessage, uint16_t &aOffset, uint16_t aNumRecords)
template<class RecordType >
static Error ReadRecord (const Message &aMessage, uint16_t &aOffset, RecordType &aRecord)
Protected Member Functions inherited from ResourceRecord
Error ReadName (const Message &aMessage, uint16_t &aOffset, uint16_t aStartOffset, char *aNameBuffer, uint16_t aNameBufferSize, bool aSkipRecord) const
Error SkipRecord (const Message &aMessage, uint16_t &aOffset) const
Detailed Description
This class implements Resource Record body format of KEY type (RFC 2535).
Member Enumeration Documentation
UseFlags
enum UseFlags : uint8_t
This enumeration type represents the use (or key type) flags (RFC 2535 - section 3.1.2).
Enumerator
kAuthConfidPermitted
Use of the key for authentication and/or confidentiality is permitted.
kAuthPermitted
Use of the key is only permitted for authentication.
kConfidPermitted
Use of the key is only permitted for confidentiality.
kNoKey
No key value (e.g., can indicate zone is not secure).
OwnerFlags
enum OwnerFlags : uint8_t
This enumeration type represents key owner (or name type) flags (RFC 2535 - section 3.1.2).
Enumerator
kOwnerUser
Key is associated with a "user" or "account" at end entity.
kOwnerZone
Key is a zone key (used for data origin authentication).
kOwnerNonZone
Key is associated with a non-zone "entity".
kOwnerReserved
Reserved for future use.
Member Function Documentation
Init()
void Init (uint16_t aClass = kClassInternet) inline
This method initializes the KEY Resource Record by setting its type and class.
Other record fields (TTL, length, flags, protocol, algorithm) remain unchanged/uninitialized.
Parameters
[in] aClass The class of the resource record (default is kClassInternet).
References ResourceRecord::Init().
Referenced by KeyRecord::IsValid().
IsValid()
bool IsValid (void) const
This method tells whether the KEY record is valid.
Returns
TRUE if this is a valid KEY record, FALSE if an invalid KEY record.
References Header::GetType(), KeyRecord::Init(), and ResourceRecord::kTypeKey.
GetUseFlags()
UseFlags GetUseFlags (void) const inline
This method gets the key use (or key type) flags.
Returns
The key use flags.
References Header::mFlags.
GetOwnerFlags()
OwnerFlags GetOwnerFlags (void) const inline
This method gets the owner (or name type) flags.
Returns
The key owner flags.
References Header::mFlags.
GetSignatoryFlags()
uint8_t GetSignatoryFlags (void) const inline
This method gets the signatory flags.
Returns
The signatory flags.
References Header::mFlags.
SetFlags()
void SetFlags (UseFlags aUseFlags, OwnerFlags aOwnerFlags, uint8_t aSignatoryFlags) inline
This method sets the flags field.
Parameters
[in] aUseFlags The UseFlags value.
[in] aOwnerFlags The OwnerFlags value.
[in] aSignatoryFlags The signatory flags.
References Header::mFlags.
GetProtocol()
uint8_t GetProtocol (void) const inline
This method returns the KEY record's protocol value.
Returns
The protocol value.
SetProtocol()
void SetProtocol (uint8_t aProtocol) inline
This method sets the KEY record's protocol value.
Parameters
[in] aProtocol The protocol value.
GetAlgorithm()
uint8_t GetAlgorithm (void) const inline
This method returns the KEY record's algorithm value.
Returns
The algorithm value.
SetAlgorithm()
void SetAlgorithm (uint8_t aAlgorithm) inline
This method sets the KEY record's algorithm value.
Parameters
[in] aAlgorithm The algorithm value.
Field Documentation
kType
constexpr uint16_t kType = kTypeKey static
The KEY record type.
kProtocolTls
constexpr uint8_t kProtocolTls = 1 static
TLS protocol code.
kProtocolDnsSec
constexpr uint8_t kProtocolDnsSec = 3 static
DNS security protocol code.
kAlgorithmEcdsaP256Sha256
constexpr uint8_t kAlgorithmEcdsaP256Sha256 = 13 static
ECDSA-P256-SHA256 algorithm.
kAlgorithmEcdsaP384Sha384
constexpr uint8_t kAlgorithmEcdsaP384Sha384 = 14 static
ECDSA-P384-SHA384 algorithm.
kAlgorithmEd25519
constexpr uint8_t kAlgorithmEd25519 = 15 static
ED25519 algorithm.
kAlgorithmEd448
constexpr uint8_t kAlgorithmEd448 = 16 static
ED448 algorithm.
kSignatoryFlagZone
constexpr uint8_t kSignatoryFlagZone = 1 << 3 static
Key is authorized to attach, detach, and move zones.
kSignatoryFlagStrong
constexpr uint8_t kSignatoryFlagStrong = 1 << 2 static
Key is authorized to add and delete RRs even if RRs auth with other key.
kSignatoryFlagUnique
constexpr uint8_t kSignatoryFlagUnique = 1 << 1 static
Key is authorized to add and update RRs for only a single owner name.
kSignatoryFlagGeneral
constexpr uint8_t kSignatoryFlagGeneral = 1 << 0 static
If the other flags are zero, this is used to indicate it is an update key.
kUseFlagsMask
constexpr uint8_t kUseFlagsMask = 0xc0 static private
kOwnerFlagsMask
constexpr uint8_t kOwnerFlagsMask = 0x03 static private
kSignatoryFlagsMask
constexpr uint8_t kSignatoryFlagsMask = 0x0f static private
mFlags
uint8_t mFlags[2] private
mProtocol
uint8_t mProtocol private
mAlgorithm
uint8_t mAlgorithm private
The documentation for this class was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale