OpenThread: DataPollSender Class Reference
DataPollSender Class Reference
Core-data-poll-sender
#include <data_poll_sender.hpp>
Public Member Functions
DataPollSender (Instance &aInstance)
uint32_t GetDefaultPollPeriod (void) const
uint32_t GetExternalPollPeriod (void) const
uint32_t GetKeepAlivePollPeriod (void) const
void HandlePollSent (Mac::TxFrame &aFrame, Error aError)
void HandlePollTimeout (void)
Mac::TxFrame * PrepareDataRequest (Mac::TxFrames &aTxFrames)
void ProcessRxFrame (const Mac::RxFrame &aFrame)
void ProcessTxDone (const Mac::TxFrame &aFrame, const Mac::RxFrame *aAckFrame, Error aError)
void RecalculatePollPeriod (void)
void ResetKeepAliveTimer (void)
Error SendDataPoll (void)
void SendFastPolls (uint8_t aNumFastPolls=0)
void SetAttachMode (bool aMode)
Error SetExternalPollPeriod (uint32_t aPeriod)
void StartPolling (void)
void StopFastPolls (void)
void StopPolling (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Attributes
static constexpr uint8_t kDefaultFastPolls = 8
Default number of fast poll tx (.
static constexpr uint8_t kMaxFastPolls = 15
Maximum number of fast poll tx allowed.
static constexpr uint8_t kMaxFastPollsUsers = 63
Maximum number of the users of fast poll tx allowed.
Private Types
enum PollPeriodSelector : uint8_t { kUsePreviousPollPeriod, kRecalculatePollPeriod }
Private Member Functions
uint32_t CalculatePollPeriod (void) const
const Neighbor & GetParent (void) const
Error GetPollDestinationAddress (Mac::Address &aDest) const
void ScheduleNextPoll (PollPeriodSelector aPollPeriodSelector)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandlePollTimer (Timer &aTimer)
Private Attributes
bool mAttachMode: 1
bool mEnabled: 1
uint32_t mExternalPollPeriod: 26
uint8_t mFastPollsUsers: 6
uint32_t mPollPeriod
uint8_t mPollTimeoutCounter: 4
uint8_t mPollTxFailureCounter: 4
uint8_t mRemainingFastPolls: 4
bool mRetxMode: 1
TimerMilli mTimer
TimeMilli mTimerStartTime
Static Private Attributes
static constexpr uint32_t kAttachDataPollPeriod = OPENTHREAD_CONFIG_MAC_ATTACH_DATA_POLL_PERIOD
static constexpr uint32_t kFastPollPeriod = 188
static constexpr uint8_t kMaxCslPollRetxAttempts = OPENTHREAD_CONFIG_MAC_DEFAULT_MAX_FRAME_RETRIES_DIRECT
static constexpr uint32_t kMaxExternalPeriod = ((1 << 26) - 1)
static constexpr uint8_t kMaxPollRetxAttempts = OPENTHREAD_CONFIG_FAILED_CHILD_TRANSMISSIONS
static constexpr uint32_t kMinPollPeriod = OPENTHREAD_CONFIG_MAC_MINIMUM_POLL_PERIOD
static constexpr uint8_t kQuickPollsAfterTimeout = 5
static constexpr uint32_t kRetxPollPeriod = OPENTHREAD_CONFIG_MAC_RETX_POLL_PERIOD
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements the data poll (mac data request command) sender.
Member Enumeration Documentation
PollPeriodSelector
enum PollPeriodSelector : uint8_t private
Enumerator
kUsePreviousPollPeriod
kRecalculatePollPeriod
Constructor & Destructor Documentation
DataPollSender()
DataPollSender (Instance & aInstance) explicit
This constructor initializes the data poll sender object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
StartPolling()
void StartPolling (void)
This method instructs the data poll sender to start sending periodic data polls.
References DataPollSender::kRecalculatePollPeriod, DataPollSender::mEnabled, OT_ASSERT, DataPollSender::ScheduleNextPoll(), and VerifyOrExit.
Referenced by MeshForwarder::SetRxOnWhenIdle().
StopPolling()
void StopPolling (void)
This method instructs the data poll sender to stop sending periodic data polls.
References DataPollSender::mAttachMode, DataPollSender::mEnabled, DataPollSender::mFastPollsUsers, DataPollSender::mPollTimeoutCounter, DataPollSender::mPollTxFailureCounter, DataPollSender::mRemainingFastPolls, DataPollSender::mRetxMode, DataPollSender::mTimer, and TimerMilli::Stop().
Referenced by DataPollSender::HandlePollSent(), DataPollSender::SendDataPoll(), MeshForwarder::SetRxOnWhenIdle(), and MeshForwarder::Stop().
SendDataPoll()
Error SendDataPoll (void)
This method enqueues a data poll (an IEEE 802.15.4 Data Request) message.
Return values
kErrorNone Successfully enqueued a data poll message
kErrorAlready A data poll message is already enqueued.
kErrorInvalidState Device is not in rx-off-when-idle mode.
kErrorNoBufs Insufficient message buffers available.
References ot::ErrorToString(), DataPollSender::GetParent(), DataPollSender::GetPollDestinationAddress(), ot::kErrorInvalidState, ot::kErrorNone, DataPollSender::kRecalculatePollPeriod, DataPollSender::kUsePreviousPollPeriod, LogDebg, LogWarn, DataPollSender::mEnabled, DataPollSender::mTimer, DataPollSender::ScheduleNextPoll(), TimerMilli::Stop(), DataPollSender::StopPolling(), SuccessOrExit, and VerifyOrExit.
Referenced by DataPollSender::HandlePollTimeout(), DataPollSender::HandlePollTimer(), DataPollSender::ProcessRxFrame(), and DataPollSender::ProcessTxDone().
SetExternalPollPeriod()
Error SetExternalPollPeriod (uint32_t aPeriod)
This method sets/clears a user-specified/external data poll period.
Value of zero for aPeriod clears the user-specified poll period.
If the user provides a non-zero poll period, the user value specifies the maximum period between data request transmissions. Note that OpenThread may send data request transmissions more frequently when expecting a control-message from a parent or in case of data poll transmission failures or timeouts, or when the specified value is larger than the child timeout.
A non-zero aPeriod should be larger than or equal to OPENTHREAD_CONFIG_MAC_MINIMUM_POLL_PERIOD (10ms) or this method returns kErrorInvalidArgs. If a non-zero aPeriod is larger than maximum value of 0x3FFFFFF ((1 << 26) - 1), it would be clipped to this value.
Parameters
[in] aPeriod The data poll period in milliseconds.
Return values
kErrorNone Successfully set/cleared user-specified poll period.
kErrorInvalidArgs If aPeriod is invalid.
References ot::kErrorInvalidArgs, ot::kErrorNone, DataPollSender::kMaxExternalPeriod, DataPollSender::kRecalculatePollPeriod, DataPollSender::mEnabled, DataPollSender::mExternalPollPeriod, OPENTHREAD_CONFIG_MAC_MINIMUM_POLL_PERIOD, DataPollSender::ScheduleNextPoll(), and VerifyOrExit.
GetExternalPollPeriod()
uint32_t GetExternalPollPeriod (void) const inline
This method gets the current user-specified/external data poll period.
Returns
The data poll period in milliseconds.
References DataPollSender::GetDefaultPollPeriod(), DataPollSender::GetKeepAlivePollPeriod(), DataPollSender::HandlePollSent(), DataPollSender::HandlePollTimeout(), DataPollSender::mExternalPollPeriod, DataPollSender::PrepareDataRequest(), DataPollSender::ProcessRxFrame(), DataPollSender::ProcessTxDone(), DataPollSender::RecalculatePollPeriod(), DataPollSender::ResetKeepAliveTimer(), DataPollSender::SendFastPolls(), DataPollSender::SetAttachMode(), and DataPollSender::StopFastPolls().
HandlePollSent()
void HandlePollSent (Mac::TxFrame & aFrame, Error aError)
This method informs the data poll sender of success/error status of a previously requested poll frame transmission.
In case of transmit failure, the data poll sender may choose to send the next data poll more quickly (up to some fixed number of attempts).
Parameters
[in] aFrame The data poll frame.
[in] aError Error status of a data poll message transmission.
References ot::ErrorToString(), ExitNow, Frame::GetDstAddr(), DataPollSender::GetParent(), IgnoreError(), Frame::IsEmpty(), ot::kErrorAbort, ot::kErrorChannelAccessFailure, ot::kErrorNone, CslIe::kHeaderIeId, DataPollSender::kMaxCslPollRetxAttempts, DataPollSender::kMaxPollRetxAttempts, DataPollSender::kRecalculatePollPeriod, LogInfo, DataPollSender::mEnabled, DataPollSender::mFastPollsUsers, DataPollSender::mPollTxFailureCounter, DataPollSender::mRemainingFastPolls, DataPollSender::mRetxMode, DataPollSender::ScheduleNextPoll(), DataPollSender::StopPolling(), and VerifyOrExit.
Referenced by DataPollSender::GetExternalPollPeriod().
HandlePollTimeout()
void HandlePollTimeout (void)
This method informs the data poll sender that a data poll timeout happened, i.e., when the ack in response to a data request command indicated that a frame was pending, but no frame was received after timeout interval.
Data poll sender may choose to transmit another data poll immediately (up to some fixed number of attempts).
References IgnoreError(), DataPollSender::kQuickPollsAfterTimeout, LogInfo, DataPollSender::mEnabled, DataPollSender::mPollTimeoutCounter, DataPollSender::SendDataPoll(), and VerifyOrExit.
Referenced by DataPollSender::GetExternalPollPeriod().
ProcessRxFrame()
void ProcessRxFrame (const Mac::RxFrame & aFrame)
This method informs the data poll sender to process a received MAC frame.
Parameters
[in] aFrame A reference to the received frame to process.
References Frame::GetFramePending(), IgnoreError(), DataPollSender::mEnabled, DataPollSender::mPollTimeoutCounter, DataPollSender::SendDataPoll(), and VerifyOrExit.
Referenced by DataPollSender::GetExternalPollPeriod().
ProcessTxDone()
void ProcessTxDone (const Mac::TxFrame & aFrame, const Mac::RxFrame * aAckFrame, Error aError)
This method informs the data poll sender to process a transmitted MAC frame.
Parameters
[in] aFrame A reference to the frame that was transmitted.
[in] aAckFrame A pointer to the ACK frame, nullptr if no ACK was received.
[in] aError kErrorNone when the frame was transmitted successfully, kErrorNoAck when the frame was transmitted but no ACK was received, kErrorChannelAccessFailure when the tx failed due to activity on the channel, kErrorAbort when transmission was aborted for other reasons.
References Frame::GetFramePending(), DataPollSender::GetParent(), Frame::GetSecurityEnabled(), IgnoreError(), ot::kErrorNone, CslIe::kHeaderIeId, DataPollSender::mEnabled, otRadioFrame::mInfo, DataPollSender::mPollTimeoutCounter, otRadioFrame::mTxInfo, DataPollSender::ResetKeepAliveTimer(), DataPollSender::SendDataPoll(), and VerifyOrExit.
Referenced by DataPollSender::GetExternalPollPeriod().
RecalculatePollPeriod()
void RecalculatePollPeriod (void)
This method asks the data poll sender to recalculate the poll period.
This is mainly used to inform the poll sender that a parameter impacting the poll period (e.g., the child's timeout value which is used to determine the default data poll period) is modified.
References DataPollSender::kRecalculatePollPeriod, DataPollSender::mEnabled, and DataPollSender::ScheduleNextPoll().
Referenced by DataPollSender::GetExternalPollPeriod().
SetAttachMode()
void SetAttachMode (bool aMode)
This method sets/clears the attach mode on data poll sender.
When attach mode is enabled, the data poll sender will send data polls at a faster rate determined by poll period configuration option OPENTHREAD_CONFIG_MAC_ATTACH_DATA_POLL_PERIOD.
Parameters
[in] aMode The mode value.
References DataPollSender::kRecalculatePollPeriod, DataPollSender::mAttachMode, DataPollSender::mEnabled, and DataPollSender::ScheduleNextPoll().
Referenced by DataPollSender::GetExternalPollPeriod().
SendFastPolls()
void SendFastPolls (uint8_t aNumFastPolls = 0)
This method asks data poll sender to send the next given number of polls at a faster rate (poll period defined by kFastPollPeriod). This is used by OpenThread stack when it expects a response from the parent/sender.
If aNumFastPolls is zero the default value specified by kDefaultFastPolls is used instead. The number of fast polls is clipped by maximum value specified by kMaxFastPolls.
Note that per SendFastPolls() would increase the internal reference count until up to the allowed maximum value. If there are retransmission mechanism in the caller component, it should be responsible to call StopFastPolls() the same times as SendFastPolls() it triggered to decrease the reference count properly, guaranteeing to exit fast poll mode gracefully. Otherwise, fast poll would continue until all data polls are sent out.
Parameters
[in] aNumFastPolls If non-zero, number of fast polls to send, if zero, default value is used instead.
References DataPollSender::kDefaultFastPolls, DataPollSender::kMaxFastPolls, DataPollSender::kMaxFastPollsUsers, DataPollSender::kRecalculatePollPeriod, DataPollSender::mEnabled, DataPollSender::mFastPollsUsers, DataPollSender::mRemainingFastPolls, and DataPollSender::ScheduleNextPoll().
Referenced by DataPollSender::GetExternalPollPeriod().
StopFastPolls()
void StopFastPolls (void)
This method asks data poll sender to stop fast polls when the expecting response is received.
References DataPollSender::kMaxFastPollsUsers, DataPollSender::kRecalculatePollPeriod, DataPollSender::mFastPollsUsers, DataPollSender::mRemainingFastPolls, DataPollSender::ScheduleNextPoll(), and VerifyOrExit.
Referenced by DataPollSender::GetExternalPollPeriod().
GetKeepAlivePollPeriod()
uint32_t GetKeepAlivePollPeriod (void) const
This method gets the maximum data polling period in use.
The maximum data poll period is determined based as the minimum of the user-specified poll interval and the default poll interval.
Returns
The maximum data polling period in use.
References DataPollSender::GetDefaultPollPeriod(), DataPollSender::mExternalPollPeriod, and ot::Min().
Referenced by DataPollSender::GetExternalPollPeriod().
ResetKeepAliveTimer()
void ResetKeepAliveTimer (void)
This method resets the timer for sending keep-alive messages.
References DataPollSender::GetDefaultPollPeriod(), TimerMilli::GetNow(), Timer::IsRunning(), DataPollSender::mPollPeriod, DataPollSender::mTimer, DataPollSender::mTimerStartTime, and TimerMilli::StartAt().
Referenced by DataPollSender::GetExternalPollPeriod(), and DataPollSender::ProcessTxDone().
GetDefaultPollPeriod()
uint32_t GetDefaultPollPeriod (void) const
This method returns the default maximum poll period.
The default poll period is determined based on the child timeout interval, ensuing the child would send data poll within the child's timeout.
Returns
The maximum default data polling interval (in msec).
References DataPollSender::kMaxPollRetxAttempts, DataPollSender::kRetxPollPeriod, ot::Min(), and Time::SecToMsec().
Referenced by DataPollSender::CalculatePollPeriod(), DataPollSender::GetExternalPollPeriod(), DataPollSender::GetKeepAlivePollPeriod(), and DataPollSender::ResetKeepAliveTimer().
PrepareDataRequest()
Mac::TxFrame * PrepareDataRequest (Mac::TxFrames & aTxFrames)
This method prepares and returns a data request command frame.
Parameters
[in] aTxFrames The set of TxFrames for all radio links.
Returns
The data poll frame.
References DataPollSender::GetPollDestinationAddress(), IgnoreError(), Frame::InitMacHeader(), Frame::IsDstPanIdPresent(), Address::IsExtended(), Frame::kFcfAckRequest, Frame::kFcfDstAddrExt, Frame::kFcfDstAddrShort, Frame::kFcfFrameMacCmd, Frame::kFcfIePresent, Frame::kFcfPanidCompression, Frame::kFcfSecurityEnabled, Frame::kFcfSrcAddrExt, Frame::kFcfSrcAddrShort, CslIe::kHeaderIeId, Frame::kKeyIdMode1, Frame::kMacCmdDataRequest, Frame::kSecEncMic32, Frame::SetCommandId(), Frame::SetDstAddr(), Frame::SetDstPanId(), Address::SetExtended(), TxFrames::SetMaxFrameRetries(), Address::SetShort(), Frame::SetSrcAddr(), and SuccessOrExit.
Referenced by DataPollSender::GetExternalPollPeriod().
ScheduleNextPoll()
void ScheduleNextPoll (PollPeriodSelector aPollPeriodSelector) private
References DataPollSender::CalculatePollPeriod(), TimerMilli::GetNow(), Timer::IsRunning(), DataPollSender::kMinPollPeriod, DataPollSender::kRecalculatePollPeriod, DataPollSender::mPollPeriod, DataPollSender::mTimer, DataPollSender::mTimerStartTime, and TimerMilli::StartAt().
Referenced by DataPollSender::HandlePollSent(), DataPollSender::RecalculatePollPeriod(), DataPollSender::SendDataPoll(), DataPollSender::SendFastPolls(), DataPollSender::SetAttachMode(), DataPollSender::SetExternalPollPeriod(), DataPollSender::StartPolling(), and DataPollSender::StopFastPolls().
CalculatePollPeriod()
uint32_t CalculatePollPeriod (void) const private
References DataPollSender::GetDefaultPollPeriod(), DataPollSender::kAttachDataPollPeriod, DataPollSender::kFastPollPeriod, DataPollSender::kMinPollPeriod, DataPollSender::kRetxPollPeriod, DataPollSender::mAttachMode, DataPollSender::mExternalPollPeriod, ot::Min(), DataPollSender::mRemainingFastPolls, and DataPollSender::mRetxMode.
Referenced by DataPollSender::ScheduleNextPoll().
GetParent()
const Neighbor & GetParent (void) const private
References Neighbor::IsStateValid().
Referenced by DataPollSender::GetPollDestinationAddress(), DataPollSender::HandlePollSent(), DataPollSender::ProcessTxDone(), and DataPollSender::SendDataPoll().
HandlePollTimer()
void HandlePollTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), IgnoreError(), and DataPollSender::SendDataPoll().
GetPollDestinationAddress()
Error GetPollDestinationAddress (Mac::Address & aDest) const private
References Neighbor::GetExtAddress(), DataPollSender::GetParent(), Neighbor::GetRloc16(), Neighbor::IsStateValidOrRestoring(), ot::kErrorAbort, ot::kErrorNone, ot::Mac::kShortAddrInvalid, Address::SetExtended(), Address::SetShort(), and VerifyOrExit.
Referenced by DataPollSender::PrepareDataRequest(), and DataPollSender::SendDataPoll().
Field Documentation
kDefaultFastPolls
constexpr uint8_t kDefaultFastPolls = 8 static
Default number of fast poll tx (.
See also
StartFastPolls).
Referenced by Mle::SendDataRequest(), Mle::SendDelayedResponse(), and DataPollSender::SendFastPolls().
kMaxFastPolls
constexpr uint8_t kMaxFastPolls = 15 static
Maximum number of fast poll tx allowed.
Referenced by DataPollSender::SendFastPolls().
kMaxFastPollsUsers
constexpr uint8_t kMaxFastPollsUsers = 63 static
Maximum number of the users of fast poll tx allowed.
Referenced by DataPollSender::SendFastPolls(), and DataPollSender::StopFastPolls().
kQuickPollsAfterTimeout
constexpr uint8_t kQuickPollsAfterTimeout = 5 static private
Referenced by DataPollSender::HandlePollTimeout().
kMaxPollRetxAttempts
constexpr uint8_t kMaxPollRetxAttempts = OPENTHREAD_CONFIG_FAILED_CHILD_TRANSMISSIONS static private
Referenced by DataPollSender::GetDefaultPollPeriod(), and DataPollSender::HandlePollSent().
kMaxCslPollRetxAttempts
constexpr uint8_t kMaxCslPollRetxAttempts = OPENTHREAD_CONFIG_MAC_DEFAULT_MAX_FRAME_RETRIES_DIRECT static private
Referenced by DataPollSender::HandlePollSent().
kAttachDataPollPeriod
constexpr uint32_t kAttachDataPollPeriod = OPENTHREAD_CONFIG_MAC_ATTACH_DATA_POLL_PERIOD static private
Referenced by DataPollSender::CalculatePollPeriod().
kRetxPollPeriod
constexpr uint32_t kRetxPollPeriod = OPENTHREAD_CONFIG_MAC_RETX_POLL_PERIOD static private
Referenced by DataPollSender::CalculatePollPeriod(), and DataPollSender::GetDefaultPollPeriod().
kFastPollPeriod
constexpr uint32_t kFastPollPeriod = 188 static private
Referenced by DataPollSender::CalculatePollPeriod().
kMinPollPeriod
constexpr uint32_t kMinPollPeriod = OPENTHREAD_CONFIG_MAC_MINIMUM_POLL_PERIOD static private
Referenced by DataPollSender::CalculatePollPeriod(), and DataPollSender::ScheduleNextPoll().
kMaxExternalPeriod
constexpr uint32_t kMaxExternalPeriod = ((1 << 26) - 1) static private
Referenced by DataPollSender::SetExternalPollPeriod().
mTimerStartTime
TimeMilli mTimerStartTime private
Referenced by DataPollSender::ResetKeepAliveTimer(), and DataPollSender::ScheduleNextPoll().
mPollPeriod
uint32_t mPollPeriod private
Referenced by DataPollSender::ResetKeepAliveTimer(), and DataPollSender::ScheduleNextPoll().
mExternalPollPeriod
uint32_t mExternalPollPeriod private
Referenced by DataPollSender::CalculatePollPeriod(), DataPollSender::GetExternalPollPeriod(), DataPollSender::GetKeepAlivePollPeriod(), and DataPollSender::SetExternalPollPeriod().
mFastPollsUsers
uint8_t mFastPollsUsers private
Referenced by DataPollSender::HandlePollSent(), DataPollSender::SendFastPolls(), DataPollSender::StopFastPolls(), and DataPollSender::StopPolling().
mTimer
TimerMilli mTimer private
Referenced by DataPollSender::ResetKeepAliveTimer(), DataPollSender::ScheduleNextPoll(), DataPollSender::SendDataPoll(), and DataPollSender::StopPolling().
mEnabled
bool mEnabled private
Referenced by DataPollSender::HandlePollSent(), DataPollSender::HandlePollTimeout(), DataPollSender::ProcessRxFrame(), DataPollSender::ProcessTxDone(), DataPollSender::RecalculatePollPeriod(), DataPollSender::SendDataPoll(), DataPollSender::SendFastPolls(), DataPollSender::SetAttachMode(), DataPollSender::SetExternalPollPeriod(), DataPollSender::StartPolling(), and DataPollSender::StopPolling().
mAttachMode
bool mAttachMode private
Referenced by DataPollSender::CalculatePollPeriod(), DataPollSender::SetAttachMode(), and DataPollSender::StopPolling().
mRetxMode
bool mRetxMode private
Referenced by DataPollSender::CalculatePollPeriod(), DataPollSender::HandlePollSent(), and DataPollSender::StopPolling().
mPollTimeoutCounter
uint8_t mPollTimeoutCounter private
Referenced by DataPollSender::HandlePollTimeout(), DataPollSender::ProcessRxFrame(), DataPollSender::ProcessTxDone(), and DataPollSender::StopPolling().
mPollTxFailureCounter
uint8_t mPollTxFailureCounter private
Referenced by DataPollSender::HandlePollSent(), and DataPollSender::StopPolling().
mRemainingFastPolls
uint8_t mRemainingFastPolls private
Referenced by DataPollSender::CalculatePollPeriod(), DataPollSender::HandlePollSent(), DataPollSender::SendFastPolls(), DataPollSender::StopFastPolls(), and DataPollSender::StopPolling().
The documentation for this class was generated from the following files:
data_poll_sender.hpp
data_poll_sender.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale