OpenThread: Icmp::Header Class Reference
Icmp::Header Class Reference
#include <icmp6.hpp>
Public Types
enum Code : uint8_t { kCodeDstUnreachNoRoute = OT_ICMP6_CODE_DST_UNREACH_NO_ROUTE, kCodeFragmReasTimeEx = OT_ICMP6_CODE_FRAGM_REAS_TIME_EX }
enum Type : uint8_t {
kTypeDstUnreach = OT_ICMP6_TYPE_DST_UNREACH, kTypePacketToBig = OT_ICMP6_TYPE_PACKET_TO_BIG, kTypeTimeExceeded = OT_ICMP6_TYPE_TIME_EXCEEDED, kTypeParameterProblem = OT_ICMP6_TYPE_PARAMETER_PROBLEM,
kTypeEchoRequest = OT_ICMP6_TYPE_ECHO_REQUEST, kTypeEchoReply = OT_ICMP6_TYPE_ECHO_REPLY, kTypeRouterSolicit = OT_ICMP6_TYPE_ROUTER_SOLICIT, kTypeRouterAdvert = OT_ICMP6_TYPE_ROUTER_ADVERT
}
Public Member Functions
uint16_t GetChecksum (void) const
Code GetCode (void) const
uint16_t GetId (void) const
uint16_t GetSequence (void) const
Type GetType (void) const
bool IsError (void) const
void SetChecksum (uint16_t aChecksum)
void SetCode (Code aCode)
void SetId (uint16_t aId)
void SetSequence (uint16_t aSequence)
void SetType (Type aType)
Public Member Functions inherited from Clearable< Header >
void Clear (void)
Static Public Attributes
static constexpr uint8_t kChecksumFieldOffset = 2
The byte offset of Checksum field in ICMP6 header.
static constexpr uint8_t kCodeFieldOffset = 1
The byte offset of Code field in ICMP6 header.
static constexpr uint8_t kDataFieldOffset = 4
The byte offset of Data field in ICMP6 header.
static constexpr uint8_t kTypeFieldOffset = 0
The byte offset of Type field in ICMP6 header.
Additional Inherited Members
Data Fields inherited from otIcmp6Header
uint16_t mChecksum
Checksum.
uint8_t mCode
Code.
union otIcmp6Header::OT_TOOL_PACKED_FIELD mData
Message-specific data.
uint8_t mType
Type.
Member Enumeration Documentation
Type
enum Type : uint8_t
ICMPv6 Message Types
Enumerator
kTypeDstUnreach
Destination Unreachable.
kTypePacketToBig
Packet To Big.
kTypeTimeExceeded
Time Exceeded.
kTypeParameterProblem
Parameter Problem.
kTypeEchoRequest
Echo Request.
kTypeEchoReply
Echo Reply.
kTypeRouterSolicit
Router Solicitation.
kTypeRouterAdvert
Router Advertisement.
Code
enum Code : uint8_t
ICMPv6 Message Codes
Enumerator
kCodeDstUnreachNoRoute
Destination Unreachable No Route.
kCodeFragmReasTimeEx
Fragment Reassembly Time Exceeded.
Member Function Documentation
IsError()
bool IsError (void) const inline
This method indicates whether the ICMPv6 message is an error message.
Return values
TRUE if the ICMPv6 message is an error message.
FALSE if the ICMPv6 message is an informational message.
References otIcmp6Header::mType, and OT_ICMP6_TYPE_ECHO_REQUEST.
Referenced by MeshForwarder::GetFramePriority(), and Icmp::SendError().
GetType()
Type GetType (void) const inline
This method returns the ICMPv6 message type.
Returns
The ICMPv6 message type.
References otIcmp6Header::mType.
Referenced by AddressResolver::HandleAddressError(), Icmp::HandleMessage(), and Ip6::ProcessReceiveCallback().
SetType()
void SetType (Type aType) inline
This method sets the ICMPv6 message type.
Parameters
[in] aType The ICMPv6 message type.
References otIcmp6Header::mType.
Referenced by Icmp::HandleEchoRequest(), Icmp::SendEchoRequest(), and Icmp::SendError().
GetCode()
Code GetCode (void) const inline
This method returns the ICMPv6 message code.
Returns
The ICMPv6 message code.
References otIcmp6Header::mCode.
Referenced by AddressResolver::HandleAddressError().
SetCode()
void SetCode (Code aCode) inline
This method sets the ICMPv6 message code.
Parameters
[in] aCode The ICMPv6 message code.
References otIcmp6Header::mCode.
Referenced by Icmp::SendError().
GetChecksum()
uint16_t GetChecksum (void) const inline
This method returns the ICMPv6 message checksum.
Returns
The ICMPv6 message checksum.
References ot::Encoding::BigEndian::HostSwap16(), and otIcmp6Header::mChecksum.
SetChecksum()
void SetChecksum (uint16_t aChecksum) inline
This method sets the ICMPv6 message checksum.
Parameters
[in] aChecksum The ICMPv6 message checksum.
References ot::Encoding::BigEndian::HostSwap16(), and otIcmp6Header::mChecksum.
GetId()
uint16_t GetId (void) const inline
This method returns the ICMPv6 message ID for Echo Requests and Replies.
Returns
The ICMPv6 message ID.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, and otIcmp6Header::mData.
SetId()
void SetId (uint16_t aId) inline
This method sets the ICMPv6 message ID for Echo Requests and Replies.
Parameters
[in] aId The ICMPv6 message ID.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, and otIcmp6Header::mData.
Referenced by Icmp::SendEchoRequest().
GetSequence()
uint16_t GetSequence (void) const inline
This method returns the ICMPv6 message sequence for Echo Requests and Replies.
Returns
The ICMPv6 message sequence.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, and otIcmp6Header::mData.
Referenced by Icmp::HandleEchoRequest(), and Icmp::SendEchoRequest().
SetSequence()
void SetSequence (uint16_t aSequence) inline
This method sets the ICMPv6 message sequence for Echo Requests and Replies.
Parameters
[in] aSequence The ICMPv6 message sequence.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, otIcmp6Header::mData, and Icmp::OT_TOOL_PACKED_END.
Referenced by Icmp::SendEchoRequest().
Field Documentation
kTypeFieldOffset
constexpr uint8_t kTypeFieldOffset = 0 static
The byte offset of Type field in ICMP6 header.
kCodeFieldOffset
constexpr uint8_t kCodeFieldOffset = 1 static
The byte offset of Code field in ICMP6 header.
kChecksumFieldOffset
constexpr uint8_t kChecksumFieldOffset = 2 static
The byte offset of Checksum field in ICMP6 header.
Referenced by Checksum::UpdateMessageChecksum().
kDataFieldOffset
constexpr uint8_t kDataFieldOffset = 4 static
The byte offset of Data field in ICMP6 header.
Referenced by Icmp::HandleEchoRequest().
The documentation for this class was generated from the following file:
icmp6.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale