OpenThread: OptionHeader Class Reference
OptionHeader Class Reference
Core-ipv6 » IPv6
#include <ip6_headers.hpp>
Public Types
enum Action : uint8_t { kActionSkip = 0x00, kActionDiscard = 0x40, kActionForceIcmp = 0x80, kActionIcmp = 0xc0 }
Public Member Functions
Action GetAction (void) const
uint8_t GetLength (void) const
uint8_t GetType (void) const
OptionHeader (void)
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint8_t mLength
uint8_t mType
Static Private Attributes
static constexpr uint8_t kActionMask = 0xc0
Detailed Description
This class implements IPv6 Options generation and parsing.
Member Enumeration Documentation
Action
enum Action : uint8_t
IPv6 Option Type actions for unrecognized IPv6 Options.
Enumerator
kActionSkip
skip over this option and continue processing the header
kActionDiscard
discard the packet
kActionForceIcmp
discard the packet and forcibly send an ICMP Parameter Problem
kActionIcmp
discard packet and conditionally send an ICMP Parameter Problem
Constructor & Destructor Documentation
OptionHeader()
OptionHeader (void) inline
Default constructor.
Referenced by OptionMpl::GetTotalLength().
Member Function Documentation
GetType()
uint8_t GetType (void) const inline
This method returns the IPv6 Option Type value.
Returns
The IPv6 Option Type value.
Referenced by Lowpan::CompressExtensionHeader(), Ip6::HandleOptions(), and Ip6::RemoveMplOption().
SetType()
void SetType (uint8_t aType) inline
This method sets the IPv6 Option Type value.
Parameters
[in] aType The IPv6 Option Type value.
Referenced by OptionMpl::Init().
GetAction()
Action GetAction (void) const inline
This method returns the IPv6 Option action for unrecognized IPv6 Options.
Returns
The IPv6 Option action for unrecognized IPv6 Options.
Referenced by Ip6::HandleOptions().
GetLength()
uint8_t GetLength (void) const inline
This method returns the IPv6 Option Length value.
Returns
The IPv6 Option Length value.
Referenced by Lowpan::CompressExtensionHeader(), OptionMpl::GetTotalLength(), Ip6::HandleOptions(), Mpl::InitOption(), and Ip6::RemoveMplOption().
SetLength()
void SetLength (uint8_t aLength) inline
This method sets the IPv6 Option Length value.
Parameters
[in] aLength The IPv6 Option Length value.
Referenced by OptionMpl::Init(), and Mpl::InitOption().
Field Documentation
kActionMask
constexpr uint8_t kActionMask = 0xc0 static private
mType
uint8_t mType private
mLength
uint8_t mLength private
The documentation for this class was generated from the following file:
ip6_headers.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale