OpenThread: Data Class Reference
Data Class Reference
#include <heap_data.hpp>
Public Member Functions
Error CopyBytesTo (Message &aMessage) const
void CopyBytesTo (uint8_t *aBuffer) const
Data (void)
Data (Data &&aData)
Data (const Data &)=delete
void Free (void)
const uint8_t * GetBytes (void) const
uint16_t GetLength (void) const
bool IsNull (void) const
Data & operator= (const Data &)=delete
Error SetFrom (const uint8_t *aBuffer, uint16_t aLength)
Error SetFrom (const Message &aMessage)
Error SetFrom (const Message &aMessage, uint16_t aOffset, uint16_t aLength)
void SetFrom (Data &&aData)
~Data (void)
Private Member Functions
void TakeFrom (Data &aData)
Error UpdateBuffer (uint16_t aNewLength)
Private Attributes
MutableData< kWithUint16Length > mData
Detailed Description
This class represents a heap allocated data.
Constructor & Destructor Documentation
Data() [1/3]
Data (void) inline
This constructor initializes the Heap::Data as empty.
References MutableData< kDataLengthType >::Init(), and Data::mData.
Referenced by Data::CopyBytesTo().
Data() [2/3]
Data (Data && aData) inline
This is the move constructor for Heap::Data.
Heap::Data is non-copyable (copy constructor is deleted) but move constructor is provided to allow it to to be used as return type (return by value) from functions/methods (which will then use move semantics).
Parameters
[in] aData An rvalue reference to another Heap::Data to move from.
References Data::TakeFrom().
~Data()
~Data (void) inline
This is the destructor for Heap::Data object.
References Data::Free().
Data() [3/3]
Data (const Data &) delete
Member Function Documentation
IsNull()
bool IsNull (void) const inline
This method indicates whether or not the Heap::Data is null (i.e., it was never successfully set or it was freed).
Return values
TRUE The Heap::Data is null.
FALSE The Heap::Data is not null.
References MutableData< kDataLengthType >::GetBytes(), and Data::mData.
GetBytes()
const uint8_t* GetBytes (void) const inline
This method returns a pointer to the Heap::Data bytes buffer.
Returns
A pointer to data buffer or nullptr if the Heap::Data is null (never set or freed).
References MutableData< kDataLengthType >::GetBytes(), and Data::mData.
GetLength()
uint16_t GetLength (void) const inline
This method returns the Heap::Data length.
Returns
The data length (number of bytes) or zero if the HeadpData is null.
References Data< kDataLengthType >::GetLength(), Data::mData, and Data::SetFrom().
Referenced by Data::TakeFrom().
SetFrom() [1/4]
Error SetFrom (const uint8_t * aBuffer, uint16_t aLength)
This method sets the Heap::Data from the content of a given buffer.
Parameters
[in] aBuffer The buffer to copy bytes from.
[in] aLength The buffer length (number of bytes).
Return values
kErrorNone Successfully set the Heap::Data.
kErrorNoBufs Failed to allocate buffer.
References MutableData< kDataLengthType >::CopyBytesFrom(), Data::mData, SuccessOrAssert, SuccessOrExit, Data::UpdateBuffer(), and VerifyOrExit.
Referenced by Data::GetLength(), and Data::SetFrom().
SetFrom() [2/4]
Error SetFrom (const Message & aMessage)
This method sets the Heap::Data from the content of a given message.
The bytes are copied from current offset in aMessage till the end of the message.
Parameters
[in] aMessage The message to copy bytes from (starting from offset till the end of message).
Return values
kErrorNone Successfully set the Heap::Data.
kErrorNoBufs Failed to allocate buffer.
References Message::GetLength(), Message::GetOffset(), and Data::SetFrom().
SetFrom() [3/4]
Error SetFrom (const Message & aMessage, uint16_t aOffset, uint16_t aLength)
This method sets the Heap::Data from the content of a given message read at a given offset up to a given length.
Parameters
[in] aMessage The message to read and copy bytes from.
[in] aOffset The offset into the message to start reading the bytes from.
[in] aLength The number of bytes to read from message. If aMessage contains fewer bytes than requested, then Heap::Data is cleared and this method returns kErrorParse.
Return values
kErrorNone Successfully set the Heap::Data.
kErrorNoBufs Failed to allocate buffer.
kErrorParse Not enough bytes in aMessage to read the requested aLength bytes.
References MutableData< kDataLengthType >::GetBytes(), Message::GetLength(), ot::kErrorParse, Data::mData, Message::Read(), SuccessOrAssert, SuccessOrExit, Data::UpdateBuffer(), and VerifyOrExit.
SetFrom() [4/4]
void SetFrom (Data && aData)
This method sets the Heap::Data from another one (move semantics).
Parameters
[in] aData The other Heap::Data to set from (rvalue reference).
References Data::Free(), and Data::TakeFrom().
CopyBytesTo() [1/2]
Error CopyBytesTo (Message & aMessage) const inline
This method appends the bytes from Heap::Data to a given message.
Parameters
[in] aMessage The message to append the bytes into.
Return values
kErrorNone Successfully copied the bytes from Heap::Data into aMessage.
kErrorNoBufs Failed to allocate buffer.
References Message::AppendBytes(), MutableData< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), and Data::mData.
CopyBytesTo() [2/2]
void CopyBytesTo (uint8_t * aBuffer) const inline
This method copies the bytes from Heap::Data into a given buffer.
It is up to the caller to ensure that aBuffer has enough space for the current data length.
Parameters
[in] aBuffer A pointer to buffer to copy the bytes into.
References Data< kDataLengthType >::CopyBytesTo(), Data::Data(), Data::Free(), Data::mData, Data::operator=(), Data::TakeFrom(), and Data::UpdateBuffer().
Free()
void Free (void)
This method frees any buffer allocated by the Heap::Data.
The Heap::Data destructor will automatically call Free(). This method allows caller to free the buffer explicitly.
References ot::Heap::Free(), MutableData< kDataLengthType >::GetBytes(), MutableData< kDataLengthType >::Init(), and Data::mData.
Referenced by Data::CopyBytesTo(), Data::SetFrom(), and Data::~Data().
operator=()
Data& operator= (const Data &) delete
Referenced by Data::CopyBytesTo().
UpdateBuffer()
Error UpdateBuffer (uint16_t aNewLength) private
References ot::Heap::CAlloc(), ot::Heap::Free(), MutableData< kDataLengthType >::GetBytes(), Data< kDataLengthType >::GetLength(), MutableData< kDataLengthType >::Init(), ot::kErrorNoBufs, ot::kErrorNone, Data::mData, and VerifyOrExit.
Referenced by Data::CopyBytesTo(), and Data::SetFrom().
TakeFrom()
void TakeFrom (Data & aData) private
References MutableData< kDataLengthType >::GetBytes(), Data::GetLength(), MutableData< kDataLengthType >::Init(), and Data::mData.
Referenced by Data::CopyBytesTo(), Data::Data(), and Data::SetFrom().
Field Documentation
mData
MutableData<kWithUint16Length> mData private
Referenced by Data::CopyBytesTo(), Data::Data(), Data::Free(), Data::GetBytes(), Data::GetLength(), Data::IsNull(), Data::SetFrom(), Data::TakeFrom(), and Data::UpdateBuffer().
The documentation for this class was generated from the following files:
heap_data.hpp
heap_data.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale