OpenThread: SerialNumber Class Reference
SerialNumber Class Reference
#include <serial_number.hpp>
Static Public Member Functions
template<typename UintType >
static bool IsGreater (UintType aFirst, UintType aSecond)
template<typename UintType >
static bool IsLess (UintType aFirst, UintType aSecond)
Member Function Documentation
IsLess()
static bool IsLess (UintType aFirst, UintType aSecond) inline static
This static method indicates whether or not a first serial number is strictly less than a second serial number.
The comparison takes into account the wrapping of serial number values (similar to RFC-1982). It is semantically equivalent to aFirst < aSecond.
Template Parameters
UintType The unsigned integer type.
Parameters
[in] aFirst The first serial number.
[in] aSecond The second serial number.
Return values
TRUE If aFirst is less than aSecond.
FALSE If aFirst is not less than aSecond.
Referenced by SerialNumber::IsGreater(), Time::operator<(), and Mpl::UpdateSeedSet().
IsGreater()
static bool IsGreater (UintType aFirst, UintType aSecond) inline static
This static method indicates whether or not a first serial number is strictly greater than a second serial number.
The comparison takes into account the wrapping of serial number values (similar to RFC-1982). It is semantically equivalent to aFirst > aSecond.
Template Parameters
UintType The unsigned integer type.
Parameters
[in] aFirst The first serial number.
[in] aSecond The second serial number.
Return values
TRUE If aFirst is greater than aSecond.
FALSE If aFirst is not greater than aSecond.
References SerialNumber::IsLess().
Referenced by Manager::FindPreferredDnsSrpAnycastInfo(), Mle::HandleParentResponse(), Mle::IsNetworkDataNewer(), and Neighbor::SetRloc16().
The documentation for this class was generated from the following file:
serial_number.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale