OpenThread: MeshForwarder Class Reference
MeshForwarder Class Reference
Core-mesh-forwarding
#include <mesh_forwarder.hpp>
Public Member Functions
Error EvictMessage (Message::Priority aPriority)
const otIpCounters & GetCounters (void) const
const MessageQueue & GetReassemblyQueue (void) const
bool GetRxOnWhenIdle (void) const
const PriorityQueue & GetSendQueue (void) const
void HandleResolved (const Ip6::Address &aEid, Error aError)
MeshForwarder (Instance &aInstance)
void RemoveDataResponseMessages (void)
void ResetCounters (void)
Error SendMessage (Message &aMessage)
void SetDiscoverParameters (const Mac::ChannelMask &aScanChannels)
void SetRxOnWhenIdle (bool aRxOnWhenIdle)
void Start (void)
void Stop (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Types
enum AnycastType : uint8_t { kAnycastDhcp6Agent, kAnycastNeighborDiscoveryAgent, kAnycastService }
enum MessageAction : uint8_t {
kMessageReceive, kMessageTransmit, kMessagePrepareIndirect, kMessageDrop,
kMessageReassemblyDrop, kMessageEvict
}
Private Member Functions
Error AnycastRouteLookup (uint8_t aServiceId, AnycastType aType, uint16_t &aMeshDest) const
uint16_t CalcFrameVersion (const Neighbor *aNeighbor, bool aIePresent)
bool CalcIePresent (const Message *aMessage)
Error CheckReachability (const FrameData &aFrameData, const Mac::Addresses &aMeshAddrs)
void ClearReassemblyList (void)
void EvaluateRoutingCost (uint16_t aDest, uint8_t &aBestCost, uint16_t &aBestDest) const
Error FrameToMessage (const FrameData &aFrameData, uint16_t aDatagramSize, const Mac::Addresses &aMacAddrs, Message *&aMessage)
void GetForwardFramePriority (const FrameData &aFrameData, const Mac::Addresses &aMeshAddrs, Message::Priority &aPriority)
Error GetFragmentPriority (Lowpan::FragmentHeader &aFragmentHeader, uint16_t aSrcRloc16, Message::Priority &aPriority)
Error GetFramePriority (const FrameData &aFrameData, const Mac::Addresses &aMacAddrs, Message::Priority &aPriority)
void GetMacDestinationAddress (const Ip6::Address &aIp6Addr, Mac::Address &aMacAddr)
void GetMacSourceAddress (const Ip6::Address &aIp6Addr, Mac::Address &aMacAddr)
Error HandleDatagram (Message &aMessage, const ThreadLinkInfo &aLinkInfo, const Mac::Address &aMacSource)
void HandleDiscoverComplete (void)
void HandleFragment (FrameData &aFrameData, const Mac::Addresses &aMacAddrs, const ThreadLinkInfo &aLinkInfo)
Mac::TxFrame * HandleFrameRequest (Mac::TxFrames &aTxFrames)
void HandleLowpanHC (const FrameData &aFrameData, const Mac::Addresses &aMacAddrs, const ThreadLinkInfo &aLinkInfo)
void HandleMesh (FrameData &aFrameData, const Mac::Address &aMacSource, const ThreadLinkInfo &aLinkInfo)
void HandleReceivedFrame (Mac::RxFrame &aFrame)
void HandleSentFrame (Mac::TxFrame &aFrame, Error aError)
void HandleTimeTick (void)
void LogFragmentFrameDrop (Error aError, uint16_t aFrameLength, const Mac::Addresses &aMacAddrs, const Lowpan::FragmentHeader &aFragmentHeader, bool aIsSecure)
void LogFrame (const char *aActionText, const Mac::Frame &aFrame, Error aError)
void LogLowpanHcFrameDrop (Error aError, uint16_t aFrameLength, const Mac::Addresses &aMacAddrs, bool aIsSecure)
void LogMessage (MessageAction aAction, const Message &aMessage, Error aError=kErrorNone, const Mac::Address *aAddress=nullptr)
void PauseMessageTransmissions (void)
uint16_t PrepareDataFrame (Mac::TxFrame &aFrame, Message &aMessage, const Mac::Addresses &aMacAddrs, bool aAddMeshHeader=false, uint16_t aMeshSource=0xffff, uint16_t aMeshDest=0xffff, bool aAddFragHeader=false)
void PrepareEmptyFrame (Mac::TxFrame &aFrame, const Mac::Address &aMacDest, bool aAckRequest)
Message * PrepareNextDirectTransmission (void)
void RemoveMessage (Message &aMessage)
void RemoveMessageIfNoPendingTx (Message &aMessage)
void ResumeMessageTransmissions (void)
void ScheduleTransmissionTask (void)
void SendDestinationUnreachable (uint16_t aMeshSource, const Ip6::Headers &aIp6Headers)
void SendIcmpErrorIfDstUnreach (const Message &aMessage, const Mac::Addresses &aMacAddrs)
void SendMesh (Message &aMessage, Mac::TxFrame &aFrame)
void UpdateFragmentPriority (Lowpan::FragmentHeader &aFragmentHeader, uint16_t aFragmentLength, uint16_t aSrcRloc16, Message::Priority aPriority)
Error UpdateIp6Route (Message &aMessage)
Error UpdateIp6RouteFtd (Ip6::Header &ip6Header, Message &aMessage)
Error UpdateMeshRoute (Message &aMessage)
void UpdateNeighborLinkFailures (Neighbor &aNeighbor, Error aError, bool aAllowNeighborRemove, uint8_t aFailLimit=Mle::kFailedRouterTransmissions)
Neighbor * UpdateNeighborOnSentFrame (Mac::TxFrame &aFrame, Error aError, const Mac::Address &aMacDest, bool aIsDataPoll=false)
bool UpdateReassemblyList (void)
void UpdateRoutes (const FrameData &aFrameData, const Mac::Addresses &aMeshAddrs)
void UpdateSendMessage (Error aFrameTxError, Mac::Address &aMacDest, Neighbor *aNeighbor)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void ScheduleTransmissionTask (Tasklet &aTasklet)
Private Attributes
bool mAddMeshHeader: 1
DataPollSender mDataPollSender
bool mEnabled: 1
uint16_t mFragTag
otIpCounters mIpCounters
Mac::Addresses mMacAddrs
uint16_t mMeshDest
uint16_t mMeshSource
uint16_t mMessageNextOffset
MessageQueue mReassemblyList
Tasklet mScheduleTransmissionTask
bool mSendBusy: 1
Message * mSendMessage
PriorityQueue mSendQueue
bool mTxPaused: 1
Static Private Attributes
static constexpr uint8_t kMeshHeaderFrameFcsSize = sizeof(uint16_t)
static constexpr uint8_t kMeshHeaderFrameMtu = OT_RADIO_FRAME_MAX_SIZE
static constexpr uint8_t kReassemblyTimeout = OPENTHREAD_CONFIG_6LOWPAN_REASSEMBLY_TIMEOUT
static constexpr uint32_t kTxDelayInterval = OPENTHREAD_CONFIG_MAC_COLLISION_AVOIDANCE_DELAY_INTERVAL
Friends
class DataPollSender
class IndirectSender
class Instance
class Ip6::Ip6
class Mac::Mac
class Mle::DiscoverScanner
class TimeTicker
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements mesh forwarding within Thread.
Member Enumeration Documentation
MessageAction
enum MessageAction : uint8_t private
Enumerator
kMessageReceive
kMessageTransmit
kMessagePrepareIndirect
kMessageDrop
kMessageReassemblyDrop
kMessageEvict
AnycastType
enum AnycastType : uint8_t private
Enumerator
kAnycastDhcp6Agent
kAnycastNeighborDiscoveryAgent
kAnycastService
Constructor & Destructor Documentation
MeshForwarder()
MeshForwarder (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ot::Random::NonCrypto::GetUint16(), MeshForwarder::mFragTag, and MeshForwarder::ResetCounters().
Member Function Documentation
Start()
void Start (void)
This method enables mesh forwarding and the IEEE 802.15.4 MAC layer.
References MeshForwarder::mEnabled, and MeshForwarder::SetRxOnWhenIdle().
Referenced by MeshForwarder::SetRxOnWhenIdle().
Stop()
void Stop (void)
This method disables mesh forwarding and the IEEE 802.15.4 MAC layer.
References MessageQueue::DequeueAndFreeAll(), PriorityQueue::DequeueAndFreeAll(), TimeTicker::kMeshForwarder, MeshForwarder::mDataPollSender, MeshForwarder::mEnabled, MeshForwarder::mReassemblyList, MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, MeshForwarder::SetRxOnWhenIdle(), DataPollSender::StopPolling(), and VerifyOrExit.
Referenced by MeshForwarder::SetRxOnWhenIdle().
SendMessage()
Error SendMessage (Message & aMessage)
This method submits a message to the mesh forwarder for forwarding.
Parameters
[in] aMessage A reference to the message.
Return values
kErrorNone Successfully enqueued the message.
kErrorAlready The message was already enqueued.
kErrorDrop The message could not be sent and should be dropped.
Referenced by MeshForwarder::GetFramePriority().
HandleResolved()
void HandleResolved (const Ip6::Address & aEid, Error aError)
This method is called by the address resolver when an EID-to-RLOC mapping has been resolved.
Parameters
[in] aEid A reference to the EID that has been resolved.
[in] aError kErrorNone on success and kErrorDrop otherwise.
GetRxOnWhenIdle()
bool GetRxOnWhenIdle (void) const
This method indicates whether or not rx-on-when-idle mode is enabled.
Return values
TRUE The rx-on-when-idle mode is enabled.
FALSE The rx-on-when-idle-mode is disabled.
Referenced by MeshForwarder::GetFramePriority(), and MeshForwarder::HandleFragment().
SetRxOnWhenIdle()
void SetRxOnWhenIdle (bool aRxOnWhenIdle)
This method sets the rx-on-when-idle mode
Parameters
[in] aRxOnWhenIdle TRUE to enable, FALSE otherwise.
References MeshForwarder::mDataPollSender, MeshForwarder::Start(), DataPollSender::StartPolling(), MeshForwarder::Stop(), and DataPollSender::StopPolling().
Referenced by MeshForwarder::Start(), and MeshForwarder::Stop().
SetDiscoverParameters()
void SetDiscoverParameters (const Mac::ChannelMask & aScanChannels)
This method sets the scan parameters for MLE Discovery Request messages.
Parameters
[in] aScanChannels A reference to channel mask indicating which channels to scan. If aScanChannels is empty, then all channels are used instead.
RemoveDataResponseMessages()
void RemoveDataResponseMessages (void)
This method frees unicast/multicast MLE Data Responses from Send Message Queue if any.
EvictMessage()
Error EvictMessage (Message::Priority aPriority)
This method evicts the message with lowest priority in the send queue.
Parameters
[in] aPriority The highest priority level of the evicted message.
Return values
kErrorNone Successfully evicted a low priority message.
kErrorNotFound No low priority messages available to evict.
GetSendQueue()
const PriorityQueue& GetSendQueue (void) const inline
This method returns a reference to the send queue.
Returns
A reference to the send queue.
GetReassemblyQueue()
const MessageQueue& GetReassemblyQueue (void) const inline
This method returns a reference to the reassembly queue.
Returns
A reference to the reassembly queue.
GetCounters()
const otIpCounters& GetCounters (void) const inline
This method returns a reference to the IP level counters.
Returns
A reference to the IP level counters.
ResetCounters()
void ResetCounters (void) inline
This method resets the IP level counters.
Referenced by MeshForwarder::MeshForwarder().
SendIcmpErrorIfDstUnreach()
void SendIcmpErrorIfDstUnreach (const Message & aMessage, const Mac::Addresses & aMacAddrs) private
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
CheckReachability()
Error CheckReachability (const FrameData & aFrameData, const Mac::Addresses & aMeshAddrs) private
UpdateRoutes()
void UpdateRoutes (const FrameData & aFrameData, const Mac::Addresses & aMeshAddrs) private
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
FrameToMessage()
Error FrameToMessage (const FrameData & aFrameData, uint16_t aDatagramSize, const Mac::Addresses & aMacAddrs, Message *& aMessage) private
References Message::AppendData(), MeshForwarder::GetFramePriority(), Data< kDataLengthType >::GetLength(), ot::kErrorNoBufs, ot::kErrorNone, Message::kTypeIp6, Message::MoveOffset(), SuccessOrExit, and VerifyOrExit.
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
GetMacDestinationAddress()
void GetMacDestinationAddress (const Ip6::Address & aIp6Addr, Mac::Address & aMacAddr) private
References InterfaceIdentifier::ConvertToMacAddress(), Address::GetIid(), InterfaceIdentifier::GetLocator(), Address::IsMulticast(), ot::Mac::kShortAddrBroadcast, and Address::SetShort().
Referenced by MeshForwarder::UpdateIp6Route().
GetMacSourceAddress()
void GetMacSourceAddress (const Ip6::Address & aIp6Addr, Mac::Address & aMacAddr) private
References InterfaceIdentifier::ConvertToMacAddress(), Address::GetExtended(), Address::GetIid(), and Address::SetShort().
Referenced by MeshForwarder::UpdateIp6Route().
PrepareNextDirectTransmission()
Message * PrepareNextDirectTransmission (void) private
References PriorityQueue::DequeueAndFree(), ExitNow, PriorityQueue::GetHead(), Message::GetNext(), Message::GetType(), Message::IsDirectTransmission(), Message::IsResolvingAddress(), ot::kErrorAddressQuery, ot::kErrorDrop, ot::kErrorNone, MeshForwarder::kMessageDrop, Message::kType6lowpan, Message::kTypeIp6, Message::kTypeMacEmptyData, MeshForwarder::LogMessage(), MeshForwarder::mSendQueue, Message::SetDoNotEvict(), Message::SetResolvingAddress(), MeshForwarder::UpdateIp6Route(), and MeshForwarder::UpdateMeshRoute().
Referenced by MeshForwarder::ScheduleTransmissionTask().
HandleMesh()
void HandleMesh (FrameData & aFrameData, const Mac::Address & aMacSource, const ThreadLinkInfo & aLinkInfo) private
Referenced by MeshForwarder::HandleReceivedFrame().
HandleFragment()
void HandleFragment (FrameData & aFrameData, const Mac::Addresses & aMacAddrs, const ThreadLinkInfo & aLinkInfo) private
References Message::AddRss(), MeshForwarder::ClearReassemblyList(), MessageQueue::Dequeue(), MessageQueue::Enqueue(), MeshForwarder::FrameToMessage(), FreeMessage, FragmentHeader::GetDatagramOffset(), FragmentHeader::GetDatagramSize(), FragmentHeader::GetDatagramTag(), Data< kDataLengthType >::GetLength(), Message::GetLength(), ThreadLinkInfo::GetLqi(), Message::GetOffset(), ThreadLinkInfo::GetRss(), MeshForwarder::GetRxOnWhenIdle(), MeshForwarder::HandleDatagram(), IgnoreError(), ThreadLinkInfo::IsLinkSecurityEnabled(), Message::IsLinkSecurityEnabled(), ot::kErrorDrop, ot::kErrorDuplicated, ot::kErrorNone, ot::kErrorParse, Neighbor::kInStateAnyExceptInvalid, TimeTicker::kMeshForwarder, MeshForwarder::LogFragmentFrameDrop(), otThreadLinkInfo::mLinkSecurity, Message::MoveOffset(), MeshForwarder::mReassemblyList, Addresses::mSource, FragmentHeader::ParseFrom(), MeshForwarder::SendIcmpErrorIfDstUnreach(), Message::SetDatagramTag(), Message::SetLength(), Message::SetLinkInfo(), Message::SetTimestampToNow(), SuccessOrExit, MeshForwarder::UpdateRoutes(), VerifyOrExit, and Message::WriteData().
Referenced by MeshForwarder::HandleReceivedFrame().
HandleLowpanHC()
void HandleLowpanHC (const FrameData & aFrameData, const Mac::Addresses & aMacAddrs, const ThreadLinkInfo & aLinkInfo) private
References MeshForwarder::FrameToMessage(), FreeMessage, Data< kDataLengthType >::GetLength(), MeshForwarder::HandleDatagram(), IgnoreError(), ThreadLinkInfo::IsLinkSecurityEnabled(), ot::kErrorDrop, ot::kErrorNone, MeshForwarder::LogLowpanHcFrameDrop(), Addresses::mSource, MeshForwarder::SendIcmpErrorIfDstUnreach(), Message::SetLinkInfo(), SuccessOrExit, MeshForwarder::UpdateRoutes(), and VerifyOrExit.
Referenced by MeshForwarder::HandleReceivedFrame().
PrepareDataFrame()
uint16_t PrepareDataFrame (Mac::TxFrame & aFrame, Message & aMessage, const Mac::Addresses & aMacAddrs, bool aAddMeshHeader = false, uint16_t aMeshSource = 0xffff, uint16_t aMeshDest = 0xffff, bool aAddFragHeader = false) private
References FrameBuilder::Append(), FrameBuilder::AppendBytesFromMessage(), MeshForwarder::CalcFrameVersion(), MeshForwarder::CalcIePresent(), Message::GetChannel(), Message::GetDatagramTag(), Frame::GetFcsSize(), Frame::GetFooterLength(), Frame::GetHeaderLength(), FrameBuilder::GetLength(), Message::GetLength(), FrameBuilder::GetMaxLength(), Frame::GetMaxPayloadLength(), Message::GetOffset(), Message::GetPanId(), Frame::GetPayload(), FrameBuilder::GetRemainingLength(), Message::GetSubType(), IgnoreError(), FrameBuilder::Init(), FragmentHeader::FirstFrag::Init(), FragmentHeader::NextFrag::Init(), Frame::InitMacHeader(), FrameBuilder::Insert(), Mle::IsActiveRouter(), Address::IsBroadcast(), Frame::IsDstPanIdPresent(), Address::IsExtended(), Message::IsLinkSecurityEnabled(), Address::IsShort(), Message::IsSubTypeMle(), MeshHeader::kAdditionalHopsLeft, Frame::kFcfAckRequest, Frame::kFcfDstAddrExt, Frame::kFcfDstAddrMask, Frame::kFcfDstAddrShort, Frame::kFcfFrameData, Frame::kFcfFrameVersion2006, Frame::kFcfFrameVersion2015, Frame::kFcfFrameVersionMask, Frame::kFcfIePresent, Frame::kFcfPanidCompression, Frame::kFcfSecurityEnabled, Frame::kFcfSrcAddrExt, Frame::kFcfSrcAddrMask, Frame::kFcfSrcAddrShort, Frame::kKeyIdMode0, Frame::kKeyIdMode1, Frame::kKeyIdMode2, ot::Mle::kMaxRouteCost, MeshForwarder::kMeshHeaderFrameFcsSize, MeshForwarder::kMeshHeaderFrameMtu, ot::Mac::kPanIdBroadcast, Frame::kSecEncMic32, Frame::kSecNone, Message::kSubTypeJoinerEntrust, Message::kSubTypeMleAnnounce, Message::kSubTypeMleDiscoverRequest, Message::kSubTypeMleDiscoverResponse, Addresses::mDestination, MeshForwarder::mFragTag, Addresses::mSource, Mle::RouterIdFromRloc16(), Frame::SetChannel(), Message::SetDatagramTag(), Frame::SetDstAddr(), Frame::SetDstPanId(), Frame::SetFramePending(), Message::SetLinkSecurityEnabled(), FrameBuilder::SetMaxLength(), Message::SetOffset(), Frame::SetPayloadLength(), Address::SetShort(), Frame::SetSrcAddr(), Frame::SetSrcPanId(), and SuccessOrAssert.
Referenced by MeshForwarder::HandleFrameRequest().
PrepareEmptyFrame()
void PrepareEmptyFrame (Mac::TxFrame & aFrame, const Mac::Address & aMacDest, bool aAckRequest) private
References MeshForwarder::CalcFrameVersion(), MeshForwarder::CalcIePresent(), IgnoreError(), Frame::InitMacHeader(), Frame::IsDstPanIdPresent(), Address::IsExtended(), Address::IsShort(), Address::IsShortAddrInvalid(), Frame::kFcfAckRequest, Frame::kFcfDstAddrExt, Frame::kFcfDstAddrShort, Frame::kFcfFrameData, Frame::kFcfIePresent, Frame::kFcfPanidCompression, Frame::kFcfSecurityEnabled, Frame::kFcfSrcAddrExt, Frame::kFcfSrcAddrShort, Frame::kKeyIdMode1, Frame::kSecEncMic32, Frame::SetDstAddr(), Frame::SetDstPanId(), Address::SetExtended(), Frame::SetFramePending(), Frame::SetPayloadLength(), Address::SetShort(), Frame::SetSrcAddr(), and Frame::SetSrcPanId().
Referenced by MeshForwarder::HandleFrameRequest().
SendMesh()
void SendMesh (Message & aMessage, Mac::TxFrame & aFrame) private
Referenced by MeshForwarder::HandleFrameRequest().
SendDestinationUnreachable()
void SendDestinationUnreachable (uint16_t aMeshSource, const Ip6::Headers & aIp6Headers) private
UpdateIp6Route()
Error UpdateIp6Route (Message & aMessage) private
References ExitNow, Header::GetDestination(), MeshForwarder::GetMacDestinationAddress(), MeshForwarder::GetMacSourceAddress(), Header::GetSource(), IgnoreError(), Address::IsLinkLocal(), Address::IsLinkLocalMulticast(), Message::IsLinkSecurityEnabled(), Address::IsMulticast(), Message::IsSubTypeMle(), ot::kErrorDrop, ot::kErrorNone, ot::Mac::kShortAddrBroadcast, MeshForwarder::mAddMeshHeader, Addresses::mDestination, MeshForwarder::mMacAddrs, Addresses::mSource, OT_ASSERT, Message::Read(), Address::SetShort(), MeshForwarder::UpdateIp6RouteFtd(), and VerifyOrExit.
Referenced by MeshForwarder::PrepareNextDirectTransmission().
UpdateIp6RouteFtd()
Error UpdateIp6RouteFtd (Ip6::Header & ip6Header, Message & aMessage) private
Referenced by MeshForwarder::UpdateIp6Route().
EvaluateRoutingCost()
void EvaluateRoutingCost (uint16_t aDest, uint8_t & aBestCost, uint16_t & aBestDest) const private
AnycastRouteLookup()
Error AnycastRouteLookup (uint8_t aServiceId, AnycastType aType, uint16_t & aMeshDest) const private
UpdateMeshRoute()
Error UpdateMeshRoute (Message & aMessage) private
Referenced by MeshForwarder::PrepareNextDirectTransmission().
UpdateReassemblyList()
bool UpdateReassemblyList (void) private
References TimerMilli::GetNow(), ot::kErrorReassemblyTimeout, MeshForwarder::kMessageReassemblyDrop, MeshForwarder::kReassemblyTimeout, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mIpCounters, MeshForwarder::mReassemblyList, otIpCounters::mRxFailure, and Time::SecToMsec().
Referenced by MeshForwarder::HandleTimeTick().
UpdateFragmentPriority()
void UpdateFragmentPriority (Lowpan::FragmentHeader & aFragmentHeader, uint16_t aFragmentLength, uint16_t aSrcRloc16, Message::Priority aPriority) private
HandleDatagram()
Error HandleDatagram (Message & aMessage, const ThreadLinkInfo & aLinkInfo, const Mac::Address & aMacSource) private
References Message::GetType(), ot::kErrorNone, Ip6::kFromThreadNetif, MeshForwarder::kMessageReceive, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mIpCounters, and otIpCounters::mRxSuccess.
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
ClearReassemblyList()
void ClearReassemblyList (void) private
References ot::kErrorNoFrameReceived, MeshForwarder::kMessageReassemblyDrop, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mIpCounters, MeshForwarder::mReassemblyList, and otIpCounters::mRxFailure.
Referenced by MeshForwarder::HandleFragment().
RemoveMessage()
void RemoveMessage (Message & aMessage) private
References PriorityQueue::DequeueAndFree(), Message::GetPriorityQueue(), IgnoreError(), ot::kErrorNoBufs, MeshForwarder::kMessageEvict, MeshForwarder::LogMessage(), MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, and OT_ASSERT.
HandleDiscoverComplete()
void HandleDiscoverComplete (void) private
HandleReceivedFrame()
void HandleReceivedFrame (Mac::RxFrame & aFrame) private
References Frame::GetDstAddr(), Data< kDataLengthType >::GetLength(), Frame::GetPayload(), Frame::GetPayloadLength(), Frame::GetSrcAddr(), Frame::GetType(), MeshForwarder::HandleFragment(), MeshForwarder::HandleLowpanHC(), MeshForwarder::HandleMesh(), Data< kDataLengthType >::Init(), FragmentHeader::IsFragmentHeader(), ThreadLinkInfo::IsLinkSecurityEnabled(), Lowpan::IsLowpanHc(), MeshHeader::IsMeshHeader(), ot::kErrorDrop, ot::kErrorInvalidState, ot::kErrorNone, ot::kErrorNotLowpanDataFrame, Frame::kFcfFrameBeacon, Frame::kFcfFrameData, MeshForwarder::LogFrame(), Addresses::mDestination, MeshForwarder::mEnabled, Addresses::mSource, ThreadLinkInfo::SetFrom(), SuccessOrExit, and VerifyOrExit.
HandleFrameRequest()
Mac::TxFrame * HandleFrameRequest (Mac::TxFrames & aTxFrames) private
References ExitNow, Message::GetLength(), Message::GetSubType(), Message::GetType(), Message::IsLinkSecurityEnabled(), Message::IsSubTypeMle(), Message::kSubTypeMleChildIdRequest, Message::kSubTypeMleDiscoverRequest, Message::kType6lowpan, Message::kTypeIp6, Message::kTypeMacEmptyData, Message::kTypeSupervision, LogNote, MeshForwarder::mAddMeshHeader, Addresses::mDestination, MeshForwarder::mEnabled, MeshForwarder::mMacAddrs, MeshForwarder::mMeshDest, MeshForwarder::mMeshSource, MeshForwarder::mMessageNextOffset, MeshForwarder::mSendBusy, MeshForwarder::mSendMessage, OT_FALL_THROUGH, MeshForwarder::PrepareDataFrame(), MeshForwarder::PrepareEmptyFrame(), MeshForwarder::SendMesh(), TxFrame::SetIsARetransmission(), Message::SetLinkSecurityEnabled(), Address::SetShort(), and VerifyOrExit.
UpdateNeighborOnSentFrame()
Neighbor * UpdateNeighborOnSentFrame (Mac::TxFrame & aFrame, Error aError, const Mac::Address & aMacDest, bool aIsDataPoll = false) private
References Frame::GetAckRequest(), ot::kErrorNone, CslIe::kHeaderIeId, MeshForwarder::mEnabled, OT_UNUSED_VARIABLE, MeshForwarder::UpdateNeighborLinkFailures(), and VerifyOrExit.
Referenced by MeshForwarder::HandleSentFrame().
UpdateNeighborLinkFailures()
void UpdateNeighborLinkFailures (Neighbor & aNeighbor, Error aError, bool aAllowNeighborRemove, uint8_t aFailLimit = Mle::kFailedRouterTransmissions) private
References String< kSize >::AsCString(), Neighbor::GetExtAddress(), Neighbor::GetLinkFailures(), Neighbor::GetRloc16(), Neighbor::IncrementLinkFailures(), Mle::IsActiveRouter(), ot::kErrorNoAck, ot::kErrorNone, LogInfo, MeshForwarder::mEnabled, Neighbor::ResetLinkFailures(), ExtAddress::ToString(), and VerifyOrExit.
Referenced by MeshForwarder::UpdateNeighborOnSentFrame().
HandleSentFrame()
void HandleSentFrame (Mac::TxFrame & aFrame, Error aError) private
References Frame::GetDstAddr(), IgnoreError(), Frame::IsEmpty(), ot::kErrorAbort, ot::kErrorChannelAccessFailure, ot::kErrorNoAck, ot::kErrorNone, MeshForwarder::kTxDelayInterval, LogDebg, MeshForwarder::mEnabled, MeshForwarder::mSendBusy, OT_ASSERT, MeshForwarder::UpdateNeighborOnSentFrame(), MeshForwarder::UpdateSendMessage(), and VerifyOrExit.
UpdateSendMessage()
void UpdateSendMessage (Error aFrameTxError, Mac::Address & aMacDest, Neighbor * aNeighbor) private
References LinkQualityInfo::AddMessageTxStatus(), Message::ClearDirectTransmission(), ExitNow, Message::GetLength(), Neighbor::GetLinkInfo(), Message::GetSubType(), Message::GetTxSuccess(), Message::GetType(), Message::IsDirectTransmission(), Message::IsLinkSecurityEnabled(), ot::kErrorFailed, ot::kErrorNone, MeshForwarder::kMessageTransmit, Message::kSubTypeMleChildIdRequest, Message::kSubTypeMleDiscoverRequest, Message::kTypeIp6, LogInfo, MeshForwarder::LogMessage(), MeshForwarder::mIpCounters, MeshForwarder::mMessageNextOffset, MeshForwarder::mScheduleTransmissionTask, MeshForwarder::mSendMessage, otIpCounters::mTxFailure, otIpCounters::mTxSuccess, OT_ASSERT, Tasklet::Post(), MeshForwarder::RemoveMessageIfNoPendingTx(), Message::SetOffset(), Message::SetTxSuccess(), and VerifyOrExit.
Referenced by MeshForwarder::HandleSentFrame().
RemoveMessageIfNoPendingTx()
void RemoveMessageIfNoPendingTx (Message & aMessage) private
References PriorityQueue::DequeueAndFree(), Message::IsChildPending(), Message::IsDirectTransmission(), MeshForwarder::mMessageNextOffset, MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, and VerifyOrExit.
Referenced by MeshForwarder::ResumeMessageTransmissions(), and MeshForwarder::UpdateSendMessage().
HandleTimeTick()
void HandleTimeTick (void) private
References TimeTicker::kMeshForwarder, and MeshForwarder::UpdateReassemblyList().
ScheduleTransmissionTask() [1/2]
void ScheduleTransmissionTask (Tasklet & aTasklet) static private
References GetProvider< InstanceGetProvider >::Get(), and MeshForwarder::ScheduleTransmissionTask().
ScheduleTransmissionTask() [2/2]
void ScheduleTransmissionTask (void) private
References Message::GetOffset(), MeshForwarder::mSendBusy, MeshForwarder::mSendMessage, MeshForwarder::mTxPaused, MeshForwarder::PrepareNextDirectTransmission(), Message::SetTxSuccess(), and VerifyOrExit.
Referenced by MeshForwarder::ScheduleTransmissionTask().
GetFramePriority()
Error GetFramePriority (const FrameData & aFrameData, const Mac::Addresses & aMacAddrs, Message::Priority & aPriority) private
References Headers::DecompressFrom(), Ip6::DscpToPriority(), ot::ErrorToString(), FreeMessageOnError, Udp::Header::GetDestinationPort(), Header::GetDscp(), Headers::GetIcmpHeader(), InstanceLocator::GetInstance(), Headers::GetIp6Header(), MeshForwarder::GetRxOnWhenIdle(), Headers::GetUdpHeader(), Icmp::Header::IsError(), Headers::IsIcmp6(), Headers::IsUdp(), ot::kErrorInvalidState, ot::kErrorNoBufs, ot::kErrorNone, Message::kPriorityNet, Message::kTypeMacEmptyData, ot::Tmf::kUdpPort, ot::Mle::kUdpPort, LogDebg, MeshForwarder::mEnabled, MeshForwarder::SendMessage(), SuccessOrExit, and VerifyOrExit.
Referenced by MeshForwarder::FrameToMessage().
GetFragmentPriority()
Error GetFragmentPriority (Lowpan::FragmentHeader & aFragmentHeader, uint16_t aSrcRloc16, Message::Priority & aPriority) private
GetForwardFramePriority()
void GetForwardFramePriority (const FrameData & aFrameData, const Mac::Addresses & aMeshAddrs, Message::Priority & aPriority) private
CalcIePresent()
bool CalcIePresent (const Message * aMessage) private
References Message::GetLength(), Frame::GetType(), IgnoreError(), Message::IsTimeSync(), Frame::kFcfFrameMacCmd, otRadioFrame::mInfo, otRadioFrame::mTxInfo, and OT_UNUSED_VARIABLE.
Referenced by MeshForwarder::PrepareDataFrame(), and MeshForwarder::PrepareEmptyFrame().
CalcFrameVersion()
uint16_t CalcFrameVersion (const Neighbor * aNeighbor, bool aIePresent) private
References String< kSize >::AsCString(), Ip6::EcnToString(), ot::ErrorToString(), Headers::GetChecksum(), FragmentHeader::GetDatagramOffset(), FragmentHeader::GetDatagramSize(), FragmentHeader::GetDatagramTag(), Headers::GetDestinationAddress(), Headers::GetDestinationPort(), Headers::GetEcn(), Headers::GetIpProto(), Message::GetLength(), Instance::GetLogLevel(), Message::GetPriority(), Neighbor::GetRloc16(), Message::GetRssAverager(), Headers::GetSourceAddress(), Headers::GetSourcePort(), Message::GetType(), Ip6::IpProtoToString(), Message::IsLinkSecurityEnabled(), ot::kErrorNone, Frame::kFcfFrameVersion2006, Frame::kFcfFrameVersion2015, ot::kLogLevelInfo, ot::kLogLevelNote, MeshForwarder::kMessageDrop, MeshForwarder::kMessageEvict, MeshForwarder::kMessagePrepareIndirect, MeshForwarder::kMessageReassemblyDrop, MeshForwarder::kMessageReceive, MeshForwarder::kMessageTransmit, Message::kType6lowpan, Message::kTypeIp6, LogAt, MeshForwarder::LogFragmentFrameDrop(), MeshForwarder::LogFrame(), LogInfo, MeshForwarder::LogLowpanHcFrameDrop(), MeshForwarder::LogMessage(), LogNote, Addresses::mDestination, Addresses::mSource, OT_UNUSED_VARIABLE, Headers::ParseFrom(), Message::PriorityToString(), SuccessOrExit, Frame::ToInfoString(), RssAverager::ToString(), Address::ToString(), ot::ToYesNo(), and VerifyOrExit.
Referenced by MeshForwarder::PrepareDataFrame(), and MeshForwarder::PrepareEmptyFrame().
PauseMessageTransmissions()
void PauseMessageTransmissions (void) inline private
References ot::kErrorNone.
ResumeMessageTransmissions()
void ResumeMessageTransmissions (void) private
References Message::ClearDirectTransmission(), ExitNow, GetProvider< InstanceGetProvider >::Get(), FragmentHeader::GetDatagramOffset(), FragmentHeader::GetDatagramSize(), FragmentHeader::GetDatagramTag(), Header::GetEcn(), PriorityQueue::GetHead(), Message::GetLength(), Message::GetNext(), TimerMilli::GetNow(), Message::GetOffset(), Header::GetSource(), MeshHeader::GetSource(), Message::GetTimestamp(), Message::GetType(), IgnoreError(), Message::IsDirectTransmission(), ot::Ip6::kEcnCapable0, ot::Ip6::kEcnCapable1, ot::Ip6::kEcnMarked, ot::Ip6::kEcnNotCapable, ot::kErrorDrop, ot::kErrorNone, ot::kErrorNotFound, Message::kType6lowpan, Message::kTypeIp6, Message::kTypeMacEmptyData, Message::kTypeSupervision, LogDebg, MeshForwarder::LogMessage(), MeshForwarder::mScheduleTransmissionTask, MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, MeshForwarder::mTxPaused, OPENTHREAD_CONFIG_MAX_FRAMES_IN_DIRECT_TX_QUEUE, OT_UNUSED_VARIABLE, MeshHeader::ParseFrom(), FragmentHeader::ParseFrom(), Tasklet::Post(), Message::Read(), MeshForwarder::RemoveMessageIfNoPendingTx(), Header::SetEcn(), VerifyOrExit, and Message::Write().
LogMessage()
void LogMessage (MessageAction aAction, const Message & aMessage, Error aError = kErrorNone, const Mac::Address * aAddress = nullptr) private
Referenced by MeshForwarder::CalcFrameVersion(), MeshForwarder::ClearReassemblyList(), MeshForwarder::HandleDatagram(), MeshForwarder::PrepareNextDirectTransmission(), MeshForwarder::RemoveMessage(), MeshForwarder::ResumeMessageTransmissions(), MeshForwarder::UpdateReassemblyList(), and MeshForwarder::UpdateSendMessage().
LogFrame()
void LogFrame (const char * aActionText, const Mac::Frame & aFrame, Error aError) private
Referenced by MeshForwarder::CalcFrameVersion(), and MeshForwarder::HandleReceivedFrame().
LogFragmentFrameDrop()
void LogFragmentFrameDrop (Error aError, uint16_t aFrameLength, const Mac::Addresses & aMacAddrs, const Lowpan::FragmentHeader & aFragmentHeader, bool aIsSecure) private
Referenced by MeshForwarder::CalcFrameVersion(), and MeshForwarder::HandleFragment().
LogLowpanHcFrameDrop()
void LogLowpanHcFrameDrop (Error aError, uint16_t aFrameLength, const Mac::Addresses & aMacAddrs, bool aIsSecure) private
Referenced by MeshForwarder::CalcFrameVersion(), and MeshForwarder::HandleLowpanHC().
Friends And Related Function Documentation
Mac::Mac
friend class Mac::Mac friend
Instance
friend class Instance friend
DataPollSender
friend class DataPollSender friend
IndirectSender
friend class IndirectSender friend
Ip6::Ip6
friend class Ip6::Ip6 friend
Mle::DiscoverScanner
friend class Mle::DiscoverScanner friend
TimeTicker
friend class TimeTicker friend
Field Documentation
kReassemblyTimeout
constexpr uint8_t kReassemblyTimeout = OPENTHREAD_CONFIG_6LOWPAN_REASSEMBLY_TIMEOUT static private
Referenced by MeshForwarder::UpdateReassemblyList().
kMeshHeaderFrameMtu
constexpr uint8_t kMeshHeaderFrameMtu = OT_RADIO_FRAME_MAX_SIZE static private
Referenced by MeshForwarder::PrepareDataFrame().
kMeshHeaderFrameFcsSize
constexpr uint8_t kMeshHeaderFrameFcsSize = sizeof(uint16_t) static private
Referenced by MeshForwarder::PrepareDataFrame().
kTxDelayInterval
constexpr uint32_t kTxDelayInterval = OPENTHREAD_CONFIG_MAC_COLLISION_AVOIDANCE_DELAY_INTERVAL static private
Referenced by MeshForwarder::HandleSentFrame().
mSendQueue
PriorityQueue mSendQueue private
Referenced by MeshForwarder::PrepareNextDirectTransmission(), MeshForwarder::RemoveMessage(), MeshForwarder::RemoveMessageIfNoPendingTx(), MeshForwarder::ResumeMessageTransmissions(), and MeshForwarder::Stop().
mReassemblyList
MessageQueue mReassemblyList private
Referenced by MeshForwarder::ClearReassemblyList(), MeshForwarder::HandleFragment(), MeshForwarder::Stop(), and MeshForwarder::UpdateReassemblyList().
mFragTag
uint16_t mFragTag private
Referenced by MeshForwarder::MeshForwarder(), and MeshForwarder::PrepareDataFrame().
mMessageNextOffset
uint16_t mMessageNextOffset private
Referenced by MeshForwarder::HandleFrameRequest(), MeshForwarder::RemoveMessageIfNoPendingTx(), and MeshForwarder::UpdateSendMessage().
mSendMessage
Message* mSendMessage private
Referenced by MeshForwarder::HandleFrameRequest(), MeshForwarder::RemoveMessage(), MeshForwarder::RemoveMessageIfNoPendingTx(), MeshForwarder::ResumeMessageTransmissions(), MeshForwarder::ScheduleTransmissionTask(), MeshForwarder::Stop(), and MeshForwarder::UpdateSendMessage().
mMacAddrs
Mac::Addresses mMacAddrs private
Referenced by MeshForwarder::HandleFrameRequest(), and MeshForwarder::UpdateIp6Route().
mMeshSource
uint16_t mMeshSource private
Referenced by MeshForwarder::HandleFrameRequest().
mMeshDest
uint16_t mMeshDest private
Referenced by MeshForwarder::HandleFrameRequest().
mAddMeshHeader
bool mAddMeshHeader private
Referenced by MeshForwarder::HandleFrameRequest(), and MeshForwarder::UpdateIp6Route().
mEnabled
bool mEnabled private
Referenced by MeshForwarder::GetFramePriority(), MeshForwarder::HandleFrameRequest(), MeshForwarder::HandleReceivedFrame(), MeshForwarder::HandleSentFrame(), MeshForwarder::Start(), MeshForwarder::Stop(), MeshForwarder::UpdateNeighborLinkFailures(), and MeshForwarder::UpdateNeighborOnSentFrame().
mTxPaused
bool mTxPaused private
Referenced by MeshForwarder::ResumeMessageTransmissions(), and MeshForwarder::ScheduleTransmissionTask().
mSendBusy
bool mSendBusy private
Referenced by MeshForwarder::HandleFrameRequest(), MeshForwarder::HandleSentFrame(), and MeshForwarder::ScheduleTransmissionTask().
mScheduleTransmissionTask
Tasklet mScheduleTransmissionTask private
Referenced by MeshForwarder::ResumeMessageTransmissions(), and MeshForwarder::UpdateSendMessage().
mIpCounters
otIpCounters mIpCounters private
Referenced by MeshForwarder::ClearReassemblyList(), MeshForwarder::HandleDatagram(), MeshForwarder::UpdateReassemblyList(), and MeshForwarder::UpdateSendMessage().
mDataPollSender
DataPollSender mDataPollSender private
Referenced by MeshForwarder::SetRxOnWhenIdle(), and MeshForwarder::Stop().
The documentation for this class was generated from the following files:
mesh_forwarder.hpp
mesh_forwarder.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale