OpenThread: AesCcm Class Reference
AesCcm Class Reference
Core-security
#include <aes_ccm.hpp>
Public Types
enum Mode : uint8_t { kEncrypt, kDecrypt }
Public Member Functions
void Finalize (void *aTag)
uint8_t GetTagLength (void) const
void Header (const void *aHeader, uint32_t aHeaderLength)
template<typename ObjectType >
void Header (const ObjectType &aObject)
void Init (uint32_t aHeaderLength, uint32_t aPlainTextLength, uint8_t aTagLength, const void *aNonce, uint8_t aNonceLength)
void Payload (void *aPlainText, void *aCipherText, uint32_t aLength, Mode aMode)
void Payload (Message &aMessage, uint16_t aOffset, uint16_t aLength, Mode aMode)
void SetKey (const Key &aKey)
void SetKey (const uint8_t *aKey, uint16_t aKeyLength)
void SetKey (const Mac::KeyMaterial &aMacKey)
Static Public Member Functions
static void GenerateNonce (const Mac::ExtAddress &aAddress, uint32_t aFrameCounter, uint8_t aSecurityLevel, uint8_t *aNonce)
Static Public Attributes
static constexpr uint8_t kMaxTagLength = AesEcb::kBlockSize
Maximum tag length (in bytes).
static constexpr uint8_t kMinTagLength = 4
Minimum tag length (in bytes).
static constexpr uint8_t kNonceSize = 13
Size of IEEE 802.15.4 Nonce (in bytes).
Private Attributes
uint8_t mBlock [AesEcb::kBlockSize]
uint16_t mBlockLength
uint8_t mCtr [AesEcb::kBlockSize]
uint16_t mCtrLength
uint8_t mCtrPad [AesEcb::kBlockSize]
AesEcb mEcb
uint32_t mHeaderCur
uint32_t mHeaderLength
uint8_t mNonceLength
uint32_t mPlainTextCur
uint32_t mPlainTextLength
uint8_t mTagLength
Detailed Description
This class implements AES CCM computation.
Member Enumeration Documentation
Mode
enum Mode : uint8_t
This enumeration type represent the encryption vs decryption mode.
Enumerator
kEncrypt
kDecrypt
Member Function Documentation
SetKey() [1/3]
void SetKey (const Key & aKey) inline
This method sets the key.
Parameters
[in] aKey Crypto Key used in AES operation
References AesCcm::Header(), AesCcm::Init(), AesCcm::mEcb, and AesEcb::SetKey().
Referenced by otCryptoAesCcm(), Mle::ProcessMessageSecurity(), RxFrame::ProcessReceiveAesCcm(), TxFrame::ProcessTransmitAesCcm(), and AesCcm::SetKey().
SetKey() [2/3]
void SetKey (const uint8_t * aKey, uint16_t aKeyLength)
This method sets the key.
Parameters
[in] aKey A pointer to the key.
[in] aKeyLength Length of the key in bytes.
References Key::Set(), and AesCcm::SetKey().
SetKey() [3/3]
void SetKey (const Mac::KeyMaterial & aMacKey)
This method sets the key.
Parameters
[in] aMacKey Key Material for AES operation.
References KeyMaterial::ConvertToCryptoKey(), and AesCcm::SetKey().
Init()
void Init (uint32_t aHeaderLength, uint32_t aPlainTextLength, uint8_t aTagLength, const void * aNonce, uint8_t aNonceLength)
This method initializes the AES CCM computation.
Parameters
[in] aHeaderLength Length of header in bytes.
[in] aPlainTextLength Length of plaintext in bytes.
[in] aTagLength Length of tag in bytes (must be even and in [kMinTagLength, kMaxTagLength]).
[in] aNonce A pointer to the nonce.
[in] aNonceLength Length of nonce in bytes.
References AesEcb::Encrypt(), AesCcm::kMaxTagLength, AesCcm::kMinTagLength, AesCcm::mBlock, AesCcm::mBlockLength, AesCcm::mCtr, AesCcm::mCtrLength, AesCcm::mCtrPad, AesCcm::mEcb, AesCcm::mHeaderCur, AesCcm::mHeaderLength, AesCcm::mNonceLength, AesCcm::mPlainTextCur, AesCcm::mPlainTextLength, AesCcm::mTagLength, and OT_ASSERT.
Referenced by otCryptoAesCcm(), Mle::ProcessMessageSecurity(), RxFrame::ProcessReceiveAesCcm(), TxFrame::ProcessTransmitAesCcm(), and AesCcm::SetKey().
Header() [1/2]
void Header (const void * aHeader, uint32_t aHeaderLength)
This method processes the header.
Parameters
[in] aHeader A pointer to the header.
[in] aHeaderLength Length of header in bytes.
References AesEcb::Encrypt(), AesCcm::mBlock, AesCcm::mBlockLength, AesCcm::mEcb, AesCcm::mHeaderCur, AesCcm::mHeaderLength, and OT_ASSERT.
Referenced by AesCcm::Header(), otCryptoAesCcm(), Mle::ProcessMessageSecurity(), RxFrame::ProcessReceiveAesCcm(), TxFrame::ProcessTransmitAesCcm(), and AesCcm::SetKey().
Header() [2/2]
void Header (const ObjectType & aObject) inline
This method processes the header.
Template Parameters
ObjectType The object type.
Parameters
[in] aObject A reference to the object to add to header.
References AesCcm::Header(), and AesCcm::Payload().
Payload() [1/2]
void Payload (void * aPlainText, void * aCipherText, uint32_t aLength, Mode aMode)
This method processes the payload.
Parameters
[in,out] aPlainText A pointer to the plaintext.
[in,out] aCipherText A pointer to the ciphertext.
[in] aLength Payload length in bytes.
[in] aMode Mode to indicate whether to encrypt (kEncrypt) or decrypt (kDecrypt).
References AesEcb::Encrypt(), AesCcm::kEncrypt, AesCcm::mBlock, AesCcm::mBlockLength, AesCcm::mCtr, AesCcm::mCtrLength, AesCcm::mCtrPad, AesCcm::mEcb, AesCcm::mNonceLength, AesCcm::mPlainTextCur, AesCcm::mPlainTextLength, and OT_ASSERT.
Referenced by AesCcm::Header(), otCryptoAesCcm(), AesCcm::Payload(), Mle::ProcessMessageSecurity(), RxFrame::ProcessReceiveAesCcm(), and TxFrame::ProcessTransmitAesCcm().
Payload() [2/2]
void Payload (Message & aMessage, uint16_t aOffset, uint16_t aLength, Mode aMode)
This method processes the payload within a given message.
This method encrypts/decrypts the payload content in place within the aMessage.
Parameters
[in,out] aMessage The message to read from and update.
[in] aOffset The offset in aMessage to start of payload.
[in] aLength Payload length in bytes.
[in] aMode Mode to indicate whether to encrypt (kEncrypt) or decrypt (kDecrypt).
References Message::MutableChunk::GetBytes(), Message::GetFirstChunk(), Data< kDataLengthType >::GetLength(), Message::GetNextChunk(), and AesCcm::Payload().
GetTagLength()
uint8_t GetTagLength (void) const inline
This method returns the tag length in bytes.
Returns
The tag length in bytes.
References AesCcm::Finalize(), AesCcm::GenerateNonce(), and AesCcm::mTagLength.
Finalize()
void Finalize (void * aTag)
This method generates the tag.
Parameters
[out] aTag A pointer to the tag (must have GetTagLength() bytes).
References AesEcb::Encrypt(), AesCcm::mBlock, AesCcm::mCtr, AesCcm::mCtrPad, AesCcm::mEcb, AesCcm::mPlainTextCur, AesCcm::mPlainTextLength, AesCcm::mTagLength, and OT_ASSERT.
Referenced by AesCcm::GetTagLength(), otCryptoAesCcm(), Mle::ProcessMessageSecurity(), RxFrame::ProcessReceiveAesCcm(), and TxFrame::ProcessTransmitAesCcm().
GenerateNonce()
void GenerateNonce (const Mac::ExtAddress & aAddress, uint32_t aFrameCounter, uint8_t aSecurityLevel, uint8_t * aNonce) static
This static method generates IEEE 802.15.4 nonce byte sequence.
Parameters
[in] aAddress An extended address.
[in] aFrameCounter A frame counter.
[in] aSecurityLevel A security level.
[out] aNonce A buffer (with kNonceSize bytes) to place the generated nonce.
References otExtAddress::m8, and ot::Encoding::BigEndian::WriteUint32().
Referenced by AesCcm::GetTagLength(), Mle::ProcessMessageSecurity(), RxFrame::ProcessReceiveAesCcm(), and TxFrame::ProcessTransmitAesCcm().
Field Documentation
kMinTagLength
constexpr uint8_t kMinTagLength = 4 static
Minimum tag length (in bytes).
Referenced by AesCcm::Init().
kMaxTagLength
constexpr uint8_t kMaxTagLength = AesEcb::kBlockSize static
Maximum tag length (in bytes).
Referenced by AesCcm::Init().
kNonceSize
constexpr uint8_t kNonceSize = 13 static
Size of IEEE 802.15.4 Nonce (in bytes).
Referenced by Mle::ProcessMessageSecurity(), RxFrame::ProcessReceiveAesCcm(), and TxFrame::ProcessTransmitAesCcm().
mEcb
AesEcb mEcb private
Referenced by AesCcm::Finalize(), AesCcm::Header(), AesCcm::Init(), AesCcm::Payload(), and AesCcm::SetKey().
mBlock
uint8_t mBlock[AesEcb::kBlockSize] private
Referenced by AesCcm::Finalize(), AesCcm::Header(), AesCcm::Init(), and AesCcm::Payload().
mCtr
uint8_t mCtr[AesEcb::kBlockSize] private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mCtrPad
uint8_t mCtrPad[AesEcb::kBlockSize] private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mHeaderLength
uint32_t mHeaderLength private
Referenced by AesCcm::Header(), and AesCcm::Init().
mHeaderCur
uint32_t mHeaderCur private
Referenced by AesCcm::Header(), and AesCcm::Init().
mPlainTextLength
uint32_t mPlainTextLength private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mPlainTextCur
uint32_t mPlainTextCur private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mBlockLength
uint16_t mBlockLength private
Referenced by AesCcm::Header(), AesCcm::Init(), and AesCcm::Payload().
mCtrLength
uint16_t mCtrLength private
Referenced by AesCcm::Init(), and AesCcm::Payload().
mNonceLength
uint8_t mNonceLength private
Referenced by AesCcm::Init(), and AesCcm::Payload().
mTagLength
uint8_t mTagLength private
Referenced by AesCcm::Finalize(), AesCcm::GetTagLength(), and AesCcm::Init().
The documentation for this class was generated from the following files:
aes_ccm.hpp
aes_ccm.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale