OpenThread: DeviceMode Class Reference
DeviceMode Class Reference
MLE » Core
#include <mle_types.hpp>
Public Types
typedef String< kInfoStringSize > InfoString
typedef otLinkModeConfig ModeConfig
Public Member Functions
DeviceMode (void)=default
DeviceMode (uint8_t aMode)
DeviceMode (ModeConfig aModeConfig)
uint8_t Get (void) const
void Get (ModeConfig &aModeConfig) const
NetworkData::Type GetNetworkDataType (void) const
bool IsFullThreadDevice (void) const
bool IsMinimalEndDevice (void) const
bool IsRxOnWhenIdle (void) const
bool IsValid (void) const
void Set (uint8_t aMode)
void Set (const ModeConfig &aModeConfig)
InfoString ToString (void) const
Public Member Functions inherited from Equatable< DeviceMode >
bool operator== (const DeviceMode &aOther) const
Public Member Functions inherited from Unequatable< DeviceMode >
bool operator!= (const DeviceMode &aOther) const
Static Public Attributes
static constexpr uint16_t kInfoStringSize = 45
String buffer size used for ToString().
static constexpr uint8_t kModeFullNetworkData = 1 << 0
If the device requires the full Network Data.
static constexpr uint8_t kModeFullThreadDevice = 1 << 1
If the device is an FTD.
static constexpr uint8_t kModeReserved = 1 << 2
Set on transmission, ignore on reception.
static constexpr uint8_t kModeRxOnWhenIdle = 1 << 3
If to keep receiver on when not transmitting.
Private Attributes
uint8_t mMode
Detailed Description
This type represents a MLE device mode.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
ModeConfig
typedef otLinkModeConfig ModeConfig
This structure represents an MLE Mode configuration.
Constructor & Destructor Documentation
DeviceMode() [1/3]
DeviceMode (void) default
This is the default constructor for DeviceMode object.
DeviceMode() [2/3]
DeviceMode (uint8_t aMode) inline explicit
This constructor initializes a DeviceMode object from a given mode TLV bitmask.
Parameters
[in] aMode A mode TLV bitmask to initialize the DeviceMode object.
DeviceMode() [3/3]
DeviceMode (ModeConfig aModeConfig) inline explicit
This constructor initializes a DeviceMode object from a given mode configuration structure.
Parameters
[in] aModeConfig A mode configuration to initialize the DeviceMode object.
Member Function Documentation
Get() [1/2]
uint8_t Get (void) const inline
This method gets the device mode as a mode TLV bitmask.
Returns
The device mode as a mode TLV bitmask.
Referenced by Mle::TxMessage::AppendModeTlv(), Mle::SetDeviceMode(), Neighbor::SetDeviceMode(), ChildTableEntry::SetMode(), and Mle::Store().
Set() [1/2]
void Set (uint8_t aMode) inline
This method sets the device mode from a given mode TLV bitmask.
Parameters
[in] aMode A mode TLV bitmask.
Referenced by Mle::Restore().
Get() [2/2]
void Get (ModeConfig & aModeConfig) const
This method gets the device mode as a mode configuration structure.
Parameters
[out] aModeConfig A reference to a mode configuration structure to output the device mode.
References DeviceMode::GetNetworkDataType(), DeviceMode::IsFullThreadDevice(), DeviceMode::IsRxOnWhenIdle(), ot::NetworkData::kFullSet, otLinkModeConfig::mDeviceType, otLinkModeConfig::mNetworkData, and otLinkModeConfig::mRxOnWhenIdle.
Set() [2/2]
void Set (const ModeConfig & aModeConfig)
this method sets the device mode from a given mode configuration structure.
Parameters
[in] aModeConfig A mode configuration structure.
References DeviceMode::kModeFullNetworkData, DeviceMode::kModeFullThreadDevice, DeviceMode::kModeReserved, DeviceMode::kModeRxOnWhenIdle, otLinkModeConfig::mDeviceType, DeviceMode::mMode, otLinkModeConfig::mNetworkData, and otLinkModeConfig::mRxOnWhenIdle.
IsRxOnWhenIdle()
bool IsRxOnWhenIdle (void) const inline
This method indicates whether or not the device is rx-on-when-idle.
Return values
TRUE If the device is rx-on-when-idle (non-sleepy).
FALSE If the device is not rx-on-when-idle (sleepy).
Referenced by DeviceMode::Get(), Mle::IsRxOnWhenIdle(), Neighbor::IsRxOnWhenIdle(), and DeviceMode::ToString().
IsFullThreadDevice()
bool IsFullThreadDevice (void) const inline
This method indicates whether or not the device is a Full Thread Device.
Return values
TRUE If the device is Full Thread Device.
FALSE If the device if not Full Thread Device.
Referenced by DeviceMode::Get(), Mle::IsFullThreadDevice(), Neighbor::IsFullThreadDevice(), Mle::SetDeviceMode(), and DeviceMode::ToString().
GetNetworkDataType()
NetworkData::Type GetNetworkDataType (void) const inline
This method gets the Network Data type (full set or stable subset) that the device requests.
Returns
The Network Data type requested by this device.
References ot::NetworkData::kFullSet, and ot::NetworkData::kStableSubset.
Referenced by DeviceMode::Get(), Mle::GetNetworkDataType(), Neighbor::GetNetworkDataType(), and DeviceMode::ToString().
IsMinimalEndDevice()
bool IsMinimalEndDevice (void) const inline
This method indicates whether or not the device is a Minimal End Device.
Return values
TRUE If the device is a Minimal End Device.
FALSE If the device is not a Minimal End Device.
Referenced by Mle::IsMinimalEndDevice().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the device mode flags are valid.
An FTD which is not rx-on-when-idle (is sleepy) is considered invalid.
Returns
TRUE if , FALSE otherwise.
Return values
TRUE If the device mode flags are valid.
FALSE If the device mode flags are not valid.
Referenced by Mle::SetDeviceMode().
ToString()
DeviceMode::InfoString ToString (void) const
This method converts the device mode into a human-readable string.
Returns
An InfoString object representing the device mode.
References StringWriter::Append(), DeviceMode::GetNetworkDataType(), DeviceMode::IsFullThreadDevice(), DeviceMode::IsRxOnWhenIdle(), ot::NetworkData::kFullSet, and ot::ToYesNo().
Referenced by Mle::SetDeviceMode().
Field Documentation
kModeRxOnWhenIdle
constexpr uint8_t kModeRxOnWhenIdle = 1 << 3 static
If to keep receiver on when not transmitting.
Referenced by Mle::HandleParentResponse(), Mle::Restore(), and DeviceMode::Set().
kModeReserved
constexpr uint8_t kModeReserved = 1 << 2 static
Set on transmission, ignore on reception.
Referenced by DeviceMode::Set().
kModeFullThreadDevice
constexpr uint8_t kModeFullThreadDevice = 1 << 1 static
If the device is an FTD.
Referenced by Mle::HandleParentResponse(), Mle::Restore(), and DeviceMode::Set().
kModeFullNetworkData
constexpr uint8_t kModeFullNetworkData = 1 << 0 static
If the device requires the full Network Data.
Referenced by Mle::HandleParentResponse(), Mle::Restore(), and DeviceMode::Set().
kInfoStringSize
constexpr uint16_t kInfoStringSize = 45 static
String buffer size used for ToString().
mMode
uint8_t mMode private
Referenced by DeviceMode::Set().
The documentation for this class was generated from the following files:
mle_types.hpp
mle_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale