OpenThread: TrickleTimer Class Reference
TrickleTimer Class Reference
Core-timer-trickle
#include <trickle_timer.hpp>
Public Types
typedef void(&) Handler(TrickleTimer &aTimer)
enum Mode : uint8_t { kModeTrickle, kModePlainTimer }
Public Types inherited from Timer
typedef void(&) Handler(Timer &aTimer)
Public Member Functions
Mode GetMode (void) const
void IndicateConsistent (void)
void IndicateInconsistent (void)
bool IsRunning (void) const
void Start (Mode aMode, uint32_t aIntervalMin, uint32_t aIntervalMax, uint16_t aRedundancyConstant=kInfiniteRedundancyConstant)
void Stop (void)
TrickleTimer (Instance &aInstance, Handler aHandler)
Public Member Functions inherited from TimerMilli
void FireAt (TimeMilli aFireTime)
void FireAtIfEarlier (TimeMilli aFireTime)
void Start (uint32_t aDelay)
void StartAt (TimeMilli aStartTime, uint32_t aDelay)
void Stop (void)
TimerMilli (Instance &aInstance, Handler aHandler)
Public Member Functions inherited from Timer
Time GetFireTime (void) const
bool IsRunning (void) const
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Public Member Functions inherited from LinkedListEntry< Timer >
const Timer * GetNext (void) const
Timer * GetNext (void)
void SetNext (Timer *aNext)
Static Public Attributes
static constexpr uint16_t kInfiniteRedundancyConstant = NumericLimits<uint16_t>::kMax
Static Public Attributes inherited from Timer
static const uint32_t kMaxDelay = (Time::kMaxDuration >> 1)
Private Types
enum Phase : uint8_t { kBeforeRandomTime, kAfterRandomTime }
Private Member Functions
void FireAt (void)
void FireAtIfEarlier (void)
void GetFireTime (void)
void HandleEndOfInterval (void)
void HandleEndOfTimeInInterval (void)
void HandleTimer (void)
void StartAt (void)
void StartNewInterval (void)
Static Private Member Functions
static void HandleTimer (Timer &aTimer)
Private Attributes
uint16_t mCounter
Handler mHandler
uint32_t mInterval
uint32_t mIntervalMax
uint32_t mIntervalMin
Mode mMode
Phase mPhase
uint16_t mRedundancyConstant
uint32_t mTimeInInterval
Additional Inherited Members
Static Public Member Functions inherited from TimerMilli
static TimeMilli GetNow (void)
Protected Member Functions inherited from Timer
bool DoesFireBefore (const Timer &aSecondTimer, Time aNow) const
void Fired (void)
Timer (Instance &aInstance, Handler aHandler)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Static Protected Member Functions inherited from TimerMilli
static void RemoveAll (Instance &aInstance)
Protected Attributes inherited from Timer
Time mFireTime
Handler mHandler
Timer * mNext
Detailed Description
This class implements a trickle timer.
Member Typedef Documentation
Handler
typedef void(&) Handler(TrickleTimer &aTimer)
This function pointer is called when the timer expires (i.e., transmission should happen).
Parameters
[in] aTimer A reference to the trickle timer.
Member Enumeration Documentation
Mode
enum Mode : uint8_t
This enumeration defines the modes of operation for the TrickleTimer.
Enumerator
kModeTrickle
Operate as the normal trickle logic (as per RFC 6206).
kModePlainTimer
Operate as a plain periodic timer with random interval selected within min/max intervals.
Phase
enum Phase : uint8_t private
Enumerator
kBeforeRandomTime
kAfterRandomTime
Constructor & Destructor Documentation
TrickleTimer()
TrickleTimer (Instance & aInstance, Handler aHandler)
This constructor initializes a TrickleTimer instance.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aHandler A handler which is called when transmission should occur.
Member Function Documentation
IsRunning()
bool IsRunning (void) const inline
This method indicates whether or not the trickle timer instance is running.
Return values
TRUE If the trickle timer is running.
FALSE If the trickle timer is not running.
References Timer::IsRunning().
Referenced by TrickleTimer::IndicateInconsistent().
GetMode()
Mode GetMode (void) const inline
This method gets the current operation mode of the trickle timer.
Returns
The current operation mode of the timer.
References TrickleTimer::mMode, and TrickleTimer::Start().
Start()
void Start (Mode aMode, uint32_t aIntervalMin, uint32_t aIntervalMax, uint16_t aRedundancyConstant = kInfiniteRedundancyConstant)
This method starts the trickle timer.
Parameters
[in] aMode The operation mode of timer (trickle or plain periodic mode).
[in] aIntervalMin The minimum interval for the timer in milliseconds.
[in] aIntervalMax The maximum interval for the timer in milliseconds.
[in] aRedundancyConstant The redundancy constant for the timer, also known as k. The default value is set to kInfiniteRedundancyConstant which disables the suppression behavior (i.e., handler is always invoked independent of number of "consistent" events).
References ot::Random::NonCrypto::GetUint32InRange(), TrickleTimer::mInterval, TrickleTimer::mIntervalMax, TrickleTimer::mIntervalMin, TrickleTimer::mMode, TrickleTimer::mRedundancyConstant, OT_ASSERT, and TrickleTimer::StartNewInterval().
Referenced by TrickleTimer::GetMode().
Stop()
void Stop (void) inline
This method stops the trickle timer.
References TrickleTimer::IndicateConsistent(), TrickleTimer::IndicateInconsistent(), and TimerMilli::Stop().
IndicateConsistent()
void IndicateConsistent (void)
This method indicates to the trickle timer a 'consistent' event.
The 'consistent' events are used to control suppression behavior. The trickle timer keeps track of the number of 'consistent' events in each interval. The timer handler is invoked only if the number of consistent events received in the interval is less than the redundancy constant.
References TrickleTimer::kInfiniteRedundancyConstant, and TrickleTimer::mCounter.
Referenced by TrickleTimer::Stop().
IndicateInconsistent()
void IndicateInconsistent (void)
This method indicates to the trickle timer an 'inconsistent' event.
Receiving an 'inconsistent' event causes the trickle timer to reset (i.e., start with interval set to the min value) unless the current interval being used is already equal to the min interval.
References TrickleTimer::IsRunning(), TrickleTimer::kModeTrickle, TrickleTimer::mInterval, TrickleTimer::mIntervalMin, TrickleTimer::mMode, TrickleTimer::StartNewInterval(), and VerifyOrExit.
Referenced by TrickleTimer::Stop().
StartNewInterval()
void StartNewInterval (void) private
References ot::Random::NonCrypto::GetUint32InRange(), TrickleTimer::kBeforeRandomTime, TrickleTimer::kModePlainTimer, TrickleTimer::kModeTrickle, TrickleTimer::mCounter, TrickleTimer::mInterval, TrickleTimer::mMode, TrickleTimer::mPhase, TrickleTimer::mTimeInInterval, and TimerMilli::Start().
Referenced by TrickleTimer::HandleTimer(), TrickleTimer::IndicateInconsistent(), and TrickleTimer::Start().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References TrickleTimer::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References ExitNow, ot::Random::NonCrypto::GetUint32InRange(), TrickleTimer::kAfterRandomTime, TrickleTimer::kBeforeRandomTime, TrickleTimer::kModePlainTimer, TrickleTimer::kModeTrickle, TrickleTimer::mCounter, TrickleTimer::mHandler, TrickleTimer::mInterval, TrickleTimer::mIntervalMax, TrickleTimer::mIntervalMin, TrickleTimer::mMode, TrickleTimer::mPhase, TrickleTimer::mRedundancyConstant, TrickleTimer::mTimeInInterval, TimerMilli::Start(), TrickleTimer::StartNewInterval(), and VerifyOrExit.
Referenced by TrickleTimer::HandleTimer().
HandleEndOfTimeInInterval()
void HandleEndOfTimeInInterval (void) private
HandleEndOfInterval()
void HandleEndOfInterval (void) private
StartAt()
void StartAt (void) inline private
FireAt()
void FireAt (void) inline private
FireAtIfEarlier()
void FireAtIfEarlier (void) inline private
GetFireTime()
void GetFireTime (void) inline private
Field Documentation
kInfiniteRedundancyConstant
constexpr uint16_t kInfiniteRedundancyConstant = NumericLimits<uint16_t>::kMax static
Special value for redundancy constant (aka k) to indicate infinity (when used, it disables trickle timer's suppression behavior, invoking the handler callback independent of number of "consistent" events).
Referenced by TrickleTimer::IndicateConsistent().
mIntervalMin
uint32_t mIntervalMin private
Referenced by TrickleTimer::HandleTimer(), TrickleTimer::IndicateInconsistent(), and TrickleTimer::Start().
mIntervalMax
uint32_t mIntervalMax private
Referenced by TrickleTimer::HandleTimer(), and TrickleTimer::Start().
mInterval
uint32_t mInterval private
Referenced by TrickleTimer::HandleTimer(), TrickleTimer::IndicateInconsistent(), TrickleTimer::Start(), and TrickleTimer::StartNewInterval().
mTimeInInterval
uint32_t mTimeInInterval private
Referenced by TrickleTimer::HandleTimer(), and TrickleTimer::StartNewInterval().
mRedundancyConstant
uint16_t mRedundancyConstant private
Referenced by TrickleTimer::HandleTimer(), and TrickleTimer::Start().
mCounter
uint16_t mCounter private
Referenced by TrickleTimer::HandleTimer(), TrickleTimer::IndicateConsistent(), and TrickleTimer::StartNewInterval().
mHandler
Handler mHandler private
Referenced by TrickleTimer::HandleTimer().
mMode
Mode mMode private
Referenced by TrickleTimer::GetMode(), TrickleTimer::HandleTimer(), TrickleTimer::IndicateInconsistent(), TrickleTimer::Start(), and TrickleTimer::StartNewInterval().
mPhase
Phase mPhase private
Referenced by TrickleTimer::HandleTimer(), and TrickleTimer::StartNewInterval().
The documentation for this class was generated from the following files:
trickle_timer.hpp
trickle_timer.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale