OpenThread: PtrRecord Class Reference
PtrRecord Class Reference
Core-dns
#include <dns_types.hpp>
Public Member Functions
void Init (uint16_t aClass=kClassInternet)
Error ReadPtrName (const Message &aMessage, uint16_t &aOffset, char *aNameBuffer, uint16_t aNameBufferSize) const
Error ReadPtrName (const Message &aMessage, uint16_t &aOffset, char *aLabelBuffer, uint8_t aLabelBufferSize, char *aNameBuffer, uint16_t aNameBufferSize) const
Public Member Functions inherited from ResourceRecord
uint16_t GetClass (void) const
uint16_t GetLength (void) const
uint32_t GetSize (void) const
uint32_t GetTtl (void) const
uint16_t GetType (void) const
void Init (uint16_t aType, uint16_t aClass=kClassInternet)
bool Matches (uint16_t aType, uint16_t aClass=kClassInternet)
void SetClass (uint16_t aClass)
void SetLength (uint16_t aLength)
void SetTtl (uint32_t aTtl)
void SetType (uint16_t aType)
Static Public Attributes
static constexpr uint16_t kType = kTypePtr
The PTR record type.
Static Public Attributes inherited from ResourceRecord
static constexpr uint16_t kClassAny = 255
Class code Any (ANY).
static constexpr uint16_t kClassInternet = 1
Class code Internet (IN).
static constexpr uint16_t kClassNone = 254
Class code None (NONE) - RFC 2136.
static constexpr uint16_t kTypeA = 1
Address record (IPv4).
static constexpr uint16_t kTypeAaaa = 28
IPv6 address record.
static constexpr uint16_t kTypeAny = 255
ANY record.
static constexpr uint16_t kTypeCname = 5
CNAME record.
static constexpr uint16_t kTypeKey = 25
KEY record.
static constexpr uint16_t kTypeOpt = 41
Option record.
static constexpr uint16_t kTypePtr = 12
PTR record.
static constexpr uint16_t kTypeSig = 24
SIG record.
static constexpr uint16_t kTypeSoa = 6
Start of (zone of) authority.
static constexpr uint16_t kTypeSrv = 33
SRV locator record.
static constexpr uint16_t kTypeTxt = 16
TXT record.
static constexpr uint16_t kTypeZero = 0
Zero as special indicator for the SIG RR (SIG(0) from RFC 2931).
Additional Inherited Members
Static Public Member Functions inherited from ResourceRecord
static Error FindRecord (const Message &aMessage, uint16_t &aOffset, uint16_t &aNumRecords, const Name &aName)
template<class RecordType >
static Error FindRecord (const Message &aMessage, uint16_t &aOffset, uint16_t aNumRecords, uint16_t aIndex, const Name &aName, RecordType &aRecord)
static Error ParseRecords (const Message &aMessage, uint16_t &aOffset, uint16_t aNumRecords)
template<class RecordType >
static Error ReadRecord (const Message &aMessage, uint16_t &aOffset, RecordType &aRecord)
Protected Member Functions inherited from ResourceRecord
Error ReadName (const Message &aMessage, uint16_t &aOffset, uint16_t aStartOffset, char *aNameBuffer, uint16_t aNameBufferSize, bool aSkipRecord) const
Error SkipRecord (const Message &aMessage, uint16_t &aOffset) const
Detailed Description
This class implements Resource Record body format of PTR type.
Member Function Documentation
Init()
void Init (uint16_t aClass = kClassInternet) inline
This method initializes the PTR Resource Record by setting its type and class.
Other record fields (TTL, length) remain unchanged/uninitialized.
Parameters
[in] aClass The class of the resource record (default is kClassInternet).
References ResourceRecord::Init().
ReadPtrName() [1/2]
Error ReadPtrName (const Message & aMessage, uint16_t & aOffset, char * aNameBuffer, uint16_t aNameBufferSize) const inline
This method parses and reads the PTR name from a message.
This method also verifies that the PTR record is well-formed (e.g., the record data length GetLength() matches the PTR encoded name).
Parameters
[in] aMessage The message to read from. aMessage.GetOffset() MUST point to the start of DNS header.
[in,out] aOffset On input, the offset in aMessage to start of PTR name field. On exit when successfully read, aOffset is updated to point to the byte after the entire PTR record (skipping over the record).
[out] aNameBuffer A pointer to a char array to output the read name as a null-terminated C string (MUST NOT be nullptr).
[in] aNameBufferSize The size of aNameBuffer.
Return values
kErrorNone The PTR name was read successfully. aOffset and aNameBuffer are updated.
kErrorParse The PTR record in aMessage could not be parsed (invalid format).
kErrorNoBufs Name could not fit in aNameBufferSize chars.
References OT_TOOL_PACKED_BEGIN, ot::Dns::OT_TOOL_PACKED_END, and ResourceRecord::ReadName().
ReadPtrName() [2/2]
Error ReadPtrName (const Message & aMessage, uint16_t & aOffset, char * aLabelBuffer, uint8_t aLabelBufferSize, char * aNameBuffer, uint16_t aNameBufferSize) const
This method parses and reads the PTR name from a message.
This method also verifies that the PTR record is well-formed (e.g., the record data length GetLength() matches the PTR encoded name).
Unlike the previous method which reads the entire PTR name into a single char buffer, this method reads the first label separately and into a different buffer aLabelBuffer and the rest of the name into aNameBuffer. The aNameBuffer can be set to nullptr if the caller is only interested in the first label. This method is intended for "Service Instance Name" where first label (<Instance> portion) can be a user-friendly string and can contain dot character.
Parameters
[in] aMessage The message to read from. aMessage.GetOffset() MUST point to the start of DNS header.
[in,out] aOffset On input, the offset in aMessage to the start of PTR name field. On exit, when successfully read, aOffset is updated to point to the byte after the entire PTR record (skipping over the record).
[out] aLabelBuffer A pointer to a char array to output the first label as a null-terminated C string (MUST NOT be nullptr).
[in] aLabelBufferSize The size of aLabelBuffer.
[out] aNameBuffer A pointer to a char array to output the rest of name (after first label). Can be nullptr if caller is only interested in the first label.
[in] aNameBufferSize The size of aNameBuffer.
Return values
kErrorNone The PTR name was read successfully. aOffset, and are updated.
kErrorParse The PTR record in aMessage could not be parsed (invalid format).
kErrorNoBufs Either label or name could not fit in the related char buffers.
References ot::kErrorNone, ot::kErrorParse, Name::ParseName(), Name::ReadLabel(), Name::ReadName(), SuccessOrExit, and VerifyOrExit.
Field Documentation
kType
constexpr uint16_t kType = kTypePtr static
The PTR record type.
The documentation for this class was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale