OpenThread: DatasetManager Class Reference
DatasetManager Class Reference
#include <dataset_manager.hpp>
Data Structures
class DatasetTlv
Public Member Functions
Error ApplyConfiguration (void) const
Error GetChannelMask (Mac::ChannelMask &aChannelMask) const
const Timestamp * GetTimestamp (void) const
void HandleDetach (void)
Error Read (Dataset &aDataset) const
Error Read (Dataset::Info &aDatasetInfo) const
Error Read (otOperationalDatasetTlvs &aDataset) const
Error Restore (void)
Error SendGetRequest (const Dataset::Components &aDatasetComponents, const uint8_t *aTlvTypes, uint8_t aLength, const otIp6Address *aAddress) const
Error SendSetRequest (const Dataset::Info &aDatasetInfo, const uint8_t *aTlvs, uint8_t aLength, otDatasetMgmtSetCallback aCallback, void *aContext)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Protected Member Functions
void Clear (void)
DatasetManager (Instance &aInstance, Dataset::Type aType, TimerMilli::Handler aTimerHandler)
Dataset::Type GetType (void) const
void HandleGet (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleNetworkUpdate (void)
void HandleTimer (void)
Error Save (const Dataset &aDataset)
Error Save (const Dataset::Info &aDatasetInfo)
Error Save (const otOperationalDatasetTlvs &aDataset)
Error Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Error SaveLocal (const Dataset &aDataset)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Protected Attributes
DatasetLocal mLocal
Timestamp mTimestamp
bool mTimestampValid: 1
ot::MeshCoP::DatasetManager::DatasetTlv OT_TOOL_PACKED_END
Private Member Functions
Error AppendDatasetToMessage (const Dataset::Info &aDatasetInfo, Message &aMessage) const
void HandleDatasetUpdated (void)
void HandleMgmtSetResponse (Coap::Message *aMessage, const Ip6::MessageInfo *aMessageInfo, Error aError)
bool IsActiveDataset (void) const
bool IsPendingDataset (void) const
void SendGetResponse (const Coap::Message &aRequest, const Ip6::MessageInfo &aMessageInfo, uint8_t *aTlvs, uint8_t aLength) const
void SendSet (void)
void SignalDatasetChange (void) const
Static Private Member Functions
static void HandleMgmtSetResponse (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo, Error aError)
Private Attributes
bool mMgmtPending: 1
otDatasetMgmtSetCallback mMgmtSetCallback
void * mMgmtSetCallbackContext
TimerMilli mTimer
Static Private Attributes
static constexpr uint8_t kMaxDatasetTlvs = 16
static constexpr uint32_t kSendSetDelay = 5000
Constructor & Destructor Documentation
DatasetManager()
DatasetManager (Instance & aInstance, Dataset::Type aType, TimerMilli::Handler aTimerHandler) protected
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aType Dataset type, Active or Pending.
[in] aTimerHandler The registration timer handler.
References Clearable< Type >::Clear(), and DatasetManager::mTimestamp.
Member Function Documentation
GetTimestamp()
const Timestamp * GetTimestamp (void) const
This method returns a pointer to the Timestamp.
Returns
A pointer to the Timestamp.
References DatasetManager::mTimestamp, and DatasetManager::mTimestampValid.
Referenced by DatasetManager::SendSet().
Restore()
Error Restore (void)
This method restores the Operational Dataset from non-volatile memory.
Return values
kErrorNone Successfully restore the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References Dataset::ApplyConfiguration(), InstanceLocator::GetInstance(), Dataset::GetTimestamp(), DatasetManager::GetType(), IgnoreError(), DatasetManager::IsActiveDataset(), ot::kErrorNone, DatasetManager::mLocal, DatasetManager::mTimer, DatasetManager::mTimestamp, DatasetManager::mTimestampValid, DatasetLocal::Restore(), DatasetManager::SignalDatasetChange(), TimerMilli::Stop(), and SuccessOrExit.
Referenced by DatasetManager::HandleDatasetUpdated(), and DatasetManager::HandleDetach().
Read() [1/3]
Error Read (Dataset & aDataset) const inline
This method retrieves the dataset from non-volatile memory.
Parameters
[out] aDataset Where to place the dataset.
Return values
kErrorNone Successfully retrieved the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References DatasetManager::mLocal, and DatasetLocal::Read().
Referenced by DatasetManager::ApplyConfiguration(), DatasetManager::GetChannelMask(), PendingDatasetManager::HandleDelayTimer(), ActiveDatasetManager::IsCommissioned(), DatasetManager::SendGetResponse(), DatasetManager::SendSet(), and PendingDatasetManager::StartDelayTimer().
Read() [2/3]
Error Read (Dataset::Info & aDatasetInfo) const inline
This method retrieves the dataset from non-volatile memory.
Parameters
[out] aDatasetInfo Where to place the dataset (as Dataset::Info).
Return values
kErrorNone Successfully retrieved the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References DatasetManager::mLocal, and DatasetLocal::Read().
Read() [3/3]
Error Read (otOperationalDatasetTlvs & aDataset) const inline
This method retrieves the dataset from non-volatile memory.
Parameters
[out] aDataset Where to place the dataset.
Return values
kErrorNone Successfully retrieved the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References DatasetManager::ApplyConfiguration(), DatasetManager::GetChannelMask(), DatasetManager::HandleDetach(), DatasetManager::mLocal, OT_TOOL_PACKED_BEGIN, DatasetLocal::Read(), DatasetManager::SendGetRequest(), and DatasetManager::SendSetRequest().
GetChannelMask()
Error GetChannelMask (Mac::ChannelMask & aChannelMask) const
This method retrieves the channel mask from local dataset.
Parameters
[out] aChannelMask A reference to the channel mask.
Return values
kErrorNone Successfully retrieved the channel mask.
kErrorNotFound There is no valid channel mask stored in local dataset.
References ChannelMaskTlv::GetChannelMask(), Dataset::GetTlv(), ChannelMask::IsEmpty(), ot::kErrorNotFound, DatasetManager::Read(), ChannelMask::SetMask(), SuccessOrExit, and VerifyOrExit.
Referenced by DatasetManager::Read().
ApplyConfiguration()
Error ApplyConfiguration (void) const
This method applies the Active or Pending Dataset to the Thread interface.
Return values
kErrorNone Successfully applied configuration.
kErrorParse The dataset has at least one TLV with invalid format.
References Dataset::ApplyConfiguration(), InstanceLocator::GetInstance(), DatasetManager::Read(), and SuccessOrExit.
Referenced by DatasetManager::Read().
HandleDetach()
void HandleDetach (void)
This method updates the Operational Dataset when detaching from the network.
On detach, the Operational Dataset is restored from non-volatile memory.
References IgnoreError(), and DatasetManager::Restore().
Referenced by DatasetManager::Read().
SendSetRequest()
Error SendSetRequest (const Dataset::Info & aDatasetInfo, const uint8_t * aTlvs, uint8_t aLength, otDatasetMgmtSetCallback aCallback, void * aContext)
This method sends a MGMT_SET request to the Leader.
Parameters
[in] aDatasetInfo The Operational Dataset.
[in] aTlvs Any additional raw TLVs to include.
[in] aLength Number of bytes in aTlvs.
[in] aCallback A pointer to a function that is called on response reception or timeout.
[in] aContext A pointer to application-specific context for aCallback.
Return values
kErrorNone Successfully send the meshcop dataset command.
kErrorNoBufs Insufficient buffer space to send.
kErrorBusy A previous request is ongoing.
References Message::AppendBytes(), DatasetManager::AppendDatasetToMessage(), FreeMessageOnError, InstanceLocator::GetInstance(), Tlv::GetNext(), DatasetManager::HandleMgmtSetResponse(), IgnoreError(), DatasetManager::IsActiveDataset(), UriPath::kActiveSet, Tlv::kCommissionerSessionId, ot::kErrorBusy, ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, UriPath::kPendingSet, LogInfo, DatasetManager::mMgmtPending, DatasetManager::mMgmtSetCallback, DatasetManager::mMgmtSetCallbackContext, MessageInfo::SetSockAddrToRlocPeerAddrToLeaderAloc(), SuccessOrExit, and VerifyOrExit.
Referenced by DatasetManager::Read().
SendGetRequest()
Error SendGetRequest (const Dataset::Components & aDatasetComponents, const uint8_t * aTlvTypes, uint8_t aLength, const otIp6Address * aAddress) const
This method sends a MGMT_GET request.
Parameters
[in] aDatasetComponents An Operational Dataset components structure specifying components to request.
[in] aTlvTypes A pointer to array containing additional raw TLV types to be requested.
[in] aLength Number of bytes in aTlvTypes.
[in] aAddress The IPv6 destination address for the MGMT_GET request.
Return values
kErrorNone Successfully send the meshcop dataset command.
kErrorNoBufs Insufficient buffer space to send.
References Message::Append(), Message::AppendBytes(), ot::AsCoreType(), FreeMessageOnError, InstanceLocator::GetInstance(), IgnoreError(), DatasetManager::IsActiveDataset(), Dataset::Components::IsActiveTimestampPresent(), Dataset::Components::IsChannelMaskPresent(), Dataset::Components::IsChannelPresent(), Dataset::Components::IsDelayPresent(), Dataset::Components::IsExtendedPanIdPresent(), Dataset::Components::IsMeshLocalPrefixPresent(), Dataset::Components::IsNetworkKeyPresent(), Dataset::Components::IsNetworkNamePresent(), Dataset::Components::IsPanIdPresent(), Dataset::Components::IsPendingTimestampPresent(), Dataset::Components::IsPskcPresent(), Dataset::Components::IsSecurityPolicyPresent(), UriPath::kActiveGet, Tlv::kActiveTimestamp, Tlv::kChannel, Tlv::kChannelMask, Tlv::kDelayTimer, ot::kErrorNoBufs, ot::kErrorNone, Tlv::kExtendedPanId, Tlv::kGet, DatasetManager::kMaxDatasetTlvs, Tlv::kMeshLocalPrefix, Tlv::kNetworkKey, Tlv::kNetworkName, Tlv::kPanId, UriPath::kPendingGet, Tlv::kPendingTimestamp, Tlv::kPskc, Tlv::kSecurityPolicy, LogInfo, Tlv::SetLength(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderAloc(), Tlv::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by DatasetManager::Read().
GetType()
Dataset::Type GetType (void) const inline protected
This method gets the Operational Dataset type (Active or Pending).
Returns
The Operational Dataset type.
References DatasetManager::Clear(), DatasetLocal::GetType(), DatasetManager::HandleGet(), DatasetManager::HandleNetworkUpdate(), DatasetManager::HandleTimer(), DatasetManager::mLocal, DatasetManager::Save(), and DatasetManager::SaveLocal().
Referenced by DatasetManager::Restore(), DatasetManager::Save(), DatasetManager::SendGetResponse(), and DatasetManager::SendSet().
Clear()
void Clear (void) protected
This method clears the Operational Dataset.
References Clearable< Type >::Clear(), DatasetLocal::Clear(), DatasetManager::mLocal, DatasetManager::mTimer, DatasetManager::mTimestamp, DatasetManager::mTimestampValid, DatasetManager::SignalDatasetChange(), and TimerMilli::Stop().
Referenced by ActiveDatasetManager::Clear(), PendingDatasetManager::Clear(), and DatasetManager::GetType().
Save() [1/4]
Error Save (const Dataset & aDataset) protected
This method saves the Operational Dataset in non-volatile memory.
Parameters
[in] aDataset The Operational Dataset.
Return values
kErrorNone Successfully applied configuration.
kErrorParse The dataset has at least one TLV with invalid format.
References Dataset::ApplyConfiguration(), Timestamp::Compare(), InstanceLocator::GetInstance(), DatasetLocal::GetTimestamp(), Dataset::GetTimestamp(), DatasetManager::GetType(), DatasetManager::IsActiveDataset(), ot::kErrorNone, DatasetManager::kSendSetDelay, DatasetManager::mLocal, DatasetManager::mTimer, DatasetManager::mTimestamp, DatasetManager::mTimestampValid, DatasetLocal::Save(), DatasetManager::SignalDatasetChange(), TimerMilli::Start(), and SuccessOrExit.
Referenced by PendingDatasetManager::ClearNetwork(), DatasetManager::GetType(), ActiveDatasetManager::Save(), and PendingDatasetManager::Save().
Save() [2/4]
Error Save (const Dataset::Info & aDatasetInfo) protected
This method saves the Operational Dataset in non-volatile memory.
Parameters
[in] aDatasetInfo The Operational Dataset as Dataset::Info.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References DatasetManager::HandleDatasetUpdated(), DatasetManager::mLocal, DatasetLocal::Save(), and SuccessOrExit.
Save() [3/4]
Error Save (const otOperationalDatasetTlvs & aDataset) protected
This method saves the Operational Dataset in non-volatile memory.
Parameters
[in] aDataset The Operational Dataset.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References DatasetManager::HandleDatasetUpdated(), DatasetManager::mLocal, DatasetLocal::Save(), and SuccessOrExit.
Save() [4/4]
Error Save (const Timestamp & aTimestamp, const Message & aMessage, uint16_t aOffset, uint8_t aLength) protected
This method sets the Operational Dataset for the partition.
This method also updates the non-volatile version if the partition's Operational Dataset is newer.
Parameters
[in] aTimestamp The timestamp for the Operational Dataset.
[in] aMessage The message buffer.
[in] aOffset The offset where the Operational Dataset begins.
[in] aLength The length of the Operational Dataset.
Return values
kErrorNone Successfully parsed the Dataset from the aMessage and saved it.
kErrorParse Could not parse the Dataset from aMessage.
SaveLocal()
Error SaveLocal (const Dataset & aDataset) protected
This method saves the Operational Dataset in non-volatile memory.
Parameters
[in] aDataset The Operational Dataset.
Return values
kErrorNone Successfully applied configuration.
kErrorParse The dataset has at least one TLV with invalid format.
References DatasetManager::HandleDatasetUpdated(), DatasetManager::mLocal, DatasetLocal::Save(), and SuccessOrExit.
Referenced by DatasetManager::GetType(), and PendingDatasetManager::Save().
HandleGet()
void HandleGet (const Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) const protected
This method handles a MGMT_GET request message.
Parameters
[in] aMessage The CoAP message buffer.
[in] aMessageInfo The message info.
References ExitNow, Tlv::GetLength(), Message::GetLength(), Message::GetOffset(), Tlv::GetType(), DatasetManager::IsPendingDataset(), Tlv::kDelayTimer, Tlv::kGet, Dataset::kMaxGetTypes, Message::Read(), Message::ReadBytes(), DatasetManager::SendGetResponse(), SuccessOrExit, and VerifyOrExit.
Referenced by DatasetManager::GetType(), ActiveDatasetManager::HandleGet(), PendingDatasetManager::HandleGet(), ActiveDatasetManager::HandleTimer(), and PendingDatasetManager::HandleTimer().
HandleNetworkUpdate()
void HandleNetworkUpdate (void) protected
This method compares the partition's Operational Dataset with that stored in non-volatile memory.
If the partition's Operational Dataset is newer, the non-volatile storage is updated. If the partition's Operational Dataset is older, the registration process is started.
Referenced by DatasetManager::GetType().
HandleTimer()
void HandleTimer (void) protected
This method initiates a network data registration message with the Leader.
References DatasetManager::SendSet().
Referenced by DatasetManager::GetType(), ActiveDatasetManager::HandleTimer(), PendingDatasetManager::HandleTimer(), and ActiveDatasetManager::Save().
HandleMgmtSetResponse() [1/2]
void HandleMgmtSetResponse (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo, Error aError) static private
References ot::AsCoapMessagePtr(), and ot::AsCoreTypePtr().
Referenced by DatasetManager::SendSet(), and DatasetManager::SendSetRequest().
HandleMgmtSetResponse() [2/2]
void HandleMgmtSetResponse (Coap::Message * aMessage, const Ip6::MessageInfo * aMessageInfo, Error aError) private
References ot::ErrorToString(), Tlv::FindTlv(), StateTlv::GetState(), StateTlv::kAccept, ot::kErrorNone, ot::kErrorParse, ot::kErrorRejected, StateTlv::kReject, DatasetManager::kSendSetDelay, LogInfo, DatasetManager::mMgmtPending, DatasetManager::mMgmtSetCallback, DatasetManager::mMgmtSetCallbackContext, DatasetManager::mTimer, OT_UNUSED_VARIABLE, TimerMilli::Start(), SuccessOrExit, and VerifyOrExit.
IsActiveDataset()
bool IsActiveDataset (void) const inline private
References Tlv::GetType(), and Dataset::kActive.
Referenced by DatasetManager::Restore(), DatasetManager::Save(), DatasetManager::SendGetRequest(), DatasetManager::SendSet(), and DatasetManager::SendSetRequest().
IsPendingDataset()
bool IsPendingDataset (void) const inline private
References DatasetManager::AppendDatasetToMessage(), Tlv::GetType(), DatasetManager::HandleDatasetUpdated(), Dataset::kPending, DatasetManager::SendGetResponse(), DatasetManager::SendSet(), and DatasetManager::SignalDatasetChange().
Referenced by DatasetManager::HandleGet().
SignalDatasetChange()
void SignalDatasetChange (void) const private
References DatasetLocal::GetType(), Dataset::kActive, ot::kEventActiveDatasetChanged, ot::kEventPendingDatasetChanged, and DatasetManager::mLocal.
Referenced by DatasetManager::Clear(), DatasetManager::HandleDatasetUpdated(), DatasetManager::IsPendingDataset(), DatasetManager::Restore(), and DatasetManager::Save().
HandleDatasetUpdated()
void HandleDatasetUpdated (void) private
References IgnoreError(), ot::Mle::kRoleChild, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, DatasetManager::Restore(), DatasetManager::SendSet(), and DatasetManager::SignalDatasetChange().
Referenced by DatasetManager::IsPendingDataset(), DatasetManager::Save(), and DatasetManager::SaveLocal().
AppendDatasetToMessage()
Error AppendDatasetToMessage (const Dataset::Info & aDatasetInfo, Message & aMessage) const private
References Message::AppendBytes(), Dataset::GetBytes(), Dataset::GetSize(), Dataset::SetFrom(), and SuccessOrExit.
Referenced by DatasetManager::IsPendingDataset(), and DatasetManager::SendSetRequest().
SendSet()
void SendSet (void) private
References Message::AppendBytes(), Timestamp::Compare(), ExitNow, FreeMessage, Dataset::GetBytes(), InstanceLocator::GetInstance(), Dataset::GetSize(), DatasetManager::GetTimestamp(), DatasetLocal::GetTimestamp(), Dataset::GetTimestamp(), DatasetManager::GetType(), DatasetManager::HandleMgmtSetResponse(), IgnoreError(), DatasetManager::IsActiveDataset(), Dataset::kActive, UriPath::kActiveSet, ot::kErrorAlready, ot::kErrorBusy, ot::kErrorInvalidState, ot::kErrorNoBufs, ot::kErrorNone, UriPath::kPendingSet, DatasetManager::kSendSetDelay, ot::MeshCoP::LogError(), LogInfo, DatasetManager::mLocal, DatasetManager::mMgmtPending, DatasetManager::mTimer, OT_FALL_THROUGH, DatasetManager::Read(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderAloc(), TimerMilli::Start(), SuccessOrExit, Dataset::TypeToString(), and VerifyOrExit.
Referenced by DatasetManager::HandleDatasetUpdated(), DatasetManager::HandleTimer(), and DatasetManager::IsPendingDataset().
SendGetResponse()
void SendGetResponse (const Coap::Message & aRequest, const Ip6::MessageInfo & aMessageInfo, uint8_t * aTlvs, uint8_t aLength) const private
References Tlv::AppendTo(), String< kSize >::AsCString(), FreeMessageOnError, Tlv::GetNext(), MessageInfo::GetPeerAddr(), Dataset::GetTlv(), Dataset::GetTlvsEnd(), Dataset::GetTlvsStart(), DatasetManager::GetType(), IgnoreError(), Dataset::kActive, ot::kErrorNoBufs, ot::kErrorNone, Tlv::kNetworkKey, LogInfo, DatasetManager::Read(), SuccessOrExit, Address::ToString(), and VerifyOrExit.
Referenced by DatasetManager::HandleGet(), and DatasetManager::IsPendingDataset().
Field Documentation
OT_TOOL_PACKED_END
ot::MeshCoP::DatasetManager::DatasetTlv OT_TOOL_PACKED_END protected
mLocal
DatasetLocal mLocal protected
Referenced by DatasetManager::Clear(), DatasetManager::GetType(), ActiveDatasetManager::IsPartiallyComplete(), DatasetManager::Read(), DatasetManager::Restore(), DatasetManager::Save(), DatasetManager::SaveLocal(), DatasetManager::SendSet(), and DatasetManager::SignalDatasetChange().
mTimestamp
Timestamp mTimestamp protected
Referenced by DatasetManager::Clear(), PendingDatasetManager::ClearNetwork(), DatasetManager::DatasetManager(), DatasetManager::GetTimestamp(), DatasetManager::Restore(), and DatasetManager::Save().
mTimestampValid
bool mTimestampValid protected
Referenced by DatasetManager::Clear(), PendingDatasetManager::ClearNetwork(), DatasetManager::GetTimestamp(), ActiveDatasetManager::IsPartiallyComplete(), DatasetManager::Restore(), and DatasetManager::Save().
kMaxDatasetTlvs
constexpr uint8_t kMaxDatasetTlvs = 16 static private
Referenced by DatasetManager::SendGetRequest().
kSendSetDelay
constexpr uint32_t kSendSetDelay = 5000 static private
Referenced by DatasetManager::HandleMgmtSetResponse(), DatasetManager::Save(), and DatasetManager::SendSet().
mMgmtPending
bool mMgmtPending private
Referenced by DatasetManager::HandleMgmtSetResponse(), DatasetManager::SendSet(), and DatasetManager::SendSetRequest().
mTimer
TimerMilli mTimer private
Referenced by DatasetManager::Clear(), DatasetManager::HandleMgmtSetResponse(), DatasetManager::Restore(), DatasetManager::Save(), and DatasetManager::SendSet().
mMgmtSetCallback
otDatasetMgmtSetCallback mMgmtSetCallback private
Referenced by DatasetManager::HandleMgmtSetResponse(), and DatasetManager::SendSetRequest().
mMgmtSetCallbackContext
void* mMgmtSetCallbackContext private
Referenced by DatasetManager::HandleMgmtSetResponse(), and DatasetManager::SendSetRequest().
The documentation for this class was generated from the following files:
dataset_manager.hpp
dataset_manager.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale