OpenThread: OptionPadN Class Reference
OptionPadN Class Reference
Core-ipv6 » IPv6
#include <ip6_headers.hpp>
Public Member Functions
uint8_t GetTotalLength (void) const
void Init (uint8_t aPadLength)
Public Member Functions inherited from OptionHeader
Action GetAction (void) const
uint8_t GetLength (void) const
uint8_t GetType (void) const
OptionHeader (void)
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Attributes
static constexpr uint8_t kData = 0x00
PadN specific data.
static constexpr uint8_t kMaxLength = 0x05
Maximum length of PadN option data.
static constexpr uint8_t kType = 0x01
PadN type.
Private Attributes
uint8_t mPad [kMaxLength]
Additional Inherited Members
Public Types inherited from OptionHeader
enum Action : uint8_t { kActionSkip = 0x00, kActionDiscard = 0x40, kActionForceIcmp = 0x80, kActionIcmp = 0xc0 }
Detailed Description
This class implements IPv6 PadN Option generation and parsing.
Member Function Documentation
Init()
void Init (uint8_t aPadLength) inline
This method initializes the PadN header.
Parameters
[in] aPadLength The length of needed padding. Allowed value from range 2-7.
Referenced by Ip6::AddMplOption(), Lowpan::DecompressExtensionHeader(), Ip6::InsertMplOption(), and Ip6::RemoveMplOption().
GetTotalLength()
uint8_t GetTotalLength (void) const inline
This method returns the total IPv6 Option Length value including option header.
Returns
The total IPv6 Option Length.
Referenced by Ip6::AddMplOption(), Ip6::InsertMplOption(), and Ip6::RemoveMplOption().
Field Documentation
kType
constexpr uint8_t kType = 0x01 static
PadN type.
Referenced by Lowpan::CompressExtensionHeader(), and Ip6::RemoveMplOption().
kData
constexpr uint8_t kData = 0x00 static
PadN specific data.
kMaxLength
constexpr uint8_t kMaxLength = 0x05 static
Maximum length of PadN option data.
mPad
uint8_t mPad[kMaxLength] private
The documentation for this class was generated from the following file:
ip6_headers.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale