OpenThread: Udp::Header Class Reference
Udp::Header Class Reference
#include <udp6.hpp>
Public Member Functions
uint16_t GetChecksum (void) const
uint16_t GetDestinationPort (void) const
uint16_t GetLength (void) const
uint16_t GetSourcePort (void) const
void SetChecksum (uint16_t aChecksum)
void SetDestinationPort (uint16_t aPort)
void SetLength (uint16_t aLength)
void SetSourcePort (uint16_t aPort)
Public Member Functions inherited from Clearable< Header >
void Clear (void)
Static Public Attributes
static constexpr uint16_t kChecksumFieldOffset = 6
Byte offset of Checksum field in UDP header.
static constexpr uint16_t kDestPortFieldOffset = 2
Byte offset of Destination Port field in UDP header.
static constexpr uint16_t kLengthFieldOffset = 4
Byte offset of Length field in UDP header.
static constexpr uint16_t kSourcePortFieldOffset = 0
Byte offset of Source Port field in UDP header.
Private Attributes
uint16_t mChecksum
uint16_t mDestinationPort
uint16_t mLength
uint16_t mSourcePort
Detailed Description
This class implements UDP header generation and parsing.
Member Function Documentation
GetSourcePort()
uint16_t GetSourcePort (void) const inline
This method returns the UDP Source Port.
Returns
The UDP Source Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::CompressUdp(), and Udp::HandleMessage().
SetSourcePort()
void SetSourcePort (uint16_t aPort) inline
This method sets the UDP Source Port.
Parameters
[in] aPort The UDP Source Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
GetDestinationPort()
uint16_t GetDestinationPort (void) const inline
This method returns the UDP Destination Port.
Returns
The UDP Destination Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::CompressUdp(), MeshForwarder::GetFramePriority(), Udp::HandleMessage(), and Ip6::ProcessReceiveCallback().
SetDestinationPort()
void SetDestinationPort (uint16_t aPort) inline
This method sets the UDP Destination Port.
Parameters
[in] aPort The UDP Destination Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
GetLength()
uint16_t GetLength (void) const inline
This method returns the UDP Length.
Returns
The UDP Length.
References ot::Encoding::BigEndian::HostSwap16().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the UDP Length.
Parameters
[in] aLength The UDP Length.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
GetChecksum()
uint16_t GetChecksum (void) const inline
This method returns the UDP Checksum.
Returns
The UDP Checksum.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::CompressUdp().
SetChecksum()
void SetChecksum (uint16_t aChecksum) inline
This method sets the UDP Checksum.
Parameters
[in] aChecksum The UDP Checksum.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
Field Documentation
kSourcePortFieldOffset
constexpr uint16_t kSourcePortFieldOffset = 0 static
Byte offset of Source Port field in UDP header.
kDestPortFieldOffset
constexpr uint16_t kDestPortFieldOffset = 2 static
Byte offset of Destination Port field in UDP header.
Referenced by Ip6::HandleDatagram().
kLengthFieldOffset
constexpr uint16_t kLengthFieldOffset = 4 static
Byte offset of Length field in UDP header.
Referenced by Lowpan::CompressUdp().
kChecksumFieldOffset
constexpr uint16_t kChecksumFieldOffset = 6 static
Byte offset of Checksum field in UDP header.
Referenced by Checksum::UpdateMessageChecksum().
mSourcePort
uint16_t mSourcePort private
mDestinationPort
uint16_t mDestinationPort private
mLength
uint16_t mLength private
mChecksum
uint16_t mChecksum private
The documentation for this class was generated from the following file:
udp6.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale