OpenThread: LeaderData Class Reference
LeaderData Class Reference
MLE » Core
#include <mle_types.hpp>
Public Member Functions
uint8_t GetDataVersion (NetworkData::Type aType) const
uint8_t GetLeaderRouterId (void) const
uint32_t GetPartitionId (void) const
uint8_t GetWeighting (void) const
void SetDataVersion (uint8_t aVersion)
void SetLeaderRouterId (uint8_t aRouterId)
void SetPartitionId (uint32_t aPartitionId)
void SetStableDataVersion (uint8_t aVersion)
void SetWeighting (uint8_t aWeighting)
Public Member Functions inherited from Clearable< LeaderData >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otLeaderData
uint8_t mDataVersion
Full Network Data Version.
uint8_t mLeaderRouterId
Leader Router ID.
uint32_t mPartitionId
Partition ID.
uint8_t mStableDataVersion
Stable Network Data Version.
uint8_t mWeighting
Leader Weight.
Detailed Description
This class represents the Thread Leader Data.
Member Function Documentation
GetPartitionId()
uint32_t GetPartitionId (void) const inline
This method returns the Partition ID value.
Returns
The Partition ID value.
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), Mle::HandleParentResponse(), LeaderDataTlv::Set(), Mle::SetLeaderData(), and Mle::Store().
SetPartitionId()
void SetPartitionId (uint32_t aPartitionId) inline
This method sets the Partition ID value.
Parameters
[in] aPartitionId The Partition ID value.
Referenced by LeaderDataTlv::Get(), and Mle::SetLeaderData().
GetWeighting()
uint8_t GetWeighting (void) const inline
This method returns the Weighting value.
Returns
The Weighting value.
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), and LeaderDataTlv::Set().
SetWeighting()
void SetWeighting (uint8_t aWeighting) inline
This method sets the Weighting value.
Parameters
[in] aWeighting The Weighting value.
Referenced by LeaderDataTlv::Get(), and Mle::SetLeaderData().
GetDataVersion()
uint8_t GetDataVersion (NetworkData::Type aType) const inline
This method returns the Data Version value for a type (full set or stable subset).
Parameters
[in] aType The Network Data type (full set or stable subset).
Returns
The Data Version value for aType.
References ot::NetworkData::kFullSet.
Referenced by Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), Mle::IsNetworkDataNewer(), and LeaderDataTlv::Set().
SetDataVersion()
void SetDataVersion (uint8_t aVersion) inline
This method sets the Data Version value.
Parameters
[in] aVersion The Data Version value.
Referenced by Mle::TxMessage::AppendLeaderDataTlv(), LeaderDataTlv::Get(), and Mle::GetLeaderData().
SetStableDataVersion()
void SetStableDataVersion (uint8_t aVersion) inline
This method sets the Stable Data Version value.
Parameters
[in] aVersion The Stable Data Version value.
Referenced by Mle::TxMessage::AppendLeaderDataTlv(), LeaderDataTlv::Get(), and Mle::GetLeaderData().
GetLeaderRouterId()
uint8_t GetLeaderRouterId (void) const inline
This method returns the Leader Router ID value.
Returns
The Leader Router ID value.
Referenced by Mle::GetLeaderAddress(), Mle::GetLeaderId(), Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), and LeaderDataTlv::Set().
SetLeaderRouterId()
void SetLeaderRouterId (uint8_t aRouterId) inline
This method sets the Leader Router ID value.
Parameters
[in] aRouterId The Leader Router ID value.
References OT_TOOL_PACKED_BEGIN.
Referenced by LeaderDataTlv::Get(), and Mle::SetLeaderData().
The documentation for this class was generated from the following file:
mle_types.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale