OpenThread: Message Class Reference
Message Class Reference
Core-message
#include <message.hpp>
Data Structures
class Chunk
class ConstIterator
class Iterator
class MutableChunk
class Settings
Public Types
enum LinkSecurityMode : bool { kNoLinkSecurity = false, kWithLinkSecurity = true }
enum Ownership : uint8_t { kTakeCustody, kCopyToUse }
enum Priority : uint8_t { kPriorityLow = OT_MESSAGE_PRIORITY_LOW, kPriorityNormal = OT_MESSAGE_PRIORITY_NORMAL, kPriorityHigh = OT_MESSAGE_PRIORITY_HIGH, kPriorityNet = OT_MESSAGE_PRIORITY_HIGH + 1 }
enum SubType : uint8_t {
kSubTypeNone = 0, kSubTypeMleAnnounce = 1, kSubTypeMleDiscoverRequest = 2, kSubTypeMleDiscoverResponse = 3,
kSubTypeJoinerEntrust = 4, kSubTypeMplRetransmission = 5, kSubTypeMleGeneral = 6, kSubTypeJoinerFinalizeResponse = 7,
kSubTypeMleChildUpdateRequest = 8, kSubTypeMleDataResponse = 9, kSubTypeMleChildIdRequest = 10, kSubTypeMleDataRequest = 11
}
enum Type : uint8_t {
kTypeIp6 = 0, kType6lowpan = 1, kTypeSupervision = 2, kTypeMacEmptyData = 3,
kTypeIp4 = 4, kTypeOther = 5
}
Public Member Functions
void AddRss (int8_t aRss)
template<typename ObjectType >
Error Append (const ObjectType &aObject)
Error AppendBytes (const void *aBuf, uint16_t aLength)
Error AppendBytesFromMessage (const Message &aMessage, uint16_t aOffset, uint16_t aLength)
template<DataLengthType kDataLengthType>
Error AppendData (const Data< kDataLengthType > &aData)
void ClearChildMask (uint16_t aChildIndex)
void ClearDirectTransmission (void)
Message * Clone (uint16_t aLength) const
Message * Clone (void) const
template<typename ObjectType >
bool Compare (uint16_t aOffset, const ObjectType &aObject) const
bool CompareBytes (uint16_t aOffset, const void *aBuf, uint16_t aLength, ByteMatcher aMatcher=nullptr) const
bool CompareBytes (uint16_t aOffset, const Message &aOtherMessage, uint16_t aOtherOffset, uint16_t aLength, ByteMatcher aMatcher=nullptr) const
uint16_t CopyTo (uint16_t aSourceOffset, uint16_t aDestinationOffset, uint16_t aLength, Message &aMessage) const
void Free (void)
int8_t GetAverageRss (void) const
uint8_t GetBufferCount (void) const
uint8_t GetChannel (void) const
bool GetChildMask (uint16_t aChildIndex) const
uint32_t GetDatagramTag (void) const
bool GetDoNotEvict (void) const
Instance & GetInstance (void) const
uint16_t GetLength (void) const
uint16_t GetMeshDest (void) const
MessageQueue * GetMessageQueue (void) const
bool GetMulticastLoop (void) const
Message * GetNext (void) const
uint16_t GetOffset (void) const
uint16_t GetPanId (void) const
Priority GetPriority (void) const
PriorityQueue * GetPriorityQueue (void) const
const RssAverager & GetRssAverager (void) const
SubType GetSubType (void) const
TimeMilli GetTimestamp (void) const
bool GetTxSuccess (void) const
Type GetType (void) const
bool IsChildPending (void) const
bool IsDirectTransmission (void) const
bool IsLinkSecurityEnabled (void) const
bool IsResolvingAddress (void) const
bool IsSubTypeMle (void) const
bool IsTimeSync (void) const
void MoveOffset (int aDelta)
template<typename ObjectType >
Error Prepend (const ObjectType &aObject)
Error PrependBytes (const void *aBuf, uint16_t aLength)
Error Read (uint16_t aOffset, void *aBuf, uint16_t aLength) const
template<typename ObjectType >
Error Read (uint16_t aOffset, ObjectType &aObject) const
uint16_t ReadBytes (uint16_t aOffset, void *aBuf, uint16_t aLength) const
void RemoveHeader (uint16_t aLength)
void SetChannel (uint8_t aChannel)
void SetChildMask (uint16_t aChildIndex)
void SetDatagramTag (uint32_t aTag)
void SetDirectTransmission (void)
void SetDoNotEvict (bool aDoNotEvict)
Error SetLength (uint16_t aLength)
void SetLinkInfo (const ThreadLinkInfo &aLinkInfo)
void SetLinkSecurityEnabled (bool aEnabled)
void SetMeshDest (uint16_t aMeshDest)
void SetMulticastLoop (bool aMulticastLoop)
void SetOffset (uint16_t aOffset)
void SetPanId (uint16_t aPanId)
Error SetPriority (Priority aPriority)
void SetResolvingAddress (bool aResolvingAddress)
void SetSubType (SubType aSubType)
void SetTimestamp (TimeMilli aTimestamp)
void SetTimestampToNow (void)
void SetTxSuccess (bool aTxSuccess)
void SetType (Type aType)
template<typename ObjectType >
void Write (uint16_t aOffset, const ObjectType &aObject)
void WriteBytes (uint16_t aOffset, const void *aBuf, uint16_t aLength)
template<DataLengthType kDataLengthType>
void WriteData (uint16_t aOffset, const Data< kDataLengthType > &aData)
Public Member Functions inherited from Buffer
Buffer * GetNextBuffer (void)
const Buffer * GetNextBuffer (void) const
void SetNextBuffer (Buffer *aNext)
Public Member Functions inherited from LinkedListEntry< Buffer >
const Buffer * GetNext (void) const
Buffer * GetNext (void)
void SetNext (Buffer *aNext)
Public Member Functions inherited from GetProvider< Message >
Type & Get (void) const
Static Public Member Functions
static const char * PriorityToString (Priority aPriority)
Static Public Attributes
static constexpr uint8_t kNumPriorities = 4
Number of priority levels.
Protected Member Functions
uint16_t GetReserved (void) const
void SetReserved (uint16_t aReservedHeader)
Protected Member Functions inherited from Buffer
uint8_t * GetData (void)
const uint8_t * GetData (void) const
uint8_t * GetFirstData (void)
const uint8_t * GetFirstData (void) const
Metadata & GetMetadata (void)
const Metadata & GetMetadata (void) const
Protected Member Functions inherited from GetProvider< Message >
GetProvider (void)=default
Private Member Functions
void GetFirstChunk (uint16_t aOffset, uint16_t &aLength, Chunk &aChunk) const
void GetFirstChunk (uint16_t aOffset, uint16_t &aLength, MutableChunk &aChunk)
MessagePool * GetMessagePool (void) const
void GetNextChunk (uint16_t &aLength, Chunk &aChunk) const
void GetNextChunk (uint16_t &aLength, MutableChunk &aChunk)
bool IsInAQueue (void) const
Message *& Next (void)
Message *const & Next (void) const
Message *& Prev (void)
Error ResizeMessage (uint16_t aLength)
void SetMessagePool (MessagePool *aMessagePool)
void SetMessageQueue (MessageQueue *aMessageQueue)
void SetPriorityQueue (PriorityQueue *aPriorityQueue)
Static Private Member Functions
static Message * NextOf (Message *aMessage)
static const Message * NextOf (const Message *aMessage)
Friends
class Checksum
class Crypto::AesCcm
class Crypto::HmacSha256
class Crypto::Sha256
class MessagePool
class MessageQueue
class PriorityQueue
Additional Inherited Members
Data Fields inherited from otMessageBuffer
struct otMessageBuffer * mNext
Pointer to the next buffer.
Static Protected Attributes inherited from Buffer
static constexpr uint16_t kBufferDataSize = kBufferSize - sizeof(otMessageBuffer)
static constexpr uint16_t kHeadBufferDataSize = kBufferDataSize - sizeof(Metadata)
Detailed Description
This class represents a message.
Member Enumeration Documentation
Type
enum Type : uint8_t
This enumeration represents the message type.
Enumerator
kTypeIp6
A full uncompressed IPv6 packet.
kType6lowpan
A 6lowpan frame.
kTypeSupervision
A child supervision frame.
kTypeMacEmptyData
An empty MAC data frame.
kTypeIp4
A full uncompressed IPv4 packet, for NAT64.
kTypeOther
Other (data) message.
SubType
enum SubType : uint8_t
This enumeration represents the message sub-type.
Enumerator
kSubTypeNone
None.
kSubTypeMleAnnounce
MLE Announce.
kSubTypeMleDiscoverRequest
MLE Discover Request.
kSubTypeMleDiscoverResponse
MLE Discover Response.
kSubTypeJoinerEntrust
Joiner Entrust.
kSubTypeMplRetransmission
MPL next retransmission message.
kSubTypeMleGeneral
General MLE.
kSubTypeJoinerFinalizeResponse
Joiner Finalize Response.
kSubTypeMleChildUpdateRequest
MLE Child Update Request.
kSubTypeMleDataResponse
MLE Data Response.
kSubTypeMleChildIdRequest
MLE Child ID Request.
kSubTypeMleDataRequest
MLE Data Request.
Priority
enum Priority : uint8_t
Enumerator
kPriorityLow
Low priority level.
kPriorityNormal
Normal priority level.
kPriorityHigh
High priority level.
kPriorityNet
Network Control priority level.
LinkSecurityMode
enum LinkSecurityMode : bool
This enumeration represents the link security mode (used by Settings constructor).
Enumerator
kNoLinkSecurity
Link security disabled (no link security).
kWithLinkSecurity
Link security enabled.
Ownership
enum Ownership : uint8_t
This enumeration represents the message ownership model when a Message instance is passed to a method/function.
Enumerator
kTakeCustody
This value indicates that the method/function receiving a Message instance should take custody of the message (e.g., the method should Free() the message if no longer needed).
kCopyToUse
This value indicates that the method/function receiving a Message instance does not own the message (e.g., it should not Free() or Enqueue() it in a queue). The receiving method/function should create a copy/clone of the message to keep (if/when needed).
Member Function Documentation
Free()
void Free (void)
This method frees this message buffer.
Referenced by CoapBase::DequeueMessage(), ResponsesQueue::EnqueueResponse(), Ip6::HandleDatagram(), Ip6::HandleOptions(), Ip6::NewMessage(), Ip6::ProcessReceiveCallback(), and Ip6::SendRaw().
GetNext()
Message* GetNext (void) const
This method returns a pointer to the next message.
Returns
A pointer to the next message in the list or nullptr if at the end of the list.
Referenced by Message::GetNextCoapMessage(), Message::Iterator::NextMessage(), MeshForwarder::PrepareNextDirectTransmission(), and MeshForwarder::ResumeMessageTransmissions().
GetLength()
uint16_t GetLength (void) const inline
This method returns the number of bytes in the message.
Returns
The number of bytes in the message.
Referenced by Option::Iterator::Advance(), Appender::Appender(), Message::AppendOption(), MeshForwarder::CalcFrameVersion(), MeshForwarder::CalcIePresent(), Checksum::Calculate(), ResourceRecord::CheckRecord(), Message::Clone(), Lowpan::CompressExtensionHeader(), CoapBase::DequeueMessage(), Tlv::Find(), Message::Finish(), ResponsesQueue::GetMatchedResponseCopy(), Icmp::HandleEchoRequest(), MeshForwarder::HandleFragment(), MeshForwarder::HandleFrameRequest(), DatasetManager::HandleGet(), Ip6::HandleOptions(), Mpl::HandleSeedSetTimer(), Option::Iterator::Init(), Header::ParseFrom(), MeshForwarder::PrepareDataFrame(), Mle::ProcessMessageSecurity(), Ip6::ProcessReceiveCallback(), ResponsesQueue::ResponseMetadata::ReadFrom(), CoapBase::Metadata::ReadFrom(), Mle::DelayedResponseMetadata::ReadFrom(), Tlv::ReadTlv(), Mle::DelayedResponseMetadata::RemoveFrom(), Ip6::RemoveMplOption(), MeshForwarder::ResumeMessageTransmissions(), CoapBase::SendCopy(), Ip6::SendDatagram(), Udp::SendDatagram(), CoapBase::SendMessage(), Data::SetFrom(), Message::SetPayloadMarker(), CoapBase::Metadata::UpdateIn(), and MeshForwarder::UpdateSendMessage().
SetLength()
Error SetLength (uint16_t aLength)
This method sets the number of bytes in the message.
Parameters
[in] aLength Requested number of bytes in the message.
Return values
kErrorNone Successfully set the length of the message.
kErrorNoBufs Failed to grow the size of the message because insufficient buffers were available.
Referenced by Mle::CheckReachability(), Message::Finish(), Icmp::HandleEchoRequest(), MeshForwarder::HandleFragment(), Ip6::HandleOptions(), Mpl::HandleSeedSetTimer(), Message::Init(), Mle::ProcessMessageSecurity(), Mle::DelayedResponseMetadata::RemoveFrom(), and Message::SetToken().
GetBufferCount()
uint8_t GetBufferCount (void) const
This method returns the number of buffers in the message.
GetOffset()
uint16_t GetOffset (void) const inline
This method returns the byte offset within the message.
Returns
A byte offset within the message.
Referenced by Name::AppendPointerLabel(), Checksum::Calculate(), Lowpan::Compress(), Lowpan::CompressExtensionHeader(), Lowpan::CompressUdp(), Lowpan::Decompress(), Lowpan::DecompressUdpHeader(), CoapBase::DequeueMessage(), Tlv::Find(), AddressResolver::HandleAddressError(), Ip6::HandleDatagram(), Icmp::HandleEchoRequest(), Ip6::HandleExtensionHeaders(), Ip6::HandleFragment(), MeshForwarder::HandleFragment(), DatasetManager::HandleGet(), Icmp::HandleMessage(), Udp::HandleMessage(), Ip6::HandleOptions(), Udp::HandlePayload(), Mle::HandleUdpReceive(), Message::ParseHeader(), MeshForwarder::PrepareDataFrame(), Mpl::ProcessOption(), Ip6::ProcessReceiveCallback(), MeshForwarder::ResumeMessageTransmissions(), MeshForwarder::ScheduleTransmissionTask(), Data::SetFrom(), and Checksum::UpdateMessageChecksum().
MoveOffset()
void MoveOffset (int aDelta)
This method moves the byte offset within the message.
Parameters
[in] aDelta The number of bytes to move the current offset, which may be positive or negative.
Referenced by Lowpan::Compress(), Lowpan::CompressExtensionHeader(), Lowpan::CompressUdp(), Lowpan::Decompress(), Lowpan::DecompressExtensionHeader(), Lowpan::DecompressUdpHeader(), MeshForwarder::FrameToMessage(), Ip6::HandleFragment(), MeshForwarder::HandleFragment(), Icmp::HandleMessage(), Udp::HandleMessage(), Ip6::HandleOptions(), Mle::HandleUdpReceive(), and Message::ParseHeader().
SetOffset()
void SetOffset (uint16_t aOffset)
This method sets the byte offset within the message.
Parameters
[in] aOffset The byte offset within the message.
Referenced by Lowpan::Compress(), Lowpan::CompressExtensionHeader(), Lowpan::CompressUdp(), Ip6::HandleDatagram(), Ip6::HandleOptions(), Message::Init(), CoapBase::NewMessage(), MeshForwarder::PrepareDataFrame(), Udp::SendDatagram(), Icmp::SendEchoRequest(), Message::SetPayloadMarker(), and MeshForwarder::UpdateSendMessage().
GetType()
Type GetType (void) const inline
This method returns the type of the message.
Returns
The type of the message.
Referenced by MeshForwarder::CalcFrameVersion(), MeshForwarder::HandleDatagram(), MeshForwarder::HandleFrameRequest(), MeshForwarder::PrepareNextDirectTransmission(), MeshForwarder::ResumeMessageTransmissions(), and MeshForwarder::UpdateSendMessage().
SetType()
void SetType (Type aType) inline
This method sets the message type.
Parameters
[in] aType The message type.
GetSubType()
SubType GetSubType (void) const inline
This method returns the sub type of the message.
Returns
The sub type of the message.
Referenced by MeshForwarder::HandleFrameRequest(), MeshForwarder::PrepareDataFrame(), Mle::SendDelayedResponse(), and MeshForwarder::UpdateSendMessage().
SetSubType()
void SetSubType (SubType aSubType) inline
This method sets the message sub type.
Parameters
[in] aSubType The message sub type.
Referenced by Mpl::HandleSeedSetTimer(), and Mle::NewMleMessage().
IsSubTypeMle()
bool IsSubTypeMle (void) const
This method returns whether or not the message is of MLE subtype.
Return values
TRUE If message is of MLE subtype.
FALSE If message is not of MLE subtype.
Referenced by MeshForwarder::HandleFrameRequest(), MeshForwarder::PrepareDataFrame(), and MeshForwarder::UpdateIp6Route().
GetMulticastLoop()
bool GetMulticastLoop (void) const inline
This method checks whether this multicast message may be looped back.
Return values
TRUE If message may be looped back.
FALSE If message must not be looped back.
Referenced by Ip6::HandleDatagram().
SetMulticastLoop()
void SetMulticastLoop (bool aMulticastLoop) inline
This method sets whether multicast may be looped back.
Parameters
[in] aMulticastLoop Whether allow looping back multicast.
Referenced by Ip6::SendDatagram().
GetPriority()
Priority GetPriority (void) const inline
This method returns the message priority level.
Returns
The priority level associated with this message.
Referenced by MeshForwarder::CalcFrameVersion(), Ip6::HandleOptions(), and Ip6::SendDatagram().
SetPriority()
Error SetPriority (Priority aPriority)
This method sets the messages priority. If the message is already queued in a priority queue, changing the priority ensures to update the message in the associated queue.
Parameters
[in] aPriority The message priority level.
Return values
kErrorNone Successfully set the priority for the message.
kErrorInvalidArgs Priority level is not invalid.
Referenced by Ip6::HandleOptions().
PriorityToString()
static const char* PriorityToString (Priority aPriority) static
This static method convert a Priority to a string.
Parameters
[in] aPriority The priority level.
Returns
A string representation of aPriority.
Referenced by MeshForwarder::CalcFrameVersion().
PrependBytes()
Error PrependBytes (const void * aBuf, uint16_t aLength)
This method prepends bytes to the front of the message.
On success, this method grows the message by aLength bytes.
Parameters
[in] aBuf A pointer to a data buffer (can be nullptr to grow message without writing bytes).
[in] aLength The number of bytes to prepend.
Return values
kErrorNone Successfully prepended the bytes.
kErrorNoBufs Not enough reserved bytes in the message.
Referenced by Ip6::AddMplOption(), and Ip6::InsertMplOption().
Prepend()
Error Prepend (const ObjectType & aObject) inline
This method prepends an object to the front of the message.
On success, this method grows the message by the size of the object.
Template Parameters
ObjectType The object type to prepend to the message.
Parameters
[in] aObject A reference to the object to prepend to the message.
Return values
kErrorNone Successfully prepended the object.
kErrorNoBufs Not enough reserved bytes in the message.
Referenced by Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Ip6::InsertMplOption(), Ip6::SendDatagram(), Udp::SendDatagram(), and Icmp::SendEchoRequest().
RemoveHeader()
void RemoveHeader (uint16_t aLength)
This method removes header bytes from the message.
Parameters
[in] aLength Number of header bytes to remove.
Referenced by Ip6::HandleDatagram(), Udp::HandlePayload(), Ip6::InsertMplOption(), and Ip6::RemoveMplOption().
AppendBytes()
Error AppendBytes (const void * aBuf, uint16_t aLength)
This method appends bytes to the end of the message.
On success, this method grows the message by aLength bytes.
Parameters
[in] aBuf A pointer to a data buffer (MUST not be nullptr).
[in] aLength The number of bytes to append.
Return values
kErrorNone Successfully appended the bytes.
kErrorNoBufs Insufficient available buffers to grow the message.
Referenced by DatasetManager::AppendDatasetToMessage(), Name::AppendLabel(), Message::AppendOption(), Tlv::AppendTlv(), Tlv::AppendTo(), MeshHeader::AppendTo(), Data::CopyBytesTo(), Lowpan::DecompressExtensionHeader(), CoapBase::DequeueMessage(), Mle::HasMoreChannelsToAnnouce(), Ip6::NewMessage(), Mle::RoleToString(), Mle::SendDataRequest(), DatasetManager::SendGetRequest(), CoapBase::SendMessage(), EnergyScanServer::SendReport(), NetworkData::SendServerDataNotification(), DatasetManager::SendSet(), and DatasetManager::SendSetRequest().
AppendBytesFromMessage()
Error AppendBytesFromMessage (const Message & aMessage, uint16_t aOffset, uint16_t aLength)
This method appends bytes read from another or potentially the same message to the end of the current message.
On success, this method grows the message by aLength bytes.
Parameters
[in] aMessage The message to read the bytes from (it can be the same as the current message).
[in] aOffset The offset in aMessage to start reading the bytes from.
[in] aLength The number of bytes to read from aMessage and append.
Return values
kErrorNone Successfully appended the bytes.
kErrorNoBufs Insufficient available buffers to grow the message.
kErrorParse Not enough bytes in aMessage to read aLength bytes from aOffset.
Referenced by Name::LabelIterator::AppendLabel().
Append()
Error Append (const ObjectType & aObject) inline
This method appends an object to the end of the message.
On success, this method grows the message by the size of the appended object
Template Parameters
ObjectType The object type to append to the message.
Parameters
[in] aObject A reference to the object to append to the message.
Return values
kErrorNone Successfully appended the object.
kErrorNoBufs Insufficient available buffers to grow the message.
Referenced by Name::AppendLabel(), Name::LabelIterator::AppendLabel(), Dataset::AppendMleDatasetTlv(), Name::AppendPointerLabel(), Name::AppendTerminator(), Tlv::AppendTlv(), ResponsesQueue::ResponseMetadata::AppendTo(), CoapBase::Metadata::AppendTo(), Mle::DelayedResponseMetadata::AppendTo(), Lowpan::Decompress(), Lowpan::DecompressUdpHeader(), DiscoverScanner::Discover(), Mle::HasMoreChannelsToAnnouce(), Mle::NewMleMessage(), Mle::ProcessMessageSecurity(), Icmp::SendError(), DatasetManager::SendGetRequest(), EnergyScanServer::SendReport(), NetworkData::SendServerDataNotification(), and Message::SetPayloadMarker().
AppendData()
Error AppendData (const Data< kDataLengthType > & aData) inline
This method appends bytes from a given Data instance to the end of the message.
On success, this method grows the message by the size of the appended data.
Template Parameters
kDataLengthType Determines the data length type (uint8_t or uint16_t).
Parameters
[in] aData A reference to Data to append to the message.
Return values
kErrorNone Successfully appended the bytes from aData.
kErrorNoBufs Insufficient available buffers to grow the message.
References Data< kDataLengthType >::GetBytes(), and Data< kDataLengthType >::GetLength().
Referenced by MeshForwarder::FrameToMessage().
ReadBytes()
uint16_t ReadBytes (uint16_t aOffset, void * aBuf, uint16_t aLength) const
This method reads bytes from the message.
Parameters
[in] aOffset Byte offset within the message to begin reading.
[out] aBuf A pointer to a data buffer to copy the read bytes into.
[in] aLength Number of bytes to read.
Returns
The number of bytes read.
Referenced by Headers::DecompressFrom(), CoapBase::DequeueMessage(), Tlv::FindTlv(), DatasetManager::HandleGet(), MeshHeader::ParseFrom(), FragmentHeader::ParseFrom(), Mpl::ProcessOption(), Tlv::ReadTlv(), and LeaderBase::SetNetworkData().
Read() [1/2]
Error Read (uint16_t aOffset, void * aBuf, uint16_t aLength) const
This method reads a given number of bytes from the message.
If there are fewer bytes available in the message than the requested read length, the available bytes will be read and copied into aBuf. In this case kErrorParse will be returned.
Parameters
[in] aOffset Byte offset within the message to begin reading.
[out] aBuf A pointer to a data buffer to copy the read bytes into.
[in] aLength Number of bytes to read.
Return values
kErrorNone aLength bytes were successfully read from message.
kErrorParse Not enough bytes remaining in message to read the entire object.
Referenced by Option::Iterator::Advance(), FrameBuilder::AppendBytesFromMessage(), Lowpan::Compress(), Lowpan::CompressExtensionHeader(), Lowpan::CompressUdp(), Lowpan::DecompressEcn(), Tlv::Find(), ChannelMaskTlv::GetChannelMask(), AddressResolver::HandleAddressError(), Mle::HandleChildIdResponse(), Ip6::HandleDatagram(), DiscoverScanner::HandleDiscoveryResponse(), Icmp::HandleEchoRequest(), Ip6::HandleExtensionHeaders(), Ip6::HandleFragment(), DatasetManager::HandleGet(), Mle::HandleLeaderData(), Icmp::HandleMessage(), Udp::HandleMessage(), Ip6::HandleOptions(), Mpl::HandleSeedSetTimer(), Mle::HandleUdpReceive(), Ip6::InsertMplOption(), Option::Iterator::MarkAsParseErrored(), Lowpan::MarkCompressedEcn(), Headers::ParseFrom(), Header::ParseFrom(), Message::ParseHeader(), Ip6::ProcessReceiveCallback(), Option::Iterator::Read(), ChildTableTlv::ReadEntry(), Option::Iterator::ReadExtendedOptionField(), ResponsesQueue::ResponseMetadata::ReadFrom(), CoapBase::Metadata::ReadFrom(), ResourceRecord::ReadFrom(), Mle::DelayedResponseMetadata::ReadFrom(), Dataset::ReadFromMessage(), ResourceRecord::ReadRecord(), Tlv::ReadTlv(), TxtRecord::ReadTxtData(), Ip6::RemoveMplOption(), MeshForwarder::ResumeMessageTransmissions(), Data::SetFrom(), LeaderBase::SetNetworkData(), and MeshForwarder::UpdateIp6Route().
Read() [2/2]
Error Read (uint16_t aOffset, ObjectType & aObject) const inline
This method reads an object from the message.
If there are fewer bytes available in the message than the requested object size, the available bytes will be read and copied into aObject (aObject will be read partially). In this case kErrorParse will be returned.
Template Parameters
ObjectType The object type to read from the message.
Parameters
[in] aOffset Byte offset within the message to begin reading.
[out] aObject A reference to the object to read into.
Return values
kErrorNone Object aObject was successfully read from message.
kErrorParse Not enough bytes remaining in message to read the entire object.
CompareBytes() [1/2]
bool CompareBytes (uint16_t aOffset, const void * aBuf, uint16_t aLength, ByteMatcher aMatcher = nullptr) const
This method compares the bytes in the message at a given offset with a given byte array.
If there are fewer bytes available in the message than the requested aLength, the comparison is treated as failure (returns FALSE).
Parameters
[in] aOffset Byte offset within the message to read from for the comparison.
[in] aBuf A pointer to a data buffer to compare with the bytes from message.
[in] aLength Number of bytes in aBuf.
[in] aMatcher A ByteMatcher function pointer to match the bytes. If nullptr then bytes are directly compared.
Returns
TRUE if there are enough bytes available in aMessage and they match the bytes from aBuf, FALSE otherwise.
CompareBytes() [2/2]
bool CompareBytes (uint16_t aOffset, const Message & aOtherMessage, uint16_t aOtherOffset, uint16_t aLength, ByteMatcher aMatcher = nullptr) const
This method compares the bytes in the message at a given offset with bytes read from another message.
If either message has fewer bytes available than the requested aLength, the comparison is treated as failure (returns FALSE).
Parameters
[in] aOffset Byte offset within the message to read from for the comparison.
[in] aOtherMessage The other message to compare with.
[in] aOtherOffset Byte offset within aOtherMessage to read from for the comparison.
[in] aLength Number of bytes to compare.
[in] aMatcher A ByteMatcher function pointer to match the bytes. If nullptr then bytes are directly compared.
Returns
TRUE if there are enough bytes available in both messages and they all match. FALSE otherwise.
Compare()
bool Compare (uint16_t aOffset, const ObjectType & aObject) const inline
This method compares the bytes in the message at a given offset with an object.
The bytes in the message are compared with the bytes in aObject. If there are fewer bytes available in the message than the requested object size, it is treated as failed comparison (returns FALSE).
Template Parameters
ObjectType The object type to compare with the bytes in message.
Parameters
[in] aOffset Byte offset within the message to read from for the comparison.
[in] aObject A reference to the object to compare with the message bytes.
Returns
TRUE if there are enough bytes available in aMessage and they match the bytes in aObject, FALSE otherwise.
Referenced by Mle::ProcessMessageSecurity().
WriteBytes()
void WriteBytes (uint16_t aOffset, const void * aBuf, uint16_t aLength)
This method writes bytes to the message.
This method will not resize the message. The given data to write (with aLength bytes) MUST fit within the existing message buffer (from the given offset aOffset up to the message's length).
Parameters
[in] aOffset Byte offset within the message to begin writing.
[in] aBuf A pointer to a data buffer.
[in] aLength Number of bytes to write.
Referenced by Message::Finish(), Icmp::HandleEchoRequest(), Ip6::InsertMplOption(), and Ip6::RemoveMplOption().
Write()
void Write (uint16_t aOffset, const ObjectType & aObject) inline
This methods writes an object to the message.
This method will not resize the message. The entire given object (all its bytes) MUST fit within the existing message buffer (from the given offset aOffset up to the message's length).
Template Parameters
ObjectType The object type to write to the message.
Parameters
[in] aOffset Byte offset within the message to begin writing.
[in] aObject A reference to the object to write.
Referenced by Lowpan::Decompress(), Ip6::HandleDatagram(), Ip6::HandleOptions(), Mpl::HandleSeedSetTimer(), Ip6::InsertMplOption(), Lowpan::MarkCompressedEcn(), Ip6::RemoveMplOption(), MeshForwarder::ResumeMessageTransmissions(), CoapBase::Metadata::UpdateIn(), Checksum::UpdateMessageChecksum(), and Checksum::WriteToMessage().
WriteData()
void WriteData (uint16_t aOffset, const Data< kDataLengthType > & aData) inline
This method writes bytes from a given Data instance to the message.
This method will not resize the message. The given data to write MUST fit within the existing message buffer (from the given offset aOffset up to the message's length).
Template Parameters
kDataLengthType Determines the data length type (uint8_t or uint16_t).
Parameters
[in] aOffset Byte offset within the message to begin writing.
[in] aData The Data to write to the message.
References Data< kDataLengthType >::GetBytes(), and Data< kDataLengthType >::GetLength().
Referenced by MeshForwarder::HandleFragment().
CopyTo()
uint16_t CopyTo (uint16_t aSourceOffset, uint16_t aDestinationOffset, uint16_t aLength, Message & aMessage) const
This method copies bytes from one message to another.
If source and destination messages are the same, CopyTo() can be used to perform a backward copy, but it MUST not be used to forward copy within the same message (i.e., when source and destination messages are the same and source offset is smaller than the destination offset).
Parameters
[in] aSourceOffset Byte offset within the source message to begin reading.
[in] aDestinationOffset Byte offset within the destination message to begin writing.
[in] aLength Number of bytes to copy.
[in] aMessage Message to copy to.
Returns
The number of bytes copied.
Referenced by Icmp::HandleEchoRequest(), Ip6::HandleOptions(), and Ip6::InsertMplOption().
Clone() [1/2]
Message* Clone (uint16_t aLength) const
This method creates a copy of the message.
It allocates the new message from the same message pool as the original one and copies aLength octets of the payload. The Type, SubType, LinkSecurity, Offset, InterfaceId, and Priority fields on the cloned message are also copied from the original one.
Parameters
[in] aLength Number of payload bytes to copy.
Returns
A pointer to the message or nullptr if insufficient message buffers are available.
Referenced by Ip6::HandlePayload(), Mpl::HandleSeedSetTimer(), Ip6::InsertMplOption(), Ip6::ProcessReceiveCallback(), and Ip6::SendDatagram().
Clone() [2/2]
Message* Clone (void) const inline
This method creates a copy of the message.
It allocates the new message from the same message pool as the original one and copies the entire payload. The Type, SubType, LinkSecurity, Offset, InterfaceId, and Priority fields on the cloned message are also copied from the original one.
Returns
A pointer to the message or nullptr if insufficient message buffers are available.
References Message::Clone().
Referenced by Message::Clone().
GetDatagramTag()
uint32_t GetDatagramTag (void) const inline
This method returns the datagram tag used for 6LoWPAN fragmentation or the identification used for IPv6 fragmentation.
Returns
The 6LoWPAN datagram tag or the IPv6 fragment identification.
Referenced by MeshForwarder::PrepareDataFrame().
SetDatagramTag()
void SetDatagramTag (uint32_t aTag) inline
This method sets the datagram tag used for 6LoWPAN fragmentation.
Parameters
[in] aTag The 6LoWPAN datagram tag.
Referenced by MeshForwarder::HandleFragment(), Ip6::HandleOptions(), and MeshForwarder::PrepareDataFrame().
GetChildMask()
bool GetChildMask (uint16_t aChildIndex) const
This method returns whether or not the message forwarding is scheduled for the child.
Parameters
[in] aChildIndex The index into the child table.
Return values
TRUE If the message is scheduled to be forwarded to the child.
FALSE If the message is not scheduled to be forwarded to the child.
ClearChildMask()
void ClearChildMask (uint16_t aChildIndex)
This method unschedules forwarding of the message to the child.
Parameters
[in] aChildIndex The index into the child table.
SetChildMask()
void SetChildMask (uint16_t aChildIndex)
This method schedules forwarding of the message to the child.
Parameters
[in] aChildIndex The index into the child table.
IsChildPending()
bool IsChildPending (void) const
This method returns whether or not the message forwarding is scheduled for at least one child.
Return values
TRUE If message forwarding is scheduled for at least one child.
FALSE If message forwarding is not scheduled for any child.
Referenced by MeshForwarder::RemoveMessageIfNoPendingTx().
GetMeshDest()
uint16_t GetMeshDest (void) const inline
This method returns the RLOC16 of the mesh destination.
Note
Only use this for non-link-local unicast messages.
Returns
The IEEE 802.15.4 Destination PAN ID.
SetMeshDest()
void SetMeshDest (uint16_t aMeshDest) inline
This method sets the RLOC16 of the mesh destination.
Note
Only use this when sending non-link-local unicast messages.
Parameters
[in] aMeshDest The IEEE 802.15.4 Destination PAN ID.
GetPanId()
uint16_t GetPanId (void) const inline
This method returns the IEEE 802.15.4 Destination PAN ID.
Note
Only use this when sending MLE Discover Request or Response messages.
Returns
The IEEE 802.15.4 Destination PAN ID.
Referenced by MeshForwarder::PrepareDataFrame().
SetPanId()
void SetPanId (uint16_t aPanId) inline
This method sets the IEEE 802.15.4 Destination PAN ID.
Note
Only use this when sending MLE Discover Request or Response messages.
Parameters
[in] aPanId The IEEE 802.15.4 Destination PAN ID.
Referenced by DiscoverScanner::Discover().
GetChannel()
uint8_t GetChannel (void) const inline
This method returns the IEEE 802.15.4 Channel to use for transmission.
Note
Only use this when sending MLE Announce messages.
Returns
The IEEE 802.15.4 Channel to use for transmission.
Referenced by MeshForwarder::PrepareDataFrame().
SetChannel()
void SetChannel (uint8_t aChannel) inline
This method sets the IEEE 802.15.4 Channel to use for transmission.
Note
Only use this when sending MLE Announce messages.
Parameters
[in] aChannel The IEEE 802.15.4 Channel to use for transmission.
Referenced by Mle::SendAnnounce().
GetTimestamp()
TimeMilli GetTimestamp (void) const inline
This method returns the message timestamp.
Returns
The message timestamp.
Referenced by MeshForwarder::ResumeMessageTransmissions().
SetTimestamp()
void SetTimestamp (TimeMilli aTimestamp) inline
This method sets the message timestamp to a given time.
Parameters
[in] aTimestamp The timestamp value.
SetTimestampToNow()
void SetTimestampToNow (void) inline
This method sets the message timestamp to the current time.
Referenced by DiscoverScanner::HandleDiscoveryRequestFrameTxDone(), MeshForwarder::HandleFragment(), and Ip6::HandleOptions().
IsDirectTransmission()
bool IsDirectTransmission (void) const inline
This method returns whether or not message forwarding is scheduled for direct transmission.
Return values
TRUE If message forwarding is scheduled for direct transmission.
FALSE If message forwarding is not scheduled for direct transmission.
Referenced by MeshForwarder::PrepareNextDirectTransmission(), MeshForwarder::RemoveMessageIfNoPendingTx(), MeshForwarder::ResumeMessageTransmissions(), and MeshForwarder::UpdateSendMessage().
ClearDirectTransmission()
void ClearDirectTransmission (void) inline
This method unschedules forwarding using direct transmission.
Referenced by MeshForwarder::ResumeMessageTransmissions(), and MeshForwarder::UpdateSendMessage().
SetDirectTransmission()
void SetDirectTransmission (void) inline
This method schedules forwarding using direct transmission.
Referenced by DiscoverScanner::HandleDiscoveryRequestFrameTxDone().
GetTxSuccess()
bool GetTxSuccess (void) const inline
This method indicates whether the direct transmission of message was successful.
Return values
TRUE If direct transmission of message was successful (all fragments were delivered and acked).
FALSE If direct transmission of message failed (at least one fragment failed).
Referenced by MeshForwarder::UpdateSendMessage().
SetTxSuccess()
void SetTxSuccess (bool aTxSuccess) inline
This method sets whether the direct transmission of message was successful.
Parameters
[in] aTxSuccess TRUE if the direct transmission is successful, FALSE otherwise (i.e., at least one fragment transmission failed).
Referenced by MeshForwarder::ScheduleTransmissionTask(), and MeshForwarder::UpdateSendMessage().
GetDoNotEvict()
bool GetDoNotEvict (void) const inline
This method indicates whether the message may be evicted.
Return values
TRUE If the message must not be evicted.
FALSE If the message may be evicted.
SetDoNotEvict()
void SetDoNotEvict (bool aDoNotEvict) inline
This method sets whether the message may be evicted.
Parameters
[in] aDoNotEvict TRUE if the message may not be evicted, FALSE otherwise.
Referenced by MeshForwarder::PrepareNextDirectTransmission().
IsResolvingAddress()
bool IsResolvingAddress (void) const inline
This method indicates whether the message is waiting for an address query resolution.
Return values
TRUE If the message is waiting for address query resolution.
FALSE If the message is not waiting for address query resolution.
Referenced by MeshForwarder::PrepareNextDirectTransmission().
SetResolvingAddress()
void SetResolvingAddress (bool aResolvingAddress) inline
This method sets whether the message is waiting for an address query resolution.
Parameters
[in] aResolvingAddress TRUE if message is waiting for address resolution, FALSE otherwise.
Referenced by MeshForwarder::PrepareNextDirectTransmission().
IsLinkSecurityEnabled()
bool IsLinkSecurityEnabled (void) const inline
This method indicates whether or not link security is enabled for the message.
Return values
TRUE If link security is enabled.
FALSE If link security is not enabled.
Referenced by Filter::Accept(), MeshForwarder::CalcFrameVersion(), MeshForwarder::HandleFragment(), MeshForwarder::HandleFrameRequest(), MeshForwarder::PrepareDataFrame(), MeshForwarder::UpdateIp6Route(), and MeshForwarder::UpdateSendMessage().
SetLinkSecurityEnabled()
void SetLinkSecurityEnabled (bool aEnabled) inline
This method sets whether or not link security is enabled for the message.
Parameters
[in] aEnabled TRUE if link security is enabled, FALSE otherwise.
Referenced by MeshForwarder::HandleFrameRequest(), MeshForwarder::PrepareDataFrame(), and Mle::SendAnnounce().
AddRss()
void AddRss (int8_t aRss) inline
This method updates the average RSS (Received Signal Strength) associated with the message by adding the given RSS value to the average. Note that a message can be composed of multiple 802.15.4 data frame fragments each received with a different signal strength.
Parameters
[in] aRss A new RSS value (in dBm) to be added to average.
References RssAverager::Add(), and IgnoreError().
Referenced by MeshForwarder::HandleFragment().
GetAverageRss()
int8_t GetAverageRss (void) const inline
This method returns the average RSS (Received Signal Strength) associated with the message.
Returns
The current average RSS value (in dBm) or OT_RADIO_RSSI_INVALID if no average is available.
Referenced by Mle::HandleAnnounce().
GetRssAverager()
const RssAverager& GetRssAverager (void) const inline
This method returns a const reference to RssAverager of the message.
Returns
A const reference to the RssAverager of the message.
References RssAverager::Add().
Referenced by MeshForwarder::CalcFrameVersion().
SetLinkInfo()
void SetLinkInfo (const ThreadLinkInfo & aLinkInfo)
This method sets the message's link info properties (PAN ID, link security, RSS) from a given ThreadLinkInfo.
Parameters
[in] aLinkInfo The ThreadLinkInfo instance from which to set message's related properties.
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
GetMessageQueue()
MessageQueue* GetMessageQueue (void) const inline
This method returns a pointer to the message queue (if any) where this message is queued.
Returns
A pointer to the message queue or nullptr if not in any message queue.
GetPriorityQueue()
PriorityQueue* GetPriorityQueue (void) const inline
This method returns a pointer to the priority message queue (if any) where this message is queued.
Returns
A pointer to the priority queue or nullptr if not in any priority queue.
Referenced by MeshForwarder::RemoveMessage().
IsTimeSync()
bool IsTimeSync (void) const
This method indicates whether or not the message is also used for time sync purpose.
When OPENTHREAD_CONFIG_TIME_SYNC_ENABLE is 0, this method always return false.
Return values
TRUE If the message is also used for time sync purpose.
FALSE If the message is not used for time sync purpose.
Referenced by MeshForwarder::CalcIePresent().
GetReserved()
uint16_t GetReserved (void) const inline protected
Referenced by Message::ParseHeader().
SetReserved()
void SetReserved (uint16_t aReservedHeader) inline protected
GetFirstChunk() [1/2]
void GetFirstChunk (uint16_t aOffset, uint16_t & aLength, Chunk & aChunk) const private
Referenced by Checksum::Calculate(), AesCcm::Payload(), HmacSha256::Update(), and Sha256::Update().
GetNextChunk() [1/2]
void GetNextChunk (uint16_t & aLength, Chunk & aChunk) const private
Referenced by Checksum::Calculate(), AesCcm::Payload(), HmacSha256::Update(), and Sha256::Update().
GetFirstChunk() [2/2]
void GetFirstChunk (uint16_t aOffset, uint16_t & aLength, MutableChunk & aChunk) inline private
References ot::AsConst().
GetNextChunk() [2/2]
void GetNextChunk (uint16_t & aLength, MutableChunk & aChunk) inline private
References ot::AsConst().
GetMessagePool()
MessagePool* GetMessagePool (void) const inline private
SetMessagePool()
void SetMessagePool (MessagePool * aMessagePool) inline private
IsInAQueue()
bool IsInAQueue (void) const inline private
SetMessageQueue()
void SetMessageQueue (MessageQueue * aMessageQueue) private
SetPriorityQueue()
void SetPriorityQueue (PriorityQueue * aPriorityQueue) private
Next() [1/2]
Message*& Next (void) inline private
References otMessageBuffer::mNext.
Referenced by Message::NextOf().
Next() [2/2]
Message* const& Next (void) const inline private
References otMessageBuffer::mNext.
Prev()
Message*& Prev (void) inline private
NextOf() [1/2]
static Message* NextOf (Message * aMessage) inline static private
References Message::Next().
NextOf() [2/2]
static const Message* NextOf (const Message * aMessage) inline static private
References Message::Next().
ResizeMessage()
Error ResizeMessage (uint16_t aLength) private
Friends And Related Function Documentation
Checksum
friend class Checksum friend
Crypto::HmacSha256
friend class Crypto::HmacSha256 friend
Crypto::Sha256
friend class Crypto::Sha256 friend
Crypto::AesCcm
friend class Crypto::AesCcm friend
MessagePool
friend class MessagePool friend
MessageQueue
friend class MessageQueue friend
PriorityQueue
friend class PriorityQueue friend
Field Documentation
kNumPriorities
constexpr uint8_t kNumPriorities = 4 static
Number of priority levels.
The documentation for this class was generated from the following file:
message.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale