OpenThread: PrefixInfoOption Class Reference
PrefixInfoOption Class Reference
#include <nd6.hpp>
Public Member Functions
void ClearAutoAddrConfigFlag (void)
void ClearOnLinkFlag (void)
uint32_t GetPreferredLifetime (void) const
void GetPrefix (Prefix &aPrefix) const
uint32_t GetValidLifetime (void) const
void Init (void)
bool IsAutoAddrConfigFlagSet (void) const
bool IsOnLinkFlagSet (void) const
bool IsValid (void) const
PrefixInfoOption (void)=delete
void SetAutoAddrConfigFlag (void)
void SetOnLinkFlag (void)
void SetPreferredLifetime (uint32_t aPreferredLifetime)
void SetPrefix (const Prefix &aPrefix)
void SetValidLifetime (uint32_t aValidLifetime)
Public Member Functions inherited from Option
uint16_t GetLength (void) const
uint16_t GetSize (void) const
uint8_t GetType (void) const
bool IsValid (void) const
void SetLength (uint8_t aLength)
void SetSize (uint16_t aSize)
void SetType (Type aType)
Static Public Attributes
static constexpr Type kType = kTypePrefixInfo
Prefix Information Option Type.
Static Public Attributes inherited from Option
static constexpr uint16_t kLengthUnit = 8
The unit of length in octets.
Private Attributes
uint8_t mFlags
uint32_t mPreferredLifetime
Address mPrefix
uint8_t mPrefixLength
uint32_t mReserved2
uint32_t mValidLifetime
Static Private Attributes
static constexpr uint8_t kAutoConfigFlagMask = 0x40
static constexpr uint8_t kOnLinkFlagMask = 0x80
Additional Inherited Members
Public Types inherited from Option
enum Type : uint8_t { kTypePrefixInfo = 3, kTypeRouteInfo = 24 }
Private Member Functions inherited from Clearable< PrefixInfoOption >
void Clear (void)
Detailed Description
This class represents the Prefix Information Option.
See section 4.6.2 of RFC 4861 for definition of this option [https://tools.ietf.org/html/rfc4861#section-4.6.2]
Constructor & Destructor Documentation
PrefixInfoOption()
PrefixInfoOption (void) delete
Member Function Documentation
Init()
void Init (void)
This method initializes the Prefix Info option with proper type and length and sets all other fields to zero.
References Option::kTypePrefixInfo, OT_UNUSED_VARIABLE, Option::SetSize(), and Option::SetType().
Referenced by RouterAdvertMessage::AppendPrefixInfoOption().
IsOnLinkFlagSet()
bool IsOnLinkFlagSet (void) const inline
This method indicates whether or not the on-link flag is set.
Return values
TRUE The on-link flag is set.
FALSE The on-link flag is not set.
SetOnLinkFlag()
void SetOnLinkFlag (void) inline
This method sets the on-link (L) flag.
Referenced by RouterAdvertMessage::AppendPrefixInfoOption().
ClearOnLinkFlag()
void ClearOnLinkFlag (void) inline
This method clears the on-link (L) flag.
IsAutoAddrConfigFlagSet()
bool IsAutoAddrConfigFlagSet (void) const inline
This method indicates whether or not the autonomous address-configuration (A) flag is set.
Return values
TRUE The auto address-config flag is set.
FALSE The auto address-config flag is not set.
SetAutoAddrConfigFlag()
void SetAutoAddrConfigFlag (void) inline
This method sets the autonomous address-configuration (A) flag.
Referenced by RouterAdvertMessage::AppendPrefixInfoOption().
ClearAutoAddrConfigFlag()
void ClearAutoAddrConfigFlag (void) inline
This method clears the autonomous address-configuration (A) flag.
SetValidLifetime()
void SetValidLifetime (uint32_t aValidLifetime) inline
This method sets the valid lifetime of the prefix in seconds.
Parameters
[in] aValidLifetime The valid lifetime in seconds.
References ot::Encoding::BigEndian::HostSwap32().
Referenced by RouterAdvertMessage::AppendPrefixInfoOption().
GetValidLifetime()
uint32_t GetValidLifetime (void) const inline
THis method gets the valid lifetime of the prefix in seconds.
Returns
The valid lifetime in seconds.
References ot::Encoding::BigEndian::HostSwap32().
SetPreferredLifetime()
void SetPreferredLifetime (uint32_t aPreferredLifetime) inline
This method sets the preferred lifetime of the prefix in seconds.
Parameters
[in] aPreferredLifetime The preferred lifetime in seconds.
References ot::Encoding::BigEndian::HostSwap32().
Referenced by RouterAdvertMessage::AppendPrefixInfoOption().
GetPreferredLifetime()
uint32_t GetPreferredLifetime (void) const inline
THis method returns the preferred lifetime of the prefix in seconds.
Returns
The preferred lifetime in seconds.
References ot::Encoding::BigEndian::HostSwap32(), and Option::IsValid().
SetPrefix()
void SetPrefix (const Prefix & aPrefix)
This method sets the prefix.
Parameters
[in] aPrefix The prefix contained in this option.
References ot::AsCoreType(), otIp6Prefix::mLength, and otIp6Prefix::mPrefix.
Referenced by RouterAdvertMessage::AppendPrefixInfoOption().
GetPrefix()
void GetPrefix (Prefix & aPrefix) const
This method gets the prefix in this option.
Parameters
[out] aPrefix Reference to a Prefix to return the prefix.
References Prefix::Set().
IsValid()
bool IsValid (void) const
This method indicates whether or not the option is valid.
Return values
TRUE The option is valid
FALSE The option is not valid.
References Option::GetSize(), and Prefix::kMaxLength.
Field Documentation
kType
constexpr Type kType = kTypePrefixInfo static
Prefix Information Option Type.
kAutoConfigFlagMask
constexpr uint8_t kAutoConfigFlagMask = 0x40 static private
kOnLinkFlagMask
constexpr uint8_t kOnLinkFlagMask = 0x80 static private
mPrefixLength
uint8_t mPrefixLength private
mFlags
uint8_t mFlags private
mValidLifetime
uint32_t mValidLifetime private
mPreferredLifetime
uint32_t mPreferredLifetime private
mReserved2
uint32_t mReserved2 private
mPrefix
Address mPrefix private
The documentation for this class was generated from the following files:
nd6.hpp
nd6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale