OpenThread: SettingsDriver Class Reference
SettingsDriver Class Reference
#include <settings_driver.hpp>
Public Member Functions
Error Add (uint16_t aKey, const void *aValue, uint16_t aValueLength)
void Deinit (void)
Error Delete (uint16_t aKey, int aIndex=-1)
Error Get (uint16_t aKey, int aIndex, void *aValue, uint16_t *aValueLength) const
Error Get (uint16_t aKey, void *aValue, uint16_t *aValueLength) const
void Init (const uint16_t *aSensitiveKeys, uint16_t aSensitiveKeysLength)
Error Set (uint16_t aKey, const void *aValue, uint16_t aValueLength)
SettingsDriver (Instance &aInstance)
void Wipe (void)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
otInstance * GetInstancePtr (void) const
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Constructor & Destructor Documentation
SettingsDriver()
SettingsDriver (Instance & aInstance) inline explicit
This constructor initializes the SettingsDriver.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Init()
void Init (const uint16_t * aSensitiveKeys, uint16_t aSensitiveKeysLength) inline
This method initializes the settings storage driver.
Parameters
[in] aSensitiveKeys A pointer to an array containing the list of sensitive keys.
[in] aSensitiveKeysLength The number of entries in the aSensitiveKeys array.
References SettingsDriver::GetInstancePtr(), OT_UNUSED_VARIABLE, and otPlatSettingsInit().
Deinit()
void Deinit (void) inline
This method deinitializes the settings driver.
References SettingsDriver::GetInstancePtr(), and otPlatSettingsDeinit().
Add()
Error Add (uint16_t aKey, const void * aValue, uint16_t aValueLength) inline
This method adds a value to aKey.
Parameters
[in] aKey The key associated with the value.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be nullptr if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
kErrorNone The value was added.
kErrorNoBufs Not enough space to store the value.
References SettingsDriver::GetInstancePtr(), and otPlatSettingsAdd().
Delete()
Error Delete (uint16_t aKey, int aIndex = -1) inline
This method removes a value from aKey.
Parameters
[in] aKey The key associated with the value.
[in] aIndex The index of the value to be removed. If set to -1, all values for aKey will be removed.
Return values
kErrorNone The given key and index was found and removed successfully.
kErrorNotFound The given key or index was not found.
References SettingsDriver::GetInstancePtr(), and otPlatSettingsDelete().
Get() [1/2]
Error Get (uint16_t aKey, int aIndex, void * aValue, uint16_t * aValueLength) const inline
This method fetches the value identified by aKey at a given aIndex.
Parameters
[in] aKey The key associated with the requested value.
[in] aIndex The index of the specific item to get.
[out] aValue A pointer to where the value of the setting should be written. May be nullptr if just testing for the presence or length of a key.
[in,out] aValueLength A pointer to the length of the value. When called, this should point to an integer containing the maximum bytes that can be written to aValue. At return, the actual length of the setting is written. May be nullptr if performing a presence check.
Return values
kErrorNone The value was fetched successfully.
kErrorNotFound The key was not found.
References SettingsDriver::GetInstancePtr(), and otPlatSettingsGet().
Get() [2/2]
Error Get (uint16_t aKey, void * aValue, uint16_t * aValueLength) const inline
This method fetches the value identified by aKey.
Parameters
[in] aKey The key associated with the requested value.
[out] aValue A pointer to where the value of the setting should be written. May be nullptr if just testing for the presence or length of a key.
[in,out] aValueLength A pointer to the length of the value. When called, this should point to an integer containing the maximum bytes that can be written to aValue. At return, the actual length of the setting is written. May be nullptr if performing a presence check.
Return values
kErrorNone The value was fetched successfully.
kErrorNotFound The key was not found.
References SettingsDriver::Get().
Referenced by SettingsDriver::Get().
Set()
Error Set (uint16_t aKey, const void * aValue, uint16_t aValueLength) inline
This method sets or replaces the value identified by aKey.
If there was more than one value previously associated with aKey, then they are all deleted and replaced with this single entry.
Parameters
[in] aKey The key associated with the value.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be nullptr if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
kErrorNone The value was changed.
kErrorNoBufs Not enough space to store the value.
References SettingsDriver::GetInstancePtr(), and otPlatSettingsSet().
Wipe()
void Wipe (void) inline
This method removes all values.
References SettingsDriver::GetInstancePtr(), and otPlatSettingsWipe().
GetInstancePtr()
otInstance* GetInstancePtr (void) const inline private
References InstanceLocator::GetInstance().
Referenced by SettingsDriver::Add(), SettingsDriver::Deinit(), SettingsDriver::Delete(), SettingsDriver::Get(), SettingsDriver::Init(), SettingsDriver::Set(), and SettingsDriver::Wipe().
The documentation for this class was generated from the following file:
settings_driver.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale