OpenThread: LeaseOption Class Reference
LeaseOption Class Reference
Core-dns
#include <dns_types.hpp>
Public Member Functions
uint32_t GetKeyLeaseInterval (void) const
uint32_t GetLeaseInterval (void) const
void Init (void)
bool IsValid (void) const
void SetKeyLeaseInterval (uint32_t aKeyLeaseInterval)
void SetLeaseInterval (uint32_t aLeaseInterval)
Public Member Functions inherited from Option
uint16_t GetOptionCode (void) const
uint16_t GetOptionLength (void) const
uint32_t GetSize (void) const
void SetOptionCode (uint16_t aOptionCode)
void SetOptionLength (uint16_t aOptionLength)
Static Public Attributes
static constexpr uint16_t kOptionLength = sizeof(uint32_t) + sizeof(uint32_t)
lease and key lease values
Static Public Attributes inherited from Option
static constexpr uint16_t kUpdateLease = 2
Update lease option code.
Private Attributes
uint32_t mKeyLeaseInterval
uint32_t mLeaseInterval
Detailed Description
This class implements an Update Lease Option body.
This implementation is intended for use in Dynamic DNS Update Lease Requests and Responses as specified in https://tools.ietf.org/html/draft-sekar-dns-ul-02.
Member Function Documentation
Init()
void Init (void) inline
This method initialize the Update Lease Option by setting the Option Code and Option Length.
The lease and key lease intervals remain unchanged/uninitialized.
IsValid()
bool IsValid (void) const
This method tells whether this is a valid Lease Option.
Returns
TRUE if this is a valid Lease Option, FALSE if not a valid Lease Option.
GetLeaseInterval()
uint32_t GetLeaseInterval (void) const inline
This method returns the Update Lease OPT record's lease interval value.
Returns
The lease interval value (in seconds).
References ot::Encoding::BigEndian::HostSwap32().
SetLeaseInterval()
void SetLeaseInterval (uint32_t aLeaseInterval) inline
This method sets the Update Lease OPT record's lease interval value.
Parameters
[in] aLeaseInterval The lease interval value.
References ot::Encoding::BigEndian::HostSwap32().
GetKeyLeaseInterval()
uint32_t GetKeyLeaseInterval (void) const inline
This method returns the Update Lease OPT record's key lease interval value.
Returns
The key lease interval value (in seconds).
References ot::Encoding::BigEndian::HostSwap32().
SetKeyLeaseInterval()
void SetKeyLeaseInterval (uint32_t aKeyLeaseInterval) inline
This method sets the Update Lease OPT record's key lease interval value.
Parameters
[in] aKeyLeaseInterval The key lease interval value (in seconds).
References ot::Encoding::BigEndian::HostSwap32().
Field Documentation
kOptionLength
constexpr uint16_t kOptionLength = sizeof(uint32_t) + sizeof(uint32_t) static
lease and key lease values
mLeaseInterval
uint32_t mLeaseInterval private
mKeyLeaseInterval
uint32_t mKeyLeaseInterval private
The documentation for this class was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale