OpenThread: ChannelMaskEntry Class Reference
ChannelMaskEntry Class Reference
#include <meshcop_tlvs.hpp>
Public Member Functions
uint32_t GetMask (void) const
void Init (void)
bool IsValid (void) const
void SetMask (uint32_t aMask)
Public Member Functions inherited from ChannelMaskEntryBase
void ClearChannel (uint8_t aChannel)
uint8_t GetChannelPage (void) const
uint16_t GetEntrySize (void) const
uint8_t GetMaskLength (void) const
const ChannelMaskEntryBase * GetNext (void) const
ChannelMaskEntryBase * GetNext (void)
bool IsChannelSet (uint8_t aChannel) const
void SetChannel (uint8_t aChannel)
void SetChannelPage (uint8_t aChannelPage)
void SetMaskLength (uint8_t aMaskLength)
Private Attributes
uint32_t mMask
Detailed Description
This class implements Channel Mask Entry Page 0 generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the entry.
Referenced by ChannelMaskTlv::SetChannelMask().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the entry appears to be well-formed.
Return values
TRUE If the entry appears to be well-formed.
FALSE If the entry does not appear to be well-formed.
GetMask()
uint32_t GetMask (void) const inline
This method returns the Channel Mask value as a uint32_t bit mask.
Returns
The Channel Mask value.
References ot::Encoding::BigEndian::HostSwap32(), and ot::Encoding::Reverse32().
Referenced by ChannelMaskTlv::GetChannelMask().
SetMask()
void SetMask (uint32_t aMask) inline
This method sets the Channel Mask value.
Parameters
[in] aMask The Channel Mask value.
References ot::Encoding::BigEndian::HostSwap32(), and ot::Encoding::Reverse32().
Referenced by ChannelMaskTlv::SetChannelMask().
Field Documentation
mMask
uint32_t mMask private
The documentation for this class was generated from the following file:
meshcop_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale