OpenThread: Address Class Reference
Address Class Reference
Core-mac
#include <mac_types.hpp>
Public Types
typedef ExtAddress::InfoString InfoString
enum Type : uint8_t { kTypeNone, kTypeShort, kTypeExtended }
Public Member Functions
Address (void)
const ExtAddress & GetExtended (void) const
ExtAddress & GetExtended (void)
ShortAddress GetShort (void) const
Type GetType (void) const
bool IsBroadcast (void) const
bool IsExtended (void) const
bool IsNone (void) const
bool IsShort (void) const
bool IsShortAddrInvalid (void) const
void SetExtended (const ExtAddress &aExtAddress)
void SetExtended (const uint8_t *aBuffer, ExtAddress::CopyByteOrder aByteOrder=ExtAddress::kNormalByteOrder)
void SetNone (void)
void SetShort (ShortAddress aShortAddress)
InfoString ToString (void) const
Private Attributes
union {
ExtAddress mExtAddress
The IEEE 802.15.4 Extended Address.
ShortAddress mShortAddress
The IEEE 802.15.4 Short Address.
} mShared
Type mType
The address type (Short, Extended, or none).
Detailed Description
This class represents an IEEE 802.15.4 Short or Extended Address.
Member Typedef Documentation
InfoString
typedef ExtAddress::InfoString InfoString
This type defines the fixed-length String object returned from ToString().
Member Enumeration Documentation
Type
enum Type : uint8_t
This enumeration specifies the IEEE 802.15.4 Address type.
Enumerator
kTypeNone
No address.
kTypeShort
IEEE 802.15.4 Short Address.
kTypeExtended
IEEE 802.15.4 Extended Address.
Constructor & Destructor Documentation
Address()
Address (void) inline
This constructor initializes an Address.
Member Function Documentation
GetType()
Type GetType (void) const inline
This method gets the address type (Short Address, Extended Address, or none).
Returns
The address type.
Referenced by Lowpan::ComputeIid(), Mac::HandleReceivedFrame(), Frame::SetDstAddr(), and Frame::SetSrcAddr().
IsNone()
bool IsNone (void) const inline
This method indicates whether or not there is an address.
Returns
TRUE if there is no address (i.e. address type is kTypeNone), FALSE otherwise.
Referenced by NeighborTable::FindNeighbor(), Mac::HandleReceivedFrame(), and Mac::ProcessEnhAckSecurity().
IsShort()
bool IsShort (void) const inline
This method indicates whether or not the Address is a Short Address.
Returns
TRUE if it is a Short Address, FALSE otherwise.
Referenced by MeshForwarder::PrepareDataFrame(), and MeshForwarder::PrepareEmptyFrame().
IsExtended()
bool IsExtended (void) const inline
This method indicates whether or not the Address is an Extended Address.
Returns
TRUE if it is an Extended Address, FALSE otherwise.
Referenced by Mac::ConvertBeaconToActiveScanResult(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), MeshForwarder::PrepareEmptyFrame(), and Mac::ProcessEnhAckSecurity().
GetShort()
ShortAddress GetShort (void) const inline
This method gets the address as a Short Address.
This method MUST be used only if the address type is Short Address.
Returns
The Short Address.
Referenced by Lowpan::ComputeIid(), Mac::HandleReceivedFrame(), Frame::SetDstAddr(), and Frame::SetSrcAddr().
GetExtended() [1/2]
const ExtAddress& GetExtended (void) const inline
This method gets the address as an Extended Address.
This method MUST be used only if the address type is Extended Address.
Returns
A constant reference to the Extended Address.
Referenced by Lowpan::ComputeIid(), Mac::ConvertBeaconToActiveScanResult(), InterfaceIdentifier::ConvertToMacAddress(), MeshForwarder::GetMacSourceAddress(), Mac::HandleReceivedFrame(), Mac::ProcessEnhAckSecurity(), Mac::ProcessReceiveSecurity(), Frame::SetDstAddr(), and Frame::SetSrcAddr().
GetExtended() [2/2]
ExtAddress& GetExtended (void) inline
This method gets the address as an Extended Address.
This method MUST be used only if the address type is Extended Address.
Returns
A reference to the Extended Address.
SetNone()
void SetNone (void) inline
This method sets the address to none (i.e., clears the address).
Address type will be updated to kTypeNone.
Referenced by Frame::GetDstAddr(), and Frame::GetSrcAddr().
SetShort()
void SetShort (ShortAddress aShortAddress) inline
This method sets the address with a Short Address.
The type is also updated to indicate that address is Short.
Parameters
[in] aShortAddress A Short Address
Referenced by NeighborTable::FindNeighbor(), Frame::GetDstAddr(), MeshForwarder::GetMacDestinationAddress(), MeshForwarder::GetMacSourceAddress(), DataPollSender::GetPollDestinationAddress(), Frame::GetSrcAddr(), MeshForwarder::HandleFrameRequest(), MeshForwarder::PrepareDataFrame(), DataPollSender::PrepareDataRequest(), MeshForwarder::PrepareEmptyFrame(), and MeshForwarder::UpdateIp6Route().
SetExtended() [1/2]
void SetExtended (const ExtAddress & aExtAddress) inline
This method sets the address with an Extended Address.
The type is also updated to indicate that the address is Extended.
Parameters
[in] aExtAddress An Extended Address
Referenced by InterfaceIdentifier::ConvertToMacAddress(), Frame::GetDstAddr(), DataPollSender::GetPollDestinationAddress(), Frame::GetSrcAddr(), Mac::HandleReceivedFrame(), DataPollSender::PrepareDataRequest(), MeshForwarder::PrepareEmptyFrame(), and Mac::ProcessEnhAckSecurity().
SetExtended() [2/2]
void SetExtended (const uint8_t * aBuffer, ExtAddress::CopyByteOrder aByteOrder = ExtAddress::kNormalByteOrder) inline
This method sets the address with an Extended Address given as a byte array.
The type is also updated to indicate that the address is Extended.
Parameters
[in] aBuffer Pointer to an array containing the Extended Address. OT_EXT_ADDRESS_SIZE bytes from buffer are copied to form the Extended Address.
[in] aByteOrder The byte order to copy the address from aBuffer.
IsBroadcast()
bool IsBroadcast (void) const inline
This method indicates whether or not the address is a Short Broadcast Address.
Returns
TRUE if address is Short Broadcast Address, FALSE otherwise.
Referenced by Mac::HandleReceivedFrame(), Mac::HandleTransmitDone(), MeshForwarder::PrepareDataFrame(), and Mac::RecordFrameTransmitStatus().
IsShortAddrInvalid()
bool IsShortAddrInvalid (void) const inline
This method indicates whether or not the address is a Short Invalid Address.
Returns
TRUE if address is Short Invalid Address, FALSE otherwise.
References ExtAddress::ToString().
Referenced by MeshForwarder::PrepareEmptyFrame().
ToString()
Address::InfoString ToString (void) const
This method converts an address to a null-terminated string
Returns
A String representing the address.
References StringWriter::Append(), StringWriter::AppendHexBytes(), LinkFrameCounters::Get(), otExtAddress::m8, and OT_UNUSED_VARIABLE.
Referenced by MeshForwarder::CalcFrameVersion(), and RxFrame::ProcessReceiveAesCcm().
Field Documentation
mShortAddress
ShortAddress mShortAddress
The IEEE 802.15.4 Short Address.
mExtAddress
ExtAddress mExtAddress
The IEEE 802.15.4 Extended Address.
mShared
union { ... } mShared
mType
Type mType private
The address type (Short, Extended, or none).
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale