OpenThread: Udp::Socket Class Reference
Udp::Socket Class Reference
#include <udp6.hpp>
Public Member Functions
Error Bind (const SockAddr &aSockAddr, otNetifIdentifier aNetifIdentifier=OT_NETIF_THREAD)
Error Bind (uint16_t aPort, otNetifIdentifier aNetifIdentifier=OT_NETIF_THREAD)
Error Bind (void)
Error Close (void)
Error Connect (const SockAddr &aSockAddr)
Error Connect (uint16_t aPort)
Error Connect (void)
bool IsOpen (void) const
Message * NewMessage (uint16_t aReserved, const Message::Settings &aSettings=Message::Settings::GetDefault())
Error Open (otUdpReceive aHandler, void *aContext)
Error SendTo (Message &aMessage, const MessageInfo &aMessageInfo)
Socket (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Public Member Functions inherited from Udp::SocketHandle
SockAddr & GetPeerName (void)
const SockAddr & GetPeerName (void) const
SockAddr & GetSockName (void)
const SockAddr & GetSockName (void) const
bool IsBound (void) const
Public Member Functions inherited from LinkedListEntry< SocketHandle >
const SocketHandle * GetNext (void) const
SocketHandle * GetNext (void)
void SetNext (SocketHandle *aNext)
Public Member Functions inherited from Clearable< SocketHandle >
void Clear (void)
Friends
class Udp
Additional Inherited Members
Data Fields inherited from otUdpSocket
void * mContext
A pointer to application-specific context.
void * mHandle
A handle to platform's UDP.
otUdpReceive mHandler
A function pointer to the application callback.
struct otUdpSocket * mNext
A pointer to the next UDP socket (internal use only).
otSockAddr mPeerName
The peer IPv6 socket address.
otSockAddr mSockName
The local IPv6 socket address.
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements a UDP/IPv6 socket.
Constructor & Destructor Documentation
Socket()
Socket (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to OpenThread instance.
References Clearable< SocketHandle >::Clear().
Member Function Documentation
NewMessage()
Message * NewMessage (uint16_t aReserved, const Message::Settings & aSettings = Message::Settings::GetDefault())
This method returns a new UDP message with sufficient header space reserved.
Parameters
[in] aReserved The number of header bytes to reserve after the UDP header.
[in] aSettings The message settings (default is used if not provided).
Returns
A pointer to the message or nullptr if no buffers are available.
Referenced by Mle::NewMleMessage().
Open()
Error Open (otUdpReceive aHandler, void * aContext)
This method opens the UDP socket.
Parameters
[in] aHandler A pointer to a function that is called when receiving UDP messages.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Successfully opened the socket.
kErrorFailed Failed to open the socket.
Referenced by Mle::Enable(), and Coap::Start().
IsOpen()
bool IsOpen (void) const
This method returns if the UDP socket is open.
Returns
If the UDP socket is open.
Bind() [1/3]
Error Bind (const SockAddr & aSockAddr, otNetifIdentifier aNetifIdentifier = OT_NETIF_THREAD)
This method binds the UDP socket.
Parameters
[in] aSockAddr A reference to the socket address.
[in] aNetifIdentifier The network interface identifier.
Return values
kErrorNone Successfully bound the socket.
kErrorInvalidArgs Unable to bind to Thread network interface with the given address.
kErrorFailed Failed to bind UDP Socket.
References Udp::Socket::Bind().
Referenced by Mle::Enable(), and Coap::Start().
Bind() [2/3]
Error Bind (uint16_t aPort, otNetifIdentifier aNetifIdentifier = OT_NETIF_THREAD)
This method binds the UDP socket.
Parameters
[in] aPort A port number.
[in] aNetifIdentifier The network interface identifier.
Return values
kErrorNone Successfully bound the socket.
kErrorFailed Failed to bind UDP Socket.
References Udp::Socket::Bind().
Bind() [3/3]
Error Bind (void) inline
This method binds the UDP socket.
Return values
kErrorNone Successfully bound the socket.
kErrorFailed Failed to bind UDP Socket.
References Udp::Socket::Bind(), and Udp::Connect().
Referenced by Udp::Socket::Bind().
Connect() [1/3]
Error Connect (const SockAddr & aSockAddr)
This method connects the UDP socket.
Parameters
[in] aSockAddr A reference to the socket address.
Return values
kErrorNone Successfully connected the socket.
kErrorFailed Failed to connect UDP Socket.
References Udp::Socket::Connect().
Connect() [2/3]
Error Connect (uint16_t aPort)
This method connects the UDP socket.
Parameters
[in] aPort A port number.
Return values
kErrorNone Successfully connected the socket.
kErrorFailed Failed to connect UDP Socket.
References Udp::Socket::Connect().
Connect() [3/3]
Error Connect (void) inline
This method connects the UDP socket.
Return values
kErrorNone Successfully connected the socket.
kErrorFailed Failed to connect UDP Socket.
References Udp::Close(), Udp::Socket::Connect(), and Udp::SendTo().
Referenced by Udp::Socket::Connect().
Close()
Error Close (void)
This method closes the UDP socket.
Return values
kErrorNone Successfully closed the UDP socket.
kErrorFailed Failed to close UDP Socket.
Referenced by Mle::Disable(), Coap::Start(), and Coap::Stop().
SendTo()
Error SendTo (Message & aMessage, const MessageInfo & aMessageInfo)
This method sends a UDP message.
Parameters
[in] aMessage The message to send.
[in] aMessageInfo The message info associated with aMessage.
Return values
kErrorNone Successfully sent the UDP message.
kErrorInvalidArgs If no peer is specified in aMessageInfo or by Connect().
kErrorNoBufs Insufficient available buffer to add the UDP and IPv6 headers.
References Address::IsMulticast(), ot::kErrorInvalidArgs, ot::kErrorNotImplemented, OT_UNUSED_VARIABLE, otPlatUdpJoinMulticastGroup(), otPlatUdpLeaveMulticastGroup(), and VerifyOrExit.
Referenced by Coap::Send(), and Mle::TxMessage::SendTo().
Friends And Related Function Documentation
Udp
friend class Udp friend
The documentation for this class was generated from the following files:
udp6.hpp
udp6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale