OpenThread: RouteTlv Class Reference
RouteTlv Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Member Functions
LinkQuality GetLinkQualityIn (uint8_t aRouterIndex) const
LinkQuality GetLinkQualityOut (uint8_t aRouterIndex) const
uint8_t GetRouteCost (uint8_t aRouterIndex) const
uint8_t GetRouteDataLength (void) const
const RouterIdSet & GetRouterIdMask (void) const
uint8_t GetRouterIdSequence (void) const
void Init (void)
bool IsRouterIdSet (uint8_t aRouterId) const
bool IsValid (void) const
void SetLinkQualityIn (uint8_t aRouterIndex, LinkQuality aLinkQuality)
void SetLinkQualityOut (uint8_t aRouterIndex, LinkQuality aLinkQuality)
void SetRouteCost (uint8_t aRouterIndex, uint8_t aRouteCost)
void SetRouteDataLength (uint8_t aLength)
void SetRouterIdMask (const RouterIdSet &aRouterIdSet)
void SetRouterIdSequence (uint8_t aSequence)
Public Member Functions inherited from Tlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint8_t mRouteData [kMaxRouterId+1]
RouterIdSet mRouterIdMask
uint8_t mRouterIdSequence
Static Private Attributes
static constexpr uint8_t kLinkQualityInMask = 3 << kLinkQualityInOffset
static constexpr uint8_t kLinkQualityInOffset = 4
static constexpr uint8_t kLinkQualityOutMask = 3 << kLinkQualityOutOffset
static constexpr uint8_t kLinkQualityOutOffset = 6
static constexpr uint8_t kRouteCostMask = 0xf << kRouteCostOffset
static constexpr uint8_t kRouteCostOffset = 0
Additional Inherited Members
Public Types inherited from Tlv
enum Type : uint8_t {
kSourceAddress = 0, kMode = 1, kTimeout = 2, kChallenge = 3,
kResponse = 4, kLinkFrameCounter = 5, kLinkQuality = 6, kNetworkParameter = 7,
kMleFrameCounter = 8, kRoute = 9, kAddress16 = 10, kLeaderData = 11,
kNetworkData = 12, kTlvRequest = 13, kScanMask = 14, kConnectivity = 15,
kLinkMargin = 16, kStatus = 17, kVersion = 18, kAddressRegistration = 19,
kChannel = 20, kPanId = 21, kActiveTimestamp = 22, kPendingTimestamp = 23,
kActiveDataset = 24, kPendingDataset = 25, kDiscovery = 26, kCslChannel = 80,
kCslTimeout = 85, kCslClockAccuracy = 86, kLinkMetricsQuery = 87, kLinkMetricsManagement = 88,
kLinkMetricsReport = 89, kLinkProbe = 90, kTimeRequest = 252, kTimeParameter = 253,
kXtalAccuracy = 254, kInvalid = 255
}
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< Tlv::kRoute >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements Route TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References Tlv::kRoute, Tlv::SetLength(), and Tlv::SetType().
Referenced by Mle::TxMessage::SendAfterDelay().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
GetRouterIdSequence()
uint8_t GetRouterIdSequence (void) const inline
This method returns the Router ID Sequence value.
Returns
The Router ID Sequence value.
SetRouterIdSequence()
void SetRouterIdSequence (uint8_t aSequence) inline
This method sets the Router ID Sequence value.
Parameters
[in] aSequence The Router ID Sequence value.
GetRouterIdMask()
const RouterIdSet& GetRouterIdMask (void) const inline
This method gets the Router ID Mask.
SetRouterIdMask()
void SetRouterIdMask (const RouterIdSet & aRouterIdSet) inline
This method sets the Router ID Mask.
Parameters
[in] aRouterIdSet The Router ID Mask to set.
IsRouterIdSet()
bool IsRouterIdSet (uint8_t aRouterId) const inline
This method indicates whether or not a Router ID bit is set.
Parameters
[in] aRouterId The Router ID bit.
Return values
TRUE If the Router ID bit is set.
FALSE If the Router ID bit is not set.
GetRouteDataLength()
uint8_t GetRouteDataLength (void) const inline
This method returns the Route Data Length value.
Returns
The Route Data Length value.
References Tlv::GetLength().
SetRouteDataLength()
void SetRouteDataLength (uint8_t aLength) inline
This method sets the Route Data Length value.
Parameters
[in] aLength The Route Data Length value.
References Tlv::SetLength().
GetRouteCost()
uint8_t GetRouteCost (uint8_t aRouterIndex) const inline
This method returns the Route Cost value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Route Cost value for a given Router index.
SetRouteCost()
void SetRouteCost (uint8_t aRouterIndex, uint8_t aRouteCost) inline
This method sets the Route Cost value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aRouteCost The Route Cost value.
GetLinkQualityIn()
LinkQuality GetLinkQualityIn (uint8_t aRouterIndex) const inline
This method returns the Link Quality In value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Link Quality In value for a given Router index.
SetLinkQualityIn()
void SetLinkQualityIn (uint8_t aRouterIndex, LinkQuality aLinkQuality) inline
This method sets the Link Quality In value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aLinkQuality The Link Quality In value for a given Router index.
GetLinkQualityOut()
LinkQuality GetLinkQualityOut (uint8_t aRouterIndex) const inline
This method returns the Link Quality Out value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Link Quality Out value for a given Router index.
SetLinkQualityOut()
void SetLinkQualityOut (uint8_t aRouterIndex, LinkQuality aLinkQuality) inline
This method sets the Link Quality Out value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aLinkQuality The Link Quality Out value for a given Router index.
Field Documentation
kLinkQualityOutOffset
constexpr uint8_t kLinkQualityOutOffset = 6 static private
kLinkQualityOutMask
constexpr uint8_t kLinkQualityOutMask = 3 << kLinkQualityOutOffset static private
kLinkQualityInOffset
constexpr uint8_t kLinkQualityInOffset = 4 static private
kLinkQualityInMask
constexpr uint8_t kLinkQualityInMask = 3 << kLinkQualityInOffset static private
kRouteCostOffset
constexpr uint8_t kRouteCostOffset = 0 static private
kRouteCostMask
constexpr uint8_t kRouteCostMask = 0xf << kRouteCostOffset static private
mRouterIdSequence
uint8_t mRouterIdSequence private
mRouterIdMask
RouterIdSet mRouterIdMask private
mRouteData
uint8_t mRouteData[kMaxRouterId+1] private
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale