OpenThread: RouterAdvertMessage::Header Class Reference
RouterAdvertMessage::Header Class Reference
#include <nd6.hpp>
Public Member Functions
RoutePreference GetDefaultRouterPreference (void) const
uint16_t GetRouterLifetime (void) const
Header (void)
void SetChecksum (uint16_t aChecksum)
void SetDefaultRouterPreference (RoutePreference aPreference)
void SetRouterLifetime (uint16_t aRouterLifetime)
void SetToDefault (void)
Public Member Functions inherited from Equatable< Header >
bool operator== (const Header &aOther) const
Public Member Functions inherited from Unequatable< Header >
bool operator!= (const Header &aOther) const
Private Attributes
uint16_t mChecksum
uint8_t mCode
uint8_t mCurHopLimit
uint8_t mFlags
uint32_t mReachableTime
uint32_t mRetransTimer
uint16_t mRouterLifetime
uint8_t mType
Static Private Attributes
static constexpr uint8_t kPreferenceMask = 3 << kPreferenceOffset
static constexpr uint8_t kPreferenceOffset = 3
Additional Inherited Members
Private Member Functions inherited from Clearable< Header >
void Clear (void)
Detailed Description
This class implements the RA message header.
See section 2.2 of RFC 4191 [https://datatracker.ietf.org/doc/html/rfc4191]
Constructor & Destructor Documentation
Header()
Header (void) inline
This constructor initializes the Router Advertisement message with zero router lifetime, reachable time and retransmission timer.
Member Function Documentation
SetToDefault()
void SetToDefault (void)
This method sets the RA message to default values.
References Icmp::Header::kTypeRouterAdvert, Option::mType, and OT_UNUSED_VARIABLE.
SetChecksum()
void SetChecksum (uint16_t aChecksum) inline
This method sets the checksum value.
Parameters
[in] aChecksum The checksum value.
References ot::Encoding::BigEndian::HostSwap16().
SetRouterLifetime()
void SetRouterLifetime (uint16_t aRouterLifetime) inline
This method sets the Router Lifetime in seconds.
Parameters
[in] aRouterLifetime The router lifetime in seconds.
References ot::Encoding::BigEndian::HostSwap16().
GetRouterLifetime()
uint16_t GetRouterLifetime (void) const inline
This method gets the Router Lifetime (in seconds).
Router Lifetime set to zero indicates that the sender is not a default router.
Returns
The router lifetime in seconds.
References ot::Encoding::BigEndian::HostSwap16().
SetDefaultRouterPreference()
void SetDefaultRouterPreference (RoutePreference aPreference)
This method sets the default router preference.
Parameters
[in] aPreference The router preference.
References ot::NetworkData::RoutePreferenceToValue().
GetDefaultRouterPreference()
RoutePreference GetDefaultRouterPreference (void) const
This method gets the default router preference.
Returns
The router preference.
References ot::NetworkData::RoutePreferenceFromValue().
Field Documentation
kPreferenceOffset
constexpr uint8_t kPreferenceOffset = 3 static private
kPreferenceMask
constexpr uint8_t kPreferenceMask = 3 << kPreferenceOffset static private
mType
uint8_t mType private
mCode
uint8_t mCode private
mChecksum
uint16_t mChecksum private
mCurHopLimit
uint8_t mCurHopLimit private
mFlags
uint8_t mFlags private
mRouterLifetime
uint16_t mRouterLifetime private
mReachableTime
uint32_t mReachableTime private
mRetransTimer
uint32_t mRetransTimer private
The documentation for this class was generated from the following files:
nd6.hpp
nd6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale