OpenThread: ThreadRouterMaskTlv Class Reference
ThreadRouterMaskTlv Class Reference
#include <thread_tlvs.hpp>
Public Member Functions
const Mle::RouterIdSet & GetAssignedRouterIdMask (void) const
uint8_t GetIdSequence (void) const
void Init (void)
bool IsValid (void) const
void SetAssignedRouterIdMask (const Mle::RouterIdSet &aRouterIdSet)
void SetIdSequence (uint8_t aSequence)
Public Member Functions inherited from ThreadTlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
Mle::RouterIdSet mAssignedRouterIdMask
uint8_t mIdSequence
Additional Inherited Members
Public Types inherited from ThreadTlv
enum Type : uint8_t {
kTarget = 0, kExtMacAddress = 1, kRloc16 = 2, kMeshLocalEid = 3,
kStatus = 4, kLastTransactionTime = 6, kRouterMask = 7, kNdOption = 8,
kNdData = 9, kThreadNetworkData = 10, kTimeout = 11, kNetworkName = 12,
kIp6Addresses = 14, kCommissionerSessionId = 15
}
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< ThreadTlv::kRouterMask >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements Router Mask TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References ThreadTlv::kRouterMask, Tlv::SetLength(), and ThreadTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
GetIdSequence()
uint8_t GetIdSequence (void) const inline
This method returns the ID Sequence value.
Returns
The ID Sequence value.
SetIdSequence()
void SetIdSequence (uint8_t aSequence) inline
This method sets the ID Sequence value.
Parameters
[in] aSequence The ID Sequence value.
GetAssignedRouterIdMask()
const Mle::RouterIdSet& GetAssignedRouterIdMask (void) const inline
This method gets the Assigned Router ID Mask.
Returns
The Assigned Router ID Mask.
SetAssignedRouterIdMask()
void SetAssignedRouterIdMask (const Mle::RouterIdSet & aRouterIdSet) inline
This method sets the Assigned Router ID Mask.
Parameters
[in] aRouterIdSet A reference to the Assigned Router ID Mask.
Field Documentation
mIdSequence
uint8_t mIdSequence private
mAssignedRouterIdMask
Mle::RouterIdSet mAssignedRouterIdMask private
The documentation for this class was generated from the following file:
thread_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale