OpenThread: Url Class Reference
Url Class Reference
#include <url.hpp>
Public Member Functions
const char * GetPath (void) const
const char * GetProtocol (void) const
const char * GetValue (const char *aName, const char *aLastValue=nullptr) const
otError Init (char *aUrl)
Additional Inherited Members
Data Fields inherited from otUrl
const char * mEnd
The end of the URL buffer.
const char * mPath
The path.
const char * mProtocol
The URL protocol.
const char * mQuery
The start of the URL query string.
Detailed Description
This class implements the URL processing.
Member Function Documentation
Init()
otError Init (char * aUrl)
This method initializes the URL.
Parameters
[in] aUrl A buffer stores the null-terminated URL string.
Return values
OT_ERROR_NONE Successfully parsed the URL.
OT_ERROR_PARSE Failed to parse the string as a URL.
References otUrl::mEnd, otUrl::mPath, otUrl::mProtocol, otUrl::mQuery, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by RadioUrl::RadioUrl().
GetPath()
const char* GetPath (void) const inline
This method gets the path in URL.
Returns
The path in URL.
References otUrl::mPath.
Referenced by HdlcInterface::ForkPty(), HdlcInterface::Init(), HdlcInterface::OpenFile(), and Radio::Radio().
GetValue()
const char * GetValue (const char * aName, const char * aLastValue = nullptr) const
This method gets the value of parameter aName.
Parameters
[in] aName The parameter name.
[in] aLastValue The last iterated parameter value, nullptr for the first value.
Returns
The parameter value.
References ExitNow, otUrl::mEnd, otUrl::mQuery, and VerifyOrExit.
Referenced by HdlcInterface::ForkPty(), Radio::Init(), and HdlcInterface::OpenFile().
GetProtocol()
const char* GetProtocol (void) const inline
This method returns the URL protocol.
Returns
The URL protocol.
References otUrl::mProtocol.
Referenced by get802154RadioUrl().
The documentation for this class was generated from the following files:
url.hpp
url.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale