OpenThread: Option::Iterator Class Reference
Option::Iterator Class Reference
Public Member Functions
Iterator (void)
Iterator (const void *aStart, const void *aEnd)
const Option & operator* (void)
void operator++ (void)
void operator++ (int)
bool operator== (const Iterator &aOther) const
Public Member Functions inherited from Unequatable< Iterator >
bool operator!= (const Iterator &aOther) const
Private Member Functions
void Advance (void)
const Option * Validate (const Option *aOption) const
Static Private Member Functions
static const Option * Next (const Option *aOption)
Private Attributes
const Option * mEnd
const Option * mOption
Constructor & Destructor Documentation
Iterator() [1/2]
Iterator (void)
Iterator() [2/2]
Iterator (const void * aStart, const void * aEnd)
References Option::Iterator::mOption, and Option::Iterator::Validate().
Member Function Documentation
operator*()
const Option& operator* (void) inline
References Option::Iterator::mOption.
operator++() [1/2]
void operator++ (void) inline
References Option::Iterator::Advance().
operator++() [2/2]
void operator++ (int) inline
References Option::Iterator::Advance().
operator==()
bool operator== (const Iterator & aOther) const inline
References Option::Iterator::Advance(), Option::Iterator::mOption, Option::Iterator::Next(), and Option::Iterator::Validate().
Next()
const Option * Next (const Option * aOption) static private
References Option::GetSize().
Referenced by Option::Iterator::Advance(), Option::Iterator::operator==(), and Option::Iterator::Validate().
Advance()
void Advance (void) private
References Option::Iterator::mOption, Option::Iterator::Next(), and Option::Iterator::Validate().
Referenced by Option::Iterator::operator++(), and Option::Iterator::operator==().
Validate()
const Option * Validate (const Option * aOption) const private
References Option::IsValid(), Option::Iterator::mEnd, and Option::Iterator::Next().
Referenced by Option::Iterator::Advance(), Option::Iterator::Iterator(), and Option::Iterator::operator==().
Field Documentation
mOption
const Option* mOption private
Referenced by Option::Iterator::Advance(), Option::Iterator::Iterator(), Option::Iterator::operator*(), and Option::Iterator::operator==().
mEnd
const Option* mEnd private
Referenced by Option::Iterator::Validate().
The documentation for this class was generated from the following files:
nd6.hpp
nd6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale