OpenThread: AddressRegistrationEntry Class Reference
AddressRegistrationEntry Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Member Functions
uint8_t GetContextId (void) const
const Ip6::InterfaceIdentifier & GetIid (void) const
const Ip6::Address & GetIp6Address (void) const
uint8_t GetLength (void) const
bool IsCompressed (void) const
void SetContextId (uint8_t aContextId)
void SetIid (const Ip6::InterfaceIdentifier &aIid)
void SetIp6Address (const Ip6::Address &aAddress)
void SetUncompressed (void)
Private Attributes
uint8_t mControl
union {
Ip6::InterfaceIdentifier mIid
Ip6::Address mIp6Address
} OT_TOOL_PACKED_FIELD
Static Private Attributes
static constexpr uint8_t kCidMask = 0xf
static constexpr uint8_t kCompressed = 1 << 7
Detailed Description
This class implements Source Address TLV generation and parsing.
Member Function Documentation
GetLength()
uint8_t GetLength (void) const inline
This method returns the IPv6 address or IID length.
Returns
The IPv6 address length if the Compressed bit is clear, or the IID length if the Compressed bit is set.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), and Mle::TxMessage::SendAfterDelay().
IsCompressed()
bool IsCompressed (void) const inline
This method indicates whether or not the Compressed flag is set.
Return values
TRUE If the Compressed flag is set.
FALSE If the Compressed flag is not set.
SetUncompressed()
void SetUncompressed (void) inline
This method sets the Uncompressed flag.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), and Mle::TxMessage::SendAfterDelay().
GetContextId()
uint8_t GetContextId (void) const inline
This method returns the Context ID for the compressed form.
Returns
The Context ID value.
SetContextId()
void SetContextId (uint8_t aContextId) inline
This method sets the Context ID value.
Parameters
[in] aContextId The Context ID value.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), and Mle::TxMessage::SendAfterDelay().
GetIid()
const Ip6::InterfaceIdentifier& GetIid (void) const inline
This method returns the IID value.
Returns
The IID value.
SetIid()
void SetIid (const Ip6::InterfaceIdentifier & aIid) inline
This method sets the IID value.
Parameters
[in] aIid The IID value.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), and Mle::TxMessage::SendAfterDelay().
GetIp6Address()
const Ip6::Address& GetIp6Address (void) const inline
This method returns the IPv6 Address value.
Returns
The IPv6 Address value.
SetIp6Address()
void SetIp6Address (const Ip6::Address & aAddress) inline
This method sets the IPv6 Address value.
Parameters
[in] aAddress A reference to the IPv6 Address value.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), and Mle::TxMessage::SendAfterDelay().
Field Documentation
kCompressed
constexpr uint8_t kCompressed = 1 << 7 static private
kCidMask
constexpr uint8_t kCidMask = 0xf static private
mControl
uint8_t mControl private
mIid
Ip6::InterfaceIdentifier mIid
mIp6Address
Ip6::Address mIp6Address
OT_TOOL_PACKED_FIELD
union { ... } OT_TOOL_PACKED_FIELD
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale