OpenThread: MutableData< kDataLengthType > Class Template Reference
MutableData< kDataLengthType > Class Template Reference
#include <data.hpp>
Public Types
using LengthType = typename Base::LengthType
Public Types inherited from Data< kDataLengthType >
using LengthType = typename TypeTraits::Conditional< kDataLengthType==kWithUint8Length, uint8_t, uint16_t >::Type
Public Member Functions
void ClearBytes (void)
Error CopyBytesFrom (const uint8_t *aBuffer, LengthType aLength)
Error CopyBytesFrom (const Data< kDataLengthType > &aData)
uint8_t * GetBytes (void)
const uint8_t * GetBytes (void) const
void Init (void *aBuffer, LengthType aLength)
void InitFormRange (uint8_t *aStart, uint8_t *aEnd)
template<typename ObjectType >
void InitFrom (ObjectType &aObject)
Public Member Functions inherited from Data< kDataLengthType >
void CopyBytesTo (void *aBuffer) const
const uint8_t * GetBytes (void) const
LengthType GetLength (void) const
void Init (const void *aBuffer, LengthType aLength)
template<typename ObjectType >
void InitFrom (const ObjectType &aObject)
void InitFromRange (const uint8_t *aStart, const uint8_t *aEnd)
bool MatchesBytesIn (const void *aBuffer) const
bool MatchesBytesIn (const void *aBuffer, ByteMatcher aMatcher)
bool operator== (const Data &aOtherData) const
void SetLength (LengthType aLength)
bool StartsWith (const Data &aOtherData) const
Public Member Functions inherited from Clearable< Data< kDataLengthType > >
void Clear (void)
Public Member Functions inherited from Unequatable< Data< kDataLengthType > >
bool operator!= (const Data< kDataLengthType > &aOther) const
Private Types
using Base = Data< kDataLengthType >
Detailed Description
template<DataLengthType kDataLengthType>
class ot::MutableData< kDataLengthType >
This type represents a generic MutableData which is simply a wrapper over a pointer to a buffer with a given data length.
It inherits from Data but unlike Data which treats its buffer content as immutable, MutableData allows its data buffer content to be changed.
A MutableData instance MUST be initialized (using any of the Init() methods) before calling any other methods (e.g., GetBytes() or GetLength()), otherwise the behavior is undefined.
Member Typedef Documentation
Base
using Base = Data<kDataLengthType> private
LengthType
using LengthType = typename Base::LengthType
This type represents the data length type (uint8_t or uint16_t).
Member Function Documentation
Init()
void Init (void * aBuffer, LengthType aLength) inline
This method initializes the MutableData to point to a given buffer with a given length.
Parameters
[in] aBuffer A pointer to a buffer containing the data.
[in] aLength The data length (number of bytes in aBuffer)
Referenced by NameData::CopyTo(), Data::Data(), Data::Free(), Data::TakeFrom(), and Data::UpdateBuffer().
InitFormRange()
void InitFormRange (uint8_t * aStart, uint8_t * aEnd) inline
This method initializes the MutableData to point to a range of bytes in a given buffer.
The range is specified by the pointers to its start aStart and its end aEnd. Data will point to the bytes in the buffer from aStart up to but excluding aEnd (i.e., aStart <= bytes < aEnd).
Parameters
[in] aStart Pointer to the start of the range.
[in] aEnd Pointer to the end of the range.
InitFrom()
void InitFrom (ObjectType & aObject) inline
This template method initializes the MutableData to point to the content of an object.
ObjectType The object type (MUST not be a pointer type).
Parameters
[in] aObject The object to initialize the MutableData with.
GetBytes() [1/2]
uint8_t* GetBytes (void) inline
This method returns a pointer to the data bytes buffer.
Returns
A pointer to the data bytes buffer (can be nullptr if Data is empty or uninitialized).
Referenced by TxtEntry::AppendEntries(), Data::CopyBytesTo(), Data::Free(), Data::GetBytes(), Data::IsNull(), Data::SetFrom(), Data::TakeFrom(), and Data::UpdateBuffer().
GetBytes() [2/2]
const uint8_t* GetBytes (void) const inline
This method returns a pointer to the data bytes buffer.
Returns
A pointer to the data bytes buffer (can be nullptr if Data is empty or uninitialized).
ClearBytes()
void ClearBytes (void) inline
This method clears all the bytes (sets them to zero) in the buffer pointed by the MutableData.
Referenced by NameData::CopyTo().
CopyBytesFrom() [1/2]
Error CopyBytesFrom (const uint8_t * aBuffer, LengthType aLength) inline
This method copies the bytes from a given buffer into the MutableData buffer.
If the current MutableData length is larger than or equal to aLength, then all the bytes are copied from aBuffer into the buffer of MutableData and the MutableData's length is changed to aLength.
If the current MutableData length is smaller than aLength, then the method returns kErrorNoBufs but still copies as many bytes as can fit.
Parameters
[in] aBuffer A pointer to a buffer to copy from.
[in] aLength The length of aBuffer (number of bytes).
Return values
kErrorNone Successfully copied the bytes into MutableData buffer and adjusted its length.
kErrorNoBufs MutableData buffer cannot fit the given aLength bytes.
Referenced by NameData::CopyTo(), and Data::SetFrom().
CopyBytesFrom() [2/2]
Error CopyBytesFrom (const Data< kDataLengthType > & aData) inline
This method copies the bytes from an given Data instance into the MutableData buffer.
If the current MutableData length is larger than or equal to the aData length, then all the bytes are copied from aData into the buffer of MutableData and the MutableData's length is adjusted accordingly.
If the current MutableData length is smaller than aData length, then as many bytes as can fit are copied and the method returns kErrorNoBufs.
Parameters
[in] aData A Data instance to copy the content from.
Return values
kErrorNone Successfully copied the bytes into MutableData buffer and adjusted its length.
kErrorNoBufs MutableData buffer cannot fit the given aData bytes.
The documentation for this class was generated from the following file:
data.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale