OpenThread: LinkFrameCounters Class Reference
LinkFrameCounters Class Reference
Core-mac
#include <mac_types.hpp>
Public Member Functions
uint32_t Get (void) const void Set(uint32_t aCounter) uint32_t GetMaximum(void) const
void Reset (void)
void SetAll (uint32_t aCounter)
Detailed Description
This class represents Link Frame Counters for all supported radio links.
Member Function Documentation
Reset()
void Reset (void) inline
This method resets all counters (set them all to zero).
References ExtAddress::Set().
Referenced by Mle::HandleUdpReceive(), KeyManager::KeyManager(), and KeyManager::ResetFrameCounters().
Get()
uint32_t Get (void) const
This method gets the Link Frame Counter value.
Returns
The Link Frame Counter value. This method sets the Link Frame Counter for a given radio link.
Parameters
[in] aCounter The new counter value. This method gets the maximum Link Frame Counter among all supported radio links.
Returns
The maximum Link frame Counter among all supported radio links.
Referenced by Mac::ProcessReceiveSecurity(), and Address::ToString().
SetAll()
void SetAll (uint32_t aCounter)
This method sets the Link Frame Counter value for all radio links.
Parameters
[in] aCounter The Link Frame Counter value.
References VerifyOrExit.
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), and KeyManager::SetAllMacFrameCounters().
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale