OpenThread: RssAverager Class Reference
RssAverager Class Reference
Core-link-quality
#include <link_quality.hpp>
Public Types
typedef String< kStringSize > InfoString
Public Member Functions
Error Add (int8_t aRss)
int8_t GetAverage (void) const
uint16_t GetRaw (void) const
bool HasAverage (void) const
InfoString ToString (void) const
Public Member Functions inherited from Clearable< RssAverager >
void Clear (void)
Static Public Attributes
static constexpr uint16_t kStringSize = 10
Max string size for average (.
Private Attributes
uint16_t mAverage: 11
uint16_t mCount: 5
Static Private Attributes
static constexpr uint8_t kCoeffBitShift = 3
static constexpr uint8_t kPrecision = (1 << kPrecisionBitShift)
static constexpr uint8_t kPrecisionBitMask = (kPrecision - 1)
static constexpr uint8_t kPrecisionBitShift = 3
Detailed Description
This class implements a Received Signal Strength (RSS) averager.
The average is maintained using an adaptive exponentially weighted moving filter.
Member Typedef Documentation
InfoString
typedef String<kStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Function Documentation
HasAverage()
bool HasAverage (void) const inline
This method indicates whether the averager contains an average (i.e., at least one RSS value has been added).
Return values
true If the average value is available (at least one RSS value has been added).
false Averager is empty (no RSS value added yet).
Add()
Error Add (int8_t aRss)
This method adds a received signal strength (RSS) value to the average.
If aRss is OT_RADIO_RSSI_INVALID, it is ignored and error status kErrorInvalidArgs is returned. The value of RSS is capped at 0dBm (i.e., for any given RSS value higher than 0dBm, 0dBm is used instead).
Parameters
[in] aRss Received signal strength value (in dBm) to be added to the average.
Return values
kErrorNone New RSS value added to average successfully.
kErrorInvalidArgs Value of aRss is OT_RADIO_RSSI_INVALID.
References ot::kErrorInvalidArgs, ot::kErrorNone, OT_RADIO_RSSI_INVALID, and VerifyOrExit.
Referenced by Message::AddRss(), and Message::GetRssAverager().
GetAverage()
int8_t GetAverage (void) const
This method returns the current average signal strength value maintained by the averager.
Returns
The current average value (in dBm) or OT_RADIO_RSSI_INVALID if no average is available.
References OT_RADIO_RSSI_INVALID, and VerifyOrExit.
GetRaw()
uint16_t GetRaw (void) const inline
This method returns an raw/encoded version of current average signal strength value. The raw value is the average multiplied by a precision factor (currently set as -8).
Returns
The current average multiplied by precision factor or zero if no average is available.
ToString()
RssAverager::InfoString ToString (void) const
This method converts the current average RSS value to a human-readable string (e.g., "-80.375"). If the average is unknown, empty string is returned.
Returns
An InfoString object containing the string representation of average RSS.
References VerifyOrExit.
Referenced by MeshForwarder::CalcFrameVersion().
Field Documentation
kStringSize
constexpr uint16_t kStringSize = 10 static
Max string size for average (.
See also
ToString()).
kPrecisionBitShift
constexpr uint8_t kPrecisionBitShift = 3 static private
kPrecision
constexpr uint8_t kPrecision = (1 << kPrecisionBitShift) static private
kPrecisionBitMask
constexpr uint8_t kPrecisionBitMask = (kPrecision - 1) static private
kCoeffBitShift
constexpr uint8_t kCoeffBitShift = 3 static private
mAverage
uint16_t mAverage private
mCount
uint16_t mCount private
The documentation for this class was generated from the following files:
link_quality.hpp
link_quality.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale