OpenThread: SubMac::Callbacks Class Reference
SubMac::Callbacks Class Reference
#include <sub_mac.hpp>
Public Member Functions
Callbacks (Instance &aInstance)
void EnergyScanDone (int8_t aMaxRssi)
void FrameCounterUsed (uint32_t aFrameCounter)
void ReceiveDone (RxFrame *aFrame, Error aError)
void RecordCcaStatus (bool aCcaSuccess, uint8_t aChannel)
void RecordFrameTransmitStatus (const TxFrame &aFrame, const RxFrame *aAckFrame, Error aError, uint8_t aRetryCount, bool aWillRetx)
void TransmitDone (TxFrame &aFrame, RxFrame *aAckFrame, Error aError)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class defines the callbacks notifying SubMac user of changes and events.
Constructor & Destructor Documentation
Callbacks()
Callbacks (Instance & aInstance) explicit
This constructor initializes the Callbacks object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References SubMac::Callbacks::EnergyScanDone(), SubMac::Callbacks::FrameCounterUsed(), SubMac::HandleTransmitDone(), OT_UNUSED_VARIABLE, SubMac::Callbacks::ReceiveDone(), SubMac::Callbacks::RecordCcaStatus(), SubMac::Callbacks::RecordFrameTransmitStatus(), and SubMac::Callbacks::TransmitDone().
Member Function Documentation
ReceiveDone()
void ReceiveDone (RxFrame * aFrame, Error aError)
This method notifies user of SubMac of a received frame.
Parameters
[in] aFrame A pointer to the received frame or nullptr if the receive operation failed.
[in] aError kErrorNone when successfully received a frame, kErrorAbort when reception was aborted and a frame was not received, kErrorNoBufs when a frame could not be received due to lack of rx buffer space.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleReceiveDone().
RecordCcaStatus()
void RecordCcaStatus (bool aCcaSuccess, uint8_t aChannel)
This method notifies user of SubMac of CCA status (success/failure) for a frame transmission attempt.
This is intended for updating counters, logging, and/or tracking CCA failure rate statistics.
Parameters
[in] aCcaSuccess TRUE if the CCA succeeded, FALSE otherwise.
[in] aChannel The channel on which CCA was performed.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleTransmitDone().
RecordFrameTransmitStatus()
void RecordFrameTransmitStatus (const TxFrame & aFrame, const RxFrame * aAckFrame, Error aError, uint8_t aRetryCount, bool aWillRetx)
This method notifies user of SubMac of the status of a frame transmission attempt.
This is intended for updating counters, logging, and/or collecting statistics.
Note
Unlike TransmitDone which is invoked after all re-transmission attempts to indicate the final status of a frame transmission, this method is invoked on all frame transmission attempts.
Parameters
[in] aFrame The transmitted frame.
[in] aAckFrame A pointer to the ACK frame, or nullptr if no ACK was received.
[in] aError kErrorNone when the frame was transmitted successfully, kErrorNoAck when the frame was transmitted but no ACK was received, kErrorChannelAccessFailure tx failed due to activity on the channel, kErrorAbort when transmission was aborted for other reasons.
[in] aRetryCount Current retry count. This is valid only when sub-mac handles frame re-transmissions.
[in] aWillRetx Indicates whether frame will be retransmitted or not. This is applicable only when there was an error in current transmission attempt.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleTransmitDone().
TransmitDone()
void TransmitDone (TxFrame & aFrame, RxFrame * aAckFrame, Error aError)
The method notifies user of SubMac that the transmit operation has completed, providing, if applicable, the received ACK frame.
Parameters
[in] aFrame The transmitted frame.
[in] aAckFrame A pointer to the ACK frame, nullptr if no ACK was received.
[in] aError kErrorNone when the frame was transmitted, kErrorNoAck when the frame was transmitted but no ACK was received, kErrorChannelAccessFailure tx failed due to activity on the channel, kErrorAbort when transmission was aborted for other reasons.
Referenced by SubMac::Callbacks::Callbacks(), SubMac::HandleTransmitDone(), and SubMac::Send().
EnergyScanDone()
void EnergyScanDone (int8_t aMaxRssi)
This method notifies user of SubMac that energy scan is complete.
Parameters
[in] aMaxRssi Maximum RSSI seen on the channel, or SubMac::kInvalidRssiValue if failed.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleEnergyScanDone().
FrameCounterUsed()
void FrameCounterUsed (uint32_t aFrameCounter)
This method notifies user of SubMac that a specific MAC frame counter is used for transmission.
It is possible that this callback is invoked out of order in terms of counter values (i.e., called for a smaller counter value after a call for a larger counter value).
Parameters
[in] aFrameCounter The MAC frame counter value which was used.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::SignalFrameCounterUsed().
The documentation for this class was generated from the following files:
sub_mac.hpp
sub_mac_callbacks.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale