OpenThread: AnnounceSenderBase Class Reference
AnnounceSenderBase Class Reference
#include <announce_sender.hpp>
Protected Member Functions
AnnounceSenderBase (Instance &aInstance, Timer::Handler aHandler)
const Mac::ChannelMask GetChannelMask (void) const
uint16_t GetJitter (void) const
uint32_t GetPeriod (void) const
uint8_t GetStartingChannel (void) const
void HandleTimer (void)
bool IsRunning (void) const
void SendAnnounce (uint8_t aCount)
void SetChannelMask (Mac::ChannelMask aChannelMask)
void SetJitter (uint16_t aJitter)
void SetPeriod (uint32_t aPeriod)
void SetStartingChannel (uint8_t aStartingChannel)
void Stop (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Static Protected Attributes
static constexpr uint8_t kChannelIteratorFirst = Mac::ChannelMask::kChannelIteratorFirst
Private Member Functions
void SelectStartingChannel (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
uint8_t mChannel
Mac::ChannelMask mChannelMask
uint8_t mCount
uint16_t mJitter
uint32_t mPeriod
uint8_t mStartingChannel
TimerMilli mTimer
Additional Inherited Members
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Detailed Description
This class implements the base class for an AnnounceSender and AnnounceBeginSever.
This class provides APIs to schedule periodic transmission of MLE Announcement messages for a given number transmissions per channel.
Constructor & Destructor Documentation
AnnounceSenderBase()
AnnounceSenderBase (Instance & aInstance, Timer::Handler aHandler) protected
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aHandler A timer handler provided by sub-class.
Referenced by AnnounceSenderBase::HandleTimer().
Member Function Documentation
SendAnnounce()
void SendAnnounce (uint8_t aCount) protected
This method schedules the MLE Announce transmissions.
This method requests aCount additional MLE transmission cycles to be scheduled. Each cycle covers all the channels in the specified channel mask from GetChannelMask(), with GetPeriod() as the time interval between any two successive MLE Announcement transmissions (possibly) on different channels from the mask. The GetJitter() value is used to add a random interval from [-jitter, jitter] to each period interval.
If a "starting channel" is specified using SetStartingChannel(), then the cycle starts with MLE Announce transmission on the given starting channel. Otherwise the cycle starts with the first channel (with smallest channel number) in the mask.
If a previously requested MLE Announce transmission is still ongoing, a subsequent call to this method adds the aCount cycles to the schedule.
If there is no active MLE Announce transmission, after call to SendAnnounce(), the first MLE Announce transmission happens within a short random interval selected from range [0, jitter].
Parameters
[in] aCount The number of cycles to schedule.
References ExitNow, ot::Random::NonCrypto::GetUint32InRange(), ChannelMask::IsEmpty(), AnnounceSenderBase::IsRunning(), AnnounceSenderBase::mChannel, AnnounceSenderBase::mChannelMask, AnnounceSenderBase::mCount, AnnounceSenderBase::mJitter, AnnounceSenderBase::mPeriod, AnnounceSenderBase::mStartingChannel, AnnounceSenderBase::mTimer, AnnounceSenderBase::SelectStartingChannel(), TimerMilli::Start(), and VerifyOrExit.
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceBeginServer::SendAnnounce().
Stop()
void Stop (void) protected
This method stops the ongoing MLE Announce transmissions.
References AnnounceSenderBase::mCount, AnnounceSenderBase::mTimer, and TimerMilli::Stop().
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SetChannelMask().
IsRunning()
bool IsRunning (void) const inline protected
This method indicates whether a previously scheduled MLE Announce transmission is currently in progress or is finished.
Returns
TRUE if the MLE Announce transmission is in progress, FALSE otherwise.
References Timer::IsRunning(), and AnnounceSenderBase::mTimer.
Referenced by AnnounceSenderBase::SendAnnounce().
GetPeriod()
uint32_t GetPeriod (void) const inline protected
This method gets the period interval.
Returns
The period interval (in milliseconds).
References AnnounceSenderBase::mPeriod.
Referenced by AnnounceSenderBase::HandleTimer().
SetPeriod()
void SetPeriod (uint32_t aPeriod) inline protected
This method sets the period interval.
The period along with jitter value from (Get/SetJitter()) determines the interval between two successive MLE Announcement transmissions (possibly) on different channels from the specified channel mask.
Parameters
[in] aPeriod The period interval (in milliseconds).
References AnnounceSenderBase::mPeriod.
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceBeginServer::SendAnnounce().
GetJitter()
uint16_t GetJitter (void) const inline protected
This method gets the current jitter interval.
Returns
The jitter interval (in milliseconds).
References AnnounceSenderBase::mJitter.
SetJitter()
void SetJitter (uint16_t aJitter) inline protected
This method sets the jitter interval.
Parameters
[in] aJitter The jitter interval (in milliseconds).
References AnnounceSenderBase::mJitter.
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceBeginServer::SendAnnounce().
GetChannelMask()
const Mac::ChannelMask GetChannelMask (void) const inline protected
This method gets the channel mask.
Returns
The channel mask.
References AnnounceSenderBase::mChannelMask, and AnnounceSenderBase::SetChannelMask().
Referenced by AnnounceSenderBase::HandleTimer().
SetChannelMask()
void SetChannelMask (Mac::ChannelMask aChannelMask) protected
This method sets the channel mask.
Parameters
[in] aChannelMask The channel mask.
References ChannelMask::Intersect(), ChannelMask::IsEmpty(), AnnounceSenderBase::mChannelMask, AnnounceSenderBase::SelectStartingChannel(), AnnounceSenderBase::Stop(), and VerifyOrExit.
Referenced by AnnounceSenderBase::GetChannelMask(), AnnounceSenderBase::HandleTimer(), and AnnounceBeginServer::SendAnnounce().
GetStartingChannel()
uint8_t GetStartingChannel (void) const inline protected
This method gets the starting channel, i.e., the first channel in a TX cycle to send MLE Announcement on.
Returns
The current starting channel.
References AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::mStartingChannel, AnnounceSenderBase::SelectStartingChannel(), and AnnounceSenderBase::SetStartingChannel().
Referenced by AnnounceSenderBase::HandleTimer().
SetStartingChannel()
void SetStartingChannel (uint8_t aStartingChannel) protected
This method sets the starting channel, i.e., the first channel in a TX cycle to send MLE Announcement on.
aStartingChannel MUST be present in the current channel mask (from GetChannelMask()), otherwise it is ignored and an MLE transmission cycle starts with the first channel (with smallest channel number) in the channel mask.
Parameters
[in] aStartingChannel The starting channel.
References AnnounceSenderBase::mStartingChannel, and AnnounceSenderBase::SelectStartingChannel().
Referenced by AnnounceSenderBase::GetStartingChannel(), and AnnounceSenderBase::HandleTimer().
HandleTimer()
void HandleTimer (void) protected
This method is the timer handler and must be invoked by sub-class when the timer expires from the aHandler callback function provided in the constructor.
References ot::Random::NonCrypto::AddJitter(), AnnounceSenderBase::AnnounceSenderBase(), Events::Contains(), ExitNow, GetProvider< InstanceGetProvider >::Get(), AnnounceSenderBase::GetChannelMask(), ChannelMask::GetNextChannel(), ChannelMask::GetNumberOfChannels(), AnnounceSenderBase::GetPeriod(), AnnounceSenderBase::GetStartingChannel(), ChannelMask::IsEmpty(), AnnounceSenderBase::kChannelIteratorFirst, ot::kErrorNone, ot::kEventActiveDatasetChanged, ot::kEventThreadChannelChanged, ot::kEventThreadRoleChanged, TrickleTimer::kModeTrickle, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, LogInfo, AnnounceSenderBase::mChannel, AnnounceSenderBase::mChannelMask, AnnounceSenderBase::mCount, AnnounceSenderBase::mJitter, AnnounceSenderBase::mPeriod, AnnounceSenderBase::mStartingChannel, AnnounceSenderBase::mTimer, OT_FALL_THROUGH, AnnounceSenderBase::SendAnnounce(), AnnounceSenderBase::SetChannelMask(), AnnounceSenderBase::SetJitter(), AnnounceSenderBase::SetPeriod(), AnnounceSenderBase::SetStartingChannel(), TimerMilli::Start(), AnnounceSenderBase::Stop(), SuccessOrExit, and VerifyOrExit.
Referenced by AnnounceSenderBase::GetStartingChannel(), and AnnounceBeginServer::HandleTimer().
SelectStartingChannel()
void SelectStartingChannel (void) private
References ChannelMask::ContainsChannel(), ChannelMask::GetNextChannel(), IgnoreError(), ChannelMask::IsEmpty(), AnnounceSenderBase::kChannelIteratorFirst, AnnounceSenderBase::mChannelMask, AnnounceSenderBase::mStartingChannel, and VerifyOrExit.
Referenced by AnnounceSenderBase::GetStartingChannel(), AnnounceSenderBase::SendAnnounce(), AnnounceSenderBase::SetChannelMask(), and AnnounceSenderBase::SetStartingChannel().
Field Documentation
kChannelIteratorFirst
constexpr uint8_t kChannelIteratorFirst = Mac::ChannelMask::kChannelIteratorFirst static protected
This constant defines the special channel value to start from the first channel in the channel mask.
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SelectStartingChannel().
mChannelMask
Mac::ChannelMask mChannelMask private
Referenced by AnnounceSenderBase::GetChannelMask(), AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::SelectStartingChannel(), AnnounceSenderBase::SendAnnounce(), and AnnounceSenderBase::SetChannelMask().
mPeriod
uint32_t mPeriod private
Referenced by AnnounceSenderBase::GetPeriod(), AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::SendAnnounce(), and AnnounceSenderBase::SetPeriod().
mJitter
uint16_t mJitter private
Referenced by AnnounceSenderBase::GetJitter(), AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::SendAnnounce(), and AnnounceSenderBase::SetJitter().
mCount
uint8_t mCount private
Referenced by AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::SendAnnounce(), and AnnounceSenderBase::Stop().
mChannel
uint8_t mChannel private
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SendAnnounce().
mStartingChannel
uint8_t mStartingChannel private
Referenced by AnnounceSenderBase::GetStartingChannel(), AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::SelectStartingChannel(), AnnounceSenderBase::SendAnnounce(), and AnnounceSenderBase::SetStartingChannel().
mTimer
TimerMilli mTimer private
Referenced by AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::IsRunning(), AnnounceSenderBase::SendAnnounce(), and AnnounceSenderBase::Stop().
The documentation for this class was generated from the following files:
announce_sender.hpp
announce_sender.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale