OpenThread: HeaderIe Class Reference
HeaderIe Class Reference
Core-mac
#include <mac_frame.hpp>
Data Structures
union OT_TOOL_PACKED_FIELD
Public Member Functions
uint16_t GetId (void) const
uint8_t GetLength (void) const
void Init (void)
void Init (uint16_t aId, uint8_t aLen)
void SetId (uint16_t aId)
void SetLength (uint8_t aLength)
Private Attributes
union ot::Mac::HeaderIe::OT_TOOL_PACKED_FIELD mFields
Static Private Attributes
static constexpr uint16_t kIdMask = 0x00ff << kIdOffset
static constexpr uint8_t kIdOffset = 7
static constexpr uint8_t kLengthMask = 0x7f
static constexpr uint8_t kSize = 2
Detailed Description
This class implements IEEE 802.15.4 IE (Information Element) header generation and parsing.
Member Function Documentation
Init() [1/2]
void Init (void) inline
This method initializes the Header IE.
References HeaderIe::OT_TOOL_PACKED_FIELD::m16, and HeaderIe::mFields.
Referenced by Frame::GetFooter(), and HeaderIe::Init().
Init() [2/2]
void Init (uint16_t aId, uint8_t aLen)
This method initializes the Header IE with Id and Length.
Parameters
[in] aId The IE Element Id.
[in] aLen The IE content length.
References HeaderIe::Init(), HeaderIe::SetId(), and HeaderIe::SetLength().
GetId()
uint16_t GetId (void) const inline
This method returns the IE Element Id.
Returns
the IE Element Id.
References ot::Encoding::BigEndian::HostSwap16(), HeaderIe::kIdMask, HeaderIe::kIdOffset, HeaderIe::OT_TOOL_PACKED_FIELD::m16, and HeaderIe::mFields.
Referenced by Frame::FindPayloadIndex(), and Frame::GetFooter().
SetId()
void SetId (uint16_t aId) inline
This method sets the IE Element Id.
Parameters
[in] aId The IE Element Id.
References ot::Encoding::BigEndian::HostSwap16(), HeaderIe::kIdMask, HeaderIe::kIdOffset, HeaderIe::OT_TOOL_PACKED_FIELD::m16, and HeaderIe::mFields.
Referenced by HeaderIe::Init().
GetLength()
uint8_t GetLength (void) const inline
This method returns the IE content length.
Returns
the IE content length.
References HeaderIe::kLengthMask, HeaderIe::OT_TOOL_PACKED_FIELD::m8, and HeaderIe::mFields.
Referenced by Frame::FindPayloadIndex(), Frame::GetFooter(), and Mac::LogFrameTxFailure().
SetLength()
void SetLength (uint8_t aLength) inline
This method sets the IE content length.
Parameters
[in] aLength The IE content length.
References HeaderIe::kLengthMask, HeaderIe::OT_TOOL_PACKED_FIELD::m8, and HeaderIe::mFields.
Referenced by TxFrame::CopyFrom(), and HeaderIe::Init().
Field Documentation
kSize
constexpr uint8_t kSize = 2 static private
kIdOffset
constexpr uint8_t kIdOffset = 7 static private
Referenced by HeaderIe::GetId(), and HeaderIe::SetId().
kLengthMask
constexpr uint8_t kLengthMask = 0x7f static private
Referenced by HeaderIe::GetLength(), and HeaderIe::SetLength().
kIdMask
constexpr uint16_t kIdMask = 0x00ff << kIdOffset static private
Referenced by HeaderIe::GetId(), and HeaderIe::SetId().
mFields
union ot::Mac::HeaderIe::OT_TOOL_PACKED_FIELD mFields private
Referenced by HeaderIe::GetId(), HeaderIe::GetLength(), HeaderIe::Init(), HeaderIe::SetId(), and HeaderIe::SetLength().
The documentation for this class was generated from the following files:
mac_frame.hpp
mac_frame.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale