OpenThread: HkdfSha256 Class Reference
HkdfSha256 Class Reference
Core-security
#include <hkdf_sha256.hpp>
Public Member Functions
void Expand (const uint8_t *aInfo, uint16_t aInfoLength, uint8_t *aOutputKey, uint16_t aOutputKeyLength)
void Extract (const uint8_t *aSalt, uint16_t aSaltLength, const Key &aInputKey)
HkdfSha256 (void)
~HkdfSha256 (void)
Private Member Functions
OT_DEFINE_ALIGNED_VAR (mContextStorage, kHkdfContextSize, uint64_t)
Private Attributes
otCryptoContext mContext
Detailed Description
This class implements HMAC-based Extract-and-Expand Key Derivation Function (HKDF) [RFC5869] using SHA-256.
Constructor & Destructor Documentation
HkdfSha256()
HkdfSha256 (void)
Constructor to initialize the context.
References HkdfSha256::mContext, otCryptoContext::mContext, otCryptoContext::mContextSize, otPlatCryptoHkdfInit(), and SuccessOrAssert.
~HkdfSha256()
~HkdfSha256 (void)
Destructor to free the context.
References HkdfSha256::mContext, otPlatCryptoHkdfDeinit(), and SuccessOrAssert.
Member Function Documentation
Extract()
void Extract (const uint8_t * aSalt, uint16_t aSaltLength, const Key & aInputKey)
This method performs the HKDF Extract step.
In the Extract step getting an input key extracts from it a pseudo-random key.
Parameters
[in] aSalt A pointer to buffer containing salt.
[in] aSaltLength The salt length (in bytes).
[in] aInputKey The input key.
References HkdfSha256::mContext, otPlatCryptoHkdfExtract(), and SuccessOrAssert.
Referenced by KeyManager::ComputeKeys().
Expand()
void Expand (const uint8_t * aInfo, uint16_t aInfoLength, uint8_t * aOutputKey, uint16_t aOutputKeyLength)
This method performs the HKDF Expand step.
The method should be used after a previous Extract call, otherwise its behavior is undefined. In the Expand stage an output key of a given length is derived from the pseudo-random key of Extract stage.
Parameters
[in] aInfo A pointer to buffer containing info sequence.
[in] aInfoLength The info length (in bytes).
[out] aOutputKey Buffer to place the output key (must contain at least aOutputKeyLength bytes).
[in] aOutputKeyLength The output key length.
References HkdfSha256::mContext, otPlatCryptoHkdfExpand(), and SuccessOrAssert.
Referenced by KeyManager::ComputeKeys().
OT_DEFINE_ALIGNED_VAR()
OT_DEFINE_ALIGNED_VAR (mContextStorage , kHkdfContextSize , uint64_t) private
Field Documentation
mContext
otCryptoContext mContext private
Referenced by HkdfSha256::Expand(), HkdfSha256::Extract(), HkdfSha256::HkdfSha256(), and HkdfSha256::~HkdfSha256().
The documentation for this class was generated from the following files:
hkdf_sha256.hpp
hkdf_sha256.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale