OpenThread: LeaderBase Class Reference
LeaderBase Class Reference
Core-netdata » Leader
#include <network_data_leader.hpp>
Public Member Functions
CommissioningDataTlv * GetCommissioningData (void)
const CommissioningDataTlv * GetCommissioningData (void) const
MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType)
const MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType) const
Error GetContext (const Ip6::Address &aAddress, Lowpan::Context &aContext) const
Error GetContext (uint8_t aContextId, Lowpan::Context &aContext) const
Error GetPreferredNat64Prefix (ExternalRouteConfig &aConfig) const
Error GetServiceId (uint32_t aEnterpriseNumber, const ServiceData &aServiceData, bool aServerStable, uint8_t &aServiceId) const
uint8_t GetVersion (Type aType) const
bool IsJoiningEnabled (void) const
bool IsOnMesh (const Ip6::Address &aAddress) const
LeaderBase (Instance &aInstance)
void Reset (void)
Error RouteLookup (const Ip6::Address &aSource, const Ip6::Address &aDestination, uint8_t *aPrefixMatchLength, uint16_t *aRloc16) const
Error SetCommissioningData (const uint8_t *aValue, uint8_t aValueLength)
Error SetNetworkData (uint8_t aVersion, uint8_t aStableVersion, Type aType, const Message &aMessage, uint16_t aMessageOffset)
Error SteeringDataCheckJoiner (const Mac::ExtAddress &aEui64) const
Error SteeringDataCheckJoiner (const MeshCoP::JoinerDiscerner &aDiscerner) const
Public Member Functions inherited from MutableNetworkData
void Clear (void)
uint8_t * GetBytes (void)
uint8_t GetSize (void) const
MutableNetworkData (Instance &aInstance, uint8_t *aTlvs, uint8_t aLength, uint8_t aSize)
Public Member Functions inherited from NetworkData
bool ContainsBorderRouterWithRloc (uint16_t aRloc16) const
bool ContainsEntriesFrom (const NetworkData &aCompare, uint16_t aRloc16) const
bool ContainsExternalRoute (const ExternalRouteConfig &aRoute) const
bool ContainsOnMeshPrefix (const OnMeshPrefixConfig &aPrefix) const
bool ContainsService (const ServiceConfig &aService) const
Error CopyNetworkData (Type aType, uint8_t *aData, uint8_t &aDataLength) const
Error CopyNetworkData (Type aType, MutableNetworkData &aNetworkData) const
uint8_t CountBorderRouters (RoleFilter aRoleFilter) const
Error FindBorderRouters (RoleFilter aRoleFilter, uint16_t aRlocs[], uint8_t &aRlocsLength) const
const uint8_t * GetBytes (void) const
uint8_t GetLength (void) const
Error GetNextExternalRoute (Iterator &aIterator, ExternalRouteConfig &aConfig) const
Error GetNextExternalRoute (Iterator &aIterator, uint16_t aRloc16, ExternalRouteConfig &aConfig) const
Error GetNextOnMeshPrefix (Iterator &aIterator, OnMeshPrefixConfig &aConfig) const
Error GetNextOnMeshPrefix (Iterator &aIterator, uint16_t aRloc16, OnMeshPrefixConfig &aConfig) const
Error GetNextServer (Iterator &aIterator, uint16_t &aRloc16) const
Error GetNextService (Iterator &aIterator, ServiceConfig &aConfig) const
Error GetNextService (Iterator &aIterator, uint16_t aRloc16, ServiceConfig &aConfig) const
NetworkData (Instance &aInstance, const uint8_t *aTlvs=nullptr, uint8_t aLength=0)
NetworkData (Instance &aInstance, const NetworkDataTlv *aStartTlv, const NetworkDataTlv *aEndTlv)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Protected Attributes
uint8_t mStableVersion
uint8_t mVersion
Private Types
using FilterIndexes = MeshCoP::SteeringData::HashBitIndexes
Private Member Functions
Error DefaultRouteLookup (const PrefixTlv &aPrefix, uint16_t *aRloc16) const
Error ExternalRouteLookup (uint8_t aDomainId, const Ip6::Address &aDestination, uint8_t *aPrefixMatchLength, uint16_t *aRloc16) const
const PrefixTlv * FindNextMatchingPrefix (const Ip6::Address &aAddress, const PrefixTlv *aPrevTlv) const
void GetContextForMeshLocalPrefix (Lowpan::Context &aContext) const
void RemoveCommissioningData (void)
Error SteeringDataCheck (const FilterIndexes &aFilterIndexes) const
Private Attributes
uint8_t mTlvBuffer [kMaxSize]
Additional Inherited Members
Static Public Attributes inherited from NetworkData
static constexpr uint8_t kMaxSize = 254
Maximum size of Thread Network Data in bytes.
Protected Types inherited from NetworkData
enum ServiceMatchMode : uint8_t { kServicePrefixMatch, kServiceExactMatch }
Protected Member Functions inherited from MutableNetworkData
NetworkDataTlv * AppendTlv (uint16_t aTlvSize)
bool CanInsert (uint16_t aSize) const
PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength)
PrefixTlv * FindPrefix (const Ip6::Prefix &aPrefix)
ServiceTlv * FindService (uint32_t aEnterpriseNumber, const ServiceData &aServiceData, ServiceMatchMode aServiceMatchMode)
NetworkDataTlv * GetTlvsEnd (void)
NetworkDataTlv * GetTlvsStart (void)
void Insert (void *aStart, uint8_t aLength)
void Remove (void *aRemoveStart, uint8_t aRemoveLength)
void RemoveTemporaryData (void)
void RemoveTlv (NetworkDataTlv *aTlv)
void SetLength (uint8_t aLength)
Protected Member Functions inherited from NetworkData
const ServiceTlv * FindNextService (const ServiceTlv *aPrevServiceTlv, uint32_t aEnterpriseNumber, const ServiceData &aServiceData, ServiceMatchMode aServiceMatchMode) const
const ServiceTlv * FindNextThreadService (const ServiceTlv *aPrevServiceTlv, const ServiceData &aServiceData, ServiceMatchMode aServiceMatchMode) const
const PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength) const
const PrefixTlv * FindPrefix (const Ip6::Prefix &aPrefix) const
const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const ServiceData &aServiceData, ServiceMatchMode aServiceMatchMode) const
const NetworkDataTlv * GetTlvsEnd (void) const
const NetworkDataTlv * GetTlvsStart (void) const
Error SendServerDataNotification (uint16_t aRloc16, bool aAppendNetDataTlv, Coap::ResponseHandler aHandler, void *aContext) const
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements the Thread Network Data maintained by the Leader.
Member Typedef Documentation
FilterIndexes
using FilterIndexes = MeshCoP::SteeringData::HashBitIndexes private
Constructor & Destructor Documentation
LeaderBase()
LeaderBase (Instance & aInstance) inline explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References LeaderBase::Reset().
Member Function Documentation
Reset()
void Reset (void)
This method reset the Thread Network Data.
References ot::Random::NonCrypto::GetUint8(), ot::kEventThreadNetdataChanged, LeaderBase::mStableVersion, LeaderBase::mVersion, and MutableNetworkData::SetLength().
Referenced by LeaderBase::LeaderBase().
GetVersion()
uint8_t GetVersion (Type aType) const inline
This method returns the Data Version value for a type (full set or stable subset).
Parameters
[in] aType The Network Data type (full set or stable subset).
Returns
The Data Version value for aType.
References LeaderBase::GetContext(), LeaderBase::IsOnMesh(), ot::NetworkData::kFullSet, LeaderBase::mStableVersion, LeaderBase::mVersion, LeaderBase::RouteLookup(), and LeaderBase::SetNetworkData().
GetContext() [1/2]
Error GetContext (const Ip6::Address & aAddress, Lowpan::Context & aContext) const
This method retrieves the 6LoWPAN Context information based on a given IPv6 address.
Parameters
[in] aAddress A reference to an IPv6 address.
[out] aContext A reference to 6LoWPAN Context information.
Return values
kErrorNone Successfully retrieved 6LoWPAN Context information.
kErrorNotFound Could not find the 6LoWPAN Context information.
References LeaderBase::FindNextMatchingPrefix(), PrefixTlv::FindSubTlv(), LeaderBase::GetContextForMeshLocalPrefix(), ContextTlv::GetContextId(), Prefix::GetLength(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), ContextTlv::IsCompress(), ot::kErrorNone, ot::kErrorNotFound, Context::mCompressFlag, Context::mContextId, Context::mIsValid, Context::mPrefix, Prefix::Set(), and Prefix::SetLength().
Referenced by LeaderBase::GetVersion().
GetContext() [2/2]
Error GetContext (uint8_t aContextId, Lowpan::Context & aContext) const
This method retrieves the 6LoWPAN Context information based on a given Context ID.
Parameters
[in] aContextId The Context ID value.
[out] aContext A reference to the 6LoWPAN Context information.
Return values
kErrorNone Successfully retrieved 6LoWPAN Context information.
kErrorNotFound Could not find the 6LoWPAN Context information.
References ExitNow, PrefixTlv::FindSubTlv(), LeaderBase::GetContextForMeshLocalPrefix(), ContextTlv::GetContextId(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), MutableNetworkData::GetTlvsEnd(), MutableNetworkData::GetTlvsStart(), ContextTlv::IsCompress(), TlvIterator::Iterate(), ot::kErrorNone, ot::kErrorNotFound, ot::Mle::kMeshLocalPrefixContextId, Context::mCompressFlag, Context::mContextId, Context::mIsValid, Context::mPrefix, and Prefix::Set().
IsOnMesh()
bool IsOnMesh (const Ip6::Address & aAddress) const
This method indicates whether or not the given IPv6 address is on-mesh.
Parameters
[in] aAddress A reference to an IPv6 address.
Return values
TRUE If aAddress is on-link.
FALSE If aAddress if not on-link.
References ExitNow, LeaderBase::FindNextMatchingPrefix(), PrefixTlv::FindSubTlv(), BorderRouterTlv::GetFirstEntry(), BorderRouterTlv::GetLastEntry(), BorderRouterEntry::GetNext(), and VerifyOrExit.
Referenced by LeaderBase::GetVersion().
RouteLookup()
Error RouteLookup (const Ip6::Address & aSource, const Ip6::Address & aDestination, uint8_t * aPrefixMatchLength, uint16_t * aRloc16) const
This method performs a route lookup using the Network Data.
Parameters
[in] aSource A reference to the IPv6 source address.
[in] aDestination A reference to the IPv6 destination address.
[out] aPrefixMatchLength A pointer to output the longest prefix match length in bits.
[out] aRloc16 A pointer to the RLOC16 for the selected route.
Return values
kErrorNone Successfully found a route.
kErrorNoRoute No valid route was found.
References LeaderBase::DefaultRouteLookup(), ExitNow, LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), PrefixTlv::GetDomainId(), ot::kErrorNone, and ot::kErrorNoRoute.
Referenced by LeaderBase::GetVersion().
SetNetworkData()
Error SetNetworkData (uint8_t aVersion, uint8_t aStableVersion, Type aType, const Message & aMessage, uint16_t aMessageOffset)
This method is used by non-Leader devices to set newly received Network Data from the Leader.
Parameters
[in] aVersion The Version value.
[in] aStableVersion The Stable Version value.
[in] aType The Network Data type to set, the full set or stable subset.
[in] aMessage A reference to the MLE message.
[in] aMessageOffset The offset in aMessage for the Network Data TLV.
Return values
kErrorNone Successfully set the network data.
kErrorParse Network Data TLV in aMessage is not valid.
References DumpDebg, MutableNetworkData::GetBytes(), Tlv::GetLength(), NetworkData::GetLength(), ot::kErrorNone, ot::kErrorParse, ot::kEventThreadNetdataChanged, ot::NetworkData::kStableSubset, LeaderBase::mStableVersion, LeaderBase::mVersion, Message::Read(), Message::ReadBytes(), MutableNetworkData::RemoveTemporaryData(), MutableNetworkData::SetLength(), SuccessOrExit, and VerifyOrExit.
Referenced by LeaderBase::GetVersion().
GetCommissioningData() [1/2]
CommissioningDataTlv* GetCommissioningData (void) inline
This method returns a pointer to the Commissioning Data.
Returns
A pointer to the Commissioning Data or nullptr if no Commissioning Data exists.
References ot::AsConst(), ot::AsNonConst(), and LeaderBase::GetCommissioningData().
Referenced by LeaderBase::GetCommissioningData(), LeaderBase::GetCommissioningDataSubTlv(), and LeaderBase::RemoveCommissioningData().
GetCommissioningData() [2/2]
const CommissioningDataTlv * GetCommissioningData (void) const
This method returns a pointer to the Commissioning Data.
Returns
A pointer to the Commissioning Data or nullptr if no Commissioning Data exists.
References MutableNetworkData::GetTlvsEnd(), and MutableNetworkData::GetTlvsStart().
GetCommissioningDataSubTlv() [1/2]
MeshCoP::Tlv* GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType) inline
This method returns a pointer to the Commissioning Data Sub-TLV.
Parameters
[in] aType The TLV type value.
Returns
A pointer to the Commissioning Data Sub-TLV or nullptr if no Sub-TLV exists.
References ot::AsConst(), ot::AsNonConst(), LeaderBase::GetPreferredNat64Prefix(), LeaderBase::GetServiceId(), LeaderBase::IsJoiningEnabled(), LeaderBase::SetCommissioningData(), and LeaderBase::SteeringDataCheckJoiner().
Referenced by LeaderBase::IsJoiningEnabled(), and LeaderBase::SteeringDataCheck().
GetCommissioningDataSubTlv() [2/2]
const MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType) const
This method returns a pointer to the Commissioning Data Sub-TLV.
Parameters
[in] aType The TLV type value.
Returns
A pointer to the Commissioning Data Sub-TLV or nullptr if no Sub-TLV exists.
References Tlv::FindTlv(), LeaderBase::GetCommissioningData(), NetworkDataTlv::GetLength(), NetworkDataTlv::GetValue(), and VerifyOrExit.
IsJoiningEnabled()
bool IsJoiningEnabled (void) const
This method indicates whether or not the Commissioning Data TLV indicates Joining is enabled.
Joining is enabled if a Border Agent Locator TLV exist and the Steering Data TLV is non-zero.
Returns
TRUE if the Commissioning Data TLV says Joining is enabled, FALSE otherwise.
References ExitNow, LeaderBase::GetCommissioningDataSubTlv(), Tlv::GetLength(), Tlv::GetValue(), Tlv::kBorderAgentLocator, Tlv::kSteeringData, and VerifyOrExit.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
SetCommissioningData()
Error SetCommissioningData (const uint8_t * aValue, uint8_t aValueLength)
This method adds Commissioning Data to the Thread Network Data.
Parameters
[in] aValue A pointer to the Commissioning Data value.
[in] aValueLength The length of aValue.
Return values
kErrorNone Successfully added the Commissioning Data.
kErrorNoBufs Insufficient space to add the Commissioning Data.
References MutableNetworkData::AppendTlv(), NetworkDataTlv::GetValue(), CommissioningDataTlv::Init(), ot::kErrorNoBufs, ot::kErrorNone, ot::kEventThreadNetdataChanged, NetworkData::kMaxSize, LeaderBase::mVersion, LeaderBase::RemoveCommissioningData(), NetworkDataTlv::SetLength(), and VerifyOrExit.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
SteeringDataCheckJoiner() [1/2]
Error SteeringDataCheckJoiner (const Mac::ExtAddress & aEui64) const
This method checks if the steering data includes a Joiner.
Parameters
[in] aEui64 A reference to the Joiner's IEEE EUI-64.
Return values
kErrorNone aEui64 is in the bloom filter.
kErrorInvalidState No steering data present.
kErrorNotFound aEui64 is not in the bloom filter.
References SteeringData::CalculateHashBitIndexes(), ot::MeshCoP::ComputeJoinerId(), and LeaderBase::SteeringDataCheck().
Referenced by LeaderBase::GetCommissioningDataSubTlv().
SteeringDataCheckJoiner() [2/2]
Error SteeringDataCheckJoiner (const MeshCoP::JoinerDiscerner & aDiscerner) const
This method checks if the steering data includes a Joiner with a given discerner value.
Parameters
[in] aDiscerner A reference to the Joiner Discerner.
Return values
kErrorNone aDiscerner is in the bloom filter.
kErrorInvalidState No steering data present.
kErrorNotFound aDiscerner is not in the bloom filter.
References SteeringData::CalculateHashBitIndexes(), and LeaderBase::SteeringDataCheck().
GetServiceId()
Error GetServiceId (uint32_t aEnterpriseNumber, const ServiceData & aServiceData, bool aServerStable, uint8_t & aServiceId) const
This method gets the Service ID for the specified service.
Parameters
[in] aEnterpriseNumber Enterprise Number (IANA-assigned) for Service TLV
[in] aServiceData The Service Data.
[in] aServerStable The Stable flag value for Server TLV.
[out] aServiceId A reference where to put the Service ID.
Return values
kErrorNone Successfully got the Service ID.
kErrorNotFound The specified service was not found.
References ExitNow, NetworkData::GetNextService(), ServiceConfig::GetServiceData(), ot::kErrorNone, ot::kErrorNotFound, ot::NetworkData::kIteratorInit, otServiceConfig::mEnterpriseNumber, otServiceConfig::mServerConfig, otServiceConfig::mServiceId, and otServerConfig::mStable.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
GetPreferredNat64Prefix()
Error GetPreferredNat64Prefix (ExternalRouteConfig & aConfig) const
This methods gets the preferred NAT64 prefix from network data.
The returned prefix is the highest preference external route entry in Network Data with NAT64 flag set. If there are multiple such entries the first one is returned.
Parameters
[out] aConfig A reference to an ExternalRouteConfig to return the prefix.
Return values
kErrorNone Found the NAT64 prefix and updated aConfig.
kErrorNotFound Could not find any NAT64 entry.
References NetworkData::GetNextExternalRoute(), ExternalRouteConfig::GetPrefix(), Prefix::IsValidNat64(), ot::kErrorNone, ot::kErrorNotFound, ot::NetworkData::kIteratorInit, otExternalRouteConfig::mNat64, and otExternalRouteConfig::mPreference.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
FindNextMatchingPrefix()
const PrefixTlv * FindNextMatchingPrefix (const Ip6::Address & aAddress, const PrefixTlv * aPrevTlv) const private
References NetworkDataTlv::GetNext(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), MutableNetworkData::GetTlvsEnd(), MutableNetworkData::GetTlvsStart(), and Address::MatchesPrefix().
Referenced by LeaderBase::GetContext(), LeaderBase::IsOnMesh(), and LeaderBase::RouteLookup().
RemoveCommissioningData()
void RemoveCommissioningData (void) private
References LeaderBase::GetCommissioningData(), MutableNetworkData::RemoveTlv(), and VerifyOrExit.
Referenced by LeaderBase::SetCommissioningData().
ExternalRouteLookup()
Error ExternalRouteLookup (uint8_t aDomainId, const Ip6::Address & aDestination, uint8_t * aPrefixMatchLength, uint16_t * aRloc16) const private
References PrefixTlv::GetDomainId(), HasRouteTlv::GetFirstEntry(), HasRouteTlv::GetLastEntry(), HasRouteEntry::GetNext(), HasRouteEntry::GetPreference(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), HasRouteEntry::GetRloc(), MutableNetworkData::GetTlvsEnd(), MutableNetworkData::GetTlvsStart(), TlvIterator::Iterate(), ot::kErrorNone, ot::kErrorNoRoute, and Address::MatchesPrefix().
Referenced by LeaderBase::RouteLookup().
DefaultRouteLookup()
Error DefaultRouteLookup (const PrefixTlv & aPrefix, uint16_t * aRloc16) const private
References BorderRouterTlv::GetFirstEntry(), BorderRouterTlv::GetLastEntry(), BorderRouterEntry::GetNext(), BorderRouterEntry::GetPreference(), BorderRouterEntry::GetRloc(), TlvIterator::Iterate(), ot::kErrorNone, and ot::kErrorNoRoute.
Referenced by LeaderBase::RouteLookup().
SteeringDataCheck()
Error SteeringDataCheck (const FilterIndexes & aFilterIndexes) const private
References SteeringData::Contains(), LeaderBase::GetCommissioningDataSubTlv(), ot::kErrorInvalidState, ot::kErrorNone, ot::kErrorNotFound, Tlv::kSteeringData, and VerifyOrExit.
Referenced by LeaderBase::SteeringDataCheckJoiner().
GetContextForMeshLocalPrefix()
void GetContextForMeshLocalPrefix (Lowpan::Context & aContext) const private
References ot::Mle::kMeshLocalPrefixContextId, Context::mCompressFlag, Context::mContextId, Context::mIsValid, Context::mPrefix, and Prefix::Set().
Referenced by LeaderBase::GetContext().
Field Documentation
mStableVersion
uint8_t mStableVersion protected
Referenced by LeaderBase::GetVersion(), LeaderBase::Reset(), and LeaderBase::SetNetworkData().
mVersion
uint8_t mVersion protected
Referenced by LeaderBase::GetVersion(), LeaderBase::Reset(), LeaderBase::SetCommissioningData(), and LeaderBase::SetNetworkData().
mTlvBuffer
uint8_t mTlvBuffer[kMaxSize] private
The documentation for this class was generated from the following files:
network_data_leader.hpp
network_data_leader.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale