OpenThread: UdpEncapsulationTlv Class Reference
UdpEncapsulationTlv Class Reference
#include <meshcop_tlvs.hpp>
Public Member Functions
uint16_t GetDestinationPort (void) const
uint16_t GetSourcePort (void) const
uint16_t GetUdpLength (void) const
void Init (void)
bool IsValid (void) const
void SetDestinationPort (uint16_t aDestinationPort)
void SetSourcePort (uint16_t aSourcePort)
void SetUdpLength (uint16_t aLength)
Public Member Functions inherited from ExtendedTlv
MeshCoP::Tlv::Type GetType (void) const
void SetType (MeshCoP::Tlv::Type aType)
Public Member Functions inherited from ExtendedTlv
uint16_t GetLength (void) const
void SetLength (uint16_t aLength)
Public Member Functions inherited from Tlv
Error AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint16_t mDestinationPort
uint16_t mSourcePort
Additional Inherited Members
Static Public Member Functions inherited from Tlv
template<typename TlvType >
static Error Append (Message &aMessage, const void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Append (Message &aMessage, const typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Append (Message &aMessage, typename UintTlvType::UintValueType aValue)
template<typename TlvType >
static Error Find (const Message &aMessage, void *aValue, uint8_t aLength)
template<typename SimpleTlvType >
static Error Find (const Message &aMessage, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Find (const Message &aMessage, typename UintTlvType::UintValueType &aValue)
static Error FindTlv (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
template<typename TlvType >
static Error FindTlv (const Message &aMessage, TlvType &aTlv)
static Error FindTlvOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static Error FindTlvValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aValueOffset, uint16_t &aLength)
template<typename SimpleTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename SimpleTlvType::ValueType &aValue)
template<typename UintTlvType >
static Error Read (const Message &aMessage, uint16_t aOffset, typename UintTlvType::UintValueType &aValue)
static Error ReadTlv (const Message &aMessage, uint16_t aOffset, void *aValue, uint8_t aMinLength)
Static Public Attributes inherited from Tlv
static constexpr uint8_t kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH
Static Public Attributes inherited from TlvInfo< MeshCoP::Tlv::kUdpEncapsulation >
static constexpr uint8_t kType
The TLV Type value.
Static Protected Attributes inherited from Tlv
static const uint8_t kExtendedLength = 255
Detailed Description
This class implements UDP Encapsulation TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References Tlv::kUdpEncapsulation, Tlv::SetLength(), and Tlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
GetSourcePort()
uint16_t GetSourcePort (void) const inline
This method returns the source port.
Returns
The source port.
References ot::Encoding::BigEndian::HostSwap16().
SetSourcePort()
void SetSourcePort (uint16_t aSourcePort) inline
This method updates the source port.
Parameters
[in] aSourcePort The source port.
References ot::Encoding::BigEndian::HostSwap16().
GetDestinationPort()
uint16_t GetDestinationPort (void) const inline
This method returns the destination port.
Returns
The destination port.
References ot::Encoding::BigEndian::HostSwap16().
SetDestinationPort()
void SetDestinationPort (uint16_t aDestinationPort) inline
This method updates the destination port.
Parameters
[in] aDestinationPort The destination port.
References ot::Encoding::BigEndian::HostSwap16().
GetUdpLength()
uint16_t GetUdpLength (void) const inline
This method returns the calculated UDP length.
Returns
The calculated UDP length.
References Tlv::GetLength().
SetUdpLength()
void SetUdpLength (uint16_t aLength) inline
This method updates the UDP length.
Parameters
[in] aLength The length of UDP payload in bytes.
References Tlv::SetLength().
Field Documentation
mSourcePort
uint16_t mSourcePort private
mDestinationPort
uint16_t mDestinationPort private
The documentation for this class was generated from the following file:
meshcop_tlvs.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale