OpenThread: Icmp Class Reference
Icmp Class Reference
Core-ipv6 » ICMPv6
#include <icmp6.hpp>
Data Structures
class Handler
class Header
Public Member Functions
otIcmp6EchoMode GetEchoMode (void) const
uint16_t GetEchoSequence (void) const
Error HandleMessage (Message &aMessage, MessageInfo &aMessageInfo)
Icmp (Instance &aInstance)
Message * NewMessage (uint16_t aReserved)
Error RegisterHandler (Handler &aHandler)
Error SendEchoRequest (Message &aMessage, const MessageInfo &aMessageInfo, uint16_t aIdentifier)
Error SendError (Header::Type aType, Header::Code aCode, const MessageInfo &aMessageInfo, const Message &aMessage)
Error SendError (Header::Type aType, Header::Code aCode, const MessageInfo &aMessageInfo, const Headers &aHeaders)
void SetEchoMode (otIcmp6EchoMode aMode)
bool ShouldHandleEchoRequest (const MessageInfo &aMessageInfo)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Data Fields
ot::Ip6::Icmp::Header OT_TOOL_PACKED_END
Private Member Functions
Error HandleEchoRequest (Message &aRequestMessage, const MessageInfo &aMessageInfo)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
otIcmp6EchoMode mEchoMode
uint16_t mEchoSequence
LinkedList< Handler > mHandlers
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements ICMPv6.
Constructor & Destructor Documentation
Icmp()
Icmp (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Referenced by Icmp::Handler::HandleReceiveMessage().
Member Function Documentation
NewMessage()
Message * NewMessage (uint16_t aReserved)
This method returns a new ICMP message with sufficient header space reserved.
Parameters
[in] aReserved The number of header bytes to reserve after the ICMP header.
Returns
A pointer to the message or nullptr if no buffers are available.
Referenced by Icmp::HandleEchoRequest(), Icmp::Handler::HandleReceiveMessage(), and Icmp::SendError().
RegisterHandler()
Error RegisterHandler (Handler & aHandler)
This method registers ICMPv6 handler.
Parameters
[in] aHandler A reference to the ICMPv6 handler.
Return values
kErrorNone Successfully registered the ICMPv6 handler.
kErrorAlready The ICMPv6 handler is already registered.
References Icmp::mHandlers.
Referenced by Icmp::Handler::HandleReceiveMessage().
SendEchoRequest()
Error SendEchoRequest (Message & aMessage, const MessageInfo & aMessageInfo, uint16_t aIdentifier)
This method sends an ICMPv6 Echo Request message.
Parameters
[in] aMessage A reference to the Echo Request payload.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aIdentifier An identifier to aid in matching Echo Replies to this Echo Request. May be zero.
Return values
kErrorNone Successfully enqueued the ICMPv6 Echo Request message.
kErrorNoBufs Insufficient buffers available to generate an ICMPv6 Echo Request message.
References Clearable< Type >::Clear(), Icmp::Header::GetSequence(), ot::kErrorNone, ot::Ip6::kProtoIcmp6, Icmp::Header::kTypeEchoRequest, LogInfo, Icmp::mEchoSequence, Message::Prepend(), Icmp::Header::SetId(), Message::SetOffset(), Icmp::Header::SetSequence(), Icmp::Header::SetType(), and SuccessOrExit.
Referenced by Icmp::Handler::HandleReceiveMessage().
SendError() [1/2]
Error SendError (Header::Type aType, Header::Code aCode, const MessageInfo & aMessageInfo, const Message & aMessage)
This method sends an ICMPv6 error message.
Parameters
[in] aType The ICMPv6 message type.
[in] aCode The ICMPv6 message code.
[in] aMessageInfo A reference to the message info.
[in] aMessage The error-causing IPv6 message.
Return values
kErrorNone Successfully enqueued the ICMPv6 error message.
kErrorNoBufs Insufficient buffers available.
References Headers::ParseFrom(), and SuccessOrExit.
Referenced by Ip6::HandleOptions(), and Icmp::Handler::HandleReceiveMessage().
SendError() [2/2]
Error SendError (Header::Type aType, Header::Code aCode, const MessageInfo & aMessageInfo, const Headers & aHeaders)
This method sends an ICMPv6 error message.
Parameters
[in] aType The ICMPv6 message type.
[in] aCode The ICMPv6 message code.
[in] aMessageInfo A reference to the message info.
[in] aHeaders The parsed headers from the error-causing IPv6 message.
Return values
kErrorNone Successfully enqueued the ICMPv6 error message.
kErrorNoBufs Insufficient buffers available.
References Message::Append(), Clearable< Type >::Clear(), FreeMessageOnError, Headers::GetIcmpHeader(), Headers::GetIp6Header(), Headers::GetIpProto(), Icmp::Header::IsError(), ot::kErrorNoBufs, ot::kErrorNone, Message::kPriorityNet, ot::Ip6::kProtoIcmp6, Message::kWithLinkSecurity, LogInfo, Icmp::NewMessage(), Icmp::Header::SetCode(), Icmp::Header::SetType(), SuccessOrExit, and VerifyOrExit.
HandleMessage()
Error HandleMessage (Message & aMessage, MessageInfo & aMessageInfo)
This method handles an ICMPv6 message.
Parameters
[in] aMessage A reference to the ICMPv6 message.
[in] aMessageInfo A reference to the message info associated with aMessage.
Return values
kErrorNone Successfully processed the ICMPv6 message.
kErrorNoBufs Insufficient buffers available to generate the reply.
kErrorDrop The ICMPv6 message was invalid and dropped.
References Message::GetOffset(), Icmp::Header::GetType(), Icmp::HandleEchoRequest(), ot::kErrorNone, ot::Ip6::kProtoIcmp6, Icmp::Header::kTypeEchoRequest, Icmp::mHandlers, Message::MoveOffset(), Message::Read(), SuccessOrExit, and Checksum::VerifyMessageChecksum().
Referenced by Ip6::HandlePayload(), and Icmp::Handler::HandleReceiveMessage().
GetEchoMode()
otIcmp6EchoMode GetEchoMode (void) const inline
This method indicates whether or not ICMPv6 Echo processing is enabled.
Return values
TRUE ICMPv6 Echo processing is enabled.
FALSE ICMPv6 Echo processing is disabled.
References Icmp::mEchoMode.
SetEchoMode()
void SetEchoMode (otIcmp6EchoMode aMode) inline
Sets the ICMPv6 echo mode.
Parameters
[in] aMode The ICMPv6 echo mode.
References Icmp::mEchoMode, and Icmp::ShouldHandleEchoRequest().
ShouldHandleEchoRequest()
bool ShouldHandleEchoRequest (const MessageInfo & aMessageInfo)
This method indicates whether or not the ICMPv6 Echo Request should be handled.
Return values
TRUE if OpenThread should respond with an ICMPv6 Echo Reply.
FALSE if OpenThread should not respond with an ICMPv6 Echo Reply.
References MessageInfo::GetSockAddr(), Address::IsMulticast(), Icmp::mEchoMode, OT_ICMP6_ECHO_HANDLER_ALL, OT_ICMP6_ECHO_HANDLER_DISABLED, OT_ICMP6_ECHO_HANDLER_MULTICAST_ONLY, and OT_ICMP6_ECHO_HANDLER_UNICAST_ONLY.
Referenced by Icmp::HandleEchoRequest(), Ip6::ProcessReceiveCallback(), and Icmp::SetEchoMode().
GetEchoSequence()
uint16_t GetEchoSequence (void) const inline
This method returns the ICMPv6 Echo sequence number.
Returns
The sequence number of the next ICMPv6 Echo request.
References Icmp::HandleEchoRequest(), and Icmp::mEchoSequence.
HandleEchoRequest()
Error HandleEchoRequest (Message & aRequestMessage, const MessageInfo & aMessageInfo) private
References Clearable< Type >::Clear(), Message::CopyTo(), ExitNow, FreeMessageOnError, Address::GetIid(), Message::GetLength(), Message::GetOffset(), MessageInfo::GetPeerAddr(), Icmp::Header::GetSequence(), MessageInfo::GetSockAddr(), IgnoreError(), InterfaceIdentifier::IsLocator(), Address::IsMulticast(), Icmp::Header::kDataFieldOffset, ot::kErrorNone, ot::Ip6::kProtoIcmp6, Icmp::Header::kTypeEchoReply, LogDebg, LogInfo, Icmp::NewMessage(), Message::Read(), Message::SetLength(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), Icmp::Header::SetType(), Icmp::ShouldHandleEchoRequest(), SuccessOrExit, VerifyOrExit, and Message::WriteBytes().
Referenced by Icmp::GetEchoSequence(), and Icmp::HandleMessage().
Field Documentation
OT_TOOL_PACKED_END
ot::Ip6::Icmp::Header OT_TOOL_PACKED_END
Referenced by Icmp::Header::SetSequence().
mHandlers
LinkedList<Handler> mHandlers private
Referenced by Icmp::HandleMessage(), and Icmp::RegisterHandler().
mEchoSequence
uint16_t mEchoSequence private
Referenced by Icmp::GetEchoSequence(), and Icmp::SendEchoRequest().
mEchoMode
otIcmp6EchoMode mEchoMode private
Referenced by Icmp::GetEchoMode(), Icmp::SetEchoMode(), and Icmp::ShouldHandleEchoRequest().
The documentation for this class was generated from the following files:
icmp6.hpp
icmp6.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale