OpenThread: StringWriter Class Reference
StringWriter Class Reference
Core-string
#include <string.hpp>
Public Member Functions
StringWriter & Append (const char *aFormat,...)
StringWriter & AppendHexBytes (const uint8_t *aBytes, uint16_t aLength)
StringWriter & AppendVarArgs (const char *aFormat, va_list aArgs)
StringWriter & Clear (void)
void ConvertToLowercase (void)
void ConvertToUppercase (void)
uint16_t GetLength (void) const
uint16_t GetSize (void) const
bool IsTruncated (void) const
StringWriter (char *aBuffer, uint16_t aSize)
Private Attributes
char * mBuffer
uint16_t mLength
const uint16_t mSize
Detailed Description
This class implements writing to a string buffer.
Constructor & Destructor Documentation
StringWriter()
StringWriter (char * aBuffer, uint16_t aSize)
This constructor initializes the object as cleared on the provided buffer.
Parameters
[in] aBuffer A pointer to the char buffer to write into.
[in] aSize The size of aBuffer.
References ot::kNullChar, and StringWriter::mBuffer.
Member Function Documentation
Clear()
StringWriter & Clear (void)
This method clears the string writer.
Returns
The string writer.
References ot::kNullChar, StringWriter::mBuffer, and StringWriter::mLength.
IsTruncated()
bool IsTruncated (void) const inline
This method returns whether the output is truncated.
Note
If the output is truncated, the buffer is still null-terminated.
Return values
true The output is truncated.
false The output is not truncated.
References StringWriter::mLength, and StringWriter::mSize.
Referenced by StringWriter::AppendVarArgs().
GetLength()
uint16_t GetLength (void) const inline
This method gets the length of the wanted string.
Similar to strlen() the length does not include the null character at the end of the string.
Returns
The string length.
References StringWriter::mLength.
GetSize()
uint16_t GetSize (void) const inline
This method returns the size (number of chars) in the buffer.
Returns
The size of the buffer.
References StringWriter::Append(), StringWriter::AppendHexBytes(), StringWriter::AppendVarArgs(), and StringWriter::mSize.
Append()
StringWriter & Append (const char * aFormat, ...)
This method appends printf() style formatted data to the buffer.
Parameters
[in] aFormat A pointer to the format string.
[in] ... Arguments for the format specification.
Returns
The string writer.
References StringWriter::AppendVarArgs().
Referenced by StringWriter::AppendHexBytes(), Address::AppendHexWords(), Mle::CheckReachability(), StringWriter::GetSize(), Output::OutputFormatV(), LinkQualityInfo::ToInfoString(), Address::ToString(), Cidr::ToString(), JoinerDiscerner::ToString(), Prefix::ToString(), SockAddr::ToString(), and DeviceMode::ToString().
AppendVarArgs()
StringWriter & AppendVarArgs (const char * aFormat, va_list aArgs)
This method appends printf() style formatted data to the buffer.
Parameters
[in] aFormat A pointer to the format string.
[in] aArgs Arguments for the format specification (as va_list).
Returns
The string writer.
References StringWriter::IsTruncated(), ot::kNullChar, StringWriter::mBuffer, StringWriter::mLength, StringWriter::mSize, and OT_ASSERT.
Referenced by StringWriter::Append(), and StringWriter::GetSize().
AppendHexBytes()
StringWriter & AppendHexBytes (const uint8_t * aBytes, uint16_t aLength)
This method appends an array of bytes in hex representation (using "%02x" style) to the buffer.
Parameters
[in] aBytes A pointer to buffer containing the bytes to append.
[in] aLength The length of aBytes buffer (in bytes).
Returns
The string writer.
References StringWriter::Append().
Referenced by StringWriter::GetSize(), ExtendedPanId::ToString(), ExtAddress::ToString(), Address::ToString(), and InterfaceIdentifier::ToString().
ConvertToLowercase()
void ConvertToLowercase (void) inline
This method converts all uppercase letter characters in the string to lowercase.
References StringWriter::mBuffer, and ot::StringConvertToLowercase().
ConvertToUppercase()
void ConvertToUppercase (void) inline
This method converts all lowercase letter characters in the string to uppercase.
References StringWriter::mBuffer, and ot::StringConvertToUppercase().
Field Documentation
mBuffer
char* mBuffer private
Referenced by StringWriter::AppendVarArgs(), String< kSize >::AsCString(), StringWriter::Clear(), StringWriter::ConvertToLowercase(), StringWriter::ConvertToUppercase(), and StringWriter::StringWriter().
mLength
uint16_t mLength private
Referenced by StringWriter::AppendVarArgs(), StringWriter::Clear(), StringWriter::GetLength(), and StringWriter::IsTruncated().
mSize
const uint16_t mSize private
Referenced by StringWriter::AppendVarArgs(), StringWriter::GetSize(), and StringWriter::IsTruncated().
The documentation for this class was generated from the following files:
string.hpp
string.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale