OpenThread: Allocatable< Type > Class Template Reference
Allocatable< Type > Class Template Reference
#include <heap_allocatable.hpp>
Public Member Functions
void Free (void)
Static Public Member Functions
template<typename... Args>
static Type * Allocate (Args &&... aArgs)
template<typename... Args>
static Type * AllocateAndInit (Args &&... aArgs)
Protected Member Functions
Allocatable (void)=default
Detailed Description
template<class Type>
class ot::Heap::Allocatable< Type >
This template class defines a Heap::Allocatable object.
Heap::Allocatable provides methods to allocate and free instances of Type on heap.
Users of this class should follow CRTP-style inheritance, i.e., the Type class itself should inherit from Allocatable<Type>.
The Type class destructor is used when Free() is called. The destructor frees any heap allocated data members that are stored in a Type instance (e.g., Heap::String, Heap::Data, etc).
Constructor & Destructor Documentation
Allocatable()
Allocatable (void) protected default
Referenced by Allocatable< Type >::Free().
Member Function Documentation
Allocate()
static Type* Allocate (Args &&... aArgs) inline static
This static method allocates a new instance of Type on heap and initializes it using Type constructor.
The Type class MUST have a constructor Type(Args...) which is invoked upon allocation of new Type to initialize it.
Parameters
[in] aArgs A set of arguments to pass to the Type constructor of the allocated Type instance.
Returns
A pointer to the newly allocated instance or nullptr if it fails to allocate.
References ot::Heap::CAlloc().
AllocateAndInit()
static Type* AllocateAndInit (Args &&... aArgs) inline static
This static method allocates a new instance of Type on heap and initializes it using Type::Init() method.
The Type class MUST have a default constructor (with no arguments) which is invoked upon allocation of new Type instance. It MUST also provide an Error Init(Args...) method to initialize the instance. If any Error other than kErrorNone is returned the initialization is considered failed.
Parameters
[in] aArgs A set of arguments to initialize the allocated Type instance.
Returns
A pointer to the newly allocated instance or nullptr if it fails to allocate or initialize.
References ot::Heap::CAlloc(), ot::kErrorNone, and VerifyOrExit.
Free()
void Free (void) inline
This method frees the Type instance.
The instance MUST be heap allocated using either Allocate() or AllocateAndInit().
The Free() method invokes the Type destructor before releasing the allocated heap buffer for the instance. This ensures that any heap allocated member variables in Type are freed before the Type instance itself is freed.
References Allocatable< Type >::Allocatable(), and ot::Heap::Free().
The documentation for this class was generated from the following file:
heap_allocatable.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale