OpenThread: MessageInfo Class Reference
MessageInfo Class Reference
Core-ipv6 » IPv6
#include <socket.hpp>
Public Member Functions
Ecn GetEcn (void) const
uint8_t GetHopLimit (void) const
const void * GetLinkInfo (void) const
bool GetMulticastLoop (void) const
Address & GetPeerAddr (void)
const Address & GetPeerAddr (void) const
uint16_t GetPeerPort (void) const
Address & GetSockAddr (void)
const Address & GetSockAddr (void) const
uint16_t GetSockPort (void) const
const ThreadLinkInfo * GetThreadLinkInfo (void) const
bool IsHostInterface (void) const
MessageInfo (void)
void SetEcn (Ecn aEcn)
void SetHopLimit (uint8_t aHopLimit)
void SetIsHostInterface (bool aIsHost)
void SetLinkInfo (const void *aLinkInfo)
void SetMulticastLoop (bool aMulticastLoop)
void SetPeerAddr (const Address &aAddress)
void SetPeerPort (uint16_t aPort)
void SetSockAddr (const Address &aAddress)
void SetSockPort (uint16_t aPort)
bool ShouldAllowZeroHopLimit (void) const
Public Member Functions inherited from Clearable< MessageInfo >
void Clear (void)
Additional Inherited Members
Data Fields inherited from otMessageInfo
bool mAllowZeroHopLimit: 1
TRUE to allow IPv6 Hop Limit 0 in mHopLimit, FALSE otherwise.
uint8_t mEcn: 2
The ECN status of the packet, represented as in the IPv6 header.
uint8_t mHopLimit
bool mIsHostInterface: 1
TRUE if packets sent/received via host interface, FALSE otherwise.
const void * mLinkInfo
A pointer to link-specific information.
bool mMulticastLoop: 1
TRUE to allow looping back multicast, FALSE otherwise.
otIp6Address mPeerAddr
The peer IPv6 address.
uint16_t mPeerPort
The peer transport-layer port.
otIp6Address mSockAddr
The local IPv6 address.
uint16_t mSockPort
The local transport-layer port.
Detailed Description
This class implements message information for an IPv6 message.
Constructor & Destructor Documentation
MessageInfo()
MessageInfo (void) inline
This constructor initializes the object.
References Clearable< MessageInfo >::Clear().
Member Function Documentation
GetSockAddr() [1/2]
Address& GetSockAddr (void) inline
This method returns a reference to the local socket address.
Returns
A reference to the local socket address.
References ot::AsCoreType(), and otMessageInfo::mSockAddr.
Referenced by Agent::Filter(), AddressResolver::HandleAddressError(), Icmp::HandleEchoRequest(), Mle::HandleLeaderData(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), AnnounceBeginServer::HandleRequest(), Mle::HandleUdpReceive(), Udp::SocketHandle::Matches(), Mle::ProcessMessageSecurity(), Ip6::ProcessReceiveCallback(), CoapBase::ProcessReceivedRequest(), CoapBase::Receive(), Ip6::SendDatagram(), CoapBase::SendMessage(), Udp::SendTo(), Ip6::ShouldForwardToThread(), Icmp::ShouldHandleEchoRequest(), and Checksum::VerifyMessageChecksum().
GetSockAddr() [2/2]
const Address& GetSockAddr (void) const inline
This method returns a reference to the local socket address.
Returns
A reference to the local socket address.
References ot::AsCoreType(), and otMessageInfo::mSockAddr.
SetSockAddr()
void SetSockAddr (const Address & aAddress) inline
This method sets the local socket address.
Parameters
[in] aAddress The IPv6 address.
References otMessageInfo::mSockAddr.
Referenced by Mle::CheckReachability(), Ip6::HandleDatagram(), Icmp::HandleEchoRequest(), Ip6::HandleOptions(), CoapBase::HandleRetransmissionTimer(), otUdpGetSockets(), Ip6::SendRaw(), Udp::SendTo(), Mle::TxMessage::SendTo(), and MessageInfo::SetSockAddrToRloc().
GetSockPort()
uint16_t GetSockPort (void) const inline
This method gets the local socket port.
Returns
The local socket port.
References otMessageInfo::mSockPort.
Referenced by Agent::Filter(), Udp::SocketHandle::Matches(), and Udp::SendTo().
SetSockPort()
void SetSockPort (uint16_t aPort) inline
This method gets the local socket port.
Parameters
[in] aPort The port value.
References otMessageInfo::mSockPort.
Referenced by otUdpGetSockets(), Udp::SendTo(), and MessageInfo::SetSockPortToTmf().
GetPeerAddr() [1/2]
Address& GetPeerAddr (void) inline
This method returns a reference to the peer socket address.
Returns
A reference to the peer socket address.
References ot::AsCoreType(), and otMessageInfo::mPeerAddr.
Referenced by AddressResolver::AddressResolver(), Ip6::AddTunneledMplOption(), Mle::CheckReachability(), Agent::Filter(), ResponsesQueue::FindMatchedResponse(), CoapBase::FindRelatedRequest(), AddressResolver::HandleAddressError(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), DiscoverScanner::HandleDiscoveryResponse(), Icmp::HandleEchoRequest(), Mle::HandleLeaderData(), Mle::HandleParentResponse(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), Mle::HandleUdpReceive(), Udp::SocketHandle::Matches(), Mle::ProcessMessageSecurity(), Ip6::SelectSourceAddress(), Ip6::SendDatagram(), Udp::SendDatagram(), DatasetManager::SendGetResponse(), CoapBase::SendMessage(), Udp::SendTo(), MessageInfo::SetSockAddrToRlocPeerAddrTo(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderAloc(), MessageInfo::SetSockAddrToRlocPeerAddrToLeaderRloc(), MessageInfo::SetSockAddrToRlocPeerAddrToRealmLocalAllRoutersMulticast(), Interpreter::SetUserCommands(), Ip6::ShouldForwardToThread(), and Checksum::VerifyMessageChecksum().
GetPeerAddr() [2/2]
const Address& GetPeerAddr (void) const inline
This method returns a reference to the peer socket address.
Returns
A reference to the peer socket address.
References ot::AsCoreType(), and otMessageInfo::mPeerAddr.
SetPeerAddr()
void SetPeerAddr (const Address & aAddress) inline
This method sets the peer's socket address.
Parameters
[in] aAddress The IPv6 address.
References otMessageInfo::mPeerAddr.
Referenced by Mle::CheckReachability(), Ip6::HandleDatagram(), Icmp::HandleEchoRequest(), Ip6::HandleOptions(), CoapBase::HandleRetransmissionTimer(), otUdpGetSockets(), DatasetManager::SendGetRequest(), Ip6::SendRaw(), Udp::SendTo(), Mle::TxMessage::SendTo(), and MessageInfo::SetSockAddrToRlocPeerAddrTo().
GetPeerPort()
uint16_t GetPeerPort (void) const inline
This method gets the peer socket port.
Returns
The peer socket port.
References otMessageInfo::mPeerPort.
Referenced by ResponsesQueue::FindMatchedResponse(), CoapBase::FindRelatedRequest(), Udp::SocketHandle::Matches(), and CoapBase::SendMessage().
SetPeerPort()
void SetPeerPort (uint16_t aPort) inline
This method gets the peer socket port.
Parameters
[in] aPort The port value.
References otMessageInfo::mPeerPort.
Referenced by CoapBase::HandleRetransmissionTimer(), MessageInfo::MessageInfo(), otUdpGetSockets(), Mle::TxMessage::SendTo(), and Interpreter::SetUserCommands().
GetHopLimit()
uint8_t GetHopLimit (void) const inline
This method gets the Hop Limit.
Returns
The Hop Limit.
References otMessageInfo::mHopLimit.
Referenced by Mle::HandleUdpReceive(), Ip6::SendDatagram(), and CoapBase::SendMessage().
SetHopLimit()
void SetHopLimit (uint8_t aHopLimit) inline
This method sets the Hop Limit.
Parameters
[in] aHopLimit The Hop Limit.
References otMessageInfo::mHopLimit.
Referenced by Ip6::HandleDatagram(), Ip6::HandleOptions(), CoapBase::HandleRetransmissionTimer(), Ip6::SendRaw(), and Mle::TxMessage::SendTo().
GetMulticastLoop()
bool GetMulticastLoop (void) const inline
This method returns whether multicast may be looped back.
Return values
TRUE If message may be looped back.
FALSE If message must not be looped back.
References otMessageInfo::mMulticastLoop.
Referenced by Ip6::SendDatagram(), and CoapBase::SendMessage().
SetMulticastLoop()
void SetMulticastLoop (bool aMulticastLoop) inline
This method sets whether multicast may be looped back.
Parameters
[in] aMulticastLoop Whether allow looping back multicast.
References otMessageInfo::mMulticastLoop.
Referenced by CoapBase::HandleRetransmissionTimer().
GetLinkInfo()
const void* GetLinkInfo (void) const inline
This method returns a pointer to the link-specific information object.
Returns
A pointer to the link-specific information object.
References otMessageInfo::mLinkInfo.
Referenced by Mle::HandleUdpReceive().
SetLinkInfo()
void SetLinkInfo (const void * aLinkInfo) inline
This method sets the pointer to the link-specific information object.
Parameters
[in] aLinkInfo A pointer to the link-specific information object.
References otMessageInfo::mLinkInfo.
Referenced by Ip6::HandleDatagram(), and Ip6::HandleOptions().
GetThreadLinkInfo()
const ThreadLinkInfo* GetThreadLinkInfo (void) const inline
This method returns a pointer to the link-specific information as a ThreadLinkInfo.
Returns
A pointer to to the link-specific information object as ThreadLinkInfo.
References otMessageInfo::mLinkInfo.
Referenced by DiscoverScanner::HandleDiscoveryResponse(), Mle::HandleParentResponse(), and Mle::HandleUdpReceive().
GetEcn()
Ecn GetEcn (void) const inline
This method gets the ECN status.
Returns
The ECN status, as represented in the IP header.
References otMessageInfo::mEcn.
Referenced by Ip6::SendDatagram().
SetEcn()
void SetEcn (Ecn aEcn) inline
This method sets the ECN status.
Parameters
[in] aEcn The ECN status, as represented in the IP header.
References otMessageInfo::mEcn.
Referenced by Ip6::HandleDatagram().
IsHostInterface()
bool IsHostInterface (void) const inline
This method indicates whether peer is via the host interface.
Return values
TRUE if the peer is via the host interface.
FALSE if the peer is via the Thread interface.
References otMessageInfo::mIsHostInterface.
Referenced by Udp::HandlePayload(), Udp::SendDatagram(), and CoapBase::SendMessage().
ShouldAllowZeroHopLimit()
bool ShouldAllowZeroHopLimit (void) const inline
This method indicates whether or not to apply hop limit 0.
Return values
TRUE if applying hop limit 0 when mHopLimit field is 0.
FALSE if applying default OPENTHREAD_CONFIG_IP6_HOP_LIMIT_DEFAULT when mHopLimit field is 0.
References otMessageInfo::mAllowZeroHopLimit.
Referenced by Ip6::SendDatagram().
SetIsHostInterface()
void SetIsHostInterface (bool aIsHost) inline
This method sets whether the peer is via the host interface.
Parameters
[in] aIsHost TRUE if the peer is via the host interface, FALSE otherwise.
References otMessageInfo::mIsHostInterface.
Referenced by CoapBase::HandleRetransmissionTimer(), and otUdpGetSockets().
The documentation for this class was generated from the following file:
socket.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale