OpenThread: Tasklet::Scheduler Class Reference
Tasklet::Scheduler Class Reference
#include <tasklet.hpp>
Public Member Functions
bool AreTaskletsPending (void) const
void ProcessQueuedTasklets (void)
Scheduler (void)
Private Member Functions
void PostTasklet (Tasklet &aTasklet)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Private Attributes
Tasklet * mTail
Friends
class Tasklet
Detailed Description
This class implements the tasklet scheduler.
Constructor & Destructor Documentation
Scheduler()
Scheduler (void) inline
This constructor initializes the object.
Member Function Documentation
AreTaskletsPending()
bool AreTaskletsPending (void) const inline
This method indicates whether or not there are tasklets pending.
Return values
TRUE If there are tasklets pending.
FALSE If there are no tasklets pending.
References Tasklet::Scheduler::mTail, Tasklet::Scheduler::PostTasklet(), and Tasklet::Scheduler::ProcessQueuedTasklets().
ProcessQueuedTasklets()
void ProcessQueuedTasklets (void)
This method processes all tasklets queued when this is called.
References Tasklet::mNext, and Tasklet::RunTask().
Referenced by Tasklet::Scheduler::AreTaskletsPending().
PostTasklet()
void PostTasklet (Tasklet & aTasklet) private
References InstanceLocator::GetInstance(), Tasklet::mNext, and otTaskletsSignalPending().
Referenced by Tasklet::Scheduler::AreTaskletsPending().
Friends And Related Function Documentation
Tasklet
friend class Tasklet friend
Field Documentation
mTail
Tasklet* mTail private
Referenced by Tasklet::Scheduler::AreTaskletsPending().
The documentation for this class was generated from the following files:
tasklet.hpp
tasklet.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale