OpenThread: OptionMpl Class Reference
OptionMpl Class Reference
Core-ipv6 » MPL
#include <ip6_mpl.hpp>
Public Types
enum SeedIdLength : uint8_t { kSeedIdLength0 = 0 << 6, kSeedIdLength2 = 1 << 6, kSeedIdLength8 = 2 << 6, kSeedIdLength16 = 3 << 6 }
Public Types inherited from OptionHeader
enum Action : uint8_t { kActionSkip = 0x00, kActionDiscard = 0x40, kActionForceIcmp = 0x80, kActionIcmp = 0xc0 }
Public Member Functions
void ClearMaxFlag (void)
uint16_t GetSeedId (void) const
SeedIdLength GetSeedIdLength (void) const
uint8_t GetSequence (void) const
uint8_t GetTotalLength (void) const
void Init (void)
bool IsMaxFlagSet (void) const
void SetMaxFlag (void)
void SetSeedId (uint16_t aSeedId)
void SetSeedIdLength (SeedIdLength aSeedIdLength)
void SetSequence (uint8_t aSequence)
Public Member Functions inherited from OptionHeader
Action GetAction (void) const
uint8_t GetLength (void) const
uint8_t GetType (void) const
OptionHeader (void)
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Attributes
static constexpr uint8_t kMinLength = 2
static constexpr uint8_t kType = 0x6d
Private Attributes
uint8_t mControl
uint16_t mSeedId
uint8_t mSequence
Static Private Attributes
static constexpr uint8_t kMaxFlag = 1 << 5
static constexpr uint8_t kSeedIdLengthMask = 3 << 6
Detailed Description
This class implements MPL header generation and parsing.
Member Enumeration Documentation
SeedIdLength
enum SeedIdLength : uint8_t
MPL Seed Id lengths.
Enumerator
kSeedIdLength0
0-byte MPL Seed Id Length.
kSeedIdLength2
2-byte MPL Seed Id Length.
kSeedIdLength8
8-byte MPL Seed Id Length.
kSeedIdLength16
16-byte MPL Seed Id Length.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the MPL header.
References OptionMpl::mControl, OptionHeader::SetLength(), and OptionHeader::SetType().
Referenced by Mpl::InitOption().
GetTotalLength()
uint8_t GetTotalLength (void) const inline
This method returns the total MPL Option length value including option header.
Returns
The total IPv6 Option Length.
References OptionHeader::GetLength(), and OptionHeader::OptionHeader().
Referenced by Ip6::AddMplOption(), and Ip6::InsertMplOption().
GetSeedIdLength()
SeedIdLength GetSeedIdLength (void) const inline
This method returns the MPL Seed Id Length value.
Returns
The MPL Seed Id Length value.
References OptionMpl::kSeedIdLengthMask, and OptionMpl::mControl.
Referenced by Mpl::ProcessOption().
SetSeedIdLength()
void SetSeedIdLength (SeedIdLength aSeedIdLength) inline
This method sets the MPL Seed Id Length value.
Parameters
[in] aSeedIdLength The MPL Seed Length.
References OptionMpl::kSeedIdLengthMask, and OptionMpl::mControl.
Referenced by Mpl::InitOption().
IsMaxFlagSet()
bool IsMaxFlagSet (void) const inline
This method indicates whether or not the MPL M flag is set.
Return values
TRUE If the MPL M flag is set.
FALSE If the MPL M flag is not set.
References OptionMpl::kMaxFlag, and OptionMpl::mControl.
ClearMaxFlag()
void ClearMaxFlag (void) inline
This method clears the MPL M flag.
References OptionMpl::kMaxFlag, and OptionMpl::mControl.
SetMaxFlag()
void SetMaxFlag (void) inline
This method sets the MPL M flag.
References OptionMpl::kMaxFlag, and OptionMpl::mControl.
GetSequence()
uint8_t GetSequence (void) const inline
This method returns the MPL Sequence value.
Returns
The MPL Sequence value.
References OptionMpl::mSequence.
Referenced by Mpl::ProcessOption().
SetSequence()
void SetSequence (uint8_t aSequence) inline
This method sets the MPL Sequence value.
Parameters
[in] aSequence The MPL Sequence value.
References OptionMpl::mSequence.
Referenced by Mpl::InitOption().
GetSeedId()
uint16_t GetSeedId (void) const inline
This method returns the MPL Seed Id value.
Returns
The MPL Seed Id value.
References ot::Encoding::BigEndian::HostSwap16(), and OptionMpl::mSeedId.
Referenced by Mpl::ProcessOption().
SetSeedId()
void SetSeedId (uint16_t aSeedId) inline
This method sets the MPL Seed Id value.
Parameters
[in] aSeedId The MPL Seed Id value.
References ot::Encoding::BigEndian::HostSwap16(), and OptionMpl::mSeedId.
Referenced by Mpl::InitOption(), and Mpl::ProcessOption().
Field Documentation
kType
constexpr uint8_t kType = 0x6d static
Referenced by Ip6::HandleOptions(), and Ip6::RemoveMplOption().
kMinLength
constexpr uint8_t kMinLength = 2 static
Referenced by Mpl::ProcessOption().
kSeedIdLengthMask
constexpr uint8_t kSeedIdLengthMask = 3 << 6 static private
Referenced by OptionMpl::GetSeedIdLength(), and OptionMpl::SetSeedIdLength().
kMaxFlag
constexpr uint8_t kMaxFlag = 1 << 5 static private
Referenced by OptionMpl::ClearMaxFlag(), OptionMpl::IsMaxFlagSet(), and OptionMpl::SetMaxFlag().
mControl
uint8_t mControl private
Referenced by OptionMpl::ClearMaxFlag(), OptionMpl::GetSeedIdLength(), OptionMpl::Init(), OptionMpl::IsMaxFlagSet(), OptionMpl::SetMaxFlag(), and OptionMpl::SetSeedIdLength().
mSequence
uint8_t mSequence private
Referenced by OptionMpl::GetSequence(), and OptionMpl::SetSequence().
mSeedId
uint16_t mSeedId private
Referenced by OptionMpl::GetSeedId(), Mpl::GetSeedId(), OptionMpl::SetSeedId(), and Mpl::SetSeedId().
The documentation for this class was generated from the following file:
ip6_mpl.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale