OpenThread: Buffer Class Reference
Buffer Class Reference
Core-message
#include <message.hpp>
Data Structures
struct Metadata
Public Member Functions
Buffer * GetNextBuffer (void)
const Buffer * GetNextBuffer (void) const
void SetNextBuffer (Buffer *aNext)
Public Member Functions inherited from LinkedListEntry< Buffer >
const Buffer * GetNext (void) const
Buffer * GetNext (void)
void SetNext (Buffer *aNext)
Protected Member Functions
uint8_t * GetData (void)
const uint8_t * GetData (void) const
uint8_t * GetFirstData (void)
const uint8_t * GetFirstData (void) const
Metadata & GetMetadata (void)
const Metadata & GetMetadata (void) const
Static Protected Attributes
static constexpr uint16_t kBufferDataSize = kBufferSize - sizeof(otMessageBuffer)
static constexpr uint16_t kHeadBufferDataSize = kBufferDataSize - sizeof(Metadata)
Private Attributes
union {
uint8_t mData [kBufferDataSize]
struct {
uint8_t mData [kHeadBufferDataSize]
Metadata mMetadata
} mHead
} mBuffer
Friends
class Message
A TMF message.
Additional Inherited Members
Data Fields inherited from otMessageBuffer
struct otMessageBuffer * mNext
Pointer to the next buffer.
Detailed Description
This class represents a Message buffer.
Member Function Documentation
GetNextBuffer() [1/2]
Buffer* GetNextBuffer (void) inline
This method returns a pointer to the next message buffer.
Returns
A pointer to the next message buffer.
GetNextBuffer() [2/2]
const Buffer* GetNextBuffer (void) const inline
This method returns a pointer to the next message buffer.
Returns
A pointer to the next message buffer.
SetNextBuffer()
void SetNextBuffer (Buffer * aNext) inline
This method sets the pointer to the next message buffer.
Parameters
[in] aNext A pointer to the next buffer.
GetMetadata() [1/2]
Metadata& GetMetadata (void) inline protected
GetMetadata() [2/2]
const Metadata& GetMetadata (void) const inline protected
GetFirstData() [1/2]
uint8_t* GetFirstData (void) inline protected
Referenced by Message::GetHelpData(), and Message::ParseHeader().
GetFirstData() [2/2]
const uint8_t* GetFirstData (void) const inline protected
GetData() [1/2]
uint8_t* GetData (void) inline protected
GetData() [2/2]
const uint8_t* GetData (void) const inline protected
Friends And Related Function Documentation
Message
friend class Message friend
A TMF message.
Field Documentation
kBufferDataSize
constexpr uint16_t kBufferDataSize = kBufferSize - sizeof(otMessageBuffer) static protected
kHeadBufferDataSize
constexpr uint16_t kHeadBufferDataSize = kBufferDataSize - sizeof(Metadata) static protected
Referenced by Message::GetHelpData().
mMetadata
Metadata mMetadata
mData
uint8_t mData[kBufferDataSize]
mHead
struct { ... } mHead
mBuffer
union { ... } mBuffer
The documentation for this class was generated from the following file:
message.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale