OpenThread: InstanceLocatorInit Class Reference
InstanceLocatorInit Class Reference
Core-locator
#include <locator.hpp>
Protected Member Functions
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Additional Inherited Members
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Detailed Description
This class implements a locator for an OpenThread Instance object.
The InstanceLocatorInit is similar to InstanceLocator but provides a default constructor (instead of a parameterized one) and allows an inheriting class to initialize the object (set the OpenThread Instance) post constructor call using the Init() method. This class is intended for types that require a default constructor and cannot use a parameterized one. (e.g., Neighbor/Child/Router classes which are used as a C array element type inChildTable/RouterTable).
The inheriting class from InstanceLocatorInit should ensure that object is properly initialized after the object is created and more importantly that it is re-initialized when/if it is cleared or reset.
Constructor & Destructor Documentation
InstanceLocatorInit()
InstanceLocatorInit (void) inline protected
This is the default constructor for the InstanceLocatorInit object.
Member Function Documentation
Init()
void Init (Instance & aInstance) inline protected
This method (re)initializes the object and sets the OpenThread Instance.
Parameters
[in] aInstance A reference to the OpenThread Instance.
References OT_UNUSED_VARIABLE.
Referenced by AddressResolver::HandleAddressError(), LinkQualityInfo::Init(), and Neighbor::Init().
The documentation for this class was generated from the following file:
locator.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale