OpenThread: LinkedList< Type > Class Template Reference
LinkedList< Type > Class Template Reference
Core-linked-list
#include <linked_list.hpp>
Data Structures
class ConstIterator
class Iterator
Public Member Functions
Error Add (Type &aEntry)
Iterator begin (void)
ConstIterator begin (void) const
void Clear (void)
bool Contains (const Type &aEntry) const
template<typename Indicator >
bool ContainsMatching (const Indicator &aIndicator) const
Iterator end (void)
ConstIterator end (void) const
Error Find (const Type &aEntry, const Type *&aPrevEntry) const
Error Find (const Type &aEntry, Type *&aPrevEntry)
template<typename Indicator >
const Type * FindMatching (const Type *aBegin, const Type *aEnd, const Indicator &aIndicator, const Type *&aPrevEntry) const
template<typename Indicator >
Type * FindMatching (const Type *aBegin, const Type *aEnd, const Indicator &aIndicator, Type *&aPrevEntry)
template<typename Indicator >
const Type * FindMatching (const Indicator &aIndicator, const Type *&aPrevEntry) const
template<typename Indicator >
Type * FindMatching (const Indicator &aIndicator, Type *&aPrevEntry)
template<typename Indicator >
const Type * FindMatching (const Indicator &aIndicator) const
template<typename Indicator >
Type * FindMatching (const Indicator &aIndicator)
Type * GetHead (void)
const Type * GetHead (void) const
const Type * GetTail (void) const
Type * GetTail (void)
bool IsEmpty (void) const
LinkedList (void)
Type * Pop (void)
Type * PopAfter (Type *aPrevEntry)
void Push (Type &aEntry)
void PushAfter (Type &aEntry, Type &aPrevEntry)
Error Remove (const Type &aEntry)
template<typename Indicator >
void RemoveAllMatching (const Indicator &aIndicator, LinkedList &aRemovedList)
template<typename Indicator >
Type * RemoveMatching (const Indicator &aIndicator)
void SetHead (Type *aHead)
Private Attributes
Type * mHead
Detailed Description
template<typename Type>
class ot::LinkedList< Type >
This template class represents a singly linked list.
The template type Type should provide GetNext() and SetNext() methods (which can be realized by Type inheriting from LinkedListEntry<Type> class).
Constructor & Destructor Documentation
LinkedList()
LinkedList (void) inline
This constructor initializes the linked list.
Member Function Documentation
GetHead() [1/2]
Type* GetHead (void) inline
This method returns the entry at the head of the linked list
Returns
Pointer to the entry at the head of the linked list, or nullptr if the list is empty.
GetHead() [2/2]
const Type* GetHead (void) const inline
This method returns the entry at the head of the linked list.
Returns
Pointer to the entry at the head of the linked list, or nullptr if the list is empty.
SetHead()
void SetHead (Type * aHead) inline
This method sets the head of the linked list to a given entry.
Parameters
[in] aHead A pointer to an entry to set as the head of the linked list.
Clear()
void Clear (void) inline
This method clears the linked list.
IsEmpty()
bool IsEmpty (void) const inline
This method indicates whether the linked list is empty or not.
Return values
TRUE If the linked list is empty.
FALSE If the linked list is not empty.
Push()
void Push (Type & aEntry) inline
This method pushes an entry at the head of the linked list.
Parameters
[in] aEntry A reference to an entry to push at the head of linked list.
Referenced by LinkedList< ot::Ip6::Icmp::Handler >::RemoveAllMatching().
PushAfter()
void PushAfter (Type & aEntry, Type & aPrevEntry) inline
This method pushes an entry after a given previous existing entry in the linked list.
Parameters
[in] aEntry A reference to an entry to push into the list.
[in] aPrevEntry A reference to a previous entry (new entry aEntry will be pushed after this).
Pop()
Type* Pop (void) inline
This method pops an entry from head of the linked list.
Note
This method does not change the popped entry itself, i.e., the popped entry next pointer stays as before.
Returns
The entry that was popped if the list is not empty, or nullptr if the list is empty.
Referenced by OwningList< Type >::Pop().
PopAfter()
Type* PopAfter (Type * aPrevEntry) inline
This method pops an entry after a given previous entry.
Note
This method does not change the popped entry itself, i.e., the popped entry next pointer stays as before.
Parameters
[in] aPrevEntry A pointer to a previous entry. If it is not nullptr the entry after this will be popped, otherwise (if it is nullptr) the entry at the head of the list is popped.
Returns
Pointer to the entry that was popped, or nullptr if there is no entry to pop.
Referenced by OwningList< Type >::PopAfter().
Contains()
bool Contains (const Type & aEntry) const inline
This method indicates whether the linked list contains a given entry.
Parameters
[in] aEntry A reference to an entry.
Return values
TRUE The linked list contains aEntry.
FALSE The linked list does not contain aEntry.
ContainsMatching()
bool ContainsMatching (const Indicator & aIndicator) const inline
This template method indicates whether the linked list contains an entry matching a given entry indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aIndicator An entry indicator to match against entries in the list.
Return values
TRUE The linked list contains an entry matching aIndicator.
FALSE The linked list contains no entry matching aIndicator.
Add()
Error Add (Type & aEntry) inline
This method adds an entry (at the head of the linked list) if it is not already in the list.
Parameters
[in] aEntry A reference to an entry to add.
Return values
kErrorNone The entry was successfully added at the head of the list.
kErrorAlready The entry is already in the list.
Remove()
Error Remove (const Type & aEntry) inline
This method removes an entry from the linked list.
Note
This method does not change the removed entry aEntry itself (it is const), i.e., the entry next pointer of aEntry stays as before.
Parameters
[in] aEntry A reference to an entry to remove.
Return values
kErrorNone The entry was successfully removed from the list.
kErrorNotFound Could not find the entry in the list.
RemoveMatching()
Type* RemoveMatching (const Indicator & aIndicator) inline
This template method removes an entry matching a given entry indicator from the linked list.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Note
This method does not change the removed entry itself (which is returned in case of success), i.e., the entry next pointer stays as before.
Parameters
[in] aIndicator An entry indicator to match against entries in the list.
Returns
A pointer to the removed matching entry if one could be found, or nullptr if no matching entry is found.
Referenced by OwningList< Type >::RemoveMatching().
RemoveAllMatching()
void RemoveAllMatching (const Indicator & aIndicator, LinkedList< Type > & aRemovedList) inline
This template method removes all entries in the list matching a given entry indicator from the list and adds them to a new list.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aIndicator An entry indicator to match against entries in the list.
[in] aRemovedList The list to add the removed entries to.
Referenced by OwningList< Type >::RemoveAllMatching().
Find() [1/2]
Error Find (const Type & aEntry, const Type *& aPrevEntry) const inline
This method searches within the linked list to find an entry and if found returns a pointer to previous entry.
Parameters
[in] aEntry A reference to an entry to find.
[out] aPrevEntry A pointer to output the previous entry on success (when aEntry is found in the list). aPrevEntry is set to nullptr if aEntry is the head of the list. Otherwise it is updated to point to the previous entry before aEntry in the list.
Return values
kErrorNone The entry was found in the list and aPrevEntry was updated successfully.
kErrorNotFound The entry was not found in the list.
Find() [2/2]
Error Find (const Type & aEntry, Type *& aPrevEntry) inline
This method searches within the linked list to find an entry and if found returns a pointer to previous entry.
Parameters
[in] aEntry A reference to an entry to find.
[out] aPrevEntry A pointer to output the previous entry on success (when aEntry is found in the list). aPrevEntry is set to nullptr if aEntry is the head of the list. Otherwise it is updated to point to the previous entry before aEntry in the list.
Return values
kErrorNone The entry was found in the list and aPrevEntry was updated successfully.
kErrorNotFound The entry was not found in the list.
FindMatching() [1/6]
const Type* FindMatching (const Type * aBegin, const Type * aEnd, const Indicator & aIndicator, const Type *& aPrevEntry) const inline
This template method searches within a given range of the linked list to find an entry matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aBegin A pointer to the begin of the range.
[in] aEnd A pointer to the end of the range, or nullptr to search all entries after aBegin.
[in] aIndicator An indicator to match with entries in the list.
[out] aPrevEntry A pointer to output the previous entry on success (when a match is found in the list). aPrevEntry is set to nullptr if the matching entry is the head of the list. Otherwise it is updated to point to the previous entry before the matching entry in the list.
Returns
A pointer to the matching entry if one is found, or nullptr if no matching entry was found.
FindMatching() [2/6]
Type* FindMatching (const Type * aBegin, const Type * aEnd, const Indicator & aIndicator, Type *& aPrevEntry) inline
This template method searches within a given range of the linked list to find an entry matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aBegin A pointer to the begin of the range.
[in] aEnd A pointer to the end of the range, or nullptr to search all entries after aBegin.
[in] aIndicator An indicator to match with entries in the list.
[out] aPrevEntry A pointer to output the previous entry on success (when a match is found in the list). aPrevEntry is set to nullptr if the matching entry is the head of the list. Otherwise it is updated to point to the previous entry before the matching entry in the list.
Returns
A pointer to the matching entry if one is found, or nullptr if no matching entry was found.
FindMatching() [3/6]
const Type* FindMatching (const Indicator & aIndicator, const Type *& aPrevEntry) const inline
This template method searches within the linked list to find an entry matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aIndicator An indicator to match with entries in the list.
[out] aPrevEntry A pointer to output the previous entry on success (when a match is found in the list). aPrevEntry is set to nullptr if the matching entry is the head of the list. Otherwise it is updated to point to the previous entry before the matching entry in the list.
Returns
A pointer to the matching entry if one is found, or nullptr if no matching entry was found.
FindMatching() [4/6]
Type* FindMatching (const Indicator & aIndicator, Type *& aPrevEntry) inline
This template method searches within the linked list to find an entry matching a given indicator, and if found returns a pointer to its previous entry in the list.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aIndicator An indicator to match with entries in the list.
[out] aPrevEntry A pointer to output the previous entry on success (when a match is found in the list). aPrevEntry is set to nullptr if the matching entry is the head of the list. Otherwise it is updated to point to the previous entry before the matching entry in the list.
Returns
A pointer to the matching entry if one is found, or nullptr if no matching entry was found.
FindMatching() [5/6]
const Type* FindMatching (const Indicator & aIndicator) const inline
This template method searches within the linked list to find an entry matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aIndicator An indicator to match with entries in the list.
Returns
A pointer to the matching entry if one is found, or nullptr if no matching entry was found.
FindMatching() [6/6]
Type* FindMatching (const Indicator & aIndicator) inline
This template method searches within the linked list to find an entry matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aIndicator An indicator to match with entries in the list.
Returns
A pointer to the matching entry if one is found, or nullptr if no matching entry was found.
GetTail() [1/2]
const Type* GetTail (void) const inline
This method returns the tail of the linked list (i.e., the last entry in the list).
Returns
A pointer to the tail entry in the linked list or nullptr if the list is empty.
GetTail() [2/2]
Type* GetTail (void) inline
This method returns the tail of the linked list (i.e., the last entry in the list).
Returns
A pointer to the tail entry in the linked list or nullptr if the list is empty.
Referenced by LinkedList< ot::Ip6::Icmp::Handler >::GetTail().
begin() [1/2]
Iterator begin (void) inline
end() [1/2]
Iterator end (void) inline
begin() [2/2]
ConstIterator begin (void) const inline
end() [2/2]
ConstIterator end (void) const inline
Field Documentation
mHead
Type* mHead private
The documentation for this class was generated from the following file:
linked_list.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale