OpenThread: NetworkData Class Reference
NetworkData Class Reference
#include <cli_network_data.hpp>
Public Types
typedef Utils::CmdLineParser::Arg Arg
typedef char FlagsString[kFlagsStringSize]
Flags String type (char array of kFlagsStringSize).
Public Member Functions
NetworkData (Output &aOutput)
void OutputPrefix (const otBorderRouterConfig &aConfig)
void OutputRoute (const otExternalRouteConfig &aConfig)
void OutputService (const otServiceConfig &aConfig)
otError Process (Arg aArgs[])
Static Public Member Functions
static void PrefixFlagsToString (const otBorderRouterConfig &aConfig, FlagsString &aString)
static void RouteFlagsToString (const otExternalRouteConfig &aConfig, FlagsString &aString)
Static Public Attributes
static constexpr uint16_t kFlagsStringSize = 17
Private Types
using Command = CommandEntry< NetworkData >
Private Types inherited from OutputBase
typedef Utils::CmdLineParser::Arg Arg
An argument.
Private Member Functions
otError GetNextPrefix (otNetworkDataIterator *aIterator, otBorderRouterConfig *aConfig, bool aLocal)
otError GetNextRoute (otNetworkDataIterator *aIterator, otExternalRouteConfig *aConfig, bool aLocal)
otError GetNextService (otNetworkDataIterator *aIterator, otServiceConfig *aConfig, bool aLocal)
otError OutputBinary (bool aLocal)
void OutputPrefixes (bool aLocal)
void OutputRoutes (bool aLocal)
void OutputServices (bool aLocal)
template<CommandId kCommandId>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
template<>
otError Process (Arg aArgs[])
Private Member Functions inherited from OutputWrapper
otInstance * GetInstancePtr (void)
template<uint8_t kBytesLength>
void OutputBytes (const uint8_t(&aBytes)[kBytesLength])
void OutputBytes (const uint8_t *aBytes, uint16_t aLength)
template<uint8_t kBytesLength>
void OutputBytesLine (const uint8_t(&aBytes)[kBytesLength])
void OutputBytesLine (const uint8_t *aBytes, uint16_t aLength)
template<typename Cli , uint16_t kLength>
void OutputCommandTable (const CommandEntry< Cli >(&aCommandTable)[kLength])
void OutputEnabledDisabledStatus (bool aEnabled)
void OutputExtAddress (const otExtAddress &aExtAddress)
void OutputExtAddressLine (const otExtAddress &aExtAddress)
template<typename... Args>
void OutputFormat (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputFormat (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (const char *aFormat, Args... aArgs)
template<typename... Args>
void OutputLine (uint8_t aIndentSize, const char *aFormat, Args... aArgs)
void OutputSpaces (uint8_t aCount)
template<uint8_t kTableNumColumns>
void OutputTableHeader (const char *const (&aTitles)[kTableNumColumns], const uint8_t(&aWidths)[kTableNumColumns])
template<uint8_t kTableNumColumns>
void OutputTableSeparator (const uint8_t(&aWidths)[kTableNumColumns])
OutputWrapper (Output &aOutput)
Private Member Functions inherited from OutputBase
OutputBase (void)=default
Additional Inherited Members
Static Private Member Functions inherited from OutputBase
template<typename EnumType , uint16_t kLength>
static const char * Stringify (EnumType aEnum, const char *const (&aTable)[kLength], const char *aNotFound=kUnknownString)
Static Private Attributes inherited from OutputBase
static const char kUnknownString [] = "unknown"
Detailed Description
This class implements the Network Data CLI.
Member Typedef Documentation
Arg
typedef Utils::CmdLineParser::Arg Arg
FlagsString
typedef char FlagsString[kFlagsStringSize]
Flags String type (char array of kFlagsStringSize).
Command
using Command = CommandEntry<NetworkData> private
Constructor & Destructor Documentation
NetworkData()
NetworkData (Output & aOutput) inline explicit
Constructor
Parameters
[in] aOutput The CLI console output context
References NetworkData::OutputPrefix(), NetworkData::OutputRoute(), NetworkData::OutputService(), NetworkData::PrefixFlagsToString(), NetworkData::Process(), and NetworkData::RouteFlagsToString().
Member Function Documentation
Process() [1/4]
otError Process (Arg aArgs[])
This method interprets a list of CLI arguments.
Parameters
[in] aArgs An array of command line arguments.
netdata help
netdata help
help
publish
register
show
steeringdata
unpublish
Done
Gets a list of netdata CLI commands.
See also
References CmdEntry, ExitNow, BinarySearch::Find(), BinarySearch::IsSorted(), kCommands, OutputBase::CommandEntry< Cli >::mHandler, OT_ERROR_INVALID_COMMAND, OT_ERROR_NONE, OutputWrapper::OutputCommandTable(), and VerifyOrExit.
Referenced by NetworkData::NetworkData(), and NetworkData::OutputService().
OutputPrefix()
void OutputPrefix (const otBorderRouterConfig & aConfig)
This method outputs the prefix config.
Parameters
[in] aConfig The prefix config.
References otBorderRouterConfig::mPreference, otBorderRouterConfig::mPrefix, otBorderRouterConfig::mRloc16, OutputWrapper::OutputFormat(), OutputWrapper::OutputLine(), Interpreter::PreferenceToString(), and NetworkData::PrefixFlagsToString().
Referenced by NetworkData::NetworkData(), and NetworkData::OutputPrefixes().
OutputRoute()
void OutputRoute (const otExternalRouteConfig & aConfig)
This method outputs the route config.
Parameters
[in] aConfig The route config.
References otExternalRouteConfig::mPreference, otExternalRouteConfig::mPrefix, otExternalRouteConfig::mRloc16, OutputWrapper::OutputFormat(), OutputWrapper::OutputLine(), Interpreter::PreferenceToString(), and NetworkData::RouteFlagsToString().
Referenced by NetworkData::NetworkData(), and NetworkData::OutputRoutes().
OutputService()
void OutputService (const otServiceConfig & aConfig)
This method outputs the service config.
Parameters
[in] aConfig The service config.
References ot::Cli::Cmd(), ExitNow, OutputWrapper::GetInstancePtr(), otServiceConfig::mEnterpriseNumber, otServerConfig::mRloc16, otServiceConfig::mServerConfig, otServerConfig::mServerData, otServerConfig::mServerDataLength, otServiceConfig::mServiceData, otServiceConfig::mServiceDataLength, otServerConfig::mStable, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_UNUSED_VARIABLE, otBorderRouterRegister(), otNetDataPublishDnsSrpServiceAnycast(), otNetDataPublishDnsSrpServiceUnicast(), otNetDataPublishDnsSrpServiceUnicastMeshLocalEid(), otNetDataPublishExternalRoute(), otNetDataPublishOnMeshPrefix(), otNetDataUnpublishDnsSrpService(), otNetDataUnpublishPrefix(), otServerRegister(), OutputWrapper::OutputBytes(), OutputWrapper::OutputFormat(), OutputWrapper::OutputLine(), ot::Utils::CmdLineParser::ParseAsUint16(), ot::Utils::CmdLineParser::ParseAsUint8(), NetworkData::Process(), and SuccessOrExit.
Referenced by NetworkData::NetworkData(), and NetworkData::OutputServices().
PrefixFlagsToString()
void PrefixFlagsToString (const otBorderRouterConfig & aConfig, FlagsString & aString) static
This method converts the flags from a given prefix config to string.
Parameters
[in] aConfig The prefix config.
[out] aString The string to populate from Config flags.
References otBorderRouterConfig::mConfigure, otBorderRouterConfig::mDefaultRoute, otBorderRouterConfig::mDhcp, otBorderRouterConfig::mDp, otBorderRouterConfig::mNdDns, otBorderRouterConfig::mOnMesh, otBorderRouterConfig::mPreferred, otBorderRouterConfig::mSlaac, and otBorderRouterConfig::mStable.
Referenced by NetworkData::NetworkData(), and NetworkData::OutputPrefix().
RouteFlagsToString()
void RouteFlagsToString (const otExternalRouteConfig & aConfig, FlagsString & aString) static
This method converts the flags from a given route config to string.
Parameters
[in] aConfig The route config.
[out] aString The string to populate from Config flags.
References otExternalRouteConfig::mNat64, and otExternalRouteConfig::mStable.
Referenced by NetworkData::NetworkData(), and NetworkData::OutputRoute().
Process() [2/4]
otError Process (Arg aArgs[]) private
GetNextPrefix()
otError GetNextPrefix (otNetworkDataIterator * aIterator, otBorderRouterConfig * aConfig, bool aLocal) private
References OutputWrapper::GetInstancePtr(), OT_ERROR_NOT_FOUND, otBorderRouterGetNextOnMeshPrefix(), and otNetDataGetNextOnMeshPrefix().
Referenced by NetworkData::OutputPrefixes().
GetNextRoute()
otError GetNextRoute (otNetworkDataIterator * aIterator, otExternalRouteConfig * aConfig, bool aLocal) private
References OutputWrapper::GetInstancePtr(), OT_ERROR_NOT_FOUND, otBorderRouterGetNextRoute(), and otNetDataGetNextRoute().
Referenced by NetworkData::OutputRoutes().
GetNextService()
otError GetNextService (otNetworkDataIterator * aIterator, otServiceConfig * aConfig, bool aLocal) private
References OutputWrapper::GetInstancePtr(), OT_ERROR_NOT_FOUND, otNetDataGetNextService(), and otServerGetNextService().
Referenced by NetworkData::OutputServices().
OutputBinary()
otError OutputBinary (bool aLocal) private
References OutputWrapper::GetInstancePtr(), OT_ERROR_NOT_IMPLEMENTED, otBorderRouterGetNetData(), otNetDataGet(), OutputWrapper::OutputBytesLine(), and SuccessOrExit.
Referenced by NetworkData::Process().
OutputPrefixes()
void OutputPrefixes (bool aLocal) private
References NetworkData::GetNextPrefix(), OT_ERROR_NONE, OT_NETWORK_DATA_ITERATOR_INIT, OutputWrapper::OutputLine(), and NetworkData::OutputPrefix().
Referenced by NetworkData::Process().
OutputRoutes()
void OutputRoutes (bool aLocal) private
References NetworkData::GetNextRoute(), OT_ERROR_NONE, OT_NETWORK_DATA_ITERATOR_INIT, OutputWrapper::OutputLine(), and NetworkData::OutputRoute().
Referenced by NetworkData::Process().
OutputServices()
void OutputServices (bool aLocal) private
References NetworkData::GetNextService(), OT_ERROR_NONE, OT_NETWORK_DATA_ITERATOR_INIT, OutputWrapper::OutputLine(), and NetworkData::OutputService().
Referenced by NetworkData::Process().
Process() [3/4]
otError Process (Arg aArgs[]) private
netdata steeringdata check (discerner)
netdata steeringdata check 0xabc/12
Done
netdata steeringdata check 0xdef/12
Error 23: NotFound
netdata steeringdata check {discerner}
discerner: The Joiner discerner in format {number}/{length}.
api_copy
otNetDataSteeringDataCheckJoinerWithDiscerner {joiner discerner}
netdata steeringdata check (eui64)
netdata steeringdata check d45e64fa83f81cf7
Done
netdata steeringdata check {eui64}
eui64: The IEEE EUI-64 of the Joiner.
api_copy
otNetDataSteeringDataCheckJoiner {eui64}
References OutputWrapper::GetInstancePtr(), otExtAddress::m8, otJoinerDiscerner::mLength, OT_ERROR_INVALID_ARGS, OT_ERROR_NOT_FOUND, otNetDataSteeringDataCheckJoiner(), otNetDataSteeringDataCheckJoinerWithDiscerner(), Interpreter::ParseJoinerDiscerner(), SuccessOrExit, and VerifyOrExit.
Process() [4/4]
otError Process (Arg aArgs[]) private
netdata show
netdata show
Prefixes:
fd00:dead:beef:cafe::/64 paros med dc00
Routes:
fd49:7770:7fc5:0::/64 s med 4000
Services:
44970 5d c000 s 4000
44970 01 9a04b000000e10 s 4000
Done
netdata show -x
08040b02174703140040fd00deadbeefcafe0504dc00330007021140
Done
netdata show [{-x}]
The optional -x argument gets Network Data as hex-encoded TLVs.
netdata show from OT CLI gets full Network Data received from the Leader. This command uses several API functions to combine prefixes, routes, and services, including otNetDataGetNextOnMeshPrefix, otNetDataGetNextRoute, and otNetDataGetNextService.
{}. {br omrprefix} {br onlinkprefix}
See also
otBorderRouterGetNetData
netdata show local
netdata show local
Prefixes:
fd00:dead:beef:cafe::/64 paros med dc00
Routes:
Services:
Done
netdata show local -x
08040b02174703140040fd00deadbeefcafe0504dc00330007021140
Done
netdata show local [{-x}]
The optional -x argument gets local Network Data as hex-encoded TLVs.
Print local Network Data to sync with the Leader. {netdata show}
References ExitNow, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, NetworkData::OutputBinary(), NetworkData::OutputPrefixes(), NetworkData::OutputRoutes(), and NetworkData::OutputServices().
Field Documentation
kFlagsStringSize
constexpr uint16_t kFlagsStringSize = 17 static
This constant specifies the string size for representing Network Data prefix/route entry flags.
BorderRouter (OnMeshPrefix) TLV uses uint16_t for its flags and ExternalRoute uses uint8_t, though some of the bits are not currently used and reserved for future, so 17 chars string (16 flags plus null char at end of string) covers current and future flags.
The documentation for this class was generated from the following files:
cli_network_data.hpp
cli_network_data.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale