OpenThread: OwningList< Type > Class Template Reference
OwningList< Type > Class Template Reference
#include <owning_list.hpp>
Public Member Functions
void Clear (void)
void Free (void)
OwningList (void)=default
OwnedPtr< Type > Pop (void)
OwnedPtr< Type > PopAfter (Type *aPrevEntry)
template<typename Indicator >
void RemoveAllMatching (const Indicator &aIndicator, OwningList &aRemovedList)
template<typename Indicator >
OwnedPtr< Type > RemoveMatching (const Indicator &aIndicator)
~OwningList (void)
Public Member Functions inherited from LinkedList< Type >
Error Add (Type &aEntry)
Iterator begin (void)
ConstIterator begin (void) const
void Clear (void)
bool Contains (const Type &aEntry) const
template<typename Indicator >
bool ContainsMatching (const Indicator &aIndicator) const
Iterator end (void)
ConstIterator end (void) const
Error Find (const Type &aEntry, const Type *&aPrevEntry) const
Error Find (const Type &aEntry, Type *&aPrevEntry)
template<typename Indicator >
const Type * FindMatching (const Type *aBegin, const Type *aEnd, const Indicator &aIndicator, const Type *&aPrevEntry) const
template<typename Indicator >
Type * FindMatching (const Type *aBegin, const Type *aEnd, const Indicator &aIndicator, Type *&aPrevEntry)
template<typename Indicator >
const Type * FindMatching (const Indicator &aIndicator, const Type *&aPrevEntry) const
template<typename Indicator >
Type * FindMatching (const Indicator &aIndicator, Type *&aPrevEntry)
template<typename Indicator >
const Type * FindMatching (const Indicator &aIndicator) const
template<typename Indicator >
Type * FindMatching (const Indicator &aIndicator)
Type * GetHead (void)
const Type * GetHead (void) const
const Type * GetTail (void) const
Type * GetTail (void)
bool IsEmpty (void) const
LinkedList (void)
Type * Pop (void)
Type * PopAfter (Type *aPrevEntry)
void Push (Type &aEntry)
void PushAfter (Type &aEntry, Type &aPrevEntry)
Error Remove (const Type &aEntry)
template<typename Indicator >
void RemoveAllMatching (const Indicator &aIndicator, LinkedList &aRemovedList)
template<typename Indicator >
Type * RemoveMatching (const Indicator &aIndicator)
void SetHead (Type *aHead)
Detailed Description
template<typename Type>
class ot::OwningList< Type >
This template class represents a singly linked list which owns its entries and frees them upon destruction of the list.
Constructor & Destructor Documentation
OwningList()
OwningList (void) default
This is the default constructor for OwningList
~OwningList()
~OwningList (void) inline
This is the destructor for OwningList.
On destruction, all existing entries in the list are freed.
References OwningList< Type >::Free().
Member Function Documentation
Free()
void Free (void) inline
This method clears the list and frees all existing entries in it.
References OwningList< Type >::Pop().
Referenced by OwningList< Type >::Clear(), and OwningList< Type >::~OwningList().
Clear()
void Clear (void) inline
This method clears the list and frees all existing entries in it.
References OwningList< Type >::Free().
Pop()
OwnedPtr<Type> Pop (void) inline
This method pops an entry from head of the linked list and return an OwnedPtr to it.
Note
This method does not change the popped entry itself, i.e., the popped entry next pointer stays as before.
Returns
An OwnedPtr to the entry that was popped (set to null if list of empty).
References LinkedList< Type >::Pop().
Referenced by OwningList< Type >::Free().
PopAfter()
OwnedPtr<Type> PopAfter (Type * aPrevEntry) inline
This method pops an entry after a given previous entry.
Note
This method does not change the popped entry itself, i.e., the popped entry next pointer stays as before.
Parameters
[in] aPrevEntry A pointer to a previous entry. If it is not nullptr the entry after this will be popped, otherwise (if it is nullptr) the entry at the head of the list is popped.
Returns
An OwnedPtr to the entry that was popped (set to null if there is no entry to pop).
References LinkedList< Type >::PopAfter().
RemoveMatching()
OwnedPtr<Type> RemoveMatching (const Indicator & aIndicator) inline
This template method removes an entry matching a given entry indicator from the linked list.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Note
This method does not change the removed entry itself (which is returned in case of success), i.e., the entry next pointer stays as before.
Parameters
[in] aIndicator An entry indicator to match against entries in the list.
Returns
An OwnedPtr to the entry that was removed (set to null if there is no matching entry to remove).
References LinkedList< Type >::RemoveMatching().
RemoveAllMatching()
void RemoveAllMatching (const Indicator & aIndicator, OwningList< Type > & aRemovedList) inline
This template method removes all entries in the list matching a given entry indicator from the list and adds them to a new list.
The template type Indicator specifies the type of aIndicator object which is used to match against entries in the list. To check that an entry matches the given indicator, the Matches() method is invoked on each Type entry in the list. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
The ownership of the removed entries is transferred from the original list to the aRemovedList.
Parameters
[in] aIndicator An entry indicator to match against entries in the list.
[in] aRemovedList The list to add the removed entries to.
References LinkedList< Type >::RemoveAllMatching().
The documentation for this class was generated from the following file:
owning_list.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale