OpenThread: String Class Reference
String Class Reference
#include <heap_string.hpp>
Public Member Functions
const char * AsCString (void) const
void Free (void)
bool IsNull (void) const
bool operator!= (const char *aCString) const
String & operator= (const String &)=delete
bool operator== (const char *aCString) const
bool operator== (const String &aString) const
Error Set (const char *aCString)
Error Set (const String &aString)
Error Set (String &&aString)
String (void)
String (String &&aString)
String (const String &)=delete
~String (void)
Public Member Functions inherited from Unequatable< String >
bool operator!= (const String &aOther) const
Private Attributes
char * mStringBuffer
Detailed Description
This class represents a heap allocated string.
The buffer to store the string is allocated from heap and is manged by the Heap::String class itself, e.g., it may be reused and/or freed and reallocated when the string is set. The Heap::String destructor will always free the allocated buffer.
Constructor & Destructor Documentation
String() [1/3]
String (void) inline
This constructor initializes the String as null (or empty).
Referenced by String::operator==().
String() [2/3]
String (String && aString) inline
This is the move constructor for String.
String is non-copyable (copy constructor is deleted) but move constructor is provided to allow it to to be used as return type (return by value) from functions/methods (which will then use move semantics).
~String()
~String (void) inline
This is the destructor for HealString object
References String::Free().
String() [3/3]
String (const String &) delete
Member Function Documentation
IsNull()
bool IsNull (void) const inline
This method indicates whether or not the String is null (i.e., it was never successfully set or it was freed).
Return values
TRUE The String is null.
FALSE The String is not null.
References String::mStringBuffer.
AsCString()
const char* AsCString (void) const inline
This method returns the String as a C string.
Returns
A pointer to C string buffer or nullptr if the String is null (never set or freed).
References String::mStringBuffer, and String::Set().
Referenced by String::operator==(), and String::Set().
Set() [1/3]
Error Set (const char * aCString)
This method sets the string from a given C string.
Parameters
[in] aCString A pointer to c string buffer. Can be nullptr which then frees the String.
Return values
kErrorNone Successfully set the string.
kErrorNoBufs Failed to allocate buffer for string.
References ot::Heap::CAlloc(), ot::Heap::Free(), String::Free(), ot::kErrorNoBufs, ot::kErrorNone, String::mStringBuffer, and VerifyOrExit.
Referenced by String::AsCString(), and String::Set().
Set() [2/3]
Error Set (const String & aString) inline
This method sets the string from another String.
Parameters
[in] aString The other String to set from.
Return values
kErrorNone Successfully set the string.
kErrorNoBufs Failed to allocate buffer for string.
References String::AsCString(), String::Free(), String::operator==(), and String::Set().
Referenced by String::Set().
Set() [3/3]
Error Set (String && aString)
This method sets the string from another String.
Parameters
[in] aString The other String to set from (rvalue reference using move semantics).
Return values
kErrorNone Successfully set the string.
kErrorNoBufs Failed to allocate buffer for string.
References ot::Heap::Free(), ot::kErrorNone, String::mStringBuffer, and VerifyOrExit.
Free()
void Free (void)
This method frees any buffer allocated by the String.
The String destructor will automatically call Free(). This method allows caller to free buffer explicitly.
References ot::Heap::Free(), and String::mStringBuffer.
Referenced by String::Set(), and String::~String().
operator==() [1/2]
bool operator== (const char * aCString) const
This method overloads operator == to evaluate whether or not the String is equal to a given C string.
Parameters
[in] aCString A C string to compare with. Can be nullptr which then checks if String is null.
Return values
TRUE If the two strings are equal.
FALSE If the two strings are not equal.
References String::mStringBuffer, and VerifyOrExit.
Referenced by String::Set().
operator!=()
bool operator!= (const char * aCString) const inline
This method overloads operator != to evaluate whether or not the String is unequal to a given C string.
Parameters
[in] aCString A C string to compare with. Can be nullptr which then checks if String is not null.
Return values
TRUE If the two strings are not equal.
FALSE If the two strings are equal.
operator==() [2/2]
bool operator== (const String & aString) const inline
This method overloads operator == to evaluate whether or not two String are equal.
Parameters
[in] aString The other string to compare with.
Return values
TRUE If the two strings are equal.
FALSE If the two strings are not equal.
References String::AsCString(), String::operator=(), and String::String().
operator=()
String& operator= (const String &) delete
Referenced by String::operator==().
Field Documentation
mStringBuffer
char* mStringBuffer private
Referenced by String::AsCString(), String::Free(), String::IsNull(), String::operator==(), and String::Set().
The documentation for this class was generated from the following files:
heap_string.hpp
heap_string.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale