OpenThread: Array< Type, kCapacityIncrements > Class Template Reference
Array< Type, kCapacityIncrements > Class Template Reference
#include <heap_array.hpp>
Public Types
using IndexType = uint16_t
Public Member Functions
Array (void)
Array (const Array &)=delete
const Type * AsCArray (void) const
Type * At (IndexType aIndex)
const Type * At (IndexType aIndex) const
Type * Back (void)
const Type * Back (void) const
Type * begin (void)
const Type * begin (void) const
void Clear (void)
bool Contains (const Type &aEntry) const
template<typename Indicator >
bool ContainsMatching (const Indicator &aIndicator) const
Type * end (void)
const Type * end (void) const
Type * Find (const Type &aEntry)
const Type * Find (const Type &aEntry) const
template<typename Indicator >
Type * FindMatching (const Indicator &aIndicator)
template<typename Indicator >
const Type * FindMatching (const Indicator &aIndicator) const
void Free (void)
Type * Front (void)
const Type * Front (void) const
IndexType GetCapacity (void) const
IndexType GetLength (void) const
IndexType IndexOf (const Type &aElement) const
Array & operator= (const Array &)=delete
Type & operator[] (IndexType aIndex)
const Type & operator[] (IndexType aIndex) const
void PopBack (void)
Error PushBack (const Type &aEntry)
Error PushBack (Type &&aEntry)
Type * PushBack (void)
Error ReserveCapacity (IndexType aCapacity)
void TakeFrom (Array &&aOther)
~Array (void)
Private Member Functions
Error Allocate (IndexType aCapacity)
Private Attributes
Type * mArray
IndexType mCapacity
IndexType mLength
Detailed Description
template<typename Type, uint16_t kCapacityIncrements = 2>
class ot::Heap::Array< Type, kCapacityIncrements >
This class represents a heap allocated array.
The buffer to store the elements is allocated from heap and is managed by the Heap::Array class itself. The Array implementation will automatically grow the buffer when new entries are added. The Heap::Array destructor will always free the allocated buffer.
The Type class MUST provide a move constructor Type(Type &&aOther) (or a copy constructor if no move constructor is provided). This constructor is used to move existing elements when array buffer is grown (new buffer is allocated) to make room for new elements.
Template Parameters
Type The array element type.
kCapacityIncrements Number of elements to allocate at a time when updating the array buffer.
Member Typedef Documentation
IndexType
using IndexType = uint16_t
Constructor & Destructor Documentation
Array() [1/2]
Array (void) inline
This constructor initializes the Array as empty.
Referenced by Array< Type, kCapacityIncrements >::end().
~Array()
~Array (void) inline
This is the destructor for Array object.
References Array< Type, kCapacityIncrements >::Free().
Array() [2/2]
Array (const Array< Type, kCapacityIncrements > &) delete
Member Function Documentation
Free()
void Free (void) inline
This method frees any buffer allocated by the Array.
The Array destructor will automatically call Free(). This method allows caller to free buffer explicitly.
References Array< Type, kCapacityIncrements >::Clear(), ot::Heap::Free(), Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mCapacity.
Referenced by Array< Type, kCapacityIncrements >::TakeFrom(), and Array< Type, kCapacityIncrements >::~Array().
Clear()
void Clear (void) inline
This method clears the array.
Note that Clear() method (unlike Free()) does not free the allocated buffer and therefore does not change the current capacity of the array.
This method invokes Type destructor on all cleared existing elements of array.
References Array< Type, kCapacityIncrements >::mLength.
Referenced by Array< Type, kCapacityIncrements >::Free().
GetLength()
IndexType GetLength (void) const inline
This method returns the current array length (number of elements in the array).
Returns
The array length.
References Array< Type, kCapacityIncrements >::mLength.
AsCArray()
const Type* AsCArray (void) const inline
This method returns a raw pointer to the array buffer.
The returned raw pointer is valid only while the Array remains unchanged.
Returns
A pointer to the array buffer or nullptr if the array is empty.
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
GetCapacity()
IndexType GetCapacity (void) const inline
This method returns the current capacity of array (number of elements that can fit in current allocated buffer).
The allocated buffer and array capacity are automatically increased (by the Array itself) when new elements are added to array. Removing elements does not change the buffer and the capacity. A desired capacity can be reserved using ReserveCapacity() method.
Returns
The current capacity of the array.
References Array< Type, kCapacityIncrements >::mCapacity.
ReserveCapacity()
Error ReserveCapacity (IndexType aCapacity) inline
This method allocates buffer to reserve a given capacity for array.
If the requested aCapacity is smaller than the current length of the array, capacity remains unchanged.
Parameters
[in] aCapacity The target capacity for the array.
Return values
kErrorNone Array was successfully updated to support aCapacity.
kErrorNoBufs Could not allocate buffer.
References Array< Type, kCapacityIncrements >::Allocate().
TakeFrom()
void TakeFrom (Array< Type, kCapacityIncrements > && aOther) inline
This method sets the array by taking the buffer from another given array (using move semantics).
Parameters
[in] aOther The other Heap::Array to take from (rvalue reference).
References Array< Type, kCapacityIncrements >::Free(), Array< Type, kCapacityIncrements >::mArray, Array< Type, kCapacityIncrements >::mCapacity, and Array< Type, kCapacityIncrements >::mLength.
operator[]() [1/2]
Type& operator[] (IndexType aIndex) inline
This method overloads the [] operator to get the element at a given index.
This method does not perform index bounds checking. Behavior is undefined if aIndex is not valid.
Parameters
[in] aIndex The index to get.
Returns
A reference to the element in array at aIndex.
References Array< Type, kCapacityIncrements >::mArray.
operator[]() [2/2]
const Type& operator[] (IndexType aIndex) const inline
This method overloads the [] operator to get the element at a given index.
This method does not perform index bounds checking. Behavior is undefined if aIndex is not valid.
Parameters
[in] aIndex The index to get.
Returns
A reference to the element in array at aIndex.
References Array< Type, kCapacityIncrements >::mArray.
At() [1/2]
Type* At (IndexType aIndex) inline
This method gets a pointer to the element at a given index.
Unlike operator[], this method checks aIndex to be valid and within the current length. The returned pointer is valid only while the Array remains unchanged.
Parameters
[in] aIndex The index to get.
Returns
A pointer to element in array at aIndex or nullptr if aIndex is not valid.
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
Referenced by Array< Type, kCapacityIncrements >::Front().
At() [2/2]
const Type* At (IndexType aIndex) const inline
This method gets a pointer to the element at a given index.
Unlike operator[], this method checks aIndex to be valid and within the current length. The returned pointer is valid only while the Array remains unchanged.
Parameters
[in] aIndex The index to get.
Returns
A pointer to element in array at aIndex or nullptr if aIndex is not valid.
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
Front() [1/2]
Type* Front (void) inline
This method gets a pointer to the element at the front of the array (first element).
The returned pointer is valid only while the Array remains unchanged.
Returns
A pointer to the front element or nullptr if array is empty.
References Array< Type, kCapacityIncrements >::At().
Front() [2/2]
const Type* Front (void) const inline
This method gets a pointer to the element at the front of the array (first element).
The returned pointer is valid only while the Array remains unchanged.
Returns
A pointer to the front element or nullptr if array is empty.
References Array< Type, kCapacityIncrements >::At().
Back() [1/2]
Type* Back (void) inline
This method gets a pointer to the element at the back of the array (last element).
The returned pointer is valid only while the Array remains unchanged.
Returns
A pointer to the back element or nullptr if array is empty.
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
Back() [2/2]
const Type* Back (void) const inline
This method gets a pointer to the element at the back of the array (last element).
The returned pointer is valid only while the Array remains unchanged.
Returns
A pointer to the back element or nullptr if array is empty.
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
PushBack() [1/3]
Error PushBack (const Type & aEntry) inline
This method appends a new entry to the end of the array.
This method requires the Type to provide a copy constructor of format Type(const Type &aOther) to init the new element in the array from aEntry.
Parameters
[in] aEntry The new entry to push back.
Return values
kErrorNone Successfully pushed back aEntry to the end of the array.
kErrorNoBufs Could not allocate buffer to grow the array.
References Array< Type, kCapacityIncrements >::Allocate(), ot::kErrorNone, Array< Type, kCapacityIncrements >::mArray, Array< Type, kCapacityIncrements >::mCapacity, Array< Type, kCapacityIncrements >::mLength, and SuccessOrExit.
PushBack() [2/3]
Error PushBack (Type && aEntry) inline
This method appends a new entry to the end of the array.
This method requires the Type to provide a copy constructor of format Type(Type &&aOther) to init the new element in the array from aEntry.
Parameters
[in] aEntry The new entry to push back (an rvalue reference)
Return values
kErrorNone Successfully pushed back aEntry to the end of the array.
kErrorNoBufs Could not allocate buffer to grow the array.
References Array< Type, kCapacityIncrements >::Allocate(), ot::kErrorNone, Array< Type, kCapacityIncrements >::mArray, Array< Type, kCapacityIncrements >::mCapacity, Array< Type, kCapacityIncrements >::mLength, and SuccessOrExit.
PushBack() [3/3]
Type* PushBack (void) inline
This method appends a new entry to the end of the array.
On success, this method returns a pointer to the newly appended element in the array for the caller to initialize and use. This method uses the Type(void) default constructor on the newly appended element (if not nullptr).
The returned pointer is valid only while the Array remains unchanged.
Returns
A pointer to the newly appended element or nullptr if could not allocate buffer to grow the array
References Array< Type, kCapacityIncrements >::Allocate(), Array< Type, kCapacityIncrements >::mArray, Array< Type, kCapacityIncrements >::mCapacity, Array< Type, kCapacityIncrements >::mLength, and SuccessOrExit.
PopBack()
void PopBack (void) inline
This method removes the last element in the array.
This method will invoke the Type destructor on the removed element.
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
IndexOf()
IndexType IndexOf (const Type & aElement) const inline
This method returns the index of an element in the array.
The aElement MUST be from the array, otherwise the behavior of this method is undefined.
Parameters
[in] aElement A reference to an element in the array.
Returns
The index of aElement in the array.
References Array< Type, kCapacityIncrements >::mArray.
Find() [1/2]
Type* Find (const Type & aEntry) inline
This method finds the first match of a given entry in the array.
This method uses == operator on Type to compare the array element with aEntry. The returned pointer is valid only while the Array remains unchanged.
Parameters
[in] aEntry The entry to search for within the array.
Returns
A pointer to matched array element, or nullptr if a match could not be found.
References ot::AsConst(), ot::AsNonConst(), and Array< Type, kCapacityIncrements >::Find().
Referenced by Array< Type, kCapacityIncrements >::Contains(), and Array< Type, kCapacityIncrements >::Find().
Find() [2/2]
const Type* Find (const Type & aEntry) const inline
This method finds the first match of a given entry in the array.
This method uses == operator to compare the array elements with aEntry. The returned pointer is valid only while the Array remains unchanged.
Parameters
[in] aEntry The entry to search for within the array.
Returns
A pointer to matched array element, or nullptr if a match could not be found.
Contains()
bool Contains (const Type & aEntry) const inline
This method indicates whether or not a match to given entry exists in the array.
This method uses == operator on Type to compare the array elements with aEntry.
Parameters
[in] aEntry The entry to search for within the array.
Return values
TRUE The array contains a matching element with aEntry.
FALSE The array does not contain a matching element with aEntry.
References Array< Type, kCapacityIncrements >::Find().
FindMatching() [1/2]
Type* FindMatching (const Indicator & aIndicator) inline
This template method finds the first element in the array matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against elements in the array. To check that an element matches the given indicator, the Matches() method is invoked on each Type element in the array. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
The returned pointer is valid only while the Array remains unchanged.
Parameters
[in] aIndicator An indicator to match with elements in the array.
Returns
A pointer to the matched array element, or nullptr if a match could not be found.
References ot::AsConst(), and ot::AsNonConst().
Referenced by Array< Type, kCapacityIncrements >::ContainsMatching().
FindMatching() [2/2]
const Type* FindMatching (const Indicator & aIndicator) const inline
This template method finds the first element in the array matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against elements in the array. To check that an element matches the given indicator, the Matches() method is invoked on each Type element in the array. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
The returned pointer is valid only while the Array remains unchanged.
Parameters
[in] aIndicator An indicator to match with elements in the array.
Returns
A pointer to the matched array element, or nullptr if a match could not be found.
ContainsMatching()
bool ContainsMatching (const Indicator & aIndicator) const inline
This template method indicates whether or not the array contains an element matching a given indicator.
The template type Indicator specifies the type of aIndicator object which is used to match against elements in the array. To check that an element matches the given indicator, the Matches() method is invoked on each Type element in the array. The Matches() method should be provided by Type class accordingly:
bool Type::Matches(const Indicator &aIndicator) const
Parameters
[in] aIndicator An indicator to match with elements in the array.
Return values
TRUE The array contains a matching element with aIndicator.
FALSE The array does not contain a matching element with aIndicator.
References Array< Type, kCapacityIncrements >::FindMatching().
begin() [1/2]
Type* begin (void) inline
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
end() [1/2]
Type* end (void) inline
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
begin() [2/2]
const Type* begin (void) const inline
References Array< Type, kCapacityIncrements >::mArray, and Array< Type, kCapacityIncrements >::mLength.
end() [2/2]
const Type* end (void) const inline
References Array< Type, kCapacityIncrements >::Array(), Array< Type, kCapacityIncrements >::mArray, Array< Type, kCapacityIncrements >::mLength, and Array< Type, kCapacityIncrements >::operator=().
operator=()
Array& operator= (const Array< Type, kCapacityIncrements > &) delete
Referenced by Array< Type, kCapacityIncrements >::end().
Allocate()
Error Allocate (IndexType aCapacity) inline private
References ot::Heap::CAlloc(), ot::Heap::Free(), ot::kErrorNoBufs, ot::kErrorNone, Array< Type, kCapacityIncrements >::mArray, Array< Type, kCapacityIncrements >::mCapacity, Array< Type, kCapacityIncrements >::mLength, and VerifyOrExit.
Referenced by Array< Type, kCapacityIncrements >::PushBack(), and Array< Type, kCapacityIncrements >::ReserveCapacity().
Field Documentation
mArray
Type* mArray private
Referenced by Array< Type, kCapacityIncrements >::Allocate(), Array< Type, kCapacityIncrements >::AsCArray(), Array< Type, kCapacityIncrements >::At(), Array< Type, kCapacityIncrements >::Back(), Array< Type, kCapacityIncrements >::begin(), Array< Type, kCapacityIncrements >::end(), Array< Type, kCapacityIncrements >::Free(), Array< Type, kCapacityIncrements >::IndexOf(), Array< Type, kCapacityIncrements >::operator[](), Array< Type, kCapacityIncrements >::PopBack(), Array< Type, kCapacityIncrements >::PushBack(), and Array< Type, kCapacityIncrements >::TakeFrom().
mLength
IndexType mLength private
Referenced by Array< Type, kCapacityIncrements >::Allocate(), Array< Type, kCapacityIncrements >::AsCArray(), Array< Type, kCapacityIncrements >::At(), Array< Type, kCapacityIncrements >::Back(), Array< Type, kCapacityIncrements >::begin(), Array< Type, kCapacityIncrements >::Clear(), Array< Type, kCapacityIncrements >::end(), Array< Type, kCapacityIncrements >::GetLength(), Array< Type, kCapacityIncrements >::PopBack(), Array< Type, kCapacityIncrements >::PushBack(), and Array< Type, kCapacityIncrements >::TakeFrom().
mCapacity
IndexType mCapacity private
Referenced by Array< Type, kCapacityIncrements >::Allocate(), Array< Type, kCapacityIncrements >::Free(), Array< Type, kCapacityIncrements >::GetCapacity(), Array< Type, kCapacityIncrements >::PushBack(), and Array< Type, kCapacityIncrements >::TakeFrom().
The documentation for this class was generated from the following file:
heap_array.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale