OpenThread: RadioSpinel< InterfaceType, ProcessContextType > Class Template Reference
RadioSpinel< InterfaceType, ProcessContextType > Class Template Reference
#include <radio_spinel.hpp>
Public Member Functions
otError AddSrcMatchExtEntry (const otExtAddress &aExtAddress)
otError AddSrcMatchShortEntry (uint16_t aShortAddress)
otError ClearSrcMatchExtEntries (void)
otError ClearSrcMatchExtEntry (const otExtAddress &aExtAddress)
otError ClearSrcMatchShortEntries (void)
otError ClearSrcMatchShortEntry (uint16_t aShortAddress)
void Deinit (void)
otError Disable (void)
otError Enable (otInstance *aInstance)
otError EnableSrcMatch (bool aEnable)
otError EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
otError Get (spinel_prop_key_t aKey, const char *aFormat,...)
uint32_t GetBusSpeed (void) const
otError GetCcaEnergyDetectThreshold (int8_t &aThreshold)
uint8_t GetChannel (void) const
otError GetFemLnaGain (int8_t &aGain)
otError GetIeeeEui64 (uint8_t *aIeeeEui64)
uint64_t GetNextRadioTimeRecalcStart (void) const
uint64_t GetNow (void)
otRadioCaps GetRadioCaps (void) const
uint32_t GetRadioChannelMask (bool aPreferred)
otError GetRadioRegion (uint16_t *aRegionCode)
const otRadioSpinelMetrics * GetRadioSpinelMetrics (void) const
int8_t GetReceiveSensitivity (void) const
int8_t GetRssi (void)
InterfaceType & GetSpinelInterface (void)
otRadioState GetState (void) const
otRadioFrame & GetTransmitFrame (void)
otError GetTransmitPower (int8_t &aPower)
uint64_t GetTxRadioEndUs (void) const
const char * GetVersion (void) const
otError GetWithParam (spinel_prop_key_t aKey, const uint8_t *aParam, spinel_size_t aParamSize, const char *aFormat,...)
void HandleReceivedFrame (void)
bool HasPendingFrame (void) const
void Init (bool aResetRadio, bool aRestoreDataSetFromNcp, bool aSkipRcpCompatibilityCheck)
otError Insert (spinel_prop_key_t aKey, const char *aFormat,...)
bool IsEnabled (void) const
bool IsPromiscuous (void) const
bool IsRcp (bool &aSupportsRcpApiVersion)
bool IsTransmitDone (void) const
bool IsTransmitting (void) const
void Process (const ProcessContextType &aContext)
RadioSpinel (void)
otError Receive (uint8_t aChannel)
otError Remove (spinel_prop_key_t aKey, const char *aFormat,...)
otError RestoreDatasetFromNcp (void)
otError SendReset (uint8_t aResetType)
otError Set (spinel_prop_key_t aKey, const char *aFormat,...)
otError SetCcaEnergyDetectThreshold (int8_t aThreshold)
otError SetChannelMaxTransmitPower (uint8_t aChannel, int8_t aPower)
otError SetExtendedAddress (const otExtAddress &aAddress)
otError SetFemLnaGain (int8_t aGain)
otError SetMacFrameCounter (uint32_t aMacFrameCounter)
otError SetMacKey (uint8_t aKeyIdMode, uint8_t aKeyId, const otMacKeyMaterial *aPrevKey, const otMacKeyMaterial *aCurrKey, const otMacKeyMaterial *aNextKey)
otError SetPanId (uint16_t aPanId)
otError SetPromiscuous (bool aEnable)
otError SetRadioRegion (uint16_t aRegionCode)
otError SetShortAddress (uint16_t aAddress)
otError SetTransmitPower (int8_t aPower)
otError Sleep (void)
otError Transmit (otRadioFrame &aFrame)
Private Types
enum {
kMaxSpinelFrame = SPINEL_FRAME_MAX_SIZE, kMaxWaitTime = 2000, kVersionStringSize = 128, kCapsBufferSize = 100,
kChannelMaskBufferSize = 32
}
typedef otError(RadioSpinel::* ResponseHandler) (const uint8_t *aBuffer, uint16_t aLength)
enum State {
kStateDisabled, kStateSleep, kStateReceive, kStateTransmitting,
kStateTransmitDone
}
Private Member Functions
void CalcRcpTimeOffset (void)
otError CheckRadioCapabilities (void)
otError CheckRcpApiVersion (bool aSupportsRcpApiVersion)
otError CheckSpinelVersion (void)
void FreeTid (spinel_tid_t tid)
spinel_tid_t GetNextTid (void)
void HandleNotification (SpinelInterface::RxFrameBuffer &aFrameBuffer)
void HandleNotification (const uint8_t *aBuffer, uint16_t aLength)
void HandleRcpTimeout (void)
void HandleRcpUnexpectedReset (spinel_status_t aStatus)
void HandleResponse (const uint8_t *aBuffer, uint16_t aLength)
void HandleTransmitDone (uint32_t aCommand, spinel_prop_key_t aKey, const uint8_t *aBuffer, uint16_t aLength)
void HandleValueIs (spinel_prop_key_t aKey, const uint8_t *aBuffer, uint16_t aLength)
void HandleWaitingResponse (uint32_t aCommand, spinel_prop_key_t aKey, const uint8_t *aBuffer, uint16_t aLength)
bool IsSafeToHandleNow (spinel_prop_key_t aKey) const
otError ParseRadioFrame (otRadioFrame &aFrame, const uint8_t *aBuffer, uint16_t aLength, spinel_ssize_t &aUnpacked)
void ProcessFrameQueue (void)
void ProcessRadioStateMachine (void)
void RadioReceive (void)
void RecoverFromRcpFailure (void)
otError Request (uint32_t aCommand, spinel_prop_key_t aKey, const char *aFormat,...)
otError RequestV (uint32_t aCommand, spinel_prop_key_t aKey, const char *aFormat, va_list aArgs)
otError RequestWithExpectedCommandV (uint32_t aExpectedCommand, uint32_t aCommand, spinel_prop_key_t aKey, const char *aFormat, va_list aArgs)
otError RequestWithPropertyFormat (const char *aPropertyFormat, uint32_t aCommand, spinel_prop_key_t aKey, const char *aFormat,...)
otError RequestWithPropertyFormatV (const char *aPropertyFormat, uint32_t aCommand, spinel_prop_key_t aKey, const char *aFormat, va_list aArgs)
otError SendCommand (uint32_t aCommand, spinel_prop_key_t aKey, spinel_tid_t aTid, const char *aFormat, va_list aArgs)
otError ThreadDatasetHandler (const uint8_t *aBuffer, uint16_t aLength)
void TransmitDone (otRadioFrame *aFrame, otRadioFrame *aAckFrame, otError aError)
void UpdateParseErrorCount (otError aError)
otError WaitResponse (void)
Static Private Member Functions
static void HandleReceivedFrame (void *aContext)
Private Attributes
uint8_t mAckPsdu [OT_RADIO_FRAME_MAX_SIZE]
otRadioFrame mAckRadioFrame
uint8_t mChannel
spinel_tid_t mCmdNextTid
Next available transaction id.
uint16_t mCmdTidsInUse
Used transaction ids.
otError mError
The result of current transaction.
uint32_t mExpectedCommand
Expected response command of current transaction.
otExtAddress mExtendedAddress
otExtAddress mIeeeEui64
otInstance * mInstance
bool mIsPromiscuous: 1
Promiscuous mode.
bool mIsReady: 1
NCP ready.
bool mIsTimeSynced: 1
Host has calculated the time difference between host and RCP.
MaxPowerTable mMaxPowerTable
uint16_t mPanId
va_list mPropertyArgs
The arguments pack or unpack spinel property of current transaction.
const char * mPropertyFormat
The spinel property format of current transaction.
otRadioCaps mRadioCaps
otRadioSpinelMetrics mRadioSpinelMetrics
int64_t mRadioTimeOffset
Time difference with estimated RCP time minus host time.
uint64_t mRadioTimeRecalcStart
When to recalculate RCP time offset.
SpinelInterface::RxFrameBuffer mRxFrameBuffer
uint8_t mRxPsdu [OT_RADIO_FRAME_MAX_SIZE]
otRadioFrame mRxRadioFrame
int8_t mRxSensitivity
uint16_t mShortAddress
InterfaceType mSpinelInterface
State mState
bool mSupportsLogStream: 1
RCP supports LOG_STREAM property with OpenThread log meta-data format.
otRadioFrame * mTransmitFrame
Points to the frame to send.
otError mTxError
uint8_t mTxPsdu [OT_RADIO_FRAME_MAX_SIZE]
uint64_t mTxRadioEndUs
otRadioFrame mTxRadioFrame
spinel_tid_t mTxRadioTid
The transaction id used to send a radio frame.
char mVersion [kVersionStringSize]
spinel_prop_key_t mWaitingKey
The property key of current transaction.
spinel_tid_t mWaitingTid
The transaction id of current transaction.
Detailed Description
template<typename InterfaceType, typename ProcessContextType>
class ot::Spinel::RadioSpinel< InterfaceType, ProcessContextType >
The class for providing a OpenThread radio interface by talking with a radio-only co-processor(RCP). The InterfaceType template parameter should provide the following methods:
class InterfaceType {
// This constructor initializes the object.
//
Parameters
[in] aCallback Callback on frame received //
[in] aCallbackContext Callback context //
[in] aFrameBuffer A reference to a RxFrameBuffer object.
InterfaceType(Spinel::SpinelInterface::ReceiveFrameCallback aCallback, void * aCallbackContext, Spinel::SpinelInterface::RxFrameBuffer & aFrameBuffer);
// This method encodes and sends a spinel frame to Radio Co-processor (RCP) over the socket.
// This is blocking call, i.e., if the socket is not writable, this method waits for it to become writable for // up to kMaxWaitTime interval.
//
Parameters
[in] aFrame A pointer to buffer containing the spinel frame to send. //
[in] aLength The length (number of bytes) in the frame.
//
Return values
OT_ERROR_NONE Successfully encoded and sent the spinel frame. //
OT_ERROR_NO_BUFS Insufficient buffer space available to encode the frame. //
OT_ERROR_FAILED Failed to send due to socket not becoming writable within kMaxWaitTime.
otError SendFrame(const uint8_t *aFrame, uint16_t aLength);
// This method waits for receiving part or all of spinel frame within specified interval.
//
Parameters
[in] aTimeout The timeout value in microseconds.
//
Return values
OT_ERROR_NONE Part or all of spinel frame is received. //
OT_ERROR_RESPONSE_TIMEOUT No spinel frame is received within aTimeout.
otError WaitForFrame(uint64_t& aTimeoutUs);
// This method performs radio driver processing.
//
Parameters
[in] aContext The context containing fd_sets. // The type is specified by the user in template parameters.
void Process(const ProcessContextType &aContext);
// This method deinitializes the interface to the RCP.
void Deinit(void); };
Member Typedef Documentation
ResponseHandler
typedef otError(RadioSpinel::* ResponseHandler) (const uint8_t *aBuffer, uint16_t aLength) private
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kMaxSpinelFrame
kMaxWaitTime
Max time to wait for response in milliseconds.
kVersionStringSize
Max size of version string.
kCapsBufferSize
Max buffer size used to store SPINEL_PROP_CAPS value.
kChannelMaskBufferSize
Max buffer size used to store SPINEL_PROP_PHY_CHAN_SUPPORTED value.
State
enum State private
Enumerator
kStateDisabled
Radio is disabled.
kStateSleep
Radio is sleep.
kStateReceive
Radio is in receive mode.
kStateTransmitting
Frame passed to radio for transmission, waiting for done event from radio.
kStateTransmitDone
Radio indicated frame transmission is done.
Constructor & Destructor Documentation
RadioSpinel()
RadioSpinel (void)
This constructor initializes the spinel based OpenThread transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mRadioSpinelMetrics, and RadioSpinel< InterfaceType, ProcessContextType >::mVersion.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Deinit().
Member Function Documentation
Init()
void Init (bool aResetRadio, bool aRestoreDataSetFromNcp, bool aSkipRcpCompatibilityCheck)
Initialize this radio transceiver.
Parameters
[in] aResetRadio TRUE to reset on init, FALSE to not reset on init.
[in] aRestoreDatasetFromNcp TRUE to restore dataset to host from non-volatile memory (only used when attempts to upgrade from NCP to RCP mode), FALSE otherwise.
[in] aSkipRcpCompatibilityCheck TRUE to skip RCP compatibility check, FALSE to perform the check.
References RadioSpinel< InterfaceType, ProcessContextType >::CheckRadioCapabilities(), RadioSpinel< InterfaceType, ProcessContextType >::CheckRcpApiVersion(), RadioSpinel< InterfaceType, ProcessContextType >::CheckSpinelVersion(), DieNow, RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::IsRcp(), otExtAddress::m8, RadioSpinel< InterfaceType, ProcessContextType >::mAckPsdu, RadioSpinel< InterfaceType, ProcessContextType >::mAckRadioFrame, RadioSpinel< InterfaceType, ProcessContextType >::mIeeeEui64, RadioSpinel< InterfaceType, ProcessContextType >::mIsReady, otRadioFrame::mPsdu, RadioSpinel< InterfaceType, ProcessContextType >::mRxPsdu, RadioSpinel< InterfaceType, ProcessContextType >::mRxRadioFrame, RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface, RadioSpinel< InterfaceType, ProcessContextType >::mTxPsdu, RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioFrame, RadioSpinel< InterfaceType, ProcessContextType >::mVersion, OT_ERROR_FAILED, OT_ERROR_NONE, OT_EXIT_FAILURE, OT_EXIT_RADIO_SPINEL_INCOMPATIBLE, OT_EXIT_SUCCESS, RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp(), RadioSpinel< InterfaceType, ProcessContextType >::SendReset(), SPINEL_DATATYPE_EUI64_S, SPINEL_DATATYPE_UTF8_S, SPINEL_PROP_HWADDR, SPINEL_PROP_NCP_VERSION, SPINEL_RESET_STACK, SuccessOrDie, SuccessOrExit, VerifyOrExit, and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
Referenced by Radio::Init(), and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
Deinit()
void Deinit (void)
Deinitialize this radio transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface, and RadioSpinel< InterfaceType, ProcessContextType >::RadioSpinel().
Referenced by platformRadioDeinit(), and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
IsPromiscuous()
bool IsPromiscuous (void) const inline
This method gets the status of promiscuous mode.
Return values
true Promiscuous mode is enabled.
false Promiscuous mode is disabled.
References RadioSpinel< InterfaceType, ProcessContextType >::GetCcaEnergyDetectThreshold(), RadioSpinel< InterfaceType, ProcessContextType >::GetFemLnaGain(), RadioSpinel< InterfaceType, ProcessContextType >::GetIeeeEui64(), RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitPower(), RadioSpinel< InterfaceType, ProcessContextType >::mIsPromiscuous, RadioSpinel< InterfaceType, ProcessContextType >::SetCcaEnergyDetectThreshold(), RadioSpinel< InterfaceType, ProcessContextType >::SetExtendedAddress(), RadioSpinel< InterfaceType, ProcessContextType >::SetFemLnaGain(), RadioSpinel< InterfaceType, ProcessContextType >::SetPanId(), RadioSpinel< InterfaceType, ProcessContextType >::SetPromiscuous(), RadioSpinel< InterfaceType, ProcessContextType >::SetShortAddress(), and RadioSpinel< InterfaceType, ProcessContextType >::SetTransmitPower().
Referenced by otPlatRadioGetPromiscuous().
SetPromiscuous()
otError SetPromiscuous (bool aEnable)
This method sets the status of promiscuous mode.
Parameters
[in] aEnable Whether to enable or disable promiscuous mode.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mIsPromiscuous, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_UINT8_S, SPINEL_MAC_PROMISCUOUS_MODE_NETWORK, SPINEL_MAC_PROMISCUOUS_MODE_OFF, SPINEL_PROP_MAC_PROMISCUOUS_MODE, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioSetPromiscuous().
SetShortAddress()
otError SetShortAddress (uint16_t aAddress)
This method sets the Short Address for address filtering.
Parameters
[in] aShortAddress The IEEE 802.15.4 Short Address.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mShortAddress, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_UINT16_S, SPINEL_PROP_MAC_15_4_SADDR, SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioSetShortAddress().
GetIeeeEui64()
otError GetIeeeEui64 (uint8_t * aIeeeEui64)
This method gets the factory-assigned IEEE EUI-64 for this transceiver.
Parameters
[in] aInstance The OpenThread instance structure.
[out] aIeeeEui64 A pointer to the factory-assigned IEEE EUI-64.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References otExtAddress::m8, RadioSpinel< InterfaceType, ProcessContextType >::mIeeeEui64, and OT_ERROR_NONE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioGetIeeeEui64().
SetExtendedAddress()
otError SetExtendedAddress (const otExtAddress & aAddress)
This method sets the Extended Address for address filtering.
Parameters
[in] aExtAddress A pointer to the IEEE 802.15.4 Extended Address stored in little-endian byte order.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References otExtAddress::m8, RadioSpinel< InterfaceType, ProcessContextType >::mExtendedAddress, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_EUI64_S, SPINEL_PROP_MAC_15_4_LADDR, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioSetExtendedAddress().
SetPanId()
otError SetPanId (uint16_t aPanId)
This method sets the PAN ID for address filtering.
Parameters
[in] aPanId The IEEE 802.15.4 PAN ID.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mPanId, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_UINT16_S, SPINEL_PROP_MAC_15_4_PANID, SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioSetPanId().
GetTransmitPower()
otError GetTransmitPower (int8_t & aPower)
This method gets the radio's transmit power in dBm.
Parameters
[out] aPower The transmit power in dBm.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), ot::Spinel::LogIfFail(), SPINEL_DATATYPE_INT8_S, and SPINEL_PROP_PHY_TX_POWER.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioGetTransmitPower().
SetTransmitPower()
otError SetTransmitPower (int8_t aPower)
This method sets the radio's transmit power in dBm.
Parameters
[in] aPower The transmit power in dBm.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_INT8_S, SPINEL_PROP_PHY_TX_POWER, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioSetTransmitPower().
GetCcaEnergyDetectThreshold()
otError GetCcaEnergyDetectThreshold (int8_t & aThreshold)
This method gets the radio's CCA ED threshold in dBm.
Parameters
[out] aThreshold The CCA ED threshold in dBm.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), ot::Spinel::LogIfFail(), SPINEL_DATATYPE_INT8_S, and SPINEL_PROP_PHY_CCA_THRESHOLD.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioGetCcaEnergyDetectThreshold().
SetCcaEnergyDetectThreshold()
otError SetCcaEnergyDetectThreshold (int8_t aThreshold)
This method sets the radio's CCA ED threshold in dBm.
Parameters
[in] aThreshold The CCA ED threshold in dBm.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_INT8_S, SPINEL_PROP_PHY_CCA_THRESHOLD, and SuccessOrExit.
Referenced by Radio::Init(), RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioSetCcaEnergyDetectThreshold().
GetFemLnaGain()
otError GetFemLnaGain (int8_t & aGain)
This method gets the FEM's Rx LNA gain in dBm.
Parameters
[out] aGain The FEM's Rx LNA gain in dBm.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), ot::Spinel::LogIfFail(), SPINEL_DATATYPE_INT8_S, and SPINEL_PROP_PHY_FEM_LNA_GAIN.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioGetFemLnaGain().
SetFemLnaGain()
otError SetFemLnaGain (int8_t aGain)
This method sets the FEM's Rx LNA gain in dBm.
Parameters
[in] aGain The FEM's Rx LNA gain in dBm.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_INT8_S, SPINEL_PROP_PHY_FEM_LNA_GAIN, and SuccessOrExit.
Referenced by Radio::Init(), RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and otPlatRadioSetFemLnaGain().
GetVersion()
const char* GetVersion (void) const inline
This method returns the radio sw version string.
Returns
A pointer to the radio version string.
References RadioSpinel< InterfaceType, ProcessContextType >::mVersion.
Referenced by otPlatRadioGetVersionString().
GetRadioCaps()
otRadioCaps GetRadioCaps (void) const inline
This method returns the radio capabilities.
Returns
The radio capability bit vector.
References RadioSpinel< InterfaceType, ProcessContextType >::GetRssi(), and RadioSpinel< InterfaceType, ProcessContextType >::mRadioCaps.
Referenced by otPlatRadioGetCaps().
GetRssi()
int8_t GetRssi (void)
This method gets the most recent RSSI measurement.
Returns
The RSSI in dBm when it is valid. 127 when RSSI is invalid.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), ot::Spinel::LogIfFail(), otRadioCoexMetrics::mAvgRxRequestToGrantTime, otRadioCoexMetrics::mAvgTxRequestToGrantTime, otRadioCoexMetrics::mNumGrantGlitch, otRadioCoexMetrics::mNumRxDelayedGrant, otRadioCoexMetrics::mNumRxGrantDeactivatedDuringRequest, otRadioCoexMetrics::mNumRxGrantImmediate, otRadioCoexMetrics::mNumRxGrantNone, otRadioCoexMetrics::mNumRxGrantWait, otRadioCoexMetrics::mNumRxGrantWaitActivated, otRadioCoexMetrics::mNumRxGrantWaitTimeout, otRadioCoexMetrics::mNumRxRequest, otRadioCoexMetrics::mNumTxDelayedGrant, otRadioCoexMetrics::mNumTxGrantDeactivatedDuringRequest, otRadioCoexMetrics::mNumTxGrantImmediate, otRadioCoexMetrics::mNumTxGrantWait, otRadioCoexMetrics::mNumTxGrantWaitActivated, otRadioCoexMetrics::mNumTxGrantWaitTimeout, otRadioCoexMetrics::mNumTxRequest, otRadioCoexMetrics::mStopped, OT_RADIO_RSSI_INVALID, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_BOOL_S, SPINEL_DATATYPE_INT8_S, SPINEL_DATATYPE_STRUCT_S, SPINEL_DATATYPE_UINT32_S, SPINEL_PROP_PHY_RSSI, SPINEL_PROP_RADIO_COEX_ENABLE, SPINEL_PROP_RADIO_COEX_METRICS, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetRadioCaps(), and otPlatRadioGetRssi().
GetReceiveSensitivity()
int8_t GetReceiveSensitivity (void) const inline
This method returns the radio receive sensitivity value.
Returns
The radio receive sensitivity value in dBm.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::GetState(), and RadioSpinel< InterfaceType, ProcessContextType >::mRxSensitivity.
Referenced by otPlatRadioGetReceiveSensitivity().
GetState()
otRadioState GetState (void) const
This method gets current state of the radio.
Returns
Current state of the radio.
References RadioSpinel< InterfaceType, ProcessContextType >::mState, OT_RADIO_STATE_DISABLED, OT_RADIO_STATE_RECEIVE, OT_RADIO_STATE_SLEEP, and OT_RADIO_STATE_TRANSMIT.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetReceiveSensitivity(), and otPlatRadioGetState().
GetChannel()
uint8_t GetChannel (void) const inline
This method gets the current receiving channel.
Returns
Current receiving channel.
References RadioSpinel< InterfaceType, ProcessContextType >::mChannel.
GetTransmitFrame()
otRadioFrame& GetTransmitFrame (void) inline
This method returns a reference to the transmit buffer.
The caller forms the IEEE 802.15.4 frame in this buffer then calls otPlatRadioTransmit() to request transmission.
Returns
A reference to the transmit buffer.
References RadioSpinel< InterfaceType, ProcessContextType >::AddSrcMatchExtEntry(), RadioSpinel< InterfaceType, ProcessContextType >::AddSrcMatchShortEntry(), RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchExtEntries(), RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchExtEntry(), RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchShortEntries(), RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchShortEntry(), RadioSpinel< InterfaceType, ProcessContextType >::Disable(), RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::EnableSrcMatch(), RadioSpinel< InterfaceType, ProcessContextType >::EnergyScan(), RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioFrame, RadioSpinel< InterfaceType, ProcessContextType >::Receive(), RadioSpinel< InterfaceType, ProcessContextType >::Sleep(), and RadioSpinel< InterfaceType, ProcessContextType >::Transmit().
Referenced by otPlatRadioGetTransmitBuffer().
EnableSrcMatch()
otError EnableSrcMatch (bool aEnable)
This method enables or disables source address match feature.
Parameters
[in] aEnable Enable/disable source address match feature.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_BOOL_S, and SPINEL_PROP_MAC_SRC_MATCH_ENABLED.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioEnableSrcMatch().
AddSrcMatchShortEntry()
otError AddSrcMatchShortEntry (uint16_t aShortAddress)
This method adds a short address to the source address match table.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aShortAddress The short address to be added.
Return values
OT_ERROR_NONE Successfully added short address to the source match table.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
OT_ERROR_NO_BUFS No available entry in the source match table.
References ExitNow, RadioSpinel< InterfaceType, ProcessContextType >::Insert(), OPENTHREAD_CONFIG_MLE_MAX_CHILDREN, SPINEL_DATATYPE_UINT16_S, SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioAddSrcMatchShortEntry().
ClearSrcMatchShortEntry()
otError ClearSrcMatchShortEntry (uint16_t aShortAddress)
This method removes a short address from the source address match table.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aShortAddress The short address to be removed.
Return values
OT_ERROR_NONE Successfully removed short address from the source match table.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
OT_ERROR_NO_ADDRESS The short address is not in source address match table.
References RadioSpinel< InterfaceType, ProcessContextType >::Remove(), SPINEL_DATATYPE_UINT16_S, SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioClearSrcMatchShortEntry().
ClearSrcMatchShortEntries()
otError ClearSrcMatchShortEntries (void)
Clear all short addresses from the source address match table.
Parameters
[in] aInstance The OpenThread instance structure.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioClearSrcMatchShortEntries().
AddSrcMatchExtEntry()
otError AddSrcMatchExtEntry (const otExtAddress & aExtAddress)
Add an extended address to the source address match table.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aExtAddress The extended address to be added stored in little-endian byte order.
Return values
OT_ERROR_NONE Successfully added extended address to the source match table.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
OT_ERROR_NO_BUFS No available entry in the source match table.
References ExitNow, RadioSpinel< InterfaceType, ProcessContextType >::Insert(), otExtAddress::m8, OPENTHREAD_CONFIG_MLE_MAX_CHILDREN, OT_EXT_ADDRESS_SIZE, SPINEL_DATATYPE_EUI64_S, SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioAddSrcMatchExtEntry().
ClearSrcMatchExtEntry()
otError ClearSrcMatchExtEntry (const otExtAddress & aExtAddress)
Remove an extended address from the source address match table.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aExtAddress The extended address to be removed stored in little-endian byte order.
Return values
OT_ERROR_NONE Successfully removed the extended address from the source match table.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
OT_ERROR_NO_ADDRESS The extended address is not in source address match table.
References otExtAddress::m8, OT_EXT_ADDRESS_SIZE, RadioSpinel< InterfaceType, ProcessContextType >::Remove(), SPINEL_DATATYPE_EUI64_S, SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioClearSrcMatchExtEntry().
ClearSrcMatchExtEntries()
otError ClearSrcMatchExtEntries (void)
Clear all the extended/long addresses from source address match table.
Parameters
[in] aInstance The OpenThread instance structure.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioClearSrcMatchExtEntries().
EnergyScan()
otError EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
This method begins the energy scan sequence on the radio.
Parameters
[in] aScanChannel The channel to perform the energy scan on.
[in] aScanDuration The duration, in milliseconds, for the channel to be scanned.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mChannel, RadioSpinel< InterfaceType, ProcessContextType >::mRadioCaps, OT_ERROR_NOT_CAPABLE, OT_RADIO_CAPS_ENERGY_SCAN, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_DATA_S, SPINEL_DATATYPE_UINT16_S, SPINEL_DATATYPE_UINT8_S, SPINEL_PROP_MAC_SCAN_MASK, SPINEL_PROP_MAC_SCAN_PERIOD, SPINEL_PROP_MAC_SCAN_STATE, SPINEL_SCAN_STATE_ENERGY, SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), otPlatRadioEnergyScan(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
Transmit()
otError Transmit (otRadioFrame & aFrame)
This method switches the radio state from Receive to Transmit.
Parameters
[in] aFrame A reference to the transmitted frame.
Return values
OT_ERROR_NONE Successfully transitioned to Transmit.
OT_ERROR_BUSY Failed due to another transmission is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
OT_ERROR_INVALID_STATE The radio was not in the Receive state.
References RadioSpinel< InterfaceType, ProcessContextType >::kStateReceive, RadioSpinel< InterfaceType, ProcessContextType >::kStateSleep, RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitting, otRadioFrame::mChannel, RadioSpinel< InterfaceType, ProcessContextType >::mChannel, otRadioFrame::mInfo, RadioSpinel< InterfaceType, ProcessContextType >::mInstance, otRadioFrame::mLength, otRadioFrame::mPsdu, RadioSpinel< InterfaceType, ProcessContextType >::mRadioCaps, RadioSpinel< InterfaceType, ProcessContextType >::mState, RadioSpinel< InterfaceType, ProcessContextType >::mTransmitFrame, otRadioFrame::mTxInfo, RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioEndUs, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_RADIO_CAPS_SLEEP_TO_TX, otPlatRadioTxStarted(), otPlatTimeGet(), RadioSpinel< InterfaceType, ProcessContextType >::Request(), SPINEL_CMD_PROP_VALUE_SET, SPINEL_DATATYPE_BOOL_S, SPINEL_DATATYPE_DATA_WLEN_S, SPINEL_DATATYPE_UINT32_S, SPINEL_DATATYPE_UINT8_S, SPINEL_PROP_STREAM_RAW, TX_WAIT_US, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioTransmit().
Receive()
otError Receive (uint8_t aChannel)
This method switches the radio state from Sleep to Receive.
Parameters
[in] aChannel The channel to use for receiving.
Return values
OT_ERROR_NONE Successfully transitioned to Receive.
OT_ERROR_INVALID_STATE The radio was disabled or transmitting.
References RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::kStateDisabled, RadioSpinel< InterfaceType, ProcessContextType >::kStateReceive, RadioSpinel< InterfaceType, ProcessContextType >::kStateSleep, RadioSpinel< InterfaceType, ProcessContextType >::mChannel, RadioSpinel< InterfaceType, ProcessContextType >::mState, RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioTid, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_BOOL_S, SPINEL_DATATYPE_UINT8_S, SPINEL_PROP_MAC_RAW_STREAM_ENABLED, SPINEL_PROP_PHY_CHAN, SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioReceive().
Sleep()
otError Sleep (void)
This method switches the radio state from Receive to Sleep.
Return values
OT_ERROR_NONE Successfully transitioned to Sleep.
OT_ERROR_BUSY The radio was transmitting
OT_ERROR_INVALID_STATE The radio was disabled
References RadioSpinel< InterfaceType, ProcessContextType >::kStateReceive, RadioSpinel< InterfaceType, ProcessContextType >::kStateSleep, RadioSpinel< InterfaceType, ProcessContextType >::mState, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_BOOL_S, SPINEL_PROP_MAC_RAW_STREAM_ENABLED, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioSleep().
Enable()
otError Enable (otInstance * aInstance)
Enable the radio.
Parameters
[in] aInstance A pointer to the OpenThread instance.
Return values
OT_ERROR_NONE Successfully enabled.
OT_ERROR_FAILED The radio could not be enabled.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::IsEnabled(), RadioSpinel< InterfaceType, ProcessContextType >::kStateSleep, RadioSpinel< InterfaceType, ProcessContextType >::mInstance, RadioSpinel< InterfaceType, ProcessContextType >::mPanId, RadioSpinel< InterfaceType, ProcessContextType >::mRxSensitivity, RadioSpinel< InterfaceType, ProcessContextType >::mShortAddress, RadioSpinel< InterfaceType, ProcessContextType >::mState, OT_ERROR_FAILED, OT_ERROR_NONE, otLogWarnPlat(), otThreadErrorToString(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_BOOL_S, SPINEL_DATATYPE_INT8_S, SPINEL_DATATYPE_UINT16_S, SPINEL_PROP_MAC_15_4_PANID, SPINEL_PROP_MAC_15_4_SADDR, SPINEL_PROP_PHY_ENABLED, SPINEL_PROP_PHY_RX_SENSITIVITY, SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioEnable().
Disable()
otError Disable (void)
Disable the radio.
Return values
OT_ERROR_NONE Successfully transitioned to Disabled.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::IsEnabled(), RadioSpinel< InterfaceType, ProcessContextType >::kStateDisabled, RadioSpinel< InterfaceType, ProcessContextType >::kStateSleep, RadioSpinel< InterfaceType, ProcessContextType >::mInstance, RadioSpinel< InterfaceType, ProcessContextType >::mState, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_BOOL_S, SPINEL_DATATYPE_UTF8_S, SPINEL_PROP_NEST_STREAM_MFG, SPINEL_PROP_PHY_ENABLED, SuccessOrDie, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and otPlatRadioDisable().
IsEnabled()
bool IsEnabled (void) const inline
This method checks whether radio is enabled or not.
Returns
TRUE if the radio is enabled, FALSE otherwise.
References RadioSpinel< InterfaceType, ProcessContextType >::kStateDisabled, and RadioSpinel< InterfaceType, ProcessContextType >::mState.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Disable(), RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), and otPlatRadioIsEnabled().
IsTransmitting()
bool IsTransmitting (void) const inline
This method indicates whether there is a pending transmission.
Return values
TRUE There is a pending transmission.
FALSE There is no pending transmission.
References RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitting, and RadioSpinel< InterfaceType, ProcessContextType >::mState.
Referenced by platformRadioUpdateFdSet().
IsTransmitDone()
bool IsTransmitDone (void) const inline
This method indicates whether a transmit has just finished.
Return values
TRUE The transmission is done.
FALSE The transmission is not done.
References RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitDone, and RadioSpinel< InterfaceType, ProcessContextType >::mState.
Referenced by platformRadioUpdateFdSet().
GetTxRadioEndUs()
uint64_t GetTxRadioEndUs (void) const inline
This method returns the timeout timepoint for the pending transmission.
Returns
The timeout timepoint for the pending transmission.
References RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioEndUs, and RadioSpinel< InterfaceType, ProcessContextType >::Process().
Referenced by platformRadioUpdateFdSet().
Process()
void Process (const ProcessContextType & aContext)
This method processes any pending the I/O data.
Parameters
[in] aContext The process context.
References RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), MultiFrameBuffer< kSize >::HasSavedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::mRxFrameBuffer, RadioSpinel< InterfaceType, ProcessContextType >::ProcessFrameQueue(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTxRadioEndUs(), platformRadioProcess(), and platformRadioUpdateFdSet().
GetSpinelInterface()
InterfaceType& GetSpinelInterface (void) inline
This method returns the underlying spinel interface.
Returns
The underlying spinel interface.
References RadioSpinel< InterfaceType, ProcessContextType >::GetRadioChannelMask(), RadioSpinel< InterfaceType, ProcessContextType >::GetRadioRegion(), RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::IsRcp(), RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface, RadioSpinel< InterfaceType, ProcessContextType >::SetMacFrameCounter(), RadioSpinel< InterfaceType, ProcessContextType >::SetMacKey(), and RadioSpinel< InterfaceType, ProcessContextType >::SetRadioRegion().
Referenced by Radio::Init(), otSysGetRcpInterfaceMetrics(), platformRadioUpdateFdSet(), and RadioSpinel< InterfaceType, ProcessContextType >::Process().
GetRadioChannelMask()
uint32_t GetRadioChannelMask (bool aPreferred)
This method returns the radio channel mask.
Parameters
[in] aPreferred TRUE to get preferred channel mask, FALSE to get supported channel mask.
Returns
The radio channel mask according to : The radio supported channel mask that the device is allowed to be on. The radio preferred channel mask that the device prefers to form on.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), MaxPowerTable::GetSupportedChannelMask(), RadioSpinel< InterfaceType, ProcessContextType >::kChannelMaskBufferSize, ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::mMaxPowerTable, OT_ERROR_FAILED, OT_ERROR_NONE, OT_ERROR_PARSE, SPINEL_DATATYPE_DATA_S, SPINEL_DATATYPE_UINT8_S, spinel_datatype_unpack(), SPINEL_PROP_PHY_CHAN_PREFERRED, SPINEL_PROP_PHY_CHAN_SUPPORTED, SuccessOrDie, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), otPlatRadioGetPreferredChannelMask(), and otPlatRadioGetSupportedChannelMask().
HandleReceivedFrame() [1/2]
void HandleReceivedFrame (void)
This method processes a received Spinel frame.
The newly received frame is available in RxFrameBuffer from SpinelInterface::GetRxFrameBuffer().
References MultiFrameBuffer< kSize >::DiscardFrame(), MultiFrameBuffer< kSize >::GetFrame(), MultiFrameBuffer< kSize >::GetLength(), RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::mRxFrameBuffer, OT_ERROR_NONE, OT_ERROR_PARSE, otLogWarnPlat(), otThreadErrorToString(), spinel_datatype_unpack(), SPINEL_HEADER_FLAG, SPINEL_HEADER_GET_IID, SPINEL_HEADER_GET_TID, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface().
SetMacKey()
otError SetMacKey (uint8_t aKeyIdMode, uint8_t aKeyId, const otMacKeyMaterial * aPrevKey, const otMacKeyMaterial * aCurrKey, const otMacKeyMaterial * aNextKey)
This method sets MAC key and key index to RCP.
Parameters
[in] aKeyIdMode The key ID mode.
[in] aKeyId The key index.
[in] aPrevKey Pointer to previous MAC key.
[in] aCurrKey Pointer to current MAC key.
[in] aNextKey Pointer to next MAC key.
Return values
OT_ERROR_NONE Succeeded.
OT_ERROR_INVALID_ARGS One of the keys passed is invalid..
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References ot::kErrorInvalidArgs, otMacKey::m8, otMacKeyMaterial::mKey, otMacKeyMaterial::mKeyMaterial, otMacKeyMaterial::mKeyRef, OT_MAC_KEY_SIZE, OT_UNUSED_VARIABLE, otPlatCryptoExportKey(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_DATA_WLEN_S, SPINEL_DATATYPE_UINT8_S, SPINEL_PROP_RCP_MAC_KEY, SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), and otPlatRadioSetMacKey().
SetMacFrameCounter()
otError SetMacFrameCounter (uint32_t aMacFrameCounter)
This method sets the current MAC Frame Counter value.
Parameters
[in] aMacFrameCounter The MAC Frame Counter value.
References RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_UINT32_S, SPINEL_PROP_RCP_MAC_FRAME_COUNTER, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), and otPlatRadioSetMacFrameCounter().
SetRadioRegion()
otError SetRadioRegion (uint16_t aRegionCode)
This method sets the radio region code.
Parameters
[in] aRegionCode The radio region code.
Return values
OT_ERROR_NONE Successfully set region code.
OT_ERROR_FAILED Other platform specific errors.
References OT_ERROR_NONE, otLogNotePlat(), otLogWarnPlat(), otThreadErrorToString(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_UINT16_S, and SPINEL_PROP_PHY_REGION_CODE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), Radio::Init(), and otPlatRadioSetRegion().
GetRadioRegion()
otError GetRadioRegion (uint16_t * aRegionCode)
This method gets the radio region code.
Parameters
[out] aRegionCode The radio region code.
Return values
OT_ERROR_INVALID_ARGS aRegionCode is nullptr.
OT_ERROR_NONE Successfully got region code.
OT_ERROR_FAILED Other platform specific errors.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), ot::Spinel::LogIfFail(), otExtAddress::m8, otLinkMetrics::mLinkMargin, otLinkMetrics::mLqi, otLinkMetrics::mPduCount, otLinkMetrics::mRssi, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::Set(), SPINEL_DATATYPE_EUI64_S, SPINEL_DATATYPE_UINT16_S, SPINEL_DATATYPE_UINT8_S, SPINEL_PROP_PHY_REGION_CODE, SPINEL_PROP_RCP_CSL_ACCURACY, SPINEL_PROP_RCP_CSL_UNCERTAINTY, SPINEL_PROP_RCP_ENH_ACK_PROBING, SPINEL_THREAD_LINK_METRIC_LINK_MARGIN, SPINEL_THREAD_LINK_METRIC_LQI, SPINEL_THREAD_LINK_METRIC_PDU_COUNT, SPINEL_THREAD_LINK_METRIC_RSSI, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), and otPlatRadioGetRegion().
IsRcp()
bool IsRcp (bool & aSupportsRcpApiVersion)
This method checks whether the spinel interface is radio-only.
Parameters
[out] aSupportsRcpApiVersion A reference to a boolean variable to update whether the list of spinel capabilities include SPINEL_CAP_RCP_API_VERSION.
Return values
TRUE The radio chip is in radio-only mode.
FALSE Otherwise.
References DieNow, RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::kCapsBufferSize, RadioSpinel< InterfaceType, ProcessContextType >::mSupportsLogStream, OT_EXIT_RADIO_SPINEL_INCOMPATIBLE, otLogCritPlat(), SPINEL_CAP_CONFIG_RADIO, SPINEL_CAP_MAC_RAW, SPINEL_CAP_OPENTHREAD_LOG_METADATA, SPINEL_CAP_RCP_API_VERSION, SPINEL_DATATYPE_DATA_S, SPINEL_DATATYPE_UINT_PACKED_S, spinel_datatype_unpack(), SPINEL_PROP_CAPS, SuccessOrDie, and VerifyOrDie.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), and RadioSpinel< InterfaceType, ProcessContextType >::Init().
HasPendingFrame()
bool HasPendingFrame (void) const inline
This method checks whether there is pending frame in the buffer.
Returns
Whether there is pending frame in the buffer.
References MultiFrameBuffer< kSize >::HasSavedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::mRxFrameBuffer, and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
Referenced by platformRadioUpdateFdSet().
RestoreDatasetFromNcp()
otError RestoreDatasetFromNcp (void)
This method gets dataset from NCP radio and saves it.
Return values
OT_ERROR_NONE Successfully restore dataset.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the radio.
OT_ERROR_NOT_FOUND Failed due to spinel property not supported in radio.
OT_ERROR_FAILED Failed due to other reasons.
References RadioSpinel< InterfaceType, ProcessContextType >::Deinit(), Instance::Get(), RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), OT_ERROR_NONE, otLogInfoPlat(), SPINEL_DATATYPE_VOID_S, SPINEL_PROP_THREAD_ACTIVE_DATASET, SPINEL_PROP_THREAD_PENDING_DATASET, SuccessOrExit, and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HasPendingFrame(), and RadioSpinel< InterfaceType, ProcessContextType >::Init().
GetNextRadioTimeRecalcStart()
uint64_t GetNextRadioTimeRecalcStart (void) const inline
This method returns the next timepoint to recalculate RCP time offset.
Returns
The timepoint to start the recalculation of RCP time offset.
References RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::GetBusSpeed(), RadioSpinel< InterfaceType, ProcessContextType >::GetNow(), RadioSpinel< InterfaceType, ProcessContextType >::GetWithParam(), RadioSpinel< InterfaceType, ProcessContextType >::Insert(), RadioSpinel< InterfaceType, ProcessContextType >::mRadioTimeRecalcStart, RadioSpinel< InterfaceType, ProcessContextType >::Remove(), RadioSpinel< InterfaceType, ProcessContextType >::SendReset(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), and RadioSpinel< InterfaceType, ProcessContextType >::SetChannelMaxTransmitPower().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), and platformRadioUpdateFdSet().
GetNow()
uint64_t GetNow (void)
This method gets the current estimated time on RCP.
Returns
The current estimated RCP time in microseconds.
References RadioSpinel< InterfaceType, ProcessContextType >::mIsTimeSynced, RadioSpinel< InterfaceType, ProcessContextType >::mRadioTimeOffset, and otPlatTimeGet().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), and otPlatRadioGetNow().
GetBusSpeed()
uint32_t GetBusSpeed (void) const
This method returns the bus speed between the host and the radio.
Returns
bus speed in bits/second.
References RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), and otPlatRadioGetBusSpeed().
SetChannelMaxTransmitPower()
otError SetChannelMaxTransmitPower (uint8_t aChannel, int8_t aPower)
This method sets the max transmit power.
Parameters
[in] aChannel The radio channel.
[in] aPower The max transmit power in dBm.
Return values
OT_ERROR_NONE Successfully set the max transmit power.
OT_ERROR_INVALID_ARGS Channel is not in valid range.
References RadioSpinel< InterfaceType, ProcessContextType >::mMaxPowerTable, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::Set(), MaxPowerTable::SetTransmitPower(), SPINEL_DATATYPE_INT8_S, SPINEL_DATATYPE_UINT8_S, SPINEL_PROP_PHY_CHAN_MAX_POWER, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), Radio::Init(), otPlatRadioSetChannelMaxTransmitPower(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
Get()
otError Get (spinel_prop_key_t aKey, const char * aFormat, ...)
This method tries to retrieve a spinel property from OpenThread transceiver.
Parameters
[in] aKey Spinel property key.
[in] aFormat Spinel formatter to unpack property value.
[out] ... Variable arguments list.
Return values
OT_ERROR_NONE Successfully got the property.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mPropertyArgs, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormatV(), and SPINEL_CMD_PROP_VALUE_GET.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CheckRadioCapabilities(), RadioSpinel< InterfaceType, ProcessContextType >::CheckRcpApiVersion(), RadioSpinel< InterfaceType, ProcessContextType >::CheckSpinelVersion(), RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::GetCcaEnergyDetectThreshold(), RadioSpinel< InterfaceType, ProcessContextType >::GetFemLnaGain(), RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), RadioSpinel< InterfaceType, ProcessContextType >::GetRadioChannelMask(), RadioSpinel< InterfaceType, ProcessContextType >::GetRadioRegion(), RadioSpinel< InterfaceType, ProcessContextType >::GetRssi(), RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitPower(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), RadioSpinel< InterfaceType, ProcessContextType >::IsRcp(), and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
GetWithParam()
otError GetWithParam (spinel_prop_key_t aKey, const uint8_t * aParam, spinel_size_t aParamSize, const char * aFormat, ...)
This method tries to retrieve a spinel property from OpenThread transceiver with parameter appended.
Parameters
[in] aKey Spinel property key.
[in] aParam Parameter appended to spinel command.
[in] aParamSize Size of parameter appended to spinel command
[in] aFormat Spinel formatter to unpack property value.
[out] ... Variable arguments list.
Return values
OT_ERROR_NONE Successfully got the property.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mPropertyArgs, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormat(), SPINEL_CMD_PROP_VALUE_GET, and SPINEL_DATATYPE_DATA_S.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), and RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart().
Set()
otError Set (spinel_prop_key_t aKey, const char * aFormat, ...)
This method tries to update a spinel property of OpenThread transceiver.
Parameters
[in] aKey Spinel property key.
[in] aFormat Spinel formatter to pack property value.
[in] ... Variable arguments list.
Return values
OT_ERROR_NONE Successfully set the property.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mPropertyArgs, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithExpectedCommandV(), SPINEL_CMD_PROP_VALUE_IS, and SPINEL_CMD_PROP_VALUE_SET.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchExtEntries(), RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchShortEntries(), RadioSpinel< InterfaceType, ProcessContextType >::Disable(), RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::EnableSrcMatch(), RadioSpinel< InterfaceType, ProcessContextType >::EnergyScan(), RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), RadioSpinel< InterfaceType, ProcessContextType >::GetRadioRegion(), RadioSpinel< InterfaceType, ProcessContextType >::GetRssi(), RadioSpinel< InterfaceType, ProcessContextType >::Receive(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::SetCcaEnergyDetectThreshold(), RadioSpinel< InterfaceType, ProcessContextType >::SetChannelMaxTransmitPower(), RadioSpinel< InterfaceType, ProcessContextType >::SetExtendedAddress(), RadioSpinel< InterfaceType, ProcessContextType >::SetFemLnaGain(), RadioSpinel< InterfaceType, ProcessContextType >::SetMacFrameCounter(), RadioSpinel< InterfaceType, ProcessContextType >::SetMacKey(), RadioSpinel< InterfaceType, ProcessContextType >::SetPanId(), RadioSpinel< InterfaceType, ProcessContextType >::SetPromiscuous(), RadioSpinel< InterfaceType, ProcessContextType >::SetRadioRegion(), RadioSpinel< InterfaceType, ProcessContextType >::SetShortAddress(), RadioSpinel< InterfaceType, ProcessContextType >::SetTransmitPower(), RadioSpinel< InterfaceType, ProcessContextType >::Sleep(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
Insert()
otError Insert (spinel_prop_key_t aKey, const char * aFormat, ...)
This method tries to insert a item into a spinel list property of OpenThread transceiver.
Parameters
[in] aKey Spinel property key.
[in] aFormat Spinel formatter to pack the item.
[in] ... Variable arguments list.
Return values
OT_ERROR_NONE Successfully insert item into the property.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mPropertyArgs, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithExpectedCommandV(), SPINEL_CMD_PROP_VALUE_INSERT, and SPINEL_CMD_PROP_VALUE_INSERTED.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::AddSrcMatchExtEntry(), RadioSpinel< InterfaceType, ProcessContextType >::AddSrcMatchShortEntry(), RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
Remove()
otError Remove (spinel_prop_key_t aKey, const char * aFormat, ...)
This method tries to remove a item from a spinel list property of OpenThread transceiver.
Parameters
[in] aKey Spinel property key.
[in] aFormat Spinel formatter to pack the item.
[in] ... Variable arguments list.
Return values
OT_ERROR_NONE Successfully removed item from the property.
OT_ERROR_BUSY Failed due to another operation is on going.
OT_ERROR_RESPONSE_TIMEOUT Failed due to no response received from the transceiver.
References RadioSpinel< InterfaceType, ProcessContextType >::mPropertyArgs, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithExpectedCommandV(), SPINEL_CMD_PROP_VALUE_REMOVE, and SPINEL_CMD_PROP_VALUE_REMOVED.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchExtEntry(), RadioSpinel< InterfaceType, ProcessContextType >::ClearSrcMatchShortEntry(), and RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart().
SendReset()
otError SendReset (uint8_t aResetType)
This method tries to reset the co-processor.
[in] aResetType The reset type, SPINEL_RESET_PLATFORM or SPINEL_RESET_STACK.
Return values
OT_ERROR_NONE Successfully removed item from the property.
OT_ERROR_BUSY Failed due to another operation is on going.
References RadioSpinel< InterfaceType, ProcessContextType >::kMaxSpinelFrame, RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface, OT_ERROR_NO_BUFS, OT_ERROR_NONE, SPINEL_CMD_RESET, SPINEL_DATATYPE_COMMAND_S, spinel_datatype_pack(), SPINEL_DATATYPE_UINT8_S, SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
GetRadioSpinelMetrics()
const otRadioSpinelMetrics* GetRadioSpinelMetrics (void) const inline
This method returns the radio Spinel metrics.
Returns
The radio Spinel metrics.
References RadioSpinel< InterfaceType, ProcessContextType >::mRadioSpinelMetrics.
Referenced by otSysGetRadioSpinelMetrics().
HandleReceivedFrame() [2/2]
void HandleReceivedFrame (void * aContext) static private
CheckSpinelVersion()
otError CheckSpinelVersion (void) private
References DieNow, RadioSpinel< InterfaceType, ProcessContextType >::Get(), OT_ERROR_NONE, OT_EXIT_RADIO_SPINEL_INCOMPATIBLE, otLogCritPlat(), SPINEL_DATATYPE_UINT_PACKED_S, SPINEL_PROP_PROTOCOL_VERSION, SPINEL_PROTOCOL_VERSION_THREAD_MAJOR, SPINEL_PROTOCOL_VERSION_THREAD_MINOR, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Init().
CheckRadioCapabilities()
otError CheckRadioCapabilities (void) private
References DieNow, RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::mRadioCaps, OT_ERROR_NONE, OT_EXIT_RADIO_SPINEL_INCOMPATIBLE, OT_RADIO_CAPS_ACK_TIMEOUT, OT_RADIO_CAPS_CSMA_BACKOFF, OT_RADIO_CAPS_TRANSMIT_RETRIES, OT_RADIO_CAPS_TRANSMIT_SEC, OT_RADIO_CAPS_TRANSMIT_TIMING, OT_UNUSED_VARIABLE, otLogCritPlat(), SPINEL_DATATYPE_UINT_PACKED_S, SPINEL_PROP_RADIO_CAPS, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Init().
CheckRcpApiVersion()
otError CheckRcpApiVersion (bool aSupportsRcpApiVersion) private
References DieNow, RadioSpinel< InterfaceType, ProcessContextType >::Get(), OT_ERROR_NONE, OT_EXIT_RADIO_SPINEL_INCOMPATIBLE, otLogCritPlat(), otLogNotePlat(), SPINEL_DATATYPE_UINT_PACKED_S, SPINEL_MIN_HOST_SUPPORTED_RCP_API_VERSION, SPINEL_PROP_RCP_API_VERSION, SPINEL_RCP_API_VERSION, and SuccessOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Init().
ProcessRadioStateMachine()
void ProcessRadioStateMachine (void) private
This method triggers a state transfer of the state machine.
References RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpTimeout(), RadioSpinel< InterfaceType, ProcessContextType >::kStateReceive, RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitDone, RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitting, RadioSpinel< InterfaceType, ProcessContextType >::mAckRadioFrame, otRadioFrame::mLength, RadioSpinel< InterfaceType, ProcessContextType >::mState, RadioSpinel< InterfaceType, ProcessContextType >::mTransmitFrame, RadioSpinel< InterfaceType, ProcessContextType >::mTxError, RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioEndUs, otLogWarnPlat(), otPlatTimeGet(), and RadioSpinel< InterfaceType, ProcessContextType >::TransmitDone().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Process().
ProcessFrameQueue()
void ProcessFrameQueue (void) private
This method processes the frame queue.
References MultiFrameBuffer< kSize >::ClearSavedFrames(), MultiFrameBuffer< kSize >::GetNextSavedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), RadioSpinel< InterfaceType, ProcessContextType >::mRxFrameBuffer, and OT_ERROR_NONE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Process().
GetNextTid()
spinel_tid_t GetNextTid (void) private
References ExitNow, RadioSpinel< InterfaceType, ProcessContextType >::mCmdNextTid, RadioSpinel< InterfaceType, ProcessContextType >::mCmdTidsInUse, and SPINEL_GET_NEXT_TID.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::RequestV().
FreeTid()
void FreeTid (spinel_tid_t tid) inline private
References RadioSpinel< InterfaceType, ProcessContextType >::mCmdTidsInUse, RadioSpinel< InterfaceType, ProcessContextType >::ParseRadioFrame(), RadioSpinel< InterfaceType, ProcessContextType >::Request(), RadioSpinel< InterfaceType, ProcessContextType >::RequestV(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithExpectedCommandV(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormat(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormatV(), RadioSpinel< InterfaceType, ProcessContextType >::SendCommand(), RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), and RadioSpinel< InterfaceType, ProcessContextType >::Receive().
RequestV()
otError RequestV (uint32_t aCommand, spinel_prop_key_t aKey, const char * aFormat, va_list aArgs) private
References RadioSpinel< InterfaceType, ProcessContextType >::GetNextTid(), RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioTid, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingKey, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, OT_ERROR_BUSY, OT_ERROR_NONE, RadioSpinel< InterfaceType, ProcessContextType >::SendCommand(), SPINEL_PROP_STREAM_RAW, SuccessOrExit, VerifyOrExit, and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::Request(), RadioSpinel< InterfaceType, ProcessContextType >::RequestWithExpectedCommandV(), and RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormatV().
Request()
otError Request (uint32_t aCommand, spinel_prop_key_t aKey, const char * aFormat, ...) private
References RadioSpinel< InterfaceType, ProcessContextType >::RequestV().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), and RadioSpinel< InterfaceType, ProcessContextType >::Transmit().
RequestWithPropertyFormat()
otError RequestWithPropertyFormat (const char * aPropertyFormat, uint32_t aCommand, spinel_prop_key_t aKey, const char * aFormat, ...) private
References RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormatV().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), and RadioSpinel< InterfaceType, ProcessContextType >::GetWithParam().
RequestWithPropertyFormatV()
otError RequestWithPropertyFormatV (const char * aPropertyFormat, uint32_t aCommand, spinel_prop_key_t aKey, const char * aFormat, va_list aArgs) private
References RadioSpinel< InterfaceType, ProcessContextType >::mPropertyFormat, and RadioSpinel< InterfaceType, ProcessContextType >::RequestV().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::Get(), and RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormat().
RequestWithExpectedCommandV()
otError RequestWithExpectedCommandV (uint32_t aExpectedCommand, uint32_t aCommand, spinel_prop_key_t aKey, const char * aFormat, va_list aArgs) private
References RadioSpinel< InterfaceType, ProcessContextType >::mExpectedCommand, RadioSpinel< InterfaceType, ProcessContextType >::RequestV(), and SPINEL_CMD_NOOP.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::Insert(), RadioSpinel< InterfaceType, ProcessContextType >::Remove(), and RadioSpinel< InterfaceType, ProcessContextType >::Set().
WaitResponse()
otError WaitResponse (void) private
References ExitNow, RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpTimeout(), RadioSpinel< InterfaceType, ProcessContextType >::kMaxWaitTime, ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::mError, RadioSpinel< InterfaceType, ProcessContextType >::mIsReady, RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingKey, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, OT_ERROR_NONE, otLogDebgPlat(), otLogWarnPlat(), otPlatTimeGet(), SPINEL_PROP_LAST_STATUS, and US_PER_MS.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::RequestV().
SendCommand()
otError SendCommand (uint32_t aCommand, spinel_prop_key_t aKey, spinel_tid_t aTid, const char * aFormat, va_list aArgs) private
References RadioSpinel< InterfaceType, ProcessContextType >::kMaxSpinelFrame, RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface, OT_ERROR_NO_BUFS, OT_ERROR_NONE, spinel_datatype_pack(), spinel_datatype_vpack(), SPINEL_HEADER_FLAG, SPINEL_HEADER_IID_0, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), and RadioSpinel< InterfaceType, ProcessContextType >::RequestV().
ParseRadioFrame()
otError ParseRadioFrame (otRadioFrame & aFrame, const uint8_t * aBuffer, uint16_t aLength, spinel_ssize_t & aUnpacked) private
References ot::Spinel::LogIfFail(), otRadioFrame::mChannel, otRadioFrame::mInfo, otRadioFrame::mLength, otRadioFrame::mPsdu, RadioSpinel< InterfaceType, ProcessContextType >::mRadioCaps, otRadioFrame::mRxInfo, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NUM_ERRORS, OT_RADIO_CAPS_TRANSMIT_SEC, OT_RADIO_FRAME_MAX_SIZE, SPINEL_DATATYPE_DATA_WLEN_S, SPINEL_DATATYPE_INT8_S, SPINEL_DATATYPE_STRUCT_S, SPINEL_DATATYPE_UINT16_S, SPINEL_DATATYPE_UINT32_S, SPINEL_DATATYPE_UINT64_S, SPINEL_DATATYPE_UINT8_S, SPINEL_DATATYPE_UINT_PACKED_S, spinel_datatype_unpack_in_place(), SPINEL_MD_FLAG_ACKED_FP, SPINEL_MD_FLAG_ACKED_SEC, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), and RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs().
ThreadDatasetHandler()
otError ThreadDatasetHandler (const uint8_t * aBuffer, uint16_t aLength) private
References Decoder::CloseStruct(), Instance::Get(), Dataset::GetBytes(), Decoder::GetRemainingLengthInStruct(), Dataset::GetSize(), Decoder::Init(), Decoder::IsAllReadInStruct(), SettingsBase::kKeyActiveDataset, SettingsBase::kKeyPendingDataset, otNetworkKey::m8, otNetworkName::m8, otIp6NetworkPrefix::m8, otExtendedPanId::m8, otPskc::m8, otOperationalDataset::mActiveTimestamp, otOperationalDataset::mChannel, otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDataset::mDelay, otOperationalDataset::mExtendedPanId, otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelMaskPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsDelayPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkKeyPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPskcPresent, otOperationalDatasetComponents::mIsSecurityPolicyPresent, otOperationalDataset::mMeshLocalPrefix, otOperationalDataset::mNetworkKey, otOperationalDataset::mNetworkName, otOperationalDataset::mPanId, otOperationalDataset::mPskc, otSecurityPolicy::mRotationTime, otOperationalDataset::mSecurityPolicy, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingKey, Decoder::OpenStruct(), OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_EXT_PAN_ID_SIZE, OT_IP6_PREFIX_BITSIZE, OT_MESH_LOCAL_PREFIX_SIZE, OT_NETWORK_KEY_SIZE, OT_NETWORK_NAME_MAX_SIZE, OT_PSKC_MAX_SIZE, OT_THREAD_VERSION_1_2, otThreadGetVersion(), Decoder::ReadData(), Decoder::ReadIp6Address(), Decoder::ReadUint16(), Decoder::ReadUint32(), Decoder::ReadUint8(), Decoder::ReadUintPacked(), Decoder::ReadUtf8(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), Dataset::SetFrom(), SPINEL_PROP_DATASET_DELAY_TIMER, SPINEL_PROP_DATASET_SECURITY_POLICY, SPINEL_PROP_IPV6_ML_PREFIX, SPINEL_PROP_MAC_15_4_PANID, SPINEL_PROP_NET_NETWORK_KEY, SPINEL_PROP_NET_NETWORK_NAME, SPINEL_PROP_NET_PSKC, SPINEL_PROP_NET_XPANID, SPINEL_PROP_PHY_CHAN, SPINEL_PROP_PHY_CHAN_SUPPORTED, SPINEL_PROP_THREAD_ACTIVE_DATASET, ot::StringLength(), SuccessOrExit, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
IsSafeToHandleNow()
bool IsSafeToHandleNow (spinel_prop_key_t aKey) const inline private
This method returns if the property changed event is safe to be handled now.
If a property handler will go up to core stack, it may cause reentrant issue of Hdlc::Decode() and WaitResponse().
Parameters
[in] aKey The identifier of the property.
Returns
Whether this property is safe to be handled now.
References RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpTimeout(), RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpUnexpectedReset(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::RadioReceive(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), SPINEL_PROP_MAC_ENERGY_SCAN_RESULT, SPINEL_PROP_STREAM_RAW, and RadioSpinel< InterfaceType, ProcessContextType >::TransmitDone().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification().
HandleNotification() [1/2]
void HandleNotification (SpinelInterface::RxFrameBuffer & aFrameBuffer) private
References MultiFrameBuffer< kSize >::DiscardFrame(), ExitNow, MultiFrameBuffer< kSize >::GetFrame(), MultiFrameBuffer< kSize >::GetLength(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow(), ot::Spinel::LogIfFail(), OT_ERROR_NONE, OT_ERROR_PARSE, otLogInfoPlat(), MultiFrameBuffer< kSize >::SaveFrame(), SPINEL_CMD_PROP_VALUE_INSERTED, SPINEL_CMD_PROP_VALUE_IS, SPINEL_CMD_PROP_VALUE_REMOVED, spinel_datatype_unpack(), SPINEL_HEADER_GET_TID, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow(), and RadioSpinel< InterfaceType, ProcessContextType >::ProcessFrameQueue().
HandleNotification() [2/2]
void HandleNotification (const uint8_t * aBuffer, uint16_t aLength) private
References RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), ot::Spinel::LogIfFail(), OT_ERROR_NONE, OT_ERROR_PARSE, SPINEL_CMD_PROP_VALUE_IS, spinel_datatype_unpack(), SPINEL_HEADER_GET_TID, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
HandleValueIs()
void HandleValueIs (spinel_prop_key_t aKey, const uint8_t * aBuffer, uint16_t aLength) private
References ExitNow, RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpUnexpectedReset(), RadioSpinel< InterfaceType, ProcessContextType >::IsEnabled(), ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::mInstance, RadioSpinel< InterfaceType, ProcessContextType >::mIsReady, RadioSpinel< InterfaceType, ProcessContextType >::mRxRadioFrame, RadioSpinel< InterfaceType, ProcessContextType >::mSupportsLogStream, OPENTHREAD_CONFIG_NCP_SPINEL_LOG_MAX_SIZE, OT_ERROR_NONE, OT_ERROR_PARSE, otLogCritPlat(), otLogDebgPlat(), otLogInfoPlat(), otLogNotePlat(), otLogWarnPlat(), otPlatRadioEnergyScanDone(), RadioSpinel< InterfaceType, ProcessContextType >::ParseRadioFrame(), RadioSpinel< InterfaceType, ProcessContextType >::RadioReceive(), SPINEL_DATATYPE_DATA_S, SPINEL_DATATYPE_UINT8_S, spinel_datatype_unpack(), spinel_datatype_unpack_in_place(), SPINEL_DATATYPE_UTF8_S, SPINEL_NCP_LOG_LEVEL_ALERT, SPINEL_NCP_LOG_LEVEL_CRIT, SPINEL_NCP_LOG_LEVEL_DEBUG, SPINEL_NCP_LOG_LEVEL_EMERG, SPINEL_NCP_LOG_LEVEL_ERR, SPINEL_NCP_LOG_LEVEL_INFO, SPINEL_NCP_LOG_LEVEL_NOTICE, SPINEL_NCP_LOG_LEVEL_WARN, SPINEL_PROP_LAST_STATUS, SPINEL_PROP_MAC_ENERGY_SCAN_RESULT, SPINEL_PROP_STREAM_DEBUG, SPINEL_PROP_STREAM_LOG, SPINEL_PROP_STREAM_RAW, SPINEL_STATUS_OK, SPINEL_STATUS_RESET__BEGIN, SPINEL_STATUS_RESET__END, spinel_status_to_cstr(), SuccessOrExit, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), and RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow().
HandleResponse()
void HandleResponse (const uint8_t * aBuffer, uint16_t aLength) private
References RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitting, ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::mState, RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioTid, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, otLogWarnPlat(), SPINEL_CMD_PROP_VALUE_IS, SPINEL_CMD_PROP_VALUE_REMOVED, spinel_datatype_unpack(), SPINEL_HEADER_GET_TID, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), and RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow().
HandleTransmitDone()
void HandleTransmitDone (uint32_t aCommand, spinel_prop_key_t aKey, const uint8_t * aBuffer, uint16_t aLength) private
References RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitDone, ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::mAckRadioFrame, RadioSpinel< InterfaceType, ProcessContextType >::mRadioCaps, RadioSpinel< InterfaceType, ProcessContextType >::mState, RadioSpinel< InterfaceType, ProcessContextType >::mTransmitFrame, RadioSpinel< InterfaceType, ProcessContextType >::mTxError, OT_ERROR_FAILED, OT_ERROR_NONE, OT_ERROR_PARSE, OT_RADIO_CAPS_TRANSMIT_SEC, RadioSpinel< InterfaceType, ProcessContextType >::ParseRadioFrame(), SPINEL_CMD_PROP_VALUE_IS, SPINEL_DATATYPE_BOOL_S, SPINEL_DATATYPE_UINT32_S, SPINEL_DATATYPE_UINT8_S, SPINEL_DATATYPE_UINT_PACKED_S, spinel_datatype_unpack(), SPINEL_PROP_LAST_STATUS, SPINEL_STATUS_OK, ot::Spinel::SpinelStatusToOtError(), SuccessOrExit, RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), and RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow().
HandleWaitingResponse()
void HandleWaitingResponse (uint32_t aCommand, spinel_prop_key_t aKey, const uint8_t * aBuffer, uint16_t aLength) private
References ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::mError, RadioSpinel< InterfaceType, ProcessContextType >::mExpectedCommand, RadioSpinel< InterfaceType, ProcessContextType >::mPropertyArgs, RadioSpinel< InterfaceType, ProcessContextType >::mPropertyFormat, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingKey, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, spinel_datatype_unpack(), spinel_datatype_unpack_in_place(), SPINEL_DATATYPE_UTF8_S, SPINEL_DATATYPE_VOID_C, spinel_datatype_vunpack_in_place(), SPINEL_PROP_LAST_STATUS, SPINEL_PROP_NEST_STREAM_MFG, ot::Spinel::SpinelStatusToOtError(), RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount(), and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), and RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow().
RadioReceive()
void RadioReceive (void) private
References ExitNow, RadioSpinel< InterfaceType, ProcessContextType >::kStateDisabled, RadioSpinel< InterfaceType, ProcessContextType >::kStateReceive, RadioSpinel< InterfaceType, ProcessContextType >::kStateSleep, RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitDone, RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitting, RadioSpinel< InterfaceType, ProcessContextType >::mInstance, RadioSpinel< InterfaceType, ProcessContextType >::mIsPromiscuous, RadioSpinel< InterfaceType, ProcessContextType >::mRxRadioFrame, RadioSpinel< InterfaceType, ProcessContextType >::mState, OT_ERROR_NONE, otPlatDiagModeGet(), otPlatDiagRadioReceiveDone(), and otPlatRadioReceiveDone().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), and RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow().
TransmitDone()
void TransmitDone (otRadioFrame * aFrame, otRadioFrame * aAckFrame, otError aError) private
References RadioSpinel< InterfaceType, ProcessContextType >::mInstance, otPlatDiagModeGet(), otPlatDiagRadioTransmitDone(), and otPlatRadioTxDone().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow(), and RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine().
CalcRcpTimeOffset()
void CalcRcpTimeOffset (void) private
References RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), RadioSpinel< InterfaceType, ProcessContextType >::GetWithParam(), ot::Spinel::LogIfFail(), RadioSpinel< InterfaceType, ProcessContextType >::mIsTimeSynced, RadioSpinel< InterfaceType, ProcessContextType >::mRadioTimeOffset, RadioSpinel< InterfaceType, ProcessContextType >::mRadioTimeRecalcStart, OT_ERROR_NO_BUFS, OT_ERROR_NONE, otLogDebgPlat(), otPlatTimeGet(), RCP_TIME_OFFSET_CHECK_INTERVAL, spinel_datatype_pack(), SPINEL_DATATYPE_UINT64_S, SPINEL_PROP_RCP_TIMESTAMP, and VerifyOrExit.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow(), RadioSpinel< InterfaceType, ProcessContextType >::Process(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
HandleRcpUnexpectedReset()
void HandleRcpUnexpectedReset (spinel_status_t aStatus) private
References DieNow, RadioSpinel< InterfaceType, ProcessContextType >::mRadioSpinelMetrics, otRadioSpinelMetrics::mRcpUnexpectedResetCount, OT_EXIT_RADIO_SPINEL_RESET, OT_UNUSED_VARIABLE, otLogCritPlat(), and spinel_status_to_cstr().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), and RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow().
HandleRcpTimeout()
void HandleRcpTimeout (void) private
References DieNow, RadioSpinel< InterfaceType, ProcessContextType >::mRadioSpinelMetrics, otRadioSpinelMetrics::mRcpTimeoutCount, and OT_EXIT_RADIO_SPINEL_NO_RESPONSE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
RecoverFromRcpFailure()
void RecoverFromRcpFailure (void) private
References RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), MultiFrameBuffer< kSize >::Clear(), DieNow, RadioSpinel< InterfaceType, ProcessContextType >::EnergyScan(), ExitNow, SettingsBase::NetworkInfo::GetMacFrameCounter(), MaxPowerTable::GetTransmitPower(), RadioSpinel< InterfaceType, ProcessContextType >::Insert(), RadioSpinel< InterfaceType, ProcessContextType >::kStateDisabled, RadioSpinel< InterfaceType, ProcessContextType >::kStateReceive, RadioSpinel< InterfaceType, ProcessContextType >::kStateSleep, RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitDone, RadioSpinel< InterfaceType, ProcessContextType >::kStateTransmitting, otExtAddress::m8, RadioSpinel< InterfaceType, ProcessContextType >::mChannel, RadioSpinel< InterfaceType, ProcessContextType >::mCmdNextTid, RadioSpinel< InterfaceType, ProcessContextType >::mCmdTidsInUse, RadioSpinel< InterfaceType, ProcessContextType >::mError, RadioSpinel< InterfaceType, ProcessContextType >::mExtendedAddress, RadioSpinel< InterfaceType, ProcessContextType >::mInstance, RadioSpinel< InterfaceType, ProcessContextType >::mIsReady, RadioSpinel< InterfaceType, ProcessContextType >::mIsTimeSynced, RadioSpinel< InterfaceType, ProcessContextType >::mMaxPowerTable, RadioSpinel< InterfaceType, ProcessContextType >::mPanId, RadioSpinel< InterfaceType, ProcessContextType >::mRadioSpinelMetrics, otRadioSpinelMetrics::mRcpRestorationCount, RadioSpinel< InterfaceType, ProcessContextType >::mRxFrameBuffer, RadioSpinel< InterfaceType, ProcessContextType >::mShortAddress, RadioSpinel< InterfaceType, ProcessContextType >::mSpinelInterface, RadioSpinel< InterfaceType, ProcessContextType >::mState, RadioSpinel< InterfaceType, ProcessContextType >::mTxError, RadioSpinel< InterfaceType, ProcessContextType >::mTxRadioTid, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingKey, RadioSpinel< InterfaceType, ProcessContextType >::mWaitingTid, OPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT, OT_ERROR_ABORT, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_EXIT_FAILURE, OT_RADIO_POWER_INVALID, otLogCritPlat(), otLogNotePlat(), otLogWarnPlat(), RadioSpinel< InterfaceType, ProcessContextType >::SendReset(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), RadioSpinel< InterfaceType, ProcessContextType >::SetChannelMaxTransmitPower(), SPINEL_DATATYPE_BOOL_S, SPINEL_DATATYPE_DATA_WLEN_S, SPINEL_DATATYPE_EUI64_S, SPINEL_DATATYPE_INT8_S, SPINEL_DATATYPE_UINT16_S, SPINEL_DATATYPE_UINT32_S, SPINEL_DATATYPE_UINT8_S, SPINEL_PROP_LAST_STATUS, SPINEL_PROP_MAC_15_4_LADDR, SPINEL_PROP_MAC_15_4_PANID, SPINEL_PROP_MAC_15_4_SADDR, SPINEL_PROP_MAC_RAW_STREAM_ENABLED, SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, SPINEL_PROP_PHY_CCA_THRESHOLD, SPINEL_PROP_PHY_CHAN, SPINEL_PROP_PHY_ENABLED, SPINEL_PROP_PHY_FEM_LNA_GAIN, SPINEL_PROP_PHY_TX_POWER, SPINEL_PROP_RADIO_COEX_ENABLE, SPINEL_PROP_RCP_MAC_FRAME_COUNTER, SPINEL_PROP_RCP_MAC_KEY, SPINEL_RESET_STACK, SuccessOrDie, and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::GetWithParam(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), RadioSpinel< InterfaceType, ProcessContextType >::Insert(), RadioSpinel< InterfaceType, ProcessContextType >::IsSafeToHandleNow(), RadioSpinel< InterfaceType, ProcessContextType >::Process(), RadioSpinel< InterfaceType, ProcessContextType >::Remove(), and RadioSpinel< InterfaceType, ProcessContextType >::Set().
UpdateParseErrorCount()
void UpdateParseErrorCount (otError aError) inline private
References RadioSpinel< InterfaceType, ProcessContextType >::mRadioSpinelMetrics, otRadioSpinelMetrics::mSpinelParseErrorCount, and OT_ERROR_PARSE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetRadioChannelMask(), RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), and RadioSpinel< InterfaceType, ProcessContextType >::ParseRadioFrame().
Field Documentation
mInstance
otInstance* mInstance private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Disable(), RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::RadioReceive(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::Transmit(), and RadioSpinel< InterfaceType, ProcessContextType >::TransmitDone().
mRxFrameBuffer
SpinelInterface::RxFrameBuffer mRxFrameBuffer private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::HasPendingFrame(), RadioSpinel< InterfaceType, ProcessContextType >::Process(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessFrameQueue(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
mSpinelInterface
InterfaceType mSpinelInterface private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Deinit(), RadioSpinel< InterfaceType, ProcessContextType >::GetBusSpeed(), RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::SendCommand(), RadioSpinel< InterfaceType, ProcessContextType >::SendReset(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
mCmdTidsInUse
uint16_t mCmdTidsInUse private
Used transaction ids.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::FreeTid(), RadioSpinel< InterfaceType, ProcessContextType >::GetNextTid(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
mCmdNextTid
spinel_tid_t mCmdNextTid private
Next available transaction id.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetNextTid(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
mTxRadioTid
spinel_tid_t mTxRadioTid private
The transaction id used to send a radio frame.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::Receive(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::RequestV().
mWaitingTid
spinel_tid_t mWaitingTid private
The transaction id of current transaction.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::GetWithParam(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::Insert(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::Remove(), RadioSpinel< InterfaceType, ProcessContextType >::RequestV(), RadioSpinel< InterfaceType, ProcessContextType >::Set(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
mWaitingKey
spinel_prop_key_t mWaitingKey private
The property key of current transaction.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::RequestV(), RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
mPropertyFormat
const char* mPropertyFormat private
The spinel property format of current transaction.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), and RadioSpinel< InterfaceType, ProcessContextType >::RequestWithPropertyFormatV().
mPropertyArgs
va_list mPropertyArgs private
The arguments pack or unpack spinel property of current transaction.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Get(), RadioSpinel< InterfaceType, ProcessContextType >::GetWithParam(), RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::Insert(), RadioSpinel< InterfaceType, ProcessContextType >::Remove(), and RadioSpinel< InterfaceType, ProcessContextType >::Set().
mExpectedCommand
uint32_t mExpectedCommand private
Expected response command of current transaction.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), and RadioSpinel< InterfaceType, ProcessContextType >::RequestWithExpectedCommandV().
mError
otError mError private
The result of current transaction.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
mRxPsdu
uint8_t mRxPsdu[OT_RADIO_FRAME_MAX_SIZE] private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Init().
mTxPsdu
uint8_t mTxPsdu[OT_RADIO_FRAME_MAX_SIZE] private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Init().
mAckPsdu
uint8_t mAckPsdu[OT_RADIO_FRAME_MAX_SIZE] private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Init().
mRxRadioFrame
otRadioFrame mRxRadioFrame private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), and RadioSpinel< InterfaceType, ProcessContextType >::RadioReceive().
mTxRadioFrame
otRadioFrame mTxRadioFrame private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitFrame(), and RadioSpinel< InterfaceType, ProcessContextType >::Init().
mAckRadioFrame
otRadioFrame mAckRadioFrame private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), and RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine().
mTransmitFrame
otRadioFrame* mTransmitFrame private
Points to the frame to send.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), and RadioSpinel< InterfaceType, ProcessContextType >::Transmit().
mExtendedAddress
otExtAddress mExtendedAddress private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::SetExtendedAddress().
mShortAddress
uint16_t mShortAddress private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::SetShortAddress().
mPanId
uint16_t mPanId private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::SetPanId().
mRadioCaps
otRadioCaps mRadioCaps private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CheckRadioCapabilities(), RadioSpinel< InterfaceType, ProcessContextType >::EnergyScan(), RadioSpinel< InterfaceType, ProcessContextType >::GetRadioCaps(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::ParseRadioFrame(), and RadioSpinel< InterfaceType, ProcessContextType >::Transmit().
mChannel
uint8_t mChannel private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::EnergyScan(), RadioSpinel< InterfaceType, ProcessContextType >::GetChannel(), RadioSpinel< InterfaceType, ProcessContextType >::Receive(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::Transmit().
mRxSensitivity
int8_t mRxSensitivity private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Enable(), and RadioSpinel< InterfaceType, ProcessContextType >::GetReceiveSensitivity().
mTxError
otError mTxError private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
mVersion
char mVersion[kVersionStringSize] private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetVersion(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), and RadioSpinel< InterfaceType, ProcessContextType >::RadioSpinel().
mIeeeEui64
otExtAddress mIeeeEui64 private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetIeeeEui64(), and RadioSpinel< InterfaceType, ProcessContextType >::Init().
mState
State mState private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Disable(), RadioSpinel< InterfaceType, ProcessContextType >::Enable(), RadioSpinel< InterfaceType, ProcessContextType >::GetState(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::IsEnabled(), RadioSpinel< InterfaceType, ProcessContextType >::IsTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::IsTransmitting(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), RadioSpinel< InterfaceType, ProcessContextType >::RadioReceive(), RadioSpinel< InterfaceType, ProcessContextType >::Receive(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::Sleep(), and RadioSpinel< InterfaceType, ProcessContextType >::Transmit().
mIsPromiscuous
bool mIsPromiscuous private
Promiscuous mode.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), RadioSpinel< InterfaceType, ProcessContextType >::RadioReceive(), and RadioSpinel< InterfaceType, ProcessContextType >::SetPromiscuous().
mIsReady
bool mIsReady private
NCP ready.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::Init(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
mSupportsLogStream
bool mSupportsLogStream private
RCP supports LOG_STREAM property with OpenThread log meta-data format.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), and RadioSpinel< InterfaceType, ProcessContextType >::IsRcp().
mIsTimeSynced
bool mIsTimeSynced private
Host has calculated the time difference between host and RCP.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), RadioSpinel< InterfaceType, ProcessContextType >::GetNow(), and RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure().
mTxRadioEndUs
uint64_t mTxRadioEndUs private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetTxRadioEndUs(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), and RadioSpinel< InterfaceType, ProcessContextType >::Transmit().
mRadioTimeRecalcStart
uint64_t mRadioTimeRecalcStart private
When to recalculate RCP time offset.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), and RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart().
mRadioTimeOffset
int64_t mRadioTimeOffset private
Time difference with estimated RCP time minus host time.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), and RadioSpinel< InterfaceType, ProcessContextType >::GetNow().
mMaxPowerTable
MaxPowerTable mMaxPowerTable private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetRadioChannelMask(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::SetChannelMaxTransmitPower().
mRadioSpinelMetrics
otRadioSpinelMetrics mRadioSpinelMetrics private
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetRadioSpinelMetrics(), RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpTimeout(), RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpUnexpectedReset(), RadioSpinel< InterfaceType, ProcessContextType >::RadioSpinel(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::UpdateParseErrorCount().
The documentation for this class was generated from the following files:
radio_spinel.hpp
radio_spinel_impl.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale