OpenThread: ActiveDatasetManager Class Reference
ActiveDatasetManager Class Reference
#include <dataset_manager.hpp>
Public Member Functions
ActiveDatasetManager (Instance &aInstance)
void Clear (void)
bool IsCommissioned (void) const
bool IsPartiallyComplete (void) const
void Save (const Dataset &aDataset)
Error Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Error Save (const Dataset::Info &aDatasetInfo)
Error Save (const otOperationalDatasetTlvs &aDataset)
Public Member Functions inherited from DatasetManager
Error ApplyConfiguration (void) const
Error GetChannelMask (Mac::ChannelMask &aChannelMask) const
const Timestamp * GetTimestamp (void) const
void HandleDetach (void)
Error Read (Dataset &aDataset) const
Error Read (Dataset::Info &aDatasetInfo) const
Error Read (otOperationalDatasetTlvs &aDataset) const
Error Restore (void)
Error SendGetRequest (const Dataset::Components &aDatasetComponents, const uint8_t *aTlvTypes, uint8_t aLength, const otIp6Address *aAddress) const
Error SendSetRequest (const Dataset::Info &aDatasetInfo, const uint8_t *aTlvs, uint8_t aLength, otDatasetMgmtSetCallback aCallback, void *aContext)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
void HandleGet (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleTimer (void)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleGet (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleTimer (Timer &aTimer)
Private Attributes
Coap::Resource mResourceGet
Additional Inherited Members
Protected Member Functions inherited from DatasetManager
void Clear (void)
DatasetManager (Instance &aInstance, Dataset::Type aType, TimerMilli::Handler aTimerHandler)
Dataset::Type GetType (void) const
void HandleGet (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleNetworkUpdate (void)
void HandleTimer (void)
Error Save (const Dataset &aDataset)
Error Save (const Dataset::Info &aDatasetInfo)
Error Save (const otOperationalDatasetTlvs &aDataset)
Error Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Error SaveLocal (const Dataset &aDataset)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Protected Attributes inherited from DatasetManager
DatasetLocal mLocal
Timestamp mTimestamp
bool mTimestampValid: 1
ot::MeshCoP::DatasetManager::DatasetTlv OT_TOOL_PACKED_END
Constructor & Destructor Documentation
ActiveDatasetManager()
ActiveDatasetManager (Instance & aInstance) explicit
This constructor initializes the ActiveDatasetManager object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ActiveDatasetManager::mResourceGet.
Member Function Documentation
IsPartiallyComplete()
bool IsPartiallyComplete (void) const
This method indicates whether the Active Dataset is partially complete.
This method is primarily used to determine whether a user has supplied a partial Active Dataset for use with joining a network.
Return values
TRUE if an Active Dataset is saved but does not include an Active Timestamp.
FALSE if an Active Dataset is not saved or does include an Active Timestamp.
References DatasetLocal::IsSaved(), DatasetManager::mLocal, and DatasetManager::mTimestampValid.
IsCommissioned()
bool IsCommissioned (void) const
This method indicates whether or not a valid network is present in the Active Operational Dataset.
Return values
TRUE if a valid network is present in the Active Dataset.
FALSE if a valid network is not present in the Active Dataset.
References Dataset::Info::IsChannelPresent(), Dataset::Info::IsExtendedPanIdPresent(), Dataset::Info::IsNetworkKeyPresent(), Dataset::Info::IsNetworkNamePresent(), Dataset::Info::IsPanIdPresent(), DatasetManager::Read(), and SuccessOrExit.
Clear()
void Clear (void) inline
This method clears the Active Operational Dataset.
References DatasetManager::Clear().
Save() [1/4]
void Save (const Dataset & aDataset) inline
This method saves the Operational Dataset in non-volatile memory.
This method also reconfigures the Thread interface.
Parameters
[in] aDataset The Operational Dataset.
References IgnoreError(), and DatasetManager::Save().
Save() [2/4]
Error Save (const Timestamp & aTimestamp, const Message & aMessage, uint16_t aOffset, uint8_t aLength)
This method sets the Operational Dataset for the partition.
This method also reconfigures the Thread interface. This method also updates the non-volatile version if the partition's Operational Dataset is newer.
Parameters
[in] aTimestamp The timestamp for the Operational Dataset.
[in] aMessage The message buffer.
[in] aOffset The offset where the Operational Dataset begins.
[in] aLength The length of the Operational Dataset.
Return values
kErrorNone Successfully parsed the Dataset from the aMessage and saved it.
kErrorParse Could not parse the Dataset from aMessage.
References Dataset::kActive, ot::kErrorNone, Dataset::ReadFromMessage(), DatasetManager::Save(), Dataset::SetTimestamp(), and SuccessOrExit.
Save() [3/4]
Error Save (const Dataset::Info & aDatasetInfo) inline
This method sets the Operational Dataset in non-volatile memory.
Parameters
[in] aDatasetInfo The Operational Dataset as Dataset::Info.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References DatasetManager::Save().
Save() [4/4]
Error Save (const otOperationalDatasetTlvs & aDataset) inline
This method sets the Operational Dataset in non-volatile memory.
Parameters
[in] aDataset The Operational Dataset.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References Dataset::Info::GenerateRandom(), InstanceLocator::GetInstance(), DatasetManager::HandleTimer(), and DatasetManager::Save().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and ActiveDatasetManager::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) inline private
References DatasetManager::HandleGet(), and DatasetManager::HandleTimer().
Referenced by ActiveDatasetManager::HandleTimer().
HandleGet() [1/2]
void HandleGet (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References ot::AsCoapMessage(), and ot::AsCoreType().
HandleGet() [2/2]
void HandleGet (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) const private
References DatasetManager::HandleGet().
Field Documentation
mResourceGet
Coap::Resource mResourceGet private
Referenced by ActiveDatasetManager::ActiveDatasetManager().
The documentation for this class was generated from the following files:
dataset_manager.hpp
dataset_manager.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale