OpenThread: SubMac Class Reference
SubMac Class Reference
Core-mac
#include <sub_mac.hpp>
Data Structures
class Callbacks
Public Member Functions
Error Disable (void)
Error Enable (void)
Error EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
otRadioCaps GetCaps (void) const
const KeyMaterial & GetCurrentMacKey (void) const
const ExtAddress & GetExtAddress (void) const
uint32_t GetFrameCounter (void) const
const KeyMaterial & GetNextMacKey (void) const
int8_t GetNoiseFloor (void)
const KeyMaterial & GetPreviousMacKey (void) const
otRadioCaps GetRadioCaps (void) const
int8_t GetRssi (void) const
ShortAddress GetShortAddress (void) const
TxFrame & GetTransmitFrame (void)
uint8_t GetTransmitRetries (void) const
bool IsTransmittingOrScanning (void) const
Error Receive (uint8_t aChannel)
Error Send (void)
void SetExtAddress (const ExtAddress &aExtAddress)
void SetFrameCounter (uint32_t aFrameCounter)
void SetMacKey (uint8_t aKeyIdMode, uint8_t aKeyId, const KeyMaterial &aPrevKey, const KeyMaterial &aCurrKey, const KeyMaterial &aNextKey)
void SetPanId (PanId aPanId)
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void *aCallbackContext)
void SetRxOnWhenBackoff (bool aRxOnWhenBackoff)
void SetShortAddress (ShortAddress aShortAddress)
Error Sleep (void)
SubMac (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Static Public Attributes
static constexpr int8_t kInvalidRssiValue = 127
Invalid Received Signal Strength Indicator (RSSI) value.
Private Types
enum State : uint8_t {
kStateDisabled, kStateSleep, kStateReceive, kStateCsmaBackoff,
kStateTransmit, kStateEnergyScan
}
Private Member Functions
void BeginTransmit (void)
void HandleEnergyScanDone (int8_t aMaxRssi)
void HandleReceiveDone (RxFrame *aFrame, Error aError)
void HandleTimer (void)
void HandleTransmitDone (TxFrame &aFrame, RxFrame *aAckFrame, Error aError)
void HandleTransmitStarted (TxFrame &aFrame)
void Init (void)
void ProcessTransmitSecurity (void)
bool RadioSupportsAckTimeout (void) const
bool RadioSupportsCsmaBackoff (void) const
bool RadioSupportsEnergyScan (void) const
bool RadioSupportsReceiveTiming (void) const
bool RadioSupportsRetries (void) const
bool RadioSupportsTransmitSecurity (void) const
bool RadioSupportsTransmitTiming (void) const
void SampleRssi (void)
void SetState (State aState)
bool ShouldHandleAckTimeout (void) const
bool ShouldHandleCsmaBackOff (void) const
bool ShouldHandleEnergyScan (void) const
bool ShouldHandleRetries (void) const
bool ShouldHandleTransmitSecurity (void) const
bool ShouldHandleTransmitTargetTime (void) const
void SignalFrameCounterUsed (uint32_t aFrameCounter)
void SignalFrameCounterUsedOnTxDone (const TxFrame &aFrame)
void StartCsmaBackoff (void)
void StartTimerForBackoff (uint8_t aBackoffExponent)
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Static Private Member Functions
static void HandleTimer (Timer &aTimer)
static const char * StateToString (State aState)
Private Attributes
Callbacks mCallbacks
uint8_t mCsmaBackoffs
KeyMaterial mCurrKey
TimeMilli mEnergyScanEndTime
int8_t mEnergyScanMaxRssi
ExtAddress mExtAddress
uint32_t mFrameCounter
uint8_t mKeyId
KeyMaterial mNextKey
otLinkPcapCallback mPcapCallback
void * mPcapCallbackContext
KeyMaterial mPrevKey
otRadioCaps mRadioCaps
bool mRxOnWhenBackoff: 1
ShortAddress mShortAddress
State mState
TimerMilli mTimer
TxFrame & mTransmitFrame
uint8_t mTransmitRetries
Static Private Attributes
static constexpr uint32_t kAckTimeout = 16
static constexpr uint32_t kCcaSampleInterval = 128
static constexpr uint8_t kCsmaMaxBe = 5
static constexpr uint8_t kCsmaMinBe = 3
static constexpr uint32_t kEnergyScanRssiSampleInterval = 1
static constexpr uint32_t kUnitBackoffPeriod = 20
Friends
class LinkRaw
class Radio::Callbacks
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Detailed Description
This class implements the IEEE 802.15.4 MAC (sub-MAC).
Sub-MAC layer implements a subset of IEEE802.15.4 MAC primitives which are shared by both MAC layer (in FTD/MTD modes) and Raw Link (Radio only mode).
The sub-MAC layer handles the following (if not provided by radio platform):
Ack timeout for frame transmission,
CSMA backoff logic,
Frame re-transmissions,
Energy scan on a single channel and RSSI sampling.
It also act as the interface (to radio platform) for setting/getting radio configurations such as short or extended addresses and PAN Id.
Member Enumeration Documentation
State
enum State : uint8_t private
Enumerator
kStateDisabled
kStateSleep
kStateReceive
kStateCsmaBackoff
kStateTransmit
kStateEnergyScan
Constructor & Destructor Documentation
SubMac()
SubMac (Instance & aInstance) explicit
This constructor initializes the SubMac object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References SubMac::Init().
Member Function Documentation
GetRadioCaps()
otRadioCaps GetRadioCaps (void) const inline
This method gets the capabilities provided by platform radio.
Returns
The capability bit vector (see OT_RADIO_CAP_* definitions).
References SubMac::GetCaps(), SubMac::mRadioCaps, and SubMac::SetPanId().
GetCaps()
otRadioCaps GetCaps (void) const
This method gets the capabilities provided by SubMac layer.
Returns
The capability bit vector (see OT_RADIO_CAP_* definitions).
References SubMac::mRadioCaps, OT_RADIO_CAPS_ACK_TIMEOUT, OT_RADIO_CAPS_CSMA_BACKOFF, OT_RADIO_CAPS_ENERGY_SCAN, OT_RADIO_CAPS_RECEIVE_TIMING, OT_RADIO_CAPS_TRANSMIT_RETRIES, OT_RADIO_CAPS_TRANSMIT_SEC, and OT_RADIO_CAPS_TRANSMIT_TIMING.
Referenced by SubMac::GetRadioCaps().
SetPanId()
void SetPanId (PanId aPanId)
This method sets the PAN ID.
Parameters
[in] aPanId The PAN ID.
References LogDebg.
Referenced by SubMac::GetRadioCaps().
GetShortAddress()
ShortAddress GetShortAddress (void) const inline
This method gets the short address.
Returns
The short address.
References SubMac::mShortAddress, and SubMac::SetShortAddress().
SetShortAddress()
void SetShortAddress (ShortAddress aShortAddress)
This method sets the short address.
Parameters
[in] aShortAddress The short address.
References LogDebg, and SubMac::mShortAddress.
Referenced by SubMac::GetShortAddress().
GetExtAddress()
const ExtAddress& GetExtAddress (void) const inline
This function gets the extended address.
Returns
A reference to the extended address.
References SubMac::mExtAddress, SubMac::SetExtAddress(), and SubMac::SetPcapCallback().
Referenced by SubMac::ProcessTransmitSecurity().
SetExtAddress()
void SetExtAddress (const ExtAddress & aExtAddress)
This method sets extended address.
Parameters
[in] aExtAddress The extended address.
References String< kSize >::AsCString(), ExtAddress::kReverseByteOrder, LogDebg, otExtAddress::m8, SubMac::mExtAddress, ExtAddress::Set(), and ExtAddress::ToString().
Referenced by SubMac::GetExtAddress().
SetPcapCallback()
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void * aCallbackContext)
This method registers a callback to provide received packet capture for IEEE 802.15.4 frames.
Parameters
[in] aPcapCallback A pointer to a function that is called when receiving an IEEE 802.15.4 link frame or nullptr to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
References SubMac::mPcapCallback, and SubMac::mPcapCallbackContext.
Referenced by SubMac::GetExtAddress().
SetRxOnWhenBackoff()
void SetRxOnWhenBackoff (bool aRxOnWhenBackoff) inline
This method indicates whether radio should stay in Receive or Sleep during CSMA backoff.
Parameters
[in] aRxOnWhenBackoff TRUE to keep radio in Receive, FALSE to put to Sleep during CSMA backoff.
References SubMac::Disable(), SubMac::Enable(), SubMac::mRxOnWhenBackoff, and SubMac::Sleep().
Enable()
Error Enable (void)
This method enables the radio.
Return values
kErrorNone Successfully enabled.
kErrorFailed The radio could not be enabled.
References ot::kErrorNone, SubMac::kStateDisabled, SubMac::kStateSleep, SubMac::mState, SubMac::SetState(), SubMac::Sleep(), SuccessOrAssert, SuccessOrExit, and VerifyOrExit.
Referenced by SubMac::SetRxOnWhenBackoff().
Disable()
Error Disable (void)
This method disables the radio.
Return values
kErrorNone Successfully disabled the radio.
References SubMac::kStateDisabled, SubMac::mTimer, SubMac::SetState(), SubMac::Sleep(), TimerMilli::Stop(), and SuccessOrExit.
Referenced by SubMac::SetRxOnWhenBackoff().
Sleep()
Error Sleep (void)
This method transitions the radio to Sleep.
Return values
kErrorNone Successfully transitioned to Sleep.
kErrorBusy The radio was transmitting.
kErrorInvalidState The radio was disabled.
References ot::ErrorToString(), ExitNow, ot::kErrorNone, SubMac::kStateSleep, LogWarn, and SubMac::SetState().
Referenced by SubMac::Disable(), SubMac::Enable(), SubMac::Receive(), SubMac::SetRxOnWhenBackoff(), SubMac::StartTimerForBackoff(), and SubMac::StateToString().
IsTransmittingOrScanning()
bool IsTransmittingOrScanning (void) const inline
This method indicates whether the sub-mac is busy transmitting or scanning.
Return values
TRUE if the sub-mac is busy transmitting or scanning.
FALSE if the sub-mac is not busy transmitting or scanning.
References SubMac::kStateEnergyScan, SubMac::kStateTransmit, SubMac::mState, and SubMac::Receive().
Receive()
Error Receive (uint8_t aChannel)
This method transitions the radio to Receive.
Parameters
[in] aChannel The channel to use for receiving.
Return values
kErrorNone Successfully transitioned to Receive.
kErrorInvalidState The radio was disabled or transmitting.
References ot::ErrorToString(), ExitNow, IgnoreError(), ot::kErrorNone, SubMac::kStateReceive, LogWarn, SubMac::RadioSupportsReceiveTiming(), SubMac::SetState(), SubMac::Sleep(), and VerifyOrExit.
Referenced by SubMac::BeginTransmit(), SubMac::EnergyScan(), SubMac::HandleTimer(), SubMac::IsTransmittingOrScanning(), SubMac::StartTimerForBackoff(), and SubMac::StateToString().
GetTransmitFrame()
TxFrame& GetTransmitFrame (void) inline
This method gets the radio transmit frame.
Returns
The transmit frame.
References SubMac::mTransmitFrame, and SubMac::Send().
Send()
Error Send (void)
This method sends a prepared frame.
The frame should be placed in GetTransmitFrame() frame.
The SubMac layer handles Ack timeout, CSMA backoff, and frame retransmission.
Return values
kErrorNone Successfully started the frame transmission
kErrorInvalidState The radio was disabled or transmitting.
References ExitNow, Frame::GetAckRequest(), ot::kErrorInvalidState, ot::kErrorNoAck, ot::kErrorNone, SubMac::kStateCsmaBackoff, SubMac::kStateDisabled, SubMac::kStateEnergyScan, SubMac::kStateReceive, SubMac::kStateSleep, SubMac::kStateTransmit, SubMac::mCallbacks, SubMac::mCsmaBackoffs, SubMac::mState, SubMac::mTransmitFrame, SubMac::mTransmitRetries, OT_UNREACHABLE_CODE, SubMac::ProcessTransmitSecurity(), SubMac::StartCsmaBackoff(), and SubMac::Callbacks::TransmitDone().
Referenced by SubMac::GetTransmitFrame(), and Links::Links().
GetTransmitRetries()
uint8_t GetTransmitRetries (void) const inline
This method gets the number of transmit retries of last transmitted frame.
Returns
Number of transmit retries.
References SubMac::EnergyScan(), SubMac::GetNoiseFloor(), SubMac::GetRssi(), SubMac::mTransmitRetries, and SubMac::SetMacKey().
GetRssi()
int8_t GetRssi (void) const
This method gets the most recent RSSI measurement.
Returns
The RSSI in dBm when it is valid. kInvalidRssiValue when RSSI is invalid.
References SubMac::kInvalidRssiValue.
Referenced by SubMac::GetTransmitRetries(), and SubMac::SampleRssi().
EnergyScan()
Error EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
This method begins energy scan.
Parameters
[in] aScanChannel The channel to perform the energy scan on.
[in] aScanDuration The duration, in milliseconds, for the channel to be scanned.
Return values
kErrorNone Successfully started scanning the channel.
kErrorBusy The radio is performing energy scanning.
kErrorInvalidState The radio was disabled or transmitting.
kErrorNotImplemented Energy scan is not supported (applicable in link-raw/radio mode only).
References ExitNow, TimerMilli::GetNow(), SubMac::HandleEnergyScanDone(), IgnoreError(), ot::kErrorInvalidState, ot::kErrorNone, ot::kErrorNotImplemented, SubMac::kInvalidRssiValue, SubMac::kStateCsmaBackoff, SubMac::kStateDisabled, SubMac::kStateEnergyScan, SubMac::kStateReceive, SubMac::kStateSleep, SubMac::kStateTransmit, SubMac::mEnergyScanEndTime, SubMac::mEnergyScanMaxRssi, SubMac::mState, SubMac::mTimer, SubMac::RadioSupportsEnergyScan(), SubMac::Receive(), SubMac::SetState(), SubMac::ShouldHandleEnergyScan(), TimerMilli::Start(), SuccessOrAssert, and VerifyOrExit.
Referenced by SubMac::GetTransmitRetries().
GetNoiseFloor()
int8_t GetNoiseFloor (void)
This method returns the noise floor value (currently use the radio receive sensitivity value).
Returns
The noise floor value in dBm.
Referenced by SubMac::GetTransmitRetries().
SetMacKey()
void SetMacKey (uint8_t aKeyIdMode, uint8_t aKeyId, const KeyMaterial & aPrevKey, const KeyMaterial & aCurrKey, const KeyMaterial & aNextKey)
This method sets MAC keys and key index.
Parameters
[in] aKeyIdMode MAC key ID mode.
[in] aKeyId The key ID.
[in] aPrevKey The previous MAC key.
[in] aCurrKey The current MAC key.
[in] aNextKey The next MAC key.
References Frame::kKeyIdMode0, Frame::kKeyIdMode1, Frame::kKeyIdMode2, SubMac::mCurrKey, SubMac::mKeyId, SubMac::mNextKey, SubMac::mPrevKey, OT_ASSERT, SubMac::ShouldHandleTransmitSecurity(), and VerifyOrExit.
Referenced by SubMac::GetTransmitRetries().
GetCurrentMacKey()
const KeyMaterial& GetCurrentMacKey (void) const inline
This method returns a reference to the current MAC key.
Returns
A reference to the current MAC key.
References SubMac::mCurrKey.
Referenced by Mac::ProcessEnhAckSecurity(), and SubMac::ProcessTransmitSecurity().
GetPreviousMacKey()
const KeyMaterial& GetPreviousMacKey (void) const inline
This method returns a reference to the previous MAC key.
Returns
A reference to the previous MAC key.
References SubMac::mPrevKey.
Referenced by Mac::ProcessEnhAckSecurity().
GetNextMacKey()
const KeyMaterial& GetNextMacKey (void) const inline
This method returns a reference to the next MAC key.
Returns
A reference to the next MAC key.
References SubMac::mNextKey.
Referenced by Mac::ProcessEnhAckSecurity().
GetFrameCounter()
uint32_t GetFrameCounter (void) const inline
This method returns the current MAC frame counter value.
Returns
The current MAC frame counter value.
References SubMac::mFrameCounter, and SubMac::SetFrameCounter().
Referenced by SubMac::ProcessTransmitSecurity().
SetFrameCounter()
void SetFrameCounter (uint32_t aFrameCounter)
This method sets the current MAC Frame Counter value.
Parameters
[in] aFrameCounter The MAC Frame Counter value.
References SubMac::mFrameCounter, SubMac::ShouldHandleTransmitSecurity(), and VerifyOrExit.
Referenced by SubMac::GetFrameCounter().
Init()
void Init (void) private
This method initializes the states of the sub-MAC layer.
References Clearable< Type >::Clear(), KeyMaterial::Clear(), SubMac::kInvalidRssiValue, ot::Mac::kShortAddrInvalid, SubMac::kStateDisabled, SubMac::mCsmaBackoffs, SubMac::mCurrKey, SubMac::mEnergyScanEndTime, SubMac::mEnergyScanMaxRssi, SubMac::mExtAddress, SubMac::mFrameCounter, SubMac::mKeyId, SubMac::mNextKey, SubMac::mPrevKey, SubMac::mRxOnWhenBackoff, SubMac::mShortAddress, SubMac::mState, SubMac::mTimer, SubMac::mTransmitRetries, and TimerMilli::Stop().
Referenced by SubMac::SubMac().
RadioSupportsCsmaBackoff()
bool RadioSupportsCsmaBackoff (void) const inline private
References SubMac::mRadioCaps, OT_RADIO_CAPS_CSMA_BACKOFF, and OT_RADIO_CAPS_TRANSMIT_RETRIES.
Referenced by SubMac::ShouldHandleCsmaBackOff().
RadioSupportsTransmitSecurity()
bool RadioSupportsTransmitSecurity (void) const inline private
References SubMac::mRadioCaps, and OT_RADIO_CAPS_TRANSMIT_SEC.
Referenced by SubMac::ShouldHandleTransmitSecurity().
RadioSupportsRetries()
bool RadioSupportsRetries (void) const inline private
References SubMac::mRadioCaps, and OT_RADIO_CAPS_TRANSMIT_RETRIES.
Referenced by SubMac::ShouldHandleRetries().
RadioSupportsAckTimeout()
bool RadioSupportsAckTimeout (void) const inline private
References SubMac::mRadioCaps, and OT_RADIO_CAPS_ACK_TIMEOUT.
Referenced by SubMac::ShouldHandleAckTimeout().
RadioSupportsEnergyScan()
bool RadioSupportsEnergyScan (void) const inline private
References SubMac::mRadioCaps, and OT_RADIO_CAPS_ENERGY_SCAN.
Referenced by SubMac::EnergyScan(), SubMac::SampleRssi(), and SubMac::ShouldHandleEnergyScan().
RadioSupportsTransmitTiming()
bool RadioSupportsTransmitTiming (void) const inline private
References SubMac::mRadioCaps, and OT_RADIO_CAPS_TRANSMIT_TIMING.
Referenced by SubMac::ShouldHandleTransmitTargetTime().
RadioSupportsReceiveTiming()
bool RadioSupportsReceiveTiming (void) const inline private
References SubMac::BeginTransmit(), SubMac::HandleEnergyScanDone(), SubMac::HandleReceiveDone(), SubMac::HandleTimer(), SubMac::HandleTransmitDone(), SubMac::HandleTransmitStarted(), SubMac::mRadioCaps, OT_RADIO_CAPS_RECEIVE_TIMING, SubMac::ProcessTransmitSecurity(), SubMac::SampleRssi(), SubMac::SetState(), SubMac::ShouldHandleAckTimeout(), SubMac::ShouldHandleCsmaBackOff(), SubMac::ShouldHandleEnergyScan(), SubMac::ShouldHandleRetries(), SubMac::ShouldHandleTransmitSecurity(), SubMac::ShouldHandleTransmitTargetTime(), SubMac::SignalFrameCounterUsed(), SubMac::SignalFrameCounterUsedOnTxDone(), SubMac::StartCsmaBackoff(), SubMac::StartTimerForBackoff(), and SubMac::StateToString().
Referenced by SubMac::Receive(), and SubMac::StateToString().
ShouldHandleTransmitSecurity()
bool ShouldHandleTransmitSecurity (void) const private
References OPENTHREAD_CONFIG_MAC_SOFTWARE_TX_SECURITY_ENABLE, SubMac::RadioSupportsTransmitSecurity(), and VerifyOrExit.
Referenced by SubMac::HandleReceiveDone(), SubMac::ProcessTransmitSecurity(), SubMac::RadioSupportsReceiveTiming(), SubMac::SetFrameCounter(), SubMac::SetMacKey(), and SubMac::SignalFrameCounterUsedOnTxDone().
ShouldHandleCsmaBackOff()
bool ShouldHandleCsmaBackOff (void) const private
References OPENTHREAD_CONFIG_MAC_SOFTWARE_CSMA_BACKOFF_ENABLE, SubMac::RadioSupportsCsmaBackoff(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitDone(), SubMac::RadioSupportsReceiveTiming(), and SubMac::StartCsmaBackoff().
ShouldHandleAckTimeout()
bool ShouldHandleAckTimeout (void) const private
References OPENTHREAD_CONFIG_MAC_SOFTWARE_ACK_TIMEOUT_ENABLE, SubMac::RadioSupportsAckTimeout(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitStarted(), and SubMac::RadioSupportsReceiveTiming().
ShouldHandleRetries()
bool ShouldHandleRetries (void) const private
References OPENTHREAD_CONFIG_MAC_SOFTWARE_RETRANSMIT_ENABLE, SubMac::RadioSupportsRetries(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitDone(), and SubMac::RadioSupportsReceiveTiming().
ShouldHandleEnergyScan()
bool ShouldHandleEnergyScan (void) const private
References OPENTHREAD_CONFIG_MAC_SOFTWARE_ENERGY_SCAN_ENABLE, SubMac::RadioSupportsEnergyScan(), and VerifyOrExit.
Referenced by SubMac::EnergyScan(), and SubMac::RadioSupportsReceiveTiming().
ShouldHandleTransmitTargetTime()
bool ShouldHandleTransmitTargetTime (void) const private
References OPENTHREAD_CONFIG_MAC_SOFTWARE_TX_TIMING_ENABLE, SubMac::RadioSupportsTransmitTiming(), and VerifyOrExit.
Referenced by SubMac::RadioSupportsReceiveTiming(), and SubMac::StartCsmaBackoff().
ProcessTransmitSecurity()
void ProcessTransmitSecurity (void) private
References SubMac::GetCurrentMacKey(), SubMac::GetExtAddress(), SubMac::GetFrameCounter(), Frame::GetKeyIdMode(), Frame::GetSecurityEnabled(), TxFrame::IsHeaderUpdated(), TxFrame::IsSecurityProcessed(), Frame::kKeyIdMode1, SubMac::mKeyId, SubMac::mTransmitFrame, TxFrame::ProcessTransmitAesCcm(), TxFrame::SetAesKey(), Frame::SetFrameCounter(), Frame::SetKeyId(), SubMac::ShouldHandleTransmitSecurity(), SubMac::SignalFrameCounterUsed(), SuccessOrExit, and VerifyOrExit.
Referenced by SubMac::RadioSupportsReceiveTiming(), and SubMac::Send().
SignalFrameCounterUsed()
void SignalFrameCounterUsed (uint32_t aFrameCounter) private
References SubMac::Callbacks::FrameCounterUsed(), SubMac::mCallbacks, SubMac::mFrameCounter, and VerifyOrExit.
Referenced by SubMac::HandleReceiveDone(), SubMac::ProcessTransmitSecurity(), SubMac::RadioSupportsReceiveTiming(), and SubMac::SignalFrameCounterUsedOnTxDone().
StartCsmaBackoff()
void StartCsmaBackoff (void) private
References SubMac::BeginTransmit(), ExitNow, InstanceLocator::GetInstance(), SubMac::kCcaSampleInterval, SubMac::kCsmaMaxBe, SubMac::kCsmaMinBe, SubMac::kStateCsmaBackoff, SubMac::mCsmaBackoffs, otRadioFrame::mInfo, SubMac::mTimer, SubMac::mTransmitFrame, otRadioFrame::mTxInfo, otPlatRadioGetNow(), SubMac::SetState(), SubMac::ShouldHandleCsmaBackOff(), SubMac::ShouldHandleTransmitTargetTime(), TimerMilli::StartAt(), SubMac::StartTimerForBackoff(), and VerifyOrExit.
Referenced by SubMac::HandleTimer(), SubMac::HandleTransmitDone(), SubMac::RadioSupportsReceiveTiming(), and SubMac::Send().
StartTimerForBackoff()
void StartTimerForBackoff (uint8_t aBackoffExponent) private
References Frame::GetChannel(), ot::Random::NonCrypto::GetUint32InRange(), IgnoreError(), Radio::kSymbolTime, SubMac::kUnitBackoffPeriod, LogDebg, SubMac::mRxOnWhenBackoff, SubMac::mState, SubMac::mTimer, SubMac::mTransmitFrame, SubMac::Receive(), SubMac::Sleep(), and TimerMilli::Start().
Referenced by SubMac::HandleTransmitDone(), SubMac::RadioSupportsReceiveTiming(), and SubMac::StartCsmaBackoff().
BeginTransmit()
void BeginTransmit (void) private
References Frame::GetChannel(), ot::kErrorInvalidState, SubMac::kStateCsmaBackoff, SubMac::kStateTransmit, otRadioFrame::mInfo, SubMac::mPcapCallback, SubMac::mPcapCallbackContext, SubMac::mRadioCaps, SubMac::mState, SubMac::mTransmitFrame, otRadioFrame::mTxInfo, OT_RADIO_CAPS_SLEEP_TO_TX, SubMac::Receive(), SubMac::SetState(), SuccessOrAssert, and VerifyOrExit.
Referenced by SubMac::HandleTimer(), SubMac::RadioSupportsReceiveTiming(), and SubMac::StartCsmaBackoff().
SampleRssi()
void SampleRssi (void) private
References Timer::GetFireTime(), TimerMilli::GetNow(), SubMac::GetRssi(), SubMac::HandleEnergyScanDone(), SubMac::kEnergyScanRssiSampleInterval, SubMac::kInvalidRssiValue, SubMac::mEnergyScanEndTime, SubMac::mEnergyScanMaxRssi, SubMac::mTimer, OT_ASSERT, SubMac::RadioSupportsEnergyScan(), and TimerMilli::StartAt().
Referenced by SubMac::HandleTimer(), and SubMac::RadioSupportsReceiveTiming().
HandleReceiveDone()
void HandleReceiveDone (RxFrame * aFrame, Error aError) private
References ot::kErrorNone, LogDebg, SubMac::mCallbacks, otRadioFrame::mInfo, SubMac::mPcapCallback, SubMac::mPcapCallbackContext, otRadioFrame::mRxInfo, SubMac::mState, SubMac::Callbacks::ReceiveDone(), SubMac::ShouldHandleTransmitSecurity(), SubMac::SignalFrameCounterUsed(), and SubMac::StateToString().
Referenced by SubMac::RadioSupportsReceiveTiming().
HandleTransmitStarted()
void HandleTransmitStarted (TxFrame & aFrame) private
References Frame::GetAckRequest(), SubMac::kAckTimeout, SubMac::mTimer, SubMac::ShouldHandleAckTimeout(), and TimerMilli::Start().
Referenced by SubMac::RadioSupportsReceiveTiming().
HandleTransmitDone()
void HandleTransmitDone (TxFrame & aFrame, RxFrame * aAckFrame, Error aError) private
References ExitNow, Frame::GetChannel(), InstanceLocator::GetInstance(), TxFrame::GetMaxCsmaBackoffs(), TxFrame::GetMaxFrameRetries(), TxFrame::IsCsmaCaEnabled(), ot::kErrorAbort, ot::kErrorChannelAccessFailure, ot::kErrorNoAck, ot::kErrorNone, SubMac::kStateReceive, SubMac::mCallbacks, SubMac::mCsmaBackoffs, ot::Min(), SubMac::mTimer, SubMac::mTransmitRetries, OT_ASSERT, OT_FALL_THROUGH, OT_UNREACHABLE_CODE, otPlatRadioGetNow(), SubMac::Callbacks::RecordCcaStatus(), SubMac::Callbacks::RecordFrameTransmitStatus(), TxFrame::SetIsARetransmission(), SubMac::SetState(), SubMac::ShouldHandleCsmaBackOff(), SubMac::ShouldHandleRetries(), SubMac::SignalFrameCounterUsedOnTxDone(), SubMac::StartCsmaBackoff(), SubMac::StartTimerForBackoff(), TimerMilli::Stop(), and SubMac::Callbacks::TransmitDone().
Referenced by SubMac::Callbacks::Callbacks(), SubMac::HandleTimer(), and SubMac::RadioSupportsReceiveTiming().
SignalFrameCounterUsedOnTxDone()
void SignalFrameCounterUsedOnTxDone (const TxFrame & aFrame) private
References Frame::GetFrameCounter(), Frame::GetKeyIdMode(), Frame::GetSecurityEnabled(), TxFrame::IsHeaderUpdated(), ot::kErrorNone, Frame::kKeyIdMode1, OT_ASSERT, OT_UNUSED_VARIABLE, SubMac::ShouldHandleTransmitSecurity(), SubMac::SignalFrameCounterUsed(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitDone(), and SubMac::RadioSupportsReceiveTiming().
HandleEnergyScanDone()
void HandleEnergyScanDone (int8_t aMaxRssi) private
References SubMac::Callbacks::EnergyScanDone(), SubMac::kStateReceive, SubMac::mCallbacks, and SubMac::SetState().
Referenced by SubMac::EnergyScan(), SubMac::RadioSupportsReceiveTiming(), and SubMac::SampleRssi().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and SubMac::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References SubMac::BeginTransmit(), Frame::GetChannel(), SubMac::HandleTransmitDone(), IgnoreError(), ot::kErrorNoAck, SubMac::kStateCsmaBackoff, SubMac::kStateEnergyScan, SubMac::kStateTransmit, LogDebg, SubMac::mState, SubMac::mTransmitFrame, SubMac::Receive(), SubMac::SampleRssi(), and SubMac::StartCsmaBackoff().
Referenced by SubMac::HandleTimer(), and SubMac::RadioSupportsReceiveTiming().
SetState()
void SetState (State aState) private
References LogDebg, SubMac::mState, and SubMac::StateToString().
Referenced by SubMac::BeginTransmit(), SubMac::Disable(), SubMac::Enable(), SubMac::EnergyScan(), SubMac::HandleEnergyScanDone(), SubMac::HandleTransmitDone(), SubMac::RadioSupportsReceiveTiming(), SubMac::Receive(), SubMac::Sleep(), and SubMac::StartCsmaBackoff().
StateToString()
const char * StateToString (State aState) static private
References GetProvider< InstanceGetProvider >::Get(), InstanceLocator::GetInstance(), IgnoreError(), SubMac::kStateCsmaBackoff, SubMac::kStateDisabled, SubMac::kStateEnergyScan, SubMac::kStateReceive, SubMac::kStateSleep, SubMac::kStateTransmit, ot::kUsPerTenSymbols, LogDebg, SubMac::mState, otPlatRadioGetNow(), SubMac::RadioSupportsReceiveTiming(), SubMac::Receive(), SubMac::Sleep(), and VerifyOrExit.
Referenced by SubMac::HandleReceiveDone(), SubMac::RadioSupportsReceiveTiming(), and SubMac::SetState().
Friends And Related Function Documentation
Radio::Callbacks
friend class Radio::Callbacks friend
LinkRaw
friend class LinkRaw friend
Field Documentation
kInvalidRssiValue
constexpr int8_t kInvalidRssiValue = 127 static
Invalid Received Signal Strength Indicator (RSSI) value.
Referenced by SubMac::EnergyScan(), SubMac::GetRssi(), SubMac::Init(), and SubMac::SampleRssi().
kCsmaMinBe
constexpr uint8_t kCsmaMinBe = 3 static private
Referenced by SubMac::StartCsmaBackoff().
kCsmaMaxBe
constexpr uint8_t kCsmaMaxBe = 5 static private
Referenced by SubMac::StartCsmaBackoff().
kUnitBackoffPeriod
constexpr uint32_t kUnitBackoffPeriod = 20 static private
Referenced by SubMac::StartTimerForBackoff().
kAckTimeout
constexpr uint32_t kAckTimeout = 16 static private
Referenced by SubMac::HandleTransmitStarted().
kCcaSampleInterval
constexpr uint32_t kCcaSampleInterval = 128 static private
Referenced by SubMac::StartCsmaBackoff().
kEnergyScanRssiSampleInterval
constexpr uint32_t kEnergyScanRssiSampleInterval = 1 static private
Referenced by SubMac::SampleRssi().
mRadioCaps
otRadioCaps mRadioCaps private
Referenced by SubMac::BeginTransmit(), SubMac::GetCaps(), SubMac::GetRadioCaps(), SubMac::RadioSupportsAckTimeout(), SubMac::RadioSupportsCsmaBackoff(), SubMac::RadioSupportsEnergyScan(), SubMac::RadioSupportsReceiveTiming(), SubMac::RadioSupportsRetries(), SubMac::RadioSupportsTransmitSecurity(), and SubMac::RadioSupportsTransmitTiming().
mState
State mState private
Referenced by SubMac::BeginTransmit(), SubMac::Enable(), SubMac::EnergyScan(), SubMac::HandleReceiveDone(), SubMac::HandleTimer(), SubMac::Init(), SubMac::IsTransmittingOrScanning(), SubMac::Send(), SubMac::SetState(), SubMac::StartTimerForBackoff(), and SubMac::StateToString().
mCsmaBackoffs
uint8_t mCsmaBackoffs private
Referenced by SubMac::HandleTransmitDone(), SubMac::Init(), SubMac::Send(), and SubMac::StartCsmaBackoff().
mTransmitRetries
uint8_t mTransmitRetries private
Referenced by SubMac::GetTransmitRetries(), SubMac::HandleTransmitDone(), SubMac::Init(), and SubMac::Send().
mShortAddress
ShortAddress mShortAddress private
Referenced by SubMac::GetShortAddress(), SubMac::Init(), and SubMac::SetShortAddress().
mExtAddress
ExtAddress mExtAddress private
Referenced by SubMac::GetExtAddress(), SubMac::Init(), and SubMac::SetExtAddress().
mRxOnWhenBackoff
bool mRxOnWhenBackoff private
Referenced by SubMac::Init(), SubMac::SetRxOnWhenBackoff(), and SubMac::StartTimerForBackoff().
mEnergyScanMaxRssi
int8_t mEnergyScanMaxRssi private
Referenced by SubMac::EnergyScan(), SubMac::Init(), and SubMac::SampleRssi().
mEnergyScanEndTime
TimeMilli mEnergyScanEndTime private
Referenced by SubMac::EnergyScan(), SubMac::Init(), and SubMac::SampleRssi().
mTransmitFrame
TxFrame& mTransmitFrame private
Referenced by SubMac::BeginTransmit(), SubMac::GetTransmitFrame(), SubMac::HandleTimer(), SubMac::ProcessTransmitSecurity(), SubMac::Send(), SubMac::StartCsmaBackoff(), and SubMac::StartTimerForBackoff().
mCallbacks
Callbacks mCallbacks private
Referenced by SubMac::HandleEnergyScanDone(), SubMac::HandleReceiveDone(), SubMac::HandleTransmitDone(), SubMac::Send(), and SubMac::SignalFrameCounterUsed().
mPcapCallback
otLinkPcapCallback mPcapCallback private
Referenced by SubMac::BeginTransmit(), SubMac::HandleReceiveDone(), and SubMac::SetPcapCallback().
mPcapCallbackContext
void* mPcapCallbackContext private
Referenced by SubMac::BeginTransmit(), SubMac::HandleReceiveDone(), and SubMac::SetPcapCallback().
mPrevKey
KeyMaterial mPrevKey private
Referenced by SubMac::GetPreviousMacKey(), SubMac::Init(), and SubMac::SetMacKey().
mCurrKey
KeyMaterial mCurrKey private
Referenced by SubMac::GetCurrentMacKey(), SubMac::Init(), and SubMac::SetMacKey().
mNextKey
KeyMaterial mNextKey private
Referenced by SubMac::GetNextMacKey(), SubMac::Init(), and SubMac::SetMacKey().
mFrameCounter
uint32_t mFrameCounter private
Referenced by SubMac::GetFrameCounter(), SubMac::Init(), SubMac::SetFrameCounter(), and SubMac::SignalFrameCounterUsed().
mKeyId
uint8_t mKeyId private
Referenced by SubMac::Init(), SubMac::ProcessTransmitSecurity(), and SubMac::SetMacKey().
mTimer
TimerMilli mTimer private
Referenced by SubMac::Disable(), SubMac::EnergyScan(), SubMac::HandleTransmitDone(), SubMac::HandleTransmitStarted(), SubMac::Init(), SubMac::SampleRssi(), SubMac::StartCsmaBackoff(), and SubMac::StartTimerForBackoff().
The documentation for this class was generated from the following files:
sub_mac.hpp
sub_mac.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale