OpenThread: DatasetLocal Class Reference
DatasetLocal Class Reference
#include <dataset_local.hpp>
Public Member Functions
void Clear (void)
DatasetLocal (Instance &aInstance, Dataset::Type aType)
const Timestamp * GetTimestamp (void) const
Dataset::Type GetType (void) const
TimeMilli GetUpdateTime (void) const
bool IsSaved (void) const
bool IsTimestampPresent (void) const
Error Read (Dataset &aDataset) const
Error Read (Dataset::Info &aDatasetInfo) const
Error Read (otOperationalDatasetTlvs &aDataset) const
Error Restore (Dataset &aDataset)
Error Save (const Dataset::Info &aDatasetInfo)
Error Save (const otOperationalDatasetTlvs &aDataset)
Error Save (const Dataset &aDataset)
Public Member Functions inherited from InstanceLocator
Instance & GetInstance (void) const
Public Member Functions inherited from GetProvider< InstanceLocator >
Type & Get (void) const
Private Member Functions
bool IsActive (void) const
void SetTimestamp (const Dataset &aDataset)
Private Attributes
bool mSaved: 1
Whether a dataset is saved in non-volatile.
Timestamp mTimestamp
Active or Pending Timestamp.
bool mTimestampPresent: 1
Whether a timestamp is present.
Dataset::Type mType
Active or Pending.
TimeMilli mUpdateTime
Local time last updated.
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from GetProvider< InstanceLocator >
GetProvider (void)=default
Constructor & Destructor Documentation
DatasetLocal()
DatasetLocal (Instance & aInstance, Dataset::Type aType)
This constructor initializes the object.
Parameters
[in] aInstance A reference to an OpenThread instance.
[in] aType The type of the dataset, active or pending.
References Clearable< Type >::Clear(), and DatasetLocal::mTimestamp.
Member Function Documentation
GetType()
Dataset::Type GetType (void) const inline
This method indicates whether this is an Active or Pending Dataset.
Returns
The Dataset type.
References DatasetLocal::Clear(), and DatasetLocal::mType.
Referenced by DatasetManager::GetType(), DatasetLocal::Save(), and DatasetManager::SignalDatasetChange().
Clear()
void Clear (void)
This method clears the Dataset.
References Clearable< Type >::Clear(), IgnoreError(), DatasetLocal::mSaved, DatasetLocal::mTimestamp, DatasetLocal::mTimestampPresent, and DatasetLocal::mType.
Referenced by DatasetManager::Clear(), and DatasetLocal::GetType().
IsSaved()
bool IsSaved (void) const inline
This method indicates whether an Active or Pending Dataset is saved in non-volatile memory.
Return values
TRUE if an Active or Pending Dataset is saved in non-volatile memory.
FALSE if an Active or Pending Dataset is not saved in non-volatile memory.
References DatasetLocal::mSaved.
Referenced by ActiveDatasetManager::IsPartiallyComplete().
IsTimestampPresent()
bool IsTimestampPresent (void) const inline
This method indicates whether an Active (Pending) Timestamp is present in the Active (Pending) Dataset.
Return values
TRUE if an Active/Pending Timestamp is present.
FALSE if an Active/Pending Timestamp is not present.
References DatasetLocal::mTimestampPresent.
GetTimestamp()
const Timestamp* GetTimestamp (void) const inline
This method returns a pointer to the Timestamp or nullptr when it is not present in the Dataset.
Returns
A pointer to the Timestamp or nullptr if timestamp is not present in the Dataset.
References DatasetLocal::mTimestamp, DatasetLocal::mTimestampPresent, DatasetLocal::Read(), and DatasetLocal::Restore().
Referenced by DatasetManager::Save(), and DatasetManager::SendSet().
Restore()
Error Restore (Dataset & aDataset)
This method restores and retrieves the dataset from non-volatile memory.
This method also sets the memory-cached timestamp for subsequent calls to Compare().
Parameters
[out] aDataset Where to place the dataset.
Return values
kErrorNone Successfully retrieved the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References Dataset::GetTimestamp(), ot::kErrorNone, DatasetLocal::mSaved, DatasetLocal::mTimestamp, DatasetLocal::mTimestampPresent, DatasetLocal::mType, DatasetLocal::Read(), and SuccessOrExit.
Referenced by DatasetLocal::GetTimestamp(), and DatasetManager::Restore().
Read() [1/3]
Error Read (Dataset & aDataset) const
This method retrieves the dataset from non-volatile memory.
Parameters
[out] aDataset Where to place the dataset.
Return values
kErrorNone Successfully retrieved the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References DelayTimerTlv::GetDelayTimer(), TimerMilli::GetNow(), Dataset::GetTlv(), Dataset::kActive, Tlv::kDelayTimer, ot::kErrorNone, Tlv::kPendingTimestamp, DatasetLocal::mType, DatasetLocal::mUpdateTime, Dataset::mUpdateTime, Dataset::RemoveTlv(), DelayTimerTlv::SetDelayTimer(), and VerifyOrExit.
Referenced by DatasetLocal::GetTimestamp(), DatasetManager::Read(), DatasetLocal::Read(), and DatasetLocal::Restore().
Read() [2/3]
Error Read (Dataset::Info & aDatasetInfo) const
This method retrieves the dataset from non-volatile memory.
Parameters
[out] aDatasetInfo Where to place the dataset as Dataset::Info.
Return values
kErrorNone Successfully retrieved the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References Clearable< Type >::Clear(), Dataset::ConvertTo(), DatasetLocal::Read(), and SuccessOrExit.
Read() [3/3]
Error Read (otOperationalDatasetTlvs & aDataset) const
This method retrieves the dataset from non-volatile memory.
Parameters
[out] aDataset Where to place the dataset.
Return values
kErrorNone Successfully retrieved the dataset.
kErrorNotFound There is no corresponding dataset stored in non-volatile memory.
References Dataset::ConvertTo(), DatasetLocal::Read(), and SuccessOrExit.
GetUpdateTime()
TimeMilli GetUpdateTime (void) const inline
This method returns the local time this dataset was last updated or restored.
Returns
The local time this dataset was last updated or restored.
References DatasetLocal::mUpdateTime, and DatasetLocal::Save().
Save() [1/3]
Error Save (const Dataset::Info & aDatasetInfo)
This method stores the dataset into non-volatile memory.
Parameters
[in] aDatasetInfo The Dataset to save as Dataset::Info.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References Dataset::SetFrom(), and SuccessOrExit.
Referenced by DatasetLocal::GetUpdateTime(), DatasetLocal::Save(), DatasetManager::Save(), and DatasetManager::SaveLocal().
Save() [2/3]
Error Save (const otOperationalDatasetTlvs & aDataset)
This method stores the dataset into non-volatile memory.
Parameters
[in] aDataset The Dataset to save as otOperationalDatasetTlvs.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References DatasetLocal::Save(), and Dataset::SetFrom().
Save() [3/3]
Error Save (const Dataset & aDataset)
This method stores the dataset into non-volatile memory.
Parameters
[in] aDataset The Dataset to save.
Return values
kErrorNone Successfully saved the dataset.
kErrorNotImplemented The platform does not implement settings functionality.
References Clearable< Type >::Clear(), NetworkKeyTlv::GetNetworkKey(), TimerMilli::GetNow(), Dataset::GetSize(), Dataset::GetTimestamp(), Dataset::GetTlv(), DatasetLocal::GetType(), IgnoreError(), DatasetLocal::IsActive(), ot::kErrorNone, NetworkKey::kSize, Pskc::kSize, LogInfo, otNetworkKey::m8, otPskc::m8, DatasetLocal::mSaved, DatasetLocal::mTimestamp, DatasetLocal::mTimestampPresent, DatasetLocal::mType, DatasetLocal::mUpdateTime, OT_ASSERT, Dataset::Set(), NetworkKeyTlv::SetNetworkKey(), SuccessOrAssert, SuccessOrExit, and Dataset::TypeToString().
IsActive()
bool IsActive (void) const inline private
References Dataset::kActive, DatasetLocal::mType, and DatasetLocal::SetTimestamp().
Referenced by DatasetLocal::Save().
SetTimestamp()
void SetTimestamp (const Dataset & aDataset) private
Referenced by DatasetLocal::IsActive().
Field Documentation
mTimestamp
Timestamp mTimestamp private
Active or Pending Timestamp.
Referenced by DatasetLocal::Clear(), DatasetLocal::DatasetLocal(), DatasetLocal::GetTimestamp(), DatasetLocal::Restore(), and DatasetLocal::Save().
mUpdateTime
TimeMilli mUpdateTime private
Local time last updated.
Referenced by DatasetLocal::GetUpdateTime(), DatasetLocal::Read(), and DatasetLocal::Save().
mType
Dataset::Type mType private
Active or Pending.
Referenced by DatasetLocal::Clear(), DatasetLocal::GetType(), DatasetLocal::IsActive(), DatasetLocal::Read(), DatasetLocal::Restore(), and DatasetLocal::Save().
mTimestampPresent
bool mTimestampPresent private
Whether a timestamp is present.
Referenced by DatasetLocal::Clear(), DatasetLocal::GetTimestamp(), DatasetLocal::IsTimestampPresent(), DatasetLocal::Restore(), and DatasetLocal::Save().
mSaved
bool mSaved private
Whether a dataset is saved in non-volatile.
Referenced by DatasetLocal::Clear(), DatasetLocal::IsSaved(), DatasetLocal::Restore(), and DatasetLocal::Save().
The documentation for this class was generated from the following files:
dataset_local.hpp
dataset_local.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale