OpenThread: Block Class Reference
Block Class Reference
#include <heap.hpp>
Public Member Functions
uint16_t GetLeftNext (void) const
uint16_t GetNext (void) const
void * GetPointer (void)
uint16_t GetSize (void) const
bool IsFree (void) const
bool IsLeftFree (void) const
void SetNext (uint16_t aNext)
void SetSize (uint16_t aSize)
Private Attributes
uint8_t mMemory [sizeof(uint16_t)]
uint16_t mSize
Static Private Attributes
static constexpr uint16_t kGuardBlockSize = 0xffff
Friends
class Heap
Detailed Description
This class represents a memory block.
A block is of the structure as below.
+------------------------------+
| mSize   |  mMemory |  mNext  |
|---------|----------| --------|
| 2 bytes |  n bytes | 2 bytes |
+------------------------------+
Since block metadata is of 4-byte size, mSize and mNext are separated at the beginning and end of the block to make sure the mMemory is aligned with long.
Member Function Documentation
GetSize()
uint16_t GetSize (void) const inline
This method returns the size of this block.
Returns
Size of this block.
References Block::mSize.
Referenced by Heap::BlockInsert(), Heap::BlockRight(), Heap::CAlloc(), Heap::Free(), and Heap::IsClean().
SetSize()
void SetSize (uint16_t aSize) inline
This method updates the size of this block.
Parameters
[in] aSize Size of this block in bytes.
References Block::mSize.
Referenced by Heap::CAlloc(), Heap::Free(), and Heap::Heap().
GetNext()
uint16_t GetNext (void) const inline
This method returns the offset of the free block after this block.
Note
This offset is relative to the start of the heap.
Returns
Offset of the next free block in bytes.
Return values
0 This block is not free.
References Block::mSize.
Referenced by Heap::BlockInsert(), Heap::BlockNext(), Heap::BlockPrev(), Heap::CAlloc(), Heap::Free(), Heap::IsClean(), and Block::IsFree().
SetNext()
void SetNext (uint16_t aNext) inline
This method updates the offset of the free block after this block.
Note
This offset aNext must be relative to the start of the heap.
Parameters
[in] aNext Offset of the next free block in bytes.
References Block::mSize.
Referenced by Heap::BlockInsert(), Heap::CAlloc(), Heap::Free(), and Heap::Heap().
GetPointer()
void* GetPointer (void) inline
This method returns the pointer to the start of the memory for user.
Return values
Pointer to the user memory. The pointer address is aligned to sizeof(long).
References Block::mMemory.
Referenced by Heap::CAlloc().
GetLeftNext()
uint16_t GetLeftNext (void) const inline
This method returns the offset of the free block after the left neighbor block.
Returns
Offset in bytes.
References Block::mSize.
Referenced by Heap::Free(), and Block::IsLeftFree().
IsLeftFree()
bool IsLeftFree (void) const inline
This method returns whether the left neighbor block is a free block.
Return values
true The left neighbor block is free.
false The left neighbor block is not free.
References Block::GetLeftNext().
Referenced by Heap::IsLeftFree().
IsFree()
bool IsFree (void) const inline
This method returns whether the current block is a free block.
Return values
true The block is free.
false The block is not free.
References Block::GetNext(), Block::kGuardBlockSize, and Block::mSize.
Referenced by Heap::CAlloc(), and Heap::Free().
Friends And Related Function Documentation
Heap
friend class Heap friend
Field Documentation
kGuardBlockSize
constexpr uint16_t kGuardBlockSize = 0xffff static private
Referenced by Heap::Heap(), and Block::IsFree().
mSize
uint16_t mSize private
Referenced by Block::GetLeftNext(), Block::GetNext(), Block::GetSize(), Block::IsFree(), Block::SetNext(), and Block::SetSize().
mMemory
uint8_t mMemory[sizeof(uint16_t)] private
Referenced by Block::GetPointer().
The documentation for this class was generated from the following file:
utils/heap.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale