OpenThread: MbedTls Class Reference
MbedTls Class Reference
Core-security
#include <mbedtls.hpp>
Public Member Functions
MbedTls (void)
Static Public Member Functions
static int CryptoSecurePrng (void *aContext, unsigned char *aBuffer, size_t aSize)
static Error MapError (int aMbedTlsError)
Additional Inherited Members
Private Member Functions inherited from NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (void)=default
Detailed Description
This class implements mbedTLS memory.
Constructor & Destructor Documentation
MbedTls()
MbedTls (void)
This constructor initializes the object.
References ot::Heap::CAlloc(), ot::Heap::Free(), and OPENTHREAD_CONFIG_LOG_LEVEL.
Member Function Documentation
MapError()
Error MapError (int aMbedTlsError) static
This method converts an mbed TLS error to OpenThread error.
Parameters
[in] aMbedTlsError The mbed TLS error.
Returns
The mapped Error.
References ot::kErrorBusy, ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNotCapable, and ot::kErrorSecurity.
Referenced by otPlatCryptoRandomGet().
CryptoSecurePrng()
int CryptoSecurePrng (void * aContext, unsigned char * aBuffer, size_t aSize) static
This function fills a given buffer with cryptographically secure random bytes.
Parameters
[in] aContext A pointer to arbitrary context.
[out] aBuffer A pointer to a buffer to fill with the random bytes.
[in] aSize Size of buffer (number of bytes to fill).
Return values
kErrorNone Successfully filled buffer with random values.
References ot::Random::Crypto::FillBuffer(), and IgnoreError().
The documentation for this class was generated from the following files:
mbedtls.hpp
mbedtls.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale