OpenThread: OutputBase Class Reference
OutputBase Class Reference
#include <cli_output.hpp>
Data Structures
struct CommandEntry
Public Types
typedef Utils::CmdLineParser::Arg Arg
An argument.
Static Public Member Functions
template<typename EnumType , uint16_t kLength>
static const char * Stringify (EnumType aEnum, const char *const (&aTable)[kLength], const char *aNotFound=kUnknownString)
Static Public Attributes
static const char kUnknownString [] = "unknown"
Protected Member Functions
OutputBase (void)=default
Detailed Description
This class is the base class for Output and OutputWrapper providing common helper methods.
Member Typedef Documentation
Arg
typedef Utils::CmdLineParser::Arg Arg
An argument.
Constructor & Destructor Documentation
OutputBase()
OutputBase (void) protected default
Referenced by OutputBase::Stringify().
Member Function Documentation
Stringify()
static const char* Stringify (EnumType aEnum, const char *const (&) aTable[kLength], const char * aNotFound = kUnknownString) inline static
This template static method converts an enumeration value to a string using a table array.
Template Parameters
EnumType The enum type.
kLength The table array length (number of entries in the array).
Parameters
[in] aEnum The enumeration value to convert (MUST be of EnumType).
[in] aTable A reference to the array of strings of length kLength. aTable[e] is the string representation of enumeration value e.
[in] aNotFound The string to return if the aEnum is not in the aTable.
Returns
The string representation of aEnum from aTable, or aNotFound if it is not in the table.
References OutputBase::OutputBase().
Referenced by Interpreter::SetUserCommands().
Field Documentation
kUnknownString
const char kUnknownString = "unknown" static
The documentation for this class was generated from the following files:
cli_output.hpp
cli_output.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale