OpenThread: Sha256::Hash Class Reference
Sha256::Hash Class Reference
#include <sha256.hpp>
Public Member Functions
const uint8_t * GetBytes (void) const
Public Member Functions inherited from Clearable< Hash >
void Clear (void)
Public Member Functions inherited from Equatable< Hash >
bool operator== (const Hash &aOther) const
Public Member Functions inherited from Unequatable< Hash >
bool operator!= (const Hash &aOther) const
Static Public Attributes
static const uint8_t kSize = OT_CRYPTO_SHA256_HASH_SIZE
SHA-256 hash size (bytes)
Additional Inherited Members
Data Fields inherited from otCryptoSha256Hash
uint8_t m8 [OT_CRYPTO_SHA256_HASH_SIZE]
Hash bytes.
Detailed Description
This type represents a SHA-256 hash.
Member Function Documentation
GetBytes()
const uint8_t* GetBytes (void) const inline
This method returns a pointer to a byte array containing the hash value.
Returns
A pointer to a byte array containing the hash.
References otCryptoSha256Hash::m8, Sha256::Sha256(), Sha256::Start(), Sha256::Update(), and Sha256::~Sha256().
Referenced by ot::MeshCoP::ComputeJoinerId(), and otPlatCryptoHkdfExpand().
Field Documentation
kSize
const uint8_t kSize = OT_CRYPTO_SHA256_HASH_SIZE static
SHA-256 hash size (bytes)
Referenced by HmacSha256::Finish(), and Sha256::Finish().
The documentation for this class was generated from the following file:
sha256.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale