OpenThread: OnMeshPrefixConfig Class Reference
OnMeshPrefixConfig Class Reference
#include <network_data_types.hpp>
Public Member Functions
RoutePreference GetPreference (void) const
const Ip6::Prefix & GetPrefix (void) const
Ip6::Prefix & GetPrefix (void)
Public Member Functions inherited from Clearable< OnMeshPrefixConfig >
void Clear (void)
Public Member Functions inherited from Equatable< OnMeshPrefixConfig >
bool operator== (const OnMeshPrefixConfig &aOther) const
Public Member Functions inherited from Unequatable< OnMeshPrefixConfig >
bool operator!= (const OnMeshPrefixConfig &aOther) const
Private Member Functions
void SetFrom (const PrefixTlv &aPrefixTlv, const BorderRouterTlv &aBorderRouterTlv, const BorderRouterEntry &aBorderRouterEntry)
void SetFromTlvFlags (uint16_t aFlags)
Friends
class Leader
class Local
class NetworkData
class Publisher
Additional Inherited Members
Data Fields inherited from otBorderRouterConfig
bool mConfigure: 1
Whether DHCPv6 Agent supplying other config data.
bool mDefaultRoute: 1
Whether border router is a default router for prefix.
bool mDhcp: 1
Whether border router is DHCPv6 Agent.
bool mDp: 1
Whether prefix is a Thread Domain Prefix (added since Thread 1.2).
bool mNdDns: 1
Whether this border router can supply DNS information via ND.
bool mOnMesh: 1
Whether this prefix is considered on-mesh.
signed int mPreference: 2
A 2-bit signed int preference (OT_ROUTE_PREFERENCE_* values).
bool mPreferred: 1
Whether prefix is preferred.
otIp6Prefix mPrefix
The IPv6 prefix.
uint16_t mRloc16
The border router's RLOC16 (value ignored on config add).
bool mSlaac: 1
Whether prefix can be used for address auto-configuration (SLAAC).
bool mStable: 1
Whether this configuration is considered Stable Network Data.
Detailed Description
This class represents an On-mesh Prefix (Border Router) configuration.
Member Function Documentation
GetPrefix() [1/2]
const Ip6::Prefix& GetPrefix (void) const inline
This method gets the prefix.
Returns
The prefix.
References ot::AsCoreType(), and otBorderRouterConfig::mPrefix.
Referenced by OnMeshPrefixConfig::SetFrom(), ExternalRouteConfig::SetFrom(), OnMeshPrefixConfig::SetFromTlvFlags(), and Leader::UpdateDomainPrefixConfig().
GetPrefix() [2/2]
Ip6::Prefix& GetPrefix (void) inline
This method gets the prefix.
Returns
The prefix.
References ot::AsCoreType(), and otBorderRouterConfig::mPrefix.
GetPreference()
RoutePreference GetPreference (void) const inline
This method gets the preference.
Returns
The preference.
References otBorderRouterConfig::mPreference, ot::NetworkData::RoutePreferenceFromValue(), ot::NetworkData::RoutePreferenceToValue(), OnMeshPrefixConfig::SetFrom(), and OnMeshPrefixConfig::SetFromTlvFlags().
SetFrom()
void SetFrom (const PrefixTlv & aPrefixTlv, const BorderRouterTlv & aBorderRouterTlv, const BorderRouterEntry & aBorderRouterEntry) private
References Clearable< OnMeshPrefixConfig >::Clear(), PrefixTlv::CopyPrefixTo(), BorderRouterEntry::GetFlags(), OnMeshPrefixConfig::GetPrefix(), BorderRouterEntry::GetRloc(), NetworkDataTlv::IsStable(), otBorderRouterConfig::mRloc16, otBorderRouterConfig::mStable, and OnMeshPrefixConfig::SetFromTlvFlags().
Referenced by OnMeshPrefixConfig::GetPreference(), ServiceConfig::GetServerConfig(), ServiceConfig::ServerConfig::GetServerData(), NetworkData::Iterate(), and ExternalRouteConfig::SetPrefix().
SetFromTlvFlags()
void SetFromTlvFlags (uint16_t aFlags) private
References OnMeshPrefixConfig::GetPrefix(), ot::NetworkData::IsRoutePreferenceValid(), BorderRouterEntry::kConfigureFlag, BorderRouterEntry::kDefaultRouteFlag, BorderRouterEntry::kDhcpFlag, BorderRouterEntry::kDpFlag, HasRouteEntry::kNat64Flag, BorderRouterEntry::kNdDnsFlag, BorderRouterEntry::kOnMeshFlag, HasRouteEntry::kPreferenceOffset, BorderRouterEntry::kPreferenceOffset, BorderRouterEntry::kPreferredFlag, BorderRouterEntry::kSlaacFlag, otBorderRouterConfig::mConfigure, otBorderRouterConfig::mDefaultRoute, otBorderRouterConfig::mDhcp, otBorderRouterConfig::mDp, otBorderRouterConfig::mNdDns, otBorderRouterConfig::mOnMesh, otBorderRouterConfig::mPreference, otBorderRouterConfig::mPreferred, otBorderRouterConfig::mSlaac, ot::NetworkData::RoutePreferenceFromValue(), ot::NetworkData::RoutePreferenceToValue(), and VerifyOrExit.
Referenced by OnMeshPrefixConfig::GetPreference(), OnMeshPrefixConfig::SetFrom(), ExternalRouteConfig::SetFrom(), and ExternalRouteConfig::SetPrefix().
Friends And Related Function Documentation
NetworkData
friend class NetworkData friend
Leader
friend class Leader friend
Local
friend class Local friend
Publisher
friend class Publisher friend
The documentation for this class was generated from the following files:
network_data_types.hpp
network_data_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale