OpenThread: Clearable< Type > Class Template Reference
Clearable< Type > Class Template Reference
#include <clearable.hpp>
Public Member Functions
void Clear (void)
Detailed Description
template<typename Type>
class ot::Clearable< Type >
This template class defines a Clearable object which provides Clear() method.
The Clear implementation simply sets all the bytes of a Type instance to zero.
Users of this class should follow CRTP-style inheritance, i.e., the Type class itself should publicly inherit from Clearable<Type>.
Member Function Documentation
Clear()
void Clear (void) inline
Referenced by SteeringData::CalculateHashBitIndexes(), DatasetLocal::Clear(), DatasetManager::Clear(), PendingDatasetManager::ClearNetwork(), Udp::Close(), Dataset::ConvertTo(), DatasetLocal::DatasetLocal(), DatasetManager::DatasetManager(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressUdpHeader(), ExtendedPanIdManager::ExtendedPanIdManager(), KeyMaterial::ExtractKey(), Instance::Finalize(), Lowpan::FindContextForId(), Lowpan::FindContextToCompressAddress(), KeyManager::GetNetworkKey(), KeyManager::GetPskc(), Ip6::HandleDatagram(), Icmp::HandleEchoRequest(), Message::Init(), SubMac::Init(), KeyManager::KeyManager(), Links::Links(), Mac::Mac(), Mle::Mle(), Udp::Open(), otSysGetThreadNetifIndex(), Message::ParseHeader(), DatasetLocal::Read(), DatasetLocal::Save(), Mle::SendAnnounce(), Icmp::SendEchoRequest(), Icmp::SendError(), and Mac::SetPanChannel().
The documentation for this class was generated from the following file:
clearable.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale