OpenThread: Option Class Reference
Option Class Reference
Core-dns
#include <dns_types.hpp>
Public Member Functions
uint16_t GetOptionCode (void) const
uint16_t GetOptionLength (void) const
uint32_t GetSize (void) const
void SetOptionCode (uint16_t aOptionCode)
void SetOptionLength (uint16_t aOptionLength)
Static Public Attributes
static constexpr uint16_t kUpdateLease = 2
Update lease option code.
Private Attributes
uint16_t mOptionCode
uint16_t mOptionLength
Detailed Description
This class implements the body of an Option in OPT Pseudo Resource Record (RFC 6981 - Section 6.1).
Member Function Documentation
GetOptionCode()
uint16_t GetOptionCode (void) const inline
This method returns the option code value.
Returns
The option code value.
References ot::Encoding::BigEndian::HostSwap16().
SetOptionCode()
void SetOptionCode (uint16_t aOptionCode) inline
This method sets the option code value.
Parameters
[in] aOptionCode The option code value.
References ot::Encoding::BigEndian::HostSwap16().
GetOptionLength()
uint16_t GetOptionLength (void) const inline
This method returns the option length value.
Returns
The option length (size of option data in bytes).
References ot::Encoding::BigEndian::HostSwap16().
SetOptionLength()
void SetOptionLength (uint16_t aOptionLength) inline
This method sets the option length value.
Parameters
[in] aOptionLength The option length (size of option data in bytes).
References ot::Encoding::BigEndian::HostSwap16().
GetSize()
uint32_t GetSize (void) const inline
This method returns the size of (number of bytes) in the Option and its data.
Returns
Size (number of bytes) of the Option its data section.
Field Documentation
kUpdateLease
constexpr uint16_t kUpdateLease = 2 static
Update lease option code.
mOptionCode
uint16_t mOptionCode private
mOptionLength
uint16_t mOptionLength private
The documentation for this class was generated from the following file:
dns_types.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale