OpenThread: cli_stdio.cpp File Reference
cli_stdio.cpp File Reference
#include "platform/openthread-posix-config.h"
#include <openthread/config.h>
#include <openthread/openthread-system.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <openthread/cli.h>
#include "cli/cli_config.h"
#include "common/code_utils.hpp"
#include "openthread-core-config.h"
#include "platform-posix.h"
Functions
void otAppCliDeinit (void)
void otAppCliInit (otInstance *aInstance)
void otAppCliProcess (const otSysMainloopContext *aMainloop)
void otAppCliUpdate (otSysMainloopContext *aMainloop)
Function Documentation
otAppCliInit()
void otAppCliInit (otInstance * aInstance)
This function initializes CLI app.
Parameters
[in] aInstance A pointer to the OpenThread instance.
References otCliInit().
Referenced by main().
otAppCliDeinit()
void otAppCliDeinit (void)
This function deinitializes CLI app.
Referenced by main().
otAppCliUpdate()
void otAppCliUpdate (otSysMainloopContext * aMainloop)
This function updates the file descriptor sets with file descriptors used by console.
Parameters
[in,out] aMainloop A pointer to the mainloop context.
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, and otSysMainloopContext::mReadFdSet.
Referenced by main().
otAppCliProcess()
void otAppCliProcess (const otSysMainloopContext * aMainloop)
This function performs console driver processing.
Parameters
[in] aMainloop A pointer to the mainloop context.
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mReadFdSet, OPENTHREAD_CONFIG_CLI_MAX_LINE_LENGTH, OT_EXIT_FAILURE, OT_EXIT_SUCCESS, and otCliInputLine().
Referenced by main().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale