OpenThread: Child Supervision
Child Supervision
API » Add-Ons
This module includes functions for child supervision feature.
Functions
uint16_t otChildSupervisionGetCheckTimeout (otInstance *aInstance)
uint16_t otChildSupervisionGetInterval (otInstance *aInstance)
void otChildSupervisionSetCheckTimeout (otInstance *aInstance, uint16_t aTimeout)
void otChildSupervisionSetInterval (otInstance *aInstance, uint16_t aInterval)
Detailed Description
This module includes functions for child supervision feature.
The functions in this module are available when child supervision feature (OPENTHREAD_CONFIG_CHILD_SUPERVISION_ENABLE) is enabled.
Function Documentation
otChildSupervisionGetInterval()
uint16_t otChildSupervisionGetInterval (otInstance * aInstance)
Get the child supervision interval (in seconds).
Child supervision feature provides a mechanism for parent to ensure that a message is sent to each sleepy child within the supervision interval. If there is no transmission to the child within the supervision interval, OpenThread enqueues and sends a supervision message (a data message with empty payload) to the child.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The child supervision interval. Zero indicates that child supervision is disabled.
Referenced by Interpreter::SetUserCommands().
otChildSupervisionSetInterval()
void otChildSupervisionSetInterval (otInstance * aInstance, uint16_t aInterval)
Set the child supervision interval (in seconds).
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aInterval The supervision interval (in seconds). Zero to disable supervision on parent.
Referenced by Interpreter::SetUserCommands().
otChildSupervisionGetCheckTimeout()
uint16_t otChildSupervisionGetCheckTimeout (otInstance * aInstance)
Get the supervision check timeout interval (in seconds).
If the device is a sleepy child and it does not hear from its parent within the specified check timeout, it initiates the re-attach process (MLE Child Update Request/Response exchange with its parent).
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The supervision check timeout. Zero indicates that supervision check on the child is disabled.
Referenced by Interpreter::SetUserCommands().
otChildSupervisionSetCheckTimeout()
void otChildSupervisionSetCheckTimeout (otInstance * aInstance, uint16_t aTimeout)
Set the supervision check timeout interval (in seconds).
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aTimeout The check timeout (in seconds). Zero to disable supervision check on the child.
Referenced by Interpreter::SetUserCommands().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale