OpenThread: Core-timer
Core-timer
This module includes definitions for the time instance.
Data Structures
class Time
class Timer
class TimerMilli
class TimerMilliContext
Typedefs
typedef Time TimeMilli
Functions
void otPlatAlarmMilliFired (otInstance *aInstance)
Detailed Description
This module includes definitions for the time instance.
This module includes definitions for the multiplexed timer service.
Typedef Documentation
TimeMilli
typedef Time TimeMilli
This type represents a time instance (millisecond time).
Function Documentation
otPlatAlarmMilliFired()
void otPlatAlarmMilliFired (otInstance * aInstance)
Signal that the alarm has fired.
Parameters
[in] aInstance The OpenThread instance structure.
References ot::AsCoreType(), Timer::kMaxDelay, Timer::mFireTime, OT_ASSERT, otInstanceIsInitialized(), otPlatAlarmMicroFired(), otPlatAlarmMicroGetNow(), otPlatAlarmMicroStartAt(), otPlatAlarmMicroStop(), and VerifyOrExit.
Referenced by platformAlarmProcess().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale