OpenThread: Utils-parse-cmd-line
Utils-parse-cmd-line
This module includes definitions for command line parser.
Data Structures
class Arg
Functions
template<>
otError ParseAs (uint8_t &aValue) const
template<>
otError ParseAs (uint16_t &aValue) const
template<>
otError ParseAs (uint32_t &aValue) const
template<>
otError ParseAs (uint64_t &aValue) const
template<>
otError ParseAs (bool &aValue) const
template<>
otError ParseAs (int8_t &aValue) const
template<>
otError ParseAs (int16_t &aValue) const
template<>
otError ParseAs (int32_t &aValue) const
Error ParseAsBool (const char *aString, bool &aBool)
template<uint16_t kBufferSize>
static otError ParseAsHexString (const char *aString, uint8_t(&aBuffer)[kBufferSize])
Error ParseAsHexString (const char *aString, uint8_t *aBuffer, uint16_t aSize)
Error ParseAsHexString (const char *aString, uint16_t &aSize, uint8_t *aBuffer)
Error ParseAsHexStringSegment (const char *&aString, uint16_t &aSize, uint8_t *aBuffer)
Error ParseAsInt16 (const char *aString, int16_t &aInt16)
Error ParseAsInt32 (const char *aString, int32_t &aInt32)
Error ParseAsInt8 (const char *aString, int8_t &aInt8)
Error ParseAsUint16 (const char *aString, uint16_t &aUint16)
Error ParseAsUint32 (const char *aString, uint32_t &aUint32)
Error ParseAsUint64 (const char *aString, uint64_t &aUint64)
Error ParseAsUint8 (const char *aString, uint8_t &aUint8)
Error ParseCmd (char *aCommandString, Arg aArgs[], uint8_t aArgsMaxLength)
template<uint8_t kLength>
otError ParseCmd (char *aCommandString, Arg(&aArgs)[kLength])
Detailed Description
This module includes definitions for command line parser.
Function Documentation
ParseAsUint8()
otError ParseAsUint8 (const char * aString, uint8_t & aUint8)
This function parses a string as a uint8_t value.
The number in string is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[in] aString The string to parse.
[out] aUint8 A reference to an uint8_t variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number (e.g., value out of range).
Referenced by NetworkData::OutputService(), ot::Utils::CmdLineParser::ParseAsBool(), Arg::ParseAsUint8(), and Interpreter::SetUserCommands().
ParseAsUint16()
otError ParseAsUint16 (const char * aString, uint16_t & aUint16)
This function parses a string as a uint16_t value.
The number in string is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[in] aString The string to parse.
[out] aUint16 A reference to an uint16_t variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number (e.g., value out of range).
Referenced by NetworkData::OutputService(), Arg::ParseAsUint16(), Dataset::Process(), UdpExample::ProcessBind(), UdpExample::ProcessConnect(), UdpExample::ProcessSend(), and Interpreter::SetUserCommands().
ParseAsUint32()
otError ParseAsUint32 (const char * aString, uint32_t & aUint32)
This function parses a string as a uint32_t value.
The number in string is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[in] aString The string to parse.
[out] aUint32 A reference to an uint32_t variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number (e.g., value out of range).
Referenced by ot::Utils::CmdLineParser::ParseAsBool(), Arg::ParseAsUint32(), Dataset::Process(), and Interpreter::SetUserCommands().
ParseAsUint64()
otError ParseAsUint64 (const char * aString, uint64_t & aUint64)
This function parses a string as a uint64_t value.
The number in string is parsed as decimal or hex format (if contains 0x or 0X prefix).
Parameters
[in] aString The string to parse.
[out] aUint64 A reference to an uint64_t variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number (e.g., value out of range).
References ot::kErrorInvalidArgs, ot::kErrorNone, ot::Utils::CmdLineParser::ParseDigit(), ot::Utils::CmdLineParser::ParseHexDigit(), SuccessOrExit, and VerifyOrExit.
Referenced by ot::Utils::CmdLineParser::ParseAsInt32(), Arg::ParseAsUint64(), ot::Utils::CmdLineParser::ParseUint(), and Dataset::Process().
ParseAsInt8()
otError ParseAsInt8 (const char * aString, int8_t & aInt8)
This function parses a string as a int8_t value.
The number in string is parsed as decimal or hex format (if contains 0x or 0X prefix). The string can start with +/- sign.
Parameters
[in] aString The string to parse.
[out] aInt8 A reference to an int8_t variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number (e.g., value out of range).
Referenced by Arg::ParseAsInt8(), and Interpreter::SetUserCommands().
ParseAsInt16()
otError ParseAsInt16 (const char * aString, int16_t & aInt16)
This function parses a string as a int16_t value.
The number in string is parsed as decimal or hex format (if contains 0x or 0X prefix). The string can start with +/- sign.
Parameters
[in] aString The string to parse.
[out] aInt16 A reference to an int16_t variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number (e.g., value out of range).
Referenced by Arg::ParseAsInt16().
ParseAsInt32()
otError ParseAsInt32 (const char * aString, int32_t & aInt32)
This function parses a string as a int32_t value.
The number in string is parsed as decimal or hex format (if contains 0x or 0X prefix). The string can start with +/- sign.
Parameters
[in] aString The string to parse.
[out] aInt32 A reference to an int32_t variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number (e.g., value out of range).
References ot::kErrorInvalidArgs, ot::Utils::CmdLineParser::ParseAsUint64(), SuccessOrExit, and VerifyOrExit.
Referenced by Arg::ParseAsInt32(), and ot::Utils::CmdLineParser::ParseInt().
ParseAsBool()
otError ParseAsBool (const char * aString, bool & aBool)
This function parses a string as a bool value.
Zero value is treated as false, non-zero value as true.
Parameters
[in] aString The string to parse.
[out] aBool A reference to a bool variable to output the parsed value.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid number.
References ot::kErrorInvalidArgs, otIp6Prefix::mLength, otIp6Prefix::mPrefix, otIp6AddressFromString(), ot::Utils::CmdLineParser::ParseAsUint32(), ot::Utils::CmdLineParser::ParseAsUint8(), ot::StringFind(), SuccessOrExit, and VerifyOrExit.
Referenced by Arg::ParseAsBool(), and Interpreter::SetUserCommands().
ParseAsHexString() [1/3]
otError ParseAsHexString (const char * aString, uint8_t * aBuffer, uint16_t aSize)
This function parses a hex string into a byte array of fixed expected size.
This function returns kErrorNone only when the hex string contains exactly aSize bytes (after parsing). If there are fewer or more bytes in hex string that aSize, the parsed bytes (up to aSize) are copied into the aBuffer and kErrorInvalidArgs is returned.
This function correctly handles hex strings with even or odd length. For example, "AABBCCDD" (with even length) is parsed as {0xaa, 0xbb, 0xcc, 0xdd} and "123" (with odd length) is parsed as {0x01, 0x23}.
Parameters
[in] aString The string to parse.
[out] aBuffer A pointer to a buffer to output the parsed byte sequence.
[in] aSize The expected size of byte sequence (number of bytes after parsing).
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid hex bytes and/or not aSize bytes.
References ot::Utils::CmdLineParser::kModeExtactSize, and ot::Utils::CmdLineParser::ParseHexString().
Referenced by ot::Utils::CmdLineParser::ParseAsHexString(), Arg::ParseAsHexString(), Dataset::Process(), and Interpreter::SetUserCommands().
ParseAsHexString() [2/3]
static otError ot::Utils::CmdLineParser::ParseAsHexString (const char * aString, uint8_t(&) aBuffer[kBufferSize]) static
This template function parses a hex string into a a given fixed size array.
This function returns kErrorNone only when the hex string contains exactly kBufferSize bytes (after parsing). If there are fewer or more bytes in hex string that kBufferSize, the parsed bytes (up to kBufferSize) are copied into the aBuffer and kErrorInvalidArgs is returned.
This function correctly handles hex strings with even or odd length. For example, "AABBCCDD" (with even length) is parsed as {0xaa, 0xbb, 0xcc, 0xdd} and "123" (with odd length) is parsed as {0x01, 0x23}.
Template Parameters
kBufferSize The byte array size (number of bytes).
Parameters
[in] aString The string to parse.
[out] aBuffer A reference to a byte array to output the parsed byte sequence.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid hex bytes and/or not aSize bytes.
References ot::Utils::CmdLineParser::ParseAsHexString(), and ot::Utils::CmdLineParser::ParseAsHexStringSegment().
ParseAsHexString() [3/3]
otError ParseAsHexString (const char * aString, uint16_t & aSize, uint8_t * aBuffer)
This function parses a hex string into a byte array.
This function verifies that the parsed hex string bytes fit in aBuffer with its given aSize.
This function correctly handles hex strings with even or odd length. For example, "AABBCCDD" (with even length) is parsed as {0xaa, 0xbb, 0xcc, 0xdd} and "123" (with odd length) is parsed as {0x01, 0x23}.
Parameters
[in] aString The string to parse.
[in,out] aSize On entry indicates the number of bytes in aBuffer (max size of aBuffer). On exit provides number of bytes parsed and copied into aBuffer.
[out] aBuffer A pointer to a buffer to output the parsed byte sequence.
Return values
kErrorNone The string was parsed successfully.
kErrorInvalidArgs The string does not contain valid format or too many bytes.
References ot::Utils::CmdLineParser::kModeUpToSize, and ot::Utils::CmdLineParser::ParseHexString().
ParseAsHexStringSegment()
otError ParseAsHexStringSegment (const char *& aString, uint16_t & aSize, uint8_t * aBuffer)
This function parses a segment of a hex string up to a given size.
This function allows a longer hex string to be parsed and read in smaller segments into a given buffer. If the entire hex string bytes can fit in the given aBuffer with its aSize, they are copied into aBuffer and function returns kErrorNone. Otherwise, aSize bytes are read and copied and function returns kErrorPending to indicate that there are more bytes to parse. The aString is also updated to skip over the parsed segment.
This function correctly handles hex strings with even or odd length. For example, "AABBCCDD" (with even length) is parsed as {0xaa, 0xbb, 0xcc, 0xdd} and "123" (with odd length) is parsed as {0x01, 0x23}.
Parameters
[in,out] aString A reference to string to parse. On successful parse, updated to skip parsed digits.
[in,out] aSize On entry indicates the segment size (number of bytes in aBuffer). On exit provides number of bytes parsed and copied into aBuffer.
[out] aBuffer A pointer to a buffer to output the parsed byte sequence.
Return values
kErrorNone The string was parsed successfully to the end of string.
kErrorPedning The string segment was parsed successfully, but there are additional bytes remaining to be parsed.
kErrorInvalidArgs The string does not contain valid format hex digits.
References ot::Utils::CmdLineParser::kModeAllowPartial, and ot::Utils::CmdLineParser::ParseHexString().
Referenced by ot::Utils::CmdLineParser::ParseAsHexString(), and UdpExample::PrepareHexStringPaylod().
ParseCmd() [1/2]
otError ParseCmd (char * aCommandString, Arg aArgs[], uint8_t aArgsMaxLength)
This function parses a given command line string and breaks it into an argument list.
This function may change the input aCommandString, it will put a '\0' by the end of each argument, and aArgs will point to the arguments in the input aCommandString. Backslash ('\') can be used to escape separators (' ', '', '', '
') and the backslash itself.
As the arguments are parsed, the aArgs array entries are populated. Any remaining aArgs entries in the array will be cleared and marked as empty. So the number of arguments can be determined by going through aArgs array entries till we get to an empty Arg (i.e., Arg::IsEmpty() returns `true).
This function ensures that the last entry in aArgs array is always used to indicate the end (always marked as empty), so the aArgs array should have one more entry than the desired max number of arguments.
Parameters
[in] aCommandString A null-terminated input string.
[out] aArgs The argument array.
[in] aArgsMaxLength The max length of aArgs array.
Return values
OT_ERROR_NONE The command line parsed successfully and aArgs array is populated.
OT_ERROR_INVALID_ARGS Too many arguments in aCommandString and could not fit in aArgs array.
References Arg::Clear(), ot::Utils::CmdLineParser::IsEscapable(), ot::Utils::CmdLineParser::IsSeparator(), ot::kErrorInvalidArgs, ot::kErrorNone, and Arg::SetCString().
Referenced by ot::Utils::CmdLineParser::ParseCmd(), and Interpreter::ProcessLine().
ParseCmd() [2/2]
otError ot::Utils::CmdLineParser::ParseCmd (char * aCommandString, Arg(&) aArgs[kLength]) inline
References ot::Utils::CmdLineParser::ParseCmd().
ParseAs() [1/8]
otError ParseAs (uint8_t & aValue) const inline
References Arg::ParseAsUint8().
ParseAs() [2/8]
otError ParseAs (uint16_t & aValue) const inline
References Arg::ParseAsUint16().
ParseAs() [3/8]
otError ParseAs (uint32_t & aValue) const inline
References Arg::ParseAsUint32().
ParseAs() [4/8]
otError ParseAs (uint64_t & aValue) const inline
References Arg::ParseAsUint64().
ParseAs() [5/8]
otError ParseAs (bool & aValue) const inline
References Arg::ParseAsBool().
ParseAs() [6/8]
otError ParseAs (int8_t & aValue) const inline
References Arg::ParseAsInt8().
ParseAs() [7/8]
otError ParseAs (int16_t & aValue) const inline
References Arg::ParseAsInt16().
ParseAs() [8/8]
otError ParseAs (int32_t & aValue) const inline
References Arg::ParseAs(), and Arg::ParseAsInt32().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale