OpenThread: Alarm
Alarm
Platform Abstraction
This module includes the platform abstraction for the alarm service.
Functions
void otPlatAlarmMicroFired (otInstance *aInstance)
uint32_t otPlatAlarmMicroGetNow (void)
void otPlatAlarmMicroStartAt (otInstance *aInstance, uint32_t aT0, uint32_t aDt)
void otPlatAlarmMicroStop (otInstance *aInstance)
void otPlatAlarmMilliFired (otInstance *aInstance)
uint32_t otPlatAlarmMilliGetNow (void)
void otPlatAlarmMilliStartAt (otInstance *aInstance, uint32_t aT0, uint32_t aDt)
void otPlatAlarmMilliStop (otInstance *aInstance)
void otPlatDiagAlarmFired (otInstance *aInstance)
Detailed Description
This module includes the platform abstraction for the alarm service.
Function Documentation
otPlatAlarmMicroStartAt()
void otPlatAlarmMicroStartAt (otInstance * aInstance, uint32_t aT0, uint32_t aDt)
Set the alarm to fire at aDt microseconds after aT0.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aT0 The reference time.
[in] aDt The time delay in microseconds from aT0.
Referenced by otPlatAlarmMilliFired(), and otPlatAlarmMilliStop().
otPlatAlarmMicroStop()
void otPlatAlarmMicroStop (otInstance * aInstance)
Stop the alarm.
Parameters
[in] aInstance The OpenThread instance structure.
Referenced by otPlatAlarmMilliFired(), and otPlatAlarmMilliStop().
otPlatAlarmMicroGetNow()
uint32_t otPlatAlarmMicroGetNow (void)
Get the current time.
Returns
The current time in microseconds.
Referenced by otPlatAlarmMilliFired(), otPlatAlarmMilliStop(), and platformAlarmProcess().
otPlatAlarmMicroFired()
void otPlatAlarmMicroFired (otInstance * aInstance)
Signal that the alarm has fired.
Parameters
[in] aInstance The OpenThread instance structure.
Referenced by otPlatAlarmMilliFired(), and platformAlarmProcess().
otPlatAlarmMilliStartAt()
void otPlatAlarmMilliStartAt (otInstance * aInstance, uint32_t aT0, uint32_t aDt)
Set the alarm to fire at aDt milliseconds after aT0.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aT0 The reference time.
[in] aDt The time delay in milliseconds from aT0.
References OT_UNUSED_VARIABLE, sIsMsRunning, and sMsAlarm.
otPlatAlarmMilliStop()
void otPlatAlarmMilliStop (otInstance * aInstance)
Stop the alarm.
Parameters
[in] aInstance The OpenThread instance structure.
References NS_PER_US, OT_UNUSED_VARIABLE, otLogWarnPlat(), otPlatAlarmMicroGetNow(), otPlatAlarmMicroStartAt(), otPlatAlarmMicroStop(), platformAlarmGetNow(), sIsMsRunning, and US_PER_S.
otPlatAlarmMilliGetNow()
uint32_t otPlatAlarmMilliGetNow (void)
Get the current time.
Returns
The current time in milliseconds.
References platformAlarmGetNow(), and US_PER_MS.
Referenced by TimerMilli::GetNow(), NcpBase::HandlePropertySet(), NcpBase::Log(), and platformAlarmProcess().
otPlatAlarmMilliFired()
void otPlatAlarmMilliFired (otInstance * aInstance)
Signal that the alarm has fired.
Parameters
[in] aInstance The OpenThread instance structure.
References ot::AsCoreType(), Timer::kMaxDelay, Timer::mFireTime, OT_ASSERT, otInstanceIsInitialized(), otPlatAlarmMicroFired(), otPlatAlarmMicroGetNow(), otPlatAlarmMicroStartAt(), otPlatAlarmMicroStop(), and VerifyOrExit.
Referenced by platformAlarmProcess().
otPlatDiagAlarmFired()
void otPlatDiagAlarmFired (otInstance * aInstance)
Signal diagnostics module that the alarm has fired.
Parameters
[in] aInstance The OpenThread instance structure.
Referenced by platformAlarmProcess().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale