OpenThread: General
General
API » Thread
This module includes functions for all Thread roles.
Data Structures
struct otBorderRouterConfig
struct otExternalRouteConfig
struct otIpCounters
struct otLeaderData
struct otLinkModeConfig
struct otMleCounters
struct otNeighborInfo
struct otNetworkDiagChildEntry
struct otNetworkDiagConnectivity
struct otNetworkDiagMacCounters
struct otNetworkDiagRoute
struct otNetworkDiagRouteData
struct otNetworkDiagTlv
struct otRouterInfo
struct otServerConfig
struct otServiceConfig
struct otThreadDiscoveryRequestInfo
struct otThreadParentResponseInfo
Macros
#define OT_JOINER_ADVDATA_MAX_LENGTH 64
Maximum AdvData Length of Joiner Advertisement.
#define OT_NEIGHBOR_INFO_ITERATOR_INIT 0
Initializer for otNeighborInfoIterator.
#define OT_NETWORK_BASE_TLV_MAX_LENGTH 254
#define OT_NETWORK_DATA_ITERATOR_INIT 0
Value to initialize otNetworkDataIterator.
#define OT_NETWORK_DIAGNOSTIC_CHILD_TABLE_ENTRY_SIZE 3
#define OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT 0
#define OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES 19
#define OT_NETWORK_MAX_ROUTER_ID 62
Maximum Router ID.
#define OT_SERVER_DATA_MAX_SIZE 248
Max size of Server Data in bytes. Theoretical limit, practically much lower.
#define OT_SERVICE_DATA_MAX_SIZE 252
Max size of Service Data in bytes.
Typedefs
typedef struct otBorderRouterConfig otBorderRouterConfig
typedef void(* otDetachGracefullyCallback) (void *aContext)
typedef struct otExternalRouteConfig otExternalRouteConfig
typedef struct otIpCounters otIpCounters
typedef struct otLeaderData otLeaderData
typedef struct otLinkModeConfig otLinkModeConfig
typedef struct otMleCounters otMleCounters
typedef int16_t otNeighborInfoIterator
Used to iterate through neighbor table.
typedef void(* otNetDataDnsSrpServicePublisherCallback) (otNetDataPublisherEvent aEvent, void *aContext)
typedef void(* otNetDataPrefixPublisherCallback) (otNetDataPublisherEvent aEvent, const otIp6Prefix *aPrefix, void *aContext)
typedef enum otNetDataPublisherEvent otNetDataPublisherEvent
typedef uint32_t otNetworkDataIterator
Used to iterate through Network Data information.
typedef struct otNetworkDiagChildEntry otNetworkDiagChildEntry
typedef struct otNetworkDiagConnectivity otNetworkDiagConnectivity
typedef uint16_t otNetworkDiagIterator
Used to iterate through Network Diagnostic TLV.
typedef struct otNetworkDiagMacCounters otNetworkDiagMacCounters
typedef struct otNetworkDiagRoute otNetworkDiagRoute
typedef struct otNetworkDiagRouteData otNetworkDiagRouteData
typedef struct otNetworkDiagTlv otNetworkDiagTlv
typedef void(* otReceiveDiagnosticGetCallback) (otError aError, otMessage *aMessage, const otMessageInfo *aMessageInfo, void *aContext)
typedef enum otRoutePreference otRoutePreference
typedef struct otServerConfig otServerConfig
typedef struct otServiceConfig otServiceConfig
typedef void(* otThreadAnycastLocatorCallback) (void *aContext, otError aError, const otIp6Address *aMeshLocalAddress, uint16_t aRloc16)
typedef void(* otThreadDiscoveryRequestCallback) (const otThreadDiscoveryRequestInfo *aInfo, void *aContext)
typedef struct otThreadDiscoveryRequestInfo otThreadDiscoveryRequestInfo
typedef void(* otThreadParentResponseCallback) (otThreadParentResponseInfo *aInfo, void *aContext)
typedef struct otThreadParentResponseInfo otThreadParentResponseInfo
Enumerations
enum {
OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS = 0, OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS = 1, OT_NETWORK_DIAGNOSTIC_TLV_MODE = 2, OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT = 3,
OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY = 4, OT_NETWORK_DIAGNOSTIC_TLV_ROUTE = 5, OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA = 6, OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA = 7,
OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST = 8, OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS = 9, OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL = 14, OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE = 15,
OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE = 16, OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES = 17, OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST = 18, OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT = 19
}
enum otDeviceRole {
OT_DEVICE_ROLE_DISABLED = 0, OT_DEVICE_ROLE_DETACHED = 1, OT_DEVICE_ROLE_CHILD = 2, OT_DEVICE_ROLE_ROUTER = 3,
OT_DEVICE_ROLE_LEADER = 4
}
enum otNetDataPublisherEvent { OT_NETDATA_PUBLISHER_EVENT_ENTRY_ADDED = 0, OT_NETDATA_PUBLISHER_EVENT_ENTRY_REMOVED = 1 }
enum otRoutePreference { OT_ROUTE_PREFERENCE_LOW = -1, OT_ROUTE_PREFERENCE_MED = 0, OT_ROUTE_PREFERENCE_HIGH = 1 }
Functions
bool otNetDataContainsOmrPrefix (otInstance *aInstance, const otIp6Prefix *aPrefix)
otError otNetDataGet (otInstance *aInstance, bool aStable, uint8_t *aData, uint8_t *aDataLength)
otError otNetDataGetNextOnMeshPrefix (otInstance *aInstance, otNetworkDataIterator *aIterator, otBorderRouterConfig *aConfig)
otError otNetDataGetNextRoute (otInstance *aInstance, otNetworkDataIterator *aIterator, otExternalRouteConfig *aConfig)
otError otNetDataGetNextService (otInstance *aInstance, otNetworkDataIterator *aIterator, otServiceConfig *aConfig)
uint8_t otNetDataGetStableVersion (otInstance *aInstance)
uint8_t otNetDataGetVersion (otInstance *aInstance)
bool otNetDataIsDnsSrpServiceAdded (otInstance *aInstance)
bool otNetDataIsPrefixAdded (otInstance *aInstance, const otIp6Prefix *aPrefix)
void otNetDataPublishDnsSrpServiceAnycast (otInstance *aInstance, uint8_t aSequenceNUmber)
void otNetDataPublishDnsSrpServiceUnicast (otInstance *aInstance, const otIp6Address *aAddress, uint16_t aPort)
void otNetDataPublishDnsSrpServiceUnicastMeshLocalEid (otInstance *aInstance, uint16_t aPort)
otError otNetDataPublishExternalRoute (otInstance *aInstance, const otExternalRouteConfig *aConfig)
otError otNetDataPublishOnMeshPrefix (otInstance *aInstance, const otBorderRouterConfig *aConfig)
void otNetDataSetDnsSrpServicePublisherCallback (otInstance *aInstance, otNetDataDnsSrpServicePublisherCallback aCallback, void *aContext)
void otNetDataSetPrefixPublisherCallback (otInstance *aInstance, otNetDataPrefixPublisherCallback aCallback, void *aContext)
otError otNetDataSteeringDataCheckJoiner (otInstance *aInstance, const otExtAddress *aEui64)
otError otNetDataSteeringDataCheckJoinerWithDiscerner (otInstance *aInstance, const struct otJoinerDiscerner *aDiscerner)
void otNetDataUnpublishDnsSrpService (otInstance *aInstance)
otError otNetDataUnpublishPrefix (otInstance *aInstance, const otIp6Prefix *aPrefix)
otError otThreadBecomeChild (otInstance *aInstance)
otError otThreadBecomeDetached (otInstance *aInstance)
otError otThreadDetachGracefully (otInstance *aInstance, otDetachGracefullyCallback aCallback, void *aContext)
const char * otThreadDeviceRoleToString (otDeviceRole aRole)
otError otThreadDiscover (otInstance *aInstance, uint32_t aScanChannels, uint16_t aPanId, bool aJoiner, bool aEnableEui64Filtering, otHandleActiveScanResult aCallback, void *aCallbackContext)
uint32_t otThreadGetChildTimeout (otInstance *aInstance)
otDeviceRole otThreadGetDeviceRole (otInstance *aInstance)
const char * otThreadGetDomainName (otInstance *aInstance)
const otExtendedPanId * otThreadGetExtendedPanId (otInstance *aInstance)
const otIp6InterfaceIdentifier * otThreadGetFixedDuaInterfaceIdentifier (otInstance *aInstance)
const otIpCounters * otThreadGetIp6Counters (otInstance *aInstance)
uint32_t otThreadGetKeySequenceCounter (otInstance *aInstance)
uint32_t otThreadGetKeySwitchGuardTime (otInstance *aInstance)
otError otThreadGetLeaderData (otInstance *aInstance, otLeaderData *aLeaderData)
otError otThreadGetLeaderRloc (otInstance *aInstance, otIp6Address *aLeaderRloc)
uint8_t otThreadGetLeaderRouterId (otInstance *aInstance)
uint8_t otThreadGetLeaderWeight (otInstance *aInstance)
const otIp6Address * otThreadGetLinkLocalAllThreadNodesMulticastAddress (otInstance *aInstance)
const otIp6Address * otThreadGetLinkLocalIp6Address (otInstance *aInstance)
otLinkModeConfig otThreadGetLinkMode (otInstance *aInstance)
const otIp6Address * otThreadGetMeshLocalEid (otInstance *aInstance)
const otMeshLocalPrefix * otThreadGetMeshLocalPrefix (otInstance *aInstance)
const otMleCounters * otThreadGetMleCounters (otInstance *aInstance)
void otThreadGetNetworkKey (otInstance *aInstance, otNetworkKey *aNetworkKey)
otNetworkKeyRef otThreadGetNetworkKeyRef (otInstance *aInstance)
const char * otThreadGetNetworkName (otInstance *aInstance)
otError otThreadGetNextDiagnosticTlv (const otMessage *aMessage, otNetworkDiagIterator *aIterator, otNetworkDiagTlv *aNetworkDiagTlv)
otError otThreadGetNextNeighborInfo (otInstance *aInstance, otNeighborInfoIterator *aIterator, otNeighborInfo *aInfo)
otError otThreadGetParentAverageRssi (otInstance *aInstance, int8_t *aParentRssi)
otError otThreadGetParentInfo (otInstance *aInstance, otRouterInfo *aParentInfo)
otError otThreadGetParentLastRssi (otInstance *aInstance, int8_t *aLastRssi)
uint32_t otThreadGetPartitionId (otInstance *aInstance)
const otIp6Address * otThreadGetRealmLocalAllThreadNodesMulticastAddress (otInstance *aInstance)
const otIp6Address * otThreadGetRloc (otInstance *aInstance)
uint16_t otThreadGetRloc16 (otInstance *aInstance)
otError otThreadGetServiceAloc (otInstance *aInstance, uint8_t aServiceId, otIp6Address *aServiceAloc)
uint16_t otThreadGetVersion (void)
bool otThreadIsAnycastLocateInProgress (otInstance *aInstance)
bool otThreadIsDiscoverInProgress (otInstance *aInstance)
bool otThreadIsSingleton (otInstance *aInstance)
otError otThreadLocateAnycastDestination (otInstance *aInstance, const otIp6Address *aAnycastAddress, otThreadAnycastLocatorCallback aCallback, void *aContext)
void otThreadRegisterParentResponseCallback (otInstance *aInstance, otThreadParentResponseCallback aCallback, void *aContext)
void otThreadResetIp6Counters (otInstance *aInstance)
void otThreadResetMleCounters (otInstance *aInstance)
otError otThreadSearchForBetterParent (otInstance *aInstance)
void otThreadSendAddressNotification (otInstance *aInstance, otIp6Address *aDestination, otIp6Address *aTarget, otIp6InterfaceIdentifier *aMlIid)
otError otThreadSendDiagnosticGet (otInstance *aInstance, const otIp6Address *aDestination, const uint8_t aTlvTypes[], uint8_t aCount, otReceiveDiagnosticGetCallback aCallback, void *aCallbackContext)
otError otThreadSendDiagnosticReset (otInstance *aInstance, const otIp6Address *aDestination, const uint8_t aTlvTypes[], uint8_t aCount)
otError otThreadSendProactiveBackboneNotification (otInstance *aInstance, otIp6Address *aTarget, otIp6InterfaceIdentifier *aMlIid, uint32_t aTimeSinceLastTransaction)
void otThreadSetChildTimeout (otInstance *aInstance, uint32_t aTimeout)
void otThreadSetDiscoveryRequestCallback (otInstance *aInstance, otThreadDiscoveryRequestCallback aCallback, void *aContext)
otError otThreadSetDomainName (otInstance *aInstance, const char *aDomainName)
otError otThreadSetEnabled (otInstance *aInstance, bool aEnabled)
otError otThreadSetExtendedPanId (otInstance *aInstance, const otExtendedPanId *aExtendedPanId)
otError otThreadSetFixedDuaInterfaceIdentifier (otInstance *aInstance, const otIp6InterfaceIdentifier *aIid)
otError otThreadSetJoinerAdvertisement (otInstance *aInstance, uint32_t aOui, const uint8_t *aAdvData, uint8_t aAdvDataLength)
void otThreadSetKeySequenceCounter (otInstance *aInstance, uint32_t aKeySequenceCounter)
void otThreadSetKeySwitchGuardTime (otInstance *aInstance, uint32_t aKeySwitchGuardTime)
otError otThreadSetLinkMode (otInstance *aInstance, otLinkModeConfig aConfig)
otError otThreadSetMeshLocalPrefix (otInstance *aInstance, const otMeshLocalPrefix *aMeshLocalPrefix)
otError otThreadSetNetworkKey (otInstance *aInstance, const otNetworkKey *aKey)
otError otThreadSetNetworkKeyRef (otInstance *aInstance, otNetworkKeyRef aKeyRef)
otError otThreadSetNetworkName (otInstance *aInstance, const char *aNetworkName)
Detailed Description
This module includes functions for all Thread roles.
The Network Data Publisher provides mechanisms to limit the number of similar Service and/or Prefix (on-mesh prefix or external route) entries in the Thread Network Data by monitoring the Network Data and managing if or when to add or remove entries.
All the functions in this module require OPENTHREAD_CONFIG_NETDATA_PUBLISHER_ENABLE to be enabled.
Note
The functions in this module require OPENTHREAD_FTD=1 or OPENTHREAD_MTD=1.
Macro Definition Documentation
OT_NETWORK_DATA_ITERATOR_INIT
#define OT_NETWORK_DATA_ITERATOR_INIT 0
Value to initialize otNetworkDataIterator.
Referenced by otSysGetThreadNetifIndex(), NetworkData::OutputPrefixes(), NetworkData::OutputRoutes(), NetworkData::OutputServices(), and Interpreter::SetUserCommands().
OT_SERVICE_DATA_MAX_SIZE
#define OT_SERVICE_DATA_MAX_SIZE 252
Max size of Service Data in bytes.
OT_SERVER_DATA_MAX_SIZE
#define OT_SERVER_DATA_MAX_SIZE 248
Max size of Server Data in bytes. Theoretical limit, practically much lower.
OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES
#define OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES 19
Maximum Number of Network Diagnostic TLV Types to Request or Reset.
Referenced by Interpreter::SetUserCommands().
OT_NETWORK_DIAGNOSTIC_CHILD_TABLE_ENTRY_SIZE
#define OT_NETWORK_DIAGNOSTIC_CHILD_TABLE_ENTRY_SIZE 3
Size of Network Diagnostic Child Table entry.
OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT
#define OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT 0
Initializer for otNetworkDiagIterator.
Referenced by Interpreter::SetUserCommands().
OT_NETWORK_BASE_TLV_MAX_LENGTH
#define OT_NETWORK_BASE_TLV_MAX_LENGTH 254
Maximum value length of Thread Base TLV.
OT_NETWORK_MAX_ROUTER_ID
#define OT_NETWORK_MAX_ROUTER_ID 62
Maximum Router ID.
OT_NEIGHBOR_INFO_ITERATOR_INIT
#define OT_NEIGHBOR_INFO_ITERATOR_INIT 0
Initializer for otNeighborInfoIterator.
Referenced by NeighborTable::FindNeighbor(), and Interpreter::SetUserCommands().
OT_JOINER_ADVDATA_MAX_LENGTH
#define OT_JOINER_ADVDATA_MAX_LENGTH 64
Maximum AdvData Length of Joiner Advertisement.
Typedef Documentation
otNetworkDataIterator
typedef uint32_t otNetworkDataIterator
Used to iterate through Network Data information.
otBorderRouterConfig
typedef struct otBorderRouterConfig otBorderRouterConfig
This structure represents a Border Router configuration.
otExternalRouteConfig
typedef struct otExternalRouteConfig otExternalRouteConfig
This structure represents an External Route configuration.
otRoutePreference
typedef enum otRoutePreference otRoutePreference
Defines valid values for mPreference in otExternalRouteConfig and otBorderRouterConfig.
otServerConfig
typedef struct otServerConfig otServerConfig
This structure represents a Server configuration.
otServiceConfig
typedef struct otServiceConfig otServiceConfig
This structure represents a Service configuration.
otNetDataPublisherEvent
typedef enum otNetDataPublisherEvent otNetDataPublisherEvent
This enumeration represents the events reported from the Publisher callbacks.
otNetDataDnsSrpServicePublisherCallback
typedef void(* otNetDataDnsSrpServicePublisherCallback) (otNetDataPublisherEvent aEvent, void *aContext)
This function pointer type defines the callback used to notify when a "DNS/SRP Service" entry is added to or removed from the Thread Network Data.
On remove the callback is invoked independent of whether the entry is removed by Publisher (e.g., when there are too many similar entries already present in the Network Data) or through an explicit call to unpublish the entry (i.e., a call to otNetDataUnpublishDnsSrpService()).
Parameters
[in] aEvent Indicates the event (whether the entry was added or removed).
[in] aContext A pointer to application-specific context.
otNetDataPrefixPublisherCallback
typedef void(* otNetDataPrefixPublisherCallback) (otNetDataPublisherEvent aEvent, const otIp6Prefix *aPrefix, void *aContext)
This function pointer type defines the callback used to notify when a prefix (on-mesh or external route) entry is added to or removed from the Thread Network Data.
On remove the callback is invoked independent of whether the entry is removed by Publisher (e.g., when there are too many similar entries already present in the Network Data) or through an explicit call to unpublish the entry.
Parameters
[in] aEvent Indicates the event (whether the entry was added or removed).
[in] aPrefix A pointer to the prefix entry.
[in] aContext A pointer to application-specific context.
otNetworkDiagIterator
typedef uint16_t otNetworkDiagIterator
Used to iterate through Network Diagnostic TLV.
otNetworkDiagConnectivity
typedef struct otNetworkDiagConnectivity otNetworkDiagConnectivity
This structure represents a Network Diagnostic Connectivity value.
otNetworkDiagRouteData
typedef struct otNetworkDiagRouteData otNetworkDiagRouteData
This structure represents a Network Diagnostic Route data.
otNetworkDiagRoute
typedef struct otNetworkDiagRoute otNetworkDiagRoute
This structure represents a Network Diagnostic Route TLV value.
otNetworkDiagMacCounters
typedef struct otNetworkDiagMacCounters otNetworkDiagMacCounters
This structure represents a Network Diagnostic Mac Counters value.
See RFC 2863 for definitions of member fields.
otNetworkDiagChildEntry
typedef struct otNetworkDiagChildEntry otNetworkDiagChildEntry
This structure represents a Network Diagnostic Child Table Entry.
otNetworkDiagTlv
typedef struct otNetworkDiagTlv otNetworkDiagTlv
This structure represents a Network Diagnostic TLV.
otReceiveDiagnosticGetCallback
typedef void(* otReceiveDiagnosticGetCallback) (otError aError, otMessage *aMessage, const otMessageInfo *aMessageInfo, void *aContext)
This function pointer is called when Network Diagnostic Get response is received.
Parameters
[in] aError The error when failed to get the response.
[in] aMessage A pointer to the message buffer containing the received Network Diagnostic Get response payload. Available only when aError is OT_ERROR_NONE.
[in] aMessageInfo A pointer to the message info for aMessage. Available only when aError is OT_ERROR_NONE.
[in] aContext A pointer to application-specific context.
otLinkModeConfig
typedef struct otLinkModeConfig otLinkModeConfig
This structure represents an MLE Link Mode configuration.
otNeighborInfoIterator
typedef int16_t otNeighborInfoIterator
Used to iterate through neighbor table.
otLeaderData
typedef struct otLeaderData otLeaderData
This structure represents the Thread Leader Data.
otIpCounters
typedef struct otIpCounters otIpCounters
This structure represents the IP level counters.
otMleCounters
typedef struct otMleCounters otMleCounters
This structure represents the Thread MLE counters.
otThreadParentResponseInfo
typedef struct otThreadParentResponseInfo otThreadParentResponseInfo
This structure represents the MLE Parent Response data.
otDetachGracefullyCallback
typedef void(* otDetachGracefullyCallback) (void *aContext)
This callback informs the application that the detaching process has finished.
Parameters
[in] aContext A pointer to application-specific context.
otThreadParentResponseCallback
typedef void(* otThreadParentResponseCallback) (otThreadParentResponseInfo *aInfo, void *aContext)
This function pointer is called every time an MLE Parent Response message is received.
Parameters
[in] aInfo A pointer to a location on stack holding the stats data.
[in] aContext A pointer to callback client-specific context.
otThreadDiscoveryRequestInfo
typedef struct otThreadDiscoveryRequestInfo otThreadDiscoveryRequestInfo
This structure represents the Thread Discovery Request data.
otThreadDiscoveryRequestCallback
typedef void(* otThreadDiscoveryRequestCallback) (const otThreadDiscoveryRequestInfo *aInfo, void *aContext)
This function pointer is called every time an MLE Discovery Request message is received.
Parameters
[in] aInfo A pointer to the Discovery Request info data.
[in] aContext A pointer to callback application-specific context.
otThreadAnycastLocatorCallback
typedef void(* otThreadAnycastLocatorCallback) (void *aContext, otError aError, const otIp6Address *aMeshLocalAddress, uint16_t aRloc16)
This function pointer type defines the callback to notify the outcome of a otThreadLocateAnycastDestination() request.
Parameters
[in] aContext A pointer to an arbitrary context (provided when callback is registered).
[in] aError The error when handling the request. OT_ERROR_NONE indicates success. OT_ERROR_RESPONSE_TIMEOUT indicates a destination could not be found. OT_ERROR_ABORT indicates the request was aborted.
[in] aMeshLocalAddress A pointer to the mesh-local EID of the closest destination of the anycast address when aError is OT_ERROR_NONE, NULL otherwise.
[in] aRloc16 The RLOC16 of the destination if found, otherwise invalid RLOC16 (0xfffe).
Enumeration Type Documentation
otRoutePreference
enum otRoutePreference
Defines valid values for mPreference in otExternalRouteConfig and otBorderRouterConfig.
Enumerator
OT_ROUTE_PREFERENCE_LOW
Low route preference.
OT_ROUTE_PREFERENCE_MED
Medium route preference.
OT_ROUTE_PREFERENCE_HIGH
High route preference.
otNetDataPublisherEvent
enum otNetDataPublisherEvent
This enumeration represents the events reported from the Publisher callbacks.
Enumerator
OT_NETDATA_PUBLISHER_EVENT_ENTRY_ADDED
Published entry is added to the Thread Network Data.
OT_NETDATA_PUBLISHER_EVENT_ENTRY_REMOVED
Published entry is removed from the Thread Network Data.
anonymous enum
anonymous enum
Enumerator
OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS
MAC Extended Address TLV.
OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS
Address16 TLV.
OT_NETWORK_DIAGNOSTIC_TLV_MODE
Mode TLV.
OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT
Timeout TLV (the maximum polling time period for SEDs)
OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY
Connectivity TLV.
OT_NETWORK_DIAGNOSTIC_TLV_ROUTE
Route64 TLV.
OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA
Leader Data TLV.
OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA
Network Data TLV.
OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST
IPv6 Address List TLV.
OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS
MAC Counters TLV.
OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL
Battery Level TLV.
OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE
Supply Voltage TLV.
OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE
Child Table TLV.
OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES
Channel Pages TLV.
OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST
Type List TLV.
OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
Max Child Timeout TLV.
otDeviceRole
enum otDeviceRole
Represents a Thread device role.
Enumerator
OT_DEVICE_ROLE_DISABLED
The Thread stack is disabled.
OT_DEVICE_ROLE_DETACHED
Not currently participating in a Thread network/partition.
OT_DEVICE_ROLE_CHILD
The Thread Child role.
OT_DEVICE_ROLE_ROUTER
The Thread Router role.
OT_DEVICE_ROLE_LEADER
The Thread Leader role.
Function Documentation
otNetDataGet()
otError otNetDataGet (otInstance * aInstance, bool aStable, uint8_t * aData, uint8_t * aDataLength)
This method provides a full or stable copy of the Partition's Thread Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aStable TRUE when copying the stable version, FALSE when copying the full version.
[out] aData A pointer to the data buffer.
[in,out] aDataLength On entry, size of the data buffer pointed to by aData. On exit, number of copied bytes.
References ot::AsCoreType(), AssertPointerIsNotNull, ot::NetworkData::kFullSet, and ot::NetworkData::kStableSubset.
Referenced by NetworkData::OutputBinary().
otNetDataGetNextOnMeshPrefix()
otError otNetDataGetNextOnMeshPrefix (otInstance * aInstance, otNetworkDataIterator * aIterator, otBorderRouterConfig * aConfig)
This function gets the next On Mesh Prefix in the partition's Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the Network Data iterator context. To get the first on-mesh entry it should be set to OT_NETWORK_DATA_ITERATOR_INIT.
[out] aConfig A pointer to where the On Mesh Prefix information will be placed.
Return values
OT_ERROR_NONE Successfully found the next On Mesh prefix.
OT_ERROR_NOT_FOUND No subsequent On Mesh prefix exists in the Thread Network Data.
References ot::AsCoreType(), AssertPointerIsNotNull, and otNetDataContainsOmrPrefix().
Referenced by NetworkData::GetNextPrefix(), and otSysGetThreadNetifIndex().
otNetDataGetNextRoute()
otError otNetDataGetNextRoute (otInstance * aInstance, otNetworkDataIterator * aIterator, otExternalRouteConfig * aConfig)
This function gets the next external route in the partition's Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the Network Data iterator context. To get the first external route entry it should be set to OT_NETWORK_DATA_ITERATOR_INIT.
[out] aConfig A pointer to where the External Route information will be placed.
Return values
OT_ERROR_NONE Successfully found the next External Route.
OT_ERROR_NOT_FOUND No subsequent external route entry exists in the Thread Network Data.
References ot::AsCoreType(), and AssertPointerIsNotNull.
Referenced by NetworkData::GetNextRoute(), and otSysGetThreadNetifIndex().
otNetDataGetNextService()
otError otNetDataGetNextService (otInstance * aInstance, otNetworkDataIterator * aIterator, otServiceConfig * aConfig)
This function gets the next service in the partition's Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the Network Data iterator context. To get the first service entry it should be set to OT_NETWORK_DATA_ITERATOR_INIT.
[out] aConfig A pointer to where the service information will be placed.
Return values
OT_ERROR_NONE Successfully found the next service.
OT_ERROR_NOT_FOUND No subsequent service exists in the partition's Network Data.
References ot::AsCoreType(), and AssertPointerIsNotNull.
Referenced by NetworkData::GetNextService().
otNetDataGetVersion()
uint8_t otNetDataGetVersion (otInstance * aInstance)
Get the Network Data Version.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Network Data Version.
References ot::AsCoreType(), and ot::NetworkData::kFullSet.
otNetDataGetStableVersion()
uint8_t otNetDataGetStableVersion (otInstance * aInstance)
Get the Stable Network Data Version.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Stable Network Data Version.
References ot::AsCoreType(), and ot::NetworkData::kStableSubset.
otNetDataSteeringDataCheckJoiner()
otError otNetDataSteeringDataCheckJoiner (otInstance * aInstance, const otExtAddress * aEui64)
Check if the steering data includes a Joiner.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aEui64 A pointer to the Joiner's IEEE EUI-64.
Return values
OT_ERROR_NONE aEui64 is included in the steering data.
OT_ERROR_INVALID_STATE No steering data present.
OT_ERROR_NOT_FOUND aEui64 is not included in the steering data.
References ot::AsCoreType().
Referenced by NetworkData::Process().
otNetDataSteeringDataCheckJoinerWithDiscerner()
otError otNetDataSteeringDataCheckJoinerWithDiscerner (otInstance * aInstance, const struct otJoinerDiscerner * aDiscerner)
Check if the steering data includes a Joiner with a given discerner value.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDiscerner A pointer to the Joiner Discerner.
Return values
OT_ERROR_NONE aDiscerner is included in the steering data.
OT_ERROR_INVALID_STATE No steering data present.
OT_ERROR_NOT_FOUND aDiscerner is not included in the steering data.
otNetDataContainsOmrPrefix()
bool otNetDataContainsOmrPrefix (otInstance * aInstance, const otIp6Prefix * aPrefix)
This function checks whether a given Prefix can act as a valid OMR prefix and also the Leader's Network Data contains this prefix.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aPrefix A pointer to the IPv6 prefix.
Returns
Whether aPrefix is a valid OMR prefix and Leader's Network Data contains the OMR prefix aPrefix.
Note
This API is only available when OPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE is used.
Referenced by otNetDataGetNextOnMeshPrefix(), and otSysGetThreadNetifIndex().
otNetDataPublishDnsSrpServiceAnycast()
void otNetDataPublishDnsSrpServiceAnycast (otInstance * aInstance, uint8_t aSequenceNUmber)
This function requests "DNS/SRP Service Anycast Address" to be published in the Thread Network Data.
This function requires the feature OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE to be enabled.
A call to this function will remove and replace any previous "DNS/SRP Service" entry that was being published (from earlier call to any of otNetDataPublishDnsSrpService{Type}() functions).
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aSequenceNUmber The sequence number of DNS/SRP Anycast Service.
Referenced by NetworkData::OutputService().
otNetDataPublishDnsSrpServiceUnicast()
void otNetDataPublishDnsSrpServiceUnicast (otInstance * aInstance, const otIp6Address * aAddress, uint16_t aPort)
This function requests "DNS/SRP Service Unicast Address" to be published in the Thread Network Data.
This function requires the feature OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE to be enabled.
A call to this function will remove and replace any previous "DNS/SRP Service" entry that was being published (from earlier call to any of otNetDataPublishDnsSrpService{Type}() functions).
This function publishes the "DNS/SRP Service Unicast Address" by including the address and port info in the Service TLV data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aAddress The DNS/SRP server address to publish (MUST NOT be NULL).
[in] aPort The SRP server port number to publish.
Referenced by NetworkData::OutputService().
otNetDataPublishDnsSrpServiceUnicastMeshLocalEid()
void otNetDataPublishDnsSrpServiceUnicastMeshLocalEid (otInstance * aInstance, uint16_t aPort)
This function requests "DNS/SRP Service Unicast Address" to be published in the Thread Network Data.
This function requires the feature OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE to be enabled.
A call to this function will remove and replace any previous "DNS/SRP Service" entry that was being published (from earlier call to any of otNetDataPublishDnsSrpService{Type}() functions).
Unlike otNetDataPublishDnsSrpServiceUnicast() which requires the published address to be given and includes the info in the Service TLV data, this function uses the device's mesh-local EID and includes the info in the Server TLV data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aPort The SRP server port number to publish.
Referenced by NetworkData::OutputService().
otNetDataIsDnsSrpServiceAdded()
bool otNetDataIsDnsSrpServiceAdded (otInstance * aInstance)
This function indicates whether or not currently the "DNS/SRP Service" entry is added to the Thread Network Data.
This function requires the feature OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE to be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
TRUE The published DNS/SRP Service entry is added to the Thread Network Data.
FALSE The entry is not added to Thread Network Data or there is no entry to publish.
otNetDataSetDnsSrpServicePublisherCallback()
void otNetDataSetDnsSrpServicePublisherCallback (otInstance * aInstance, otNetDataDnsSrpServicePublisherCallback aCallback, void * aContext)
This function sets a callback for notifying when a published "DNS/SRP Service" is actually added to or removed from the Thread Network Data.
A subsequent call to this function replaces any previously set callback function.
This function requires the feature OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE to be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aCallback The callback function pointer (can be NULL if not needed).
[in] aContext A pointer to application-specific context (used when aCallback is invoked).
otNetDataUnpublishDnsSrpService()
void otNetDataUnpublishDnsSrpService (otInstance * aInstance)
Unpublishes any previously added DNS/SRP (Anycast or Unicast) Service entry from the Thread Network Data.
OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE must be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Referenced by NetworkData::OutputService().
otNetDataPublishOnMeshPrefix()
otError otNetDataPublishOnMeshPrefix (otInstance * aInstance, const otBorderRouterConfig * aConfig)
This function requests an on-mesh prefix to be published in the Thread Network Data.
This function requires the feature OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE to be enabled.
Only stable entries can be published (i.e.,aConfig.mStable MUST be TRUE).
A subsequent call to this method will replace a previous request for the same prefix. In particular, if the new call only changes the flags (e.g., preference level) and the prefix is already added in the Network Data, the change to flags is immediately reflected in the Network Data. This ensures that existing entries in the Network Data are not abruptly removed. Note that a change in the preference level can potentially later cause the entry to be removed from the Network Data after determining there are other nodes that are publishing the same prefix with the same or higher preference.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aConfig The on-mesh prefix config to publish (MUST NOT be NULL).
Return values
OT_ERROR_NONE The on-mesh prefix is published successfully.
OT_ERROR_INVALID_ARGS The aConfig is not valid (bad prefix, invalid flag combinations, or not stable).
OT_ERROR_NO_BUFS Could not allocate an entry for the new request. Publisher supports a limited number of entries (shared between on-mesh prefix and external route) determined by config OPENTHREAD_CONFIG_NETDATA_PUBLISHER_MAX_PREFIX_ENTRIES.
Referenced by NetworkData::OutputService().
otNetDataPublishExternalRoute()
otError otNetDataPublishExternalRoute (otInstance * aInstance, const otExternalRouteConfig * aConfig)
This function requests an external route prefix to be published in the Thread Network Data.
This function requires the feature OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE to be enabled.
Only stable entries can be published (i.e.,aConfig.mStable MUST be TRUE).
A subsequent call to this method will replace a previous request for the same prefix. In particular, if the new call only changes the flags (e.g., preference level) and the prefix is already added in the Network Data, the change to flags is immediately reflected in the Network Data. This ensures that existing entries in the Network Data are not abruptly removed. Note that a change in the preference level can potentially later cause the entry to be removed from the Network Data after determining there are other nodes that are publishing the same prefix with the same or higher preference.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aConfig The external route config to publish (MUST NOT be NULL).
Return values
OT_ERROR_NONE The external route is published successfully.
OT_ERROR_INVALID_ARGS The aConfig is not valid (bad prefix, invalid flag combinations, or not stable).
OT_ERROR_NO_BUFS Could not allocate an entry for the new request. Publisher supports a limited number of entries (shared between on-mesh prefix and external route) determined by config OPENTHREAD_CONFIG_NETDATA_PUBLISHER_MAX_PREFIX_ENTRIES.
Referenced by NetworkData::OutputService().
otNetDataIsPrefixAdded()
bool otNetDataIsPrefixAdded (otInstance * aInstance, const otIp6Prefix * aPrefix)
This function indicates whether or not currently a published prefix entry (on-mesh or external route) is added to the Thread Network Data.
This function requires the feature OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE to be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aPrefix A pointer to the prefix (MUST NOT be NULL).
Return values
TRUE The published prefix entry is added to the Thread Network Data.
FALSE The entry is not added to Thread Network Data or there is no entry to publish.
otNetDataSetPrefixPublisherCallback()
void otNetDataSetPrefixPublisherCallback (otInstance * aInstance, otNetDataPrefixPublisherCallback aCallback, void * aContext)
This function sets a callback for notifying when a published prefix entry is actually added to or removed from the Thread Network Data.
A subsequent call to this function replaces any previously set callback function.
This function requires the feature OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE to be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aCallback The callback function pointer (can be NULL if not needed).
[in] aContext A pointer to application-specific context (used when aCallback is invoked).
otNetDataUnpublishPrefix()
otError otNetDataUnpublishPrefix (otInstance * aInstance, const otIp6Prefix * aPrefix)
Unpublishes a previously published On-Mesh or External Route Prefix.
OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE must be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aPrefix The prefix to unpublish (MUST NOT be NULL).
Return values
OT_ERROR_NONE The prefix was unpublished successfully.
OT_ERROR_NOT_FOUND Could not find the prefix in the published list.
Referenced by NetworkData::OutputService().
otThreadGetNextDiagnosticTlv()
otError otThreadGetNextDiagnosticTlv (const otMessage * aMessage, otNetworkDiagIterator * aIterator, otNetworkDiagTlv * aNetworkDiagTlv)
This function gets the next Network Diagnostic TLV in the message.
Parameters
[in] aMessage A pointer to a message.
[in,out] aIterator A pointer to the Network Diagnostic iterator context. To get the first Network Diagnostic TLV it should be set to OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT.
[out] aNetworkDiagTlv A pointer to where the Network Diagnostic TLV information will be placed.
Return values
OT_ERROR_NONE Successfully found the next Network Diagnostic TLV.
OT_ERROR_NOT_FOUND No subsequent Network Diagnostic TLV exists in the message.
OT_ERROR_PARSE Parsing the next Network Diagnostic failed.
A subsequent call to this function is allowed only when current return value is OT_ERROR_NONE.
Referenced by Interpreter::SetUserCommands().
otThreadSendDiagnosticGet()
otError otThreadSendDiagnosticGet (otInstance * aInstance, const otIp6Address * aDestination, const uint8_t aTlvTypes[], uint8_t aCount, otReceiveDiagnosticGetCallback aCallback, void * aCallbackContext)
Send a Network Diagnostic Get request.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDestination A pointer to destination address.
[in] aTlvTypes An array of Network Diagnostic TLV types.
[in] aCount Number of types in aTlvTypes.
[in] aCallback A pointer to a function that is called when Network Diagnostic Get response is received or NULL to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
Return values
OT_ERROR_NONE Successfully queued the DIAG_GET.req.
OT_ERROR_NO_BUFS Insufficient message buffers available to send DIAG_GET.req.
Referenced by Interpreter::SetUserCommands().
otThreadSendDiagnosticReset()
otError otThreadSendDiagnosticReset (otInstance * aInstance, const otIp6Address * aDestination, const uint8_t aTlvTypes[], uint8_t aCount)
Send a Network Diagnostic Reset request.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDestination A pointer to destination address.
[in] aTlvTypes An array of Network Diagnostic TLV types. Currently only Type 9 is allowed.
[in] aCount Number of types in aTlvTypes
Return values
OT_ERROR_NONE Successfully queued the DIAG_RST.ntf.
OT_ERROR_NO_BUFS Insufficient message buffers available to send DIAG_RST.ntf.
Referenced by Interpreter::SetUserCommands().
otThreadSetEnabled()
otError otThreadSetEnabled (otInstance * aInstance, bool aEnabled)
This function starts Thread protocol operation.
The interface must be up when calling this function.
Calling this function with aEnabled set to FALSE stops any ongoing processes of detaching started by otThreadDetachGracefully(). Its callback will be called.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aEnabled TRUE if Thread is enabled, FALSE otherwise.
Return values
OT_ERROR_NONE Successfully started Thread protocol operation.
OT_ERROR_INVALID_STATE The network interface was not not up.
Referenced by NcpBase::CommandHandler_RESET(), Instance::Finalize(), NcpBase::HandlePropertyGet(), and Interpreter::SetUserCommands().
otThreadGetVersion()
uint16_t otThreadGetVersion (void)
This function gets the Thread protocol version.
Returns
the Thread protocol version.
Referenced by InitInstance(), Interpreter::SetUserCommands(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
otThreadIsSingleton()
bool otThreadIsSingleton (otInstance * aInstance)
This function indicates whether a node is the only router on the network.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
TRUE It is the only router in the network.
FALSE It is a child or is not a single router in the network.
Referenced by Interpreter::SetUserCommands().
otThreadDiscover()
otError otThreadDiscover (otInstance * aInstance, uint32_t aScanChannels, uint16_t aPanId, bool aJoiner, bool aEnableEui64Filtering, otHandleActiveScanResult aCallback, void * aCallbackContext)
This function starts a Thread Discovery scan.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aScanChannels A bit vector indicating which channels to scan (e.g. OT_CHANNEL_11_MASK).
[in] aPanId The PAN ID filter (set to Broadcast PAN to disable filter).
[in] aJoiner Value of the Joiner Flag in the Discovery Request TLV.
[in] aEnableEui64Filtering TRUE to filter responses on EUI-64, FALSE otherwise.
[in] aCallback A pointer to a function called on receiving an MLE Discovery Response or scan completes.
[in] aCallbackContext A pointer to application-specific context.
Return values
OT_ERROR_NONE Successfully started a Thread Discovery Scan.
OT_ERROR_INVALID_STATE The IPv6 interface is not enabled (netif is not up).
OT_ERROR_NO_BUFS Could not allocate message for Discovery Request.
OT_ERROR_BUSY Thread Discovery Scan is already in progress.
Referenced by NcpBase::HandlePropertySet(), and Interpreter::SetUserCommands().
otThreadIsDiscoverInProgress()
bool otThreadIsDiscoverInProgress (otInstance * aInstance)
This function determines if an MLE Thread Discovery is currently in progress.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Referenced by NcpBase::HandlePropertyGet().
otThreadSetJoinerAdvertisement()
otError otThreadSetJoinerAdvertisement (otInstance * aInstance, uint32_t aOui, const uint8_t * aAdvData, uint8_t aAdvDataLength)
This method sets the Thread Joiner Advertisement when discovering Thread network.
Thread Joiner Advertisement is used to allow a Joiner to advertise its own application-specific information (such as Vendor ID, Product ID, Discriminator, etc.) via a newly-proposed Joiner Advertisement TLV, and to make this information available to Commissioners or Commissioner Candidates without human interaction.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aOui The Vendor IEEE OUI value that will be included in the Joiner Advertisement. Only the least significant 3 bytes will be used, and the most significant byte will be ignored.
[in] aAdvData A pointer to the AdvData that will be included in the Joiner Advertisement.
[in] aAdvDataLength The length of AdvData in bytes.
Return values
OT_ERROR_NONE Successfully set Joiner Advertisement.
OT_ERROR_INVALID_ARGS Invalid AdvData.
otThreadGetChildTimeout()
uint32_t otThreadGetChildTimeout (otInstance * aInstance)
Get the Thread Child Timeout used when operating in the Child role.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Thread Child Timeout value in seconds.
See also
otThreadSetChildTimeout
Referenced by Interpreter::SetUserCommands().
otThreadSetChildTimeout()
void otThreadSetChildTimeout (otInstance * aInstance, uint32_t aTimeout)
Set the Thread Child Timeout used when operating in the Child role.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aTimeout The timeout value in seconds.
See also
otThreadGetChildTimeout
Referenced by Interpreter::SetUserCommands().
otThreadGetExtendedPanId()
const otExtendedPanId* otThreadGetExtendedPanId (otInstance * aInstance)
Gets the IEEE 802.15.4 Extended PAN ID.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the IEEE 802.15.4 Extended PAN ID.
See also
otThreadSetExtendedPanId
Referenced by Dataset::Process(), and Interpreter::SetUserCommands().
otThreadSetExtendedPanId()
otError otThreadSetExtendedPanId (otInstance * aInstance, const otExtendedPanId * aExtendedPanId)
Sets the IEEE 802.15.4 Extended PAN ID.
Note
Can only be called while Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aExtendedPanId A pointer to the IEEE 802.15.4 Extended PAN ID.
Return values
OT_ERROR_NONE Successfully set the Extended PAN ID.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetExtendedPanId
Referenced by Interpreter::SetUserCommands().
otThreadGetLeaderRloc()
otError otThreadGetLeaderRloc (otInstance * aInstance, otIp6Address * aLeaderRloc)
This function returns a pointer to the Leader's RLOC.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aLeaderRloc A pointer to the Leader's RLOC.
Return values
OT_ERROR_NONE The Leader's RLOC was successfully written to aLeaderRloc.
OT_ERROR_INVALID_ARGS aLeaderRloc was NULL.
OT_ERROR_DETACHED Not currently attached to a Thread Partition.
otThreadGetLinkMode()
otLinkModeConfig otThreadGetLinkMode (otInstance * aInstance)
Get the MLE Link Mode configuration.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The MLE Link Mode configuration.
See also
otThreadSetLinkMode
Referenced by Interpreter::SetUserCommands().
otThreadSetLinkMode()
otError otThreadSetLinkMode (otInstance * aInstance, otLinkModeConfig aConfig)
Set the MLE Link Mode configuration.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aConfig A pointer to the Link Mode configuration.
Return values
OT_ERROR_NONE Successfully set the MLE Link Mode configuration.
See also
otThreadGetLinkMode
Referenced by Interpreter::SetUserCommands().
otThreadGetNetworkKey()
void otThreadGetNetworkKey (otInstance * aInstance, otNetworkKey * aNetworkKey)
Get the Thread Network Key.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aNetworkKey A pointer to an otNetworkkey to return the Thread Network Key.
See also
otThreadSetNetworkKey
Referenced by Interpreter::SetUserCommands().
otThreadGetNetworkKeyRef()
otNetworkKeyRef otThreadGetNetworkKeyRef (otInstance * aInstance)
Get the otNetworkKeyRef for Thread Network Key.
This function requires the build-time feature OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE to be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
Reference to the Thread Network Key stored in memory.
See also
otThreadSetNetworkKeyRef
Referenced by Interpreter::SetUserCommands().
otThreadSetNetworkKey()
otError otThreadSetNetworkKey (otInstance * aInstance, const otNetworkKey * aKey)
Set the Thread Network Key.
This function succeeds only when Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKey A pointer to a buffer containing the Thread Network Key.
Return values
OT_ERROR_NONE Successfully set the Thread Network Key.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetNetworkKey
Referenced by Interpreter::SetUserCommands().
otThreadSetNetworkKeyRef()
otError otThreadSetNetworkKeyRef (otInstance * aInstance, otNetworkKeyRef aKeyRef)
Set the Thread Network Key as a otNetworkKeyRef.
This function succeeds only when Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
This function requires the build-time feature OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE to be enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKeyRef Reference to the Thread Network Key.
Return values
OT_ERROR_NONE Successfully set the Thread Network Key.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetNetworkKeyRef
Referenced by Interpreter::SetUserCommands().
otThreadGetRloc()
const otIp6Address* otThreadGetRloc (otInstance * aInstance)
This function returns a pointer to the Thread Routing Locator (RLOC) address.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread Routing Locator (RLOC) address.
Referenced by Interpreter::SetUserCommands().
otThreadGetMeshLocalEid()
const otIp6Address* otThreadGetMeshLocalEid (otInstance * aInstance)
This function returns a pointer to the Mesh Local EID address.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Mesh Local EID address.
Referenced by Interpreter::SetUserCommands().
otThreadGetMeshLocalPrefix()
const otMeshLocalPrefix* otThreadGetMeshLocalPrefix (otInstance * aInstance)
This function returns a pointer to the Mesh Local Prefix.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Mesh Local Prefix.
Referenced by Interpreter::SetUserCommands().
otThreadSetMeshLocalPrefix()
otError otThreadSetMeshLocalPrefix (otInstance * aInstance, const otMeshLocalPrefix * aMeshLocalPrefix)
This function sets the Mesh Local Prefix.
This function succeeds only when Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aMeshLocalPrefix A pointer to the Mesh Local Prefix.
Return values
OT_ERROR_NONE Successfully set the Mesh Local Prefix.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
Referenced by Interpreter::SetUserCommands().
otThreadGetLinkLocalIp6Address()
const otIp6Address* otThreadGetLinkLocalIp6Address (otInstance * aInstance)
This function returns the Thread link-local IPv6 address.
The Thread link local address is derived using IEEE802.15.4 Extended Address as Interface Identifier.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to Thread link-local IPv6 address.
Referenced by Interpreter::SetUserCommands().
otThreadGetLinkLocalAllThreadNodesMulticastAddress()
const otIp6Address* otThreadGetLinkLocalAllThreadNodesMulticastAddress (otInstance * aInstance)
This function returns the Thread Link-Local All Thread Nodes multicast address.
The address is a link-local Unicast Prefix-Based Multcast Address [RFC 3306], with:
flgs set to 3 (P = 1 and T = 1)
scop set to 2
plen set to 64
network prefix set to the Mesh Local Prefix
group ID set to 1
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to Thread Link-Local All Thread Nodes multicast address.
Referenced by Interpreter::SetUserCommands().
otThreadGetRealmLocalAllThreadNodesMulticastAddress()
const otIp6Address* otThreadGetRealmLocalAllThreadNodesMulticastAddress (otInstance * aInstance)
This function returns the Thread Realm-Local All Thread Nodes multicast address.
The address is a realm-local Unicast Prefix-Based Multcast Address [RFC 3306], with:
flgs set to 3 (P = 1 and T = 1)
scop set to 3
plen set to 64
network prefix set to the Mesh Local Prefix
group ID set to 1
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to Thread Realm-Local All Thread Nodes multicast address.
Referenced by Interpreter::SetUserCommands().
otThreadGetServiceAloc()
otError otThreadGetServiceAloc (otInstance * aInstance, uint8_t aServiceId, otIp6Address * aServiceAloc)
This function retrieves the Service ALOC for given Service ID.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aServiceId Service ID to get ALOC for.
[out] aServiceAloc A pointer to output the Service ALOC. MUST NOT BE NULL.
Return values
OT_ERROR_NONE Successfully retrieved the Service ALOC.
OT_ERROR_DETACHED The Thread interface is not currently attached to a Thread Partition.
otThreadGetNetworkName()
const char* otThreadGetNetworkName (otInstance * aInstance)
Get the Thread Network Name.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread Network Name.
See also
otThreadSetNetworkName
Referenced by Dataset::Process(), and Interpreter::SetUserCommands().
otThreadSetNetworkName()
otError otThreadSetNetworkName (otInstance * aInstance, const char * aNetworkName)
Set the Thread Network Name.
This function succeeds only when Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aNetworkName A pointer to the Thread Network Name.
Return values
OT_ERROR_NONE Successfully set the Thread Network Name.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetNetworkName
Referenced by Interpreter::SetUserCommands().
otThreadGetDomainName()
const char* otThreadGetDomainName (otInstance * aInstance)
Gets the Thread Domain Name.
Note
Available since Thread 1.2.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread Domain Name.
See also
otThreadSetDomainName
Referenced by Interpreter::SetUserCommands().
otThreadSetDomainName()
otError otThreadSetDomainName (otInstance * aInstance, const char * aDomainName)
Sets the Thread Domain Name. Only succeeds when Thread protocols are disabled.
Note
Available since Thread 1.2.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDomainName A pointer to the Thread Domain Name.
Return values
OT_ERROR_NONE Successfully set the Thread Domain Name.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetDomainName
Referenced by Interpreter::SetUserCommands().
otThreadSetFixedDuaInterfaceIdentifier()
otError otThreadSetFixedDuaInterfaceIdentifier (otInstance * aInstance, const otIp6InterfaceIdentifier * aIid)
Sets or clears the Interface Identifier manually specified for the Thread Domain Unicast Address.
Available when OPENTHREAD_CONFIG_DUA_ENABLE is enabled.
Note
Only available since Thread 1.2.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aIid A pointer to the Interface Identifier to set or NULL to clear.
Return values
OT_ERROR_NONE Successfully set/cleared the Interface Identifier.
OT_ERROR_INVALID_ARGS The specified Interface Identifier is reserved.
See also
otThreadGetFixedDuaInterfaceIdentifier
Referenced by Interpreter::SetUserCommands().
otThreadGetFixedDuaInterfaceIdentifier()
const otIp6InterfaceIdentifier* otThreadGetFixedDuaInterfaceIdentifier (otInstance * aInstance)
Gets the Interface Identifier manually specified for the Thread Domain Unicast Address.
Available when OPENTHREAD_CONFIG_DUA_ENABLE is enabled.
Note
Only available since Thread 1.2.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Interface Identifier which was set manually, or NULL if none was set.
See also
otThreadSetFixedDuaInterfaceIdentifier
Referenced by Interpreter::SetUserCommands().
otThreadGetKeySequenceCounter()
uint32_t otThreadGetKeySequenceCounter (otInstance * aInstance)
Get the thrKeySequenceCounter.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The thrKeySequenceCounter value.
See also
otThreadSetKeySequenceCounter
Referenced by Interpreter::SetUserCommands().
otThreadSetKeySequenceCounter()
void otThreadSetKeySequenceCounter (otInstance * aInstance, uint32_t aKeySequenceCounter)
Set the thrKeySequenceCounter.
Note
This API is reserved for testing and demo purposes only. Changing settings with this API will render a production application non-compliant with the Thread Specification.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKeySequenceCounter The thrKeySequenceCounter value.
See also
otThreadGetKeySequenceCounter
Referenced by Interpreter::SetUserCommands().
otThreadGetKeySwitchGuardTime()
uint32_t otThreadGetKeySwitchGuardTime (otInstance * aInstance)
Get the thrKeySwitchGuardTime
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The thrKeySwitchGuardTime value (in hours).
See also
otThreadSetKeySwitchGuardTime
Referenced by Interpreter::SetUserCommands().
otThreadSetKeySwitchGuardTime()
void otThreadSetKeySwitchGuardTime (otInstance * aInstance, uint32_t aKeySwitchGuardTime)
Set the thrKeySwitchGuardTime
Note
This API is reserved for testing and demo purposes only. Changing settings with this API will render a production application non-compliant with the Thread Specification.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKeySwitchGuardTime The thrKeySwitchGuardTime value (in hours).
See also
otThreadGetKeySwitchGuardTime
Referenced by Interpreter::SetUserCommands().
otThreadBecomeDetached()
otError otThreadBecomeDetached (otInstance * aInstance)
Detach from the Thread network.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
OT_ERROR_NONE Successfully detached from the Thread network.
OT_ERROR_INVALID_STATE Thread is disabled.
Referenced by Interpreter::SetUserCommands().
otThreadBecomeChild()
otError otThreadBecomeChild (otInstance * aInstance)
Attempt to reattach as a child.
Note
This API is reserved for testing and demo purposes only. Changing settings with this API will render a production application non-compliant with the Thread Specification.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
OT_ERROR_NONE Successfully begin attempt to become a child.
OT_ERROR_INVALID_STATE Thread is disabled.
Referenced by Interpreter::SetUserCommands().
otThreadGetNextNeighborInfo()
otError otThreadGetNextNeighborInfo (otInstance * aInstance, otNeighborInfoIterator * aIterator, otNeighborInfo * aInfo)
This function gets the next neighbor information. It is used to go through the entries of the neighbor table.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the iterator context. To get the first neighbor entry it should be set to OT_NEIGHBOR_INFO_ITERATOR_INIT.
[out] aInfo A pointer to the neighbor information.
Return values
OT_ERROR_NONE Successfully found the next neighbor entry in table.
OT_ERROR_NOT_FOUND No subsequent neighbor entry exists in the table.
OT_ERROR_INVALID_ARGS aIterator or aInfo was NULL.
Referenced by Interpreter::SetUserCommands().
otThreadGetDeviceRole()
otDeviceRole otThreadGetDeviceRole (otInstance * aInstance)
Get the device role.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
OT_DEVICE_ROLE_DISABLED The Thread stack is disabled.
OT_DEVICE_ROLE_DETACHED The device is not currently participating in a Thread network/partition.
OT_DEVICE_ROLE_CHILD The device is currently operating as a Thread Child.
OT_DEVICE_ROLE_ROUTER The device is currently operating as a Thread Router.
OT_DEVICE_ROLE_LEADER The device is currently operating as a Thread Leader.
Referenced by NcpBase::HandlePropertyGet(), otSysGetThreadNetifIndex(), and Interpreter::SetUserCommands().
otThreadDeviceRoleToString()
const char* otThreadDeviceRoleToString (otDeviceRole aRole)
Convert the device role to human-readable string.
Parameters
[in] aRole The device role to convert.
Returns
A string representing aRole.
Referenced by Interpreter::SetUserCommands().
otThreadGetLeaderData()
otError otThreadGetLeaderData (otInstance * aInstance, otLeaderData * aLeaderData)
This function get the Thread Leader Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aLeaderData A pointer to where the leader data is placed.
Return values
OT_ERROR_NONE Successfully retrieved the leader data.
OT_ERROR_DETACHED Not currently attached.
Referenced by Interpreter::SetUserCommands().
otThreadGetLeaderRouterId()
uint8_t otThreadGetLeaderRouterId (otInstance * aInstance)
Get the Leader's Router ID.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Leader's Router ID.
otThreadGetLeaderWeight()
uint8_t otThreadGetLeaderWeight (otInstance * aInstance)
Get the Leader's Weight.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Leader's Weight.
otThreadGetPartitionId()
uint32_t otThreadGetPartitionId (otInstance * aInstance)
Get the Partition ID.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Partition ID.
Referenced by Interpreter::SetUserCommands().
otThreadGetRloc16()
uint16_t otThreadGetRloc16 (otInstance * aInstance)
Get the RLOC16.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The RLOC16.
Referenced by otSysGetThreadNetifIndex(), and Interpreter::SetUserCommands().
otThreadGetParentInfo()
otError otThreadGetParentInfo (otInstance * aInstance, otRouterInfo * aParentInfo)
The function retrieves diagnostic information for a Thread Router as parent.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aParentInfo A pointer to where the parent router information is placed.
Referenced by Interpreter::SetUserCommands().
otThreadGetParentAverageRssi()
otError otThreadGetParentAverageRssi (otInstance * aInstance, int8_t * aParentRssi)
The function retrieves the average RSSI for the Thread Parent.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aParentRssi A pointer to where the parent RSSI should be placed.
otThreadGetParentLastRssi()
otError otThreadGetParentLastRssi (otInstance * aInstance, int8_t * aLastRssi)
The function retrieves the RSSI of the last packet from the Thread Parent.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aLastRssi A pointer to where the last RSSI should be placed.
Return values
OT_ERROR_NONE Successfully retrieved the RSSI data.
OT_ERROR_FAILED Unable to get RSSI data.
OT_ERROR_INVALID_ARGS aLastRssi is NULL.
otThreadSearchForBetterParent()
otError otThreadSearchForBetterParent (otInstance * aInstance)
Starts the process for child to search for a better parent while staying attached to its current parent.
Must be used when device is attached as a child.
Return values
OT_ERROR_NONE Successfully started the process to search for a better parent.
OT_ERROR_INVALID_STATE Device role is not child.
Referenced by Interpreter::SetUserCommands().
otThreadGetIp6Counters()
const otIpCounters* otThreadGetIp6Counters (otInstance * aInstance)
Gets the IPv6 counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the IPv6 counters.
Referenced by Interpreter::SetUserCommands().
otThreadResetIp6Counters()
void otThreadResetIp6Counters (otInstance * aInstance)
Resets the IPv6 counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Referenced by Interpreter::SetUserCommands().
otThreadGetMleCounters()
const otMleCounters* otThreadGetMleCounters (otInstance * aInstance)
Gets the Thread MLE counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread MLE counters.
Referenced by Interpreter::SetUserCommands().
otThreadResetMleCounters()
void otThreadResetMleCounters (otInstance * aInstance)
Resets the Thread MLE counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Referenced by Interpreter::SetUserCommands().
otThreadRegisterParentResponseCallback()
void otThreadRegisterParentResponseCallback (otInstance * aInstance, otThreadParentResponseCallback aCallback, void * aContext)
This function registers a callback to receive MLE Parent Response data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aCallback A pointer to a function that is called upon receiving an MLE Parent Response message.
[in] aContext A pointer to callback client-specific context.
Referenced by NcpBase::NcpBase().
otThreadSetDiscoveryRequestCallback()
void otThreadSetDiscoveryRequestCallback (otInstance * aInstance, otThreadDiscoveryRequestCallback aCallback, void * aContext)
This function sets a callback to receive MLE Discovery Request data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aCallback A pointer to a function that is called upon receiving an MLE Discovery Request message.
[in] aContext A pointer to callback application-specific context.
Referenced by Interpreter::Interpreter().
otThreadLocateAnycastDestination()
otError otThreadLocateAnycastDestination (otInstance * aInstance, const otIp6Address * aAnycastAddress, otThreadAnycastLocatorCallback aCallback, void * aContext)
This function requests the closest destination of a given anycast address to be located.
This function is only available when OPENTHREAD_CONFIG_TMF_ANYCAST_LOCATOR_ENABLE is enabled.
If a previous request is ongoing, a subsequent call to this function will cancel and replace the earlier request.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aAnycastAddress The anycast address to locate. MUST NOT be NULL.
[in] aCallback The callback function to report the result.
[in] aContext An arbitrary context used with aCallback.
Return values
OT_ERROR_NONE The request started successfully. aCallback will be invoked to report the result.
OT_ERROR_INVALID_ARGS The aAnycastAddress is not a valid anycast address or aCallback is NULL.
OT_ERROR_NO_BUFS Out of buffer to prepare and send the request message.
Referenced by Interpreter::SetUserCommands().
otThreadIsAnycastLocateInProgress()
bool otThreadIsAnycastLocateInProgress (otInstance * aInstance)
This function indicates whether an anycast locate request is currently in progress.
This function is only available when OPENTHREAD_CONFIG_TMF_ANYCAST_LOCATOR_ENABLE is enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
TRUE if an anycast locate request is currently in progress, FALSE otherwise.
Referenced by Interpreter::SetUserCommands().
otThreadSendAddressNotification()
void otThreadSendAddressNotification (otInstance * aInstance, otIp6Address * aDestination, otIp6Address * aTarget, otIp6InterfaceIdentifier * aMlIid)
This function sends a Proactive Address Notification (ADDR_NTF.ntf) message.
This function is only available when OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE is enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDestination The destination to send the ADDR_NTF.ntf message.
[in] aTarget The target address of the ADDR_NTF.ntf message.
[in] aMlIid The ML-IID of the ADDR_NTF.ntf message.
Referenced by Interpreter::SetUserCommands().
otThreadSendProactiveBackboneNotification()
otError otThreadSendProactiveBackboneNotification (otInstance * aInstance, otIp6Address * aTarget, otIp6InterfaceIdentifier * aMlIid, uint32_t aTimeSinceLastTransaction)
This function sends a Proactive Backbone Notification (PRO_BB.ntf) message on the Backbone link.
This function is only available when OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE is enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aTarget The target address of the PRO_BB.ntf message.
[in] aMlIid The ML-IID of the PRO_BB.ntf message.
[in] aTimeSinceLastTransaction Time since last transaction (in seconds).
Return values
OT_ERROR_NONE Successfully sent PRO_BB.ntf on backbone link.
OT_ERROR_NO_BUFS If insufficient message buffers available.
Referenced by Interpreter::SetUserCommands().
otThreadDetachGracefully()
otError otThreadDetachGracefully (otInstance * aInstance, otDetachGracefullyCallback aCallback, void * aContext)
This function notifies other nodes in the network (if any) and then stops Thread protocol operation.
It sends an Address Release if it's a router, or sets its child timeout to 0 if it's a child.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aCallback A pointer to a function that is called upon finishing detaching.
[in] aContext A pointer to callback application-specific context.
Return values
OT_ERROR_NONE Successfully started detaching.
OT_ERROR_BUSY Detaching is already in progress.
Referenced by Interpreter::SetUserCommands().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale