OpenThread: Radio Configuration
Radio Configuration
Platform Abstraction » Radio
This module includes the platform abstraction for radio configuration.
Functions
uint32_t otPlatRadioGetBusSpeed (otInstance *aInstance)
otRadioCaps otPlatRadioGetCaps (otInstance *aInstance)
otError otPlatRadioGetCcaEnergyDetectThreshold (otInstance *aInstance, int8_t *aThreshold)
otError otPlatRadioGetFemLnaGain (otInstance *aInstance, int8_t *aGain)
void otPlatRadioGetIeeeEui64 (otInstance *aInstance, uint8_t *aIeeeEui64)
uint64_t otPlatRadioGetNow (otInstance *aInstance)
bool otPlatRadioGetPromiscuous (otInstance *aInstance)
int8_t otPlatRadioGetReceiveSensitivity (otInstance *aInstance)
otError otPlatRadioGetTransmitPower (otInstance *aInstance, int8_t *aPower)
const char * otPlatRadioGetVersionString (otInstance *aInstance)
otError otPlatRadioSetCcaEnergyDetectThreshold (otInstance *aInstance, int8_t aThreshold)
void otPlatRadioSetExtendedAddress (otInstance *aInstance, const otExtAddress *aExtAddress)
otError otPlatRadioSetFemLnaGain (otInstance *aInstance, int8_t aGain)
void otPlatRadioSetMacFrameCounter (otInstance *aInstance, uint32_t aMacFrameCounter)
void otPlatRadioSetMacKey (otInstance *aInstance, uint8_t aKeyIdMode, uint8_t aKeyId, const otMacKeyMaterial *aPrevKey, const otMacKeyMaterial *aCurrKey, const otMacKeyMaterial *aNextKey, otRadioKeyType aKeyType)
void otPlatRadioSetPanId (otInstance *aInstance, otPanId aPanId)
void otPlatRadioSetPromiscuous (otInstance *aInstance, bool aEnable)
void otPlatRadioSetShortAddress (otInstance *aInstance, otShortAddress aShortAddress)
otError otPlatRadioSetTransmitPower (otInstance *aInstance, int8_t aPower)
Detailed Description
This module includes the platform abstraction for radio configuration.
Function Documentation
otPlatRadioGetCaps()
otRadioCaps otPlatRadioGetCaps (otInstance * aInstance)
Get the radio capabilities.
Parameters
[in] aInstance The OpenThread instance structure.
Returns
The radio capability bit vector (see OT_RADIO_CAP_* definitions).
References RadioSpinel< InterfaceType, ProcessContextType >::GetRadioCaps(), and OT_UNUSED_VARIABLE.
Referenced by Radio::GetPreferredChannelMask().
otPlatRadioGetVersionString()
const char* otPlatRadioGetVersionString (otInstance * aInstance)
Get the radio version string.
This is an optional radio driver platform function. If not provided by platform radio driver, OpenThread uses the OpenThread version instead (
See also
otGetVersionString()).
Parameters
[in] aInstance The OpenThread instance structure.
Returns
A pointer to the OpenThread radio version.
References RadioSpinel< InterfaceType, ProcessContextType >::GetVersion(), OT_UNUSED_VARIABLE, and otGetVersionString().
Referenced by Radio::GetVersionString(), InitInstance(), and Interpreter::SetUserCommands().
otPlatRadioGetReceiveSensitivity()
int8_t otPlatRadioGetReceiveSensitivity (otInstance * aInstance)
Get the radio receive sensitivity value.
Parameters
[in] aInstance The OpenThread instance structure.
Returns
The radio receive sensitivity value in dBm.
References RadioSpinel< InterfaceType, ProcessContextType >::GetReceiveSensitivity(), OPENTHREAD_CONFIG_DIAG_CMD_LINE_BUFFER_SIZE, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_UNUSED_VARIABLE, otPlatDiagAlarmCallback(), otPlatDiagChannelSet(), otPlatDiagModeGet(), otPlatDiagModeSet(), otPlatDiagProcess(), otPlatDiagRadioReceived(), otPlatDiagTxPowerSet(), otPlatRadioGetCoexMetrics(), otPlatRadioIsCoexEnabled(), otPlatRadioSetCoexEnabled(), SuccessOrExit, and VerifyOrExit.
Referenced by Radio::GetPreferredChannelMask(), and NcpBase::HandlePropertyGet().
otPlatRadioGetIeeeEui64()
void otPlatRadioGetIeeeEui64 (otInstance * aInstance, uint8_t * aIeeeEui64)
Gets the factory-assigned IEEE EUI-64 for this interface.
Parameters
[in] aInstance The OpenThread instance structure.
[out] aIeeeEui64 A pointer to the factory-assigned IEEE EUI-64.
References RadioSpinel< InterfaceType, ProcessContextType >::GetIeeeEui64(), OT_UNUSED_VARIABLE, and SuccessOrDie.
Referenced by Radio::GetIeeeEui64(), and getSettingsFileName().
otPlatRadioSetPanId()
void otPlatRadioSetPanId (otInstance * aInstance, otPanId aPanId)
Set the PAN ID for address filtering.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aPanId The IEEE 802.15.4 PAN ID.
References OT_UNUSED_VARIABLE, RadioSpinel< InterfaceType, ProcessContextType >::SetPanId(), and SuccessOrDie.
Referenced by Radio::GetPreferredChannelMask().
otPlatRadioSetExtendedAddress()
void otPlatRadioSetExtendedAddress (otInstance * aInstance, const otExtAddress * aExtAddress)
Set the Extended Address for address filtering.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aExtAddress A pointer to the IEEE 802.15.4 Extended Address stored in little-endian byte order.
References otExtAddress::m8, OT_UNUSED_VARIABLE, RadioSpinel< InterfaceType, ProcessContextType >::SetExtendedAddress(), and SuccessOrDie.
otPlatRadioSetShortAddress()
void otPlatRadioSetShortAddress (otInstance * aInstance, otShortAddress aShortAddress)
Set the Short Address for address filtering.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aShortAddress The IEEE 802.15.4 Short Address.
References OT_UNUSED_VARIABLE, RadioSpinel< InterfaceType, ProcessContextType >::SetShortAddress(), and SuccessOrDie.
otPlatRadioGetTransmitPower()
otError otPlatRadioGetTransmitPower (otInstance * aInstance, int8_t * aPower)
Get the radio's transmit power in dBm.
Note
The transmit power returned will be no larger than the power specified in the max power table for the current channel.
Parameters
[in] aInstance The OpenThread instance structure.
[out] aPower The transmit power in dBm.
Return values
OT_ERROR_NONE Successfully retrieved the transmit power.
OT_ERROR_INVALID_ARGS aPower was NULL.
OT_ERROR_NOT_IMPLEMENTED Transmit power configuration via dBm is not implemented.
References RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitPower(), and OT_UNUSED_VARIABLE.
Referenced by Radio::GetPreferredChannelMask(), NcpBase::HandlePropertyGet(), and Interpreter::SetUserCommands().
otPlatRadioSetTransmitPower()
otError otPlatRadioSetTransmitPower (otInstance * aInstance, int8_t aPower)
Set the radio's transmit power in dBm.
Note
The real transmit power will be no larger than the power specified in the max power table for the current channel.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aPower The transmit power in dBm.
Return values
OT_ERROR_NONE Successfully set the transmit power.
OT_ERROR_NOT_IMPLEMENTED Transmit power configuration via dBm is not implemented.
References OT_UNUSED_VARIABLE, and RadioSpinel< InterfaceType, ProcessContextType >::SetTransmitPower().
Referenced by Radio::GetPreferredChannelMask(), NcpBase::HandlePropertySet(), and Interpreter::SetUserCommands().
otPlatRadioGetCcaEnergyDetectThreshold()
otError otPlatRadioGetCcaEnergyDetectThreshold (otInstance * aInstance, int8_t * aThreshold)
Get the radio's CCA ED threshold in dBm measured at antenna connector per IEEE 802.15.4 - 2015 section 10.1.4.
Parameters
[in] aInstance The OpenThread instance structure.
[out] aThreshold The CCA ED threshold in dBm.
Return values
OT_ERROR_NONE Successfully retrieved the CCA ED threshold.
OT_ERROR_INVALID_ARGS aThreshold was NULL.
OT_ERROR_NOT_IMPLEMENTED CCA ED threshold configuration via dBm is not implemented.
References RadioSpinel< InterfaceType, ProcessContextType >::GetCcaEnergyDetectThreshold(), and OT_UNUSED_VARIABLE.
Referenced by Radio::GetPreferredChannelMask(), NcpBase::HandlePropertyGet(), and Interpreter::SetUserCommands().
otPlatRadioSetCcaEnergyDetectThreshold()
otError otPlatRadioSetCcaEnergyDetectThreshold (otInstance * aInstance, int8_t aThreshold)
Set the radio's CCA ED threshold in dBm measured at antenna connector per IEEE 802.15.4 - 2015 section 10.1.4.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aThreshold The CCA ED threshold in dBm.
Return values
OT_ERROR_NONE Successfully set the transmit power.
OT_ERROR_INVALID_ARGS Given threshold is out of range.
OT_ERROR_NOT_IMPLEMENTED CCA ED threshold configuration via dBm is not implemented.
References OT_UNUSED_VARIABLE, and RadioSpinel< InterfaceType, ProcessContextType >::SetCcaEnergyDetectThreshold().
Referenced by Radio::GetPreferredChannelMask(), NcpBase::HandlePropertySet(), and Interpreter::SetUserCommands().
otPlatRadioGetFemLnaGain()
otError otPlatRadioGetFemLnaGain (otInstance * aInstance, int8_t * aGain)
Gets the external FEM's Rx LNA gain in dBm.
Parameters
[in] aInstance The OpenThread instance structure.
[out] aGain The external FEM's Rx LNA gain in dBm.
Return values
OT_ERROR_NONE Successfully retrieved the external FEM's LNA gain.
OT_ERROR_INVALID_ARGS aGain was NULL.
OT_ERROR_NOT_IMPLEMENTED External FEM's LNA setting is not implemented.
References RadioSpinel< InterfaceType, ProcessContextType >::GetFemLnaGain(), ot::kErrorNotImplemented, and OT_UNUSED_VARIABLE.
Referenced by NcpBase::HandlePropertyGet(), and Interpreter::SetUserCommands().
otPlatRadioSetFemLnaGain()
otError otPlatRadioSetFemLnaGain (otInstance * aInstance, int8_t aGain)
Sets the external FEM's Rx LNA gain in dBm.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aGain The external FEM's Rx LNA gain in dBm.
Return values
OT_ERROR_NONE Successfully set the external FEM's LNA gain.
OT_ERROR_NOT_IMPLEMENTED External FEM's LNA gain setting is not implemented.
References ot::kErrorNotImplemented, OT_UNUSED_VARIABLE, and RadioSpinel< InterfaceType, ProcessContextType >::SetFemLnaGain().
Referenced by NcpBase::HandlePropertySet(), and Interpreter::SetUserCommands().
otPlatRadioGetPromiscuous()
bool otPlatRadioGetPromiscuous (otInstance * aInstance)
Get the status of promiscuous mode.
Parameters
[in] aInstance The OpenThread instance structure.
Return values
TRUE Promiscuous mode is enabled.
FALSE Promiscuous mode is disabled.
References RadioSpinel< InterfaceType, ProcessContextType >::IsPromiscuous(), and OT_UNUSED_VARIABLE.
Referenced by Radio::GetPreferredChannelMask(), and Interpreter::SetUserCommands().
otPlatRadioSetPromiscuous()
void otPlatRadioSetPromiscuous (otInstance * aInstance, bool aEnable)
Enable or disable promiscuous mode.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aEnable TRUE to enable or FALSE to disable promiscuous mode.
References OT_UNUSED_VARIABLE, RadioSpinel< InterfaceType, ProcessContextType >::SetPromiscuous(), and SuccessOrDie.
Referenced by Radio::GetPreferredChannelMask().
otPlatRadioSetMacKey()
void otPlatRadioSetMacKey (otInstance * aInstance, uint8_t aKeyIdMode, uint8_t aKeyId, const otMacKeyMaterial * aPrevKey, const otMacKeyMaterial * aCurrKey, const otMacKeyMaterial * aNextKey, otRadioKeyType aKeyType)
Update MAC keys and key index
This function is used when radio provides OT_RADIO_CAPS_TRANSMIT_SEC capability.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKeyIdMode The key ID mode.
[in] aKeyId Current MAC key index.
[in] aPrevKey A pointer to the previous MAC key.
[in] aCurrKey A pointer to the current MAC key.
[in] aNextKey A pointer to the next MAC key.
[in] aKeyType Key Type used.
References OT_UNUSED_VARIABLE, RadioSpinel< InterfaceType, ProcessContextType >::SetMacKey(), and SuccessOrDie.
Referenced by Radio::GetPreferredChannelMask().
otPlatRadioSetMacFrameCounter()
void otPlatRadioSetMacFrameCounter (otInstance * aInstance, uint32_t aMacFrameCounter)
This method sets the current MAC frame counter value.
This function is used when radio provides OT_RADIO_CAPS_TRANSMIT_SEC capability.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aMacFrameCounter The MAC frame counter value.
References OT_UNUSED_VARIABLE, RadioSpinel< InterfaceType, ProcessContextType >::SetMacFrameCounter(), and SuccessOrDie.
Referenced by Radio::SetMacFrameCounter().
otPlatRadioGetNow()
uint64_t otPlatRadioGetNow (otInstance * aInstance)
Get the current estimated time (in microseconds) of the radio chip.
This microsecond timer must be a free-running timer. The timer must continue to advance with microsecond precision even when the radio is in the sleep state.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The current time in microseconds. UINT64_MAX when platform does not support or radio time is not ready.
References RadioSpinel< InterfaceType, ProcessContextType >::GetNow(), and OT_UNUSED_VARIABLE.
Referenced by SubMac::HandleTransmitDone(), SubMac::StartCsmaBackoff(), and SubMac::StateToString().
otPlatRadioGetBusSpeed()
uint32_t otPlatRadioGetBusSpeed (otInstance * aInstance)
Get the bus speed in bits/second between the host and the radio chip.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The bus speed in bits/second between the host and the radio chip. Return 0 when the MAC and above layer and Radio layer resides on the same chip.
References RadioSpinel< InterfaceType, ProcessContextType >::GetBusSpeed(), OT_UNUSED_VARIABLE, otPlatRadioGetCslAccuracy(), and otPlatRadioGetCslUncertainty().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale