OpenThread: Core-string
Core-string
This module includes definitions for OpenThread String class.
Data Structures
class String< kSize >
class Stringify
class StringWriter
Enumerations
enum StringMatchMode : uint8_t { kStringExactMatch, kStringCaseInsensitiveMatch }
Functions
constexpr bool AreStringsInOrder (const char *aFirst, const char *aSecond)
bool IsValidUtf8String (const char *aString)
bool IsValidUtf8String (const char *aString, size_t aLength)
void StringConvertToLowercase (char *aString)
void StringConvertToUppercase (char *aString)
bool StringEndsWith (const char *aString, char aChar)
bool StringEndsWith (const char *aString, const char *aSubString, StringMatchMode aMode)
const char * StringFind (const char *aString, char aChar)
const char * StringFind (const char *aString, const char *aSubString, StringMatchMode aMode)
uint16_t StringLength (const char *aString, uint16_t aMaxLength)
bool StringMatch (const char *aFirstString, const char *aSecondString, StringMatchMode aMode)
bool StringStartsWith (const char *aString, const char *aPrefixString, StringMatchMode aMode)
char ToLowercase (char aChar)
char ToUppercase (char aChar)
const char * ToYesNo (bool aBool)
Variables
static constexpr char kNullChar = '\0'
null character.
Detailed Description
This module includes definitions for OpenThread String class.
Enumeration Type Documentation
StringMatchMode
enum StringMatchMode : uint8_t
This enumeration represents comparison mode when matching strings.
Enumerator
kStringExactMatch
Exact match of characters.
kStringCaseInsensitiveMatch
Case insensitive match (uppercase and lowercase characters are treated as equal).
Function Documentation
StringLength()
uint16_t StringLength (const char * aString, uint16_t aMaxLength)
This function returns the number of characters that precede the terminating null character.
Parameters
[in] aString A pointer to the string.
[in] aMaxLength The maximum length in bytes.
Returns
The number of characters that precede the terminating null character or aMaxLength, whichever is smaller.
References ot::kNullChar.
Referenced by Name::AppendLabel(), TxtEntry::AppendTo(), Name::LabelIterator::CompareLabel(), NetworkName::GetAsData(), ot::MeshCoP::GetBorderAgentRloc(), JoinerPskd::GetLength(), JoinerPskd::IsPskdValid(), Name::IsSubDomainOf(), Interpreter::ProcessLine(), Decoder::ReadUtf8(), NetworkName::Set(), CommissionerIdTlv::SetCommissionerId(), JoinerPskd::SetFrom(), ProvisioningUrlTlv::SetProvisioningUrl(), VendorDataTlv::SetVendorData(), VendorModelTlv::SetVendorModel(), VendorNameTlv::SetVendorName(), VendorSwVersionTlv::SetVendorSwVersion(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
StringFind() [1/2]
const char * StringFind (const char * aString, char aChar)
This function finds the first occurrence of a given character in a null-terminated string.
Parameters
[in] aString A pointer to the string.
[in] aChar A char to search for in the string.
Returns
The pointer to first occurrence of the aChar in aString, or nullptr if cannot be found.
References ot::kNullChar.
Referenced by Message::AppendUriPathOptions(), ot::Utils::CmdLineParser::ParseAsBool(), and Name::LabelIterator::ReadLabel().
StringFind() [2/2]
const char * StringFind (const char * aString, const char * aSubString, StringMatchMode aMode = kStringExactMatch)
This function finds the first occurrence of a given sub-string in a null-terminated string.
Parameters
[in] aString A pointer to the string.
[in] aSubString A sub-string to search for.
[in] aMode The string comparison mode, exact match or case insensitive match.
Returns
The pointer to first match of the aSubString in aString (using comparison aMode), or nullptr if cannot be found.
References ExitNow, and VerifyOrExit.
StringStartsWith()
bool StringStartsWith (const char * aString, const char * aPrefixString, StringMatchMode aMode = kStringExactMatch)
This function checks whether a null-terminated string starts with a given prefix string.
Parameters
[in] aString A pointer to the string.
[in] aPrefixString A prefix string.
[in] aMode The string comparison mode, exact match or case insensitive match.
Return values
TRUE If aString starts with aPrefixString.
FALSE If aString does not start with aPrefixString.
Referenced by Name::IsSubDomainOf().
StringEndsWith() [1/2]
bool StringEndsWith (const char * aString, char aChar)
This function checks whether a null-terminated string ends with a given character.
Parameters
[in] aString A pointer to the string.
[in] aChar A char to check.
Return values
TRUE If aString ends with character aChar.
FALSE If aString does not end with character aChar.
StringEndsWith() [2/2]
bool StringEndsWith (const char * aString, const char * aSubString, StringMatchMode aMode = kStringExactMatch)
This function checks whether a null-terminated string ends with a given sub-string.
Parameters
[in] aString A pointer to the string.
[in] aSubString A sub-string to check against.
[in] aMode The string comparison mode, exact match or case insensitive match.
Return values
TRUE If aString ends with sub-string aSubString.
FALSE If aString does not end with sub-string aSubString.
StringMatch()
bool StringMatch (const char * aFirstString, const char * aSecondString, StringMatchMode aMode = kStringExactMatch)
This method checks whether or not two null-terminated strings match.
Parameters
[in] aFirstString A pointer to the first string.
[in] aSecondString A pointer to the second string.
[in] aMode The string comparison mode, exact match or case insensitive match.
Return values
TRUE If aFirstString matches aSecondString using match mode aMode.
FALSE If aFirstString does not match aSecondString using match mode aMode.
Referenced by Name::IsSubDomainOf().
StringConvertToLowercase()
void StringConvertToLowercase (char * aString)
This function converts all uppercase letter characters in a given string to lowercase.
Parameters
[in,out] aString A pointer to the string to convert.
References ot::kNullChar, and ot::ToLowercase().
Referenced by StringWriter::ConvertToLowercase().
StringConvertToUppercase()
void StringConvertToUppercase (char * aString)
This function converts all lowercase letter characters in a given string to uppercase.
Parameters
[in,out] aString A pointer to the string to convert.
References ot::kNullChar, and ot::ToUppercase().
Referenced by StringWriter::ConvertToUppercase().
ToLowercase()
char ToLowercase (char aChar)
This function converts an uppercase letter character to lowercase.
If aChar is uppercase letter it is converted lowercase. Otherwise, it remains unchanged.
Parameters
[in] aChar The character to convert
Returns
The character converted to lowercase.
Referenced by Name::LabelIterator::CaseInsensitiveMatch(), and ot::StringConvertToLowercase().
ToUppercase()
char ToUppercase (char aChar)
This function converts a lowercase letter character to uppercase.
If aChar is lowercase letter it is converted uppercase. Otherwise, it remains unchanged.
Parameters
[in] aChar The character to convert
Returns
The character converted to uppercase.
Referenced by ot::StringConvertToUppercase().
ToYesNo()
const char * ToYesNo (bool aBool)
This function coverts a boolean to "yes" or "no" string.
Parameters
[in] aBool A boolean value to convert.
Returns
The converted string representation of aBool ("yes" for TRUE and "no" for FALSE).
Referenced by MeshForwarder::CalcFrameVersion(), Mac::HandleTransmitDone(), RxFrame::ProcessReceiveAesCcm(), and DeviceMode::ToString().
IsValidUtf8String() [1/2]
bool IsValidUtf8String (const char * aString)
This function validates whether a given byte sequence (string) follows UTF-8 encoding. Control characters are not allowed.
Parameters
[in] aString A null-terminated byte sequence.
Return values
TRUE The sequence is a valid UTF-8 string.
FALSE The sequence is not a valid UTF-8 string.
Referenced by Mac::ConvertBeaconToActiveScanResult(), ot::MeshCoP::GetBorderAgentRloc(), NetworkNameTlv::IsValid(), and NetworkName::Set().
IsValidUtf8String() [2/2]
bool IsValidUtf8String (const char * aString, size_t aLength)
This function validates whether a given byte sequence (string) follows UTF-8 encoding. Control characters are not allowed.
Parameters
[in] aString A byte sequence.
[in] aLength Length of the sequence.
Return values
TRUE The sequence is a valid UTF-8 string.
FALSE The sequence is not a valid UTF-8 string.
References ExitNow, and VerifyOrExit.
AreStringsInOrder()
constexpr bool ot::AreStringsInOrder (const char * aFirst, const char * aSecond) inline
This constexpr function checks whether two given C strings are in order (alphabetical order).
This is intended for use from static_assert, e.g., checking if a lookup table entries are sorted. It is not recommended to use this function in other situations as it uses recursion so that it can be constexpr.
Parameters
[in] aFirst The first string.
[in] aSecond The second string.
Return values
TRUE If first string is strictly before second string (alphabetical order).
FALSE If first string is not strictly before second string (alphabetical order).
Referenced by OutputBase::CommandEntry< Cli >::AreInOrder().
Variable Documentation
kNullChar
constexpr char kNullChar = '\0' static
null character.
Referenced by Name::AppendMultipleLabels(), StringWriter::AppendVarArgs(), StringWriter::Clear(), Name::LabelIterator::CompareLabel(), Name::CompareName(), Address::FromString(), TxtEntry::Iterator::GetNextEntry(), Name::LabelIterator::ReadLabel(), Name::ReadName(), ot::StringConvertToLowercase(), ot::StringConvertToUppercase(), ot::StringFind(), ot::StringLength(), and StringWriter::StringWriter().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale