OpenThread: Core
Core
MLE
This module includes definitions for MLE functionality required by the Thread Child, Router, and Leader roles.
Data Structures
struct Mle::Challenge
struct Mle::DelayedResponseMetadata
class DeviceMode
class LeaderData
class Mle
class RouterIdSet
struct Mle::RxInfo
class Mle::RxMessage
class Mle::SecurityHeader
class Mle::TlvList
class Mle::TxMessage
Typedefs
typedef Mac::Key Key
typedef Mac::KeyMaterial KeyMaterial
Enumerations
enum AddressRegistrationMode : uint8_t { kAppendAllAddresses, kAppendMeshLocalOnly }
enum AnnounceMode : uint8_t { kNormalAnnounce, kOrphanAnnounce }
enum AttachMode : uint8_t {
kAnyPartition, kSamePartition, kSamePartitionRetry, kBetterPartition,
kDowngradeToReed, kBetterParent
}
enum AttachState : uint8_t {
kAttachStateIdle, kAttachStateProcessAnnounce, kAttachStateStart, kAttachStateParentRequest,
kAttachStateAnnounce, kAttachStateChildIdRequest
}
enum ChildDuaState : uint8_t { kAdded, kChanged, kRemoved, kUnchanged }
enum ChildUpdateRequestState : uint8_t { kChildUpdateRequestNone, kChildUpdateRequestPending, kChildUpdateRequestActive }
enum Class : uint8_t { kUnknown, kAuthoritativeMessage, kPeerMessage }
enum Command : uint8_t {
kCommandLinkRequest = 0, kCommandLinkAccept = 1, kCommandLinkAcceptAndRequest = 2, kCommandLinkReject = 3,
kCommandAdvertisement = 4, kCommandUpdate = 5, kCommandUpdateRequest = 6, kCommandDataRequest = 7,
kCommandDataResponse = 8, kCommandParentRequest = 9, kCommandParentResponse = 10, kCommandChildIdRequest = 11,
kCommandChildIdResponse = 12, kCommandChildUpdateRequest = 13, kCommandChildUpdateResponse = 14, kCommandAnnounce = 15,
kCommandDiscoveryRequest = 16, kCommandDiscoveryResponse = 17, kCommandLinkMetricsManagementRequest = 18, kCommandLinkMetricsManagementResponse = 19,
kCommandLinkProbe = 20, kCommandTimeSync = 99
}
enum DataRequestState : uint8_t { kDataRequestNone, kDataRequestActive }
enum DeviceRole : uint8_t {
kRoleDisabled = OT_DEVICE_ROLE_DISABLED, kRoleDetached = OT_DEVICE_ROLE_DETACHED, kRoleChild = OT_DEVICE_ROLE_CHILD, kRoleRouter = OT_DEVICE_ROLE_ROUTER,
kRoleLeader = OT_DEVICE_ROLE_LEADER
}
enum LeaderStartMode : uint8_t { kStartingAsLeader, kRestoringLeaderRoleAfterReset }
enum MessageAction : uint8_t { kMessageSend, kMessageReceive, kMessageDelay, kMessageRemoveDelayed }
enum MessageType : uint8_t {
kTypeAdvertisement, kTypeAnnounce, kTypeChildIdRequest, kTypeChildIdRequestShort,
kTypeChildIdResponse, kTypeChildUpdateRequestOfParent, kTypeChildUpdateResponseOfParent, kTypeDataRequest,
kTypeDataResponse, kTypeDiscoveryRequest, kTypeDiscoveryResponse, kTypeGenericDelayed,
kTypeGenericUdp, kTypeParentRequestToRouters, kTypeParentRequestToRoutersReeds, kTypeParentResponse
}
enum ParentRequestType : uint8_t { kToRouters, kToRoutersAndReeds }
enum ReattachState : uint8_t { kReattachStop, kReattachStart, kReattachActive, kReattachPending }
enum SecuritySuite : uint8_t { k154Security = 0, kNoSecurity = 255 }
enum StartMode : uint8_t { kNormalAttach, kAnnounceAttach }
enum StopMode : uint8_t { kKeepNetworkDatasets, kUpdateNetworkDatasets }
Functions
void Add (uint8_t aTlvType)
void AddElementsFrom (const TlvList &aTlvList)
Error AppendActiveTimestampTlv (void)
Error AppendAddress16Tlv (uint16_t aRloc16)
Error AppendAddressRegistrationTlv (AddressRegistrationMode aMode=kAppendAllAddresses)
Error AppendChallengeTlv (const uint8_t *aChallenge, uint8_t aChallengeLength)
Error AppendChallengeTlv (const Challenge &aChallenge)
Error AppendLeaderDataTlv (void)
Error AppendLinkFrameCounterTlv (void)
Error AppendLinkMarginTlv (uint8_t aLinkMargin)
Error AppendMleFrameCounterTlv (void)
Error AppendModeTlv (DeviceMode aMode)
Error AppendNetworkDataTlv (NetworkData::Type aType)
Error AppendPendingTimestampTlv (void)
Error AppendResponseTlv (const Challenge &aResponse)
Error AppendScanMaskTlv (uint8_t aScanMask)
Error AppendSourceAddressTlv (void)
Error AppendStatusTlv (StatusTlv::Status aStatus)
Error AppendTimeoutTlv (uint32_t aTimeout)
Error AppendTlvRequestTlv (const uint8_t *aTlvs, uint8_t aTlvsLength)
template<uint8_t kArrayLength>
Error AppendTlvRequestTlv (const uint8_t(&aTlvArray)[kArrayLength])
Error AppendTo (Message &aMessage) const
Error AppendVersionTlv (void)
Error AppendXtalAccuracyTlv (void)
void ApplyMeshLocalPrefix (void)
void Attach (AttachMode aMode)
Error BecomeChild (void)
Error BecomeDetached (void)
Error CheckReachability (uint16_t aMeshDest, const Ip6::Header &aIp6Header)
static uint16_t ChildIdFromRloc16 (uint16_t aRloc16)
static uint16_t CommissionerAloc16FromId (uint16_t aSessionId)
Error DetachGracefully (otDetachGracefullyCallback aCallback, void *aContext)
Error DetermineParentRequestType (ParentRequestType &aType) const
Error Disable (void)
Error Enable (void)
void GenerateRandom (void)
uint32_t GetAttachStartDelay (void) const
Error GetCommissionerAloc (Ip6::Address &aAddress, uint16_t aSessionId) const
const otMleCounters & GetCounters (void) const
DeviceMode GetDeviceMode (void) const
uint32_t GetFrameCounter (void) const
uint32_t GetKeyId (void) const
Error GetLeaderAddress (Ip6::Address &aAddress) const
Error GetLeaderAloc (Ip6::Address &aAddress) const
const LeaderData & GetLeaderData (void)
uint8_t GetLeaderId (void) const
const Ip6::Address & GetLinkLocalAddress (void) const
const Ip6::Address & GetLinkLocalAllThreadNodesAddress (void) const
Error GetLocatorAddress (Ip6::Address &aAddress, uint16_t aLocator) const
const Ip6::Address & GetMeshLocal16 (void) const
const Ip6::Address & GetMeshLocal64 (void) const
const Ip6::NetworkPrefix & GetMeshLocalPrefix (void) const
const MessageQueue & GetMessageQueue (void) const
NetworkData::Type GetNetworkDataType (void) const
Error GetNextAnnouceChannel (uint8_t &aChannel) const
Mac::ShortAddress GetNextHop (uint16_t aDestination) const
Parent & GetParent (void)
Parent & GetParentCandidate (void)
Error GetParentInfo (Router::Info &aParentInfo) const
const Ip6::Address & GetRealmLocalAllThreadNodesAddress (void) const
uint16_t GetRloc16 (void) const
DeviceRole GetRole (void) const
Error GetServiceAloc (uint8_t aServiceId, Ip6::Address &aAddress) const
uint32_t GetTimeout (void) const
void HandleAdvertisement (RxInfo &aRxInfo)
void HandleAnnounce (RxInfo &aRxInfo)
static void HandleAttachTimer (Timer &aTimer)
void HandleAttachTimer (void)
void HandleChildIdResponse (RxInfo &aRxInfo)
void HandleChildUpdateRequest (RxInfo &aRxInfo)
void HandleChildUpdateResponse (RxInfo &aRxInfo)
void HandleDataResponse (RxInfo &aRxInfo)
static void HandleDelayedResponseTimer (Timer &aTimer)
void HandleDelayedResponseTimer (void)
static void HandleDetachGracefullyTimer (Timer &aTimer)
void HandleDetachGracefullyTimer (void)
Error HandleLeaderData (RxInfo &aRxInfo)
static void HandleMessageTransmissionTimer (Timer &aTimer)
void HandleMessageTransmissionTimer (void)
void HandleNotifierEvents (Events aEvents)
void HandleParentResponse (RxInfo &aRxInfo)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
void HandleUdpReceive (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
bool HasAcceptableParentCandidate (void) const
bool HasMoreChannelsToAnnouce (void) const
bool HasRestored (void) const
bool HasUnregisteredAddress (void)
void InformPreviousChannel (void)
void InitSecurityControl (void)
static bool IsActiveRouter (uint16_t aRloc16)
bool IsAnnounceAttach (void) const
bool IsAnycastLocator (const Ip6::Address &aAddress) const
bool IsAttached (void) const
bool IsAttaching (void) const
bool IsBetterParent (uint16_t aRloc16, LinkQuality aLinkQuality, uint8_t aLinkMargin, const ConnectivityTlv &aConnectivityTlv, uint16_t aVersion, const Mac::CslAccuracy &aCslAccuracy)
bool IsChild (void) const
bool IsDetached (void) const
bool IsDetachingGracefully (void)
bool IsDisabled (void) const
bool IsFullThreadDevice (void) const
bool IsLeader (void) const
bool IsMeshLocalAddress (const Ip6::Address &aAddress) const
bool IsMinimalEndDevice (void) const
bool IsNetworkDataNewer (const LeaderData &aLeaderData)
bool IsRouter (void) const
bool IsRouterOrLeader (void) const
bool IsRoutingLocator (const Ip6::Address &aAddress) const
bool IsRxOnWhenIdle (void) const
bool IsSecurityControlValid (void) const
static void Log (MessageAction, MessageType, const Ip6::Address &)
static void Log (MessageAction, MessageType, const Ip6::Address &, uint16_t)
static void LogProcessError (MessageType, Error)
static void LogSendError (MessageType, Error)
bool Matches (const uint8_t *aBuffer, uint8_t aLength) const
Mle (Instance &aInstance)
TxMessage * NewMleMessage (Command aCommand)
bool operator== (const Challenge &aOther) const
bool PrepareAnnounceState (void)
void ProcessAnnounce (void)
Error ProcessMessageSecurity (Crypto::AesCcm::Mode aMode, Message &aMessage, const Ip6::MessageInfo &aMessageInfo, uint16_t aCmdOffset, const SecurityHeader &aHeader)
Error ReadChallengeOrResponse (uint8_t aTlvType, Challenge &aBuffer) const
Error ReadChallengeTlv (Challenge &aChallenge) const
Error ReadFrameCounterTlvs (uint32_t &aLinkFrameCounter, uint32_t &aMleFrameCounter) const
void ReadFrom (const Message &aMessage)
Error ReadLeaderDataTlv (LeaderData &aLeaderData) const
Error ReadResponseTlv (Challenge &aResponse) const
Error ReadTlvRequestTlv (TlvList &aTlvList) const
uint32_t Reattach (void)
void ReestablishLinkWithNeighbor (Neighbor &aNeighbor)
void RegisterParentResponseStatsCallback (otThreadParentResponseCallback aCallback, void *aContext)
void RemoveDelayedDataRequestMessage (const Ip6::Address &aDestination)
void RemoveDelayedDataResponseMessage (void)
void RemoveDelayedMessage (Message::SubType aSubType, MessageType aMessageType, const Ip6::Address *aDestination)
void RemoveFrom (Message &aMessage) const
void RequestShorterChildIdRequest (void)
void ResetCounters (void)
void Restore (void)
static uint16_t Rloc16FromRouterId (uint8_t aRouterId)
static const char * RoleToString (DeviceRole aRole)
static uint8_t RouterIdFromRloc16 (uint16_t aRloc16)
static bool RouterIdMatch (uint16_t aRloc16A, uint16_t aRloc16B)
RxInfo (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void ScheduleChildUpdateRequest (void)
void ScheduleMessageTransmissionTimer (void)
Error SearchForBetterParent (void)
Error SendAfterDelay (const Ip6::Address &aDestination, uint16_t aDelay)
void SendAnnounce (uint8_t aChannel)
void SendAnnounce (uint8_t aChannel, AnnounceMode aMode)
void SendAnnounce (uint8_t aChannel, const Ip6::Address &aDestination, AnnounceMode aMode=kNormalAnnounce)
Error SendChildIdRequest (void)
Error SendChildUpdateRequest (bool aAppendChallenge=false)
Error SendChildUpdateRequest (bool aAppendChallenge, uint32_t aTimeout)
Error SendChildUpdateResponse (const TlvList &aTlvList, const Challenge &aChallenge)
Error SendDataRequest (const Ip6::Address &aDestination, const uint8_t *aTlvs, uint8_t aTlvsLength, uint16_t aDelay, const uint8_t *aExtraTlvs, uint8_t aExtraTlvsLength)
template<uint8_t kArrayLength>
Error SendDataRequest (const Ip6::Address &aDestination, const uint8_t(&aTlvs)[kArrayLength], uint16_t aDelay=0)
void SendDelayedResponse (TxMessage &aMessage, const DelayedResponseMetadata &aMetadata)
void SendParentRequest (ParentRequestType aType)
Error SendTo (const Ip6::Address &aDestination)
static uint16_t ServiceAlocFromId (uint8_t aServiceId)
static uint8_t ServiceIdFromAloc (uint16_t aAloc16)
void SetAttachState (AttachState aState)
Error SetDeviceMode (DeviceMode aDeviceMode)
void SetFrameCounter (uint32_t aCounter)
void SetKeyId (uint32_t aKeySequence)
void SetLeaderData (uint32_t aPartitionId, uint8_t aWeighting, uint8_t aLeaderRouterId)
void SetMeshLocalPrefix (const Ip6::NetworkPrefix &aMeshLocalPrefix)
void SetRloc16 (uint16_t aRloc16)
void SetRole (DeviceRole aRole)
void SetStateChild (uint16_t aRloc16)
void SetStateDetached (void)
void SetTimeout (uint32_t aTimeout)
Error Start (void)
Error Start (StartMode aMode)
void Stop (void)
void Stop (StopMode aMode)
Error Store (void)
TlvList (void)=default
void UpdateLinkLocalAddress (void)
Variables
constexpr uint32_t kAdvertiseIntervalMax = 32
Max Advertise interval (in sec)
constexpr uint32_t kAdvertiseIntervalMin = 1
Min Advertise interval (in sec)
constexpr uint16_t kAloc16BackboneRouterPrimary = 0xfc38
constexpr uint16_t kAloc16CommissionerEnd = 0xfc37
constexpr uint16_t kAloc16CommissionerMask = 0x0007
constexpr uint16_t kAloc16CommissionerStart = 0xfc30
constexpr uint16_t kAloc16DhcpAgentEnd = 0xfc0f
constexpr uint16_t kAloc16DhcpAgentStart = 0xfc01
constexpr uint16_t kAloc16Leader = 0xfc00
constexpr uint16_t kAloc16NeighborDiscoveryAgentEnd = 0xfc4e
constexpr uint16_t kAloc16NeighborDiscoveryAgentStart = 0xfc40
constexpr uint16_t kAloc16ServiceEnd = 0xfc2f
constexpr uint16_t kAloc16ServiceStart = 0xfc10
constexpr uint32_t kAnnounceProcessTimeout = 250
Delay after Announce rx before channel/pan-id change.
constexpr uint32_t kAnnounceTimeout = 1400
Total timeout for sending Announce messages (in msec)
static constexpr uint32_t kAttachBackoffDelayToResetCounter
static constexpr uint32_t kAttachBackoffJitter = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_JITTER_INTERVAL
static constexpr uint32_t kAttachBackoffMaxInterval = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MAXIMUM_INTERVAL
static constexpr uint32_t kAttachBackoffMinInterval = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MINIMUM_INTERVAL
constexpr uint32_t kAttachStartJitter = 50
Max jitter time added to start of attach (in msec)
constexpr uint8_t kBackboneRouterRegistrationJitter = 5
In seconds.
constexpr uint32_t kChildUpdateRequestPendingDelay = 100
Delay for aggregating Child Update Req (in msec)
constexpr uint8_t kDefaultBackboneHoplimit = 1
default hoplimit for Backbone Link Protocol messages
static constexpr uint32_t kDetachGracefullyTimeout = 1000
constexpr uint32_t kDuaDadPeriod = 100
constexpr uint8_t kDuaDadRepeats = 3
constexpr uint32_t kDuaRecentTime = 20
constexpr uint8_t kFailedChildTransmissions = OPENTHREAD_CONFIG_FAILED_CHILD_TRANSMISSIONS
constexpr uint8_t kFailedRouterTransmissions = 4
static constexpr uint8_t kFirstAttachCycleNumParentRequestToRouters = 2
static constexpr uint8_t kFirstAttachCycleTotalParentRequests = 6
constexpr uint8_t kImmediateReRegisterDelay = 1
In seconds.
constexpr uint8_t kInvalidRouterId = kMaxRouterId + 1
Value indicating incorrect Router ID.
static constexpr uint8_t kKeyIdMode2Mic32 = (Mac::Frame::kKeyIdMode2 | Mac::Frame::kSecEncMic32)
constexpr uint8_t kLeaderWeight = 64
Default leader weight.
constexpr uint8_t kLinkAcceptMaxRouters = 20
Max Route TLV entries in a Link Accept message.
constexpr uint8_t kLinkAcceptSequenceRollback = 64
Route Sequence value rollback in a Link Accept message.
constexpr uint8_t kLinkQuality0LinkCost = kMaxRouteCost
Link Cost for Link Quality 0.
constexpr uint8_t kLinkQuality1LinkCost = 4
Link Cost for Link Quality 1.
constexpr uint8_t kLinkQuality2LinkCost = 2
Link Cost for Link Quality 2.
constexpr uint8_t kLinkQuality3LinkCost = 1
Link Cost for Link Quality 3.
constexpr uint8_t kMaxChallengeSize = 8
Maximum Challenge size in bytes.
constexpr uint16_t kMaxChildId = 511
Maximum Child ID.
constexpr uint32_t kMaxChildIdRequestTimeout = 5000
Max delay to rx a Child ID Request (in msec)
constexpr uint8_t kMaxChildKeepAliveAttempts = 4
Max keep alive attempts before reattach to a new Parent.
constexpr uint16_t kMaxChildren = OPENTHREAD_CONFIG_MLE_MAX_CHILDREN
constexpr uint32_t kMaxChildUpdateResponseTimeout = 2000
Max delay to rx a Child Update Response (in msec)
constexpr uint32_t kMaxLeaderToRouterTimeout = 90
(in sec)
constexpr uint32_t kMaxLinkRequestTimeout = 2000
Max delay to rx a Link Accept.
constexpr uint32_t kMaxNeighborAge = 100
(in sec)
constexpr uint32_t kMaxResponseDelay = 1000
Max response delay for a multicast request (in msec)
constexpr uint8_t kMaxRouteCost = 16
constexpr uint8_t kMaxRouterId = OT_NETWORK_MAX_ROUTER_ID
Max Router ID.
constexpr uint8_t kMaxRouters = OPENTHREAD_CONFIG_MLE_MAX_ROUTERS
constexpr uint8_t kMaxServiceAlocs = OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_MAX_ALOCS
static constexpr uint8_t kMaxTlvListSize = 16
Maximum number of TLVs in a TlvList.
constexpr uint8_t kMaxTransmissionCount = 3
Max number of times an MLE message may be transmitted.
constexpr uint8_t kMeshLocalPrefixContextId = 0
0 is reserved for Mesh Local Prefix
constexpr uint32_t kMinAnnounceDelay = 80
Min delay between Announcement messages (in msec)
constexpr uint8_t kMinChallengeSize = 4
Minimum Challenge size in bytes.
constexpr uint16_t kMinChildId = 1
Minimum Child ID.
constexpr uint8_t kMinDowngradeNeighbors = 7
constexpr uint32_t kMinPollPeriod = OPENTHREAD_CONFIG_MAC_MINIMUM_POLL_PERIOD
constexpr uint32_t kMinTimeout = OT_MAX(kMinTimeoutKeepAlive, kMinTimeoutDataPoll)
Min timeout (in sec)
constexpr uint32_t kMinTimeoutDataPoll = (kMinPollPeriod + kFailedChildTransmissions * kRetxPollPeriod) / 1000
constexpr uint32_t kMinTimeoutKeepAlive = (((kMaxChildKeepAliveAttempts + 1) * kUnicastRetransmissionDelay) / 1000)
constexpr uint32_t kMleEndDeviceTimeout = OPENTHREAD_CONFIG_MLE_CHILD_TIMEOUT_DEFAULT
(in sec)
static constexpr uint8_t kMleHopLimit = 255
static constexpr uint16_t kMleMaxResponseDelay = 1000u
Max delay before responding to a multicast request.
static constexpr uint8_t kMleSecurityTagSize = 4
constexpr uint32_t kMlrTimeoutDefault = 3600
In seconds.
constexpr uint32_t kMlrTimeoutMax = 0x7fffffff / 1000
In seconds (about 24 days).
constexpr uint32_t kMlrTimeoutMin = 300
In seconds.
constexpr uint8_t kMplChildDataMessageTimerExpirations = 0
Number of MPL retransmissions for Children.
constexpr uint8_t kMplRouterDataMessageTimerExpirations = 2
Number of MPL retransmissions for Routers.
constexpr uint8_t kMulticastLinkRequestDelay = 5
Max delay for sending a mcast Link Request (in sec)
constexpr uint8_t kNetworkIdTimeout = 120
(in sec)
static constexpr uint8_t kNextAttachCycleNumParentRequestToRouters = 1
static constexpr uint8_t kNextAttachCycleTotalParentRequests = 2
constexpr uint8_t kNoBufDelay = 5
In seconds.
constexpr uint8_t kParentAggregateDelay = 5
In seconds.
constexpr int8_t kParentPriorityHigh = 1
Parent Priority High.
constexpr int8_t kParentPriorityLow = -1
Parent Priority Low.
constexpr int8_t kParentPriorityMedium = 0
Parent Priority Medium (default)
constexpr int8_t kParentPriorityUnspecified = -2
Parent Priority Unspecified.
constexpr uint32_t kParentRequestDuplicateMargin = 50
Margin for duplicate parent request.
constexpr uint32_t kParentRequestReedTimeout = 1250
Router and REEDs Parent Request timeout (in msec)
constexpr uint32_t kParentRequestRouterTimeout = 750
Router Parent Request timeout (in msec)
constexpr uint32_t kParentResponseMaxDelayAll = 1000
Max response delay for Parent Req to all (in msec)
constexpr uint32_t kParentResponseMaxDelayRouters = 500
Max response delay for Parent Req to routers (in msec)
constexpr uint8_t kParentRouteToLeaderTimeout = 20
(in sec)
constexpr uint32_t kReedAdvertiseInterval = 570
(in sec)
constexpr uint32_t kReedAdvertiseJitter = 60
(in sec)
constexpr uint16_t kRegistrationDelayDefault = 5
In seconds.
constexpr uint8_t KResponseTimeoutDelay = 30
In seconds.
constexpr uint32_t kRetxPollPeriod = OPENTHREAD_CONFIG_MAC_RETX_POLL_PERIOD
constexpr uint8_t kRlocPrefixLength = 14
Prefix length of RLOC in bytes.
constexpr uint8_t kRouterDowngradeThreshold = 23
constexpr uint8_t kRouterIdOffset = 10
Bit offset of Router ID in RLOC16.
constexpr uint8_t kRouterIdReuseDelay = 100
(in sec)
constexpr uint32_t kRouterIdSequencePeriod = 10
(in sec)
constexpr uint8_t kRouterSelectionJitter = 120
(in sec)
constexpr uint8_t kRouterUpgradeBorderRouterRequestThreshold = 2
constexpr uint8_t kRouterUpgradeThreshold = 16
constexpr uint8_t kServiceMaxId = 0x0f
Maximal Service ID.
constexpr uint8_t kServiceMinId = 0x00
Minimal Service ID.
constexpr uint32_t kTimeSinceLastTransactionMax = 10 * 86400
In seconds (10 days).
constexpr uint16_t kUdpPort = 19788
MLE UDP Port.
constexpr uint32_t kUnicastRetransmissionDelay = 1000
Base delay before an MLE unicast retx (in msec)
AddressRegistrationMode mAddressRegistrationMode
uint8_t mAlternateChannel
uint16_t mAlternatePanId
uint64_t mAlternateTimestamp
uint8_t mAnnounceChannel
uint16_t mAnnounceDelay
Delay in between sending Announce messages during attach.
uint16_t mAttachCounter
Attach attempt counter.
AttachMode mAttachMode
AttachState mAttachState
The attach state.
TimerMilli mAttachTimer
The timer for driving the attach process.
uint8_t mBuffer [kMaxChallengeSize]
Buffer containing the challenge/response byte sequence.
uint8_t mChildUpdateAttempts
ChildUpdateRequestState mChildUpdateRequestState
Class mClass
The message class (authoritative, peer, or unknown).
otMleCounters mCounters
uint8_t mDataRequestAttempts
DataRequestState mDataRequestState
MessageQueue mDelayedResponses
TimerMilli mDelayedResponseTimer
The timer to delay MLE responses.
Ip6::Address mDestination
otDetachGracefullyCallback mDetachGracefullyCallback
void * mDetachGracefullyContext
TimerMilli mDetachGracefullyTimer
DeviceMode mDeviceMode
Device mode setting.
uint32_t mFrameCounter
The frame counter from aux security header.
uint32_t mFrameCounter
bool mHasRestored
uint8_t mKeyIndex
uint32_t mKeySequence
The key sequence from aux security header.
uint32_t mKeySource
Ip6::Netif::UnicastAddress mLeaderAloc
Leader anycast locator.
LeaderData mLeaderData
Last received Leader Data TLV.
uint8_t mLength
Challenge length (in bytes).
Ip6::Netif::UnicastAddress mLinkLocal64
Ip6::Netif::MulticastAddress mLinkLocalAllThreadNodes
Ip6::Netif::UnicastAddress mMeshLocal16
Ip6::Netif::UnicastAddress mMeshLocal64
RxMessage & mMessage
The MLE message.
const Ip6::MessageInfo & mMessageInfo
The MessageInfo associated with the message.
TimerMilli mMessageTransmissionTimer
The timer for (re-)sending of MLE messages (e.g. Child Update).
Neighbor * mNeighbor
Neighbor from which message was received (can be nullptr).
NeighborTable mNeighborTable
The neighbor table.
Parent mParent
Parent information.
Parent mParentCandidate
Parent candidate information.
Challenge mParentCandidateChallenge
bool mParentIsSingleton
uint8_t mParentLeaderCost
LeaderData mParentLeaderData
uint8_t mParentLinkMargin
uint8_t mParentLinkQuality1
uint8_t mParentLinkQuality2
uint8_t mParentLinkQuality3
int8_t mParentPriority
Challenge mParentRequestChallenge
uint8_t mParentRequestCounter
Number of parent requests while in kAttachStateParentRequest.
otThreadParentResponseCallback mParentResponseCb
void * mParentResponseCbContext
uint16_t mParentSedBufferSize
uint8_t mParentSedDatagramCount
uint16_t mPreviousParentRloc
Ip6::Netif::MulticastAddress mRealmLocalAllThreadNodes
ReattachState mReattachState
Reattach state.
bool mReceivedResponseFromParent
bool mRetrieveNewNetworkData
Indicating new Network Data is needed if set.
DeviceRole mRole
Current Thread role.
uint8_t mSecurityControl
TimeMilli mSendTime
Ip6::Udp::Socket mSocket
uint32_t mTimeout
OT_TOOL_PACKED_BEGIN class ot::Mle::Mle::SecurityHeader OT_TOOL_PACKED_END
static const otMeshLocalPrefix sMeshLocalPrefixInit
Friends
class DiscoverScanner
class ot::Notifier
Detailed Description
This module includes definitions for MLE functionality required by the Thread Child, Router, and Leader roles.
This module includes definition for MLE types and constants.
Typedef Documentation
KeyMaterial
typedef Mac::KeyMaterial KeyMaterial
This class represents a MLE Key Material
Key
typedef Mac::Key Key
This class represents a MLE Key.
Enumeration Type Documentation
Command
enum Command : uint8_t protected
MLE Command Types.
Enumerator
kCommandLinkRequest
Link Request.
kCommandLinkAccept
Link Accept.
kCommandLinkAcceptAndRequest
Link Accept and Reject.
kCommandLinkReject
Link Reject.
kCommandAdvertisement
Advertisement.
kCommandUpdate
Update.
kCommandUpdateRequest
Update Request.
kCommandDataRequest
Data Request.
kCommandDataResponse
Data Response.
kCommandParentRequest
Parent Request.
kCommandParentResponse
Parent Response.
kCommandChildIdRequest
Child ID Request.
kCommandChildIdResponse
Child ID Response.
kCommandChildUpdateRequest
Child Update Request.
kCommandChildUpdateResponse
Child Update Response.
kCommandAnnounce
Announce.
kCommandDiscoveryRequest
Discovery Request.
kCommandDiscoveryResponse
Discovery Response.
kCommandLinkMetricsManagementRequest
Link Metrics Management Request.
kCommandLinkMetricsManagementResponse
Link Metrics Management Response.
kCommandLinkProbe
Link Probe.
kCommandTimeSync
Time Sync (when OPENTHREAD_CONFIG_TIME_SYNC_ENABLE enabled)
AttachMode
enum AttachMode : uint8_t protected
Attach mode.
Enumerator
kAnyPartition
Attach to any Thread partition.
kSamePartition
Attach to the same Thread partition (attempt 1 when losing connectivity).
kSamePartitionRetry
Attach to the same Thread partition (attempt 2 when losing connectivity).
kBetterPartition
Attach to a better (i.e. higher weight/partition id) Thread partition.
kDowngradeToReed
Attach to the same Thread partition during downgrade process.
kBetterParent
Attach to a better parent.
AttachState
enum AttachState : uint8_t protected
States during attach (when searching for a parent).
Enumerator
kAttachStateIdle
Not currently searching for a parent.
kAttachStateProcessAnnounce
Waiting to process a received Announce (to switch channel/pan-id).
kAttachStateStart
Starting to look for a parent.
kAttachStateParentRequest
Send Parent Request (current number tracked by mParentRequestCounter).
kAttachStateAnnounce
Send Announce messages.
kAttachStateChildIdRequest
Sending a Child ID Request message.
ReattachState
enum ReattachState : uint8_t protected
States when reattaching network using stored dataset
Enumerator
kReattachStop
Reattach process is disabled or finished.
kReattachStart
Start reattach process.
kReattachActive
Reattach using stored Active Dataset.
kReattachPending
Reattach using stored Pending Dataset.
AddressRegistrationMode
enum AddressRegistrationMode : uint8_t protected
This enumeration type is used in AppendAddressRegistrationTlv() to determine which addresses to include in the appended Address Registration TLV.
Enumerator
kAppendAllAddresses
Append all addresses (unicast/multicast) in Address Registration TLV.
kAppendMeshLocalOnly
Only append the Mesh Local (ML-EID) address in Address Registration TLV.
MessageAction
enum MessageAction : uint8_t protected
This enumeration represents the message actions used in Log() methods.
Enumerator
kMessageSend
kMessageReceive
kMessageDelay
kMessageRemoveDelayed
MessageType
enum MessageType : uint8_t protected
This enumeration represents message types used in Log() methods.
Enumerator
kTypeAdvertisement
kTypeAnnounce
kTypeChildIdRequest
kTypeChildIdRequestShort
kTypeChildIdResponse
kTypeChildUpdateRequestOfParent
kTypeChildUpdateResponseOfParent
kTypeDataRequest
kTypeDataResponse
kTypeDiscoveryRequest
kTypeDiscoveryResponse
kTypeGenericDelayed
kTypeGenericUdp
kTypeParentRequestToRouters
kTypeParentRequestToRoutersReeds
kTypeParentResponse
Class
enum Class : uint8_t
This enumeration represents a received MLE message class.
Enumerator
kUnknown
Unknown (default value, also indicates MLE message parse error).
kAuthoritativeMessage
Authoritative message (larger received key seq MUST be adopted).
kPeerMessage
Peer message (adopt only if from a known neighbor and is greater by one).
StartMode
enum StartMode : uint8_t private
Enumerator
kNormalAttach
kAnnounceAttach
StopMode
enum StopMode : uint8_t private
Enumerator
kKeepNetworkDatasets
kUpdateNetworkDatasets
AnnounceMode
enum AnnounceMode : uint8_t private
Enumerator
kNormalAnnounce
kOrphanAnnounce
ParentRequestType
enum ParentRequestType : uint8_t private
Enumerator
kToRouters
kToRoutersAndReeds
ChildUpdateRequestState
enum ChildUpdateRequestState : uint8_t private
Enumerator
kChildUpdateRequestNone
kChildUpdateRequestPending
kChildUpdateRequestActive
DataRequestState
enum DataRequestState : uint8_t private
Enumerator
kDataRequestNone
kDataRequestActive
SecuritySuite
enum SecuritySuite : uint8_t private
Enumerator
k154Security
kNoSecurity
DeviceRole
enum DeviceRole : uint8_t
This type represents a Thread device role.
Enumerator
kRoleDisabled
The Thread stack is disabled.
kRoleDetached
Not currently participating in a Thread network/partition.
kRoleChild
The Thread Child role.
kRoleRouter
The Thread Router role.
kRoleLeader
The Thread Leader role.
LeaderStartMode
enum LeaderStartMode : uint8_t
This enumeration specifies the leader role start mode.
The start mode indicates whether device is starting normally as leader or restoring its role after reset.
Enumerator
kStartingAsLeader
Starting as leader normally.
kRestoringLeaderRoleAfterReset
Restoring leader role after reset.
ChildDuaState
enum ChildDuaState : uint8_t strong
State change of Child's DUA
Enumerator
kAdded
A new DUA registered by the Child via Address Registration.
kChanged
A different DUA registered by the Child via Address Registration.
kRemoved
DUA registered by the Child is removed and not in Address Registration.
kUnchanged
The Child registers the same DUA again.
Function Documentation
Mle()
Mle (Instance & aInstance) explicit
This constructor initializes the MLE object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ot::AsCoreType(), Clearable< Type >::Clear(), Parent::Clear(), InterfaceIdentifier::GenerateRandom(), Netif::UnicastAddress::GetAddress(), Netif::MulticastAddress::GetAddress(), Address::GetIid(), ot::Encoding::BigEndian::HostSwap16(), Parent::Init(), Netif::UnicastAddress::InitAsThreadOrigin(), Netif::UnicastAddress::InitAsThreadOriginRealmLocalScope(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::mFields, Mle::mLeaderAloc, Mle::mLeaderData, Mle::mLinkLocal64, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mParent, Mle::mParentCandidate, Mle::mParentLeaderData, Mle::mRealmLocalAllThreadNodes, otNetifAddress::mRloc, Mle::ResetCounters(), Mle::SetMeshLocalPrefix(), Address::SetToLinkLocalAddress(), InterfaceIdentifier::SetToLocator(), and Mle::sMeshLocalPrefixInit.
Enable()
Error Enable (void)
This method enables MLE.
Return values
kErrorNone Successfully enabled MLE.
kErrorAlready MLE was already enabled.
References Udp::Socket::Bind(), Mle::HandleUdpReceive(), ot::kErrorNone, ot::Mle::kUdpPort, Mle::mSocket, Udp::Socket::Open(), SuccessOrExit, and Mle::UpdateLinkLocalAddress().
Disable()
Error Disable (void)
This method disables MLE.
Return values
kErrorNone Successfully disabled MLE.
References Udp::Socket::Close(), ot::kErrorNone, Mle::kKeepNetworkDatasets, Mle::mLinkLocal64, Mle::mSocket, Mle::Stop(), and SuccessOrExit.
Start() [1/2]
Error Start (void) inline
This method starts the MLE protocol operation.
Return values
kErrorNone Successfully started the protocol operation.
kErrorInvalidState IPv6 interface is down or device is in raw-link mode.
References Mle::kNormalAttach, and Mle::Start().
Referenced by Mle::ProcessAnnounce(), and Mle::Start().
Stop() [1/2]
void Stop (void) inline
This method stops the MLE protocol operation.
References Mle::kUpdateNetworkDatasets, Mle::Restore(), Mle::Stop(), and Mle::Store().
Referenced by Mle::Disable(), Mle::HandleChildUpdateResponse(), Mle::HandleDetachGracefullyTimer(), Mle::ProcessAnnounce(), and Mle::Stop().
Restore()
void Restore (void)
This method restores network information from non-volatile memory (if any).
References Parent::Clear(), ExitNow, Netif::UnicastAddress::GetAddress(), SettingsBase::NetworkInfo::GetDeviceMode(), SettingsBase::NetworkInfo::GetExtAddress(), SettingsBase::ParentInfo::GetExtAddress(), SettingsBase::NetworkInfo::GetKeySequence(), SettingsBase::NetworkInfo::GetMacFrameCounter(), SettingsBase::NetworkInfo::GetMeshLocalIid(), SettingsBase::NetworkInfo::GetMleFrameCounter(), SettingsBase::NetworkInfo::GetPreviousPartitionId(), SettingsBase::NetworkInfo::GetRloc16(), Neighbor::GetRloc16(), Mle::GetRloc16(), SettingsBase::NetworkInfo::GetRole(), SettingsBase::NetworkInfo::GetVersion(), SettingsBase::ParentInfo::GetVersion(), IgnoreError(), Mle::IsActiveRouter(), ot::kErrorNone, DeviceMode::kModeFullNetworkData, DeviceMode::kModeFullThreadDevice, DeviceMode::kModeRxOnWhenIdle, ot::Mle::kRoleChild, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, ot::Mac::kShortAddrInvalid, Neighbor::kStateRestored, ot::kThreadVersion, LogWarn, Mle::mDeviceMode, Mle::mHasRestored, Mle::mMeshLocal64, Mle::mParent, Mle::mPreviousParentRloc, Mle::Rloc16FromRouterId(), Mle::RouterIdFromRloc16(), DeviceMode::Set(), Neighbor::SetDeviceMode(), Neighbor::SetExtAddress(), Address::SetIid(), Neighbor::SetRloc16(), Neighbor::SetState(), Neighbor::SetVersion(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::Attach(), Mle::Reattach(), and Mle::Stop().
Store()
Error Store (void)
This method stores network information into non-volatile memory.
Return values
kErrorNone Successfully store the network information.
kErrorNoBufs Could not store the network information due to insufficient memory space.
References DeviceMode::Get(), Netif::UnicastAddress::GetAddress(), Neighbor::GetExtAddress(), Address::GetIid(), SettingsBase::NetworkInfo::GetMacFrameCounter(), SettingsBase::NetworkInfo::GetMleFrameCounter(), LeaderData::GetPartitionId(), Mle::GetRloc16(), Neighbor::GetVersion(), SettingsBase::NetworkInfo::Init(), SettingsBase::ParentInfo::Init(), Mle::IsAttached(), Mle::IsChild(), ot::kErrorNone, ot::kThreadVersion, LogDebg, Mle::mDeviceMode, Mle::mLeaderData, Mle::mMeshLocal64, Mle::mParent, Mle::mRole, OPENTHREAD_CONFIG_STORE_FRAME_COUNTER_AHEAD, SettingsBase::NetworkInfo::SetDeviceMode(), SettingsBase::NetworkInfo::SetExtAddress(), SettingsBase::ParentInfo::SetExtAddress(), SettingsBase::NetworkInfo::SetKeySequence(), SettingsBase::NetworkInfo::SetMacFrameCounter(), SettingsBase::NetworkInfo::SetMeshLocalIid(), SettingsBase::NetworkInfo::SetMleFrameCounter(), SettingsBase::NetworkInfo::SetPreviousPartitionId(), SettingsBase::NetworkInfo::SetRloc16(), SettingsBase::NetworkInfo::SetRole(), SettingsBase::NetworkInfo::SetVersion(), SettingsBase::ParentInfo::SetVersion(), and SuccessOrExit.
Referenced by Mle::HandleNotifierEvents(), Mle::SetDeviceMode(), and Mle::Stop().
SendAnnounce() [1/3]
void SendAnnounce (uint8_t aChannel) inline
This method generates an MLE Announce message.
Parameters
[in] aChannel The channel to use when transmitting.
References Mle::BecomeChild(), Mle::BecomeDetached(), Mle::DetachGracefully(), Mle::IsAttached(), Mle::kNormalAnnounce, and Mle::SendAnnounce().
Referenced by Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::InformPreviousChannel(), Mle::IsDetachingGracefully(), and Mle::SendAnnounce().
BecomeDetached()
Error BecomeDetached (void)
This method causes the Thread interface to detach from the Thread network.
Return values
kErrorNone Successfully detached from the Thread network.
kErrorInvalidState MLE is Disabled.
References Mle::Attach(), Mle::IsDetached(), Mle::IsDisabled(), Mle::kAnyPartition, Mle::kAttachStateStart, ot::kErrorInvalidState, ot::kErrorNone, Mle::kReattachStop, ot::Mac::kShortAddrInvalid, Neighbor::kStateInvalid, Mle::mAttachState, Mle::mParent, Mle::mReattachState, Mle::SetRloc16(), Neighbor::SetState(), Mle::SetStateDetached(), and VerifyOrExit.
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::Reattach(), Mle::SendAnnounce(), Mle::SendChildUpdateRequest(), and Mle::SetDeviceMode().
BecomeChild()
Error BecomeChild (void)
This method causes the Thread interface to attempt an MLE attach.
Return values
kErrorNone Successfully began the attach process.
kErrorInvalidState MLE is Disabled.
kErrorBusy An attach process is in progress.
References Mle::Attach(), Mle::IsAttaching(), Mle::IsDisabled(), Mle::kAnyPartition, ot::kErrorBusy, ot::kErrorInvalidState, ot::kErrorNone, and VerifyOrExit.
Referenced by Mle::SendAnnounce().
DetachGracefully()
Error DetachGracefully (otDetachGracefullyCallback aCallback, void * aContext)
This function notifies other nodes in the network (if any) and then stops Thread protocol operation.
It sends an Address Release if it's a router, or sets its child timeout to 0 if it's a child.
Parameters
[in] aCallback A pointer to a function that is called upon finishing detaching.
[in] aContext A pointer to callback application-specific context.
Return values
kErrorNone Successfully started detaching.
kErrorBusy Detaching is already in progress.
References IgnoreError(), Mle::IsChild(), Mle::IsDetachingGracefully(), Mle::IsRouter(), Mle::kDetachGracefullyTimeout, ot::kErrorBusy, ot::kErrorNone, Mle::mDetachGracefullyCallback, Mle::mDetachGracefullyContext, Mle::mDetachGracefullyTimer, OT_ASSERT, Mle::SendChildUpdateRequest(), TimerMilli::Start(), and VerifyOrExit.
Referenced by Mle::SendAnnounce().
IsAttached()
bool IsAttached (void) const
This method indicates whether or not the Thread device is attached to a Thread network.
Return values
TRUE Attached to a Thread network.
FALSE Not attached to a Thread network.
References Mle::IsChild(), Mle::IsLeader(), and Mle::IsRouter().
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::HandleNotifierEvents(), Mle::HandleParentResponse(), Mle::ReestablishLinkWithNeighbor(), Mle::SendAnnounce(), and Mle::Store().
IsAttaching()
bool IsAttaching (void) const inline
This method indicates whether device is currently attaching or not.
Note that an already attached device may also be in attaching state. Examples of this include a leader/router trying to attach to a better partition, or a child trying to find a better parent (when feature OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE is enabled).
Return values
TRUE Device is currently trying to attach.
FALSE Device is not in middle of attach process.
References Mle::kAttachStateIdle, and Mle::mAttachState.
Referenced by Mle::Attach(), and Mle::BecomeChild().
GetRole()
DeviceRole GetRole (void) const inline
This method returns the current Thread device role.
Returns
The current Thread device role.
References Mle::mRole.
IsDisabled()
bool IsDisabled (void) const inline
This method indicates whether device role is disabled.
Return values
TRUE Device role is disabled.
FALSE Device role is not disabled.
References ot::Mle::kRoleDisabled, and Mle::mRole.
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::Attach(), Mle::BecomeChild(), Mle::BecomeDetached(), Mle::HandleNotifierEvents(), Mle::HandleUdpReceive(), and Mle::Stop().
IsDetached()
bool IsDetached (void) const inline
This method indicates whether device role is detached.
Return values
TRUE Device role is detached.
FALSE Device role is not detached.
References ot::Mle::kRoleDetached, and Mle::mRole.
Referenced by Mle::Attach(), Mle::BecomeDetached(), Mle::GetAttachStartDelay(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleParentResponse(), and Mle::SendChildUpdateRequest().
IsChild()
bool IsChild (void) const inline
This method indicates whether device role is child.
Return values
TRUE Device role is child.
FALSE Device role is not child.
References ot::Mle::kRoleChild, and Mle::mRole.
Referenced by Mle::CheckReachability(), Mle::DetachGracefully(), Mle::GetParentInfo(), Mle::HandleLeaderData(), Mle::HandleMessageTransmissionTimer(), Mle::HandleNotifierEvents(), Mle::HandleParentResponse(), Mle::HasAcceptableParentCandidate(), Mle::InformPreviousChannel(), Mle::IsAttached(), Mle::PrepareAnnounceState(), Mle::Reattach(), Mle::ReestablishLinkWithNeighbor(), Mle::ScheduleMessageTransmissionTimer(), Mle::SearchForBetterParent(), Mle::SendChildIdRequest(), Mle::SendDataRequest(), Mle::SetRole(), Mle::SetTimeout(), and Mle::Store().
IsRouter()
bool IsRouter (void) const inline
This method indicates whether device role is router.
Return values
TRUE Device role is router.
FALSE Device role is not router.
References ot::Mle::kRoleRouter, and Mle::mRole.
Referenced by Mle::DetachGracefully(), Mle::InformPreviousChannel(), Mle::IsAttached(), and Mle::IsRouterOrLeader().
IsLeader()
bool IsLeader (void) const inline
This method indicates whether device role is leader.
Return values
TRUE Device role is leader.
FALSE Device role is not leader.
References Mle::IsRouterOrLeader(), ot::Mle::kRoleLeader, and Mle::mRole.
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::HandleLeaderData(), Mle::IsAttached(), Mle::IsRouterOrLeader(), Mle::SetStateChild(), and Mle::SetStateDetached().
IsRouterOrLeader()
bool IsRouterOrLeader (void) const
This method indicates whether device role is either router or leader.
Return values
TRUE Device role is either router or leader.
FALSE Device role is neither router nor leader.
References Mle::IsLeader(), and Mle::IsRouter().
Referenced by Mle::HandleUdpReceive(), and Mle::IsLeader().
GetDeviceMode()
DeviceMode GetDeviceMode (void) const inline
This method returns the Device Mode as reported in the Mode TLV.
Returns
The Device Mode as reported in the Mode TLV.
References Mle::mDeviceMode, and Mle::SetDeviceMode().
SetDeviceMode()
Error SetDeviceMode (DeviceMode aDeviceMode)
This method sets the Device Mode as reported in the Mode TLV.
Parameters
[in] aDeviceMode The device mode to set.
Return values
kErrorNone Successfully set the Mode TLV.
kErrorInvalidArgs The mode combination specified in aMode is invalid.
References String< kSize >::AsCString(), Mle::Attach(), Mle::BecomeDetached(), DeviceMode::Get(), Mle::GetRloc16(), IgnoreError(), DeviceMode::IsFullThreadDevice(), DeviceMode::IsValid(), Mle::kAnyPartition, ot::kErrorInvalidArgs, ot::kErrorNone, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, LogNote, Mle::mAttachCounter, Mle::mDeviceMode, Mle::mRole, Mle::SendChildUpdateRequest(), Mle::SetStateChild(), Mle::SetStateDetached(), Mle::Store(), DeviceMode::ToString(), and VerifyOrExit.
Referenced by Mle::GetDeviceMode().
IsRxOnWhenIdle()
bool IsRxOnWhenIdle (void) const inline
This method indicates whether or not the device is rx-on-when-idle.
Returns
TRUE if rx-on-when-idle, FALSE otherwise.
References DeviceMode::IsRxOnWhenIdle(), and Mle::mDeviceMode.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), Mle::Attach(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleMessageTransmissionTimer(), Mle::HandleNotifierEvents(), Mle::HasUnregisteredAddress(), Mle::IsBetterParent(), Mle::Reattach(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendDataRequest(), and Mle::SendDelayedResponse().
IsFullThreadDevice()
bool IsFullThreadDevice (void) const inline
This method indicates whether or not the device is a Full Thread Device.
Returns
TRUE if a Full Thread Device, FALSE otherwise.
References DeviceMode::IsFullThreadDevice(), and Mle::mDeviceMode.
Referenced by Mle::Attach(), Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleNotifierEvents(), Mle::HandleParentResponse(), Mle::InformPreviousChannel(), Mle::PrepareAnnounceState(), Mle::Reattach(), Mle::ReestablishLinkWithNeighbor(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), and Mle::SetStateChild().
IsMinimalEndDevice()
bool IsMinimalEndDevice (void) const inline
This method indicates whether or not the device is a Minimal End Device.
Returns
TRUE if the device is a Minimal End Device, FALSE otherwise.
References DeviceMode::IsMinimalEndDevice(), and Mle::mDeviceMode.
GetNetworkDataType()
NetworkData::Type GetNetworkDataType (void) const inline
This method gets the Network Data type (full set or stable subset) that this device requests.
Returns
The Network Data type requested by this device.
References DeviceMode::GetNetworkDataType(), and Mle::mDeviceMode.
Referenced by Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), and Mle::IsNetworkDataNewer().
GetMeshLocalPrefix()
const Ip6::NetworkPrefix& GetMeshLocalPrefix (void) const inline
This method returns a pointer to the Mesh Local Prefix.
Returns
A reference to the Mesh Local Prefix.
References Mle::ApplyMeshLocalPrefix(), Netif::UnicastAddress::GetAddress(), Address::GetPrefix(), Mle::mMeshLocal16, and Mle::SetMeshLocalPrefix().
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::GetLeaderAddress(), Mle::GetServiceAloc(), Mle::IsMeshLocalAddress(), and Mle::SetMeshLocalPrefix().
SetMeshLocalPrefix()
void SetMeshLocalPrefix (const Ip6::NetworkPrefix & aMeshLocalPrefix)
This method sets the Mesh Local Prefix.
Parameters
[in] aMeshLocalPrefix A reference to the Mesh Local Prefix.
References Mle::ApplyMeshLocalPrefix(), Netif::UnicastAddress::GetAddress(), Mle::GetMeshLocalPrefix(), ot::kErrorInvalidState, ot::kErrorNone, ot::kEventThreadMeshLocalAddrChanged, Mle::mLeaderAloc, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mRealmLocalAllThreadNodes, Address::SetIid(), Address::SetPrefix(), and VerifyOrExit.
Referenced by Mle::GetMeshLocalPrefix(), and Mle::Mle().
ApplyMeshLocalPrefix()
void ApplyMeshLocalPrefix (void)
This method applies the Mesh Local Prefix.
References Netif::MulticastAddress::GetAddress(), Mle::GetMeshLocalPrefix(), Mle::IsAttached(), Mle::IsDisabled(), Mle::IsLeader(), ot::kEventThreadMeshLocalAddrChanged, Mle::mLeaderAloc, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mRealmLocalAllThreadNodes, Address::SetMulticastNetworkPrefix(), and VerifyOrExit.
Referenced by Mle::GetMeshLocalPrefix(), Mle::SetMeshLocalPrefix(), and Mle::Start().
GetLinkLocalAddress()
const Ip6::Address& GetLinkLocalAddress (void) const inline
This method returns a reference to the Thread link-local address.
The Thread link local address is derived using IEEE802.15.4 Extended Address as Interface Identifier.
Returns
A reference to the Thread link local address.
References Netif::UnicastAddress::GetAddress(), Mle::mLinkLocal64, and Mle::UpdateLinkLocalAddress().
UpdateLinkLocalAddress()
void UpdateLinkLocalAddress (void)
This method updates the link local address.
Call this method when the IEEE 802.15.4 Extended Address has changed.
References Netif::UnicastAddress::GetAddress(), Address::GetIid(), ot::kEventThreadLinkLocalAddrChanged, Mle::mLinkLocal64, and InterfaceIdentifier::SetFromExtAddress().
Referenced by Mle::Enable(), and Mle::GetLinkLocalAddress().
GetLinkLocalAllThreadNodesAddress()
const Ip6::Address& GetLinkLocalAllThreadNodesAddress (void) const inline
This method returns a reference to the link-local all Thread nodes multicast address.
Returns
A reference to the link-local all Thread nodes multicast address.
References Netif::MulticastAddress::GetAddress(), and Mle::mLinkLocalAllThreadNodes.
GetRealmLocalAllThreadNodesAddress()
const Ip6::Address& GetRealmLocalAllThreadNodesAddress (void) const inline
This method returns a reference to the realm-local all Thread nodes multicast address.
Returns
A reference to the realm-local all Thread nodes multicast address.
References Netif::MulticastAddress::GetAddress(), and Mle::mRealmLocalAllThreadNodes.
GetParent()
Parent& GetParent (void) inline
This method gets the parent when operating in End Device mode.
Returns
A reference to the parent.
References Mle::GetParentInfo(), and Mle::mParent.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), Mle::CheckReachability(), NeighborTable::FindParent(), and Mle::HandleNotifierEvents().
GetParentInfo()
Error GetParentInfo (Router::Info & aParentInfo) const
The method retrieves information about the parent.
Parameters
[out] aParentInfo Reference to a parent information structure.
Return values
kErrorNone Successfully retrieved the parent info and updated aParentInfo.
kErrorInvalidState Device role is not child.
References ExitNow, Mle::IsChild(), ot::kErrorInvalidState, ot::kErrorNone, Mle::mParent, Router::Info::SetFrom(), and VerifyOrExit.
Referenced by Mle::GetParent().
GetParentCandidate()
Parent& GetParentCandidate (void) inline
This method get the parent candidate.
The parent candidate is valid when attempting to attach to a new parent.
References Mle::IsAnycastLocator(), Mle::IsMeshLocalAddress(), Mle::IsRoutingLocator(), Mle::mParentCandidate, and Mle::SearchForBetterParent().
Referenced by NeighborTable::FindParent().
SearchForBetterParent()
Error SearchForBetterParent (void)
This method starts the process for child to search for a better parent while staying attached to its current parent
Return values
kErrorNone Successfully started the process to search for a better parent.
kErrorInvalidState Device role is not child.
References Mle::Attach(), Mle::IsChild(), Mle::kBetterParent, ot::kErrorInvalidState, ot::kErrorNone, and VerifyOrExit.
Referenced by Mle::GetParentCandidate().
IsRoutingLocator()
bool IsRoutingLocator (const Ip6::Address & aAddress) const
This method indicates whether or not an IPv6 address is an RLOC.
Return values
TRUE If aAddress is an RLOC.
FALSE If aAddress is not an RLOC.
References Address::GetIid(), Mle::IsMeshLocalAddress(), and InterfaceIdentifier::IsRoutingLocator().
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), Mle::GetParentCandidate(), and Mle::HasUnregisteredAddress().
IsAnycastLocator()
bool IsAnycastLocator (const Ip6::Address & aAddress) const
This method indicates whether or not an IPv6 address is an ALOC.
Return values
TRUE If aAddress is an ALOC.
FALSE If aAddress is not an ALOC.
References Address::GetIid(), InterfaceIdentifier::IsAnycastLocator(), and Mle::IsMeshLocalAddress().
Referenced by Mle::GetParentCandidate(), and Mle::HasUnregisteredAddress().
IsMeshLocalAddress()
bool IsMeshLocalAddress (const Ip6::Address & aAddress) const
This method indicates whether or not an IPv6 address is a Mesh Local Address.
Return values
TRUE If aAddress is a Mesh Local Address.
FALSE If aAddress is not a Mesh Local Address.
References Mle::GetMeshLocalPrefix(), and Address::GetPrefix().
Referenced by Mle::GetParentCandidate(), Mle::IsAnycastLocator(), and Mle::IsRoutingLocator().
GetTimeout()
uint32_t GetTimeout (void) const inline
This method returns the MLE Timeout value.
Returns
The MLE Timeout value in seconds.
References Mle::GetRloc16(), Mle::mTimeout, and Mle::SetTimeout().
Referenced by Mle::TxMessage::AppendPendingTimestampTlv().
SetTimeout()
void SetTimeout (uint32_t aTimeout)
This method sets the MLE Timeout value.
Parameters
[in] aTimeout The Timeout value in seconds.
References IgnoreError(), Mle::IsChild(), ot::Mle::kMinTimeout, Mle::mTimeout, Mle::SendChildUpdateRequest(), and VerifyOrExit.
Referenced by Mle::GetTimeout().
GetRloc16()
uint16_t GetRloc16 (void) const
This method returns the RLOC16 assigned to the Thread interface.
Returns
The RLOC16 assigned to the Thread interface.
Referenced by Mle::TxMessage::AppendSourceAddressTlv(), Mle::CheckReachability(), Mle::GetLeaderAddress(), Mle::GetLocatorAddress(), Mle::GetServiceAloc(), Mle::GetTimeout(), Mle::HandleChildUpdateResponse(), Mle::HandleNotifierEvents(), Mle::Restore(), Mle::SetDeviceMode(), Mle::SetRloc16(), Mle::Start(), and Mle::Store().
GetMeshLocal16()
const Ip6::Address& GetMeshLocal16 (void) const inline
This method returns a reference to the RLOC assigned to the Thread interface.
Returns
A reference to the RLOC assigned to the Thread interface.
References Netif::UnicastAddress::GetAddress(), and Mle::mMeshLocal16.
Referenced by Mle::CheckReachability().
GetMeshLocal64()
const Ip6::Address& GetMeshLocal64 (void) const inline
This method returns a reference to the ML-EID assigned to the Thread interface.
Returns
A reference to the ML-EID assigned to the Thread interface.
References Netif::UnicastAddress::GetAddress(), and Mle::mMeshLocal64.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), Mle::CheckReachability(), and Mle::HasUnregisteredAddress().
GetLeaderId()
uint8_t GetLeaderId (void) const inline
This method returns the Router ID of the Leader.
Returns
The Router ID of the Leader.
References Mle::GetLeaderAddress(), LeaderData::GetLeaderRouterId(), and Mle::mLeaderData.
Referenced by Mle::HandleAdvertisement(), and Mle::HandleLeaderData().
GetLeaderAddress()
Error GetLeaderAddress (Ip6::Address & aAddress) const
This method retrieves the Leader's RLOC.
Parameters
[out] aAddress A reference to the Leader's RLOC.
Return values
kErrorNone Successfully retrieved the Leader's RLOC.
kErrorDetached The Thread interface is not currently attached to a Thread Partition.
References LeaderData::GetLeaderRouterId(), Mle::GetMeshLocalPrefix(), Mle::GetRloc16(), ot::kErrorDetached, ot::kErrorNone, ot::Mac::kShortAddrInvalid, Mle::mLeaderData, Mle::Rloc16FromRouterId(), Address::SetToRoutingLocator(), and VerifyOrExit.
Referenced by Mle::GetLeaderId().
GetLeaderAloc()
Error GetLeaderAloc (Ip6::Address & aAddress) const inline
This method retrieves the Leader's ALOC.
Parameters
[out] aAddress A reference to the Leader's ALOC.
Return values
kErrorNone Successfully retrieved the Leader's ALOC.
kErrorDetached The Thread interface is not currently attached to a Thread Partition.
References Mle::GetLocatorAddress(), and ot::Mle::kAloc16Leader.
GetCommissionerAloc()
Error GetCommissionerAloc (Ip6::Address & aAddress, uint16_t aSessionId) const inline
This method computes the Commissioner's ALOC.
Parameters
[out] aAddress A reference to the Commissioner's ALOC.
[in] aSessionId Commissioner session id.
Return values
kErrorNone Successfully retrieved the Commissioner's ALOC.
kErrorDetached The Thread interface is not currently attached to a Thread Partition.
References Mle::CommissionerAloc16FromId(), Mle::GetLeaderData(), Mle::GetLocatorAddress(), and Mle::GetServiceAloc().
GetServiceAloc()
Error GetServiceAloc (uint8_t aServiceId, Ip6::Address & aAddress) const
This method retrieves the Service ALOC for given Service ID.
Parameters
[in] aServiceId Service ID to get ALOC for.
[out] aAddress A reference to the Service ALOC.
Return values
kErrorNone Successfully retrieved the Service ALOC.
kErrorDetached The Thread interface is not currently attached to a Thread Partition.
References Mle::GetMeshLocalPrefix(), Mle::GetRloc16(), ot::kErrorDetached, ot::kErrorNone, ot::Mac::kShortAddrInvalid, Mle::ServiceAlocFromId(), Address::SetToAnycastLocator(), and VerifyOrExit.
Referenced by Mle::GetCommissionerAloc().
GetLeaderData()
const LeaderData & GetLeaderData (void)
This method returns the most recently received Leader Data.
Returns
A reference to the most recently received Leader Data.
References ot::NetworkData::kFullSet, ot::NetworkData::kStableSubset, Mle::mLeaderData, LeaderData::SetDataVersion(), and LeaderData::SetStableDataVersion().
Referenced by Mle::GetCommissionerAloc().
ChildIdFromRloc16()
static uint16_t ChildIdFromRloc16 (uint16_t aRloc16) inline static
This method derives the Child ID from a given RLOC16.
Parameters
[in] aRloc16 The RLOC16 value.
Returns
The Child ID portion of an RLOC16.
References ot::Mle::kMaxChildId.
Referenced by Mle::IsActiveRouter(), and Neighbor::StateToString().
RouterIdFromRloc16()
static uint8_t RouterIdFromRloc16 (uint16_t aRloc16) inline static
This method derives the Router ID portion from a given RLOC16.
Parameters
[in] aRloc16 The RLOC16 value.
Returns
The Router ID portion of an RLOC16.
References ot::Mle::kRouterIdOffset.
Referenced by Mle::HandleChildUpdateResponse(), MeshForwarder::PrepareDataFrame(), Mle::Restore(), Mle::RouterIdMatch(), and Router::Info::SetFrom().
RouterIdMatch()
static bool RouterIdMatch (uint16_t aRloc16A, uint16_t aRloc16B) inline static
This method returns whether the two RLOC16 have the same Router ID.
Parameters
[in] aRloc16A The first RLOC16 value.
[in] aRloc16B The second RLOC16 value.
Returns
true if the two RLOC16 have the same Router ID, false otherwise.
References Mle::RouterIdFromRloc16().
Referenced by AddressResolver::AddressResolver(), and Mle::HandleChildIdResponse().
ServiceIdFromAloc()
static uint8_t ServiceIdFromAloc (uint16_t aAloc16) inline static
This method returns the Service ID corresponding to a Service ALOC16.
Parameters
[in] aAloc16 The Service ALOC16 value.
Returns
The Service ID corresponding to given ALOC16.
References ot::Mle::kAloc16ServiceStart.
Referenced by Mle::HandleNotifierEvents().
ServiceAlocFromId()
static uint16_t ServiceAlocFromId (uint8_t aServiceId) inline static
This method returns the Service ALOC16 corresponding to a Service ID.
Parameters
[in] aServiceId The Service ID value.
Returns
The Service ALOC16 corresponding to given ID.
References ot::Mle::kAloc16ServiceStart.
Referenced by Manager::GetNextDnsSrpAnycastInfo(), Mle::GetServiceAloc(), Mle::HandleNotifierEvents(), and MutableNetworkData::RemoveTemporaryDataIn().
CommissionerAloc16FromId()
static uint16_t CommissionerAloc16FromId (uint16_t aSessionId) inline static
This method returns the Commissioner Aloc corresponding to a Commissioner Session ID.
Parameters
[in] aSessionId The Commissioner Session ID value.
Returns
The Commissioner ALOC16 corresponding to given ID.
References ot::Mle::kAloc16CommissionerMask, and ot::Mle::kAloc16CommissionerStart.
Referenced by Mle::GetCommissionerAloc().
Rloc16FromRouterId()
static uint16_t Rloc16FromRouterId (uint8_t aRouterId) inline static
This method derives RLOC16 from a given Router ID.
Parameters
[in] aRouterId The Router ID value.
Returns
The RLOC16 corresponding to the given Router ID.
References ot::Mle::kRouterIdOffset.
Referenced by AddressResolver::AddressResolver(), Mle::GetLeaderAddress(), Manager::IsBackboneRouterPreferredTo(), and Mle::Restore().
IsActiveRouter()
static bool IsActiveRouter (uint16_t aRloc16) inline static
This method indicates whether or not aRloc16 refers to an active router.
Parameters
[in] aRloc16 The RLOC16 value.
Return values
TRUE If aRloc16 refers to an active router.
FALSE If aRloc16 does not refer to an active router.
References Mle::ChildIdFromRloc16().
Referenced by NetworkData::FindBorderRouters(), Mle::IsBetterParent(), MeshForwarder::PrepareDataFrame(), Mle::ReestablishLinkWithNeighbor(), Mle::Restore(), Mle::Start(), and MeshForwarder::UpdateNeighborLinkFailures().
GetMessageQueue()
const MessageQueue& GetMessageQueue (void) const inline
This method returns a reference to the send queue.
Returns
A reference to the send queue.
References Mle::mDelayedResponses, Mle::RemoveDelayedDataResponseMessage(), and Mle::RoleToString().
RemoveDelayedDataResponseMessage()
void RemoveDelayedDataResponseMessage (void)
This method frees multicast MLE Data Response from Delayed Message Queue if any.
References Message::kSubTypeMleDataResponse, Mle::kTypeDataResponse, and Mle::RemoveDelayedMessage().
Referenced by Mle::GetMessageQueue().
RoleToString()
const char * RoleToString (DeviceRole aRole) static
This method converts a device role into a human-readable string.
References Message::AppendBytes(), FreeMessageOnError, ot::GetArrayLength(), Mle::kAnyPartition, Mle::kAttachStateAnnounce, Mle::kAttachStateChildIdRequest, Mle::kAttachStateIdle, Mle::kAttachStateParentRequest, Mle::kAttachStateProcessAnnounce, Mle::kAttachStateStart, Mle::kBetterParent, Mle::kBetterPartition, Mle::kCommandLinkMetricsManagementRequest, Mle::kDowngradeToReed, ot::kErrorNoBufs, ot::kErrorNone, Tlv::kLinkMetricsManagement, Mle::kReattachActive, Mle::kReattachPending, Mle::kReattachStart, Mle::kReattachStop, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Mle::kSamePartition, Mle::kSamePartitionRetry, Mle::NewMleMessage(), Mle::TxMessage::SendTo(), Tlv::SetLength(), Tlv::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::GetMessageQueue(), and Mle::SetRole().
GetCounters()
const otMleCounters& GetCounters (void) const inline
This method gets the MLE counters.
Returns
A reference to the MLE counters.
References Mle::mCounters.
ResetCounters()
void ResetCounters (void) inline
This method resets the MLE counters.
References Mle::GetLocatorAddress(), Mle::mCounters, Mle::RegisterParentResponseStatsCallback(), Mle::RequestShorterChildIdRequest(), and Mle::ScheduleChildUpdateRequest().
Referenced by Mle::Mle().
RegisterParentResponseStatsCallback()
void RegisterParentResponseStatsCallback (otThreadParentResponseCallback aCallback, void * aContext)
This function registers the client callback that is called when processing an MLE Parent Response message.
Parameters
[in] aCallback A pointer to a function that is called to deliver MLE Parent Response data.
[in] aContext A pointer to application-specific context.
References CslAccuracy::GetClockAccuracy(), CslAccuracy::GetUncertaintyInMicrosec(), ot::kUsPerTenSymbols, Mle::mParentResponseCb, and Mle::mParentResponseCbContext.
Referenced by Mle::ResetCounters().
RequestShorterChildIdRequest()
void RequestShorterChildIdRequest (void)
This method requests MLE layer to prepare and send a shorter version of Child ID Request message by only including the mesh-local IPv6 address in the Address Registration TLV.
This method should be called when a previous MLE Child ID Request message would require fragmentation at 6LoWPAN layer.
References IgnoreError(), Mle::kAppendMeshLocalOnly, Mle::kAttachStateChildIdRequest, Mle::mAddressRegistrationMode, Mle::mAttachState, and Mle::SendChildIdRequest().
Referenced by Mle::ResetCounters().
GetLocatorAddress()
Error GetLocatorAddress (Ip6::Address & aAddress, uint16_t aLocator) const
This method gets the RLOC or ALOC of a given RLOC16 or ALOC16.
Parameters
[out] aAddress A reference to the RLOC or ALOC.
[in] aLocator RLOC16 or ALOC16.
Return values
kErrorNone If got the RLOC or ALOC successfully.
kErrorDetached If device is detached.
References Netif::UnicastAddress::GetAddress(), Address::GetIid(), Mle::GetRloc16(), ot::kErrorDetached, ot::kErrorNone, ot::Mac::kShortAddrInvalid, Mle::mMeshLocal16, InterfaceIdentifier::SetLocator(), and VerifyOrExit.
Referenced by Mle::GetCommissionerAloc(), Mle::GetLeaderAloc(), and Mle::ResetCounters().
ScheduleChildUpdateRequest()
void ScheduleChildUpdateRequest (void)
This method schedules a Child Update Request.
References Mle::kChildUpdateRequestPending, Mle::mChildUpdateRequestState, and Mle::ScheduleMessageTransmissionTimer().
Referenced by Mle::HandleNotifierEvents(), Mle::HasUnregisteredAddress(), and Mle::ResetCounters().
HasRestored()
bool HasRestored (void) const inline
References Mle::mHasRestored.
TlvList()
TlvList (void) default
This constructor initializes the TlvList as empty.
Add()
void Add (uint8_t aTlvType)
This method checks if a given TLV type is not already present in the list and adds it in the list.
If the list is full, this method logs it as a warning.
Parameters
[in] aTlvType The TLV type to add to the list.
References ot::kErrorNone, LogWarn, and VerifyOrExit.
Referenced by Mle::HandleChildUpdateRequest().
AddElementsFrom()
void AddElementsFrom (const TlvList & aTlvList)
This method adds elements from a given list to this TLV list (if not already present in the list).
Parameters
[in] aTlvList The TLV list to add elements from.
Referenced by Mle::HandleChildUpdateRequest().
GenerateRandom()
void GenerateRandom (void)
This method generates a cryptographically secure random sequence to populate the challenge data.
References ot::Random::Crypto::FillBuffer(), IgnoreError(), and ot::Mle::kMaxChallengeSize.
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
Matches()
bool Matches (const uint8_t * aBuffer, uint8_t aLength) const
This method indicates whether the Challenge matches a given buffer.
Parameters
[in] aBuffer A pointer to a buffer to compare with the Challenge.
[in] aLength Length of aBuffer (in bytes).
Return values
TRUE If the Challenge matches the given buffer.
FALSE If the Challenge does not match the given buffer.
operator==()
bool operator== (const Challenge & aOther) const inline
This method indicates whether two Challenge data byte sequences are equal or not.
Parameters
[in] aOther Another Challenge data to compare.
Return values
TRUE If the two Challenges match.
FALSE If the two Challenges do not match.
References Mle::Challenge::mBuffer, and Mle::Challenge::mLength.
AppendSourceAddressTlv()
Error AppendSourceAddressTlv (void)
This method appends a Source Address TLV to the message.
Return values
kErrorNone Successfully appended the Source Address TLV.
kErrorNoBufs Insufficient buffers available to append the Source Address TLV.
References Mle::GetRloc16().
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
AppendModeTlv()
Error AppendModeTlv (DeviceMode aMode)
This method appends a Mode TLV to the message.
Parameters
[in] aMode The Device Mode.
Return values
kErrorNone Successfully appended the Mode TLV.
kErrorNoBufs Insufficient buffers available to append the Mode TLV.
References DeviceMode::Get().
Referenced by Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
AppendTimeoutTlv()
Error AppendTimeoutTlv (uint32_t aTimeout)
This method appends a Timeout TLV to the message.
Parameters
[in] aTimeout The Timeout value.
Return values
kErrorNone Successfully appended the Timeout TLV.
kErrorNoBufs Insufficient buffers available to append the Timeout TLV.
Referenced by Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
AppendChallengeTlv() [1/2]
Error AppendChallengeTlv (const uint8_t * aChallenge, uint8_t aChallengeLength)
This method appends a Challenge TLV to the message.
Parameters
[in] aChallenge A pointer to the Challenge value.
[in] aChallengeLength The length of the Challenge value in bytes.
Return values
kErrorNone Successfully appended the Challenge TLV.
kErrorNoBufs Insufficient buffers available to append the Challenge TLV.
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
AppendChallengeTlv() [2/2]
Error AppendChallengeTlv (const Challenge & aChallenge)
This method appends a Challenge TLV to the message.
Parameters
[in] aChallenge A reference to the Challenge data.
Return values
kErrorNone Successfully appended the Challenge TLV.
kErrorNoBufs Insufficient buffers available to append the Challenge TLV.
References Mle::Challenge::mBuffer, and Mle::Challenge::mLength.
AppendResponseTlv()
Error AppendResponseTlv (const Challenge & aResponse)
This method appends a Response TLV to the message.
Parameters
[in] aResponse A reference to the Response data.
Return values
kErrorNone Successfully appended the Response TLV.
kErrorNoBufs Insufficient buffers available to append the Response TLV.
References Mle::Challenge::mBuffer, and Mle::Challenge::mLength.
Referenced by Mle::SendChildIdRequest(), and Mle::SendChildUpdateResponse().
AppendLinkFrameCounterTlv()
Error AppendLinkFrameCounterTlv (void)
This method appends a Link Frame Counter TLV to the message.
Return values
kErrorNone Successfully appended the Link Frame Counter TLV.
kErrorNoBufs Insufficient buffers available to append the Link Frame Counter TLV.
Referenced by Mle::SendChildIdRequest(), and Mle::SendChildUpdateResponse().
AppendMleFrameCounterTlv()
Error AppendMleFrameCounterTlv (void)
This method appends an MLE Frame Counter TLV to the message.
Return values
kErrorNone Successfully appended the Frame Counter TLV.
kErrorNoBufs Insufficient buffers available to append the MLE Frame Counter TLV.
Referenced by Mle::SendChildIdRequest(), and Mle::SendChildUpdateResponse().
AppendAddress16Tlv()
Error AppendAddress16Tlv (uint16_t aRloc16)
This method appends an Address16 TLV to the message.
Parameters
[in] aRloc16 The RLOC16 value.
Return values
kErrorNone Successfully appended the Address16 TLV.
kErrorNoBufs Insufficient buffers available to append the Address16 TLV.
AppendNetworkDataTlv()
Error AppendNetworkDataTlv (NetworkData::Type aType)
This method appends a Network Data TLV to the message.
Parameters
[in] aType The Network Data type to append, full set or stable subset.
Return values
kErrorNone Successfully appended the Network Data TLV.
kErrorNoBufs Insufficient buffers available to append the Network Data TLV.
References IgnoreError(), ot::kErrorInvalidState, ot::kErrorNone, NetworkData::kMaxSize, Mle::mRetrieveNewNetworkData, and VerifyOrExit.
AppendTlvRequestTlv() [1/2]
Error AppendTlvRequestTlv (const uint8_t * aTlvs, uint8_t aTlvsLength)
This method appends a TLV Request TLV to the message.
Parameters
[in] aTlvs A pointer to the list of TLV types.
[in] aTlvsLength The number of TLV types in aTlvs
Return values
kErrorNone Successfully appended the TLV Request TLV.
kErrorNoBufs Insufficient buffers available to append the TLV Request TLV.
Referenced by Mle::SendChildIdRequest(), and Mle::SendDataRequest().
AppendTlvRequestTlv() [2/2]
Error AppendTlvRequestTlv (const uint8_t(&) aTlvArray[kArrayLength]) inline
This method appends a TLV Request TLV to the message.
Template Parameters
kArrayLength The TLV array length.
Parameters
[in] aTlvArray A reference to an array of TLV types of kArrayLength length.
Return values
kErrorNone Successfully appended the TLV Request TLV.
kErrorNoBufs Insufficient buffers available to append the TLV Request TLV.
References Mle::kAppendAllAddresses.
AppendLeaderDataTlv()
Error AppendLeaderDataTlv (void)
This method appends a Leader Data TLV to the message.
Return values
kErrorNone Successfully appended the Leader Data TLV.
kErrorNoBufs Insufficient buffers available to append the Leader Data TLV.
References Tlv::AppendTo(), LeaderDataTlv::Init(), ot::NetworkData::kFullSet, ot::NetworkData::kStableSubset, Mle::mLeaderData, LeaderDataTlv::Set(), LeaderData::SetDataVersion(), and LeaderData::SetStableDataVersion().
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
AppendScanMaskTlv()
Error AppendScanMaskTlv (uint8_t aScanMask)
This method appends a Scan Mask TLV to th message.
Parameters
[in] aScanMask The Scan Mask value.
Return values
kErrorNone Successfully appended the Scan Mask TLV.
kErrorNoBufs Insufficient buffers available to append the Scan Mask TLV.
Referenced by Mle::SendParentRequest().
AppendStatusTlv()
Error AppendStatusTlv (StatusTlv::Status aStatus)
This method appends a Status TLV to the message.
Parameters
[in] aStatus The Status value.
Return values
kErrorNone Successfully appended the Status TLV.
kErrorNoBufs Insufficient buffers available to append the Status TLV.
Referenced by Mle::SendChildUpdateResponse().
AppendLinkMarginTlv()
Error AppendLinkMarginTlv (uint8_t aLinkMargin)
This method appends a Link Margin TLV to the message.
Parameters
[in] aLinkMargin The Link Margin value.
Return values
kErrorNone Successfully appended the Link Margin TLV.
kErrorNoBufs Insufficient buffers available to append the Link Margin TLV.
AppendVersionTlv()
Error AppendVersionTlv (void)
This method appends a Version TLV to the message.
Return values
kErrorNone Successfully appended the Version TLV.
kErrorNoBufs Insufficient buffers available to append the Version TLV.
References ot::kThreadVersion.
Referenced by Mle::SendChildIdRequest(), and Mle::SendParentRequest().
AppendAddressRegistrationTlv()
Error AppendAddressRegistrationTlv (AddressRegistrationMode aMode = kAppendAllAddresses)
This method appends an Address Registration TLV to the message.
Parameters
[in] aMode Determines which addresses to include in the TLV (see AddressRegistrationMode).
Return values
kErrorNone Successfully appended the Address Registration TLV.
kErrorNoBufs Insufficient buffers available to append the Address Registration TLV.
References Mle::TxMessage::AppendXtalAccuracyTlv(), Address::GetIid(), AddressRegistrationEntry::GetLength(), Mle::GetMeshLocal64(), Mle::GetParent(), Mle::IsRoutingLocator(), Mle::IsRxOnWhenIdle(), Tlv::kAddressRegistration, Mle::kAppendMeshLocalOnly, ot::kErrorNone, ot::Mle::kMeshLocalPrefixContextId, Context::mContextId, OPENTHREAD_CONFIG_MLE_IP_ADDRS_TO_REGISTER, OPENTHREAD_CONFIG_THREAD_VERSION, OT_THREAD_VERSION_1_2, otPlatTimeGetXtalAccuracy(), AddressRegistrationEntry::SetContextId(), AddressRegistrationEntry::SetIid(), AddressRegistrationEntry::SetIp6Address(), Tlv::SetLength(), Tlv::SetType(), AddressRegistrationEntry::SetUncompressed(), SuccessOrAssert, SuccessOrExit, and VerifyOrExit.
Referenced by Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
AppendXtalAccuracyTlv()
Error AppendXtalAccuracyTlv (void)
This method appends a XTAL Accuracy TLV to the message.
Return values
kErrorNone Successfully appended the XTAL Accuracy TLV.
kErrorNoBufs Insufficient buffers available to append the XTAl Accuracy TLV.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv().
AppendActiveTimestampTlv()
Error AppendActiveTimestampTlv (void)
This method appends a Active Timestamp TLV to the message.
Return values
kErrorNone Successfully appended the Active Timestamp TLV.
kErrorNoBufs Insufficient buffers available to append the Active Timestamp TLV.
References ot::kErrorNone, and VerifyOrExit.
Referenced by Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendDataRequest(), and Mle::SendDelayedResponse().
AppendPendingTimestampTlv()
Error AppendPendingTimestampTlv (void)
This method appends a Pending Timestamp TLV to the message.
Return values
kErrorNone Successfully appended the Pending Timestamp TLV.
kErrorNoBufs Insufficient buffers available to append the Pending Timestamp TLV.
References Timestamp::GetSeconds(), Mle::GetTimeout(), ot::kErrorNone, and VerifyOrExit.
Referenced by Mle::SendChildIdRequest(), Mle::SendDataRequest(), and Mle::SendDelayedResponse().
SendTo()
Error SendTo (const Ip6::Address & aDestination)
This method submits the MLE message to the UDP socket to be sent.
Parameters
[in] aDestination A reference to the IPv6 address of the destination.
Return values
kErrorNone Successfully submitted the MLE message.
kErrorNoBufs Insufficient buffers to form the rest of the MLE message.
References Netif::UnicastAddress::GetAddress(), IgnoreError(), Mle::k154Security, AesCcm::kEncrypt, ot::kErrorNone, Mle::kMleHopLimit, ot::Mle::kUdpPort, Mle::mLinkLocal64, Mle::mSocket, Mle::ProcessMessageSecurity(), Udp::Socket::SendTo(), Mle::SecurityHeader::SetFrameCounter(), MessageInfo::SetHopLimit(), Mle::SecurityHeader::SetKeyId(), MessageInfo::SetPeerAddr(), MessageInfo::SetPeerPort(), MessageInfo::SetSockAddr(), and SuccessOrExit.
Referenced by DiscoverScanner::Discover(), Mle::HasMoreChannelsToAnnouce(), Mle::RoleToString(), Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), Mle::SendDelayedResponse(), and Mle::SendParentRequest().
SendAfterDelay()
Error SendAfterDelay (const Ip6::Address & aDestination, uint16_t aDelay)
This method enqueues the message to be sent after a given delay.
Parameters
[in] aDestination The IPv6 address of the recipient of the message.
[in] aDelay The delay in milliseconds before transmission of the message.
Return values
kErrorNone Successfully queued the message to transmit after the delay.
kErrorNoBufs Insufficient buffers to queue the message.
References Tlv::AppendTo(), Mle::DelayedResponseMetadata::AppendTo(), MessageQueue::Enqueue(), TimerMilli::FireAtIfEarlier(), AddressRegistrationEntry::GetLength(), TimerMilli::GetNow(), RouteTlv::Init(), ConnectivityTlv::Init(), Tlv::kAddressRegistration, ot::kErrorNone, ot::Mle::kMeshLocalPrefixContextId, Context::mContextId, Mle::mDelayedResponses, Mle::mDelayedResponseTimer, Mle::DelayedResponseMetadata::mDestination, Mle::DelayedResponseMetadata::mSendTime, AddressRegistrationEntry::SetContextId(), AddressRegistrationEntry::SetIid(), AddressRegistrationEntry::SetIp6Address(), Tlv::SetLength(), Tlv::SetType(), AddressRegistrationEntry::SetUncompressed(), and SuccessOrExit.
Referenced by Mle::SendDataRequest().
ReadChallengeTlv()
Error ReadChallengeTlv (Challenge & aChallenge) const
This method reads Challenge TLV from the message.
Parameters
[out] aChallenge A reference to the Challenge data where to output the read value.
Return values
kErrorNone Successfully read the Challenge TLV.
kErrorNotFound Challenge TLV was not found in the message.
kErrorParse Challenge TLV was found but could not be parsed.
References Tlv::kChallenge.
Referenced by Mle::HandleChildUpdateRequest(), and Mle::HandleParentResponse().
ReadResponseTlv()
Error ReadResponseTlv (Challenge & aResponse) const
This method reads Response TLV from the message.
Parameters
[out] aResponse A reference to the Response data where to output the read value.
Return values
kErrorNone Successfully read the Response TLV.
kErrorNotFound Response TLV was not found in the message.
kErrorParse Response TLV was found but could not be parsed.
References Tlv::kResponse.
Referenced by Mle::HandleChildUpdateResponse(), and Mle::HandleParentResponse().
ReadFrameCounterTlvs()
Error ReadFrameCounterTlvs (uint32_t & aLinkFrameCounter, uint32_t & aMleFrameCounter) const
This method reads Link and MLE Frame Counters from the message.
Link Frame Counter TLV must be present in the message and its value is read into aLinkFrameCounter. If MLE Frame Counter TLV is present in the message, its value is read into aMleFrameCounter. If the MLE Frame Counter TLV is not present in the message, then aMleFrameCounter is set to the same value as aLinkFrameCounter.
Parameters
[out] aLinkFrameCounter A reference to an uint32_t to output the Link Frame Counter.
[out] aMleFrameCounter A reference to an uint32_t to output the MLE Frame Counter.
Return values
kErrorNone Successfully read the counters.
kErrorNotFound Link Frame Counter TLV was not found in the message.
kErrorParse TLVs are not well-formed.
References ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, and SuccessOrExit.
Referenced by Mle::HandleChildUpdateResponse(), and Mle::HandleParentResponse().
ReadTlvRequestTlv()
Error ReadTlvRequestTlv (TlvList & aTlvList) const
This method reads TLV Request TLV from the message.
Parameters
[out] aTlvList A reference to output the read list of requested TLVs.
Return values
kErrorNone Successfully read the TLV.
kErrorNotFound TLV was not found in the message.
kErrorParse TLV was found but could not be parsed.
References Tlv::FindTlv(), Tlv::FindTlvValueOffset(), ot::kErrorParse, Tlv::kTlvRequest, CslAccuracy::SetClockAccuracy(), CslAccuracy::SetUncertainty(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleChildUpdateRequest().
ReadLeaderDataTlv()
Error ReadLeaderDataTlv (LeaderData & aLeaderData) const
This method reads Leader Data TLV from a message.
Parameters
[out] aLeaderData A reference to output the Leader Data.
Return values
kErrorNone Successfully read the TLV.
kErrorNotFound TLV was not found in the message.
kErrorParse TLV was found but could not be parsed.
References Tlv::FindTlv(), LeaderDataTlv::Get(), LeaderDataTlv::IsValid(), ot::kErrorParse, SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), and Mle::HandleParentResponse().
ReadChallengeOrResponse()
Error ReadChallengeOrResponse (uint8_t aTlvType, Challenge & aBuffer) const private
References Tlv::FindTlvValueOffset(), ot::kErrorParse, ot::Mle::kMaxChallengeSize, ot::Mle::kMinChallengeSize, Mle::Challenge::mBuffer, Mle::Challenge::mLength, SuccessOrExit, and VerifyOrExit.
RxInfo()
RxInfo (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) inline
This constructor initializes the RxInfo.
Parameters
[in] aMessage The received MLE message.
[in] aMessageInfo The Ip6::MessageInfo associated with message.
NewMleMessage()
Mle::TxMessage * NewMleMessage (Command aCommand) protected
This method allocates and initializes new MLE message for a given command.
Parameters
[in] aCommand The MLE command.
Returns
A pointer to the message or nullptr if insufficient message buffers are available.
References Message::Append(), FreeAndNullMessageOnError, Mle::SecurityHeader::InitSecurityControl(), Mle::k154Security, Mle::kCommandAnnounce, Mle::kCommandChildIdRequest, Mle::kCommandChildUpdateRequest, Mle::kCommandDataRequest, Mle::kCommandDataResponse, Mle::kCommandDiscoveryRequest, Mle::kCommandDiscoveryResponse, ot::kErrorNoBufs, ot::kErrorNone, Message::kNoLinkSecurity, Mle::kNoSecurity, Message::kPriorityNet, Message::kSubTypeMleAnnounce, Message::kSubTypeMleChildIdRequest, Message::kSubTypeMleChildUpdateRequest, Message::kSubTypeMleDataRequest, Message::kSubTypeMleDataResponse, Message::kSubTypeMleDiscoverRequest, Message::kSubTypeMleDiscoverResponse, Message::kSubTypeMleGeneral, Mle::mSocket, Udp::Socket::NewMessage(), Message::SetSubType(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HasMoreChannelsToAnnouce(), Mle::RoleToString(), Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), and Mle::SendParentRequest().
SetRole()
void SetRole (DeviceRole aRole) protected
This method sets the device role.
Parameters
[in] aRole A device role.
References Mle::IsChild(), ot::kEventThreadRoleChanged, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Neighbor::kStateInvalid, LogNote, otMleCounters::mChildRole, Mle::mCounters, otMleCounters::mDetachedRole, otMleCounters::mDisabledRole, otMleCounters::mLeaderRole, Mle::mParent, Mle::mRole, otMleCounters::mRouterRole, Mle::RoleToString(), Neighbor::SetState(), and SuccessOrExit.
Referenced by Mle::SetStateChild(), Mle::SetStateDetached(), and Mle::Stop().
Attach()
void Attach (AttachMode aMode) protected
This method causes the Thread interface to attempt an MLE attach.
Parameters
[in] aMode Indicates what partitions to attach to.
References Parent::Clear(), Mle::GetAttachStartDelay(), Mle::IsAttaching(), Mle::IsDetached(), Mle::IsDisabled(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Mle::kAttachStateStart, Mle::kBetterPartition, ot::kErrorNone, Mle::kReattachActive, Mle::kReattachStart, Mle::kReattachStop, otMleCounters::mAttachAttempts, Mle::mAttachCounter, Mle::mAttachMode, Mle::mAttachTimer, otMleCounters::mBetterPartitionAttachAttempts, Mle::mCounters, Mle::mParentCandidate, Mle::mReattachState, Mle::Restore(), Mle::SetAttachState(), TimerMilli::Start(), and VerifyOrExit.
Referenced by Mle::BecomeChild(), Mle::BecomeDetached(), Mle::CheckReachability(), Mle::Reattach(), Mle::SearchForBetterParent(), Mle::SetDeviceMode(), and Mle::Start().
SetAttachState()
void SetAttachState (AttachState aState) protected
This method sets the attach state
Parameters
[in] aState An attach state
References LogInfo, Mle::mAttachState, and VerifyOrExit.
Referenced by Mle::Attach(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::Reattach(), Mle::SetStateChild(), and Mle::SetStateDetached().
CheckReachability()
Error CheckReachability (uint16_t aMeshDest, const Ip6::Header & aIp6Header) protected
This method checks if the destination is reachable.
Parameters
[in] aMeshDest The RLOC16 of the destination.
[in] aIp6Header The IPv6 header of the message.
Return values
kErrorNone The destination is reachable.
kErrorNoRoute The destination is not reachable and the message should be dropped.
References StringWriter::Append(), String< kSize >::AsCString(), Mle::Attach(), ot::ErrorToString(), FreeMessage, GetProvider< InstanceGetProvider >::Get(), LinkQualityInfo::GetAverageRss(), Header::GetDestination(), Address::GetIid(), Neighbor::GetLinkInfo(), Mle::GetMeshLocal16(), Mle::GetMeshLocal64(), TimerMilli::GetNow(), Mle::GetParent(), MessageInfo::GetPeerAddr(), Neighbor::GetRloc16(), Mle::GetRloc16(), ot::Random::NonCrypto::GetUint32InRange(), Mle::IsChild(), Mle::kBetterParent, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNoRoute, Mle::kMessageDelay, Mle::kMessageReceive, Mle::kMessageRemoveDelayed, Mle::kMessageSend, ot::Ip6::kProtoNone, ot::Mac::kShortAddrInvalid, Mle::kTypeAdvertisement, Mle::kTypeAnnounce, Mle::kTypeChildIdRequest, Mle::kTypeChildIdRequestShort, Mle::kTypeChildIdResponse, Mle::kTypeChildUpdateRequestOfParent, Mle::kTypeChildUpdateResponseOfParent, Mle::kTypeDataRequest, Mle::kTypeDataResponse, Mle::kTypeDiscoveryRequest, Mle::kTypeDiscoveryResponse, Mle::kTypeGenericDelayed, Mle::kTypeGenericUdp, Mle::kTypeParentRequestToRouters, Mle::kTypeParentRequestToRoutersReeds, Mle::kTypeParentResponse, Mle::Log(), ot::MeshCoP::LogError(), LogInfo, LogNote, Mle::LogProcessError(), Mle::LogSendError(), LogWarn, Mle::mParent, Mle::mPreviousParentRloc, OT_RADIO_RSSI_INVALID, Message::SetLength(), InterfaceIdentifier::SetLocator(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), SuccessOrExit, Address::ToString(), and VerifyOrExit.
GetNextHop()
uint16_t GetNextHop (uint16_t aDestination) const protected
This method returns the next hop towards an RLOC16 destination.
Parameters
[in] aDestination The RLOC16 of the destination.
Returns
A RLOC16 of the next hop if a route is known, kInvalidRloc16 otherwise.
References Neighbor::GetRloc16(), Neighbor::IsStateValid(), ot::Mac::kShortAddrInvalid, Mle::mParent, and OT_UNUSED_VARIABLE.
SendDataRequest() [1/2]
Error SendDataRequest (const Ip6::Address & aDestination, const uint8_t * aTlvs, uint8_t aTlvsLength, uint16_t aDelay, const uint8_t * aExtraTlvs, uint8_t aExtraTlvsLength) protected
This method generates an MLE Data Request message.
Parameters
[in] aDestination A reference to the IPv6 address of the destination.
[in] aTlvs A pointer to requested TLV types.
[in] aTlvsLength The number of TLV types in aTlvs.
[in] aDelay Delay in milliseconds before the Data Request message is sent.
[in] aExtraTlvs A pointer to extra TLVs.
[in] aExtraTlvsLength Length of extra TLVs.
Return values
kErrorNone Successfully generated an MLE Data Request message.
kErrorNoBufs Insufficient buffers to generate the MLE Data Request message.
References Mle::TxMessage::AppendActiveTimestampTlv(), Message::AppendBytes(), Mle::TxMessage::AppendPendingTimestampTlv(), Mle::TxMessage::AppendTlvRequestTlv(), FreeMessageOnError, Mle::IsChild(), Mle::IsRxOnWhenIdle(), Mle::kChildUpdateRequestNone, Mle::kCommandDataRequest, Mle::kDataRequestActive, DataPollSender::kDefaultFastPolls, ot::kErrorNoBufs, ot::kErrorNone, Mle::kMessageDelay, Mle::kMessageSend, Mle::kTypeDataRequest, Mle::Log(), Mle::mChildUpdateRequestState, Mle::mDataRequestState, Mle::NewMleMessage(), Mle::RemoveDelayedDataRequestMessage(), Mle::ScheduleMessageTransmissionTimer(), Mle::TxMessage::SendAfterDelay(), Mle::TxMessage::SendTo(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAdvertisement(), Mle::HandleLeaderData(), Mle::HandleMessageTransmissionTimer(), and Mle::SendDataRequest().
SendDataRequest() [2/2]
Error SendDataRequest (const Ip6::Address & aDestination, const uint8_t(&) aTlvs[kArrayLength], uint16_t aDelay = 0) inline protected
This method generates an MLE Data Request message.
Template Parameters
kArrayLength The TLV array length.
Parameters
[in] aDestination A reference to the IPv6 address of the destination.
[in] aTlvs An array of requested TLVs.
[in] aDelay Delay in milliseconds before the Data Request message is sent.
Return values
kErrorNone Successfully generated an MLE Data Request message.
kErrorNoBufs Insufficient buffers to generate the MLE Data Request message.
References Mle::Log(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), Mle::SetLeaderData(), Mle::SetRloc16(), Mle::SetStateChild(), and Mle::SetStateDetached().
SendChildUpdateRequest() [1/2]
Error SendChildUpdateRequest (bool aAppendChallenge = false) protected
This method generates an MLE Child Update Request message.
Parameters
[in] aAppendChallenge Indicates whether or not to include a Challenge TLV (even when already attached).
Return values
kErrorNone Successfully generated an MLE Child Update Request message.
kErrorNoBufs Insufficient buffers to generate the MLE Child Update Request message.
References Mle::mTimeout.
Referenced by Mle::DetachGracefully(), Mle::HandleMessageTransmissionTimer(), Mle::IsDetachingGracefully(), Mle::ReestablishLinkWithNeighbor(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), Mle::SetDeviceMode(), Mle::SetTimeout(), and Mle::Start().
SendChildUpdateResponse()
Error SendChildUpdateResponse (const TlvList & aTlvList, const Challenge & aChallenge) protected
This method generates an MLE Child Update Response message.
Parameters
[in] aTlvList A list of requested TLV types.
[in] aChallenge The Challenge for the response.
Return values
kErrorNone Successfully generated an MLE Child Update Response message.
kErrorNoBufs Insufficient buffers to generate the MLE Child Update Response message.
References Mle::TxMessage::AppendAddressRegistrationTlv(), Mle::TxMessage::AppendLeaderDataTlv(), Mle::TxMessage::AppendLinkFrameCounterTlv(), Mle::TxMessage::AppendMleFrameCounterTlv(), Mle::TxMessage::AppendResponseTlv(), Mle::TxMessage::AppendSourceAddressTlv(), Mle::TxMessage::AppendStatusTlv(), Mle::TxMessage::AppendTimeoutTlv(), FreeMessageOnError, Neighbor::GetExtAddress(), Mle::HasUnregisteredAddress(), IgnoreError(), Mle::IsFullThreadDevice(), Tlv::kAddressRegistration, Mle::kAppendMeshLocalOnly, Mle::kCommandChildUpdateResponse, Tlv::kCslTimeout, StatusTlv::kError, ot::kErrorNoBufs, ot::kErrorNone, Tlv::kLinkFrameCounter, Mle::kMessageSend, Tlv::kMleFrameCounter, Tlv::kResponse, Tlv::kStatus, Tlv::kTimeout, Mle::kTypeChildUpdateResponseOfParent, Mle::Log(), Mle::mParent, Mle::mTimeout, Mle::NewMleMessage(), Mle::SendChildUpdateRequest(), Mle::TxMessage::SendTo(), Address::SetToLinkLocalAddress(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleChildUpdateRequest(), and Mle::SendDataRequest().
SetRloc16()
void SetRloc16 (uint16_t aRloc16) protected
This method sets the RLOC16 assigned to the Thread interface.
Parameters
[in] aRloc16 The RLOC16 to set.
References Netif::UnicastAddress::GetAddress(), Address::GetIid(), InterfaceIdentifier::GetLocator(), Mle::GetRloc16(), ot::Mac::kShortAddrInvalid, LogNote, Mle::mMeshLocal16, and InterfaceIdentifier::SetLocator().
Referenced by Mle::BecomeDetached(), Mle::SendDataRequest(), Mle::SetStateChild(), and Mle::Start().
SetStateDetached()
void SetStateDetached (void) protected
This method sets the Device State to Detached.
References Mle::IsLeader(), Mle::kAttachStateIdle, Mle::kChildUpdateRequestNone, Mle::kDataRequestNone, ot::Mle::kRoleDetached, Mle::mAttachTimer, Mle::mChildUpdateAttempts, Mle::mChildUpdateRequestState, Mle::mDataRequestAttempts, Mle::mDataRequestState, Mle::mLeaderAloc, Mle::mMessageTransmissionTimer, Mle::SetAttachState(), Mle::SetRole(), and TimerMilli::Stop().
Referenced by Mle::BecomeDetached(), Mle::HandleChildIdResponse(), Mle::SendDataRequest(), Mle::SetDeviceMode(), Mle::Start(), and Mle::Stop().
SetStateChild()
void SetStateChild (uint16_t aRloc16) protected
This method sets the Device State to Child.
References Neighbor::GetRloc16(), Mle::InformPreviousChannel(), Mle::IsFullThreadDevice(), Mle::IsLeader(), Mle::kAttachBackoffDelayToResetCounter, Mle::kAttachStateIdle, ot::Mle::kMplChildDataMessageTimerExpirations, Mle::kReattachStop, ot::Mle::kRoleChild, ot::Mac::kShortAddrInvalid, Mle::mAttachMode, Mle::mAttachTimer, Mle::mChildUpdateAttempts, Mle::mCounters, Mle::mDataRequestAttempts, Mle::mLeaderAloc, Mle::mParent, otMleCounters::mParentChanges, Mle::mPreviousParentRloc, Mle::mReattachState, Mle::ScheduleMessageTransmissionTimer(), Mle::SetAttachState(), Mle::SetRloc16(), Mle::SetRole(), and TimerMilli::Start().
Referenced by Mle::HandleChildIdResponse(), Mle::HandleChildUpdateResponse(), Mle::SendDataRequest(), and Mle::SetDeviceMode().
SetLeaderData()
void SetLeaderData (uint32_t aPartitionId, uint8_t aWeighting, uint8_t aLeaderRouterId) protected
This method sets the Leader's Partition ID, Weighting, and Router ID values.
Parameters
[in] aPartitionId The Leader's Partition ID value.
[in] aWeighting The Leader's Weighting value.
[in] aLeaderRouterId The Leader's Router ID value.
References LeaderData::GetPartitionId(), ot::kEventThreadPartitionIdChanged, Mle::mCounters, Mle::mLeaderData, otMleCounters::mPartitionIdChanges, LeaderData::SetLeaderRouterId(), LeaderData::SetPartitionId(), and LeaderData::SetWeighting().
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), and Mle::SendDataRequest().
Log() [1/2]
static void Log (MessageAction , MessageType , const Ip6::Address &) inline static protected
Referenced by Mle::CheckReachability(), DiscoverScanner::Discover(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), DiscoverScanner::HandleDiscoveryResponse(), Mle::HandleParentResponse(), Mle::RemoveDelayedMessage(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), Mle::SendDelayedResponse(), and Mle::SendParentRequest().
Log() [2/2]
static void Log (MessageAction , MessageType , const Ip6::Address & , uint16_t) inline static protected
References Mle::LogProcessError(), and Mle::LogSendError().
LogProcessError()
static void LogProcessError (MessageType , Error) inline static protected
Referenced by Mle::CheckReachability(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), DiscoverScanner::HandleDiscoveryResponse(), Mle::HandleParentResponse(), Mle::HandleUdpReceive(), and Mle::Log().
LogSendError()
static void LogSendError (MessageType , Error) inline static protected
References Mle::InformPreviousChannel().
Referenced by Mle::CheckReachability(), and Mle::Log().
InformPreviousChannel()
void InformPreviousChannel (void) protected
This method triggers MLE Announce on previous channel after the Thread device successfully attaches and receives the new Active Commissioning Dataset if needed.
MTD would send Announce immediately after attached. FTD would delay to send Announce after tried to become Router or decided to stay in REED role.
References Mle::IsChild(), Mle::IsFullThreadDevice(), Mle::IsRouter(), ot::Mac::kPanIdBroadcast, Mle::mAlternateChannel, Mle::mAlternatePanId, Mle::SendAnnounce(), and VerifyOrExit.
Referenced by Mle::LogSendError(), and Mle::SetStateChild().
IsAnnounceAttach()
bool IsAnnounceAttach (void) const inline protected
This method indicates whether or not in announce attach process.
Return values
true if attaching/attached on the announced parameters, false otherwise.
References ot::Mac::kPanIdBroadcast, and Mle::mAlternatePanId.
AppendTo()
Error AppendTo (Message & aMessage) const inline
References Message::Append().
Referenced by Mle::TxMessage::SendAfterDelay().
ReadFrom()
void ReadFrom (const Message & aMessage)
References Message::GetLength(), IgnoreError(), OT_ASSERT, and Message::Read().
Referenced by Mle::HandleDelayedResponseTimer(), and Mle::RemoveDelayedMessage().
RemoveFrom()
void RemoveFrom (Message & aMessage) const
References Message::GetLength(), Message::SetLength(), and SuccessOrAssert.
Referenced by Mle::SendDelayedResponse().
InitSecurityControl()
void InitSecurityControl (void) inline
Referenced by Mle::NewMleMessage().
IsSecurityControlValid()
bool IsSecurityControlValid (void) const inline
Referenced by Mle::HandleUdpReceive().
GetFrameCounter()
uint32_t GetFrameCounter (void) const inline
References ot::Encoding::LittleEndian::HostSwap32().
Referenced by Mle::HandleUdpReceive(), and Mle::ProcessMessageSecurity().
SetFrameCounter()
void SetFrameCounter (uint32_t aCounter) inline
References ot::Encoding::LittleEndian::HostSwap32().
Referenced by Mle::TxMessage::SendTo().
GetKeyId()
uint32_t GetKeyId (void) const inline
References ot::Encoding::BigEndian::HostSwap32().
Referenced by Mle::HandleUdpReceive(), and Mle::ProcessMessageSecurity().
SetKeyId()
void SetKeyId (uint32_t aKeySequence) inline
References ot::Encoding::BigEndian::HostSwap32().
Referenced by Mle::TxMessage::SendTo().
Start() [2/2]
Error Start (StartMode aMode) private
References Mle::ApplyMeshLocalPrefix(), Mle::Attach(), ot::Mac::GenerateRandomPanId(), Mle::GetRloc16(), IgnoreError(), Mle::IsActiveRouter(), Mle::kAnnounceAttach, Mle::kAnyPartition, ot::kErrorInvalidState, ot::kErrorNone, Mle::kNormalAttach, ot::Mac::kPanIdBroadcast, Mle::kReattachStart, ot::Mac::kShortAddrInvalid, ThreadStatusTlv::kTooFewRouters, Mle::mAttachCounter, Mle::mChildUpdateAttempts, Mle::mReattachState, Mle::SendChildUpdateRequest(), Mle::SetRloc16(), Mle::SetStateDetached(), Mle::Start(), and VerifyOrExit.
Stop() [2/2]
void Stop (StopMode aMode) private
References Mle::IsDisabled(), ot::Mle::kRoleDisabled, Mle::kUpdateNetworkDatasets, Mle::mDetachGracefullyCallback, Mle::mDetachGracefullyContext, Mle::mDetachGracefullyTimer, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mRealmLocalAllThreadNodes, Mle::SetRole(), Mle::SetStateDetached(), Mle::Stop(), TimerMilli::Stop(), and VerifyOrExit.
HandleNotifierEvents()
void HandleNotifierEvents (Events aEvents) private
References Events::Contains(), Events::ContainsAny(), InterfaceIdentifier::GenerateRandom(), Netif::UnicastAddress::GetAddress(), Address::GetIid(), Mle::GetParent(), Mle::GetRloc16(), IgnoreError(), Mle::IsAttached(), Mle::IsChild(), Mle::IsDisabled(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Neighbor::IsThreadVersion1p1(), Mle::kAppendAllAddresses, Mle::kAppendMeshLocalOnly, ot::kErrorNone, ot::kEventIp6AddressAdded, ot::kEventIp6AddressRemoved, ot::kEventIp6MulticastSubscribed, ot::kEventIp6MulticastUnsubscribed, ot::kEventThreadKeySeqCounterChanged, ot::kEventThreadMeshLocalAddrChanged, ot::kEventThreadNetdataChanged, ot::kEventThreadRoleChanged, ot::NetworkData::kIteratorInit, Mle::mAddressRegistrationMode, Mle::mMeshLocal64, otServiceConfig::mServiceId, Mle::ScheduleChildUpdateRequest(), Mle::ServiceAlocFromId(), Mle::ServiceIdFromAloc(), Mle::Store(), and VerifyOrExit.
HandleAttachTimer() [1/2]
void HandleAttachTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and Mle::HandleAttachTimer().
HandleAttachTimer() [2/2]
void HandleAttachTimer (void) private
References Parent::Clear(), Mle::DetermineParentRequestType(), ExitNow, Mle::GetNextAnnouceChannel(), Mle::HasAcceptableParentCandidate(), Mle::kAttachStateAnnounce, Mle::kAttachStateChildIdRequest, Mle::kAttachStateIdle, Mle::kAttachStateParentRequest, Mle::kAttachStateProcessAnnounce, Mle::kAttachStateStart, ChannelMask::kChannelIteratorFirst, ot::kErrorNone, Mle::kOrphanAnnounce, ot::Mle::kParentRequestReedTimeout, ot::Mle::kParentRequestRouterTimeout, Neighbor::kStateInvalid, Mle::kToRouters, Mle::kToRoutersAndReeds, LogNote, Mle::mAnnounceChannel, Mle::mAnnounceDelay, Mle::mAttachCounter, Mle::mAttachMode, Mle::mAttachState, Mle::mAttachTimer, Mle::mParentCandidate, Mle::mParentRequestCounter, Mle::mReattachState, Mle::mReceivedResponseFromParent, OT_FALL_THROUGH, Mle::PrepareAnnounceState(), Mle::ProcessAnnounce(), Mle::Reattach(), Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendParentRequest(), Mle::SetAttachState(), Neighbor::SetState(), and TimerMilli::Start().
Referenced by Mle::HandleAttachTimer().
HandleDelayedResponseTimer() [1/2]
void HandleDelayedResponseTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and Mle::HandleDelayedResponseTimer().
HandleDelayedResponseTimer() [2/2]
void HandleDelayedResponseTimer (void) private
References TimerMilli::FireAt(), Time::GetDistantFuture(), TimerMilli::GetNow(), Mle::mDelayedResponses, Mle::mDelayedResponseTimer, Mle::DelayedResponseMetadata::mSendTime, Mle::DelayedResponseMetadata::ReadFrom(), and Mle::SendDelayedResponse().
Referenced by Mle::HandleDelayedResponseTimer().
SendDelayedResponse()
void SendDelayedResponse (TxMessage & aMessage, const DelayedResponseMetadata & aMetadata) private
References Mle::TxMessage::AppendActiveTimestampTlv(), Mle::TxMessage::AppendPendingTimestampTlv(), FreeMessageOnError, Message::GetSubType(), Mle::IsRxOnWhenIdle(), DataPollSender::kDefaultFastPolls, ot::kErrorNone, Mle::kMessageSend, Message::kSubTypeMleDataRequest, Mle::kTypeGenericDelayed, Mle::Log(), Mle::DelayedResponseMetadata::mDestination, Mle::DelayedResponseMetadata::RemoveFrom(), Mle::TxMessage::SendTo(), and SuccessOrExit.
Referenced by Mle::HandleDelayedResponseTimer().
HandleMessageTransmissionTimer() [1/2]
void HandleMessageTransmissionTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and Mle::HandleMessageTransmissionTimer().
HandleMessageTransmissionTimer() [2/2]
void HandleMessageTransmissionTimer (void) private
References Mle::BecomeDetached(), ExitNow, Neighbor::GetExtAddress(), IgnoreError(), Mle::IsChild(), Mle::IsRxOnWhenIdle(), Mle::kChildUpdateRequestActive, Mle::kChildUpdateRequestNone, Mle::kChildUpdateRequestPending, Mle::kDataRequestActive, ot::kErrorNone, ot::Mle::kMaxChildKeepAliveAttempts, Tlv::kNetworkData, Mle::mChildUpdateAttempts, Mle::mChildUpdateRequestState, Mle::mDataRequestAttempts, Mle::mDataRequestState, Mle::mParent, Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildUpdateRequest(), Mle::SendDataRequest(), Address::SetToLinkLocalAddress(), and VerifyOrExit.
Referenced by Mle::HandleMessageTransmissionTimer().
HandleUdpReceive() [1/2]
void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References ot::AsCoreType().
Referenced by Mle::Enable().
HandleUdpReceive() [2/2]
void HandleUdpReceive (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References InterfaceIdentifier::ConvertToExtAddress(), ExitNow, NeighborTable::FindNeighbor(), NeighborTable::FindParent(), Mle::SecurityHeader::GetFrameCounter(), MessageInfo::GetHopLimit(), Address::GetIid(), Mle::SecurityHeader::GetKeyId(), Neighbor::GetKeySequence(), Neighbor::GetLinkFrameCounters(), MessageInfo::GetLinkInfo(), Neighbor::GetMleFrameCounter(), Message::GetOffset(), MessageInfo::GetPeerAddr(), Neighbor::GetRloc16(), MessageInfo::GetSockAddr(), MessageInfo::GetThreadLinkInfo(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleParentResponse(), IgnoreError(), Mle::IsDisabled(), ThreadLinkInfo::IsDstPanIdBroadcast(), Address::IsMulticast(), Mle::IsRouterOrLeader(), Mle::SecurityHeader::IsSecurityControlValid(), Neighbor::IsStateInvalid(), Neighbor::IsStateValid(), Mle::k154Security, Mle::RxInfo::kAuthoritativeMessage, Mle::kCommandAdvertisement, Mle::kCommandAnnounce, Mle::kCommandChildIdRequest, Mle::kCommandChildIdResponse, Mle::kCommandChildUpdateRequest, Mle::kCommandChildUpdateResponse, Mle::kCommandDataRequest, Mle::kCommandDataResponse, Mle::kCommandDiscoveryRequest, Mle::kCommandDiscoveryResponse, Mle::kCommandLinkAccept, Mle::kCommandLinkAcceptAndRequest, Mle::kCommandLinkMetricsManagementRequest, Mle::kCommandLinkMetricsManagementResponse, Mle::kCommandLinkProbe, Mle::kCommandLinkRequest, Mle::kCommandParentRequest, Mle::kCommandParentResponse, Mle::kCommandTimeSync, AesCcm::kDecrypt, ot::kErrorDrop, ot::kErrorDuplicated, ot::kErrorInvalidState, ot::kErrorNone, ot::kErrorParse, Neighbor::kInStateAnyExceptInvalid, Mle::kMleHopLimit, Mle::kNoSecurity, Mle::RxInfo::kPeerMessage, Mle::kTypeGenericUdp, Mle::RxInfo::kUnknown, LogDebg, LogInfo, Mle::LogProcessError(), Mle::RxInfo::mClass, Mle::RxInfo::mFrameCounter, Mle::RxInfo::mKeySequence, Mle::RxInfo::mNeighbor, Mle::mNeighborTable, Message::MoveOffset(), OT_ASSERT, Mle::ProcessMessageSecurity(), Message::Read(), Mle::ReestablishLinkWithNeighbor(), LinkFrameCounters::Reset(), Neighbor::SetKeySequence(), Neighbor::SetLinkAckFrameCounter(), Neighbor::SetMleFrameCounter(), SuccessOrExit, and VerifyOrExit.
ScheduleMessageTransmissionTimer()
void ScheduleMessageTransmissionTimer (void) private
References ExitNow, Mle::IsChild(), Mle::IsRxOnWhenIdle(), Mle::kChildUpdateRequestActive, Mle::kChildUpdateRequestNone, Mle::kChildUpdateRequestPending, ot::Mle::kChildUpdateRequestPendingDelay, Mle::kDataRequestActive, Mle::kDataRequestNone, ot::Mle::kMaxChildKeepAliveAttempts, ot::Mle::kUnicastRetransmissionDelay, ot::kUsPerTenSymbols, Mle::mChildUpdateRequestState, Mle::mDataRequestState, Mle::mMessageTransmissionTimer, Mle::mTimeout, Time::SecToMsec(), TimerMilli::Start(), and TimerMilli::Stop().
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::ScheduleChildUpdateRequest(), Mle::SendChildUpdateRequest(), Mle::SendDataRequest(), and Mle::SetStateChild().
ReestablishLinkWithNeighbor()
void ReestablishLinkWithNeighbor (Neighbor & aNeighbor) private
References ExitNow, Neighbor::GetRloc16(), IgnoreError(), Mle::IsActiveRouter(), Mle::IsAttached(), Mle::IsChild(), Mle::IsFullThreadDevice(), Neighbor::IsStateValid(), Mle::mParent, Mle::SendChildUpdateRequest(), and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleDetachGracefullyTimer() [1/2]
void HandleDetachGracefullyTimer (Timer & aTimer) static private
References GetProvider< InstanceGetProvider >::Get(), and Mle::HandleDetachGracefullyTimer().
HandleDetachGracefullyTimer() [2/2]
void HandleDetachGracefullyTimer (void) private
References Mle::IsDetachingGracefully(), OT_UNUSED_VARIABLE, and Mle::Stop().
Referenced by Mle::HandleDetachGracefullyTimer().
IsDetachingGracefully()
bool IsDetachingGracefully (void) inline private
References Mle::DetermineParentRequestType(), Mle::GetAttachStartDelay(), Mle::GetNextAnnouceChannel(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleLeaderData(), Mle::HandleParentResponse(), Mle::HasAcceptableParentCandidate(), Mle::HasMoreChannelsToAnnouce(), Mle::HasUnregisteredAddress(), Mle::IsBetterParent(), Mle::IsNetworkDataNewer(), Timer::IsRunning(), Mle::kNormalAnnounce, ot::MeshCoP::LogError(), Mle::mDetachGracefullyTimer, Mle::PrepareAnnounceState(), Mle::ProcessAnnounce(), Mle::ProcessMessageSecurity(), Mle::Reattach(), Mle::RemoveDelayedDataRequestMessage(), Mle::RemoveDelayedMessage(), Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
Referenced by Mle::DetachGracefully(), Mle::HandleChildUpdateResponse(), and Mle::HandleDetachGracefullyTimer().
SendChildUpdateRequest() [2/2]
Error SendChildUpdateRequest (bool aAppendChallenge, uint32_t aTimeout) private
References Mle::TxMessage::AppendAddressRegistrationTlv(), Mle::TxMessage::AppendChallengeTlv(), Mle::TxMessage::AppendLeaderDataTlv(), Mle::TxMessage::AppendModeTlv(), Mle::TxMessage::AppendSourceAddressTlv(), Mle::TxMessage::AppendTimeoutTlv(), Mle::BecomeDetached(), ExitNow, FreeMessageOnError, Mle::Challenge::GenerateRandom(), Neighbor::GetExtAddress(), IgnoreError(), Mle::IsDetached(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Neighbor::IsStateValidOrRestoring(), Mle::kAppendAllAddresses, Mle::kAppendMeshLocalOnly, Mle::kChildUpdateRequestActive, Mle::kCommandChildUpdateRequest, ot::kErrorNoBufs, ot::kErrorNone, Mle::kMessageSend, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Mle::kTypeChildUpdateRequestOfParent, Mle::Log(), LogWarn, Mle::mChildUpdateRequestState, Mle::mDeviceMode, Mle::mParent, Mle::mParentRequestChallenge, Mle::mRole, Mle::NewMleMessage(), OT_ASSERT, OT_UNREACHABLE_CODE, Mle::ScheduleMessageTransmissionTimer(), Mle::TxMessage::SendTo(), Address::SetToLinkLocalAddress(), SuccessOrExit, and VerifyOrExit.
HandleAdvertisement()
void HandleAdvertisement (RxInfo & aRxInfo) private
References Mle::BecomeDetached(), ExitNow, Mle::GetLeaderId(), LeaderData::GetLeaderRouterId(), TimerMilli::GetNow(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), Neighbor::GetRloc16(), ot::Random::NonCrypto::GetUint16InRange(), LeaderData::GetWeighting(), IgnoreError(), Mle::IsDetached(), Mle::IsFullThreadDevice(), Mle::IsNetworkDataNewer(), Neighbor::IsStateValid(), ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, Mle::kMessageReceive, Mle::kMleMaxResponseDelay, Tlv::kNetworkData, Mle::RxInfo::kPeerMessage, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Mle::kTypeAdvertisement, Mle::Log(), Mle::LogProcessError(), Mle::RxInfo::mClass, Mle::mLeaderData, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::RxInfo::mNeighbor, Mle::mParent, Mle::mRetrieveNewNetworkData, Mle::mRole, Mle::RxMessage::ReadLeaderDataTlv(), Mle::SendDataRequest(), Neighbor::SetLastHeard(), Mle::SetLeaderData(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), and Mle::IsDetachingGracefully().
HandleChildIdResponse()
void HandleChildIdResponse (RxInfo & aRxInfo) private
References Parent::Clear(), ExitNow, Tlv::FindTlvOffset(), LeaderData::GetDataVersion(), LeaderData::GetLeaderRouterId(), Tlv::GetLength(), Mle::GetNetworkDataType(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), LeaderData::GetWeighting(), IgnoreError(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Neighbor::IsStateValid(), Tlv::kActiveDataset, Mle::kAttachStateChildIdRequest, ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, ot::kErrorRejected, ot::kErrorSecurity, ot::NetworkData::kFullSet, Mle::kMessageReceive, Tlv::kNetworkData, Mle::RxInfo::kPeerMessage, Tlv::kPendingDataset, Mle::kReattachPending, ot::NetworkData::kStableSubset, Mle::kTypeChildIdResponse, Mle::Log(), Mle::LogProcessError(), Mle::mAttachState, Mle::RxInfo::mClass, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::RxInfo::mNeighbor, Mle::mParent, Mle::mParentCandidate, Mle::mReattachState, OT_TIME_SYNC_INVALID_SEQ, Message::Read(), Mle::RxMessage::ReadLeaderDataTlv(), Mle::RouterIdMatch(), Mle::SetLeaderData(), Neighbor::SetRloc16(), Mle::SetStateChild(), Mle::SetStateDetached(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), and Mle::IsDetachingGracefully().
HandleChildUpdateRequest()
void HandleChildUpdateRequest (RxInfo & aRxInfo) private
References Mle::TlvList::Add(), Mle::TlvList::AddElementsFrom(), Mle::BecomeDetached(), ExitNow, MessageInfo::GetPeerAddr(), Neighbor::GetRloc16(), Mle::HandleLeaderData(), IgnoreError(), Tlv::kCslTimeout, StatusTlv::kError, ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, Tlv::kLinkFrameCounter, Mle::kMessageReceive, Tlv::kMleFrameCounter, Mle::RxInfo::kPeerMessage, Tlv::kResponse, Tlv::kStatus, Mle::kTypeChildUpdateRequestOfParent, Mle::Log(), Mle::LogProcessError(), Mle::RxInfo::mClass, Mle::Challenge::mLength, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::RxInfo::mNeighbor, Mle::mParent, Mle::RxMessage::ReadChallengeTlv(), Mle::RxMessage::ReadTlvRequestTlv(), Mle::SendChildUpdateResponse(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), and Mle::IsDetachingGracefully().
HandleChildUpdateResponse()
void HandleChildUpdateResponse (RxInfo & aRxInfo) private
References Mle::BecomeDetached(), ExitNow, Neighbor::GetLinkFrameCounters(), MessageInfo::GetPeerAddr(), Mle::GetRloc16(), Mle::HandleLeaderData(), IgnoreError(), Mle::IsDetachingGracefully(), Mle::IsRxOnWhenIdle(), Neighbor::IsStateValid(), Mle::RxInfo::kAuthoritativeMessage, Mle::kChildUpdateRequestActive, Mle::kChildUpdateRequestNone, ot::kErrorDrop, ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, ot::kErrorSecurity, Mle::kMessageReceive, Mle::RxInfo::kPeerMessage, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, Neighbor::kStateValid, Mle::kTypeChildUpdateResponseOfParent, Mle::Log(), Mle::LogProcessError(), Mle::mChildUpdateAttempts, Mle::mChildUpdateRequestState, Mle::RxInfo::mClass, Mle::mDeviceMode, Mle::Challenge::mLength, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::RxInfo::mNeighbor, Mle::mParent, Mle::mParentRequestChallenge, Mle::mRetrieveNewNetworkData, Mle::mRole, Mle::mTimeout, OT_ASSERT, OT_FALL_THROUGH, OT_UNREACHABLE_CODE, Mle::RxMessage::ReadFrameCounterTlvs(), Mle::RxMessage::ReadResponseTlv(), Mle::RouterIdFromRloc16(), Mle::ScheduleMessageTransmissionTimer(), LinkFrameCounters::SetAll(), Neighbor::SetLinkAckFrameCounter(), Neighbor::SetMleFrameCounter(), Neighbor::SetState(), Mle::SetStateChild(), Mle::Stop(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), and Mle::IsDetachingGracefully().
HandleDataResponse()
void HandleDataResponse (RxInfo & aRxInfo) private
References Tlv::FindTlvValueOffset(), MessageInfo::GetPeerAddr(), Mle::HandleLeaderData(), Mle::IsRxOnWhenIdle(), Neighbor::IsStateValid(), Mle::kDataRequestNone, ot::kErrorDrop, ot::kErrorNone, Tlv::kLinkMetricsReport, Mle::kMessageReceive, Mle::RxInfo::kPeerMessage, Mle::kTypeDataResponse, Mle::Log(), Mle::LogProcessError(), Mle::RxInfo::mClass, Mle::mDataRequestState, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::RxInfo::mNeighbor, SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), and Mle::IsDetachingGracefully().
HandleParentResponse()
void HandleParentResponse (RxInfo & aRxInfo) private
References LinkQualityInfo::AddRss(), LinkQualityInfo::Clear(), LinkQualityInfo::ConvertLinkMarginToLinkQuality(), LinkQualityInfo::ConvertRssToLinkMargin(), InterfaceIdentifier::ConvertToExtAddress(), ExitNow, Tlv::FindTlv(), ConnectivityTlv::GetActiveRouters(), Neighbor::GetExtAddress(), ConnectivityTlv::GetIdSequence(), Address::GetIid(), ConnectivityTlv::GetLeaderCost(), Neighbor::GetLinkFrameCounters(), Neighbor::GetLinkInfo(), ConnectivityTlv::GetLinkQuality1(), ConnectivityTlv::GetLinkQuality2(), ConnectivityTlv::GetLinkQuality3(), ConnectivityTlv::GetParentPriority(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), ThreadLinkInfo::GetRss(), ConnectivityTlv::GetSedBufferSize(), ConnectivityTlv::GetSedDatagramCount(), MessageInfo::GetThreadLinkInfo(), CslAccuracy::Init(), Mle::IsAttached(), Mle::IsBetterParent(), Mle::IsChild(), Mle::IsDetached(), Mle::IsFullThreadDevice(), SerialNumber::IsGreater(), Neighbor::IsStateParentResponse(), ConnectivityTlv::IsValid(), Mle::kAnyPartition, Mle::RxInfo::kAuthoritativeMessage, Mle::kBetterParent, Mle::kBetterPartition, Mle::kDowngradeToReed, ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, Mle::kMessageReceive, DeviceMode::kModeFullNetworkData, DeviceMode::kModeFullThreadDevice, DeviceMode::kModeRxOnWhenIdle, Mle::kSamePartition, Mle::kSamePartitionRetry, Neighbor::kStateParentResponse, Mle::kTypeParentResponse, Mle::Log(), Mle::LogProcessError(), Mle::mAttachMode, Mle::RxInfo::mClass, otThreadParentResponseInfo::mExtAddr, otThreadParentResponseInfo::mIsAttached, Mle::RxInfo::mKeySequence, Mle::mLeaderData, otThreadParentResponseInfo::mLinkQuality1, otThreadParentResponseInfo::mLinkQuality2, otThreadParentResponseInfo::mLinkQuality3, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::mParent, Mle::mParentCandidate, Mle::mParentCandidateChallenge, Mle::mParentIsSingleton, Mle::mParentLeaderCost, Mle::mParentLeaderData, Mle::mParentLinkMargin, Mle::mParentLinkQuality1, Mle::mParentLinkQuality2, Mle::mParentLinkQuality3, Mle::mParentPriority, Mle::mParentRequestChallenge, Mle::mParentResponseCb, Mle::mParentResponseCbContext, Mle::mParentSedBufferSize, Mle::mParentSedDatagramCount, otThreadParentResponseInfo::mPriority, Mle::mReceivedResponseFromParent, otThreadParentResponseInfo::mRloc16, otThreadParentResponseInfo::mRssi, OT_THREAD_VERSION_1_1, Mle::RxMessage::ReadChallengeTlv(), Mle::RxMessage::ReadFrameCounterTlvs(), Mle::RxMessage::ReadLeaderDataTlv(), Mle::RxMessage::ReadResponseTlv(), Neighbor::ResetLinkFailures(), LinkFrameCounters::SetAll(), Neighbor::SetDeviceMode(), Neighbor::SetExtAddress(), Neighbor::SetKeySequence(), Neighbor::SetLinkAckFrameCounter(), Router::SetLinkQualityOut(), Neighbor::SetMleFrameCounter(), Neighbor::SetRloc16(), Neighbor::SetState(), Neighbor::SetVersion(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), and Mle::IsDetachingGracefully().
HandleAnnounce()
void HandleAnnounce (RxInfo & aRxInfo) private
References Timestamp::Compare(), Tlv::FindTlv(), Message::GetAverageRss(), ChannelTlv::GetChannel(), MessageInfo::GetPeerAddr(), Timestamp::GetSeconds(), Mle::IsDetached(), Timestamp::IsOrphanTimestamp(), ChannelTlv::IsValid(), ot::Mle::kAnnounceProcessTimeout, Mle::kAttachStateProcessAnnounce, ot::kErrorInvalidState, ot::kErrorNone, ot::kErrorParse, Mle::kMessageReceive, Mle::RxInfo::kPeerMessage, Mle::kTypeAnnounce, Mle::Log(), LogNote, Mle::LogProcessError(), Mle::mAlternateChannel, Mle::mAlternatePanId, Mle::mAlternateTimestamp, Mle::mAttachCounter, Mle::mAttachState, Mle::mAttachTimer, Mle::RxInfo::mClass, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::RxInfo::mNeighbor, Mle::SendAnnounce(), Mle::SetAttachState(), TimerMilli::Start(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), and Mle::IsDetachingGracefully().
HandleLeaderData()
Error HandleLeaderData (RxInfo & aRxInfo) private
References Timestamp::Compare(), ExitNow, Tlv::FindTlvOffset(), LeaderData::GetDataVersion(), Mle::GetLeaderId(), LeaderData::GetLeaderRouterId(), Tlv::GetLength(), Mle::GetNetworkDataType(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), ot::Random::NonCrypto::GetUint16InRange(), LeaderData::GetWeighting(), IgnoreError(), Mle::IsChild(), Mle::IsLeader(), Address::IsMulticast(), Mle::IsNetworkDataNewer(), Tlv::kActiveDataset, Mle::kDataRequestNone, ot::kErrorDrop, ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, ot::NetworkData::kFullSet, Mle::kMleMaxResponseDelay, Tlv::kNetworkData, Tlv::kPendingDataset, ot::NetworkData::kStableSubset, Mle::mDataRequestAttempts, Mle::mDataRequestState, Mle::mLeaderData, Mle::RxInfo::mMessage, Mle::RxInfo::mMessageInfo, Mle::mRetrieveNewNetworkData, Message::Read(), Mle::RxMessage::ReadLeaderDataTlv(), Mle::SendDataRequest(), Mle::SetLeaderData(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), and Mle::IsDetachingGracefully().
ProcessAnnounce()
void ProcessAnnounce (void) private
References IgnoreError(), Mle::kAnnounceAttach, Mle::kAttachStateProcessAnnounce, Mle::kKeepNetworkDatasets, LogNote, Mle::mAlternateChannel, Mle::mAlternatePanId, Mle::mAlternateTimestamp, Mle::mAttachState, OT_ASSERT, Mle::Start(), and Mle::Stop().
Referenced by Mle::HandleAttachTimer(), and Mle::IsDetachingGracefully().
HasUnregisteredAddress()
bool HasUnregisteredAddress (void) private
References ExitNow, Mle::GetMeshLocal64(), Mle::IsAnycastLocator(), Mle::IsRoutingLocator(), Mle::IsRxOnWhenIdle(), Mle::ScheduleChildUpdateRequest(), and VerifyOrExit.
Referenced by Mle::IsDetachingGracefully(), and Mle::SendChildUpdateResponse().
GetAttachStartDelay()
uint32_t GetAttachStartDelay (void) const private
References ot::Random::NonCrypto::AddJitter(), ExitNow, ot::Random::NonCrypto::GetUint32InRange(), Mle::IsDetached(), Mle::kAttachBackoffJitter, Mle::kAttachBackoffMaxInterval, Mle::kAttachBackoffMinInterval, ot::Mle::kAttachStartJitter, ot::Mle::kParentRequestRouterTimeout, LogNote, Mle::mAttachCounter, and VerifyOrExit.
Referenced by Mle::Attach(), and Mle::IsDetachingGracefully().
SendParentRequest()
void SendParentRequest (ParentRequestType aType) private
References Mle::TxMessage::AppendChallengeTlv(), Mle::TxMessage::AppendModeTlv(), Mle::TxMessage::AppendScanMaskTlv(), Mle::TxMessage::AppendVersionTlv(), FreeMessageOnError, Mle::Challenge::GenerateRandom(), Mle::kCommandParentRequest, ScanMaskTlv::kEndDeviceFlag, ot::kErrorNoBufs, ot::kErrorNone, Mle::kMessageSend, ScanMaskTlv::kRouterFlag, Mle::kToRouters, Mle::kToRoutersAndReeds, Mle::kTypeParentRequestToRouters, Mle::kTypeParentRequestToRoutersReeds, Mle::Log(), Mle::mDeviceMode, Mle::mParentRequestChallenge, Mle::NewMleMessage(), Mle::TxMessage::SendTo(), Address::SetToLinkLocalAllRoutersMulticast(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer(), and Mle::IsDetachingGracefully().
SendChildIdRequest()
Error SendChildIdRequest (void) private
References Mle::TxMessage::AppendActiveTimestampTlv(), Mle::TxMessage::AppendAddressRegistrationTlv(), Mle::TxMessage::AppendLinkFrameCounterTlv(), Mle::TxMessage::AppendMleFrameCounterTlv(), Mle::TxMessage::AppendModeTlv(), Mle::TxMessage::AppendPendingTimestampTlv(), Mle::TxMessage::AppendResponseTlv(), Mle::TxMessage::AppendTimeoutTlv(), Mle::TxMessage::AppendTlvRequestTlv(), Mle::TxMessage::AppendVersionTlv(), ExitNow, FreeMessageOnError, Neighbor::GetExtAddress(), Mle::IsChild(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Tlv::kAddress16, Mle::kAppendMeshLocalOnly, Mle::kCommandChildIdRequest, ot::kErrorAlready, ot::kErrorNoBufs, ot::kErrorNone, Mle::kMessageSend, Tlv::kNetworkData, Tlv::kRoute, Neighbor::kStateInvalid, Neighbor::kStateValid, Mle::kTypeChildIdRequest, Mle::kTypeChildIdRequestShort, Mle::Log(), LogInfo, Mle::mAddressRegistrationMode, Mle::mDeviceMode, Mle::mParent, Mle::mParentCandidate, Mle::mParentCandidateChallenge, Mle::mTimeout, Mle::NewMleMessage(), Mle::TxMessage::SendTo(), Neighbor::SetState(), Address::SetToLinkLocalAddress(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer(), Mle::IsDetachingGracefully(), and Mle::RequestShorterChildIdRequest().
GetNextAnnouceChannel()
Error GetNextAnnouceChannel (uint8_t & aChannel) const private
References ChannelMask::GetNextChannel(), and ot::kErrorNone.
Referenced by Mle::HandleAttachTimer(), Mle::HasMoreChannelsToAnnouce(), and Mle::IsDetachingGracefully().
HasMoreChannelsToAnnouce()
bool HasMoreChannelsToAnnouce (void) const private
References Message::Append(), Message::AppendBytes(), FreeMessageOnError, Mle::GetNextAnnouceChannel(), Tlv::GetSize(), Mle::kCommandLinkMetricsManagementResponse, Mle::kCommandLinkProbe, ot::kErrorNoBufs, ot::kErrorNone, Tlv::kLinkMetricsManagement, Tlv::kLinkProbe, Mle::mAnnounceChannel, Mle::NewMleMessage(), Mle::TxMessage::SendTo(), Tlv::SetLength(), Tlv::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HasAcceptableParentCandidate(), and Mle::IsDetachingGracefully().
PrepareAnnounceState()
bool PrepareAnnounceState (void) private
References ChannelMask::GetNumberOfChannels(), Mle::IsChild(), Mle::IsFullThreadDevice(), ot::Mle::kAnnounceTimeout, ot::kErrorNone, ot::Mle::kMinAnnounceDelay, Mle::kReattachStop, Mle::mAnnounceDelay, Mle::mReattachState, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer(), and Mle::IsDetachingGracefully().
SendAnnounce() [2/3]
void SendAnnounce (uint8_t aChannel, AnnounceMode aMode) private
References Mle::SendAnnounce(), and Address::SetToLinkLocalAllNodesMulticast().
SendAnnounce() [3/3]
void SendAnnounce (uint8_t aChannel, const Ip6::Address & aDestination, AnnounceMode aMode = kNormalAnnounce) private
References Mle::TxMessage::AppendActiveTimestampTlv(), Tlv::AppendTo(), Clearable< Type >::Clear(), FreeMessageOnError, ChannelTlv::Init(), Mle::kCommandAnnounce, ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, Mle::kNormalAnnounce, Mle::kOrphanAnnounce, LogInfo, Mle::NewMleMessage(), Mle::TxMessage::SendTo(), Timestamp::SetAuthoritative(), Message::SetChannel(), ChannelTlv::SetChannel(), ChannelTlv::SetChannelPage(), Message::SetLinkSecurityEnabled(), SuccessOrExit, and VerifyOrExit.
RemoveDelayedMessage()
void RemoveDelayedMessage (Message::SubType aSubType, MessageType aMessageType, const Ip6::Address * aDestination) private
References Mle::kMessageRemoveDelayed, Mle::Log(), Mle::mDelayedResponses, Mle::DelayedResponseMetadata::mDestination, and Mle::DelayedResponseMetadata::ReadFrom().
Referenced by Mle::IsDetachingGracefully(), Mle::RemoveDelayedDataRequestMessage(), and Mle::RemoveDelayedDataResponseMessage().
RemoveDelayedDataRequestMessage()
void RemoveDelayedDataRequestMessage (const Ip6::Address & aDestination) private
References Message::kSubTypeMleDataRequest, Mle::kTypeDataRequest, and Mle::RemoveDelayedMessage().
Referenced by Mle::IsDetachingGracefully(), and Mle::SendDataRequest().
Reattach()
uint32_t Reattach (void) private
References Mle::Attach(), Mle::BecomeDetached(), ot::Random::NonCrypto::GetUint32InRange(), IgnoreError(), Mle::IsChild(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Mle::kAnyPartition, ot::Mle::kAttachStartJitter, Mle::kAttachStateStart, Mle::kBetterParent, Mle::kBetterPartition, Mle::kDowngradeToReed, ot::kErrorNone, ot::Mac::kPanIdBroadcast, Mle::kReattachActive, Mle::kReattachPending, Mle::kReattachStop, Mle::kSamePartition, Mle::kSamePartitionRetry, Mle::mAlternateChannel, Mle::mAlternatePanId, Mle::mAttachMode, Mle::mReattachState, Mle::Restore(), Mle::SetAttachState(), and VerifyOrExit.
Referenced by Mle::HandleAttachTimer(), and Mle::IsDetachingGracefully().
HasAcceptableParentCandidate()
bool HasAcceptableParentCandidate (void) const private
References Mle::DetermineParentRequestType(), ExitNow, Neighbor::GetLinkInfo(), LinkQualityInfo::GetLinkQuality(), Router::GetLinkQualityOut(), Mle::HasMoreChannelsToAnnouce(), Mle::IsChild(), Neighbor::IsStateParentResponse(), Mle::kAttachStateAnnounce, Mle::kAttachStateParentRequest, Mle::kBetterPartition, ot::kLinkQuality3, Mle::kToRouters, Mle::mAttachMode, Mle::mAttachState, ot::Min(), Mle::mParentCandidate, Mle::mReceivedResponseFromParent, SuccessOrAssert, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer(), and Mle::IsDetachingGracefully().
DetermineParentRequestType()
Error DetermineParentRequestType (ParentRequestType & aType) const private
References Mle::kAttachStateParentRequest, Mle::kBetterParent, ot::kErrorNone, ot::kErrorNotFound, Mle::kFirstAttachCycleNumParentRequestToRouters, Mle::kFirstAttachCycleTotalParentRequests, Mle::kNextAttachCycleNumParentRequestToRouters, Mle::kNextAttachCycleTotalParentRequests, Mle::kSamePartition, Mle::kSamePartitionRetry, Mle::kToRouters, Mle::kToRoutersAndReeds, Mle::mAttachCounter, Mle::mAttachMode, Mle::mAttachState, Mle::mParentRequestCounter, OT_ASSERT, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer(), Mle::HasAcceptableParentCandidate(), and Mle::IsDetachingGracefully().
IsBetterParent()
bool IsBetterParent (uint16_t aRloc16, LinkQuality aLinkQuality, uint8_t aLinkMargin, const ConnectivityTlv & aConnectivityTlv, uint16_t aVersion, const Mac::CslAccuracy & aCslAccuracy) private
References ExitNow, Neighbor::GetLinkInfo(), LinkQualityInfo::GetLinkQuality(), ConnectivityTlv::GetLinkQuality1(), ConnectivityTlv::GetLinkQuality2(), ConnectivityTlv::GetLinkQuality3(), Router::GetLinkQualityOut(), ConnectivityTlv::GetParentPriority(), Neighbor::GetRloc16(), ConnectivityTlv::GetSedBufferSize(), ConnectivityTlv::GetSedDatagramCount(), Neighbor::GetVersion(), Mle::IsActiveRouter(), Mle::IsRxOnWhenIdle(), ot::Min(), Mle::mParentCandidate, Mle::mParentLinkMargin, Mle::mParentLinkQuality1, Mle::mParentLinkQuality2, Mle::mParentLinkQuality3, Mle::mParentPriority, Mle::mParentSedBufferSize, Mle::mParentSedDatagramCount, and OT_UNUSED_VARIABLE.
Referenced by Mle::HandleParentResponse(), and Mle::IsDetachingGracefully().
IsNetworkDataNewer()
bool IsNetworkDataNewer (const LeaderData & aLeaderData) private
References LeaderData::GetDataVersion(), Mle::GetNetworkDataType(), and SerialNumber::IsGreater().
Referenced by Mle::HandleAdvertisement(), Mle::HandleLeaderData(), and Mle::IsDetachingGracefully().
ProcessMessageSecurity()
Error ProcessMessageSecurity (Crypto::AesCcm::Mode aMode, Message & aMessage, const Ip6::MessageInfo & aMessageInfo, uint16_t aCmdOffset, const SecurityHeader & aHeader) private
References Message::Append(), Message::Compare(), InterfaceIdentifier::ConvertToExtAddress(), ExitNow, AesCcm::Finalize(), AesCcm::GenerateNonce(), Mle::SecurityHeader::GetFrameCounter(), Address::GetIid(), Mle::SecurityHeader::GetKeyId(), Message::GetLength(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), AesCcm::Header(), IgnoreError(), AesCcm::Init(), AesCcm::kDecrypt, AesCcm::kEncrypt, ot::kErrorNone, ot::kErrorParse, ot::kErrorSecurity, Mle::kMleSecurityTagSize, AesCcm::kNonceSize, Frame::kSecEncMic32, AesCcm::Payload(), AesCcm::SetKey(), Message::SetLength(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive(), Mle::IsDetachingGracefully(), and Mle::TxMessage::SendTo().
Variable Documentation
kMleMaxResponseDelay
constexpr uint16_t kMleMaxResponseDelay = 1000u static protected
Max delay before responding to a multicast request.
Referenced by Mle::HandleAdvertisement(), and Mle::HandleLeaderData().
kMaxTlvListSize
constexpr uint8_t kMaxTlvListSize = 16 static protected
Maximum number of TLVs in a TlvList.
mBuffer
uint8_t mBuffer[kMaxChallengeSize]
Buffer containing the challenge/response byte sequence.
Referenced by Mle::TxMessage::AppendChallengeTlv(), Mle::TxMessage::AppendResponseTlv(), Mle::Challenge::operator==(), and Mle::RxMessage::ReadChallengeOrResponse().
mLength
uint8_t mLength
Challenge length (in bytes).
Referenced by Mle::TxMessage::AppendChallengeTlv(), Mle::TxMessage::AppendResponseTlv(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::Challenge::operator==(), and Mle::RxMessage::ReadChallengeOrResponse().
mMessage
RxMessage& mMessage
The MLE message.
Referenced by Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), DiscoverScanner::HandleDiscoveryResponse(), Mle::HandleLeaderData(), and Mle::HandleParentResponse().
mMessageInfo
const Ip6::MessageInfo& mMessageInfo
The MessageInfo associated with the message.
Referenced by Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), DiscoverScanner::HandleDiscoveryResponse(), Mle::HandleLeaderData(), and Mle::HandleParentResponse().
mFrameCounter [1/2]
uint32_t mFrameCounter
The frame counter from aux security header.
Referenced by Mle::HandleUdpReceive().
mKeySequence
uint32_t mKeySequence
The key sequence from aux security header.
Referenced by Mle::HandleParentResponse(), and Mle::HandleUdpReceive().
mNeighbor
Neighbor* mNeighbor
Neighbor from which message was received (can be nullptr).
Referenced by Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), and Mle::HandleUdpReceive().
mClass
Class mClass
The message class (authoritative, peer, or unknown).
Referenced by Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleParentResponse(), and Mle::HandleUdpReceive().
mLeaderAloc
Ip6::Netif::UnicastAddress mLeaderAloc protected
Leader anycast locator.
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::Mle(), Mle::SetMeshLocalPrefix(), Mle::SetStateChild(), and Mle::SetStateDetached().
mLeaderData
LeaderData mLeaderData protected
Last received Leader Data TLV.
Referenced by Mle::TxMessage::AppendLeaderDataTlv(), Mle::GetLeaderAddress(), Mle::GetLeaderData(), Mle::GetLeaderId(), Mle::HandleAdvertisement(), Mle::HandleLeaderData(), Mle::HandleParentResponse(), Mle::Mle(), Mle::SetLeaderData(), and Mle::Store().
mRetrieveNewNetworkData
bool mRetrieveNewNetworkData protected
Indicating new Network Data is needed if set.
Referenced by Mle::TxMessage::AppendNetworkDataTlv(), Mle::HandleAdvertisement(), Mle::HandleChildUpdateResponse(), and Mle::HandleLeaderData().
mRole
DeviceRole mRole protected
Current Thread role.
Referenced by Mle::GetRole(), Mle::HandleAdvertisement(), Mle::HandleChildUpdateResponse(), Mle::IsChild(), Mle::IsDetached(), Mle::IsDisabled(), Mle::IsLeader(), Mle::IsRouter(), Mle::SendChildUpdateRequest(), Mle::SetDeviceMode(), Mle::SetRole(), and Mle::Store().
mParent
Parent mParent protected
Parent information.
Referenced by Mle::BecomeDetached(), Mle::CheckReachability(), Mle::GetNextHop(), Mle::GetParent(), Mle::GetParentInfo(), Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::HandleParentResponse(), Mle::Mle(), Mle::ReestablishLinkWithNeighbor(), Mle::Restore(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SetRole(), Mle::SetStateChild(), and Mle::Store().
mParentCandidate
Parent mParentCandidate protected
Parent candidate information.
Referenced by Mle::Attach(), Mle::GetParentCandidate(), Mle::HandleAttachTimer(), Mle::HandleChildIdResponse(), Mle::HandleParentResponse(), Mle::HasAcceptableParentCandidate(), Mle::IsBetterParent(), Mle::Mle(), and Mle::SendChildIdRequest().
mNeighborTable
NeighborTable mNeighborTable protected
The neighbor table.
Referenced by Mle::HandleUdpReceive().
mDeviceMode
DeviceMode mDeviceMode protected
Device mode setting.
Referenced by Mle::GetDeviceMode(), Mle::GetNetworkDataType(), Mle::HandleChildUpdateResponse(), Mle::IsFullThreadDevice(), Mle::IsMinimalEndDevice(), Mle::IsRxOnWhenIdle(), Mle::Restore(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendParentRequest(), Mle::SetDeviceMode(), and Mle::Store().
mAttachState
AttachState mAttachState protected
The attach state.
Referenced by Mle::BecomeDetached(), Mle::DetermineParentRequestType(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::HandleChildIdResponse(), Mle::HasAcceptableParentCandidate(), Mle::IsAttaching(), Mle::ProcessAnnounce(), Mle::RequestShorterChildIdRequest(), and Mle::SetAttachState().
mParentRequestCounter
uint8_t mParentRequestCounter protected
Number of parent requests while in kAttachStateParentRequest.
Referenced by Mle::DetermineParentRequestType(), and Mle::HandleAttachTimer().
mReattachState
ReattachState mReattachState protected
Reattach state.
Referenced by Mle::Attach(), Mle::BecomeDetached(), Mle::HandleAttachTimer(), Mle::HandleChildIdResponse(), Mle::PrepareAnnounceState(), Mle::Reattach(), Mle::SetStateChild(), and Mle::Start().
mAttachCounter
uint16_t mAttachCounter protected
Attach attempt counter.
Referenced by Mle::Attach(), Mle::DetermineParentRequestType(), Mle::GetAttachStartDelay(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::SetDeviceMode(), and Mle::Start().
mAnnounceDelay
uint16_t mAnnounceDelay protected
Delay in between sending Announce messages during attach.
Referenced by Mle::HandleAttachTimer(), and Mle::PrepareAnnounceState().
mAttachTimer
TimerMilli mAttachTimer protected
The timer for driving the attach process.
Referenced by Mle::Attach(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::SetStateChild(), and Mle::SetStateDetached().
mDelayedResponseTimer
TimerMilli mDelayedResponseTimer protected
The timer to delay MLE responses.
Referenced by Mle::HandleDelayedResponseTimer(), and Mle::TxMessage::SendAfterDelay().
mMessageTransmissionTimer
TimerMilli mMessageTransmissionTimer protected
The timer for (re-)sending of MLE messages (e.g. Child Update).
Referenced by Mle::ScheduleMessageTransmissionTimer(), and Mle::SetStateDetached().
mParentLeaderCost
uint8_t mParentLeaderCost protected
Referenced by Mle::HandleParentResponse().
kMleHopLimit
constexpr uint8_t kMleHopLimit = 255 static private
Referenced by Mle::HandleUdpReceive(), and Mle::TxMessage::SendTo().
kMleSecurityTagSize
constexpr uint8_t kMleSecurityTagSize = 4 static private
Referenced by Mle::ProcessMessageSecurity().
kAttachBackoffMinInterval
constexpr uint32_t kAttachBackoffMinInterval = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MINIMUM_INTERVAL static private
Referenced by Mle::GetAttachStartDelay().
kAttachBackoffMaxInterval
constexpr uint32_t kAttachBackoffMaxInterval = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MAXIMUM_INTERVAL static private
Referenced by Mle::GetAttachStartDelay().
kAttachBackoffJitter
constexpr uint32_t kAttachBackoffJitter = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_JITTER_INTERVAL static private
Referenced by Mle::GetAttachStartDelay().
kAttachBackoffDelayToResetCounter
constexpr uint32_t kAttachBackoffDelayToResetCounter static private
Initial value:
=
        OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_DELAY_TO_RESET_BACKOFF_INTERVAL
Referenced by Mle::SetStateChild().
kFirstAttachCycleTotalParentRequests
constexpr uint8_t kFirstAttachCycleTotalParentRequests = 6 static private
Referenced by Mle::DetermineParentRequestType().
kFirstAttachCycleNumParentRequestToRouters
constexpr uint8_t kFirstAttachCycleNumParentRequestToRouters = 2 static private
Referenced by Mle::DetermineParentRequestType().
kNextAttachCycleTotalParentRequests
constexpr uint8_t kNextAttachCycleTotalParentRequests = 2 static private
Referenced by Mle::DetermineParentRequestType().
kNextAttachCycleNumParentRequestToRouters
constexpr uint8_t kNextAttachCycleNumParentRequestToRouters = 1 static private
Referenced by Mle::DetermineParentRequestType().
kDetachGracefullyTimeout
constexpr uint32_t kDetachGracefullyTimeout = 1000 static private
Referenced by Mle::DetachGracefully().
mDestination
Ip6::Address mDestination
Referenced by Mle::RemoveDelayedMessage(), Mle::TxMessage::SendAfterDelay(), and Mle::SendDelayedResponse().
mSendTime
TimeMilli mSendTime
Referenced by Mle::HandleDelayedResponseTimer(), and Mle::TxMessage::SendAfterDelay().
kKeyIdMode2Mic32
constexpr uint8_t kKeyIdMode2Mic32 = (Mac::Frame::kKeyIdMode2 | Mac::Frame::kSecEncMic32) static private
mSecurityControl
uint8_t mSecurityControl private
mFrameCounter [2/2]
uint32_t mFrameCounter private
mKeySource
uint32_t mKeySource private
mKeyIndex
uint8_t mKeyIndex private
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::Mle::Mle::SecurityHeader OT_TOOL_PACKED_END private
mDelayedResponses
MessageQueue mDelayedResponses private
Referenced by Mle::GetMessageQueue(), Mle::HandleDelayedResponseTimer(), Mle::RemoveDelayedMessage(), and Mle::TxMessage::SendAfterDelay().
mParentRequestChallenge
Challenge mParentRequestChallenge private
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
mAttachMode
AttachMode mAttachMode private
Referenced by Mle::Attach(), Mle::DetermineParentRequestType(), Mle::HandleAttachTimer(), Mle::HandleParentResponse(), Mle::HasAcceptableParentCandidate(), Mle::Reattach(), and Mle::SetStateChild().
mParentPriority
int8_t mParentPriority private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentLinkQuality3
uint8_t mParentLinkQuality3 private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentLinkQuality2
uint8_t mParentLinkQuality2 private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentLinkQuality1
uint8_t mParentLinkQuality1 private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentSedBufferSize
uint16_t mParentSedBufferSize private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentSedDatagramCount
uint8_t mParentSedDatagramCount private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mChildUpdateAttempts
uint8_t mChildUpdateAttempts private
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::SetStateChild(), Mle::SetStateDetached(), and Mle::Start().
mChildUpdateRequestState
ChildUpdateRequestState mChildUpdateRequestState private
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::ScheduleChildUpdateRequest(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildUpdateRequest(), Mle::SendDataRequest(), and Mle::SetStateDetached().
mDataRequestAttempts
uint8_t mDataRequestAttempts private
Referenced by Mle::HandleLeaderData(), Mle::HandleMessageTransmissionTimer(), Mle::SetStateChild(), and Mle::SetStateDetached().
mDataRequestState
DataRequestState mDataRequestState private
Referenced by Mle::HandleDataResponse(), Mle::HandleLeaderData(), Mle::HandleMessageTransmissionTimer(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendDataRequest(), and Mle::SetStateDetached().
mAddressRegistrationMode
AddressRegistrationMode mAddressRegistrationMode private
Referenced by Mle::HandleNotifierEvents(), Mle::RequestShorterChildIdRequest(), and Mle::SendChildIdRequest().
mHasRestored
bool mHasRestored private
Referenced by Mle::HasRestored(), and Mle::Restore().
mParentLinkMargin
uint8_t mParentLinkMargin private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentIsSingleton
bool mParentIsSingleton private
Referenced by Mle::HandleParentResponse().
mReceivedResponseFromParent
bool mReceivedResponseFromParent private
Referenced by Mle::HandleAttachTimer(), Mle::HandleParentResponse(), and Mle::HasAcceptableParentCandidate().
mParentLeaderData
LeaderData mParentLeaderData private
Referenced by Mle::HandleParentResponse(), and Mle::Mle().
mParentCandidateChallenge
Challenge mParentCandidateChallenge private
Referenced by Mle::HandleParentResponse(), and Mle::SendChildIdRequest().
mSocket
Ip6::Udp::Socket mSocket private
Referenced by Mle::Disable(), Mle::Enable(), Mle::NewMleMessage(), and Mle::TxMessage::SendTo().
mTimeout
uint32_t mTimeout private
Referenced by Mle::GetTimeout(), Mle::HandleChildUpdateResponse(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), and Mle::SetTimeout().
mPreviousParentRloc
uint16_t mPreviousParentRloc private
Referenced by Mle::CheckReachability(), Mle::Restore(), and Mle::SetStateChild().
mAnnounceChannel
uint8_t mAnnounceChannel private
Referenced by Mle::HandleAttachTimer(), and Mle::HasMoreChannelsToAnnouce().
mAlternateChannel
uint8_t mAlternateChannel private
Referenced by Mle::HandleAnnounce(), Mle::InformPreviousChannel(), Mle::ProcessAnnounce(), and Mle::Reattach().
mAlternatePanId
uint16_t mAlternatePanId private
Referenced by Mle::HandleAnnounce(), Mle::InformPreviousChannel(), Mle::IsAnnounceAttach(), Mle::ProcessAnnounce(), and Mle::Reattach().
mAlternateTimestamp
uint64_t mAlternateTimestamp private
Referenced by Mle::HandleAnnounce(), and Mle::ProcessAnnounce().
mCounters
otMleCounters mCounters private
Referenced by Mle::Attach(), Mle::GetCounters(), Mle::ResetCounters(), Mle::SetLeaderData(), Mle::SetRole(), and Mle::SetStateChild().
sMeshLocalPrefixInit
const otMeshLocalPrefix sMeshLocalPrefixInit static private
Initial value:
= {
    {0xfd, 0xde, 0xad, 0x00, 0xbe, 0xef, 0x00, 0x00},
}
Referenced by Mle::Mle().
mLinkLocal64
Ip6::Netif::UnicastAddress mLinkLocal64 private
Referenced by Mle::Disable(), Mle::GetLinkLocalAddress(), Mle::Mle(), Mle::TxMessage::SendTo(), and Mle::UpdateLinkLocalAddress().
mMeshLocal64
Ip6::Netif::UnicastAddress mMeshLocal64 private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::GetMeshLocal64(), Mle::HandleNotifierEvents(), Mle::Mle(), Mle::Restore(), Mle::SetMeshLocalPrefix(), Mle::Stop(), and Mle::Store().
mMeshLocal16
Ip6::Netif::UnicastAddress mMeshLocal16 private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::GetLocatorAddress(), Mle::GetMeshLocal16(), Mle::GetMeshLocalPrefix(), Mle::Mle(), Mle::SetMeshLocalPrefix(), Mle::SetRloc16(), and Mle::Stop().
mLinkLocalAllThreadNodes
Ip6::Netif::MulticastAddress mLinkLocalAllThreadNodes private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::GetLinkLocalAllThreadNodesAddress(), Mle::Mle(), Mle::SetMeshLocalPrefix(), and Mle::Stop().
mRealmLocalAllThreadNodes
Ip6::Netif::MulticastAddress mRealmLocalAllThreadNodes private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::GetRealmLocalAllThreadNodesAddress(), Mle::Mle(), Mle::SetMeshLocalPrefix(), and Mle::Stop().
mDetachGracefullyTimer
TimerMilli mDetachGracefullyTimer private
Referenced by Mle::DetachGracefully(), Mle::IsDetachingGracefully(), and Mle::Stop().
mDetachGracefullyCallback
otDetachGracefullyCallback mDetachGracefullyCallback private
Referenced by Mle::DetachGracefully(), and Mle::Stop().
mDetachGracefullyContext
void* mDetachGracefullyContext private
Referenced by Mle::DetachGracefully(), and Mle::Stop().
mParentResponseCb
otThreadParentResponseCallback mParentResponseCb private
Referenced by Mle::HandleParentResponse(), and Mle::RegisterParentResponseStatsCallback().
mParentResponseCbContext
void* mParentResponseCbContext private
Referenced by Mle::HandleParentResponse(), and Mle::RegisterParentResponseStatsCallback().
kMaxChildren
constexpr uint16_t kMaxChildren = OPENTHREAD_CONFIG_MLE_MAX_CHILDREN
kMaxChildKeepAliveAttempts
constexpr uint8_t kMaxChildKeepAliveAttempts = 4
Max keep alive attempts before reattach to a new Parent.
Referenced by Mle::HandleMessageTransmissionTimer(), and Mle::ScheduleMessageTransmissionTimer().
kFailedChildTransmissions
constexpr uint8_t kFailedChildTransmissions = OPENTHREAD_CONFIG_FAILED_CHILD_TRANSMISSIONS
Referenced by AddressResolver::HandleAddressError().
kMaxServiceAlocs
constexpr uint8_t kMaxServiceAlocs = OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_MAX_ALOCS
kUdpPort
constexpr uint16_t kUdpPort = 19788
MLE UDP Port.
Referenced by Filter::Accept(), Mle::Enable(), MeshForwarder::GetFramePriority(), Mle::TxMessage::SendTo(), and Udp::ShouldUsePlatformUdp().
kParentRequestRouterTimeout
constexpr uint32_t kParentRequestRouterTimeout = 750
Router Parent Request timeout (in msec)
Referenced by Mle::GetAttachStartDelay(), and Mle::HandleAttachTimer().
kParentRequestDuplicateMargin
constexpr uint32_t kParentRequestDuplicateMargin = 50
Margin for duplicate parent request.
kParentRequestReedTimeout
constexpr uint32_t kParentRequestReedTimeout = 1250
Router and REEDs Parent Request timeout (in msec)
Referenced by Mle::HandleAttachTimer().
kAttachStartJitter
constexpr uint32_t kAttachStartJitter = 50
Max jitter time added to start of attach (in msec)
Referenced by Mle::GetAttachStartDelay(), and Mle::Reattach().
kAnnounceProcessTimeout
constexpr uint32_t kAnnounceProcessTimeout = 250
Delay after Announce rx before channel/pan-id change.
Referenced by Mle::HandleAnnounce().
kAnnounceTimeout
constexpr uint32_t kAnnounceTimeout = 1400
Total timeout for sending Announce messages (in msec)
Referenced by Mle::PrepareAnnounceState().
kMinAnnounceDelay
constexpr uint32_t kMinAnnounceDelay = 80
Min delay between Announcement messages (in msec)
Referenced by Mle::PrepareAnnounceState().
kParentResponseMaxDelayRouters
constexpr uint32_t kParentResponseMaxDelayRouters = 500
Max response delay for Parent Req to routers (in msec)
kParentResponseMaxDelayAll
constexpr uint32_t kParentResponseMaxDelayAll = 1000
Max response delay for Parent Req to all (in msec)
kUnicastRetransmissionDelay
constexpr uint32_t kUnicastRetransmissionDelay = 1000
Base delay before an MLE unicast retx (in msec)
Referenced by Mle::ScheduleMessageTransmissionTimer().
kChildUpdateRequestPendingDelay
constexpr uint32_t kChildUpdateRequestPendingDelay = 100
Delay for aggregating Child Update Req (in msec)
Referenced by Mle::ScheduleMessageTransmissionTimer().
kMaxTransmissionCount
constexpr uint8_t kMaxTransmissionCount = 3
Max number of times an MLE message may be transmitted.
kMaxResponseDelay
constexpr uint32_t kMaxResponseDelay = 1000
Max response delay for a multicast request (in msec)
kMaxChildIdRequestTimeout
constexpr uint32_t kMaxChildIdRequestTimeout = 5000
Max delay to rx a Child ID Request (in msec)
kMaxChildUpdateResponseTimeout
constexpr uint32_t kMaxChildUpdateResponseTimeout = 2000
Max delay to rx a Child Update Response (in msec)
kMaxLinkRequestTimeout
constexpr uint32_t kMaxLinkRequestTimeout = 2000
Max delay to rx a Link Accept.
kMulticastLinkRequestDelay
constexpr uint8_t kMulticastLinkRequestDelay = 5
Max delay for sending a mcast Link Request (in sec)
kMinTimeoutKeepAlive
constexpr uint32_t kMinTimeoutKeepAlive = (((kMaxChildKeepAliveAttempts + 1) * kUnicastRetransmissionDelay) / 1000)
kMinPollPeriod
constexpr uint32_t kMinPollPeriod = OPENTHREAD_CONFIG_MAC_MINIMUM_POLL_PERIOD
kRetxPollPeriod
constexpr uint32_t kRetxPollPeriod = OPENTHREAD_CONFIG_MAC_RETX_POLL_PERIOD
kMinTimeoutDataPoll
constexpr uint32_t kMinTimeoutDataPoll = (kMinPollPeriod + kFailedChildTransmissions * kRetxPollPeriod) / 1000
kMinTimeout
constexpr uint32_t kMinTimeout = OT_MAX(kMinTimeoutKeepAlive, kMinTimeoutDataPoll)
Min timeout (in sec)
Referenced by Mle::SetTimeout().
kLinkAcceptMaxRouters
constexpr uint8_t kLinkAcceptMaxRouters = 20
Max Route TLV entries in a Link Accept message.
kLinkAcceptSequenceRollback
constexpr uint8_t kLinkAcceptSequenceRollback = 64
Route Sequence value rollback in a Link Accept message.
kMinChildId
constexpr uint16_t kMinChildId = 1
Minimum Child ID.
kMaxChildId
constexpr uint16_t kMaxChildId = 511
Maximum Child ID.
Referenced by Mle::ChildIdFromRloc16().
kRouterIdOffset
constexpr uint8_t kRouterIdOffset = 10
Bit offset of Router ID in RLOC16.
Referenced by Neighbor::GetRouterId(), Mle::Rloc16FromRouterId(), and Mle::RouterIdFromRloc16().
kRlocPrefixLength
constexpr uint8_t kRlocPrefixLength = 14
Prefix length of RLOC in bytes.
kMinChallengeSize
constexpr uint8_t kMinChallengeSize = 4
Minimum Challenge size in bytes.
Referenced by Mle::RxMessage::ReadChallengeOrResponse().
kMaxChallengeSize
constexpr uint8_t kMaxChallengeSize = 8
Maximum Challenge size in bytes.
Referenced by Mle::Challenge::GenerateRandom(), and Mle::RxMessage::ReadChallengeOrResponse().
kAdvertiseIntervalMin
constexpr uint32_t kAdvertiseIntervalMin = 1
Min Advertise interval (in sec)
kAdvertiseIntervalMax
constexpr uint32_t kAdvertiseIntervalMax = 32
Max Advertise interval (in sec)
kFailedRouterTransmissions
constexpr uint8_t kFailedRouterTransmissions = 4
kRouterIdReuseDelay
constexpr uint8_t kRouterIdReuseDelay = 100
(in sec)
kRouterIdSequencePeriod
constexpr uint32_t kRouterIdSequencePeriod = 10
(in sec)
kMaxNeighborAge
constexpr uint32_t kMaxNeighborAge = 100
(in sec)
kMaxRouteCost
constexpr uint8_t kMaxRouteCost = 16
Referenced by MeshForwarder::PrepareDataFrame().
kMaxRouterId
constexpr uint8_t kMaxRouterId = OT_NETWORK_MAX_ROUTER_ID
Max Router ID.
Referenced by NeighborTable::FindNeighbor().
kInvalidRouterId
constexpr uint8_t kInvalidRouterId = kMaxRouterId + 1
Value indicating incorrect Router ID.
kMaxRouters
constexpr uint8_t kMaxRouters = OPENTHREAD_CONFIG_MLE_MAX_ROUTERS
Referenced by Mpl::HandleSeedSetTimer().
kMinDowngradeNeighbors
constexpr uint8_t kMinDowngradeNeighbors = 7
kNetworkIdTimeout
constexpr uint8_t kNetworkIdTimeout = 120
(in sec)
kParentRouteToLeaderTimeout
constexpr uint8_t kParentRouteToLeaderTimeout = 20
(in sec)
kRouterSelectionJitter
constexpr uint8_t kRouterSelectionJitter = 120
(in sec)
kRouterDowngradeThreshold
constexpr uint8_t kRouterDowngradeThreshold = 23
kRouterUpgradeThreshold
constexpr uint8_t kRouterUpgradeThreshold = 16
kRouterUpgradeBorderRouterRequestThreshold
constexpr uint8_t kRouterUpgradeBorderRouterRequestThreshold = 2
Threshold to accept a router upgrade request with reason kBorderRouterRequest (number of BRs acting as router in Network Data).
kMaxLeaderToRouterTimeout
constexpr uint32_t kMaxLeaderToRouterTimeout = 90
(in sec)
kReedAdvertiseInterval
constexpr uint32_t kReedAdvertiseInterval = 570
(in sec)
kReedAdvertiseJitter
constexpr uint32_t kReedAdvertiseJitter = 60
(in sec)
kLeaderWeight
constexpr uint8_t kLeaderWeight = 64
Default leader weight.
kMleEndDeviceTimeout
constexpr uint32_t kMleEndDeviceTimeout = OPENTHREAD_CONFIG_MLE_CHILD_TIMEOUT_DEFAULT
(in sec)
kMeshLocalPrefixContextId
constexpr uint8_t kMeshLocalPrefixContextId = 0
0 is reserved for Mesh Local Prefix
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv(), LeaderBase::GetContext(), LeaderBase::GetContextForMeshLocalPrefix(), and Mle::TxMessage::SendAfterDelay().
kParentPriorityHigh
constexpr int8_t kParentPriorityHigh = 1
Parent Priority High.
kParentPriorityMedium
constexpr int8_t kParentPriorityMedium = 0
Parent Priority Medium (default)
kParentPriorityLow
constexpr int8_t kParentPriorityLow = -1
Parent Priority Low.
kParentPriorityUnspecified
constexpr int8_t kParentPriorityUnspecified = -2
Parent Priority Unspecified.
kLinkQuality3LinkCost
constexpr uint8_t kLinkQuality3LinkCost = 1
Link Cost for Link Quality 3.
kLinkQuality2LinkCost
constexpr uint8_t kLinkQuality2LinkCost = 2
Link Cost for Link Quality 2.
kLinkQuality1LinkCost
constexpr uint8_t kLinkQuality1LinkCost = 4
Link Cost for Link Quality 1.
kLinkQuality0LinkCost
constexpr uint8_t kLinkQuality0LinkCost = kMaxRouteCost
Link Cost for Link Quality 0.
kMplChildDataMessageTimerExpirations
constexpr uint8_t kMplChildDataMessageTimerExpirations = 0
Number of MPL retransmissions for Children.
Referenced by Mle::SetStateChild().
kMplRouterDataMessageTimerExpirations
constexpr uint8_t kMplRouterDataMessageTimerExpirations = 2
Number of MPL retransmissions for Routers.
kAloc16Leader
constexpr uint16_t kAloc16Leader = 0xfc00
Referenced by Mle::GetLeaderAloc().
kAloc16DhcpAgentStart
constexpr uint16_t kAloc16DhcpAgentStart = 0xfc01
kAloc16DhcpAgentEnd
constexpr uint16_t kAloc16DhcpAgentEnd = 0xfc0f
kAloc16ServiceStart
constexpr uint16_t kAloc16ServiceStart = 0xfc10
Referenced by InterfaceIdentifier::IsAnycastServiceLocator(), Mle::ServiceAlocFromId(), and Mle::ServiceIdFromAloc().
kAloc16ServiceEnd
constexpr uint16_t kAloc16ServiceEnd = 0xfc2f
Referenced by InterfaceIdentifier::IsAnycastServiceLocator().
kAloc16CommissionerStart
constexpr uint16_t kAloc16CommissionerStart = 0xfc30
Referenced by Mle::CommissionerAloc16FromId().
kAloc16CommissionerEnd
constexpr uint16_t kAloc16CommissionerEnd = 0xfc37
kAloc16BackboneRouterPrimary
constexpr uint16_t kAloc16BackboneRouterPrimary = 0xfc38
kAloc16CommissionerMask
constexpr uint16_t kAloc16CommissionerMask = 0x0007
Referenced by Mle::CommissionerAloc16FromId().
kAloc16NeighborDiscoveryAgentStart
constexpr uint16_t kAloc16NeighborDiscoveryAgentStart = 0xfc40
kAloc16NeighborDiscoveryAgentEnd
constexpr uint16_t kAloc16NeighborDiscoveryAgentEnd = 0xfc4e
kServiceMinId
constexpr uint8_t kServiceMinId = 0x00
Minimal Service ID.
kServiceMaxId
constexpr uint8_t kServiceMaxId = 0x0f
Maximal Service ID.
kRegistrationDelayDefault
constexpr uint16_t kRegistrationDelayDefault = 5
In seconds.
kMlrTimeoutDefault
constexpr uint32_t kMlrTimeoutDefault = 3600
In seconds.
kMlrTimeoutMin
constexpr uint32_t kMlrTimeoutMin = 300
In seconds.
Referenced by Leader::UpdateBackboneRouterPrimary().
kMlrTimeoutMax
constexpr uint32_t kMlrTimeoutMax = 0x7fffffff / 1000
In seconds (about 24 days).
Referenced by Leader::UpdateBackboneRouterPrimary().
kBackboneRouterRegistrationJitter
constexpr uint8_t kBackboneRouterRegistrationJitter = 5
In seconds.
kParentAggregateDelay
constexpr uint8_t kParentAggregateDelay = 5
In seconds.
kNoBufDelay
constexpr uint8_t kNoBufDelay = 5
In seconds.
kImmediateReRegisterDelay
constexpr uint8_t kImmediateReRegisterDelay = 1
In seconds.
KResponseTimeoutDelay
constexpr uint8_t KResponseTimeoutDelay = 30
In seconds.
kDuaDadPeriod
constexpr uint32_t kDuaDadPeriod = 100
Time period after which the address becomes "Preferred" if no duplicate address error (in seconds).
kDuaDadRepeats
constexpr uint8_t kDuaDadRepeats = 3
Maximum number of times the multicast DAD query and wait time DUA_DAD_QUERY_TIMEOUT are repeated by the BBR, as part of the DAD process.
kDuaRecentTime
constexpr uint32_t kDuaRecentTime = 20
Time period (in seconds) during which a DUA registration is considered 'recent' at a BBR.
kTimeSinceLastTransactionMax
constexpr uint32_t kTimeSinceLastTransactionMax = 10 * 86400
In seconds (10 days).
kDefaultBackboneHoplimit
constexpr uint8_t kDefaultBackboneHoplimit = 1
default hoplimit for Backbone Link Protocol messages
Friends
DiscoverScanner
friend class DiscoverScanner friend
ot::Notifier
friend class ot::Notifier friend
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale