OpenThread: Logging - Thread Stack
Logging - Thread Stack
API » Add-Ons
This module includes OpenThread logging related definitions.
Functions
void otDumpCritPlat (const char *aText, const void *aData, uint16_t aDataLength)
void otDumpDebgPlat (const char *aText, const void *aData, uint16_t aDataLength)
void otDumpInfoPlat (const char *aText, const void *aData, uint16_t aDataLength)
void otDumpNotePlat (const char *aText, const void *aData, uint16_t aDataLength)
void otDumpWarnPlat (const char *aText, const void *aData, uint16_t aDataLength)
void otLogCli (otLogLevel aLogLevel, const char *aFormat,...)
void otLogCritPlat (const char *aFormat,...)
void otLogDebgPlat (const char *aFormat,...)
otLogLevel otLoggingGetLevel (void)
otError otLoggingSetLevel (otLogLevel aLogLevel)
void otLogInfoPlat (const char *aFormat,...)
void otLogNotePlat (const char *aFormat,...)
void otLogWarnPlat (const char *aFormat,...)
Detailed Description
This module includes OpenThread logging related definitions.
Function Documentation
otLoggingGetLevel()
otLogLevel otLoggingGetLevel (void)
This function returns the current log level.
If dynamic log level feature OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE is enabled, this function returns the currently set dynamic log level. Otherwise, this function returns the build-time configured log level.
Returns
The log level.
References Instance::GetLogLevel(), ot::kErrorInvalidArgs, ot::kErrorNone, ot::kLogLevelNone, otLoggingSetLevel(), and VerifyOrExit.
Referenced by NcpBase::HandlePropertyGet(), and Interpreter::SetUserCommands().
otLoggingSetLevel()
otError otLoggingSetLevel (otLogLevel aLogLevel)
This function sets the log level.
Note
This function requires OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE=1.
Parameters
[in] aLogLevel The log level.
Return values
OT_ERROR_NONE Successfully updated log level.
OT_ERROR_INVALID_ARGS Log level value is invalid.
Referenced by NcpBase::HandlePropertyGet(), InitInstance(), otLoggingGetLevel(), and Interpreter::SetUserCommands().
otLogCritPlat()
void otLogCritPlat (const char * aFormat, ...)
This function emits a log message at critical log level.
This function is intended for use by platform. If OPENTHREAD_CONFIG_LOG_PLATFORM is not set or the current log level is below critical, this function does not emit any log message.
Parameters
[in] aFormat The format string.
[in] ... Arguments for the format specification.
References ot::kLogLevelCrit, kPlatformModuleName, and OT_UNUSED_VARIABLE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CheckRadioCapabilities(), RadioSpinel< InterfaceType, ProcessContextType >::CheckRcpApiVersion(), RadioSpinel< InterfaceType, ProcessContextType >::CheckSpinelVersion(), RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpUnexpectedReset(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), HdlcInterface::Init(), RadioSpinel< InterfaceType, ProcessContextType >::IsRcp(), otPlatAssertFail(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and HdlcInterface::ResetConnection().
otLogWarnPlat()
void otLogWarnPlat (const char * aFormat, ...)
This function emits a log message at warning log level.
This function is intended for use by platform. If OPENTHREAD_CONFIG_LOG_PLATFORM is not set or the current log level is below warning, this function does not emit any log message.
Parameters
[in] aFormat The format string.
[in] ... Arguments for the format specification.
References ot::kLogLevelWarn, kPlatformModuleName, and OT_UNUSED_VARIABLE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Enable(), HdlcInterface::HandleHdlcFrame(), RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), ot::Spinel::LogIfFail(), otPlatAlarmMilliStop(), otSysGetThreadNetifIndex(), platformAlarmInit(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), RadioSpinel< InterfaceType, ProcessContextType >::SetRadioRegion(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
otLogNotePlat()
void otLogNotePlat (const char * aFormat, ...)
This function emits a log message at note log level.
This function is intended for use by platform. If OPENTHREAD_CONFIG_LOG_PLATFORM is not set or the current log level is below note, this function does not emit any log message.
Parameters
[in] aFormat The format string.
[in] ... Arguments for the format specification.
References ot::kLogLevelNote, kPlatformModuleName, and OT_UNUSED_VARIABLE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CheckRcpApiVersion(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), otSysGetThreadNetifIndex(), RadioSpinel< InterfaceType, ProcessContextType >::RecoverFromRcpFailure(), and RadioSpinel< InterfaceType, ProcessContextType >::SetRadioRegion().
otLogInfoPlat()
void otLogInfoPlat (const char * aFormat, ...)
This function emits a log message at info log level.
This function is intended for use by platform. If OPENTHREAD_CONFIG_LOG_PLATFORM is not set or the current log level is below info, this function does not emit any log message.
Parameters
[in] aFormat The format string.
[in] ... Arguments for the format specification.
References ot::kLogLevelInfo, kPlatformModuleName, and OT_UNUSED_VARIABLE.
Referenced by ot::Posix::ExecuteCommand(), RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), otSysGetThreadNetifIndex(), and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
otLogDebgPlat()
void otLogDebgPlat (const char * aFormat, ...)
This function emits a log message at debug log level.
This function is intended for use by platform. If OPENTHREAD_CONFIG_LOG_PLATFORM is not set or the current log level is below debug, this function does not emit any log message.
Parameters
[in] aFormat The format string.
[in] ... Arguments for the format specification.
References ot::kLogLevelDebg, kPlatformModuleName, and OT_UNUSED_VARIABLE.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), otSysGetThreadNetifIndex(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
otDumpCritPlat()
void otDumpCritPlat (const char * aText, const void * aData, uint16_t aDataLength)
This function generates a memory dump at critical log level.
If OPENTHREAD_CONFIG_LOG_PLATFORM or OPENTHREAD_CONFIG_LOG_PKT_DUMP is not set or the current log level is below critical this function does not emit any log message.
Parameters
[in] aText A string that is printed before the bytes.
[in] aData A pointer to the data buffer.
[in] aDataLength Number of bytes in aData.
References ot::kLogLevelCrit, kPlatformModuleName, and OT_UNUSED_VARIABLE.
otDumpWarnPlat()
void otDumpWarnPlat (const char * aText, const void * aData, uint16_t aDataLength)
This function generates a memory dump at warning log level.
If OPENTHREAD_CONFIG_LOG_PLATFORM or OPENTHREAD_CONFIG_LOG_PKT_DUMP is not set or the current log level is below warning this function does not emit any log message.
Parameters
[in] aText A string that is printed before the bytes.
[in] aData A pointer to the data buffer.
[in] aDataLength Number of bytes in aData.
References ot::kLogLevelWarn, kPlatformModuleName, and OT_UNUSED_VARIABLE.
otDumpNotePlat()
void otDumpNotePlat (const char * aText, const void * aData, uint16_t aDataLength)
This function generates a memory dump at note log level.
If OPENTHREAD_CONFIG_LOG_PLATFORM or OPENTHREAD_CONFIG_LOG_PKT_DUMP is not set or the current log level is below note this function does not emit any log message.
Parameters
[in] aText A string that is printed before the bytes.
[in] aData A pointer to the data buffer.
[in] aDataLength Number of bytes in aData.
References ot::kLogLevelNote, kPlatformModuleName, and OT_UNUSED_VARIABLE.
otDumpInfoPlat()
void otDumpInfoPlat (const char * aText, const void * aData, uint16_t aDataLength)
This function generates a memory dump at info log level.
If OPENTHREAD_CONFIG_LOG_PLATFORM or OPENTHREAD_CONFIG_LOG_PKT_DUMP is not set or the current log level is below info this function does not emit any log message.
Parameters
[in] aText A string that is printed before the bytes.
[in] aData A pointer to the data buffer.
[in] aDataLength Number of bytes in aData.
References ot::kLogLevelInfo, kPlatformModuleName, and OT_UNUSED_VARIABLE.
Referenced by otSysGetThreadNetifIndex().
otDumpDebgPlat()
void otDumpDebgPlat (const char * aText, const void * aData, uint16_t aDataLength)
This function generates a memory dump at debug log level.
If OPENTHREAD_CONFIG_LOG_PLATFORM or OPENTHREAD_CONFIG_LOG_PKT_DUMP is not set or the current log level is below debug this function does not emit any log message.
Parameters
[in] aText A string that is printed before the bytes.
[in] aData A pointer to the data buffer.
[in] aDataLength Number of bytes in aData.
References ot::kLogLevelDebg, kPlatformModuleName, and OT_UNUSED_VARIABLE.
otLogCli()
void otLogCli (otLogLevel aLogLevel, const char * aFormat, ...)
This function emits a log message at a given log level.
This function is intended for use by CLI only. If OPENTHREAD_CONFIG_LOG_CLI is not set or the current log level is below the given log level, this function does not emit any log message.
Parameters
[in] aLogLevel The log level.
[in] aFormat The format string.
[in] ... Arguments for the format specification.
References ot::kLogLevelDebg, ot::kLogLevelNone, OT_ASSERT, OT_UNUSED_VARIABLE, and VerifyOrExit.
Referenced by Output::OutputFormatV().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale