OpenThread: Time Service
Time Service
Platform Abstraction
This module includes the platform abstraction for the time service.
Functions
uint64_t otPlatTimeGet (void)
uint16_t otPlatTimeGetXtalAccuracy (void)
Detailed Description
This module includes the platform abstraction for the time service.
Function Documentation
otPlatTimeGet()
uint64_t otPlatTimeGet (void)
Get the current time (64bits width).
Returns
The current time in microseconds.
References NS_PER_US, OT_EXIT_FAILURE, OT_POSIX_CLOCK_ID, US_PER_S, and VerifyOrDie.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), RadioSpinel< InterfaceType, ProcessContextType >::GetNow(), platformAlarmGetNow(), platformRadioUpdateFdSet(), RadioSpinel< InterfaceType, ProcessContextType >::ProcessRadioStateMachine(), HdlcInterface::ResetConnection(), RadioSpinel< InterfaceType, ProcessContextType >::Transmit(), HdlcInterface::WaitForWritable(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
otPlatTimeGetXtalAccuracy()
uint16_t otPlatTimeGetXtalAccuracy (void)
Get the device's XTAL accuracy.
Returns
The device's XTAL accuracy, in ppm.
Referenced by Mle::TxMessage::AppendAddressRegistrationTlv().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale