OpenThread: Factory Diagnostics - Platform
Factory Diagnostics - Platform
Platform Abstraction
This module includes the platform abstraction for diagnostics features.
Functions
void otPlatDiagAlarmCallback (otInstance *aInstance)
void otPlatDiagChannelSet (uint8_t aChannel)
bool otPlatDiagModeGet (void)
void otPlatDiagModeSet (bool aMode)
otError otPlatDiagProcess (otInstance *aInstance, uint8_t aArgsLength, char *aArgs[], char *aOutput, size_t aOutputMaxLen)
void otPlatDiagRadioReceived (otInstance *aInstance, otRadioFrame *aFrame, otError aError)
void otPlatDiagTxPowerSet (int8_t aTxPower)
Detailed Description
This module includes the platform abstraction for diagnostics features.
Function Documentation
otPlatDiagProcess()
otError otPlatDiagProcess (otInstance * aInstance, uint8_t aArgsLength, char * aArgs[], char * aOutput, size_t aOutputMaxLen)
This function processes a factory diagnostics command line.
The output of this function (the content written to aOutput) MUST terminate with \0 and the \0 is within the output buffer.
Parameters
[in] aInstance The OpenThread instance for current request.
[in] aArgsLength The number of arguments in aArgs.
[in] aArgs The arguments of diagnostics command line.
[out] aOutput The diagnostics execution result.
[in] aOutputMaxLen The output buffer size.
Return values
OT_ERROR_INVALID_ARGS The command is supported but invalid arguments provided.
OT_ERROR_NONE The command is successfully process.
OT_ERROR_INVALID_COMMAND The command is not valid or not supported.
Referenced by otPlatRadioGetReceiveSensitivity().
otPlatDiagModeSet()
void otPlatDiagModeSet (bool aMode)
This function enables/disables the factory diagnostics mode.
Parameters
[in] aMode TRUE to enable diagnostics mode, FALSE otherwise.
Referenced by otPlatRadioGetReceiveSensitivity().
otPlatDiagModeGet()
bool otPlatDiagModeGet (void)
This function indicates whether or not factory diagnostics mode is enabled.
Returns
TRUE if factory diagnostics mode is enabled, FALSE otherwise.
Referenced by otPlatRadioGetReceiveSensitivity(), platformAlarmProcess(), RadioSpinel< InterfaceType, ProcessContextType >::RadioReceive(), and RadioSpinel< InterfaceType, ProcessContextType >::TransmitDone().
otPlatDiagChannelSet()
void otPlatDiagChannelSet (uint8_t aChannel)
This function sets the channel to use for factory diagnostics.
Parameters
[in] aChannel The channel value.
Referenced by otPlatRadioGetReceiveSensitivity().
otPlatDiagTxPowerSet()
void otPlatDiagTxPowerSet (int8_t aTxPower)
This function sets the transmit power to use for factory diagnostics.
Parameters
[in] aTxPower The transmit power value.
Referenced by otPlatRadioGetReceiveSensitivity().
otPlatDiagRadioReceived()
void otPlatDiagRadioReceived (otInstance * aInstance, otRadioFrame * aFrame, otError aError)
This function processes the received radio frame.
Parameters
[in] aInstance The OpenThread instance for current request.
[in] aFrame The received radio frame.
[in] aError The received radio frame status.
Referenced by otPlatRadioGetReceiveSensitivity().
otPlatDiagAlarmCallback()
void otPlatDiagAlarmCallback (otInstance * aInstance)
This function processes the alarm event.
Parameters
[in] aInstance The OpenThread instance for current request.
Referenced by otPlatRadioGetReceiveSensitivity().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale