OpenThread: Command Line Interface
Command Line Interface
API » Add-Ons
This module includes functions that control the Thread stack's execution.
Typedefs
typedef int(* otCliOutputCallback) (void *aContext, const char *aFormat, va_list aArguments)
Functions
void otCliAppendResult (otError aError)
void otCliInit (otInstance *aInstance, otCliOutputCallback aCallback, void *aContext)
void otCliInputLine (char *aBuf)
void otCliOutputBytes (const uint8_t *aBytes, uint8_t aLength)
void otCliOutputFormat (const char *aFmt,...)
void otCliPlatLogv (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat, va_list aArgs)
void otCliSetUserCommands (const otCliCommand *aUserCommands, uint8_t aLength, void *aContext)
Detailed Description
This module includes functions that control the Thread stack's execution.
Typedef Documentation
otCliOutputCallback
typedef int(* otCliOutputCallback) (void *aContext, const char *aFormat, va_list aArguments)
This function pointer is called to notify about Console output.
Parameters
[out] aContext A user context pointer.
[in] aFormat The format string.
[in] aArguments The format string arguments.
Returns
Number of bytes written by the callback.
Function Documentation
otCliInit()
void otCliInit (otInstance * aInstance, otCliOutputCallback aCallback, void * aContext)
Initialize the CLI module.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aCallback A callback method called to process CLI output.
[in] aContext A user context pointer.
References Interpreter::Initialize().
Referenced by otAppCliInit().
otCliInputLine()
void otCliInputLine (char * aBuf)
This method is called to feed in a console input line.
Parameters
[in] aBuf A pointer to a null-terminated string.
References Interpreter::GetInterpreter(), and Interpreter::ProcessLine().
Referenced by otAppCliProcess().
otCliSetUserCommands()
void otCliSetUserCommands (const otCliCommand * aUserCommands, uint8_t aLength, void * aContext)
Set a user command table.
Parameters
[in] aUserCommands A pointer to an array with user commands.
[in] aLength aUserCommands length.
[in] aContext The context passed to the handler.
References Interpreter::GetInterpreter(), and Interpreter::SetUserCommands().
Referenced by main().
otCliOutputBytes()
void otCliOutputBytes (const uint8_t * aBytes, uint8_t aLength)
Write a number of bytes to the CLI console as a hex string.
Parameters
[in] aBytes A pointer to data which should be printed.
[in] aLength aBytes length.
References Interpreter::GetInterpreter(), and Output::OutputBytes().
otCliOutputFormat()
void otCliOutputFormat (const char * aFmt, ...)
Write formatted string to the CLI console
Parameters
[in] aFmt A pointer to the format string.
[in] ... A matching list of arguments.
References Interpreter::GetInterpreter(), and Output::OutputFormatV().
Referenced by ProcessNetif().
otCliAppendResult()
void otCliAppendResult (otError aError)
Write error code to the CLI console
If the aError is OT_ERROR_PENDING nothing will be outputted.
Parameters
[in] aError Error code value.
References Interpreter::GetInterpreter(), and Interpreter::OutputResult().
otCliPlatLogv()
void otCliPlatLogv (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, va_list aArgs)
Callback to write the OpenThread Log to the CLI console
Parameters
[in] aLogLevel The log level.
[in] aLogRegion The log region.
[in] aFormat A pointer to the format string.
[in] aArgs va_list matching aFormat.
References Interpreter::GetInterpreter(), Interpreter::IsInitialized(), OT_TOOL_WEAK, OT_UNUSED_VARIABLE, otNcpHandleDidReceiveNewLegacyUlaPrefix(), otNcpHandleLegacyNodeDidJoin(), otNcpRegisterLegacyHandlers(), Output::OutputFormatV(), Output::OutputLine(), Output::SetEmittingCommandOutput(), and VerifyOrExit.
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale