OpenThread: Core-tcp
Core-tcp
This module includes definitions for TCP/IPv6 sockets.
Data Structures
class Tcp::Endpoint
class Tcp::Header
class Tcp::Listener
class Tcp
Enumerations
enum : uint8_t {
kTimerDelack = 0, kTimerRexmtPersist = 1, kTimerKeep = 2, kTimer2Msl = 3,
kNumTimers = 4
}
enum { kDynamicPortMin = 49152, kDynamicPortMax = 65535 }
Functions
Error Abort (void)
bool AutoBind (const SockAddr &aPeer, SockAddr &aToBind, bool aBindAddress, bool aBindPort)
Error Bind (const SockAddr &aSockName)
static Error BsdErrorToOtError (int aBsdError)
bool CanBind (const SockAddr &aSockName)
void CancelTimer (uint8_t aTimerFlag)
Error CommitReceive (size_t aNumBytes, uint32_t aFlags)
Error Connect (const SockAddr &aSockName, uint32_t aFlags)
Error Deinitialize (void)
Error Deinitialize (void)
bool FirePendingCallbacks (void)
bool FirePendingTimers (TimeMilli aNow, bool &aHasFutureTimer, TimeMilli &aEarliestFutureExpiry)
static Endpoint & FromTcb (struct tcpcb &aTcb)
static Listener & FromTcbListen (struct tcpcb_listen &aTcbListen)
uint32_t GetAcknowledgmentNumber (void) const
size_t GetBacklogBytes (void) const
uint16_t GetChecksum (void) const
void * GetContext (void)
void * GetContext (void)
uint16_t GetDestinationPort (void) const
uint16_t GetFlags (void) const
Address & GetForeignIp6Address (void)
const Address & GetForeignIp6Address (void) const
size_t GetInFlightBytes (void) const
Instance & GetInstance (void) const
Instance & GetInstance (void) const
const SockAddr & GetLocalAddress (void) const
Address & GetLocalIp6Address (void)
const Address & GetLocalIp6Address (void) const
Address & GetLocalIp6Address (void)
const Address & GetLocalIp6Address (void) const
const SockAddr & GetPeerAddress (void) const
size_t GetSendBufferBytes (void) const
uint32_t GetSequenceNumber (void) const
uint16_t GetSourcePort (void) const
struct tcpcb & GetTcb (void)
const struct tcpcb & GetTcb (void) const
struct tcpcb_listen & GetTcbListen (void)
const struct tcpcb_listen & GetTcbListen (void) const
uint16_t GetUrgentPointer (void) const
uint16_t GetWindow (void) const
Error HandleMessage (ot::Ip6::Header &aIp6Header, Message &aMessage, MessageInfo &aMessageInfo)
static void HandleTasklet (Tasklet &aTasklet)
static void HandleTimer (Timer &aTimer)
Error Initialize (Instance &aInstance, const otTcpEndpointInitializeArgs &aArgs)
Error Initialize (Instance &aInstance, const otTcpListenerInitializeArgs &aArgs)
bool IsClosed (void) const
bool IsClosed (void) const
bool IsInitialized (const Endpoint &aEndpoint) const
bool IsInitialized (const Listener &aListener) const
bool IsTimerActive (uint8_t aTimerIndex)
Error Listen (const SockAddr &aSockName)
bool Matches (const MessageInfo &aMessageInfo) const
bool Matches (const MessageInfo &aMessageInfo) const
void PostCallbacksAfterSend (size_t aSent, size_t aBacklogBefore)
void ProcessCallbacks (void)
void ProcessSignals (Endpoint &aEndpoint, otLinkedBuffer *aPriorHead, size_t aPriorBacklog, struct tcplp_signals &aSignals)
void ProcessTimers (void)
Error ReceiveByReference (const otLinkedBuffer *&aBuffer)
Error ReceiveContiguify (void)
Error SendByExtension (size_t aNumBytes, uint32_t aFlags)
Error SendByReference (otLinkedBuffer &aBuffer, uint32_t aFlags)
Error SendEndOfStream (void)
void SetTimer (uint8_t aTimerFlag, uint32_t aDelay)
Error StopListening (void)
Tcp (Instance &aInstance)
static uint8_t TimerFlagToIndex (uint8_t aTimerFlag)
friend void ::tcplp_sys_set_timer (struct tcpcb *aTcb, uint8_t aTimerFlag, uint32_t aDelay)
friend void ::tcplp_sys_stop_timer (struct tcpcb *aTcb, uint8_t aTimerFlag)
Variables
static constexpr uint8_t kChecksumFieldOffset = 16
Byte offset of the Checksum field in the TCP header.
static constexpr uint8_t kDisconnectedCallbackFlag = (1 << 4)
static constexpr uint8_t kEstablishedCallbackFlag = (1 << 0)
static constexpr uint8_t kForwardProgressCallbackFlag = (1 << 2)
static constexpr uint8_t kReceiveAvailableCallbackFlag = (1 << 3)
static constexpr uint8_t kSendDoneCallbackFlag = (1 << 1)
uint32_t mAckNumber
uint16_t mChecksum
uint16_t mDestination
LinkedList< Endpoint > mEndpoints
uint16_t mEphemeralPort
uint16_t mFlags
LinkedList< Listener > mListeners
uint32_t mSequenceNumber
uint16_t mSource
Tasklet mTasklet
TimerMilli mTimer
uint16_t mUrgentPointer
uint16_t mWindow
ot::Ip6::Tcp::Header OT_TOOL_PACKED_END
Friends
class LinkedList< Endpoint >
class LinkedList< Listener >
class Tcp
Detailed Description
This module includes definitions for TCP/IPv6 sockets.
Enumeration Type Documentation
anonymous enum
anonymous enum : uint8_t private
Enumerator
kTimerDelack
kTimerRexmtPersist
kTimerKeep
kTimer2Msl
kNumTimers
anonymous enum
anonymous enum private
Enumerator
kDynamicPortMin
Service Name and Transport Protocol Port Number Registry.
kDynamicPortMax
Service Name and Transport Protocol Port Number Registry.
Function Documentation
Initialize() [1/2]
Error Initialize (Instance & aInstance, const otTcpEndpointInitializeArgs & aArgs)
Initializes a TCP endpoint.
Calling this function causes OpenThread to keep track of this Endpoint and store and retrieve TCP data inside of it. The application should refrain from directly accessing or modifying the fields in this Endpoint. If the application needs to reclaim the memory backing this Endpoint, it should call otTcpEndpointDeinitialize().
See also
otTcpEndpointInitialize in include/openthread/tcp.h.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aArgs A pointer to a structure of arguments.
Return values
kErrorNone Successfully opened the TCP endpoint.
kErrorFailed Failed to open the TCP endpoint.
GetInstance() [1/2]
Instance& GetInstance (void) const
Obtains the Instance that was associated with this Endpoint upon initialization.
See also
otTcpEndpointGetInstance
Returns
The Instance pointer associated with this Endpoint.
GetContext() [1/2]
void* GetContext (void) inline
Obtains the context pointer that was associated this Endpoint upon initialization.
See also
otTcpEndpointGetContext
Returns
The context pointer associated with this Endpoint.
References Tcp::Endpoint::Abort(), Tcp::Endpoint::Bind(), Tcp::Endpoint::CommitReceive(), Tcp::Endpoint::Connect(), Tcp::Endpoint::Deinitialize(), Tcp::Endpoint::GetLocalAddress(), Tcp::Endpoint::GetPeerAddress(), otTcpEndpoint::mContext, Tcp::Endpoint::ReceiveByReference(), Tcp::Endpoint::ReceiveContiguify(), Tcp::Endpoint::SendByExtension(), Tcp::Endpoint::SendByReference(), and Tcp::Endpoint::SendEndOfStream().
GetLocalAddress()
const SockAddr& GetLocalAddress (void) const
Obtains a pointer to a TCP endpoint's local host and port.
The contents of the host and port may be stale if this socket is not in a connected state and has not been bound after it was last disconnected.
See also
otTcpGetLocalAddress
Returns
The local host and port of this Endpoint.
Referenced by Tcp::Endpoint::GetContext().
GetPeerAddress()
const SockAddr& GetPeerAddress (void) const
Obtains a pointer to a TCP endpoint's peer's host and port.
The contents of the host and port may be stale if this socket is not in a connected state.
See also
otTcpGetPeerAddress
Returns
The host and port of the connection peer of this Endpoint.
Referenced by Tcp::Endpoint::GetContext().
Bind()
Error Bind (const SockAddr & aSockName)
Binds the TCP endpoint to an IP address and port.
See also
otTcpBind
Parameters
[in] aSockName The address and port to which to bind this TCP endpoint.
Return values
kErrorNone Successfully bound the TCP endpoint.
kErrorFailed Failed to bind the TCP endpoint.
Referenced by Tcp::Endpoint::GetContext().
Connect()
Error Connect (const SockAddr & aSockName, uint32_t aFlags)
Records the remote host and port for this connection.
By default TCP Fast Open is used. This means that this function merely records the remote host and port, and that the TCP connection establishment handshake only happens on the first call to otTcpSendByReference(). TCP Fast Open can be explicitly disabled using aFlags, in which case the TCP connection establishment handshake is initiated immediately.
See also
otTcpConnect
Parameters
[in] aSockName The IP address and port of the host to which to connect.
[in] aFlags Flags specifying options for this operation (see enumeration above).
Return values
kErrorNone Successfully completed the operation.
kErrorFailed Failed to complete the operation.
Referenced by Tcp::Endpoint::GetContext().
SendByReference()
Error SendByReference (otLinkedBuffer & aBuffer, uint32_t aFlags)
Adds data referenced by the linked buffer pointed to by aBuffer to the send buffer.
Upon a successful call to this function, the linked buffer and data it references are owned by the TCP stack; they should not be modified by the application until a "send done" callback returns ownership of those objects to the application. It is acceptable to call this function to add another linked buffer to the send queue, even if the "send done" callback for a previous invocation of this function has not yet fired.
Note that aBuffer should not be chained; its mNext field should be NULL. If additional data will be added right after this call, then the OT_TCP_SEND_MORE_TO_COME flag should be used as a hint to the TCP implementation.
See also
otTcpSendByReference
Parameters
[in] aBuffer A pointer to the linked buffer chain referencing data to add to the send buffer.
[in] aFlags Flags specifying options for this operation (see enumeration above).
Return values
kErrorNone Successfully added data to the send buffer.
kErrorFailed Failed to add data to the send buffer.
Referenced by Tcp::Endpoint::GetContext().
SendByExtension()
Error SendByExtension (size_t aNumBytes, uint32_t aFlags)
Adds data to the send buffer by extending the length of the final otLinkedBuffer in the send buffer by the specified amount.
If the send buffer is empty, then the operation fails.
See also
otTcpSendByExtension
Parameters
[in] aNumBytes The number of bytes by which to extend the length of the final linked buffer.
[in] aFlags Flags specifying options for this operation (see enumeration above).
Return values
kErrorNone Successfully added data to the send buffer.
kErrorFailed Failed to add data to the send buffer.
Referenced by Tcp::Endpoint::GetContext().
ReceiveByReference()
Error ReceiveByReference (const otLinkedBuffer *& aBuffer)
Provides the application with a linked buffer chain referencing data currently in the TCP receive buffer.
The linked buffer chain is valid until the "receive ready" callback is next invoked, or until the next call to otTcpReceiveContiguify() or otTcpCommitReceive().
See also
otTcpReceiveByReference
Parameters
[out] aBuffer A pointer to the linked buffer chain referencing data currently in the receive buffer.
Return values
kErrorNone Successfully completed the operation.
kErrorFailed Failed to complete the operation.
Referenced by Tcp::Endpoint::GetContext().
ReceiveContiguify()
Error ReceiveContiguify (void)
Reorganizes the receive buffer to be entirely contiguous in memory.
This is optional; an application can simply traverse the linked buffer chain obtained by calling otTcpReceiveByReference. Some applications may wish to call this function to make the receive buffer contiguous to simplify their data processing, but this comes at the expense of CPU time to reorganize the data in the receive buffer.
See also
otTcpReceiveContiguify
Return values
kErrorNone Successfully completed the operation.
kErrorFailed Failed to complete the operation.
Referenced by Tcp::Endpoint::GetContext().
CommitReceive()
Error CommitReceive (size_t aNumBytes, uint32_t aFlags)
Informs the TCP stack that the application has finished processing aNumBytes bytes of data at the start of the receive buffer and that the TCP stack need not continue maintaining those bytes in the receive buffer.
See also
otTcpCommitReceive
Parameters
[in] aNumBytes The number of bytes consumed.
[in] aFlags Flags specifying options for this operation (none yet).
Return values
kErrorNone Successfully completed the receive operation.
kErrorFailed Failed to complete the receive operation.
Referenced by Tcp::Endpoint::GetContext().
SendEndOfStream()
Error SendEndOfStream (void)
Informs the connection peer that this TCP endpoint will not send more data.
This should be used when the application has no more data to send to the connection peer. For this connection, future reads on the connection peer will result in the "end of stream" condition, and future writes on this connection endpoint will fail.
The "end of stream" condition only applies after any data previously provided to the TCP stack to send out has been received by the connection peer.
See also
otTcpSendEndOfStream
Return values
kErrorNone Successfully queued the "end of stream" condition for transmission.
kErrorFailed Failed to queue the "end of stream" condition for transmission.
Referenced by Tcp::Endpoint::GetContext().
Abort()
Error Abort (void)
Forcibly ends the TCP connection associated with this TCP endpoint.
This immediately makes the TCP endpoint free for use for another connection and empties the send and receive buffers, transferring ownership of any data provided by the application in otTcpSendByReference() calls back to the application. The TCP endpoint's callbacks and memory for the receive buffer remain associated with the TCP endpoint.
See also
otTcpAbort
Return values
kErrorNone Successfully aborted the TCP endpoint's connection.
kErrorFailed Failed to abort the TCP endpoint's connection.
Referenced by Tcp::Endpoint::GetContext().
Deinitialize() [1/2]
Error Deinitialize (void)
Deinitializes this TCP endpoint.
This means that OpenThread no longer keeps track of this TCP endpoint and deallocates all resources it has internally allocated for this TCP endpoint. The application can reuse the memory backing the TCP endpoint as it sees fit.
If it corresponds to a live TCP connection, the connection is terminated unceremoniously (as in otTcpAbort()). All resources the application has provided for this TCP endpoint (linked buffers for the send buffer, memory for the receive buffer, this Endpoint structure itself, etc.) are immediately returned to the application.
See also
otTcpEndpointDeinitialize
Return values
kErrorNone Successfully deinitialized the TCP endpoint.
kErrorFailed Failed to deinitialize the TCP endpoint.
Referenced by Tcp::Endpoint::GetContext(), and Tcp::Listener::GetContext().
FromTcb()
static Endpoint& FromTcb (struct tcpcb & aTcb) inline static
Converts a reference to a struct tcpcb to a reference to its enclosing Endpoint.
GetTcb() [1/2]
struct tcpcb& GetTcb (void) inline
Obtains a reference to this Endpoint's struct tcpcb.
References otTcpEndpoint::mTcb.
GetTcb() [2/2]
const struct tcpcb& GetTcb (void) const inline
Obtains a const reference to this Endpoint's struct tcpcb.
References Tcp::Endpoint::IsClosed(), otTcpEndpoint::mTcb, tcplp_sys_set_timer(), and tcplp_sys_stop_timer().
IsClosed() [1/2]
bool IsClosed (void) const
Checks if this Endpoint is in the closed state.
Referenced by Tcp::Endpoint::GetTcb(), and Tcp::Listener::GetTcbListen().
void ::tcplp_sys_set_timer()
void ::tcplp_sys_set_timer (struct tcpcb * aTcb, uint8_t aTimerFlag, uint32_t aDelay) private
void ::tcplp_sys_stop_timer()
void ::tcplp_sys_stop_timer (struct tcpcb * aTcb, uint8_t aTimerFlag) private
TimerFlagToIndex()
static uint8_t TimerFlagToIndex (uint8_t aTimerFlag) static private
IsTimerActive()
bool IsTimerActive (uint8_t aTimerIndex) private
SetTimer()
void SetTimer (uint8_t aTimerFlag, uint32_t aDelay) private
CancelTimer()
void CancelTimer (uint8_t aTimerFlag) private
FirePendingTimers()
bool FirePendingTimers (TimeMilli aNow, bool & aHasFutureTimer, TimeMilli & aEarliestFutureExpiry) private
PostCallbacksAfterSend()
void PostCallbacksAfterSend (size_t aSent, size_t aBacklogBefore) private
FirePendingCallbacks()
bool FirePendingCallbacks (void) private
GetSendBufferBytes()
size_t GetSendBufferBytes (void) const private
GetInFlightBytes()
size_t GetInFlightBytes (void) const private
GetBacklogBytes()
size_t GetBacklogBytes (void) const private
GetLocalIp6Address() [1/4]
Address& GetLocalIp6Address (void) private
Referenced by Tcp::Listener::GetTcbListen().
GetLocalIp6Address() [2/4]
const Address& GetLocalIp6Address (void) const private
GetForeignIp6Address() [1/2]
Address& GetForeignIp6Address (void) private
GetForeignIp6Address() [2/2]
const Address& GetForeignIp6Address (void) const private
Matches() [1/2]
bool Matches (const MessageInfo & aMessageInfo) const private
Referenced by Tcp::Listener::GetTcbListen().
Initialize() [2/2]
Error Initialize (Instance & aInstance, const otTcpListenerInitializeArgs & aArgs)
Initializes a TCP listener.
Calling this function causes OpenThread to keep track of the TCP listener and store and retrieve TCP data inside this Listener. The application should refrain from directly accessing or modifying the fields in this Listener. If the application needs to reclaim the memory backing this Listener, it should call otTcpListenerDeinitialize().
See also
otTcpListenerInitialize
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aArgs A pointer to a structure of arguments.
Return values
kErrorNone Successfully opened the TCP listener.
kErrorFailed Failed to open the TCP listener.
GetInstance() [2/2]
Instance& GetInstance (void) const
Obtains the otInstance that was associated with this Listener upon initialization.
See also
otTcpListenerGetInstance
Returns
The otInstance pointer associated with this Listener.
GetContext() [2/2]
void* GetContext (void) inline
Obtains the context pointer that was associated with this Listener upon initialization.
See also
otTcpListenerGetContext
Returns
The context pointer associated with this Listener.
References Tcp::Endpoint::Deinitialize(), and otTcpEndpoint::mContext.
Listen()
Error Listen (const SockAddr & aSockName)
Causes incoming TCP connections that match the specified IP address and port to trigger this TCP listener's callbacks.
See also
otTcpListen
Parameters
[in] aSockName The address and port on which to listen for incoming connections.
Return values
kErrorNone Successfully initiated listening on the TCP listener.
kErrorFailed Failed to initiate listening on the TCP listener.
StopListening()
Error StopListening (void)
Causes this TCP listener to stop listening for incoming connections.
See also
otTcpStopListening
Return values
kErrorNone Successfully stopped listening on the TCP listener.
kErrorFailed Failed to stop listening on the TCP listener.
Deinitialize() [2/2]
Error Deinitialize (void)
Deinitializes this TCP listener.
This means that OpenThread no longer keeps track of this TCP listener and deallocates all resources it has internally allocated for this TCP endpoint. The application can reuse the memory backing the TCP listener as it sees fit.
If the TCP listener is currently listening, it stops listening.
See also
otTcpListenerDeinitialize
Return values
kErrorNone Successfully deinitialized the TCP listener.
kErrorFailed Failed to deinitialize the TCP listener.
FromTcbListen()
static Listener& FromTcbListen (struct tcpcb_listen & aTcbListen) inline static
Converts a reference to a struct tcpcb_listen to a reference to its enclosing Listener.
GetTcbListen() [1/2]
struct tcpcb_listen& GetTcbListen (void) inline
Obtains a reference to this Listener's struct tcpcb_listen.
GetTcbListen() [2/2]
const struct tcpcb_listen& GetTcbListen (void) const inline
Obtains a const reference to this Listener's struct tcpcb_listen.
References Tcp::Endpoint::GetLocalIp6Address(), Tcp::Endpoint::IsClosed(), Tcp::Endpoint::Matches(), and OT_TOOL_PACKED_BEGIN.
IsClosed() [2/2]
bool IsClosed (void) const
Checks if this Listener is in the closed state.
GetLocalIp6Address() [3/4]
Address& GetLocalIp6Address (void) private
GetLocalIp6Address() [4/4]
const Address& GetLocalIp6Address (void) const private
Matches() [2/2]
bool Matches (const MessageInfo & aMessageInfo) const private
GetSourcePort()
uint16_t GetSourcePort (void) const inline
This method returns the TCP Source Port.
Returns
The TCP Source Port.
References ot::Encoding::BigEndian::HostSwap16().
GetDestinationPort()
uint16_t GetDestinationPort (void) const inline
This method returns the TCP Destination Port.
Returns
The TCP Destination Port.
References ot::Encoding::BigEndian::HostSwap16().
GetSequenceNumber()
uint32_t GetSequenceNumber (void) const inline
This method returns the TCP Sequence Number.
Returns
The TCP Sequence Number.
References ot::Encoding::BigEndian::HostSwap32().
GetAcknowledgmentNumber()
uint32_t GetAcknowledgmentNumber (void) const inline
This method returns the TCP Acknowledgment Sequence Number.
Returns
The TCP Acknowledgment Sequence Number.
References ot::Encoding::BigEndian::HostSwap32().
GetFlags()
uint16_t GetFlags (void) const inline
This method returns the TCP Flags.
Returns
The TCP Flags.
References ot::Encoding::BigEndian::HostSwap16().
GetWindow()
uint16_t GetWindow (void) const inline
This method returns the TCP Window.
Returns
The TCP Window.
References ot::Encoding::BigEndian::HostSwap16().
GetChecksum()
uint16_t GetChecksum (void) const inline
This method returns the TCP Checksum.
Returns
The TCP Checksum.
References ot::Encoding::BigEndian::HostSwap16().
GetUrgentPointer()
uint16_t GetUrgentPointer (void) const inline
This method returns the TCP Urgent Pointer.
Returns
The TCP Urgent Pointer.
References ot::Encoding::BigEndian::HostSwap16().
Tcp()
Tcp (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
HandleMessage()
Error HandleMessage (ot::Ip6::Header & aIp6Header, Message & aMessage, MessageInfo & aMessageInfo)
Processes a received TCP segment.
Parameters
[in] aIp6Header A reference to a structure containing the segment's IPv6 header.
[in] aMessage A reference to the message containing the TCP segment.
[in] aMessageInfo A reference to the message info associated with aMessage.
Return values
kErrorNone Successfully processed the TCP segment.
kErrorDrop Dropped the TCP segment due to an invalid checksum.
AutoBind()
bool AutoBind (const SockAddr & aPeer, SockAddr & aToBind, bool aBindAddress, bool aBindPort)
Automatically selects a local address and/or port for communication with the specified peer.
Parameters
[in] aPeer The peer's address and port.
[in,out] aToBind The SockAddr into which to store the selected address and/or port.
[in] aBindAddress If true, the local address is selected; if not, the current address in aToBind is treated as a given.
[in] aBindPort If true, the local port is selected; if not, the current port in aToBind is treated as a given.
Returns
True if successful, false otherwise.
IsInitialized() [1/2]
bool IsInitialized (const Endpoint & aEndpoint) const inline
Checks if an Endpoint is in the list of initialized endpoints.
References Tcp::mEndpoints.
IsInitialized() [2/2]
bool IsInitialized (const Listener & aListener) const inline
Checks if a Listener is in the list of initialized Listeners.
References Tcp::mListeners.
ProcessSignals()
void ProcessSignals (Endpoint & aEndpoint, otLinkedBuffer * aPriorHead, size_t aPriorBacklog, struct tcplp_signals & aSignals) private
BsdErrorToOtError()
static Error BsdErrorToOtError (int aBsdError) static private
CanBind()
bool CanBind (const SockAddr & aSockName) private
HandleTimer()
static void HandleTimer (Timer & aTimer) static private
ProcessTimers()
void ProcessTimers (void) private
HandleTasklet()
static void HandleTasklet (Tasklet & aTasklet) static private
ProcessCallbacks()
void ProcessCallbacks (void) private
Variable Documentation
kChecksumFieldOffset
constexpr uint8_t kChecksumFieldOffset = 16 static
Byte offset of the Checksum field in the TCP header.
Referenced by Checksum::UpdateMessageChecksum().
mSource
uint16_t mSource private
mDestination
uint16_t mDestination private
mSequenceNumber
uint32_t mSequenceNumber private
mAckNumber
uint32_t mAckNumber private
mFlags
uint16_t mFlags private
mWindow
uint16_t mWindow private
mChecksum
uint16_t mChecksum private
mUrgentPointer
uint16_t mUrgentPointer private
OT_TOOL_PACKED_END
ot::Ip6::Tcp::Header OT_TOOL_PACKED_END
kEstablishedCallbackFlag
constexpr uint8_t kEstablishedCallbackFlag = (1 << 0) static private
kSendDoneCallbackFlag
constexpr uint8_t kSendDoneCallbackFlag = (1 << 1) static private
kForwardProgressCallbackFlag
constexpr uint8_t kForwardProgressCallbackFlag = (1 << 2) static private
kReceiveAvailableCallbackFlag
constexpr uint8_t kReceiveAvailableCallbackFlag = (1 << 3) static private
kDisconnectedCallbackFlag
constexpr uint8_t kDisconnectedCallbackFlag = (1 << 4) static private
mTimer
TimerMilli mTimer private
mTasklet
Tasklet mTasklet private
mEndpoints
LinkedList<Endpoint> mEndpoints private
Referenced by Tcp::IsInitialized().
mListeners
LinkedList<Listener> mListeners private
Referenced by Tcp::IsInitialized().
mEphemeralPort
uint16_t mEphemeralPort private
Friends
Tcp
friend class Tcp friend
LinkedList< Endpoint >
friend class LinkedList< Endpoint > friend
LinkedList< Listener >
friend class LinkedList< Listener > friend
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale