OpenThread: Settings
Settings
Platform Abstraction
This module includes the platform abstraction for secure non-volatile storage of settings.
Enumerations
enum {
OT_SETTINGS_KEY_ACTIVE_DATASET = 0x0001, OT_SETTINGS_KEY_PENDING_DATASET = 0x0002, OT_SETTINGS_KEY_NETWORK_INFO = 0x0003, OT_SETTINGS_KEY_PARENT_INFO = 0x0004,
OT_SETTINGS_KEY_CHILD_INFO = 0x0005, OT_SETTINGS_KEY_SLAAC_IID_SECRET_KEY = 0x0007, OT_SETTINGS_KEY_DAD_INFO = 0x0008, OT_SETTINGS_KEY_SRP_ECDSA_KEY = 0x000b,
OT_SETTINGS_KEY_SRP_CLIENT_INFO = 0x000c, OT_SETTINGS_KEY_SRP_SERVER_INFO = 0x000d, OT_SETTINGS_KEY_BR_ULA_PREFIX = 0x000f, OT_SETTINGS_KEY_VENDOR_RESERVED_MIN = 0x8000,
OT_SETTINGS_KEY_VENDOR_RESERVED_MAX = 0xffff
}
Functions
otError otPlatSettingsAdd (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
void otPlatSettingsDeinit (otInstance *aInstance)
otError otPlatSettingsDelete (otInstance *aInstance, uint16_t aKey, int aIndex)
otError otPlatSettingsGet (otInstance *aInstance, uint16_t aKey, int aIndex, uint8_t *aValue, uint16_t *aValueLength)
void otPlatSettingsInit (otInstance *aInstance, const uint16_t *aSensitiveKeys, uint16_t aSensitiveKeysLength)
otError otPlatSettingsSet (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
void otPlatSettingsWipe (otInstance *aInstance)
otError otPosixSecureSettingsAdd (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
void otPosixSecureSettingsDeinit (otInstance *aInstance)
otError otPosixSecureSettingsDelete (otInstance *aInstance, uint16_t aKey, int aIndex)
otError otPosixSecureSettingsGet (otInstance *aInstance, uint16_t aKey, int aIndex, uint8_t *aValue, uint16_t *aValueLength)
void otPosixSecureSettingsInit (otInstance *aInstance)
otError otPosixSecureSettingsSet (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
void otPosixSecureSettingsWipe (otInstance *aInstance)
Detailed Description
This module includes the platform abstraction for secure non-volatile storage of settings.
This module includes the platform abstraction for non-volatile storage of settings.
Enumeration Type Documentation
anonymous enum
anonymous enum
This enumeration defines the keys of settings.
Note: When adding a new settings key, if the settings corresponding to the key contains security sensitive information, the developer MUST add the key to the array aSensitiveKeys which is passed in otPlatSettingsInit().
Enumerator
OT_SETTINGS_KEY_ACTIVE_DATASET
Active Operational Dataset.
OT_SETTINGS_KEY_PENDING_DATASET
Pending Operational Dataset.
OT_SETTINGS_KEY_NETWORK_INFO
Thread network information.
OT_SETTINGS_KEY_PARENT_INFO
Parent information.
OT_SETTINGS_KEY_CHILD_INFO
Child information.
OT_SETTINGS_KEY_SLAAC_IID_SECRET_KEY
SLAAC key to generate semantically opaque IID.
OT_SETTINGS_KEY_DAD_INFO
Duplicate Address Detection (DAD) information.
OT_SETTINGS_KEY_SRP_ECDSA_KEY
SRP client ECDSA public/private key pair.
OT_SETTINGS_KEY_SRP_CLIENT_INFO
The SRP client info (selected SRP server address).
OT_SETTINGS_KEY_SRP_SERVER_INFO
The SRP server info (UDP port).
OT_SETTINGS_KEY_BR_ULA_PREFIX
BR ULA prefix.
OT_SETTINGS_KEY_VENDOR_RESERVED_MIN
OT_SETTINGS_KEY_VENDOR_RESERVED_MAX
Function Documentation
otPosixSecureSettingsInit()
void otPosixSecureSettingsInit (otInstance * aInstance)
This function performs any initialization for the secure settings subsystem, if necessary.
Parameters
[in] aInstance The OpenThread instance structure.
Referenced by otPlatSettingsInit().
otPosixSecureSettingsDeinit()
void otPosixSecureSettingsDeinit (otInstance * aInstance)
This function performs any de-initialization for the secure settings subsystem, if necessary.
Parameters
[in] aInstance The OpenThread instance structure.
Referenced by otPlatSettingsDeinit().
otPosixSecureSettingsGet()
otError otPosixSecureSettingsGet (otInstance * aInstance, uint16_t aKey, int aIndex, uint8_t * aValue, uint16_t * aValueLength)
This function fetches the value of the setting identified by aKey and write it to the memory pointed to by aValue. It then writes the length to the integer pointed to by aValueLength. The initial value of aValueLength is the maximum number of bytes to be written to aValue.
This function can be used to check for the existence of a key without fetching the value by setting aValue and aValueLength to NULL. You can also check the length of the setting without fetching it by setting only aValue to NULL.
Note that the underlying storage implementation is not required to maintain the order of settings with multiple values. The order of such values MAY change after ANY write operation to the store.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the specific item to get.
[out] aValue A pointer to where the value of the setting should be written. May be set to NULL if just testing for the presence or length of a setting.
[in,out] aValueLength A pointer to the length of the value. When called, this pointer should point to an integer containing the maximum value size that can be written to aValue. At return, the actual length of the setting is written. This may be set to NULL if performing a presence check.
Return values
OT_ERROR_NONE The given setting was found and fetched successfully.
OT_ERROR_NOT_FOUND The given setting was not found in the setting store.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
Referenced by otPlatSettingsGet().
otPosixSecureSettingsSet()
otError otPosixSecureSettingsSet (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This function sets or replaces the value of a setting identified by aKey. If there was more than one value previously associated with aKey, then they are all deleted and replaced with this single entry.
Calling this function successfully may cause unrelated settings with multiple values to be reordered.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the setting to change.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The given setting was changed or staged.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
OT_ERROR_NO_BUFS No space remaining to store the given setting.
Referenced by otPlatSettingsSet().
otPosixSecureSettingsAdd()
otError otPosixSecureSettingsAdd (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This function adds the value to a setting identified by aKey, without replacing any existing values.
Note that the underlying implementation is not required to maintain the order of the items associated with a specific key. The added value may be added to the end, the beginning, or even somewhere in the middle. The order of any pre-existing values may also change.
Calling this function successfully may cause unrelated settings with multiple values to be reordered.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the setting to change.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The given setting was added or staged to be added.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
OT_ERROR_NO_BUFS No space remaining to store the given setting.
Referenced by otPlatSettingsAdd().
otPosixSecureSettingsDelete()
otError otPosixSecureSettingsDelete (otInstance * aInstance, uint16_t aKey, int aIndex)
This function deletes a specific value from the setting identified by aKey from the secure settings store.
Note that the underlying implementation is not required to maintain the order of the items associated with a specific key.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the value to be removed. If set to -1, all values for this aKey will be removed.
Return values
OT_ERROR_NONE The given key and index was found and removed successfully.
OT_ERROR_NOT_FOUND The given key or index was not found in the setting store.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
Referenced by otPlatSettingsDelete().
otPosixSecureSettingsWipe()
void otPosixSecureSettingsWipe (otInstance * aInstance)
This function deletes all settings from the secure settings store, resetting it to its initial factory state.
Parameters
[in] aInstance The OpenThread instance structure.
Referenced by otPlatSettingsWipe().
otPlatSettingsInit()
void otPlatSettingsInit (otInstance * aInstance, const uint16_t * aSensitiveKeys, uint16_t aSensitiveKeysLength)
Performs any initialization for the settings subsystem, if necessary.
This function also sets the sensitive keys that should be stored in the secure area.
Note that the memory pointed by aSensitiveKeys MUST not be released before aInstance is destroyed.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aSensitiveKeys A pointer to an array containing the list of sensitive keys. May be NULL only if aSensitiveKeysLength is 0, which means that there is no sensitive keys.
[in] aSensitiveKeysLength The number of entries in the aSensitiveKeys array.
References getSettingsFileName(), IsSystemDryRun(), kMaxFileNameSize, OPENTHREAD_CONFIG_POSIX_SETTINGS_PATH, OT_ERROR_NONE, OT_ERROR_PARSE, OT_EXIT_ERROR_ERRNO, OT_UNUSED_VARIABLE, otPosixSecureSettingsInit(), sSettingsFd, VerifyOrDie, and VerifyOrExit.
Referenced by SettingsDriver::Init().
otPlatSettingsDeinit()
void otPlatSettingsDeinit (otInstance * aInstance)
Performs any de-initialization for the settings subsystem, if necessary.
Parameters
[in] aInstance The OpenThread instance structure.
References IsSystemDryRun(), OT_EXIT_ERROR_ERRNO, OT_UNUSED_VARIABLE, otPosixSecureSettingsDeinit(), sSettingsFd, VerifyOrDie, and VerifyOrExit.
Referenced by SettingsDriver::Deinit().
otPlatSettingsGet()
otError otPlatSettingsGet (otInstance * aInstance, uint16_t aKey, int aIndex, uint8_t * aValue, uint16_t * aValueLength)
Fetches the value of a setting.
This function fetches the value of the setting identified by aKey and write it to the memory pointed to by aValue. It then writes the length to the integer pointed to by aValueLength. The initial value of aValueLength is the maximum number of bytes to be written to aValue.
This function can be used to check for the existence of a key without fetching the value by setting aValue and aValueLength to NULL. You can also check the length of the setting without fetching it by setting only aValue to NULL.
Note that the underlying storage implementation is not required to maintain the order of settings with multiple values. The order of such values MAY change after ANY write operation to the store.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the specific item to get.
[out] aValue A pointer to where the value of the setting should be written. May be set to NULL if just testing for the presence or length of a setting.
[in,out] aValueLength A pointer to the length of the value. When called, this pointer should point to an integer containing the maximum value size that can be written to aValue. At return, the actual length of the setting is written. This may be set to NULL if performing a presence check.
Return values
OT_ERROR_NONE The given setting was found and fetched successfully.
OT_ERROR_NOT_FOUND The given setting was not found in the setting store.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
References IsSystemDryRun(), OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, OT_EXIT_FAILURE, OT_UNUSED_VARIABLE, otPosixSecureSettingsGet(), ot::Posix::PlatformSettingsGet(), VerifyOrDie, and VerifyOrExit.
Referenced by SettingsDriver::Get().
otPlatSettingsSet()
otError otPlatSettingsSet (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
Sets or replaces the value of a setting.
This function sets or replaces the value of a setting identified by aKey.
Calling this function successfully may cause unrelated settings with multiple values to be reordered.
OpenThread stack guarantees to use otPlatSettingsSet() method for a aKey that was either previously set using otPlatSettingsSet() (i.e., contains a single value) or is empty and/or fully deleted (contains no value).
Platform layer can rely and use this fact for optimizing its implementation.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the setting to change.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The given setting was changed or staged.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
OT_ERROR_NO_BUFS No space remaining to store the given setting.
References OT_ERROR_NONE, otPosixSecureSettingsSet(), and ot::Posix::PlatformSettingsSet().
Referenced by SettingsDriver::Set().
otPlatSettingsAdd()
otError otPlatSettingsAdd (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
Adds a value to a setting.
This function adds the value to a setting identified by aKey, without replacing any existing values.
Note that the underlying implementation is not required to maintain the order of the items associated with a specific key. The added value may be added to the end, the beginning, or even somewhere in the middle. The order of any pre-existing values may also change.
Calling this function successfully may cause unrelated settings with multiple values to be reordered.
OpenThread stack guarantees to use otPlatSettingsAdd() method for a aKey that was either previously managed by otPlatSettingsAdd() (i.e., contains one or more items) or is empty and/or fully deleted (contains no value).
Platform layer can rely and use this fact for optimizing its implementation.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the setting to change.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The given setting was added or staged to be added.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
OT_ERROR_NO_BUFS No space remaining to store the given setting.
References OT_ERROR_NONE, OT_UNUSED_VARIABLE, otPosixSecureSettingsAdd(), and ot::Posix::PlatformSettingsAdd().
Referenced by SettingsDriver::Add().
otPlatSettingsDelete()
otError otPlatSettingsDelete (otInstance * aInstance, uint16_t aKey, int aIndex)
Removes a setting from the setting store.
This function deletes a specific value from the setting identified by aKey from the settings store.
Note that the underlying implementation is not required to maintain the order of the items associated with a specific key.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the value to be removed. If set to -1, all values for this aKey will be removed.
Return values
OT_ERROR_NONE The given key and index was found and removed successfully.
OT_ERROR_NOT_FOUND The given key or index was not found in the setting store.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
References otPosixSecureSettingsDelete(), and ot::Posix::PlatformSettingsDelete().
Referenced by SettingsDriver::Delete().
otPlatSettingsWipe()
void otPlatSettingsWipe (otInstance * aInstance)
Removes all settings from the setting store.
This function deletes all settings from the settings store, resetting it to its initial factory state.
Parameters
[in] aInstance The OpenThread instance structure.
References OT_EXIT_ERROR_ERRNO, OT_UNUSED_VARIABLE, otPosixSecureSettingsWipe(), sSettingsFd, and VerifyOrDie.
Referenced by SettingsDriver::Wipe().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale