OpenThread: Crypto - Platform
Crypto - Platform
Platform Abstraction
This module includes the platform abstraction for Crypto.
Data Structures
struct otCryptoContext
struct otCryptoKey
Typedefs
typedef struct otCryptoContext otCryptoContext
typedef struct otCryptoKey otCryptoKey
typedef uint32_t otCryptoKeyRef
Enumerations
enum {
OT_CRYPTO_KEY_USAGE_NONE = 0, OT_CRYPTO_KEY_USAGE_EXPORT = 1 << 0, OT_CRYPTO_KEY_USAGE_ENCRYPT = 1 << 1, OT_CRYPTO_KEY_USAGE_DECRYPT = 1 << 2,
OT_CRYPTO_KEY_USAGE_SIGN_HASH = 1 << 3
}
enum otCryptoKeyAlgorithm { OT_CRYPTO_KEY_ALG_VENDOR, OT_CRYPTO_KEY_ALG_AES_ECB, OT_CRYPTO_KEY_ALG_HMAC_SHA_256 }
enum otCryptoKeyStorage { OT_CRYPTO_KEY_STORAGE_VOLATILE, OT_CRYPTO_KEY_STORAGE_PERSISTENT }
enum otCryptoKeyType { OT_CRYPTO_KEY_TYPE_RAW, OT_CRYPTO_KEY_TYPE_AES, OT_CRYPTO_KEY_TYPE_HMAC }
Functions
otError otPlatCryptoAesEncrypt (otCryptoContext *aContext, const uint8_t *aInput, uint8_t *aOutput)
otError otPlatCryptoAesFree (otCryptoContext *aContext)
otError otPlatCryptoAesInit (otCryptoContext *aContext)
otError otPlatCryptoAesSetKey (otCryptoContext *aContext, const otCryptoKey *aKey)
otError otPlatCryptoDestroyKey (otCryptoKeyRef aKeyRef)
otError otPlatCryptoExportKey (otCryptoKeyRef aKeyRef, uint8_t *aBuffer, size_t aBufferLen, size_t *aKeyLen)
bool otPlatCryptoHasKey (otCryptoKeyRef aKeyRef)
otError otPlatCryptoHkdfDeinit (otCryptoContext *aContext)
otError otPlatCryptoHkdfExpand (otCryptoContext *aContext, const uint8_t *aInfo, uint16_t aInfoLength, uint8_t *aOutputKey, uint16_t aOutputKeyLength)
otError otPlatCryptoHkdfExtract (otCryptoContext *aContext, const uint8_t *aSalt, uint16_t aSaltLength, const otCryptoKey *aInputKey)
otError otPlatCryptoHkdfInit (otCryptoContext *aContext)
otError otPlatCryptoHmacSha256Deinit (otCryptoContext *aContext)
otError otPlatCryptoHmacSha256Finish (otCryptoContext *aContext, uint8_t *aBuf, size_t aBufLength)
otError otPlatCryptoHmacSha256Init (otCryptoContext *aContext)
otError otPlatCryptoHmacSha256Start (otCryptoContext *aContext, const otCryptoKey *aKey)
otError otPlatCryptoHmacSha256Update (otCryptoContext *aContext, const void *aBuf, uint16_t aBufLength)
otError otPlatCryptoImportKey (otCryptoKeyRef *aKeyRef, otCryptoKeyType aKeyType, otCryptoKeyAlgorithm aKeyAlgorithm, int aKeyUsage, otCryptoKeyStorage aKeyPersistence, const uint8_t *aKey, size_t aKeyLen)
void otPlatCryptoInit (void)
void otPlatCryptoRandomDeinit (void)
otError otPlatCryptoRandomGet (uint8_t *aBuffer, uint16_t aSize)
void otPlatCryptoRandomInit (void)
otError otPlatCryptoSha256Deinit (otCryptoContext *aContext)
otError otPlatCryptoSha256Finish (otCryptoContext *aContext, uint8_t *aHash, uint16_t aHashSize)
otError otPlatCryptoSha256Init (otCryptoContext *aContext)
otError otPlatCryptoSha256Start (otCryptoContext *aContext)
otError otPlatCryptoSha256Update (otCryptoContext *aContext, const void *aBuf, uint16_t aBufLength)
Detailed Description
This module includes the platform abstraction for Crypto.
Typedef Documentation
otCryptoKeyRef
typedef uint32_t otCryptoKeyRef
This datatype represents the key reference.
otCryptoKey
typedef struct otCryptoKey otCryptoKey
otCryptoContext
typedef struct otCryptoContext otCryptoContext
Enumeration Type Documentation
otCryptoKeyType
enum otCryptoKeyType
This enumeration defines the key types.
Enumerator
OT_CRYPTO_KEY_TYPE_RAW
Key Type: Raw Data.
OT_CRYPTO_KEY_TYPE_AES
Key Type: AES.
OT_CRYPTO_KEY_TYPE_HMAC
Key Type: HMAC.
otCryptoKeyAlgorithm
enum otCryptoKeyAlgorithm
This enumeration defines the key algorithms.
Enumerator
OT_CRYPTO_KEY_ALG_VENDOR
Key Algorithm: Vendor Defined.
OT_CRYPTO_KEY_ALG_AES_ECB
Key Algorithm: AES ECB.
OT_CRYPTO_KEY_ALG_HMAC_SHA_256
Key Algorithm: HMAC SHA-256.
anonymous enum
anonymous enum
This enumeration defines the key usage flags.
Enumerator
OT_CRYPTO_KEY_USAGE_NONE
Key Usage: Key Usage is empty.
OT_CRYPTO_KEY_USAGE_EXPORT
Key Usage: Key can be exported.
OT_CRYPTO_KEY_USAGE_ENCRYPT
Key Usage: Encryption (vendor defined).
OT_CRYPTO_KEY_USAGE_DECRYPT
Key Usage: AES ECB.
OT_CRYPTO_KEY_USAGE_SIGN_HASH
Key Usage: HMAC SHA-256.
otCryptoKeyStorage
enum otCryptoKeyStorage
This enumeration defines the key storage types.
Enumerator
OT_CRYPTO_KEY_STORAGE_VOLATILE
Key Persistence: Key is volatile.
OT_CRYPTO_KEY_STORAGE_PERSISTENT
Key Persistence: Key is persistent.
Function Documentation
otPlatCryptoInit()
void otPlatCryptoInit (void)
Initialize the Crypto module.
Referenced by KeyManager::KeyManager().
otPlatCryptoImportKey()
otError otPlatCryptoImportKey (otCryptoKeyRef * aKeyRef, otCryptoKeyType aKeyType, otCryptoKeyAlgorithm aKeyAlgorithm, int aKeyUsage, otCryptoKeyStorage aKeyPersistence, const uint8_t * aKey, size_t aKeyLen)
Import a key into PSA ITS.
Parameters
[in,out] aKeyRef Pointer to the key ref to be used for crypto operations.
[in] aKeyType Key Type encoding for the key.
[in] aKeyAlgorithm Key algorithm encoding for the key.
[in] aKeyUsage Key Usage encoding for the key (combinations of OT_CRYPTO_KEY_USAGE_*).
[in] aKeyPersistence Key Persistence for this key
[in] aKey Actual key to be imported.
[in] aKeyLen Length of the key to be imported.
Return values
OT_ERROR_NONE Successfully imported the key.
OT_ERROR_FAILED Failed to import the key.
OT_ERROR_INVALID_ARGS aKey was set to NULL.
Note
If OT_CRYPTO_KEY_STORAGE_PERSISTENT is passed for aKeyPersistence then aKeyRef is input and platform should use the given aKeyRef and MUST not change it.
If OT_CRYPTO_KEY_STORAGE_VOLATILE is passed for aKeyPersistence then aKeyRef is output, the initial value does not matter and platform API MUST update it to return the new key ref.
This API is only used by OT core when OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE is enabled.
otPlatCryptoExportKey()
otError otPlatCryptoExportKey (otCryptoKeyRef aKeyRef, uint8_t * aBuffer, size_t aBufferLen, size_t * aKeyLen)
Export a key stored in PSA ITS.
Parameters
[in] aKeyRef The key ref to be used for crypto operations.
[out] aBuffer Pointer to the buffer where key needs to be exported.
[in] aBufferLen Length of the buffer passed to store the exported key.
[out] aKeyLen Pointer to return the length of the exported key.
Return values
OT_ERROR_NONE Successfully exported aKeyRef.
OT_ERROR_FAILED Failed to export aKeyRef.
OT_ERROR_INVALID_ARGS aBuffer was NULL
Note
This API is only used by OT core when OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE is enabled.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::SetMacKey().
otPlatCryptoDestroyKey()
otError otPlatCryptoDestroyKey (otCryptoKeyRef aKeyRef)
Destroy a key stored in PSA ITS.
Parameters
[in] aKeyRef The key ref to be destroyed
Return values
OT_ERROR_NONE Successfully destroyed the key.
OT_ERROR_FAILED Failed to destroy the key.
Note
This API is only used by OT core when OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE is enabled.
otPlatCryptoHasKey()
bool otPlatCryptoHasKey (otCryptoKeyRef aKeyRef)
Check if the key ref passed has an associated key in PSA ITS.
Parameters
[in] aKeyRef The Key Ref to check.
Return values
TRUE There is an associated key with aKeyRef.
FALSE There is no associated key with aKeyRef.
Note
This API is only used by OT core when OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE is enabled.
otPlatCryptoHmacSha256Init()
otError otPlatCryptoHmacSha256Init (otCryptoContext * aContext)
Initialize the HMAC operation.
Parameters
[in] aContext Context for HMAC operation.
Return values
OT_ERROR_NONE Successfully initialized HMAC operation.
OT_ERROR_FAILED Failed to initialize HMAC operation.
OT_ERROR_INVALID_ARGS aContext was NULL
Note
The platform driver shall point the context to the correct object such as psa_mac_operation_t or mbedtls_md_context_t.
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by HmacSha256::HmacSha256().
otPlatCryptoHmacSha256Deinit()
otError otPlatCryptoHmacSha256Deinit (otCryptoContext * aContext)
Uninitialize the HMAC operation.
Parameters
[in] aContext Context for HMAC operation.
Return values
OT_ERROR_NONE Successfully uninitialized HMAC operation.
OT_ERROR_FAILED Failed to uninitialized HMAC operation.
OT_ERROR_INVALID_ARGS aContext was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by HmacSha256::~HmacSha256().
otPlatCryptoHmacSha256Start()
otError otPlatCryptoHmacSha256Start (otCryptoContext * aContext, const otCryptoKey * aKey)
Start HMAC operation.
Parameters
[in] aContext Context for HMAC operation.
[in] aKey Key material to be used for for HMAC operation.
Return values
OT_ERROR_NONE Successfully started HMAC operation.
OT_ERROR_FAILED Failed to start HMAC operation.
OT_ERROR_INVALID_ARGS aContext or aKey was NULL
References LiteralKey::GetBytes(), LiteralKey::GetLength(), ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by HmacSha256::Start().
otPlatCryptoHmacSha256Update()
otError otPlatCryptoHmacSha256Update (otCryptoContext * aContext, const void * aBuf, uint16_t aBufLength)
Update the HMAC operation with new input.
Parameters
[in] aContext Context for HMAC operation.
[in] aBuf A pointer to the input buffer.
[in] aBufLength The length of aBuf in bytes.
Return values
OT_ERROR_NONE Successfully updated HMAC with new input operation.
OT_ERROR_FAILED Failed to update HMAC operation.
OT_ERROR_INVALID_ARGS aContext or aBuf was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by HmacSha256::Update().
otPlatCryptoHmacSha256Finish()
otError otPlatCryptoHmacSha256Finish (otCryptoContext * aContext, uint8_t * aBuf, size_t aBufLength)
Complete the HMAC operation.
Parameters
[in] aContext Context for HMAC operation.
[out] aBuf A pointer to the output buffer.
[in] aBufLength The length of aBuf in bytes.
Return values
OT_ERROR_NONE Successfully completed HMAC operation.
OT_ERROR_FAILED Failed to complete HMAC operation.
OT_ERROR_INVALID_ARGS aContext or aBuf was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, OT_UNUSED_VARIABLE, and VerifyOrExit.
Referenced by HmacSha256::Finish().
otPlatCryptoAesInit()
otError otPlatCryptoAesInit (otCryptoContext * aContext)
Initialise the AES operation.
Parameters
[in] aContext Context for AES operation.
Return values
OT_ERROR_NONE Successfully Initialised AES operation.
OT_ERROR_FAILED Failed to Initialise AES operation.
OT_ERROR_INVALID_ARGS aContext was NULL
OT_ERROR_NO_BUFS Cannot allocate the context.
Note
The platform driver shall point the context to the correct object such as psa_key_id or mbedtls_aes_context_t.
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by AesEcb::AesEcb().
otPlatCryptoAesSetKey()
otError otPlatCryptoAesSetKey (otCryptoContext * aContext, const otCryptoKey * aKey)
Set the key for AES operation.
Parameters
[in] aContext Context for AES operation.
[out] aKey Key to use for AES operation.
Return values
OT_ERROR_NONE Successfully set the key for AES operation.
OT_ERROR_FAILED Failed to set the key for AES operation.
OT_ERROR_INVALID_ARGS aContext or aKey was NULL
References LiteralKey::GetBytes(), LiteralKey::GetLength(), ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by AesEcb::SetKey().
otPlatCryptoAesEncrypt()
otError otPlatCryptoAesEncrypt (otCryptoContext * aContext, const uint8_t * aInput, uint8_t * aOutput)
Encrypt the given data.
Parameters
[in] aContext Context for AES operation.
[in] aInput Pointer to the input buffer.
[in] aOutput Pointer to the output buffer.
Return values
OT_ERROR_NONE Successfully encrypted aInput.
OT_ERROR_FAILED Failed to encrypt aInput.
OT_ERROR_INVALID_ARGS aContext or aKey or aOutput were NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by AesEcb::Encrypt().
otPlatCryptoAesFree()
otError otPlatCryptoAesFree (otCryptoContext * aContext)
Free the AES context.
Parameters
[in] aContext Context for AES operation.
Return values
OT_ERROR_NONE Successfully freed AES context.
OT_ERROR_FAILED Failed to free AES context.
OT_ERROR_INVALID_ARGS aContext was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by AesEcb::~AesEcb().
otPlatCryptoHkdfInit()
otError otPlatCryptoHkdfInit (otCryptoContext * aContext)
Initialise the HKDF context.
Parameters
[in] aContext Context for HKDF operation.
Return values
OT_ERROR_NONE Successfully Initialised AES operation.
OT_ERROR_FAILED Failed to Initialise AES operation.
OT_ERROR_INVALID_ARGS aContext was NULL
Note
The platform driver shall point the context to the correct object such as psa_key_derivation_operation_t or HmacSha256::Hash
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by HkdfSha256::HkdfSha256().
otPlatCryptoHkdfExpand()
otError otPlatCryptoHkdfExpand (otCryptoContext * aContext, const uint8_t * aInfo, uint16_t aInfoLength, uint8_t * aOutputKey, uint16_t aOutputKeyLength)
Perform HKDF Expand step.
Parameters
[in] aContext Operation context for HKDF operation.
[in] aInfo Pointer to the Info sequence.
[in] aInfoLength Length of the Info sequence.
[out] aOutputKey Pointer to the output Key.
[in] aOutputKeyLength Size of the output key buffer.
Return values
OT_ERROR_NONE HKDF Expand was successful.
OT_ERROR_FAILED HKDF Expand failed.
OT_ERROR_INVALID_ARGS aContext was NULL
References HmacSha256::Finish(), Sha256::Hash::GetBytes(), ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, Key::Set(), HmacSha256::Start(), HmacSha256::Update(), and VerifyOrExit.
Referenced by HkdfSha256::Expand().
otPlatCryptoHkdfExtract()
otError otPlatCryptoHkdfExtract (otCryptoContext * aContext, const uint8_t * aSalt, uint16_t aSaltLength, const otCryptoKey * aInputKey)
Perform HKDF Extract step.
Parameters
[in] aContext Operation context for HKDF operation.
[in] aSalt Pointer to the Salt for HKDF.
[in] aSaltLength Length of Salt.
[in] aInputKey Pointer to the input key.
Return values
OT_ERROR_NONE HKDF Extract was successful.
OT_ERROR_FAILED HKDF Extract failed.
References HmacSha256::Finish(), LiteralKey::GetBytes(), LiteralKey::GetLength(), ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, Key::Set(), HmacSha256::Start(), HmacSha256::Update(), and VerifyOrExit.
Referenced by HkdfSha256::Extract().
otPlatCryptoHkdfDeinit()
otError otPlatCryptoHkdfDeinit (otCryptoContext * aContext)
Uninitialize the HKDF context.
Parameters
[in] aContext Context for HKDF operation.
Return values
OT_ERROR_NONE Successfully un-initialised HKDF operation.
OT_ERROR_FAILED Failed to un-initialised HKDF operation.
OT_ERROR_INVALID_ARGS aContext was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by HkdfSha256::~HkdfSha256().
otPlatCryptoSha256Init()
otError otPlatCryptoSha256Init (otCryptoContext * aContext)
Initialise the SHA-256 operation.
Parameters
[in] aContext Context for SHA-256 operation.
Return values
OT_ERROR_NONE Successfully initialised SHA-256 operation.
OT_ERROR_FAILED Failed to initialise SHA-256 operation.
OT_ERROR_INVALID_ARGS aContext was NULL
Note
The platform driver shall point the context to the correct object such as psa_hash_operation_t or mbedtls_sha256_context.
References ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, and VerifyOrExit.
Referenced by Sha256::Sha256().
otPlatCryptoSha256Deinit()
otError otPlatCryptoSha256Deinit (otCryptoContext * aContext)
Uninitialize the SHA-256 operation.
Parameters
[in] aContext Context for SHA-256 operation.
Return values
OT_ERROR_NONE Successfully un-initialised SHA-256 operation.
OT_ERROR_FAILED Failed to un-initialised SHA-256 operation.
OT_ERROR_INVALID_ARGS aContext was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by Sha256::~Sha256().
otPlatCryptoSha256Start()
otError otPlatCryptoSha256Start (otCryptoContext * aContext)
Start SHA-256 operation.
Parameters
[in] aContext Context for SHA-256 operation.
Return values
OT_ERROR_NONE Successfully started SHA-256 operation.
OT_ERROR_FAILED Failed to start SHA-256 operation.
OT_ERROR_INVALID_ARGS aContext was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by Sha256::Start().
otPlatCryptoSha256Update()
otError otPlatCryptoSha256Update (otCryptoContext * aContext, const void * aBuf, uint16_t aBufLength)
Update SHA-256 operation with new input.
Parameters
[in] aContext Context for SHA-256 operation.
[in] aBuf A pointer to the input buffer.
[in] aBufLength The length of aBuf in bytes.
Return values
OT_ERROR_NONE Successfully updated SHA-256 with new input operation.
OT_ERROR_FAILED Failed to update SHA-256 operation.
OT_ERROR_INVALID_ARGS aContext or aBuf was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, and VerifyOrExit.
Referenced by Sha256::Update().
otPlatCryptoSha256Finish()
otError otPlatCryptoSha256Finish (otCryptoContext * aContext, uint8_t * aHash, uint16_t aHashSize)
Finish SHA-256 operation.
Parameters
[in] aContext Context for SHA-256 operation.
[in] aHash A pointer to the output buffer, where hash needs to be stored.
[in] aHashSize The length of aHash in bytes.
Return values
OT_ERROR_NONE Successfully completed the SHA-256 operation.
OT_ERROR_FAILED Failed to complete SHA-256 operation.
OT_ERROR_INVALID_ARGS aContext or aHash was NULL
References ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNone, otCryptoContext::mContext, otCryptoContext::mContextSize, OT_UNUSED_VARIABLE, otPlatEntropyGet(), SuccessOrExit, and VerifyOrExit.
Referenced by Sha256::Finish().
otPlatCryptoRandomInit()
void otPlatCryptoRandomInit (void)
Initialize cryptographically-secure pseudorandom number generator (CSPRNG).
References OT_ASSERT, OT_UNUSED_VARIABLE, sCtrDrbgContext, and sEntropyContext.
Referenced by Manager::Manager().
otPlatCryptoRandomDeinit()
void otPlatCryptoRandomDeinit (void)
Deinitialize cryptographically-secure pseudorandom number generator (CSPRNG).
References sCtrDrbgContext, and sEntropyContext.
Referenced by Manager::~Manager().
otPlatCryptoRandomGet()
otError otPlatCryptoRandomGet (uint8_t * aBuffer, uint16_t aSize)
Fills a given buffer with cryptographically secure random bytes.
Parameters
[out] aBuffer A pointer to a buffer to fill with the random bytes.
[in] aSize Size of buffer (number of bytes to fill).
Return values
OT_ERROR_NONE Successfully filled buffer with random values.
OT_ERROR_FAILED Operation failed.
References MbedTls::MapError(), and sCtrDrbgContext.
Referenced by Manager::CryptoFillBuffer().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale