OpenThread: Error
Error
API
This module includes error definitions used in OpenThread.
Typedefs
typedef enum OT_MUST_USE_RESULT otError otError
Functions
const char * otThreadErrorToString (otError aError)
Detailed Description
This module includes error definitions used in OpenThread.
Typedef Documentation
otError
enum OT_MUST_USE_RESULT otError
This enumeration represents error codes used throughout OpenThread.
Function Documentation
otThreadErrorToString()
const char* otThreadErrorToString (otError aError)
This function converts an otError enum into a string.
Parameters
[in] aError An otError enum.
Returns
A string representation of an otError.
References ot::ErrorToString().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::Enable(), HdlcInterface::HandleHdlcFrame(), RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), ot::Spinel::LogIfFail(), otSysGetThreadNetifIndex(), Interpreter::OutputResult(), Dataset::Process(), RadioSpinel< InterfaceType, ProcessContextType >::SetRadioRegion(), and Interpreter::SetUserCommands().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale