OpenThread: Factory Diagnostics - Thread Stack
Factory Diagnostics - Thread Stack
API » Add-Ons
This module includes functions that control the Thread stack's execution.
Functions
bool otDiagIsEnabled (otInstance *aInstance)
otError otDiagProcessCmd (otInstance *aInstance, uint8_t aArgsLength, char *aArgs[], char *aOutput, size_t aOutputMaxLen)
void otDiagProcessCmdLine (otInstance *aInstance, const char *aString, char *aOutput, size_t aOutputMaxLen)
Detailed Description
This module includes functions that control the Thread stack's execution.
Function Documentation
otDiagProcessCmd()
otError otDiagProcessCmd (otInstance * aInstance, uint8_t aArgsLength, char * aArgs[], char * aOutput, size_t aOutputMaxLen)
This function processes a factory diagnostics command line.
The output of this function (the content written to aOutput) MUST terminate with \0 and the \0 is within the output buffer.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aArgsLength The number of elements in aArgs.
[in] aArgs An array of arguments.
[out] aOutput The diagnostics execution result.
[in] aOutputMaxLen The output buffer size.
Return values
OT_ERROR_INVALID_ARGS The command is supported but invalid arguments provided.
OT_ERROR_NONE The command is successfully process.
OT_ERROR_NOT_IMPLEMENTED The command is not supported.
Referenced by Interpreter::LinkModeToString().
otDiagProcessCmdLine()
void otDiagProcessCmdLine (otInstance * aInstance, const char * aString, char * aOutput, size_t aOutputMaxLen)
This function processes a factory diagnostics command line.
The output of this function (the content written to aOutput) MUST terminate with \0 and the \0 is within the output buffer.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aString A NULL-terminated input string.
[out] aOutput The diagnostics execution result.
[in] aOutputMaxLen The output buffer size.
Referenced by NcpBase::CommandHandler_PROP_VALUE_update().
otDiagIsEnabled()
bool otDiagIsEnabled (otInstance * aInstance)
This function indicates whether or not the factory diagnostics mode is enabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
TRUE if factory diagnostics mode is enabled
FALSE if factory diagnostics mode is disabled.
Referenced by Interpreter::ProcessLine().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale