OpenThread: Core-coap
Core-coap
This module includes definitions for CoAP.
Data Structures
class Coap
class CoapBase
class Message
class MessageQueue
struct CoapBase::Metadata
class Option
class Resource
struct ResponsesQueue::ResponseMetadata
class ResponsesQueue
class TxParameters
Typedefs
typedef Error(* Interceptor) (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, void *aContext)
typedef otCoapRequestHandler RequestHandler
typedef otCoapResponseHandler ResponseHandler
typedef Error(* Sender) (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Enumerations
enum Code : uint8_t {
kCodeEmpty = OT_COAP_CODE_EMPTY, kCodeGet = OT_COAP_CODE_GET, kCodePost = OT_COAP_CODE_POST, kCodePut = OT_COAP_CODE_PUT,
kCodeDelete = OT_COAP_CODE_DELETE, kCodeResponseMin = OT_COAP_CODE_RESPONSE_MIN, kCodeCreated = OT_COAP_CODE_CREATED, kCodeDeleted = OT_COAP_CODE_DELETED,
kCodeValid = OT_COAP_CODE_VALID, kCodeChanged = OT_COAP_CODE_CHANGED, kCodeContent = OT_COAP_CODE_CONTENT, kCodeContinue = OT_COAP_CODE_CONTINUE,
kCodeBadRequest = OT_COAP_CODE_BAD_REQUEST, kCodeUnauthorized = OT_COAP_CODE_UNAUTHORIZED, kCodeBadOption = OT_COAP_CODE_BAD_OPTION, kCodeForbidden = OT_COAP_CODE_FORBIDDEN,
kCodeNotFound = OT_COAP_CODE_NOT_FOUND, kCodeMethodNotAllowed = OT_COAP_CODE_METHOD_NOT_ALLOWED, kCodeNotAcceptable = OT_COAP_CODE_NOT_ACCEPTABLE, kCodeRequestIncomplete = OT_COAP_CODE_REQUEST_INCOMPLETE,
kCodePreconditionFailed = OT_COAP_CODE_PRECONDITION_FAILED, kCodeRequestTooLarge = OT_COAP_CODE_REQUEST_TOO_LARGE, kCodeUnsupportedFormat = OT_COAP_CODE_UNSUPPORTED_FORMAT, kCodeInternalError = OT_COAP_CODE_INTERNAL_ERROR,
kCodeNotImplemented = OT_COAP_CODE_NOT_IMPLEMENTED, kCodeBadGateway = OT_COAP_CODE_BAD_GATEWAY, kCodeServiceUnavailable = OT_COAP_CODE_SERVICE_UNAVAILABLE, kCodeGatewayTimeout = OT_COAP_CODE_GATEWAY_TIMEOUT,
kCodeProxyNotSupported = OT_COAP_CODE_PROXY_NOT_SUPPORTED
}
enum OptionNumber : uint16_t {
kOptionIfMatch = OT_COAP_OPTION_IF_MATCH, kOptionUriHost = OT_COAP_OPTION_URI_HOST, kOptionETag = OT_COAP_OPTION_E_TAG, kOptionIfNoneMatch = OT_COAP_OPTION_IF_NONE_MATCH,
kOptionObserve = OT_COAP_OPTION_OBSERVE, kOptionUriPort = OT_COAP_OPTION_URI_PORT, kOptionLocationPath = OT_COAP_OPTION_LOCATION_PATH, kOptionUriPath = OT_COAP_OPTION_URI_PATH,
kOptionContentFormat = OT_COAP_OPTION_CONTENT_FORMAT, kOptionMaxAge = OT_COAP_OPTION_MAX_AGE, kOptionUriQuery = OT_COAP_OPTION_URI_QUERY, kOptionAccept = OT_COAP_OPTION_ACCEPT,
kOptionLocationQuery = OT_COAP_OPTION_LOCATION_QUERY, kOptionBlock2 = OT_COAP_OPTION_BLOCK2, kOptionBlock1 = OT_COAP_OPTION_BLOCK1, kOptionSize2 = OT_COAP_OPTION_SIZE2,
kOptionProxyUri = OT_COAP_OPTION_PROXY_URI, kOptionProxyScheme = OT_COAP_OPTION_PROXY_SCHEME, kOptionSize1 = OT_COAP_OPTION_SIZE1
}
enum Type : uint8_t { kTypeConfirmable = OT_COAP_TYPE_CONFIRMABLE, kTypeNonConfirmable = OT_COAP_TYPE_NON_CONFIRMABLE, kTypeAck = OT_COAP_TYPE_ACKNOWLEDGMENT, kTypeReset = OT_COAP_TYPE_RESET }
Functions
Error AbortTransaction (ResponseHandler aHandler, void *aContext)
void AddResource (Resource &aResource)
Error AppendTo (Message &aMessage) const
Error AppendTo (Message &aMessage) const
uint32_t CalculateExchangeLifetime (void) const
uint32_t CalculateInitialRetransmissionTimeout (void) const
uint32_t CalculateMaxTransmitWait (void) const
uint32_t CalculateSpan (uint8_t aMaxRetx) const
void ClearRequests (const Ip6::Address &aAddress)
void ClearRequests (const Ip6::Address *aAddress)
void ClearRequestsAndResponses (void)
Coap (Instance &aInstance)
CoapBase (Instance &aInstance, Sender aSender)
Message * CopyAndEnqueueMessage (const Message &aMessage, uint16_t aCopyLength, const Metadata &aMetadata)
void DequeueAllResponses (void)
void DequeueMessage (Message &aMessage)
void DequeueResponse (Message &aMessage)
void EnqueueResponse (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const TxParameters &aTxParameters)
void FinalizeCoapTransaction (Message &aRequest, const Metadata &aMetadata, Message *aResponse, const Ip6::MessageInfo *aMessageInfo, Error aResult)
const Message * FindMatchedResponse (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo) const
Message * FindRelatedRequest (const Message &aResponse, const Ip6::MessageInfo &aMessageInfo, Metadata &aMetadata)
static const TxParameters & From (const otCoapTxParameters *aTxParameters)
const MessageQueue & GetCachedResponses (void) const
static const TxParameters & GetDefault (void)
Error GetMatchedResponseCopy (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo, Message **aResponse)
const MessageQueue & GetRequestMessages (void) const
const MessageQueue & GetResponses (void) const
const char * GetUriPath (void) const
void HandleRequest (Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
static void HandleRetransmissionTimer (Timer &aTimer)
void HandleRetransmissionTimer (void)
static void HandleTimer (Timer &aTimer)
void HandleTimer (void)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Message * InitMessage (Message *aMessage, Type aType, const char *aUriPath)
Message * InitResponse (Message *aMessage, const Message &aResponse)
bool IsValid (void) const
Message * NewConfirmablePostMessage (const char *aUriPath)
Message * NewMessage (const Message::Settings &aSettings=Message::Settings::GetDefault())
Message * NewNonConfirmablePostMessage (const char *aUriPath)
Message * NewPriorityConfirmablePostMessage (const char *aUriPath)
Message * NewPriorityMessage (void)
Message * NewPriorityNonConfirmablePostMessage (const char *aUriPath)
Message * NewPriorityResponseMessage (const Message &aRequest)
Message * NewResponseMessage (const Message &aRequest)
void ProcessReceivedRequest (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void ProcessReceivedResponse (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void ReadFrom (const Message &aMessage)
void ReadFrom (const Message &aMessage)
void Receive (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void RemoveResource (Resource &aResource)
Resource (const char *aUriPath, RequestHandler aHandler, void *aContext)
ResponsesQueue (Instance &aInstance)
Error Send (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
static Error Send (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Error Send (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Error SendAck (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
void SendCopy (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Error SendEmptyAck (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo, Code aCode=kCodeChanged)
Error SendEmptyMessage (Type aType, const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
Error SendHeaderResponse (Message::Code aCode, const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
Error SendMessage (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const TxParameters &aTxParameters, ResponseHandler aHandler=nullptr, void *aContext=nullptr)
Error SendMessage (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, ResponseHandler aHandler=nullptr, void *aContext=nullptr)
Error SendNotFound (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
Error SendReset (Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
void SetDefaultHandler (RequestHandler aHandler, void *aContext)
void SetInterceptor (Interceptor aInterceptor, void *aContext)
Error Start (uint16_t aPort, otNetifIdentifier aNetifIdentifier=OT_NETIF_UNSPECIFIED)
Error Stop (void)
void UpdateIn (Message &aMessage) const
void UpdateQueue (void)
Variables
static constexpr uint8_t kDefaultAckRandomFactorDenominator = 2
static constexpr uint8_t kDefaultAckRandomFactorNumerator = 3
static constexpr uint32_t kDefaultAckTimeout = 2000
static constexpr uint32_t kDefaultMaxLatency = 100000
static constexpr uint8_t kDefaultMaxRetransmit = 4
static const otCoapTxParameters kDefaultTxParameters
static constexpr uint16_t kMaxCachedResponses = OPENTHREAD_CONFIG_COAP_SERVER_MAX_CACHED_RESPONSES
bool mAcknowledged: 1
bool mConfirmable: 1
void * mContext
RequestHandler mDefaultHandler
void * mDefaultHandlerContext
TimeMilli mDequeueTime
Ip6::Address mDestinationAddress
uint16_t mDestinationPort
Interceptor mInterceptor
uint16_t mMessageId
Ip6::MessageInfo mMessageInfo
bool mMulticastLoop: 1
TimeMilli mNextTimerShot
MessageQueue mPendingRequests
MessageQueue mQueue
LinkedList< Resource > mResources
void * mResponseContext
ResponseHandler mResponseHandler
ResponsesQueue mResponsesQueue
uint8_t mRetransmissionsRemaining
uint32_t mRetransmissionTimeout
TimerMilliContext mRetransmissionTimer
const Sender mSender
Ip6::Udp::Socket mSocket
Ip6::Address mSourceAddress
TimerMilliContext mTimer
Friends
class CoapBase
class CoapBase
class ResponsesQueue
class ResponsesQueue
Detailed Description
This module includes definitions for CoAP.
Typedef Documentation
ResponseHandler
typedef otCoapResponseHandler ResponseHandler
This type represents a function pointer which is called when a CoAP response is received or on the request timeout.
Please see otCoapResponseHandler for details.
RequestHandler
typedef otCoapRequestHandler RequestHandler
This type represents a function pointer which is called when a CoAP request associated with a given URI path is received.
Please see otCoapRequestHandler for details.
Interceptor
typedef Error(* Interceptor) (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, void *aContext)
This function pointer is called before CoAP server processing a CoAP message.
Parameters
[in] aMessage A reference to the message. @
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Server should continue processing this message, other return values indicates the server should stop processing this message.
kErrorNotTmf The message is not a TMF message.
Sender
typedef Error(* Sender) (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) protected
This function pointer is called to send a CoAP message.
Parameters
[in] aCoapBase A reference to the CoAP agent.
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
Return values
kErrorNone Successfully sent CoAP message.
kErrorNoBufs Failed to allocate retransmission data.
Enumeration Type Documentation
Type
enum Type : uint8_t
CoAP Type values.
Enumerator
kTypeConfirmable
Confirmable type.
kTypeNonConfirmable
Non-confirmable type.
kTypeAck
Acknowledgment type.
kTypeReset
Reset type.
Code
enum Code : uint8_t
CoAP Code values.
Enumerator
kCodeEmpty
Empty message code.
kCodeGet
Get.
kCodePost
Post.
kCodePut
Put.
kCodeDelete
Delete.
kCodeResponseMin
2.00
kCodeCreated
Created.
kCodeDeleted
Deleted.
kCodeValid
Valid.
kCodeChanged
Changed.
kCodeContent
Content.
kCodeContinue
RFC7959 Continue.
kCodeBadRequest
Bad Request.
kCodeUnauthorized
Unauthorized.
kCodeBadOption
Bad Option.
kCodeForbidden
Forbidden.
kCodeNotFound
Not Found.
kCodeMethodNotAllowed
Method Not Allowed.
kCodeNotAcceptable
Not Acceptable.
kCodeRequestIncomplete
RFC7959 Request Entity Incomplete.
kCodePreconditionFailed
Precondition Failed.
kCodeRequestTooLarge
Request Entity Too Large.
kCodeUnsupportedFormat
Unsupported Content-Format.
kCodeInternalError
Internal Server Error.
kCodeNotImplemented
Not Implemented.
kCodeBadGateway
Bad Gateway.
kCodeServiceUnavailable
Service Unavailable.
kCodeGatewayTimeout
Gateway Timeout.
kCodeProxyNotSupported
Proxying Not Supported.
OptionNumber
enum OptionNumber : uint16_t
CoAP Option Numbers.
Enumerator
kOptionIfMatch
If-Match.
kOptionUriHost
Uri-Host.
kOptionETag
ETag.
kOptionIfNoneMatch
If-None-Match.
kOptionObserve
Observe [RFC7641].
kOptionUriPort
Uri-Port.
kOptionLocationPath
Location-Path.
kOptionUriPath
Uri-Path.
kOptionContentFormat
Content-Format.
kOptionMaxAge
Max-Age.
kOptionUriQuery
Uri-Query.
kOptionAccept
Accept.
kOptionLocationQuery
Location-Query.
kOptionBlock2
Block2 (RFC7959)
kOptionBlock1
Block1 (RFC7959)
kOptionSize2
Size2 (RFC7959)
kOptionProxyUri
Proxy-Uri.
kOptionProxyScheme
Proxy-Scheme.
kOptionSize1
Size1.
Function Documentation
From()
static const TxParameters& From (const otCoapTxParameters * aTxParameters) inline static
This static method coverts a pointer to otCoapTxParameters to Coap::TxParamters
If the pointer is nullptr, the default parameters are used instead.
Parameters
[in] aTxParameters A pointer to tx parameter.
Returns
A reference to corresponding TxParamters if aTxParameters is not nullptr, otherwise the default tx parameters.
References TxParameters::GetDefault(), and TxParameters::IsValid().
IsValid()
bool IsValid (void) const
This method validates whether the CoAP transmission parameters are valid.
Returns
Whether the parameters are valid.
References ot::Coap::Multiply(), OT_COAP_MAX_RETRANSMIT, and OT_COAP_MIN_ACK_TIMEOUT.
Referenced by TxParameters::From().
GetDefault()
static const TxParameters& GetDefault (void) inline static
This static method returns default CoAP tx parameters.
Returns
The default tx parameters.
References TxParameters::kDefaultTxParameters.
Referenced by CoapBase::DequeueMessage(), TxParameters::From(), and CoapBase::SendMessage().
CalculateInitialRetransmissionTimeout()
uint32_t CalculateInitialRetransmissionTimeout (void) const private
References ot::Random::NonCrypto::GetUint32InRange().
Referenced by CoapBase::SendMessage().
CalculateExchangeLifetime()
uint32_t CalculateExchangeLifetime (void) const private
Referenced by ResponsesQueue::EnqueueResponse().
CalculateMaxTransmitWait()
uint32_t CalculateMaxTransmitWait (void) const private
Referenced by CoapBase::SendMessage().
CalculateSpan()
uint32_t CalculateSpan (uint8_t aMaxRetx) const private
References TxParameters::kDefaultTxParameters.
Resource()
Resource (const char * aUriPath, RequestHandler aHandler, void * aContext) inline
This constructor initializes the resource.
Parameters
[in] aUriPath A pointer to a null-terminated string for the URI path.
[in] aHandler A function pointer that is called when receiving a CoAP message for aUriPath.
[in] aContext A pointer to arbitrary context information.
GetUriPath()
const char* GetUriPath (void) const inline
This method returns a pointer to the URI path.
Returns
A pointer to the URI path.
HandleRequest()
void HandleRequest (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) const inline protected
References otCoapBlockwiseResource::mContext.
ResponsesQueue()
ResponsesQueue (Instance & aInstance) explicit
Default class constructor.
Parameters
[in] aInstance A reference to the OpenThread instance.
EnqueueResponse()
void EnqueueResponse (Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const TxParameters & aTxParameters)
This method adds a given response to the cache.
If matching response (the same Message ID, source endpoint address and port) exists in the cache given response is not added.
The CoAP response is copied before it is added to the cache.
Parameters
[in] aMessage The CoAP response to add to the cache.
[in] aMessageInfo The message info corresponding to aMessage.
[in] aTxParameters Transmission parameters.
References ResponsesQueue::ResponseMetadata::AppendTo(), TxParameters::CalculateExchangeLifetime(), Message::Clone(), MessageQueue::Enqueue(), ResponsesQueue::FindMatchedResponse(), TimerMilli::FireAtIfEarlier(), Message::Free(), TimerMilli::GetNow(), ot::kErrorNone, ResponsesQueue::ResponseMetadata::mDequeueTime, ResponsesQueue::ResponseMetadata::mMessageInfo, ResponsesQueue::mQueue, ResponsesQueue::mTimer, ResponsesQueue::UpdateQueue(), and VerifyOrExit.
Referenced by CoapBase::SendMessage().
DequeueAllResponses()
void DequeueAllResponses (void)
This method removes all responses from the cache.
References MessageQueue::DequeueAndFreeAll(), and ResponsesQueue::mQueue.
Referenced by CoapBase::ClearRequestsAndResponses().
GetMatchedResponseCopy()
Error GetMatchedResponseCopy (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo, Message ** aResponse)
This method gets a copy of CoAP response from the cache that matches a given Message ID and source endpoint.
Parameters
[in] aRequest The CoAP message containing Message ID.
[in] aMessageInfo The message info containing source endpoint address and port.
[out] aResponse A pointer to return a copy of a cached CoAP response matching given arguments.
Return values
kErrorNone Matching response found and successfully created a copy.
kErrorNoBufs Matching response found but there is not sufficient buffer to create a copy.
kErrorNotFound Matching response not found.
References Message::Clone(), ResponsesQueue::FindMatchedResponse(), Message::GetLength(), ot::kErrorNoBufs, ot::kErrorNone, ot::kErrorNotFound, and VerifyOrExit.
Referenced by CoapBase::ProcessReceivedRequest().
GetResponses()
const MessageQueue& GetResponses (void) const inline
This method gets a reference to the cached CoAP responses queue.
Returns
A reference to the cached CoAP responses queue.
AppendTo() [1/2]
Error AppendTo (Message & aMessage) const inline
References Message::Append().
Referenced by ResponsesQueue::EnqueueResponse().
ReadFrom() [1/2]
void ReadFrom (const Message & aMessage)
References Message::GetLength(), IgnoreError(), OT_ASSERT, and Message::Read().
Referenced by ResponsesQueue::FindMatchedResponse(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
FindMatchedResponse()
const Message * FindMatchedResponse (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo) const private
References Message::GetMessageId(), MessageInfo::GetPeerAddr(), MessageInfo::GetPeerPort(), ResponsesQueue::ResponseMetadata::mMessageInfo, ResponsesQueue::mQueue, and ResponsesQueue::ResponseMetadata::ReadFrom().
Referenced by ResponsesQueue::EnqueueResponse(), and ResponsesQueue::GetMatchedResponseCopy().
DequeueResponse()
void DequeueResponse (Message & aMessage) private
References MessageQueue::DequeueAndFree(), and ResponsesQueue::mQueue.
Referenced by ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
UpdateQueue()
void UpdateQueue (void) private
References ResponsesQueue::DequeueResponse(), ResponsesQueue::kMaxCachedResponses, ResponsesQueue::ResponseMetadata::mDequeueTime, ResponsesQueue::mQueue, and ResponsesQueue::ResponseMetadata::ReadFrom().
Referenced by ResponsesQueue::EnqueueResponse().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References ResponsesQueue::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References ResponsesQueue::DequeueResponse(), TimerMilli::FireAt(), Time::GetDistantFuture(), TimerMilli::GetNow(), ResponsesQueue::ResponseMetadata::mDequeueTime, ResponsesQueue::mQueue, ResponsesQueue::mTimer, and ResponsesQueue::ResponseMetadata::ReadFrom().
Referenced by ResponsesQueue::HandleTimer().
ClearRequestsAndResponses()
void ClearRequestsAndResponses (void)
This method clears requests and responses used by this CoAP agent.
References CoapBase::ClearRequests(), ResponsesQueue::DequeueAllResponses(), and CoapBase::mResponsesQueue.
Referenced by Coap::Stop().
ClearRequests() [1/2]
void ClearRequests (const Ip6::Address & aAddress)
This method clears requests with specified source address used by this CoAP agent.
Parameters
[in] aAddress A reference to the specified address.
Referenced by CoapBase::ClearRequestsAndResponses().
AddResource()
void AddResource (Resource & aResource)
This method adds a resource to the CoAP server.
Parameters
[in] aResource A reference to the resource.
References IgnoreError(), and CoapBase::mResources.
RemoveResource()
void RemoveResource (Resource & aResource)
This method removes a resource from the CoAP server.
Parameters
[in] aResource A reference to the resource.
References IgnoreError(), CoapBase::mResources, and LinkedListEntry< Type >::SetNext().
SetDefaultHandler()
void SetDefaultHandler (RequestHandler aHandler, void * aContext)
References CoapBase::mDefaultHandler, and CoapBase::mDefaultHandlerContext.
NewMessage()
Message * NewMessage (const Message::Settings & aSettings = Message::Settings::GetDefault())
This method allocates a new message with a CoAP header.
Parameters
[in] aSettings The message settings.
Returns
A pointer to the message or nullptr if failed to allocate message.
References ot::AsCoapMessagePtr(), Message::SetOffset(), and VerifyOrExit.
Referenced by CoapBase::DequeueMessage(), CoapBase::NewConfirmablePostMessage(), CoapBase::NewNonConfirmablePostMessage(), CoapBase::NewResponseMessage(), CoapBase::SendEmptyMessage(), and CoapBase::SendHeaderResponse().
NewPriorityMessage()
Message* NewPriorityMessage (void) inline
This method allocates a new message with a CoAP header that has Network Control priority level.
Returns
A pointer to the message or nullptr if failed to allocate message.
References ot::Coap::kCodeChanged, ot::Coap::kCodeRequestIncomplete, Message::kPriorityNet, and Message::kWithLinkSecurity.
Referenced by CoapBase::NewPriorityConfirmablePostMessage(), CoapBase::NewPriorityNonConfirmablePostMessage(), and CoapBase::NewPriorityResponseMessage().
NewPriorityConfirmablePostMessage()
Message * NewPriorityConfirmablePostMessage (const char * aUriPath)
This method allocates and initializes a new CoAP Confirmable Post message with Network Control priority level.
The CoAP header is initialized as kTypeConfirmable and kCodePost with a given URI path and a randomly generated token (of default length). This method also sets the payload marker (SetPayloadMarker() on message. Even if message has no payload, calling SetPayloadMarker() is harmless, since SendMessage() will check and remove the payload marker when there is no payload.
Parameters
[in] aUriPath The URI path string.
Returns
A pointer to the message or nullptr if failed to allocate message.
References CoapBase::InitMessage(), ot::Coap::kTypeConfirmable, and CoapBase::NewPriorityMessage().
NewConfirmablePostMessage()
Message * NewConfirmablePostMessage (const char * aUriPath)
This method allocates and initializes a new CoAP Confirmable Post message with normal priority level.
The CoAP header is initialized as kTypeConfirmable and kCodePost with a given URI path and a randomly generated token (of default length). This method also sets the payload marker (calling SetPayloadMarker()). Even if message has no payload, calling SetPayloadMarker() is harmless, since SendMessage() will check and remove the payload marker when there is no payload.
Parameters
[in] aUriPath The URI path string.
Returns
A pointer to the message or nullptr if failed to allocate message.
References CoapBase::InitMessage(), ot::Coap::kTypeConfirmable, and CoapBase::NewMessage().
NewPriorityNonConfirmablePostMessage()
Message * NewPriorityNonConfirmablePostMessage (const char * aUriPath)
This method allocates and initializes a new CoAP Non-confirmable Post message with Network Control priority level.
The CoAP header is initialized as kTypeNonConfirmable and kCodePost with a given URI path and a randomly generated token (of default length). This method also sets the payload marker (calling SetPayloadMarker()). Even if message has no payload, calling SetPayloadMarker() is harmless, since SendMessage() will check and remove the payload marker when there is no payload.
Parameters
[in] aUriPath The URI path string.
Returns
A pointer to the message or nullptr if failed to allocate message.
References CoapBase::InitMessage(), ot::Coap::kTypeNonConfirmable, and CoapBase::NewPriorityMessage().
NewNonConfirmablePostMessage()
Message * NewNonConfirmablePostMessage (const char * aUriPath)
This method allocates and initializes a new CoAP Non-confirmable Post message with normal priority level.
The CoAP header is initialized as kTypeNonConfirmable and kCodePost with a given URI path and a randomly generated token (of default length). This method also sets the payload marker (calling SetPayloadMarker()). Even if message has no payload, calling SetPayloadMarker() is harmless, since SendMessage() will check and remove the payload marker when there is no payload.
Parameters
[in] aUriPath The URI path string.
Returns
A pointer to the message or nullptr if failed to allocate message.
References CoapBase::InitMessage(), ot::Coap::kTypeNonConfirmable, and CoapBase::NewMessage().
NewPriorityResponseMessage()
Message * NewPriorityResponseMessage (const Message & aRequest)
This method allocates and initializes a new CoAP response message with Network Control priority level for a given request message.
The CoAP header is initialized as kTypeAck with kCodeChanged. The token and message ID is copied from aRequest. This method also sets the payload marker (calling SetPayloadMarker()). Even if message has no payload, calling SetPayloadMarker() is harmless, since SendMessage() will check and remove the payload marker when there is no payload.
Returns
A pointer to the message or nullptr if failed to allocate message.
References CoapBase::InitResponse(), and CoapBase::NewPriorityMessage().
NewResponseMessage()
Message * NewResponseMessage (const Message & aRequest)
This method allocates and initializes a new CoAP response message with regular priority level for a given request message.
The CoAP header is initialized as kTypeAck with kCodeChanged. The token and message ID is copied from aRequest. This method also sets the payload marker (calling SetPayloadMarker()). Even if message has no payload, calling SetPayloadMarker() is harmless, since SendMessage() will check and remove the payload marker when there is no payload.
Returns
A pointer to the message or nullptr if failed to allocate message.
References CoapBase::InitResponse(), and CoapBase::NewMessage().
SendMessage() [1/2]
Error SendMessage (Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const TxParameters & aTxParameters, ResponseHandler aHandler = nullptr, void * aContext = nullptr)
This method sends a CoAP message with custom transmission parameters.
If a response for a request is expected, respective function and context information should be provided. If no response is expected, these arguments should be nullptr pointers. If Message Id was not set in the header (equal to 0), this function will assign unique Message Id to the message.
Parameters
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aTxParameters A reference to transmission parameters for this message.
[in] aHandler A function pointer that shall be called on response reception or time-out.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Successfully sent CoAP message.
kErrorNoBufs Insufficient buffers available to send the CoAP message.
References Message::AppendBytes(), TxParameters::CalculateInitialRetransmissionTimeout(), TxParameters::CalculateMaxTransmitWait(), CoapBase::CopyAndEnqueueMessage(), CoapBase::DequeueMessage(), ResponsesQueue::EnqueueResponse(), CoapBase::FinalizeCoapTransaction(), CoapBase::FindRelatedRequest(), Message::Finish(), Message::GetCode(), MessageInfo::GetHopLimit(), Message::GetLength(), MessageInfo::GetMulticastLoop(), TimerMilli::GetNow(), Message::GetOptionStart(), MessageInfo::GetPeerAddr(), MessageInfo::GetPeerPort(), MessageInfo::GetSockAddr(), Message::GetType(), Option::Iterator::Init(), Message::IsConfirmable(), Option::Iterator::IsDone(), Message::IsGetRequest(), MessageInfo::IsHostInterface(), Message::IsNonConfirmable(), ot::Coap::kCodeEmpty, ot::kErrorNoBufs, ot::kErrorNone, ot::Coap::kOptionBlock1, ot::Coap::kOptionBlock2, ot::Coap::kOptionObserve, ot::Coap::kTypeAck, ot::Coap::kTypeConfirmable, ot::Coap::kTypeReset, CoapBase::Metadata::mAcknowledged, CoapBase::Metadata::mConfirmable, CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mDestinationPort, otCoapTxParameters::mMaxRetransmit, CoapBase::mMessageId, CoapBase::Metadata::mMulticastLoop, CoapBase::Metadata::mNextTimerShot, CoapBase::Metadata::mResponseContext, CoapBase::Metadata::mResponseHandler, CoapBase::mResponsesQueue, CoapBase::Metadata::mRetransmissionsRemaining, CoapBase::Metadata::mRetransmissionTimeout, CoapBase::Metadata::mSourceAddress, OT_ASSERT, otCoapBlockSizeFromExponent(), Option::Iterator::ReadOptionValue(), CoapBase::Send(), Message::SetMessageId(), Message::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::DequeueMessage(), CoapBase::Send(), CoapBase::SendHeaderResponse(), and CoapBase::SendMessage().
SendMessage() [2/2]
Error SendMessage (Message & aMessage, const Ip6::MessageInfo & aMessageInfo, ResponseHandler aHandler = nullptr, void * aContext = nullptr)
This method sends a CoAP message with default transmission parameters.
If a response for a request is expected, respective function and context information should be provided. If no response is expected, these arguments should be nullptr pointers. If Message Id was not set in the header (equal to 0), this function will assign unique Message Id to the message.
Parameters
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aHandler A function pointer that shall be called on response reception or time-out.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Successfully sent CoAP message.
kErrorNoBufs Insufficient buffers available to send the CoAP response.
References TxParameters::GetDefault(), and CoapBase::SendMessage().
SendReset()
Error SendReset (Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends a CoAP reset message.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
kErrorNone Successfully enqueued the CoAP response message.
kErrorNoBufs Insufficient buffers available to send the CoAP response.
kErrorInvalidArgs The aRequest is not of confirmable type.
References ot::Coap::kTypeReset, and CoapBase::SendEmptyMessage().
Referenced by CoapBase::ProcessReceivedResponse(), and CoapBase::Receive().
SendHeaderResponse()
Error SendHeaderResponse (Message::Code aCode, const Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends header-only CoAP response message.
Parameters
[in] aCode The CoAP code of this response.
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
kErrorNone Successfully enqueued the CoAP response message.
kErrorNoBufs Insufficient buffers available to send the CoAP response.
kErrorInvalidArgs The aRequest header is not of confirmable type.
References ExitNow, FreeMessageOnError, Message::GetMessageId(), Message::GetType(), Message::Init(), Message::IsRequest(), ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, ot::Coap::kTypeAck, ot::Coap::kTypeConfirmable, ot::Coap::kTypeNonConfirmable, CoapBase::NewMessage(), OT_UNREACHABLE_CODE, CoapBase::SendMessage(), Message::SetMessageId(), Message::SetTokenFromMessage(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::ProcessReceivedRequest(), CoapBase::SendEmptyAck(), and CoapBase::SendNotFound().
SendAck()
Error SendAck (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends a CoAP ACK empty message which is used in Separate Response for confirmable requests.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
kErrorNone Successfully enqueued the CoAP response message.
kErrorNoBufs Insufficient buffers available to send the CoAP response.
kErrorInvalidArgs The aRequest header is not of confirmable type.
References ot::Coap::kTypeAck, and CoapBase::SendEmptyMessage().
Referenced by CoapBase::ProcessReceivedResponse().
SendEmptyAck()
Error SendEmptyAck (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo, Code aCode = kCodeChanged)
This method sends a CoAP ACK message on which a dummy CoAP response is piggybacked.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
[in] aCode The CoAP code of the dummy CoAP response.
Return values
kErrorNone Successfully enqueued the CoAP response message.
kErrorNoBufs Insufficient buffers available to send the CoAP response.
kErrorInvalidArgs The aRequest header is not of confirmable type.
References Message::IsConfirmable(), ot::kErrorInvalidArgs, and CoapBase::SendHeaderResponse().
SendNotFound()
Error SendNotFound (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends a header-only CoAP message to indicate no resource matched for the request.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
kErrorNone Successfully enqueued the CoAP response message.
kErrorNoBufs Insufficient buffers available to send the CoAP response.
References ot::Coap::kCodeNotFound, and CoapBase::SendHeaderResponse().
Referenced by CoapBase::ProcessReceivedRequest().
AbortTransaction()
Error AbortTransaction (ResponseHandler aHandler, void * aContext)
This method aborts CoAP transactions associated with given handler and context.
The associated response handler will be called with kErrorAbort.
Parameters
[in] aHandler A function pointer that should be called when the transaction ends.
[in] aContext A pointer to arbitrary context information.
Return values
kErrorNone Successfully aborted CoAP transactions.
kErrorNotFound CoAP transaction associated with given handler was not found.
References CoapBase::FinalizeCoapTransaction(), ot::kErrorAbort, ot::kErrorNone, ot::kErrorNotFound, CoapBase::mPendingRequests, CoapBase::Metadata::mResponseContext, CoapBase::Metadata::mResponseHandler, and CoapBase::Metadata::ReadFrom().
SetInterceptor()
void SetInterceptor (Interceptor aInterceptor, void * aContext)
This method sets interceptor to be called before processing a CoAP packet.
Parameters
[in] aInterceptor A pointer to the interceptor.
[in] aContext A pointer to arbitrary context information.
References CoapBase::mContext, and CoapBase::mInterceptor.
GetRequestMessages()
const MessageQueue& GetRequestMessages (void) const inline
This method returns a reference to the request message list.
Returns
A reference to the request message list.
GetCachedResponses()
const MessageQueue& GetCachedResponses (void) const inline
This method returns a reference to the cached response list.
Returns
A reference to the cached response list.
CoapBase()
CoapBase (Instance & aInstance, Sender aSender) protected
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aSender A function pointer to send CoAP message, which SHOULD be a static member method of a descendant of this class.
Receive()
void Receive (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) protected
This method receives a CoAP message.
Parameters
[in] aMessage A reference to the received message.
[in] aMessageInfo A reference to the message info associated with aMessage.
References ot::AsCoapMessage(), MessageInfo::GetSockAddr(), IgnoreError(), Message::IsConfirmable(), Address::IsMulticast(), Message::IsRequest(), ot::kErrorNone, LogDebg, Message::ParseHeader(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendReset().
Referenced by Coap::HandleUdpReceive().
AppendTo() [2/2]
Error AppendTo (Message & aMessage) const inline
References Message::Append().
Referenced by CoapBase::CopyAndEnqueueMessage().
ReadFrom() [2/2]
void ReadFrom (const Message & aMessage)
References Message::GetLength(), IgnoreError(), OT_ASSERT, and Message::Read().
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), CoapBase::FindRelatedRequest(), and CoapBase::HandleRetransmissionTimer().
UpdateIn()
void UpdateIn (Message & aMessage) const
References Message::GetLength(), and Message::Write().
Referenced by CoapBase::HandleRetransmissionTimer(), and CoapBase::ProcessReceivedResponse().
InitMessage()
Message * InitMessage (Message * aMessage, Type aType, const char * aUriPath) private
References FreeAndNullMessageOnError, Message::Init(), ot::Coap::kCodePost, ot::kErrorNone, Message::SetPayloadMarker(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::NewConfirmablePostMessage(), CoapBase::NewNonConfirmablePostMessage(), CoapBase::NewPriorityConfirmablePostMessage(), and CoapBase::NewPriorityNonConfirmablePostMessage().
InitResponse()
Message * InitResponse (Message * aMessage, const Message & aResponse) private
References FreeAndNullMessageOnError, ot::kErrorNone, Message::SetDefaultResponseHeader(), Message::SetPayloadMarker(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::NewPriorityResponseMessage(), and CoapBase::NewResponseMessage().
HandleRetransmissionTimer() [1/2]
void HandleRetransmissionTimer (Timer & aTimer) static private
References CoapBase::HandleRetransmissionTimer().
HandleRetransmissionTimer() [2/2]
void HandleRetransmissionTimer (void) private
References CoapBase::FinalizeCoapTransaction(), TimerMilli::FireAt(), Time::GetDistantFuture(), TimerMilli::GetNow(), ot::kErrorResponseTimeout, CoapBase::Metadata::mAcknowledged, CoapBase::Metadata::mConfirmable, CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mDestinationPort, CoapBase::Metadata::mMulticastLoop, CoapBase::Metadata::mNextTimerShot, CoapBase::mPendingRequests, CoapBase::Metadata::mRetransmissionsRemaining, CoapBase::Metadata::mRetransmissionTimeout, CoapBase::mRetransmissionTimer, CoapBase::Metadata::mSourceAddress, CoapBase::Metadata::ReadFrom(), CoapBase::SendCopy(), MessageInfo::SetHopLimit(), MessageInfo::SetIsHostInterface(), MessageInfo::SetMulticastLoop(), MessageInfo::SetPeerAddr(), MessageInfo::SetPeerPort(), MessageInfo::SetSockAddr(), and CoapBase::Metadata::UpdateIn().
Referenced by CoapBase::HandleRetransmissionTimer().
ClearRequests() [2/2]
void ClearRequests (const Ip6::Address * aAddress) private
References CoapBase::FinalizeCoapTransaction(), IgnoreError(), ot::kErrorAbort, CoapBase::mPendingRequests, CoapBase::Metadata::mSourceAddress, and CoapBase::Metadata::ReadFrom().
CopyAndEnqueueMessage()
Message * CopyAndEnqueueMessage (const Message & aMessage, uint16_t aCopyLength, const Metadata & aMetadata) private
References CoapBase::Metadata::AppendTo(), Message::Clone(), MessageQueue::Enqueue(), TimerMilli::FireAtIfEarlier(), FreeAndNullMessageOnError, ot::kErrorNoBufs, ot::kErrorNone, CoapBase::Metadata::mNextTimerShot, CoapBase::mPendingRequests, CoapBase::mRetransmissionTimer, SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::SendMessage().
DequeueMessage()
void DequeueMessage (Message & aMessage) private
References Option::Iterator::Advance(), Message::AppendBlockOption(), Message::AppendBytes(), Message::AppendOption(), ot::AsConst(), Message::Clone(), MessageQueue::Dequeue(), ExitNow, CoapBase::FinalizeCoapTransaction(), Message::Free(), FreeMessageOnError, Message::GetCode(), TxParameters::GetDefault(), MessageQueue::GetHead(), Message::GetLength(), Option::GetLength(), Message::GetMessageId(), Option::GetNumber(), Message::GetOffset(), Option::Iterator::GetOption(), Message::GetTokenLength(), IgnoreReturnValue, Message::Init(), Option::Iterator::Init(), Option::Iterator::IsDone(), Timer::IsRunning(), Message::kBlockType1, Message::kBlockType2, ot::Coap::kCodeContent, ot::Coap::kCodeContinue, ot::kErrorBusy, ot::kErrorFailed, ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, ot::Coap::kOptionBlock1, ot::Coap::kOptionBlock2, ot::Coap::kTypeAck, ot::Coap::kTypeConfirmable, LogInfo, CoapBase::mPendingRequests, CoapBase::Metadata::mResponseContext, CoapBase::Metadata::mResponseHandler, CoapBase::mRetransmissionTimer, CoapBase::NewMessage(), OT_COAP_OPTION_BLOCK_SZX_1024, OT_COAP_OPTION_BLOCK_SZX_128, OT_COAP_OPTION_BLOCK_SZX_16, OT_COAP_OPTION_BLOCK_SZX_256, OT_COAP_OPTION_BLOCK_SZX_32, OT_COAP_OPTION_BLOCK_SZX_512, OT_COAP_OPTION_BLOCK_SZX_64, otCoapBlockSizeFromExponent(), Message::ReadBytes(), Option::Iterator::ReadOptionValue(), CoapBase::SendMessage(), Message::SetMessageId(), Message::SetPayloadMarker(), Message::SetToken(), TimerMilli::Stop(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::FinalizeCoapTransaction(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
FindRelatedRequest()
Message * FindRelatedRequest (const Message & aResponse, const Ip6::MessageInfo & aMessageInfo, Metadata & aMetadata) private
References ExitNow, Address::GetIid(), Message::GetMessageId(), MessageInfo::GetPeerAddr(), MessageInfo::GetPeerPort(), Message::GetType(), InterfaceIdentifier::IsAnycastLocator(), Address::IsMulticast(), Message::IsTokenEqual(), ot::Coap::kTypeAck, ot::Coap::kTypeConfirmable, ot::Coap::kTypeNonConfirmable, ot::Coap::kTypeReset, CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mDestinationPort, CoapBase::mPendingRequests, and CoapBase::Metadata::ReadFrom().
Referenced by CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
FinalizeCoapTransaction()
void FinalizeCoapTransaction (Message & aRequest, const Metadata & aMetadata, Message * aResponse, const Ip6::MessageInfo * aMessageInfo, Error aResult) private
References CoapBase::DequeueMessage(), CoapBase::Metadata::mResponseContext, and CoapBase::Metadata::mResponseHandler.
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), CoapBase::DequeueMessage(), CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
ProcessReceivedRequest()
void ProcessReceivedRequest (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References Option::Iterator::Advance(), ot::ErrorToString(), ExitNow, Message::Finish(), FreeMessage, ot::GetArrayEnd(), Option::GetLength(), ResponsesQueue::GetMatchedResponseCopy(), Option::GetNumber(), Option::Iterator::GetOption(), MessageInfo::GetSockAddr(), IgnoreError(), IgnoreReturnValue, Option::Iterator::Init(), Option::Iterator::IsDone(), Address::IsMulticast(), ot::Coap::kCodeInternalError, ot::Coap::kCodeRequestIncomplete, ot::Coap::kCodeRequestTooLarge, ot::kErrorBusy, ot::kErrorDrop, ot::kErrorNoBufs, ot::kErrorNoFrameReceived, ot::kErrorNone, ot::kErrorNotFound, ot::kErrorParse, Message::kMaxReceivedUriPath, ot::Coap::kOptionBlock1, ot::Coap::kOptionBlock2, ot::Coap::kOptionSize1, ot::Coap::kOptionUriPath, LogInfo, CoapBase::mContext, CoapBase::mDefaultHandler, CoapBase::mDefaultHandlerContext, CoapBase::mInterceptor, CoapBase::mResources, CoapBase::mResponsesQueue, OT_FALL_THROUGH, Option::Iterator::ReadOptionValue(), Message::ReadUriPathOptions(), CoapBase::Send(), CoapBase::SendHeaderResponse(), CoapBase::SendNotFound(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::Receive().
ProcessReceivedResponse()
void ProcessReceivedResponse (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References Option::Iterator::Advance(), CoapBase::DequeueMessage(), CoapBase::FinalizeCoapTransaction(), CoapBase::FindRelatedRequest(), Message::GetCode(), Option::GetNumber(), Option::Iterator::GetOption(), Message::GetType(), IgnoreError(), Option::Iterator::Init(), Message::IsConfirmable(), Option::Iterator::IsDone(), Message::IsEmpty(), Address::IsMulticast(), Message::IsNonConfirmable(), Message::IsRequest(), Message::IsResponse(), Message::IsTokenEqual(), ot::Coap::kCodeBadRequest, ot::Coap::kCodeContinue, ot::kErrorAbort, ot::kErrorNone, ot::Coap::kOptionBlock1, ot::Coap::kOptionBlock2, ot::Coap::kOptionObserve, ot::Coap::kOptionSize2, ot::Coap::kTypeAck, ot::Coap::kTypeConfirmable, ot::Coap::kTypeNonConfirmable, ot::Coap::kTypeReset, CoapBase::Metadata::mAcknowledged, CoapBase::Metadata::mConfirmable, CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mResponseContext, CoapBase::Metadata::mResponseHandler, OT_FALL_THROUGH, CoapBase::SendAck(), CoapBase::SendReset(), SuccessOrExit, CoapBase::Metadata::UpdateIn(), and VerifyOrExit.
Referenced by CoapBase::Receive().
SendCopy()
void SendCopy (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References Message::Clone(), ot::ErrorToString(), FreeMessage, Message::GetLength(), ot::kErrorNoBufs, ot::kErrorNone, LogWarn, CoapBase::Send(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::HandleRetransmissionTimer().
SendEmptyMessage()
Error SendEmptyMessage (Type aType, const Message & aRequest, const Ip6::MessageInfo & aMessageInfo) private
References Message::Finish(), FreeMessageOnError, Message::GetMessageId(), Message::Init(), Message::IsConfirmable(), ot::Coap::kCodeEmpty, ot::kErrorInvalidArgs, ot::kErrorNoBufs, ot::kErrorNone, CoapBase::NewMessage(), CoapBase::Send(), Message::SetMessageId(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::SendAck(), and CoapBase::SendReset().
Send() [1/3]
Error Send (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ot::AsCoapMessage(), ot::kErrorNone, CoapBase::mSender, and CoapBase::SendMessage().
Referenced by CoapBase::ProcessReceivedRequest(), CoapBase::SendCopy(), CoapBase::SendEmptyMessage(), and CoapBase::SendMessage().
Coap()
Coap (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Start()
Error Start (uint16_t aPort, otNetifIdentifier aNetifIdentifier = OT_NETIF_UNSPECIFIED)
This method starts the CoAP service.
Parameters
[in] aPort The local UDP port to bind to.
[in] aNetifIdentifier The network interface identifier to bind.
Return values
kErrorNone Successfully started the CoAP service.
kErrorFailed Failed to start CoAP agent.
References Udp::Socket::Bind(), Udp::Socket::Close(), Coap::HandleUdpReceive(), IgnoreError(), Udp::SocketHandle::IsBound(), ot::kErrorNone, Coap::mSocket, Udp::Socket::Open(), SuccessOrExit, and VerifyOrExit.
Stop()
Error Stop (void)
This method stops the CoAP service.
Return values
kErrorNone Successfully stopped the CoAP service.
kErrorFailed Failed to stop CoAP agent.
References CoapBase::ClearRequestsAndResponses(), Udp::Socket::Close(), Udp::SocketHandle::IsBound(), ot::kErrorNone, Coap::mSocket, SuccessOrExit, and VerifyOrExit.
Send() [2/3]
Error Send (CoapBase & aCoapBase, ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) static private
HandleUdpReceive()
void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References ot::AsCoapMessage(), ot::AsCoreType(), and CoapBase::Receive().
Referenced by Coap::Start().
Send() [3/3]
Error Send (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References Udp::SocketHandle::IsBound(), ot::kErrorInvalidState, Coap::mSocket, and Udp::Socket::SendTo().
Variable Documentation
kDefaultAckTimeout
constexpr uint32_t kDefaultAckTimeout = 2000 static private
kDefaultAckRandomFactorNumerator
constexpr uint8_t kDefaultAckRandomFactorNumerator = 3 static private
kDefaultAckRandomFactorDenominator
constexpr uint8_t kDefaultAckRandomFactorDenominator = 2 static private
kDefaultMaxRetransmit
constexpr uint8_t kDefaultMaxRetransmit = 4 static private
kDefaultMaxLatency
constexpr uint32_t kDefaultMaxLatency = 100000 static private
kDefaultTxParameters
const otCoapTxParameters kDefaultTxParameters static private
Initial value:
= {
    kDefaultAckTimeout,
    kDefaultAckRandomFactorNumerator,
    kDefaultAckRandomFactorDenominator,
    kDefaultMaxRetransmit,
}
Referenced by TxParameters::CalculateSpan(), and TxParameters::GetDefault().
kMaxCachedResponses
constexpr uint16_t kMaxCachedResponses = OPENTHREAD_CONFIG_COAP_SERVER_MAX_CACHED_RESPONSES static private
Referenced by ResponsesQueue::UpdateQueue().
mDequeueTime
TimeMilli mDequeueTime
Referenced by ResponsesQueue::EnqueueResponse(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
mMessageInfo
Ip6::MessageInfo mMessageInfo
Referenced by ResponsesQueue::EnqueueResponse(), and ResponsesQueue::FindMatchedResponse().
mQueue
MessageQueue mQueue private
Referenced by ResponsesQueue::DequeueAllResponses(), ResponsesQueue::DequeueResponse(), ResponsesQueue::EnqueueResponse(), ResponsesQueue::FindMatchedResponse(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
mTimer
TimerMilliContext mTimer private
Referenced by ResponsesQueue::EnqueueResponse(), and ResponsesQueue::HandleTimer().
mSourceAddress
Ip6::Address mSourceAddress
Referenced by CoapBase::ClearRequests(), CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mDestinationAddress
Ip6::Address mDestinationAddress
Referenced by CoapBase::FindRelatedRequest(), CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mDestinationPort
uint16_t mDestinationPort
Referenced by CoapBase::FindRelatedRequest(), CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mResponseHandler
ResponseHandler mResponseHandler
Referenced by CoapBase::AbortTransaction(), CoapBase::DequeueMessage(), CoapBase::FinalizeCoapTransaction(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mResponseContext
void* mResponseContext
Referenced by CoapBase::AbortTransaction(), CoapBase::DequeueMessage(), CoapBase::FinalizeCoapTransaction(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mNextTimerShot
TimeMilli mNextTimerShot
Referenced by CoapBase::CopyAndEnqueueMessage(), CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mRetransmissionTimeout
uint32_t mRetransmissionTimeout
Referenced by CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mRetransmissionsRemaining
uint8_t mRetransmissionsRemaining
Referenced by CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mAcknowledged
bool mAcknowledged
Referenced by CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mConfirmable
bool mConfirmable
Referenced by CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mMulticastLoop
bool mMulticastLoop
Referenced by CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mPendingRequests
MessageQueue mPendingRequests private
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), CoapBase::CopyAndEnqueueMessage(), CoapBase::DequeueMessage(), CoapBase::FindRelatedRequest(), and CoapBase::HandleRetransmissionTimer().
mMessageId
uint16_t mMessageId private
Referenced by CoapBase::SendMessage().
mRetransmissionTimer
TimerMilliContext mRetransmissionTimer private
Referenced by CoapBase::CopyAndEnqueueMessage(), CoapBase::DequeueMessage(), and CoapBase::HandleRetransmissionTimer().
mResources
LinkedList<Resource> mResources private
Referenced by CoapBase::AddResource(), CoapBase::ProcessReceivedRequest(), and CoapBase::RemoveResource().
mContext
void* mContext private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetInterceptor().
mInterceptor
Interceptor mInterceptor private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetInterceptor().
mResponsesQueue
ResponsesQueue mResponsesQueue private
Referenced by CoapBase::ClearRequestsAndResponses(), CoapBase::ProcessReceivedRequest(), and CoapBase::SendMessage().
mDefaultHandler
RequestHandler mDefaultHandler private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetDefaultHandler().
mDefaultHandlerContext
void* mDefaultHandlerContext private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetDefaultHandler().
mSender
const Sender mSender private
Referenced by CoapBase::Send().
mSocket
Ip6::Udp::Socket mSocket protected
Referenced by Coap::Send(), Coap::Start(), and Coap::Stop().
Friends
CoapBase [1/2]
friend class CoapBase friend
ResponsesQueue [1/2]
friend class ResponsesQueue friend
CoapBase [2/2]
friend class CoapBase friend
ResponsesQueue [2/2]
friend class ResponsesQueue friend
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale