OpenThread: Core-radio
Core-radio
This module includes definitions for OpenThread radio abstraction.
Data Structures
class Radio::Callbacks
class Radio
Functions
Error AddSrcMatchExtEntry (const Mac::ExtAddress &aExtAddress)
Error AddSrcMatchShortEntry (Mac::ShortAddress aShortAddress)
Callbacks (Instance &aInstance)
void ClearSrcMatchExtEntries (void)
Error ClearSrcMatchExtEntry (const Mac::ExtAddress &aExtAddress)
void ClearSrcMatchShortEntries (void)
Error ClearSrcMatchShortEntry (Mac::ShortAddress aShortAddress)
Error Disable (void)
Error Enable (void)
void EnableSrcMatch (bool aEnable)
Error EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
otRadioCaps GetCaps (void)
Error GetCcaEnergyDetectThreshold (int8_t &aThreshold)
void GetIeeeEui64 (Mac::ExtAddress &aIeeeEui64)
otInstance * GetInstancePtr (void)
uint32_t GetPreferredChannelMask (void)
bool GetPromiscuous (void)
int8_t GetReceiveSensitivity (void)
int8_t GetRssi (void)
otRadioState GetState (void)
uint32_t GetSupportedChannelMask (void)
Mac::TxFrame & GetTransmitBuffer (void)
Error GetTransmitPower (int8_t &aPower)
const char * GetVersionString (void)
void HandleEnergyScanDone (int8_t aMaxRssi)
void HandleReceiveDone (Mac::RxFrame *aFrame, Error aError)
void HandleTransmitDone (Mac::TxFrame &aFrame, Mac::RxFrame *aAckFrame, Error aError)
void HandleTransmitStarted (Mac::TxFrame &aFrame)
static bool IsCslChannelValid (uint8_t aCslChannel)
bool IsEnabled (void)
Radio (Instance &aInstance)
Error Receive (uint8_t aChannel)
Error SetCcaEnergyDetectThreshold (int8_t aThreshold)
void SetExtendedAddress (const Mac::ExtAddress &aExtAddress)
void SetMacFrameCounter (uint32_t aMacFrameCounter)
void SetMacKey (uint8_t aKeyIdMode, uint8_t aKeyId, const Mac::KeyMaterial &aPrevKey, const Mac::KeyMaterial &aCurrKey, const Mac::KeyMaterial &aNextKey)
void SetPanId (Mac::PanId aPanId)
void SetPromiscuous (bool aEnable)
void SetShortAddress (Mac::ShortAddress aShortAddress)
Error SetTransmitPower (int8_t aPower)
Error Sleep (void)
Error Transmit (Mac::TxFrame &aFrame)
Variables
static constexpr uint32_t kSymbolTime = OT_RADIO_SYMBOL_TIME
Callbacks mCallbacks
Friends
class Instance
class Radio
Detailed Description
This module includes definitions for OpenThread radio abstraction.
Function Documentation
HandleReceiveDone()
void HandleReceiveDone (Mac::RxFrame * aFrame, Error aError)
This callback method handles a "Receive Done" event from radio platform.
Parameters
[in] aFrame A pointer to the received frame or nullptr if the receive operation failed.
[in] aError kErrorNone when successfully received a frame, kErrorAbort when reception was aborted and a frame was not received, kErrorNoBufs when a frame could not be received due to lack of rx buffer space.
Referenced by Radio::Callbacks::HandleEnergyScanDone().
HandleTransmitStarted()
void HandleTransmitStarted (Mac::TxFrame & aFrame)
This callback method handles a "Transmit Started" event from radio platform.
Parameters
[in] aFrame The frame that is being transmitted.
HandleTransmitDone()
void HandleTransmitDone (Mac::TxFrame & aFrame, Mac::RxFrame * aAckFrame, Error aError)
This callback method handles a "Transmit Done" event from radio platform.
Parameters
[in] aFrame The frame that was transmitted.
[in] aAckFrame A pointer to the ACK frame, nullptr if no ACK was received.
[in] aError kErrorNone when the frame was transmitted, kErrorNoAck when the frame was transmitted but no ACK was received, kErrorChannelAccessFailure tx could not take place due to activity on the channel, kErrorAbort when transmission was aborted for other reasons.
Referenced by Radio::Callbacks::HandleEnergyScanDone().
HandleEnergyScanDone()
void HandleEnergyScanDone (int8_t aMaxRssi)
This callback method handles "Energy Scan Done" event from radio platform.
This method is used when radio provides OT_RADIO_CAPS_ENERGY_SCAN capability. It is called from otPlatRadioEnergyScanDone().
Parameters
[in] aMaxRssi The maximum RSSI encountered on the scanned channel.
References Radio::Callbacks::HandleReceiveDone(), Radio::Callbacks::HandleTransmitDone(), and OT_UNUSED_VARIABLE.
Callbacks()
Callbacks (Instance & aInstance) inline explicit private
Radio()
Radio (Instance & aInstance) inline explicit
This constructor initializes the Radio object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Radio::GetCaps(), Radio::GetIeeeEui64(), Radio::GetReceiveSensitivity(), Radio::GetVersionString(), Radio::SetExtendedAddress(), Radio::SetMacKey(), Radio::SetPanId(), and Radio::SetShortAddress().
GetVersionString()
const char * GetVersionString (void) inline
This method gets the radio version string.
Returns
A pointer to the OpenThread radio version.
References Radio::GetInstancePtr(), and otPlatRadioGetVersionString().
Referenced by Radio::Radio().
GetIeeeEui64()
void GetIeeeEui64 (Mac::ExtAddress & aIeeeEui64) inline
This method gets the factory-assigned IEEE EUI-64 for the device.
Parameters
[out] aIeeeEui64 A reference to Mac::ExtAddress to place the factory-assigned IEEE EUI-64.
References Radio::GetInstancePtr(), otExtAddress::m8, and otPlatRadioGetIeeeEui64().
Referenced by Radio::Radio().
GetCaps()
otRadioCaps GetCaps (void) inline
This method gets the radio capabilities.
Returns
The radio capability bit vector (see OT_RADIO_CAP_* definitions).
References OT_RADIO_CAPS_ACK_TIMEOUT, OT_RADIO_CAPS_CSMA_BACKOFF, and OT_RADIO_CAPS_TRANSMIT_RETRIES.
Referenced by Radio::GetPreferredChannelMask(), and Radio::Radio().
GetReceiveSensitivity()
int8_t GetReceiveSensitivity (void) inline
This method gets the radio receive sensitivity value.
Returns
The radio receive sensitivity value in dBm.
Referenced by Radio::GetPreferredChannelMask(), and Radio::Radio().
SetPanId()
void SetPanId (Mac::PanId aPanId) inline
This method sets the PAN ID for address filtering.
Parameters
[in] aPanId The IEEE 802.15.4 PAN ID.
Referenced by Radio::GetPreferredChannelMask(), and Radio::Radio().
SetExtendedAddress()
void SetExtendedAddress (const Mac::ExtAddress & aExtAddress) inline
This method sets the Extended Address for address filtering.
Parameters
[in] aExtAddress The IEEE 802.15.4 Extended Address stored in little-endian byte order.
Referenced by Radio::Radio().
SetShortAddress()
void SetShortAddress (Mac::ShortAddress aShortAddress) inline
This method sets the Short Address for address filtering.
Parameters
[in] aShortAddress The IEEE 802.15.4 Short Address.
Referenced by Radio::Radio().
SetMacKey()
void SetMacKey (uint8_t aKeyIdMode, uint8_t aKeyId, const Mac::KeyMaterial & aPrevKey, const Mac::KeyMaterial & aCurrKey, const Mac::KeyMaterial & aNextKey) inline
This method sets MAC key and key ID.
Parameters
[in] aKeyIdMode MAC key ID mode.
[in] aKeyId Current MAC key index.
[in] aPrevKey The previous MAC key.
[in] aCurrKey The current MAC key.
[in] aNextKey The next MAC key.
Referenced by Radio::GetPreferredChannelMask(), and Radio::Radio().
SetMacFrameCounter()
void SetMacFrameCounter (uint32_t aMacFrameCounter) inline
This method sets the current MAC Frame Counter value.
Parameters
[in] aMacFrameCounter The MAC Frame Counter value.
References Radio::AddSrcMatchExtEntry(), Radio::AddSrcMatchShortEntry(), Radio::ClearSrcMatchExtEntries(), Radio::ClearSrcMatchExtEntry(), Radio::ClearSrcMatchShortEntries(), Radio::ClearSrcMatchShortEntry(), Radio::Disable(), Radio::Enable(), Radio::EnableSrcMatch(), Radio::EnergyScan(), Radio::GetCcaEnergyDetectThreshold(), Radio::GetInstancePtr(), Radio::GetPreferredChannelMask(), Radio::GetPromiscuous(), Radio::GetRssi(), Radio::GetState(), Radio::GetSupportedChannelMask(), Radio::GetTransmitBuffer(), Radio::GetTransmitPower(), Radio::IsEnabled(), otPlatRadioConfigureEnhAckProbing(), otPlatRadioSetMacFrameCounter(), Radio::Receive(), Radio::SetCcaEnergyDetectThreshold(), Radio::SetPromiscuous(), Radio::SetTransmitPower(), Radio::Sleep(), and Radio::Transmit().
GetTransmitPower()
Error GetTransmitPower (int8_t & aPower) inline
This method gets the radio's transmit power in dBm.
Parameters
[out] aPower A reference to output the transmit power in dBm.
Return values
kErrorNone Successfully retrieved the transmit power.
kErrorNotImplemented Transmit power configuration via dBm is not implemented.
References ot::kErrorNotImplemented.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
SetTransmitPower()
Error SetTransmitPower (int8_t aPower) inline
This method sets the radio's transmit power in dBm.
Parameters
[in] aPower The transmit power in dBm.
Return values
kErrorNone Successfully set the transmit power.
kErrorNotImplemented Transmit power configuration via dBm is not implemented.
References ot::kErrorNotImplemented.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
GetCcaEnergyDetectThreshold()
Error GetCcaEnergyDetectThreshold (int8_t & aThreshold) inline
This method gets the radio's CCA ED threshold in dBm.
Parameters
[in] aThreshold The CCA ED threshold in dBm.
Return values
kErrorNone A reference to output the CCA ED threshold in dBm.
kErrorNotImplemented CCA ED threshold configuration via dBm is not implemented.
References ot::kErrorNotImplemented.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
SetCcaEnergyDetectThreshold()
Error SetCcaEnergyDetectThreshold (int8_t aThreshold) inline
This method sets the radio's CCA ED threshold in dBm.
Parameters
[in] aThreshold The CCA ED threshold in dBm.
Return values
kErrorNone Successfully set the CCA ED threshold.
kErrorNotImplemented CCA ED threshold configuration via dBm is not implemented.
References ot::kErrorNotImplemented.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
GetPromiscuous()
bool GetPromiscuous (void) inline
This method gets the status of promiscuous mode.
Return values
TRUE Promiscuous mode is enabled.
FALSE Promiscuous mode is disabled.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
SetPromiscuous()
void SetPromiscuous (bool aEnable) inline
This method enables or disables promiscuous mode.
Parameters
[in] aEnable TRUE to enable or FALSE to disable promiscuous mode.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
GetState()
otRadioState GetState (void) inline
This method returns the current state of the radio.
This function is not required by OpenThread. It may be used for debugging and/or application-specific purposes.
Note
This function may be not implemented. In this case it always returns OT_RADIO_STATE_INVALID state.
Returns
Current state of the radio.
References OT_RADIO_STATE_DISABLED.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
Enable()
Error Enable (void) inline
This method enables the radio.
Return values
kErrorNone Successfully enabled.
kErrorFailed The radio could not be enabled.
References ot::kErrorNone.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
Disable()
Error Disable (void) inline
This method disables the radio.
Return values
kErrorNone Successfully transitioned to Disabled.
kErrorInvalidState The radio was not in sleep state.
References ot::kErrorInvalidState.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
IsEnabled()
bool IsEnabled (void) inline
This method indicates whether radio is enabled or not.
Returns
TRUE if the radio is enabled, FALSE otherwise.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
Sleep()
Error Sleep (void) inline
This method transitions the radio from Receive to Sleep (turn off the radio).
Return values
kErrorNone Successfully transitioned to Sleep.
kErrorBusy The radio was transmitting.
kErrorInvalidState The radio was disabled.
References ot::kErrorNone.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
Receive()
Error Receive (uint8_t aChannel) inline
This method transitions the radio from Sleep to Receive (turn on the radio).
Parameters
[in] aChannel The channel to use for receiving.
Return values
kErrorNone Successfully transitioned to Receive.
kErrorInvalidState The radio was disabled or transmitting.
References ot::kErrorNone, and ot::kErrorNotImplemented.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
GetTransmitBuffer()
Mac::TxFrame & GetTransmitBuffer (void) inline
This method gets the radio transmit frame buffer.
OpenThread forms the IEEE 802.15.4 frame in this buffer then calls Transmit() to request transmission.
Returns
A reference to the transmit frame buffer.
References Radio::GetInstancePtr(), and otPlatRadioGetTransmitBuffer().
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
Transmit()
Error Transmit (Mac::TxFrame & aFrame) inline
This method starts the transmit sequence on the radio.
The caller must form the IEEE 802.15.4 frame in the buffer provided by GetTransmitBuffer() before requesting transmission. The channel and transmit power are also included in the frame.
Parameters
[in] aFrame A reference to the frame to be transmitted.
Return values
kErrorNone Successfully transitioned to Transmit.
kErrorInvalidState The radio was not in the Receive state.
References ot::kErrorAbort.
Referenced by Radio::SetMacFrameCounter().
GetRssi()
int8_t GetRssi (void) inline
This method gets the most recent RSSI measurement.
Returns
The RSSI in dBm when it is valid. 127 when RSSI is invalid.
References OT_RADIO_RSSI_INVALID.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
EnergyScan()
Error EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration) inline
This method begins the energy scan sequence on the radio.
This function is used when radio provides OT_RADIO_CAPS_ENERGY_SCAN capability.
Parameters
[in] aScanChannel The channel to perform the energy scan on.
[in] aScanDuration The duration, in milliseconds, for the channel to be scanned.
Return values
kErrorNone Successfully started scanning the channel.
kErrorBusy The radio is performing energy scanning.
kErrorNotImplemented The radio doesn't support energy scanning.
References ot::kErrorNotImplemented.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
EnableSrcMatch()
void EnableSrcMatch (bool aEnable) inline
This method enables/disables source address match feature.
The source address match feature controls how the radio layer decides the "frame pending" bit for acks sent in response to data request commands from children.
If disabled, the radio layer must set the "frame pending" on all acks to data request commands.
If enabled, the radio layer uses the source address match table to determine whether to set or clear the "frame pending" bit in an ack to a data request command.
The source address match table provides the list of children for which there is a pending frame. Either a short address or an extended/long address can be added to the source address match table.
Parameters
[in] aEnable Enable/disable source address match feature.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
AddSrcMatchShortEntry()
Error AddSrcMatchShortEntry (Mac::ShortAddress aShortAddress) inline
This method adds a short address to the source address match table.
Parameters
[in] aShortAddress The short address to be added.
Return values
kErrorNone Successfully added short address to the source match table.
kErrorNoBufs No available entry in the source match table.
References ot::kErrorNone.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
AddSrcMatchExtEntry()
Error AddSrcMatchExtEntry (const Mac::ExtAddress & aExtAddress) inline
This method adds an extended address to the source address match table.
Parameters
[in] aExtAddress The extended address to be added stored in little-endian byte order.
Return values
kErrorNone Successfully added extended address to the source match table.
kErrorNoBufs No available entry in the source match table.
References ot::kErrorNone.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
ClearSrcMatchShortEntry()
Error ClearSrcMatchShortEntry (Mac::ShortAddress aShortAddress) inline
This method removes a short address from the source address match table.
Parameters
[in] aShortAddress The short address to be removed.
Return values
kErrorNone Successfully removed short address from the source match table.
kErrorNoAddress The short address is not in source address match table.
References ot::kErrorNone.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
ClearSrcMatchExtEntry()
Error ClearSrcMatchExtEntry (const Mac::ExtAddress & aExtAddress) inline
This method removes an extended address from the source address match table.
Parameters
[in] aExtAddress The extended address to be removed stored in little-endian byte order.
Return values
kErrorNone Successfully removed the extended address from the source match table.
kErrorNoAddress The extended address is not in source address match table.
References ot::kErrorNone.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
ClearSrcMatchShortEntries()
void ClearSrcMatchShortEntries (void) inline
This method clears all short addresses from the source address match table.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
ClearSrcMatchExtEntries()
void ClearSrcMatchExtEntries (void) inline
This method clears all the extended/long addresses from source address match table.
Referenced by Radio::GetPreferredChannelMask(), and Radio::SetMacFrameCounter().
GetSupportedChannelMask()
uint32_t GetSupportedChannelMask (void) inline
This method gets the radio supported channel mask that the device is allowed to be on.
Returns
The radio supported channel mask.
References Radio::GetInstancePtr(), and otPlatRadioGetSupportedChannelMask().
Referenced by Radio::SetMacFrameCounter().
GetPreferredChannelMask()
uint32_t GetPreferredChannelMask (void) inline
This method gets the radio preferred channel mask that the device prefers to form on.
Returns
The radio preferred channel mask.
References Radio::AddSrcMatchExtEntry(), Radio::AddSrcMatchShortEntry(), Radio::ClearSrcMatchExtEntries(), Radio::ClearSrcMatchExtEntry(), Radio::ClearSrcMatchShortEntries(), Radio::ClearSrcMatchShortEntry(), Radio::Disable(), Radio::Enable(), Radio::EnableSrcMatch(), Radio::EnergyScan(), Radio::GetCaps(), Radio::GetCcaEnergyDetectThreshold(), Radio::GetInstancePtr(), Radio::GetPromiscuous(), Radio::GetReceiveSensitivity(), Radio::GetRssi(), Radio::GetState(), Radio::GetTransmitBuffer(), Radio::GetTransmitPower(), Radio::IsEnabled(), OT_KEY_TYPE_KEY_REF, OT_KEY_TYPE_LITERAL_KEY, otPlatRadioAddSrcMatchExtEntry(), otPlatRadioAddSrcMatchShortEntry(), otPlatRadioClearSrcMatchExtEntries(), otPlatRadioClearSrcMatchExtEntry(), otPlatRadioClearSrcMatchShortEntries(), otPlatRadioClearSrcMatchShortEntry(), otPlatRadioDisable(), otPlatRadioEnable(), otPlatRadioEnableCsl(), otPlatRadioEnableSrcMatch(), otPlatRadioEnergyScan(), otPlatRadioGetCaps(), otPlatRadioGetCcaEnergyDetectThreshold(), otPlatRadioGetCslAccuracy(), otPlatRadioGetCslUncertainty(), otPlatRadioGetPreferredChannelMask(), otPlatRadioGetPromiscuous(), otPlatRadioGetReceiveSensitivity(), otPlatRadioGetRssi(), otPlatRadioGetState(), otPlatRadioGetTransmitBuffer(), otPlatRadioGetTransmitPower(), otPlatRadioIsEnabled(), otPlatRadioReceive(), otPlatRadioReceiveAt(), otPlatRadioSetCcaEnergyDetectThreshold(), otPlatRadioSetMacKey(), otPlatRadioSetPanId(), otPlatRadioSetPromiscuous(), otPlatRadioSetTransmitPower(), otPlatRadioSleep(), otPlatRadioUpdateCslSampleTime(), Radio::Receive(), Radio::SetCcaEnergyDetectThreshold(), Radio::SetMacKey(), Radio::SetPanId(), Radio::SetPromiscuous(), Radio::SetTransmitPower(), and Radio::Sleep().
Referenced by Dataset::Info::GenerateRandom(), and Radio::SetMacFrameCounter().
IsCslChannelValid()
static bool IsCslChannelValid (uint8_t aCslChannel) inline static
This method checks if a given channel is valid as a CSL channel.
Return values
true The channel is valid.
false The channel is invalid.
Referenced by otLinkGetCcaFailureRate().
GetInstancePtr()
otInstance* GetInstancePtr (void) inline private
References InstanceLocator::GetInstance().
Referenced by Radio::GetIeeeEui64(), Radio::GetPreferredChannelMask(), Radio::GetSupportedChannelMask(), Radio::GetTransmitBuffer(), Radio::GetVersionString(), and Radio::SetMacFrameCounter().
Variable Documentation
kSymbolTime
constexpr uint32_t kSymbolTime = OT_RADIO_SYMBOL_TIME static
Referenced by SubMac::StartTimerForBackoff().
mCallbacks
Callbacks mCallbacks private
Friends
Instance
friend class Instance friend
Radio
friend class Radio friend
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale