OpenThread: Tasklets
Tasklets
API » Execution
This module includes functions that control the Thread stack's execution.
Functions
bool otTaskletsArePending (otInstance *aInstance)
void otTaskletsProcess (otInstance *aInstance)
void otTaskletsSignalPending (otInstance *aInstance)
Detailed Description
This module includes functions that control the Thread stack's execution.
Function Documentation
otTaskletsProcess()
void otTaskletsProcess (otInstance * aInstance)
Run all queued OpenThread tasklets at the time this is called.
Parameters
[in] aInstance A pointer to an OpenThread instance.
References ot::AsCoreType(), otInstanceIsInitialized(), and VerifyOrExit.
Referenced by main().
otTaskletsArePending()
bool otTaskletsArePending (otInstance * aInstance)
Indicates whether or not OpenThread has tasklets pending.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
TRUE If there are tasklets pending.
FALSE If there are no tasklets pending.
References ot::AsCoreType(), otInstanceIsInitialized(), and VerifyOrExit.
Referenced by otSysMainloopUpdate().
otTaskletsSignalPending()
void otTaskletsSignalPending (otInstance * aInstance)
OpenThread calls this function when the tasklet queue transitions from empty to non-empty.
Parameters
[in] aInstance A pointer to an OpenThread instance.
References OT_UNUSED_VARIABLE.
Referenced by Tasklet::Scheduler::PostTasklet().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale