OpenThread: main.c File Reference
main.c File Reference
#include "platform/openthread-posix-config.h"
#include <openthread/config.h>
#include <assert.h>
#include <errno.h>
#include <getopt.h>
#include <libgen.h>
#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>
#include <unistd.h>
#include <openthread/cli.h>
#include <openthread/diag.h>
#include <openthread/logging.h>
#include <openthread/tasklet.h>
#include <openthread/thread.h>
#include <openthread/platform/radio.h>
#include "cli/cli_config.h"
#include <common/code_utils.hpp>
#include <lib/platform/exit_code.h>
#include <openthread/openthread-system.h>
#include <openthread/platform/misc.h>
#include "lib/platform/reset_util.h"
Macros
#define HAVE_LIBEDIT 0
#define HAVE_LIBREADLINE 0
Typedefs
typedef struct PosixConfig PosixConfig
Enumerations
enum {
OT_POSIX_OPT_BACKBONE_INTERFACE_NAME = 'B', OT_POSIX_OPT_DEBUG_LEVEL = 'd', OT_POSIX_OPT_DRY_RUN = 'n', OT_POSIX_OPT_HELP = 'h',
OT_POSIX_OPT_INTERFACE_NAME = 'I', OT_POSIX_OPT_TIME_SPEED = 's', OT_POSIX_OPT_VERBOSE = 'v', OT_POSIX_OPT_SHORT_MAX = 128,
OT_POSIX_OPT_RADIO_VERSION, OT_POSIX_OPT_REAL_TIME_SIGNAL
}
Functions
static otInstance * InitInstance (PosixConfig *aConfig)
int main (int argc, char *argv[])
void otAppCliDeinit (void)
void otAppCliInit (otInstance *aInstance)
void otAppCliProcess (const otSysMainloopContext *aMainloop)
void otAppCliUpdate (otSysMainloopContext *aMainloop)
void otAppNcpInit (otInstance *aInstance)
void otAppNcpProcess (const otSysMainloopContext *aContext)
void otAppNcpUpdate (otSysMainloopContext *aContext)
void otPlatReset (otInstance *aInstance)
void otTaskletsSignalPending (otInstance *aInstance)
static void ParseArg (int aArgCount, char *aArgVector[], PosixConfig *aConfig)
static void PrintUsage (const char *aProgramName, FILE *aStream, int aExitCode)
static void ProcessExit (void *aContext, uint8_t aArgsLength, char *aArgs[])
static void ProcessNetif (void *aContext, uint8_t aArgsLength, char *aArgs[])
Variables
static const otCliCommand kCommands []
static const struct option kOptions []
Macro Definition Documentation
HAVE_LIBEDIT
#define HAVE_LIBEDIT 0
HAVE_LIBREADLINE
#define HAVE_LIBREADLINE 0
Typedef Documentation
PosixConfig
typedef struct PosixConfig PosixConfig
Enumeration Type Documentation
anonymous enum
anonymous enum
This enumeration defines the argument return values.
Enumerator
OT_POSIX_OPT_BACKBONE_INTERFACE_NAME
OT_POSIX_OPT_DEBUG_LEVEL
OT_POSIX_OPT_DRY_RUN
OT_POSIX_OPT_HELP
OT_POSIX_OPT_INTERFACE_NAME
OT_POSIX_OPT_TIME_SPEED
OT_POSIX_OPT_VERBOSE
OT_POSIX_OPT_SHORT_MAX
OT_POSIX_OPT_RADIO_VERSION
OT_POSIX_OPT_REAL_TIME_SIGNAL
Function Documentation
otAppNcpInit()
void otAppNcpInit (otInstance * aInstance)
This function initializes NCP app.
Parameters
[in] aInstance A pointer to the OpenThread instance.
otAppNcpUpdate()
void otAppNcpUpdate (otSysMainloopContext * aContext)
This function deinitializes NCP app.
otAppNcpProcess()
void otAppNcpProcess (const otSysMainloopContext * aContext)
This function updates the file descriptor sets with file descriptors used by console.
Parameters
[in,out] aMainloop A pointer to the mainloop context.
otAppCliInit()
void otAppCliInit (otInstance * aInstance)
This function initializes CLI app.
Parameters
[in] aInstance A pointer to the OpenThread instance.
References otCliInit().
Referenced by main().
otAppCliDeinit()
void otAppCliDeinit (void)
This function deinitializes CLI app.
Referenced by main().
otAppCliUpdate()
void otAppCliUpdate (otSysMainloopContext * aMainloop)
This function updates the file descriptor sets with file descriptors used by console.
Parameters
[in,out] aMainloop A pointer to the mainloop context.
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, and otSysMainloopContext::mReadFdSet.
Referenced by main().
otAppCliProcess()
void otAppCliProcess (const otSysMainloopContext * aMainloop)
This function performs console driver processing.
Parameters
[in] aMainloop A pointer to the mainloop context.
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mReadFdSet, OPENTHREAD_CONFIG_CLI_MAX_LINE_LENGTH, OT_EXIT_FAILURE, OT_EXIT_SUCCESS, and otCliInputLine().
Referenced by main().
PrintUsage()
static void PrintUsage (const char * aProgramName, FILE * aStream, int aExitCode) static
References otSysGetRadioUrlHelpString().
Referenced by ParseArg().
ParseArg()
static void ParseArg (int aArgCount, char * aArgVector[], PosixConfig * aConfig) static
References kOptions, OT_ARRAY_LENGTH, OT_EXIT_INVALID_ARGUMENTS, OT_EXIT_SUCCESS, OT_LOG_LEVEL_CRIT, OT_POSIX_OPT_BACKBONE_INTERFACE_NAME, OT_POSIX_OPT_DEBUG_LEVEL, OT_POSIX_OPT_DRY_RUN, OT_POSIX_OPT_HELP, OT_POSIX_OPT_INTERFACE_NAME, OT_POSIX_OPT_RADIO_VERSION, OT_POSIX_OPT_REAL_TIME_SIGNAL, OT_POSIX_OPT_TIME_SPEED, OT_POSIX_OPT_VERBOSE, PrintUsage(), and VerifyOrDie.
Referenced by main().
InitInstance()
static otInstance* InitInstance (PosixConfig * aConfig) static
References IgnoreError(), OT_EXIT_FAILURE, OT_EXIT_SUCCESS, otGetVersionString(), otLoggingSetLevel(), otPlatRadioGetVersionString(), otSysGetThreadNetifName(), otSysInit(), otThreadGetVersion(), and VerifyOrDie.
Referenced by main().
ProcessNetif()
static void ProcessNetif (void * aContext, uint8_t aArgsLength, char * aArgs[]) static
References OT_UNUSED_VARIABLE, otCliOutputFormat(), otSysGetThreadNetifIndex(), and otSysGetThreadNetifName().
ProcessExit()
static void ProcessExit (void * aContext, uint8_t aArgsLength, char * aArgs[]) static
References OT_UNUSED_VARIABLE.
main()
int main (int argc, char * argv[])
References ExitNow, InitInstance(), otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mTimeout, otSysMainloopContext::mWriteFdSet, OT_ARRAY_LENGTH, OT_EXIT_FAILURE, OT_SETUP_RESET_JUMP, otAppCliDeinit(), otAppCliInit(), otAppCliProcess(), otAppCliUpdate(), otCliSetUserCommands(), otSysDeinit(), otSysMainloopPoll(), otSysMainloopProcess(), otSysMainloopUpdate(), otTaskletsProcess(), and ParseArg().
Variable Documentation
kOptions
const struct option kOptions[] static
Initial value:
= {
    {"backbone-interface-name", required_argument, NULL, OT_POSIX_OPT_BACKBONE_INTERFACE_NAME},
    {"debug-level", required_argument, NULL, OT_POSIX_OPT_DEBUG_LEVEL},
    {"dry-run", no_argument, NULL, OT_POSIX_OPT_DRY_RUN},
    {"help", no_argument, NULL, OT_POSIX_OPT_HELP},
    {"interface-name", required_argument, NULL, OT_POSIX_OPT_INTERFACE_NAME},
    {"radio-version", no_argument, NULL, OT_POSIX_OPT_RADIO_VERSION},
    {"real-time-signal", required_argument, NULL, OT_POSIX_OPT_REAL_TIME_SIGNAL},
    {"time-speed", required_argument, NULL, OT_POSIX_OPT_TIME_SPEED},
    {"verbose", no_argument, NULL, OT_POSIX_OPT_VERBOSE},
    {0, 0, 0, 0}}
Referenced by ParseArg().
kCommands
const otCliCommand kCommands[] static
Initial value:
= {
    {"exit", ProcessExit},
    {"netif", ProcessNetif},
}
Referenced by Dataset::Process(), NetworkData::Process(), and Interpreter::ProcessCommand().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale