OpenThread: ot::NetworkData Namespace Reference
ot::NetworkData Namespace Reference
This namespace includes definitions for managing Thread Network Data.
Namespaces
Service
Data Structures
class BorderRouterEntry
class BorderRouterTlv
class CommissioningDataTlv
class ContextTlv
class ExternalRouteConfig
class HasRouteEntry
class HasRouteTlv
class LeaderBase
class MutableNetworkData
class NetworkData
class NetworkDataTlv
class OnMeshPrefixConfig
class PrefixTlv
class ServerData
class ServerTlv
class ServiceConfig
class ServiceData
class ServiceTlv
class TlvIterator
Typedefs
typedef otNetworkDataIterator Iterator
Enumerations
enum RoleFilter : uint8_t { kAnyRole, kRouterRoleOnly, kChildRoleOnly }
enum RoutePreference : int8_t { kRoutePreferenceLow = OT_ROUTE_PREFERENCE_LOW, kRoutePreferenceMedium = OT_ROUTE_PREFERENCE_MED, kRoutePreferenceHigh = OT_ROUTE_PREFERENCE_HIGH }
enum Type : uint8_t { kFullSet, kStableSubset }
Functions
template<class TlvType >
TlvType * As (NetworkDataTlv *aTlv)
template<class TlvType >
const TlvType * As (const NetworkDataTlv *aTlv)
template<class TlvType >
TlvType & As (NetworkDataTlv &aTlv)
template<class TlvType >
const TlvType & As (const NetworkDataTlv &aTlv)
bool IsRoutePreferenceValid (int8_t aPref)
RegisterLogModule ("NetworkData")
RoutePreference RoutePreferenceFromValue (uint8_t aValue)
uint8_t RoutePreferenceToValue (int8_t aPref)
Variables
constexpr Iterator kIteratorInit = OT_NETWORK_DATA_ITERATOR_INIT
Initializer for Iterator type.
OT_TOOL_PACKED_BEGIN class ot::NetworkData::NetworkDataTlv OT_TOOL_PACKED_END
Detailed Description
This namespace includes definitions for managing Thread Network Data.
Enumeration Type Documentation
Type
enum Type : uint8_t
This enumeration represents the Network Data type.
Enumerator
kFullSet
Full Network Data set.
kStableSubset
Stable Network Data subset.
RoutePreference
enum RoutePreference : int8_t
This enumeration type represents the route preference values as a signed integer (per RFC-4191).
Enumerator
kRoutePreferenceLow
Low route preference.
kRoutePreferenceMedium
Medium route preference.
kRoutePreferenceHigh
High route preference.
RoleFilter
enum RoleFilter : uint8_t
This enumeration represents the border router RLOC role filter used when searching for border routers in the Network Data.
Enumerator
kAnyRole
Include devices in any role.
kRouterRoleOnly
Include devices that act as Thread router.
kChildRoleOnly
Include devices that act as Thread child (end-device).
Function Documentation
RegisterLogModule()
RegisterLogModule ("NetworkData")
IsRoutePreferenceValid()
bool ot::NetworkData::IsRoutePreferenceValid (int8_t aPref) inline
This function indicates whether a given int8_t preference value is a valid route preference (i.e., one of the values from RoutePreference enumeration).
Parameters
[in] aPref The signed route preference value.
Return values
TRUE if aPref is valid.
FALSE if aPref is not valid
References kRoutePreferenceHigh, kRoutePreferenceLow, and kRoutePreferenceMedium.
Referenced by RouteInfoOption::IsValid(), RoutePreferenceToValue(), and OnMeshPrefixConfig::SetFromTlvFlags().
RoutePreferenceToValue()
uint8_t ot::NetworkData::RoutePreferenceToValue (int8_t aPref) inline
This function coverts a route preference to a 2-bit unsigned value.
The aPref MUST be valid (value from RoutePreference enumeration), or the behavior is undefined.
Parameters
[in] aPref The route preference to convert.
Returns
The 2-bit unsigned value representing aPref.
References IsRoutePreferenceValid(), and OT_ASSERT.
Referenced by OnMeshPrefixConfig::GetPreference(), RouterAdvertMessage::Header::SetDefaultRouterPreference(), OnMeshPrefixConfig::SetFromTlvFlags(), and RouteInfoOption::SetPreference().
RoutePreferenceFromValue()
RoutePreference ot::NetworkData::RoutePreferenceFromValue (uint8_t aValue) inline
This function coverts a 2-bit unsigned value to a route preference.
Parameters
[in] aValue The 2-bit unsigned value to convert from. Note that only the first two bits of aValue are used and the rest of bits are ignored.
Returns
The route preference corresponding to aValue.
References kRoutePreferenceHigh, kRoutePreferenceLow, and kRoutePreferenceMedium.
Referenced by RouterAdvertMessage::Header::GetDefaultRouterPreference(), OnMeshPrefixConfig::GetPreference(), RouteInfoOption::GetPreference(), HasRouteEntry::PreferenceFromFlags(), BorderRouterEntry::PreferenceFromFlags(), OnMeshPrefixConfig::SetFromTlvFlags(), and ExternalRouteConfig::SetFromTlvFlags().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale