OpenThread: ot::MeshCoP Namespace Reference
ot::MeshCoP Namespace Reference
Data Structures
class ActiveDatasetManager
class ActiveTimestampTlv
class BorderAgentLocatorTlv
class ChannelMaskBaseTlv
class ChannelMaskEntry
class ChannelMaskEntryBase
class ChannelMaskTlv
class ChannelTlv
class CommissionerIdTlv
class CommissionerSessionIdTlv
class Dataset
class DatasetLocal
class DatasetManager
class DelayTimerTlv
class DiscoveryRequestTlv
class DiscoveryResponseTlv
class Dtls
class EnergyListTlv
class ExtendedPanId
class ExtendedPanIdManager
class ExtendedPanIdTlv
class ExtendedTlv
class JoinerAdvertisementTlv
class JoinerDiscerner
class JoinerPskd
class JoinerUdpPortTlv
class MeshLocalPrefixTlv
class NameData
class NetworkKeySequenceTlv
class NetworkKeyTlv
class NetworkName
class NetworkNameManager
class NetworkNameTlv
class PanIdTlv
class PendingDatasetManager
class PendingTimestampTlv
class ProvisioningUrlTlv
class PskcTlv
class SecurityPolicyTlv
class StateTlv
class SteeringData
class SteeringDataTlv
class Timestamp
class Tlv
class UdpEncapsulationTlv
class VendorDataTlv
class VendorModelTlv
class VendorNameTlv
class VendorStackVersionTlv
class VendorSwVersionTlv
Typedefs
typedef UintTlvInfo< Tlv::kCommissionerUdpPort, uint16_t > CommissionerUdpPortTlv
typedef UintTlvInfo< Tlv::kCount, uint8_t > CountTlv
typedef NetworkName DomainName
typedef SimpleTlvInfo< Tlv::kIp6Address, Ip6::Address > Ip6AddressTlv
typedef SimpleTlvInfo< Tlv::kJoinerIid, Ip6::InterfaceIdentifier > JoinerIidTlv
typedef SimpleTlvInfo< Tlv::kJoinerRouterKek, Kek > JoinerRouterKekTlv
typedef UintTlvInfo< Tlv::kJoinerRouterLocator, uint16_t > JoinerRouterLocatorTlv
typedef UintTlvInfo< Tlv::kPeriod, uint16_t > PeriodTlv
typedef UintTlvInfo< Tlv::kScanDuration, uint16_t > ScanDurationTlv
Functions
void ComputeJoinerId (const Mac::ExtAddress &aEui64, Mac::ExtAddress &aJoinerId)
Error GeneratePskc (const char *aPassPhrase, const NetworkName &aNetworkName, const ExtendedPanId &aExtPanId, Pskc &aPskc)
Error GetBorderAgentRloc (ThreadNetif &aNetif, uint16_t &aRloc)
void LogError (const char *, Error)
RegisterLogModule ("DatasetLocal")
RegisterLogModule ("Dataset")
RegisterLogModule ("DatasetManager")
Variables
ot::MeshCoP::ExtendedPanId OT_TOOL_PACKED_END
Typedef Documentation
CommissionerUdpPortTlv
typedef UintTlvInfo<Tlv::kCommissionerUdpPort, uint16_t> CommissionerUdpPortTlv
This class defines Commissioner UDP Port TLV constants and types.
Ip6AddressTlv
typedef SimpleTlvInfo<Tlv::kIp6Address, Ip6::Address> Ip6AddressTlv
This class defines IPv6 Address TLV constants and types.
JoinerIidTlv
typedef SimpleTlvInfo<Tlv::kJoinerIid, Ip6::InterfaceIdentifier> JoinerIidTlv
This class defines Joiner IID TLV constants and types.
JoinerRouterLocatorTlv
typedef UintTlvInfo<Tlv::kJoinerRouterLocator, uint16_t> JoinerRouterLocatorTlv
This class defines Joiner Router Locator TLV constants and types.
JoinerRouterKekTlv
typedef SimpleTlvInfo<Tlv::kJoinerRouterKek, Kek> JoinerRouterKekTlv
This class defines Joiner Router KEK TLV constants and types.
CountTlv
typedef UintTlvInfo<Tlv::kCount, uint8_t> CountTlv
This class defines Count TLV constants and types.
PeriodTlv
typedef UintTlvInfo<Tlv::kPeriod, uint16_t> PeriodTlv
This class defines Period TLV constants and types.
ScanDurationTlv
typedef UintTlvInfo<Tlv::kScanDuration, uint16_t> ScanDurationTlv
This class defines Scan Duration TLV constants and types.
DomainName
typedef NetworkName DomainName
This type represents a Thread Domain Name.
Function Documentation
RegisterLogModule() [1/3]
ot::MeshCoP::RegisterLogModule ("Dataset")
RegisterLogModule() [2/3]
ot::MeshCoP::RegisterLogModule ("DatasetLocal")
RegisterLogModule() [3/3]
ot::MeshCoP::RegisterLogModule ("DatasetManager")
ComputeJoinerId()
void ComputeJoinerId (const Mac::ExtAddress & aEui64, Mac::ExtAddress & aJoinerId)
This function computes the Joiner ID from a factory-assigned IEEE EUI-64.
Parameters
[in] aEui64 The factory-assigned IEEE EUI-64.
[out] aJoinerId The Joiner ID.
References Sha256::Finish(), Sha256::Hash::GetBytes(), ExtAddress::SetLocal(), Sha256::Start(), and Sha256::Update().
Referenced by SteeringData::ClearBit(), DiscoverScanner::Discover(), and LeaderBase::SteeringDataCheckJoiner().
GetBorderAgentRloc()
Error GetBorderAgentRloc (ThreadNetif & aNetIf, uint16_t & aRloc)
This function gets the border agent RLOC.
Parameters
[in] aNetIf A reference to the thread interface.
[out] aRloc Border agent RLOC.
Return values
kErrorNone Successfully got the Border Agent Rloc.
kErrorNotFound Border agent is not available.
References ot::ErrorToString(), ot::Crypto::Pbkdf2::GenerateKey(), GeneratePskc(), GetProvider< InstanceGetProvider >::Get(), NetworkName::GetAsCString(), BorderAgentLocatorTlv::GetBorderAgentLocator(), ot::IsValidUtf8String(), Tlv::kBorderAgentLocator, ot::kErrorAlready, ot::kErrorInvalidArgs, ot::kErrorNone, ot::kErrorNotFound, ot::Crypto::Pbkdf2::kMaxSaltLength, LogError(), LogWarn, otExtendedPanId::m8, otPskc::m8, OT_COMMISSIONING_PASSPHRASE_MAX_SIZE, OT_COMMISSIONING_PASSPHRASE_MIN_SIZE, OT_EXT_PAN_ID_SIZE, OT_NETWORK_NAME_MAX_SIZE, OT_PSKC_MAX_SIZE, ot::StringLength(), and VerifyOrExit.
Referenced by SteeringData::ClearBit().
GeneratePskc()
Error ot::MeshCoP::GeneratePskc (const char * aPassPhrase, const NetworkName & aNetworkName, const ExtendedPanId & aExtPanId, Pskc & aPskc)
This function generates PSKc.
PSKc is used to establish the Commissioner Session.
Parameters
[in] aPassPhrase The commissioning passphrase.
[in] aNetworkName The network name for PSKc computation.
[in] aExtPanId The extended PAN ID for PSKc computation.
[out] aPskc A reference to a PSKc where the generated PSKc will be placed.
Return values
kErrorNone Successfully generate PSKc.
kErrorInvalidArgs If the length of passphrase is out of range.
Referenced by SteeringData::ClearBit(), GetBorderAgentRloc(), and otDatasetSendMgmtPendingSet().
LogError()
void ot::MeshCoP::LogError (const char * , Error) inline
References ot::DefineCoreType().
Referenced by Mle::CheckReachability(), SteeringData::ClearBit(), GetBorderAgentRloc(), Mle::IsDetachingGracefully(), PanIdQueryServer::SendConflict(), EnergyScanServer::SendReport(), and DatasetManager::SendSet().
Variable Documentation
OT_TOOL_PACKED_END
ot::MeshCoP::Timestamp OT_TOOL_PACKED_END
Referenced by Tlv::FindTlv(), ChannelMaskBaseTlv::Init(), EnergyListTlv::IsValid(), and ExtendedTlv::SetType().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale