OpenThread: ot::Utils::CmdLineParser Namespace Reference
ot::Utils::CmdLineParser Namespace Reference
Data Structures
class Arg
Enumerations
enum HexStringParseMode { kModeExtactSize, kModeUpToSize, kModeAllowPartial }
Functions
static bool IsEscapable (char aChar)
static bool IsSeparator (char aChar)
Error ParseAsBool (const char *aString, bool &aBool)
template<uint16_t kBufferSize>
static otError ParseAsHexString (const char *aString, uint8_t(&aBuffer)[kBufferSize])
Error ParseAsHexString (const char *aString, uint8_t *aBuffer, uint16_t aSize)
Error ParseAsHexString (const char *aString, uint16_t &aSize, uint8_t *aBuffer)
Error ParseAsHexStringSegment (const char *&aString, uint16_t &aSize, uint8_t *aBuffer)
Error ParseAsInt16 (const char *aString, int16_t &aInt16)
Error ParseAsInt32 (const char *aString, int32_t &aInt32)
Error ParseAsInt8 (const char *aString, int8_t &aInt8)
Error ParseAsUint16 (const char *aString, uint16_t &aUint16)
Error ParseAsUint32 (const char *aString, uint32_t &aUint32)
Error ParseAsUint64 (const char *aString, uint64_t &aUint64)
Error ParseAsUint8 (const char *aString, uint8_t &aUint8)
Error ParseCmd (char *aCommandString, Arg aArgs[], uint8_t aArgsMaxLength)
template<uint8_t kLength>
otError ParseCmd (char *aCommandString, Arg(&aArgs)[kLength])
static Error ParseDigit (char aDigitChar, uint8_t &aValue)
static Error ParseHexDigit (char aHexChar, uint8_t &aValue)
static Error ParseHexString (const char *&aString, uint16_t &aSize, uint8_t *aBuffer, HexStringParseMode aMode)
template<typename IntType >
Error ParseInt (const char *aString, IntType &aInt)
template<typename UintType >
Error ParseUint (const char *aString, UintType &aUint)
Enumeration Type Documentation
HexStringParseMode
enum HexStringParseMode
Enumerator
kModeExtactSize
kModeUpToSize
kModeAllowPartial
Function Documentation
IsSeparator()
static bool ot::Utils::CmdLineParser::IsSeparator (char aChar) static
Referenced by IsEscapable(), and ParseCmd().
IsEscapable()
static bool ot::Utils::CmdLineParser::IsEscapable (char aChar) static
References IsSeparator().
Referenced by ParseCmd().
ParseDigit()
static Error ot::Utils::CmdLineParser::ParseDigit (char aDigitChar, uint8_t & aValue) static
References ot::kErrorInvalidArgs, ot::kErrorNone, and VerifyOrExit.
Referenced by ParseAsUint64(), and ParseHexDigit().
ParseHexDigit()
static Error ot::Utils::CmdLineParser::ParseHexDigit (char aHexChar, uint8_t & aValue) static
References ExitNow, ot::kErrorNone, and ParseDigit().
Referenced by ParseAsUint64(), and ParseHexString().
ParseUint()
Error ot::Utils::CmdLineParser::ParseUint (const char * aString, UintType & aUint)
References ot::kErrorInvalidArgs, ParseAsUint64(), SuccessOrExit, and VerifyOrExit.
ParseInt()
Error ot::Utils::CmdLineParser::ParseInt (const char * aString, IntType & aInt)
References ot::kErrorInvalidArgs, ParseAsInt32(), SuccessOrExit, and VerifyOrExit.
ParseHexString()
static Error ot::Utils::CmdLineParser::ParseHexString (const char *& aString, uint16_t & aSize, uint8_t * aBuffer, HexStringParseMode aMode) static
References ExitNow, ot::kErrorInvalidArgs, ot::kErrorNone, ot::kErrorPending, kModeAllowPartial, kModeExtactSize, kModeUpToSize, ParseHexDigit(), SuccessOrExit, and VerifyOrExit.
Referenced by ParseAsHexString(), and ParseAsHexStringSegment().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale