OpenThread: ot::Heap Namespace Reference
ot::Heap Namespace Reference
Data Structures
class Allocatable
class Array
class Data
class String
Functions
void * CAlloc (size_t aCount, size_t aSize)
void Free (void *aPointer)
Function Documentation
CAlloc()
void * CAlloc (size_t aCount, size_t aSize)
This function allocates memory from heap for an array of given number of object of certain size.
Parameters
[in] aCount Number of objects.
[in] aSize Size of each object.
Returns
A pointer to the allocated buffer or nullptr if fails to allocate.
Referenced by Allocatable< Type >::Allocate(), Array< Type, kCapacityIncrements >::Allocate(), Allocatable< Type >::AllocateAndInit(), MbedTls::MbedTls(), otHeapCAlloc(), String::Set(), and Data::UpdateBuffer().
Free()
void Free (void * aPointer)
This function frees a previously heap allocated buffer.
A heap allocated buffer MUST be freed only once.
Parameters
[in] aPointer A pointer to the previously heap allocated buffer. Can be nullptr which does nothing.
Referenced by Array< Type, kCapacityIncrements >::Allocate(), Array< Type, kCapacityIncrements >::Free(), Allocatable< Type >::Free(), String::Free(), Data::Free(), MbedTls::MbedTls(), otHeapFree(), String::Set(), and Data::UpdateBuffer().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale