OpenThread: ot::Posix Namespace Reference
ot::Posix Namespace Reference
Namespaces
Ip6Utils
Mainloop
Data Structures
class Daemon
class HdlcInterface
class Radio
class RadioUrl
class Udp
Enumerations
enum { kSystemCommandMaxLength = 1024, kOutputBufferSize = 1024 }
Functions
otError ExecuteCommand (const char *aFormat,...)
void PlatformSettingsAdd (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
otError PlatformSettingsDelete (otInstance *aInstance, uint16_t aKey, int aIndex, int *aSwapFd)
otError PlatformSettingsGet (otInstance *aInstance, uint16_t aKey, int aIndex, uint8_t *aValue, uint16_t *aValueLength)
void PlatformSettingsGetSensitiveKeys (otInstance *aInstance, const uint16_t **aKeys, uint16_t *aKeysLength)
void PlatformSettingsSet (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kSystemCommandMaxLength
Max length of a system call command.
kOutputBufferSize
Buffer size of command output.
Function Documentation
PlatformSettingsGet()
otError PlatformSettingsGet (otInstance * aInstance, uint16_t aKey, int aIndex, uint8_t * aValue, uint16_t * aValueLength)
This function gets a setting from the persisted file.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the specific item to get.
[out] aValue A pointer to where the value of the setting should be written.
[in,out] aValueLength A pointer to the length of the value.
Return values
OT_ERROR_NONE The given setting was found and fetched successfully.
OT_ERROR_NOT_FOUND The given key or index was not found in the setting store.
References OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, OT_UNUSED_VARIABLE, sSettingsFd, and VerifyOrExit.
Referenced by otPlatSettingsGet().
PlatformSettingsSet()
void PlatformSettingsSet (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This function sets a setting in the persisted file.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aValue A pointer to where the new value of the setting should be read from.
[in] aValueLength The length of the data pointed to by aValue.
References OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_EXIT_FAILURE, PlatformSettingsDelete(), swapPersist(), and VerifyOrDie.
Referenced by otPlatSettingsSet().
PlatformSettingsAdd()
void PlatformSettingsAdd (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This function adds a setting to the persisted file.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aValue A pointer to where the new value of the setting should be read from.
[in] aValueLength The length of the data pointed to by aValue.
References OT_EXIT_ERROR_ERRNO, OT_EXIT_FAILURE, sSettingsFd, swapOpen(), swapPersist(), swapWrite(), and VerifyOrDie.
Referenced by otPlatSettingsAdd().
PlatformSettingsDelete()
otError PlatformSettingsDelete (otInstance * aInstance, uint16_t aKey, int aIndex, int * aSwapFd)
This function removes a setting either from swap file or persisted file.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the value to be removed. If set to -1, all values for this aKey will be removed.
[out] aSwapFd A optional pointer to receive file descriptor of the generated swap file descriptor.
Note
If aSwapFd is null, operate deleting on the setting file. If aSwapFd is not null, operate on the swap file, and aSwapFd will point to the swap file descriptor.
Return values
OT_ERROR_NONE The given key and index was found and removed successfully.
OT_ERROR_NOT_FOUND The given key or index was not found in the setting store.
References OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, OT_EXIT_FAILURE, OT_UNUSED_VARIABLE, PlatformSettingsGetSensitiveKeys(), sSettingsFd, swapDiscard(), swapOpen(), swapPersist(), swapWrite(), VerifyOrDie, and VerifyOrExit.
Referenced by otPlatSettingsDelete(), and PlatformSettingsSet().
PlatformSettingsGetSensitiveKeys()
void ot::Posix::PlatformSettingsGetSensitiveKeys (otInstance * aInstance, const uint16_t ** aKeys, uint16_t * aKeysLength)
This function gets the sensitive keys that should be stored in the secure area.
Parameters
[in] aInstance The OpenThread instance structure.
[out] aKeys A pointer to where the pointer to the array containing sensitive keys should be written.
[out] aKeysLength A pointer to where the count of sensitive keys should be written.
Referenced by PlatformSettingsDelete().
ExecuteCommand()
otError ExecuteCommand (const char * aFormat, ...)
This method formats a system command to execute.
Parameters
[in] aFormat A pointer to the format string.
[in] ... Arguments for the format specification.
Return values
OT_ERROR_NONE The command was executed successfully.
OT_ERROR_FAILED It failed to execute the command.
References kOutputBufferSize, kSystemCommandMaxLength, OT_ERROR_FAILED, OT_ERROR_NONE, otLogInfoPlat(), and VerifyOrExit.
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale