OpenThread: ot::Hdlc Namespace Reference
ot::Hdlc Namespace Reference
This namespace includes definitions for the HDLC-lite encoder and decoder.
Data Structures
class Decoder
class Encoder
class FrameBuffer
class FrameWritePointer
class MultiFrameBuffer
Enumerations
enum {
kFlagXOn = 0x11, kFlagXOff = 0x13, kFlagSequence = 0x7e, kEscapeSequence = 0x7d,
kFlagSpecial = 0xf8
}
enum { kInitFcs = 0xffff, kGoodFcs = 0xf0b8, kFcsSize = 2 }
Functions
static bool HdlcByteNeedsEscape (uint8_t aByte)
static uint16_t UpdateFcs (uint16_t aFcs, uint8_t aByte)
Detailed Description
This namespace includes definitions for the HDLC-lite encoder and decoder.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kFlagXOn
kFlagXOff
kFlagSequence
HDLC Flag value.
kEscapeSequence
HDLC Escape value.
kFlagSpecial
anonymous enum
anonymous enum
FCS lookup table
Enumerator
kInitFcs
Initial FCS value.
kGoodFcs
Good FCS value.
kFcsSize
FCS size (number of bytes).
Function Documentation
UpdateFcs()
uint16_t UpdateFcs (uint16_t aFcs, uint8_t aByte) static
This method updates an FCS.
Parameters
[in] aFcs The FCS to update.
[in] aByte The input byte value.
Returns
The updated FCS.
Referenced by Decoder::Decode(), and Encoder::Encode().
HdlcByteNeedsEscape()
static bool ot::Hdlc::HdlcByteNeedsEscape (uint8_t aByte) static
References kEscapeSequence, kFlagSequence, kFlagSpecial, kFlagXOff, and kFlagXOn.
Referenced by Encoder::Encode().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale