OpenThread: ot::Encoding Namespace Reference
ot::Encoding Namespace Reference
Namespaces
BigEndian
LittleEndian
Functions
uint32_t Reverse32 (uint32_t v)
uint16_t Swap16 (uint16_t v)
uint32_t Swap32 (uint32_t v)
uint64_t Swap64 (uint64_t v)
Function Documentation
Swap16()
uint16_t ot::Encoding::Swap16 (uint16_t v) inline
Referenced by ot::Encoding::BigEndian::HostSwap16().
Swap32()
uint32_t ot::Encoding::Swap32 (uint32_t v) inline
Referenced by ot::Encoding::BigEndian::HostSwap32().
Swap64()
uint64_t ot::Encoding::Swap64 (uint64_t v) inline
Referenced by ot::Encoding::BigEndian::HostSwap64().
Reverse32()
uint32_t ot::Encoding::Reverse32 (uint32_t v) inline
Referenced by ChannelMaskEntry::GetMask(), and ChannelMaskEntry::SetMask().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale