OpenThread: ot::Random::NonCrypto Namespace Reference
ot::Random::NonCrypto Namespace Reference
Functions
uint32_t AddJitter (uint32_t aValue, uint16_t aJitter)
void FillBuffer (uint8_t *aBuffer, uint16_t aSize)
uint16_t GetUint16 (void)
uint16_t GetUint16InRange (uint16_t aMin, uint16_t aMax)
uint32_t GetUint32 (void)
uint32_t GetUint32InRange (uint32_t aMin, uint32_t aMax)
uint8_t GetUint8 (void)
uint8_t GetUint8InRange (uint8_t aMin, uint8_t aMax)
Function Documentation
GetUint8InRange()
uint8_t GetUint8InRange (uint8_t aMin, uint8_t aMax)
This function generates and returns a random uint8_t value within a given range [aMin, aMax).
Parameters
[in] aMin A minimum value (this value can be included in returned random result).
[in] aMax A maximum value (this value is excluded from returned random result).
Returns
A random uint8_t value in the given range (i.e., aMin <= random value < aMax).
References GetUint8(), and OT_ASSERT.
Referenced by ChannelMask::ChooseRandomChannel(), GetUint16(), Mpl::HandleSeedSetTimer(), and otRandomNonCryptoGetUint8InRange().
GetUint16InRange()
uint16_t GetUint16InRange (uint16_t aMin, uint16_t aMax)
This function generates and returns a random uint16_t value within a given range [aMin, aMax).
Note
The returned random value can include the aMin value but excludes the aMax.
Parameters
[in] aMin A minimum value (this value can be included in returned random result).
[in] aMax A maximum value (this value is excluded from returned random result).
Returns
A random uint16_t value in the given range (i.e., aMin <= random value < aMax).
References GetUint16(), and OT_ASSERT.
Referenced by GetUint16(), Mle::HandleAdvertisement(), Mle::HandleLeaderData(), and otRandomNonCryptoGetUint16InRange().
GetUint32InRange()
uint32_t GetUint32InRange (uint32_t aMin, uint32_t aMax)
This function generates and returns a random uint32_t value within a given range [aMin, aMax).
Note
The returned random value can include the aMin value but excludes the aMax.
Parameters
[in] aMin A minimum value (this value can be included in returned random result).
[in] aMax A maximum value (this value is excluded from returned random result).
Returns
A random uint32_t value in the given range (i.e., aMin <= random value < aMax).
References GetUint32(), and OT_ASSERT.
Referenced by AddJitter(), Timestamp::AdvanceRandomTicks(), TxParameters::CalculateInitialRetransmissionTimeout(), Mle::CheckReachability(), Mle::GetAttachStartDelay(), GetUint16(), TrickleTimer::HandleTimer(), otRandomNonCryptoGetUint32InRange(), Mle::Reattach(), TimeTicker::RegisterReceiver(), AnnounceSenderBase::SendAnnounce(), TrickleTimer::Start(), TrickleTimer::StartNewInterval(), and SubMac::StartTimerForBackoff().
FillBuffer()
void FillBuffer (uint8_t * aBuffer, uint16_t aSize)
This function fills a given buffer with random bytes.
Parameters
[out] aBuffer A pointer to a buffer to fill with the random bytes.
[in] aSize Size of buffer (number of bytes to fill).
References GetUint8().
Referenced by otRandomNonCryptoFillBuffer().
AddJitter()
uint32_t AddJitter (uint32_t aValue, uint16_t aJitter)
This function adds a random jitter within a given range to a given value.
Parameters
[in] aValue A value to which the random jitter is added.
[in] aJitter Maximum jitter. Random jitter is selected from the range [-aJitter, aJitter].
Returns
The given value with an added random jitter.
References GetUint32InRange().
Referenced by Mle::GetAttachStartDelay(), GetUint16(), TimeTicker::HandleTimer(), AnnounceSenderBase::HandleTimer(), and otRandomNonCryptoAddJitter().
GetUint32()
uint32_t ot::Random::NonCrypto::GetUint32 (void) inline
This function generates and returns a random uint32_t value.
Returns
A random uint32_t value.
References Manager::NonCryptoGetUint32().
Referenced by GetUint16(), GetUint32InRange(), GetUint8(), Ip6::HandleOptions(), and otRandomNonCryptoGetUint32().
GetUint8()
uint8_t ot::Random::NonCrypto::GetUint8 (void) inline
This function generates and returns a random byte.
Returns
A random uint8_t value.
References GetUint32().
Referenced by FillBuffer(), GetUint8InRange(), otRandomNonCryptoGetUint8(), and LeaderBase::Reset().
GetUint16()
uint16_t ot::Random::NonCrypto::GetUint16 (void) inline
This function generates and returns a random uint16_t value.
Returns
A random uint16_t value.
References AddJitter(), ot::Random::Crypto::FillBuffer(), GetUint16InRange(), GetUint32(), GetUint32InRange(), and GetUint8InRange().
Referenced by ot::Mac::GenerateRandomPanId(), GetUint16InRange(), MeshForwarder::MeshForwarder(), and otRandomNonCryptoGetUint16().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale