OpenThread: ot::Random::Crypto Namespace Reference
ot::Random::Crypto Namespace Reference
Functions
Error FillBuffer (uint8_t *aBuffer, uint16_t aSize)
Function Documentation
FillBuffer()
Error ot::Random::Crypto::FillBuffer (uint8_t * aBuffer, uint16_t aSize) inline
This function fills a given buffer with cryptographically secure random bytes.
Parameters
[out] aBuffer A pointer to a buffer to fill with the random bytes.
[in] aSize Size of buffer (number of bytes to fill).
Return values
kErrorNone Successfully filled buffer with random values.
References Manager::CryptoFillBuffer().
Referenced by MbedTls::CryptoSecurePrng(), Neighbor::GenerateChallenge(), ExtAddress::GenerateRandom(), NetworkKey::GenerateRandom(), Pskc::GenerateRandom(), InterfaceIdentifier::GenerateRandom(), Dataset::Info::GenerateRandom(), Mle::Challenge::GenerateRandom(), Message::GenerateRandomToken(), NetworkPrefix::GenerateRandomUla(), ot::Random::NonCrypto::GetUint16(), Manager::Manager(), otRandomCryptoFillBuffer(), Header::SetRandomMessageId(), and Neighbor::StateToString().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale