OpenThread: ot::Encoding::LittleEndian Namespace Reference
ot::Encoding::LittleEndian Namespace Reference
Functions
template<typename UintType >
UintType HostSwap (UintType aValue)
template<>
uint8_t HostSwap (uint8_t aValue)
template<>
uint16_t HostSwap (uint16_t aValue)
template<>
uint32_t HostSwap (uint32_t aValue)
template<>
uint64_t HostSwap (uint64_t aValue)
uint16_t HostSwap16 (uint16_t v)
uint32_t HostSwap32 (uint32_t v)
uint64_t HostSwap64 (uint64_t v)
uint16_t ReadUint16 (const uint8_t *aBuffer)
uint32_t ReadUint24 (const uint8_t *aBuffer)
uint32_t ReadUint32 (const uint8_t *aBuffer)
uint64_t ReadUint64 (const uint8_t *aBuffer)
void WriteUint16 (uint16_t aValue, uint8_t *aBuffer)
void WriteUint24 (uint32_t aValue, uint8_t *aBuffer)
void WriteUint32 (uint32_t aValue, uint8_t *aBuffer)
void WriteUint64 (uint64_t aValue, uint8_t *aBuffer)
Function Documentation
HostSwap16()
uint16_t ot::Encoding::LittleEndian::HostSwap16 (uint16_t v) inline
Referenced by FrameBuilder::AppendLittleEndianUint16(), SettingsBase::NetworkInfo::GetRloc16(), SettingsBase::NetworkInfo::GetVersion(), SettingsBase::ParentInfo::GetVersion(), FrameData::ReadLittleEndianUint16(), SettingsBase::NetworkInfo::SetRloc16(), SettingsBase::NetworkInfo::SetVersion(), and SettingsBase::ParentInfo::SetVersion().
HostSwap32()
uint32_t ot::Encoding::LittleEndian::HostSwap32 (uint32_t v) inline
Referenced by FrameBuilder::AppendLittleEndianUint32(), Mle::SecurityHeader::GetFrameCounter(), SettingsBase::NetworkInfo::GetKeySequence(), SettingsBase::NetworkInfo::GetMacFrameCounter(), SettingsBase::NetworkInfo::GetMleFrameCounter(), SettingsBase::NetworkInfo::GetPreviousPartitionId(), FrameData::ReadLittleEndianUint32(), Mle::SecurityHeader::SetFrameCounter(), SettingsBase::NetworkInfo::SetKeySequence(), SettingsBase::NetworkInfo::SetMacFrameCounter(), SettingsBase::NetworkInfo::SetMleFrameCounter(), and SettingsBase::NetworkInfo::SetPreviousPartitionId().
HostSwap64()
uint64_t ot::Encoding::LittleEndian::HostSwap64 (uint64_t v) inline
References ot::Encoding::BigEndian::HostSwap().
HostSwap() [1/5]
UintType ot::Encoding::LittleEndian::HostSwap (UintType aValue)
This template function performs host swap on a given unsigned integer value assuming little-endian encoding.
Template Parameters
UintType The unsigned int type.
Parameters
aValue The value to host swap.
Returns
The host swapped value.
HostSwap() [2/5]
uint8_t ot::Encoding::LittleEndian::HostSwap (uint8_t aValue) inline
HostSwap() [3/5]
uint16_t ot::Encoding::LittleEndian::HostSwap (uint16_t aValue) inline
References ot::Encoding::BigEndian::HostSwap16().
HostSwap() [4/5]
uint32_t ot::Encoding::LittleEndian::HostSwap (uint32_t aValue) inline
References ot::Encoding::BigEndian::HostSwap32().
HostSwap() [5/5]
uint64_t ot::Encoding::LittleEndian::HostSwap (uint64_t aValue) inline
References ot::Encoding::BigEndian::HostSwap64().
ReadUint16()
uint16_t ot::Encoding::LittleEndian::ReadUint16 (const uint8_t * aBuffer) inline
This function reads a uint16_t value from a given buffer assuming little-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint16_t value read from buffer.
Referenced by SpiFrame::GetHeaderAcceptLen(), SpiFrame::GetHeaderDataLen(), MultiFrameBuffer< kMaxFrameSize >::GetNextSavedFrame(), and MultiFrameBuffer< kMaxFrameSize >::GetSkipLength().
ReadUint24()
uint32_t ot::Encoding::LittleEndian::ReadUint24 (const uint8_t * aBuffer) inline
This function reads a 24-bit integer value from a given buffer assuming little-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The value read from buffer.
ReadUint32()
uint32_t ot::Encoding::LittleEndian::ReadUint32 (const uint8_t * aBuffer) inline
This function reads a uint32_t value from a given buffer assuming little-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint32_t value read from buffer.
ReadUint64()
uint64_t ot::Encoding::LittleEndian::ReadUint64 (const uint8_t * aBuffer) inline
This function reads a uint64_t value from a given buffer assuming little-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint64_t value read from buffer.
WriteUint16()
void ot::Encoding::LittleEndian::WriteUint16 (uint16_t aValue, uint8_t * aBuffer) inline
This function writes a uint16_t value to a given buffer using little-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
Referenced by MultiFrameBuffer< kMaxFrameSize >::SaveFrame(), SpiFrame::SetHeaderAcceptLen(), SpiFrame::SetHeaderDataLen(), and MultiFrameBuffer< kMaxFrameSize >::SetSkipLength().
WriteUint24()
void ot::Encoding::LittleEndian::WriteUint24 (uint32_t aValue, uint8_t * aBuffer) inline
This function writes a 24-bit integer value to a given buffer using little-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
WriteUint32()
void ot::Encoding::LittleEndian::WriteUint32 (uint32_t aValue, uint8_t * aBuffer) inline
This function writes a uint32_t value to a given buffer using little-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
WriteUint64()
void ot::Encoding::LittleEndian::WriteUint64 (uint64_t aValue, uint8_t * aBuffer) inline
This function writes a uint64_t value to a given buffer using little-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale