OpenThread: ot::Cli Namespace Reference
ot::Cli Namespace Reference
This namespace contains definitions for the CLI interpreter.
Data Structures
class Dataset
class Interpreter
class NetworkData
class Output
class OutputBase
class OutputWrapper
class TcpExample
class UdpExample
Typedefs
typedef uint64_t CommandId
Functions
static constexpr CommandId Cmd (const char *aString)
static OT_DEFINE_ALIGNED_VAR (sInterpreterRaw, sizeof(Interpreter), uint64_t)
void otCliAppendResult (otError aError)
void otCliInit (otInstance *aInstance, otCliOutputCallback aCallback, void *aContext)
void otCliInputLine (char *aBuf)
void otCliOutputBytes (const uint8_t *aBytes, uint8_t aLength)
void otCliOutputFormat (const char *aFmt,...)
void otCliPlatLogv (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat, va_list aArgs)
void otCliSetUserCommands (const otCliCommand *aUserCommands, uint8_t aLength, void *aContext)
Detailed Description
This namespace contains definitions for the CLI interpreter.
Typedef Documentation
CommandId
typedef uint64_t CommandId
This type represents a ID number value associated with a CLI command string.
Function Documentation
OT_DEFINE_ALIGNED_VAR()
static ot::Cli::OT_DEFINE_ALIGNED_VAR (sInterpreterRaw , sizeof(Interpreter) , uint64_t) static
Cmd()
static constexpr CommandId ot::Cli::Cmd (const char * aString) static
This constexpr function converts a CLI command string to its associated CommandId value.
Parameters
[in] aString The CLI command string.
Returns
The associated CommandId with aString.
Referenced by Interpreter::LinkModeToString(), NetworkData::OutputService(), Dataset::Process(), and Interpreter::SetUserCommands().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale