OpenThread: ot::Encoding::BigEndian Namespace Reference
ot::Encoding::BigEndian Namespace Reference
Functions
template<typename UintType >
UintType HostSwap (UintType aValue)
template<>
uint8_t HostSwap (uint8_t aValue)
template<>
uint16_t HostSwap (uint16_t aValue)
template<>
uint32_t HostSwap (uint32_t aValue)
template<>
uint64_t HostSwap (uint64_t aValue)
uint16_t HostSwap16 (uint16_t v)
uint32_t HostSwap32 (uint32_t v)
uint64_t HostSwap64 (uint64_t v)
uint16_t ReadUint16 (const uint8_t *aBuffer)
uint32_t ReadUint24 (const uint8_t *aBuffer)
uint32_t ReadUint32 (const uint8_t *aBuffer)
uint64_t ReadUint64 (const uint8_t *aBuffer)
void WriteUint16 (uint16_t aValue, uint8_t *aBuffer)
void WriteUint24 (uint32_t aValue, uint8_t *aBuffer)
void WriteUint32 (uint32_t aValue, uint8_t *aBuffer)
void WriteUint64 (uint64_t aValue, uint8_t *aBuffer)
Function Documentation
HostSwap16()
uint16_t ot::Encoding::BigEndian::HostSwap16 (uint16_t v) inline
References ot::Encoding::Swap16().
Referenced by FrameBuilder::AppendBigEndianUint16(), Address::AppendHexWords(), Name::AppendPointerLabel(), FragmentHeader::ClearMoreFlag(), Lowpan::Compress(), Lowpan::Decompress(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressEcn(), Address::FromString(), Header::GetAdditionalRecordCount(), Header::GetAnswerCount(), Timestamp::GetAuthoritative(), Header::GetAuthorityRecordCount(), BorderAgentLocatorTlv::GetBorderAgentLocator(), VendorStackVersionTlv::GetBuild(), ChannelTlv::GetChannel(), Icmp::Header::GetChecksum(), Header::GetChecksum(), Udp::Header::GetChecksum(), Tcp::Header::GetChecksum(), ChildTableEntry::GetChildId(), ResourceRecord::GetClass(), Question::GetClass(), CommissionerSessionIdTlv::GetCommissionerSessionId(), Udp::Header::GetDestinationPort(), Tcp::Header::GetDestinationPort(), UdpEncapsulationTlv::GetDestinationPort(), Header::GetDf(), Header::GetDscp(), Tcp::Header::GetFlags(), BorderRouterEntry::GetFlags(), Header::GetFragmentOffset(), HeaderIe::GetId(), Icmp::Header::GetId(), Header::GetIdentification(), SigRecord::GetKeyTag(), Udp::Header::GetLength(), ExtendedTlv::GetLength(), ResourceRecord::GetLength(), InterfaceIdentifier::GetLocator(), Header::GetMessageId(), Message::GetMessageId(), Header::GetMf(), Name::LabelIterator::GetNextLabel(), FragmentHeader::GetOffset(), Option::GetOptionCode(), Option::GetOptionLength(), PanIdTlv::GetPanId(), Header::GetPayloadLength(), CslIe::GetPeriod(), CslIe::GetPhase(), DnsSrpUnicast::ServiceData::GetPort(), DnsSrpUnicast::ServerData::GetPort(), SrvRecord::GetPort(), SrvRecord::GetPriority(), Header::GetQuestionCount(), BackboneRouter::ServerData::GetReregistrationDelay(), ChildTableEntry::GetReserved(), VendorStackVersionTlv::GetRevision(), HasRouteEntry::GetRloc(), BorderRouterEntry::GetRloc(), SecurityPolicyTlv::GetRotationTime(), RouterAdvertMessage::Header::GetRouterLifetime(), Timestamp::GetSeconds(), ConnectivityTlv::GetSedBufferSize(), OptionMpl::GetSeedId(), Icmp::Header::GetSequence(), ServerTlv::GetServer16(), Udp::Header::GetSourcePort(), Tcp::Header::GetSourcePort(), UdpEncapsulationTlv::GetSourcePort(), Prefix::GetSubnetId(), Timestamp::GetTicks(), ChildTableEntry::GetTimeout(), Header::GetTotalLength(), Header::GetTrafficClass(), ResourceRecord::GetType(), Question::GetType(), SigRecord::GetTypeCovered(), JoinerUdpPortTlv::GetUdpPort(), Tcp::Header::GetUrgentPointer(), SrvRecord::GetWeight(), Tcp::Header::GetWindow(), Ip6::HandleDatagram(), HostSwap(), ot::Encoding::LittleEndian::HostSwap(), FragmentHeader::FirstFrag::Init(), FragmentHeader::NextFrag::Init(), Beacon::Init(), BorderRouterEntry::IsConfigure(), BorderRouterEntry::IsDefaultRoute(), BorderRouterEntry::IsDhcp(), BorderRouterEntry::IsDp(), Prefix::IsLinkLocal(), Address::IsLinkLocal(), InterfaceIdentifier::IsLocator(), FragmentHeader::IsMoreFlagSet(), BorderRouterEntry::IsNdDns(), BorderRouterEntry::IsOnMesh(), BorderRouterEntry::IsPreferred(), InterfaceIdentifier::IsReservedSubnetAnycast(), BorderRouterEntry::IsSlaac(), Beacon::IsValid(), ResourceRecord::Matches(), Mle::Mle(), Mpl::ProcessOption(), FrameData::ReadBigEndianUint16(), Option::Iterator::ReadExtendedOptionField(), Header::SetAdditionalRecordCount(), Header::SetAnswerCount(), Timestamp::SetAuthoritative(), Header::SetAuthorityRecordCount(), BorderAgentLocatorTlv::SetBorderAgentLocator(), VendorStackVersionTlv::SetBuild(), ChannelTlv::SetChannel(), Icmp::Header::SetChecksum(), Header::SetChecksum(), Udp::Header::SetChecksum(), RouterAdvertMessage::Header::SetChecksum(), ChildTableEntry::SetChildId(), ResourceRecord::SetClass(), Question::SetClass(), CommissionerSessionIdTlv::SetCommissionerSessionId(), Udp::Header::SetDestinationPort(), UdpEncapsulationTlv::SetDestinationPort(), Header::SetDscp(), BorderRouterEntry::SetFlags(), HeaderIe::SetId(), Icmp::Header::SetId(), Header::SetIdentification(), SigRecord::SetKeyTag(), Udp::Header::SetLength(), ExtendedTlv::SetLength(), ResourceRecord::SetLength(), InterfaceIdentifier::SetLocator(), Header::SetMessageId(), Message::SetMessageId(), FragmentHeader::SetMoreFlag(), FragmentHeader::SetOffset(), Option::SetOptionCode(), Option::SetOptionLength(), PanIdTlv::SetPanId(), Header::SetPayloadLength(), CslIe::SetPeriod(), CslIe::SetPhase(), SrvRecord::SetPort(), SrvRecord::SetPriority(), Header::SetQuestionCount(), BackboneRouter::ServerData::SetReregistrationDelay(), ChildTableEntry::SetReserved(), VendorStackVersionTlv::SetRevision(), HasRouteEntry::SetRloc(), BorderRouterEntry::SetRloc(), SecurityPolicyTlv::SetRotationTime(), RouterAdvertMessage::Header::SetRouterLifetime(), Timestamp::SetSeconds(), ConnectivityTlv::SetSedBufferSize(), OptionMpl::SetSeedId(), Icmp::Header::SetSequence(), ServerTlv::SetServer16(), Udp::Header::SetSourcePort(), UdpEncapsulationTlv::SetSourcePort(), Prefix::SetSubnetId(), Timestamp::SetTicks(), ChildTableEntry::SetTimeout(), Dataset::SetTlv(), InterfaceIdentifier::SetToLocator(), Header::SetTotalLength(), Header::SetTrafficClass(), ResourceRecord::SetType(), Question::SetType(), SigRecord::SetTypeCovered(), JoinerUdpPortTlv::SetUdpPort(), SrvRecord::SetWeight(), and Checksum::WriteToMessage().
HostSwap32()
uint32_t ot::Encoding::BigEndian::HostSwap32 (uint32_t v) inline
References ot::Encoding::Swap32().
Referenced by FrameBuilder::AppendBigEndianUint32(), LeaderDataTlv::Get(), Tcp::Header::GetAcknowledgmentNumber(), DelayTimerTlv::GetDelayTimer(), ServiceTlv::GetEnterpriseNumber(), SigRecord::GetExpiration(), Header::GetFlow(), MacCountersTlv::GetIfInBroadcastPkts(), MacCountersTlv::GetIfInDiscards(), MacCountersTlv::GetIfInErrors(), MacCountersTlv::GetIfInUcastPkts(), MacCountersTlv::GetIfInUnknownProtos(), MacCountersTlv::GetIfOutBroadcastPkts(), MacCountersTlv::GetIfOutDiscards(), MacCountersTlv::GetIfOutErrors(), MacCountersTlv::GetIfOutUcastPkts(), SigRecord::GetInception(), Mle::SecurityHeader::GetKeyId(), LeaseOption::GetKeyLeaseInterval(), LeaseOption::GetLeaseInterval(), ChannelMaskEntry::GetMask(), BackboneRouter::ServerData::GetMlrTimeout(), NetworkKeySequenceTlv::GetNetworkKeySequence(), SigRecord::GetOriginalTtl(), LeaderDataTlv::GetPartitionId(), PrefixInfoOption::GetPreferredLifetime(), RouteInfoOption::GetRouteLifetime(), Timestamp::GetSeconds(), Tcp::Header::GetSequenceNumber(), ResourceRecord::GetTtl(), PrefixInfoOption::GetValidLifetime(), Header::GetVerionTrafficClassFlow(), Cidr::HostMask(), HostSwap(), ot::Encoding::LittleEndian::HostSwap(), ServiceTlv::Init(), InterfaceIdentifier::IsLocator(), Address::IsLoopback(), InterfaceIdentifier::IsReservedSubnetAnycast(), FrameData::ReadBigEndianUint32(), LeaderDataTlv::Set(), DelayTimerTlv::SetDelayTimer(), SigRecord::SetExpiration(), Header::SetFlow(), MacCountersTlv::SetIfInBroadcastPkts(), MacCountersTlv::SetIfInDiscards(), MacCountersTlv::SetIfInErrors(), MacCountersTlv::SetIfInUcastPkts(), MacCountersTlv::SetIfInUnknownProtos(), MacCountersTlv::SetIfOutBroadcastPkts(), MacCountersTlv::SetIfOutDiscards(), MacCountersTlv::SetIfOutErrors(), MacCountersTlv::SetIfOutUcastPkts(), SigRecord::SetInception(), Mle::SecurityHeader::SetKeyId(), LeaseOption::SetKeyLeaseInterval(), LeaseOption::SetLeaseInterval(), ChannelMaskEntry::SetMask(), BackboneRouter::ServerData::SetMlrTimeout(), NetworkKeySequenceTlv::SetNetworkKeySequence(), SigRecord::SetOriginalTtl(), LeaderDataTlv::SetPartitionId(), PrefixInfoOption::SetPreferredLifetime(), RouteInfoOption::SetRouteLifetime(), Timestamp::SetSeconds(), Dataset::SetTlv(), Address::SetToLinkLocalAddress(), InterfaceIdentifier::SetToLocator(), ResourceRecord::SetTtl(), PrefixInfoOption::SetValidLifetime(), Header::SetVerionTrafficClassFlow(), and Address::SynthesizeFromCidrAndHost().
HostSwap64()
uint64_t ot::Encoding::BigEndian::HostSwap64 (uint64_t v) inline
References HostSwap(), and ot::Encoding::Swap64().
Referenced by getSettingsFileName(), HostSwap(), and ot::Encoding::LittleEndian::HostSwap().
HostSwap() [1/5]
UintType ot::Encoding::BigEndian::HostSwap (UintType aValue)
This template function performs host swap on a given unsigned integer value assuming big-endian encoding.
Template Parameters
UintType The unsigned int type.
Parameters
aValue The value to host swap.
Returns
The host swapped value.
Referenced by HostSwap64(), and ot::Encoding::LittleEndian::HostSwap64().
HostSwap() [2/5]
uint8_t ot::Encoding::BigEndian::HostSwap (uint8_t aValue) inline
HostSwap() [3/5]
uint16_t ot::Encoding::BigEndian::HostSwap (uint16_t aValue) inline
References HostSwap16().
HostSwap() [4/5]
uint32_t ot::Encoding::BigEndian::HostSwap (uint32_t aValue) inline
References HostSwap32().
HostSwap() [5/5]
uint64_t ot::Encoding::BigEndian::HostSwap (uint64_t aValue) inline
References HostSwap64().
ReadUint16()
uint16_t ot::Encoding::BigEndian::ReadUint16 (const uint8_t * aBuffer) inline
This function reads a uint16_t value from a given buffer assuming big-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint16_t value read from buffer.
Referenced by Frame::GetDstAddr(), Frame::GetDstPanId(), Frame::GetFrameControlField(), Manager::GetNextDnsSrpUnicastInfo(), Frame::GetSrcAddr(), Frame::GetSrcPanId(), MeshHeader::ParseFrom(), and FragmentHeader::ParseFrom().
ReadUint32()
uint32_t ot::Encoding::BigEndian::ReadUint32 (const uint8_t * aBuffer) inline
This function reads a uint32_t value from a given buffer assuming big-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint32_t value read from buffer.
Referenced by Frame::GetFrameCounter().
ReadUint24()
uint32_t ot::Encoding::BigEndian::ReadUint24 (const uint8_t * aBuffer) inline
This function reads a 24-bit integer value from a given buffer assuming big-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The value read from buffer.
Referenced by VendorStackVersionTlv::GetOui(), and JoinerAdvertisementTlv::GetOui().
ReadUint64()
uint64_t ot::Encoding::BigEndian::ReadUint64 (const uint8_t * aBuffer) inline
This function reads a uint64_t value from a given buffer assuming big-endian encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint64_t value read from buffer.
Referenced by JoinerDiscerner::Matches().
WriteUint16()
void ot::Encoding::BigEndian::WriteUint16 (uint16_t aValue, uint8_t * aBuffer) inline
This function writes a uint16_t value to a given buffer using big-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
Referenced by TxFrame::GenerateEnhAck(), TxFrame::GenerateImmAck(), Frame::InitMacHeader(), Frame::SetDstAddr(), Frame::SetDstPanId(), Frame::SetSrcAddr(), Frame::SetSrcPanId(), and Message::WriteExtendedOptionField().
WriteUint24()
void ot::Encoding::BigEndian::WriteUint24 (uint32_t aValue, uint8_t * aBuffer) inline
This function writes a 24-bit integer value to a given buffer using big-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
Referenced by VendorStackVersionTlv::SetOui(), and JoinerAdvertisementTlv::SetOui().
WriteUint32()
void ot::Encoding::BigEndian::WriteUint32 (uint32_t aValue, uint8_t * aBuffer) inline
This function writes a uint32_t value to a given buffer using big-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
Referenced by Message::AppendUintOption(), KeyManager::ComputeKeys(), AesCcm::GenerateNonce(), and Frame::SetFrameCounter().
WriteUint64()
void ot::Encoding::BigEndian::WriteUint64 (uint64_t aValue, uint8_t * aBuffer) inline
This function writes a uint64_t value to a given buffer using big-endian encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale