OpenThread: ot::Spinel Namespace Reference
ot::Spinel Namespace Reference
Data Structures
class Buffer
class Decoder
class Encoder
class RadioSpinel
class SpinelInterface
Functions
static void LogIfFail (const char *aText, otError aError)
static otError SpinelStatusToOtError (spinel_status_t aError)
Function Documentation
SpinelStatusToOtError()
static otError ot::Spinel::SpinelStatusToOtError (spinel_status_t aError) inline static
References OT_ERROR_ALREADY, OT_ERROR_BUSY, OT_ERROR_CHANNEL_ACCESS_FAILURE, OT_ERROR_DROP, OT_ERROR_FAILED, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_STATE, OT_ERROR_NO_ACK, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_NOT_IMPLEMENTED, OT_ERROR_PARSE, SPINEL_STATUS_ALREADY, SPINEL_STATUS_BUSY, SPINEL_STATUS_CCA_FAILURE, SPINEL_STATUS_DROPPED, SPINEL_STATUS_FAILURE, SPINEL_STATUS_INVALID_ARGUMENT, SPINEL_STATUS_INVALID_STATE, SPINEL_STATUS_ITEM_NOT_FOUND, SPINEL_STATUS_NO_ACK, SPINEL_STATUS_NOMEM, SPINEL_STATUS_OK, SPINEL_STATUS_PARSE_ERROR, SPINEL_STATUS_PROP_NOT_FOUND, SPINEL_STATUS_STACK_NATIVE__BEGIN, SPINEL_STATUS_STACK_NATIVE__END, and SPINEL_STATUS_UNIMPLEMENTED.
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), and RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse().
LogIfFail()
static void ot::Spinel::LogIfFail (const char * aText, otError aError) inline static
References OT_ERROR_NO_ACK, OT_ERROR_NONE, OT_UNUSED_VARIABLE, otLogWarnPlat(), and otThreadErrorToString().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), RadioSpinel< InterfaceType, ProcessContextType >::GetCcaEnergyDetectThreshold(), RadioSpinel< InterfaceType, ProcessContextType >::GetFemLnaGain(), RadioSpinel< InterfaceType, ProcessContextType >::GetRadioChannelMask(), RadioSpinel< InterfaceType, ProcessContextType >::GetRadioRegion(), RadioSpinel< InterfaceType, ProcessContextType >::GetRssi(), RadioSpinel< InterfaceType, ProcessContextType >::GetTransmitPower(), RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::ParseRadioFrame(), RadioSpinel< InterfaceType, ProcessContextType >::SetCcaEnergyDetectThreshold(), RadioSpinel< InterfaceType, ProcessContextType >::SetFemLnaGain(), RadioSpinel< InterfaceType, ProcessContextType >::SetTransmitPower(), and RadioSpinel< InterfaceType, ProcessContextType >::WaitResponse().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale