OpenThread: openthread-system.h File Reference
openthread-system.h File Reference
Detailed Description
This file defines the platform-specific functions needed by OpenThread's example applications.
#include <setjmp.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/select.h>
#include <openthread/error.h>
#include <openthread/instance.h>
#include <openthread/platform/misc.h>
#include "lib/spinel/radio_spinel_metrics.h"
Data Structures
struct otPlatformConfig
struct otRcpInterfaceMetrics
struct otSysMainloopContext
Typedefs
typedef struct otPlatformConfig otPlatformConfig
typedef struct otRcpInterfaceMetrics otRcpInterfaceMetrics
typedef struct otSysMainloopContext otSysMainloopContext
Enumerations
enum {
OT_PLATFORM_CONFIG_SPI_DEFAULT_MODE = 0, OT_PLATFORM_CONFIG_SPI_DEFAULT_SPEED_HZ = 1000000, OT_PLATFORM_CONFIG_SPI_DEFAULT_CS_DELAY_US = 20, OT_PLATFORM_CONFIG_SPI_DEFAULT_RESET_DELAY_MS = 0,
OT_PLATFORM_CONFIG_SPI_DEFAULT_ALIGN_ALLOWANCE, OT_PLATFORM_CONFIG_SPI_DEFAULT_SMALL_PACKET_SIZE, OT_PLATFORM_CONFIG_MAX_RADIO_URLS = 2
}
Functions
void otSysDeinit (void)
const char * otSysGetInfraNetifName (void)
const otRadioSpinelMetrics * otSysGetRadioSpinelMetrics (void)
const char * otSysGetRadioUrlHelpString (void)
const otRcpInterfaceMetrics * otSysGetRcpInterfaceMetrics (void)
unsigned int otSysGetThreadNetifIndex (void)
const char * otSysGetThreadNetifName (void)
otInstance * otSysInit (otPlatformConfig *aPlatformConfig)
int otSysMainloopPoll (otSysMainloopContext *aMainloop)
void otSysMainloopProcess (otInstance *aInstance, const otSysMainloopContext *aMainloop)
void otSysMainloopUpdate (otInstance *aInstance, otSysMainloopContext *aMainloop)
Variables
otPlatResetReason gPlatResetReason
Typedef Documentation
otPlatformConfig
typedef struct otPlatformConfig otPlatformConfig
This structure represents platform specific configurations.
otRcpInterfaceMetrics
typedef struct otRcpInterfaceMetrics otRcpInterfaceMetrics
This structure represents RCP interface metrics.
otSysMainloopContext
typedef struct otSysMainloopContext otSysMainloopContext
This structure represents a context for a select() based mainloop.
Enumeration Type Documentation
anonymous enum
anonymous enum
This enumeration represents default parameters for the SPI interface.
Enumerator
OT_PLATFORM_CONFIG_SPI_DEFAULT_MODE
Default SPI Mode: CPOL=0, CPHA=0.
OT_PLATFORM_CONFIG_SPI_DEFAULT_SPEED_HZ
Default SPI speed in hertz.
OT_PLATFORM_CONFIG_SPI_DEFAULT_CS_DELAY_US
Default delay after SPI C̅S̅ assertion, in µsec.
OT_PLATFORM_CONFIG_SPI_DEFAULT_RESET_DELAY_MS
Default delay after R̅E̅S̅E̅T̅ assertion, in miliseconds.
OT_PLATFORM_CONFIG_SPI_DEFAULT_ALIGN_ALLOWANCE
Default maximum number of 0xFF bytes to clip from start of MISO frame.
OT_PLATFORM_CONFIG_SPI_DEFAULT_SMALL_PACKET_SIZE
Default smallest SPI packet size we can receive in a single transaction.
OT_PLATFORM_CONFIG_MAX_RADIO_URLS
Max number of Radio URLs.
Function Documentation
otSysInit()
otInstance* otSysInit (otPlatformConfig * aPlatformConfig)
This function performs all platform-specific initialization of OpenThread's drivers and initializes the OpenThread instance.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function when initialization of OpenThread's drivers is most appropriate.
Parameters
[in] aPlatformConfig Platform configuration structure.
Returns
A pointer to the OpenThread instance.
References gDryRun, gInstance, otPlatformConfig::mDryRun, OT_ASSERT, otInstanceInitSingle(), platformInit(), and platformSetUp().
Referenced by InitInstance().
otSysDeinit()
void otSysDeinit (void)
This function finalizes the OpenThread instance and performs all platform-specific deinitialization for OpenThread's drivers.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function when deinitialization of OpenThread's drivers is most appropriate.
References OT_ASSERT, otInstanceFinalize(), platformDeinit(), and platformTearDown().
Referenced by main(), and otPlatReset().
otSysMainloopUpdate()
void otSysMainloopUpdate (otInstance * aInstance, otSysMainloopContext * aMainloop)
This function updates the file descriptor sets with file descriptors used by OpenThread drivers.
Parameters
[in] aInstance The OpenThread instance structure.
[in,out] aMainloop A pointer to the mainloop context.
References Manager::Get(), otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mTimeout, otSysMainloopContext::mWriteFdSet, otTaskletsArePending(), platformAlarmUpdateTimeout(), platformNetifUpdateFdSet(), platformRadioUpdateFdSet(), platformTrelUpdateFdSet(), Manager::Update(), and virtualTimeUpdateFdSet().
Referenced by main().
otSysMainloopPoll()
int otSysMainloopPoll (otSysMainloopContext * aMainloop)
This function polls OpenThread's mainloop.
Parameters
[in,out] aMainloop A pointer to the mainloop context.
Returns
value returned from select().
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mTimeout, otSysMainloopContext::mWriteFdSet, and virtualTimeSendSleepEvent().
Referenced by main().
otSysMainloopProcess()
void otSysMainloopProcess (otInstance * aInstance, const otSysMainloopContext * aMainloop)
This function performs all platform-specific processing for OpenThread's example applications.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function in the main loop when processing OpenThread's drivers is most appropriate.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aMainloop A pointer to the mainloop context.
References Manager::Get(), otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mWriteFdSet, platformAlarmProcess(), platformNetifProcess(), platformRadioProcess(), platformTrelProcess(), Manager::Process(), and virtualTimeProcess().
Referenced by main().
otSysGetRadioUrlHelpString()
const char* otSysGetRadioUrlHelpString (void)
This method returns the radio url help string.
Returns
the radio url help string.
References OT_RADIO_URL_HELP_BUS, and OT_RADIO_URL_HELP_MAX_POWER_TABLE.
Referenced by PrintUsage().
otSysGetThreadNetifName()
const char* otSysGetThreadNetifName (void)
This method returns the Thread network interface name.
Returns
The Thread network interface name.
References gNetifName.
Referenced by InitInstance(), platformInit(), and ProcessNetif().
otSysGetThreadNetifIndex()
unsigned int otSysGetThreadNetifIndex (void)
This method returns the Thread network interface index.
Returns
The Thread network interface index.
References Ip6AddressString::AsCString(), String< kSize >::AsCString(), Clearable< Type >::Clear(), DieNow, EINVAL, ExitNow, gInstance, gNetifIndex, gNetifName, Address::IsMulticast(), Address::kLinkLocalScope, kSocketNonBlock, otIp4Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp4Cidr::mAddress, otNetifAddress::mAddress, otNetifMulticastAddress::mAddress, otIp6AddressInfo::mAddress, otIp4Address::mFields, otIp6Address::mFields, otIp4Cidr::mLength, otIp6Prefix::mLength, otMessageSettings::mLinkSecurityEnabled, otNetifAddress::mNext, otIp6AddressInfo::mPreferred, otBorderRouterConfig::mPrefix, otExternalRouteConfig::mPrefix, otIp6Prefix::mPrefix, otNetifAddress::mPrefixLength, otIp6AddressInfo::mPrefixLength, otMessageSettings::mPriority, otExternalRouteConfig::mRloc16, otIp6AddressInfo::mScope, OPENTHREAD_CONFIG_IP6_MAX_DATAGRAM_LENGTH, OPENTHREAD_POSIX_CONFIG_EXTERNAL_ROUTE_PRIORITY, OPENTHREAD_POSIX_CONFIG_MAX_EXTERNAL_ROUTE_NUM, OPENTHREAD_POSIX_CONFIG_MAX_OMR_ROUTES_NUM, OPENTHREAD_POSIX_CONFIG_NETIF_PREFIX_ROUTE_METRIC, OPENTHREAD_POSIX_CONFIG_OMR_ROUTES_PRIORITY, OT_ASSERT, OT_CHANGED_THREAD_NETDATA, OT_CHANGED_THREAD_NETIF_STATE, OT_DEVICE_ROLE_DISABLED, OT_ERROR_ALREADY, OT_ERROR_BUSY, OT_ERROR_DROP, OT_ERROR_FAILED, OT_ERROR_INVALID_STATE, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_REJECTED, OT_EXIT_ERROR_ERRNO, OT_EXIT_FAILURE, OT_EXIT_INVALID_ARGUMENTS, OT_ICMP6_ECHO_HANDLER_ALL, OT_ICMP6_ECHO_HANDLER_DISABLED, OT_IP6_ADDRESS_STRING_SIZE, OT_IP6_PREFIX_STRING_SIZE, OT_MESSAGE_PRIORITY_LOW, OT_NETWORK_DATA_ITERATOR_INIT, OT_TOOL_PACKED_BEGIN, OT_TOOL_PACKED_END, OT_UNUSED_VARIABLE, otDumpInfoPlat(), otIcmp6SetEchoMode(), otIp4NewMessage(), otIp6AddressToString(), otIp6AddUnicastAddress(), otIp6ArePrefixesEqual(), otIp6GetUnicastAddresses(), otIp6IsEnabled(), otIp6NewMessage(), otIp6PrefixMatch(), otIp6PrefixToString(), otIp6RemoveUnicastAddress(), otIp6Send(), otIp6SetAddressCallback(), otIp6SetEnabled(), otIp6SetMulticastPromiscuousEnabled(), otIp6SetReceiveCallback(), otIp6SetReceiveFilterEnabled(), otIp6SubscribeMulticastAddress(), otIp6UnsubscribeMulticastAddress(), otLogDebgPlat(), otLogInfoPlat(), otLogNotePlat(), otLogWarnPlat(), otMessageAppend(), otMessageFree(), otMessageGetLength(), otMessageRead(), otNat64Send(), otNat64SetIp4Cidr(), otNat64SetReceiveIp4Callback(), otNetDataContainsOmrPrefix(), otNetDataGetNextOnMeshPrefix(), otNetDataGetNextRoute(), otThreadErrorToString(), otThreadGetDeviceRole(), otThreadGetRloc16(), platformNetifDeinit(), platformNetifInit(), platformNetifProcess(), platformNetifSetUp(), platformNetifStateChange(), platformNetifTearDown(), platformNetifUpdateFdSet(), Address::SetPrefix(), SocketWithCloseExec(), SuccessOrDie, SuccessOrExit, Address::ToString(), VerifyOrDie, and VerifyOrExit.
Referenced by ProcessNetif().
otSysGetInfraNetifName()
const char* otSysGetInfraNetifName (void)
This method returns the infrastructure network interface name.
Returns
The infrastructure network interface name, or nullptr if not specified.
otSysGetRadioSpinelMetrics()
const otRadioSpinelMetrics* otSysGetRadioSpinelMetrics (void)
This method returns the radio spinel metrics.
Returns
The radio spinel metrics.
References RadioSpinel< InterfaceType, ProcessContextType >::GetRadioSpinelMetrics().
otSysGetRcpInterfaceMetrics()
const otRcpInterfaceMetrics* otSysGetRcpInterfaceMetrics (void)
This method returns the RCP interface metrics.
Returns
The RCP interface metrics.
References RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface().
Variable Documentation
gPlatResetReason
otPlatResetReason gPlatResetReason
Referenced by otPlatGetResetReason(), and otPlatReset().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale