OpenThread: platform-posix.h File Reference
platform-posix.h File Reference
Detailed Description
This file includes the platform-specific initializers.
#include "openthread-posix-config.h"
#include <errno.h>
#include <net/if.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/select.h>
#include <sys/time.h>
#include <openthread/error.h>
#include <openthread/instance.h>
#include <openthread/ip6.h>
#include <openthread/logging.h>
#include <openthread/nat64.h>
#include <openthread/openthread-system.h>
#include <openthread/platform/time.h>
#include "lib/platform/exit_code.h"
#include "lib/url/url.hpp"
Data Structures
struct RadioProcessContext
struct VirtualTimeEvent
Macros
#define MS_PER_S 1000
#define NS_PER_US 1000
#define OPENTHREAD_POSIX_DAEMON_SOCKET_NAME OPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME ".sock"
#define OPENTHREAD_POSIX_VIRTUAL_TIME 0
#define US_PER_MS 1000
#define US_PER_S (MS_PER_S * US_PER_MS)
Enumerations
enum {
OT_SIM_EVENT_ALARM_FIRED = 0, OT_SIM_EVENT_RADIO_RECEIVED = 1, OT_SIM_EVENT_UART_WRITE = 2, OT_SIM_EVENT_RADIO_SPINEL_WRITE = 3,
OT_EVENT_DATA_MAX_SIZE = 1024
}
enum SocketBlockOption { kSocketBlock, kSocketNonBlock }
Functions
void platformAlarmAdvanceNow (uint64_t aDelta)
int32_t platformAlarmGetNext (void)
void platformAlarmInit (uint32_t aSpeedUpFactor, int aRealTimeSignal)
void platformAlarmProcess (otInstance *aInstance)
void platformAlarmUpdateTimeout (struct timeval *tv)
void platformBackboneDeinit (void)
void platformBackboneInit (const char *aInterfaceName)
void platformBackboneSetUp (void)
void platformBackboneStateChange (otInstance *aInstance, otChangedFlags aFlags)
void platformBackboneTearDown (void)
bool platformInfraIfIsRunning (void)
void platformLoggingInit (const char *aName)
void platformNetifDeinit (void)
void platformNetifInit (const char *aInterfaceName)
void platformNetifProcess (const fd_set *aReadFdSet, const fd_set *aWriteFdSet, const fd_set *aErrorFdSet)
void platformNetifSetUp (void)
void platformNetifStateChange (otInstance *aInstance, otChangedFlags aFlags)
void platformNetifTearDown (void)
void platformNetifUpdateFdSet (fd_set *aReadFdSet, fd_set *aWriteFdSet, fd_set *aErrorFdSet, int *aMaxFd)
void platformRadioDeinit (void)
void platformRadioInit (const char *aUrl)
void platformRadioProcess (otInstance *aInstance, const fd_set *aReadFdSet, const fd_set *aWriteFdSet)
void platformRadioReceive (otInstance *aInstance, uint8_t *aBuf, uint16_t aBufLength)
void platformRadioUpdateFdSet (fd_set *aReadFdSet, fd_set *aWriteFdSet, int *aMaxFd, struct timeval *aTimeout)
void platformRandomInit (void)
void platformTrelDeinit (void)
void platformTrelInit (const char *aTrelUrl)
void platformTrelProcess (otInstance *aInstance, const fd_set *aReadFdSet, const fd_set *aWriteFdSet)
void platformTrelUpdateFdSet (fd_set *aReadFdSet, fd_set *aWriteFdSet, int *aMaxFd, struct timeval *aTimeout)
void platformUartProcess (const fd_set *aReadFdSet, const fd_set *aWriteFdSet, const fd_set *aErrorFdSet)
void platformUartUpdateFdSet (fd_set *aReadFdSet, fd_set *aWriteFdSet, fd_set *aErrorFdSet, int *aMaxFd)
int SocketWithCloseExec (int aDomain, int aType, int aProtocol, SocketBlockOption aBlockOption)
void virtualTimeDeinit (void)
void virtualTimeInit (uint16_t aNodeId)
void virtualTimeProcess (otInstance *aInstance, const fd_set *aReadFdSet, const fd_set *aWriteFdSet, const fd_set *aErrorFdSet)
void virtualTimeRadioSpinelProcess (otInstance *aInstance, const struct VirtualTimeEvent *aEvent)
void virtualTimeReceiveEvent (struct VirtualTimeEvent *aEvent)
void virtualTimeSendRadioSpinelWriteEvent (const uint8_t *aData, uint16_t aLength)
void virtualTimeSendSleepEvent (const struct timeval *aTimeout)
void virtualTimeUpdateFdSet (fd_set *aReadFdSet, fd_set *aWriteFdSet, fd_set *aErrorFdSet, int *aMaxFd, struct timeval *aTimeout)
Variables
unsigned int gBackboneNetifIndex
char gBackboneNetifName [IFNAMSIZ]
otInstance * gInstance
otIp4Cidr gNat64Cidr
unsigned int gNetifIndex
char gNetifName [IFNAMSIZ]
OT_TOOL_PACKED_BEGIN struct VirtualTimeEvent OT_TOOL_PACKED_END
Macro Definition Documentation
OPENTHREAD_POSIX_VIRTUAL_TIME
#define OPENTHREAD_POSIX_VIRTUAL_TIME 0
This setting configures whether to use virtual time.
OPENTHREAD_POSIX_DAEMON_SOCKET_NAME
#define OPENTHREAD_POSIX_DAEMON_SOCKET_NAME OPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME ".sock"
This is the socket name used by daemon mode.
MS_PER_S
#define MS_PER_S 1000
US_PER_MS
#define US_PER_MS 1000
US_PER_S
#define US_PER_S (MS_PER_S * US_PER_MS)
NS_PER_US
#define NS_PER_US 1000
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OT_SIM_EVENT_ALARM_FIRED
OT_SIM_EVENT_RADIO_RECEIVED
OT_SIM_EVENT_UART_WRITE
OT_SIM_EVENT_RADIO_SPINEL_WRITE
OT_EVENT_DATA_MAX_SIZE
SocketBlockOption
enum SocketBlockOption
Enumerator
kSocketBlock
kSocketNonBlock
Function Documentation
platformAlarmInit()
void platformAlarmInit (uint32_t aSpeedUpFactor, int aRealTimeSignal)
This function initializes the alarm service used by OpenThread.
Parameters
[in] aSpeedUpFactor The speed up factor.
[in] aRealTimeSignal The real time signal for microsecond alarms.
References DieNow, OT_EXIT_ERROR_ERRNO, OT_EXIT_INVALID_ARGUMENTS, otLogWarnPlat(), sSpeedUpFactor, and VerifyOrDie.
Referenced by platformInit().
platformAlarmUpdateTimeout()
void platformAlarmUpdateTimeout (struct timeval * tv)
This function retrieves the time remaining until the alarm fires.
Parameters
[out] aTimeval A pointer to the timeval struct.
References platformAlarmGetNow(), sIsMsRunning, sMsAlarm, sSpeedUpFactor, US_PER_MS, US_PER_S, and VerifyOrExit.
Referenced by otSysMainloopUpdate().
platformAlarmProcess()
void platformAlarmProcess (otInstance * aInstance)
This function performs alarm driver processing.
Parameters
[in] aInstance The OpenThread instance structure.
References otPlatAlarmMicroFired(), otPlatAlarmMicroGetNow(), otPlatAlarmMilliFired(), otPlatAlarmMilliGetNow(), otPlatDiagAlarmFired(), otPlatDiagModeGet(), sIsMsRunning, and sMsAlarm.
Referenced by otSysMainloopProcess().
platformAlarmGetNext()
int32_t platformAlarmGetNext (void)
This function returns the next alarm event time.
Returns
The next alarm fire time.
platformAlarmAdvanceNow()
void platformAlarmAdvanceNow (uint64_t aDelta)
This function advances the alarm time by aDelta.
Parameters
[in] aDelta The amount of time to advance.
platformRadioInit()
void platformRadioInit (const char * aUrl)
This function initializes the radio service used by OpenThread.
Note
Even when aPlatformConfig->mResetRadio is false, a reset event (i.e. a PROP_LAST_STATUS between [SPINEL_STATUS_RESET__BEGIN, SPINEL_STATUS_RESET__END]) is still expected from RCP.
Parameters
[in] aUrl A pointer to the null-terminated radio URL.
Referenced by platformInit().
platformRadioDeinit()
void platformRadioDeinit (void)
This function shuts down the radio service used by OpenThread.
References RadioSpinel< InterfaceType, ProcessContextType >::Deinit().
Referenced by platformDeinit().
platformRadioReceive()
void platformRadioReceive (otInstance * aInstance, uint8_t * aBuf, uint16_t aBufLength)
This function inputs a received radio frame.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[in] aBuf A pointer to the received radio frame.
[in] aBufLength The size of the received radio frame.
platformRadioUpdateFdSet()
void platformRadioUpdateFdSet (fd_set * aReadFdSet, fd_set * aWriteFdSet, int * aMaxFd, struct timeval * aTimeout)
This function updates the file descriptor sets with file descriptors used by the radio driver.
Parameters
[in,out] aReadFdSet A pointer to the read file descriptors.
[in,out] aWriteFdSet A pointer to the write file descriptors.
[in,out] aMaxFd A pointer to the max file descriptor.
[in,out] aTimeout A pointer to the timeout.
References RadioSpinel< InterfaceType, ProcessContextType >::GetNextRadioTimeRecalcStart(), RadioSpinel< InterfaceType, ProcessContextType >::GetSpinelInterface(), RadioSpinel< InterfaceType, ProcessContextType >::GetTxRadioEndUs(), RadioSpinel< InterfaceType, ProcessContextType >::HasPendingFrame(), RadioSpinel< InterfaceType, ProcessContextType >::IsTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::IsTransmitting(), OT_UNUSED_VARIABLE, otPlatTimeGet(), RadioSpinel< InterfaceType, ProcessContextType >::Process(), US_PER_S, and virtualTimeRadioSpinelProcess().
Referenced by otSysMainloopUpdate().
platformRadioProcess()
void platformRadioProcess (otInstance * aInstance, const fd_set * aReadFdSet, const fd_set * aWriteFdSet)
This function performs radio driver processing.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[in] aReadFdSet A pointer to the read file descriptors.
[in] aWriteFdSet A pointer to the write file descriptors.
References OT_UNUSED_VARIABLE, and RadioSpinel< InterfaceType, ProcessContextType >::Process().
Referenced by otSysMainloopProcess().
platformRandomInit()
void platformRandomInit (void)
This function initializes the random number service used by OpenThread.
Referenced by platformInit().
platformLoggingInit()
void platformLoggingInit (const char * aName)
This function initializes the logging service used by OpenThread.
Parameters
[in] aName A name string which will be prefixed to each log line.
platformUartUpdateFdSet()
void platformUartUpdateFdSet (fd_set * aReadFdSet, fd_set * aWriteFdSet, fd_set * aErrorFdSet, int * aMaxFd)
This function updates the file descriptor sets with file descriptors used by the UART driver.
Parameters
[in,out] aReadFdSet A pointer to the read file descriptors.
[in,out] aWriteFdSet A pointer to the write file descriptors.
[in,out] aMaxFd A pointer to the max file descriptor.
platformUartProcess()
void platformUartProcess (const fd_set * aReadFdSet, const fd_set * aWriteFdSet, const fd_set * aErrorFdSet)
This function performs radio driver processing.
Parameters
[in] aReadFdSet A pointer to the read file descriptors.
[in] aWriteFdSet A pointer to the write file descriptors.
[in] aErrorFdSet A pointer to the error file descriptors.
platformNetifInit()
void platformNetifInit (const char * aInterfaceName)
This function initializes platform netif.
Note
This function is called before OpenThread instance is created.
Parameters
[in] aInterfaceName A pointer to Thread network interface name.
Referenced by otSysGetThreadNetifIndex(), and platformInit().
platformNetifSetUp()
void platformNetifSetUp (void)
This function sets up platform netif.
Note
This function is called after OpenThread instance is created.
Parameters
[in] aInstance A pointer to the OpenThread instance.
Referenced by otSysGetThreadNetifIndex(), and platformSetUp().
platformNetifTearDown()
void platformNetifTearDown (void)
This function tears down platform netif.
Note
This function is called before OpenThread instance is destructed.
Referenced by otSysGetThreadNetifIndex(), and platformTearDown().
platformNetifDeinit()
void platformNetifDeinit (void)
This function deinitializes platform netif.
Note
This function is called after OpenThread instance is destructed.
Referenced by otSysGetThreadNetifIndex(), and platformDeinit().
platformNetifUpdateFdSet()
void platformNetifUpdateFdSet (fd_set * aReadFdSet, fd_set * aWriteFdSet, fd_set * aErrorFdSet, int * aMaxFd)
This function updates the file descriptor sets with file descriptors used by platform netif module.
Parameters
[in,out] aReadFdSet A pointer to the read file descriptors.
[in,out] aWriteFdSet A pointer to the write file descriptors.
[in,out] aErrorFdSet A pointer to the error file descriptors.
[in,out] aMaxFd A pointer to the max file descriptor.
Referenced by otSysGetThreadNetifIndex(), and otSysMainloopUpdate().
platformNetifProcess()
void platformNetifProcess (const fd_set * aReadFdSet, const fd_set * aWriteFdSet, const fd_set * aErrorFdSet)
This function performs platform netif processing.
Parameters
[in] aReadFdSet A pointer to the read file descriptors.
[in] aWriteFdSet A pointer to the write file descriptors.
[in] aErrorFdSet A pointer to the error file descriptors.
Referenced by otSysGetThreadNetifIndex(), and otSysMainloopProcess().
platformNetifStateChange()
void platformNetifStateChange (otInstance * aInstance, otChangedFlags aFlags)
This function performs notifies state changes to platform netif.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[in] aFlags Flags that denote the state change events.
Referenced by otSysGetThreadNetifIndex().
virtualTimeInit()
void virtualTimeInit (uint16_t aNodeId)
This function initialize virtual time simulation.
[in] aNodeId Node id of this simulated device.
Referenced by Radio::Init().
virtualTimeDeinit()
void virtualTimeDeinit (void)
This function deinitialize virtual time simulation.
Referenced by platformDeinit().
virtualTimeProcess()
void virtualTimeProcess (otInstance * aInstance, const fd_set * aReadFdSet, const fd_set * aWriteFdSet, const fd_set * aErrorFdSet)
This function performs virtual time simulation processing.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[in] aReadFdSet A pointer to the read file descriptors.
[in] aWriteFdSet A pointer to the write file descriptors.
Referenced by otSysMainloopProcess().
virtualTimeUpdateFdSet()
void virtualTimeUpdateFdSet (fd_set * aReadFdSet, fd_set * aWriteFdSet, fd_set * aErrorFdSet, int * aMaxFd, struct timeval * aTimeout)
This function updates the file descriptor sets with file descriptors used by the virtual time simulation.
Parameters
[in,out] aReadFdSet A pointer to the read file descriptors.
[in,out] aWriteFdSet A pointer to the write file descriptors.
[in,out] aErrorFdSet A pointer to the error file descriptors.
[in,out] aMaxFd A pointer to the max file descriptor.
[in,out] aTimeout A pointer to the timeout.
Referenced by otSysMainloopUpdate().
virtualTimeSendRadioSpinelWriteEvent()
void virtualTimeSendRadioSpinelWriteEvent (const uint8_t * aData, uint16_t aLength)
This function sends radio spinel event of virtual time simulation.
Parameters
[in] aData A pointer to the spinel frame.
[in] aLength Length of the spinel frame.
Referenced by HdlcInterface::Write().
virtualTimeReceiveEvent()
void virtualTimeReceiveEvent (struct VirtualTimeEvent * aEvent)
This function receives an event of virtual time simulation.
Parameters
[out] aEvent A pointer to the event receiving the event.
Referenced by HdlcInterface::WaitForFrame().
virtualTimeSendSleepEvent()
void virtualTimeSendSleepEvent (const struct timeval * aTimeout)
This function sends sleep event through virtual time simulation.
Parameters
[in] aTimeout A pointer to the time sleeping.
Referenced by otSysMainloopPoll(), and HdlcInterface::WaitForFrame().
virtualTimeRadioSpinelProcess()
void virtualTimeRadioSpinelProcess (otInstance * aInstance, const struct VirtualTimeEvent * aEvent)
This function performs radio spinel processing of virtual time simulation.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[in] aEvent A pointer to the current event.
Referenced by platformRadioUpdateFdSet().
platformTrelInit()
void platformTrelInit (const char * aTrelUrl)
This function initializes platform TREL UDP6 driver.
Parameters
[in] aTrelUrl The TREL URL (configuration for TREL platform).
Referenced by platformInit().
platformTrelDeinit()
void platformTrelDeinit (void)
This function shuts down the platform TREL UDP6 platform driver.
Referenced by platformDeinit().
platformTrelUpdateFdSet()
void platformTrelUpdateFdSet (fd_set * aReadFdSet, fd_set * aWriteFdSet, int * aMaxFd, struct timeval * aTimeout)
This function updates the file descriptor sets with file descriptors used by the TREL driver.
Parameters
[in,out] aReadFdSet A pointer to the read file descriptors.
[in,out] aWriteFdSet A pointer to the write file descriptors.
[in,out] aMaxFd A pointer to the max file descriptor.
[in,out] aTimeout A pointer to the timeout.
Referenced by otSysMainloopUpdate().
platformTrelProcess()
void platformTrelProcess (otInstance * aInstance, const fd_set * aReadFdSet, const fd_set * aWriteFdSet)
This function performs TREL driver processing.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[in] aReadFdSet A pointer to the read file descriptors.
[in] aWriteFdSet A pointer to the write file descriptors.
Referenced by otSysMainloopProcess().
SocketWithCloseExec()
int SocketWithCloseExec (int aDomain, int aType, int aProtocol, SocketBlockOption aBlockOption)
This function creates a socket with SOCK_CLOEXEC flag set.
Parameters
[in] aDomain The communication domain.
[in] aType The semantics of communication.
[in] aProtocol The protocol to use.
[in] aBlockOption Whether to add nonblock flags.
Returns
The file descriptor of the created socket.
Return values
-1 Failed to create socket.
References kSocketNonBlock, OT_EXIT_ERROR_ERRNO, VerifyOrDie, and VerifyOrExit.
Referenced by otSysGetThreadNetifIndex().
platformBackboneInit()
void platformBackboneInit (const char * aInterfaceName)
This function initializes platform Backbone network.
Note
This function is called before OpenThread instance is created.
Parameters
[in] aInterfaceName A pointer to Thread network interface name.
Referenced by platformInit().
platformBackboneSetUp()
void platformBackboneSetUp (void)
This function sets up platform Backbone network.
Note
This function is called after OpenThread instance is created.
Parameters
[in] aInstance A pointer to the OpenThread instance.
Referenced by platformSetUp().
platformBackboneTearDown()
void platformBackboneTearDown (void)
This function tears down platform Backbone network.
Note
This function is called before OpenThread instance is destructed.
Referenced by platformTearDown().
platformBackboneDeinit()
void platformBackboneDeinit (void)
This function shuts down the platform Backbone network.
Note
This function is called after OpenThread instance is destructed.
Referenced by platformDeinit().
platformBackboneStateChange()
void platformBackboneStateChange (otInstance * aInstance, otChangedFlags aFlags)
This function performs notifies state changes to platform Backbone network.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[in] aFlags Flags that denote the state change events.
platformInfraIfIsRunning()
bool platformInfraIfIsRunning (void)
This function tells if the infrastructure interface is running.
Returns
TRUE if the infrastructure interface is running, FALSE if not.
Variable Documentation
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN struct VirtualTimeEvent OT_TOOL_PACKED_END
gNetifName
char gNetifName[IFNAMSIZ]
The name of Thread network interface.
Referenced by otSysGetThreadNetifIndex(), otSysGetThreadNetifName(), and platformInit().
gNetifIndex
unsigned int gNetifIndex
The index of Thread network interface.
Referenced by otSysGetThreadNetifIndex().
gNat64Cidr
otIp4Cidr gNat64Cidr
The CIDR for NAT64
Referenced by platformInit().
gInstance
otInstance* gInstance
A pointer to the OpenThread instance.
Referenced by otSysGetThreadNetifIndex(), and otSysInit().
gBackboneNetifName
char gBackboneNetifName[IFNAMSIZ]
The name of Backbone network interface.
gBackboneNetifIndex
unsigned int gBackboneNetifIndex
The index of Backbone network interface.
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale