OpenThread: udp.h File Reference
platform/udp.h File Reference
Detailed Description
This file includes the abstraction for the platform UDP service.
#include <openthread/udp.h>
Functions
otError otPlatUdpBind (otUdpSocket *aUdpSocket)
otError otPlatUdpBindToNetif (otUdpSocket *aUdpSocket, otNetifIdentifier aNetifIdentifier)
otError otPlatUdpClose (otUdpSocket *aUdpSocket)
otError otPlatUdpConnect (otUdpSocket *aUdpSocket)
otError otPlatUdpJoinMulticastGroup (otUdpSocket *aUdpSocket, otNetifIdentifier aNetifIdentifier, const otIp6Address *aAddress)
otError otPlatUdpLeaveMulticastGroup (otUdpSocket *aUdpSocket, otNetifIdentifier aNetifIdentifier, const otIp6Address *aAddress)
otError otPlatUdpSend (otUdpSocket *aUdpSocket, otMessage *aMessage, const otMessageInfo *aMessageInfo)
otError otPlatUdpSocket (otUdpSocket *aUdpSocket)
Function Documentation
otPlatUdpSocket()
otError otPlatUdpSocket (otUdpSocket * aUdpSocket)
This function initializes the UDP socket by platform.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
Return values
OT_ERROR_NONE Successfully initialized UDP socket by platform.
OT_ERROR_FAILED Failed to initialize UDP Socket.
Referenced by Udp::Open().
otPlatUdpClose()
otError otPlatUdpClose (otUdpSocket * aUdpSocket)
This function closes the UDP socket by platform.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
Return values
OT_ERROR_NONE Successfully closed UDP socket by platform.
OT_ERROR_FAILED Failed to close UDP Socket.
Referenced by Udp::Close().
otPlatUdpBind()
otError otPlatUdpBind (otUdpSocket * aUdpSocket)
This function binds the UDP socket by platform.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
Return values
OT_ERROR_NONE Successfully binded UDP socket by platform.
OT_ERROR_FAILED Failed to bind UDP socket.
Referenced by Udp::Bind().
otPlatUdpBindToNetif()
otError otPlatUdpBindToNetif (otUdpSocket * aUdpSocket, otNetifIdentifier aNetifIdentifier)
This function binds the UDP socket to a platform network interface.
Note: only available when OPENTHREAD_CONFIG_PLATFORM_UDP_ENABLE is used.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
[in] aNetifIdentifier The network interface identifier.
Return values
OT_ERROR_NONE Successfully bound UDP socket.
OT_ERROR_FAILED Failed to bind UDP.
Referenced by Udp::Bind().
otPlatUdpConnect()
otError otPlatUdpConnect (otUdpSocket * aUdpSocket)
This function connects UDP socket by platform.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
Return values
OT_ERROR_NONE Successfully connected by platform.
OT_ERROR_FAILED Failed to connect UDP socket.
Referenced by Udp::Connect().
otPlatUdpSend()
otError otPlatUdpSend (otUdpSocket * aUdpSocket, otMessage * aMessage, const otMessageInfo * aMessageInfo)
This function sends UDP payload by platform.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
[in] aMessage A pointer to the message to send.
[in] aMessageInfo A pointer to the message info associated with aMessage.
Return values
OT_ERROR_NONE Successfully sent by platform, and aMessage is freed.
OT_ERROR_FAILED Failed to binded UDP socket.
Referenced by Udp::SendTo().
otPlatUdpJoinMulticastGroup()
otError otPlatUdpJoinMulticastGroup (otUdpSocket * aUdpSocket, otNetifIdentifier aNetifIdentifier, const otIp6Address * aAddress)
This function configures the UDP socket to join a UDP multicast group.
Note: only available when OPENTHREAD_CONFIG_PLATFORM_UDP_ENABLE is used.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
[in] aNetifIdentifier The network interface identifier.
[in] aAddress The UDP multicast group address.
Return values
OT_ERROR_NONE Successfully joined the multicast group.
OT_ERROR_FAILED Failed to join the multicast group.
Referenced by Udp::Socket::SendTo().
otPlatUdpLeaveMulticastGroup()
otError otPlatUdpLeaveMulticastGroup (otUdpSocket * aUdpSocket, otNetifIdentifier aNetifIdentifier, const otIp6Address * aAddress)
This function configures the UDP socket to leave a UDP multicast group.
Note: only available when OPENTHREAD_CONFIG_PLATFORM_UDP_ENABLE is used.
Parameters
[in] aUdpSocket A pointer to the UDP socket.
[in] aNetifIdentifier The network interface identifier.
[in] aAddress The UDP multicast group address.
Return values
OT_ERROR_NONE Successfully left the multicast group.
OT_ERROR_FAILED Failed to leave the multicast group.
Referenced by Udp::Socket::SendTo().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale