OpenThread: netif.cpp File Reference
posix/platform/netif.cpp File Reference
Detailed Description
This file implements the platform network on Linux.
#include "openthread-posix-config.h"
#include "platform-posix.h"
#include <arpa/inet.h>
#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <net/if_arp.h>
#include <stdio.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <openthread/border_router.h>
#include <openthread/icmp6.h>
#include <openthread/instance.h>
#include <openthread/ip6.h>
#include <openthread/logging.h>
#include <openthread/message.h>
#include <openthread/nat64.h>
#include <openthread/netdata.h>
#include <openthread/platform/misc.h>
#include "common/code_utils.hpp"
#include "common/debug.hpp"
#include "net/ip6_address.hpp"
Functions
unsigned int otSysGetThreadNetifIndex (void)
const char * otSysGetThreadNetifName (void)
Variables
otIp4Cidr gNat64Cidr
unsigned int gNetifIndex = 0
char gNetifName [IFNAMSIZ]
Function Documentation
otSysGetThreadNetifName()
const char* otSysGetThreadNetifName (void)
This method returns the Thread network interface name.
Returns
The Thread network interface name.
References gNetifName.
Referenced by InitInstance(), platformInit(), and ProcessNetif().
otSysGetThreadNetifIndex()
unsigned int otSysGetThreadNetifIndex (void)
This method returns the Thread network interface index.
Returns
The Thread network interface index.
References Ip6AddressString::AsCString(), String< kSize >::AsCString(), Clearable< Type >::Clear(), DieNow, EINVAL, ExitNow, gInstance, gNetifIndex, gNetifName, Address::IsMulticast(), Address::kLinkLocalScope, kSocketNonBlock, otIp4Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp4Cidr::mAddress, otNetifAddress::mAddress, otNetifMulticastAddress::mAddress, otIp6AddressInfo::mAddress, otIp4Address::mFields, otIp6Address::mFields, otIp4Cidr::mLength, otIp6Prefix::mLength, otMessageSettings::mLinkSecurityEnabled, otNetifAddress::mNext, otIp6AddressInfo::mPreferred, otBorderRouterConfig::mPrefix, otExternalRouteConfig::mPrefix, otIp6Prefix::mPrefix, otNetifAddress::mPrefixLength, otIp6AddressInfo::mPrefixLength, otMessageSettings::mPriority, otExternalRouteConfig::mRloc16, otIp6AddressInfo::mScope, OPENTHREAD_CONFIG_IP6_MAX_DATAGRAM_LENGTH, OPENTHREAD_POSIX_CONFIG_EXTERNAL_ROUTE_PRIORITY, OPENTHREAD_POSIX_CONFIG_MAX_EXTERNAL_ROUTE_NUM, OPENTHREAD_POSIX_CONFIG_MAX_OMR_ROUTES_NUM, OPENTHREAD_POSIX_CONFIG_NETIF_PREFIX_ROUTE_METRIC, OPENTHREAD_POSIX_CONFIG_OMR_ROUTES_PRIORITY, OT_ASSERT, OT_CHANGED_THREAD_NETDATA, OT_CHANGED_THREAD_NETIF_STATE, OT_DEVICE_ROLE_DISABLED, OT_ERROR_ALREADY, OT_ERROR_BUSY, OT_ERROR_DROP, OT_ERROR_FAILED, OT_ERROR_INVALID_STATE, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_REJECTED, OT_EXIT_ERROR_ERRNO, OT_EXIT_FAILURE, OT_EXIT_INVALID_ARGUMENTS, OT_ICMP6_ECHO_HANDLER_ALL, OT_ICMP6_ECHO_HANDLER_DISABLED, OT_IP6_ADDRESS_STRING_SIZE, OT_IP6_PREFIX_STRING_SIZE, OT_MESSAGE_PRIORITY_LOW, OT_NETWORK_DATA_ITERATOR_INIT, OT_TOOL_PACKED_BEGIN, OT_TOOL_PACKED_END, OT_UNUSED_VARIABLE, otDumpInfoPlat(), otIcmp6SetEchoMode(), otIp4NewMessage(), otIp6AddressToString(), otIp6AddUnicastAddress(), otIp6ArePrefixesEqual(), otIp6GetUnicastAddresses(), otIp6IsEnabled(), otIp6NewMessage(), otIp6PrefixMatch(), otIp6PrefixToString(), otIp6RemoveUnicastAddress(), otIp6Send(), otIp6SetAddressCallback(), otIp6SetEnabled(), otIp6SetMulticastPromiscuousEnabled(), otIp6SetReceiveCallback(), otIp6SetReceiveFilterEnabled(), otIp6SubscribeMulticastAddress(), otIp6UnsubscribeMulticastAddress(), otLogDebgPlat(), otLogInfoPlat(), otLogNotePlat(), otLogWarnPlat(), otMessageAppend(), otMessageFree(), otMessageGetLength(), otMessageRead(), otNat64Send(), otNat64SetIp4Cidr(), otNat64SetReceiveIp4Callback(), otNetDataContainsOmrPrefix(), otNetDataGetNextOnMeshPrefix(), otNetDataGetNextRoute(), otThreadErrorToString(), otThreadGetDeviceRole(), otThreadGetRloc16(), platformNetifDeinit(), platformNetifInit(), platformNetifProcess(), platformNetifSetUp(), platformNetifStateChange(), platformNetifTearDown(), platformNetifUpdateFdSet(), Address::SetPrefix(), SocketWithCloseExec(), SuccessOrDie, SuccessOrExit, Address::ToString(), VerifyOrDie, and VerifyOrExit.
Referenced by ProcessNetif().
Variable Documentation
gNetifIndex
unsigned int gNetifIndex = 0
The index of Thread network interface.
Referenced by otSysGetThreadNetifIndex().
gNetifName
char gNetifName[IFNAMSIZ]
The name of Thread network interface.
Referenced by otSysGetThreadNetifIndex(), otSysGetThreadNetifName(), and platformInit().
gNat64Cidr
otIp4Cidr gNat64Cidr
The CIDR for NAT64
Referenced by platformInit().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale