OpenThread: spinel.c File Reference
spinel.c File Reference
#include "spinel.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define assert_printf(fmt, ...) fprintf(stderr, __FILE__ ":%d: " fmt "\n", __LINE__, __VA_ARGS__)
#define EINVAL 1
#define ENOMEM 1
#define EOVERFLOW 1
#define require(c, l) require_action(c, l, {})
#define require_action(c, l, a)
#define SPINEL_MAX_PACK_LENGTH 32767
#define SPINEL_PLATFORM_DOESNT_IMPLEMENT_ERRNO_VAR 0
#define SPINEL_PLATFORM_DOESNT_IMPLEMENT_FPRINTF 0
#define SPINEL_PLATFORM_SHOULD_LOG_ASSERTS 0
#define SPINEL_SELF_TEST 0
Functions
const char * spinel_capability_to_cstr (spinel_capability_t capability)
const char * spinel_command_to_cstr (spinel_command_t command)
spinel_ssize_t spinel_datatype_pack (uint8_t *data_out, spinel_size_t data_len_max, const char *pack_format,...)
spinel_ssize_t spinel_datatype_unpack (const uint8_t *data_in, spinel_size_t data_len, const char *pack_format,...)
spinel_ssize_t spinel_datatype_unpack_in_place (const uint8_t *data_in, spinel_size_t data_len, const char *pack_format,...)
spinel_ssize_t spinel_datatype_vpack (uint8_t *data_out, spinel_size_t data_len_max, const char *pack_format, va_list args)
static spinel_ssize_t spinel_datatype_vpack_ (uint8_t *data_out, spinel_size_t data_len_max, const char *pack_format, va_list_obj *args)
spinel_ssize_t spinel_datatype_vunpack (const uint8_t *data_in, spinel_size_t data_len, const char *pack_format, va_list args)
static spinel_ssize_t spinel_datatype_vunpack_ (bool in_place, const uint8_t *data_in, spinel_size_t data_len, const char *pack_format, va_list_obj *args)
spinel_ssize_t spinel_datatype_vunpack_in_place (const uint8_t *data_in, spinel_size_t data_len, const char *pack_format, va_list args)
const char * spinel_mcu_power_state_to_cstr (uint8_t mcu_power_state)
const char * spinel_net_role_to_cstr (uint8_t net_role)
const char * spinel_next_packed_datatype (const char *pack_format)
spinel_ssize_t spinel_packed_uint_decode (const uint8_t *bytes, spinel_size_t len, unsigned int *value_ptr)
spinel_ssize_t spinel_packed_uint_encode (uint8_t *bytes, spinel_size_t len, unsigned int value)
spinel_ssize_t spinel_packed_uint_size (unsigned int value)
const char * spinel_prop_key_to_cstr (spinel_prop_key_t prop_key)
const char * spinel_status_to_cstr (spinel_status_t status)
static size_t spinel_strnlen (const char *s, size_t maxlen)
static const char * spinel_to_cstr (const struct spinel_cstr *table, uint32_t val)
static bool spinel_validate_utf8 (const uint8_t *string)
Macro Definition Documentation
EOVERFLOW
#define EOVERFLOW 1
Referenced by spinel_datatype_vunpack_().
EINVAL
#define EINVAL 1
Referenced by otSysGetThreadNetifIndex(), spinel_datatype_vpack_(), and spinel_datatype_vunpack_().
ENOMEM
#define ENOMEM 1
Referenced by spinel_datatype_vunpack_().
SPINEL_PLATFORM_SHOULD_LOG_ASSERTS
#define SPINEL_PLATFORM_SHOULD_LOG_ASSERTS 0
SPINEL_PLATFORM_DOESNT_IMPLEMENT_ERRNO_VAR
#define SPINEL_PLATFORM_DOESNT_IMPLEMENT_ERRNO_VAR 0
SPINEL_PLATFORM_DOESNT_IMPLEMENT_FPRINTF
#define SPINEL_PLATFORM_DOESNT_IMPLEMENT_FPRINTF 0
SPINEL_SELF_TEST
#define SPINEL_SELF_TEST 0
assert_printf
#define assert_printf (fmt, ...) fprintf(stderr, __FILE__ ":%d: " fmt "\n", __LINE__, __VA_ARGS__)
require_action
#define require_action (c, l, a)
Value:
do                          \
    {                           \
        if (!(c))               \
        {                       \
            a;                  \
            goto l;             \
        }                       \
    } while (0)
Referenced by spinel_datatype_vpack_(), and spinel_datatype_vunpack_().
require
#define require (c, l) require_action(c, l, {})
Referenced by spinel_datatype_vunpack_().
SPINEL_MAX_PACK_LENGTH
#define SPINEL_MAX_PACK_LENGTH 32767
Referenced by spinel_datatype_vpack_(), and spinel_datatype_vunpack_().
Function Documentation
spinel_strnlen()
static size_t spinel_strnlen (const char * s, size_t maxlen) static
Referenced by spinel_datatype_vunpack_().
spinel_validate_utf8()
static bool spinel_validate_utf8 (const uint8_t * string) static
Referenced by spinel_capability_to_cstr(), and spinel_datatype_vunpack_().
spinel_packed_uint_decode()
spinel_ssize_t spinel_packed_uint_decode (const uint8_t * bytes, spinel_size_t len, unsigned int * value_ptr)
Referenced by Decoder::ReadUintPacked(), and spinel_datatype_vunpack_().
spinel_packed_uint_size()
spinel_ssize_t spinel_packed_uint_size (unsigned int value)
Referenced by spinel_packed_uint_encode().
spinel_packed_uint_encode()
spinel_ssize_t spinel_packed_uint_encode (uint8_t * bytes, spinel_size_t len, unsigned int value)
References spinel_packed_uint_size().
Referenced by spinel_datatype_vpack_(), and Encoder::WriteUintPacked().
spinel_next_packed_datatype()
const char* spinel_next_packed_datatype (const char * pack_format)
Referenced by spinel_datatype_vpack_(), and spinel_datatype_vunpack_().
spinel_datatype_vunpack_()
static spinel_ssize_t spinel_datatype_vunpack_ (bool in_place, const uint8_t * data_in, spinel_size_t data_len, const char * pack_format, va_list_obj * args) static
References EINVAL, ENOMEM, EOVERFLOW, require, require_action, SPINEL_DATATYPE_ARRAY_C, SPINEL_DATATYPE_BOOL_C, SPINEL_DATATYPE_DATA_C, SPINEL_DATATYPE_DATA_WLEN_C, SPINEL_DATATYPE_EUI48_C, SPINEL_DATATYPE_EUI64_C, SPINEL_DATATYPE_INT16_C, SPINEL_DATATYPE_INT32_C, SPINEL_DATATYPE_INT64_C, SPINEL_DATATYPE_INT8_C, SPINEL_DATATYPE_IPv6ADDR_C, SPINEL_DATATYPE_STRUCT_C, SPINEL_DATATYPE_UINT16_C, SPINEL_DATATYPE_UINT16_S, SPINEL_DATATYPE_UINT32_C, SPINEL_DATATYPE_UINT64_C, SPINEL_DATATYPE_UINT8_C, SPINEL_DATATYPE_UINT_PACKED_C, spinel_datatype_unpack(), SPINEL_DATATYPE_UTF8_C, SPINEL_FRAME_MAX_SIZE, SPINEL_MAX_PACK_LENGTH, SPINEL_MAX_UINT_PACKED, spinel_next_packed_datatype(), spinel_packed_uint_decode(), spinel_strnlen(), and spinel_validate_utf8().
Referenced by spinel_datatype_unpack(), spinel_datatype_unpack_in_place(), spinel_datatype_vunpack(), and spinel_datatype_vunpack_in_place().
spinel_datatype_unpack_in_place()
spinel_ssize_t spinel_datatype_unpack_in_place (const uint8_t * data_in, spinel_size_t data_len, const char * pack_format, ...)
This function parses spinel data similar to sscanf().
This function actually calls spinel_datatype_vunpack_in_place() to parse data.
Parameters
[in] data_in A pointer to the data to parse.
[in] data_len The length of data_in in bytes.
[in] pack_format C string that contains a format string follows the same specification of spinel.
[in] ... Additional arguments depending on the format string pack_format.
Returns
The parsed length in bytes.
Note
This function behaves different from spinel_datatype_unpack():
This function expects composite data arguments of pointer to data type, while spinel_datatype_unpack() expects them of pointer to data type pointer. For example, if SPINEL_DATATYPE_EUI64_C is present in pack_format, this function expects a spinel_eui64_t * is included in variable arguments, while spinel_datatype_unpack() expects a spinel_eui64_t ** is included.
For SPINEL_DATATYPE_UTF8_C, this function expects two arguments, the first of type char * and the second is of type size_t to indicate length of the provided buffer in the first argument just like strncpy(), while spinel_datatype_unpack() only expects a const char **.
See also
spinel_datatype_vunpack_in_place()
References spinel_datatype_vunpack_().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::ParseRadioFrame(), and spinel_capability_to_cstr().
spinel_datatype_unpack()
spinel_ssize_t spinel_datatype_unpack (const uint8_t * data_in, spinel_size_t data_len, const char * pack_format, ...)
References spinel_datatype_vunpack_().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::GetRadioChannelMask(), RadioSpinel< InterfaceType, ProcessContextType >::HandleNotification(), RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), RadioSpinel< InterfaceType, ProcessContextType >::HandleResponse(), RadioSpinel< InterfaceType, ProcessContextType >::HandleTransmitDone(), RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs(), RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse(), RadioSpinel< InterfaceType, ProcessContextType >::IsRcp(), spinel_capability_to_cstr(), and spinel_datatype_vunpack_().
spinel_datatype_vunpack_in_place()
spinel_ssize_t spinel_datatype_vunpack_in_place (const uint8_t * data_in, spinel_size_t data_len, const char * pack_format, va_list args)
This function parses spinel data similar to vsscanf().
Parameters
[in] data_in A pointer to the data to parse.
[in] data_len The length of data_in in bytes.
[in] pack_format C string that contains a format string follows the same specification of spinel.
[in] args A value identifying a variable arguments list.
Returns
The parsed length in bytes.
Note
This function behaves different from spinel_datatype_vunpack():
This function expects composite data arguments of pointer to data type, while spinel_datatype_vunpack() expects them of pointer to data type pointer. For example, if SPINEL_DATATYPE_EUI64_C is present in pack_format, this function expects a spinel_eui64_t * is included in variable arguments, while spinel_datatype_vunpack() expects a spinel_eui64_t ** is included.
For SPINEL_DATATYPE_UTF8_C, this function expects two arguments, the first of type char * and the second is of type size_t to indicate length of the provided buffer in the first argument just like strncpy(), while spinel_datatype_vunpack() only expects a const char **.
See also
spinel_datatype_unpack_in_place()
References spinel_datatype_vunpack_().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleWaitingResponse().
spinel_datatype_vunpack()
spinel_ssize_t spinel_datatype_vunpack (const uint8_t * data_in, spinel_size_t data_len, const char * pack_format, va_list args)
References spinel_datatype_vunpack_().
spinel_datatype_vpack_()
static spinel_ssize_t spinel_datatype_vpack_ (uint8_t * data_out, spinel_size_t data_len_max, const char * pack_format, va_list_obj * args) static
References EINVAL, require_action, SPINEL_DATATYPE_BOOL_C, SPINEL_DATATYPE_DATA_C, SPINEL_DATATYPE_DATA_WLEN_C, SPINEL_DATATYPE_EUI48_C, SPINEL_DATATYPE_EUI64_C, SPINEL_DATATYPE_INT16_C, SPINEL_DATATYPE_INT32_C, SPINEL_DATATYPE_INT64_C, SPINEL_DATATYPE_INT8_C, SPINEL_DATATYPE_IPv6ADDR_C, spinel_datatype_pack(), SPINEL_DATATYPE_STRUCT_C, SPINEL_DATATYPE_UINT16_C, SPINEL_DATATYPE_UINT16_S, SPINEL_DATATYPE_UINT32_C, SPINEL_DATATYPE_UINT64_C, SPINEL_DATATYPE_UINT8_C, SPINEL_DATATYPE_UINT_PACKED_C, SPINEL_DATATYPE_UTF8_C, SPINEL_MAX_PACK_LENGTH, SPINEL_MAX_UINT_PACKED, spinel_next_packed_datatype(), and spinel_packed_uint_encode().
Referenced by spinel_datatype_pack(), and spinel_datatype_vpack().
spinel_datatype_pack()
spinel_ssize_t spinel_datatype_pack (uint8_t * data_out, spinel_size_t data_len_max, const char * pack_format, ...)
References spinel_datatype_vpack_().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::CalcRcpTimeOffset(), RadioSpinel< InterfaceType, ProcessContextType >::SendCommand(), RadioSpinel< InterfaceType, ProcessContextType >::SendReset(), spinel_capability_to_cstr(), and spinel_datatype_vpack_().
spinel_datatype_vpack()
spinel_ssize_t spinel_datatype_vpack (uint8_t * data_out, spinel_size_t data_len_max, const char * pack_format, va_list args)
References spinel_datatype_vpack_().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::SendCommand(), Encoder::WritePacked(), and Encoder::WriteVPacked().
spinel_to_cstr()
static const char* spinel_to_cstr (const struct spinel_cstr * table, uint32_t val) static
Referenced by spinel_capability_to_cstr(), spinel_command_to_cstr(), spinel_mcu_power_state_to_cstr(), spinel_net_role_to_cstr(), spinel_prop_key_to_cstr(), and spinel_status_to_cstr().
spinel_command_to_cstr()
const char* spinel_command_to_cstr (spinel_command_t command)
References SPINEL_CMD_HBO_DROP, SPINEL_CMD_HBO_DROPPED, SPINEL_CMD_HBO_OFFLOAD, SPINEL_CMD_HBO_OFFLOADED, SPINEL_CMD_HBO_RECLAIM, SPINEL_CMD_HBO_RECLAIMED, SPINEL_CMD_NET_CLEAR, SPINEL_CMD_NET_RECALL, SPINEL_CMD_NET_SAVE, SPINEL_CMD_NOOP, SPINEL_CMD_PEEK, SPINEL_CMD_PEEK_RET, SPINEL_CMD_POKE, SPINEL_CMD_PROP_VALUE_GET, SPINEL_CMD_PROP_VALUE_INSERT, SPINEL_CMD_PROP_VALUE_INSERTED, SPINEL_CMD_PROP_VALUE_IS, SPINEL_CMD_PROP_VALUE_MULTI_GET, SPINEL_CMD_PROP_VALUE_MULTI_SET, SPINEL_CMD_PROP_VALUE_REMOVE, SPINEL_CMD_PROP_VALUE_REMOVED, SPINEL_CMD_PROP_VALUE_SET, SPINEL_CMD_PROP_VALUES_ARE, SPINEL_CMD_RESET, and spinel_to_cstr().
spinel_prop_key_to_cstr()
const char* spinel_prop_key_to_cstr (spinel_prop_key_t prop_key)
References SPINEL_PROP_15_4_PIB_MAC_PROMISCUOUS_MODE, SPINEL_PROP_15_4_PIB_MAC_SECURITY_ENABLED, SPINEL_PROP_15_4_PIB_PHY_CHANNELS_SUPPORTED, SPINEL_PROP_CAPS, SPINEL_PROP_CHANNEL_MANAGER_AUTO_SELECT_ENABLED, SPINEL_PROP_CHANNEL_MANAGER_AUTO_SELECT_INTERVAL, SPINEL_PROP_CHANNEL_MANAGER_CHANNEL_SELECT, SPINEL_PROP_CHANNEL_MANAGER_DELAY, SPINEL_PROP_CHANNEL_MANAGER_FAVORED_CHANNELS, SPINEL_PROP_CHANNEL_MANAGER_NEW_CHANNEL, SPINEL_PROP_CHANNEL_MANAGER_SUPPORTED_CHANNELS, SPINEL_PROP_CHANNEL_MONITOR_CHANNEL_OCCUPANCY, SPINEL_PROP_CHANNEL_MONITOR_RSSI_THRESHOLD, SPINEL_PROP_CHANNEL_MONITOR_SAMPLE_COUNT, SPINEL_PROP_CHANNEL_MONITOR_SAMPLE_INTERVAL, SPINEL_PROP_CHANNEL_MONITOR_SAMPLE_WINDOW, SPINEL_PROP_CHILD_SUPERVISION_CHECK_TIMEOUT, SPINEL_PROP_CHILD_SUPERVISION_INTERVAL, SPINEL_PROP_CNTR_ALL_IP_COUNTERS, SPINEL_PROP_CNTR_ALL_MAC_COUNTERS, SPINEL_PROP_CNTR_IP_RX_FAILURE, SPINEL_PROP_CNTR_IP_RX_SUCCESS, SPINEL_PROP_CNTR_IP_TX_FAILURE, SPINEL_PROP_CNTR_IP_TX_SUCCESS, SPINEL_PROP_CNTR_MAC_RETRY_HISTOGRAM, SPINEL_PROP_CNTR_MLE_COUNTERS, SPINEL_PROP_CNTR_RESET, SPINEL_PROP_CNTR_RX_ERR_BAD_FCS, SPINEL_PROP_CNTR_RX_ERR_EMPTY, SPINEL_PROP_CNTR_RX_ERR_NVLD_SADDR, SPINEL_PROP_CNTR_RX_ERR_OTHER, SPINEL_PROP_CNTR_RX_ERR_SECURITY, SPINEL_PROP_CNTR_RX_ERR_UKWN_NBR, SPINEL_PROP_CNTR_RX_IP_DROPPED, SPINEL_PROP_CNTR_RX_IP_INSEC_TOTAL, SPINEL_PROP_CNTR_RX_IP_SEC_TOTAL, SPINEL_PROP_CNTR_RX_PKT_BEACON, SPINEL_PROP_CNTR_RX_PKT_BEACON_REQ, SPINEL_PROP_CNTR_RX_PKT_BROADCAST, SPINEL_PROP_CNTR_RX_PKT_DATA, SPINEL_PROP_CNTR_RX_PKT_DATA_POLL, SPINEL_PROP_CNTR_RX_PKT_DUP, SPINEL_PROP_CNTR_RX_PKT_FILT_DA, SPINEL_PROP_CNTR_RX_PKT_FILT_WL, SPINEL_PROP_CNTR_RX_PKT_OTHER, SPINEL_PROP_CNTR_RX_PKT_TOTAL, SPINEL_PROP_CNTR_RX_PKT_UNICAST, SPINEL_PROP_CNTR_RX_SPINEL_ERR, SPINEL_PROP_CNTR_RX_SPINEL_OUT_OF_ORDER_TID, SPINEL_PROP_CNTR_RX_SPINEL_TOTAL, SPINEL_PROP_CNTR_TX_ERR_ABORT, SPINEL_PROP_CNTR_TX_ERR_CCA, SPINEL_PROP_CNTR_TX_IP_DROPPED, SPINEL_PROP_CNTR_TX_IP_INSEC_TOTAL, SPINEL_PROP_CNTR_TX_IP_SEC_TOTAL, SPINEL_PROP_CNTR_TX_PKT_ACK_REQ, SPINEL_PROP_CNTR_TX_PKT_ACKED, SPINEL_PROP_CNTR_TX_PKT_BEACON, SPINEL_PROP_CNTR_TX_PKT_BEACON_REQ, SPINEL_PROP_CNTR_TX_PKT_BROADCAST, SPINEL_PROP_CNTR_TX_PKT_DATA, SPINEL_PROP_CNTR_TX_PKT_DATA_POLL, SPINEL_PROP_CNTR_TX_PKT_NO_ACK_REQ, SPINEL_PROP_CNTR_TX_PKT_OTHER, SPINEL_PROP_CNTR_TX_PKT_RETRY, SPINEL_PROP_CNTR_TX_PKT_TOTAL, SPINEL_PROP_CNTR_TX_PKT_UNICAST, SPINEL_PROP_CNTR_TX_SPINEL_TOTAL, SPINEL_PROP_DATASET_ACTIVE_TIMESTAMP, SPINEL_PROP_DATASET_DELAY_TIMER, SPINEL_PROP_DATASET_DEST_ADDRESS, SPINEL_PROP_DATASET_PENDING_TIMESTAMP, SPINEL_PROP_DATASET_RAW_TLVS, SPINEL_PROP_DATASET_SECURITY_POLICY, SPINEL_PROP_DEBUG_LOG_TIMESTAMP_BASE, SPINEL_PROP_DEBUG_NCP_LOG_LEVEL, SPINEL_PROP_DEBUG_TEST_ASSERT, SPINEL_PROP_DEBUG_TEST_WATCHDOG, SPINEL_PROP_DEBUG_TREL_TEST_MODE_ENABLE, SPINEL_PROP_GPIO_CONFIG, SPINEL_PROP_GPIO_STATE, SPINEL_PROP_GPIO_STATE_CLEAR, SPINEL_PROP_GPIO_STATE_SET, SPINEL_PROP_HBO_BLOCK_MAX, SPINEL_PROP_HBO_MEM_MAX, SPINEL_PROP_HOST_POWER_STATE, SPINEL_PROP_HWADDR, SPINEL_PROP_INTERFACE_COUNT, SPINEL_PROP_INTERFACE_TYPE, SPINEL_PROP_IPV6_ADDRESS_TABLE, SPINEL_PROP_IPV6_ICMP_PING_OFFLOAD, SPINEL_PROP_IPV6_ICMP_PING_OFFLOAD_MODE, SPINEL_PROP_IPV6_LL_ADDR, SPINEL_PROP_IPV6_ML_ADDR, SPINEL_PROP_IPV6_ML_PREFIX, SPINEL_PROP_IPV6_MULTICAST_ADDRESS_TABLE, SPINEL_PROP_IPV6_ROUTE_TABLE, SPINEL_PROP_JAM_DETECT_BUSY, SPINEL_PROP_JAM_DETECT_ENABLE, SPINEL_PROP_JAM_DETECT_HISTORY_BITMAP, SPINEL_PROP_JAM_DETECT_RSSI_THRESHOLD, SPINEL_PROP_JAM_DETECT_WINDOW, SPINEL_PROP_JAM_DETECTED, SPINEL_PROP_LAST_STATUS, SPINEL_PROP_LOCK, SPINEL_PROP_MAC_15_4_LADDR, SPINEL_PROP_MAC_15_4_PANID, SPINEL_PROP_MAC_15_4_SADDR, SPINEL_PROP_MAC_ALLOWLIST, SPINEL_PROP_MAC_ALLOWLIST_ENABLED, SPINEL_PROP_MAC_CCA_FAILURE_RATE, SPINEL_PROP_MAC_DATA_POLL_PERIOD, SPINEL_PROP_MAC_DENYLIST, SPINEL_PROP_MAC_DENYLIST_ENABLED, SPINEL_PROP_MAC_ENERGY_SCAN_RESULT, SPINEL_PROP_MAC_EXTENDED_ADDR, SPINEL_PROP_MAC_FIXED_RSS, SPINEL_PROP_MAC_MAX_RETRY_NUMBER_DIRECT, SPINEL_PROP_MAC_MAX_RETRY_NUMBER_INDIRECT, SPINEL_PROP_MAC_PROMISCUOUS_MODE, SPINEL_PROP_MAC_RAW_STREAM_ENABLED, SPINEL_PROP_MAC_SCAN_BEACON, SPINEL_PROP_MAC_SCAN_MASK, SPINEL_PROP_MAC_SCAN_PERIOD, SPINEL_PROP_MAC_SCAN_STATE, SPINEL_PROP_MAC_SRC_MATCH_ENABLED, SPINEL_PROP_MAC_SRC_MATCH_EXTENDED_ADDRESSES, SPINEL_PROP_MAC_SRC_MATCH_SHORT_ADDRESSES, SPINEL_PROP_MCU_POWER_STATE, SPINEL_PROP_MESHCOP_COMMISSIONER_ANNOUNCE_BEGIN, SPINEL_PROP_MESHCOP_COMMISSIONER_ENERGY_SCAN, SPINEL_PROP_MESHCOP_COMMISSIONER_ENERGY_SCAN_RESULT, SPINEL_PROP_MESHCOP_COMMISSIONER_GENERATE_PSKC, SPINEL_PROP_MESHCOP_COMMISSIONER_JOINERS, SPINEL_PROP_MESHCOP_COMMISSIONER_MGMT_GET, SPINEL_PROP_MESHCOP_COMMISSIONER_MGMT_SET, SPINEL_PROP_MESHCOP_COMMISSIONER_PAN_ID_CONFLICT_RESULT, SPINEL_PROP_MESHCOP_COMMISSIONER_PAN_ID_QUERY, SPINEL_PROP_MESHCOP_COMMISSIONER_PROVISIONING_URL, SPINEL_PROP_MESHCOP_COMMISSIONER_SESSION_ID, SPINEL_PROP_MESHCOP_COMMISSIONER_STATE, SPINEL_PROP_MESHCOP_JOINER_COMMISSIONING, SPINEL_PROP_MESHCOP_JOINER_DISCERNER, SPINEL_PROP_MESHCOP_JOINER_STATE, SPINEL_PROP_MSG_BUFFER_COUNTERS, SPINEL_PROP_NCP_VERSION, SPINEL_PROP_NEIGHBOR_TABLE_MULTI_RADIO_INFO, SPINEL_PROP_NEST_LEGACY_LAST_NODE_JOINED, SPINEL_PROP_NEST_LEGACY_ULA_PREFIX, SPINEL_PROP_NEST_STREAM_MFG, SPINEL_PROP_NET_IF_UP, SPINEL_PROP_NET_KEY_SEQUENCE_COUNTER, SPINEL_PROP_NET_KEY_SWITCH_GUARDTIME, SPINEL_PROP_NET_NETWORK_KEY, SPINEL_PROP_NET_NETWORK_NAME, SPINEL_PROP_NET_PARTITION_ID, SPINEL_PROP_NET_PSKC, SPINEL_PROP_NET_REQUIRE_JOIN_EXISTING, SPINEL_PROP_NET_ROLE, SPINEL_PROP_NET_SAVED, SPINEL_PROP_NET_STACK_UP, SPINEL_PROP_NET_XPANID, SPINEL_PROP_PARENT_RESPONSE_INFO, SPINEL_PROP_PHY_CCA_THRESHOLD, SPINEL_PROP_PHY_CHAN, SPINEL_PROP_PHY_CHAN_MAX_POWER, SPINEL_PROP_PHY_CHAN_PREFERRED, SPINEL_PROP_PHY_CHAN_SUPPORTED, SPINEL_PROP_PHY_ENABLED, SPINEL_PROP_PHY_FEM_LNA_GAIN, SPINEL_PROP_PHY_FREQ, SPINEL_PROP_PHY_PCAP_ENABLED, SPINEL_PROP_PHY_RSSI, SPINEL_PROP_PHY_RX_SENSITIVITY, SPINEL_PROP_PHY_TX_POWER, SPINEL_PROP_POWER_STATE, SPINEL_PROP_PROTOCOL_VERSION, SPINEL_PROP_RADIO_CAPS, SPINEL_PROP_RADIO_COEX_ENABLE, SPINEL_PROP_RADIO_COEX_METRICS, SPINEL_PROP_RCP_API_VERSION, SPINEL_PROP_RCP_CSL_ACCURACY, SPINEL_PROP_RCP_CSL_UNCERTAINTY, SPINEL_PROP_RCP_ENH_ACK_PROBING, SPINEL_PROP_RCP_MAC_FRAME_COUNTER, SPINEL_PROP_RCP_MAC_KEY, SPINEL_PROP_RCP_VERSION, SPINEL_PROP_SERVER_ALLOW_LOCAL_DATA_CHANGE, SPINEL_PROP_SERVER_LEADER_SERVICES, SPINEL_PROP_SERVER_SERVICES, SPINEL_PROP_SLAAC_ENABLED, SPINEL_PROP_SRP_CLIENT_EVENT, SPINEL_PROP_SRP_CLIENT_HOST_ADDRESSES, SPINEL_PROP_SRP_CLIENT_HOST_INFO, SPINEL_PROP_SRP_CLIENT_HOST_NAME, SPINEL_PROP_SRP_CLIENT_HOST_SERVICES_CLEAR, SPINEL_PROP_SRP_CLIENT_HOST_SERVICES_REMOVE, SPINEL_PROP_SRP_CLIENT_KEY_LEASE_INTERVAL, SPINEL_PROP_SRP_CLIENT_LEASE_INTERVAL, SPINEL_PROP_SRP_CLIENT_SERVICE_KEY_ENABLED, SPINEL_PROP_SRP_CLIENT_SERVICES, SPINEL_PROP_SRP_CLIENT_START, SPINEL_PROP_STREAM_DEBUG, SPINEL_PROP_STREAM_LOG, SPINEL_PROP_STREAM_NET, SPINEL_PROP_STREAM_NET_INSECURE, SPINEL_PROP_STREAM_RAW, SPINEL_PROP_SUPPORTED_RADIO_LINKS, SPINEL_PROP_THREAD_ACTIVE_DATASET, SPINEL_PROP_THREAD_ACTIVE_ROUTER_IDS, SPINEL_PROP_THREAD_ADDRESS_CACHE_TABLE, SPINEL_PROP_THREAD_ALLOW_LOCAL_NET_DATA_CHANGE, SPINEL_PROP_THREAD_ASSISTING_PORTS, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_CONFIG, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_REGISTER, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_REGISTRATION_JITTER, SPINEL_PROP_THREAD_BACKBONE_ROUTER_LOCAL_STATE, SPINEL_PROP_THREAD_BACKBONE_ROUTER_PRIMARY, SPINEL_PROP_THREAD_CHILD_COUNT_MAX, SPINEL_PROP_THREAD_CHILD_TABLE, SPINEL_PROP_THREAD_CHILD_TABLE_ADDRESSES, SPINEL_PROP_THREAD_CHILD_TIMEOUT, SPINEL_PROP_THREAD_COMMISSIONER_ENABLED, SPINEL_PROP_THREAD_CONTEXT_REUSE_DELAY, SPINEL_PROP_THREAD_CSL_CHANNEL, SPINEL_PROP_THREAD_CSL_PERIOD, SPINEL_PROP_THREAD_CSL_TIMEOUT, SPINEL_PROP_THREAD_DISCOVERY_SCAN_ENABLE_FILTERING, SPINEL_PROP_THREAD_DISCOVERY_SCAN_JOINER_FLAG, SPINEL_PROP_THREAD_DISCOVERY_SCAN_PANID, SPINEL_PROP_THREAD_DOMAIN_NAME, SPINEL_PROP_THREAD_JOINERS, SPINEL_PROP_THREAD_LEADER_ADDR, SPINEL_PROP_THREAD_LEADER_NETWORK_DATA, SPINEL_PROP_THREAD_LEADER_RID, SPINEL_PROP_THREAD_LEADER_WEIGHT, SPINEL_PROP_THREAD_LINK_METRICS_MGMT_ENH_ACK, SPINEL_PROP_THREAD_LINK_METRICS_MGMT_ENH_ACK_IE, SPINEL_PROP_THREAD_LINK_METRICS_MGMT_FORWARD, SPINEL_PROP_THREAD_LINK_METRICS_MGMT_RESPONSE, SPINEL_PROP_THREAD_LINK_METRICS_PROBE, SPINEL_PROP_THREAD_LINK_METRICS_QUERY, SPINEL_PROP_THREAD_LINK_METRICS_QUERY_RESULT, SPINEL_PROP_THREAD_LOCAL_LEADER_WEIGHT, SPINEL_PROP_THREAD_MGMT_GET_ACTIVE_DATASET, SPINEL_PROP_THREAD_MGMT_GET_PENDING_DATASET, SPINEL_PROP_THREAD_MGMT_SET_ACTIVE_DATASET, SPINEL_PROP_THREAD_MGMT_SET_PENDING_DATASET, SPINEL_PROP_THREAD_MLR_REQUEST, SPINEL_PROP_THREAD_MLR_RESPONSE, SPINEL_PROP_THREAD_MODE, SPINEL_PROP_THREAD_NEIGHBOR_TABLE, SPINEL_PROP_THREAD_NEIGHBOR_TABLE_ERROR_RATES, SPINEL_PROP_THREAD_NETWORK_DATA, SPINEL_PROP_THREAD_NETWORK_DATA_VERSION, SPINEL_PROP_THREAD_NETWORK_ID_TIMEOUT, SPINEL_PROP_THREAD_NETWORK_TIME, SPINEL_PROP_THREAD_NEW_DATASET, SPINEL_PROP_THREAD_OFF_MESH_ROUTES, SPINEL_PROP_THREAD_ON_MESH_NETS, SPINEL_PROP_THREAD_PARENT, SPINEL_PROP_THREAD_PENDING_DATASET, SPINEL_PROP_THREAD_PREFERRED_ROUTER_ID, SPINEL_PROP_THREAD_RLOC16, SPINEL_PROP_THREAD_RLOC16_DEBUG_PASSTHRU, SPINEL_PROP_THREAD_ROUTER_DOWNGRADE_THRESHOLD, SPINEL_PROP_THREAD_ROUTER_ROLE_ENABLED, SPINEL_PROP_THREAD_ROUTER_SELECTION_JITTER, SPINEL_PROP_THREAD_ROUTER_TABLE, SPINEL_PROP_THREAD_ROUTER_UPGRADE_THRESHOLD, SPINEL_PROP_THREAD_STABLE_LEADER_NETWORK_DATA, SPINEL_PROP_THREAD_STABLE_NETWORK_DATA, SPINEL_PROP_THREAD_STABLE_NETWORK_DATA_VERSION, SPINEL_PROP_THREAD_STEERING_DATA, SPINEL_PROP_THREAD_TMF_PROXY_ENABLED, SPINEL_PROP_THREAD_TMF_PROXY_STREAM, SPINEL_PROP_THREAD_UDP_FORWARD_STREAM, SPINEL_PROP_TIME_SYNC_PERIOD, SPINEL_PROP_TIME_SYNC_XTAL_THRESHOLD, SPINEL_PROP_TRNG_128, SPINEL_PROP_TRNG_32, SPINEL_PROP_TRNG_RAW_32, SPINEL_PROP_UART_BITRATE, SPINEL_PROP_UART_XON_XOFF, SPINEL_PROP_UNSOL_UPDATE_FILTER, SPINEL_PROP_UNSOL_UPDATE_LIST, SPINEL_PROP_VENDOR_ID, and spinel_to_cstr().
spinel_net_role_to_cstr()
const char* spinel_net_role_to_cstr (uint8_t net_role)
References SPINEL_NET_ROLE_CHILD, SPINEL_NET_ROLE_DETACHED, SPINEL_NET_ROLE_LEADER, SPINEL_NET_ROLE_ROUTER, and spinel_to_cstr().
spinel_mcu_power_state_to_cstr()
const char* spinel_mcu_power_state_to_cstr (uint8_t mcu_power_state)
References SPINEL_MCU_POWER_STATE_LOW_POWER, SPINEL_MCU_POWER_STATE_OFF, SPINEL_MCU_POWER_STATE_ON, and spinel_to_cstr().
spinel_status_to_cstr()
const char* spinel_status_to_cstr (spinel_status_t status)
References SPINEL_STATUS_ALREADY, SPINEL_STATUS_BUSY, SPINEL_STATUS_CCA_FAILURE, SPINEL_STATUS_CMD_TOO_BIG, SPINEL_STATUS_DROPPED, SPINEL_STATUS_EMPTY, SPINEL_STATUS_FAILURE, SPINEL_STATUS_IN_PROGRESS, SPINEL_STATUS_INTERNAL_ERROR, SPINEL_STATUS_INVALID_ARGUMENT, SPINEL_STATUS_INVALID_COMMAND, SPINEL_STATUS_INVALID_COMMAND_FOR_PROP, SPINEL_STATUS_INVALID_INTERFACE, SPINEL_STATUS_INVALID_STATE, SPINEL_STATUS_ITEM_NOT_FOUND, SPINEL_STATUS_JOIN_FAILURE, SPINEL_STATUS_JOIN_INCOMPATIBLE, SPINEL_STATUS_JOIN_NO_PEERS, SPINEL_STATUS_JOIN_RSP_TIMEOUT, SPINEL_STATUS_JOIN_SECURITY, SPINEL_STATUS_JOIN_SUCCESS, SPINEL_STATUS_NO_ACK, SPINEL_STATUS_NOMEM, SPINEL_STATUS_OK, SPINEL_STATUS_PARSE_ERROR, SPINEL_STATUS_PROP_NOT_FOUND, SPINEL_STATUS_RESET_ASSERT, SPINEL_STATUS_RESET_CRASH, SPINEL_STATUS_RESET_EXTERNAL, SPINEL_STATUS_RESET_FAULT, SPINEL_STATUS_RESET_OTHER, SPINEL_STATUS_RESET_POWER_ON, SPINEL_STATUS_RESET_SOFTWARE, SPINEL_STATUS_RESET_UNKNOWN, SPINEL_STATUS_RESET_WATCHDOG, SPINEL_STATUS_RESPONSE_TIMEOUT, SPINEL_STATUS_SECURITY_ERROR, SPINEL_STATUS_UNIMPLEMENTED, and spinel_to_cstr().
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::HandleRcpUnexpectedReset(), and RadioSpinel< InterfaceType, ProcessContextType >::HandleValueIs().
spinel_capability_to_cstr()
const char* spinel_capability_to_cstr (spinel_capability_t capability)
References main(), SPINEL_CAP_802_15_4_2003, SPINEL_CAP_802_15_4_2006, SPINEL_CAP_802_15_4_2011, SPINEL_CAP_802_15_4_2450MHZ_OQPSK, SPINEL_CAP_802_15_4_868MHZ_ASK, SPINEL_CAP_802_15_4_868MHZ_BPSK, SPINEL_CAP_802_15_4_868MHZ_OQPSK, SPINEL_CAP_802_15_4_915MHZ_ASK, SPINEL_CAP_802_15_4_915MHZ_BPSK, SPINEL_CAP_802_15_4_915MHZ_OQPSK, SPINEL_CAP_802_15_4_PIB, SPINEL_CAP_CHANNEL_MANAGER, SPINEL_CAP_CHANNEL_MONITOR, SPINEL_CAP_CHILD_SUPERVISION, SPINEL_CAP_CMD_MULTI, SPINEL_CAP_CONFIG_FTD, SPINEL_CAP_CONFIG_MTD, SPINEL_CAP_CONFIG_RADIO, SPINEL_CAP_COUNTERS, SPINEL_CAP_DUA, SPINEL_CAP_ERROR_RATE_TRACKING, SPINEL_CAP_GPIO, SPINEL_CAP_HBO, SPINEL_CAP_JAM_DETECT, SPINEL_CAP_LOCK, SPINEL_CAP_MAC_ALLOWLIST, SPINEL_CAP_MAC_RAW, SPINEL_CAP_MAC_RETRY_HISTOGRAM, SPINEL_CAP_MCU_POWER_STATE, SPINEL_CAP_MULTI_RADIO, SPINEL_CAP_NEST_LEGACY_INTERFACE, SPINEL_CAP_NEST_LEGACY_NET_WAKE, SPINEL_CAP_NEST_TRANSMIT_HOOK, SPINEL_CAP_NET_SAVE, SPINEL_CAP_NET_THREAD_1_0, SPINEL_CAP_NET_THREAD_1_1, SPINEL_CAP_NET_THREAD_1_2, SPINEL_CAP_OOB_STEERING_DATA, SPINEL_CAP_OPENTHREAD_LOG_METADATA, SPINEL_CAP_PCAP, SPINEL_CAP_PEEK_POKE, SPINEL_CAP_POSIX, SPINEL_CAP_POWER_SAVE, SPINEL_CAP_RADIO_COEX, SPINEL_CAP_RCP_API_VERSION, SPINEL_CAP_REFERENCE_DEVICE, SPINEL_CAP_ROLE_ROUTER, SPINEL_CAP_ROLE_SLEEPY, SPINEL_CAP_SLAAC, SPINEL_CAP_SRP_CLIENT, SPINEL_CAP_THREAD_BACKBONE_ROUTER, SPINEL_CAP_THREAD_BORDER_ROUTER, SPINEL_CAP_THREAD_COMMISSIONER, SPINEL_CAP_THREAD_CSL_RECEIVER, SPINEL_CAP_THREAD_JOINER, SPINEL_CAP_THREAD_SERVICE, SPINEL_CAP_THREAD_TMF_PROXY, SPINEL_CAP_THREAD_UDP_FORWARD, SPINEL_CAP_TIME_SYNC, SPINEL_CAP_TRNG, SPINEL_CAP_UNSOL_UPDATE_FILTER, SPINEL_CAP_WRITABLE_RAW_STREAM, spinel_datatype_pack(), spinel_datatype_unpack(), spinel_datatype_unpack_in_place(), spinel_to_cstr(), and spinel_validate_utf8().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale