OpenThread: Name::LabelIterator Struct Reference
Name::LabelIterator Struct Reference
Public Member Functions
Error AppendLabel (Message &aMessage) const
bool CompareLabel (const char *&aName, bool aIsSingleLabel) const
bool CompareLabel (const LabelIterator &aOtherIterator) const
Error GetNextLabel (void)
bool IsEndOffsetSet (void) const
LabelIterator (const Message &aMessage, uint16_t aLabelOffset)
Error ReadLabel (char *aLabelBuffer, uint8_t &aLabelLength, bool aAllowDotCharInLabel) const
Static Public Member Functions
static bool CaseInsensitiveMatch (uint8_t aFirst, uint8_t aSecond)
Data Fields
uint8_t mLabelLength
uint16_t mLabelStartOffset
const Message & mMessage
uint16_t mNameEndOffset
uint16_t mNextLabelOffset
Static Public Attributes
static constexpr uint16_t kUnsetNameEndOffset = 0
Constructor & Destructor Documentation
LabelIterator()
LabelIterator (const Message & aMessage, uint16_t aLabelOffset) inline
Member Function Documentation
IsEndOffsetSet()
bool IsEndOffsetSet (void) const inline
GetNextLabel()
Error GetNextLabel (void)
References ExitNow, ot::Encoding::BigEndian::HostSwap16(), ot::kErrorNotFound, ot::kErrorParse, and SuccessOrExit.
Referenced by Name::AppendTo(), Name::CompareLabel(), Name::CompareName(), Name::ParseName(), Name::ReadLabel(), and Name::ReadName().
ReadLabel()
Error ReadLabel (char * aLabelBuffer, uint8_t & aLabelLength, bool aAllowDotCharInLabel) const
References ot::kErrorNoBufs, ot::kErrorParse, ot::kNullChar, ot::StringFind(), SuccessOrExit, and VerifyOrExit.
Referenced by Name::ReadLabel(), and Name::ReadName().
CompareLabel() [1/2]
bool CompareLabel (const char *& aName, bool aIsSingleLabel) const
References ot::kNullChar, ot::StringLength(), and VerifyOrExit.
Referenced by Name::CompareLabel(), and Name::CompareName().
CompareLabel() [2/2]
bool CompareLabel (const LabelIterator & aOtherIterator) const
References Name::LabelIterator::mLabelLength, Name::LabelIterator::mLabelStartOffset, and Name::LabelIterator::mMessage.
AppendLabel()
Error AppendLabel (Message & aMessage) const
References Message::Append(), Message::AppendBytesFromMessage(), ot::kErrorInvalidArgs, SuccessOrExit, and VerifyOrExit.
Referenced by Name::AppendTo().
CaseInsensitiveMatch()
bool CaseInsensitiveMatch (uint8_t aFirst, uint8_t aSecond) static
References ot::ToLowercase().
Field Documentation
kUnsetNameEndOffset
constexpr uint16_t kUnsetNameEndOffset = 0 static
mMessage
const Message& mMessage
Referenced by Name::LabelIterator::CompareLabel().
mLabelStartOffset
uint16_t mLabelStartOffset
Referenced by Name::LabelIterator::CompareLabel().
mLabelLength
uint8_t mLabelLength
Referenced by Name::LabelIterator::CompareLabel().
mNextLabelOffset
uint16_t mNextLabelOffset
Referenced by Name::CompareLabel(), and Name::ReadLabel().
mNameEndOffset
uint16_t mNameEndOffset
Referenced by Name::CompareName(), Name::ParseName(), and Name::ReadName().
The documentation for this struct was generated from the following files:
dns_types.hpp
dns_types.cpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale