OpenThread: Timer::Scheduler::AlarmApi Struct Reference
Timer::Scheduler::AlarmApi Struct Reference
#include <timer.hpp>
Data Fields
uint32_t(* AlarmGetNow)(void)
void(* AlarmStartAt)(otInstance *aInstance, uint32_t aT0, uint32_t aDt)
void(* AlarmStop)(otInstance *aInstance)
Field Documentation
AlarmStartAt
void(* AlarmStartAt) (otInstance *aInstance, uint32_t aT0, uint32_t aDt)
Referenced by Timer::Scheduler::SetAlarm().
AlarmStop
void(* AlarmStop) (otInstance *aInstance)
Referenced by Timer::Scheduler::SetAlarm().
AlarmGetNow
uint32_t(* AlarmGetNow) (void)
Referenced by Timer::Scheduler::Add(), Timer::Scheduler::ProcessTimers(), and Timer::Scheduler::SetAlarm().
The documentation for this struct was generated from the following file:
timer.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale