OpenThread: system.hpp File Reference
system.hpp File Reference
Detailed Description
This file includes posix-specific system methods.
Functions
bool IsSystemDryRun (void)
Function Documentation
IsSystemDryRun()
bool IsSystemDryRun (void)
References gDryRun.
Referenced by otPlatSettingsDeinit(), otPlatSettingsGet(), and otPlatSettingsInit().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale