OpenThread: system.cpp File Reference
system.cpp File Reference
Detailed Description
This file includes the platform-specific initializers.
#include "openthread-posix-config.h"
#include "platform-posix.h"
#include <assert.h>
#include <inttypes.h>
#include <openthread-core-config.h>
#include <openthread/border_router.h>
#include <openthread/heap.h>
#include <openthread/tasklet.h>
#include <openthread/platform/alarm-milli.h>
#include <openthread/platform/infra_if.h>
#include <openthread/platform/otns.h>
#include <openthread/platform/radio.h>
#include "common/code_utils.hpp"
#include "common/debug.hpp"
#include "posix/platform/daemon.hpp"
#include "posix/platform/firewall.hpp"
#include "posix/platform/infra_if.hpp"
#include "posix/platform/mainloop.hpp"
#include "posix/platform/radio_url.hpp"
#include "posix/platform/udp.hpp"
Functions
static const char * get802154RadioUrl (otPlatformConfig *aPlatformConfig)
bool IsSystemDryRun (void)
void otSysDeinit (void)
otInstance * otSysInit (otPlatformConfig *aPlatformConfig)
int otSysMainloopPoll (otSysMainloopContext *aMainloop)
void otSysMainloopProcess (otInstance *aInstance, const otSysMainloopContext *aMainloop)
void otSysMainloopUpdate (otInstance *aInstance, otSysMainloopContext *aMainloop)
void platformDeinit (void)
void platformInit (otPlatformConfig *aPlatformConfig)
void platformSetUp (void)
void platformTearDown (void)
Variables
bool gDryRun = false
otInstance * gInstance = nullptr
Function Documentation
get802154RadioUrl()
static const char* get802154RadioUrl (otPlatformConfig * aPlatformConfig) static
References Url::GetProtocol(), otPlatformConfig::mRadioUrlNum, otPlatformConfig::mRadioUrls, OT_EXIT_INVALID_ARGUMENTS, and VerifyOrDie.
Referenced by platformInit().
platformInit()
void platformInit (otPlatformConfig * aPlatformConfig)
References Udp::Get(), get802154RadioUrl(), gNat64Cidr, gNetifName, Udp::Init(), otIp4Address::OT_TOOL_PACKED_FIELD::m8, otIp4Cidr::mAddress, otPlatformConfig::mBackboneInterfaceName, otPlatformConfig::mDryRun, otIp4Address::mFields, otPlatformConfig::mInterfaceName, otIp4Cidr::mLength, otPlatformConfig::mRealTimeSignal, otPlatformConfig::mSpeedUpFactor, otSysGetThreadNetifName(), platformAlarmInit(), platformBackboneInit(), platformNetifInit(), platformRadioInit(), platformRandomInit(), platformTrelInit(), and VerifyOrExit.
Referenced by otSysInit().
platformSetUp()
void platformSetUp (void)
References gDryRun, Udp::Get(), Daemon::Get(), otSetStateChangedCallback(), platformBackboneSetUp(), platformNetifSetUp(), Udp::SetUp(), Daemon::SetUp(), SuccessOrDie, and VerifyOrExit.
Referenced by otSysInit().
otSysInit()
otInstance* otSysInit (otPlatformConfig * aPlatformConfig)
This function performs all platform-specific initialization of OpenThread's drivers and initializes the OpenThread instance.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function when initialization of OpenThread's drivers is most appropriate.
Parameters
[in] aPlatformConfig Platform configuration structure.
Returns
A pointer to the OpenThread instance.
References gDryRun, gInstance, otPlatformConfig::mDryRun, OT_ASSERT, otInstanceInitSingle(), platformInit(), and platformSetUp().
Referenced by InitInstance().
platformTearDown()
void platformTearDown (void)
References gDryRun, Udp::Get(), Daemon::Get(), platformBackboneTearDown(), platformNetifTearDown(), Udp::TearDown(), Daemon::TearDown(), and VerifyOrExit.
Referenced by otSysDeinit().
platformDeinit()
void platformDeinit (void)
References Udp::Deinit(), gDryRun, Udp::Get(), platformBackboneDeinit(), platformNetifDeinit(), platformRadioDeinit(), platformTrelDeinit(), VerifyOrExit, and virtualTimeDeinit().
Referenced by otSysDeinit().
otSysDeinit()
void otSysDeinit (void)
This function finalizes the OpenThread instance and performs all platform-specific deinitialization for OpenThread's drivers.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function when deinitialization of OpenThread's drivers is most appropriate.
References OT_ASSERT, otInstanceFinalize(), platformDeinit(), and platformTearDown().
Referenced by main(), and otPlatReset().
otSysMainloopUpdate()
void otSysMainloopUpdate (otInstance * aInstance, otSysMainloopContext * aMainloop)
This function updates the file descriptor sets with file descriptors used by OpenThread drivers.
Parameters
[in] aInstance The OpenThread instance structure.
[in,out] aMainloop A pointer to the mainloop context.
References Manager::Get(), otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mTimeout, otSysMainloopContext::mWriteFdSet, otTaskletsArePending(), platformAlarmUpdateTimeout(), platformNetifUpdateFdSet(), platformRadioUpdateFdSet(), platformTrelUpdateFdSet(), Manager::Update(), and virtualTimeUpdateFdSet().
Referenced by main().
otSysMainloopPoll()
int otSysMainloopPoll (otSysMainloopContext * aMainloop)
This function polls OpenThread's mainloop.
Parameters
[in,out] aMainloop A pointer to the mainloop context.
Returns
value returned from select().
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mTimeout, otSysMainloopContext::mWriteFdSet, and virtualTimeSendSleepEvent().
Referenced by main().
otSysMainloopProcess()
void otSysMainloopProcess (otInstance * aInstance, const otSysMainloopContext * aMainloop)
This function performs all platform-specific processing for OpenThread's example applications.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function in the main loop when processing OpenThread's drivers is most appropriate.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aMainloop A pointer to the mainloop context.
References Manager::Get(), otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mWriteFdSet, platformAlarmProcess(), platformNetifProcess(), platformRadioProcess(), platformTrelProcess(), Manager::Process(), and virtualTimeProcess().
Referenced by main().
IsSystemDryRun()
bool IsSystemDryRun (void)
References gDryRun.
Referenced by otPlatSettingsDeinit(), otPlatSettingsGet(), and otPlatSettingsInit().
Variable Documentation
gInstance
otInstance* gInstance = nullptr
A pointer to the OpenThread instance.
Referenced by otSysGetThreadNetifIndex(), and otSysInit().
gDryRun
bool gDryRun = false
Referenced by IsSystemDryRun(), otSysInit(), platformDeinit(), platformSetUp(), and platformTearDown().
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale