OpenThread: Header::OT_TOOL_PACKED_FIELD Union Reference
Header::OT_TOOL_PACKED_FIELD Union Reference
Data Fields
uint16_t m16 [sizeof(uint32_t)/sizeof(uint16_t)]
uint32_t m32
uint8_t m8 [sizeof(uint32_t)/sizeof(uint8_t)]
Field Documentation
m8
uint8_t m8[sizeof(uint32_t)/sizeof(uint8_t)]
Referenced by Header::GetEcn(), Header::IsVersion6(), and Header::SetEcn().
m16
uint16_t m16[sizeof(uint32_t)/sizeof(uint16_t)]
Referenced by Header::GetDscp(), Header::GetTrafficClass(), Header::SetDscp(), and Header::SetTrafficClass().
m32
uint32_t m32
Referenced by Header::GetFlow(), Header::GetVerionTrafficClassFlow(), Header::SetFlow(), and Header::SetVerionTrafficClassFlow().
The documentation for this union was generated from the following file:
ip6_headers.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale