OpenThread: otIcmp6Header::OT_TOOL_PACKED_FIELD Union Reference
otIcmp6Header::OT_TOOL_PACKED_FIELD Union Reference
#include <icmp6.h>
Data Fields
uint16_t m16 [OT_ICMP6_HEADER_DATA_SIZE/sizeof(uint16_t)]
uint32_t m32 [OT_ICMP6_HEADER_DATA_SIZE/sizeof(uint32_t)]
uint8_t m8 [OT_ICMP6_HEADER_DATA_SIZE/sizeof(uint8_t)]
Field Documentation
m8
uint8_t m8[OT_ICMP6_HEADER_DATA_SIZE/sizeof(uint8_t)]
m16
uint16_t m16[OT_ICMP6_HEADER_DATA_SIZE/sizeof(uint16_t)]
Referenced by Icmp::Header::GetId(), Icmp::Header::GetSequence(), Icmp::Header::SetId(), and Icmp::Header::SetSequence().
m32
uint32_t m32[OT_ICMP6_HEADER_DATA_SIZE/sizeof(uint32_t)]
The documentation for this union was generated from the following file:
icmp6.h
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale