OpenThread: KeyManager::HashKeys Union Reference
KeyManager::HashKeys Union Reference
Public Member Functions
const Mac::Key & GetMacKey (void) const
const Mle::Key & GetMleKey (void) const
Data Fields
Crypto::HmacSha256::Hash mHash
Keys mKeys
Member Function Documentation
GetMleKey()
const Mle::Key& GetMleKey (void) const inline
References KeyManager::Keys::mMleKey.
Referenced by KeyManager::GetTemporaryMleKey(), and KeyManager::UpdateKeyMaterial().
GetMacKey()
const Mac::Key& GetMacKey (void) const inline
References KeyManager::Keys::mMacKey.
Referenced by KeyManager::UpdateKeyMaterial().
Field Documentation
mHash
Crypto::HmacSha256::Hash mHash
Referenced by KeyManager::ComputeKeys().
mKeys
Keys mKeys
The documentation for this union was generated from the following file:
key_manager.hpp
© Copyright 1995-2022, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale